### PR TITLE
code,pal: Removes unused headers

### LINKED ISSUE #1091: palinternal.h breaks "errno": src/pal/src/include/pal/thread.hpp:498:13: error: use of undeclared identifier 'errno'
I was [unable to compile CoreCLR on FreeBSD](https://github.com/dotnet/coreclr/issues/1044#issuecomment-107916239), due to `errno` being apparently undefined at the point where it's needed in `src/pal/src/include/thread.hpp`. ([full log](https://gist.github.com/saper/eafc21d80b753511270d)).

The problem might have been uncovered (but not caused) by f1b2b7d934339b0def5a96f111ea954974156ff8, which (re)introduced the use of system `errno` instead of using some own implementation.

The problem is that `palinternal.h` is a clever trick that does not handle some system headers fully.
It is worth to read https://github.com/dotnet/coreclr/blob/master/src/pal/src/include/pal/palinternal.h#L14-L136 before proceeding :)

What happens is this:

- `src/exception/seh.cpp` includes `<typeinfo>` and then `"pal/thread.hpp"`
- on my system `<typeinfo>` includes `<errno.h>`
- `<palinternal.h>` does its funny tricks and together with `<pal.h>` try to redefine `errno`. 
- What happens in the end is that `errno` stays undefined once the `corunix.hpp` is processed.
- Subsequent `#include <errno.h>` in the `thread.hpp` DOES NOT help, because `<errno.h>` was already included and the header guard (in my case `_SYS_ERRNO_H_`) is already defined
- This way we never get original system macro definition of `errno` back.
- This problem does not occur in the other files because at the point `palinternal.h` gets used `<errno.h>` has not yet been included by any other file.

So there needs to be a warning in the 'palinternal.h' file that explains the problem - 
using header files of the undef'd identifiers is probably a no-no.

When moving some function from category `A.2` (as described in `palinternal.h`) to category `A.1` 
it needs to be carefully checked if everything gets defined again.

Not sure where the bug is, maybe `#undef errno` and friends should go away, maybe `errno` should not be redefined in `pal.h`... etc. etc.

Anyway, my workaround was to include `<typeinfo>` *after* `"pal/thread.hpp"` in the `seh.cpp`
and the CoreCLR got compiled; but that is certainly not a solution.

This problem is not very FreeBSD specific, any use of some system header before `palinternal.h` gets included may create such problems, or worse, hidden bugs.

(mentioning https://github.com/dotnet/coreclr/issues/1010)

Thanks @josteink @jasonwilliams200OK for assisting me to get this sorted out.

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
`<typeinfo>` and `<errno.h>` were unused in `seh.cpp`.
On FreeBSD, the `errno` macro was conflicting due to these
stale inclusions. The exact cause is still unknown that how
it is building on CI and only failing locally on clean FreeBSD 10.2
installation with Clang 3.5.

Fixes #1091.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
Tested with FreeBSD 10.2 amd64 running under Windows 10 Hyper-V using this guide: https://gist.github.com/jasonwilliams200OK/06db121ec534821fe541.

**Comment by janvorli** [comment]
LGTM

File: src/pal/src/exception/seh.cpp [hunk 1]
```diff
@@ -30,18 +28,19 @@ Module Name:
 #include "pal/init.h"
 #include "pal/process.h"
 #include "pal/malloc.hpp"
+#include "signal.hpp"
 
 #if HAVE_ALLOCA_H
-#include "alloca.h"
+#  include "alloca.h"
```
Comment (janvorli) [inline src/pal/src/exception/seh.cpp]: Please don't indent these. We don't use this convention anywhere in PAL / CoreCLR

**Comment by janvorli** [comment]
LGTM modulo the nit comment.

File: src/pal/src/exception/seh.cpp (hunk 1 above)
Comment (jasonwilliams200OK) [inline src/pal/src/exception/seh.cpp]: I used it in https://github.com/dotnet/coreclr/pull/1687/files. The advantage of indented convention is it makes it easier to read. Will revert it. :)

**Comment by jasonwilliams200OK** [comment]
Fixed the nit, rebased and re-pushed.

**Comment by janvorli** [comment]
LGTM
