### PR TITLE
[RyuJIT/armel] Support putting floating-point args

### LINKED ISSUE #11928: [RyuJIT/armel] CodeGenBringUpTests Assertion failed '(allRegs(theInterval->registerType) & mask) != 0'
A sub-issue for #11822 

Some tests fail with below assert failure.

```
               Assert failure(PID 13122 [0x00003342], Thread: 13122 [0x3342]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'System.Collections.Hashtable:.ctor():this' (IL size 15)

                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 892
```

List of the tests fail with above message in `JIT/CodeGenBringUpTests`

```
FAILED   - [  23]JIT/CodeGenBringUpTests/DblAdd/DblAdd.sh
FAILED   - [  24]JIT/CodeGenBringUpTests/DblAddConst/DblAddConst.sh
FAILED   - [  26]JIT/CodeGenBringUpTests/DblArray/DblArray.sh
FAILED   - [  27]JIT/CodeGenBringUpTests/DblAvg2/DblAvg2.sh
FAILED   - [  29]JIT/CodeGenBringUpTests/DblCall1/DblCall1.sh
FAILED   - [  32]JIT/CodeGenBringUpTests/DblDiv/DblDiv.sh
FAILED   - [  33]JIT/CodeGenBringUpTests/DblDivConst/DblDivConst.sh
FAILED   - [  35]JIT/CodeGenBringUpTests/DblMul/DblMul.sh
FAILED   - [  36]JIT/CodeGenBringUpTests/DblMulConst/DblMulConst.sh
FAILED   - [  37]JIT/CodeGenBringUpTests/DblNeg/DblNeg.sh
FAILED   - [  38]JIT/CodeGenBringUpTests/DblRem/DblRem.sh
FAILED   - [  40]JIT/CodeGenBringUpTests/DblSub/DblSub.sh
FAILED   - [  41]JIT/CodeGenBringUpTests/DblSubConst/DblSubConst.sh
FAILED   - [  42]JIT/CodeGenBringUpTests/DblVar/DblVar.sh
FAILED   - [  43]JIT/CodeGenBringUpTests/DivConst/DivConst.sh
FAILED   - [  45]JIT/CodeGenBringUpTests/FPAdd/FPAdd.sh
FAILED   - [  46]JIT/CodeGenBringUpTests/FPAddConst/FPAddConst.sh
FAILED   - [  47]JIT/CodeGenBringUpTests/FPArea/FPArea.sh
FAILED   - [  48]JIT/CodeGenBringUpTests/FPArray/FPArray.sh
FAILED   - [  49]JIT/CodeGenBringUpTests/FPAvg2/FPAvg2.sh
FAILED   - [  50]JIT/CodeGenBringUpTests/FPAvg6/FPAvg6.sh
FAILED   - [  51]JIT/CodeGenBringUpTests/FPCall1/FPCall1.sh
FAILED   - [  52]JIT/CodeGenBringUpTests/FPCall2/FPCall2.sh
FAILED   - [  53]JIT/CodeGenBringUpTests/FPConvDbl2Lng/FPConvDbl2Lng.sh
FAILED   - [  54]JIT/CodeGenBringUpTests/FPConvF2F/FPConvF2F.sh
FAILED   - [  55]JIT/CodeGenBringUpTests/FPConvF2I/FPConvF2I.sh
FAILED   - [  56]JIT/CodeGenBringUpTests/FPConvF2Lng/FPConvF2Lng.sh
FAILED   - [  57]JIT/CodeGenBringUpTests/FPConvI2F/FPConvI2F.sh
FAILED   - [  58]JIT/CodeGenBringUpTests/FPDist/FPDist.sh
FAILED   - [  59]JIT/CodeGenBringUpTests/FPDiv/FPDiv.sh
FAILED   - [  60]JIT/CodeGenBringUpTests/FPDivConst/FPDivConst.sh
FAILED   - [  61]JIT/CodeGenBringUpTests/FPError/FPError.sh
FAILED   - [  62]JIT/CodeGenBringUpTests/FPFillArray/FPFillArray.sh
FAILED   - [  63]JIT/CodeGenBringUpTests/FPMath/FPMath.sh
FAILED   - [  64]JIT/CodeGenBringUpTests/FPMul/FPMul.sh
FAILED   - [  65]JIT/CodeGenBringUpTests/FPMulConst/FPMulConst.sh
FAILED   - [  66]JIT/CodeGenBringUpTests/FPNeg/FPNeg.sh
FAILED   - [  67]JIT/CodeGenBringUpTests/FPRem/FPRem.sh
FAILED   - [  68]JIT/CodeGenBringUpTests/FPRoots/FPRoots.sh
FAILED   - [  69]JIT/CodeGenBringUpTests/FPSmall/FPSmall.sh
FAILED   - [  70]JIT/CodeGenBringUpTests/FPSub/FPSub.sh
FAILED   - [  71]JIT/CodeGenBringUpTests/FPSubConst/FPSubConst.sh
FAILED   - [  72]JIT/CodeGenBringUpTests/FPVar/FPVar.sh
FAILED   - [  85]JIT/CodeGenBringUpTests/JTrueEqDbl/JTrueEqDbl.sh
FAILED   - [  86]JIT/CodeGenBringUpTests/JTrueEqFP/JTrueEqFP.sh
FAILED   - [  88]JIT/CodeGenBringUpTests/JTrueGeDbl/JTrueGeDbl.sh
FAILED   - [  89]JIT/CodeGenBringUpTests/JTrueGeFP/JTrueGeFP.sh
FAILED   - [  91]JIT/CodeGenBringUpTests/JTrueGtDbl/JTrueGtDbl.sh
FAILED   - [  92]JIT/CodeGenBringUpTests/JTrueGtFP/JTrueGtFP.sh
FAILED   - [  94]JIT/CodeGenBringUpTests/JTrueLeDbl/JTrueLeDbl.sh
FAILED   - [  95]JIT/CodeGenBringUpTests/JTrueLeFP/JTrueLeFP.sh
FAILED   - [  97]JIT/CodeGenBringUpTests/JTrueLtDbl/JTrueLtDbl.sh
FAILED   - [  98]JIT/CodeGenBringUpTests/JTrueLtFP/JTrueLtFP.sh
FAILED   - [ 100]JIT/CodeGenBringUpTests/JTrueNeDbl/JTrueNeDbl.sh
FAILED   - [ 101]JIT/CodeGenBringUpTests/JTrueNeFP/JTrueNeFP.sh
FAILED   - [ 121]JIT/CodeGenBringUpTests/ModConst/ModConst.sh
FAILED   - [ 143]JIT/CodeGenBringUpTests/UDivConst/UDivConst.sh
FAILED   - [ 144]JIT/CodeGenBringUpTests/UModConst/UModConst.sh
FAILED   - [ 150]JIT/CodeGenBringUpTests/div2/div2.sh
```

### PR DESCRIPTION
**Pull request by wateret**
- Make Lowering and LSRA be aware of armel argument push convention.
- Implement codegen for GT_COPY that was newly created from `LowerArg()`.

Fix #11928

### CODE REVIEW

**Comment by wateret** [comment]
cc: @dotnet/arm32-contrib

**Comment by wateret** [comment]
Is it possible that PUTARG_REG have two target registers? The problem with `double` is we need to generate something like `vmov.d2i r0, r1, d?` which as two destination registers.

Or it seems like we need to do something like decomposing long into field list.

File: src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -1448,10 +1448,28 @@ void CodeGen::genRegCopy(GenTree* treeNode)
...
+            assert(varTypeIsFloating(op1));
+
+            if (op1->TypeGet() == TYP_FLOAT)
+            {
+                inst_RV_RV(INS_vmov_f2i, targetReg, genConsumeReg(op1), targetType);
+            }
+            else
+            {
+                // FIXME : Is it OK to assume the second destination be the next of targetReg?
+                inst_RV_RV_RV(INS_vmov_d2i, targetReg, REG_NEXT(targetReg), genConsumeReg(op1), EA_8BYTE);
```
Comment (CarolEidt) [inline src/jit/codegenarmarch.cpp]: You can't assume that the second destination is the next of `targetReg`.
Also, I would add a comment noting that this is `TYP_DOUBLE`, just for clarity.
For future reference, this should probably be a `TODO-Arm-Bug:` comment (see https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#715-todo) (though I suspect that in this case you might want to address the issue before merging).

**Comment by hqueue** [comment]
@wateret As @CarolEidt suggested, there is `gtOtherReg` defined in `GenTreeMulLong` as below.
I also think using this struct by renaming is a good approach.  If we can use similar struct, gtRegNum and gtOtherReg can be two independent destination resister.

https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.h#L3735
```C++
#if !defined(LEGACY_BACKEND) && defined(_TARGET_ARM_)
struct GenTreeMulLong : public GenTreeOp
{
    regNumber gtOtherReg;

    GenTreeMulLong(var_types type, GenTreePtr op1, GenTreePtr op2) : GenTreeOp(GT_MUL_LONG, type, op1, op2)
    {
    }

#if DEBUGGABLE_GENTREE
    GenTreeMulLong() : GenTreeOp()
    {
    }
#endif
};
#endif
```

**Comment by wateret** [comment]
@CarolEidt @hqueue Thank you all for the comments. I'll try that way.

**Comment by wateret** [comment]
@CarolEidt Could we merge this if this is OK other than `double` handling part? I updated the PR so `double` codegen part to be NYI. And then I'll raise a separated issue for handling `double`.
It may take some time for me to handle `double` type. Also It would be good for other work like #12105 related to this PR.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -4294,7 +4301,7 @@ void LinearScan::updateRegStateForArg(LclVarDsc* argDsc)
 #ifndef _TARGET_AMD64_
                         && !compiler->info.compIsVarArgs
 #endif
-                        );
+                        && !compiler->opts.compUseSoftFP);
```
Comment (alpencolt) [inline src/jit/lsra.cpp]: I think proper to make this change in current PR.

**Comment by wateret** [comment]
@CarolEidt Resolved merge conflict.

**Comment by hqueue** [comment]
@dotnet-bot please test Ubuntu arm Cross Release Build

**Comment by CarolEidt** [comment]
> @CarolEidt Could we merge this if this is OK other than double handling part? I updated the PR so double codegen part to be NYI. And then I'll raise a separated issue for handling double.

Sounds reasonable.
