### PR TITLE
Lowering: Atomic ops can produce a value

### LINKED ISSUE #19171: Lowering: Atomic ops can produce a value
This code:
```
        if (!checkResult(Interlocked.Read(ref g_static)))
```
Results in the following assert:
```
Assertion failed 'argNode->gtRegNum == argReg' in 'NewBug:Function(long)'
```
This is because #18887 changed `OperIsStore` to include the atomic functions, but `Lowering::LowerArg()` and `Lowering::CheckCallArg()` assume that stores do not produce a value, so it doesn't correctly set the argument register (or build a `PUTARG_REG`) for the case where the result of an atomic op is passed to a call.

### PR DESCRIPTION
**Pull request by CarolEidt**
#18887 changed OperIsStore to include the atomic functions, but `Lowering::LowerArg()` and `Lowering::CheckCallArg()` assume that stores do not produce a value, so it doesn't correctly set the argument register (or build a `PUTARG_REG`) for the case where the result of an atomic op is passed to a call.
Fix this and add additional asserts.

Fix #19171

### CODE REVIEW

**Comment by CarolEidt** [comment]
@briansull @dotnet/jit-contrib PTAL

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -1288,10 +1288,14 @@ void Lowering::LowerArg(GenTreeCall* call, GenTree** ppArg)
     // Assignments/stores at this level are not really placing an argument.
     // They are setting up temporary locals that will later be placed into
     // outgoing regs or stack.
-    if (arg->OperIsStore() || arg->IsArgPlaceHolderNode() || arg->IsNothingNode() || arg->OperIsCopyBlkOp())
+    // Note that atomic ops may be stores and still produce a value.
+    if ((arg->OperIsStore() && !arg->IsValue()) || arg->IsArgPlaceHolderNode() || arg->IsNothingNode() ||
+        arg->OperIsCopyBlkOp())
```
Comment (briansull) [inline src/jit/lower.cpp]: Is there a good reason that we couldn't just check `arg->IsValue()`and return whenever it is false?

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -5297,10 +5301,13 @@ void Lowering::DoPhase()
 //
 void Lowering::CheckCallArg(GenTree* arg)
 {
-    if (arg->OperIsStore() || arg->IsArgPlaceHolderNode() || arg->IsNothingNode() || arg->OperIsCopyBlkOp())
+    if ((arg->OperIsStore() && !arg->IsValue()) || arg->IsArgPlaceHolderNode() || arg->IsNothingNode() ||
+        arg->OperIsCopyBlkOp())
```
Comment (briansull) [inline src/jit/lower.cpp]: Likewise could we just check `arg->IsValue() || arg->OperIsPutArgStk() ` here instead?
