### PR TITLE
Arm64 StoreBlk Lowering Fix

### LINKED ISSUE #7197: ARM64: New test failures
These tests fail with the latest sources, but were not failing prior to #7027. It was not fixed by PR #7188 which fixed some other failures due to that PR. This affects the following three tests (though I don't know for certain that they are caused by the same issue):
JIT\Generics\Fields\static_passing_class01\static_passing_class01.cmd
JIT\Generics\Fields\static_passing_struct01\static_passing_struct01.cmd
JIT\SIMD\Ldind_ro\Ldind_ro.cmd

### PR DESCRIPTION
**Pull request by CarolEidt**
With the block assignment changes, the Arm64 version of
Lowering::TreeNodeInfoInitBlockStore was not using the correct node
for the source address.

Fix #7197

### CODE REVIEW

File: src/jit/lowerarm64.cpp [hunk 1]
```diff
@@ -1370,7 +1370,6 @@ void Lowering::TreeNodeInfoInitBlockStore(GenTreeBlk* blkNode)
             // CopyBlk
             unsigned   size                  = blkNode->gtBlkSize;
             GenTreePtr dstAddr               = blkNode->Addr();
-            GenTreePtr srcAddr               = blkNode->Data();
```
Comment (CarolEidt) [inline src/jit/lowerarm64.cpp]: Note that there is code above this that sets `srcAddr`. This is an old (re)definition that was inadvertently left in.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
LGTM

**Comment by briansull** [comment]
LGTM
