### PR TITLE
Fix a bug with disappeared cast to byte in numeric binary expressions

### LINKED ISSUE #1323: Reboxing byte values changed since .NET 4.5
Here's my solved stack overflow thread on this issue
http://stackoverflow.com/questions/31752991/net-4-6-breaks-xor-cipher-pattern

### PR DESCRIPTION
**Pull request by AndreyAkinshin**
`Lowering::IndirsAreEquivalent` doesn't check if the 2 indirections have the same type and because of that a RMW style instruction is generated instead of the expected

```
movzx    rax, byte  ptr [7FFA61024742h]
xor      eax, 33
mov      word  ptr [7FFA61024742h], ax
```

This behaviour was fixed by adding an additional check to `IndirsAreEquivalent` (Implementation of the mikedn's approach: https://github.com/dotnet/coreclr/issues/1323#issuecomment-126868630).

Fix #1323.

### CODE REVIEW

**Comment by sharwell** [comment]
:bulb: I would prefer to see a regression test added for this.

:bulb: It seems like the commit message could be misleading, as this issue has nothing to do with boxing of value types.

**Comment by AndreyAkinshin** [comment]
@sharwell,
>  I would prefer to see a regression test added for this.

Ok, I will add it. What the best place for such test?

>  It seems like the commit message could be misleading

Agree, I will fix it.

**Comment by sharwell** [comment]
> Ok, I will add it. What the best place for such test?

I actually don't know, which is why I used :bulb: instead of :exclamation: for the suggestion.

**Comment by AndreyAkinshin** [comment]
@sharwell, see my updates.

**Comment by sharwell** [comment]
The update looks good to me. :+1: 

Keep in mind that I'm an inexperienced reviewer for this project. In particular, someone else will need to make sure the test actually gets run automatically and is correctly reported by the CI build. Someone else will also need to verify that the proposed implementation is actually the desired solution for this problem and won't cause other problems. :smile:

**Comment by akoeplinger** [comment]
Looks like the test runs fine on CI :smile: 

image

**Comment by AndreyAkinshin** [comment]
@sharwell, @akoeplinger, the other tests also successfully completed: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_prtest/1748/

**Comment by mikedn** [comment]
IMO the commit message could be improved:
* Referencing the GitHub issue number in the commit title is not very useful as such numbers are specific to GitHub and don't travel with the Git repository itself
* The commit description should actually describe the change. I'm honored that my GitHub handle is used in the commit message but that's not very useful to people who look at the Git history :smile:
* The issue is not specific to `xor`, it likely applies to all numeric binary operators.

**Comment by AndreyAkinshin** [comment]
@mikedn, Ok, I will update it.

> The issue is not specific to xor, it likely applies to all numeric binary operators.

Can you provide an example? I have tried the `and` and `or` operators but I couldn't reproduce the bug.

**Comment by mikedn** [comment]
For example:
* `x | 0x21` produces 0x2121 instead of 0x21
* `x & 0x2121` produces 0x2121 instead of 0x21
* `x + 0x21` produces 0x2142 instead of 0x42
* `x - 0x21` produces 0x2100 instead of 0
* `x >> 1` produces 0x2110 instead of 0x10

**Comment by sharwell** [comment]
> Referencing the GitHub issue number in the commit title is not very useful as such numbers are specific to GitHub and don't travel with the Git repository itself

As long as the repository/issue tracker exists here, this is extremely useful information. I don't mind adding additional information, but removing the existing reference to the issue number would cause a usability problem.

**Comment by mikedn** [comment]
@sharwell IMO if such references are to be included they should be in the commit description lines, not in the title line.

**Comment by AndreyAkinshin** [comment]
@mikedn, @sharwell,

What do you think about the following commit message:

```
Fix a bug with disappeared cast to byte in numeric binary expressions

It appears that Lowering::IndirsAreEquivalent doesn't check if the 2 indirections have the same type and because of that a RMW style instruction is generated instead of the expected

movzx    rax, byte  ptr [7FFA61024742h]
xor      eax, 33
mov      word  ptr [7FFA61024742h], ax

This behaviour was fixed by adding an additional check to IndirsAreEquivalent (Implementation of the mikedn's approach: https://github.com/dotnet/coreclr/issues/1323#issuecomment-126868630).

Fix #1323.
```

**Comment by mikedn** [comment]
> It appears that Lowering::IndirsAreEquivalent doesn't check if the 2 indirections have the same type and because of that a RMW style instruction is generated instead of the expected

You may want to drop "it appears" from this text. I kind of expect that if a commit is made the issue was properly investigated and then there's no room for "it appears".

**Comment by AndreyAkinshin** [comment]
@mikedn, ok, updated.

**Comment by cmckinsey** [comment]
@mmitche, PTAL.

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -3408,6 +3408,9 @@ bool Lowering::IndirsAreEquivalent(GenTreePtr candidate, GenTreePtr storeInd)
     if (pTreeA->OperGet() != pTreeB->OperGet())
         return false;
 
+    if (candidate->gtType != storeInd->gtType)
```
Comment (mmitche) [inline src/jit/lower.cpp]: Can we hoist this up above candidate->gtGetOp1() to avoid extra computation?

Also, I ran some extra validation and it looks like we need to be more specific with the type check.  There are no unsigned stind opcodes (though there are unsigned ldind opcodes).  This means that case like...

const byte myconst = 0x10;
byte foo = 0x0;
foo |= myconst;

...will generate an unneeded indirection because the types on either side of the binary op won't match (in signedness).  I think in this case that checking the sizes the is the right way to go:

if (genTypeSize(candidate->gtType) != genTypeSize(storeInd->gtType))

/cc @CarolEidt

File: tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs [hunk 2]
```diff
@@ -0,0 +1,22 @@
+using System;
```
Comment (mmitche) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: Can you add the MIT license header here?

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//

File: src/jit/lower.cpp (hunk 1 above)
Comment (mmitche) [inline src/jit/lower.cpp]: Also can you add a comment to this line to indicate why the test exists?

Comment (mikedn) [inline src/jit/lower.cpp]: @mmitche I had the same concern about this type check being too conservative but I wasn't able to find a repro. I don't see where in your example you have different signedness. I tried to use `ushort` and `short` in the original example but I ended up with TYP_CHAR everywhere.

Anyway, checking the type size should work in this case but there should be an assert that the involved types are integral, otherwise the function might be misused in the future and return true for indirections of type float and int.

Comment (mmitche) [inline src/jit/lower.cpp]: I saw this case when using byte and constants.  Byte as a type is signed, but the indirect store will be signed.

I think that we're guaranteed that we'll get compatible types here, but an assert would be good to add.

Comment (mikedn) [inline src/jit/lower.cpp]: I still can't reproduce the byte issue, before lowering both indirection types are ubyte:

>
```
( 11, 13) [000007] ------------             *  stmtExpr  void  (top level) (IL 0x000...0x009)
N001 (  4,  5) [000005] ----G--N----             |  /--*  &clsVar   byref  Hnd=0x8c1a5cc0 $200
N002 (  4,  5) [000001] ----G-------             |  |     /--*  &clsVar   byref  Hnd=0x8c1a5cc0 <l:$181, c:$180>
     (  4,  5) [000013] ----G-------             |  |  /--*  indir     ubyte
N003 (  1,  1) [000002] ------------             |  |  +--*  const     int    16 $42
N004 (  6,  7) [000003] ----G-------             |  +--*  |         int    <l:$183, c:$182>
N005 ( 11, 13) [000006] -A--G-------             \--*  storeIndir ubyte  <l:$183, c:$182>
```

Comment (mikedn) [inline src/jit/lower.cpp]: > I think that we're guaranteed that we'll get compatible types here, but an assert would be good to add.

Or like this:
```C++
    if (genTypeSize(candidate->gtType) != genTypeSize(storeInd->gtType) ||
        genActualType(candidate->gtType) != genActualType(storeInd->gtType))
```

File: tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs (hunk 2 above)
Comment (kangaroo) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: Is @mikedn a microsoft employee?  I thought he was external.  He should add a MIT license (c) to him.

Comment (mmitche) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: @kangaroo @mikedn You may be right there, I'm checking up on this.

Comment (mikedn) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: I'm not sure what that has to do with me, I did not create that file.

Comment (mmitche) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: Woops meant @AndreyAkinshin.  You both had such good contributions to the bug fix that I kept getting mixed up ;-)  Anyways, I'll let you know.

Comment (AndreyAkinshin) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: I'm not a Microsoft employee. So, what kind of copyright I should write?

File: src/jit/lower.cpp (hunk 1 above)
Comment (mmitche) [inline src/jit/lower.cpp]: Yeah.  I saw the diffs in a few places in framework assemblies during ngen.  I have been unable to get a reduced repro to show the same behavior unfortunately.  But the tree looked like:

               [000052] ------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
               [000049] ---XG-------             |  /--*  cast      int <- ubyte <- int
               [000047] ------------             |  |  |  /--*  const     int    64
               [000048] ---XG-------             |  |  \--*  |         int   
               [000046] *--XG-------             |  |     \--*  indir     ubyte 
               [000044] ------------             |  |        \--*  lclVar    byref  V05 tmp3         
               [000051] -A-XG-------             \--*  =         byte  
               [000050] *------N----                \--*  indir     byte  
               [000045] ------------                   \--*  lclVar    byref  V05 tmp3

File: tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs (hunk 2 above)
Comment (mmitche) [inline tests/src/JIT/Regression/JitBlue/GitHub_1323/GitHub_1323.cs]: Got the clarification:

// Copyright (c) <your name here>. All rights reserved.
 // Licensed under the MIT license. See LICENSE file in the project root for full license information.
 //

File: src/jit/lower.cpp (hunk 1 above)
Comment (mikedn) [inline src/jit/lower.cpp]: Yikes, thanks for reminding me about ngen/crossgen, I could have done the diffs myself. This happens if `ref byte` or `byte*` are used, for example somewhere in mscorlib there's the following method:

```C#
private static unsafe void WriteNibble(ref byte* ptr, byte* endPtr, uint value)
{
    Contract.Assert(0 <= value && value < 16);
    Contract.Assert(ptr < endPtr);

    if (*ptr != 0)
        *ptr++ |= (byte)value; // this generates worse code with the current fix in place
    else
        *ptr = (byte)(value << 4);
}
```
No diffs are reported in mscorlib if the check I mentioned in a post above is used instead of the original check.

Comment (mmitche) [inline src/jit/lower.cpp]: So in the no-diff case you're using the size + actual type check?

Comment (mmitche) [inline src/jit/lower.cpp]: Anyways, I like your fix, though I'd make the genActualType check an assert only.  I talked to a few others over here, and it should be impossible to get differing types like int/float at this point without an explicit cast node, based on the IR design.

Comment (mikedn) [inline src/jit/lower.cpp]: OK, I used the following:

```C++
    assert(genActualType(candidate->gtType) == genActualType(storeInd->gtType));
    
    if (genTypeSize(candidate->gtType) != genTypeSize(storeInd->gtType))
        return false;
```
and crossgened mscorlib and other corefx assemblies (not all of them due to some issues with System.Runtime version). No diffs and no asserts were generated.

**Comment by mmitche** [comment]
@AndreyAkinshin Do you have time to finish this off?

**Comment by AndreyAkinshin** [comment]
@mmitche, Yes. I can update the fix with the last mikedn's approach: https://github.com/dotnet/coreclr/pull/1329/files#r36397171
Is it ok?

**Comment by mmitche** [comment]
@AndreyAkinshin yep

**Comment by AndreyAkinshin** [comment]
@mmitche, done.

**Comment by mmitche** [comment]
LGTM.  Squash and we're good to go!

**Comment by AndreyAkinshin** [comment]
@mmitche, done.

**Comment by Eyas** [comment]
@AndreyAkinshin just a nit, but your commit message seems to be referring to a nonexistent link after squashing, since @mikedn's commend doesn't appear there. If you manage to see this before its merged, you might want to update the commit message to point to

    https://github.com/dotnet/coreclr/pull/1329#discussion_r36397171

instead.

**Comment by AndreyAkinshin** [comment]
@Eyas, thanks, fixed.

**Comment by mmitche** [comment]
@AndreyAkinshin Thanks.
