### PR TITLE
Fixing use case of incomplete Event Source payload

### LINKED ISSUE #2233: ArgumentOutOfRangeException When Tracing on Linux
When tracing on Linux, an ArgumentOutOfRangeException is thrown by the XplatEventLogger serialization code:

System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Diagnostics.Tracing.XplatEventLogger.Serialize(ReadOnlyCollection`1 payloadName, ReadOnlyCollection`1 payload, String sep)
   at System.Diagnostics.Tracing.XplatEventLogger.LogOnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Threading.Tasks.TplEtwProvider.TaskScheduled(Int32 OriginatingTaskSchedulerID, Int32 OriginatingTaskID, Int32 TaskID, Int32 CreatingTaskID, Int32 TaskCreationOptions, Int32 appDomain)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)

### PR DESCRIPTION
**Pull request by ramarag**
This resolves #2233.

EventSource allows its providers to not specify all of its arguments through the  API  [WriteEventWithRelatedActivityIdCore](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs#L1145) within mscorlib . In this case payload and payloadNames do not match in size, I am not sure this is a documented feature, but that is the current behavior. If this is a bug I would like to fix populating the eventpayload names in  [PayLoadName getter](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs#L4827) to truncate it to the correct length of Min(PayLoad.Count,m_eventSource.m_eventData[EventId].Parameters.Count)

The incomplete Payload is accepted in [WriteToAllListeners] (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs#L2127)
@brianrob @vancem @sergiy-k  PTAL

### CODE REVIEW

File: src/mscorlib/src/System/Diagnostics/Eventing/XplatEventLogger.cs [hunk 1]
```diff
@@ -78,16 +78,17 @@ private static string Serialize(ReadOnlyCollection<string> payloadName, ReadOnly
...
+               eventDataCount = Math.Min(payloadName.Count, payload.Count);
             }
             
             var sb = StringBuilderCache.Acquire();
 
             sb.Append('{');
-            for (int i = 0; i < payloadName.Count; i++)
+            for (int i = 0; i < eventDataCount; i++)
             {
                 var fieldstr = payloadName[i].ToString();
```
Comment (brianrob) [inline src/mscorlib/src/System/Diagnostics/Eventing/XplatEventLogger.cs]: If you have a partial payload does the partial payload always start with the first arg and end at N-K, K being some intermediate payload field?  If it is possible to pick and choose which payload fields to specify, then it looks like this fix won't work, as the payload names are matched to payload fields by index into the array.

**Comment by vancem** [comment]
Rama Above you say:

 * EventSource allows its providers to not specify all of its arguments through the API WriteEventWithRelatedActivityIdCore within mscorlib .

Can be more specific?    It really sounds like you are describing an error condition, and while a certain amount of robustness to errors is good, I also want to insure that the root error also gets fixed

@davmason

**Comment by ramarag** [comment]
An example of the usage is present in mscorlib:  [Taskscheduled](https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs#L415)

As Brian pointed out, I believe the provider can leave out as many trailing arguments as it wants

**Comment by vancem** [comment]
I am OK with this code being robust with respect to mismatching, however it is an error, and we should fix the code site that generated the event to emit the correct number of arguments (it is in the same repro, right? so lets just fix it).

**Comment by ramarag** [comment]
done PTAL

**Comment by vancem** [comment]
LGTM

**Comment by brianrob** [comment]
LGTM

**Comment by ramarag** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

File: src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs [hunk 2]
```diff
@@ -434,13 +434,15 @@ public class Keywords // thisname is important for EventSource
                     eventPayload[3].DataPointer = ((IntPtr) (&CreatingTaskID));
                     eventPayload[4].Size = sizeof(int);
                     eventPayload[4].DataPointer = ((IntPtr) (&TaskCreationOptions));
+                    eventPayload[5].Size = sizeof(int);
+                    eventPayload[5].DataPointer = ((IntPtr) (&appDomain));
                     if (TasksSetActivityIds)
                     {
                         Guid childActivityId = CreateGuidForTaskID(TaskID);
                         WriteEventWithRelatedActivityIdCore(TASKSCHEDULED_ID, &childActivityId, 5, eventPayload);
```
Comment (sergiy-k) [inline src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs]: Should this line also be fixed? i.e. 5=>6

Comment (ramarag) [inline src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs]: Oops you are correct

**Comment by ramarag** [comment]
@dotnet-bot test   OSX x64 Release Build and Test

**Comment by ramarag** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by ramarag** [comment]
@dotnet-bot test OSX x64 Release Build and Test

**Comment by ramarag** [comment]
@dotnet-bot test OSX x64 Release Build and Test
