### PR TITLE
Optimize bounds checks with correct assertion set

### LINKED ISSUE #6318: JIT: assertion prop inferring too much in bounds-check commas
When assertion prop processes a bounds check that is the LHS of a comma, it does so in a context where it has already incorporated any assertions generated in the RHS of the comma.  Typically the RHS just retrieves a value and this isn't an issue, but the SIMD intrinsics generate commas with more complex right-hand-sides, so e.g. this snippet fails (with optimizations enabled) with the wrong exception type thrown for the out-of-bounds access:

```
    public static class C
    {
        public static int Main(string[] args)
        {
            try
            {
                Foo(System.Numerics.Vector<int>.Zero);
            }
            catch (System.ArgumentOutOfRangeException)
            {
                // Caught the right exception
                return 100;
            }
            catch
            {
                // Caught the wrong exception
                return -1;
            }
            // Caught no exception
            return -2;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static int Foo(System.Numerics.Vector<int> vec)
        {
            int[] a = new int[5];
            vec.CopyTo(a, 5);
            return a[0];
        }
    }
```

This is blocking #6285 since that exposes the issue in existing SIMD tests.

I am working on a fix.

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Assertion prop defers removing redundant bounds checks until processing
the parent comma, because the rewrite involves the comma as well.  The
code currently has a bug in that its checks for whether the bounds check
is redundant also occurs when processing reaches the comma, which is wrong
because the assertion set may then include assertions generated by the RHS
of the comma (there is code to compensate for the assertion generated by
the bounds check itself, which is the LHS of the comma, but no compensation
for the RHS).

This change moves the analysis of whether bounds checks are redundant to
the proper spot in the processing order, and delays only the rewrite to
the processing of the comma; the redundancy of the bounds check is
communicated by updating its throw kind flag to None.

The 'throw kind == None' range checks can sometimes persist to lowering,
because upstream optimization may have moved/removed the check's parent
comma (e.g. this happens in one of the JIT Methodical IL tests, where the
RHS of the comma is a NOP that gets removed).  This change updates the
lowering to handle such checks, inserting a failfast on the failure path,
though of course it will be preferable in the future to
revisit/codify/enforce our canonical form for range checks (as LHS of
commas), and/or to update our optimizations to either handle removing
range checks that aren't children of commas or maintain the parent node
context when optimizing them.

Fixes #6318.

@dotnet/jit-contrib PTAL.  Diffs are minimal; nothing in frameworks assemblies, and SuperPMI just turns up three tests where a couple bounds-checks are left in due to the bugfix (i.e. removing them was unsound) and a couple bounds-checks are proven in-bounds but not in the canonical comma form and so an extra (unreachable) call to failfast gets emitted.

### CODE REVIEW

**Comment by CarolEidt** [comment]
Could you explain why the bounds check can't be replace with a nop instead of setting it to SCK_NONE?

**Comment by JosephTremoulet** [comment]
> Could you explain why the bounds check can't be replace with a nop instead of setting it to SCK_NONE?

I'm inferring that from the fact that `optRemoveRangeCheck` is written to take the parent comma and someone went out of their way to do this optimization at the comma node rather than the range check node.  Reading the implementation of `optRemoveRangeCheck`, I believe the issue is that the range check might have side-effects which need to be preserved, which means we need to rewrite the comma in that case (or maybe we could bash the range check to a comma and put the side-effects on one side and a NOP on the other side, or etc., but I'd think such a change should be applied to `optRemoveRangeCheck` generally).

**Comment by CarolEidt** [comment]
Ah, makes sense; one might be tempted to open an issue to make that general change to `optRemoveRangeCheck`, but based on your results it would seem that it would have little enough impact to make it not necessarily worth the trouble.
Looks good to me.

**Comment by JosephTremoulet** [comment]
@dotnet-bot:
 - test Linux ARM Emulator Cross Debug Build
 - test Windows_NT x64 Release Priority 1 Build and Test
 - test Windows_NT x86 legacy_backend Checked Build and Test
 - test Windows_NT x86 ryujit Checked Build and Test

File: src/jit/flowgraph.cpp [hunk 1]
```diff
@@ -17495,6 +17499,12 @@ BasicBlock*         Compiler::fgAddCodeRef(BasicBlock*      srcBlk,
                             break;
 #endif // COR_JIT_EE_VERSION
 
+    // SCK_NONE can appear on range checks that optimization proved will succeed
+    // but which it failed to remove for mechanical reasons; use failfast for
+    // these cases.
+    case SCK_NONE:          helper = CORINFO_HELP_FAIL_FAST;
```
Comment (briansull) [inline src/jit/flowgraph.cpp]: Calling Fail Fast here seems like an unnecessarily dangerous default.
This is OK for checked build, but having a customer report that their app hits a fail fast termination for this would be unfortunate.

Comment (JosephTremoulet) [inline src/jit/flowgraph.cpp]: What would you prefer?  The check has been proven in-bounds, this is unreachable code being emitted.

Comment (briansull) [inline src/jit/flowgraph.cpp]: OK I see now,  This is for the basic block that gets added.
This block would have previously unconditionally have thrown Range Check
With your change this block will call Fail Fast.

SInce the range checks were removed control flow won't reach this block.

And if it does reach this block calling Fail Fast isn't going to be  worse than any alternative.

**Comment by briansull** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
Looks like the "failure to restore a package" is hitting #6522 as well, I'm inclined to believe it's unrelated to this change.  @mmitche, @swaroop-sridhar, thoughts?

**Comment by mikedn** [comment]
The "failure to restore package" appears to be a failed test actually:
```
Assert failure(PID 1048 [0x00000418], Thread: 2500 [0x09c4]): Assertion failed 'tgtBlk == compiler->fgFindExcptnTarget(codeKind, compiler->bbThrowIndex(compiler->compCurBB))->acdDstBlk' in 'ILGEN_0x1d013582:Method_0x7ef63454():long' (IL size 2316)

```

**Comment by JosephTremoulet** [comment]
Oops!  Thanks, @mikedn, investigating...

**Comment by briansull** [comment]
According to Compiler::optAssertionProp_Comma()
the reason it waits until the comma node is:

 // Process the bounds check as part of the GT_COMMA node since, we need parent pointer to remove nodes.

**Comment by briansull** [comment]
I think that a better approach would be to mark the 
GT_ARR_BOUNDS_CHECK node with a new node specific flag:

 #define GTF_ARRBNDCHK_REDUNDANT    0x80000000  // This check was proven to be redundant.

Add a new case in optAssertionProp to call 

    case GT_ARR_BOUNDS_CHECK:
        return optAssertionProp_BndsChk(assertions, tree, stmt);

Change that method to only accept a GT_ARR_BOUNDS_CHECK (instead of a GT_COMMA) node
 and have it set this flag based upon the current set of assertions: 

gtFlags |= GTF_ARRBNDCHK_REDUNDANT

Also remove the last part of this method where it calls:  optRemoveRangeCheck and optAssertionProp_Update()  (I also think that the "if (newTree !=  nullptr) can be eliminated as well, but you'll need to investigate that further)

Then change the comma visitor function optAssertionProp_Comma
to check for a op1 that is a GT_ARR_BOUNDS_CHEK node with that flag set and then call  optRemoveRangeCheck() to remove and rewrite the GT_COMMA node. and just call optAssertionProp_Update().

**Comment by JosephTremoulet** [comment]
@briansull, unless I'm misreading something, the changes I've made to assertion prop are exactly as you describe except that I was communicating the redundancy in the throw kind rather than a new flag bit.  So then what you're saying is that it's better to add a new bit to the flag and have the dynamically unreachable code we emit call whichever throw helper it would have needed to call were it reachable, than to be stingy with the bit and call fail_fast from the (possibly newly-created) dynamically unreachable throw block.  Am I understanding the feedback correctly?  Sure, I can make that change if so.

**Comment by briansull** [comment]
Using a flag on  the GT_ARR_BOUNDS_CHECK node sem like a  clear easier to understand way of implementing this.

IMO modifying the  fgAddCodeRef stuff in the way that you proposed make a confusing area even more confusing.

BBJ_THROW, // SCK_NONE (vestigial range check; see below)

**Comment by JosephTremoulet** [comment]
Updated to use a new GT flag and drop the changes to `fgAddCodeRef` etc.  I called the flag `GTF_ARR_BOUND_INBND`, thinking that having proved the index is always in-bounds is more salient than it being redundant to a prior check and that this leaves the door open for proved out-of-bounds cases should we need those at some point.

@briansull PTAL.

**Comment by briansull** [comment]
LGTM
That looks a whole lot better now.

**Comment by JosephTremoulet** [comment]
@dotnet-bot,
 - test OS X x64 Checked Build and Test
 - test Ubuntu x64 Checked Build and Test
 - test Windows_NT x86 ryujit Checked Build and Test

**Comment by JosephTremoulet** [comment]
@dotnet-bot, I meant to say "test OSX x64 Checked Build and Test"

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test (looks like the last run hit #6553)
