### PR TITLE
Always try to load user32 instead of ntuser api set  

### LINKED ISSUE #4156: JIT asserts don't display message box
On Windows desktop CLR, when you hit a JIT assert, you get a pop-up message box. When you hit "Retry" on this, and you are running under a debugger, the debugger stops at the assert.

On Windows CoreCLR, this is not working.

This is because the CLR fails in LateboundMessageBoxW():

```
#if defined(FEATURE_CORESYSTEM) && !defined(CROSSGEN_COMPILE)
    // Some CoreSystem OSs will support MessageBoxW via an extension library. The following technique is what
    // was recommeded by Philippe Joubert from the CoreSystem team.
    HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1"), NULL, 0);
#else
```

namely, it fails to load this library.

The call stack is:

```
>	coreclr.dll!LateboundMessageBoxW(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpCaption, unsigned int uType) Line 1002	C++
 	coreclr.dll!MessageBoxImpl(HWND__ * hWnd, const wchar_t * message, const wchar_t * title, const wchar_t * detailedText, unsigned int uType) Line 113	C++
 	coreclr.dll!UtilMessageBoxNonLocalizedVA(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpTitle, const wchar_t * lpDetails, unsigned int uType, int displayForNonInteractive, int showFileNameInTitle, int * pInputFromUser, char * args) Line 435	C++
 	coreclr.dll!UtilMessageBoxNonLocalizedVA(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int displayForNonInteractive, int showFileNameInTitle, int * pInputFromUser, char * args) Line 322	C++
 	coreclr.dll!UtilMessageBoxCatastrophicNonLocalizedVA(const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int showFileNameInTitle, char * args) Line 598	C++
 	coreclr.dll!UtilMessageBoxCatastrophicNonLocalized(const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int showFileNameInTitle, ...) Line 539	C++
 	coreclr.dll!_DbgBreakCheck(const char * szFile, int iLine, const char * szExpr, int fConstrained) Line 471	C++
 	coreclr.dll!CEEInfo::doAssert(const char * szFile, int iLine, const char * szExpr) Line 9989	C++
```

The function then returns zero, which propagates back to _DbgBreakCheck(), which calls TerminateProcess().

(Apparently we used to always tell the caller to break, but that is #if 0'ed for some reason:
```
    case 0:
#if 0
        // The message box was not displayed. Tell caller to break.
        return true;
#endif
```
)

This hampers JIT team productivity because:
1. it prevents using a just-in-time debugger,
2. it requires always setting a breakpoint on clrjit.dll!assertAbort() or similar, instead of using the existing message box mechanism.

### PR DESCRIPTION
**Pull request by mikedn**
Fixes #4156

### CODE REVIEW

File: src/inc/winwrap.h [hunk 1]
```diff
@@ -981,7 +981,11 @@ inline int LateboundMessageBoxW(HWND hWnd,
 #if defined(FEATURE_CORESYSTEM) && !defined(CROSSGEN_COMPILE)
     // Some CoreSystem OSs will support MessageBoxW via an extension library. The following technique is what
     // was recommeded by Philippe Joubert from the CoreSystem team.
-    HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1"), NULL, 0);
+    HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1-1-0"), NULL, 0);
```
Comment (jkotas) [inline src/inc/winwrap.h]: I think we should get rid of the internal Windows API set loading. Just load the user32 (basically remove the ifdef and update the comment).

Comment (mikedn) [inline src/inc/winwrap.h]: OK, I'll do that. I was thinking that since someone went to the trouble of asking someone else in another team on how to deal with this it's not nice to just remove everything :)

Comment (jkotas) [inline src/inc/winwrap.h]: It was a long time ago and things have changed since then...

**Comment by jkotas** [comment]
Thanks!
