### PR TITLE
Fix spill check for struct lclVars

### LINKED ISSUE #23545: Test failure: JIT_Methodical._flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_/_flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_cmd
Opened on behalf of @AriNuer

The test `JIT_Methodical._flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_/_flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_cmd` has failed.

Failure Message:
```

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.\r
   at ILGEN_0xd01d9fe9.Method_0x594ff2c5(Int16 Arg_0x0, Byte Arg_0x1, UInt16 Arg_0x2, Int64 Arg_0x3, IntPtr Arg_0x4, SByte Arg_0x5, Byte Arg_0x6, UInt16 Arg_0x7, UInt32 Arg_0x8, Int32 Arg_0x9, Int32 Arg_0xa, Byte Arg_0xb, IntPtr Arg_0xc, SByte Arg_0xd)\r
   at ILGEN_0xd01d9fe9.Main()


Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\306a361e-556b-4ccb-9f78-ea5dbce902c2\\Work\\f286b2da-a2ee-4350-a306-96ac67aa4779\\Exec\\Reports\\JIT.Methodical\\flowgraph\\dev10_bug679955\\volatileLocal1\\volatileLocal1.output.txt
Raw output:
BEGIN EXECUTION\r
 \"C:\\dotnetbuild\\work\\306a361e-556b-4ccb-9f78-ea5dbce902c2\\Payload\\corerun.exe\" volatileLocal1.exe \r
Expected: 100\r
Actual: -532462766\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r

To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\306a361e-556b-4ccb-9f78-ea5dbce902c2\\Payload
> C:\\dotnetbuild\\work\\306a361e-556b-4ccb-9f78-ea5dbce902c2\\Work\\f286b2da-a2ee-4350-a306-96ac67aa4779\\Exec\\flowgraph\\dev10_bug679955\\volatileLocal1\\volatileLocal1.cmd
\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at JIT_Methodical._flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_._flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.arm64.Release\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs:line 80329
```

Build : 3.0 - 20190328.73 (Core Tests)
Failing configurations:
- Windows.10.Arm64-arm64
  - 
  - 
- Windows.10.Arm64-arm
  - 
  - 
- Windows.81.Amd64-x86
  - 
  - 
- Windows.7.Amd64-x86
  - 
  - 
- Windows.10.Amd64.Core-x86
  - 
  - 
- Windows.10.Amd64-x86
  - 
  - 
- Windows.81.Amd64-x64
  - 
  - 
- Windows.7.Amd64-x64
  - 
  - 
- Windows.10.Amd64.Core-x64
  - 
  - 
- Windows.10.Nano.Amd64-x64
  - 
  - 
- Windows.10.Amd64-x64
  - 
  - 

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190328.73/workItem/JIT.Methodical/analysis/xunit/JIT_Methodical._flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_~2F_flowgraph_dev10_bug679955_volatileLocal1_volatileLocal1_cmd

### PR DESCRIPTION
**Pull request by CarolEidt**
With the 1st class struct changes, the `SPILL_APPEND` check for the case of an assignment to a lclVar needs to handle block ops as well as lclVar lhs.

Fix #23545

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
I ran PMI diffs on x64, and there are zero diffs. I'm running x86 diffs now.

**Comment by CarolEidt** [comment]
Zero x86 diffs as well

**Comment by CarolEidt** [comment]
@dotnet/dnceng - I'm getting "download failure" errors on the "Test pri0 Linux arm64 checked" leg, on several retries (e.g. 88d45f1d-2938-4d52-b7ac-a2f18683e194). And along with the failure, the "Publish logs" job gives "Artifact testbuild_Linux_arm64_checked_innerloop_Logs already exists for build 139295."

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping - I'd really like to get Linux arm64 testing on this, but so far I have no reason to believe it will fail. Can I get a review of this?

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -10624,11 +10624,22 @@ void Compiler::impImportBlockCode(BasicBlock* block)
...
-                    impSpillLclRefs(op1->gtOp.gtOp1->AsLclVarCommon()->gtLclNum);
+                    GenTree*             lhs    = op1->gtGetOp1();
+                    GenTreeLclVarCommon* lclVar = nullptr;
+                    if (lhs->gtOper == GT_LCL_VAR)
+                    {
+                        lclVar = lhs->AsLclVarCommon();
+                    }
+                    else if (lhs->OperIsBlk())
+                    {
+                        lclVar = lhs->AsBlk()->Addr()->IsLocalAddrExpr();
```
Comment (mikedn) [inline src/jit/importer.cpp]: Is `IsLocalAddrExpr` really the right function to use here? There are a few that attempt to detect local addresses and they differ in the trees that they recognize. This one recognizes something like `ADD(ADDR(LCL_VAR, 2)` but that's less common during import. There's also `impIsAddressInLocal` that does something similar but instead of `ADD` nodes it looks for `FIELD` nodes, which of course are more common during import.

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -10624,11 +10624,22 @@ void Compiler::impImportBlockCode(BasicBlock* block)
             SPILL_APPEND:
 
                 // We need to call impSpillLclRefs() for a struct type lclVar.
-                // This is done for non-block assignments in the handling of stloc.
-                if ((op1->OperGet() == GT_ASG) && varTypeIsStruct(op1->gtOp.gtOp1) &&
-                    (op1->gtOp.gtOp1->gtOper == GT_LCL_VAR))
+                if ((op1->OperGet() == GT_ASG) && varTypeIsStruct(op1->gtGetOp1()))
```
Comment (AndyAyersMS) [inline src/jit/importer.cpp]: Would be nice to also describe why we need to spill in the first place.

File: src/jit/importer.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: Yes, I think you're right. `IsLocalAddrExpr()` would be the right thing to call after morph, but at this point we might see a `FIELD`. I'm going to try to get a repro case for that.

File: src/jit/importer.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: OK, will do.

File: src/jit/importer.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: Having spent some time on this, I'm fairly certain that this only needs to handle full assignments. The `FIELD` case is handled here: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L14507, and explicit `stloc` cases here: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L11103
.In the failure case the "assignment" is an `initobj`. The block cases handle this with a `goto SPILL_APPEND` which lands here. Pretty much anything else that would modify a local would involve explicitly taking its address (not just in the context of doing a field store).

I gave some thought to whether an assert could be added, but I was unable to do so. So, I'm actually going to simplify this check.

**Comment by CarolEidt** [comment]
I added a comment to the offending PR (https://github.com/dotnet/coreclr/pull/22255/files#diff-edc46b80f57431489a82311948a8234d) that shows where this case was previously being handled.

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests

**Comment by CarolEidt** [comment]
@dotnet/dnceng - another isntance of the "Test pri0 Linux arm checked" leg being cancelled.

**Comment by CarolEidt** [comment]
I can't figure out how to retry that leg. I'm going to merge this without that leg.
