### PR TITLE
Inliner: avoid inlining callees with GC structs on cold paths

### LINKED ISSUE #7569: String::Format Memory Optimization Degrades Performance under RuyJIT 64
The `String::Format` methods have been updated some time ago to eliminate excessive array object allocations and reduce memory traffic.

Was:
```C#
public static String Format(String format, Object arg0) {
    return Format(null, format, new Object[] {arg0}); }
```

Now:
```C#
public static string Format(string format, object arg0) {
    return string.FormatHelper((IFormatProvider) null, format, new ParamsArray(arg0)); }
```

Unfortunately, with RyuJIT x64 this makes simple functions execute up to 10 (ten!) times slower than before in code paths which *do not call* `String::Format`.

Here is a code sample.

```C#
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int FastFunctionNotCallingStringFormat(int param)
    {
      if(param < 0)
        throw new Exception(string.Format("We do not like the value {0:N0}.", param));
      if(param == int.MaxValue)
        throw new Exception(string.Format("{0:N0} is maxed out.", param));
      if(param > int.MaxValue / 2)
        throw new Exception(string.Format("We do not like the value {0:N0} either.", param));
      return param * 2;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int FastFunctionNotHavingStringFormat(int param)
    {
      if(param < 0)
        throw new ArgumentOutOfRangeException("param", "We do not like this value.");
      if(param == int.MaxValue)
        throw new ArgumentOutOfRangeException("param", "Maxed out.");
      if(param > int.MaxValue / 2)
        throw new ArgumentOutOfRangeException("param", "We do not like this value either.");
      return param * 2;
    }

    private static int Main()
    {
      int sum = 0;
      for(int a = int.MaxValue / 2; a --> 0;)
      {
        sum = unchecked(sum + FastFunctionNotHavingStringFormat(a));
        sum = unchecked(sum + FastFunctionNotCallingStringFormat(a));
      }
      Console.WriteLine(sum);
      return 0;
    }
```

> A real-life example of this mock-up would be a collection object which has range checks with diagnostics in its `get_Item` indexer. That's how we've hit it: a simple enough indexer suddenly showed up as the hottest function in the profile.

Notice that `String::Format` is *never* called within the course of execution. Supposedly, these two functions should run at the same speed.

Now that's what it looks like in the profiler:

image

None of these functions calls formatting, but the one which merely has it on unused code paths takes tenfold (well, almost) time to execute.

If we go even deeper, the code which takes up the extra time is:
```asm
lea rdi, ptr [rsp+0x28]
mov ecx, 0x20
xor eax, eax
rep stosd dword ptr [rdi]
```
It is located in the function head, before any user code.
That's like doing `ZeroMemory` on the stack frame, and quite an amount of that.

From this I can guess that:
* JIT has inlined the `String::Format` function into the `FastFunctionNotCallingStringFormat` body.
* `System.ParamsArray` now lives on the stack frame of `FastFunctionNotCallingStringFormat`.
* Even though the scopes of the three `System.ParamsArray` copies do not intersect, each seems to be getting its own space in the stack frame. The amount is `0x20 * sizeof(DWORD)`, or `128` bytes, which is enough for entire `4 * sizeof(ParamsArray)`.
* Even though these `System.ParamsArray`s are never used or created in the actually executed code, `ZeroMemory` for them has been pulled up to the head of the function, and it affects any call to this function.

So string-formats which are only sitting there but are never called do suddenly have a cost.

> UPD: Mostly the same happens in 32-bit runtimes, even the relative speeds are the same, even though both lower somewhat.

I hope for the following improvements:
* Costly `ZeroMemory` could be moved closer to the usage; the JITter might even know when it is safe to omit it altogether, but the point is to avoid this until (and unless) the structure is put to use. 
* Memory could be reused for structures whose lifetimes never intersect (and even are of the same type).

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If an inline introduces a local or temp GC struct, the initialization
of that struct is done in the root method prolog. This can hurt
performance if the inline call site is cold. Detect this during
importation and update the inline policy to back out of the inline if
the inline is an always or discretionary candidate.

Jit diffs shows size wins in the core library with no regressions.
```
Total bytes of diff: -8789 (-0.29 % of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file improvements by size (bytes):
       -8789 : System.Private.CoreLib.dasm (-0.29 % of base)
1 total files with size differences.
Top method improvements by size (bytes):
        -320 : System.Private.CoreLib.dasm - FrameSecurityDescriptor:CheckDemand2(ref,ref,long,bool):bool:this
        -224 : System.Private.CoreLib.dasm - RuntimeConstructorInfo:CheckCanCreateInstance(ref,bool)
        -214 : System.Private.CoreLib.dasm - RuntimeType:GetMethodBase(ref,long):ref
        -150 : System.Private.CoreLib.dasm - CultureInfo:GetCultureInfoByIetfLanguageTag(ref):ref
        -146 : System.Private.CoreLib.dasm - GC:RegisterForFullGCNotification(int,int)
103 total methods with size differences.
```
Desktop testing shows similar wins in a number of places and only
a few sparse small regressions.

Added a perf test. Thanks to @hypersw for noticing this.

Closes #7569.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

**Comment by mikedn** [comment]
I suppose this doesn't work with "no return" calls? By the time a "no return" call is encountered and the block marked as cold other calls in the same block have already been inlined. Not that it would matter too much, if someone uses throw helpers then they probably won't have a bunch of calls before the throw helper call.

File: tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+{
+
+#if DEBUG
+    public const int Iterations = 1;
+#else
+    public const int Iterations = 2500000;
+#endif
+
+[MethodImpl(MethodImplOptions.NoInlining)]
+public static int FastFunctionNotCallingStringFormat(int param)
```
Comment (briansull) [inline tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs]: It would be nice to have a comment that explains what the expected behavior is for this new test case.
I assume that you don't want the String.Format calls to be inlined here.
If someone have to investigate this as a failure, (like if we ran this test with JIT64 or JIT32) it would be good 
have an explanation about what we want to happen.
You also might want to reference this PR https://github.com/dotnet/coreclr/pull/7727 as well in the comment.

**Comment by benaadams** [comment]
@AndyAyersMS tangential; but related; in the inverse)... 

Is it possible (or would it make sense) to add a multiplier to struct .ctors for inlining? If they have lots of argument validation with throws it can easily push them into being non inlinable.

Example/fixed in https://github.com/aspnet/Common/pull/159; though I has to go all the way to AggressiveInline to push it consistently over the edge as it was too variable depending on the caller code (which does make sense).

File: tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+{
```
Comment (briansull) [inline tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs]: Could you add a comment that explain what the purpose of the test is and that we expect that the method System.Format is not inlined here.  WE may run this test case using JIT32 or JIT64 and if it fails its nice to have a comment explaining what is expected behavior.

You could also reference this PR is the comment as well https://github.com/dotnet/coreclr/pull/7727

Comment (briansull) [inline tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs]: Could you add a comment that explain what the purpose of the test is and that we expect that the method System.Format is not inlined here.  WE may run this test case using JIT32 or JIT64 and if it fails its nice to have a comment explaining what is expected behavior.

You could also reference this PR is the comment as well https://github.com/dotnet/coreclr/pull/7727

**Comment by AndyAyersMS** [comment]
For the most part the jit's inline decision making is order independent, but the noreturn case is one where we might benefit from considering ordering candidates.

For instance we could inline from back to front, instead of front to back like we do now, since most IL producers will create sequential flow in increasing IL offset order.

**Comment by AndyAyersMS** [comment]
@benaadams I would hope the new inlining heuristics (in the works) would be better at spotting cases like the one you note, since they have machine-learning derived predictive models for code size impact.

There's a preliminary version of these heuristics checked in. You can use COMPlus_JitInlinePolicyModel=1 to enable. The code size estimates seem reasonably good -- though not perfect. If they miss cases like this I can add some more examples to the training set.

**Comment by briansull** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
Suspect this got orphaned by the CI reboot.

@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Windows_NT x64 Formatting

**Comment by AndyAyersMS** [comment]
Not sure what went wrong but the legacy x86 build & test leg went south building tests. [Link here](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_lb_checked_windows_nt_prtest/1063/)

@dotnet-bot retest Windows_NT x86 legacy_backend Checked Build and Test

File: tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs (hunk 1 above)
Comment (AndyAyersMS) [inline tests/src/JIT/Performance/CodeQuality/Inlining/InlineGCStruct.cs]: Ok, added a link from test case to issue.

**Comment by AndyAyersMS** [comment]
OSX [failed during git clone](https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx_flow_prtest/1132/), likely a known issue. Retrying.

@dotnet-bot retest OSX x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
[Arm Emulator timeout](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_debug_ubuntu_prtest/1160/). Yet another thing to retry....

@dotnet-bot retest Linux ARM Emulator Cross Debug Build

**Comment by AndyAyersMS** [comment]
@hypersw I think the change in policy is doing basically what you suggest. Inline candidates are classified into one of three categories:

* always inlines (small methods)
* forced inlines (methods with the aggressive inline attribute)
* discretionary inlines (not forced or always and the jit believes the inline is profitable)

This change will back out of inlining (for rare calls that introduce GC structs) for the always and discretionary categories, but will still go and inline cases that in the forced category.
