### PR TITLE
Respect STA/MTAThread attributes

### LINKED ISSUE #13688: STAThread attribute is not respected in netcoreapp
Create a new `netcoreapp2.0` project and set the `Program.cs` file to:
```csharp
using System;
using System.Threading;

namespace ConsoleApp4
{
    class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            Console.WriteLine(Thread.CurrentThread.GetApartmentState());
            Console.ReadLine();
        }
    }
}
```

Examine that the output from the application is:
```
MTA
```

Not respecting `STAThread` means that users who depend on it (even if it really only matters on Windows), have to manually spawn a thread to run their code.

In some cases, certain libraries actually check and enforce that the calling thread is STA, and will throw an exception if it is not.

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #13688 
Tests PR - https://github.com/dotnet/corefx/pull/25934

### CODE REVIEW

**Comment by jkotas** [comment]
2000+ tests failing in CI on Windows

**Comment by jkotas** [comment]
Also, we should have tests to exercise the newly added code

File: src/vm/interoputil.cpp [hunk 1]
```diff
@@ -2335,14 +2335,10 @@ VOID EnsureComStarted(BOOL fCoInitCurrentThread)
 
     if (g_fComStarted == FALSE)
     {
-        FinalizerThread::GetFinalizerThread()->SetRequiresCoInitialize();
```
Comment (jkotas) [inline src/vm/interoputil.cpp]: Why did you remove this?

**Comment by Anipik** [comment]
Tests for this new code will be added to corefx

**Comment by jkotas** [comment]
This is runtime/interop feature. I think CoreCLR would be more appropriate repo for it. 

But if you prefer to add them to CoreFX, I am ok with it - but I would like to review them together with the code change.

**Comment by jkotas** [comment]
cc interop owners @shrah @luqunl

**Comment by jkotas** [comment]
@fiigii Take a look at the OSX failure in Intrinsic tests. It is unrelated to the changes in this PR:

```
Thread: 57175 [0xdf57]): Assertion failed 'dataSrc->OperIsIndir()' in 'System.Runtime.Intrinsics.X86.Avx:Add(struct,struct):struct' (IL size 8) File: /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_prtest/src/jit/rationalize.cpp Line: 853
```

**Comment by fiigii** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by Anipik** [comment]
Assert failure(PID 24668 [0x0000605c], Thread: 27512 [0x6b78]): CONTRACT VIOLATION by SystemDomain::GetEntryPointThreadAptState at "c:\git\coreclr\src\vm\appdomain.cpp" @ 3054

MODE_PREEMPTIVE encountered while thread is in cooperative state.

                        CONTRACT in SystemDomain::GetEntryPointThreadAptState at "c:\git\coreclr\src\vm\appdomain.cpp" @ 3054
VIOLATED-->  GCX_COOP in Assembly::ExecuteMainMethod at "c:\git\coreclr\src\vm\assembly.cpp" @ 1790
                        CONTRACT in Assembly::ExecuteMainMethod at "c:\git\coreclr\src\vm\assembly.cpp" @ 1774
                        GCX_COOP in CorHost2::ExecuteAssembly at "c:\git\coreclr\src\vm\corhost.cpp" @ 480
                        CONTRACT in CorHost2::ExecuteAssembly at "c:\git\coreclr\src\vm\corhost.cpp" @ 424 

@jkotas most probably we are not calling this Api at appropriate place. How can we safely call the Api here or whether I should be doing it somewhere else

**Comment by jkotas** [comment]
Right, the assert is complaining about GC mode violation. The rules are described here: https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-code-guide.md#218-use-the-right-gc-mode--preemptive-vs-cooperative

File: src/vm/assembly.cpp [hunk 2]
```diff
@@ -1780,6 +1780,36 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
...
+            if (scope->IsValidToken(tkEntryPoint))
+                state = SystemDomain::GetEntryPointThreadAptState(scope, tkEntryPoint);
+            else
+                ThrowHR(COR_E_BADIMAGEFORMAT);
+        }
+
+        // If the entry point has an explicit thread apartment state, set it
+        // before running the AppDomainManager initialization code.
+        if (state == Thread::AS_InSTA || state == Thread::AS_InMTA)
+            SystemDomain::SetThreadAptState(scope, state);
```
Comment (jkotas) [inline src/vm/assembly.cpp]: Could you please delete `scope` argument of the `SetThreadAptState` method and the .NET Framework 1.0 compat quirk from it.

File: src/vm/assembly.cpp [hunk 3]
```diff
@@ -1780,6 +1780,36 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
...
+        ReleaseHolder<IMDInternalImport> scope(m_pManifestFile->GetMDImportWithRef());
+        // In theory, we should have a valid executable image and scope should never be NULL, but we've been  
+        // getting Watson failures for AVs here due to ISVs modifying image headers and some new OS loader 
+        // checks (see Dev10# 718530 and Windows 7# 615596)
+        if (scope == NULL)
+        {
+            ThrowHR(COR_E_BADIMAGEFORMAT);
+        }
+
+#ifdef FEATURE_COMINTEROP
```
Comment (tannergooding) [inline src/vm/assembly.cpp]: Shouldn't we be setting the apartment state, regardless of whether `FEATURE_COMINTEROP` is defined? That way `Thread.GetApartmentState` returns the correct value?

File: src/vm/interoputil.cpp [hunk 4]
```diff
@@ -2335,14 +2335,11 @@ VOID EnsureComStarted(BOOL fCoInitCurrentThread)
...
-        // Attempt to set the thread's apartment model (to MTA by default). May not
-        // succeed (if someone beat us to the punch). That doesn't matter (since
-        // COM+ objects are now apartment agile), we only care that a CoInitializeEx
-        // has been performed on this thread by us.
+        FinalizerThread::GetFinalizerThread()->SetRequiresCoInitialize(); 
+        // Setting the thread's apartment state to Unknown when no attribute is supplied by the User.
+        // Thread is not CoInitialized
         if (fCoInitCurrentThread)
-            GetThread()->SetApartment(Thread::AS_InMTA, FALSE);
+            GetThread()->SetApartment(Thread::AS_Unknown, FALSE);
```
Comment (jkotas) [inline src/vm/interoputil.cpp]: Calling `SetApartment(Thread::AS_Unknown` will cause the COM to be uninitialized: https://github.com/dotnet/coreclr/blob/ddab65b2643ec2c3b7a376f4f44a05073124b732/src/vm/threads.cpp#L5168

This means that this EnsureComStarted method is doing opposite to what its name suggests. It is ensuring that the COM is not started, not that the COM is started.

Comment (jkotas) [reply src/vm/interoputil.cpp]: The dummy apartment state on Unix is handled in C# . It does not even go to here.

File: src/vm/appdomain.cpp [hunk 5]
```diff
@@ -3081,39 +3081,10 @@ Thread::ApartmentState SystemDomain::GetEntryPointThreadAptState(IMDInternalImpo
...
-            (pVer[2] == '.') )
-        {
-            // Looks like a version.  Is it lesser than v2.0 major version where we start using new behavior?
-            fIsLegacy = DIGIT_TO_INT(pVer[1]) < METAMODEL_MAJOR_VER_WITH_NEW_BEHAVIOR;
-        }
-    }
-
-    if (!fIsLegacy && g_pConfig != NULL)
-    {
-        fIsLegacy = g_pConfig->LegacyApartmentInitPolicy();
```
Comment (jkotas) [inline src/vm/appdomain.cpp]: Nit: You can delete `LegacyApartmentInitPolicy` references from everywhere in inc and vm directories.

Comment (jkotas) [inline src/vm/appdomain.cpp]: Nit: You can delete `LegacyApartmentInitPolicy` references from everywhere in inc and vm directories.

File: src/vm/comsynchronizable.cpp [hunk 6]
```diff
@@ -1055,7 +1055,6 @@ FCIMPL1(INT32, ThreadNative::GetApartmentState, ThreadBaseObject* pThisUNSAFE)
         // ApartmentState.Unknown to our callers.
```
Comment (jkotas) [inline src/vm/comsynchronizable.cpp]: This comment says that this method is intentionally initializing COM to not return ApartmentState.Unknown. It means that somebody thought about it and intentionally made this change.

Returning `ApartmentState.Unknown` here is a breaking change. If we want to make that breaking change, we need to understand the impact, why it was done this way in the first place, etc.

Comment (Anipik) [reply src/vm/comsynchronizable.cpp]: @danmosemsft do you know why  "Returning ApartmentState.Unknown" was done in the first place ?

**Comment by Anipik** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Innerloop Build

File: src/vm/assembly.cpp [hunk 7]
```diff
@@ -1780,6 +1780,37 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
...
+        // checks (see Dev10# 718530 and Windows 7# 615596)
+        if (scope == NULL)
+        {
+            ThrowHR(COR_E_BADIMAGEFORMAT);
+        }
+
+#ifdef FEATURE_COMINTEROP 
+        Thread::ApartmentState state = Thread::AS_Unknown;        
+
+        if((!IsNilToken(tkEntryPoint)) && (TypeFromToken(tkEntryPoint) == mdtMethodDef)) {
```
Comment (jkotas) [inline src/vm/assembly.cpp]: This should just use the `MethodDesc*` of the entrypoint that is fetched below:  pMeth = GetEntryPoint();. No need to compute it or validate the token twice.

File: src/vm/comsynchronizable.cpp (hunk 6 above)
Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: This code existed at least until the move from Source Depot in 2010, SDV won't let me go further back.

What I observed in the issue:
> Main thread: 
> * On Core, starts off uninitialized, but GetApartmentState returns MTA (should be Unknown). Because it's uninitialized, you can successfully SetApartmentState to STA or MTA and that initializes it.
> * On Full FX, starts off as specified in attribute, else MTA. GAS returns the value accurately and because it is already  initialized you can't SAS to a different value.

>Secondary threads:
> * On both platforms, GAS accurately reports Unknown. You can set to MTA or STA to intialize it, until you have started the thread at which point GAS returns MTA unless you requested STA and SAS fails.

It looks like EnsureComStarted() here=>thread->SetApartment(Thread::AS_InMTA..)=> sets the state if it's Unknown, pends the CoInit if thread isn't started. Subsequent calls to EnsureComStarted() return true. Subsequent direct calls to SetApartment always succeed if thread isn't started.

The managed SetApartment=>thread->SetApartment with the requested value, or throws if it's already running.

When a thread starts, PrepareApartmentAndContext()=>thread->SetApartment(..) which is what ensures CoInit actually happens to whatever it was prepped with.

Secondary threads always return Unknown initially because EnsureComStarted() was already called on the main thread so g_fComStarted was set so calls to EnsureComStarted() return true.

Hmm.

Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: We should return the apartment state that accurately represents what the state of the thread will be when it's started. We should not change the behavior of what apartment state is chosen (aside from not ignoring the attribute anymore).

If (assuming no attributes) Core is currently CoInitializing the main thread to MTA, then we are correctly returning MTA. So this line should be reverted and you will never get Unknown apartment state on the main thread.

Comment (Anipik) [reply src/vm/comsynchronizable.cpp]: The state of Main thread is Unknown when it is started (assuming no attribute) as we are able to set it to STA or MTA.

Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: @Anipik that's what I thought, but it's only true if you haven't called GAS already. This

```c#
            Thread t = Thread.CurrentThread;
            Console.WriteLine(t.GetApartmentState());
            t.SetApartmentState(ApartmentState.STA);
```
throws.

The reason being this call in GAS to EnsureComStarted(). So we should never return Unknown because the act of getting the value sets it to MTA (if it was Unknown) !

Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: fyi @tannergooding

Comment (Anipik) [reply src/vm/comsynchronizable.cpp]: @danmosemsft  shouldn't we just start the COM and keep the state as Unknown (if it was Unknown) In GAS ?

Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: No because then the value would be different than .NET Framework even though the behavior is the same -- in both runtimes, the main thread ends up as MTA (unless there is an STA attribute or you set STA).

There is still one difference, in .NET Framework you cannot do SAS to something else on the main thread even if you never ran GAS. So this fails on .NET Framework and works on .NET Core:
```c#
        public static void Main(string[] args) // No attribute
        {       
            Thread t = Thread.CurrentThread;
            t.SetApartmentState(ApartmentState.STA);
```
Put in a GAS before the SAS and it will fail on Core also.

I don't know why that is, you would have to debug, but the key thing is what the thread is CoIinitialized to when it starts, and it's MTA in both cases, so ideally we would behave the same as .NET Framework here also.

Comment (danmosemsft) [reply src/vm/comsynchronizable.cpp]: BTW I don't think it's partiuclarly important to mimic that SAS can't be called even without GAS.

File: src/vm/assembly.cpp (hunk 7 above)
Comment (Anipik) [reply src/vm/assembly.cpp]: I have removed the checks. but I am not able to figure how to avoid computing tkentrypoint(mdtoken)
mdToken tkEntryPoint = m_pManifestFile->GetEntryPointToken();
As we are using this token to get the state in 
state = SystemDomain::GetEntryPointThreadAptState(scope, tkEntryPoint);

File: src/vm/assembly.cpp (hunk 3 above)
Comment (Anipik) [reply src/vm/assembly.cpp]: Removing this if leads to failure of tests on Unix systems. I still need to debug the reason for that

Comment (jkotas) [reply src/vm/assembly.cpp]: As I have said in the other comment, the dummy apartment state on Unix is handled in C# . It does not even go to VM. This ifdef is fine. Appartments are Windows-specific COM-specific feature.

File: src/vm/assembly.cpp [hunk 8]
```diff
@@ -1790,6 +1790,20 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
         GCX_COOP();
 
         pMeth = GetEntryPoint();
+        {
+            GCX_PREEMP();
+
+#ifdef FEATURE_COMINTEROP
```
Comment (jkotas) [inline src/vm/assembly.cpp]: You can include the `GCX_PREEMP();` in the ifdef as well.

File: src/vm/assembly.cpp [hunk 9]
```diff
@@ -1790,6 +1790,20 @@ INT32 Assembly::ExecuteMainMethod(PTRARRAYREF *stringArgs, BOOL waitForOtherThre
...
+            state = SystemDomain::GetEntryPointThreadAptState(pMeth->GetMDImport(), pMeth->GetMemberDef());
+
+            // If the entry point has an explicit thread apartment state, set it
+            // before running the AppDomainManager initialization code.
+            if (state == Thread::AS_InSTA || state == Thread::AS_InMTA)
+                SystemDomain::SetThreadAptState(state);
+#endif // FEATURE_COMINTEROP
+        }
+
         if (pMeth) {
```
Comment (jkotas) [inline src/vm/assembly.cpp]: Your new code should be undef this `if` to handle the case where `pMeth` is NULL.

File: src/vm/assembly.cpp (hunk 3 above)
Comment (tannergooding) [reply src/vm/assembly.cpp]: I understand that the actual behavior the state controls is Windows (or more specifically COM) specific.

I was just worried that Unix would not get set apprioately, which could cause potential issues in applications that do a RequiresStaThread, or equivalent check.

If Unix is already handling this in the managed code path, then it is probably fine

Comment (jkotas) [reply src/vm/assembly.cpp]: This is behavior on Unix: https://github.com/dotnet/corefx/blob/master/src/System.Threading.Thread/src/System/Threading/Thread.Unix.cs

File: src/vm/appdomain.cpp (hunk 5 above)
Comment (jkotas) [reply src/vm/appdomain.cpp]: Do you plan to do this cleanup? (It should be pretty straightforward - it is just a few places.)

Comment (Anipik) [reply src/vm/appdomain.cpp]: yeah i am going to do it. I was just waiting to first settle the rest of the code for this PR

File: src/vm/comsynchronizable.cpp [hunk 10]
```diff
@@ -1109,7 +1109,7 @@ FCIMPL1(void, ThreadNative::StartupSetApartmentState, ThreadBaseObject* pThisUNS
     // Assert that the thread hasn't been started yet.
     _ASSERTE(Thread::TS_Unstarted & thread->GetSnapshotState());
 
-    if ((g_pConfig != NULL) && !g_pConfig->LegacyApartmentInitPolicy())
+    if (g_pConfig != NULL)
```
Comment (jkotas) [inline src/vm/comsynchronizable.cpp]: `if (g_pConfig != NULL)` can be deleted too.

Comment (jkotas) [inline src/vm/comsynchronizable.cpp]: if (g_pConfig != NULL) can be deleted too.

**Comment by Anipik** [comment]
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by Anipik** [comment]
@dotnet-bot Ubuntu arm Cross Debug Innerloop Build

**Comment by Anipik** [comment]
@dotnet-bot test Ubuntu arm Cross Debug Innerloop Build

**Comment by BruceForstall** [comment]
@jkotas @Anipik Since this was merged, I've seen regular but not 100% test failures in the CI, related to EH. 

E.g.:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/3441/
```
JIT_Methodical._eh_finallyexec_switchincatch_ro_switchincatch_ro_._eh_finallyexec_switchincatch_ro_switchincatch_ro_cmd
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/3445/
```
JIT_Methodical._eh_interactions_switchinfinally_do_switchinfinally_do_._eh_interactions_switchinfinally_do_switchinfinally_do_cmd
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/3448/
```
JIT_Methodical._eh_regress_asurt_122239_outermostFinally_outermostFinally_._eh_regress_asurt_122239_outermostFinally_outermostFinally_cmd
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/3449/
```
JIT_Methodical._eh_deadcode_loopstrswitchgoto_ro_loopstrswitchgoto_ro_._eh_deadcode_loopstrswitchgoto_ro_loopstrswitchgoto_ro_cmd
JIT_Methodical._eh_interactions_switchinfinally_ro_switchinfinally_ro_._eh_interactions_switchinfinally_ro_switchinfinally_ro_cmd
```

The x64 jobs show similar things:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt/3850/
```
JIT_Methodical._eh_interactions_switchinfinally_r_switchinfinally_r_._eh_interactions_switchinfinally_r_switchinfinally_r_cmd
JIT_Regression._VS_ia64_JIT_M00_b99403_b99403_b99403_._VS_ia64_JIT_M00_b99403_b99403_b99403_cmd
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt/3849/
```
JIT_Regression._VS_ia64_JIT_M00_b98431_b98431_b98431_._VS_ia64_JIT_M00_b98431_b98431_b98431_cmd
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt/3847/
```
JIT_Methodical._eh_finallyexec_switchincatch_ro_switchincatch_ro_._eh_finallyexec_switchincatch_ro_switchincatch_ro_cmd
```

etc.

Can you investigate?

**Comment by jkotas** [comment]
@BruceForstall Thanks for the heads-up. All failing tests you have listed are marked with STAThread attribute, so they certainly are affected by this change.

I have queued revert of this change https://github.com/dotnet/coreclr/pull/15586 so that we are not suffering from this instability in CI until this is understood and fixed.

**Comment by Anipik** [comment]
@jkotas I am able to repro the bug locally. But I am not able to find any more information about the failure than provided in the console output. I also dont how you find out that these tests are marked with STAThread attribute. can you help ?

c:\git\coreclr\bin\tests\Windows_NT.x64.Debug\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs(17257): error
: JIT_Methodical._eh_interactions_switchinfinally_d_switchinfinally_d_._eh_interactions_switchinfinally_d_switchinfinal
ly_d_cmd [FAIL] [c:\git\coreclr\tests\runtest.proj]


  Return code:      1
  Raw output file:      c:\git\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\JIT.Methodical\eh\interactions\switchinfi
  nally_d\switchinfinally_d.output.txt
  Raw output:
  BEGIN EXECUTION
         "c:\git\coreclr\tests\..\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" switchinfinally_d.exe
        In MyClass
        In finally
        Still in finally

        Exitting finally

        done testing
        1234
        Expected: 100
        Actual: -2146234327
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

  To run the test:
  > set CORE_ROOT=c:\git\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root
  > c:\git\coreclr\bin\tests\Windows_NT.x64.Debug\JIT\Methodical\eh\interactions\switchinfinally_d\switchinfinally_d.cm
  d

        Expected: True
        Actual:   False
          c:\git\coreclr\bin\tests\Windows_NT.x64.Debug\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs(1725
  7,0): at JIT_Methodical._eh_interactions_switchinfinally_d_switchinfinally_d_._eh_interactions_switchinfinally_d_swit
  chinfinally_d_cmd()

**Comment by jkotas** [comment]
> I also dont how you find out that these tests are marked with STAThread attribute

The STAThread attribute used to be part of the default program templates in the past. The tests that have been created using those templates have the attribute, even though they may not strictly need it.

These tests are likely approximating .NET Core program population out there. There is a good chance that programs that have been copy&pasted from .NET Framework to .NET Core will have this attribute.

**Comment by jkotas** [comment]
> I am not able to find any more information about the failure 

Have you tried running it under debugger (windbg will probably work the best)?

**Comment by Anipik** [comment]
I will try to that now
