### PR TITLE
Fix #7089.

### LINKED ISSUE #7089: RyuJIT x86: Assertion failed '!isRegPairType(tree->gtType)'
In Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.4

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPLus_JitStressRegs=4

/JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.cmd

> D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(106986): error : JIT._jit64_hfa_main_testE_hfa_sf2E_d_hfa_sf2E_d_._jit64_hfa_main_testE_hfa_sf2E_d_hfa_sf2E_d_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\runtest.proj]
> Assert failure(PID 4288 [0x000010c0], Thread: 4604 [0x11fc]): Assertion failed '!isRegPairType(tree->gtType)' in 'DomainBoundILStubClass:IL_STUB_PInvoke():struct' (IL size 44)
> File: d:\j\workspace\x86_ryujit_ch---5357ccf8\src\jit\regset.cpp Line: 2342
> Image: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\hfa\main\testE\hfa_sf2E_d\hfa_sf2E_d.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" hfa_sf2E_d.exe
> [Identity HFA 01]	PASSED
> [Identity HFA 02]	PASSED
> [Identity HFA 03]	PASSED
> [Identity HFA 05]	PASSED
> [Identity HFA 08]	PASSED
> [Identity HFA 11]	PASSED
> [Identity HFA 19]	PASSED
> [Get HFA 01]	PASSED
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by pgavlin**
This bug was due to an assert that became misplaced with support
for partially spilling and restoring multi-reg call results.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet/jit-contrib @CarolEidt @sivarv @adiaaida PTAL

**Comment by adiaaida** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

File: src/jit/regset.cpp [hunk 1]
```diff
@@ -2339,8 +2339,6 @@ regNumber RegSet::rsUnspillOneReg(GenTreePtr tree, regNumber oldReg, KeepReg wil
 //
 TempDsc* RegSet::rsUnspillInPlace(GenTreePtr tree, regNumber oldReg, unsigned regIdx /* =0 */)
 {
-    assert(!isRegPairType(tree->gtType));
```
Comment (sivarv) [inline src/jit/regset.cpp]: I am not sure this is the right fix.  May be I am don't have the full context here.

On x86 RyuJIT a multi-reg call node is not considered a regpair type.  In fact with multi-reg call node support added to x86 ryujit we have disabled regPair types.  We need to understand  why gentree is considered a repair type.

Comment (pgavlin) [inline src/jit/regset.cpp]: > On x86 RyuJIT a multi-reg call node is not considered a regpair type. In fact with multi-reg call node support added to x86 ryujit we have disabled regPair types.

AFAICT the code for `isRegPairType` disagrees:

```
inline bool isRegPairType(int /* s/b "var_types" */ type)
{
#ifdef _TARGET_64BIT_
    return false;
#elif CPU_HAS_FP_SUPPORT
    return type == TYP_LONG;
#else
    return type == TYP_LONG || type == TYP_DOUBLE;
#endif
}
```

Comment (pgavlin) [inline src/jit/regset.cpp]: FWIW, the code I've changed appears to be the only part of the RyuJIT backend that observes `isRegPairType`. We could probably go further and `#ifdef` out `isRegPairType` entirely for RyuJIT.

Comment (sivarv) [inline src/jit/regset.cpp]: Yes, That seems like the right fix.

**Comment by sivarv** [comment]
Looks good.
