### PR TITLE
JIT: In morph, only call DefinesLocal on assignments

### LINKED ISSUE #22747: JIT: morph overly aggressive in killing local assertions
Checking `DefinesLocal` is not sufficient to establish that a tree is a local def. One also needs to check for `GTF_VAR_DEF`. 

Because of this, morph ends up killing off local assertions for variables at uses as well as defs. Not surprisingly, this limits the usefulness of local assertion prop.

https://github.com/dotnet/coreclr/blob/344004681ace2b49dbc40d83ce422f81aa7efcb5/src/jit/morph.cpp#L15183-L15193

```
fgMorphTree BB01, stmt 9 (before)
               [000025] n-----------              /--*  OBJ(24)   struct
               [000024] ------------              |  \--*  ADDR      byref 
               [000023] ------------              |     \--*  LCL_VAR   struct V02 tmp2         
               [000081] -A----------              *  ASG       struct (copy)
               [000079] D-----------              \--*  LCL_VAR   struct V04 tmp4         

The assignment [000025] using V02 removes: Copy     Assertion: V02 == V01
```
Fixing this shows some nice wins in System.Linq.Parallel:
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: -53442 (-0.14% of base)
    diff is an improvement.
Top file regressions by size (bytes):
          60 : CommandLine.dasm (0.02% of base)
          24 : System.Net.Sockets.dasm (0.01% of base)
          14 : System.Security.Cryptography.Cng.dasm (0.01% of base)
          13 : System.Reflection.Metadata.dasm (0.00% of base)
           8 : System.IO.FileSystem.dasm (0.01% of base)
Top file improvements by size (bytes):
      -47472 : System.Linq.Parallel.dasm (-4.38% of base)
       -2929 : Microsoft.CodeAnalysis.CSharp.dasm (-0.07% of base)
       -1427 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.03% of base)
       -1150 : System.Private.Xml.dasm (-0.03% of base)
        -283 : Microsoft.CodeAnalysis.dasm (-0.02% of base)
24 total files with size differences (16 improved, 8 regressed), 105 unchanged.
Top method regressions by size (bytes):
          60 (16.48% of base) : CommandLine.dasm - ErrorExtensions:ToParserResult(ref,struct):ref
          41 (100.00% of base) : System.Private.CoreLib.dasm - DefaultDecoder:GetChars(ref,int,int,ref,int):int:this (1 base, 2 diff methods)
          34 ( 3.23% of base) : System.Security.Cryptography.Algorithms.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          34 ( 3.23% of base) : System.Security.Cryptography.Cng.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          15 ( 2.63% of base) : System.Reflection.Metadata.dasm - MetadataReader:CalculateMethodDefTreatmentAndRowId(struct):int:this
Top method improvements by size (bytes):
       -1443 (-49.69% of base) : System.Linq.Parallel.dasm - UnaryQueryOperator`2:.ctor(ref):this (10 methods)
       -1443 (-50.03% of base) : System.Linq.Parallel.dasm - UnaryQueryOperator`2:.ctor(ref,bool):this (10 methods)
       -1200 (-27.45% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:TakeWhile(ref,ref):ref (10 methods)
       -1200 (-27.45% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:SkipWhile(ref,ref):ref (10 methods)
       -1200 (-27.57% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:Select(ref,ref):ref (10 methods)
Top method regressions by size (percentage):
          41 (100.00% of base) : System.Private.CoreLib.dasm - DefaultDecoder:GetChars(ref,int,int,ref,int):int:this (1 base, 2 diff methods)
          60 (16.48% of base) : CommandLine.dasm - ErrorExtensions:ToParserResult(ref,struct):ref
           7 ( 3.29% of base) : System.Net.Sockets.dasm - SocketPal:SendAsync(ref,ref,int,ref):int
          34 ( 3.23% of base) : System.Security.Cryptography.Algorithms.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          34 ( 3.23% of base) : System.Security.Cryptography.Cng.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
Top method improvements by size (percentage):
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DecimalAverageAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DecimalSumAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DoubleAverageAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DoubleSumAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - FloatAverageAggregationOperator:.ctor(ref):this
330 total methods with size differences (277 improved, 53 regressed), 193022 unchanged.
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
~~Only return true for actual assignments.~~

Only call `DefinesLocal` for `GT_ASG` nodes, so we're sure we are looking at a def, not a use.

Resolves #22747.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

We should probably revise the logic in `DefinesLocal` but will leave that for a subsequent zero-diff change.

Main impact from this change is that morph now keeps assertions viable longer, as it not longer will see some uses as assertion kills. More details in #22747.

Diffs from this change:
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: -53354 (-0.14% of base)
    diff is an improvement.
Top file regressions by size (bytes):
          96 : System.Private.CoreLib.dasm (0.00% of base)
          60 : CommandLine.dasm (0.02% of base)
          24 : System.Net.Sockets.dasm (0.01% of base)
          14 : System.Security.Cryptography.Cng.dasm (0.01% of base)
          13 : System.Reflection.Metadata.dasm (0.00% of base)
Top file improvements by size (bytes):
      -47472 : System.Linq.Parallel.dasm (-4.38% of base)
       -2929 : Microsoft.CodeAnalysis.CSharp.dasm (-0.07% of base)
       -1427 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.03% of base)
       -1150 : System.Private.Xml.dasm (-0.03% of base)
        -283 : Microsoft.CodeAnalysis.dasm (-0.02% of base)
24 total files with size differences (16 improved, 8 regressed), 105 unchanged.
Top method regressions by size (bytes):
          60 (16.48% of base) : CommandLine.dasm - ErrorExtensions:ToParserResult(ref,struct):ref
          34 ( 3.23% of base) : System.Security.Cryptography.Algorithms.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          34 ( 3.23% of base) : System.Security.Cryptography.Cng.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          15 ( 2.63% of base) : System.Reflection.Metadata.dasm - MetadataReader:CalculateMethodDefTreatmentAndRowId(struct):int:this
           9 ( 1.13% of base) : Microsoft.CodeAnalysis.CSharp.dasm - LanguageParser:ParseEnumDeclaration(struct,ref):ref:this
Top method improvements by size (bytes):
       -1443 (-49.69% of base) : System.Linq.Parallel.dasm - UnaryQueryOperator`2:.ctor(ref):this (10 methods)
       -1443 (-50.03% of base) : System.Linq.Parallel.dasm - UnaryQueryOperator`2:.ctor(ref,bool):this (10 methods)
       -1200 (-27.45% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:TakeWhile(ref,ref):ref (10 methods)
       -1200 (-27.45% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:SkipWhile(ref,ref):ref (10 methods)
       -1200 (-27.57% of base) : System.Linq.Parallel.dasm - ParallelEnumerable:Select(ref,ref):ref (10 methods)
Top method regressions by size (percentage):
          60 (16.48% of base) : CommandLine.dasm - ErrorExtensions:ToParserResult(ref,struct):ref
           7 ( 3.29% of base) : System.Net.Sockets.dasm - SocketPal:SendAsync(ref,ref,int,ref):int
          34 ( 3.23% of base) : System.Security.Cryptography.Algorithms.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
          34 ( 3.23% of base) : System.Security.Cryptography.Cng.dasm - KeyFormatHelper:WriteEncryptedPkcs8(struct,struct,ref,ref):ref
           7 ( 3.20% of base) : System.Net.Sockets.dasm - SocketPal:ReceiveAsync(ref,ref,int,ref):int
Top method improvements by size (percentage):
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DecimalAverageAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DecimalSumAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DoubleAverageAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - DoubleSumAggregationOperator:.ctor(ref):this
        -150 (-50.51% of base) : System.Linq.Parallel.dasm - FloatAverageAggregationOperator:.ctor(ref):this
328 total methods with size differences (276 improved, 52 regressed), 193024 unchanged.
```

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -15432,10 +15450,7 @@ bool GenTree::DefinesLocal(Compiler* comp, GenTreeLclVarCommon** pLclVarTree, bo
             blkNode = gtOp.gtOp1->AsBlk();
         }
     }
-    else if (OperIsBlk())
```
Comment (CarolEidt) [inline src/jit/gentree.cpp]: This is here to catch the block store case, but obviously needs to only check for stores. I'm not sure how this can be correct if it's only checking for assignments, and this is used in liveness.

Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Looks at first glance like many callers use `DefinesLocal` to try and determine if we're going to track byref exposed separately from gc heap exposed. So returning false more often just makes the jit more conservative.

For correctness, Liveness uses `DefinesLocalAddr` and looks for `GTF_VAR_DEF` to determine context.

So I suppose we could update morph to use `DefinesLocalAddr` and flags checks to kill assertions, and separately determine what if anything we need to do to `DefinesLocal`.

Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Or use `DefinesLocal` and likewise do a flag check, which is what I more or less did initially.

Comment (mikedn) [reply src/jit/gentree.cpp]: Looks to me that instead of `OperIsBlk` we need to specifically check for GT_STORE_OBJ/BLK/DYN_BLK

Comment (CarolEidt) [reply src/jit/gentree.cpp]: Right, that's what I meant to say above, but obviously wasn't clear.

Comment (mikedn) [reply src/jit/gentree.cpp]: This just shows that better handling of assignment to struct typed fields is a good preamble to getting rid of `GT_ASG`. Once that's done we only need to check for `GT_ASG(GT_LCL_VAR/FLD, x)` and `GT_STORE_LCL_VAR/FLD`. Without the whole `DefinesLocalAddr` goo.

Comment (mikedn) [reply src/jit/gentree.cpp]: I'm starting to think that the best fix at the moment is to wrap the `DefinesLocal` call in morph in `if (tree->OperIs(GT_ASG))`. All its over uses are under similar guards.

Even if you make the `OperIsBlk` check more specific, this function still doesn't cover all "defines local" cases - you'll need to add `GT_STORE_LCL_VAR/FLD` to it for what. And maybe `GT_STOREIND` too.

Ultimately this function is an artifact of `GT_ASG` and it should disappear together with it.

Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: I'd be fine with that too. Gives the same diffs as the other two variants I've tried.

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
@CarolEidt are you ok with the latest version of this?

**Comment by CarolEidt** [comment]
I'm still concerned about this case where this may be called in an LIR context, when we won't kill an assertion upon encountering a `GT_STORE_LCL_VAR`. There may be some reason that I'm missing that would cause this not to be an issue, but I'm not understanding it.

**Comment by mikedn** [comment]
> I'm still concerned about this case where this may be called in an LIR context, when we won't kill an assertion upon encountering a GT_STORE_LCL_VAR

The only known LIR use of `DefinesLocal` is in liveness and that checks for `GT_STORE_LCL_VAR` separately.

**Comment by CarolEidt** [comment]
I apologize if I'm being obtuse about this, but my concern is whether we ever do local assertion prop in LIR. If the answer is no, then I think it would be prudent to add an assert here that we don't have a local store. Then if we ever start calling it with LIR the assert will trigger. Does that make sense?

**Comment by AndyAyersMS** [comment]
Seems reasonable. Have started looking at assertion prop to see if we ever take steps to turn it off.

**Comment by mikedn** [comment]
> If the answer is no, then I think it would be prudent to add an assert here that we don't have a local store. Then if we ever start calling it with LIR the assert will trigger. Does that make sense?

Sure, an assert would be good to prevent surprises.

> I apologize if I'm being obtuse about this, but my concern is whether we ever do local assertion prop in LIR.

Here I'm probably in disagreement with the team. Sometimes I have the impression that the team would prefer adding more stuff to the JIT without fixing long standing design issues such as `GT_ASG`. IMO that's wrong, if you ever want to do something like assertion propagation in LIR then you first need to get rid of `GT_ASG` & co. Then `DefinesLocal` would no longer be an issue because it would simply disappear in the process.

**Comment by AndyAyersMS** [comment]
`fgMorphBlocks` enables local assertion prop when the jit is optimizing. `optAssertionPropMain` disables local asssertion prop (in a somewhat subtle fashion, by calling `optAssertionInit(false)`).

So currently, no local assertion prop should happen on LIR.

Is there anything other than `GT_STORE_LCL_VAR` we should check for?

**Comment by mikedn** [comment]
> Is there anything other than GT_STORE_LCL_VAR we should check for?

Its sibling, `GT_STORE_LCL_FLD`.

**Comment by AndyAyersMS** [comment]
Suspect testing got hung up by jenkins reboots. 

@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
Ubuntu CoreFX tests timed out:. Looking at history this seems to happen every so often.
```
06:19:02 Build timed out (after 360 minutes). Marking the build as aborted.
```
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests

**Comment by janvorli** [comment]
@AndyAyersMS I've noticed that this change caused 3.3% stable drop in the FractalPerf / Launch /Test on Linux x64 (Windows has a drop too, but much smaller (0.23%).

**Comment by AndyAyersMS** [comment]
Not too surprising, the jit was throwing away some useful information.

image

Oddly the BDN-based measurements show a regression over this time span, though I can't figure out exacly which CoreCLR bits these runs are testing. @adamsitnik @jorive what do the commit hashes on the BDN runs refer to?

image

**Comment by adamsitnik** [comment]
@AndyAyersMS could you please share the link to BenchView with your filter?

When I look at the xunit-performance results uploaded to BenchView I can't see the same drop as on your chart ([link](https://benchview/trendline?build_selector=latest&count=20&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[9]&mpids=[1292]&cfgids=[2927,2917]&testids=[58902]&jobid=154067&))

obraz

The results uploaded from dotnet/performance ([link](https://benchview/trendline?build_selector=latest&count=5&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[1713]&archids=[9,4]&mpids=[1292]&cfgids=[3386,2922]&testids=[58902]&jobid=154003&))

obraz

Speaking of the commits, we are currently using the sha of dotnet/core-setup. We have an issue for that https://github.com/dotnet/performance/issues/347 to change it to point to dotnet/core-sdk. This will be fixed soon, @jorive already provided a PR for that https://github.com/dotnet/performance/pull/354

Another important fact is that we run the benchmarks against the end product (we just download the latest dotnet cli). So it has all optimizations like PGO enabled.

Also, the BenchView uploader went down, @adiaaida has restarted it few minutes ago. As soon as we get the new results uploaded it should give us more data to be sure if there was a regression or no.

**Comment by AndyAyersMS** [comment]
For benchview it would be great if we could get the relevant repo hashes (at least CoreCLR and CoreFX) instead of some aggregate repo hash, so that the diff display gets us to the right commit ranges. Any friction we can remove here is a win.

Here's the [link](https://benchview/trendline?build_selector=latest&count=20&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[1713]&archids=[9]&mpids=[1292]&cfgids=[3386]&testids=[58902]&jobid=154003&) for my second chart above -- think the same data is there in your view too, the very end of the orange line. I just zoomed in a bit since I was trying to match the time interval in the first plot, and only selected Ubuntu x64, since the disparity in results in the multi-result chart leads to compressed dynamic ranges for each individual run, making it hard to assess the magnitude of changes.

This last regression could well be within noise level for that test, though the xunit-perf results are not very noisy.

**Comment by AndyAyersMS** [comment]
Here's the [link](https://benchview/trendline?build_selector=latest&count=200&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[9]&mpids=[1292]&cfgids=[2927,2917]&testids=[58902]&jobid=154067&) to the xunit-perf data from my first chart. Basically the same as yours, but you need to look back in history a bit further (40 runs is enough).

**Comment by jorive** [comment]
@AndyAyersMS The plan is to change the CoreClr and CoreFx rolling runs to use the performance repository in the near future (So we will be running against different parts of the .NET stack).

**Comment by AndyAyersMS** [comment]
@jorive understood, and looking forward to it. But if possible, we should make sure it is easy to go from a regression to the actual changes that might have caused the regression.

**Comment by adiaaida** [comment]
@AndyAyersMS I think there has been some talk of using darc to discern the relevant hashes from coreclr/corefx from a given dotnet install. I think @brianrob has been looking into this for the optimization repo, and it may be something we could look into using here. Brian, could you give some context into how you think that will work for the optimization repo?
