### PR TITLE
Fix Interop/PInvoke/Miscellaneous/HandleRef tests under GCStress

### LINKED ISSUE #21115: [Arm/Linux] Interop_PInvoke._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_sh failed with TestLibrary.AssertTestException
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst/36/
**Failed test:**
Interop_PInvoke._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_sh

**Failed log:**
```
Interop_PInvoke._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_sh [FAIL]
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst/bin/tests/Linux.arm.Checked/Interop/PInvoke/Reports/Interop.PInvoke/Miscellaneous/HandleRef/HandleRefTest/HandleRefTest.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun HandleRefTest.exe
        MarshalPointer_In
        MarshalPointer_InOut
        MarshalPointer_Out
        TestNoGC
        2
        GC callback now
        Test Failure: TestLibrary.AssertTestException: Assert.AreEqual: Expected: [3000]. Actual: [4000]. The return value is wrong
           at TestLibrary.Assert.AreEqual[T](T expected, T actual, String message) in /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 414
           at HandleRefTest.Main(String[] args) in /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.cs:line 78
        Error in Function TestNoGC(Native Client)
        Expected:1000
        Actual:0
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst/bin/tests/Linux.arm.Checked/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest/HandleRefTest.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/Interop.PInvoke/Interop.PInvoke.XUnitWrapper.cs(1369,0): at Interop_PInvoke._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_._Miscellaneous_HandleRef_HandleRefTest_HandleRefTest_sh()
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Emit a `GC.KeepAlive` call for the object wrapped in a `HandleRef` when marshalling a `HandleRef` to native code. Also, add an extra `GC.KeepAlive` for an object in the test that needs to live across the call but wasn't referenced after the P/Invoke originally.

Fixes #21115

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu arm Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Windows_NT x64 Checked gcstress0xc_jitstress1

File: src/vm/ilmarshalers.cpp [hunk 1]
```diff
@@ -2560,6 +2561,12 @@ MarshalerOverrideStatus ILHandleRefMarshaler::ArgumentOverride(NDirectStubLinker
         pcsDispatch->EmitLDC(offsetof(HANDLEREF, m_handle));
```
Comment (jkotas) [inline src/vm/ilmarshalers.cpp]: I would be nice to fetch the `m_handle` via `MscorlibBinder::GetField` as well for consistency.

File: tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.cs [hunk 2]
```diff
@@ -77,7 +77,8 @@ public unsafe static int Main(string[] args)
             Action gcCallback = () => { Console.WriteLine("GC callback now"); GC.Collect(2, GCCollectionMode.Forced); GC.WaitForPendingFinalizers(); GC.Collect(2, GCCollectionMode.Forced); };
             Assert.AreEqual(intReturn, TestNoGC(hr4, gcCallback), "The return value is wrong");
             Console.WriteLine("Native code finished");
-
+            GC.KeepAlive(boxedInt);
```
Comment (jkotas) [inline tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.cs]: Why is this needed? The GCHandle that is allocated above (and never freed) should be keeping the `boxedInt` alive.

Comment (jkotas) [reply tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.cs]: I think there is a different problem here - when ` *int4Ptr = intManaged;` runs, there does not seem to be anything pinning the `BoxedInt` object.

Comment (jkoritzinsky) [reply tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.cs]: Without this, the test was still failing under GCStress in a way different than if the HandleRef wasn't holding the reference. Without this, the value pointed to in the `CollectableClass.PtrToChange` field was changed to `0` during the GC collect passes and GCStress. If the test was failing because of `HandleRef` not holding the reference, the value pointed to should have been changed to `int.MaxValue`.

**Comment by jkotas** [comment]
`
HandleRefTest.cs(58,28): error CS0266: Cannot implicitly convert type 'System.IntPtr' to 'int*'. An explicit conversion exists (are you missing a cast?) [/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_innerloop_prtest/tests/src/Interop/PInvoke/Miscellaneous/HandleRef/HandleRefTest.csproj]
`

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu arm Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Windows_NT x64 Checked gcstress0xc_jitstress1

**Comment by jkoritzinsky** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by jkoritzinsky** [comment]
The tests that are failing in GCStress are unrelated failures (see #21143 and #21145).
