### PR TITLE
Use flags in exceptionhandling.cpp

### LINKED ISSUE #9822: [x86/Linux] GC.Coverage.delete_next_card_table test failure
The following assert failure is observed during x86/Linux CLR unittest:
```
FAILED   - [ 075 :    7 sec ] GC/Coverage/delete_next_card_table/delete_next_card_table.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170227_155439_x86_x86-emu/coreclr-unittest-170227-065508/overlay/corerun delete_next_card_table.exe
               Churn loop 0...........................OOM while Churning
               
               Assert failure(PID 17634 [0x000044e2], Thread: 17634 [0x44e2]): false && "ExceptionTracker::HasFrameBeenUnwoundByAnyActiveException"
                   File: /home/parjong/projects/dotnet/coreclr/src/vm/exceptionhandling.cpp Line: 6302
                   Image: /root/dotnet-test/coreclr_unittest_20170227_155439_x86_x86-emu/coreclr-unittest-170227-065508/overlay/corerun
               
               ./delete_next_card_table.sh: line 138: 17634 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" delete_next_card_table.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by parjong**
This commit introduces two flags in exceptionhandling.cpp:
 - USE_FUNCLET_CALL_HELPER for call helper-related code
 - STACK_RANGE_BOUNDS_ARE_CALLER_SP for m_EHClauseInfo-related checks.

This commit fixes #9822.

### CODE REVIEW

File: src/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -6184,11 +6187,11 @@ bool ExceptionTracker::IsInStackRegionUnwoundBySpecifiedException(CrawlFrame * p
 
     // Remember that sfLowerBound and sfUpperBound are in the "OS format".
     // Refer to the comment for CallerStackFrame for more information.
-#if defined(_TARGET_AMD64_)
+#ifndef USE_FUNCLET_CALL_HELPER
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: Based on the comments above, this check differs based on whether the bounds are initialized from the caller SP or the SP of the frame itself. So it seems to me that using USE_FUNCLET_CALL_HELPER is a bit misleading. While it is true now that the usage of call helper matches the difference between using caller SP or SP of the frame itself, these things are not necessarily related. 
So I would prefer keeping the bounds checks here and below around likes 6282 and 6308 conditionalized by the target.

Comment (parjong) [inline src/vm/exceptionhandling.cpp]: @janvorli While digging this issue, I found that the major difference between AMD64 and ARM/ARM64 is that AMD64 uses the result of ``GetCurrentSP()`` called inside ``CallHandler`` to set ``m_EHClauseInfo``, but ARM/ARM64 updates it inside ``CallEHFunclet`` and ``CallEHFilterFunclet`` later (this is why I used ``USE_FUNCLET_CALL_HELPER`` here).

I agree with you that these things are not necessarily related, but then I would like to introduce another flag for these checks (for me, it was very difficult to find these checks are related when it was ifdefed by targets).

Could you let me know your opinion?

Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: I don't feel like the fact where we get the current SP is related to the stack range bounds. We get it inside of the asm helper just because we need the value at the caller of the funclet and the caller is the asm helper, while in the other case the caller is directly the CallHandler. Hence the different place we capture it.
It sounds it would be ok though to introduce a new ifdef, something like STACK_RANGE_BOUNDS_ARE_CALLER_SP if you feel it makes the conditions easier to understand.

Comment (parjong) [inline src/vm/exceptionhandling.cpp]: @janvorli Thank you for comment. I'll update PR as suggested.

Comment (parjong) [inline src/vm/exceptionhandling.cpp]: @janvorli FYI, I felt like the above due to the current implementation of ``GetCurrentSP`` (for x86). 

I checked the corresponding implementation in AMD64, and found that it is a bit different. 
(I submitted #9838 to fix this).
