### PR TITLE
Fix to issues #7167, 7094 and 7143

### LINKED ISSUE #7094: RyuJIT x86: Assertion failed 'regRecord->assignedInterval == nullptr'
Windows_NT.ryujit.x86.Checked.jit_stress_regs.3

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=3

/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b71099/b71099/b71099.cmd

> D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(351660): error : JIT._Regression_CLR_x86_JIT_V1_M12_Beta2_b71099_b71099_b71099_._Regression_CLR_x86_JIT_V1_M12_Beta2_b71099_b71099_b71099_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---9ec8b55e\tests\runtest.proj]
> Assert failure(PID 3644 [0x00000e3c], Thread: 5700 [0x1644]): Assertion failed 'regRecord->assignedInterval == nullptr' in 'Test.AA:Static3(byref,byref):bool' (IL size 110)
> File: d:\j\workspace\x86_ryujit_ch---9ec8b55e\src\jit\lsra.cpp Line: 11256
> Image: D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b71099\b71099\b71099.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---9ec8b55e\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b71099.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### LINKED ISSUE #7143: RyuJIT x86: Assertion failed '(farthestRefPhysRegRecord == nullptr) || (farthestRefPosWeight < getWeight(refPosition))'
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=1
set COMPlus_AltJit=*

GC\Scenarios\DoublinkList\doublinkstay\doublinkstay.cmd
GC\Scenarios\Boxing\gcvariant\gcvariant.cmd

### LINKED ISSUE #7167: RyuJIT x86: JitStressRegs=1 or 8 needs to ensure that the candidate set has minimum 2 regs
JitStress=2 and JitStressRegs=1 or 8
JIT\SIMD\BitwiseOperations_r\BitwiseOperations_r.cmd

Assertion failed '(farthestRefPhysRegRecord != nullptr) && (farthestLocation > refLocation || refPosition->isFixedRegRef)'

Under these stress modes, candidate set is limited to callee saved regs. If the IR has byte operation nodes, src candidates of its operand nodes could be limited to bytable registers { eax, ebx, ecx, edx }
The intersection of callee saved and bytable registers is a single register {ebx} which won't be sufficient to reg allocate byte type binary opers.

### PR DESCRIPTION
**Pull request by sivarv**
Issue #7167 and #7094 : fix LSRA stress not to constrain candidates set to below the required limit.
These failures are due to LSRA stress modes (1, 2, 3, and 8) restricting candidates set to fewer registers than required to reg allocate a GenTree.  This issue didn't surface on amd64 because there were enough registers available even after stress modes (1, 2, 3 and 8) has constrained candidates.

To fix this issue holistically, now every Ref position carries with it the minimum registers that needs to be ensured in its candidates.  Stress modes, while constraining candidate mask, will ensure that candidate set doesn't get constrained below the required limit.  The number of registers required is derived from lower register specification.

Example:

// compare two byte type values, producing a byte result.
// assume that mem-op is marked as contained by lower.
GT_CMP(v01, mem-op)

In this case, the Def position of GT_CMP, Use positions of v01 are set to have minimum 2 registers in their candidates set.  

Under stress mode 3 (small int set), since it has two bytable registers (eax and ecx), candidate sets of GT_CMP and v01 are constrained to {eax, ecx}.

Under stress mode 2 (restrict to callee saved regs), the intersection of callee saved and bytable regs is just {ebx} and won't be sufficient to meet minimum candidate reg requirement and hence GT_CMP and v01 will not be constrained under the stress mode.

Now the same v01 could be part of another gentree say
GT_ADD(v01, v02)

That needs 3 registers.  In this case def position of GT_ADD, Use positions of v01 and v02 are set to have minimum 3 registers.

Issue #7143:
On x86 we could have a case where ref position candidates has a single register which is also marked reg-optional under LSRA stress.  The repro has the following IR

// byte type comparison with GT_CMP not producing a value.
// Lower constrains src candidates of v01 to bytable registers.
// Under stress mode 2 or 8, candidates will be constrained {ebx}.
// Say ebx is already allocated to a higher weight ref position.
// v01 is also marked reg-optional since we an generate "cmp [mem], const"
GT_CMP(v01, int)

In such case we still need to allocate a reg to Use position of v01 only if it is profitable.  The logic in allocateBusyReg() was always allocating the reg if candidates has a single reg without any regard to weights.  This leads to assert failure since a reg-optional marked ref position is allocated reg by spilling a ref position of higher weight. To ensure that this doesn't happen,  allocateBusyReg() should set fathestRefPosWeight to BB_MAX_WEIGHT only if the ref position is not marked 'allocateIfProfitable'

This closes #7167, closes  #7094, closes #7143

### CODE REVIEW

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80

**Comment by sivarv** [comment]
@dotnet-bot test Ubuntu jitstressregs1
@dotnet-bot test Ubuntu jitstressregs2
@dotnet-bot test Ubuntu jitstressregs3
@dotnet-bot test Ubuntu jitstressregs4
@dotnet-bot test Ubuntu jitstressregs8
@dotnet-bot test Ubuntu jitstressregs0x10
@dotnet-bot test Ubuntu jitstressregs0x80

**Comment by sivarv** [comment]
@dotnet-bot test OSX x64 checked Build and Test

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs8

**Comment by sivarv** [comment]
@CarolEidt - Please review this.
CC @dotnet/jit-contrib

**Comment by sivarv** [comment]
@dotnet-bot test Ubuntu jitstressregs8

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -355,6 +355,35 @@ RegRecord* LinearScan::getRegisterRecord(regNumber regNum)
 }
 
 #ifdef DEBUG
+
+//----------------------------------------------------------------------------
+// getConstrainedRegMask: Returns new regMask which is the intersection of
+// regMaskActual and regMaskConstraint if the new regMask has at least 
+// minRegCount registers, otherwise returns regMaskActual.
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Why wouldn't you simply reduce the set to have minRegCount registers? That would still provide some "stress value" over defaulting to the full candidate set.

**Comment by sivarv** [comment]
@dotnet-bot test Ubuntu jitstressregs1

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -373,67 +402,55 @@ regMaskTP LinearScan::stressLimitRegs(RefPosition* refPosition, regMaskTP mask)
 {
     if (getStressLimitRegs() != LSRA_LIMIT_NONE)
     {
+        // refPosition could be null. 
+        // getTempRegForResolution() one such caller.
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Please use a full sentence, e.g. "The RefPosition could be null, for example when called by getTempRegForResolution()."

Comment (sivarv) [inline src/jit/lsra.cpp]: Done.

File: src/jit/lsra.cpp (hunk 1 above)
Comment (sivarv) [inline src/jit/lsra.cpp]: I remember discussing this with you.  Though considered, I haven't done partly based on your comment  that a stress mode doesn't have to be really "stressful".    Plus

1) even if a ref position of an interval is not stressed at a particular point,  it will be stressed at its next ref position where it is possible and that way we still will have coverage.
2) It will be a little more work and could slow down stress mode execution further.  I know we don't need to be concerned about increased execution time since it is a stress mode.
3) Not sure whether on x86 we have to be careful of what registers we remove from the set.  This needs to be experimented to figure out.

**Comment by sivarv** [comment]
There are some new assert failures in lsra.cpp even with these changes.  I am going to investigate those and send an updated PR with the fix to those as well.

**Comment by sivarv** [comment]
With my first iteration of changes LSRA stress run on x86 surfaced two new assert failures. 

First assert failure is due to unused nodes:  They unused nodes are considered to produce=0 (i.e dstCount=0), buildRefPositionsForNode() has logic in a couple of cases to set that to 1.  That is the number of regs required cannot be found out from gtLsraInfo alone.  Made code changes to pass minRegCount as additional debug param from buildRefPositionsForNode() to routines that add use/def positions for internal registers.

Second failure is due to the following IR

// v0 and v1 are coming in ecx and edx
// Further assme JitStressRegs=2 (i.e. constrain to callee trash registers { eax, ecx, edx })
GT_DIV(v0, v1)

MinRegCount will be 3 and candidate set of Use positions of v0 and v1 are constrained to callee trashable registers.  LSRA allocates ecx to v0.  Now there is no register available to allocate to v1 since {eax, edx} are killed before use of v1 and v1 is marked as delayRegFree.  In this case minRegCount set for Use position of delayFreeReg marked V1 also need to taken into account of kill set of its consuming node.

I have verified that with these changes x86 LSRA stress mode runs are free from LSRA assert failures.

@CarolEidt  - Please review this.

File: src/jit/lsra.cpp [hunk 3]
```diff
@@ -2837,25 +2894,44 @@ int LinearScan::buildInternalRegisterDefsForNode(GenTree*     tree,
...
     assert(count == (internalIntCount + internalFloatCount));
     return count;
 }
 
+//------------------------------------------------------------------------
+// buildInternalRegisterUsesForNode - adds Use positions for internal
+// registers required for tree node.
+//
+// Arguments:
+//   tree                  -   Gentree node the needs internal registers
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Typo "the" => "that"

File: src/jit/lsra.cpp [hunk 4]
```diff
@@ -2801,19 +2824,53 @@ bool LinearScan::buildKillPositionsForNode(GenTree* tree, LsraLocation currentLo
...
+                          0 
+                          DEBUG_ARG(minRegCandidateCount));
 }
 
+//------------------------------------------------------------------------
+// buildInternalRegisterDefsForNode - build Def positions for internal
+// registers required for tree node.
+//
+// Arguments:
+//   tree                  -   Gentree node the needs internal registers
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Typo: "the" -> "that"

**Comment by CarolEidt** [comment]
:shipit:

File: src/jit/lsra.cpp (hunk 4 above)
Comment (sivarv) [inline src/jit/lsra.cpp]: Fixed.

File: src/jit/lsra.cpp (hunk 3 above)
Comment (sivarv) [inline src/jit/lsra.cpp]: Fixed

**Comment by sivarv** [comment]
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Ubuntu jitstressregs1
@dotnet-bot test Ubuntu jitstressregs2
@dotnet-bot test Ubuntu jitstressregs3
@dotnet-bot test Ubuntu jitstressregs4
@dotnet-bot test Ubuntu jitstressregs8
@dotnet-bot test Ubuntu jitstressregs0x10
@dotnet-bot test Ubuntu jitstressregs0x80
