### PR TITLE
Arm64: Use op2 type for LOCKADD

### LINKED ISSUE #14539: ARM64 BUILD BREAK: Assertion failed 'info->dstCount == (tree->OperIs(GT_LOCKADD) ? 0 : 1)'
**Repro:**
build arm64 checked -toolset_dir <dir>

```
Assert failure(PID 6664 [0x00001a08], Thread: 1828 [0x0724]): Assertion failed 'info->dstCount == (tree->OperIs(GT_LOCKADD) ? 0 : 1)' in 'System.Threading.SpinLock:Exit():this' (IL size 37)

    File: c:\git\corecl2\src\jit\lsraarm64.cpp Line: 404
    Image: C:\git\corecl2\bin\Product\Windows_NT.arm64.Checked\x64\crossgen.exe
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #14539

### CODE REVIEW

**Comment by CarolEidt** [comment]
@sdmaclea - I'm not certain this is the right fix, but I added an assert that the type of op2 matches the type of the `LOCKADD` before it modifies that to `TYP_VOID`. It eliminates the assert in crossgen'ing of SPC.dll. I'll wait to hear from you whether there are tests for which the assert in gentree.cpp will fail.

File: src/jit/codegenarm64.cpp [hunk 1]
```diff
@@ -2722,7 +2722,7 @@ void CodeGen::genLockedInstructions(GenTreeOp* treeNode)
     // The following instruction includes a acquire half barrier
     // TODO-ARM64-CQ Evaluate whether this is necessary
     // https://github.com/dotnet/coreclr/issues/14346
-    getEmitter()->emitIns_R_R(INS_ldaxr, emitTypeSize(treeNode), loadReg, addrReg);
+    getEmitter()->emitIns_R_R(INS_ldaxr, emitActualTypeSize(data), loadReg, addrReg);
```
Comment (sdmaclea) [inline src/jit/codegenarm64.cpp]: We generally use `emitTypeSize` for loads.  Since it does not force the size to a general purpose register size.  

Here it doesn't effect functionality, but I would prefer to change it to be consistent.

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -15290,9 +15290,8 @@ void Compiler::gtExtractSideEffList(GenTreePtr  expr,
         if (oper == GT_XADD)
         {
             expr->SetOperRaw(GT_LOCKADD);
-#ifndef _TARGET_ARM64_
+            assert(genActualType(expr->gtType) == genActualType(expr->gtOp.gtOp2->gtType));
             expr->gtType = TYP_VOID;
```
Comment (sdmaclea) [inline src/jit/gentree.cpp]: I think the importer should be changed to set the type to VOID on import of GT_LOCKADD too.  I think this must be missing unless emitTypeSize for TYP_VOID doesn't assert or return 0.

**Comment by sdmaclea** [comment]
Something between gentree and codegen is changing the type of the addend

On my tip w/o your original change, I added three asserts, that the addend matched the atomic node type.
1. Importer (creation of atomic HIR)
2. gentree (your assert from this patch)
3. codegen (since I still have the TYP_VOID assignment #ifdef out)

This test is hitting the codegen assert on my tip.
`JIT/Regression/JitBlue/GitHub_10714/GitHub_10714/GitHub_10714.sh`

**Comment by sdmaclea** [comment]
gdb from failing test case `JIT/Regression/JitBlue/GitHub_10714/GitHub_10714/GitHub_10714.sh`:
```
Assert failure(PID 44402 [0x0000ad72], Thread: 44402 [0xad72]): Assertion failed 'emitTypeSize(treeNode) == emitTypeSize(data->gtType)' in 'GitHub_10714:Test():int' (IL size 16)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/codegenarm64.cpp Line: 2732
    Image: /home/sdmaclea/coreoverlay/corerun


Thread 1 "corerun" received signal SIGABRT, Aborted.
0x0000ffffb7bb1528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) frame 9
#9  0x0000ffffb31d11b0 in CodeGen::genLockedInstructions (this=0x4d6ce0, treeNode=0x4d9da8) at /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/codegenarm64.cpp:2732
(gdb) print data->gtType
$1 = var_types::TYP_SHORT
(gdb) print treeNode->gtType
$2 = var_types::TYP_INT
(gdb) print data->isContainedIntOrIImmed()
$3 = false
(gdb) print data->OperGet()
$4 = genTreeOps::GT_IND
```

So the addend is from a indirect TYP_SHORT address.  During lowering, there must have been a cast dropped. Since on ARM64 the type of op2 would normally be evaluated with emitActualTypeSize by consumers.

I think GTF_NOVALUE, might be a better way to signal this behavior.

If we want to continue setting GT_LOCKADD->gtType to TYP_VOID, then using `emitActualTypSize` instead of `emitTypSize` would solve the problems with atomics here.

**Comment by CarolEidt** [comment]
> I think GTF_NOVALUE, might be a better way to signal this behavior.

I would like to avoid the use of `GTF_NOVALUE`. In fact, I hope to eventually elimiante it.

> If we want to continue setting GT_LOCKADD->gtType to TYP_VOID, then using emitActualTypSize instead of emitTypSize would solve the problems with atomics here.

I think that's the right approach.

File: src/jit/gentree.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/gentree.cpp]: I think that, theoretically, it is defined to return the data type. It's in `Compiler::gtExtractSideEffList` that it changes it to `TYP_VOID` when its result isn't used. However, I don't know if it ever actually returns a result.

**Comment by CarolEidt** [comment]
@sdmaclea - Do you agree that this is an appropriate and correct fix?
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib - I meant to ping on this, not on the bug.

**Comment by sdmaclea** [comment]
@CarolEidt Thanks, I had to go offline last night due to a household appliance failure

**Comment by sdmaclea** [comment]
@CarolEidt BTW, there may still be an issue for 64 bit atomics if the addend is an indirect small type, when there should be a carry into the high 32 bits.  I would guess the problem exist on all platforms now, but I am not sure.  There is certainly no coverage for this case.

**Comment by CarolEidt** [comment]
> there may still be an issue for 64 bit atomics if the addend is an indirect small type, when there should be a carry into the high 32 bits. I would guess the problem exist on all platforms now, but I am not sure. There is certainly no coverage for this case.

Agreed. I opened #14557 because I think the implementation of the interlocked operations would be cleaner and less error-prone if they took an indirection as their op1. That indirection would hold the correct type. I'll add a note there that we should add better test coverage.
