### PR TITLE
Modify amd64walker to use table based decode

### LINKED ISSUE #25132: Breakpoint changes the output of the program on x64
The output for the execution of a program may change if you add a breakpoint on a specified line.

Repro Steps:
```c#
static void Main(string[] args)
{
    Console.WriteLine(WrapDegrees(-722.5f));
    Console.WriteLine();
}

private static float WrapDegrees(float degrees)
{
    float remainder = Math.Abs(degrees);
    remainder %= 360; // breakpoint here
    return degrees < 0 ? 360 - remainder : remainder;
}
```

Code from: https://gist.github.com/tannergooding/af91efb30215ab360dfb3fe18e58fe36 

1. Add breakpoint at specified line;
2. Target .NET Core 3.0 Preview 4 for x64;
3. Start debugging;
4. Hit breakpoint and continue execution.

Expected output
357.5

Actual output
357.51007

Remarks
* If you don't add any breakpoint (or add any breakpoint as long as the specified line does not have a breakpoint), the output will be the same as expected;
* Unable to reproduce the issue with v3.0.0-preview-27122-01 or older versions (regression);
* Unable to reproduce if targeting x86.

### PR DESCRIPTION
**Pull request by sdmaclea**
Use tables for NativeWalker::DecodeInstructionForPatchSkip()
Also files used to generate the decode tables in doc folder.

Fixes #25132

### CODE REVIEW

File: src/debug/ee/amd64/doc/createOpcodes.cpp [hunk 1]
```diff
@@ -0,0 +1,253 @@
+#include <stdio.h>
```
Comment (noahfalk) [inline src/debug/ee/amd64/doc/createOpcodes.cpp]: 'doc' isn't the sub-directory I'd expect to look in to find these tools. How about 'opcode_gen' or some other name that relates to tables, generation, or disassembly?

File: src/debug/ee/amd64/doc/README.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+The files in this folders were used to create `amd64InstrDecode.h`
```
Comment (noahfalk) [inline src/debug/ee/amd64/doc/README.md]: I think we should add a little more descriptive text about what we are doing here and why we chose this approach. I don't think it will be obvious to everyone what the workflow is doing even if following the steps below does mechanically carry it out.

If there is a high level description of AMD64 assembly that would let someone unfamiliar with its encoding (such as me) understand a little better that would be great, or if the best available explanation is "go read the AMD instruction manual" then a link to the manual and references to the relevant sections would be handy.

File: src/debug/ee/amd64/amd64InstrDecode.h [hunk 3]
```diff
@@ -0,0 +1,10063 @@
...
+    //      I3B      // Instruction includes 3  bytes of immediates
+    //      I4B      // Instruction includes 4  bytes of immediates
+    //      I8B      // Instruction includes 8  bytes of immediates
+    //      Unknown  // Instruction samples did not include a modrm configured to produce RIP addressing
+    //      L        // Flags depend on L bit in encoding.  L_<flagsLTrue>_or_<flagsLFalse>
+    //      W        // Flags depend on W bit in encoding.  W_<flagsWTrue>_or_<flagsWFalse>
+    //      P        // Flags depend on OpSize prefix for encoding.  P_<flagsNoOpSizePrefix>_or_<flagsOpSizePrefix>
+    //      WP       // Flags depend on W bit in encoding and OpSize prefix.  WP_<flagsWTrue>_or__<flagsNoOpSizePrefix>_or_<flagsOpSizePrefix>
+    //      or       // Flag option separator used in W, L, P, and WP above
+    enum InstrForm
```
[the remark this answers is not in the document]
Comment (sdmaclea) [reply src/debug/ee/amd64/amd64InstrDecode.h]: Yeah I chose this encoding with the intent that these would be bytes, but failed to force the enum to use a byte.

File: src/debug/ee/amd64/doc/README.md (hunk 2 above)
Comment (sdmaclea) [reply src/debug/ee/amd64/doc/README.md]: The encoding is kind of complicated.  Citing the manual seems best.  I added a reference to the encoding flow chart and the manual section to the readme.  I think if I try to summarize it I will just create confusion.

**Comment by sdmaclea** [comment]
So far this has fairly simplistic testing.

I tested this fixed #25132.  I also tested I could set a breakpoint on any line in the file without changing results.

I will test this against our internal tests when I get instructions from @hoyosjs

**Comment by tannergooding** [comment]
@sdmaclea, is this going to be backported to 3.0 considered it results in corrupted data when debugging?

**Comment by sdmaclea** [comment]
We thought this was too big a change to meet the 3.0 bar.

**Comment by tannergooding** [comment]
What about 3.1 for the LTS?
