### PR TITLE
Disable few more transparency checks for .net core

### LINKED ISSUE #5975: Security transparency in Docker containers
I understand the security transparency model was disabled in CoreCLR (#1807). However, when using MEF in a Docker container, I'm seeing this:

```
Unhandled Exception: System.MethodAccessException: Attempt to access method System.CodeDom.Compiler.GeneratedCodeAttribute..ctor(System.String, System.String) in violation of security transparency rules failed.
   at System.RuntimeMethodHandle.CheckLinktimeDemands(IRuntimeMethodInfo method, RuntimeModule module, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ConsoleApplication.Program.Main(String[] args)
Aborted (core dumped)
```

This occurs only in the container (works as expected on Windows and Linux), and only when composing types outside the entry assembly:
``` C#
...
using System.Composition.Convention;
using System.Composition.Hosting;
...

var conventions = new ConventionBuilder();
conventions.ForTypesDerivedFrom<IPlugin>()
    .Export<IPlugin>()
    .Shared();

var doesNotThrow = new ContainerConfiguration()
    .WithAssembly(Assembly.GetEntryAssembly(), conventions)
    .CreateContainer(); // no trouble

var assemblies = Directory.GetFiles(AppContext.BaseDirectory, "*.dll")
    .Select(AssemblyLoadContext.GetAssemblyName)
    .Select(Assembly.Load);

var throws = new ContainerConfiguration()
    .WithAssemblies(assemblies, conventions)
    .CreateContainer(); // MethodAccessException
```

A full repro is available at https://github.com/chlowell/container-security-transparency

### PR DESCRIPTION
**Pull request by rahku**
Fixes #5975

### CODE REVIEW

**Comment by rahku** [comment]
PTAL @jkotas

File: src/vm/runtimehandles.cpp [hunk 1]
```diff
@@ -340,7 +340,7 @@ FCIMPL3(void, RuntimeMethodHandle::CheckLinktimeDemands, ReflectMethodObject *pM
 
         if (isDecoratedTargetSecurityTransparent && isAttributeSecurityCritical)
         {
-            if (!DoAttributeTransparencyChecks(pCallee->GetAssembly(), pDecoratedModule->GetAssembly()))
+            if (Security::IsTransparencyEnforcementEnabled() && !DoAttributeTransparencyChecks(pCallee->GetAssembly(), pDecoratedModule->GetAssembly()))
```
Comment (jkotas) [inline src/vm/runtimehandles.cpp]: I would be better (for perf) to this as the very first thing at the start of the method (even before QCALL or HMF frame).

**Comment by jkotas** [comment]
LGTM otherwise
