### PR TITLE
Fix a couple of issues involving assembly loading

### LINKED ISSUE #1187: Assembly.Load(AssemblyLoadContext.GetAssemblyName(@"...")) throws unexpected exception
Hi,
I'm currently trying to port code from full framework 4.6 to DNX Core 5 and I encounter most of my problems with the new reflection API. Here is my problem :

I need to import at run time (dynamically) some assemblies that can be saved anywhere on disk. So the user most specify an absolute path for the assembly to be loaded. In full framework, I used `Assembly.LoadFrom(string asmPath)` method to get the job done. But, after doing some searches on compatibility with DNX Core 5, I understood that it wasn't (yet?) available.

I tried something with `AssemblyName` here is the result :

Empty class to import:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public class Class1
    {
        public Class1()
        {
        }
    }
}
```
Test program :
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Reflection;
using System.Runtime.Loader;

namespace ConsoleApp1
{
    public class Program
    {
        public void Main(string[] args)
        {
            try
            {
                Assembly myAssembly = Assembly.Load(AssemblyLoadContext.GetAssemblyName(@"C:\ClassLibrary1.dll"));
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.ReadLine();
            }

        }
    }
}
```
Now the console output when running `ConsoleApp1` :
`Assembly.Load with a Codebase is not supported on Windows Phone.`

First, error message is probably not up to date since I don't target Windows Phone device (I used `vNext class library` and `vNext console app` in Visual Studio 2015 RC), and I would like to know if `Assembly.LoadFrom(string asmPath)` will be implemented for DNX Core 5 and if not, how can I load assemblies from their absolute (or relative) path on disk ?

Thx !

### LINKED ISSUE #1740: Custom AssemblyLoadContext not used when loading dependencies
When loading an assembly that has additional dependencies in a custom AssemblyLoadContext, the dependencies will be loaded by the TPA binder if they can be found in the same directory as the managed executable.

I can replicate this with CoreRun from coreclr@66b24ad114f991cd882387f1a3bb280c7cd6877f. I  also tested this with dnx (CoreClr-x64-1.0.0-rc1-15838) but I couldn't replicate it there, but it may be possible to if I knew the paths it was using.

My directory tree looks like this:
```
runtime\
  - CoreRun.exe
  - coreclr.dll
  - mscorlib.dll
  - System.*.dll
program\
  - Program.exe
  - Test.dll
  - TestDep.dll
```

The source for the assemblies in the program directory: https://gist.github.com/Rohansi/40770cc6663e04c3a76d 

And I run Program.exe with: `..\runtime\CoreRun.exe Program.exe` or `runtime\CoreRun.exe program\Program.exe`

`CustomLoadContext.Load()` will only be called once when loading Test.dll. If I move Test.dll and TestDep.dll into a lib subdirectory and load from there it will be called for both.

### PR DESCRIPTION
**Pull request by kouvel**
Fixes #1740
- After an assembly is loaded through a custom load context, when its dependencies are being loaded and the dependencies are in an app folder but not on the TPA list, don't search app paths when using the TPA binder, and instead use the default binder for the dependent assembly to load dependencies through the same custom AssemblyLoadContext.

Fixes #1187
- In the AssemblyName created by AssemblyLoadContext.GetAssemblyName(), don't initialize the CodeBase property since it's not in the exposed surface area for .NET Core. If the AssemblyName is passed to Assembly.Load(), note that regardless of the path sent to GetAssemblyName(), default search orders are still used to load the assembly by name. A custom AssemblyLoadContext would need to be used to control where an assembly is loaded from.

- Fixed a couple of error messages that mentioned phone

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k @jkotas

File: src/vm/assemblyname.cpp [hunk 1]
```diff
@@ -85,7 +85,6 @@ FCIMPL1(Object*, AssemblyNameNative::GetFileInformation, StringObject* filenameU
 
     AssemblySpec spec;
     spec.InitializeSpec(TokenFromRid(mdtAssembly,1),pImage->GetMDImport(),NULL,TRUE);
-    spec.SetCodeBase(sUrl);
```
Comment (jkotas) [inline src/vm/assemblyname.cpp]: This fix should be under FEATURE_CORECLR ifdef

Comment (kouvel) [inline src/vm/assemblyname.cpp]: Oh right, done

**Comment by kouvel** [comment]
@dotnet-bot test osx

**Comment by kouvel** [comment]
@dotnet-bot test this please

File: src/binder/clrprivbinderassemblyloadcontext.cpp [hunk 2]
```diff
@@ -160,7 +159,8 @@ HRESULT CLRPrivBinderAssemblyLoadContext::BindUsingPEImage( /* in */ PEImage *pP
             {
                 // The simple name of the assembly being requested to be bound was found in the TPA list.
                 // Now, perform the actual bind to see if the assembly was really in the TPA assembly or not.
-                hr = m_pTPABinder->BindAssemblyByNameWorker(pAssemblyName, &pCoreCLRFoundAssembly);
+                // Don't search app paths when using the TPA binder because the actual binder is using a host assembly resolver.
+                hr = m_pTPABinder->BindAssemblyByNameWorker(pAssemblyName, &pCoreCLRFoundAssembly, true /* excludeAppPaths */);
```
Comment (kouvel) [inline src/binder/clrprivbinderassemblyloadcontext.cpp]: @sergiy-k found that I was passing in the wrong value for the parameter here. Thanks for finding this, fixed.

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by sergiy-k** [comment]
LGTM

**Comment by jkotas** [comment]
LGTM
