### PR TITLE
Fix Arm64 intrinsic lookup

### LINKED ISSUE #23669: [Arm64] HardwareIntrinsics test failures
Probably hidden by the other Arm64 failures (#23577) there are now 4 additional failures. These are:
```
JIT\HardwareIntrinsics\General\NotSupported\NotSupported_ro\NotSupported_ro.cmd
JIT\HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.cmd
JIT\HardwareIntrinsics\General\Vector64_1\Vector64_1_r\Vector64_1_r.cmd
JIT\HardwareIntrinsics\General\Vector64_1\Vector64_1_ro\Vector64_1_ro.cmd
```
This appears to be an off-by-one error here: https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsicArm64.cpp#L113.
Note the extra `- 1` in the x86 case: https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsicxarch.cpp#L60

I'll have a PR up shortly.

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #23669

### CODE REVIEW

**Comment by CarolEidt** [comment]
I also added some JITDUMP output.

**Comment by CarolEidt** [comment]
@tannergooding @dotnet/jit-contrib PTAL

File: src/jit/hwintrinsicArm64.cpp [hunk 1]
```diff
@@ -109,15 +109,17 @@ NamedIntrinsic Compiler::lookupHWIntrinsic(const char* className, const char* me
     NamedIntrinsic result = NI_Illegal;
     if (isa != InstructionSet_NONE)
     {
+        JITDUMP("HW Intrinsic %s.%s: ", className, methodName);
```
Comment (tannergooding) [inline src/jit/hwintrinsicArm64.cpp]: Might be nice to centralize this logging in `Compiler::lookupNamedIntrinsic` in `importer.cpp`? That would allow all named intrinsics to have JITDUMP info and a fallback for not supported/not recognized.

Comment (CarolEidt) [reply src/jit/hwintrinsicArm64.cpp]: Currently that won't really get us what we'd really like because the VM won't even surface the intrinsics for other platforms. I'll add a note to #20379 that we should also unify the `JITDUMP` output for intrinsic recognition.

**Comment by CarolEidt** [comment]
The corefx tests are the ones that are failing in all the PRs, and the arm64 failures are #23577
