### PR TITLE
Fix collectible AssemblyLoadContext weak handle

### LINKED ISSUE #22174: Collectible AssemblyLoadContext sometimes released when not directly referenced in managed code but still in use.
Sometimes, it is possible for a collectible ALC to be GC'd and not finalized while it is still in use. On x86, with the following environment flags, the Interop/ICustomMarshaler/ConflictingNames/MultipleALCs test will fail when trying to get a `Type` from an `Assembly` that was loaded from an unloadable ALC. It seems that the managed ALC object is collected but not finalized after the call to `AssemblyLoadContext.LoadAssemblyFromPath` and before the call to `Assembly.GetType`.

Environment:
```
set COMPlus_GCStress=2
set COMPlus_TieredCompilation=0
set COMPlus_ZapDisable=1
set COMPlus_ReadyToRun=0
```

See #22133 , #22109.

### PR DESCRIPTION
**Pull request by janvorli**
Native runtime keeps short weak handle for collectible AssemblyLoadContext
until the unload time when it gets converted to a strong one. A test
running with gc stress has recently hit a problem caused by the fact
that the weak handle is "short weak" and thus doesn't track
resurrection. Here is what happened:
* The test code has lost reference to the AssemblyLoadContext
* Finalizer of that AssemblyLoadContext was just invoked due to that and
  so the weak short handle was destroyed.
* Native runtime called AssemblyLoadContext.Resolve with the now dead
  handle, the function tried to get the managed object and failed.

The fix is to change the handle type to long weak so that it doesn't get
destroyed before the finalization.

Closes #22174

### CODE REVIEW

File: src/binder/clrprivbinderassemblyloadcontext.cpp [hunk 1]
```diff
@@ -267,7 +267,7 @@ void CLRPrivBinderAssemblyLoadContext::PrepareForLoadContextRelease(INT_PTR ptrM
     // CLRPrivBinderAssemblyLoadContext::ReleaseLoadContext is called.
     OBJECTHANDLE handle = reinterpret_cast<OBJECTHANDLE>(m_ptrManagedAssemblyLoadContext);
     OBJECTHANDLE strongHandle = reinterpret_cast<OBJECTHANDLE>(ptrManagedStrongAssemblyLoadContext);
-    DestroyShortWeakHandle(handle);
+    DestroyLongWeakHandle(handle);
```
Comment (jkotas) [inline src/binder/clrprivbinderassemblyloadcontext.cpp]: Can we assert that the handle is NULL here?

**Comment by jkoritzinsky** [comment]
Thanks @janvorli!

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests please
@dotnet-bot test Windows_NT x64 Release CoreFX Tests please
