### PR TITLE
JIT: fix value numbering to handle GT_NULLCHECK more generally

### LINKED ISSUE #18937: Assert failure in JIT.Methodical.xxobj.ldobj._il_relldobj_V._il_relldobj_V 'arg0VN == VNNormVal(arg0VN)'
Found this regression introduced between [Build #9949 (Jul 13, 2018 11:03:21 AM)](https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/checked_windows_nt/9949/) and [Build #9950 (Jul 13, 2018 1:21:43 PM)](https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/checked_windows_nt/9950/) which corresponds to 

Changes: 
1. JIT: optimize some cases of unused structs (#18819) (commit: dc7492e)
```
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun _il_relldobj_V.exe
               
               Assert failure(PID 10489 [0x000028f9], Thread: 10489 [0x28f9]): Assertion failed 'arg0VN == VNNormVal(arg0VN)' in 'JitTest.Test:Main():int' (IL size 338)
               
                   File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/jit/valuenum.cpp Line: 1010
                   Image: /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
               
               ./_il_relldobj_V.sh: line 244: 10489 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```
Reproduced on Windows and Linux, x64 and arm

### PR DESCRIPTION
**Pull request by AndyAyersMS**
With the advent of #18819 we may now see GT_NULLCHECK nodes with operands
that also can cause exceptions.

Handle this in value numbering.

Closes #18937.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib 

No diffs in the _il_relldobj_V.exe from before #18819.
Don't expect any other diffs; checking now.

**Comment by AndyAyersMS** [comment]
@echesakov can you launch one or more of the Pri1 test legs that you saw failing?

**Comment by echesakovMSFT** [comment]
@dotnet-bot test CentOS7.1 x64 Build and Test
@dotnet-bot test Ubuntu x64 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test

**Comment by AndyAyersMS** [comment]
[OSX failure](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/5642/) looks like an infrastructure issue:
```
/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_prtest/Tools/dotnetcli/sdk/2.1.301/NuGet.targets(114,5): 
error : Failed to retrieve information about 'microsoft.dotnet.buildtools.coreclr' from remote source
```
will retry if everything else passes.

**Comment by AndyAyersMS** [comment]
No PMI diffs on x64 across all pri1 tests. No crossgen diffs for frameworks.

@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test

File: src/jit/valuenum.cpp [hunk 1]
```diff
@@ -7033,13 +7033,17 @@ void Compiler::fgValueNumberTree(GenTree* tree, bool evalAsgLhsInd)
...
-                                            vnStore->VNPExcSetSingleton(
-                                                vnStore->VNPairForFunc(TYP_REF, VNF_NullPtrExc,
-                                                                       tree->gtOp.gtOp1->gtVNPair)));
-                    break;
+                    // Handle case where operand tree also may case exceptions.
+                    ValueNumPair excSet = vnStore->VNPExcSetSingleton(
+                        vnStore->VNPairForFunc(TYP_REF, VNF_NullPtrExc,
+                                               vnStore->VNPNormVal(tree->gtOp.gtOp1->gtVNPair)));
+
+                    excSet         = vnStore->VNPExcSetUnion(excSet, vnStore->VNPExcVal(tree->gtOp.gtOp1->gtVNPair));
```
Comment (briansull) [inline src/jit/valuenum.cpp]: I think that we should declare a new local excSetBoth or similar instead of stomping on the old value of excSet

File: src/jit/valuenum.cpp [hunk 2]
```diff
@@ -7033,13 +7033,17 @@ void Compiler::fgValueNumberTree(GenTree* tree, bool evalAsgLhsInd)
...
                 case GT_NULLCHECK:
+                {
                     // Explicit null check.
-                    tree->gtVNPair =
-                        vnStore->VNPWithExc(ValueNumPair(ValueNumStore::VNForVoid(), ValueNumStore::VNForVoid()),
-                                            vnStore->VNPExcSetSingleton(
-                                                vnStore->VNPairForFunc(TYP_REF, VNF_NullPtrExc,
-                                                                       tree->gtOp.gtOp1->gtVNPair)));
-                    break;
+                    // Handle case where operand tree also may case exceptions.
```
Comment (erozenfeld) [inline src/jit/valuenum.cpp]: Typo: case --> cause

File: src/jit/valuenum.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/valuenum.cpp]: Ok, will fix.

File: src/jit/valuenum.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/valuenum.cpp]: Thanks.

**Comment by AndyAyersMS** [comment]
[OSX testing](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/5647/) now failing with some pal test errors.

Am going to push an update with changes from feedback and ignore OSX if it fails again.
