### PR TITLE
Fix min-opts spill of tree temp large vectors

### LINKED ISSUE #22200: [arm64] Test failed: JIT_Regression._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_sh
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst/97/

**Failed tests:**
JIT_Regression._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_sh

**Log:**
```
JIT_Regression._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_sh [FAIL]
        /n/nReturn code:      1/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/JIT/Regression/Reports/JIT.Regression/JitBlue/GitHub_20657/GitHub_20657/GitHub_20657.output.txt/nRaw output:/nBEGIN EXECUTION
        /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun GitHub_20657.exe
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/JIT/Regression/JitBlue/GitHub_20657/GitHub_20657/GitHub_20657.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(82989,0): at JIT_Regression._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_._JitBlue_GitHub_20657_GitHub_20657_GitHub_20657_sh()
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Even if we're not enregistering local vars, we may have large vectors live across a call that need to be spilled.

Fix #22200

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked jitstressregs8 Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
#22311 Fixed this issue only for the case where we are also enregistering local vars. So, for minopts, or if there are no lclVars, this wasn't kicking in for the tree temps.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping
The failures are all this test:
```
   Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh
```
Failing with:
```
   Unable to find an entry point named 'NativeFunc' in shared library 'FromNativePaths_lib
```

File: src/jit/lsrabuild.cpp [hunk 1]
```diff
@@ -1327,9 +1327,8 @@ void LinearScan::buildInternalRegisterUses()
 VARSET_VALRET_TP
 LinearScan::buildUpperVectorSaveRefPositions(GenTree* tree, LsraLocation currentLoc, regMaskTP fpCalleeKillSet)
 {
-    assert(enregisterLocalVars);
     VARSET_TP liveLargeVectors(VarSetOps::MakeEmpty(compiler));
-    if (!VarSetOps::IsEmpty(compiler, largeVectorVars))
+    if (enregisterLocalVars && !VarSetOps::IsEmpty(compiler, largeVectorVars))
```
Comment (sandreenko) [inline src/jit/lsrabuild.cpp]: Could you please clarify some names, overall we have `variables` and `temps`, `largeVectorVars` refers to `variables`, `enregisterLocalVars` also refers to variables, is it correct? 
Could we have non-empty `largeVectorVars` (that doesn't include temps, only vars) when `enregisterLocalVars ` is `false`? Sound like we can't, then can you move the deleted assert under this condition?

Comment (sandreenko) [reply src/jit/lsrabuild.cpp]: Looks like this function does two things that needs to be split:
1. a function that returns the set of lclVars (excluding temps) that are killed by this node;
2. a function that create special RefPositions for saving the upper half of a set of large vector (including temps).

and the same for `buildUpperVectorRestoreRefPositions`.

If you do not want to split them now, could you please update their headers to include that they not only create re positions but also save/restore vars.

File: src/jit/lsrabuild.cpp [hunk 2]
```diff
@@ -1376,6 +1375,10 @@ LinearScan::buildUpperVectorSaveRefPositions(GenTree* tree, LsraLocation current
 //    currentLoc - The location of the current node
 //    liveLargeVectors - The set of lclVars needing restores (returned by buildUpperVectorSaveRefPositions)
```
Comment (sandreenko) [inline src/jit/lsrabuild.cpp]: another question about names, could you please rename it to `liveLargeVectorsVars`?

File: src/jit/lsrabuild.cpp [hunk 3]
```diff
@@ -2560,13 +2563,16 @@ void LinearScan::BuildDefsWithKills(GenTree* tree, int dstCount, regMaskTP dstCa
...
 #if FEATURE_PARTIAL_SIMD_CALLEE_SAVE
-        if (enregisterLocalVars && ((killMask & RBM_FLT_CALLEE_TRASH) != RBM_NONE))
+        if ((killMask & RBM_FLT_CALLEE_TRASH) != RBM_NONE)
         {
             // Build RefPositions for saving any live large vectors.
             // This must be done after the kills, so that we know which large vectors are still live.
             VarSetOps::AssignNoCopy(compiler, liveLargeVectors,
                                     buildUpperVectorSaveRefPositions(tree, currentLoc + 1, killMask));
-            doLargeVectorRestore = true;
+            if (enregisterLocalVars && !VarSetOps::IsEmpty(compiler, liveLargeVectors))
```
Comment (sandreenko) [inline src/jit/lsrabuild.cpp]: The same comment about adding  `assert(enregisterLocalVars)` under `if`.

**Comment by CarolEidt** [comment]
> Do we have a test for this change?

No we don't have a test for this change. It is generally not easy to find tests for LSRA issues, but the `GitHub_20657` test has already found more than one.

File: src/jit/lsrabuild.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/lsrabuild.cpp]: It would make sense to split out the determination of the live large vector lclVars (including lclVar temps, which are the same as lclVars from the perspective of LSRA) from the building of the RefPositions). I'd prefer to do that as a separate refactor.
Note, though, that this method doesn't actually save or restore anything, it just creates the RefPositions that *may* cause their upper half to be saved & restored, at allocation time, *if* they reside in a callee-save register.

File: src/jit/lsrabuild.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/jit/lsrabuild.cpp]: Currently the lclVar sets are not initialized if `enregisterLocalVars` is false, so we can't move the condition to an assert (i.e. we need to check `enregisterLocalVars` before we test whether the set is empty).

File: src/jit/lsrabuild.cpp (hunk 1 above)
Comment (sandreenko) [reply src/jit/lsrabuild.cpp]: > the determination of the live large vector lclVars (including lclVar temps, which are the same as lclVars from the perspective of LSRA)

Do you mean `liveLargeVectors` that the method returns? We calculate `liveLargeVectors` only under `if (enregisterLocalVars && !VarSetOps::IsEmpty(compiler, largeVectorVars))` as I see.  How can it include lclVar temp when we iterate only through vars? Could you please rename `liveLargeVectors` to `liveLargeVectorsVars` here as well?

Note that the return value is calculated in the first part of this function and the second part does not affect it at all.

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked jitstressregs8 Build and Test
