### PR TITLE
[RyuJIT/ARM32] Implement storing multi-reg/HFA return value at caller

### LINKED ISSUE #12289: [RyuJIT/ARM32] Assertion failed 'resultReg != REG_NA'
Message:
```
Assert failure(PID 3117 [0x00000c2d], Thread: 3117 [0x0c2d]): Assertion failed 'resultReg != REG_NA' in 'CoreFX15913:Main():int' (IL size 25)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/gentree.cpp Line: 17016
```

Tests:
```
JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh
JIT/Regression/JitBlue/CoreFX_15913/CoreFX_15913/CoreFX_15913.sh
JIT/Regression/JitBlue/GitHub_7508/Vector3Test/Vector3Test.sh
JIT/Regression/JitBlue/GitHub_8220/GitHub_8220/GitHub_8220.sh
JIT/SIMD/AbsSqrt_r/AbsSqrt_r.sh
JIT/SIMD/AbsSqrt_ro/AbsSqrt_ro.sh
JIT/SIMD/Ldfld_r/Ldfld_r.sh
JIT/SIMD/MinMax_r/MinMax_r.sh
JIT/SIMD/MinMax_ro/MinMax_ro.sh
JIT/SIMD/Sums_ro/Sums_ro.sh
JIT/SIMD/Sums_r/Sums_r.sh
JIT/SIMD/Vector3_ro/Vector3_ro.sh
JIT/SIMD/Vector3_r/Vector3_r.sh
JIT/SIMD/Vector4_ro/Vector4_ro.sh
JIT/SIMD/Vector4_r/Vector4_r.sh
JIT/SIMD/VectorAbs_ro/VectorAbs_ro.sh
JIT/SIMD/VectorAbs_r/VectorAbs_r.sh
JIT/SIMD/VectorAdd_r/VectorAdd_r.sh
JIT/SIMD/VectorArray_ro/VectorArray_ro.sh
JIT/SIMD/VectorArray_r/VectorArray_r.sh
JIT/SIMD/VectorDiv_ro/VectorDiv_ro.sh
JIT/SIMD/VectorDiv_r/VectorDiv_r.sh
JIT/SIMD/VectorMax_ro/VectorMax_ro.sh
JIT/SIMD/VectorMax_r/VectorMax_r.sh
JIT/SIMD/VectorMin_ro/VectorMin_ro.sh
JIT/SIMD/VectorMin_r/VectorMin_r.sh
JIT/SIMD/VectorMul_ro/VectorMul_ro.sh
JIT/SIMD/VectorMul_r/VectorMul_r.sh
JIT/SIMD/VectorReturn_ro/VectorReturn_ro.sh
JIT/SIMD/VectorReturn_r/VectorReturn_r.sh
JIT/SIMD/VectorSub_ro/VectorSub_ro.sh
JIT/SIMD/VectorSub_r/VectorSub_r.sh
JIT/SIMD/VectorUnused_ro/VectorUnused_ro.sh
JIT/SIMD/VectorUnused_r/VectorUnused_r.sh
```

### PR DESCRIPTION
**Pull request by hqueue**
Fixes #12289

This PR implements `FEATURE_MULTIREG_RET` and `FEATURE_HFA` for struct in RyuJIT/ARM32.

All 34 tests reported in #12289 are passed.

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -16986,7 +16986,7 @@ regNumber ReturnTypeDesc::GetABIReturnReg(unsigned idx)
         }
     }
 
-#elif defined(_TARGET_X86_) || defined(_TARGET_ARM_)
+#elif defined(_TARGET_X86_)
```
Comment (BruceForstall) [inline src/jit/gentree.cpp]: Can you delete this part of the function comment:
```
// Notes:
//     Right now this is implemented only for x64 Unix
//     and yet to be implemented for other multi-reg return
//     targets (Arm64/Arm32/x86).
//
// TODO-ARM:   Implement this routine to support HFA returns.
// TODO-X86:   Implement this routine to support long returns.
```
since it seems to be obsolete.

**Comment by BruceForstall** [comment]
Looks fine to me.

**Comment by hqueue** [comment]
Please take a look. Thanks!
