### PR TITLE
Throw an exception when passing strings by-value as out parameters.

### LINKED ISSUE #21506: Interop\StringMarshalling\LPTSTR\LPTSTRTest Marshal_InOut modifies managed string inline
This is another case of a test that modifies the passed in string inline and thus breaks string interning. This test needs to be fixed or removed.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Block users from adding an `[Out]` attribute on strings and modifying them in place to avoid causing crashes with unloadability and string interning. Instead of allowing it, we'll throw a `MarshalDirectiveException`. Fixes #21506.

Blocked on dotnet/corefx#34091

### CODE REVIEW

**Comment by janvorli** [comment]
GitHub still thinks it is binary. Ok, I've just fetched the contents of the file and diffed it locally.

**Comment by janvorli** [comment]
The linux-musl x64 build now fails:
```
15:34:33 /mnt/j/workspace/dotnet_coreclr/master/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/vm/ilmarshalers.h:1978:23: error: 'GetNativeType' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
15:34:33     virtual LocalDesc GetNativeType();
15:34:33                       ^
15:34:33 /mnt/j/workspace/dotnet_coreclr/master/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/vm/ilmarshalers.h:1293:23: note: overridden virtual function is here
15:34:33     virtual LocalDesc GetNativeType() = 0;
```
That's because you have added the SupportsArgumentMarshal method with `override` and so the whole class now requires usage of override (clang's idiosyncracy). Could you please remove the `override` and add `virtual` to it?

**Comment by jkoritzinsky** [comment]
Will do.

File: src/vm/ilmarshalers.h [hunk 1]
```diff
@@ -1962,6 +1962,18 @@ class ILWSTRMarshaler : public ILMarshaler
     }
 #endif // _DEBUG
 
+    
+    virtual bool SupportsArgumentMarshal(DWORD dwMarshalFlags, UINT* pErrorResID)
+    {
+        if (IsOut(dwMarshalFlags) && !IsByref(dwMarshalFlags))
```
Comment (AaronRobinsonMSFT) [inline src/vm/ilmarshalers.h]: What about if marked by `out`? Does the `IsByRef()` return true for both the `ref` and `out` keywords? Based on this usage I am also assuming that `IsOut()` is for the attribute _not_ the keyword. Is that correct?

Comment (jkoritzinsky) [reply src/vm/ilmarshalers.h]: At a metadata level there's no difference between a `[Out] ref` and `out`. `IsByRef` returns true for both `ref` and `out` keywords. So, this check is only true for an `[Out]` by value, not `[Out] ref` or `out`.

File: tests/src/Interop/StringMarshalling/LPSTR/LPSTRTest.cs [hunk 2]
```diff
@@ -192,10 +192,19 @@ public static int Main(string[] args)
         }
 
         #region ReversePinvoke
-        DelMarshal_InOut d1 = new DelMarshal_InOut(Call_DelMarshal_InOut);
-        if (!PInvokeDef.RPinvoke_DelMarshal_InOut(d1, "ň"))
+        bool inOutByValueThrows = false;
+        try
         {
-            ReportFailure("Method RPinvoke_DelMarshal_InOut[Managed Side],Return value is false");
+            DelMarshal_InOut d1 = new DelMarshal_InOut(Call_DelMarshal_InOut);
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/StringMarshalling/LPSTR/LPSTRTest.cs]: Can we use `Assert.Throws<>()`?

**Comment by jkoritzinsky** [comment]
@dotnet-bot test this please.

File: tests/src/Interop/StringMarshalling/LPSTR/LPSTRTest.cs (hunk 2 above)
Comment (jkoritzinsky) [reply tests/src/Interop/StringMarshalling/LPSTR/LPSTRTest.cs]: I can re-write the tests to use the `Assert` infrastructure we have. Although I'd rather do that in a separate PR to keep this one focused on the string marshalling change.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test this please

**Comment by jkoritzinsky** [comment]
It looks like some portions of `System.Management` rely on the current behavior. I'll need to go update them before we can merge this in.

See: https://github.com/dotnet/corefx/blob/784bd1b648dd5a69e10d6c22067c42088aaca90b/src/System.Management/src/System/Management/ManagementPath.cs#L324-L325 and https://github.com/dotnet/corefx/blob/fcea0a593a8b198d7ae741dcb80345ea2b129fe0/src/System.Management/src/System/Management/InteropClasses/WMIInterop.cs#L966

File: tests/src/Interop/COM/ServerContracts/Server.Contracts.cs [hunk 3]
```diff
@@ -146,7 +146,7 @@ public interface IStringTesting
 
         void Reverse_LPWStr_Out([MarshalAs(UnmanagedType.LPWStr)] string a, [MarshalAs(UnmanagedType.LPWStr)] out string b);
 
-        void Reverse_LPWStr_OutAttr([MarshalAs(UnmanagedType.LPWStr)] string a, [Out][MarshalAs(UnmanagedType.LPWStr)] string b);
+        void Reverse_LPWStr_OutAttr([MarshalAs(UnmanagedType.LPWStr)] string a, [MarshalAs(UnmanagedType.LPWStr)] string b);
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/COM/ServerContracts/Server.Contracts.cs]: The name is wrong now. Should this entirely be removed? I was under the impression we should ensure this scenario properly gets an exception thrown.

Comment (AaronRobinsonMSFT) [reply tests/src/Interop/COM/ServerContracts/Server.Contracts.cs]: Also the other native contract now need to updated.

Comment (jkoritzinsky) [reply tests/src/Interop/COM/ServerContracts/Server.Contracts.cs]: Yeah I'll change this to check for the exception.

File: tests/src/Interop/COM/NETClients/Primitives/StringTests.cs [hunk 4]
```diff
@@ -191,8 +191,7 @@ private void Marshal_LPWString()
                 Assert.AreEqual(expected, actual);
 
                 actual = local;
-                this.server.Reverse_LPWStr_OutAttr(local, actual); // No-op for strings
-                Assert.AreEqual(local, actual);
+                Assert.Throws<MarshalDirectiveException>( () => this.server.Reverse_LPWStr_OutAttr(local, actual));
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/COM/NETClients/Primitives/StringTests.cs]: Please also update the managed implementation of `Reverse_LPWStr_OutAttr()` to throw an exception. Or at least documented as desired.

File: src/vm/ilmarshalers.cpp [hunk 5]
```diff
@@ -252,25 +252,56 @@ LocalDesc ILWSTRMarshaler::GetManagedType()
...
+    EmitCheckManagedStringLength(pslILEmit);
+    
+    // static void System.String.InternalCopy(String src, IntPtr dest,int len)
+    pslILEmit->EmitCALL(METHOD__STRING__INTERNAL_COPY, 3, 0);
+    pslILEmit->EmitLabel(pNullRefLabel);
 }
 
 void ILWSTRMarshaler::EmitConvertSpaceNativeToCLR(ILCodeStream* pslILEmit)
 {
     LIMITED_METHOD_CONTRACT;
```
Comment (jkoritzinsky) [inline src/vm/ilmarshalers.cpp]: @AaronRobinsonMSFT quick question for you:

If the user were to have a Reverse P/Invoke or managed COM signature with a parameter `[Out] string str`, should we marshal the native value to that `str` parameter during the native->managed call? Or should we only do it in the case of an `[In]` attribute being present or no attributes being present? The code in this PR currently requires an `[In]` attribute to be present.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

File: src/vm/ilmarshalers.cpp [hunk 6]
```diff
@@ -252,25 +252,60 @@ LocalDesc ILWSTRMarshaler::GetManagedType()
 void ILWSTRMarshaler::EmitConvertSpaceCLRToNative(ILCodeStream* pslILEmit)
 {
     LIMITED_METHOD_CONTRACT;
-    UNREACHABLE_MSG("Should be in-only and all other paths are covered by the EmitConvertSpaceAndContents* paths");
+    UNREACHABLE_MSG("All paths to this function are covered by the EmitConvertSpaceAndContents* paths");
```
Comment (AaronRobinsonMSFT) [inline src/vm/ilmarshalers.cpp]: This line asserts right?

Comment (jkoritzinsky) [reply src/vm/ilmarshalers.cpp]: Yep.

**Comment by janvorli** [comment]
@AaronRobinsonMSFT I've just found this PR from last December was not merged in yet. Since I am not familiar with the marshalling code, I don't feel confident enough to approve the change. Could you please do that?

**Comment by jkoritzinsky** [comment]
@AaronRobinsonMSFT I've already updated the docs to advise to not do this, but I'll go an add an update to that saying that it is disallowed in .NET Core 3.0+.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test this please

**Comment by janvorli** [comment]
I am trying to run the build on my local Alpine to see if I can find the real culprit.

**Comment by janvorli** [comment]
@dotnet-bot test Linux-musl x64 Debug Build please

File: tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp [hunk 7]
```diff
@@ -33,6 +33,20 @@ extern "C" LPWSTR ReturnErrString()
 }
 
 //Test Method1
+extern "C" DLL_EXPORT LPWSTR Marshal_In(/*[In]*/LPWSTR s)
+{
+    //Check the Input
+    size_t len = wcslen(s);
```
Comment (janvorli) [inline tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp]:
```suggestion
    size_t len = TP_slen(s);
```

File: tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp [hunk 8]
```diff
@@ -33,6 +33,20 @@ extern "C" LPWSTR ReturnErrString()
...
+
+    if((len != lenstrManaged)||(wmemcmp(s,(WCHAR*)strManaged,len)!=0))
```
Comment (janvorli) [inline tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp]:
```suggestion
    if((len != lenstrManaged)||(TP_wmemcmp(s,(WCHAR*)strManaged,len)!=0))
```

File: tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp (hunk 7 above)
Comment (janvorli) [reply tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp]: I have found what was making the musl CI legs to fail. You have recently modified the tests to use `TP_xxx` functions instead of wide string ones redefined to use char16_t. But since this PR predates this change, it was still using the redefined wide string functions. Alpine seems to be the only Linux where it causes the build to fail for some reason.

Comment (jkoritzinsky) [reply tests/src/Interop/StringMarshalling/LPTSTR/LPTSTRTestNative.cpp]: I don't know how I missed that... Thanks for your help!
