### PR TITLE
Fix x86 only ICastable feature bug. When we call ICastable.IsInstance…

### LINKED ISSUE #4739: ICastable interop test failure under x86
Simply run Interop\ICastable\Castable test under x86 RyuJIT using the .cmd file after setting CORE_ROOT - this is what I'm getting:

        Assert failure(PID 22548 [0x00005814], Thread: 7668 [0x1df4]): Consistency check failed: AV in clr at
  this callstack:
        ------
        CORECLR! JIT_IsInstanceOfInterface + 0x8 (0x0ff51b68)
        MSCORLIB.NI! <no symbol> + 0x0 (0x091e70ca)
        MSCORLIB.NI! <no symbol> + 0x0 (0x091e6e71)
        <no module>! <no symbol> + 0x0 (0x00720c74)
        CORECLR! CallDescrWorkerInternal + 0x34 (0x0ffd5c41)
        CORECLR! CallDescrWorker + 0x127 (0x1036f8b7)
        CORECLR! CallDescrWorkerWithHandler + 0x205 (0x1036fb45)
        CORECLR! DispatchCallSimple + 0x1A2 (0x10370e62)
        CORECLR! ObjIsInstanceOf + 0x3AA (0x1015a5ea)
        CORECLR! JITutil_IsInstanceOfAny + 0x23F (0x1015f42f)
        CORECLR! JITutil_IsInstanceOfInterface + 0x116 (0x1015f766)
        <no module>! <no symbol> + 0x0 (0x007206a7)
        CORECLR! CallDescrWorkerInternal + 0x34 (0x0ffd5c41)
        CORECLR! CallDescrWorker + 0x127 (0x1036f8b7)
        CORECLR! CallDescrWorkerWithHandler + 0x205 (0x1036fb45)
        CORECLR! MethodDescCallSite::CallTargetWorker + 0xAA7 (0x10370637)
        CORECLR! MethodDescCallSite::Call_RetArgSlot + 0xC8 (0x100c12c8)
        CORECLR! ``RunMain'::`29'::__Body::Run'::`5'::__Body::Run + 0x1BF (0x1031a77f)
        CORECLR! `RunMain'::`29'::__Body::Run + 0xA0 (0x1031a9f0)
        -----
        .AV on tid=0x1df4 (7668), cxr=0065CC94, exr=0065CC44
        FAILED: false

        CORECLR! CHECK::Trigger + 0x30A (0x0fe923ca)
        CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x28E (0x10089d8e)
        CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x87 (0x10089917)
        CORECLR! CLRVectoredExceptionHandler + 0x1DC (0x1008986c)
        CORECLR! CLRVectoredExceptionHandlerShim + 0x15B (0x1008a04b)
        NTDLL! RtlLoadString + 0x217 (0x7711fe07)
        NTDLL! RtlUnwind + 0x1B6 (0x77124136)
        NTDLL! KiUserExceptionDispatcher + 0xF (0x77138e7f)
        MSCORLIB.NI! <no symbol> + 0x0 (0x091e70ca)
        MSCORLIB.NI! <no symbol> + 0x0 (0x091e6e71)
            File: d:\github\coreclr\src\vm\excep.cpp Line: 8141
            Image: D:\GitHub\coreclr\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe

### PR DESCRIPTION
**Pull request by yizhang82**
…OfInterface, we treat RuntimeTypeHandle as a OBJECTREF, which is incorrect as-per x86 calling convention since RuntimeTypehandle is a struct that contains a RuntimeType ref field and needs to be passed in stack. Our VM simple call helpers CALL_MANAGED_METHOD doesn't handle this correctly (it does the simple thing that always assume all the arguments are passed in register first). I'm fixing this by using a static method that takes RuntimeType instead of RuntimeTypeHandle, then convert it to RuntimeTypehandle.

Fix #4739

### CODE REVIEW

**Comment by yizhang82** [comment]
If I have more time, I might try not using the CALL_MANAGED_METHOD, and use Call_RetBool variant instead. I just looked at the CallTargetWorker/ArgIterator and it seems to be handle x86 calling convention correctly, but I decided to stick with my current version for now (it's safer and there are less chance of messing up with GC_PROTECT and introduce GC holes...) and we can always switch the implementation later if it is not ideal. ICastable performance isn't critical yet.
@BruceForstall @jkotas @tijoytom PTAL.

File: src/vm/methodtable.cpp [hunk 1]
```diff
@@ -805,8 +805,8 @@ PTR_MethodTable InterfaceInfo_t::GetApproxMethodTable(Module * pContainingModule
     {
         GCStress<cfg_any>::MaybeTrigger();
 
-        // Make call to obj.GetImplType(interfaceTypeObj)
-        MethodDesc *pGetImplTypeMD = pServerMT->GetMethodDescForInterfaceMethod(MscorlibBinder::GetMethod(METHOD__ICASTABLE__GETIMPLTYPE));
+        // Make call to ICastableHelpers.GetImplType(obj, interfaceTypeObj)
+        MethodDesc *pGetImplTypeMD = MscorlibBinder::GetMethod(METHOD__ICASTABLEHELPERS__GETIMPLTYPE);
```
Comment (jkotas) [inline src/vm/methodtable.cpp]: It should be just `PREPARE_NONVIRTUAL_CALLSITE(METHOD__ICASTABLEHELPERS__GETIMPLTYPE)`

File: src/vm/virtualcallstub.cpp [hunk 2]
```diff
@@ -2277,8 +2277,8 @@ VirtualCallStubManager::Resolver(
         // It allows objects that implement ICastable to mimic behavior of other types. 
         MethodTable * pTokenMT = GetTypeFromToken(token);
 
-        // Make call to obj.GetImplType(interfaceTypeObj)
-        MethodDesc *pGetImplTypeMD = pMT->GetMethodDescForInterfaceMethod(MscorlibBinder::GetMethod(METHOD__ICASTABLE__GETIMPLTYPE));
+        // Make call to ICastableHelpers.GetImplType(this, interfaceTypeObj)
+        MethodDesc *pGetImplTypeMD = MscorlibBinder::GetMethod(METHOD__ICASTABLEHELPERS__GETIMPLTYPE);
```
Comment (jkotas) [inline src/vm/virtualcallstub.cpp]: Same here

**Comment by jkotas** [comment]
> use Call_RetBool variant instead

This one is not straightforward either. You would need to use `CallWithValueTypes_RetBoot` that has special rules associated with it as well. It is best to avoid valuetypes in signatures of reverse FCalls like you have done.

File: src/vm/methodtable.cpp (hunk 1 above)
Comment (yizhang82) [inline src/vm/methodtable.cpp]: Thanks. That one is indeed better/faster. Fixed

**Comment by yizhang82** [comment]
@jkotas Thanks. That's what I suspected as well :)
