### PR TITLE
[x86/Linux] Port RtlVirtualUnwind

### LINKED ISSUE #8887: [x86/Linux] Support Simple Exception Catch
I attempted to execute the following program with x86/Linux port:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            Console.WriteLine("Hello World!");
            throw new ArgumentException();
        }
        catch (Exception e)
        {
            Console.WriteLine("Caught");
        }
    }
}
```

CoreCLR currently shows the following assert failure for the above example:
```
Assert failure(PID 19154 [0x00004ad2], Thread: 19154 [0x4ad2]): iUnwindInfo < GetNumberOfUnwindInfos()
    File: /home/parjong/projects/dotnet/coreclr/src/vm/codeman.h Line: 342
    Image: /root/dotnet-test/overlay/current/corerun
```

### PR DESCRIPTION
**Pull request by parjong**
This commit (partially) ports RtlVirtualUnwind as a step to resolve #8887.

### CODE REVIEW

**Comment by parjong** [comment]
This PR depends on #8889, and thus we should merge this after merging #8889.

File: src/inc/regdisp.h [hunk 1]
```diff
@@ -435,10 +435,20 @@ inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pC
 
     pRD->ctxPtrsOne.Lr = &pctx->Lr;
 #elif defined(_TARGET_X86_) // _TARGET_ARM_
+    pRD->pEdi = &(pctx->Edi);
```
Comment (janvorli) [inline src/inc/regdisp.h]: This won't work for the stack walking with WIN64EXCEPTIONS. When WIN64EXCEPTIONS are defined, the stack walking uses pCurrentContextPointers and doesn't know anything about the pEsi, pEbx etc. So while the unwinder would store the context pointers in these, the pCurrentContext would always just point to the context structure instead of the real location where the register value came from.
What I believe you need to do instead is to remove the setting of the pEsi etc here and then in the OOPStackUnwinderX86::VirtualUnwind set the pRD->pEsi etc to the corresponding values from the pCurrentContext before calling the CodeManager::UnwindStackFrame. And right after calling them, copy them from the RegDisplay::pEsi etc to the corresponding members of the pCurrentContext.
Also, you need to do that only for EDI, ESI, EBX and EBP. The CodeManager::UnwindStackFrame doesn't update any others. These are the only callee saved registers.

Also, the CopyRegDisplay needs to be modified so that it uses the code path that's now for non-x86 targets for x86 on Linux too.

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test please

File: src/unwinder/i386/unwinder_i386.cpp [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+#undef CALLEE_SAVED_REGISTER
+    }
+    else
+    {
+#define CALLEE_SAVED_REGISTER(reg) rd.p##reg = NULL;
+        ENUM_CALLEE_SAVED_REGISTERS();
+#undef CALLEE_SAVED_REGISTER
+    }
+
+    if ( rd.pEbp == NULL )
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.cpp]: A nit - can you please remove extra space after `(` and before `)` here?

File: src/unwinder/i386/unwinder_i386.cpp [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+    rd.ControlPC = (PCODE)(ContextRecord->Eip);
+    rd.PCTAddr   = (UINT_PTR)&(ContextRecord->Eip);
+
+    CodeManState    codeManState;
+    codeManState.dwIsSet = 0;
+
+    EECodeInfo      codeInfo;
+    codeInfo.Init((PCODE) ControlPc);
+
+    if ( !UnwindStackFrame(&rd, &codeInfo, UpdateAllRegs, &codeManState, NULL) )
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.cpp]: A nit - can you please remove extra space after `(` and before `)` here?

File: src/unwinder/i386/unwinder_i386.cpp [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+    {
+      return HRESULT_FROM_WIN32(ERROR_READ_FAULT);
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.cpp]: A nit - wrong indentation

File: src/unwinder/i386/unwinder_i386.cpp [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+    __in _PIMAGE_RUNTIME_FUNCTION_ENTRY FunctionEntry,
+    __inout PCONTEXT ContextRecord,
+    __out PVOID *HandlerData,
+    __out PDWORD EstablisherFrame,
+    __inout_opt PKNONVOLATILE_CONTEXT_POINTERS ContextPointers,
+    __deref_opt_out_opt PEXCEPTION_ROUTINE *HandlerRoutine
+    )
+{
+    *EstablisherFrame   = ContextRecord->Esp;
+    *HandlerRoutine     = NULL;
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.cpp]: The HandlerRoutine is an optional pointer, based on the annotation (__deref_opt_out_opt). Can you please wrap the assignment in check it is not NULL?

File: src/vm/eetwain.cpp [hunk 6]
```diff
@@ -3884,21 +3884,11 @@ bool UnwindEbpDoubleAlignFrame(
...
- *  callee-unsaved registers are trashed.
- *  Returns success of operation.
- */
-
-bool EECodeManager::UnwindStackFrame(PREGDISPLAY     pContext,
-                                     EECodeInfo     *pCodeInfo,
-                                     unsigned        flags,
-                                     CodeManState   *pState,
-                                     StackwalkCacheUnwindInfo  *pUnwindInfo /* out-only, perf improvement */)
+bool UnwindStackFrame(PREGDISPLAY     pContext,
```
Comment (janvorli) [inline src/vm/eetwain.cpp]: I am not sure I understand why you have moved this function out of the EECodeManager and then just call it from there.

File: src/vm/eetwain.cpp [hunk 7]
```diff
@@ -3991,6 +3981,29 @@ bool EECodeManager::UnwindStackFrame(PREGDISPLAY     pContext,
...
+ *  Returns success of operation.
+ */
+
+bool EECodeManager::UnwindStackFrame(PREGDISPLAY     pContext,
+                                     EECodeInfo     *pCodeInfo,
+                                     unsigned        flags,
+                                     CodeManState   *pState,
+                                     StackwalkCacheUnwindInfo  *pUnwindInfo /* out-only, perf improvement */)
+{
+    return UnwindStackFrame(pContext, pCodeInfo, flags, pState, pUnwindInfo);
```
Comment (janvorli) [inline src/vm/eetwain.cpp]: I believe this creates an infinite loop, since it would call itself instead of the function.

File: src/vm/eetwain.cpp (hunk 6 above)
Comment (parjong) [inline src/vm/eetwain.cpp]: There is a case that StackWalker directly calls ``EECodeManager::UnwindStackFrame``, but this implementation does not update ``WIN64EXCEPTIONS``-related fields (which results in unwind failure).

File: src/vm/eetwain.cpp (hunk 7 above)
Comment (parjong) [inline src/vm/eetwain.cpp]: You're right... I'll fix it.

File: src/unwinder/i386/unwinder_i386.h [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+        __in DWORD ControlPc,
+        __in _PIMAGE_RUNTIME_FUNCTION_ENTRY FunctionEntry,
+        __inout PCONTEXT ContextRecord,
+        __out PVOID *HandlerData,
+        __out PDWORD EstablisherFrame,
+        __inout_opt PKNONVOLATILE_CONTEXT_POINTERS ContextPointers,
+        __deref_opt_out_opt PEXCEPTION_ROUTINE *HandlerRoutine);
+
+private:
+    static HRESULT UnwindPrologue(
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.h]: It looks like the UnwindPrologue and GetEstabliserFrame can be removed since they are not even implemented.

File: src/vm/eetwain.cpp [hunk 9]
```diff
@@ -3991,6 +3981,29 @@ bool EECodeManager::UnwindStackFrame(PREGDISPLAY     pContext,
...
+ *  Returns success of operation.
+ */
+
+bool EECodeManager::UnwindStackFrame(PREGDISPLAY     pContext,
+                                     EECodeInfo     *pCodeInfo,
+                                     unsigned        flags,
+                                     CodeManState   *pState,
+                                     StackwalkCacheUnwindInfo  *pUnwindInfo /* out-only, perf improvement */)
+{
+    return UnwindStackFrameEx(pContext, pCodeInfo, flags, pState, pUnwindInfo);
```
Comment (janvorli) [inline src/vm/eetwain.cpp]: The "Ex" seems little strange since the standalone function is not an extended version. You could have kept the same name and just classify it by "::" to indicate that the global version should be called here:
`return ::UnwindStackFrame(pContext, pCodeInfo, flags, pState, pUnwindInfo);`
Would you mind changing it that way?

File: src/unwinder/i386/unwinder_i386.cpp [hunk 10]
```diff
@@ -0,0 +1,206 @@
...
+    __out PVOID *HandlerData,
+    __out PDWORD EstablisherFrame,
+    __inout_opt PKNONVOLATILE_CONTEXT_POINTERS ContextPointers,
+    __deref_opt_out_opt PEXCEPTION_ROUTINE *HandlerRoutine
+    )
+{
+    *EstablisherFrame   = ContextRecord->Esp;
+    if (HandlerRoutine != NULL)
+    {
+        *HandlerRoutine     = NULL;
```
Comment (janvorli) [inline src/unwinder/i386/unwinder_i386.cpp]: One last nit - can you please normalize the spacing in this function? What I mean is to ensure that there is just one space at each side of the `=` and also one space between a type and variable in variable declarations.

**Comment by parjong** [comment]
@janvorli Is there any issues with GC? I recently observed some randome failures on some GC testcases.

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by janvorli** [comment]
@parjong what were the failing tests?

**Comment by parjong** [comment]
@janvorli Oops, I restarted the test without recording failed tests. I'll let you know when I see it again.

**Comment by parjong** [comment]
@janvorli Ubuntu x64 Checked Build and Test failed with the following failure:
```
FAILED   - GC/Scenarios/DoublinkList/doublinkgen/doublinkgen.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun doublinkgen.exe
               Test should return with ExitCode 100 ...
               ./doublinkgen.sh: line 138:  7818 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" doublinkgen.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```
It seems that the current PR should not affect x64/Linux port, but it failed. Could you let me know if you have any clue?

**Comment by janvorli** [comment]
@parjong this test is known to be failing occassionaly. See #6574 .
