### PR TITLE
[Arm64] Fix LowerVirtualStubCall reg allocation

### LINKED ISSUE #15143: [Arm64/Unix] 85% test fails
I am seeing ~100%~ 85% test fails on this tip ` 7fe84b111b`

Looking at first few failures, this assert is firing

```
Assert failure(PID 15614 [0x00003cfe], Thread: 15614 [0x3cfe]): pImportSection != NULL
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/virtualcallstub.cpp Line: 1252
```

Last known passing tip `f47e2640cd`

@dotnet/jit-contrib @dotnet/arm64-contrib

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #15143 

@jkotas @BruceForstall PTAL

@dotnet/jit-contrib @dotnet/arm64-contrib @janvorli FYI

### CODE REVIEW

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -4184,8 +4184,16 @@ GenTree* Lowering::LowerVirtualStubCall(GenTreeCall* call)
...
-#if !defined(_TARGET_UNIX_) && !defined(_TARGET_ARM_)
+#if !defined(_TARGET_UNIX_) && !defined(_TARGET_ARM_) && !defined(_TARGET_ARM64_)
             indir->gtRegNum = REG_JUMP_THUNK_PARAM;
+#elif defined(_TARGET_ARM64_)
+            // Prevent indir->gtRegNum from colliding with addr->gtRegNum
+            indir->gtRegNum = REG_JUMP_THUNK_PARAM;
+
+            // Sanity checks
+            assert(addr->gtRegNum != indir->gtRegNum);                  // indir and addr registers must be different
+            assert((RBM_JUMP_THUNK_PARAM & RBM_ARG_REGS) == 0);         // Not an argument register
```
Comment (BruceForstall) [inline src/jit/lower.cpp]: you could use static_assert_no_msg here

Comment (sdmaclea) [reply src/jit/lower.cpp]: Done

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -4184,8 +4184,17 @@ GenTree* Lowering::LowerVirtualStubCall(GenTreeCall* call)
...
 // TODO: specifying register probably unnecessary for other platforms, too.
-#if !defined(_TARGET_UNIX_) && !defined(_TARGET_ARM_)
+#if !defined(_TARGET_UNIX_) && !defined(_TARGET_ARM_) && !defined(_TARGET_ARM64_)
             indir->gtRegNum = REG_JUMP_THUNK_PARAM;
+#elif defined(_TARGET_ARM64_)
+            // Prevent indir->gtRegNum from colliding with addr->gtRegNum
+            indir->gtRegNum = REG_JUMP_THUNK_PARAM;
+
+            // Sanity checks
+            assert(addr->gtRegNum != indir->gtRegNum); // indir and addr registers must be different
```
Comment (CarolEidt) [inline src/jit/lower.cpp]: I think this would be clearer if you kept the assignment to `indir->gtRegNum` as common code, and then added the asserts for ARM64 only.
I don't really know what the special cases are about, e.g. why the check below for `CORINFO_CORERT_ABI`, but as @BruceForstall pointed out, this needs general cleanup, so I'm not going to press for a minor clarification.
