### PR TITLE
Uses initialized unw_context_t instead of uninitialized one

### LINKED ISSUE #4404: [ARM32] System.AccessViolationException during exception handling
On ARM32, CoreCLR currently shows unexpected behavior for the following code:
```csharp
using System;

namespace ConsoleApplication { public class Program {

  public static void Begin()      { Console.WriteLine("BEGIN"); }
  public static void AfterTry()   { Console.WriteLine("AFTER TRY"); }
  public static void AfterCalc()  { Console.WriteLine("AFTER CALC"); }
  public static void AfterCatch() { Console.WriteLine("AFTER CATCH"); }
  public static void End()        { Console.WriteLine("END"); }

  public static void Main(string[] args) {
    Begin();

    try {
      AfterTry();

      checked
      {
        byte src = 1 + byte.MaxValue / 2;

        AfterCalc();

        byte res = (byte)( src + src );
      }
    } catch (System.OverflowException) {
      AfterCatch();
    }

    End();
  }

} }
```

When running the above code, CoreCLR shows the following outputs:
```
BEGIN
AFTER TRY
AFTER CALC

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ConsoleApplication.Program.Main(String[] args)
```

The normal behavior would be the following:
```
BEGIN
AFTER TRY
AFTER CALC
AFTER CATCH
END
```

### PR DESCRIPTION
**Pull request by parjong**
Fix #4404

### CODE REVIEW

File: src/pal/src/exception/seh-unwind.cpp [hunk 1]
```diff
@@ -96,30 +123,6 @@ static void WinContextToUnwindCursor(CONTEXT *winContext, unw_cursor_t *cursor)
...
-    context.regs[7] = winContext->R7;
-    context.regs[8] = winContext->R8;
-    context.regs[9] = winContext->R9;
-    context.regs[10] = winContext->R10;
-    context.regs[11] = winContext->R11;
-    context.regs[12] = 0;
-    context.regs[13] = winContext->Sp;
-    context.regs[14] = winContext->Lr;
-    context.regs[15] = winContext->Pc;
-    unw_init_local(cursor, &context);
```
Comment (myungjoo) [inline src/pal/src/exception/seh-unwind.cpp]: You still need to do unw_init_local, which initializes the `cursor` correctly.

File: src/pal/src/exception/seh-unwind.cpp [hunk 2]
```diff
@@ -85,6 +85,33 @@ static void WinContextToUnwindContext(CONTEXT *winContext, unw_context_t *unwCon
...
+    unwContext->regs[8] = winContext->R8;
+    unwContext->regs[9] = winContext->R9;
+    unwContext->regs[10] = winContext->R10;
+    unwContext->regs[11] = winContext->R11;
+    unwContext->regs[12] = 0;
+    unwContext->regs[13] = winContext->Sp;
+    unwContext->regs[14] = winContext->Lr;
+    unwContext->regs[15] = winContext->Pc;
+#endif    
+}
```
Comment (myungjoo) [inline src/pal/src/exception/seh-unwind.cpp]: Why not do this inside `WinContextToUnwindCursor` ?

File: src/pal/src/exception/seh-unwind.cpp [hunk 3]
```diff
@@ -251,6 +254,11 @@ BOOL PAL_VirtualUnwind(CONTEXT *context, KNONVOLATILE_CONTEXT_POINTERS *contextP
         return FALSE;
     }
 #endif
+
+#if !UNWIND_CONTEXT_IS_UCONTEXT_T
+    UpdateUnwindContextWithWinContext(context, &unwContext);
+#endif
+
```
Comment (myungjoo) [inline src/pal/src/exception/seh-unwind.cpp]: Please refactor.

File: src/pal/src/exception/seh-unwind.cpp (hunk 2 above)
Comment (parjong) [inline src/pal/src/exception/seh-unwind.cpp]: ``WinContextToUnwindCursor`` takes ``unw_cursor_t`` rather than ``unw_context_t``. We need to update the existing ``unw_context_t``. I think that it would be better to have another function responsible to update ``unw_context_t`` (instead of taking ``unw_context_t`` as an extra argument of ``WinContextToUnwindCursor``)

File: src/pal/src/exception/seh-unwind.cpp (hunk 1 above)
Comment (parjong) [inline src/pal/src/exception/seh-unwind.cpp]: ``PAL_VirtualUnwind`` who invokes this function will invoke ``unw_init_local`` after this function returns.

File: src/pal/src/exception/seh-unwind.cpp (hunk 3 above)
Comment (myungjoo) [inline src/pal/src/exception/seh-unwind.cpp]: More specifically, ARM64, AMD64, and I386 are UNWIND_CONTEXT_IS_UCONTEXT_T = 1. Only ARM has 0.
(header files of libunwind have explanations on this)

You do not need to change the macros because of this, but you can make the code more readable based on this fact.
I.e., the line 245:263 (or 246:271 after this patch) may be updated to have a single #if-#else-#endif structure while removing duplicated operations.

Anyway, you are right about the last replies, this patch does have the correctness. Please refactor/consolidate the logic here, which is going to be even more distorted after this.

Comment (parjong) [inline src/pal/src/exception/seh-unwind.cpp]: Do  you mean that UNWIND_CONTEXT_IS_UCONTEXT_T = 1 always holds for I386 / AMD64 / ARM64? If so, we can eliminate the call of ``WinContextToUnwindCursor`` at line 260:262.

**Comment by parjong** [comment]
@myungjoo I merged two ifdef blocks into one, but it is still unclear for me how to address the ifdef after ``unw_init_local``. I'll check that again.

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
I would recommend a slight change here. Rename UpdateUnwindContextWithWinContext to WinContextToUnwindContext and then change this piece of code
```C++
#if UNWIND_CONTEXT_IS_UCONTEXT_T
    WinContextToUnwindContext(context, &unwContext);
#else
    st = unw_getcontext(&unwContext);
    if (st < 0)
    {
        return FALSE;
    }

    UpdateUnwindContextWithWinContext(context, &unwContext);
#endif
```
to
```C++
#if !UNWIND_CONTEXT_IS_UCONTEXT_T
    st = unw_getcontext(&unwContext);
    if (st < 0)
    {
        return FALSE;
    }
#endif

    WinContextToUnwindContext(context, &unwContext);

```

**Comment by janvorli** [comment]
Otherwise LGTM

**Comment by janvorli** [comment]
@dotnet-bot test Windows_NT x86 Debug Legacy Backend Build and Test please

**Comment by parjong** [comment]
@janvorli Please review the revised patch.

**Comment by janvorli** [comment]
LGTM
