### PR TITLE
Fix callKillSet for CORINFO_HELP_ASSIGN_BYREF on x64.

### LINKED ISSUE #19361: Segfault in libcoreclr.so
I'm experiencing a segmentation fault on .NET Core 2 on Linux/docker, under versions 2.1.2 and 2.0.9, when my process is under heavy load and using a lot of memory. 

I haven't tried to reproduce outside of Linux/docker, but I have reproduced on both AWS Kubernetes and my local Docker for Windows with identical stack traces.

Here are some details from capturing the segfault under the debugger:

```
Process 1608 stopped
* thread #54: tid = 1664, 0x00007fff821131b3, name = 'dotnet', stop reason = signal SIGSEGV: address access protected (fault address: 0x7ffd217b05c8)
    frame #0: 0x00007fff821131b3
->  0x7fff821131b3: rep
    0x7fff821131b4: movsq  (%rsi), %es:(%rdi)
    0x7fff821131b6: incl   0x8(%rbx)
    0x7fff821131b9: movl   $0x1, %eax

(lldb) clrstack
OS Thread Id: 0x680 (54)
        Child SP               IP Call Site
00007FFB5AFFA850 00007FFF821131B3 System.Collections.Generic.List`1+Enumerator[[System.ValueTuple`3[[System.DateTime, System.Private.CoreLib],[Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource, Ist.Terraform.TimeSeries],[System.Decimal, System.Private.CoreLib]], System.Private.CoreLib]].MoveNext() [/root/coreclr/src/mscorlib/shared/System/Collections/Generic/List.cs @ 1139]
00007FFB5AFFA870 00007FFF82112F6B System.Linq.Enumerable.Min[[System.ValueTuple`3[[System.DateTime, System.Private.CoreLib],[Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource, Ist.Terraform.TimeSeries],[System.Decimal, System.Private.CoreLib]], System.Private.CoreLib],[System.DateTime, System.Private.CoreLib]](System.Collections.Generic.IEnumerable`1<System.ValueTuple`3<System.DateTime,Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,System.Decimal>>, System.Func`2<System.ValueTuple`3<System.DateTime,Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,System.Decimal>,System.DateTime>) [/root/corefx-1818530/src/System.Linq/src/System/Linq/Min.cs @ 910]
00007FFB5AFFA990 00007FFF82112CE4 Ist.Terraform.TimeSeries.CompositeCalc.Portfolio.PortfolioBuyHoldReturnCalc+<>c__DisplayClass23_0.<.ctor>b__9(System.ValueTuple`3<System.DateTime,Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,System.Decimal>)
00007FFB5AFFA9D0 00007FFF82112B6A System.Linq.Enumerable+WhereListIterator`1[[System.ValueTuple`3[[System.DateTime, System.Private.CoreLib],[Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource, Ist.Terraform.TimeSeries],[System.Decimal, System.Private.CoreLib]], System.Private.CoreLib]].ToList() [/root/corefx-1818530/src/System.Linq/src/System/Linq/Where.cs @ 397]
00007FFB5AFFAAC0 00007FFF82100B35 Ist.Terraform.TimeSeries.CompositeCalc.Portfolio.PortfolioBuyHoldReturnCalc..ctor(Ist.Terraform.TimeSeries.Interfaces.ISeriesContainer, System.Collections.Generic.IDictionary`2<Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>>, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, System.Nullable`1<System.DateTime>, Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>, System.Nullable`1<Double>) [/app/src/Ist.Terraform.TimeSeries/CompositeCalc/Portfolio/PortfolioBuyHoldReturnCalc.cs @ 64]
00007FFB5AFFABD0 00007FFF820FF575 Ist.Terraform.TimeSeries.CompositeCalc.Portfolio.CalculatedCostReturnCalc..ctor(Ist.Terraform.TimeSeries.Interfaces.ISeriesContainer, System.Collections.Generic.IDictionary`2<Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>>, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, System.Nullable`1<System.DateTime>, System.Nullable`1<Double>) [/app/src/Ist.Terraform.TimeSeries/CompositeCalc/Portfolio/CalculatedCostReturnCalc.cs @ 24]
00007FFB5AFFAC50 00007FFF820FF419 Ist.Terraform.TimeSeries.TimeSeriesModuleFactory.CreatePortfolioModel(Int32, System.String, Ist.Terraform.Data.Models.Enums.CompositeType, System.Collections.Generic.IDictionary`2<Ist.Terraform.TimeSeries.CompositeCalc.CompositeSource,Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>>, Ist.Terraform.Data.Models.Enums.CurrencyCode, Ist.Terraform.Data.Models.Enums.CompositeCalcType, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, System.Collections.Generic.IList`1<Ist.Terraform.TimeSeries.CompositeCalc.CompositeRatio>, Ist.Terraform.Data.Models.Enums.RebalanceFrequency, System.Nullable`1<System.DateTime>, System.Nullable`1<Double>, Ist.Terraform.TimeSeries.Interfaces.ISeries`1<System.Nullable`1<Double>>) [/app/src/Ist.Terraform.TimeSeries/TimeSeriesModuleFactory.cs @ 261]
00007FFB5AFFAD20 00007FFF817F8544 Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<CreateSystemPortfolioAsync>d__25.MoveNext() [/app/src/Ist.Terraform.TimeSeries/TimeSeriesModuleFactory.cs @ 865]
00007FFB5AFFAE30 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFAE90 00007FFF817FFE71 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<CreateSystemPortfolioAsync>d__25, Ist.Terraform.TimeSeries]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFAEC0 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFAF00 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFAFA0 00007FFF7CB9FD46 System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 421]
00007FFB5AFFAFD0 00007FFF7CBDC60B System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetExistingTaskResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 639]
00007FFB5AFFB000 00007FFF818054AC Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<GetInvestableReturnsAsync>d__15.MoveNext()
00007FFB5AFFB080 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFB0E0 00007FFF820F6031 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<GetInvestableReturnsAsync>d__15, Ist.Terraform.TimeSeries]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFB110 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFB150 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFB1F0 00007FFF7CB9FD46 System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 421]
00007FFB5AFFB220 00007FFF7CBDC60B System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetExistingTaskResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 639]
00007FFB5AFFB250 00007FFF81806CB4 Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<GetPricesAsync>d__30.MoveNext()
00007FFB5AFFB360 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFB3C0 00007FFF818097F1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Ist.Terraform.TimeSeries.TimeSeriesModuleFactory+<GetPricesAsync>d__30, Ist.Terraform.TimeSeries]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFB3F0 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFB430 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFB4D0 00007FFF7CB9FD46 System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 421]
00007FFB5AFFB500 00007FFF7CBDC60B System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetExistingTaskResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 639]
00007FFB5AFFB530 00007FFF8180BEFA Ist.Terraform.Data.Repositories.PostgresRepository+<GetSeriesPricesAsync>d__24.MoveNext()
00007FFB5AFFBCB0 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFBD10 00007FFF81819751 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Ist.Terraform.Data.Repositories.PostgresRepository+<GetSeriesPricesAsync>d__24, Ist.Terraform.Data]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFBD40 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFBD80 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFBE20 00007FFF7CBD641C System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].TrySetResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 424]
00007FFB5AFFBE50 00007FFF7CBA93BF System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 646]
00007FFB5AFFBE70 00007FFF8181BFA0 Npgsql.NpgsqlTransaction+<Commit>d__17.MoveNext()
00007FFB5AFFBEC0 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFBF20 00007FFF80B0D6C0 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Npgsql.NpgsqlTransaction+<Commit>d__17, Npgsql]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFBF50 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFBF90 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFC030 00007FFF7CBD641C System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].TrySetResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 424]
00007FFB5AFFC060 00007FFF7CBA93BF System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 646]
00007FFB5AFFC080 00007FFF8181CBA4 Npgsql.NpgsqlConnector+<ExecuteInternalCommand>d__204.MoveNext()
00007FFB5AFFC1B0 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFC210 00007FFF80381090 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Npgsql.NpgsqlConnector+<ExecuteInternalCommand>d__204, Npgsql]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFC240 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFC280 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFC320 00007FFF7CB9FD46 System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 421]
00007FFB5AFFC350 00007FFF7CBDC60B System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetExistingTaskResult(System.__Canon) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 639]
00007FFB5AFFC380 00007FFF80AF9131 Npgsql.NpgsqlConnector+<>c__DisplayClass161_0+<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
00007FFB5AFFC470 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFC4D0 00007FFF80AFD161 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Npgsql.NpgsqlConnector+<>c__DisplayClass161_0+<<ReadMessage>g__ReadMessageLong|0>d, Npgsql]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFC500 00007FFF7CB9A637 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/TaskContinuation.cs @ 798]
00007FFB5AFFC540 00007FFF7CB5098E System.Threading.Tasks.Task.RunContinuations(System.Object) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 3275]
00007FFB5AFFC5E0 00007FFF7CBD641C System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].TrySetResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/future.cs @ 424]
00007FFB5AFFC610 00007FFF7CBA93BF System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]].SetExistingTaskResult(System.Threading.Tasks.VoidTaskResult) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 646]
00007FFB5AFFC630 00007FFF80AF9D95 Npgsql.NpgsqlReadBuffer+<>c__DisplayClass31_0+<<Ensure>g__EnsureLong|0>d.MoveNext()
00007FFB5AFFC6C0 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFC720 00007FFF80AFCB70 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Npgsql.NpgsqlReadBuffer+<>c__DisplayClass31_0+<<Ensure>g__EnsureLong|0>d, Npgsql]].MoveNext() [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs @ 568]
00007FFB5AFFC750 00007FFF7FB06D73 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 219]
00007FFB5AFFC770 00007FFF7FB075F0 System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 439]
00007FFB5AFFC780 00007FFF7CB0CF9D System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/root/coreclr/src/mscorlib/shared/System/Threading/ExecutionContext.cs @ 167]
00007FFB5AFFC7E0 00007FFF7FB08169 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32, System.Net.Sockets.SocketFlags) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 786]
00007FFB5AFFC800 00007FFF7FB095A4 System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs @ 413]
00007FFB5AFFC820 00007FFF7FB08686 System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32, Byte[], Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs @ 122]
00007FFB5AFFC830 00007FFF7FB15202 System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation.InvokeCallback(Boolean) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 464]
00007FFB5AFFC880 00007FFF7FB15D1B System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessAsyncOperation(System.__Canon) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 855]
00007FFB5AFFC8B0 00007FFF7FB16318 System.Net.Sockets.SocketAsyncContext+OperationQueue`1+<>c[[System.__Canon, System.Private.CoreLib]].<.cctor>b__18_0(System.Object) [/root/corefx-1818530/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 697]
00007FFB5AFFC8C0 00007FFF7CB9C6E8 System.Threading.ThreadPoolWorkQueue.Dispatch() [/root/coreclr/src/mscorlib/src/System/Threading/ThreadPool.cs @ 588]
00007FFB5AFFCC90 00007ffff6269ecf [DebuggerU2MCatchHandlerFrame: 00007ffb5affcc90]

(lldb) bt
* thread #54: tid = 1664, 0x00007fff821131b3, name = 'dotnet', stop reason = signal SIGSEGV: address access protected (fault address: 0x7ffd217b05c8)
  * frame #0: 0x00007fff821131b3
    frame #1: 0x00007fff82112f6b
    frame #2: 0x00007fff82112ce4
    frame #3: 0x00007fff82112b6a
    frame #4: 0x00007fff82100b35
    frame #5: 0x00007fff820ff575
    frame #6: 0x00007fff820ff419
    frame #7: 0x00007fff817f8544
    frame #8: 0x00007fff7cb0cf9d
    frame #9: 0x00007fff817ffe71
    frame #10: 0x00007fff7cb9a637
    frame #11: 0x00007fff7cb5098e
    frame #12: 0x00007fff7cb9fd46
    frame #13: 0x00007fff7cbdc60b
    frame #14: 0x00007fff818054ac
    frame #15: 0x00007fff7cb0cf9d
    frame #16: 0x00007fff820f6031
    frame #17: 0x00007fff7cb9a637
    frame #18: 0x00007fff7cb5098e
    frame #19: 0x00007fff7cb9fd46
    frame #20: 0x00007fff7cbdc60b
    frame #21: 0x00007fff81806cb4
    frame #22: 0x00007fff7cb0cf9d
    frame #23: 0x00007fff818097f1
    frame #24: 0x00007fff7cb9a637
    frame #25: 0x00007fff7cb5098e
    frame #26: 0x00007fff7cb9fd46
    frame #27: 0x00007fff7cbdc60b
    frame #28: 0x00007fff8180befa
    frame #29: 0x00007fff7cb0cf9d
    frame #30: 0x00007fff81819751
    frame #31: 0x00007fff7cb9a637
    frame #32: 0x00007fff7cb5098e
    frame #33: 0x00007fff7cbd641c
    frame #34: 0x00007fff7cba93bf
    frame #35: 0x00007fff8181bfa0
    frame #36: 0x00007fff7cb0cf9d
    frame #37: 0x00007fff80b0d6c0
    frame #38: 0x00007fff7cb9a637
    frame #39: 0x00007fff7cb5098e
    frame #40: 0x00007fff7cbd641c
    frame #41: 0x00007fff7cba93bf
    frame #42: 0x00007fff8181cba4
    frame #43: 0x00007fff7cb0cf9d
    frame #44: 0x00007fff80381090
    frame #45: 0x00007fff7cb9a637
    frame #46: 0x00007fff7cb5098e
    frame #47: 0x00007fff7cb9fd46
    frame #48: 0x00007fff7cbdc60b
    frame #49: 0x00007fff80af9131
    frame #50: 0x00007fff7cb0cf9d
    frame #51: 0x00007fff80afd161
    frame #52: 0x00007fff7cb9a637
    frame #53: 0x00007fff7cb5098e
    frame #54: 0x00007fff7cbd641c
    frame #55: 0x00007fff7cba93bf
    frame #56: 0x00007fff80af9d95
    frame #57: 0x00007fff7cb0cf9d
    frame #58: 0x00007fff80afcb70
    frame #59: 0x00007fff7fb06d73
    frame #60: 0x00007fff7cb0cf9d
    frame #61: 0x00007fff7fb08169
    frame #62: 0x00007fff7fb095a4
    frame #63: 0x00007fff7fb08686
    frame #64: 0x00007fff7fb15d1b
    frame #65: 0x00007fff7fb16318
    frame #66: 0x00007ffff6269ecf libcoreclr.so`CallDescrWorkerInternal + 124
    frame #67: 0x00007ffff618a5fc libcoreclr.so`MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) + 83 at callhelpers.cpp:78
    frame #68: 0x00007ffff618a5a9 libcoreclr.so`MethodDescCallSite::CallTargetWorker(this=<unavailable>, pArguments=<unavailable>, pReturnValue=0x00007ffb5affcb28, cbReturnValue=8) + 857 at callhelpers.cpp:620
    frame #69: 0x00007ffff630a845 libcoreclr.so`QueueUserWorkItemManagedCallback(void*) [inlined] MethodDescCallSite::Call_RetBool(this=0x00007ffb5affcb30, pArguments=<unavailable>) + 15 at callhelpers.h:433
    frame #70: 0x00007ffff630a836 libcoreclr.so`QueueUserWorkItemManagedCallback(pArg=0x00007ffb5affcebe) + 166 at comthreadpool.cpp:451
    frame #71: 0x00007ffff615bf2d libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) [inlined] ManagedThreadBase_DispatchInner(pCallState=0x00007ffb5affcd68) + 413 at threads.cpp:8850
    frame #72: 0x00007ffff615bedb libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) [inlined] ManagedThreadBase_DispatchMiddle(pCallState=0x00007ffb5affcd68) + 83 at threads.cpp:8901
    frame #73: 0x00007ffff615be88 libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) [inlined] ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_8::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const::{lambda(Param*)#1}::operator()(Param*) const at threads.cpp:9139
    frame #74: 0x00007ffff615be88 libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) at threads.cpp:9141
    frame #75: 0x00007ffff615be88 libcoreclr.so`ManagedThreadBase_DispatchOuter(pCallState=<unavailable>) + 248 at threads.cpp:9178
    frame #76: 0x00007ffff615c690 libcoreclr.so`ManagedThreadBase::ThreadPool(ADID, void (*)(void*), void*) [inlined] ManagedThreadBase_FullTransitionWithAD(pAppDomain=<unavailable>, pTarget=<unavailable>, args=<unavailable>, filterType=ThreadPoolThread)(void*), void*, UnhandledExceptionLocation) + 43 at threads.cpp:9199
    frame #77: 0x00007ffff615c665 libcoreclr.so`ManagedThreadBase::ThreadPool(pAppDomain=<unavailable>, pTarget=<unavailable>, args=<unavailable>)(void*), void*) + 21 at threads.cpp:9241
    frame #78: 0x00007ffff62eea47 libcoreclr.so`ManagedPerAppDomainTPCount::DispatchWorkItem(this=0x00000000006952a0, foundWork=0x00007ffb5affcebf, wasNotRecalled=0x00007ffb5affcebe) + 295 at threadpoolrequest.cpp:754
    frame #79: 0x00007ffff617ad23 libcoreclr.so`ThreadpoolMgr::WorkerThreadStart(void*) [inlined] ThreadpoolMgr::ExecuteWorkRequest(bool*, bool*) + 1267 at win32threadpool.cpp:1560
    frame #80: 0x00007ffff617ad02 libcoreclr.so`ThreadpoolMgr::WorkerThreadStart(lpArgs=<unavailable>) + 1234 at win32threadpool.cpp:2024
    frame #81: 0x00007ffff64f0f72 libcoreclr.so`CorUnix::CPalThread::ThreadEntry(pvParam=0x00007ffb74003b80) + 306 at thread.cpp:1682
    frame #82: 0x00007ffff79bf494 libpthread.so.0`start_thread + 196
    frame #83: 0x00007ffff6e64acf libc.so.6`clone + 63

(lldb) sos VerifyHeap
Object 00007ffb01dd4ff8 has an invalid method table.
Last good object: 00007FFB01DD4FD8.
Object 00007ffe12430570 has an invalid method table.
Last good object: 00007FFE12430358.
Object 00007fff4ffff000 has an invalid method table.Object 00007ffae914b000 has an invalid method table.Object 00007ffa9593b000 has an invalid method table.Object 00007ffe8ffff000 has an invalid method table.Object 00007fff5ffff000 has an invalid method table.Object 00007ffad9149000 has an invalid method table.Object 00007ffaa593d000 has an invalid method table.Failed to request SyncBlk at index 1.
VerifyHeap  failed

```

I don't have the coredump from this particular crash (because it got OOM killed after calling VerifyHeap!), but most times it crashes, the top of the stack is identical to this (see attached file 4 for one of the times it didn't look like this). 

Unfortunately I can't post the code because it's proprietary. We're working on trying to produce a minimal test case, but that's a lot easier said than done. However if you have somewhere secure and private to upload core dumps to, I could do that.

I have also attached information from the debugger from other crashes (the one above is file 3):

[dumpinfo1.txt](https://github.com/dotnet/coreclr/files/2271414/dumpinfo1.txt)
[dumpinfo2.txt](https://github.com/dotnet/coreclr/files/2271413/dumpinfo2.txt)
[dumpinfo3.txt](https://github.com/dotnet/coreclr/files/2271412/dumpinfo3.txt)
[dumpinfo4.txt](https://github.com/dotnet/coreclr/files/2271415/dumpinfo4.txt)

The environment I set up to reproduce the issue is here: https://github.com/ist-ltd/dotnet-core-debug-helper-tools - but it relies on a private docker image.

### PR DESCRIPTION
**Pull request by sandreenko**
Our emitter doesn't check liveness information consistency, so when we generate a LIR node that expands to a several machine instructions there is no way to check that nobody corrupts the data.

In this case `STORE_OBJ` generated
```
IN0006:        mov      rdi, r15
IN0007:        mov      rsi, r12
							Byref regs: 00009000 {r12 r15} => 00009040 {rsi r12 r15}
							Byref regs: 00009040 {rsi r12 r15} => 000090C0 {rsi rdi r12 r15}
							Call: GCvars=0000000000000000 {}, gcrefRegs=00000000 {}, byrefRegs=00009000 {r12 r15}
IN0008:        call     CORINFO_HELP_ASSIGN_BYREF
IN0009:        mov      ecx, 7
IN000a:        rep movsq 
```
where `byrefRegs` after call did not include `rsi, rdi`, because we trashed `RBM_CALLEE_TRASH_NOGC` that on Linux x64 incudes `rci, rdi`. https://github.com/dotnet/coreclr/blob/1c47703a3d548e5f3293a11d98747dd83bf429f1/src/jit/emitxarch.cpp#L6880-L6884 

Fixes #19361.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib 

I am trying to modify the repro from @jkotas to expose this issue in ci, if I success I will add it later.

File: src/jit/codegencommon.cpp [hunk 1]
```diff
@@ -639,6 +639,19 @@ regMaskTP Compiler::compNoGCHelperCallKillSet(CorInfoHelpFunc helper)
 
     switch (helper)
     {
+        case CORINFO_HELP_ASSIGN_BYREF:
+#if defined(_TARGET_X86_)
+            // This helper only trashes ECX.
+            return RBM_ECX;
+#elif defined(_TARGET_AMD64_)
+            // This uses and defs rdi and rci.
```
Comment (CarolEidt) [inline src/jit/codegencommon.cpp]: Typo: rci -> rsi
Also, you may want to just be quite explicit that "This uses and defines rdi and rsi, so they remain as live GC refs or byrefs, and are not killed." or something like that.

File: src/vm/amd64/jithelpers_fast.S [hunk 2]
```diff
@@ -228,8 +228,9 @@ LEAF_END JIT_PatchedCodeLast, _TEXT
 //   RSI - address of the data  (source)
 //
 //   Note: RyuJIT assumes that all volatile registers can be trashed by
-//   the CORINFO_HELP_ASSIGN_BYREF helper (i.e. JIT_ByRefWriteBarrier).
-//   The precise set is defined by RBM_CALLEE_TRASH.
+//   the CORINFO_HELP_ASSIGN_BYREF helper (i.e. JIT_ByRefWriteBarrier)
+//   except RDI and RCI that are incoming and outgoing registers.
```
Comment (CarolEidt) [inline src/vm/amd64/jithelpers_fast.S]: Same typo (RCI -> RSI)

**Comment by sandreenko** [comment]
random comment to start the tests

**Comment by sandreenko** [comment]
Hm, [win_x64 corefx test failed](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/2273/), lets try to rerun. Doesn't look like infra.
@dotnet-bot test  
Windows_NT x64 Checked CoreFX Tests

**Comment by AndyAyersMS** [comment]
Any idea why gc stress didn't catch this?

**Comment by sandreenko** [comment]
Have not succeed in adding a repro. I will merge the fix only for now.

> Any idea why gc stress didn't catch this?

The issue only marks struct fields as dead and we usually have other parts of the class alive (like `this` or temp variables that saves `&field` etc.). So I think it is pretty rare case when the gc can collect the whole class right after the large struct assignment.

Thank for your help with repro.
