### PR TITLE
Fix mismatch between new and free in numa.cpp

### LINKED ISSUE #15867: Mismatching allocation and deallocation in VirtualAllocExNuma()
This was found with Cppcheck

pal/src/numa/muna.cpp has `VirtualAllocExNuma()` function that does this:

    unsigned long *nodeMask = new unsigned long[nodeMaskLength];
    //whatever, then
    free(nodeMask);

Pairing `new[]` with `free()` yields undefined behavior. I guess `malloc()` with a null check should be used here - same as with other memory allocations in this translation unit.

### PR DESCRIPTION
**Pull request by janvorli**
One of the allocations in the numa.cpp uses new to allocate an array,
but it incorrectly uses free to free the memory. This change fixes it.

Closes #15867

### CODE REVIEW

File: src/pal/src/numa/numa.cpp [hunk 1]
```diff
@@ -836,7 +836,7 @@ VirtualAllocExNuma(
             if (result != NULL && g_numaAvailable)
             {
                 int nodeMaskLength = (g_highestNumaNode + 1 + sizeof(unsigned long) - 1) / sizeof(unsigned long);
-                unsigned long *nodeMask = new unsigned long[nodeMaskLength];
+                unsigned long *nodeMask = (unsigned long*)malloc(nodeMaskLength * sizeof(unsigned long));
```
Comment (Dmitry-Me) [inline src/pal/src/numa/numa.cpp]: Shouldn't the code check the return value of `malloc()`?

Comment (janvorli) [reply src/pal/src/numa/numa.cpp]: Oh, sure it should :-(. And the other mallocs as well. Sigh.

File: src/pal/src/numa/numa.cpp [hunk 2]
```diff
@@ -836,8 +860,7 @@ VirtualAllocExNuma(
             if (result != NULL && g_numaAvailable)
             {
                 int nodeMaskLength = (g_highestNumaNode + 1 + sizeof(unsigned long) - 1) / sizeof(unsigned long);
-                unsigned long *nodeMask = (unsigned long*)malloc(nodeMaskLength * sizeof(unsigned long));
-
+                unsigned long *nodeMask = (unsigned long*)alloca(nodeMaskLength * sizeof(unsigned long));
```
Comment (Dmitry-Me) [inline src/pal/src/numa/numa.cpp]: How large is the allocation? Can it consume the stack fully?

Comment (janvorli) [reply src/pal/src/numa/numa.cpp]: It is small. That's why I have converted it to alloca. There is one bit per NUMA node in this array. Number of numa nodes is smaller or equal to the number of logical CPU cores in the system. Usually, it is much smaller. Simply said, NUMA node contains processors that have the same speed of access to a part of the memory of the system. Usually, NUMA nodes correspond to processor sockets.  E.g. RHEL 7 Linux supports max 768 logical CPU cores on amd64, so that would make this array 96 bytes large even if each processor was in its own NUMA node.

File: src/pal/src/numa/numa.cpp [hunk 3]
```diff
@@ -125,6 +106,42 @@ FreeLookupArrays()
...
+    g_groupAndIndexToCpu = (short*)malloc(g_groupCount * MaxCpusPerGroup * sizeof(short));
+    if (g_groupAndIndexToCpu != NULL)
+    {
+        g_cpuToAffinity = (CpuAffinity*)malloc(g_possibleCpuCount * sizeof(CpuAffinity));
+        if (g_cpuToAffinity != NULL)
+        {
+            g_groupToCpuMask = (KAFFINITY*)malloc(g_groupCount * sizeof(KAFFINITY));
+            if (g_groupToCpuMask != NULL)
+            {
+                g_groupToCpuCount = (BYTE*)malloc(g_groupCount * sizeof(BYTE));
```
Comment (sergiy-k) [inline src/pal/src/numa/numa.cpp]: This allocation needs a null check as well, right?

Comment (jkotas) [reply src/pal/src/numa/numa.cpp]: Good catch...

@janvorli Could you please change this to use the `goto done` pattern that is used in the rest of the PAL while you are on it? It is much more readable than the deeply nested if checks.

Comment (janvorli) [reply src/pal/src/numa/numa.cpp]: Sigh, right.

File: src/pal/src/numa/numa.cpp (hunk 2 above)
Comment (Dmitry-Me) [reply src/pal/src/numa/numa.cpp]: Sounds good so far.
