### PR TITLE
Fix GT_LCL_FLD case in gtGetStructHandleIfPresent

### LINKED ISSUE #9159: RayTracer fails with COMPlus_JitStress=2 and COMPlus_EnableAVX=0
A previous failure in RayTracer/JitStress2, #9108, was caused by the issues fixed in #9123. However, on a non-AVX2 system a different failure is exposed, which is due to `gtGetStructHandleIfPresent` returning the parent struct handle for a `GT_LCL_FLD`. I am working on a fix.

### PR DESCRIPTION
**Pull request by CarolEidt**
This method was incorrectly returning the parent struct handle instead of the handle for the field. This is showing up in remorphing (due to JitStress) of a SIMD field that was assigned in a field-by-field assignment.

Fix #9159

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by sivarv** [comment]
Looks good.

**Comment by sivarv** [comment]
Wondering whether this fix is needed even on desktop?

**Comment by CarolEidt** [comment]
@sivarv Yes, but I don't think it needs to be ported for immediate release, because it is only exposed because of the recent addition of support for promoting fields of SIMD type.

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -16323,8 +16323,15 @@ CORINFO_CLASS_HANDLE Compiler::gtGetStructHandleIfPresent(GenTree* tree)
...
                 break;
-            case GT_LCL_VAR:
             case GT_LCL_FLD:
+#ifdef FEATURE_SIMD
+                if (varTypeIsSIMD(tree))
+                {
+                    structHnd = gtGetStructHandleForSIMD(tree->gtType, TYP_FLOAT);
+                }
+#endif
+                break;
```
Comment (BruceForstall) [inline src/jit/gentree.cpp]: In the non-SIMD case, does it need to continue to execute the GT_LCL_VAR code as it did before (i.e., fall through)?

Comment (CarolEidt) [inline src/jit/gentree.cpp]: No; in fact we don't want it to as it is not the right struct handle for this case. In that case it should return the `NO_CLASS_HANDLE` value which `structHnd` has already been set to.

**Comment by BruceForstall** [comment]
LGTM

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT minopts
@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked minopts

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT jitstress1
