### PR TITLE
Fix PAL signal count upper limit issues.

### LINKED ISSUE #1318: SetSignalCount assertion failure in PAL while running CoreFX tests
The assert is not allowing max int32 as a valid signal count.

I'm taking a look at this issue.

### PR DESCRIPTION
**Pull request by kouvel**
- Fix assert in SetSignalCount to allow int32 max as a valid value.
- Change ISynchStateController signal count functions to use LONG
  instead of DWORD to match the storage type for consistency.
- In ReleaseSemaphoreInternal, handle overflow of (oldCount +
  releaseCount) to return failure. Updated PAL semaphore tests to catch
  this case.

Fix #1318

### CODE REVIEW

File: src/pal/src/synchmgr/synchcontrollers.cpp [hunk 1]
```diff
@@ -556,16 +556,16 @@ namespace CorUnix
...
     waiting threads awakening.
     --*/
-    PAL_ERROR CSynchStateController::SetSignalCount(DWORD dwNewCount)
+    PAL_ERROR CSynchStateController::SetSignalCount(LONG lNewCount)
     {
         VALIDATEOBJECT(m_psdSynchData);
 
         _ASSERTE(InternalGetCurrentThread() == m_pthrOwner);
-        _ASSERT_MSG((DWORD)INT_MAX > dwNewCount,
+        _ASSERT_MSG((ULONG)INT_MAX >= (ULONG)lNewCount,
```
Comment (sergiy-k) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Since lNewCount is a signed integer now and INT_MAX is a valid value, should we just assert that it is >=0?

File: src/pal/src/synchmgr/synchcontrollers.cpp [hunk 2]
```diff
@@ -578,21 +578,22 @@ namespace CorUnix
...
+        LONG lAmountToIncrement)
     {
         VALIDATEOBJECT(m_psdSynchData);
 
-        LONG lOldCount = m_psdSynchData->GetSignalCount();        
-        LONG lNewCount = lOldCount + (LONG)dwAmountToIncrement;
-
         _ASSERTE(InternalGetCurrentThread() == m_pthrOwner);
-        _ASSERT_MSG((DWORD)INT_MAX > dwAmountToIncrement,
+        _ASSERTE(lAmountToIncrement > 0);
```
Comment (sergiy-k) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: I assume that you've checked all callers and having lAmountToIncrement to be 0 is indeed illegal?

File: src/pal/src/synchmgr/synchcontrollers.cpp [hunk 3]
```diff
@@ -578,21 +578,22 @@ namespace CorUnix
...
+        _ASSERT_MSG((ULONG)INT_MAX > (ULONG)lAmountToIncrement,
             "Signal count increment %u too large (max=%u)\n",
-            dwAmountToIncrement, (DWORD)INT_MAX);
+            (ULONG)lAmountToIncrement, (ULONG)INT_MAX);
 
-        _ASSERT_MSG(lNewCount >= lOldCount && (lNewCount >= 0 && static_cast<DWORD>(lNewCount) >= dwAmountToIncrement),
+        LONG lOldCount = m_psdSynchData->GetSignalCount();
+        LONG lNewCount = lOldCount + lAmountToIncrement;
+
+        _ASSERT_MSG(lNewCount >= lOldCount && (lNewCount >= 0 && lNewCount >= lAmountToIncrement),
```
Comment (sergiy-k) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: If lAmountToIncrement cannot be 0 then should lNewCount be always > lOldCount and > 0?

File: src/pal/src/synchmgr/synchcontrollers.cpp [hunk 4]
```diff
@@ -578,21 +578,22 @@ namespace CorUnix
...
             "Signal count increment %u would make current signal count %d to "
-            "wrap around\n", dwAmountToIncrement, lOldCount);
+            "wrap around\n", lAmountToIncrement, lOldCount);
```
Comment (sergiy-k) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Could you please double check whether it would make sense to return an error in case of an overflow like we in DecrementSignalCount in the code below? Or would it cause some problems?

File: src/pal/src/synchmgr/synchcontrollers.cpp (hunk 1 above)
Comment (kouvel) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Yea would be better, done

File: src/pal/src/synchmgr/synchcontrollers.cpp (hunk 2 above)
Comment (kouvel) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: It looks like the expectation is that callers don't call the function when the increment is 0. The only place this is called is from (Internal)ReleaseSemaphose, which doesn't allow 0 for the release count, where the release count becomes the amount to increment here.

File: src/pal/src/synchmgr/synchcontrollers.cpp (hunk 3 above)
Comment (kouvel) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Yea, since we know lOldCount >= 0 && lAmountToIncrement > 0, it should be sufficient to verify that lNewCount > lOldCount to catch overflow, changed it to that. The other checks here would be implied.

File: src/pal/src/synchmgr/synchcontrollers.cpp (hunk 4 above)
Comment (kouvel) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: I noticed that, it seems like INTERAL_ERROR is the equivalent of an unexpected case and perhaps a good reason to check for it in non-debug builds would be to prevent security issues (assert vs runtime check & fail). I can change it to a runtime check if you think it would be useful in this case, but I don't see a strong need for it to be a runtime check and probably an assert would suffice in both cases (increment & decrement) considering that all other checks that could cause similar issues are also asserts currently. I would suggest changing this runtime check into an assert since limits tests should catch most if not all such issues pretty easily. Thoughts?

File: src/pal/src/synchmgr/synchcontrollers.cpp [hunk 5]
```diff
@@ -578,21 +576,19 @@ namespace CorUnix
...
-            "Signal count increment %u too large (max=%u)\n",
-            dwAmountToIncrement, (DWORD)INT_MAX);
+        _ASSERTE(lAmountToIncrement > 0);
+
+        LONG lOldCount = m_psdSynchData->GetSignalCount();
+        LONG lNewCount = lOldCount + lAmountToIncrement;
 
-        _ASSERT_MSG(lNewCount >= lOldCount && (lNewCount >= 0 && static_cast<DWORD>(lNewCount) >= dwAmountToIncrement),
+        _ASSERT_MSG(lNewCount > lOldCount,
             "Signal count increment %u would make current signal count %d to "
```
Comment (adityamandaleeka) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Now that they're both LONGs, I suppose the `%u` should be changed as well.

File: src/pal/tests/palsuite/threading/CreateSemaphoreA_ReleaseSemaphore/test3/createsemaphore.c [hunk 6]
```diff
@@ -96,8 +98,9 @@ int __cdecl main (int argc, char **argv)
                 continue;
             }
         }
+
         /* incriment semaphore count to lMaximumCount */
```
Comment (adityamandaleeka) [inline src/pal/tests/palsuite/threading/CreateSemaphoreA_ReleaseSemaphore/test3/createsemaphore.c]: Please fix the typo on 'increment' while you're in this file.

File: src/pal/tests/palsuite/threading/CreateSemaphoreW_ReleaseSemaphore/test3/createsemaphore.c [hunk 7]
```diff
@@ -96,8 +98,9 @@ int __cdecl main (int argc, char **argv)
                 continue;
             }
         }
+
         /* incriment semaphore count to lMaximumCount */
```
Comment (adityamandaleeka) [inline src/pal/tests/palsuite/threading/CreateSemaphoreW_ReleaseSemaphore/test3/createsemaphore.c]: ...and here too

**Comment by adityamandaleeka** [comment]
LGTM. Please clean up the history before merging.

File: src/pal/src/synchmgr/synchcontrollers.cpp (hunk 5 above)
Comment (kouvel) [inline src/pal/src/synchmgr/synchcontrollers.cpp]: Oh missed that, done

File: src/pal/tests/palsuite/threading/CreateSemaphoreA_ReleaseSemaphore/test3/createsemaphore.c (hunk 6 above)
Comment (kouvel) [inline src/pal/tests/palsuite/threading/CreateSemaphoreA_ReleaseSemaphore/test3/createsemaphore.c]: Done

File: src/pal/tests/palsuite/threading/CreateSemaphoreW_ReleaseSemaphore/test3/createsemaphore.c (hunk 7 above)
Comment (kouvel) [inline src/pal/tests/palsuite/threading/CreateSemaphoreW_ReleaseSemaphore/test3/createsemaphore.c]: Done

**Comment by kouvel** [comment]
@dotnet-bot retest this please

**Comment by kouvel** [comment]
@dotnet-bot retest this please

**Comment by sergiy-k** [comment]
LGTM

**Comment by jasonwilliams200OK** [comment]
Looks like the FreeBSD timeout issue is back. It could be because your branch is 51 commits behind the current dotnet/coreclr master. 
In cmd (with git in PATH):

```cmd
cd coreclr
git remote add dotnet https://github.com/dotnet/master
git checkout kouvel-SetSignalCountAssertFix-1318
git pull --rebase dotnet master
git push -f
```

**Comment by kouvel** [comment]
That seems to have worked, thanks!
