### PR TITLE
Disable DOTNET_MULTILEVEL_LOOKUP in the build scripts

### LINKED ISSUE #22971: Build fails: System.MissingMethodException: Method not found: 'Void NuGet.Packaging.Manifest.Save
Building current master (https://github.com/dotnet/coreclr/commit/ef0fde985732148eea136e90aece4ccd3d0370b5) using `build.cmd checked skiptests` fails on Windows for me with:

```
BUILD: Building Packages for Windows_NT.x64.Checked
Tools are already initialized.
Running: dotnet msbuild /nologo /verbosity:minimal /clp:Summary /nodeReuse:false      /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log      /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true      /p:UsePartialNGENOptimization=false /maxcpucount      C:\coreclr\src\.nuget\packages.builds      /flp:Verbosity=normal;LogFile="C:\coreclr\bin\Logs\Nuget_Windows_NT__x64__Checked.log" /flp1:WarningsOnly;LogFile="C:\coreclr\bin\Logs\Nuget_Windows_NT__x64__Checked.wrn" /flp2:ErrorsOnly;LogFile="C:\coreclr\bin\Logs\Nuget_Windows_NT__x64__Checked.err" /p:Platform=x64 /p:__BuildOS=Windows_NT /p:__BuildType=Checked /p:__BuildArch=x64
C:\coreclr\Tools\Packaging.targets(1208,5): error : System.MissingMethodException: Method not found: 'Void NuGet.Packaging.Manifest.Save(System.IO.Stream, Boolean)'. [C:\coreclr\src\.nuget\Microsoft.NETCore.Runtime.CoreCLR\Microsoft.NETCore.Runtime.CoreCLR.pkgproj]
C:\coreclr\Tools\Packaging.targets(1208,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.GenerateNuSpec.WriteNuSpecFile() [C:\coreclr\src\.nuget\Microsoft.NETCore.Runtime.CoreCLR\Microsoft.NETCore.Runtime.CoreCLR.pkgproj]
C:\coreclr\Tools\Packaging.targets(1208,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.GenerateNuSpec.Execute() [C:\coreclr\src\.nuget\Microsoft.NETCore.Runtime.CoreCLR\Microsoft.NETCore.Runtime.CoreCLR.pkgproj]
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #22971

### CODE REVIEW

**Comment by jkotas** [comment]
cc @sdmaclea @jashook This is fixing an issue introduced by #22755.

File: dotnet.sh [hunk 1]
```diff
@@ -2,6 +2,12 @@
 
 working_tree_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
+# Don't resolve runtime, shared framework, or SDK from other locations to ensure build determinism
+export DOTNET_MULTILEVEL_LOOKUP=0
```
Comment (jkotas) [inline dotnet.sh]: This matches what the Arcade scripts do here: https://github.com/dotnet/coreclr/blob/master/eng/common/tools.sh#L84
