### PR TITLE
Restrict morph add rearrangement.

### LINKED ISSUE #23792: JIT optimizations can produce incorrect IL when dealing with byrefs
(See also https://github.com/dotnet/coreclr/pull/23783#discussion_r272807908.)

Repro:

```cs
private delegate ref byte MyDelegate(ref byte theRef, IntPtr a, IntPtr b);

static void Main()
{
    DynamicMethod dm = new DynamicMethod("Sample",
        typeof(byte).MakeByRefType(),
        new Type[] { typeof(byte).MakeByRefType(), typeof(IntPtr), typeof(IntPtr) });

    var ilGen = dm.GetILGenerator();
    ilGen.Emit(OpCodes.Ldarg_0);
    ilGen.Emit(OpCodes.Ldc_I4_8);
    ilGen.Emit(OpCodes.Sub);
    ilGen.Emit(OpCodes.Ldarg_1);
    ilGen.Emit(OpCodes.Add);
    ilGen.Emit(OpCodes.Ldc_I4_8);
    ilGen.Emit(OpCodes.Sub);
    ilGen.Emit(OpCodes.Ldarg_2);
    ilGen.Emit(OpCodes.Add);
    ilGen.Emit(OpCodes.Ret);

    var del = (MyDelegate)dm.CreateDelegate(typeof(MyDelegate));
}
```

Codegen:

```asm
DynamicClass.Sample(Byte ByRef, IntPtr, IntPtr):
00007ffc`80220080 4803d1          add     rdx,rcx
00007ffc`80220083 4a8d4402f0      lea     rax,[rdx+r8-10h]
00007ffc`80220088 c3              ret
```

Here, `rcx := theRef&`, `rdx := a`, and `r8 := b`. The JIT has incorrectly rearranged the addition of _a_ and the subtraction of _8_. It's possible that the caller required the operations to be done specifically in that order to avoid a GC hole. The intermediate value `ref byte temp = ref theRef + a` could result in a _temp_ that points beyond the bounds of the GC-tracked object.

Edit: the following codegen would have been acceptable, since it doesn't result in an intermediate byref.

```asm
add rdx, r8
lea rax, [rcx + rdx - 10h]
ret
```

### PR DESCRIPTION
**Pull request by erozenfeld**
Morph has transformations
((x + const) + y) => ((x + y) + const)
and
((x + const1) + (y + const2)) => ((x + y) + (const1 + const2))

If x or y is a GC pointer and one of the int operands may be negative,
this may result in a byref temp that points outside of the ref object.
If the code is in a non-interruptible region and a GC happens, the byref
won't be updated.

This change disallows the transformations if one of the non-const
operands is a GC pointer.

Fixes #23792.

### CODE REVIEW

**Comment by erozenfeld** [comment]
Codegen of `Run` method changes from
```
       4803D1               add      rdx, rcx
       4A8D4402F0           lea      rax, bword ptr [rdx+r8-16]
       C3                   ret
```
to
```
       4883C1F8             add      rcx, -8
       4803D1               add      rdx, rcx
       4A8D4402F8           lea      rax, bword ptr [rdx+r8-8]
       C3                   ret
```

**Comment by erozenfeld** [comment]
No diffs in benchmarks.
1 diff in framework assemblies: 1 byte improvement in BigInteger:SubtractDivisor(byref,int,byref,long):int from System.Private.CoreLib.dll.

**Comment by erozenfeld** [comment]
@AndyAyersMS @dotnet/jit-contrib PTAL

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -13983,39 +13983,62 @@ GenTree* Compiler::fgMorphSmpOpOptional(GenTreeOp* tree)
...
+            var_types typ2   = op2->TypeGet();
+            var_types ad1typ = ad1->TypeGet();
+
+            bool doTransformation = true;
 
-            if (varTypeIsGC(op2->TypeGet()))
+            // Don't create a byref pointer that may point outside of the ref object. If a GC happens, the byref won't
+            // get updated. This can happen, if one of the int components is negative.
+            // It also requires the address generation be in a fully-interruptible code region.
+            // We allow the transformation only if the constant is non-negative and the other int operand is unsigned.
```
Comment (mikedn) [inline src/jit/morph.cpp]: The unsigned case is probably not going to happen. If one operand is GC then the others are supposed to be pointer sized integers and these are not normally unsigned in JIT's IR (e.g. you can have a `TYP_USHORT` indir but not a `TYP_UINT`/`TYP_ULONG` one).

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -13983,39 +13983,62 @@ GenTree* Compiler::fgMorphSmpOpOptional(GenTreeOp* tree)
...
+            if (varTypeIsGC(typ2))
             {
-                noway_assert(varTypeIsGC(typ));
-                op1->gtType = typ;
+                doTransformation = ((ad2->gtIntCon.gtIconVal >= 0) && varTypeIsUnsigned(ad1typ));
```
Comment (mikedn) [inline src/jit/morph.cpp]: It would be good if new code uses `AsIntCon()` instead of `gtIntCon`. `IconValue()` would be good too, though that's a different kind of issue.

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -13983,39 +13983,62 @@ GenTree* Compiler::fgMorphSmpOpOptional(GenTreeOp* tree)
...
-            // This takes
-            //       + (tree)
-            //      / \.
-            //     /   \.
-            //    /     \.
-            //   + (op1) op2
-            //  / \.
-            //     \.
-            //     ad2
+            //  This takes
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Since these methods return bool can you get rid of the `==0` and `!=0` ?

File: src/jit/morph.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/jit/morph.cpp]: I think you are right, I wasn't able to construct an example with an unsigned case so I simplified the fix.

File: src/jit/morph.cpp (hunk 3 above)
Comment (erozenfeld) [reply src/jit/morph.cpp]: Done.

Comment (erozenfeld) [reply src/jit/morph.cpp]: Yes, the "((x+icon1)+(y+icon2)) to ((x+y)+(icon1+icon2))" transformation was also unsafe. I added a test for that and fixed the code. The codegen for `Run2`:
before
```
       4803D1               add      rdx, rcx
       4A8D4402F0           lea      rax, bword ptr [rdx+r8-16]
       C3                   ret
```
after
```
       4883C1F8             add      rcx, -8
       4883C2F8             add      rdx, -8
       488D0411             lea      rax, bword ptr [rcx+rdx]
       4903C0               add      rax, r8
       C3                   ret
```

**Comment by erozenfeld** [comment]
I addressed all feedback, PTAL. The diffs are the same, a one byte improvement in `BigInteger:SubtractDivisor(byref,int,byref,long):int`.

**Comment by erozenfeld** [comment]
The new test (`Run2`) failed on x86 because it was adding an i8 to a byref, which is illegal. I pushed a fix.

**Comment by erozenfeld** [comment]
@dotnet-bot test Ubuntu arm Cross Checked crossgen_comparison Build and Test
@dotnet-bot test Ubuntu arm Cross Release crossgen_comparison Build and Test

**Comment by erozenfeld** [comment]
arm legs are stuck because of an infrastructure issue: dotnet/core-eng#6014
