### PR TITLE
Fix for #21011: propagate GTF_DONT_CSE on comma returns

### LINKED ISSUE #21011: [arm64] 'Missing flags on tree' assert when returning struct from a synchronized method
```
using System;
using System.Runtime.CompilerServices;
using System.Collections.Generic;

public class Test
{   
    static bool flag = false;

    public static int Main()
    {
        Test test = new Test();
        test.GetPair();
        return 100;
    }

    [MethodImpl(MethodImplOptions.Synchronized | MethodImplOptions.NoInlining)]
    internal KeyValuePair<uint, float>? GetPair()
    {		
        KeyValuePair<uint,float>? result = new KeyValuePair<uint,float>?();
        return result;
    }
}
```
```
COMPlus_AltJit=*
COMPlus_AltJitAssertOnNYI=1
COMPlus_AltJitName=protononjit.dll
COMPlus_AltJitNgen=*
COMPlus_ContinueOnAssert=0
COMPlus_NoGuiOnAssert=0
COMPlus_SIMD16ByteOnly=1
COMPlus_TieredCompilation=0
```

```
Missing flags on tree [000056]: --X--------
               [000058] -ACXG+------              /--*  IND       struct
               [000057] -----+------              |  |     /--*  ADDR      byref
               [000040] -----+------              |  |     |  \--*  CNS_INT   struct 0
               [000043] --C-G+------              |  |  /--*  COMMA     byref
               [000036] --C-G+------              |  |  |  \--*  CALL help void   HELPER.CORINFO_HELP_MON_EXIT
               [000032] L----+------ arg1 in x1   |  |  |     +--*  ADDR      long
               [000031] ----G+-N----              |  |  |     |  \--*  LCL_VAR   ubyte (AX) V03 tmp1
               [000033] -----+------ arg0 in x0   |  |  |     \--*  LCL_VAR   ref    V00 this
               [000041] -AC-G+------              |  \--*  COMMA     byref
               [000006] -----+-N----              |     |  /--*  LCL_VAR   struct V01 loc0
               [000039] -A---+------              |     \--*  ASG       struct (copy)
               [000037] D----+-N----              |        \--*  LCL_VAR   struct V05 tmp3
               [000056] -AC-G--N----              *  ASG       struct (copy)
               [000055] D------N----              \--*  LCL_VAR   struct V06 tmp4
```

Assert failure(PID 15132 [0x00003b1c], Thread: 25700 [0x6464]): Assertion failed '!"Missing flags on tree"' in 'Test:GetPair():struct:this' (IL size 38)

### PR DESCRIPTION
**Pull request by erozenfeld**
When a method returns a multi-reg struct, we set GTF_DONT_CSE on return local: https://github.com/dotnet/coreclr/blob/497419bf8f19c649d821295da7e225e55581cce9/src/jit/importer.cpp#L8783

Setting GTF_DONT_CSE blocks assertion propagation here:
https://github.com/dotnet/coreclr/blob/9d49bf1ec6f102b89e5c2885e8f9d3d77f2ec144/src/jit/assertionprop.cpp#L2845-L2848

In the test we have a synchronized method so we change the return node to
return a comma that include a call to HELPER.CORINFO_HELP_MON_EXIT.
If the rightmost comma expression doesn't have GTF_DONT_CSE,
assertion propagation is not blocked and we end up with this tree:

```
               [000040] -----+------                 /--*  CNS_INT   struct 0
               [000043] --C-G+------              /--*  COMMA     struct
               [000036] --C-G+------              |  \--*  CALL help void   HELPER.CORINFO_HELP_MON_EXIT
               [000032] L----+------ arg1 in x1   |     +--*  ADDR      long
               [000031] ----G+-N----              |     |  \--*  LCL_VAR   ubyte (AX) V03 tmp1
               [000033] -----+------ arg0 in x0   |     \--*  LCL_VAR   ref    V00 this
               [000041] -AC-G+------              *  COMMA     struct
               [000006] -----+-N----              |  /--*  LCL_VAR   struct V01 loc0
               [000039] -A---+------              \--*  ASG       struct (copy)
               [000037] D----+-N----                 \--*  LCL_VAR   struct V05 tmp3
```

Downstream phases can't handle struct zero return expressed as
```
               [000040] -----+------                 /--*  CNS_INT   struct 0
```

The fix is to propagate GTF_DONT_CSE to the rightmost comma expression
to block bad assertion propagation.

Fixes #21011.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@CarolEidt @sandreenko @dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
Rather a nasty bug! Thanks for tracking this down.

File: src/jit/flowgraph.cpp [hunk 1]
```diff
@@ -8034,6 +8034,7 @@ GenTree* Compiler::fgCreateMonitorTree(unsigned lvaMonAcquired, unsigned lvaThis
             GenTree* temp = fgInsertCommaFormTemp(&retNode->gtOp.gtOp1, info.compMethodInfo->args.retTypeClass);
 
             GenTree* lclVar                 = retNode->gtOp.gtOp1->gtOp.gtOp2;
+            lclVar->gtFlags |= (retExpr->gtFlags & GTF_DONT_CSE);
```
Comment (CarolEidt) [inline src/jit/flowgraph.cpp]: It might be worth a comment describing this case.
I think that it's probably generally prudent to propagate the `GTF_DONT_CSE`, but you could mention that the return can't handle all of the trees that could be on the right-hand-side of an assignment, especially in the case of a struct. In fact, it might be sufficient to propagate the flag only in the case that it's a struct, though perhaps it's best to be conservative.

Comment (erozenfeld) [reply src/jit/flowgraph.cpp]: Added comment, thanks.

**Comment by erozenfeld** [comment]
No arm64 diffs reported by
jit-diff diff --frameworks --altjit protononjit.dll
both crossgen and pmi.
