### PR TITLE
Fix WSL alternate stack check

### LINKED ISSUE #25945: SIGSEGV is not transformed into NullReferenceException in WSL
Under WSL (at least Ubuntu 18.04, and seemingly OpenSUSE 15) , SIGSEGV is not caught and transformed into a `NullReferenceException` as it is on other platforms.

Repro:

```c#
class Program
{
    static unsafe void Main(string[] args)
    {
        int* ptr = null;
        Console.WriteLine(*ptr);
    }
}
```

```
cory@conelso1:~/39732-smtp-segfault$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
cory@conelso1:~/39732-smtp-segfault$ ./bin/Debug/netcoreapp3.0/39732-smtp-segfault
Segmentation fault (core dumped)
```

Found during our investigation of https://github.com/dotnet/corefx/issues/39732

cc @janvorli @wfurt

### PR DESCRIPTION
**Pull request by janvorli**
On WSL, the alternate stack check in sigsegv_handler doesn't work. The
uc_stack members are always zero no matter whether the handler is
executed on an alternate or default stack. So the check to detect
whether we are running on an alternate stack or not is always returning
false on WSL and it prevents NULL reference exceptions from being
handled.
The fix is to introduce an env variable COMPlus_EnableAlternateStackCheck
that can be used to enable the alternate stack check. By default, the
sigsegv_handler is considered to always run on an alternate stack. If that
env var is set, we perform a check based on the uc_stack contents.

Fix #25945

### CODE REVIEW

File: src/pal/src/exception/signal.cpp [hunk 1]
```diff
@@ -402,11 +409,23 @@ Return :
 --*/
 bool IsRunningOnAlternateStack(void *context)
 {
-    stack_t *signalStack = &((native_context_t *)context)->uc_stack;
-    // Check if the signalStack local variable address is within the alternate stack range. If it is not,
-    // then either the alternate stack was not installed at all or the current method is not running on it.
-    void* alternateStackEnd = (char *)signalStack->ss_sp + signalStack->ss_size;
-    return ((signalStack->ss_flags & SS_DISABLE) == 0) && (signalStack->ss_sp <= &signalStack) && (&signalStack < alternateStackEnd);
+    bool isRunningOnAlternateStack;
+    if (g_enable_alternate_stack_check)
```
Comment (sergiy-k) [inline src/pal/src/exception/signal.cpp]: Nit: is it worth adding a comment describing that not all Linux environments allow/support detection of alt stack in this way?

Comment (janvorli) [reply src/pal/src/exception/signal.cpp]: Sounds reasonable. Actually, only the WSL doesn't support it (and I expect that WSL2 will support it).

**Comment by sergiy-k** [comment]
LGTM. Thank you!
