### PR TITLE
Lock the the dest reg in `inst_RV_TT` if necessary.

### LINKED ISSUE #12935: [ARM32][LEGACY_BACKEND] JIT\Methodical\int64\arrays\_il_rellcs_ulong\_il_rellcs_ulong fails under JITStressRegs=1
Rather than completing successfully, this test throws (and does not handle) an instance of `System.Exception`. This test does run successfully without `JitStressRegs`.

This was originally tracked by #12914.

### PR DESCRIPTION
**Pull request by pgavlin**
For ARM32, `inst_RV_TT` may need to load the referenced lclVar into a
temporary register before emitting the requested instruction. The
chosen register *must not* be the instruction's destination register.
The existing code attempted to ensure this by masking the dest register
from the set of pickable registers, but this is not sufficient:
`rsPickReg` must return a valid register and will happily attempt to
spill and return the destination register even if it is not in the
recommended set. To prevent this, this change locks and unlocks the
destination register if necessary (i.e. if it was not locked upon
entry).

Fixes #12935.

### CODE REVIEW

**Comment by pgavlin** [comment]
@briansull @CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/instr.cpp [hunk 1]
```diff
@@ -2532,7 +2532,24 @@ void CodeGen::inst_RV_TT(instruction ins,
...
+                        else if ((regMask & regSet.rsMaskLock) == 0)
+                        {
+                            regSet.rsLockUsedReg(regMask);
+                            regTmp = regSet.rsPickReg(RBM_ALLINT);
+                            regSet.rsUnlockUsedReg(regMask);
+                        }
+                        else
+                        {
+                            regTmp = regSet.rsPickReg(RBM_ALLINT);
+                        }
```
Comment (CarolEidt) [inline src/jit/instr.cpp]: Do you understand why just requesting a register other than the ones in use is insufficient? I admit that the using and locking and requesting protocol is not entirely clear to me.

Comment (pgavlin) [inline src/jit/instr.cpp]: Yes: `rsPickReg` is documented as only treating the provided mask as a hint, not a requirement. If there are no registers from that set available, it defers to `rsGrabReg`, which only excludes locked registers and those holding lclVars.

Comment (CarolEidt) [inline src/jit/instr.cpp]: Thanks. Makes sense then.

**Comment by pgavlin** [comment]
The Windows/ARM failures appear to be regressions introduced by https://github.com/dotnet/coreclr/pull/12951 (see e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt/23/)

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test
