### PR TITLE
Fix bug where crossgen would throw OOM error

### LINKED ISSUE #24458: Crossgen /CreatePDB command needs to work with input file paths not containing any back slashes
Running crossgen /CreatePDB from a working dir containing the R2R image, and giving crossgen a plain filename as an input fails

Bug in NGenModulePdbWriter::WritePDBData():

``` C++
        SString::Iterator fileNameStart = dllPath.End();
        dllPath.FindBack(fileNameStart, DIRECTORY_SEPARATOR_STR_W);

	SString::Iterator ext = dllPath.End();
	dllPath.FindBack(ext, '.');

	// m_tempSourceDllName = Convertion of  INPUT.dll  to INPUT.ni.dll where the PDB lives.  
	m_tempSourceDllName = m_wszPdbPath;
	m_tempSourceDllName += **SString(dllPath, fileNameStart, ext - fileNameStart);**
	m_tempSourceDllName += W(".ni");
	m_tempSourceDllName += SString(dllPath, ext, dllPath.End() - ext);
	CopyFileW(dllPath, m_tempSourceDllName, false);
	dllPath = m_tempSourceDllName;
```

### PR DESCRIPTION
**Pull request by fadimounir**
Fix bug where crossgen would throw OOM when given an input with no dir-separator characters (arithmetic overflow bug).
Using crossgen from the SDK (dotnet publish) is not impacted by this issue.

The /CreatePerfMap codepath doesn't have this bug.

Fixes #24458

### CODE REVIEW

File: src/vm/compile.cpp [hunk 1]
```diff
@@ -3006,29 +3006,30 @@ HRESULT NGenModulePdbWriter::WritePDBData()
...
+    // images do not follow this convention and end up producing bad PDBS.  To fix
+    // this (without changing diasymreader.dll which ships indepdendently of .NET Core)
+    // we copy the file to somethign with this convention before generating the PDB
+    // and delete it when we are done.  
+    SString dllPath = pLoadedLayout->GetPath();
+    if (!dllPath.EndsWithCaseInsensitive(W(".ni.dll")) && !dllPath.EndsWithCaseInsensitive(W(".ni.exe")))
+    {
+        SString::Iterator fileNameStart = dllPath.End();
+        if (!dllPath.FindBack(fileNameStart, DIRECTORY_SEPARATOR_STR_W))
+            fileNameStart = dllPath.Begin();
```
Comment (fadimounir) [inline src/vm/compile.cpp]: The fix is just these 2 lines, with the if-check. The rest of the changes in the file is just replacing tabs with 4 spaces

**Comment by fadimounir** [comment]
@davidwrighton PTAL
