### PR TITLE
JIT: don't trust field offsets in R2R for nullcheck bypass

### LINKED ISSUE #16454: [RyuJit/R2R/MinOpts] JIT\Regression\JitBlue\GitHub_12949\GitHub_12949_8: Consistency check failed
[Ci example for amd64](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_r2r_jitminopts/), [ci example for arm32 ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitminopts_tst_prtest/7/).

Part of #15552.

Test output:
```

Native image GitHub_12949_8.exe generated successfully.
 "C:\git\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" GitHub_12949_8.exe

Assert failure(PID 21728 [0x000054e0], Thread: 16756 [0x4174]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! JIT_BoxFastMP_InlineGetThread + 0x60 (0x00007ff9`179d0e30)
GITHUB_12949_8! COM+_Entry_Point + 0xFFFFFFFF (0x00007ff9`8f232c96)
GITHUB_12949_8! COM+_Entry_Point + 0xFFFFFFFF (0x00007ff9`8f232bd1)
CORECLR! CallDescrWorkerInternal + 0x83 (0x00007ff9`17ab5443)
CORECLR! CallDescrWorkerWithHandler + 0x1DE (0x00007ff9`176f6b0e)
CORECLR! MethodDescCallSite::CallTargetWorker + 0xC40 (0x00007ff9`176f7760)
CORECLR! MethodDescCallSite::Call_RetArgSlot + 0xF4 (0x00007ff9`172cea14)
CORECLR! ``RunMain'::`30'::__Body::Run'::`5'::__Body::Run + 0x269 (0x00007ff9`17308769)
CORECLR! `RunMain'::`30'::__Body::Run + 0x85 (0x00007ff9`173088a5)
CORECLR! RunMain + 0x19E (0x00007ff9`17308bae)
CORECLR! Assembly::ExecuteMainMethod + 0x4AA (0x00007ff9`172ff2da)
CORECLR! CorHost2::ExecuteAssembly + 0x54E (0x00007ff9`171c340e)
CORERUN! TryRun + 0xCB5 (0x00007ff7`1e2c57a5)
CORERUN! wmain + 0x14B (0x00007ff7`1e2c6dfb)
CORERUN! invoke_main + 0x34 (0x00007ff7`1e35e964)
CORERUN! _scrt_common_main_seh + 0x127 (0x00007ff7`1e35e887)
CORERUN! _scrt_common_main + 0xE (0x00007ff7`1e35e74e)
CORERUN! wmainCRTStartup + 0x9 (0x00007ff7`1e35e9d9)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ff9`99d91fe4)
-----
.AV on tid=0x4174 (16756), cxr=000000891B57CE40, exr=000000891B57D330
FAILED: false

CORECLR! CHECK::Trigger + 0x275 (0x00007ff9`1711d535)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x331 (0x00007ff9`17234281)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x8C (0x00007ff9`17233c2c)
CORECLR! CLRVectoredExceptionHandler + 0x275 (0x00007ff9`17233b85)
CORECLR! CLRVectoredExceptionHandlerShim + 0x18A (0x00007ff9`1723455a)
NTDLL! RtlUserThreadStart + 0x132 (0x00007ff9`9a6ef0d2)
NTDLL! RtlWalkFrameChain + 0x122B (0x00007ff9`9a69ceeb)
NTDLL! KiUserExceptionDispatcher + 0x2E (0x00007ff9`9a723bae)
CORECLR! JIT_BoxFastMP_InlineGetThread + 0x60 (0x00007ff9`179d0e30)
GITHUB_12949_8! COM+_Entry_Point + 0xFFFFFFFF (0x00007ff9`8f232c96)
    File: c:\git\coreclr\src\vm\excep.cpp Line: 7916
    Image: C:\git\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When the jit is forming an field address to pass off to points unknown
it will nullcheck at the point of creation, unless it can prove that the
field is at offset zero. Unfortunately in R2R mode field offsets are not
known at jit time and so a zero value seen when prejitting may end up
being nonzero when the code is loaded and fixed up and fool the jit into
omitting a null check that is potentially needed.

So in R2R mode, always emit null checks.

Fixes #16454.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@sandreenko thanks for the analysis and discussion on this -- PTAL
cc @dotnet/jit-contrib 

jit-diff impact is happily quite small. No diffs in corelib (as expected) since in NGEN mode we know offsets.
```
Total bytes of diff: 4800 (0.02% of base)
    diff is a regression.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
        1061 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.05% of base)
        1009 : Microsoft.CodeAnalysis.CSharp.dasm (0.05% of base)
         849 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.03% of base)
         191 : System.ComponentModel.TypeConverter.dasm (0.09% of base)
         162 : System.Net.WebSockets.dasm (0.41% of base)
Top file improvements by size (bytes):
          -2 : System.Collections.Immutable.dasm (0.00% of base)
52 total files with size differences (1 improved, 51 regressed), 78 unchanged.
Top method regessions by size (bytes):
          45 : System.ComponentModel.TypeConverter.dasm - System.ComponentModel.MaskedTextProvider:TestChar(ushort,int,byref):bool:this
          45 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[ValueWebSocketReceiveResultGetter,ValueWebSocketReceiveResult][System.Net.WebSockets.ManagedWebSocket+ValueWebSocketReceiveResultGetter,System.Net.WebSockets.ValueWebSocketReceiveResult]:MoveNext():this
          44 : Microsoft.CodeAnalysis.VisualBasic.dasm - VB$StateMachine_69_GetMethodsToEmit:MoveNext():bool:this
          36 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[__Canon,__Canon][System.__Canon,System.__Canon]:MoveNext():this
          36 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[WebSocketReceiveResultGetter,__Canon][System.Net.WebSockets.ManagedWebSocket+WebSocketReceiveResultGetter,System.__Canon]:MoveNext():this
Top method improvements by size (bytes):
         -30 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax:Update(struct,struct,ref,struct,ref,ref):ref:this
         -26 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Syntax.UsingDirectiveSyntax:Update(struct,struct,ref,ref,struct):ref:this
         -20 : Newtonsoft.Json.dasm - Newtonsoft.Json.JsonSerializer:ApplySerializerSettings(ref,ref)
         -13 : System.Net.Sockets.dasm - AwaitableSocketAsyncEventArgs:<.ctor>b__2_0(ref,ref):this
          -9 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax:Update(ushort,ref,struct,ref):ref:this
1522 total methods with size differences (56 improved, 1466 regressed), 153488 unchanged.
```

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -6703,7 +6703,12 @@ GenTree* Compiler::fgMorphField(GenTree* tree, MorphAddrContext* mac)
                 else
                 {
 #if CONSERVATIVE_NULL_CHECK_BYREF_CREATION
-                    addExplicitNullCheck = (mac->m_kind == MACK_Addr && (mac->m_totalOffset + fldOffset > 0));
+                    // In R2R mode the field offset may be changed when the code is loaded.
+                    // So we can't rely on a zero offset here to suppress the null check.
+                    //
+                    // See GitHub issue #16454.
+                    addExplicitNullCheck =
+                        (mac->m_kind == MACK_Addr) && ((mac->m_totalOffset + fldOffset > 0) || opts.IsReadyToRun());
```
Comment (jkotas) [inline src/jit/morph.cpp]: This is only needed for `CORINFO_FIELD_INSTANCE_WITH_BASE` fields. I think you can check for it here using `gtField.gtFieldLookup.addr != nullptr`.  Most of the fields in R2R mode have fixed offsets.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Thanks, updated.

**Comment by AndyAyersMS** [comment]
Updated -- now has slightly smaller diffs and fewer impacted methods.
```
Total bytes of diff: 3986 (0.02% of base)
    diff is a regression.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file regressions by size (bytes):
         927 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.04% of base)
         734 : Microsoft.CodeAnalysis.CSharp.dasm (0.03% of base)
         704 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.03% of base)
         162 : System.Net.WebSockets.dasm (0.41% of base)
         160 : System.Net.Http.dasm (0.05% of base)
44 total files with size differences (0 improved, 44 regressed), 86 unchanged.
Top method regessions by size (bytes):
          45 : System.ComponentModel.TypeConverter.dasm - System.ComponentModel.MaskedTextProvider:TestChar(ushort,int,byref):bool:this
          45 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[ValueWebSocketReceiveResultGetter,ValueWebSocketReceiveResult][System.Net.WebSockets.ManagedWebSocket+ValueWebSocketReceiveResultGetter,System.Net.WebSockets.ValueWebSocketReceiveResult]:MoveNext():this
          44 : Microsoft.CodeAnalysis.VisualBasic.dasm - VB$StateMachine_69_GetMethodsToEmit:MoveNext():bool:this
          36 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[__Canon,__Canon][System.__Canon,System.__Canon]:MoveNext():this
          36 : System.Net.WebSockets.dasm - <ReceiveAsyncPrivate>d__66`2[WebSocketReceiveResultGetter,__Canon][System.Net.WebSockets.ManagedWebSocket+WebSocketReceiveResultGetter,System.__Canon]:MoveNext():this
Top method improvements by size (bytes):
         -30 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax:Update(struct,struct,ref,struct,ref,ref):ref:this
         -26 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Syntax.UsingDirectiveSyntax:Update(struct,struct,ref,ref,struct):ref:this
         -20 : Newtonsoft.Json.dasm - Newtonsoft.Json.JsonSerializer:ApplySerializerSettings(ref,ref)
         -13 : System.Net.Sockets.dasm - AwaitableSocketAsyncEventArgs:<.ctor>b__2_0(ref,ref):this
          -9 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax:Update(ushort,ref,struct,ref):ref:this
1338 total methods with size differences (59 improved, 1279 regressed), 153672 unchanged.
```

**Comment by briansull** [comment]
What makes having a zero offset special, such that we can avoid performing a null check for it when having a small positive offset would require a null check?

**Comment by AndyAyersMS** [comment]
@briansull not 100% sure, but the big comment a bit above all this code lays out a rationale. Seems like the idea is indeed to keep near-null pointers from flowing into native code where explicit checks against 0 are used. I believe C++ does something similar with when you form pointer-to-field from a object pointer that might be null.

**Comment by AndyAyersMS** [comment]
[Test failures](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_flow_prtest/963/) seem like some sort of perhaps-transient package restore issue. Am going to retry as more recent runs are greeen.

@dotnet-bot retest Ubuntu x64 Checked Innerloop Build and Test
@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot retest CentOS7.1 x64 Checked Innerloop Build and Test

**Comment by briansull** [comment]
I help debug this issue with Sergei and from what I saw the native C++ code doesn’t check the input for zero (null) either, so passing a zero would also be fatal in this case.

**Comment by AndyAyersMS** [comment]
Yeah it seems like one should arguably check for null or (near null) in the box helper, but it turns out, but if everything is working as it should, the helper will never see a null or near-null pointer.

This part of the code has been like this a long time so clearly something is preventing these values from reaching the helper.

The only way the address of a value type field can be null or near null is if it is inside a ref type and we start building the address from a null reference. And in ref types it is not possible for a field to be at a negative or zero offset. Thus the field address must end up as something non-null.

So the box helper should never see null (or near-null) addresses: null should be impossible, and near-null should be caught by the conservative check inserted by the jit.

And if we AV inside the box helper (like we did in this case before this fix, when the jit didn't always add the check) then something is wrong. 

In a checked build we could perhaps look for null and near null pointers on entry to the box helper so it is more obvious which part the system is at fault.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -6702,11 +6702,22 @@ GenTree* Compiler::fgMorphField(GenTree* tree, MorphAddrContext* mac)
...
                 else
                 {
+                    // In R2R mode the field offset for some fields may change when the code
+                    // is loaded. So we can't rely on a zero offset here to suppress the null check.
+                    //
+                    // See GitHub issue #16454.
+                    bool fieldHasChangeableOffset = false;
+
+#ifdef FEATURE_READYTORUN_COMPILER
+                    fieldHasChangeableOffset = (tree->gtField.gtFieldLookup.addr != nullptr);
```
Comment (briansull) [inline src/jit/morph.cpp]: If we can’t trust the value of fldOffset for the R2R case it would seem better to handle it above with fgIsBigOffset as it could potentially be a “Big” offset as well.

**Comment by sandreenko** [comment]
@dotnet-bot test Windows_NT arm Cross Checked r2r Build and Test
@dotnet-bot test Windows_NT arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Windows_NT x64 Cross Checked r2r_jitminopts Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot   test Windows_NT x64 Checked r2r_jitminopts
@dotnet-bot test Windows_NT x64 Checked r2r_jitstress1

File: src/jit/morph.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: That case is likely covered by R2R pitching the prejitted code when a changeable offset ends up being a big offset (see the `ENCODE_FIELD_OFFSET` case in `LoadDynamicInfoEntry`).

Though thinking about it some more I wonder if we could get burned by cases where we have nested structs such that any particular offset is not big but the cumulative offset after R2R fixups have been applied is big. Let me try working up a test case for this.

We should review who else calls `fgIsBigOffset` and see if those callers can be fooled by fields with changeable offsets.

**Comment by AndyAyersMS** [comment]
Also I think the "conservative" nullcheck model here is in fact required by the spec (in particular `ldflda` must raise an exception if it is invoked on a null reference). Consider this test case where we create pointers but don't dereference them:
```
using System;
using System.Runtime.CompilerServices;

// NRE without a dereference

struct S
{
    public int a;
    public int b;
}

unsafe class X
{
    S s;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static long Distance(X x)
    {
        fixed(S* p = &x.s)     // NRE required here if x is null
        {
            return &p->b - &p->a;
        }
    }

    public static void Main()
    {
        Distance(null);
    }
}
```
So we might consider removing the ifdefed out code for the alternate version.

**Comment by AndyAyersMS** [comment]
The pointer passed to the helper can't ever validly be null at runtime. If the base is a reference and so can be null then the zero offset will be changed to nonzero when the code is loaded, as no ref class has a field at offset zero.

So aside from the issue Brian raised around big offsets I think what's there is accurate.

In an ideal world the R2R reported layout for all classes would be an actual plausible layout. That appears not to be the case right now.

We should review the subsequent uses of field offset but it's not clear to me yet what if anything we might need to change. Some or all of the field offset addition for R2R is handled by the subsequent ifdef'd code -- and we then rely on the zero offset (at least in some cases) to bypass additional adjustments that aren't need for R2R.

I also have some concerns for what happens in the aliasing model but as long as the layout the jit sees is a plausible layout then we should generally be OK. If fields that don't overlap look like they do, or fields that do overlap look like they don't, then we could be in trouble, but I assume we'd have hit bugs from such cases by now. Technically a zero offset field in a ref class aliases the vtable pointer, but we don't model the vtable like we do other fields in a class.

**Comment by AndyAyersMS** [comment]
Still thinking about potential exposure for big offsets. The [arm r2r failures](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_r2r_flow_prtest/20/) seem like they may be some other problem as this bug case and fix are relatively obscure.

**Comment by sandreenko** [comment]
> The arm r2r failures seem like they may be some other problem as this bug case and fix are relatively obscure.

Yes, these 4 failures are known and tracked by #15552.

Windows_NT arm Cross Checked r2r_jitminopts Build and Test should be clean.

**Comment by AndyAyersMS** [comment]
In the [Windows x64 R2R jitstress1](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_r2r_jitstress1_prtest/6/) leg, DevDiv_255294 timed out. Also likely unrelated. Seems this test is a known troublemaker for crossgen (eg #11469) and maybe should be exempted from jit stress.

**Comment by AndyAyersMS** [comment]
Also I don't have a good answer for R2R/big offsets yet. So I suggest we take this fix and continue looking at what should happen in other cases.
