### PR TITLE
ARM64: Enable Long Address

### LINKED ISSUE #3668: ARM64: NYI: Implement pseudo-instructions for large conditional branch
The following test fails with this NYI assert
b28158.exe_5695 :: JIT\Regression\VS-ia64-JIT\V1.2-M02\b28158\b28158\b28158.exe  

 Assertion failed 'NYI: "Implement pseudo-instructions for large conditional branch and large load label address"' in 'test:Main():int' (IL size 267733)

### PR DESCRIPTION
**Pull request by kyulee1**
Fixes #3668
Currently ARM64 codegen can have reference within +/-1 MB due to encoding
restriction in `b<cond>/adr/ldr` instructions. This is normally okay
assuming each function is reasonably small, but certainly not working for large method which also
can be formed with an aggressive inlining probably like crossgen/corert scenarios.
In addition, for hot/cold code separation long address is a prerequisite
since reference can be across different regions which are arbitrary.
In fact, we need additional relocations which are not in this change yet.

In details, this supports long address for conditional jump/address loading/constant
loading operations by default while they can be shortened later by
`emitJumpDistBind()` if they can fit into the smaller encoding. Logically
those operations now can reach within +/-4GB address range.
Note I haven't extended unconditional jump in this change for simplicity
so it can reach within +/-128MB same as before.
`emitOutputLJ` is extended to finally encode these operations.

There are 3 pseudo instructions introduced. These can be expanded either
short/long form.

1. Conditional jump. See `emitIns_J()`
   a. Short form(`IF_BI_0B`): `b<cond> rel_addr`
   b. Long form(`IF_LARGEJMP`):
   ```
     b<rev cond> $LABEL
     b rel_addr (unconditional jump)
   $LABEL:
   ```

2. Load label(address computation).  See `emitIns_R_L()`
   a. Short form(`IF_DI_1E`): `adr x, [rel_addr]`
   b. Long form(`IF_LARGEADR`):
   ```
      adrp x, [rel_page_addr]
      add x, x, page_offs
   ```

3. Load constant (from JIT data). See `emitIns_R_C()`
   a. Short form(`IF_LS_1A`): `ldr x, [rel_addr]`
   b. Long form(`IF_LARGLDC`):
   ```
      adrp x, [rel_page_addr]
      ldr x, [x, page_offs]
     (fmov v, x in case loading vector constant)
   ```

In addition, JIT data is aligned on 8 byte to be accessible from large
load. Replaced JitLargeBranches by JitLongAddress to test stress on these
operations.

There is no asm diffs other than different label number when crossgening mscorlib.
Also validated all tests are passing with `Complus_JitLongAddress=1` locally.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

File: src/jit/codegenarm64.cpp [hunk 1]
```diff
@@ -4203,6 +4215,7 @@ CodeGen::genJumpTable(GenTree* treeNode)
     getEmitter()->emitIns_R_C(INS_lea,
         emitTypeSize(TYP_I_IMPL),
         treeNode->gtRegNum,
+        REG_NA,
```
Comment (kyulee1) [inline src/jit/codegenarm64.cpp]: JumpTable code path is dead (NYI in this function). Will revisit it when it's enabled.

File: src/jit/lowerarm64.cpp [hunk 2]
```diff
@@ -201,6 +201,21 @@ void Lowering::TreeNodeInfoInit(GenTree* stmt)
         case GT_CNS_DBL:
             info->srcCount = 0;
             info->dstCount = 1;
+            {
+                GenTreeDblCon *dblConst = tree->AsDblCon();
+                double constValue = dblConst->gtDblCon.gtDconVal;
+
+                // Make sure we use "movi reg, 0x00"  only for positive zero (0.0) and not for negative zero (-0.0)
```
Comment (kyulee1) [inline src/jit/lowerarm64.cpp]: Will delete this comment.

**Comment by kyulee1** [comment]
@dotnet/jit-contrib @dotnet/arm64-contrib PTAL

File: src/jit/emit.cpp [hunk 3]
```diff
@@ -3793,6 +3801,42 @@ void                emitter::emitJumpDistBind()
...
+            int doff = jmp->idAddr()->iiaGetJitDataOffset();
+            assert(doff >= 0);
+            ssize_t imm = emitGetInsSC(jmp);
+            assert((imm >= 0) && (imm < 0x1000));   // 0x1000 is arbitrary, currently 'imm' is always 0
+
+            unsigned dataOffs = (unsigned)(doff + imm);
+            assert(dataOffs < emitDataSize());
+
+            // Conservately assume JIT data starts after the entire code size.
+            // TODO: we might consider only hot code size which will be computed later in emitComputeCodeSizes().
```
Comment (briansull) [inline src/jit/emit.cpp]: Ultimately we will want to layout the read-only data next to the hot code so that we can use the small instruction to access it.  Accessing the read-only data from the cold section will typically use the large instructions.

File: src/jit/emitarm64.cpp [hunk 4]
```diff
@@ -7864,6 +7940,78 @@ BYTE*               emitter::emitOutputLJ(insGroup  *ig, BYTE *dst, instrDesc *i
...
+            dst = emitOutputShortAddress(dst, ins, fmt, relPageAddr, addrReg);
+
+            // ldr x, [x, page offs] -- load constant from page address + page offset into integer register.
+            ssize_t imm12 = (ssize_t)dstAddr & 0xFFF; // 12 bits
+            assert(isValidUimm12(imm12));
+            ins = INS_ldr;
+            fmt = IF_LS_2B;
+            dst = emitOutputShortConstant(dst, ins, fmt, imm12, addrReg, opSize);
+
+            // fmov v, d -- copy constant in integer register to vector register.
```
Comment (briansull) [inline src/jit/emitarm64.cpp]: Instead of loading the floating point constant into the integer registers above.
why don't we change the ldr instruction to an add with 12-byte immediate
thus computing the proper address to load from
then do a floating point load instruction with a zero offset

File: src/jit/emitarm64.cpp [hunk 5]
```diff
@@ -7977,120 +8101,290 @@ BYTE*               emitter::emitOutputLJ(insGroup  *ig, BYTE *dst, instrDesc *i
...
+            //      b<!cond> L_not  // 4 bytes. Note that we reverse the condition.
+            //      b L_target      // 4 bytes
+            //   L_not:
+            //
+            // Note that we don't actually insert any blocks: we simply encode "b <!cond> L_not" as a branch with
+            // the correct offset. Note also that this works for both integer and floating-point conditions, because
+            // the condition inversion takes ordered/unordered into account, preserving NaN behavior. For example,
+            // "GT" (greater than) is inverted to "LE" (less than, equal, or unordered).
+            //
+            // History: previously, we generated:
```
Comment (briansull) [inline src/jit/emitarm64.cpp]: This History refers to what we did for Arm32,  (the it<cond> instruction)
I'm not sure why we want to mention it here in the Arm64 implementation

File: src/jit/emitarm64.cpp [hunk 6]
```diff
@@ -7977,120 +8101,290 @@ BYTE*               emitter::emitOutputLJ(insGroup  *ig, BYTE *dst, instrDesc *i
...
-            code |= distVal <<  5;
-            code |= loBits  << 29;                        //  2 bits
+        if (opSize == EA_8BYTE)
+        {
+            // insEncodeDatasizeLS is not quite right for this case.
+            // So just specialize it.
+            if (ins == INS_ldr)
+            {
+                // set the operation size in bit 30
+                code |= 0x40000000;
```
Comment (briansull) [inline src/jit/emitarm64.cpp]: This seems redundant as we just set the bit using the code above.
One of these two blocks can be removed

File: src/jit/lowerarm64.cpp [hunk 7]
```diff
@@ -201,6 +201,21 @@ void Lowering::TreeNodeInfoInit(GenTree* stmt)
...
+                if (emitter::emitIns_valid_imm_for_fmov(constValue))
+                {
+                    // Directly encode constant to instructions.
+                }
+                else
+                {
+                    // Reserve int to load constatnt from memory (IF_LARGELDC)
+                    info->internalIntCount = 1;
```
Comment (briansull) [inline src/jit/lowerarm64.cpp]: spelling: constatnt

File: src/jit/emitarm64.cpp [hunk 8]
```diff
@@ -6675,19 +6745,22 @@ void                emitter::emitIns_J(instruction   ins,
...
-
-    // TODO-ARM64-Cleanup: there is only one size jump on ARM64. Clean this up.
-    id->idjShort = 1;
     if (dst != nullptr)
     {
         id->idAddr()->iiaBBlabel = dst;
-        id->idjKeepLong = emitComp->fgInDifferentRegions(emitComp->compCurBB, dst);
+
+        // Skip unconditional jump that has a single form.
+        // NYI. In case fgInDifferentRegions is true (hot/cold separation),
```
Comment (briansull) [inline src/jit/emitarm64.cpp]: Proper format for an NY comment is:

 // TODO-ARM64-NYI: enable hot/cold splitting

**Comment by briansull** [comment]
Very Nice,
 Looks Good (with comments)

File: src/jit/emitarm64.cpp (hunk 4 above)
Comment (kyulee1) [inline src/jit/emitarm64.cpp]: I got the point for 16 byte vector load. I was trying to minimize the code size for integer case, which is in fact not used at all yet -- even jump table for switch table, we don't directly load constant but starts from reading address using `adr`. As you suggested, once I use `adrp+add` followed by `ldr` for constant loading, then all logic are consistent regardless of float/int/vector case. And also I could simplify the code as well by reusing LoadLabel code path (`adrp+adr`).
Since the current code is fully tested and working, I will follow it up in the later work.

File: src/jit/emit.cpp (hunk 3 above)
Comment (kyulee1) [inline src/jit/emit.cpp]: We are already allocating read-only data next to the hot code, and in this change reference from cold code is always kept long. The only minor issue is that emitComputeCodeSizes() comes later than this although I can replicate the code to get hot code size. I'd like to reorder emitComputeCodeSizes() with emitJumpDistBind(), which appears okay, but given the risk of changing the common code toward RTM, I will put ARM64-TODO and follow it up later.

**Comment by kyulee1** [comment]
Thank you for quick review on the large change.
I updated changes per feedbacks and other major things are individually commented, which I will follow it up. So, I'm merging it.
