### PR TITLE
Fall back to CpuId if failed to get cache size from OS

### LINKED ISSUE #16071: use GetLogicalProcessorInformationEx in GetLargestOnDieCacheSize
Per https://github.com/dotnet/coreclr/pull/15975#discussion_r163460344

> GetLargestOnDieCacheSize should be using GetLogicalProcessorInformationEx on the OS versions where it's available and fall back to cpuid where it's not

CC @Maoni0

### PR DESCRIPTION
**Pull request by andy-ms**
It's possible for GetLogicalProcessorCacheSizeFromOS() to fail;
this happens on alpine linux where it compiles to just `return 0;`.

As a fallback, we can get the cache size from CpuId. Previously that
was specific to x86; this PR preserves the behavior that we never call
GetLogicalProcessorCacheSizeFromOS on x86.

CpuId only works on x86 and amd64; on other systems we may still return
0 from here. Then GC defaults to a cache size of only 0.25MB.

Fix #16071

### CODE REVIEW

File: src/vm/util.cpp [hunk 1]
```diff
@@ -1817,11 +1781,46 @@ size_t GetCacheSizePerLogicalCpu(BOOL bTrueSize)
     {
     }
     PAL_ENDTRY
-#else
+
+    return param.maxSize;
+}
+#endif // _TARGET_X86_
+
+// fix this if/when AMD does multicore or SMT
```
Comment (janvorli) [inline src/vm/util.cpp]: This comment is very obsolete. I was just about to ask about AMD support. I've found the following CPUID specification from AMD that contains all the necessary info here: https://www.amd.com/system/files/TechDocs/25481.pdf

File: src/vm/util.cpp [hunk 2]
```diff
@@ -1645,36 +1645,21 @@ DWORD GetLogicalCpuCountFallback()
...
 
-    static size_t maxSize;
-    static size_t maxTrueSize;
+    // Can't return from a PAL_TRY. Instead, have it write to its parameter.
+    struct Param {
+        size_t maxSize;
+    } param = { 0 };
 
-    if (maxSize)
+    PAL_TRY(Param *, pParam, &param)
```
Comment (janvorli) [inline src/vm/util.cpp]: Since the attached `PAL_EXCEPT_FILTER` is using `DefaultCatchFilter`, the parameter type has to be derived from `DefaultCatchFilterParam`. The `DefaultCatchFilter` casts the parameter * to `DefaultCatchFilterParam*` and reads the `pv` field out of it.
The `DefaultCatchFilter` is used to swallow hardware exceptions that can stem from the CPUID.
