### PR TITLE
Ensure we don't underestimate the code size for 4 byte SSE instruction.

### LINKED ISSUE #24545: [x64\windows] Assertion failed 'emitInstCodeSz(id) >= csz'
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_jitx86hwintrinsicnoavx/460/testReport/

**Failed test:**
JIT_HardwareIntrinsics._X86_Sse41_ConvertToVector128_r_ConvertToVector128_r_.JIT\\HardwareIntrinsics\\X86\\Sse41\\ConvertToVector128_r\\ConvertToVector128_r.cmd

**Failed log:**
```
JIT_HardwareIntrinsics._X86_Sse41_ConvertToVector128_r_ConvertToVector128_r_._X86_Sse41_ConvertToVector128_r_ConvertToVector128_r_cmd()
        Output:
          
          Assert failure(PID 10672 [0x000029b0], Thread: 3860 [0x0f14]): Assertion failed 'emitInstCodeSz(id) >= csz' in 'JIT.HardwareIntrinsics.X86.SimpleUnaryOpTest__ConvertToVector128Int16Byte:RunBasicScenario_UnsafeRead():this' (IL size 76)
          
              File: d:\j\workspace\x64_checked_w---0b14f95b\src\jit\emit.cpp Line: 3500
              Image: D:\j\workspace\x64_checked_w---0b14f95b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
          
          
          Return code:      1
          Raw output file:      D:\j\workspace\x64_checked_w---0b14f95b\bin\tests\Windows_NT.x64.Checked\Reports\JIT.HardwareIntrinsics\X86\Sse41\ConvertToVector128_r\ConvertToVector128_r.output.txt
          Raw output:
          BEGIN EXECUTION
           "D:\j\workspace\x64_checked_w---0b14f95b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" ConvertToVector128_r.exe 
          Supported ISAs:
            AES:       True
            AVX:       False
            AVX2:      False
            BMI1:      False
            BMI2:      False
            FMA:       False
            LZCNT:     True
            PCLMULQDQ: True
            POPCNT:    True
            SSE:       True
            SSE2:      True
            SSE3:      True
            SSE4.1:    True
            SSE4.2:    True
            SSSE3:     True
          
          Beginning test case ConvertToVector128Int16.Byte at 5/12/2019 4:53:58 PM
          Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
          
          Expected: 100
          Actual: -1073740286
          END EXECUTION - FAILED
          FAILED
          Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #24545 by applying a targeted fix. The code size logic really needs to be updated to have this stuff centralized...

### CODE REVIEW

File: src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -1969,6 +1969,7 @@ inline UNATIVE_OFFSET emitter::emitInsSizeSV(code_t code, int var, int dsp)
 
 inline UNATIVE_OFFSET emitter::emitInsSizeSV(instrDesc* id, code_t code, int var, int dsp)
 {
+    assert(id->idIns() != INS_invalid);
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: There was a few places passing in `id` without initializing `Ins` first, I added an assert to the various `emitInsSize*` functions that took a `instrDesc`

File: src/jit/emitxarch.cpp [hunk 2]
```diff
@@ -6522,10 +6527,16 @@ void emitter::emitIns_SIMD_R_R_S_R(
 
 void emitter::emitIns_S(instruction ins, emitAttr attr, int varx, int offs)
 {
+    UNATIVE_OFFSET sz;
     instrDesc*     id  = emitNewInstr(attr);
-    UNATIVE_OFFSET sz  = emitInsSizeSV(id, insCodeMR(ins), varx, offs);
     insFormat      fmt = emitInsModeFormat(ins, IF_SRD);
 
+    id->idIns(ins);
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: These ones were the ones that were calling `emitInsSize*` without initialize `id->idIns`

File: src/jit/emitxarch.cpp [hunk 3]
```diff
@@ -6599,15 +6610,28 @@ void emitter::emitIns_R_S(instruction ins, emitAttr attr, regNumber ireg, int va
...
+
+    sz = emitInsSizeSV(id, insCodeRM(ins), varx, offs);
+
     // Most 16-bit operand instructions need a prefix
     if (size == EA_2BYTE && ins != INS_movsx && ins != INS_movzx)
     {
         sz++;
     }
+    
+    if (Is4ByteSSEInstruction(ins))
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: This is the actual targeted fix.

I'm going to see if I can find any other places that need it as well, but I also want to see if I can just get a proper fix of centralizing this check done.

**Comment by tannergooding** [comment]
CC. @CarolEidt

**Comment by tannergooding** [comment]
CC. @CarolEidt. I've tried to keep the changes minimal, but still complete.

It should now be consistently computing the `codeSize` and checking for extended registers.

File: src/jit/emitxarch.cpp [hunk 4]
```diff
@@ -955,6 +955,13 @@ unsigned emitter::emitGetVexPrefixAdjustedSize(instruction ins, emitAttr attr, c
 
         return vexPrefixAdjustedSize;
     }
+
+    if (Is4ByteSSEInstruction(ins))
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: This is here because it is more convenient to centralize it than it is to have explicit `Is4ByteSSEInstruction` checks at each required location.

**Comment by tannergooding** [comment]
I've got a failure locally. Checking...

**Comment by tannergooding** [comment]
Here is the output of the tests runs with some diagnostic output for instructions whose sizes were overpredicted: [output.x64.zip](https://github.com/dotnet/coreclr/files/3188235/output.x64.zip)

But, for both x64 and x86 locally, we are no longer underpredicting for any of the tests (with AVX enabled or disabled)...

**Comment by tannergooding** [comment]
What is the current way to run outer loop tests?

File: src/jit/codegenxarch.cpp [hunk 5]
```diff
@@ -6949,7 +6949,7 @@ void CodeGen::genCkfinite(GenTree* treeNode)
         {
             inst_RV_RV(ins_Copy(targetType), targetReg, op1->gtRegNum, targetType);
         }
-        inst_RV_RV_IV(INS_shufps, EA_16BYTE, targetReg, targetReg, 0xb1);
+        inst_RV_RV_IV(INS_shufps, EA_16BYTE, targetReg, targetReg, (int8_t)0xb1);
```
Comment (tannergooding) [inline src/jit/codegenxarch.cpp]: I believe I've caught the cases that are doing this for the SIMD instructions, but it looks like we frequently pass in unsigned values to `ival`. I wonder if there are other cases where such inputs are incorrectly interpreted as "does not fit in a byte".

File: src/jit/emitxarch.cpp [hunk 6]
```diff
@@ -2122,7 +2226,7 @@ UNATIVE_OFFSET emitter::emitInsSizeAM(instrDesc* id, code_t code)
         size += emitGetRexPrefixSize(ins);
     }
     else if (IsExtendedReg(reg, EA_PTRSIZE) || IsExtendedReg(rgx, EA_PTRSIZE) ||
-             ((ins != INS_call) && IsExtendedReg(id->idReg1(), attrSize)))
+             ((ins != INS_call) && (IsExtendedReg(id->idReg1(), attrSize) || IsExtendedReg(id->idReg2(), attrSize))))
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: We should never be in a case where `idReg3` or `idReg4` are set for the addressing mode instructions (AM, SV, or CV). The instruction descriptor also doesn't allow this since those slots are used for the index and base registers in those cases.

File: src/jit/emitxarch.cpp [hunk 7]
```diff
@@ -2290,12 +2395,17 @@ inline UNATIVE_OFFSET emitter::emitInsSizeAM(instrDesc* id, code_t code, int val
     {
         valSize = sizeof(char);
     }
+    else
+    {
+        assert(!IsSSEOrAVXInstruction(ins));
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: These should catch any remaining places where we are incorrectly passing in an unsigned value > 127 to `ival`

File: src/jit/emitxarch.cpp [hunk 8]
```diff
@@ -3670,7 +3785,9 @@ void emitter::emitIns_R_I(instruction ins, emitAttr attr, regNumber reg, ssize_t
             {
                 if (IsSSEOrAVXInstruction(ins))
                 {
-                    sz = 5;
+                    sz = emitInsSize(insCodeMI(ins));
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: This should probably be a call to `emitInsSizeRR(id, insCodeMI(ins), val)`, but it would have required more refactorings to properly initialize `id` before these calls.

File: src/jit/emitxarch.cpp [hunk 9]
```diff
@@ -3956,21 +4053,44 @@ void emitter::emitIns_R_R_I(instruction ins, emitAttr attr, regNumber reg1, regN
...
-    }
-
     id->idIns(ins);
     id->idInsFmt(IF_RRW_RRW_CNS);
     id->idReg1(reg1);
     id->idReg2(reg2);
+
+    code_t code = 0;
+
+    switch (ins)
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: I grepped for all the callers to `emitIns_R_R_I` and believe I have them all covered. Most direct callers are either from simdcodegen or hwintrinsiccodegen. Most indirect callers go through `RV_RV_IV`, which itself has an assert on which instructions it should see.

File: src/jit/emitxarch.cpp [hunk 10]
```diff
@@ -4069,13 +4183,6 @@ void emitter::emitIns_R_A_I(instruction ins, emitAttr attr, regNumber reg1, GenT
     emitHandleMemOp(indir, id, IF_RRW_ARD_CNS, ins);
 
     UNATIVE_OFFSET sz = emitInsSizeAM(id, insCodeRM(ins), ival);
-
-    if (Is4ByteSSEInstruction(ins))
-    {
-        // The 4-Byte SSE instructions require two additional bytes
-        sz += 2;
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: These ones were 2 additional bytes to account for the ival.

File: src/jit/emitxarch.cpp [hunk 11]
```diff
@@ -4462,7 +4542,39 @@ void emitter::emitIns_R_R_R_I(
...
+
+    switch (ins)
+    {
+        case INS_pextrb:
+        case INS_pextrd:
+        case INS_pextrq:
+        case INS_pextrw_sse41:
+        case INS_extractps:
+        case INS_vextractf128:
+        case INS_vextracti128:
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: The only delta from `R_R_I` is that `INS_shld` and `INS_shrd` aren't included. They should never be hit though since this is only called for AVX instructions.

File: src/jit/emitxarch.cpp (hunk 3 above)
Comment (tannergooding) [reply src/jit/emitxarch.cpp]: I ended up having to centralize various checks to ensure that we aren't underestimating and that we also don't egregiously overestimate.

File: src/jit/emitxarch.h [hunk 12]
```diff
@@ -40,10 +40,11 @@ struct CnsVal
 };
 
 UNATIVE_OFFSET emitInsSize(code_t code);
-UNATIVE_OFFSET emitInsSizeRM(instruction ins);
```
Comment (CarolEidt) [inline src/jit/emitxarch.h]: As far as I can tell, this was previously unused? I was trying to figure out how the new `emitInsSizeRR` overloads replaced it.

File: src/jit/emitxarch.cpp [hunk 13]
```diff
@@ -1740,9 +1747,68 @@ inline UNATIVE_OFFSET emitter::emitInsSize(code_t code)
...
+
+    UNATIVE_OFFSET sz = emitInsSize(code);
+
+    sz += emitGetVexPrefixAdjustedSize(ins, attr, code);
+    sz += emitAdjustSizeCrc32(ins, attr);
+
+    // Most 16-bit operand instructions will need a prefix.
+    // This refers to 66h size prefix override.
+
+    if ((attr == EA_2BYTE) && (ins != INS_movzx) && (ins != INS_movsx))
```
[the remark this answers is not in the document]
Comment (CarolEidt) [reply src/jit/emitxarch.cpp]: Maybe that's best left for a future PR.

File: src/jit/emitxarch.h (hunk 12 above)
Comment (tannergooding) [reply src/jit/emitxarch.h]: Right, `git grep` showed zero usages.

File: src/jit/emitxarch.cpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/jit/emitxarch.cpp]: I need to add function headers as well, so I can just do this now...

**Comment by tannergooding** [comment]
> I'd really like to see diffs on this, especially given your last commit/comment.

`--corelib` had zero diffs.

`--frameworks` had the following:
```
Summary:
(Lower is better)
Total bytes of diff: -11 (-0.00% of base)
    diff is an improvement.
Top file regressions by size (bytes):
           4 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00% of base)
           4 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
Top file improvements by size (bytes):
          -4 : Microsoft.CodeAnalysis.CSharp.dasm (-0.00% of base)
          -4 : System.Collections.NonGeneric.dasm (-0.01% of base)
          -4 : System.Data.Common.dasm (-0.00% of base)
          -4 : System.Runtime.Numerics.dasm (-0.01% of base)
          -3 : Microsoft.CSharp.dasm (-0.00% of base)
7 total files with size differences (5 improved, 2 regressed), 122 unchanged.
Top method regressions by size (bytes):
           4 ( 2.23% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.XmlCharacterGlobalHelpers:UnicodeToUTF16(int):struct
           4 ( 0.36% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - Microsoft.Diagnostics.Tracing.Stacks.CallTree:AccumulateSumByID(ref,ref,struct):this
Top method improvements by size (bytes):
          -4 (-0.99% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Binder:CheckConstantBounds(byte,double):bool
          -4 (-1.02% of base) : System.Collections.NonGeneric.dasm - System.Collections.Queue:.ctor(int,float):this
          -4 (-0.23% of base) : System.Data.Common.dasm - System.Data.Common.UInt64Storage:Aggregate(ref,int):ref:this
          -4 (-0.67% of base) : System.Runtime.Numerics.dasm - System.Numerics.Complex:Sqrt(struct):struct
          -3 (-0.28% of base) : Microsoft.CSharp.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionBinder:bindConstantCast(ref,ref,bool,byref,bool):int:this
Top method regressions by size (percentage):
           4 ( 2.23% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.XmlCharacterGlobalHelpers:UnicodeToUTF16(int):struct
           4 ( 0.36% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - Microsoft.Diagnostics.Tracing.Stacks.CallTree:AccumulateSumByID(ref,ref,struct):this
Top method improvements by size (percentage):
          -4 (-1.02% of base) : System.Collections.NonGeneric.dasm - System.Collections.Queue:.ctor(int,float):this
          -4 (-0.99% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Binder:CheckConstantBounds(byte,double):bool
          -4 (-0.67% of base) : System.Runtime.Numerics.dasm - System.Numerics.Complex:Sqrt(struct):struct
          -3 (-0.28% of base) : Microsoft.CSharp.dasm - Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionBinder:bindConstantCast(ref,ref,bool,byref,bool):int:this
          -4 (-0.23% of base) : System.Data.Common.dasm - System.Data.Common.UInt64Storage:Aggregate(ref,int):ref:this
7 total methods with size differences (5 improved, 2 regressed), 248117 unchanged.
```

In all cases, the actual codegen didn't change we are just computing the size differently. The improvements all look to be cases where we were previously overpredicted the size by 2 and we now overpredict by 1 (which is the VEX-3 vs VEX-2 byte encoding difference). The two methods where we regressed are because there is a scenario around `mov` that we previously computed exactly and we now overpredict by 1.

The `--tests` scenario is still running.

**Comment by CarolEidt** [comment]
Thanks for running diffs!

> The two methods where we regressed are because there is a scenario around mov that we previously computed exactly and we now overpredict by 1.

I think you may have mentioned this, but have you characterized this scenario?

File: src/jit/emitxarch.cpp (hunk 4 above)
Comment (tannergooding) [reply src/jit/emitxarch.cpp]: Fixed.

File: src/jit/emitxarch.cpp [hunk 14]
```diff
@@ -1740,9 +1747,68 @@ inline UNATIVE_OFFSET emitter::emitInsSize(code_t code)
     return size;
 }
 
-inline UNATIVE_OFFSET emitter::emitInsSizeRM(instruction ins)
+inline UNATIVE_OFFSET emitter::emitInsSizeRR(instrDesc* id, code_t code)
```
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/jit/emitxarch.cpp]: Fixed.

File: src/jit/emitxarch.cpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (tannergooding) [reply src/jit/emitxarch.cpp]: I actually just moved this into `emitGetAdjustedSize`

File: src/jit/emitxarch.cpp [hunk 15]
```diff
@@ -2012,6 +2100,21 @@ inline UNATIVE_OFFSET emitter::emitInsSizeSV(instrDesc* id, code_t code, int var
         prefix += 1;
     }
 
+    // Most 16-bit operand instructions need a prefix
+    if (attrSize == EA_2BYTE && ins != INS_movsx && ins != INS_movzx)
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: @CarolEidt, this looks like the cause of the regression. Namely, this was meant to replace the check immediately preceding it here: https://github.com/dotnet/coreclr/pull/24555/files#diff-a51165bc1fd2c0fa3987370e2e714356R2098 (not be in addition to it).

I've fixed this in the latest changes, which I am testing and getting diffs for before pushing.

**Comment by tannergooding** [comment]
The latest fix now shows:
```
Analyzing diffs...
Found 7 files with textual diffs.
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: -19 (-0.00% of base)
    diff is an improvement.
Top file improvements by size (bytes):
          -4 : Microsoft.CodeAnalysis.CSharp.dasm (-0.00% of base)
          -4 : System.Collections.NonGeneric.dasm (-0.01% of base)
          -4 : System.Data.Common.dasm (-0.00% of base)
          -4 : System.Runtime.Numerics.dasm (-0.01% of base)
          -3 : Microsoft.CSharp.dasm (-0.00% of base)
5 total files with size differences (5 improved, 0 regressed), 124 unchanged.
Top method improvements by size (bytes):
          -4 (-0.99% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Binder:CheckConstantBounds(byte,double):bool
          -4 (-1.02% of base) : System.Collections.NonGeneric.dasm - Queue:.ctor(int,float):this
          -4 (-0.23% of base) : System.Data.Common.dasm - UInt64Storage:Aggregate(ref,int):ref:this
          -4 (-0.67% of base) : System.Runtime.Numerics.dasm - Complex:Sqrt(struct):struct
          -3 (-0.28% of base) : Microsoft.CSharp.dasm - ExpressionBinder:bindConstantCast(ref,ref,bool,byref,bool):int:this
Top method improvements by size (percentage):
          -4 (-1.02% of base) : System.Collections.NonGeneric.dasm - Queue:.ctor(int,float):this
          -4 (-0.99% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Binder:CheckConstantBounds(byte,double):bool
          -4 (-0.67% of base) : System.Runtime.Numerics.dasm - Complex:Sqrt(struct):struct
          -3 (-0.28% of base) : Microsoft.CSharp.dasm - ExpressionBinder:bindConstantCast(ref,ref,bool,byref,bool):int:this
          -4 (-0.23% of base) : System.Data.Common.dasm - UInt64Storage:Aggregate(ref,int):ref:this
5 total methods with size differences (5 improved, 0 regressed), 200725 unchanged.
2 files had text diffs but not size diffs.
System.Private.CoreLib.dasm had 1613 diffs
System.Numerics.Vectors.dasm had 22 diffs
Completed analysis in 22.93s
```

The cases where we are smaller all are cases where we now emit a `short jump` due to more accurately computing the instruction sizes.

The textual diffs are due to us printing `vdpps    xmm0, xmm1, -15` instead of `vdpps    xmm0, xmm1, 241` (since we are now ensuring that `fits in byte` returns true).

**Comment by tannergooding** [comment]
Sure thing @CarolEidt.

Do you know how to run the outer loop tests here? I want to run some of the additional tests (including the EnableAVX=0 tests) in CI as well, if possible (not quite sure what the new commands are, however).

**Comment by tannergooding** [comment]
Also, for reference: the framework diffs for `EnableAVX=0`:
```
Analyzing diffs...
Found 2 files with textual diffs.
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: -19 (-0.00% of base)
    diff is an improvement.
Top file improvements by size (bytes):
         -15 : System.Private.CoreLib.dasm (-0.00% of base)
          -4 : System.Numerics.Vectors.dasm (-0.01% of base)
2 total files with size differences (2 improved, 0 regressed), 127 unchanged.
Top method improvements by size (bytes):
          -9 (-0.39% of base) : System.Private.CoreLib.dasm - Sse:Shuffle(struct,struct,ubyte):struct
          -6 (-0.10% of base) : System.Private.CoreLib.dasm - X64:Insert(struct,long,ubyte):struct (2 methods)
          -4 (-2.27% of base) : System.Numerics.Vectors.dasm - Plane:Equals(ref):bool:this
Top method improvements by size (percentage):
          -4 (-2.27% of base) : System.Numerics.Vectors.dasm - Plane:Equals(ref):bool:this
          -9 (-0.39% of base) : System.Private.CoreLib.dasm - Sse:Shuffle(struct,struct,ubyte):struct
          -6 (-0.10% of base) : System.Private.CoreLib.dasm - X64:Insert(struct,long,ubyte):struct (2 methods)
3 total methods with size differences (3 improved, 0 regressed), 200727 unchanged.
Completed analysis in 20.18s
```

**Comment by tannergooding** [comment]
Figured it out. You have to manually trigger several of the outerloop tests by finding the build definition and then setting the branch appropriately (`refs/pull/<prNumber>/head`).

It also looks like we still don't have any outerloop legs for the `EnableISA=0` configurations.
