### PR TITLE
Fix initialization of resolution sets

### LINKED ISSUE #8824: [RyuJIT/x86/Checked] ngen dump assert
On the last build when I try to execute `coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root>crossgen.exe System.Private.CoreLib.dll  with complus_ngendump=* `
I see:
```
RESOLVING BB BOUNDARIES
-----------------------
Resolution Candidates:
Assert failure(PID 14924 [0x00003a4c], Thread: 17084 [0x42bc]): Assertion failed 'varNum < comp->lvaCount' in 'SR:get_ArgumentOutOfRange_Enum():ref' (IL size 11)

    File: c:\git\coreclr\src\jit\compiler.cpp Line: 8106
    Image: C:\git\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\crossgen.exe
```
x64 works fine. Looks like it is a fresh problem.

### PR DESCRIPTION
**Pull request by CarolEidt**
This was causing a failure during dumping.
Fixing it exposed another dumping failure in crossgen of System.Private.Corelib.dll on x86, due to a dead node. I've fixed the assert, but I believe the dead node should have been eliminated. I filed issue #8839 for this.

Fix #8824

### CODE REVIEW

**Comment by CarolEidt** [comment]
@sivarv @dotnet/jit-contrib PTAL

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -1914,6 +1914,8 @@ bool LinearScan::isRegCandidate(LclVarDsc* varDsc)
 
 void LinearScan::identifyCandidates()
 {
+    VarSetOps::AssignNoCopy(compiler, resolutionCandidateVars, VarSetOps::MakeEmpty(compiler));
```
Comment (mikedn) [inline src/jit/lsra.cpp]: Any reason this cannot be done in the class constructor or do you prefer having these here?

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -10412,11 +10412,21 @@ void LinearScan::lsraDispNode(GenTreePtr tree, LsraTupleDumpMode mode, bool hasD
...
-            // This can be true for the "localDefUse" case - defining a reg, but
-            // pushing it on the stack
-            assert(spillChar == ' ');
-            spillChar = '*';
-            hasDest   = true;
+            // A node can define a register, but not produce a value for a parent to consume,
+            // i.e. in the "localDefUse" case.
+            // There used to be an assert here that we wouldn't spill such a node.
+            // However, we can have unused lclVars that wind up being the node at which
+            // it is spilled. This probably indicates a bug, but we don't realy want to
```
Comment (sivarv) [inline src/jit/lsra.cpp]: Nit: Typo "realy" instead of "really"

**Comment by sivarv** [comment]
Looks good.

**Comment by sivarv** [comment]
Ubuntu x64 leg has a failure: GC.Scenarios.DoublinkList.doublinkgen.doublinkgen
I remember seeing failure of this test in the recent past too intermittently.
Not sure whether that failure is related to this PR or another instance of intermittent failure.  If it is latter, please file a tracking issue.

**Comment by mikedn** [comment]
> Not sure whether that failure is related to this PR or another instance of intermittent failure. If it is latter, please file a tracking issue.

Already there: #6574

File: src/jit/lsra.cpp (hunk 1 above)
Comment (CarolEidt) [inline src/jit/lsra.cpp]: > Any reason this cannot be done in the class constructor or do you prefer having these here?

Took me awhile to track this down but it can't be done in the constructor because at that point the set of tracked lclVars hasn't been finalized, so the epoch on the bit sets doesn't match. I've added a comment.

Comment (CarolEidt) [inline src/jit/lsra.cpp]: > Any reason this cannot be done in the class constructor or do you prefer having these here?

Took me awhile to track this down but it can't be done in the constructor because at that point the set of tracked lclVars hasn't been finalized, so the epoch on the bit sets doesn't match. I've added a comment.

**Comment by CarolEidt** [comment]
> Any reason this cannot be done in the class constructor or do you prefer having these here?

Took me awhile to track this down but it can't be done in the constructor because at that point the set of tracked lclVars hasn't been finalized, so the epoch on the bit sets doesn't match. I've added a comment.
