### PR TITLE
Correctly marshal structure return values in member functions on Win-x64 and Win-x86

### LINKED ISSUE #19474: Unexpected results returning struct with floats in RCW
In trying to wrap [`ID2D1RenderTarget::GetSize`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd316823(v=vs.85).aspx) which returns [`D2D_SIZE_F`] the expected way it would corrupt the stack.

Flipping it to an out parameter made it work, but I'm unclear as to why. Discussing with @davidwrighton, there might be a bug here. I was unable to create the same scenario via straight `[DllImport]`s against a sample project. I'll see if I can get a smaller repro together.

In `d2d1.h` it is defined as:

``` C++
STDMETHOD_(D2D1_SIZE_F, GetSize)(
    ) CONST PURE;
```

Which expands to:

``` C++
virtual __declspec(nothrow) D2D1_SIZE_F __stdcall GetSize() const = 0;
```

The struct is:

``` C++
typedef struct D2D_SIZE_F
{
    FLOAT width;
    FLOAT height;
} D2D_SIZE_F;
```

I wrapped this [here](https://github.com/JeremyKuhne/WInterop/blob/e41811b230bd332b9ead669542339e7d982d487a/src/WInterop.DirectX/Direct2d/IRenderTarget.cs#L436-L437) (`SizeF` is from System.Drawing):

``` C#
[PreserveSig]
void GetSize(out SizeF size);

// Doesn't Work:
// [PreserveSig]
// SizeF GetSize();
```

In the WInterop project I have a test `Direct2dTests.RenderTarget.GetSize()` that exercises it. One can also look at this by tweaking the Direct2dDemo project (i.e. call the method) which runs on .NET Core and sets up a render target that you can use.

As stated, I'll try and get a smaller COM repro together for this.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
On Windows x86 and x64, if we have a native member function signature with a struct return type, we need to do a by-ref return.

Superscedes #19643
Fixes #19474.

### CODE REVIEW

File: tests/src/Interop/COM/ServerContracts/Server.Contracts.cs [hunk 1]
```diff
@@ -11,6 +11,18 @@ namespace Server.Contract
     using System.Runtime.InteropServices;
     using System.Text;
 
+    public struct SizeF
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/COM/ServerContracts/Server.Contracts.cs]: Can we use the HFA type instead?

File: src/vm/ilmarshalers.h [hunk 2]
```diff
@@ -599,14 +599,21 @@ class ILMarshaler
...
-#if defined(_TARGET_X86_)
+#if defined(_TARGET_X86_) || (defined(_TARGET_AMD64_) && defined(_WIN32))
             // JIT32 and JIT64 (which is only used on the Windows Desktop CLR) has a problem generating
             // code for the pinvoke ILStubs which do a return using a struct type.  Therefore, we
             // change the signature of calli to return void and make the return buffer as first argument. 
 
             // for X86 and AMD64-Windows we bash the return type from struct to U1, U2, U4 or U8
             // and use byrefNativeReturn for all other structs.
             // for UNIX_X86_ABI, we always need a return buffer argument for any size of structs.
+#if defined(_TARGET_AMD64_) && defined(_WIN32)
```
Comment (jkotas) [inline src/vm/ilmarshalers.h]: Why to limit this to AMD64 & WIN32 only? The problem exists on ARM or Unix too, I think.

Comment (jkoritzinsky) [reply src/vm/ilmarshalers.h]: I don't believe that this problem exists on ARM or Unix. It's a weird corner case of the Windows x86/x64 calling conventions for member functions. And the SystemV ABI has more complex rules for return values that have to be dealt with in the SystemV classifier/the JIT (which I believe is already implemented there). And as far as I can tell from a test I did on Compiler Explorer, I think Windows x64 is the only 64-bit platform to pass a hidden buffer argument: https://godbolt.org/z/owtpm8. I can't check Windows x64 ARM though so I'll try to test that locally.

File: tests/src/Interop/COM/ServerContracts/Server.Contracts.cs [hunk 3]
```diff
@@ -11,6 +11,18 @@ namespace Server.Contract
...
+    {
+        public float width;
```
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply tests/src/Interop/COM/ServerContracts/Server.Contracts.cs]: The interesting parts here are struct sizes above and below 4 bytes from my experience with SharpGenTools.

File: src/vm/ilmarshalers.h [hunk 4]
```diff
@@ -599,14 +599,21 @@ class ILMarshaler
...
+            if (m_pslNDirect->TargetHasThis() && IsCLRToNative(m_dwMarshalFlags))
+            {
+                byrefNativeReturn = true;
+            }
+            else
```
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply src/vm/ilmarshalers.h]: I could wrap in it brackets and wrap the closing bracket in another ifdef if you think that would be clearer.

File: src/vm/dllimport.cpp [hunk 5]
```diff
@@ -3953,11 +3958,16 @@ static void CreateNDirectStubWorker(StubState*         pss,
     // Normally we would like this to be false so that we use the correct signature 
     // in the IL_STUB, (i.e if it returns a value class then the signature will use that)
     // When this bool is true we change the return type to void and explicitly add a
-    // return buffer argument as the first argument.
+    // return buffer argument as the first argument so as to match the native calling convention correctly.
     BOOL fMarshalReturnValueFirst = false;
```
Comment (AaronRobinsonMSFT) [inline src/vm/dllimport.cpp]: `FALSE`

File: src/vm/dllimport.cpp [hunk 6]
```diff
@@ -3975,9 +3985,16 @@ static void CreateNDirectStubWorker(StubState*         pss,
 #else // UNIX_X86_ABI
         fMarshalReturnValueFirst = HasRetBuffArg(&msig);
 #endif // UNIX_X86_ABI
-
+#elif defined(_WIN32) && defined(_TARGET_AMD64_)
+        fMarshalReturnValueFirst = SF_IsCOMStub(dwStubFlags) && msig.GetReturnType() == ELEMENT_TYPE_VALUETYPE;
```
Comment (AaronRobinsonMSFT) [inline src/vm/dllimport.cpp]: `SF_IsCOMStub(dwStubFlags)` is called above and provided to the base class. Can we tie them together?

File: src/vm/stubgen.h [hunk 7]
```diff
@@ -503,13 +502,24 @@ class ILStubLinker
     void SetStubTargetReturnType(CorElementType typ);
     void SetStubTargetReturnType(LocalDesc* pLoc);
     void SetStubTargetCallingConv(CorCallingConvention uNativeCallingConv);
+    
+    int GetReturnStackDelta()
+    {
+        if ((!m_fIsReverseStub && m_StubHasVoidReturnType) || (m_fIsReverseStub && m_StubTargetHasVoidReturnType))
```
Comment (AaronRobinsonMSFT) [inline src/vm/stubgen.h]: This function only returns 1 of 2 values. Can we return a boolean or rework how we get the information?

File: src/vm/dllimport.cpp [hunk 8]
```diff
@@ -3661,42 +3666,19 @@ static MarshalInfo::MarshalType DoMarshalReturnValue(MetaSig&           msig,
...
                 marshalType == MarshalInfo::MARSHAL_TYPE_GUID ||
                 marshalType == MarshalInfo::MARSHAL_TYPE_DECIMAL)
             {
-#ifndef _TARGET_X86_
-                // We cannot optimize marshalType to MARSHAL_TYPE_GENERIC_* because the JIT works with exact types
-                // and would refuse to compile the stub if it implicitly converted between scalars and value types (also see
-                // code:MarshalInfo.MarhalInfo where we do the optimization on x86). We want to throw only if the structure
-                // is too big to be returned in registers.
-                if (marshalType != MarshalInfo::MARSHAL_TYPE_BLITTABLEVALUECLASS ||
-                    IsUnmanagedValueTypeReturnedByRef(returnInfo.GetNativeArgSize()))
```
Comment (jkoritzinsky) [inline src/vm/dllimport.cpp]: `returnInfo.GetNativeArgSize()` isn't set up before this, so it was always returning 0, which effectively made this condition equivalent to `marshalType != MarshalInfo::MARSHAL_TYPE_BLITTABLEVALUECLASS`. So I've simplified the condition and combined it with the below failure condition.

File: tests/src/Interop/COM/NETClients/Primitives/NumericTests.cs [hunk 9]
```diff
@@ -200,5 +201,39 @@ private void Marshal_ManyInts()
             Console.WriteLine($"{expected.GetType().Name} 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = {expected}");
             Assert.IsTrue(expected == this.server.Add_ManyInts12(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12));
         }
+
+        private void Marshal_Struct_Return()
```
Comment (tannergooding) [inline tests/src/Interop/COM/NETClients/Primitives/NumericTests.cs]: Does this bug also exist for a `DllImport(CallingConvention.ThisCall)`, is it worth explicitly testing?
* More specifically wondering about the case where a user manually declares a COM VTBL and marshals the function pointer (or, eventually, when using the function pointer feature in C#).

Comment (jkoritzinsky) [reply tests/src/Interop/COM/NETClients/Primitives/NumericTests.cs]: I'll take a look.  I have a feeling that the bug will also exist for `ThisCall` and that I'll need a slightly more involved fix for that.

Comment (jkoritzinsky) [reply tests/src/Interop/COM/NETClients/Primitives/NumericTests.cs]: I've added in a test case and a fix for `thiscall` functions.

**Comment by jkoritzinsky** [comment]
Apparently Ubuntu ARM32 treats returning pointer-to-member-functions differently than pointer-to-nonmember-functions, which is what is causing the Ubuntu ARM32 leg to fail.

Pointers to nonmember functions don't require a return buffer, but pointers to member functions do. I'll see if I can figure out a good way to fit the "is instance method" check in the right place without making the code significantly messy.

**Comment by jkoritzinsky** [comment]
I had forgotten that pointer-to-member functions were really weird (i.e. they aren't actually functions and their layout is implementation defined) which was causing the issue on Ubuntu ARM. So, I've changed the test to dereference into the native vtable of a native object so I can make sure I actually get a function pointer for the test.

File: src/vm/ilmarshalers.h (hunk 2 above)
Comment (jkoritzinsky) [reply src/vm/ilmarshalers.h]: I've verified that ARM32 doesn't have this problem.

**Comment by jkotas** [comment]
Do we have ability to run IJW test suite from the C++ compiler team? It has extensive coverage for the thiscall calling convention. It may be worth running it on this change (on both x86 and x64).

**Comment by jkoritzinsky** [comment]
We'd have to port over each test individually into our test tree and set it up to run like we currently run IJW tests. So it's possible, but not simple copy-paste.

File: src/vm/dllimport.cpp [hunk 10]
```diff
@@ -3953,14 +3931,21 @@ static void CreateNDirectStubWorker(StubState*         pss,
...
+    // Since the managed return type is actually the last parameter, we need to marshal it after the last parameter in the managed signature
+    // to make sure we match the native signature correctly (when marshalling parameters, we add them to the native stub signature).
     if (!SF_IsHRESULTSwapping(dwStubFlags))
     {
-
+        bool isInstanceMethod = fStubNeedsCOM || fThisCall;
+        // We cannot just use pSig.GetReturnType() here since it will return ELEMENT_TYPE_VALUETYPE for enums.
+        bool isReturnTypeValueType = msig.GetRetTypeHandleThrowing().GetVerifierCorElementType() == ELEMENT_TYPE_VALUETYPE;
 #if defined(_TARGET_X86_) || defined(_TARGET_ARM_)
         // JIT32 has problems in generating code for pinvoke ILStubs which do a return in return buffer.
```
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply src/vm/dllimport.cpp]: I have not looked into the JIT side of this yet. I'll investigate to see if RyuJIT fixed some of this.

**Comment by jkotas** [comment]
I did not mean to port the tests over. I meant to run the tests from the managed C++ compiler test suite where they currently are. I believe the C++ compiler team has ability to do that - otherwise, they would not be able to sign off on .NET Core support for managed C++.

**Comment by jkoritzinsky** [comment]
We can't run the managed C++ compiler test suite in mixed-mode currently until we get #22636 and dotnet/core-setup#5185 both merged in and the C++ compiler team updates the compiler to link to the new `ijwhost.dll` unless we want to bin-edit the test binaries to point to ijwhost instead of mscoree.

File: src/vm/dllimport.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (jkoritzinsky) [reply src/vm/dllimport.cpp]: RyuJIT has not done any work to fix this, presumably since the interop space was already working around the limitation when RyuJIT was created.

@dotnet/jit-contrib any ideas on what it would take to support the easy case of x86 return buffers for non-member functions?

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0)
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by jkoritzinsky** [comment]
@dotnet-bot dn-bot@microsoft.com Linked test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by jkoritzinsky** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test

**Comment by jkoritzinsky** [comment]
Test failures are due to #23534 as far as I can tell.

I'm going to merge this in and file a tracking issue for moving some of the return-buffer logic to the JIT.
