### PR TITLE
Remove LOCK_WRITE enum value (in pal/inc/rt/objidl.h) because it conflicts with fcntl.h on Linux (#27386)

### LINKED ISSUE #27386: LOCK_WRITE enum value (in pal/inc/rt/objidl.h) conflicts with fcntl.h on Linux
Hi!

Is there anything we can do? @jkotas 

```
.../pal/inc/rt/objidl.h:106:7: error: expected identifier
    {   LOCK_WRITE      = 1,
        ^
/usr/include/x86_64-linux-gnu/bits/fcntl-linux.h:240:21: note: expanded from macro 'LOCK_WRITE'
# define LOCK_WRITE     128     /* ... which allows concurrent write operations.  */
                        ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by k15tfu**
Remove LOCK_WRITE enum value (in pal/inc/rt/objidl.h) because it conflicts with fcntl.h on Linux

It also completely removes LOCKTYPE enum.

Fixes #27386

### CODE REVIEW

File: src/pal/inc/rt/objidl.h [hunk 1]
```diff
@@ -101,12 +101,12 @@ enum tagSTREAM_SEEK
...
-    {	LOCK_WRITE	= 1,
-	LOCK_EXCLUSIVE	= 2,
-	LOCK_ONLYONCE	= 4
-    } 	LOCKTYPE;
+//typedef 
+//enum tagLOCKTYPE
+//    {	LOCK_WRITE	= 1,
+//	LOCK_EXCLUSIVE	= 2,
+//	LOCK_ONLYONCE	= 4
+//    } 	LOCKTYPE;
```
Comment (lpereira) [inline src/pal/inc/rt/objidl.h]: You can safely remove these lines here; no need to keep unused code commented-out.  (Version control allows this to be easily found and reverted if needed.)

Comment (jkotas) [reply src/pal/inc/rt/objidl.h]: Yes, feel free to delete the whole thing.

Comment (k15tfu) [reply src/pal/inc/rt/objidl.h]: Done.
