### PR TITLE
Curtail loop unroller epliog generation

### LINKED ISSUE #8179: RyuJIT/x86: Assert failure(PID 14212 [0x00003784], Thread: 6096 [0x17d0]): m_CodeHeader == 0...
**Repro (windows):**
```
build x86 checked
tests\runtest x86 checked generatelayoutonly
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
cd bin\tests\Windows_NT.x86.Checked\JIT\Directed\StructABI\StructABI
structabi.cmd -coreroot <coreroot>
```

**Output:**
<details>
BEGIN EXECUTION
 "c:\git\coreclr\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" StructABI.exe

Assert failure(PID 14212 [0x00003784], Thread: 6096 [0x17d0]): m_CodeHeader == 0 && "Note that this may fire if the JITCompiler tries to recompile a method"

CORECLR! CEEJitInfo::allocMem + 0x189 (0x656ed259)
PROTOJIT! emitter::emitEndCodeGen + 0x159 (0x62a77b66)
PROTOJIT! CodeGen::genGenerateCode + 0x34E (0x62a6294e)
PROTOJIT! Compiler::compCompile + 0x6A7 (0x62a6d337)
PROTOJIT! Compiler::compCompileHelper + 0x574 (0x62a6e4bc)
PROTOJIT! `Compiler::compCompile'::`43'::__Body::Run + 0x64 (0x62a6a5dc)
PROTOJIT! Compiler::compCompile + 0x5E7 (0x62a6d9c5)
PROTOJIT! ``jitNativeCode'::`11'::__Body::Run'::`6'::__Body::Run + 0x102 (0x62a6a527)
PROTOJIT! `jitNativeCode'::`11'::__Body::Run + 0x73 (0x62a6a6a0)
PROTOJIT! jitNativeCode + 0xE7 (0x62a71b4d)
    File: c:\git\coreclr\src\vm\jitinterface.cpp Line: 11677
    Image: c:\git\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
</details>

**Reference:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_ryujit_checked_windows_nt_jitstress2/7/testReport/

### PR DESCRIPTION
**Pull request by JosephTremoulet**
The Jit32 GC encoder puts a hard limit on the number of epilogs (at 4); in
this configuration, avoid unrolling any loops containing enough BBJ_RETURN
blocks to push us over that limit, the same way loop cloning is limited.

Also remove an unnecessary loop flag update to set DONT_UNROLL on some
unprofitable loops -- the loop unroller logic has been rearranged to avoid
reprocessing loops in the first place.

Fixes #8179.

Also includes a change to the overflow check in unroll cost calculation to
perform the subtraction on signed rather than unsigned ints; if the unroll
size is actually smaller than the fixed size estimate, unrolling is
profitable.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@BruceForstall, @dotnet/jit-contrib PTAL

**Comment by JosephTremoulet** [comment]
@dotnet-bot help

File: src/jit/optimizer.cpp [hunk 1]
```diff
@@ -3063,19 +3070,25 @@ void Compiler::optUnrollLoops()
                 }
             }
 
+#ifdef JIT32_GCENCODER
+            if (fgReturnCount + loopRetCount > 4)
```
Comment (BruceForstall) [inline src/jit/optimizer.cpp]: It would be nice if we could convert this "4" as well as the one in loop cloning (and anywhere else we can find it) to something named, like MAX_GCENCODER_EPILOGS, either defined under JIT32_GCENCODER, or differently (possibly?) for all platforms. Note that loop cloner still restricts to 4 even for x64.

**Comment by BruceForstall** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
How does a loop contain a return block? Seems like any such block would have to be outside the loop.

**Comment by JosephTremoulet** [comment]
@AndyAyersMS,  we have a constraint that we only recognize loops that are a contiguous sequence of blocks, so considering return blocks as part of the loop allows us to recognize more of them (without reordering blocks as part of loop recognition), is I think the reason we see this.

**Comment by JosephTremoulet** [comment]
@dotnet-bot help

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
I've noticed elsewhere that the jit seems to think about block layout too early. Not sure if we've run block placement or not when we unroll, but moving non-loop blocks out of the span of blocks in the loop sure seems like something worth considering.

**Comment by JosephTremoulet** [comment]
Pretty sure we have not run block placement yet, think the appeal is (A) so loop containment checks can be implemented as range checks on block numbers and (B) so loop detection itself can be a single pass using forward/backward branch heuristics, and yes I agree that it seems rearranging blocks and properly detecting SCCs would be good ideas.

**Comment by JosephTremoulet** [comment]
It turns out we already have a named constant for this, and also that I somehow neglected to multiply the return count by the iteration count; updated to check if `fgReturnCount + loopRetCount * (totalIter - 1) > SET_EPILOGCNT_MAX`.

**Comment by JosephTremoulet** [comment]
@dotnet-bot help

**Comment by JosephTremoulet** [comment]
Go go gadget @dotnet-bot?

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build
@dotnet-bot test Windows_NT arm Cross Debug Build
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test (Jit - JitStress=2)

**Comment by JosephTremoulet** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
