### PR TITLE
Use root compiler instance for inline result and policy

### LINKED ISSUE #3760: Inliner policy inconsistency under JitStress causes asserts
The JitStress failures uncovered when testing #3697 are a pre-existing issue. 

The inliner will use two different compiler instances to evaluate an inline candidate. The initial candidacy scan is done by the inlinee compiler instance, and the final scan is done by the root compiler instance. If these two instances have different policies (or different variants of the same policy) then a method that was a candidate during the initial scan can unexpectedly become a non-candidate at the start of the final scan. 

For instance, if the inlinee instance is using the LegacyPolicy under stress, any method with < 1000 bytes of IL is a potential candidate. Then if the root compiler is using LegacyPolicy but not under stress, this threshold drops back to 100 bytes.

This shows up as an `m_isPrejitRoot` assert in `SetNever` or `SetFailure` because in the second scan the replay of the forceinline and IL size observations disqualifies the candidate, but we don't expect those to change candidacy (just re-establish what we already knew from the initial scan) and so we go on making more observations. If one of those can also cause the inline to fail, we hit the assert.

The best fix is to ensure that we're always using the same policy and variant to evaluate the candidates.

@RussKeldorph I think this may be the problem you noticed back in #3586. Since I'd seen a this same assert in other places and was fixing it (see #3592) I didn't realize there were other ways to trigger this.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When constructing an InlineResult (and subsequent InlinePolicy)
always use the root compiler instance, so that all policy evaluations
done in a method are consistent.

Add an assert that the initial fact replay during `fgFindJumpTargets`
(force inline state and code size) doesn't change the candidacy when
inlining -- it should just be re-establishing what we knew in the
initial candidate scan.

Closes #3760.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@kyulee1 PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Adding in a stress run: @dotnet-bot test Windows_NT jitstress2

**Comment by AndyAyersMS** [comment]
@mmitche FYI hitting GitHub rate limits....
```
00:01:35.540 Unable to query GitHub for status of PullRequestjava.io.IOException: {
00:01:35.540   "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
00:01:35.540   "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
00:01:35.540 }
```

**Comment by AndyAyersMS** [comment]
Seeing if github has relented: @dotnet-bot retest Windows_NT x64 Release Build and Test

**Comment by AndyAyersMS** [comment]
Seeing if github has relented: @dotnet-bot retest Windows_NT x86 Release Legacy Backend Build and Test

**Comment by AndyAyersMS** [comment]
Restarting the rest of the borked test legs.
@dotnet-bot retest FreeBSD x64 Checked Build 
@donet-bot retest OSX x64 Checked Build and Test 
@donet-bot retest Ubuntu x64 Checked Build and Test 
@donet-bot retest Windows_NT x86 Debug Legacy Backend Build and Test

File: src/jit/inline.cpp [hunk 1]
```diff
@@ -527,14 +527,14 @@ void InlineContext::Dump(Compiler* compiler, int indent)
 // for inlining.
 //
 // Arguments
-//   compiler - the compiler instance examining an call for ininling
+//   compiler - the compiler instance examining an call for inlining
```
Comment (kyulee1) [inline src/jit/inline.cpp]: Nit: an call -> a call

**Comment by kyulee1** [comment]
LGTM

File: src/jit/inline.h [hunk 2]
```diff
@@ -447,10 +447,10 @@ class InlineResult
     // Report/log/dump decision as appropriate
     void Report();
 
-    Compiler*               m_Compiler;
+    Compiler*               m_Compiler;   // root compiler instance
     InlinePolicy*           m_Policy;
```
Comment (BruceForstall) [inline src/jit/inline.h]: I wonder if this (and all other related cases in this class, such as the constructor) should rename it m_RootCompiler to make this clear. Your call.

File: src/jit/flowgraph.cpp [hunk 3]
```diff
@@ -4222,6 +4222,16 @@ void Compiler::fgFindJumpTargets(const BYTE* codeAddr,
         compInlineResult->NoteBool(InlineObservation::CALLEE_IS_FORCE_INLINE, isForceInline);
         compInlineResult->NoteInt(InlineObservation::CALLEE_IL_CODE_SIZE, codeSize);
 
+#ifdef DEBUG
+
+        // If inlining, this method should still be a candidate.
+        if (compIsForInlining())
+        {
+            assert(compInlineResult->IsCandidate());
+        }
```
Comment (BruceForstall) [inline src/jit/flowgraph.cpp]: you could do this on one line, without #ifdef, with:
  assert(!compIsForInlining() || compInlineResult->IsCandidate());
just to reduce the number of #ifdefs in the code.

**Comment by BruceForstall** [comment]
LGTM

File: src/jit/flowgraph.cpp (hunk 3 above)
Comment (AndyAyersMS) [inline src/jit/flowgraph.cpp]: I had it that way, but changed it. 

I'm not really a fan of compound conditions in asserts (especially so when calls are involved), since it's more pain to untangle which part went wrong when debugging.

File: src/jit/inline.h (hunk 2 above)
Comment (AndyAyersMS) [inline src/jit/inline.h]: Good idea, will do.

**Comment by AndyAyersMS** [comment]
Updated per review feedback.

File: src/jit/inline.cpp (hunk 1 above)
Comment (AndyAyersMS) [inline src/jit/inline.cpp]: Fixed.

**Comment by AndyAyersMS** [comment]
Adding in a stress run: @dotnet-bot test Windows_NT jitstress2

**Comment by BruceForstall** [comment]
LGTM
