### PR TITLE
Fix the scratch register used for arm64 stack probing

### LINKED ISSUE #22284: [arm64\windows]Tests failed in arm64_cross_checked_windows_nt_r2r_jitstressregs1_tst
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_r2r_jitstressregs1_tst/37/
**Failed tests:**
JIT_jit64._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_cmd
JIT_jit64._hfa_main_testC_hfa_sf1C_r_hfa_sf1C_r_._hfa_main_testC_hfa_sf1C_r_hfa_sf1C_r_cmd
JIT_jit64._hfa_main_testC_hfa_sf0C_r_hfa_sf0C_r_._hfa_main_testC_hfa_sf0C_r_hfa_sf0C_r_cmd
JIT_jit64._hfa_main_testC_hfa_sd0C_r_hfa_sd0C_r_._hfa_main_testC_hfa_sd0C_r_hfa_sd0C_r_cmd
**Failed log:**
```
JIT_jit64._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\Reports\JIT.jit64\hfa\main\testC\hfa_sd1C_r\hfa_sd1C_r.output.txt
  Raw output:
  BEGIN EXECUTION
        
        C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r>set COMPLUS_NOGUIONASSERT=1 
        
        C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r>set COMPLUS_CONTINUEONASSERT=0 
        
        C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r>set COMPLUS_TIEREDCOMPILATION=0 
        
        C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r>set COMPLUS_JITSTRESSREGS=1 
                1 file(s) copied.
        " C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\crossgen.exe"  /Platform_Assemblies_Paths C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root;C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r\IL;C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r /in hfa_sd1C_r.org /out hfa_sd1C_r.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Native image hfa_sd1C_r.exe generated successfully.
         "C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" hfa_sd1C_r.exe 
        [Average HFA 01]	PASSED
        [Average HFA 02]	PASSED
        [Average HFA 03]	PASSED
        [Average HFA 05]	PASSED
        [Average HFA 08]	PASSED
        [Average HFA 11]	PASSED
        [Average HFA 19]	PASSED
        [Average3 HFA 01]	PASSED
        [Average3 HFA 02]	PASSED
        [Average3 HFA 03]	PASSED
        [Average3 HFA 05]	PASSED
        [Average3 HFA 08]	PASSED
        [Average3 HFA 11]	PASSED
        [Average3 HFA 19]	PASSED
        [Average5 HFA 01]	PASSED
        [Average5 HFA 02]	PASSED
        [Average5 HFA 03]	PASSED
        [Average5 HFA 05]	PASSED
        [Average5 HFA 08]	PASSED
        [Average5 HFA 11]	PASSED
        [Average5 HFA 19]	PASSED
        [Average8 HFA 01]	PASSED
        [Average8 HFA 02]	PASSED
        [Average8 HFA 03]	PASSED
        [Average8 HFA 05]	PASSED
        [Average8 HFA 08]	PASSED
        [Average8 HFA 11]	PASSED
        [Average8 HFA 19]	PASSED
        [Average11 HFA 01]	PASSED
        [Average11 HFA 02]	PASSED
        [Average11 HFA 03]	PASSED
        [Average11 HFA 05]	PASSED
        [Average11 HFA 08]	PASSED
        [Average11 HFA 11]	PASSED
        [Average11 HFA 19]	PASSED
        [Average19 HFA 01]	PASSED
        [Average19 HFA 02]	PASSED
        [Average19 HFA 03]	PASSED
        [Average19 HFA 05]	PASSED
        [Average19 HFA 08]	PASSED
        [Average19 HFA 11]	PASSED
        [Average19 HFA 19]	PASSED
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root
  > C:\j\workspace\arm64_cross_c---bc4cc99d\bin\tests\Windows_NT.arm64.Checked\JIT\jit64\hfa\main\testC\hfa_sd1C_r\hfa_sd1C_r.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\arm64_cross_c---0aaef436\bin\tests\Windows_NT.arm64.Checked\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs(11239,0): at JIT_jit64._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_._hfa_main_testC_hfa_sd1C_r_hfa_sd1C_r_cmd()
```

### PR DESCRIPTION
**Pull request by BruceForstall**
In some circumstances, genFnProlog might pick a callee-saved
register to be the initReg. This doesn't work for stack probing
since we might need a scratch register before we save the
callee-save regs. In that case, choose R9 (REG_SCRATCH) instead.

Fixes #22284

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs8 Build and Test

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked r2r_jitstressregs1 Build and Test

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by CarolEidt** [comment]
Just curious - how painful was this to track down?

File: src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -3720,6 +3720,17 @@ void CodeGen::genAllocLclFrame(unsigned frameSize, regNumber initReg, bool* pIni
...
+    // For arm64, we are probing the frame *before* the callee-saved registers are saved. The 'initReg' might in fact
+    // have been calculated to be one of the callee-saved registers (say, if all the integer argument registers are
+    // in use, and perhaps with other conditions being satisfied). If that's true, then just use the REG_SCRATCH
+    // register instead. (We could probably just always use REG_SCRATCH.)
+    if ((genRegMask(initReg) & RBM_CALLEE_SAVED) != 0)
+    {
+        initReg = REG_SCRATCH;
+    }
+#endif // _TARGET_ARM64_
+
```
Comment (briansull) [inline src/jit/codegenarmarch.cpp]: I don't think that this is the best way to fix this issue.  This method is being told what extra register it should use when it needs one.  The caller has decided what the `initReg `should be and this method also writes back if it modifies the  initReg using `*pInitRegZeroed `

This method should instead assert that the `initReg` is a scratch register and the selection logic should avoid picking a callee save register.  

Another option is to remove the two parameters `regNumber initReg, bool* pInitRegZeroed,` from this method as it is not adding any real benefit here.

Comment (BruceForstall) [reply src/jit/codegenarmarch.cpp]: It's ok to pick a callee-saved register as initReg for all other uses of initReg, which are all _after_ callee-saved regs have been saved. This function is also used by arm32, which uses initReg.

It's true that in my changed code, if we use REG_SCRATCH on arm64, we will still set `*pInitRegZeroed = false`, indicating that the passed-in initReg is trashed, which isn't strictly true, but isn't harmful. It turns out that arm64 _never_ sets `*pInitRegZeroed = true`, since if it needs a zero reg it uses `REG_ZR`.

**Comment by BruceForstall** [comment]
> Just curious - how painful was this to track down?

Not fun :-) Those HFA tests can be huge, with inlining. Luckily, it was repeatable and failed on debug

**Comment by BruceForstall** [comment]
hmmm... my triggered jobs didn't get triggered?

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs8 Build and Test

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked r2r_jitstressregs1 Build and Test

**Comment by BruceForstall** [comment]
Jenkins disconnect. 

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs4 Build and Test

**Comment by BruceForstall** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs0x1000_tst_prtest/13/consoleFull showed:
```
10:58:43 
      baseservices_threading._regressions_beta2_437017_437017_._regressions_beta2_437017_437017_sh [FAIL]
10:58:43         
10:58:43 
        Assert failure(PID 6340 [0x000018c4], Thread: 6394 [0x18fa]): m_alignpad == 0
10:58:43             File: /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/vm/syncblk.cpp Line: 3450
10:58:43             Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs0x1000_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun
10:58:43         
10:58:43         /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs0x1000_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/regressions/beta2/437017/437017.sh: line 244:  6340 Aborted                 (core dumped)
```

which has been a "random" failure in many tests: https://github.com/dotnet/coreclr/issues/18047

Try again.

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x1000 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstress2_jitstressregs8 Build and Test

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked r2r_jitstressregs1 Build and Test

**Comment by BruceForstall** [comment]
@briansull I changed the code to always use `REG_SCRATCH`. Maybe it's a little simpler.

**Comment by BruceForstall** [comment]
The test failures are all https://github.com/dotnet/coreclr/issues/22253, except r2r_jitstressregs1, which fails with 137 failures -- and the baseline has many of these also. So that test job doesn't seem stable.

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Can someone review the updated change?
