### PR TITLE
Make sure that when the StringBuilder.Append method is called we firs…

### LINKED ISSUE #4514: StringBuilder.Append(char, int) can fail mid-way
var sb = new StringBuilder();

            sb.Append('x', 2);
            sb.Length--;

            try
            {
                sb.Append('x', int.MaxValue);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex); //Expected.
            }

            Console.WriteLine(sb.ToString()); //Prints "xxxxxxxxxxxxxxxx", should print "xx".

Prints "xxxxxxxxxxxxxxxx", should print "xx". Also, the `StringBuilder` becomes corrupted but that is nothing new.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
…t check that we can insert as many characters as were requested before we actually start writting them into the StringBuilder.

This will prevent the case when we realize that there is not enough space in the StringBuilder (and we cannot grow it as much as it is requested) after we already wrote stuff in it.

Fixes #4514

### CODE REVIEW

**Comment by jkotas** [comment]
cc @GSPP

File: src/mscorlib/src/System/Text/StringBuilder.cs [hunk 1]
```diff
@@ -561,6 +561,13 @@ void ISerializable.GetObjectData(SerializationInfo info, StreamingContext contex
             if (repeatCount==0) {
                 return this;
             }
+
+            // this is where we can check if the repeatCount will put us over m_MaxCapacity
+            // We are doing the check here to prevent the corruption of the StringBuilder.
+            if (Length + repeatCount > m_MaxCapacity || repeatCount + Length < repeatCount) {
```
Comment (jkotas) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: Nit: It would be nice to cache `Length + repeatCount` into a local to make this easier to read, and also to help the JIT to generate better code for it.

**Comment by jkotas** [comment]
LGTM otherwise.

File: src/mscorlib/src/System/Text/StringBuilder.cs (hunk 1 above)
Comment (AlexGhiondea) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: Done!

File: src/mscorlib/src/System/Text/StringBuilder.cs [hunk 2]
```diff
@@ -1712,6 +1720,13 @@ public unsafe StringBuilder Append(char* value, int valueCount)
                 throw new ArgumentOutOfRangeException("valueCount", Environment.GetResourceString("ArgumentOutOfRange_NegativeCount"));
             }
 
+            // this is where we can check if the repeatCount will put us over m_MaxCapacity
```
Comment (jkotas) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: Nit: repeatCount -> valueCount

**Comment by AlexGhiondea** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by AlexGhiondea** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build

File: src/mscorlib/src/System/Text/StringBuilder.cs [hunk 3]
```diff
@@ -561,6 +561,14 @@ void ISerializable.GetObjectData(SerializationInfo info, StreamingContext contex
             if (repeatCount==0) {
                 return this;
             }
+
+            // this is where we can check if the repeatCount will put us over m_MaxCapacity
+            // We are doing the check here to prevent the corruption of the StringBuilder.
+            int newLength = Length + repeatCount;
+            if (newLength > m_MaxCapacity || newLength < repeatCount) {
+                throw new ArgumentOutOfRangeException("repeatCount", Environment.GetResourceString("ArgumentOutOfRange_NegativeCount"));
```
Comment (stephentoub) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: Is this the right resource string?  It maps to "ArgumentOutOfRange_NegativeCount", but repeatCount < 0 was already checked earlier.  This check is really about catching overflow.

**Comment by AlexGhiondea** [comment]
@dotnet-bot test  Linux ARM Emulator Cross Release Build 

/cc @mmitche

**Comment by AlexGhiondea** [comment]
@dotnet-bot test  Linux ARM Emulator Cross Debug Build

File: src/mscorlib/src/System/Text/StringBuilder.cs (hunk 3 above)
Comment (AlexGhiondea) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: I wanted to keep the same error message in case people are checking the message. A different one could be.
```
ArgumentOutOfRange_LengthGreaterThanCapacity = The length cannot be greater than the capacity.
```

If we are not worried about not changing the message in the exception, then I can update it to use the better message.

**Comment by mmitche** [comment]
@AlexGhiondea It looks like someone renamed the jobs in coreclr without a correspoding change in corefx (also, the coreclr builds are failing at the moment too).

https://github.com/dotnet/corefx/commit/98ec77efbb005bc857b8ae2c73654d21d2b80b9c

/cc @wateret

File: src/mscorlib/src/System/Text/StringBuilder.cs [hunk 4]
```diff
@@ -55,7 +55,7 @@ public sealed class StringBuilder : ISerializable
         internal char[] m_ChunkChars;                // The characters in this block
         internal StringBuilder m_ChunkPrevious;      // Link to the block logically before this block
         internal int m_ChunkLength;                  // The index in m_ChunkChars that represent the end of the block
-        internal int m_ChunkOffset;                  // The logial offset (sum of all characters in previous blocks)
+        internal int m_ChunkOffset;                  // The logial offset (sum of all fcharacters in previous blocks)
```
Comment (danmosemsft) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: typo

Comment (danmosemsft) [inline src/mscorlib/src/System/Text/StringBuilder.cs]: logial and fcharacters

**Comment by wateret** [comment]
Sorry for Linux ARM fails. It will be fixed when #7820 is merged.

**Comment by jkotas** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build  please
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by AlexGhiondea** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please
@dotnet-bot test Linux ARM Emulator Cross Release Build please
