### PR TITLE
Switch P/Invokes into libcoreclr for the PAL to QCalls

### LINKED ISSUE #25016: Segfault for project built with `-r linux-x64` running with corerun
To reproduce:

* Create a checkout of coreclr and run `./build.sh && ./build-test.sh -generatelayoutonly`.
* Create a sample .net project:

**cs.csproj**:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Program.cs**:

```cs
using System;

public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Hello");
    }
}
```

* Build with `dotnet publish -r linux-x64`
* Run with:
    CORE_ROOT="/path/to/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root"
    /path/to/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/corerun bin/Debug/netcoreapp3.0/linux-x64/cs.dll

There will be a segmentation fault.
There is no segmentation fault when publishing without `-r linux-x64`, and no corresponding problem on windows.
(Also no problem without the `Console.WriteLine` call.)

Debugging into it with lldb, `target modules list` shows that there are two versions of libcoreclr.so in existence -- one from core_root, and one from the local directory. It looks like one of these has initialized `palEnvironment`, but the other has not.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #25016

### CODE REVIEW

File: src/vm/ecalllist.h [hunk 1]
```diff
@@ -1300,6 +1348,12 @@ FCClassElement("WindowsRuntimeMarshal", "System.Runtime.InteropServices.WindowsR
 FCClassElement("XplatEventLogger", "System.Diagnostics.Tracing", gEventLogger)
 #endif //defined(FEATURE_EVENTSOURCE_XPLAT)
 
+#ifdef FEATURE_PAL
+FCClassElement("Kernel32", "Interop", gPalKernel32Funcs)
```
Comment (jkotas) [inline src/vm/ecalllist.h]: These need to be in alphabetical order
