### PR TITLE
Ensure that SIMD fields are correctly typed

### LINKED ISSUE #24336: Assertion failed '!foundDiff'
Windows/arm64 altjit PMI asm diffs run on Windows/x64 using
```
call jit-diff diff --pmi --diff --base --base_root f:\gh\coreclr12 --arch x64 --build Checked --altjit protononjit.dll --corelib
```

gives:

```
Assert failure(PID 12276 [0x00002ff4], Thread: 12000 [0x2ee0]): Assertion failed '!foundDiff' in 'System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[Vector`1][System.Numerics.Vector`1[System.Single]]:get_Task():struct:this' (IL size 44)
    File: f:\gh\coreclr10\src\jit\lsra.cpp Line: 2146
    Image: F:\gh\coreclr10\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe
```

### PR DESCRIPTION
**Pull request by CarolEidt**
When a struct field is imported, its type needs to be normalized.
Also, the LHS of a struct init, even if a SIMD type, should not be transformed to a non-block node.
Also, add an assert to catch this kind of bug in liveness.

Fix #24336

### CODE REVIEW

File: src/jit/compiler.hpp [hunk 1]
```diff
@@ -1178,6 +1178,12 @@ inline GenTree* Compiler::gtNewFieldRef(var_types typ, CORINFO_FIELD_HANDLE fldH
     /* 'GT_FIELD' nodes may later get transformed into 'GT_IND' */
     assert(GenTree::s_gtNodeSizes[GT_IND] <= GenTree::s_gtNodeSizes[GT_FIELD]);
 
+    if (typ == TYP_STRUCT)
+    {
+        CORINFO_CLASS_HANDLE fieldClass;
+        CorInfoType          fieldTreeType = info.compCompHnd->getFieldType(fldHnd, &fieldClass);
```
Comment (mikedn) [inline src/jit/compiler.hpp]: This variable does not appear to be used

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -6313,27 +6313,22 @@ GenTree* Compiler::gtNewBlockVal(GenTree* addr, unsigned size)
...
-        else
 #endif // FEATURE_SIMD
-            if (val->TypeGet() == TYP_STRUCT)
+        if (varTypeIsStruct(val) && val->OperIs(GT_LCL_VAR))
         {
-            GenTreeLclVarCommon* lcl    = addr->gtGetOp1()->AsLclVarCommon();
-            LclVarDsc*           varDsc = &(lvaTable[lcl->gtLclNum]);
-            if ((varDsc->TypeGet() == TYP_STRUCT) && (varDsc->lvExactSize == size))
+            LclVarDsc* varDsc  = lvaGetDesc(val->AsLclVarCommon());
+            unsigned   varSize = varTypeIsStruct(varDsc) ? varDsc->lvExactSize : genTypeSize(varDsc);
```
Comment (mikedn) [inline src/jit/gentree.cpp]: Presumably the non-struct case here is needed in case a primitive type variable is reinterpreted as a struct?

File: src/jit/liveness.cpp [hunk 3]
```diff
@@ -50,6 +50,9 @@ void Compiler::fgMarkUseDef(GenTreeLclVarCommon* tree)
         // loads aliasing it across a store to it.
         assert(!varDsc->lvAddrExposed);
 
+        // If this is not marked doNotEnregister, we should only see direct references (not ADDRs).
+        assert(varDsc->lvDoNotEnregister || tree->OperIs(GT_LCL_VAR, GT_STORE_LCL_VAR));
```
Comment (mikedn) [inline src/jit/liveness.cpp]: Looks like you are too optimistic :)

File: src/jit/gentree.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/gentree.cpp]: Yes, we can encounter an initObj for a non-struct local, and we could handle it here by checking for the const zero case and ensuring that we have a consistently typed zero, but that case is handled elsewhere, and I think I've already gone far enough (too far?) beyond the minimal fix for this.

File: src/jit/liveness.cpp [hunk 4]
```diff
@@ -50,6 +50,13 @@ void Compiler::fgMarkUseDef(GenTreeLclVarCommon* tree)
         // loads aliasing it across a store to it.
         assert(!varDsc->lvAddrExposed);
 
+        if (compRationalIRForm && (varDsc->lvType != TYP_STRUCT) && !varTypeIsMultiReg(varDsc))
+        {
+            // If this is an enregisterable variable that is not marked doNotEnregister,
+            // we should only see direct references (not ADDRs).
+            assert(varDsc->lvDoNotEnregister || tree->OperIs(GT_LCL_VAR, GT_STORE_LCL_VAR));
```
Comment (CarolEidt) [inline src/jit/liveness.cpp]: Note that this assert is intended to catch these kinds of bugs earlier, and with clearer feedback, than the `!foundDiff` assert in LSRA.

File: src/jit/morph.cpp [hunk 5]
```diff
@@ -9469,12 +9469,7 @@ GenTree* Compiler::fgMorphInitBlock(GenTree* tree)
         }
         else
         {
-            if (dest->OperIs(GT_IND))
-            {
-                assert(dest->TypeGet() == TYP_STRUCT);
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: This code is not really related to this fix, but is simply wrong, and obviously is never actually hit, since the sense is backward (it should be `dest->TypeGet() == TYP_STRUCT`, but in fact we should never actually see a `GT_IND` here.

File: src/jit/morph.cpp [hunk 6]
```diff
@@ -10026,22 +10013,6 @@ GenTree* Compiler::fgMorphBlockOperand(GenTree* tree, var_types asgType, unsigne
...
-                assert(!isDest);
-                needsIndirection = false;
-                effectiveVal     = indirTree->Addr()->gtGetOp1();
-            }
-            if (effectiveVal->OperIsSimdOrHWintrinsic())
-            {
-                needsIndirection = false;
-            }
-        }
-#endif // FEATURE_SIMD
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: This code is also not directly related to this fix, but is a path that will never be hit because we would be on the other path of the outer if in this case.

**Comment by CarolEidt** [comment]
This improves code generation for fields of SIMD types, as well as fixing the bug (which was a bug that caused a type mismatch for a promoted SIMD field). I am still examining the diffs (x64 PMI diffs for frameworks & tests), but it is a net code size reduction:
```
Total bytes of diff: -8569 (-0.01% of base)
281 total methods with size differences (164 improved, 117 regressed), 510953 unchanged
```
So far all of the diffs (improvements and regressions) are due to inlining of methods that return SIMD types. In the regression case, there's more code but one or more calls have been eliminated. In the improvement case the elimination of the call often enables better register allocation.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
This also fixes #24344 which was slightly different but also related to initblk of SIMD types.
