### PR TITLE
Fixes for bugs in optNarrowTree.

### LINKED ISSUE #18238: Cast to ushort is dropped in release
The following program gives different outputs for release and debug:
```csharp
public class Program
{
    static short s_2 = -1000;

    public static void Main()
    {
        ulong var1 = (ushort)(1U ^ s_2);
        Console.WriteLine(var1);
    }
}
```
In release, the result is `4294966297`. In debug, the result is `64537`.
@mikedn has analyzed the cause [here](https://github.com/dotnet/coreclr/issues/18235#issuecomment-393915294).

This issue repros on .NET framework as well with 64-bit JIT (it does not repro with 32-bit JIT).

### PR DESCRIPTION
**Pull request by erozenfeld**
The fix under NARROW_IND prevents transformation of, e.g.,
```
CAST      int <- ushort <- int
    CLS_VAR byte
```
into

```
CLS_VAR byte
```

With the fix the CAST is not removed.

The fix under GT_CAST prevents transformation of, e.g.,

```
CAST      int <- ushort <- long
    CAST      long <- int
       expr short
```
into

```
expt short
```

With the fix it gets transformed into

```
CAST      int <- ushort <- int
    expr short
```

Fixes #18238.

No diffs in frameworks and tests (pmi and crossgen, x64 and x86), except for the added test cases.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib @jakobbotsch @mikedn PTAL

**Comment by jakobbotsch** [comment]
Tons of fixed examples: https://github.com/jakobbotsch/Fuzzlyn/commit/86373af3984b56158a899c4af7ac0d956fce73ca

However some are still which look like they could be related:
```csharp
// Generated by Fuzzlyn on 2018-06-25 13:35:52
// Seed: 1475847211665022337
// Reduced from 41.7 KiB to 0.2 KiB
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
public class Program
{
    static char s_4;
    public static void Main()
    {
        long vr0 = 0 % ((0 & (-2147483648 % (int)(18446744073709551615UL | s_4))) | 1);
    }
}
```

```csharp
// Generated by Fuzzlyn on 2018-07-07 14:53:26
// Seed: 3545793482977672966
// Reduced from 5.7 KiB to 0.6 KiB
// Debug: Outputs 32779
// Release: Outputs 4294934539
struct S0
{
    public bool F0;
    public short F1;
    public S0(short f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    static S0 s_1;
    static sbyte s_2;
    public static void Main()
    {
        s_2 = 0;
        M3();
    }

    static sbyte M3()
    {
        char var0 = default(char);
        s_1 = new S0(-32767);
        var vr6 = s_1.F0;
        M4(var0, 0, (ushort)(10L | s_1.F1), vr6, s_1.F1);
        return s_2;
    }

    static byte[] M4(char arg0, long arg1, uint arg2, bool arg3, short arg4)
    {
        System.GC.KeepAlive(arg2);
        System.Console.WriteLine(arg2);
        return new byte[]{0};
    }
}
```

**Comment by erozenfeld** [comment]
This is a bug in fgMorphCast. Here is the bad transformation:
```
N021 (  1,  1)              [000031] ------------                 |  /--*  CNS_INT   int    10 $43
N022 ( 12, 20)              [000038] ---XG------- arg2 in r8      +--*  OR        int    <l:$445, c:$444>
N020 ( 10, 18)              [000037] ---XG-------                 |  \--*  CAST      int <- ushort <- int <l:$443, c:$442>
N019 (  9, 16) CSE #02 (use)[000036] *--XG-------                 |     \--*  IND       short  <l:$4c0, c:$1c2>
N017 (  1,  1)              [000111] ------------                 |        |  /--*  CNS_INT   long   10 field offset Fseq[#FirstElem, F1] $2c3
N018 (  6, 13)              [000112] -------N----                 |        \--*  ADD       byref  <l:$309, c:$30a>
N016 (  5, 12) CSE #01 (use)[000033] x-----------                 |           \--*  IND       ref    <l:$241, c:$285>
N015 (  3, 10)              [000032] ------------                 |              \--*  CNS_INT(h) long   0x23232882968 static Fseq[s_1] $200
```
to
```
N024 (  1,  1)              [000031] ------------              |  /--*  CNS_INT   int    10 $43
N025 ( 11, 18)              [000038] ---XG------- arg2 in r8   +--*  OR        int    <l:$445, c:$444>
N023 (  9, 16) CSE #02 (use)[000036] *--XG-------              |  \--*  IND       ushort <l:$4c0, c:$1c2>
N021 (  1,  1)              [000111] ------------              |     |  /--*  CNS_INT   long   10 field offset Fseq[#FirstElem, F1] $2c3
N022 (  6, 13)              [000112] -------N----              |     \--*  ADD       byref  <l:$309, c:$30a>
N020 (  5, 12) CSE #01 (use)[000033] x-----------              |        \--*  IND       ref    <l:$241, c:$285>
N019 (  3, 10)              [000032] ------------              |           \--*  CNS_INT(h) long   0x23232882968 static Fseq[s_1] $200
```
Note the same value numbers in
```
IND       short  <l:$4c0, c:$1c2>
```
and
```
IND       ushort <l:$4c0, c:$1c2>
```
This is incorrect since there is an implicit conversion of the result of the indirection nodes to `int`  and they have different values as ints.

The incorrect value numbers then results in an incorrect CSE.

The bug is here: https://github.com/dotnet/coreclr/blob/47c744ebc48cb6c0654f8c11a09870efe16984a3/src/jit/morph.cpp#L602

This code should either be turned off after global morph or it should keep value numbers valid.

I think there should be a separate issue for this as a fix will likely result in diffs in existing assemblies.

**Comment by erozenfeld** [comment]
@briansull @mikedn Can you please review these fixes?

**Comment by erozenfeld** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked CoreFX Tests
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test 
@dotnet-bot test Ubuntu x64 Formatting
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test 
@dotnet-bot test Windows_NT x64 Release CoreFX Tests 
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by jakobbotsch** [comment]
Thanks, I have opened #18850 for it.

File: src/jit/optimizer.cpp [hunk 1]
```diff
@@ -5835,18 +5842,19 @@ bool Compiler::optNarrowTree(GenTree* tree, var_types srct, var_types dstt, Valu
                     {
                         dstt = genSignedType(dstt);
 
-                        if (oprSize == dstSize)
+                        if ((oprSize == dstSize) && (!varTypeIsUnsigned(dstt) || varTypeIsUnsigned(oprt) ||
```
Comment (mikedn) [inline src/jit/optimizer.cpp]: It's not clear to me why the signedness of `oprt` is relevant here. It's basically always signed (`TYP_INT` or `TYP_LONG`). Did you intend to test the `GTF_UNSIGNED` flag on the cast node perhaps? But that does not apply to cast to small types so it does not seem relevant.

Comment (mikedn) [reply src/jit/optimizer.cpp]: Hmm
* `!varTypeIsUnsigned(dstt)` should always be `true` due to the above `dstt = genSignedType(dstt);`
* `dstSize == genTypeSize(genActualType(dstt))` is really `!varTypeIsSmall(dstt)`

So the interesting case is `(oprSize == dstSize) && varTypeIsSigned(oprt)` when the current useless cast is transformed into a cast to `dstt` while the original cast (that triggered narrowing) is still getting removed.

So this does seem to be correct, at least in the case of `cast(cast(ind(x))`.

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: >> !varTypeIsUnsigned(dstt) should always be true due to the above dstt = genSignedType(dstt);

genSignedType doesn't change the sign of small types, e.g., genSignedType(ushort) returns ushort.

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: >> It's not clear to me why the signedness of oprt is relevant here. It's basically always signed (TYP_INT or TYP_LONG). 

No, that's not correct. It can be, e.g., TYP_SHORT or TYP_USHORT.

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: For example, here
```
CAST      int <- ushort <- long
    CAST      long <- int
       expr short
```
oprt is TYP_SHORT

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: >> dstSize == genTypeSize(genActualType(dstt)) is really !varTypeIsSmall(dstt)
Yes, I'll update that.

Comment (mikedn) [reply src/jit/optimizer.cpp]: > genSignedType doesn't change the sign of small types, e.g., genSignedType(ushort) returns ushort.

Eh, completely forgot about that.

> No, that's not correct. It can be, e.g., TYP_SHORT or TYP_USHORT.

I know but it's kind of confusing because the signedness of the cast operand doesn't determine the kind of conversion being performed so it doesn't seem fit with the comment below that says "Same size and there is no signed --> unsigned conversion for small types".

I don't know, I need to stare more at this, I feel I'm still missing something.

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: In this example
```
CAST      int <- ushort <- long
    CAST      long <- int
       expr short
```
dsst is ushort
oprt is short

transforming it to expr short is incorrect because there is an implicit short -> int conversion.
So it needs to be
```
CAST      int <- ushort <- int
    expr short
```
On the other hand, for this example

```
CAST      int <- ushort <- long
    CAST      long <- int
       expr ushort
```
it's ok to transform it to
expr ushort.

Comment (mikedn) [reply src/jit/optimizer.cpp]: I understand the goal but I don't quite understand how we get there. As far as I can tell the morphed cast is still going to be removed and to compensate for that the useless `long<-int` cast is being changed to a cast to `dstt`. This is obvious correct for the given examples but it's not clear to me what happens for
* `CAST.short(CAST.long(IND.ushort))` - `dstt` is `short` so it is signed and the condition is true. The cast to long gets changed to a nop and the original cast is removed. We end up with just `IND.ushort`.
* What happens if we have AND/OR/XOR along the path between casts? It seems to me that the cast to `ushort` from your first example could move bellow something like `OR x, 0x10000` and as a result bit 16 set by OR will remain set because there's no longer a cast to clear it.

Comment (briansull) [reply src/jit/optimizer.cpp]: The only 'expr short/ushort' that we shodul see are memory reads.

Comment (erozenfeld) [reply src/jit/optimizer.cpp]: I think in the second example the optimization will be blocked because when optNarrowTree is called on AND/OR/XОР it'll call optNarrowTree on 0x10000 with dsst ==TYP_USHORT and that will return false here: https://github.com/dotnet/coreclr/blob/10729e1a8a65bf3669049bca234187cbaf1a2e70/src/jit/optimizer.cpp#L5665

Comment (mikedn) [reply src/jit/optimizer.cpp]: > I think in the second example the optimization will be blocked because when optNarrowTree is called on AND/OR/XОR it'll call optNarrowTree on 0x10000 with dsst ==TYP_USHORT and that will return false here: 

Right, I've missed the fact that `optNarrowTree` does not attempt to narrow constants below `TYP_INT`.

**Comment by erozenfeld** [comment]
I pushed an update with the following changes:
* Use `!varTypeIsSmall(dstt)` instead of `dstSize == genTypeSize(genActualType(dstt))`
* Don't change CAST to NOP if oprt and dsst have different signedness. This fixes the `CAST.short(CAST.long(IND.ushort))` case.
* Block cast optimizations in fgMorphCast if the cast expression is an
active CSE candidate. This fixes the case in #18850.
* Update cast expression value numbers when a cast is removed.
* Add a test case for #18850.

Still no diffs except for the added tests.

@mikedn @briansull PTAL
@jakobbotsch Please let me know if you have any other failures that you think may be related to fgMorphCast and optNarrowTree.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -532,7 +532,7 @@ GenTree* Compiler::fgMorphCast(GenTree* tree)
     /* Just in case new side effects were introduced */
     tree->gtFlags |= (oper->gtFlags & GTF_ALL_EFFECT);
 
-    if (!gtIsActiveCSE_Candidate(tree)) // tree cannot be a CSE candidate
+    if (!gtIsActiveCSE_Candidate(tree) && !gtIsActiveCSE_Candidate(oper)) // tree cannot be a CSE candidate
```
Comment (mikedn) [inline src/jit/morph.cpp]: That comment should be removed, it was useless to begin with and now it's kind out of date as well.

But IMO it's not worth another CI build just for this.

**Comment by mikedn** [comment]
New changes look good.

The whole CSE acrobatics is rather unfortunate, I wonder why CSE doesn't simply postpone morphing until it's done.

**Comment by jakobbotsch** [comment]
I went through all my remaining examples and I don't think any of them are related to `fgMorphCast` or `optNarrowTree`. Most are #18232, #18770 or #18780. This fix fixes around 2/3 of my examples. :+1:

**Comment by erozenfeld** [comment]
I ran desktop SuperPMI. There was one method with diffs, a regression of 6 bytes. Two unnecessary movzx instructions were added.
The cast in the following tree wasn't removed:
```
               [011384] ---XG+------              /--*  CAST      int <- ushort <- int
               [001048] *--XG+------              |  |  /--*  IND       byte  
               [001047] -----+------              |  |  |  \--*  LCL_VAR   long   V17 loc17        
               [001049] ---XG+------              |  \--*  AND       int   
               [001046] *--XG+------              |     \--*  IND       ushort
               [001045] *--XG+------              |        \--*  IND       long  
               [001044] -----+------              |           \--*  LCL_VAR   long   V03 loc3         
               [001051] -A-XG+------              *  ASG       int   
               [001050] D----+-N----              \--*  LCL_VAR   int    V94 loc94 
```
The reason for that is that GT_AND case in optNarrowTree only checks whether op2 can be narrowed. With my change optNarrowTree correctly returns false for op2. The CAST would be removed if the code also checked whether op1 could be narrowed. I'll open an issue for this.
