### PR TITLE
JIT: change how we block gc refs from callee saves for inline pinvokes

### LINKED ISSUE #19211: [Arm64/Linux] gcStress=4/8/C intermittent failures
The following test failed twice over the last few months.

On 7/30/2018 the failure looked like 
`GC/API/GC/GetGenerationWR/GetGenerationWR.sh`
`gcStress=0xC`
```
corerun GetGenerationWR.exe

Assert failure(PID 17500 [0x0000445c], Thread: 17500 [0x445c]): 
    !CREATE_CHECK_STRING(pMT &amp;&amp; pMT-&gt;Validate())
    File: src/vm/object.cpp Line: 733
```

Early 6/2018 the failure was similar

`gcStress=0x4`
```
corerun GetGenerationWR.exe

Assert failure(PID 14440 [0x00003868], Thread: 14440 [0x3868]): 
!CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: src/vm/object.cpp Line: 733
```

It may be worth noting the `GetGenerationWR2` is marked gcStressIncompatible

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Add a new marker instruction that we emit once we've enabled preepmtive gc in
the inline pinvoke method prolog. Use that to kill off callee saves registers
with GC references, instead of waiting until the call.

This closes a window of vulnerability we see in GC stress where if a stress
interrupt happens between the point at which we enable preeemptive GC and
the point at which we make the call, we may report callee saves as GC live
when they're actually dead.

Closes #19211.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

No codegen diffs, no gc info diffs on x64. One small IR diff, there is one IL stub where we restore the call target after we switch to preemptive mode, so this change induces an extra label and IG.

For arm64 we see the expected GC info diff for GetGenerationWR.exe -- x19 and x3 are now killed earlier, right where we transition to preemptive GC.
```diff
-Set state of slot 1 at instr offset 0x98 to Dead.
-Set state of slot 2 at instr offset 0x98 to Dead.
+Set state of slot 1 at instr offset 0x88 to Dead.
+Set state of slot 2 at instr offset 0x88 to Dead.
```

Running pmi diffs for arm64 (via altjit and with gcinfo) now, will update with the results. Also will stress GetGenerationWR.exe on HW to show that this change actually fixes the problem.

Now that we have this new marker instruction, we might want to remove the call as a source of callee saves gc ref kills.

File: src/jit/lsrabuild.cpp [hunk 1]
```diff
@@ -2556,9 +2561,11 @@ void LinearScan::BuildDefsWithKills(GenTree* tree, int dstCount, regMaskTP dstCa
     VARSET_TP liveLargeVectors(VarSetOps::UninitVal());
     bool      doLargeVectorRestore = false;
 #endif // FEATURE_PARTIAL_SIMD_CALLEE_SAVE
+
+    buildKillPositionsForNode(tree, currentLoc + 1, killMask);
```
Comment (BruceForstall) [inline src/jit/lsrabuild.cpp]: ok, I see you've changed how `killMask` works slightly. It would be useful to add a comment about argument `killMask` both in `LinearScan::buildKillPositionsForNode` (which is already missing a comment), and in `LinearScan::BuildDefsWithKills`. In the latter case, it seems the existing comment "The mask of registers killed by this node" is insufficient if we allow `RBM_NONE` now.

Or if the callers passed in `RBM_INT_CALLEE_SAVED` like I mentioned above, would existing semantics (and comments about `killMask`) be preserved?

Comment (AndyAyersMS) [reply src/jit/lsrabuild.cpp]: The reason I did it this way is that this marker instruction selectively kills registers -- non GC refs aren't impacted. And it looks like `killMask` is more definitive and describes registers that must be considered dead no matter what. For instance any callee save mentioned there will be considered  as modified and so saved in the prolog.

Comment (BruceForstall) [reply src/jit/lsrabuild.cpp]: Makes sense. It would be useful to make sure it's clearly documented.

**Comment by AndyAyersMS** [comment]
OSX hangup (will hold off on retry for now since I'll be pushing more commits)
```
15:47:50 FATAL: java.nio.channels.ClosedChannelException
15:47:50 java.nio.channels.ClosedChannelException
15:47:50 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 131.107.147.146/131.107.147.146:33579
15:47:50 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693
```

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test


@dotnet-bot test Windows_NT arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by AndyAyersMS** [comment]
So far so good. `GetGenerationWR` hasn't crashed in its first 1000 executions (running in a lop under gc stress 0x4 + additional sideloaded machine stress via `stress`).

**Comment by AndyAyersMS** [comment]
Arm64 gcstress/jitstress failures
* tracing\eventsource\eventpipeandetw
* GC\API\GC\Collect (#22443 ?)

both of which appear unrelated.

GetGenerationWR has how run under GC stress + machine stress 47000 times without a failure.

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -3688,14 +3689,18 @@ void Lowering::InsertPInvokeCallProlog(GenTreeCall* call)
...
     //  [tcb + offsetOfGcState] = 0
-
     GenTree* storeGCState = SetGCState(0);
     BlockRange().InsertBefore(insertBefore, LIR::SeqTree(comp, storeGCState));
     ContainCheckStoreIndir(storeGCState->AsIndir());
+
+    // Indicate that codegen has switched this thread to preemptive GC.
+    // This doesn't generate any code, but impacts LSRA and gc reporting
+    GenTree* preemptiveGCNode = new (comp, GT_START_PREEMPTGC) GenTree(GT_START_PREEMPTGC, TYP_VOID);
+    BlockRange().InsertBefore(insertBefore, LIR::SeqTree(comp, preemptiveGCNode));
```
Comment (mikedn) [inline src/jit/lower.cpp]: Why do you need SeqTree?

Comment (AndyAyersMS) [reply src/jit/lower.cpp]: We don't, but @BruceForstall suggested making things consistent with insertions in the rest of the method.

Comment (mikedn) [reply src/jit/lower.cpp]: Sorry, didn't notice that comment. There's no need to call SeqTree and I don't see what consistency has to do with this. It's extra complexity and wasted CPU cycles.

File: src/jit/lsrabuild.cpp (hunk 1 above)
Comment (briansull) [reply src/jit/lsrabuild.cpp]: I Agree with Bruce

**Comment by AndyAyersMS** [comment]
@briansull I updated comments re `killMask` in the second commit -- do you think more is needed?

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot retest Windows_NT arm Cross Checked Innerloop Build and Test

File: src/jit/lower.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/lower.cpp]: I agree that we should avoid calling `SeqTree` when it is obvious from the immediate context that it is a single node.

**Comment by AndyAyersMS** [comment]
Jenkins hangup

@dotnet-bot retest Windows_NT arm64 Cross Checked Innerloop Build and Test
