### PR TITLE
Fix ARM issues with Containment

### LINKED ISSUE #13451: [RyuJIT/arm32] Regression : Assertion failed '!isMarkedContained'
After #13198 merged we get a lot of assertion failure on ARM(RPi3).

```
               Assert failure(PID 8768 [0x00002240], Thread: 8768 [0x2240]): Assertion failed '!isMarkedContained' in 'HFATest.TestCase:Main():int' (IL size 2810)

                   File: /opt/code/work/src/jit/gentree.cpp Line: 15194
                   Image: /work/nfs/dotnet/arm/ttc/corerun
```

As far as we checked so far, all of the HFA tests(JIT/jit64/hfa) fail with this assertion. I'll update the full test results when it is done. 

cc: @CarolEidt @sjsinju

### PR DESCRIPTION
**Pull request by CarolEidt**
These are changes that should have been part of PR #13198:
- Correctly contain struct arguments
- Correctly get number of source registers
- Allow `GT_FIELD_LIST` to have registers, even if contained
- Remove now-redundant `ContainCheck` methods for armarch targets.

Fix #13451

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL. With this fix, I get 29 failures in the HFA tests, all with the pre-existing `genIsValidDoubleReg` assert.
cc: @dotnet/arm32-contrib

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -15189,7 +15189,16 @@ bool GenTree::isContained() const
     const bool isMarkedContained = ((gtFlags & GTF_CONTAINED) != 0);
 
 #ifdef DEBUG
-    if (!canBeContained() || gtHasReg())
+#ifdef _TARGET_ARMARCH_
+    // For ARM targets, we use the GT_FIELD_LIST nodes to carry the register numbers,
+    // even though they are always contained.
+    if (gtOper == GT_FIELD_LIST)
+    {
+        ;
```
Comment (jashook) [inline src/jit/gentree.cpp]: Is this condition expected to be empty?

**Comment by hqueue** [comment]
With this PR and  recent commit(a6045809b3720833459c9247aeb4aafe281d7841),  some regressions are still observed as in #13453 and #13454.

```
FAILED   - [   0][   6s]JIT/CodeGenBringUpTests/div2/div2.sh
FAILED   - [   1][   6s]JIT/CodeGenBringUpTests/struct16args/struct16args.sh

               Assert failure(PID 25353 [0x00006309], Thread: 25353 [0x6309]): Assertion failed 'isMarkedContained || (gtGetParent(nullptr) == nullptr)' in 'System.Reflection.RuntimeAssembly:GetManifestResourceStream(ref,byref,bool):ref:this' (IL size 65)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/gentree.cpp Line: 15246
```

**Comment by hseok-oh** [comment]
@CarolEidt I make new PR to fix regression on arm32 by fixing arm32 part only. PTAL.

File: src/jit/gentree.cpp (hunk 1 above)
Comment (CarolEidt) [inline src/jit/gentree.cpp]: Yes, it is empty because for this case, as described in the above comment, we do not assert that if it is contained it must not have a reg, as in the next case.

**Comment by CarolEidt** [comment]
@pgavlin @BruceForstall PTAL
@hseok-oh - I incorporated your `GT_FIELD_LIST` and ContainCheck changes; all the hfa tests and the additional two you mention above are now passing on my pi
cc @dotnet/jit-contrib 
The Tizen armel failure is, I believe, the usual intermittent seg fault.

**Comment by CarolEidt** [comment]
> all the hfa tests

What I should have said was, all the hfa tests are either passing or getting the `genIsValidDoubleReg(reg->regNum)` assert.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by hqueue** [comment]
> The Tizen armel failure is, I believe, the usual intermittent seg fault.

I've ran failed test on my raspberry pi and it passed.

Thanks for the fix :)

**Comment by CarolEidt** [comment]
There was still an issue with `GT_STORE_DYN_BLK` in `TreeNodeInfoInitBlockStore()` in lsraarmarch.cpp. I've fixed that (a 1 line change) and have rebased.

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Formatting
