### PR TITLE
[x86/Linux] Pass return buffer on reverse P/Invoke

### LINKED ISSUE #10161: [x86/Linux] Vector3Interop test failures
Reverse P/Invoke test in ``JIT.SIMD.Vector3Interop_r`` failed:
```
FAILED   - [ 5474 :    7 sec ] JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
...
               callBack_RPInvoke_Vector3Arg:
                   iVal 123
                   Sum0,1,2 = 1400, 14, 140
                   str abcdefg
               RPInvoke Vector3Arg test failed
```

### PR DESCRIPTION
**Pull request by parjong**
#10217 does not consider return buffer, and results in RPInvoke_Vector3Ret test failure (discussed in #10161).

This commit revises UMThunkMarshInfo::RunTimeInit and UMThunkMarshInfo::SetupArguments to account retbuf argument correctly.

This commit fixes #10161.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Formatting please

File: src/vm/dllimportcallback.cpp [hunk 1]
```diff
@@ -1380,12 +1380,25 @@ VOID UMThunkMarshInfo::RunTimeInit()
...
+    m_cbRetPop = 0;
+
     //
     // m_cbStackArgSize represents the number of arg bytes for the MANAGED signature
     //
     m_cbStackArgSize = 0;
 
     int offs = 0;
+
+#ifdef PLATFORM_UNIX
```
Comment (jkotas) [inline src/vm/dllimportcallback.cpp]: This should be UNIX_X86_ABI

File: src/vm/dllimportcallback.cpp [hunk 2]
```diff
@@ -1408,16 +1421,10 @@ VOID UMThunkMarshInfo::RunTimeInit()
...
-        // caller pop
-        m_cbRetPop = 0;
-    }
-    else
+    if (sigInfo.GetCallConv() != pmCallConvCdecl)
     {
-        // callee pop
-        m_cbRetPop = static_cast<UINT16>(m_cbActualArgSize);
+        // For all the other calling convention except cdecl, callee pops the stack arguments
+        m_cbRetPop += static_cast<UINT16>(m_cbActualArgSize);
```
Comment (jkotas) [inline src/vm/dllimportcallback.cpp]: It would be better to keep track of cbRetPop in a local and assign it just once at the end.

File: src/vm/dllimportcallback.cpp [hunk 3]
```diff
@@ -1408,16 +1420,14 @@ VOID UMThunkMarshInfo::RunTimeInit()
         new (&sigInfo) PInvokeStaticSigInfo(pMD);
     else
         new (&sigInfo) PInvokeStaticSigInfo(GetSignature(), GetModule());
-
     if (sigInfo.GetCallConv() == pmCallConvCdecl)
     {
-        // caller pop
-        m_cbRetPop = 0;
+        m_cbRetPop = cbRetPop;
```
Comment (jkotas) [inline src/vm/dllimportcallback.cpp]: Is this correct? I would except cdecl to be always zero, no matter whether there is a return buffer argument.

Comment (parjong) [inline src/vm/dllimportcallback.cpp]: I also except that, but it doesn't

Here is the corresponding native code:
```
Dump of assembler code for function nativeCall_RPInvoke_Vector3Ret(CallBack_RPInvoke_Vector3Ret):
   0xf7fd2180 <+0>:     push   %ebp
   0xf7fd2181 <+1>:     mov    %esp,%ebp
   0xf7fd2183 <+3>:     push   %ebx
   0xf7fd2184 <+4>:     push   %esi
   0xf7fd2185 <+5>:     sub    $0x50,%esp
   0xf7fd2188 <+8>:     call   0xf7fd218d <nativeCall_RPInvoke_Vector3Ret(CallBack_RPInvoke_Vector3Ret)+13>
   0xf7fd218d <+13>:    pop    %eax
   0xf7fd218e <+14>:    add    $0x1e73,%eax
   0xf7fd2194 <+20>:    mov    0x8(%ebp),%ecx
   0xf7fd2197 <+23>:    lea    -0x18(%ebp),%edx
   0xf7fd219a <+26>:    mov    %gs:0x14,%esi
   0xf7fd21a1 <+33>:    mov    %esi,-0xc(%ebp)
   0xf7fd21a4 <+36>:    mov    %ecx,-0x20(%ebp)
   0xf7fd21a7 <+39>:    mov    %edx,(%esp)
   0xf7fd21aa <+42>:    mov    %eax,%ebx
   0xf7fd21ac <+44>:    mov    %eax,-0x24(%ebp)
   0xf7fd21af <+47>:    call   *-0x20(%ebp)
   0xf7fd21b2 <+50>:    sub    $0x4,%esp
```

SP adjustment (``sub    $0x4,%esp``) after ``call   *-0x20(%ebp)`` (which invokes R/PInvkoe callback) implies that return buffer will be popped by callee.

Comment (jkotas) [inline src/vm/dllimportcallback.cpp]: Interesting...
