### PR TITLE
Mark local struct as having overlapping fields after struct reinterpretation

### LINKED ISSUE #24159: CoreFX test failures, incl. System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x80/842/

**Failed tests:**
System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance
System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance

**Failed log:**
```
System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance [FAIL]
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData_MemberData', Elapsed: 00:15:58
  [Long Running Test] 'System.IO.Tests.Pipes.AnonymousPipeReadViaFileStream', Elapsed: 00:15:38
        Assert.True() Failure
  [Long Running Test] 'System.IO.Tests.FileStream_FlushAsync.FlushAfterReading', Elapsed: 00:15:37
  [Long Running Test] 'System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncInternalBufferOverflow', Elapsed: 00:15:34
        Expected: True
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndWrite_AsyncWrites.WriteAsyncCancelledFile', Elapsed: 00:14:43
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---ac310d4a\_\fx\src\System.Memory\tests\ArrayBufferWriter\ArrayBufferWriterTests.T.cs(95,0): at System.Buffers.Tests.ArrayBufferWriterTests`1.Advance()
  [Long Running Test] 'System.IO.Tests.Sync_FileStream_ReadWrite_Span.EmptyFile_ReadAsync_Succeeds', Elapsed: 00:14:31
  [Long Running Test] 'System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync', Elapsed: 00:14:30
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str_b.CopyFileWithData_MemberData', Elapsed: 00:14:27
      System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
     System.Linq.Expressions.Tests: [Long Running Test] 'System.Linq.Expressions.Tests.ArrayBoundsTests.NewArrayBounds', Elapsed: 00:10:23
        Stack Trace:
          D:\j\workspace\x64_checked_w---ac310d4a\_\fx\src\System.Memory\tests\ArrayBufferWriter\ArrayBufferWriterTests.T.cs(95,0): at System.Buffers.Tests.ArrayBufferWriterTests`1.Advance()
     System.IO.FileSystem.Tests: [Long Running Test] 'System.IO.Tests.Sync_DerivedFileStream_ReadWrite_Span.NonEmptyWriteAsync_CustomMemoryManager_WritesExpectedData', Elapsed: 00:17:55
  [Long Running Test] 'System.IO.Tests.File_AppendAllTextAsync.OverwriteAsync', Elapsed: 00:18:15
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllLines_Enumerable_EncodedAsync.DisposingEnumeratorClosesFileAsync', Elapsed: 00:18:04
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndRead_AsyncReads.EmptyFileReadAsyncSucceedSynchronously', Elapsed: 00:18:17
  [Long Running Test] 'System.IO.Tests.File_AppendAllLinesAsync_Encoded.NullLinesAsync', Elapsed: 00:18:14
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllTextAsync.ValidWriteAsync', Elapsed: 00:18:08
  [Long Running Test] 'System.IO.Tests.FileStream_DisposeAsync.DisposeAsyncFlushes', Elapsed: 00:18:13
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllLines_EnumerableAsync.ValidWriteAsync', Elapsed: 00:18:12
  [Long Running Test] 'System.IO.Tests.File_AppendAllTextAsync_Encoded.OverwriteAsync', Elapsed: 00:18:11
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData_MemberData', Elapsed: 00:18:06
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str.CopyFileWithData_MemberData', Elapsed: 00:18:08
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData_MemberData', Elapsed: 00:18:01
  [Long Running Test] 'System.IO.Tests.Pipes.AnonymousPipeReadViaFileStream', Elapsed: 00:17:40
  [Long Running Test] 'System.IO.Tests.FileStream_FlushAsync.FlushAfterReading', Elapsed: 00:17:40
  [Long Running Test] 'System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncInternalBufferOverflow', Elapsed: 00:17:36
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndWrite_AsyncWrites.WriteAsyncCancelledFile', Elapsed: 00:16:45
  [Long Running Test] 'System.IO.Tests.Sync_FileStream_ReadWrite_Span.EmptyFile_ReadAsync_Succeeds', Elapsed: 00:16:33
  [Long Running Test] 'System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync', Elapsed: 00:16:33
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str_b.CopyFileWithData_MemberData', Elapsed: 00:16:30
     System.Linq.Expressions.Tests: [Long Running Test] 'System.Linq.Expressions.Tests.ArrayBoundsTests.NewArrayBounds', Elapsed: 00:12:25
    Finished:    System.Memory.Tests
  === TEST EXECUTION SUMMARY ===
     System.Memory.Tests  Total: 45349, Errors: 0, Failed: 2, Skipped: 0, Time: 268.522s
  ----- end 17:02:04.68 ----- exit code 1 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by erozenfeld**
Methods like System.Runtime.CompilerServices.Unsafe.As<TFrom, TTo> may
have struct reinterpretation when function signature specifies Struct1&
and the method returns Struct2& where Struct1 and Struct2 are different
structs. This may confuse jit optimizations (in particular, value
numbering) because fields of a struct of type Struct1 may be accessed
using handles of Struct2. This fix marks the source local involved in
such struct reinterpretation as having overlapping fields. That prevents
SSA builder from inserting the local into SSA.

Fixes #24159.

No diffs in framework assemblies and coreclr benchmarks.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@briansull @CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -16440,6 +16439,33 @@ bool Compiler::impReturnInstruction(BasicBlock* block, int prefixFlags, OPCODE&
...
+                        if (varTypeIsStruct(JITtype2varType(referentType)) &&
+                            (varDsc->lvVerTypeInfo.GetClassHandle() != referentClassHandle))
+                        {
+                            // We are returning a byref to struct1; the method signature specifies return type as byref
+                            // to struct2. struct1 and struct2 are different so we are "reinterpreting" the struct.
+                            // This may happen in, for example, System.Runtime.CompilerServices.Unsafe.As<TFrom, TTo>.
+                            // We need to mark the source struct variable as having overlapping fields because its
+                            // fields may be accessed using field handles of a different type, which may confuse
+                            // optimizations, in particular, value numbering.
+                            varDsc->lvOverlappingFields = true;
```
Comment (briansull) [inline src/jit/importer.cpp]: You should add a JITDUMP message here indicating that you have set lvOverlappingFields

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -16440,6 +16439,33 @@ bool Compiler::impReturnInstruction(BasicBlock* block, int prefixFlags, OPCODE&
 #endif
                 }
 
+                // If we are inlining a method that returns a struct byref, check whether we are "reinterpreting" the
+                // struct.
+                if ((returnType == TYP_BYREF) && (info.compRetType == TYP_BYREF) && (op2->OperGet() == GT_ADDR))
+                {
+                    GenTree* op2Child = op2->gtGetOp1();
```
Comment (briansull) [inline src/jit/importer.cpp]: I don't like the name `op2Child` here,  Since we must have a `GT_ADDR` the name `addrChild` would be better

File: src/jit/importer.cpp [hunk 3]
```diff
@@ -16440,6 +16439,33 @@ bool Compiler::impReturnInstruction(BasicBlock* block, int prefixFlags, OPCODE&
 #endif
                 }
 
+                // If we are inlining a method that returns a struct byref, check whether we are "reinterpreting" the
+                // struct.
+                if ((returnType == TYP_BYREF) && (info.compRetType == TYP_BYREF) && (op2->OperGet() == GT_ADDR))
```
Comment (briansull) [inline src/jit/importer.cpp]: It may be possible that `op2` is a `GT_COMMA `with `gtEffectiveVal()` that is a `GT_ADDR(GT_LCL_VAR)`

So using: 
```
GenTree* retVal = op2->gtEffectiveVal();
if ( .. (retVal->OperGet() == GT_ADDR))
```

would be better.

File: src/jit/importer.cpp [hunk 4]
```diff
@@ -16440,6 +16439,33 @@ bool Compiler::impReturnInstruction(BasicBlock* block, int prefixFlags, OPCODE&
...
+                {
+                    GenTree* op2Child = op2->gtGetOp1();
+                    if ((op2Child->OperGet() == GT_LCL_VAR) && varTypeIsStruct(op2Child->TypeGet()))
```
Comment (CarolEidt) [inline src/jit/importer.cpp]: It appears that this doesn't impact the handling of SIMD types, presumably because any code that is looking at `lvOverlappingFields` is dealing with field accesses, which we don't expect to see for those. However, to avoid future pessimization, I think it would be better to change this to:
```
if ((op2Child->OperGet() == GT_LCL_VAR) && (op2Child->TypeGet() == TYP_STRUCT))
```

Comment (erozenfeld) [reply src/jit/importer.cpp]: Just to confirm: are we never expected to see field accesses for SIMD types (now or in the future)? If so, I'll change the check. If field accesses are potentially possible for SIMD types, we may run into the same bug for them.

Comment (CarolEidt) [reply src/jit/importer.cpp]: We sometimes access fields of the fixed-size SIMD types, so a more conservative fix might be better:
```
if ((op2Child->OperGet() == GT_LCL_VAR) && varTypeIsStruct(op2Child->TypeGet() &&
    !isOpaqueSIMDLclVar(lvaGetDesc(op2Child->AsLclVarCommon())))
```

File: src/jit/importer.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/jit/importer.cpp]: Done.

File: src/jit/importer.cpp (hunk 2 above)
Comment (erozenfeld) [reply src/jit/importer.cpp]: Done.

File: src/jit/importer.cpp (hunk 3 above)
Comment (erozenfeld) [reply src/jit/importer.cpp]: Done.

File: src/jit/importer.cpp (hunk 4 above)
Comment (erozenfeld) [reply src/jit/importer.cpp]: Done.

**Comment by erozenfeld** [comment]
@briansull @CarolEidt I addressed all feedback. PTAL

**Comment by erozenfeld** [comment]
Still no diffs in frameworks assemblies and coreclr benchmarks.

**Comment by erozenfeld** [comment]
I pushed a change to remove exclusions for corefx tests `System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance` and `System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance`  since this fixes #24159.

**Comment by erozenfeld** [comment]
@dotnet-bot help

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked corefx_jitstressregs0x80

**Comment by erozenfeld** [comment]
arm failure is infrastructure issue https://github.com/dotnet/core-eng/issues/6266
arm64 failure is infrastructure issue https://github.com/dotnet/core-eng/issues/6141

**Comment by erozenfeld** [comment]
Failures in corefx job are also present in the baseline run: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x80/861/consoleText
I opened #24509 to track. These are new failures, the job was successful yesterday.
System.Memory.Tests that this PR is fixing succeeded.
