### PR TITLE
Fix StackFrameIterator::IsValid check race

### LINKED ISSUE #21581: [Linux] GCStress=C assert: "(m_pStartFrame != NULL) || (m_flags & POPFRAMES) || (m_pRealStartFrame == m_pThread->GetFrame()) || (bRedirectedPinvoke)"
Seen in several arm32 GCStress=C runs, but not every run, and not the same test. Some examples:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_flow/44/
```
14:32:49       Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1038_Generated1038_Generated1038_._TypeGeneratorTests_TypeGeneratorTest1038_Generated1038_Generated1038_sh [FAIL]
14:32:49         
14:32:49 
        Assert failure(PID 443 [0x000001bb], Thread: 504 [0x01f8]): (m_pStartFrame != NULL) || (m_flags & POPFRAMES) || (m_pRealStartFrame == m_pThread->GetFrame()) || (bRedirectedPinvoke)
14:32:49             File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/vm/stackwalk.cpp Line: 1577
14:32:49             Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
14:32:49         
14:32:49         /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/Loader/classloader/TypeGeneratorTests/TypeGeneratorTest1038/Generated1038/Generated1038.sh: line 244:   443 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_flow/42/
```
11:36:45 
      GC_Coverage._LargeObjectAlloc2_LargeObjectAlloc2_._LargeObjectAlloc2_LargeObjectAlloc2_sh [FAIL]
11:36:45         
11:36:45 
        Assert failure(PID 28988 [0x0000713c], Thread: 29011 [0x7153]): (m_pStartFrame != NULL) || (m_flags & POPFRAMES) || (m_pRealStartFrame == m_pThread->GetFrame()) || (bRedirectedPinvoke)
11:36:45             File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/vm/stackwalk.cpp Line: 1577
11:36:45             Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
11:36:45         
11:36:45         /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/GC/Coverage/LargeObjectAlloc2/LargeObjectAlloc2.sh: line 244: 28988 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
```

### PR DESCRIPTION
**Pull request by janvorli**
During GC stress >= 4, there could be a race when we would compute
bRedirectedPinvoke as false, but before the condition of the following
_ASSERTE is evaluated, the thread that is being walked pushes a
ResumableFrame to the explicit frames stack of that thread in the GC
marker handler.

The fix to prevent this race is to evaluate all the conditions that
formed the bRedirectedPinvoke after the conditions in the _ASSERTE.

Close #21581

### CODE REVIEW

File: src/vm/stackwalk.cpp [hunk 1]
```diff
@@ -1545,28 +1545,26 @@ BOOL StackFrameIterator::IsValid(void)
...
+                  (m_pRealStartFrame == m_pThread->GetFrame())
+#ifdef FEATURE_HIJACK
+                  // In GCStress >= 4 two threads could race on triggering GC;
+                  // if the one that just made p/invoke call is second and hits the trap instruction
+                  // before call to synchronize with GC, it will push a frame [ResumableFrame on Unix 
+                  // and RedirectedThreadFrame on Windows] concurrently with GC stackwalking.
+                  // In normal case (no GCStress), after p/invoke, IL_STUB will check if GC is in progress and synchronize.
+                  ||
+                  ((GCStress<cfg_instr>::IsEnabled()) && 
+                   (m_pRealStartFrame != NULL) &&
```
Comment (jkotas) [inline src/vm/stackwalk.cpp]: Are these checks against `NULL` and `FRAME_TOP` needed? They are making the condition more complex than needed.

File: src/vm/stackwalk.cpp [hunk 2]
```diff
@@ -1545,28 +1545,26 @@ BOOL StackFrameIterator::IsValid(void)
...
-                              ((m_pThread->GetFrame()->GetVTablePtr() == ResumableFrame::GetMethodFrameVPtr()) ||
-                               (m_pThread->GetFrame()->GetVTablePtr() == RedirectedThreadFrame::GetMethodFrameVPtr())));
-#endif // FEATURE_HIJACK
-
         _ASSERTE( (m_pStartFrame != NULL) ||
                   (m_flags & POPFRAMES) ||
-                  (m_pRealStartFrame == m_pThread->GetFrame()) ||
-                  (bRedirectedPinvoke));
+                  (m_pRealStartFrame == m_pThread->GetFrame())
+#ifdef FEATURE_HIJACK
```
Comment (jkotas) [inline src/vm/stackwalk.cpp]: Should this mention the subtle race condition that this is fixing?

Also, this condition is super complex now. It would be nice to keep it split into two parts like it was before at least.

Comment (janvorli) [reply src/vm/stackwalk.cpp]: I've changed it, does it look good to you now?
