### PR TITLE
RyuJIT x86: Implement GS cookie check for functions with tailcall

### LINKED ISSUE #7086: RyuJIT x86: Assertion failed '!comp->getNeedsGSSecurityCookie()'
In Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.0x10

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=0x10

/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b441487/b441487/b441487.cmd

> D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(366081): error : JIT._Regression_CLR_x86_JIT_V2_0_Beta2_b441487_b441487_b441487_._Regression_CLR_x86_JIT_V2_0_Beta2_b441487_b441487_b441487_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\runtest.proj]
> Assert failure(PID 1816 [0x00000718], Thread: 7556 [0x1d84]): Assertion failed '!comp->getNeedsGSSecurityCookie()' in 'Test.FooException`1[Int32][System.Int32]:.ctor():this' (IL size 7)
> File: d:\j\workspace\x86_ryujit_ch---b330cdd2\src\jit\lower.cpp Line: 1697
> Image: D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b441487\b441487\b441487.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b441487.exe
> Running tests for System.String
> Foo
> hello from System.String
> CatchMe
> Test.FooException`1[System.String]: hello from System.String
> at Test.Widget`1.CatchMe() in D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\src\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b441487\b441487.il:line 120
> SyncIt
> hello from System.String
> Running tests for System.Int32
> Foo
> hello from System.Int32
> CatchMe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #7086, one of the most common asserts in stress runs.

I moved some helper code from the legacy codegen to codegencommon
so it could be used. I also added the code to generate the GS
cookie check for tailcall via helper code (on x64, we never
generate GS cookie checks when there are tailcalls).

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs8

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs8

**Comment by BruceForstall** [comment]
@sivarv PTAL
cc @dotnet/jit-contrib

File: src/jit/codegencommon.cpp [hunk 1]
```diff
@@ -10853,6 +10853,139 @@ unsigned CodeGen::getFirstArgWithStackSlot()
 
 #endif // !LEGACY_BACKEND && (_TARGET_XARCH_ || _TARGET_ARM64_)
 
+void CodeGen::genSinglePush()
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: How about moving the definitions of genSinglePusy/Pop() to codegen.h file since they are trivially in-lineable?

File: src/jit/codegencommon.cpp [hunk 2]
```diff
@@ -10853,6 +10853,139 @@ unsigned CodeGen::getFirstArgWithStackSlot()
...
+{
+    genStackLevel += sizeof(void*);
+}
+
+void CodeGen::genSinglePop()
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: From the name one thinks it will also generate code.  But it just adjusts stack level.  May be these should be renamed to genAdjustStackLevelForSinglePush/Pop() to be indicative of their purpose/functionality.  I know these are pre-existing routines and you didn't introduce them.  I would leave it to your call.

File: src/jit/codegencommon.cpp [hunk 3]
```diff
@@ -10853,6 +10853,139 @@ unsigned CodeGen::getFirstArgWithStackSlot()
...
+    genStackLevel -= sizeof(void*);
+}
+
+/*****************************************************************************
+ *
+ *  Push the given registers.
+ *  This function does not check if the register is marked as used, etc.
+ */
+
+regMaskTP CodeGen::genPushRegs(regMaskTP regs, regMaskTP* byrefRegs, regMaskTP* noRefRegs)
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: Since you are at it, please see if you could add standard function header for this one and genPopRegs() below.

File: src/jit/codegenxarch.cpp [hunk 4]
```diff
@@ -297,14 +307,19 @@ void CodeGen::genEmitGSCookieCheck(bool pushReg)
...
+            assert((int)compiler->gsGlobalSecurityCookieVal == (ssize_t)compiler->gsGlobalSecurityCookieVal);
             getEmitter()->emitIns_S_I(INS_cmp, EA_PTRSIZE, compiler->lvaGSSecurityCookie, 0,
                                       (int)compiler->gsGlobalSecurityCookieVal);
         }
     }
     else
     {
         // Ngen case - GS cookie value needs to be accessed through an indirection.
+
+        pushedRegs = genPushRegs(regMaskGSCheck, &byrefPushedRegs, &norefPushedRegs);
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: Is it guaranteed that eax never contains a ref/byref type value at the time when we are emitting a gs cookie check?  Because genPushRegs()/genPopRegs() is going to treat eax as TYP_I_IMPL (TYP_INT on x86).  Is it possible to assert this assumption here?

File: src/jit/codegenxarch.cpp [hunk 5]
```diff
@@ -6184,6 +6201,14 @@ void CodeGen::genCallInstruction(GenTreePtr node)
 
 #endif // defined(_TARGET_X86_)
 
+    if (call->IsTailCallViaHelper())
+    {
+        if (compiler->getNeedsGSSecurityCookie())
+        {
+            genEmitGSCookieCheck(true);
+        }
+    }
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: The above logic needs to be under #if defined(_TARGET_X86_)?
Note: there is such a #ifdef on line 6191 to 6202, we can include this logic in that.

File: src/jit/codegencommon.cpp (hunk 1 above)
Comment (BruceForstall) [inline src/jit/codegencommon.cpp]: Well, I moved it from codegenlegacy.cpp to codegencommon.cpp.

In general, I prefer to not put implementations of any kind into header files, under the assumption that a RET build will do full, global, cross-module inlining.

File: src/jit/codegencommon.cpp (hunk 2 above)
Comment (BruceForstall) [inline src/jit/codegencommon.cpp]: There are about 40 instances of these, so I'd prefer to just leave them as-is.

File: src/jit/codegenxarch.cpp (hunk 4 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: genPushRegs() uses gcInfo.gcRegGCrefSetCur and gcInfo.gcRegByrefSetCur to determine how to treat EAX when pushing it. As long as those are correct, we are good.

File: src/jit/codegenxarch.cpp (hunk 5 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: I put it under `#ifdef _TARGET_X86_`. Turns out I think it doesn't matter because AMD64 would never set to do GS cookie and tailcall.

**Comment by BruceForstall** [comment]
Pushed comment changes

File: src/jit/codegenxarch.cpp (hunk 5 above)
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: I know.  But I thought it is better not to execute code which is not required in the first place.  Besides, #ifdef is very nearby :)

**Comment by sivarv** [comment]
Looks good.
