### PR TITLE
Fail loading types with default interface methods for fragile ngen

### LINKED ISSUE #15682: [Default interfaces] NGen support
We should fail loading the type and leave a hole in the fragile image. The type will be loaded at runtime.

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
We are not generating the right data structures for this. Since fragile crossgen is no longer a mainstream scenario, it's not worth the effort to add default interface methods support for it.

This avoids `!"Precode::GetPrecodeFromEntryPoint: Unexpected code in precode"` and similar issues.

Fixes #15682.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @sergiy-k

File: src/vm/classcompat.cpp [hunk 1]
```diff
@@ -2596,9 +2596,14 @@ VOID    MethodTableBuilder::EnumerateClassMethods()
             }
         }
 
-#ifndef FEATURE_DEFAULT_INTERFACES
         // Some interface checks.
```
Comment (jkotas) [inline src/vm/classcompat.cpp]: You can keep this under `#ifdef FEATURE_NATIVE_IMAGE_GENERATION` to make it clear that this check kicks in under crossgen only.

File: src/vm/classcompat.cpp [hunk 2]
```diff
@@ -2596,9 +2596,14 @@ VOID    MethodTableBuilder::EnumerateClassMethods()
...
-        if (fIsClassInterface)
+        // Ngen wasn't upgraded to deal with default interface methods.
+        if (fIsClassInterface
+            && IsCompilationProcess()
+#if FEATURE_READYTORUN
```
Comment (jkotas) [inline src/vm/classcompat.cpp]: You do not need this ifdef. `IsReadyToRunCompilation` is implemented to return false when `FEATURE_READYTORUN` is not compiled.

File: src/vm/methodtablebuilder.cpp [hunk 3]
```diff
@@ -2908,9 +2908,15 @@ MethodTableBuilder::EnumerateClassMethods()
             }
         }
 
-#ifndef FEATURE_DEFAULT_INTERFACES
         // Some interface checks.
-        if (fIsClassInterface)
+        // We only need them if default interface method support is disabled or if this is fragile crossgen
+#if !FEATURE_DEFAULT_INTERFACES || FEATURE_NATIVE_IMAGE_GENERATION
```
Comment (jkotas) [inline src/vm/methodtablebuilder.cpp]: Nit: CoreCLR uses "defined" for ifdefs everywhere, e.g.  `#if !defined(FEATURE_DEFAULT_INTERFACES) || defined(FEATURE_NATIVE_IMAGE_GENERATION)`. I am not sure why, but it would be nice to have a consistent style.
