### PR TITLE
Fix to issue #2970

### LINKED ISSUE #2970: Assert failure in SIMD tests
Here's a link to the failing test binaries: \\scratch2\scratch\swaroops\Test\SIMD 

```
FAILED   - JIT/SIMD/Vector3_ro/Vector3_ro.sh
               BEGIN EXECUTION
               /home/swaroops/test/Tests/coreoverlay/corerun Vector3_ro.exe
               
               Assert failure(PID 53770 [0x0000d20a], Thread: 53770 [0xd20a]): Assertion failed '!treeNode->InReg()' in 'VectorTests.Program:Main(ref):int' (IL size 88)
               
                   File: /home/swaroops/git/coreclr/src/jit/codegenxarch.cpp Line: 2667
                   Image: /home/swaroops/test/Tests/coreoverlay/corerun
               
               **** MessageBox invoked, title 'corerun - Assert Failure (PID 53770, Thread 53770/0xd20a)' ****
                 Assertion failed '!treeNode->InReg()' in 'VectorTests.Program:Main(ref):int' (IL size 88)
               
               
               /home/swaroops/git/coreclr/src/jit/codegenxarch.cpp, Line: 2667
               
               Abort - Kill program
               Retry - Debug
               Ignore - Keep running
               
               
               Image:
               /home/swaroops/test/Tests/coreoverlay/corerun
               
               ********
               
               ./Vector3_ro.sh: line 55: 53770 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Vector3_ro.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION – FAILED
```

```
FAILED   - JIT/SIMD/Vector4_ro/Vector4_ro.sh
               BEGIN EXECUTION
               /home/swaroops/test/Tests/coreoverlay/corerun Vector4_ro.exe
               
               Assert failure(PID 53831 [0x0000d247], Thread: 53831 [0xd247]): Assertion failed '!treeNode->InReg()' in 'VectorTests.Program:Main(ref):int' (IL size 98)
               
                   File: /home/swaroops/git/coreclr/src/jit/codegenxarch.cpp Line: 2667
                   Image: /home/swaroops/test/Tests/coreoverlay/corerun
               
               **** MessageBox invoked, title 'corerun - Assert Failure (PID 53831, Thread 53831/0xd247)' ****
                 Assertion failed '!treeNode->InReg()' in 'VectorTests.Program:Main(ref):int' (IL size 98)
               
               
               /home/swaroops/git/coreclr/src/jit/codegenxarch.cpp, Line: 2667
               
               Abort - Kill program
               Retry - Debug
               Ignore - Keep running
               
               
               Image:
               /home/swaroops/test/Tests/coreoverlay/corerun
               
               ********
               
               ./Vector4_ro.sh: line 55: 53831 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Vector4_ro.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by sivarv**
The repro is a case of one of the method called is returning Vector3/4 type value. On unix such a struct will gets returned in two registers and hence will be assigned to a local by importer and marked as multiRegArgOrRet=1. But it doesn't ensure that the local will not be register allocated. For the repro case it gets register allocated.

IR: GT_LCL_FLD(tmp1) = GT_CALL returning SIMD12

Codgen routine genStoreRegisterReturnInLclVar(), for stroing a struct returned in two registers to a lcl var or lcl_fld, is making an assumption that lcl var will be on stack not in a register. This may not be true for SIMD structs returned in two registers.

For now to workaround Codegen limitation marking tmp1 as DoNoEnregister. Rest of the changes are minor stylistic code cleanup for improving readability.

Fixes #2970

### CODE REVIEW

**Comment by sivarv** [comment]
Will file a Git Issue to track CQ improvement for calls returning SIMD type vectors returned in two registers not to mark tmp lcl var to which the return value of call is assigned as DoNotEnregister=1.

**Comment by sivarv** [comment]
@dotnet/jit-contrib - please review this

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -13507,19 +13514,31 @@ GenTreePtr Compiler::impAssignStructClassToVar(GenTreePtr op, CORINFO_CLASS_HAND
...
+
     // Mark the var to store the eightbytes on stack non promotable.
     // The return value is based on eightbytes, so all the fields need 
     // to be on stack before loading the eightbyte in the corresponding return register.
     lvaTable[tmpNum].lvIsMultiRegArgOrRet = true;
+
+    // TODO-Amd64-Unix-CQ: Right now codegen assumes that tmpNum lcl var is on stack and 
+    // and not lives in a register.  For example, consider Vector3/4 return value of
+    // a call is assigned to tmpNum.  In such a case tmpNum will be of SIMD type and
+    // will be allocated a register unless explicitly marked as DoNotEnregister.
```
Comment (CarolEidt) [inline src/jit/importer.cpp]: It could be confusing that marking it as "lvIsMultiRegArgOrRet" is not sufficient. That merely keeps its fields from being promoted, not from being "fully enregistered" as the SIMD lclVars can be. I would add that to your comment. Also, some minor editorial suggestions:
"and and not lives in a register" => "and does not live in a register"
"consider Vector3/4 return value" => "consider the case where a Vector3/4 return value"

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -13507,19 +13514,31 @@ GenTreePtr Compiler::impAssignStructClassToVar(GenTreePtr op, CORINFO_CLASS_HAND
...
+    //
+    // For now to workaround codegen limitation marking tmpNum as DoNotEnregister.
+    lvaTable[tmpNum].lvDoNotEnregister = true;
```
Comment (CarolEidt) [inline src/jit/importer.cpp]: I think this is overly conservative, and should be changed to:
```
if (varTypeIsSIMD(op))
{
    lvaTable[tmpNum].lvDoNotEnregister = true;
}
```

Comment (CarolEidt) [inline src/jit/importer.cpp]: Or perhaps to be more future-proof:
```
if (varTypeIsEnregisterableStruct(op))
```

Comment (sivarv) [inline src/jit/importer.cpp]: If tmpNum is non-enregistrable struct, not setting DoNotEnregister would it fetch us any value?

Comment (CarolEidt) [inline src/jit/importer.cpp]: It will not make a material difference now, but I think it is more precise in its application - for example, if we address the unix issue with handling lclVars marked `lvIsMultiRegArgOrRet` (e.g. by reassembling them or something), we may still need to be conservative with lclVars that can be full enregistered, but wouldn't want to pessimize all cases.

**Comment by sivarv** [comment]
@CarolEidt - incorporated your review feedback. Please review this.

**Comment by CarolEidt** [comment]
LGTM

**Comment by briansull** [comment]
LGTM
