### PR TITLE
Handle partial multireg COPY

### LINKED ISSUE #20063: [X64/Ubuntu] jitstressregs8 failure in StructABI test
There are also 8 failures in the corefx tests with jitstressregs8:
```
System.Linq.Parallel.Tests.AverageTests.Average_Float(count: 2, average: 0.5)
System.Linq.Parallel.Tests.AverageTests.Average_Float(count: 16, average: 7.5)
System.Linq.Parallel.Tests.AverageTests.Average_Float_SomeNull(count: 16, average: 7.5)
System.Linq.Parallel.Tests.AverageTests.Average_Double(count: 2, average: 0.5)
System.Linq.Parallel.Tests.AverageTests.Average_Double(count: 16, average: 7.5)
System.Linq.Parallel.Tests.AverageTests.Average_Double_SomeNull(count: 16, average: 7.5)
DataContractJsonSerializerTests.DCJS_Dictionary_UseSimpleDictionaryFormat_VariousKeyTypes
System.Collections.Immutable.Tests.ImmutableDictionaryTest.ToImmutableDictionary
```
When this bug is fixed, these should be check, and if they still fail, new issue(s) should be opened.

### PR DESCRIPTION
**Pull request by CarolEidt**
A multireg COPY will only have a valid register for indices that require copying. Thus, the `GetRegCount` method must return the highest index that has a valid register.

Fix #20063

### CODE REVIEW

**Comment by CarolEidt** [comment]
Also added an extra line to the jitdump when we generate a COPY with a register index > 0.

**Comment by CarolEidt** [comment]
This fixes the StructABI test case. I'll run the corefx tests with jitStressRegs=8 to see whether it fixes the other test cases mentioned in the issue.

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Checked jitstressregs8
@dotnet-bot test Ubuntu x64 Checked corefx_jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
test Ubuntu16.04 arm64 Cross Checked Innerloop Build and Test

File: src/jit/gentree.h [hunk 1]
```diff
@@ -5535,22 +5535,21 @@ struct GenTreeCopyOrReload : public GenTreeUnOp
 
     unsigned GetRegCount()
     {
-        if (gtRegNum == REG_NA)
-        {
-            return 0;
-        }
 #if FEATURE_MULTIREG_RET
-        for (unsigned i = 0; i < MAX_RET_REG_COUNT - 1; ++i)
+        // We need to return the highest index for which we have a valid register.
```
Comment (BruceForstall) [inline src/jit/gentree.h]: So there can be cases where `gtOtherRegs[0] == REG_NA` but `gtOtherRegs[1] != REG_NA`? I don't understand how that would happen, but nonetheless, it seems there should be a comment explaining this can happen. I thought a lot of these various multireg functions assumed there were no "holes" in the register sets.

**Comment by BruceForstall** [comment]
btw, don't worry about waiting for the job I triggered. I just needed some PR to use to trigger it, and I didn't create my own dummy PR...

File: src/jit/gentree.h (hunk 1 above)
Comment (CarolEidt) [reply src/jit/gentree.h]: @BruceForstall - The case with "holes" can only be true for the COPY or RELOAD - these are the cases where only the registers that need the be handled are something other than `REG_NA`. I'll add a comment.

**Comment by CarolEidt** [comment]
The Ubuntu x64 corefx failures seem to be something new (and have been seen in various corefx runs, e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_tieredcompilation/lastFailedBuild/)

**Comment by sandreenko** [comment]
@CarolEidt Are you awaiting another PR to be merged before this one?

**Comment by CarolEidt** [comment]
> Are you awaiting another PR to be merged before this one?

No, I'm waiting for arm/arm64 testing, but perhaps it's best to just merge this.
