### PR TITLE
Delete move to return spill in the implicit tail call in the inlinee with several returns.

### LINKED ISSUE #14783: Assertion failed 'retExpr->gtOper == GT_RETURN'
Failure in x64 checked corefx jitstress1 job:

```
Assert failure(PID 7916 [0x00001eec], Thread: 11608 [0x2d58]): Assertion failed 'retExpr->gtOper == GT_RETURN' in '<>c__DisplayClass24_0:<GetXml_WithoutInfo>b__0():ref:this' (IL size 12)
  
      File: d:\j\workspace\x64_checked_w---70be59df\src\jit\morph.cpp Line: 8724
      Image: D:\j\workspace\x64_checked_w---70be59df\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1_prtest/1/

Failure in `System.Security.Cryptography.Xml.Tests` test.

### PR DESCRIPTION
**Pull request by sandreenko**
If the inlinee has to spill returns as a temp, then the compiler adds spill between call and return, the actual return instruction is shared across several spills  and is located in another block. Do not do the tail call optimization.

The second commit fixes #14783 .

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Seems to me that the check jit paranoia around tail calls is the problem. I would like to see you try and fix that instead of disabling the optimization.

For instance you could note which locals are return spill temps and in the tail call checks, tolerate assignments of call return values to those temps after tail calls. We do something similar already for chains of converts.

If you have a non-stress test case for this please add it as a regression. If we can't reach this case without stress it would be good to understand why.

**Comment by sandreenko** [comment]
> If you have a non-stress test case for this please add it as a regression. If we can't reach this case without stress it would be good to understand why.

I described in the issue that it is possible to hit this without JitStress. However, it doesn't seem reasonable to construct such case now.

> Seems to me that the check jit paranoia around tail calls is the problem. I would like to see you try and fix that instead of disabling the optimization.

The issue was noway_assert, so we recompiled it with min_opts for release version.

> For instance you could note which locals are return spill temps and in the tail call checks, tolerate assignments of call return values to those temps after tail calls. We do something similar already for chains of converts.

Yes, I have tried it, the problem is that the return, that we should delete is located in another block and shared across several spills.

**Comment by AndyAyersMS** [comment]
I'm still not sure this case is reachable without some kind of unusual operating mode. I've made some attempts to repro without any luck.

Can you share out the jit dump from the failure you see w/o tail call stress in a gist? I would like to understand how it is a statement ends up after the call to "call3".

**Comment by sandreenko** [comment]
@AndyAyersMS did you try to `set complus_jitstressmodenames=STRESS_LEGACY_INLINE` without `complus_jitstress`, was you able to repro the issue?

**Comment by sandreenko** [comment]
@AndyAyersMS I added a commit that turned the optimization back for you to look. However, I would prefer to drop it and merge PR with disabling this feature.

If we want to do honest tail call optimization inside an inline, we should not create `impInlineInfo->retExpr` and import returns inside the inline. It will prevent us from creating a merge block and these temp spill variables.

In the current state this optimization looks too fragile to be done.

**Comment by AndyAyersMS** [comment]
No, I tried writing a repro case from scratch given your description of the call tree that would lead to a problem. There must be something else involved since I can't get my repro attempts to generate the pattern you show in the issue.

If you have your dumps I can just look at those. If you don't have them anymore then I'll set up CoreFx testing and repro the original issue and then go from there.

**Comment by sandreenko** [comment]
I do not know a good way how to attach a file here, so the [link](https://1drv.ms/t/s!Au1EtB0f4I5ujeRKo9gpTy2VkuS-lg): 
- only STRESS_LEGACY_INLINE is set;
- [000018] is call that we inline (`CALL nullcheck ref    System.Security.Cryptography.Xml.Signature.GetXml (exactContextHnd=0x00007FFCC6457829)).
-[000060] call, that we marked as implicit tail call inside [000018];
-[000022] move that we create to save the result of [000060] in the `lvaInlineeReturnSpillTemp`.

**Comment by AndyAyersMS** [comment]
Ok, I have a repro case... might be possible to simplify this further, but this triggers the original bug without any stress settings.
```C#
using System;
using System.Runtime.CompilerServices;

// Tail call issue

class P
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static string X(string s)
    {
        return s;
    }

    public static string X1(string s, string q)
    {
        for (int k = 0; k < 10; k++)
        {
            s = X(s);
        }

        return s;
    }

    public static string D(string x)
    {
        string a = x;
        string b = x;
        return X1(a, b);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static string C(string x)
    {
        string s = x;

        if (s.Length > 3)
        {
            return D(s);
        }
        else
        {
            return X(s);
        }
    }


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static string B(string x)
    {
        return C(x);
    }

    public static string A(string x)
    {
        string s = x;

        for (int k = 0; k < 10; k++)
        {
            s = X(s);
        }

        return B(x);
    }

    public static int Main()
    {
        string v = A("Hello");
        return v.Length + 95;
    }
}
```

**Comment by AndyAyersMS** [comment]
Thinking about this some more, it seems odd that we check what is essentially precondition after partially starting the tail call transformation, and so have to resort to `noway_assert` to back out if we see something unexpected.

I would suggest doing the following: 
* move the check for "what kind of statement can safely follow the call" up above to where all the other precondition checks happen.
* in that check, bail out of the tail call without asserting if we see the case we're discussing here where there is a post-call assignment. 
* simplify the current check to just delete statements as we've already pre-qualified them as safe to remove
* add the simple repro above as a test case and verify it bails out as expected
* open an issue for either generalizing how we handle the precondition check (to tolerate the extra assignment) and/or try to avoid creating things that need cleanup in the first place (might be hard because earlier we don't know for sure if we will tail call call, only that we might)
* report back with asm diffs (probably from SPMI as R2R disables tail calls in lots of cases)

This should be more targeted than what you originally proposed, as it's not just having the return spill temp that triggers the problem.

**Comment by sandreenko** [comment]
Thank you @AndyAyersMS for  the repro.

> move the check for "what kind of statement can safely follow the call" up above to where all the other precondition checks happen.

There are two parts of precondition checks: in the importer and in the morphCall, we don't have enough information in the importer, but I will try to move it up in the morphCall.

>report back with asm diffs (probably from SPMI as R2R disables tail calls in lots of cases)

Implicit tail calls in the inlinee are enabled only with `FEATURE_TAILCALL_OPT_SHARED_RETURN` that is disabled for Desktop. There are no spmi diffs.

**Comment by sandreenko** [comment]
PR was updated, there was a typo in the third commit that caused CI failures. The Andy's test was added.

**Comment by sandreenko** [comment]
> - move the check for "what kind of statement can safely follow the call" up above to where all the other precondition checks happen.
> - in that check, bail out of the tail call without asserting if we see the case we're discussing here where there is a post-call assignment.
> - simplify the current check to just delete statements as we've already pre-qualified them as safe to remove

There is no place where we can move it. It has to be inside `fgMorphCall`, moving it several lines up doesn't make a difference. I can refactor this `if (call->CanTailCall())` block, if we want to spend our calories on it.

If you want to move it into the importer, than it looks too aggresive to me, it is the same as delete all these noway asserts and just remove all stmts after the call.

> - add the simple repro above as a test case and verify it bails out as expected

Done.

> - report back with asm diffs (probably from SPMI as R2R disables tail calls in lots of cases)
No diffs.

**Comment by AndyAyersMS** [comment]
Right, the importer is too early.

The checks should be in `fgMorphCall` within the initial `CanTailCall` block along with all the other screening checks.

**Comment by sandreenko** [comment]
PR was updated, checks were moved up. The question is how we want to react on them when they fail? In the past it was `noway_assert`, do we want to keep them or return false in release, but blow assert in debug?

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -19624,3 +19534,136 @@ bool Compiler::fgMorphCombineSIMDFieldAssignments(BasicBlock* block, GenTreePtr
...
+                    treeWithLcl = treeWithLcl->gtGetOp1();
+                }
+
+                noway_assert(callResultLclNumber == treeWithLcl->AsLclVarCommon()->gtLclNum);
+
+                nextMorphStmt = retStmt->gtNextStmt;
+            }
+        }
+    }
+    return nextMorphStmt == nullptr;
```
Comment (sandreenko) [inline src/jit/morph.cpp]: Maybe we should do `assert(nextMorphStmt == nullptr)` here, to catch possible regressions in the future.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -8632,115 +8637,20 @@ GenTreePtr Compiler::fgMorphCall(GenTreeCall* call)
             // Peel off casts
             while (treeWithCall->gtOper == GT_CAST)
             {
-                noway_assert(!treeWithCall->gtOverflow());
+                assert(!treeWithCall->gtOverflow());
                 treeWithCall = treeWithCall->gtGetOp1();
             }
 
-            noway_assert(treeWithCall == call);
+            assert(treeWithCall == call);
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: I think maybe these should stay as `noway_asserts` ?

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -19624,3 +19534,136 @@ bool Compiler::fgMorphCombineSIMDFieldAssignments(BasicBlock* block, GenTreePtr
...
+        {
+            break;
+        }
+        stmt = stmt->gtNext;
+    }
+}
+
+#endif // !FEATURE_CORECLR && _TARGET_AMD64_
+
+bool Compiler::fgCheckStmtAfterTailCall()
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Please add a header comment.

It would be helpful if the comment summarized the "expected" types of instructions that can follow a tail call in a block.

File: src/jit/morph.cpp [hunk 4]
```diff
@@ -19624,3 +19534,136 @@ bool Compiler::fgMorphCombineSIMDFieldAssignments(BasicBlock* block, GenTreePtr
 }
 
 #endif // FEATURE_SIMD
+
+#if !defined(FEATURE_CORECLR) && defined(_TARGET_AMD64_)
+GenTreeStmt* skipNopStmts(GenTreeStmt* stmt)
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Seems like this is simple enough to maybe just have inline?

File: src/jit/morph.cpp [hunk 5]
```diff
@@ -19624,3 +19534,136 @@ bool Compiler::fgMorphCombineSIMDFieldAssignments(BasicBlock* block, GenTreePtr
...
+            noway_assert(retExpr->gtOper == GT_RETURN);
+
+            nextMorphStmt = retStmt->gtNextStmt;
+        }
+        else
+        {
+            noway_assert(callExpr->gtGetOp1()->OperIsLocal());
+            unsigned callResultLclNumber = callExpr->gtGetOp1()->AsLclVarCommon()->gtLclNum;
+
+#if defined(FEATURE_CORECLR)
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: This should probably use the same feature key we use earlier to allow inlinee call sites to be come tail call candidates.  It so happens that the two are correlated today, but they may not always be that way.

File: src/jit/morph.cpp (hunk 2 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: It is `ifdef DEBUG`, so I think we do not want to use `noway_assert` in debug-only code.

File: src/jit/morph.cpp (hunk 3 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: Fixed, but the patterns are described in the body.

File: src/jit/morph.cpp (hunk 5 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: Thanks, fixed

**Comment by sandreenko** [comment]
@dotnet-bot test ci please

File: src/jit/morph.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Ah, good point.

**Comment by sandreenko** [comment]
@dotnet-bot test ci please

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Comment by sandreenko** [comment]
@dotnet-bot test this please

**Comment by sandreenko** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu armlb Cross Debug Innerloop Build

**Comment by sandreenko** [comment]
So Ci is almost stable now, so this PR is ready to be merged.
Please take another look @AndyAyersMS.
