### PR TITLE
Finish deleting dead CAS code from CoreLib

### LINKED ISSUE #9321: Remove CAS from CoreLib
There is lots of CAS-only code -- CodeAccessPermission and related types and code that uses them. Ideally it would all be removed. I'm guessing one thing to take care of is making sure we continue to do the same parameter validation/throw the same exceptions. That has been a gotcha for IO in the past.

Removing remaining FEATURE_CAS_POLICY on the native side is already tracked by https://github.com/dotnet/coreclr/issues/9067

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #9321 and deletes CleanupToDoList.cs

### CODE REVIEW

File: src/mscorlib/src/System/Reflection/Emit/AssemblyBuilder.cs [hunk 1]
```diff
@@ -38,7 +38,6 @@ namespace System.Reflection.Emit
     using System.Runtime.Serialization;
```
Comment (danmosemsft) [inline src/mscorlib/src/System/Reflection/Emit/AssemblyBuilder.cs]: comment at the top of this file refers to low trust code ,may need updating.

Comment (danmosemsft) [inline src/mscorlib/src/System/Reflection/Emit/AssemblyBuilder.cs]: Nevermind, I guess.., I see countless other remnants of what looks CAS related. Just searching for "partial.*trust", grants, "full.*trust" and the like. It will probably take a long time to see the last of that and it's best to take it in manageable bites.

**Comment by danmosemsft** [comment]
@jkotas since there's a lot of churn here and it's basically cleanup, what do you think of holding off merging for a few days, to let 2.0 get out the branch? If so we should label no-merge.

**Comment by jkotas** [comment]
Agree.

**Comment by jkotas** [comment]
CoreCLR.dll x64 release is 110k smaller

**Comment by jkotas** [comment]
@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test test Windows_NT x64 corefx_baseline

**Comment by jkotas** [comment]
@dotnet-bot test Tizen armel Cross Release Build  please
