### PR TITLE
Fix the type of the data field of a typed ref on x86.

### LINKED ISSUE #7551: RyuJIT x86: [GCStress=0xC] SanityCheck()
```
02:49:46 D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(272379): error : JIT._Methodical_refany_lcs_lcs_._Methodical_refany_lcs_lcs_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---ddc305d1\tests\runtest.proj]
02:49:46         
02:49:46         Assert failure(PID 3332 [0x00000d04], Thread: 9092 [0x2384]): SanityCheck()
02:49:46         
02:49:46         CORECLR! MethodTable::Validate + 0x3B (0x70bbfdca)
02:49:46         CORECLR! Object::ValidateInner + 0x1E0 (0x708ebfd0)
02:49:46         CORECLR! Object::Validate + 0x152 (0x708ebb72)
02:49:46         CORECLR! Object::ValidatePromote + 0x11 (0x708ec41d)
02:49:46         CORECLR! WKS::GCHeap::Promote + 0x118 (0x70e16bb8)
02:49:46         CORECLR! PromoteCarefully + 0x8E (0x70b5188e)
02:49:46         CORECLR! GcEnumObject + 0x51 (0x70d4f391)
02:49:46         CORECLR! EECodeManager::EnumGcRefs + 0xE40 (0x70b752a0)
02:49:46         CORECLR! GcStackCrawlCallBack + 0x178 (0x70d4f798)
02:49:46         CORECLR! Thread::MakeStackwalkerCallback + 0x45 (0x709541f5)
02:49:46             File: d:\j\workspace\x86_ryujit_ch---ddc305d1\src\vm\methodtable.cpp Line: 9797
02:49:46             Image: D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
02:49:46         
02:49:46         
02:49:46   
02:49:46   Return code:      1
02:49:46   Raw output file:      D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\refany\lcs\lcs.output.txt
02:49:46   Raw output:
02:49:46   BEGIN EXECUTION
02:49:46          "D:\j\workspace\x86_ryujit_ch---ddc305d1\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" lcs.exe 
02:49:46         Expected: 100
02:49:46         Actual: 123456789
02:49:46         END EXECUTION - FAILED
02:49:46         FAILED
02:49:46         Test Harness Exitcode is : 1
02:49:46         
02:49:46   To run the test:
02:49:46   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
02:49:46   > D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\JIT\Methodical\refany\lcs\lcs.cmd
02:49:46   
02:49:46         Expected: True
02:49:46         Actual:   False
02:49:46           D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(272379,0): at JIT._Methodical_refany_lcs_lcs_._Methodical_refany_lcs_lcs_cmd()
```

### PR DESCRIPTION
**Pull request by pgavlin**
This field should be of type byref; not treating it as such causes GC
holes when passing typed references.

Fixes #7551.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @adiaaida @dotnet/jit-contrib PTAL

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -4110,7 +4110,7 @@ GenTreeCall* Compiler::fgMorphArgs(GenTreeCall* callNode)
 
             // Build the mkrefany as a GT_FIELD_LIST
             GenTreeFieldList* fieldList = new (this, GT_FIELD_LIST)
-                GenTreeFieldList(argx->gtOp.gtOp1, offsetof(CORINFO_RefAny, dataPtr), TYP_I_IMPL, nullptr);
+                GenTreeFieldList(argx->gtOp.gtOp1, offsetof(CORINFO_RefAny, dataPtr), TYP_BYREF, nullptr);
```
Comment (sivarv) [inline src/jit/morph.cpp]: >             GenTreeFieldList(argx->gtOp.gtOp1, offsetof(CORINFO_RefAny, dataPtr), TYP_BYREF, nullptr) [](start = 3, length = 102)

I see the same issue present even on non-x86 on line 4129

**Comment by adiaaida** [comment]
Lgtm

**Comment by CarolEidt** [comment]
:shipit:

**Comment by CarolEidt** [comment]
LGTM. Thanks.
