### PR TITLE
[x86/Linux] Enable FEATURE_EH_FUNCLETS

### LINKED ISSUE #8887: [x86/Linux] Support Simple Exception Catch
I attempted to execute the following program with x86/Linux port:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            Console.WriteLine("Hello World!");
            throw new ArgumentException();
        }
        catch (Exception e)
        {
            Console.WriteLine("Caught");
        }
    }
}
```

CoreCLR currently shows the following assert failure for the above example:
```
Assert failure(PID 19154 [0x00004ad2], Thread: 19154 [0x4ad2]): iUnwindInfo < GetNumberOfUnwindInfos()
    File: /home/parjong/projects/dotnet/coreclr/src/vm/codeman.h Line: 342
    Image: /root/dotnet-test/overlay/current/corerun
```

### PR DESCRIPTION
**Pull request by parjong**
This commit revises JIT to generate code based on EH FUNCLETS for x86/Linux that could call ``DispatchManagedException``.

The main changes are as follows:
 - Add unwindx86.cpp and unwindxarch.cpp
 - (Partially) Implement Funclet Prolog/Epilog Codegen for x86
 - Remove JIT_EndCatch workaround introduced in #8629.

This commit (partially) fixes #8887

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark

File: src/vm/jitinterface.cpp [hunk 1]
```diff
@@ -10882,6 +10882,31 @@ void CEEJitInfo::CompressDebugInfo()
     EE_TO_JIT_TRANSITION();
 }
 
+void increaseUnwindInfoSize(ULONG &unwindSize)
+{
+#if defined(_TARGET_AMD64_) || defined(_TARGET_X86_)
+    // Add space for personality routine, it must be 4-byte aligned.
+    // Everything in the UNWIND_INFO up to the variable-sized UnwindCodes
+    // array has already had its size included in unwindSize by the caller.
+    unwindSize += sizeof(ULONG);
```
Comment (jkotas) [inline src/vm/jitinterface.cpp]: We should not need the personality routine on x86. Also, the x64 unwind info codes referred to in next comment do not make sense on x86.

File: src/vm/jitinterface.cpp [hunk 2]
```diff
@@ -10914,27 +10939,7 @@ void CEEJitInfo::reserveUnwindInfo(BOOL isFunclet, BOOL isColdCode, ULONG unwind
```
Comment (jkotas) [inline src/vm/jitinterface.cpp]: Will the JIT ever pass non-zero unwindSize here for x86 Linux? If the unwindSize is always zero on x86 Linux, this method should do nothing for x86.

Comment (parjong) [inline src/vm/jitinterface.cpp]: @jkotas I'm not sure. ``Compiler::unwindReserveFuncHelper`` seems to pass ``sizeof(func->unwindCodes) - func->unwindCodeSlot;`` as ``unwindSize`` into ``CEEJitInfo::reserveUnwindInfo``.

Is there any documented standard related with x86? I read https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md , but some x86-related stuffs are missing.

Comment (jkotas) [inline src/vm/jitinterface.cpp]: There is no standard unwind information on Windows x86. In CoreCLR, we just store the unwind information as part of the GCInfo on x86.

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by parjong** [comment]
@jkotas @janvorli @dotnet/jit-contrib Please take a look.

File: src/vm/jitinterface.cpp (hunk 2 above)
Comment (parjong) [inline src/vm/jitinterface.cpp]: ``increaseUnwindInfoSize`` now does nothing for x86.

File: src/vm/jitinterface.cpp [hunk 3]
```diff
@@ -10882,6 +10882,33 @@ void CEEJitInfo::CompressDebugInfo()
     EE_TO_JIT_TRANSITION();
 }
 
+void increaseUnwindInfoSize(ULONG &unwindSize)
```
Comment (janvorli) [inline src/vm/jitinterface.cpp]: This function adds space for the personality routine only, so it would be better to name it to reflect that.

File: src/jit/compiler.h [hunk 4]
```diff
@@ -1771,7 +1773,11 @@ class Compiler
     // a PSPSym for functions with any EH.
     bool ehNeedsPSPSym() const
     {
+#ifdef _TARGET_X86_
```
Comment (janvorli) [inline src/jit/compiler.h]: Why is this change needed? We use the PSPSym for for ARM32, ARM64 and amd64, so why should it be different for x86 Linux?

File: src/jit/compiler.h [hunk 5]
```diff
@@ -1133,7 +1133,8 @@ struct FuncInfoDsc
                                // funclet. It is only valid if funKind field indicates this is a
                                // EH-related funclet: FUNC_HANDLER or FUNC_FILTER
 
-#if defined(_TARGET_AMD64_)
+#if FEATURE_EH_FUNCLETS
+#if defined(_TARGET_XARCH_)
```
Comment (janvorli) [inline src/jit/compiler.h]: Why is this needed? It seems to be AMD64 specific.

File: src/jit/codegencommon.cpp [hunk 6]
```diff
@@ -8760,10 +8760,10 @@ void CodeGen::genFnProlog()
     genZeroInitFrame(untrLclHi, untrLclLo, initReg, &initRegZeroed);
 
 #if FEATURE_EH_FUNCLETS
-
+#ifndef _TARGET_X86_
```
Comment (janvorli) [inline src/jit/codegencommon.cpp]: I think we need it for x86 with EH funclets too. What was the reason for excluding it?

File: src/inc/clrnt.h [hunk 7]
```diff
@@ -789,6 +789,8 @@ typedef struct _DYNAMIC_FUNCTION_TABLE {
 //
 #ifdef _TARGET_AMD64_
 
+#define COMPACT_RUNTIME_FUNCTION        0
```
Comment (janvorli) [inline src/inc/clrnt.h]: The name is confusing to me. And it also seems we don't need the EndAddress for x86, or do we? If not, we can just revert the ifdef around the EndAddress to _TARGET_AMD64_ and remove this define.

File: src/vm/jitinterface.cpp (hunk 2 above)
Comment (janvorli) [inline src/vm/jitinterface.cpp]: @parjong from your other PR, I have just realized you are trying to add unwind info that's a clone of the amd64 unwind info for x86 Linux. @jkotas, your comment was assuming that we are not going to introduce that for x86, right?

Comment (jkotas) [inline src/vm/jitinterface.cpp]: There are two options:

1. Keep the existing unwind info format that is embedded into x86 GCInfo
2. Design and implement a brand new unwind info format for x86 that is similar to unwind info formats on other platforms.

I would try to stay with 1, at least for now. The Linux x86 exception handling changes affect number of sub-systems in major way. If you start redoing yet another non-trivial part of the system as part of it, it will make it even harder to land.

File: src/jit/compiler.h (hunk 4 above)
Comment (jkotas) [inline src/jit/compiler.h]: It depends on the intricate implementation details. The current Win x86 exception handling or CoreRT exception handling on all platforms do not need PSPSym, so it is certainly possible to get away without having it ... I do not know whether it is a good idea for Linux x86.

**Comment by BruceForstall** [comment]
Can you please update `Documentation/botr/clr-abi.md` to describe the model you are implementing for Linux/x86, and alter that document to refer to Linux/x86 specific decisions?

File: src/jit/compiler.h (hunk 4 above)
Comment (parjong) [inline src/jit/compiler.h]: @janvorli According to https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#x86-eh-considerations, all the variables are accessed via frame pointer (EBP) and the managed code always stores frame pointer in its frame. That is one reason that I disable this.

In addition, I encountered various assertions failures that I could't understand when I tried to enable PSPSym-related code.

File: src/inc/clrnt.h (hunk 7 above)
Comment (parjong) [inline src/inc/clrnt.h]: As I understand, we need ``EndAddress``. 

The implementation of ``RtlpGetFunctionEndAddress`` for ARM/ARM64 computes the end address via multiplying the length of function (which seems to be the number of instruction) and the size of each instruction, which means that it this logic is valid only when the architecture has fixed instruction size.

**Comment by parjong** [comment]
@BruceForstall I currently attempt not to change the existing ABI as much as possible, but I'll update CLR ABI when I need to made any changes on ABI.

File: src/jit/compiler.h (hunk 4 above)
Comment (janvorli) [inline src/jit/compiler.h]: The problem is that the CLR ABI doesn't consider the FEATURE_EH_FUNCLETS to be enabled for x86 and the funclets are actually the thing that uses the PSPSym. 
But since this is just a one line change, I won't block you on this. Once we start handling exceptions in complex nested try / catch scenarios, it will quickly show up whether it is better to enable the PSPSym or to fix some place in the stack walker instead.

File: src/inc/clrnt.h (hunk 7 above)
Comment (janvorli) [inline src/inc/clrnt.h]: Ah, that makes sense then. So can you please just modify the COMPACT_RUNTIME_FUNCTION to something like RUNTIME_FUNCTION_HAS_ENDADDRESS or RUNTIME_FUNCTION_NEEDS_ENDADDRESS or something like that?

File: src/vm/jitinterface.cpp (hunk 3 above)
Comment (parjong) [inline src/vm/jitinterface.cpp]: Something like ``reservePresonalityRoutineInfo``?

File: src/jit/compiler.h (hunk 4 above)
Comment (parjong) [inline src/jit/compiler.h]: @janvorli I agree. Later we may need to revise this again, but I currently have no idea.

File: src/jit/compiler.h (hunk 5 above)
Comment (parjong) [inline src/jit/compiler.h]: As x86/Linux uses ``RUNTIME_FUNCTION`` with ``EndAddress``, we need to update its value inside ``CEEJitInfo::allocUnwindInfo``.

For that purpose, we need to store and deliver various ``emitLocation`` variables from JIT to EE.

File: src/inc/clrnt.h (hunk 7 above)
Comment (jkotas) [inline src/inc/clrnt.h]: You do not need the EndAddress on x86. Having it for x86 is just wasting space - encoding the length in xdata is more compact. EndAddress on Win x64 was a mistake. It would not be there if we can go back in time. 

It has nothing to do with instruction with. E.g. ARM32 has variable instruction width as well (the instruction is either 2 or 4 bytes long) and it is able to run without EndAddress just fine.

The multiplier has to do with instruction size granularity. For x86, the granularity is 1 byte so you should make the multiplier 1.

**Comment by BruceForstall** [comment]
> 

You're not generating amd64 unwind codes for x86, so none of the unwind code related data here should be enabled for x86. It would be nonsensical anyway, I think.

---
Refers to: src/jit/compiler.h:1149 in 5ee8feb. [](commit_id = 5ee8feb650051909688d957a3272f632879abc1d, deletion_comment = False)

File: src/jit/unwindxarch.cpp [hunk 8]
```diff
@@ -0,0 +1,609 @@
...
+//    isHotCode   - true if this unwind data is for the hot section, false otherwise.
+//    startOffset - byte offset of the code start that this unwind data represents.
+//    endOffset   - byte offset of the code end   that this unwind data represents.
+//    pHeader     - pointer to the unwind data blob.
+//
+void DumpUnwindInfo(bool                     isHotCode,
+                    UNATIVE_OFFSET           startOffset,
+                    UNATIVE_OFFSET           endOffset,
+                    const UNWIND_INFO* const pHeader)
+{
```
Comment (BruceForstall) [inline src/jit/unwindxarch.cpp]: It seems strange to me to move the x64 unwind code-related functions (including DumpUnwindInfo) to a common place to compile for x86, since (I assume) they won't be used for x86.

File: src/jit/codegenxarch.cpp [hunk 9]
```diff
@@ -263,10 +263,12 @@ BasicBlock* CodeGen::genCallFinally(BasicBlock* block, BasicBlock* lblk)
     }
     else
     {
+#ifndef JIT32_GCENCODER
         // Because of the way the flowgraph is connected, the liveness info for this one instruction
```
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: This will get it to compile, but is there a TODO issue here related to GC handling of this nop on x86?

File: src/jit/codegenlegacy.cpp [hunk 10]
```diff
@@ -13013,7 +13013,7 @@ void CodeGen::genCodeForBBlist()
 
             case BBJ_CALLFINALLY:
 
-#if defined(_TARGET_X86_)
+#if defined(_TARGET_X86_) && !FEATURE_EH_FUNCLETS
```
Comment (BruceForstall) [inline src/jit/codegenlegacy.cpp]: Why do you need to change legacy backend? Isn't Linux/x86 using RyuJIT/x86?

File: src/jit/codegencommon.cpp [hunk 11]
```diff
@@ -10241,6 +10241,62 @@ void CodeGen::genCaptureFuncletPrologEpilogInfo()
 
 // Look in CodeGenArm64.cpp
 
+#elif defined(_TARGET_X86_)
+
+/*****************************************************************************
+ *
+ *  Generates code for an EH funclet prolog.
+ */
+
```
Comment (BruceForstall) [inline src/jit/codegencommon.cpp]: Can you add a TODO here to say what needs to be done for Linux/x86?

File: src/jit/codegenlegacy.cpp (hunk 10 above)
Comment (parjong) [inline src/jit/codegenlegacy.cpp]: This change is introduced to fix build failure. ``lvaShadowSPslotsVar`` is not available when ``FEATURE_EH_FUNCLETS`` is set.

**Comment by BruceForstall** [comment]
@parjong:

> @BruceForstall I currently attempt not to change the existing ABI as much as possible, but I'll update CLR ABI when any changes on ABI are required.

There is no current spec for Linux/x86 (that I am aware of), so any decisions made here constitute an ABI definition. E.g., the clr-abi.md document in the "Funclets" section states, "For non-x86 platforms", and then later, "For x86". These statements are no longer strictly true given that this change creates some amount of funclet functionality for Linux/x86.

File: src/jit/codegenlegacy.cpp (hunk 10 above)
Comment (BruceForstall) [inline src/jit/codegenlegacy.cpp]: Yes, but why is this file getting built with FEATURE_EH_FUNCLETS defined on x86?

Comment (parjong) [inline src/jit/codegenlegacy.cpp]: Do you mean that ``FEATURE_EH_FUNCLETS`` should be enabled only for RyuJIT?

File: src/inc/clrnt.h (hunk 7 above)
Comment (parjong) [inline src/inc/clrnt.h]: @jkotas Could you let me know the overal architecture of ``UNWIND_INFO``". I tried with the following implementation of ``RtlpGetFunctionEndAddress``, but it shows some strange behavior:
```
// This function returns the length of a function using the new unwind info on arm.
// Taken from minkernel\ntos\rtl\arm\ntrtlarm.h.
FORCEINLINE
ULONG
RtlpGetFunctionEndAddress (
    __in PT_RUNTIME_FUNCTION FunctionEntry,
    __in ULONG ImageBase
    )
{
    ULONG FunctionLength;

    FunctionLength = FunctionEntry->UnwindData;
    if ((FunctionLength & 3) != 0) {
        FunctionLength = (FunctionLength >> 2) & 0x7ff;
    } else {
        FunctionLength = *(PTR_ULONG)(ImageBase + FunctionLength) & 0x3ffff;
    }

    return FunctionEntry->BeginAddress + FunctionLength;
}
```
``FunctionLength`` is 0 at the return state. It seems that relevant-information is currently not emiited.

File: src/jit/codegenlegacy.cpp (hunk 10 above)
Comment (BruceForstall) [inline src/jit/codegenlegacy.cpp]: For x86, yes. (FEATURE_EH_FUNCLETS is defined for legacy JIT for ARM32.)

File: src/inc/clrnt.h (hunk 7 above)
Comment (jkotas) [inline src/inc/clrnt.h]: The unwind info format is different for each platform. The Windows ABI documents linked at the start of https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md have the specs of unwind info format for x64 and ARM.

There is no standalone unwind info defined for Windows x86. Windows x86 ABI was defined before the concept of standalone unwind info came to Windows and nobody bothered to define it retroactively.

On Windows x86, the unwind info is encoded as part of GCInfo. The unwinder for it is at https://github.com/dotnet/coreclr/blob/master/src/vm/eetwain.cpp#L3897. For Linux 86, you have basically two options:

1. Keep using the existing scheme where the unwind info is encoded as part of GCInfo, maybe with some minimal modifications. These modifications have to be written down so that everybody is on the same page.
    or 
2. Define your own new x86 unwind info format that is similar to the unwind info formats used on non-x86 platforms. The spec for this format has to be written down so that everybody is on the same page.

I would recommend going with option 1, at least for now.

File: src/jit/codegencommon.cpp (hunk 11 above)
Comment (parjong) [inline src/jit/codegencommon.cpp]: I currently have no idea on which action will be required for prolog/epilog. Could you let me know if you have any idea?

File: src/inc/clrnt.h (hunk 7 above)
Comment (jkotas) [inline src/inc/clrnt.h]: > I tried with the following implementation of RtlpGetFunctionEndAddress

This implementation of RtlpGetFunctionEndAddress specific to the current ARM unwind info format. That's why it does not just work on x86.

File: src/jit/codegenxarch.cpp (hunk 9 above)
Comment (parjong) [inline src/jit/codegenxarch.cpp]: I'm not sure, yet.

File: src/jit/codegencommon.cpp (hunk 11 above)
Comment (BruceForstall) [inline src/jit/codegencommon.cpp]: typically, it would be (1) set up PSPSym (if required), (2) save/restore callee-save registers, (3) handle incoming args/return value. I assume you'll at least need to do (2).

**Comment by parjong** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test please

File: src/pal/inc/pal.h [hunk 12]
```diff
@@ -4679,7 +4679,7 @@ enum {
 //
 typedef struct _RUNTIME_FUNCTION {
     DWORD BeginAddress;
-#ifdef _AMD64_
+#if RUNTIME_FUNCTION_HAS_ENDADDRESS
```
Comment (janvorli) [inline src/pal/inc/pal.h]: Now that we have the EndAddress on amd64 only again, could you please revert the change here and get rid of the RUNTIME_FUNCTION_HAS_ENDADDRESS?

Comment (parjong) [inline src/pal/inc/pal.h]: @janvorli As I understand, the following code in ``CEEJitInfo::allocUnwindInfo`` should be paired with the above ``_RUNTIME_FUNCTION`` definition:
```
#if RUNTIME_FUNCTION_HAS_ENDADDRESS
    pRuntimeFunction->EndAddress        = currentCodeOffset + endOffset;
#endif
```

For me, it was hard to find this relationship when the above definition is written using ``_TARGET_AMD64_``.

Therefore, I would like not to revert this change if there is no further issue. Could you let me know your opinion?

Comment (janvorli) [inline src/pal/inc/pal.h]: Based on what @jkotas said, this is really AMD64 specific and we don't ever want to use it for anything else. That's why I would really prefer keeping it as it was to not to make false expectations that it might be enabled for something else than AMD64.

Comment (parjong) [inline src/pal/inc/pal.h]: @janvorli 89b2a72 reverts the changes related with ``RUNTIME_FUNCTION_HAS_ENDADDRESS``. Please take a look.

File: src/jit/compiler.h [hunk 13]
```diff
@@ -6844,10 +6850,15 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     void unwindReserveFunc(FuncInfoDsc* func);
     void unwindEmitFunc(FuncInfoDsc* func, void* pHotCode, void* pColdCode);
 
-#if defined(_TARGET_AMD64_)
+#ifdef _TARGET_XARCH_
```
Comment (janvorli) [inline src/jit/compiler.h]: I wonder if this should rather be `#if defined(_TARGET_AMD64_) || (defined(_TARGET_X86_) && FEATURE_EH_FUNCLETS)`

Comment (parjong) [inline src/jit/compiler.h]: @janvorli As you pointed out, the implementation of these functions exists only when ``_TARGET_AMD64 || (_TARGET_X86 && FEATURE_EH_FUNCLET)``.  77dc419 revised #ifdef condition.

File: src/jit/codegencommon.cpp (hunk 11 above)
Comment (parjong) [inline src/jit/codegencommon.cpp]: 936ebb7 adds TODO (I'm not sure about (1) and (3), and thus it adds only (2) as TODO).

**Comment by parjong** [comment]
@jkotas @janvorli @BruceForstall I revised PR per feedback. Please take a look.

File: src/jit/compiler.h [hunk 14]
```diff
@@ -1133,6 +1133,7 @@ struct FuncInfoDsc
                                // funclet. It is only valid if funKind field indicates this is a
                                // EH-related funclet: FUNC_HANDLER or FUNC_FILTER
 
+#if FEATURE_EH_FUNCLETS
 #if defined(_TARGET_AMD64_)
```
Comment (BruceForstall) [inline src/jit/compiler.h]: It looks like you've added `#if FEATURE_EH_FUNCLETS`, but x86 won't get any of the enclosed declarations since there is no `_TARGET_X86_` section. So can you remove the (unnecessary) added `#if FEATURE_EH_FUNCLETS`?

File: src/jit/compiler.h (hunk 4 above)
Comment (BruceForstall) [inline src/jit/compiler.h]: The main question is whether the unwinder on Linux/x86 is guaranteed to restore the EBP of the parent frame, such that it doesn't need to be restored by the code itself. That is the main reason for the PSPSym: we can't trust that EBP (or the frame pointer, on other architectures) is restored, especially in nested EH scenarios. CoreRT does this properly, and thus doesn't need the PSPSym.

---
In reply to: [95909398](https://github.com/dotnet/coreclr/pull/8889#discussion_r95909398) [](ancestors = 95909398)

File: src/jit/codegenxarch.cpp (hunk 9 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: Please add a "TODO" comment to remind us to look at this, e.g.:
```
// TODO-Linux-x86: Do we need to handle the GC information for this NOP or JMP specially, as is done for other architectures?
```

---
In reply to: [95926754](https://github.com/dotnet/coreclr/pull/8889#discussion_r95926754) [](ancestors = 95926754)

File: src/jit/codegencommon.cpp [hunk 15]
```diff
@@ -8760,10 +8760,10 @@ void CodeGen::genFnProlog()
     genZeroInitFrame(untrLclHi, untrLclLo, initReg, &initRegZeroed);
 
 #if FEATURE_EH_FUNCLETS
-
+#ifndef _TARGET_X86_
     genSetPSPSym(initReg, &initRegZeroed);
```
Comment (BruceForstall) [inline src/jit/codegencommon.cpp]: This `#ifdef` is unnecessary: genSetPSPSym() will bail out early because `lvaPSPSym == BAD_VAR_NUM` which is true because `ehNeedsPSPSym()` will return false (so `lvaMarkLocalVars()` won't create one).

File: src/jit/compiler.h (hunk 14 above)
Comment (parjong) [inline src/jit/compiler.h]: fe513b3 removes #if statement.

File: src/jit/codegencommon.cpp (hunk 15 above)
Comment (parjong) [inline src/jit/codegencommon.cpp]: Thanks you for comment! fe513b3 also removes this #if statement.

File: src/vm/jitinterface.cpp (hunk 2 above)
Comment (parjong) [inline src/vm/jitinterface.cpp]: @jkotas I am trying to stay 1. Please refers to #8911. It attempts to implement ``RtlVirtualUnwind`` using the existing unwind info as you suggested.

**Comment by BruceForstall** [comment]
LGTM

File: src/jit/compiler.h (hunk 4 above)
Comment (parjong) [inline src/jit/compiler.h]: I currently have no evidence whether Linux/x86 unwider can guarantee the correctness of EBP. We need more investigation. 

In addition, I encountered the following assertion failure while codegen once I tried to push PSPSym,:
```
Assert failure(PID 2080 [0x00000820], Thread: 2080 [0x0820]): Assertion failed 'u2.emitArgTrackTop <= u2.emitArgTrackTab + emitMaxStackDepth' in 'System.AppDomain:SetupDomain(bool,ref,ref,ref,ref):this' (IL size 72)

    File: /home/parjong/projects/dotnet/coreclr/src/jit/emit.cpp Line: 6819
    Image: /root/dotnet-test/overlay/current/corerun
```

It would be better to enable PSPSym-related features in a separate PR.

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by parjong** [comment]
@janvorli PR is updated. Please take a look.

File: src/vm/jitinterface.cpp (hunk 2 above)
Comment (janvorli) [inline src/vm/jitinterface.cpp]: @parjong, since you've said you are trying to stay with keeping the existing unwind info embedded in x86 GC info, I am not sure I understand the addition of the code to Compiler::unwindXXXX methods. Shouldn't they just be empty as before?

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli The first issue while working on #8887 was ``Assert failure(PID 19154 [0x00004ad2], Thread: 19154 [0x4ad2]): iUnwindInfo < GetNumberOfUnwindInfos()``, and the changes in ``Compiler::unwindReserve`` and ``Compiler ::unwindAllocate`` are required to resolve this issue.

You could see that (unlike corresponding implementation for AMD64) the current implementation only stores ``FunctoinLength`` (which is used to implement ``RtlpGetFnctionEndAddress``). It does not store any unwind info, such as which registers are stored, where they are store.

Instead ``RtlVirtualUnwind`` (implemented in #8911) just invokes ``UnwindStackFrame`` which performs unwind based on unwind info embedded in x86 GC info.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: @parjong I am sorry, I have not realized that the eeAllocUnwindInfo allocs just the tiny UnwindInfo with single entry.
Why don't we actually do the same thing as other platforms except for AMD64 and don't store the length in the FunctionLength directly in the RUNTIME_FUNCTION::UnwindData?

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Is it possible? As I understand, it seems that ``CEEJitInfo::allocUnwindInfo`` always stores the offset from image base to unwind info as ``UnwindData``.

Please let me know if there is something wrong. If it is possible, it would be better to use that scheme.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: I have asked because the RtlpGetFunctionEndAddress for ARM and ARM64 looks as follows, so it clearly has encoded function length in there.
```c++
ULONG
RtlpGetFunctionEndAddress (
    __in PT_RUNTIME_FUNCTION FunctionEntry,
    __in ULONG ImageBase
    )
{
    ULONG FunctionLength;
    
    FunctionLength = FunctionEntry->UnwindData;
    if ((FunctionLength & 3) != 0) {
        FunctionLength = (FunctionLength >> 2) & 0x7ff;
    } else {
        FunctionLength = *(PTR_ULONG)(ImageBase + FunctionLength) & 0x3ffff;
    }
    
    return FunctionEntry->BeginAddress + 2 * FunctionLength;
}

```

And the CEEJitInfo::allocUnwindInfo sets it like this:
```C++
size_t unwindInfoDeltaT = (size_t) pUnwindInfo - baseAddress;
...
RUNTIME_FUNCTION__SetUnwindInfoAddress(pRuntimeFunction, unwindInfoDelta);
```

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Thank you for comment. I'll take a look.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: And to make it complete:
```C++
#define RUNTIME_FUNCTION__SetUnwindInfoAddress(prf, addr) do { (prf)->UnwindData = (addr); } while(0)
```

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Both ARM and x86 defines ``RUNTIME_FUNCTION__SetUnwindInfoAddress`` in the same way::
```
#define RUNTIME_FUNCTION__SetUnwindInfoAddress(prf,address) do { (prf)->UnwindData = (address); } while (0)
```
Is there any contract between unwinder and runtime? I couldn't understand why ``RtlpGetFunctionEndAddress`` for ARM works...

Comment (parjong) [inline src/vm/jitinterface.cpp]: It seems that the the code path that executes ``FunctionLength = *(PTR_ULONG)(ImageBase + FunctionLength) & 0x3ffff;`` in ARM implementation seems to corresponds to the current x86 implementation.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: I am not sure if I understand. The UnwindData is set by the runtime (in CEEJitInfo::allocUnwindInfo) and extracted by the runtime (in RtlpGetFunctionEndAddress), so there is no need for contract between those two.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: By between those two I mean JIT and runtime

Comment (parjong) [inline src/vm/jitinterface.cpp]: It seems that the following code in ``allocUnwindInfo`` is related:
```
#elif defined(_TARGET_ARM_)

    *(LONG *)pUnwindInfo |= (1 << 20); // X bit

    ULONG * pPersonalityRoutine = (ULONG*)((BYTE *)pUnwindInfo + ALIGN_UP(unwindSize, sizeof(ULONG)));
    *pPersonalityRoutine = ExecutionManager::GetCLRPersonalityRoutineValue();

#endif
```

Comment (janvorli) [inline src/vm/jitinterface.cpp]: Ah, I've missed that there are two kinds of encoding - one is direct size in the UnwindData  and the other is reading it from memory - the *(PTR_ULONG)(ImageBase + FunctionLength) & 0x3ffff.

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Yes, it seems that the latter encoding corresponds to the current x86 implementation, but I couldn't understand why the former (direct) encoding works..

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli It turns out that the code mentioned above is not related..

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Is there any restriction on THUMB code generation? It seems that the direct encoding is related with THUMB code.

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli I read the implementation of ARM, and find the following code from ``UnwindFragmentInfo::Finalize``:
```
#if defined(_TARGET_ARM_)
    DWORD header = headerFunctionLength | (headerVers << 18) | (headerXBit << 20) | (headerEBit << 21) |
                   (headerFBit << 22) | (headerEpilogCount << 23) | (headerCodeWords << 28);
#elif defined(_TARGET_ARM64_)
    DWORD header               = headerFunctionLength | (headerVers << 18) | (headerXBit << 20) | (headerEBit << 21) |
                   (headerEpilogCount << 22) | (headerCodeWords << 27);
#endif // defined(_TARGET_ARM64_)

    ufiPrologCodes.AddHeaderWord(header);
```
It seems that ARM also stores the length of functions as unwind info as x86 does. IMO, it would be better to introduce a compact encoding as a separate PR if it is necessary.

Comment (janvorli) [inline src/vm/jitinterface.cpp]: @parjong we should not add the compact encoding, since it is not used by managed code on any of the platforms. @jkotas has explained that to me.

Comment (parjong) [inline src/vm/jitinterface.cpp]: @janvorli Oh! Thank for confirm (but still I'm wondering why direct encoding works for ARM/ARM64).

Comment (janvorli) [inline src/vm/jitinterface.cpp]: It is not used for ARM / ARM64 in CoreCLR, the information is never encoded using the compact encoding.

**Comment by janvorli** [comment]
@parjong we still have to make one change here which @jkotas has just mentioned to me. At the moment, the GCInfo is attached only to the main function. So it is possible to get GCInfo for any address in the main function. But if you try to get it for one of the funclets, you won't get anything. 
What we need to do for all funclets is to store a pointer to the GCInfo of the main function right after the unwind info. And since this pointer is optional, we also need to store there a flag indicating whether the function is a funclet or the main function.
We will also need to update the code that gets GCInfo so that in case of the funclet, it would return the main function GC info.

**Comment by parjong** [comment]
@janvorli Could you let me know related method? It would be very helpful if I could know the starting point.

**Comment by parjong** [comment]
@janvorli Could you let me know some details? It seems that JIT encodes GCInfo using ``EEJitManager::allocGCInfo``. 

Is it required to add a filed to x86 UNWIND_INFO structure that points to GCInfo of main function while emitting unwind info?

**Comment by janvorli** [comment]
@parjong I need to figure out the exact details. I will get back to you later today. But as for the pointer to the GC info of the main function, it should not be part of the UNWIND_INFO, since it has nothing to do with unwind. It should rather be just stored in memory after the UNWIND_INFO for funclets. If you put it into the UNWIND_INFO, you would unnecessarily increase memory space used by each function while only funclets need it.

**Comment by janvorli** [comment]
@parjong I have found I got somehow confused. The truth is that we don't need to do anything special for the GC info for the jitted code. We will need to solve the problem for the crossgen-ed binaries where the GC info is stored differently. The EEJitManager is used only for jitted code. For the crossgen-ed code, the NativeImageJitManager (or ReadyToRunJitManager for code crossgen-ed with the readytorun switch) is used instead.
So this change looks good and we will need to solve the other case once we start enabling crossgen for x86 Linux.

**Comment by janvorli** [comment]
@parjong the title of this issue says **(Partially)** enable ... Is there other work that you want to do here now or do you want to merge it?

**Comment by parjong** [comment]
@janvorli I currently have no further work related with this issue. Please merge this PR if it has no problem.
