### PR TITLE
[RyuJIT/ARM32] Fix double type PutArgStk check bug on LSRA init

### LINKED ISSUE #13746: [RyuJIT/arm32][JitStress=2] Assertion failed '(curArgTabEntry->numSlots == 1) || isDouble'
In Windows RyuJIT/arm32 test run with `COMPlus_JitStress=2`:

```
Assert failure(PID 1356 [0x0000054c], Thread: 8376 [0x20b8]): Assertion failed '(curArgTabEntry->numSlots == 1) || isDouble' in 'ArrayLastIndexOf4:PosTest5():bool:this' (IL size 22)

    File: e:\gh\coreclr2\src\jit\lsraarmarch.cpp Line: 493
    Image: c:\brucefo\core_root\Windows_NT.arm.Checked.2017-08-23\CoreRun.exe
```
Test:
```
CoreMangLib\cti\system\array\ArrayLastIndexOf4\ArrayLastIndexOf4.cmd (TEST_IDENTIFIER = Tests.lst=ArrayLastIndexOf4.cmd_8391)
```

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix to handle hardfp/softfp all

Fix https://github.com/dotnet/coreclr/issues/13746#issuecomment-339830426

cc/ @dotnet/arm32-contrib

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

**Comment by hseok-oh** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked Build and Test

File: src/jit/lsraarmarch.cpp [hunk 1]
```diff
@@ -464,9 +464,9 @@ void LinearScan::TreeNodeInfoInitCall(GenTreeCall* call)
             if (!varTypeIsStruct(putArgChild) && !putArgChild->OperIs(GT_FIELD_LIST))
             {
 #ifdef _TARGET_ARM_
-                // The `double` types have been transformed to `long` on arm, while the actual longs
+                // The `double` types could been transformed to `long` on arm, while the actual longs
                 // have been decomposed.
-                const bool isDouble = putArgChild->TypeGet() == TYP_LONG;
+                const bool isDouble = (putArgChild->TypeGet() == TYP_LONG || putArgChild->TypeGet() == TYP_DOUBLE);
```
Comment (BruceForstall) [inline src/jit/lsraarmarch.cpp]: We definitely need to adjust the assert below to handle the TYP_DOUBLE case. However, do we need to set srcCount=2 for TYP_DOUBLE? @CarolEidt ?

Comment (CarolEidt) [reply src/jit/lsraarmarch.cpp]: No, I don't believe we want to set `srcCount=2` for `TYP_DOUBLE`. 
I don't think that `isDouble` provides any value here. I think this would be cleaner:
```
                bool expectedSlots = 1;
#ifdef _TARGET_ARM_
                // The `double` types could have been transformed to `long` on arm, while the actual longs
                // have been decomposed.
                if (putArgChild->TypeGet() == TYP_LONG)
                {
                    argNode->gtLsraInfo.srcCount = 2;
                    expectedSlots = 2;
                }
                else if (putArgChild->TypeGet() == TYP_DOUBLE)
                {
                    expectedSlots = 2;
                }
#endif // !_TARGET_ARM_
                // Validate the slot count for this arg.
                assert(curArgTabEntry->numSlots == expectedSlots);
```

Comment (hseok-oh) [reply src/jit/lsraarmarch.cpp]: I'll fix it.

**Comment by hseok-oh** [comment]
@dotnet-bot test Windows_NT x64_arm64_altjit Checked Build and Test

**Comment by hseok-oh** [comment]
@hqueue I think it's not formatting issue. Maybe CI issue.

**Comment by CarolEidt** [comment]
The Formatting jobs are failing because jitutils isn't building correctly.
@dotnet/jit-contrib is someone taking a look at this?

**Comment by CarolEidt** [comment]
I pulled down this branch, and verified that jit-format found no errors.
