### PR TITLE
Mark a multi-reg return type LclVar of GT_RETURN(LclVar) as DoNotEnregister

### LINKED ISSUE #4412: Assertion failed '!foundDiff' with PInvoke Vector3 return on Linux
JIT hits an '!foundDiff' assertion with the testcase below to return a Vector3 object from the native side. The test passes on Windows.

- The managed testcase is built on Windows and the native code is built on Ubuntu 14.04.
- The testcase passes on Windows.

```
Assert failure(PID 3796 [0x00000ed4], Thread: 3796 [0x0ed4]): Assertion failed '!foundDiff' in 'DomainBoundILStubClass:IL_STUB_PInvoke():struct' (IL size 26)

    File: /home/sejooh/workspaces/ws0/coreclr/src/jit/lsra.cpp Line: 2334
    Image: /home/sejooh/mnt/sejooh-pc-ws/ws0/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun
```

[Vector3Ret.cs]
```
using System;
using System.Diagnostics;
using System.Numerics;
using System.Runtime.InteropServices;

class PInvokeTest 
{
    [DllImport(@"Vector3TestNative", CallingConvention = CallingConvention.StdCall)]
    public static extern Vector3 nativeCall_PInvoke_Vector3Ret();
    
    public static bool test() 
    {
        // Expected return value = 1 + 2 + 3 = 6
        Vector3 ret = nativeCall_PInvoke_Vector3Ret();
        float sum = ret.X + ret.Y + ret.Z;
        if (sum != 6) {
            Console.Write("PInvoke Vector3Ret test failed\n");
            return false;            
        }
  
        Console.Write("All PInvoke testcases passed\n");
        return true;
    }    
}

class Test {  
    public static int Main() {

        if (!PInvokeTest.test()) {
            return 101;
        }
        return 100;
    } 
}
```

[Vector3TestNative.cpp]
```

#include <stdio.h>

#if defined(__clang__)
#define EXPORT(type) __attribute__((visibility("default"))) extern "C" type
#elif defined(_MSC_VER)
#define EXPORT(type) extern "C" __declspec(dllexport) type
#else // defined(__clang__)
#define EXPORT(type) type
#endif // !defined(__clang__)

#if !defined(_MSC_VER)
#if __i386__
#define __stdcall __attribute__((stdcall))
#else // __i386__
#define __stdcall
#endif  // !__i386__
#endif // !defined(_MSC_VER)

typedef struct _Vector3 
{
    float x;
    float y;
    float z;    
} Vector3;

EXPORT(Vector3) __stdcall nativeCall_PInvoke_Vector3Ret() 
{
    Vector3 ret;
    ret.x = 1;
    ret.y = 2;
    ret.z = 3;
    float sum = ret.x + ret.y + ret.z;
    printf("nativeCall_PInvoke_Vector3Ret:\n");
    printf("    Return value: (%f, %f, %f)\n", ret.x, ret.y, ret.z);
    printf("    Sum of return scalar values = %f\n", sum);
    return ret;
}
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fixes #4412

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -1868,6 +1868,14 @@ void LinearScan::identifyCandidates()
...
         }
 
+#if FEATURE_MULTIREG_ARGS_OR_RET        
+        if (varDsc->lvIsMultiRegArgOrRet)
+        {
+            varDsc->lvLRACandidate = 0;
+            continue;
+        }        
+#endif
+
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: I think that a better way to deal with this is to always set `lvDoNotEnregister` when `lvIsMultiRegArgOrRet` is set, but that is a larger change, and since that code will change in the near future, this seemed a better (smaller scoped) fix.

**Comment by BruceForstall** [comment]
LGTM

**Comment by CarolEidt** [comment]
@mmitche - OSX tests have 17 failures; all but one are the same problem that showed up in #4613 (the win api dll not found), and 1 is a result failure - but all seem suspicious. They fail in StopWatch, GetFullPathNameW or GetTickCount.

**Comment by CarolEidt** [comment]
And FWIW - this was a re-run; the previous run showed as failed, but no failing results.

**Comment by mmitche** [comment]
@CarolEidt @AndyAyersMS My suspicion is the corefx build dependency.  The other merge to coreclr about 45 minutes ago looks suspicious, but it was too late to affect this build.  We jump from build 60 -> 62 of corefx between the failing and on-failing runs.  Here are the details of the git changes that went into those.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release/changes?from=60&to=62

**Comment by BruceForstall** [comment]
Do those corefx changes go through the Jenkins CI and normal PR process? Or are they direct submitted? If direct, how do we prevent regressions?

**Comment by mmitche** [comment]
@BruceForstall They go through a normal PR process, however they are not building and testing the runtime with each change.  Up until very recently, they have the same problem with coreclr's bits (and this is still the case for some platforms).  These issues only affect xplat, which has to pull in raw corefx bits because the build process does not pull in the correct packages for xplat.  As we shift away from this model and towards full stack builds/managed dependencies, these issues will disappear.

File: src/jit/lsra.cpp (hunk 1 above)
Comment (briansull) [inline src/jit/lsra.cpp]: I will test this change for AsmDiffs on Arm64

Comment (CarolEidt) [inline src/jit/lsra.cpp]: @briansull Thanks - let me know when your testing is done.

Comment (sivarv) [inline src/jit/lsra.cpp]: As per my understanding this issue is exposed by the below stmnt
Vector3 ret = nativeCall_PInvoke_Vector3Ret();

Where-in while jit compiling IL stub of PInvoke, we are hitting this assert.

Since the native call is returning Vector3, we must be forcing IR to be of the form var=call.  Is the bug is that var is getting marked only as multiRegArgOrRet but not DoNotEnregister on Unix?

Just for my understanding why would that be a bigger change?  We already to do that in importer.  Looks like in some code path we are missing to set DoNotEnregister? is that the core issue?

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -1868,6 +1868,14 @@ void LinearScan::identifyCandidates()
             continue;
         }
 
+#if FEATURE_MULTIREG_ARGS_OR_RET        
+        if (varDsc->lvIsMultiRegArgOrRet)
+        {
+            varDsc->lvLRACandidate = 0;
+            continue;
```
Comment (sivarv) [inline src/jit/lsra.cpp]: Shouldn't this be confined to Unix and only for SIMD locals?

Comment (sivarv) [inline src/jit/lsra.cpp]: As per my understanding, this too is a short-term change and should be removed in near future?  In fact in importer we already set DoNotEnregister in most cases.  Having this change LSRA would mean that now we have this short-term code spread around in more places than we like.

File: src/jit/lsra.cpp (hunk 1 above)
Comment (CarolEidt) [inline src/jit/lsra.cpp]: @sivarv - your understanding is correct, but there are multiple places in importer where 'lvIsMultiRegArgOrRet` is set, and only one of them sets `lvDoNotEnregister' (and it sets it directly, instead of calling `lvaSetVarDoNotEnregister` as I believe it should be doing). Furthermore, it is checked directly in `Lowering::TreeNodeInfoInit()` where it sets a return value to be contained. Also, we don't need/want to limit this to SIMD because 1) any other structs will not currently reach this point, and 2) when/if we decide to fully promote other structs, those would be impacted as well until such time as we fix this - including `treeNodeInfoInit()`.

Comment (sivarv) [inline src/jit/lsra.cpp]: Should we separate this bug fix from P-FULL struct promotion that we intend to implement in future?

The fix for this issue is to set lvDoNotEnregister on lclvar in impFixupStructReturnType() when the return type is MultiReg returned struct on unix.  Further in TreeNodeInfoInit() of GT_RETURN we also need to assert that  the lclvar that is being marked as contained is lvDoNotEnregister=true.

Note that it is the limitation of Unix codegen implementation that it requires lclvar to set to DoNotEnregister.  We definitely want to address this limitation as it would impact CQ for SIMD struct returns on Unix and for that we don't have to wait for P-FULL struct promotion support. When it is addressed, we will stop setting doNotEnregister in importer and also marking as contained in TreeNodeInfoInit() for SIMD locals and codegen would return SIMD local present in a single xmm reg in ABI return registers xmm0 and xmm1.

File: src/jit/lsra.cpp (hunk 2 above)
Comment (CarolEidt) [inline src/jit/lsra.cpp]: In importer we only set `lvDoNotEnregister` in one case (and there are several other return cases that do not). However, I realize now that we don't want to set it for args (only returns), so I think the better near-term fix is to set `lvDoNotEnregister` in `Lowering::treeNodeInfoInit()` so that we don't pessimize the arg case.

File: src/jit/lowerxarch.cpp [hunk 3]
```diff
@@ -307,6 +307,7 @@ void Lowering::TreeNodeInfoInit(GenTree* stmt)
                         GenTreeLclVarCommon* lclVarPtr = tree->gtOp.gtOp1->AsLclVarCommon();
                         LclVarDsc* varDsc = &(compiler->lvaTable[lclVarPtr->gtLclNum]);
                         assert(varDsc->lvIsMultiRegArgOrRet);
+                        varDsc->lvDoNotEnregister = true;
```
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: Should We be using lvaSetVarDoNotEnregister(lclVarPtr->gtLclNum, DNER_IsStruct)?

**Comment by sivarv** [comment]
Looks good.

File: src/jit/lowerxarch.cpp (hunk 3 above)
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: No, I don't think so. I think that we would need to settle on a DNER reason for all such cases, and it should be less fully general than DNER_IsStruct. I think this is a reasonable near-term fix.

**Comment by CarolEidt** [comment]
@dotnet-bot test  Ubuntu x64 Checked Build and Test

**Comment by CarolEidt** [comment]
Failures are pre-existing ones.
