### PR TITLE
Fix issue unveiled on NetBSD: Add PAL__vsnprintf shadow in PAL

### LINKED ISSUE #3199: Stack corruption with snprintf(3) and format %hu
PAL tests fall down with

`src/pal/tests/palsuite/c_runtime/vsprintf/test11/test11.c`

with the following example call:

```
DoNumTest("foo %hu", 0xFFFF, "foo 65535");
```

There is stack corruption here:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/cruntime/printfcpp.cpp#L1822

```
                else if (Type == PFF_TYPE_INT && Prefix == PFF_PREFIX_SHORT)
                {
                    // Convert explicitly from int to short to get
                    // correct sign extension for shorts on all systems.
                    int n;
                    short s;

                    n = va_arg(ap, int);
                    s = (short) n;

                    TempInt = snprintf(BufferPtr, TempCount, TempBuff, s); // <--- here
                }
```

```
(gdb) list
1814                        // Convert explicitly from int to short to get
1815                        // correct sign extension for shorts on all systems.
1816                        int n;
1817                        short s;
1818    
1819                        n = va_arg(ap, int);
1820                        s = (short) n;
1821    
1822                        TempInt = snprintf(BufferPtr, TempCount, TempBuff, s);
1823                    }
(gdb) n
1820                        s = (short) n;
(gdb) p n
$8 = 65535
(gdb) n
1822                        TempInt = snprintf(BufferPtr, TempCount, TempBuff, s);
(gdb) p s
$9 = -1
(gdb) p BufferPtr
$10 = (LPSTR) 0x7f7fffffd924 ""
(gdb) p BufferPtr-1
$11 = (CHAR *) 0x7f7fffffd923 " "
(gdb) p BufferPtr-2
$12 = (CHAR *) 0x7f7fffffd922 "o "
(gdb) p BufferPtr-3
$13 = (CHAR *) 0x7f7fffffd921 "oo "
(gdb) p BufferPtr-4
$14 = (CHAR *) 0x7f7fffffd920 "foo "
(gdb) p TempBuff
$15 = "%hu\000\177\177\000\000\006\362E\000\000\000\000\000\000\222\377\367\177\177\000\000\000P�\367\177\177\000\000�\322\377\377\177\177\000\000\006\362E\000\000\000\000\000�\322\377\377\177\177\000\000\000P�\367\177\177\000\000\020\323\377\377\177\177\000\000\006\362E\000\000\000\000\000��D\000\000\000\000\000\377\232N\000\000\000\000\000\000X\377\367\016\000\000\000\000P�\367\177\177\000\000@\323\377\377\177\177\000\000\006\362E\000\000\000\000\000\004\323\377\377\177\177\000\000L2�\367\177\177\000\000\000X\377\367\177\177\000\000��N\000\000\000\000\000\000X\377\367\177\177\000\000L2�\367\177\177\000\000\020\323\377\377\001\000\000\000�a�\367\177\177\000\000 \323\377\377\177\177\000\000"...
(gdb) n

Breakpoint 2, CoreVsnprintf (pthrCurrent=0x7f7ff7b05000, Buffer=0x7f7fffffd924 "", Count=2147483643, Format=0x7f7fffffd240 "%hu", aparg=0x7f7fffffcdb8)
    at /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/src/cruntime/printfcpp.cpp:1819
1819                        n = va_arg(ap, int);
(gdb) 
```

I'm trying to determine what's going on.

### PR DESCRIPTION
**Pull request by krytarowski**
NetBSD's libc internally uses a function named `_vsnprintf`. We need to mask
PAL's version of this function to remove clash with the system. With it
`snprintf`(3) calls were jumping out of libc and landing back to PAL.

It was unveiled with many PAL tests.

Detailed documentation about `_symbols` in the NetBSD libc is documented
in the NetBSD sources in a file: `src/lib/libc/README`

Thanks Jan Vorli (Microsoft) for help with debugging.

Fix #3199

### CODE REVIEW

**Comment by krytarowski** [comment]
@janvorli @jkotas PTAL

**Comment by jkotas** [comment]
Maybe also delete _vsnprintf implementation in printf.cpp because of it is unused now? (And it can only cause problems by colliding with the system-provided one.)

**Comment by krytarowski** [comment]
Done!

**Comment by janvorli** [comment]
By removing the _vsnprintf and exposing the PAL__vsnprintf externally, we have lost the logging (PERFENTRY, ENTRY, ...). It seems it would make sense to put it into the PAL__vsnprintf. It would then probably also make sense to replace all usages of PAL__vsnprintf in PAL (there are 6 of them) by the CoreVsnprintf.
@jkotas what do you think?

**Comment by jkotas** [comment]
Make sense. Also, there is build break on OSX

**Comment by krytarowski** [comment]
@janvorli 
> By removing the _vsnprintf and exposing the PAL__vsnprintf externally, we have lost the logging (PERFENTRY, ENTRY, ...). It seems it would make sense to put it into the PAL__vsnprintf. It would then probably also make sense to replace all usages of PAL__vsnprintf in PAL (there are 6 of them) by the CoreVsnprintf.

To be sure. Please make more clear this part: "It seems it would make sense to put it into the PAL__vsnprintf."

Thank you!

**Comment by janvorli** [comment]
Look at the deleted _vsnprintf:
```C++
int 		
 __cdecl 		
 _vsnprintf(char *buffer, 		
            size_t count, 		
            const char *format, 		
            va_list argptr)		
 {		
     LONG Length;		
 		
     PERF_ENTRY(_vsnprintf);		
     ENTRY("_vsnprintf (buffer=%p, count=%d, format=%p (%s), argptr=%p)\n", 		
           buffer, count, format, format, argptr);		
 		
     Length = PAL__vsnprintf(buffer, count, format, argptr);		
 		
     LOGEXIT("_vsnprintf returns int %d\n", Length);		
     PERF_EXIT(_vsnprintf);		
 		
     return Length;		
 }
```
What I meant is to add the PERF_ENTRY, ENTRY, LOGEXIT and PERF_EXIT to the PAL__vsnprintf. Just copy them from here and modify the name from _vsnprintf to PAL__vsnprintf.

**Comment by krytarowski** [comment]
`CoreVsnprintf` accepts additional parameter of `CPalThread *pthrCurrent`. Is it a problem to replace `PAL__vsnprintf()` with `CoreVsnprintf()`?

**Comment by krytarowski** [comment]
I can use `InternalGetCurrentThread()`, is it safe?

**Comment by krytarowski** [comment]
```
int
PALAPIV
wsprintfA(
      OUT LPSTR buffer,
      IN LPCSTR format,
      ...)
{
    LONG Length;
    va_list ap;

    PERF_ENTRY(wsprintfA);
    ENTRY("wsprintfA (buffer=%p, format=%p (%s))\n", buffer, format, format);

    va_start(ap, format);
    Length = CoreVsnprintf(InternalGetCurrentThread(), buffer, 1024, format, ap);
    va_end(ap);
```

For example, is LONG needed here while `CoreVsnprintf()` returns `int`?

**Comment by janvorli** [comment]
Yes, it is safe, since when it was calling PAL__vsnprintf, it was doing the same thing in the PAL__vsnprintf.

**Comment by janvorli** [comment]
LONG is defined as int, since LONG on windows is 32 bit.

**Comment by krytarowski** [comment]
OK, I will leave the `LONG` usage. I'm testing my patch and will upload soon.

**Comment by krytarowski** [comment]
Done! It might be cleaned up.. but it should be good enough.

**Comment by krytarowski** [comment]
It failed with tests... before I will be back to .Net, what's the suggested solution? It looks like tests are trying to call `_vsnprintf()`.

**Comment by janvorli** [comment]
I would try to generate pre-processed version of one of the failing tests to see what's going on. It should be ok for the tests to call _vsnprintf, as it should be defined as PAL__vsnprintf by the pal header, right?

File: src/pal/src/cruntime/printf.cpp [hunk 1]
```diff
@@ -45,6 +45,9 @@ static int SscanfFloatCheckExponent(LPCSTR buff, LPCSTR floatFmt,
                                       void * voidPtr, int * pn);
 #endif // SSCANF_CANNOT_HANDLE_MISSING_EXPONENT
 
+using namespace CorUnix;
+int CoreVsnprintf(CPalThread *pthrCurrent, LPSTR Buffer, size_t Count, LPCSTR Format, va_list ap);
```
Comment (janvorli) [inline src/pal/src/cruntime/printf.cpp]: Actually I can see now that we have InternalVsnprintf exposed in the printfcpp.hpp and it is just a wrapper for the CoreVsnprintf to make it public, so it would be cleaner to use that instead of adding the function prototype.

**Comment by krytarowski** [comment]
It looks like pal.h change has been lost. I will restore it and see what happens.

File: src/pal/src/cruntime/printf.cpp (hunk 1 above)
Comment (krytarowski) [inline src/pal/src/cruntime/printf.cpp]: I will do it.

**Comment by krytarowski** [comment]
Should be fine now. Let see what buildslaves will report.

**Comment by jasonwilliams200OK** [comment]
OS X build failed: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/checked_osx_prtest/663/console

```
Undefined symbols for architecture x86_64:
  "__vsnprintf", referenced from:
      sos::ObjectIterator::BuildError(char*, unsigned long, char const*, ...) const in gcroot.cpp.o
      void sos::Throw<sos::HeapCorruption>(char const*, ...) in gcroot.cpp.o
      void sos::Throw<sos::Exception>(char const*, ...) in gcroot.cpp.o
      TableOutput::WriteColumnFormat(int, char const*, ...) in strike.cpp.o
      void sos::Throw<sos::Exception>(char const*, ...) in strike.cpp.o
      void sos::Throw<sos::Exception>(char const*, ...) in sos.cpp.o
      void sos::Throw<sos::DataRead>(char const*, ...) in sos.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ToolBox/SOS/Strike/libsos.dylib] Error 1
make[1]: *** [src/ToolBox/SOS/Strike/CMakeFiles/sos.dir/all] Error 2
make: *** [all] Error 2
Failed to build coreclr components.
```

**Comment by krytarowski** [comment]
@kangaroo would you like to help with MacOSX investigation? Thanks

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by krytarowski** [comment]
Thank you, I got exhausted during investigation of this issue and I needed to take rest from it for few days.

**Comment by krytarowski** [comment]
I don't know MacOSX.. I will leave this for the last pull-request for myself. Unless someone will spot the error.

Thanks!

**Comment by krytarowski** [comment]
@dotnet-bot test this please

**Comment by krytarowski** [comment]
@jkotas @janvorli PTAL

MacOSX should be now fixed.

**Comment by krytarowski** [comment]
ping - this is pretty large commit to maintain locally

**Comment by jkotas** [comment]
LGTM

**Comment by krytarowski** [comment]
Thank you!
