### PR TITLE
Fix checking for reg in use

### LINKED ISSUE #14373: [RyuJIT/arm32][JitStress=2][JitStressRegs=3] Assertion failed 'nextAssignedRef->nodeLocation == refLocation || (nextAssignedRef->nodeLocation + 1 == refLocation && nextAssignedRef->delayRegFree)'
Found in x86_arm_altjit run.

```
Assert failure(PID 6456 [0x00001938], Thread: 5536 [0x15a0]): Assertion failed 'nextAssignedRef->nodeLocation == refLocation || (nextAssignedRef->nodeLocation + 1 == refLocation && nextAssignedRef->delayRegFree)' in 'testout1:Func_0_5_5_3():struct' (IL size 652)

    File: d:\j\workspace\x86_arm_altji---2c922e9d\src\jit\lsra.cpp Line: 5961
    Image: D:\j\workspace\x86_arm_altji---2c922e9d\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Tests/configurations:
```
COMPlus_JitStress=2
COMPlus_JitStressRegs=3

JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Combine the check for an inactive but not-yet-freed interval, with the check for other cases of a register that is in use at the current location. This simplifies the code and fixes the assert condition for double registers.

Fix #14373

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8

**Comment by CarolEidt** [comment]
JitStressRegs=0x80 failures:
- 20 instances of #13746 
- 1 failure in JIT\HardwareIntrinsics\Crc32_r\Crc32_r.exe - filed new issue #14771 (this is actually an x86 failure)

JitStressRegs=1: same as above, but additional instance of #14771 in Crc32_ro.exe
JitStressRegs=2: 20 instances of #13476 
JitStressRegs=3: same, plus:
- new instances of #14372 in:
  - JIT\Methodical\divrem\rem\r4rem_cs_do\r4rem_cs_do.cmd
  - JIT\Methodical\divrem\rem\r4rem_cs_ro\r4rem_cs_ro.cmd
- And a possibly new, but unreproducible by me, test failure (presumably x86) in:
  - baseservices\threading\generics\Monitor\TryEnter05\TryEnter05.cmd

JitStressRegs=4: Same as JitStressRegs=0x80

JitStressRegs=8: 17 instances of #13746, plus:
- Possibly new test failure in:
  - baseservices\threading\generics\Monitor\EnterExit12\EnterExit12.cmd

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by sandreenko** [comment]
> JitStressRegs=2: 20 instances of #13476

Typo: #13746.

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -5922,108 +5915,16 @@ bool LinearScan::canSpillDoubleReg(RegRecord*   physRegRecord,
...
-            }
-        }
-        return false;
-    }
-}
-
-//----------------------------------------------------------------------------------------
-// isIntervalActive: Determine if an Interval is active
+//------------------------------------------------------------------------
+// unassignDoubleReg:
```
Comment (BruceForstall) [inline src/jit/lsra.cpp]: nit: unassignDoublePhysReg

**Comment by CarolEidt** [comment]
> Typo: #13746.

Fixed; thanks.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -6093,14 +6011,37 @@ bool LinearScan::isRegInUse(RegRecord* regRec, RefPosition* refPosition)
...
+                           isRefPositionActive(otherHalfRegRec->assignedInterval->recentRefPosition,
+                                               refPosition->nodeLocation));
+                }
+            }
+            else
+#else
+            {
+                assert(isRefPositionActive(assignedInterval->recentRefPosition, refPosition->nodeLocation));
+            }
+#endif
```
Comment (BruceForstall) [inline src/jit/lsra.cpp]: This `#ifdef` logic is very confusing. Can you instead use:

```
            // This can only happen if we have a recentRefPosition active at this location that hasn't yet been freed
            // (Or, in the case of ARM, the other half of a double is either active or has an active recentRefPosition).
            CLANG_FORMAT_COMMENT_ANCHOR;

#ifdef _TARGET_ARM_
            if (refPosition->getInterval()->registerType != TYP_DOUBLE)
            {
                return true;
            }

            if (!isRefPositionActive(assignedInterval->recentRefPosition, refPosition->nodeLocation))
            {
                RegRecord* otherHalfRegRec = findAnotherHalfRegRec(regRec);
                assert(otherHalfRegRec->assignedInterval->isActive ||
                       isRefPositionActive(otherHalfRegRec->assignedInterval->recentRefPosition,
                                           refPosition->nodeLocation));
            }
#else // !_TARGET_ARM_
            assert(isRefPositionActive(assignedInterval->recentRefPosition, refPosition->nodeLocation));
            return true;
#endif // !_TARGET_ARM_
```

Comment (CarolEidt) [reply src/jit/lsra.cpp]: Actually, my version (and your replacement) is incorrectly skipping the assert in the non-double ARM case.

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Innerloop Formatting
