### PR TITLE
Fix Segfault in PerfInfo Image Logging

### LINKED ISSUE #26883: [Linux] Segfault when AssemblyBuilder.DefineDynamicAssembly and PerfMap
Hi!
When I build app with final **.NET Core v3.0.0** and run it with
`COMPlus_PerfMapEnabled=1`

```
static void Main(string[] args)
{
     AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Sth.dll"), AssemblyBuilderAccess.RunAndCollect);
}
```

I get instantly **Segmentation faul**t.

It seems it is working fine on Preview9 (I was not testing any other versions).

It migh be related to [Link](https://github.com/dotnet/coreclr/issues/26830) 

Fun fact,
with `COMPlus_PerfMapEnabled=1`  
I get segfault for 

`dotnet new console`
`dotnet tool install -g dotnet-sos`   
That makes it real fun to diagnose.

Maybe this stack trace helps
```
frame #0: 0x00007f5a43d32caa libcoreclr.so`PerfInfo::LogImage(PEFile, char16_t) + 90
frame #1: 0x00007f5a43d31e57 libcoreclr.so`PerfMap::LogImage(PEFile*) + 279
frame #2: 0x00007f5a43e6c56a libcoreclr.so`Assembly::CreateDynamic(AppDomain, CreateDynamicAssemblyArgs) + 2538
frame #3: 0x00007f5a43ec052a libcoreclr.so`AppDomainNative::CreateDynamicAssembly(AssemblyNameBaseObject, StackCrawlMark, int) + 234
```
Of course I can disable it, but this prevents me from profiling apps :-(

### PR DESCRIPTION
**Pull request by brianrob**
Harden perfinfo.map image logging by skipping dynamically generated assemblies and being more robust around base address logging.

Fixes #26883

### CODE REVIEW

File: src/vm/perfinfo.cpp [hunk 1]
```diff
@@ -41,8 +41,21 @@ void PerfInfo::LogImage(PEFile* pFile, WCHAR* guid)
 
     SString value;
     const SString& path = pFile->GetPath();
-    PEImageLayout *pLoadedLayout = pFile->GetLoaded();
-    SIZE_T baseAddr = (SIZE_T)pLoadedLayout->GetBase();
+    if (path.IsEmpty())
```
Comment (jkotas) [inline src/vm/perfinfo.cpp]: Why do we filter empty paths?

File: src/vm/perfinfo.cpp [hunk 2]
```diff
@@ -41,8 +41,21 @@ void PerfInfo::LogImage(PEFile* pFile, WCHAR* guid)
...
+    {
+        return;
+    }
+
+    SIZE_T baseAddr = 0;
+    if (pFile->HasOpenedILimage())
```
Comment (jkotas) [inline src/vm/perfinfo.cpp]: Should this rather use `IsILImageReadyToRun()` ? I assume we do not care about IL images here since they cannot contain any code.

Also, if the IL image does not contain any code, should we skip the logging altogether?

File: src/vm/perfinfo.cpp (hunk 1 above)
Comment (brianrob) [reply src/vm/perfinfo.cpp]: If the path is empty, then we have no way of using this information to resolve symbols.  Instead, the symbols will be resolved when the method is jitted via perf-<pid>.map.

File: src/vm/perfinfo.cpp (hunk 2 above)
Comment (brianrob) [reply src/vm/perfinfo.cpp]: I think both of these are good things to do.  I'll update the code to use `IsILImageReadyToRun()`.  Is there a cheap way to check if the image contains code?  I didn't see anything obvious on `PEImage`.

**Comment by danmosemsft** [comment]
@brianrob if you think this should go into 3.0.1 please add a template similar to https://github.com/dotnet/corefx/pull/40820 and set "ask mode" and "shiproom-consider" labels.

File: src/vm/perfinfo.cpp (hunk 2 above)
Comment (jkotas) [reply src/vm/perfinfo.cpp]: If `IsILImageReadyToRun` returns true, it means the image contains code.

Comment (brianrob) [reply src/vm/perfinfo.cpp]: Great.  I've pushed a fix for this.

**Comment by danmosemsft** [comment]
@brianrob @jeffschwMSFT I assume you guys decided against putting this into 3.0 or 3.1 and this wasn't closed by mistake?

**Comment by jeffschwMSFT** [comment]
Tracking here https://github.com/dotnet/coreclr/pull/26910
