### PR TITLE
Fix validation of spectralnorm under xunit-performance

### LINKED ISSUE #4270: tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm perf test failing
The tests under tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm seem to be failing with the following stack trace 
Test Failed 
 Unhandled exception of type 'System.Exception': System.Exception : Benchmark failed to validate 
 at SpectralNorm.Bench() in C:\github\coreclr\tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm\spectralnorm.cs:line 58 

@AndyAyersMS  Could you please take a look and fix the issue

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The valiation code wasn't correctly for the iteration strategy
used by xunit-performance.

Closes #4270.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dsgouda PTAL

File: tests/src/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm.cs [hunk 1]
```diff
@@ -49,13 +50,14 @@ public static void Bench()
...
-        {
-            throw new Exception("Benchmark failed to validate");
+
+            double norm = a / Iterations;
+            double expected = 1.274219991;
+            bool valid = Math.Abs(norm - expected) < 1e-4;
+            if (!valid)
+            {
+                throw new Exception("Benchmark failed to validate");
+            }
```
Comment (dsgouda) [inline tests/src/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm.cs]: Are you able to test and verify that this does not fail as a perf test?
Nit: Indentation looks a little off.

Comment (AndyAyersMS) [inline tests/src/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm.cs]: I don't see any indentation issues (try looking at the full diff, since I moved some code from outside a block to inside). If you still see one let me know which line....

I was able to repro the failure locally, and have verified it is indeed fixed.

**Comment by dsgouda** [comment]
LGTM :+1: 
Disregard the nit
