### PR TITLE
Don't free the loader handle if the LoaderAllocator is already dead.

### LINKED ISSUE #25194: Assert failed: !CREATE_CHECK_STRING(!\"Detected use of a corrupted OBJECTREF. Possible GC hole.\")
**Job:**
https://mc.dot.net/#/user/coreclr-outerloop-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190615.1/workItem/Interop/analysis/xunit/Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_~2F_ConflictingNames_MultipleALCs_MultipleALCs_cmd

**Failed tests:**
Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd

**Log:**
```
Assert failure(PID 4632 [0x00001218], Thread: 5856 [0x16e0]): !CREATE_CHECK_STRING(!\"Detected use of a corrupted OBJECTREF. Possible GC hole.\")

CORECLR! GetCLRRuntimeHost + 0x20D3C4 (0x728b6354)
CORECLR! GetCLRRuntimeHost + 0x20CD51 (0x728b5ce1)
CORECLR! GetCLRRuntimeHost + 0x208683 (0x728b1613)
CORECLR! GetCLRRuntimeHost + 0x1FF0C (0x726c8e9c)
CORECLR! GetCLRRuntimeHost + 0x237BD1 (0x728e0b61)
CORECLR! GetCLRRuntimeHost + 0x232779 (0x728db709)
CORECLR! GetCLRRuntimeHost + 0x3701EE (0x72a1917e)
CORECLR! GetCLRRuntimeHost + 0x376986 (0x72a1f916)
CORECLR! GetCLRRuntimeHost + 0x22F240 (0x728d81d0)
CORECLR! GetCLRRuntimeHost + 0x231DBF (0x728dad4f)
    File: f:\\workspace\\_work\\1\\s\\src\\vm\\object.cpp Line: 674
    Image: C:\\dotnetbuild\\work\\738ee127-6b75-4be2-b2f2-ec94e88da013\\Payload\\CoreRun.exe

Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\738ee127-6b75-4be2-b2f2-ec94e88da013\\Work\\f1c1b826-3df4-4eb2-820f-a0e9ec0da206\\Exec\\Interop\\ICustomMarshaler\\Reports\\Interop.ICustomMarshaler\\ConflictingNames\\MultipleALCs\\MultipleALCs.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\738ee127-6b75-4be2-b2f2-ec94e88da013\\Payload\\corerun.exe\" MultipleALCs.exe 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\738ee127-6b75-4be2-b2f2-ec94e88da013\\Payload
> C:\\dotnetbuild\\work\\738ee127-6b75-4be2-b2f2-ec94e88da013\\Work\\f1c1b826-3df4-4eb2-820f-a0e9ec0da206\\Exec\\Interop\\ICustomMarshaler\\ConflictingNames\\MultipleALCs\\MultipleALCs.cmd
Expected: True
Actual:   False
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #25194

### CODE REVIEW

File: src/vm/custommarshalerinfo.cpp [hunk 1]
```diff
@@ -134,11 +134,14 @@ CustomMarshalerInfo::~CustomMarshalerInfo()
 {
     WRAPPER_NO_CONTRACT;
 #ifndef CROSSGEN_COMPILE    
-    if (m_hndCustomMarshaler)
+    if (m_pLoaderAllocator->IsAlive() && m_hndCustomMarshaler)
```
Comment (jkotas) [inline src/vm/custommarshalerinfo.cpp]: Is this ever needed - can we depend on the loader allocator always taking care of freeing the handle?

Comment (jkoritzinsky) [reply src/vm/custommarshalerinfo.cpp]: There’s a race when creating the CustomMarshalerInfo on different threads, and we destroy the extra CMInfo if another thread creates it before we do. That’s the only path that needs this destruction logic.
