### PR TITLE
Fix visibility and signed comparison issues for GCC

### LINKED ISSUE #22571: New GNU Compiler Warning: error: 'visibility' attribute ignored on non-class types
[ 42%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o
In file included from coreclr/src/pal/src/include/pal/palinternal.h:333:0,
                 from coreclr/src/pal/src/cruntime/file.cpp:22:
coreclr/src/pal/inc/pal.h:2415:22: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetStackBase(VOID);
                      ^
coreclr/src/pal/inc/pal.h:2420:23: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetStackLimit(VOID);
                       ^
coreclr/src/pal/inc/pal.h:2666:32: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_LOADLoadPEFile(HANDLE hFile);
                                ^
In file included from coreclr/src/pal/src/include/pal/palinternal.h:333:0,
                 from coreclr/src/pal/src/cruntime/file.cpp:22:
coreclr/src/pal/inc/pal.h:5159:34: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetNativeExceptionHolderHead();
                                  ^
cc1plus.exe: all warnings being treated as errors
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o] Error 1
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by am11**
GCC indicated that some visibility attributes were not required, while others, in case of non-class required a bit different order, for which this patch uses `PALAPI_NOEXPORT` with `DLLEXPORT` at appropriate place.

Also fixes some singed to unsigned comparison errors.

Finally, removed the trailing blanks (tabs/spaces) from lines in files this delta is touching:

```sh
git show --name-only --pretty="" HEAD...dotnet/master |\
    xargs -I{} sh -c "test -f {} && sed -i '' 's/[[:space:]]*$//' {}"
```

With this patch and @franksinankaya's https://gist.githubusercontent.com/franksinankaya/1b4e5e9d1cf9cfc28af27bc2fe03f0e5/raw/4c36d5129f4282875d52fae0ac6e189bb500cc4e (which disables couple of directories), GCC build finishes successfully.

Fixes #22571

### CODE REVIEW

**Comment by am11** [comment]
@jkotas, some editors highlight trailing whitespaces as invalid characters. To improve code readability, would it be possible to do a batch cleanup from admin's or @dotnet-bot's account?

It could be:

```sh
git ls-files | xargs sed -i 's/[[:space:]]*$//'

# or selected files, *.h, *.hpp, *.c, *.cpp, *.cs
git ls-files *.c{,pp,s}, *.h{pp,} | xargs sed -i 's/[[:space:]]*$//'
```

followed by `git commit -m "Code formatting"; git push`.

File: src/debug/daccess/daccess.cpp [hunk 1]
```diff
@@ -7509,6 +7509,7 @@ STDAPI CLRDataAccessCreateInstance(ICLRDataTarget * pLegacyTarget,
 #ifdef __GNUC__
 __attribute__((used))
```
Comment (jkotas) [inline src/debug/daccess/daccess.cpp]: Do we need this attribute when this is marked with `DLLEXPORT`?

File: src/pal/inc/pal.h [hunk 2]
```diff
@@ -2411,13 +2411,13 @@ TlsFree(
 
 PALIMPORT
 void *
-PALAPI
-PAL_GetStackBase(VOID);
+PALAPI_NOEXPORT
+PAL_GetStackBase(VOID) DLLEXPORT;
```
Comment (jkotas) [inline src/pal/inc/pal.h]: What makes these special that they need `DLLEXPORT` at the end?

**Comment by jkotas** [comment]
> Code formatting

It touches many files. I will think about it. Is there a particular part of the tree where you think it would help the most?

File: src/pal/inc/pal.h (hunk 2 above)
Comment (am11) [reply src/pal/inc/pal.h]: GCC was complaining `error: 'visibility' attribute ignored on non-class types`. In this order, attribute was being applied to the return type, instead of the function itself. The other way to fix this is to apply `PALAPI` before the return type.

In hindsight, just figured that except for `PAL_GetNativeExceptionHolderHead`, the rest of 15 cases spotted by GCC are those where we do not need `PALAPI`, therefore I have removed it in 730fc23, and changed the order of `PALAPI` (before the return type).

complete diff without whitespace changes: https://github.com/dotnet/coreclr/pull/22586/files?w=1

File: src/debug/daccess/daccess.cpp (hunk 1 above)
Comment (am11) [reply src/debug/daccess/daccess.cpp]: Nope, at least not by clang (i think true all supported CI matrix) and gcc (on ubuntu) - #removed

**Comment by am11** [comment]
Perhaps `:/src/pal` and `:/tests` directories would be a reasonable start.

Alternatively, the whole tree could be visited at once or one major directory at a time (pal, vm, ..).
To persist this state, maybe `Ubuntu x64 Formatting` job could be configured to fail with actionable message, when PR has whitespace changes, something like:

```sh
#!/usr/bin/env sh
# somewhere in `Ubuntu x64 Formatting` build definition
git show dotnet/master..HEAD --name-only --pretty="" | xargs sed -i 's/[[:space:]]*$//'
if ! git diff-index --quiet HEAD --; then
  failureReason="Trailing whitespaces found. Consider running the following command at repo's root:"
  failureReason="$failureReason git show dotnet/master..HEAD --name-only --pretty="" | xargs sed -i 's/[[:space:]]*$//'"

  FailBuildWithMessage $failureReason
fi
```

File: src/pal/inc/pal.h [hunk 3]
```diff
@@ -2411,12 +2411,10 @@ TlsFree(
 
 PALIMPORT
 void *
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Should these be rather changed to return `PVOID` for consistency with all other PAL APIs and stay ``PALIMPORT` + `PALAPI` ?

File: src/pal/src/numa/numa.cpp [hunk 4]
```diff
@@ -741,7 +741,7 @@ GetCurrentProcessorNumberEx(
     ENTRY("GetCurrentProcessorNumberEx(ProcNumber=%p\n", ProcNumber);
 
     DWORD cpu = GetCurrentProcessorNumber();
-    _ASSERTE(cpu < g_possibleCpuCount);
+    _ASSERTE(cpu < (size_t)g_possibleCpuCount);
```
Comment (jkotas) [inline src/pal/src/numa/numa.cpp]: These numbers are not sizes of memory blocks. They are regular integers. Casting the other side to `int` would be more appropriate.

Comment (jkotas) [reply src/pal/src/numa/numa.cpp]: (multiple places)

File: src/pal/inc/pal.h (hunk 3 above)
Comment (am11) [reply src/pal/inc/pal.h]: Fixed and changed all the (non-`const`) `void *`s in `pal.h` with `PVOID`.

File: src/pal/inc/pal.h [hunk 5]
```diff
@@ -4315,21 +4316,21 @@ See MSDN doc for memcpy
...
-PALIMPORT void * __cdecl memcpy(void *, const void *, size_t) THROW_DECL;
+PALIMPORT PVOID __cdecl memcpy(PVOID, const void *, size_t) THROW_DECL;
 
 #define memcpy PAL_memcpy
 #define IS_PAL_memcpy 1
 #define TEST_PAL_DEFERRED(def) IS_##def
 #define IS_REDEFINED_IN_PAL(def) TEST_PAL_DEFERRED(def)
 #else //defined(_DEBUG)
-PALIMPORT void * __cdecl memcpy(void *, const void *, size_t);
+PALIMPORT PVOID __cdecl memcpy(PVOID, const void *, size_t);
```
Comment (jkotas) [inline src/pal/inc/pal.h]: `PVOID` does not look good in the signatures of C runtime functions.

File: src/pal/inc/pal.h [hunk 6]
```diff
@@ -2410,12 +2410,12 @@ TlsFree(
     IN DWORD dwTlsIndex);
 
 PALIMPORT
-void *
+PVOID
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Could you please change these to PVOID in the implementation as well?

File: src/pal/inc/pal.h (hunk 5 above)
Comment (jkotas) [reply src/pal/inc/pal.h]: Could you please revert the change for C runtime functions?

File: src/pal/inc/pal.h [hunk 7]
```diff
@@ -2829,7 +2830,7 @@ VOID
 PALAPI
 RtlMoveMemory(
           IN PVOID Destination,
-          IN CONST VOID *Source,
+          IN const void * Source,
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Undo

File: src/pal/inc/pal.h [hunk 8]
```diff
@@ -4315,7 +4316,7 @@ See MSDN doc for memcpy
 EXTERN_C
 PALIMPORT
 DLLEXPORT
-void *PAL_memcpy (void *dest, const void *src, size_t count);
+PVOID PAL_memcpy (PVOID dest, const void * src, size_t count);
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Undo

File: src/pal/inc/pal.h [hunk 9]
```diff
@@ -4605,7 +4606,7 @@ PALIMPORT char * __cdecl _fullpath(char *, const char *, size_t);
 
 #ifndef PAL_STDCPP_COMPAT
 
-PALIMPORT DLLEXPORT void __cdecl qsort(void *, size_t, size_t, int(__cdecl *)(const void *, const void *));
+PALIMPORT DLLEXPORT void __cdecl qsort(PVOID, size_t, size_t, int(__cdecl *)(const void *, const void *));
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Undo

File: src/pal/inc/pal.h [hunk 10]
```diff
@@ -4665,7 +4666,7 @@ PALIMPORT int __cdecl PAL_fclose(PAL_FILE *);
 PALIMPORT void __cdecl PAL_setbuf(PAL_FILE *, char*);
 PALIMPORT DLLEXPORT int __cdecl PAL_fflush(PAL_FILE *);
 PALIMPORT size_t __cdecl PAL_fwrite(const void *, size_t, size_t, PAL_FILE *);
-PALIMPORT size_t __cdecl PAL_fread(void *, size_t, size_t, PAL_FILE *);
+PALIMPORT size_t __cdecl PAL_fread(PVOID, size_t, size_t, PAL_FILE *);
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Undo

File: src/pal/src/cruntime/file.cpp [hunk 11]
```diff
@@ -500,7 +500,7 @@ Function :
 
 size_t
 __cdecl
-PAL_fread(void * buffer, size_t size, size_t count, PAL_FILE * f)
+PAL_fread(PVOID buffer, size_t size, size_t count, PAL_FILE * f)
```
Comment (jkotas) [inline src/pal/src/cruntime/file.cpp]: Undo

File: src/pal/src/loader/module.cpp [hunk 12]
```diff
@@ -815,8 +815,7 @@ Return value:
     non-NULL - the base address of the mapped image
     NULL - error, with last error set.
 --*/
-void *
-PALAPI
+PVOID
```
Comment (jkotas) [inline src/pal/src/loader/module.cpp]: Why drop PALAPI?

File: src/pal/src/cruntime/misc.cpp [hunk 13]
```diff
@@ -300,7 +300,7 @@ See MSDN doc for memcpy
 --*/
 EXTERN_C
 PALIMPORT
-void *PAL_memcpy (void *dest, const void *src, size_t count)
+PVOID PAL_memcpy (PVOID dest, const void *src, size_t count)
```
Comment (jkotas) [inline src/pal/src/cruntime/misc.cpp]: Undo

File: src/pal/inc/pal.h (hunk 6 above)
Comment (am11) [reply src/pal/inc/pal.h]: Changed to `PVOID` in cpp files. Also reverted from CRT functions.

File: src/pal/inc/pal.h (hunk 8 above)
Comment (am11) [reply src/pal/inc/pal.h]: Ah, i thought all PAL_* are not considered (and tested) as CRT functions?
CRT: `memcpy` and `memcpy_s` 
non-CRT: `PAL_memcpy`

Comment (jkotas) [reply src/pal/inc/pal.h]: `PAL_memcpy` is a Windows-compatible shim over regular `memcpy` that is then used to override memcpy via `define`. It is more a CRT function than not.

File: src/pal/src/loader/module.cpp (hunk 12 above)
Comment (am11) [reply src/pal/src/loader/module.cpp]: In `pal.h`, there is:

```h
PALIMPORT
PVOID
PALAPI
PAL_LOADLoadPEFile(HANDLE hFile);
```

Should the implementation have both `PALIMPORT` and `PALAPI` or just the latter?

Comment (jkotas) [reply src/pal/src/loader/module.cpp]: Just the latter - it is how all other similar implementations look like as far as I can tell.

File: src/pal/src/loader/module.cpp [hunk 14]
```diff
@@ -815,8 +815,8 @@ Return value:
     non-NULL - the base address of the mapped image
     NULL - error, with last error set.
 --*/
-void *
 PALAPI
```
Comment (jkotas) [inline src/pal/src/loader/module.cpp]: Move PALAPI after PVOID

File: src/pal/inc/pal.h [hunk 15]
```diff
@@ -5154,21 +5155,21 @@ class CatchHardwareExceptionHolder
 class NativeExceptionHolderBase;
 
 PALIMPORT
-NativeExceptionHolderBase **
 PALAPI
```
Comment (jkotas) [inline src/pal/inc/pal.h]: PALAPI after return type?

File: src/pal/inc/pal.h [hunk 16]
```diff
@@ -2679,7 +2680,7 @@ Return value:
 --*/
 BOOL
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Add PALIMPORT for consistency with `PAL_LOADLoadPEFile`?

File: src/pal/inc/pal.h [hunk 17]
```diff
@@ -2747,7 +2748,7 @@ GetModuleFileNameExW(
 // Get base address of the module containing a given symbol
 PALAPI
```
Comment (jkotas) [inline src/pal/inc/pal.h]: Same?

File: src/pal/inc/pal.h (hunk 15 above)
Comment (am11) [reply src/pal/inc/pal.h]: GCC complains `'visibility' attribute ignored`.

**Comment by am11** [comment]
test OSX10.12 x64 Checked Innerloop Build and Test
test Windows_NT x64 min_opt ryujit CoreCLR Perf Tests Correctness

File: src/pal/src/misc/miscpalapi.cpp [hunk 18]
```diff
@@ -267,7 +267,7 @@ PAL_Random(
             DWORD offset = 0;
             do
             {
-                DWORD n = read(rand_des, (BYTE*)lpBuffer + offset , dwLength - offset);
+                auto n = read(rand_des, (BYTE*)lpBuffer + offset , dwLength - offset);
```
Comment (jkotas) [inline src/pal/src/misc/miscpalapi.cpp]: We avoid `auto` unless it is obvious what the type is. `size_t` ?

File: src/pal/inc/pal.h [hunk 19]
```diff
@@ -2829,7 +2832,7 @@ VOID
...
 RtlMoveMemory(
           IN PVOID Destination,
-          IN CONST VOID *Source,
+          IN const VOID *Source,
```
Comment (jkotas) [inline src/pal/inc/pal.h]: This can say upper case `CONST`

Comment (jkotas) [reply src/pal/inc/pal.h]: Or deleted completely (from here and from the implementation). It is not used anywhere.

(can be done as a separate PR)

File: src/pal/src/misc/miscpalapi.cpp (hunk 18 above)
Comment (am11) [reply src/pal/src/misc/miscpalapi.cpp]: It was `ssize_t` and since we are compiling with `-Wall`, it is hard to know if all supported platforms share the same. We could cast RHS to `DWORD` instead.

Comment (am11) [reply src/pal/src/misc/miscpalapi.cpp]: Actually `DWORD` is `uint32_t`, so the comparison on next line with `-1` causes error with GCC. Trying with `ssize_t` on `LHS`.

File: src/pal/inc/pal.h (hunk 19 above)
Comment (am11) [reply src/pal/inc/pal.h]: I agree, it would be better as a separate PR. There are some usages under tests, that would probably need to be cleaned out as well:

```powershell
~\source\repos\coreclr [gcc-visibility ≡]> git grep RtlMoveMemory
src/pal/src/memory/heap.cpp:  RtlMoveMemory
src/pal/src/memory/heap.cpp:RtlMoveMemory(
src/pal/src/memory/heap.cpp:    PERF_ENTRY(RtlMoveMemory);
src/pal/src/memory/heap.cpp:    ENTRY("RtlMoveMemory(Destination:%p, Source:%p, Length:%d)\n",
src/pal/src/memory/heap.cpp:    LOGEXIT("RtlMoveMemory returning\n");
src/pal/src/memory/heap.cpp:    PERF_EXIT(RtlMoveMemory);
src/pal/tests/palsuite/filemapping_memmgt/CMakeLists.txt:add_subdirectory(RtlMoveMemory)
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test1/test1.cpp:    RtlMoveMemory(NewAddress, OldAddress, MEMORY_AMOUNT);
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test1/testinfo.dat:Function = RtlMoveMemory
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test1/testinfo.dat:Name = Positive test for RtlMoveMemory API
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test3/test3.cpp:    RtlMoveMemory(NewAddress, OldAddress, OLD_MEMORY_AMOUNT);
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test3/testinfo.dat:Function = RtlMoveMemory
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test3/testinfo.dat:Name = Positive test for RtlMoveMemory API, move a small block to large
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test4/test4.cpp:    RtlMoveMemory(NewAddress, OldAddress, 50);
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test4/testinfo.dat:Function = RtlMoveMemory
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test4/testinfo.dat:Name = Positive test for RtlMoveMemory API, test that overlapping works
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test5/test5.cpp:    RtlMoveMemory(NewAddress, SectionToMove, MEMORY_AMOUNT-50);
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test5/testinfo.dat:Function = RtlMoveMemory
src/pal/tests/palsuite/filemapping_memmgt/RtlMoveMemory/test5/testinfo.dat:Name = Positive test for RtlMoveMemory API, test that overlapping works
src/pal/tests/palsuite/paltestlist.txt:filemapping_memmgt/RtlMoveMemory/test1/paltest_rtlmovememory_test1
src/pal/tests/palsuite/paltestlist.txt:filemapping_memmgt/RtlMoveMemory/test3/paltest_rtlmovememory_test3
src/pal/tests/palsuite/paltestlist.txt:filemapping_memmgt/RtlMoveMemory/test4/paltest_rtlmovememory_test4
src/pal/tests/palsuite/paltestlist.txt:filemapping_memmgt/RtlMoveMemory/test5/paltest_rtlmovememory_test5
```

Comment (jkotas) [reply src/pal/inc/pal.h]: These are tests for `RtlMoveMemory`. They should be delete with it.

**Review by jkotas — APPROVED** [review]
Thanks
