### PR TITLE
Disable GUI dialogs for assertion failures on Windows by default

### LINKED ISSUE #7678: How should we address pop-up dialogs during Windows test runs?
#7669 #7670 and #7671 are examples of assertion failures that pop up and hang the automation system, wasting hours of time before they are finally killed by a "whole job" timeout.

I would have expected `COMPlus_NoGuiOnAssert=1` to suppress these, but that doesn't appear to be the case, i.e. the path through `System_Private_CoreLib_ni!System.Diagnostics.Assert.Fail`, `CoreCLR!DebuggerAssert::ShowDefaultAssertDialog`, etc. doesn't seem to query that environment variable.

I think it makes sense to do more to prevent popups rather than relying on timeouts.

My naive preference would be that `COMPlus_NoGuiOnAssert` be made to divert all internal error paths away from UI popup, but I'm not confident enough in the design to claim that outright.  (TBH, I would also prefer that the effect of `COMPlus_NoGuiOnAssert=1` be the default setting).  I feel pretty strongly that a "dialog-killing daemon" that monitors for pop-ups and automatically dismisses them is the wrong solution.

Thoughts?

### PR DESCRIPTION
**Pull request by RussKeldorph**
This change disables creating pop-up dialog boxes by default on Windows
when assertions fail.  The change consists of three pieces:

1) Make COMPlus_NoGuiOnAssert effective in Release builds (currently
only Debug/Checked builds)
2) Make DebuggerAssert::ShowDefaultAssertDialog honor the
COMPlus_NoGuiOnAssert variable.
3) Make COMPlus_NoGuiOnAssert=1 by default.

Note that COMPlus_NoGuiOnAssert was already honored for assertions
originating from native code such as the JIT.  If pop-ups are desired,
one can still set COMPlus_NoGuiOnAssert=0.

Fixes #7678

### CODE REVIEW

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT corefx_baseline
@dotnet-bot test Ubuntu corefx_baseline

**Comment by RussKeldorph** [comment]
I recommend viewing the diff with [?w=1](https://github.com/dotnet/coreclr/pull/8033/files?w=1) to filter out whitespace diffs.

**Comment by RussKeldorph** [comment]
@dotnet-bot test Windows_NT corefx_baseline
@dotnet-bot test Ubuntu corefx_baseline

**Comment by RussKeldorph** [comment]
ARM failures are infrastructure
Ubuntu x64 failure is #8030
CoreFx failures are expected.  Windows run hangs due to pop-up dialog without this change.

@janvorli @jkotas could you take a look?  I was uncertain about some things but made my best guesses.  Feel free to rip it apart if this change is revealing my ignorance of runtime code.

**Comment by RussKeldorph** [comment]
@dotnet-bot test ci please

File: src/vm/debugdebugger.cpp [hunk 1]
```diff
@@ -1367,59 +1367,70 @@ FCIMPL4(INT32, DebuggerAssert::ShowDefaultAssertDialog,
...
-        msgText.Append(W("\n"));
-    }
-    msgText.Append(W("Description: "));
-    msgText.Append(message);
-    
-    StackSString stackTraceText;
-    if (gc.strStackTrace != NULL) {
-        stackTraceText.Append(W("Stack Trace:\n"));
-        stackTraceText.Append(stackTrace);
+#ifdef _DEBUG
```
Comment (janvorli) [inline src/vm/debugdebugger.cpp]: I think we don't want GUI asserts in retail builds either. Should we rather make the NoGuiOnAssert option retail?

**Comment by RussKeldorph** [comment]
@janvorli Thanks for the proactive CR!  In case you didn't notice, in addition to making NoGuiOnAssert work in Release, I also changed the result of `DebuggerAssert::ShowDefaultAssertDialog` from FailIgnore to FailTerminate as you had initially proposed.  I didn't realize assertions from outside the runtime go through this path as well, so I agree it makes more sense to terminate rather than ignore, even though the latter allows us to see more individual test failures during test runs.

File: src/vm/debugdebugger.cpp [hunk 2]
```diff
@@ -1367,59 +1367,68 @@ FCIMPL4(INT32, DebuggerAssert::ShowDefaultAssertDialog,
...
-        msgText.Append(W("\n"));
-    }
-    msgText.Append(W("Description: "));
-    msgText.Append(message);
-    
-    StackSString stackTraceText;
-    if (gc.strStackTrace != NULL) {
-        stackTraceText.Append(W("Stack Trace:\n"));
-        stackTraceText.Append(stackTrace);
+    if (NoGuiOnAssert())
```
Comment (jkotas) [inline src/vm/debugdebugger.cpp]: Nit - I would look better to do this as early out:

```
if (NoGuiOnAssert())
{
   return FailTerminate;
}
```

Comment (RussKeldorph) [inline src/vm/debugdebugger.cpp]: Can do.  Thanks.  Wasn't sure of preferred style.
