### PR TITLE
Do not promote struct field with type mistmatch.

### LINKED ISSUE #18986: Assertion failed 'rhs->OperGet() == GT_LONG'
This is a recent regression.

Every Ubuntu arm32 JitStress=2 with JitStressRegs failed with:
```
FAILED   - JIT/Methodical/fp/exgen/10w250d_cs_ro/10w250d_cs_ro.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun 10w250d_cs_ro.exe
               
               Assert failure(PID 23405 [0x00005b6d], Thread: 23405 [0x5b6d]): Assertion failed 'rhs->OperGet() == GT_LONG' in 'testout1:Func_0_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1():double' (IL size 788)
               
                   File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/jit/decomposelongs.cpp Line: 433
                   Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
               
               ./10w250d_cs_ro.sh: line 244: 23405 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
...
FAILED   - JIT/Methodical/fp/exgen/10w5d_cs_ro/10w5d_cs_ro.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun 10w5d_cs_ro.exe
               Func_0_6_5_6_3: != true
               Func_0_6_5_4_6: <= true
               Func_0_6_5_4_5: > true
               Func_0_6_5_4_3: == false
               Func_0_6_4_6_2: != true
               Func_0_6_4_5_4: < true
               Func_0_6_4_5_1: < true
               Func_0_6_4_4: <= true
               Func_0_6_3_6_5: == false
               Func_0_6_3_4_4: <= true
               Func_0_6_3_4_3: < true
               Func_0_6_3_3: < true
               Func_0_6_3_2_3: >= true
               Func_0_6_3_1_5: < true
               Func_0_6_3_1: <= false
               Func_0_6_3: != true
               Func_0_6_2_5: != true
               Func_0_6_2_1: > false
               Func_0_6_1_6_4: < false
               Func_0_6_1_6_3: > false
               Func_0_6_1_5_4: > true
               
               Assert failure(PID 23525 [0x00005be5], Thread: 23525 [0x5be5]): Assertion failed 'rhs->OperGet() == GT_LONG' in 'testout1:Func_0_6_1_3_3():double' (IL size 157)
               
                   File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/jit/decomposelongs.cpp Line: 433
                   Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
               
               ./10w5d_cs_ro.sh: line 244: 23525 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/15/consoleText.

There is currently no recent run without JitStressRegs to see if it fails with just JitStress=2 (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_flow/)

@dotnet/arm32-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
This PR adds 3 tests and 3 fixes for them (all fail on x64 checked without any stress modes).

52ed925e56: Add a test that reads int field as double. 

It fails in `void CodeGen::genCodeForStoreInd(GenTreeStoreInd* tree)`  on `assert(!varTypeIsFloating(targetType) || (targetType == data->TypeGet()));`.
Thanks @mikedn for writing this.

a951beb454: Fix for the previous test.

No asm diffs.

5ef50d001f: Add a test that reads struct field as another struct type.

It fails with assert `Compiler::StructPromotionHelper::CheckFakedType` `assert(fakedFieldsMap.Lookup(fieldHnd));`.

9edf8d32c6: Fix the previous test.

Check that we promote with the same class. No asm diffs.

6e87b6e603: Add a test case for accessing an invalid offset.
It fails in `fgMorphStructField` with `noway_assert(fieldLclIndex != BAD_VAR_NUM);`.

cfa32e3169: Fix the previous test.

Reject field promotion if an offset is invalid. No asm diffs.

Fixes #18986.

No diffs on System.Private.CoreLib.

Also, I want to note that all these checks are necessary only to support dependent struct promotion. However, we need dependent struct promotion is mostly because we understand that we can't do independent struct promotion too late. 
I have made small measurements and if we disable dependent struct promotion that we have only 21 byte regression in `System.Private.CoreLib` because CSE works better with `LCL_VAR` than with `FIELD(ADDR(LCL_VAR))` that probably hides another bug (when CSE creates a temp for a promoted struct that changes its value through `Unsafe.AsPointer`.
I will try to write a test that exposes this issue with CSE and measure TP win if we do not waste time on tracked LCL_VARs for dependent promoted struct if I have time next week.

Also, I want to express that I am proud that these issues were not reported by our customers, it means they do not use C# "to shoot yourself in the foot".

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @CarolEidt, @briansull, @mikedn.
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
This code confuses me:
https://github.com/dotnet/coreclr/blob/e30f187cda3767e1c50b870864de8d0eb5f8582a/src/jit/morph.cpp#L5150-L5156

Does this check need to be `varDsc->lvRefCnt(RCS_EARLY) >= 1`?

And the corresponding code that set this value is located in this function that I change here:
```
                if (lvaIsImplicitByRefLocal(lclNum))
                {
                    // Keep track of the number of appearances of each promoted implicit
                    // byref (here during struct promotion, which happens during address-exposed
                    // analysis); fgMakeOutgoingStructArgCopy checks the ref counts for implicit
                    // byref params when deciding if it's legal to elide certain copies of them.
                    // This should probably be moved LocalAddressVisitor, which does this already
                    // for GT_LCL_VAR nodes it encounters.
                    JITDUMP(
                        "Incrementing ref count from %d to %d for V%02d in fgMorphStructField for promoted struct\n",
                        varDsc->lvRefCnt(RCS_EARLY), varDsc->lvRefCnt(RCS_EARLY) + 1, lclNum);
                    varDsc->incLvRefCnt(1, RCS_EARLY);
                }
```
(I can't insert a link here because github doesn't show more than 13000 lines, so if you open https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp you can see that it shows `19008 lines (16501 sloc)` but the last rendered line is 13206).

So maybe we do not need to increase this counter if we reject the promotion, in this case my fix should be moved upper.

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -17162,6 +17162,12 @@ void Compiler::fgMorphStructField(GenTree* tree, GenTree* parent)
                     varDsc->incLvRefCnt(1, RCS_EARLY);
                 }
 
+                if (genTypeSize(tree->gtType) != genTypeSize(lvaTable[fieldLclIndex].TypeGet()))
+                {
```
Comment (briansull) [inline src/jit/morph.cpp]: We can allow smaller sized access here.
It is only when we are reading a larger size that we have the problem:

**Comment by AndyAyersMS** [comment]
The confusing code is doing a lightweight form of liveness analysis. If there's just one use of the implicit by-ref struct and the the method is loop free and the use is at a not at tail call we know the struct dies there, so we can substitute in the caller's version of the struct and not make the local copy. So the count has to be exactly one.

File: src/jit/morph.cpp (hunk 1 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: Yes, I think it is safe, but I think that others part of Jit do not expect such conversions.
We will have smth like:
```
[000601] ------------              *  STMT      void  (IL   ???...  ???)
[000854] ------------              |  /--*  LCL_VAR   long   (AX) V46 tmp45
[000600] -AC---------              \--*  ASG       int  
[000599] D------N----                 \--*  LCL_VAR   int V30 tmp29 
```
that doesn't look right, does it?

Comment (CarolEidt) [reply src/jit/morph.cpp]: I think that allowing a smaller sized access would require a cast. One would have to deduce whether we're reading or writing, and then cast accordingly. I'm not sure it's worth the extra complexity, but a comment indicating that it would be safe but not worth doing would be good.
That said, I believe that, at this point, the decision to promote has already been made. If we decide not to make the transformation, we need to set the variable as `lvDoNotEnregister` (presumably `DNER_LocalField`).

Comment (mikedn) [reply src/jit/morph.cpp]: I haven't been able to reproduce the issue so perhaps I'm missing something. But it seems to me that we should check the type (the "actual" type really) and not their sizes. Otherwise the same issue will likely show up for float/int and double/long "reinterpretation".

That probably can be made to work by inserting a bitcast node but this is probably not the right time to attempt such optimizations. And anyway this code should be rewritten and moved to LocalAddressVisitor. As is now it kind of duplicates logic done by that.

Comment (sandreenko) [reply src/jit/morph.cpp]: To repro the issue cherry-pick this change: https://github.com/dotnet/coreclr/commit/d485659348af3528b688ac5b7e4c58dacba6de58.

Comment (mikedn) [reply src/jit/morph.cpp]: I tried to make R2R corelib using the ReadyToRun crossgen parameter, perhaps it doesn't have the same effect. Anyway, too much trouble to reproduce using the existing test. Speaking of floating/integer mismatches here's a test that produces an assert:
```C#


```

Comment (mikedn) [reply src/jit/morph.cpp]: Good ol' x64 non-tiered produces
```
Assert failure(PID 11844 [0x00002e44], Thread: 13556 [0x34f4]): Assertion failed '!varTypeIsFloating(targetType) || (targetType == data->TypeGet())' in 'Program2:Test(struct)' (IL size 54)

    File: d:\projects\coreclr\src\jit\codegenxarch.cpp Line: 4675
    Image: D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\CoreRun.exe
```

**Comment by sandreenko** [comment]
The PR and the header were rewritten, please take another look @CarolEidt @dotnet/jit-contrib .

**Comment by sandreenko** [comment]
ping @dotnet/jit-contrib

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -17123,7 +17123,13 @@ void Compiler::fgMorphStructField(GenTree* tree, GenTree* parent)
                 // Promoted struct
                 unsigned fldOffset     = field->gtFldOffset;
                 unsigned fieldLclIndex = lvaGetFieldLocal(varDsc, fldOffset);
-                noway_assert(fieldLclIndex != BAD_VAR_NUM);
+
+                if (fieldLclIndex == BAD_VAR_NUM)
+                {
+                    // Access a promoted struct's field with an offset that doesn't correspond to any field.
+                    // It can happen if the struct was casted to another struct with different offsets.
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: Nit: 'casted' -> 'cast'
