### PR TITLE
Fix #3570: RyuJIT x86: Float/Double mismatch in CodeGen::genStoreInd()

### LINKED ISSUE #3570: RyuJIT x86: Float/Double mismatch in CodeGen::genStoreInd()
The following tests get this assert:

Assert failure(PID 2336 [0x00000920], Thread: 15712 [0x3d60]): Assertion failed '!varTypeIsFloating(targetType) || (targetType == data->TypeGet())'
File: d:\git\coreclr\src\jit\codegenxarch.cpp Line: 5255

JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b27535\b27535\b27535.cmd
in 'stelem_test:main():int' (IL size 46)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59948\b59948\b59948.cmd
in 'ILGEN_0xa20b8571:Method_0x15903b4b(byte,double,long,ubyte):int' (IL size 284)

In both cases it seems that they are missing a cast to float from double.

### PR DESCRIPTION
**Pull request by BruceForstall**
There is code in the importer to insert explicit converts between float and double
but it was only running for `_TARGET_64BIT_`. I changed this to a more appropriate
`!_LEGACY_BACKEND_`.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by sivarv** [comment]
Looks good.

**Comment by briansull** [comment]
Looks good

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -9818,7 +9818,7 @@ void              Compiler::impImportBlockCode(BasicBlock * block)
                 {
                     arrayElem = typeInfo::nativeInt();
                 }
-#endif // _TARGET_64_BIT
+#endif // _TARGET_64BIT
```
Comment (kyulee1) [inline src/jit/importer.cpp]: _TARGET_64BIT_
