### PR TITLE
Fix Issue 7196: No extra internal regs for block nodes

### LINKED ISSUE #7196: ARM64: Assert failure: (value != 0) && ((value & (value-1)) == 0)
This occurs in the latest sources, but was not occurring prior to #7027. It was not fixed by PR #7188 which fixed some other failures due to that PR. This affects the following four tests:
JIT\Directed\perffix\primitivevt\mixed1_cs_do\mixed1_cs_do.cmd
JIT\Directed\perffix\primitivevt\mixed1_cs_ro\mixed1_cs_ro.cmd 
JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd
JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd
At first look, it seems to be asserting when getting a register.

### PR DESCRIPTION
**Pull request by CarolEidt**
There is some possibly obsolete code that copies the internal registers
for a GT_IND onto the address node as well. With the struct IR changes,
the block nodes (e.g. GT_STORE_BLK) also return true for OperIsIndir(),
so they were getting the internal registers copied over from their address
node. This led to an assert on Arm64.

Fix #7196

### CODE REVIEW

**Comment by CarolEidt** [comment]
I filed an issue, #7290, to determine whether this internal register copying code should be eliminated altogether.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -8270,7 +8270,7 @@ void LinearScan::resolveRegisters()
             {
                 JITDUMP(" internal");
                 GenTreePtr indNode = nullptr;
-                if (treeNode->OperIsIndir())
+                if (treeNode->OperGet() == GT_IND)
```
Comment (sivarv) [inline src/jit/lsra.cpp]: >if (treeNode->OperGet() == GT_IND) [](start = 16, length = 34)

It might be a good idea to audit all OperIsIndir() uses to see if code really meant to check if it is GT_IND/GT_STOREIND/GT_NULLCHECK

Comment (sivarv) [inline src/jit/lsra.cpp]: >              if (treeNode->OperGet() == GT_IND) [](start = 2, length = 48)

If I remember correctly, prior to first class struct work, OperIsIndir() was returning true if oper is GT_IND/STOREIND/NULLCHECK. 
Now this check is reduced to just checking GT_IND.  Don't we need to check here for STOREIND?

Comment (CarolEidt) [inline src/jit/lsra.cpp]: It is my belief that this code is obsolete. It is certainly not required for `GT_NULLCHECK`, for which the address is never contained. For `GT_STORE_IND`, I could not find any use of internal registers in codegen.

**Comment by sivarv** [comment]
Looks good.

**Comment by sivarv** [comment]
:shipit:

File: src/jit/lsra.cpp (hunk 1 above)
Comment (CarolEidt) [inline src/jit/lsra.cpp]: @sivarv I had done so prior to those changes, but obviously missed this one. I have just done so again. There are some places in instr.cpp where the check is broader than it needs to be (e.g. in `instEmit_indCall()` it checks `addr->OperIsIndir()` on the call address, which should probably just be a check for `GT_IND`, but it is not actually incorrect, as that is the only indirection we will encounter there).

**Comment by briansull** [comment]
LGTM
