### PR TITLE
Keep delegate fields alive across a full native call

### LINKED ISSUE #20894: Delegates fields not kept alive across a marshalling boundary
As discovered in #20689, the marshalling infrastructure in .NET Core doesn't keep delegate fields in classes or structures alive across a marshalling boundary. So, the GC can collect the delegate during the transition from managed to native and cause a crash.

#20892 fixes this in our tests by adding a `GC.KeepAlive` call after the marshalling boundary.

As an interesting note, MCG adds in `GC.KeepAlive` calls for marshalling delegates and delegate fields for ProjectN. We should look at doing something similar in CoreCLR.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
As reported in #20894, delegate fields aren't being kept alive across a marshalling boundary. So, if the struct or class containing them is not used afterwards, the GC might clean them up before the native call returns. This was discovered during a GC stress test run (#20689).

To implement this, I repurposed the  `CleanupWorkList` to also preserve delegate references in structs across the full native call, since it already exists and is also passed to each field marshaler when marshalling in the vulnerable direction.

Fixes #20894 

See #20689, #20892

### CODE REVIEW

File: src/vm/fieldmarshaler.cpp [hunk 1]
```diff
@@ -3910,7 +3910,27 @@ VOID FieldMarshaler_Delegate::UpdateNativeImpl(OBJECTREF* pCLRValue, LPVOID pNat
     }
     CONTRACTL_END;
 
+    // A cleanup list MUST be specified in order for us to be able to marshal
+    // the Delegate.
```
Comment (jkotas) [inline src/vm/fieldmarshaler.cpp]: Is this also used for manual marshaling using `PtrToStructure` - is this change going to break it?

**Comment by jkotas** [comment]
Do we need to add tests for this?

File: src/vm/fieldmarshaler.cpp (hunk 1 above)
Comment (jkoritzinsky) [reply src/vm/fieldmarshaler.cpp]: I will check and verify for you.

**Comment by jkoritzinsky** [comment]
I think the gc stress test runs will provide the test coverage we need for this.

**Comment by jkotas** [comment]
We have fixed the tests that failed under GCStress because of this to workaround the issue in #20892 . Do we need to remove the workaround?

File: src/vm/fieldmarshaler.cpp (hunk 1 above)
Comment (jkoritzinsky) [reply src/vm/fieldmarshaler.cpp]: Yes it does.

I have two possible ideas for this:

- Add a CleanupWorkList in the implementation of `Marshal.StructureToPtr`. I don't think this one really makes sense but it's an option.
- Make having a CleanupWorkList optional for delegate marshalling. This would make more sense IMO.

**Comment by jkoritzinsky** [comment]
Yes we would want to remove the workaround in #20892 if it get's merged before this does (which it likely will).

File: src/vm/fieldmarshaler.cpp (hunk 1 above)
Comment (jkotas) [reply src/vm/fieldmarshaler.cpp]: > Make having a CleanupWorkList optional for delegate marshalling. This would make more sense IMO.

Agree. (Also, check that we have a test for this - this test should be failing with the current version of the change.)

Comment (jkoritzinsky) [reply src/vm/fieldmarshaler.cpp]: Added a test om the latest commit.

File: src/System.Private.CoreLib/src/System/StubHelpers.cs [hunk 2]
```diff
@@ -1501,18 +1502,19 @@ public override void Cleanup()
 
     internal sealed class CleanupWorkList
```
Comment (jkotas) [inline src/System.Private.CoreLib/src/System/StubHelpers.cs]: You can merge `CleanupWorkListElement` and `CleanupWorkList` into one class.

File: src/vm/fieldmarshaler.cpp [hunk 3]
```diff
@@ -3956,14 +3974,15 @@ VOID FieldMarshaler_SafeHandle::UpdateNativeImpl(OBJECTREF* pCLRValue, LPVOID pN
     // A cleanup list MUST be specified in order for us to be able to marshal
     // the SafeHandle.
     if (ppCleanupWorkListOnStack == NULL)
```
Comment (jkotas) [inline src/vm/fieldmarshaler.cpp]: I would think that this should continue to throw like before. Or is the throw unreachable via public APIs?

File: src/System.Private.CoreLib/src/System/StubHelpers.cs (hunk 2 above)
Comment (jkotas) [reply src/System.Private.CoreLib/src/System/StubHelpers.cs]: (It should also allow you to keep `m_Next` field as private.)

File: src/vm/fieldmarshaler.cpp (hunk 3 above)
Comment (jkoritzinsky) [reply src/vm/fieldmarshaler.cpp]: I think this one is reachable. I'll check, and if it is I'll add back the throw.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0x3
@dotnet-bot test Windows_NT x86 Checked gcstress0x3

File: src/System.Private.CoreLib/src/System/StubHelpers.cs [hunk 4]
```diff
@@ -1453,42 +1453,83 @@ internal struct NativeVariant
...
+        public void Destroy()
+        {
+            DestroyCore();
+            var next = m_Next;
+            while (next != null)
+            {
+                next.DestroyCore();
+                next = next.m_Next;
+            }
+            m_Next = null;
```
Comment (jkotas) [inline src/System.Private.CoreLib/src/System/StubHelpers.cs]: You should not need to set it to null here.

File: src/System.Private.CoreLib/src/System/StubHelpers.cs [hunk 5]
```diff
@@ -1453,42 +1453,83 @@ internal struct NativeVariant
...
 
+    internal abstract class CleanupWorkListElement
+    {
+        private CleanupWorkListElement m_Next;
+        protected abstract void DestroyCore();
+
+        public void Destroy()
+        {
+            DestroyCore();
+            var next = m_Next;
```
Comment (jkotas) [inline src/System.Private.CoreLib/src/System/StubHelpers.cs]: This should have explicit type (`CleanupWorkListElement `) not `var` according to the coding convention.

File: src/System.Private.CoreLib/src/System/StubHelpers.cs [hunk 6]
```diff
@@ -1453,42 +1453,82 @@ internal struct NativeVariant
...
+            DestroyCore();
+            CleanupWorkListElement next = m_Next;
+            while (next != null)
+            {
+                next.DestroyCore();
+                next = next.m_Next;
+            }
+        }
+        
+        public static void AddToCleanupList(ref CleanupWorkListElement list, CleanupWorkListElement newElement)
```
Comment (AaronRobinsonMSFT) [inline src/System.Private.CoreLib/src/System/StubHelpers.cs]: Are we doing to have a threading issue here? Is this state only accessed on a single thread?

Comment (jkotas) [reply src/System.Private.CoreLib/src/System/StubHelpers.cs]: > Is this state only accessed on a single thread?

Yes.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
