### PR TITLE
Fix handling of NullReferenceException in VSD on ARM

### LINKED ISSUE #25123: [ARM7/Linux] nullref leads to ABRT / SEGV exit code
Environment:
Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/opt/dotnet/shared/Microsoft.NETCore.App]

root@gpomykala:~ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 1
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 3.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

Hardware        : Freescale i.MX6 Quad/DualLite (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

We have an ASP.NET core app which deserializes some JSON data using custom JsonConverter.
It may happen that converter throws a NullRef which is handled in the app. 

Unfortunately on linux-arm we never reach the error handling code since the process exits either with SIGABRT.
I believe it is similar to ##16462.

Logs:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MyCompany.Persistency.Converters.MyConverter`1.DoReadJson(JToken jsonObject, T resultValue, JsonSerializer serializer)
   at MyCompany.Persistency.Converters.BaseConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
) = ?
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

I am trying to make a reproduction with a sample app, please let me know whether i could provide more details.

### PR DESCRIPTION
**Pull request by janvorli**
There was a problem with handling NullReferenceExceptionHandling stemming
from virtual dispatch stub on ARM Linux. While the primary exception was
handled correctly, if the exception was rethrown or another exception
was thrown from the catch handler, it was reported as unhandled even
though there was a proper handler.
The issue was caused by exception unwinding that was unable to unwind past
the frame of the virtual dispatch stub in this case. Such stub is generated
at runtime and there is no unwind info for it.

The fix is to explicitly check for the stub frame and skip it during first
and second pass of exception handling.

Close #25123

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @RussKeldorph

File: src/vm/arm/exceparm.cpp [hunk 1]
```diff
@@ -102,8 +102,10 @@ AdjustContextForVirtualStub(
     PCODE callsite = GetAdjustedCallAddress(GetLR(pContext)); 
 
     // Lr must already have been saved before calling so it should not be necessary to restore Lr
-
-    pExceptionRecord->ExceptionAddress = (PVOID)callsite;
+    if (pExceptionRecord != NULL)
```
Comment (jkotas) [inline src/vm/arm/exceparm.cpp]: Do we need the same condition in the x86 version as well?

Comment (janvorli) [reply src/vm/arm/exceparm.cpp]: Right, we do.

**Comment by janvorli** [comment]
@dotnet/dnceng Some of the the tests in "Linux arm64 checked" leg are failing with 
```
2019-07-10 17:57:50,519: ERROR: dockerhelper(179): run: API Error attempting to talk to Docker Server:404 Client Error: Not Found ("No such container: e1f4aef5e95f0511bdc97415e559817f487e4491d9a143e66f42459443887d2d")
2019-07-10 17:57:50,519: ERROR: dockerhelper(180): run: Docker may not be configured correctly on this machine.  Contact dnceng for help.
2019-07-10 17:57:50,520: INFO: dockerhelper(35): cleanup: Cleaning up Docker on the machine
2019-07-10 17:57:50,529: ERROR: executor(521): _execute_command_in_container: Exception: local variable 'timed_out' referenced before assignment
2019-07-10 17:57:50,529: INFO: executor(523): _execute_command_in_container: Finished _execute_command_in_container, exit code: None
```
(see   Results will be available from https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F25628~2Fmerge/test~2Ffunctional~2Fcli~2F/20190710.22)

Is it possible that some of our lab devices has misconfigured docker?

**Comment by MattGal** [comment]
That error would indicate the container running somehow disappeared while this was going.  I kind of wonder if there's > 1 helix client running on the same box. 

I've taken that specific machine offline and am tagging @ilyas1974 as FYI.  I don't have time to investigate this second; Ilya can you take a peek?

**Comment by RussKeldorph** [comment]
@MeiChin-Tsai FYI

**Comment by ilyas1974** [comment]
@janvorli are you still seeing this issue on the ARM devices? I could not find anything wrong with the devices and wanted to follow up.

**Comment by MattGal** [comment]
@ilyas1974 this was one specific machine  (I think DDARM64S-003 ) that got reimaged 7/11 and seems fine since.
