### PR TITLE
Fix CircleInConvex to check result within 1 ULP

### LINKED ISSUE #3964: tests/src/JIT/SIMD/CircleInConvex.cs failure
Test returns 0 on x86.  I suspect the problem is the epsilon check here

  https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/SIMD/CircleInConvex.cs#L263

The inequality operator appears to be reversed.  The test passes on x64 because the error is greater than what is ostensibly expected.

### PR DESCRIPTION
**Pull request by CarolEidt**
This test was checking for the result to be within epsilon of the
expected result, but this is not correct unless the algorithm is
evaluating all interim results to a larger precision.
It would also be more reasonable for the test to compute the expected
result (e.g. using an alternate algorithm), and it would also be nice
to have a method to compute ULP for a given value, but those are beyond
the scope of this fix.

Fix #3964

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: tests/src/JIT/SIMD/CircleInConvex.cs [hunk 1]
```diff
@@ -259,8 +259,9 @@ static int Main(string[] args)
             float r;
             FindCircle(points, out O, out r);
 
-            float expRes = 7.565624E7F;
-            if (Math.Abs(r - expRes) > EPS)
+            float expRes = 75656240.0F;
+            float ulp    =        8.0F;
```
Comment (briansull) [inline tests/src/JIT/SIMD/CircleInConvex.cs]: I'm unsure how the value 8.0F was determined, but I do not that 
 EPS * expRes * steps = 7.5656, using 1E-09 for EPS

**Comment by briansull** [comment]
Looks Good

**Comment by RussKeldorph** [comment]
LGTM

File: tests/src/JIT/SIMD/CircleInConvex.cs (hunk 1 above)
Comment (CarolEidt) [inline tests/src/JIT/SIMD/CircleInConvex.cs]: The value is 1 ULP (unit in the last place) for the expected result value (i.e. the difference between the expected result, represented as float, and the next representable value), computed manually. It could be computed from the value, but would require several steps, including reinterpreting the bits as an int, so it seemed best to just use a "magic" constant, as is done for `expRes`.

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

**Comment by RussKeldorph** [comment]
Oops, I need to retract my LGTM.  Please remove the test exclusions in https://github.com/dotnet/coreclr/blob/master/tests/issues.targets and https://github.com/dotnet/coreclr/blob/master/tests/x86_legacy_backend_issues.targets with this change.

**Comment by RussKeldorph** [comment]
@CarolEidt In case it's not obvious, it looks like you'll need to retain the exclusions in issues.targets, but move them into the RyuJIT section nearer the bottom.

**Comment by CarolEidt** [comment]
Thanks! it wasn't obvious to me yet because I'm waiting for my daughter at a physical therapy appt, and their WiFi network isn't working, so I'm writing up the long notes while I wait.

Now I have les triage to do when I get back 😊

Sent from my Windows Phone
________________________________

**Comment by RussKeldorph** [comment]
@CarolEidt You can use issue #4992 when you add back the exclusions in issues.targets.  @BruceForstall @adiaaida FYI.

**Comment by CarolEidt** [comment]
@dotnet-bot test  FreeBSD x64 Checked Build

**Comment by RussKeldorph** [comment]
Looks like indentation is off in issues.targets, but probably not worth re-testing since these lines will necessarily be removed at some point.  LGTM.

**Comment by CarolEidt** [comment]
The OSX failures are apparently invalid tests that have now been removed.
