### PR TITLE
Avoid doing dangerous cleanup in case of process detach

### LINKED ISSUE #24472: [EventPipe] Cancel test while writing events causing crash
Test:
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs
Line 28:
Set messageIterations = 1000000;

Cancel the test while it's writing events, then it crashed with following exception:
```
F:\TempRepo\coreclr>bin\tests\Windows_NT.x64.Debug\tracing\eventsource\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd
BEGIN EXECUTION
 "F:\TempRepo\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" eventsourcetrace.exe
        Start: Enable tracing.
        End: Enable tracing.

        Start: Messaging.

Assert failure(PID 8920 [0x000022d8], Thread: 7780 [0x1e64]): Precondition failure: FAILED: HasDebuggerDataLock()

CORECLR! CHECK::Trigger + 0x261 (0x00007ff8`7c12c3c1)
CORECLR! Debugger::CreateMethodInfo + 0x184 (0x00007ff8`7ce9a1d4)
CORECLR! Debugger::GetOrCreateMethodInfo + 0x1A6 (0x00007ff8`7cea7886)
CORECLR! Debugger::GetJitInfoWorker + 0x1FE (0x00007ff8`7cea6c4e)
CORECLR! Debugger::GetJitInfo + 0x272 (0x00007ff8`7cea6992)
CORECLR! Debugger::GetILToNativeMappingIntoArrays + 0x20F (0x00007ff8`7cea564f)
CORECLR! ETW::MethodLog::SendMethodILToNativeMapEvent + 0x2BF (0x00007ff8`7c330f2f)
CORECLR! ETW::MethodLog::SendEventsForJitMethodsHelper + 0x277 (0x00007ff8`7c32ee17)
CORECLR! ETW::MethodLog::SendEventsForJitMethods + 0x31D (0x00007ff8`7c32eb1d)
CORECLR! ETW::EnumerationLog::IterateDomain + 0x302 (0x00007ff8`7c323862)
    File: f:\temprepo\coreclr\src\debug\ee\debugger.cpp Line: 2543
    Image: F:\TempRepo\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe
```

### PR DESCRIPTION
**Pull request by cshung**
Fixes #24472

When s_fProcessDetach occurs, all threads (except the one running EEShutdown) are terminated by the operating system at the moment the request to terminate the process happens (e.g. Ctrl+C or ExitProcess). Therefore, if a thread obtained a lock and got terminated, that thread will never be able to release the lock, or signal an event, so any operation pending on lock is dangerous in the shutdown.

We fixed this once in PR #24466 for issue #24459, however the fix is not sufficient. Here I simply skipped the whole process, in an attempt for a full fix.

### CODE REVIEW

File: src/vm/eventpipe.cpp [hunk 1]
```diff
@@ -196,6 +196,20 @@ void EventPipe::Shutdown()
     }
     CONTRACTL_END;
 
+    if (s_fProcessDetach)
```
Comment (sywhang) [inline src/vm/eventpipe.cpp]: `g_fProcessDetach`?
