### PR TITLE
Fix finding entry point unwind record for a method with fragmented un…

### LINKED ISSUE #19209: [Arm64/Linux] b399444b fails under gcStress=0xC jitstress=1
I added a few new configurations to my nightly runs.

This test is consistently failing in these configs
```
gcStress=0xC jitstress=1 JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
gcStress=0xC jitstress=2 JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
```

Failure looks similar to the LocalAlloc fail.

```
corerun b399444b.exe

Assert failure(PID 7270 [0x00001c66], Thread: 7270 [0x1c66]): 
    !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: src/vm/jithelpers.cpp Line: 5157
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
…wind

On Arm and Arm64 unwind records can only cover a limited range of code
(512K and 1MB respectively). So for methods larger than this the jit
will emit multiple "fragment" unwind records to cover the full method code
range. Only the first of these describes the behavior of the method prolog.

When mapping an offset back to a method's entry point unwind, make sure to
find this "root" unwind record instead of one of the internal fragments.

Fixes #19209.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@janvorli PTAL
cc @BruceForstall

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by janvorli** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

File: src/vm/codeman.cpp [hunk 1]
```diff
@@ -3899,19 +3907,24 @@ PTR_RUNTIME_FUNCTION EEJitManager::LazyGetFunctionEntry(EECodeInfo * pCodeInfo)
...
+            break;
         }
     }
 
-    return NULL;
+#if defined(EXCEPTION_DATA_SUPPORTS_FUNCTION_FRAGMENTS)
+    pFunctionEntry = FindRootEntry(pFunctionEntry, baseAddress);
+#endif
+
+    return pFunctionEntry;
```
Comment (janvorli) [inline src/vm/codeman.cpp]: Actually, I've just realized that in case we don't find a function entry, we were returning NULL before. But with your change, we would use the latest function entry we've seen. Could you please fix that to get the old behavior back? It seems that the easiest way is to move the code that looks for the root entry to the place where you have the `break`, return from there instead of breaking and put back the `return NULL` at the end.

Comment (AndyAyersMS) [reply src/vm/codeman.cpp]: Thanks, will fix.

**Comment by AndyAyersMS** [comment]
Latest push should fix the null issue and adds (restores) some comments.

@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by AndyAyersMS** [comment]
Sigh. Need to actually return the entry instead of always returning null. Will push a fix shortly.

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by AndyAyersMS** [comment]
Hmm, build issues for the GC stress legs... did not realize test legs can share a build leg like this.
```
12:24:14   bne_opt -> /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/bin/tests/Linux.arm64.Checked/JIT/jit64/opt/regress/vswhidbey/223862/bne_opt/bne_opt.exe
12:24:15 Command execution failed with exit code 139.
```
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress1 Build and Test
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked gcstress0xc_jitstress2 Build and Test

**Comment by AndyAyersMS** [comment]
@janvorli want to take one more look?

**Comment by janvorli** [comment]
@AndyAyersMS it looks good to me.
