### PR TITLE
Always normalize stores when spilling lclVars.

### LINKED ISSUE #7236: RyuJIT x86: [JitStress=2][JitStressRegs=8] JIT\Methodical\unsafecsharp\_speed_dbgunsafe-4\_speed_dbgunsafe-4.exe test fails with IndexOutOfRange exception
```
11:53:18 D:\j\workspace\x86_ryujit_ch---2044ccf6\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(283074): error : JIT._Methodical_unsafecsharp__speed_dbgunsafe_4__speed_dbgunsafe_4_._Methodical_unsafecsharp__speed_dbgunsafe_4__speed_dbgunsafe_4_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\runtest.proj]
11:53:18         
11:53:18   Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
11:53:18            at TestApp.test_25(B* pb, Int64[,,] i, Int64 ii, Byte jj) in D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\src\JIT\Methodical\unsafecsharp\unsafe-4.cs:line 28
11:53:18            at TestApp.Main() in D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\src\JIT\Methodical\unsafecsharp\unsafe-4.cs:line 306
11:53:18   
11:53:18   
11:53:18   Return code:      1
11:53:18   Raw output file:      D:\j\workspace\x86_ryujit_ch---2044ccf6\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\unsafecsharp\_speed_dbgunsafe-4\_speed_dbgunsafe-4.output.txt
11:53:18   Raw output:
11:53:18   BEGIN EXECUTION
11:53:18          "D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" _speed_dbgunsafe-4.exe 
11:53:18         Expected: 100
11:53:18         Actual: -532462766
11:53:18         END EXECUTION - FAILED
11:53:18         FAILED
11:53:18         Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by pgavlin**
In order to support the semantics of the MSIL evaluation stack, RyuJIT
normalizes all "small" lclVars (i.e. lclVars with a non-struct
type that is smaller than an int32) from the actual type of the lclVar
to int32. This normalization may be performed in one of two ways:
- the lclVar's may be normalized when the lclVar is used (load
  normalization)
- at any point at which the value is defined, the value being stored to
  the lclVar is normalized (store normalization)

Store normalization must not be used if the lclVar is aliasable, since
the contents of the upper bytes for that lclVar's slot may be modified
by some other alias. Load normalization must be used if the lclVar is
a method parameter, as there is no guarantee that the caller has
properly nomralized the arguments it has passed. As such, any lclVar
that is either aliasable or is a method parameter is load-normalized,
and any other lclVar is store-normalized. lclVars that are
store-normalized are assumed to be represented as properly zero- or
sign-extended 4-byte values at all times, and so can simply be loaded
as int32s.

This picture becomes somewhat more subtle after register allocation,
however: once a lclVar has been enregistered, the contents of its
register are guaranteed to be properly zero- or sign-extended for the
purposes of store normalization, and in order for the lclVar to have
been enregistered in the first place, it must not have been aliasable.
As such, all enregistered variables may be store-normalized (as well as
load-normalized, if they represent method parameters). This has a
particularly significant impact on spills, as it implies that even if
the lclVar being spilled is not normally considered store-normalized, it
may be considered so for the purposes of the spill. This is advantageous
for architectures such as x86, as it allows a small lclVar to be
successfully spilled from a register that is not addressable at the size
of the lclVar's type. This change switches both LSRA and the code
generator to always use the actual type of a spilled lclVar for the
corresponding store rather than making this behavior conditional on
whether or not the lclVar is store-normalized.

Fixes #7236.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @sivarv @dotnet/jit-contrib PTAL

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -8423,23 +8423,10 @@ void LinearScan::resolveRegisters()
...
-                            JITDUMP("  Move struct field param V%02u from %s to %s\n", lclNum, getRegName(sourceReg),
-                                    getRegName(initialReg));
-                            insertMove(insertionBlock, insertionPoint, lclNum, sourceReg, initialReg);
-                        }
-                    }
-                }
+
+                // Stack args that are part of dependently-promoted structs should never be register candidates (see
+                // LinearScan::isRegCandidate).
+                assert(varDsc->lvIsRegArg || !compiler->lvaIsFieldOfDependentlyPromotedStruct(varDsc));
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Ah good catch - I think this code has been there for a while, but is clearly not needed.

**Comment by CarolEidt** [comment]
Something occurred to me after pondering this for a bit. What happens if we have a sub-int type parameter that's a register candidate, but which either doesn't get assigned an initial register, or is evicted later (which will cause it to behave as if it didn't get an initial assignment, I believe)? In that case, we can't rely on it having been normalized the next time we "reload" it. I think that case may need to be handled specially - which would indicate that the spill code would need to have a way to distinguish those cases.

---
In reply to: [251833878](https://github.com/dotnet/coreclr/pull/7504#issuecomment-251833878) [](ancestors = 251833878)

**Comment by CarolEidt** [comment]
OK, nevermind - I realize that you hare optimizing the spill case, not the reload case, which is still doing the appropriate sign- or zero-extension. When we go down the path of optimizing the reload case, we'll have to take this into consideration.

---
In reply to: [251837186](https://github.com/dotnet/coreclr/pull/7504#issuecomment-251837186) [](ancestors = 251837186,251833878)

File: src/jit/codegenlinear.cpp [hunk 2]
```diff
@@ -710,11 +710,7 @@ void CodeGen::genSpillVar(GenTreePtr tree)
     bool needsSpill = ((tree->gtFlags & GTF_VAR_DEF) == 0 && varDsc->lvIsInReg());
     if (needsSpill)
     {
-        var_types lclTyp = varDsc->TypeGet();
-        if (varDsc->lvNormalizeOnStore())
-        {
-            lclTyp = genActualType(lclTyp);
-        }
+        var_types lclTyp = genActualType(varDsc->TypeGet());
```
Comment (sivarv) [inline src/jit/codegenlinear.cpp]: >  var_types lclTyp = genActualType(varDsc->TypeGet()); [](start = 6, length = 54)

It would be a good idea to add a comment explaining why we use actual type here.

File: src/jit/lsra.cpp [hunk 3]
```diff
@@ -8581,20 +8570,16 @@ void LinearScan::insertMove(
     // This var can't be marked lvRegister now
     varDsc->lvRegNum = REG_STK;
 
-    var_types lclTyp = varDsc->TypeGet();
-    if (varDsc->lvNormalizeOnStore())
-    {
-        lclTyp = genActualType(lclTyp);
-    }
+    var_types lclTyp = genActualType(varDsc->TypeGet());
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: For this case, I think you need to use the original type ("actual" type always seems a bit of a misnomer to me) if `fromReg` is `REG_STK`. Which puts you down that path again of having to worry about byteable registers, right?

Comment (sivarv) [inline src/jit/lsra.cpp]: We have the following cases

1) lcl-var is getting spilled from reg to stack:
use type of VarDsc on src.
Spill logic will use the actual/normalized type of src while writing reg to stack.

2) lcl-var is getting loaded from stack to reg:
use the type of VarDsc on src.  Codgen for GT_LCL_VAR will sign/zero-extend  the result while loading from stack to reg.

3) lcl-var is getting copied from one reg to another reg:
Use genActualType() on top and src, because codegen will use mov while generating code for GT_COPY.


---
In reply to: [82099257](https://github.com/dotnet/coreclr/pull/7504#discussion_r82099257) [](ancestors = 82099257)

Comment (pgavlin) [inline src/jit/lsra.cpp]: > Yes, and case 2 is the case that is problematic because we will need a byteable register for a byte type.

Why would we need a byte-addressable register in this case? Won't we just generate a `mov{z,s}x r32, m8`?

File: src/jit/lsra.cpp [hunk 4]
```diff
@@ -8581,20 +8570,22 @@ void LinearScan::insertMove(
...
 
-    // If we are moving from STK to reg, mark the lclVar nodes with GTF_SPILLED
-    // Otherwise, if we are moving from reg to stack, mark it as GTF_SPILL
-    // Finally, for a reg-to-reg move, generate a GT_COPY
+    // There are three cases we need to handle:
+    // - We are loading a lclVar from the stack.
+    // - We are storing a lclVar to the stack.
+    // - We are copying a lclVar between registers.
+    //
+    // In the first and second cases, the lclVar node will be marked with GTF_SPILLED and GTF_SPILL, respetively.
```
Comment (sivarv) [inline src/jit/lsra.cpp]: Nit: typo "respetively"

Comment (pgavlin) [inline src/jit/lsra.cpp]: Fixed.

**Comment by sivarv** [comment]
Looks good to me.

File: src/jit/lsra.cpp (hunk 3 above)
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Ah yes, I had forgotten that the simple move case was a non-issue for bytes.

**Comment by CarolEidt** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs8

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
