### PR TITLE
Fix assertion failure on ARM

### LINKED ISSUE #4344: ARM Regression / Assert failure: isRuntimeSuspended
On ARM/Linux, CoreCLR currently failed to execute "Hello, World" console application with the following message:
`
Assert failure(PID 1059 [0x00000423], Thread: 1059 [0x0423]): isRuntimeSuspended
    File: /home/parjong/projects/toolchains/coreclr/src/vm/arm/stubs.cpp Line: 487
    Image: /mnt/dotnet-c235ae17cd3a87f8032948bdcb838641d8e6c055/corerun
`

I checked various commits, and attached the result at below. 
- 'O' means that CoreCLR from that commit can print Hello, World, 
- 'X' means that CoreCLR failed to print Hello, World with the above assertion failrue, and 
- '?' means that CoreCLR failed to print Hello, World with a different reason.

bd7ee6206f05fbc321e7f69383423f05d440e7b6, X
dc86158d1ce41dfcb775c921a9e6d1f7fed90868, X
8614810caec4b5a2a33547fe3f9dfd3982357b6e, X
deadffbd21fde9706e3237969208f995928cd843, X
257951f3a30b880d863c813bf5528fef5f44fdea, X
a207199a67acee162c0ed865fa70252add2dccef, O
0ec739e4416d12eeaac0c365fae09e503b080eaf, X
3ad8f15af54add9dcc3ecb8b89f3b9a82c65bef3, X
8ba667ba08a57f420aa3067e8b57e51185802650, X
517207b9d3f2a53c726a8682c1331cf7bdb0360b, X
8beda3c1561aa7a4b4a18ea98e719fc9fd52a638, X
39ac49632a499877db8b8656dc63d147c7a8fe39, O
5ad8da8b1239585a9e75a20ed2137e8b92bfe6c9, X
2ef3e9124d883c859995ded1a1f177d91f789197, O
afdce3a592e5f6f2047bed057d121225be91743d, X
98d914bc0c9b167ee3e7abd3f4aee636f88cba59, O
5ef243f597b8198efce1add587f16aae59b1f568, O
867b8f1ff301d1d0842abec75447be4e94c1f17c, O
c235ae17cd3a87f8032948bdcb838641d8e6c055, X
5d55afa3600904dd2376db9af9838f2fbba27945, O
e735df2e106e2a119ced1db2a6fdcbe0ad5890c6, O
3409ad136021c42da1d982478ea0b609db1202a3, O
ae2d2f3d103d0a20d1609725c7eec0830e0cf654, O
b7e35b9c3d87ba84b859f9f9f795857dfbbda653, O
d241f9d5bcdaf9e99e4c4e54508d2cec2ed35d04, O
a1eedcb8767e5833b5f1134efcb26ff8612ec315, O
121a91d73c7ac1f0264f62eff1451d742b94e0dd, O
c2d2efffe0ed58c55be1db5f254056b54ec41654, O
7c4c8f3efc6e9acdbd1aa972b10b00ea11b63c27, O
ed172f6944eb5fd3a1b9390ceaef0ee09f3fb122, O
6b9efccc55654928225829b853267f1062fa42fa, O
63554209e89d38785f2a1241939c490370e3efed, O
5c9b92876a4b1641393e20ac2e7638c3c0f296c8, ?
68e27689d709b846505813af806dfb11b19777ef, O
9475224327e45faa56e6ecbfcc5fa503656d5c20, O
2c737588bed6550f56b9470278382d807a6fd9b4, O
0fe70e83f801002521b658372f5e1390016fe09a, O
e59013a59744d05fa4c60570f25198c160ba3582, O
67d03ca438bf8327b82655669d616d1aa7ad8541, O
b6502aae0447fe7ccbc21b354c545c8ba58c902a, O
3a6e9459c0b5dc69f898272b290ce0333cebd55b, O
484c855fe4a91a8ea67213457d69182669c65ded, O

This results indicates that 'c235ae17cd3a87f8032948bdcb838641d8e6c055' may be the first commit that introduces this symptom.

### PR DESCRIPTION
**Pull request by kouvel**
StompWriteBarrierEphemeral may be called on the init path, where the runtime is technically not suspended, but has not started yet. Added a check for g_fEEInit in the call.

Fixes #4344

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k @Maoni0 @jkotas @myungjoo

File: src/gc/gc.cpp [hunk 1]
```diff
@@ -9645,7 +9645,7 @@ void gc_heap::adjust_ephemeral_limits ()
                  (size_t)ephemeral_low, (size_t)ephemeral_high))
 
     // This updates the write barrier helpers with the new info.
-    StompWriteBarrierEphemeral(!!IsSuspendEEThread());
+    StompWriteBarrierEphemeral(g_fEEInit || !!IsSuspendEEThread());
```
Comment (jkotas) [inline src/gc/gc.cpp]: `g_fEEInit` is CoreCLR VM specific variable. It should not be used in the GC - it will cause problems with sharing the GC with ProjectN/CoreRT.

Comment (jkotas) [inline src/gc/gc.cpp]: You should pass a flag to adjust_ephemeral_limits instead.

Comment (kouvel) [inline src/gc/gc.cpp]: Ah ok, fixed

**Comment by jkotas** [comment]
LGTM

File: src/gc/gc.cpp [hunk 2]
```diff
@@ -10442,7 +10442,7 @@ gc_heap::init_gc_heap (int  h_number)
     make_background_mark_stack (b_arr);
 #endif //BACKGROUND_GC
 
-    adjust_ephemeral_limits();
+    adjust_ephemeral_limits(true);
```
Comment (adityamandaleeka) [inline src/gc/gc.cpp]: This is up to you, but in cases like this where it's not immediately clear what the parameter means and the function declaration isn't nearby, I'd do something like  `adjust_ephemeral_limits(true /* is_runtime_suspended */);`

Comment (kouvel) [inline src/gc/gc.cpp]: Yea I usually do that in new code. The change has already been merged, so I'll leave it for now.
