### PR TITLE
Use resolver to get IL header and size

### LINKED ISSUE #7896: Assert in CORECLR!tagCOR_ILMETHOD_FAT::GetSize while doing code coverage on debug coreclr
I repeatedly hit the following assert while trying to run the corefx System.IO.Tests on a debug coreclr built from the latest in master while using OpenCover to gather code coverage data.

```
---------------------------
CoreRun.exe - Assert Failure (PID 54076, Thread 48296/0xbca8)
---------------------------
Consistency check failed: AV in clr at this callstack:
------
CORECLR! tagCOR_ILMETHOD_FAT::GetSize + 0x16 (0x00007ffd`4b50ff46)
CORECLR! MethodDesc::MakeJitWorker + 0x5DC (0x00007ffd`4b8cb75c)
CORECLR! MethodDesc::DoPrestub + 0xFC0 (0x00007ffd`4b8c76c0)
CORECLR! ReflectionInvocation::CompileMethod + 0x2BF (0x00007ffd`4be7259f)
<no module>! <no symbol> + 0x0 (0x00007ffc`ed2f07b9)
<no module>! <no symbol> + 0x0 (0x00007ffc`ed488cf0)
<no module>! <no symbol> + 0x0 (0x00007ffc`ec9d8ab0)
<no module>! <no symbol> + 0x0 (0x000000e4`76dcbd20)
CORECLR! ThePreStub + 0x55 (0x00007ffd`4bbf7145)
<no module>! <no symbol> + 0x0 (0x00007ffc`ed2eeffe)
<no module>! <no symbol> + 0x0 (0x000002c0`001c1950)
<no module>! <no symbol> + 0x0 (0x000002c0`001c1950)
<no module>! <no symbol> + 0x0 (0x000002c0`001beb3c)
<no module>! <no symbol> + 0x0 (0x00000000`00000001)
-----
.AV on tid=0xbca8 (48296), cxr=000000E476DCAD40, exr=000000E476DCB230
FAILED: false

CORECLR! CHECK::Trigger + 0x26A (0x00007ffd`4b4cc6fa)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2F6 (0x00007ffd`4b725db6)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x8C (0x00007ffd`4b7257dc)
CORECLR! CLRVectoredExceptionHandler + 0x262 (0x00007ffd`4b725732)
CORECLR! CLRVectoredExceptionHandlerShim + 0x113 (0x00007ffd`4b725ff3)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffd`a503aac0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffd`a50183cb)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffd`a5078a3a)
CORECLR! tagCOR_ILMETHOD_FAT::GetSize + 0x16 (0x00007ffd`4b50ff46)
CORECLR! MethodDesc::MakeJitWorker + 0x5DC (0x00007ffd`4b8cb75c)

c:\users\stoub\source\repos\coreclr\src\vm\excep.cpp, Line: 8141
```

### PR DESCRIPTION
**Pull request by mjsabby**
The code previously had a special case (for IL Stubs) which I incorrectly read. This change is actually better since it queries the information directly from the appropriate resolver and how the JIT-EE interface also reads these values.

Fixes #7896.

### CODE REVIEW

**Comment by mjsabby** [comment]
cc @jkotas @noahfalk

File: src/vm/prestub.cpp [hunk 1]
```diff
@@ -443,7 +443,11 @@ PCODE MethodDesc::MakeJitWorker(COR_ILMETHOD_DECODER* ILHeader, DWORD flags, DWO
                 }
                 else
```
Comment (jkotas) [inline src/vm/prestub.cpp]: You will incorrectly go into this code when `&& (! fBackgroundThread)` is false. This check needs to be moved up.

**Comment by jkotas** [comment]
Thanks for fixing it.
