### PR TITLE
[RyuJIT/ARM32] Fix to find a free temp double register correctly

### LINKED ISSUE #14374: [RyuJIT/arm32][JitStress=2][JitStressRegs=4] Assertion failed '(regSet.rsMaskVars & regMask) == 0'
Found in an x86_arm_altjit run.

```
Assert failure(PID 5064 [0x000013c8], Thread: 4296 [0x10c8]): Assertion failed '(regSet.rsMaskVars & regMask) == 0' in 'ILGEN_0x372a9ae6:Method_0xdc6ff1a4(byte,byte,int,int,char,double,long,long):int' (IL size 11052)

    File: d:\j\workspace\x86_arm_altji---82a001f9\src\jit\codegencommon.cpp Line: 598
    Image: D:\j\workspace\x86_arm_altji---82a001f9\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Tests, configurations:

```
COMPlus_JitStress=2
COMPlus_JitStressRegs=4

JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59782\b59782\b59782.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b60142\b60142\b60142.cmd
```

### PR DESCRIPTION
**Pull request by hqueue**
When finding a free temporary double register to resolve conflicting edges,
we have to consider both two float registers consisting a double register.

This PR partilly resolves an assertion in #14374.
`JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b60142/b60142/b60142.sh` is passed with this fix.

### CODE REVIEW

**Comment by hqueue** [comment]
@CarolEidt Please take a look. Thanks.

/cc: @dotnet/arm32-contrib

**Comment by BruceForstall** [comment]
@hqueue Can you fix the formatting?

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -10049,10 +10049,28 @@ regNumber LinearScan::getTempRegForResolution(BasicBlock* fromBlock, BasicBlock*
...
             freeRegs &= ~genRegMask(fromReg);
+#ifdef _TARGET_ARM_
+            if (type == TYP_DOUBLE && genIsValidFloatReg(fromReg))
+            {
+                regNumber anotherHalfRegNum;
+                anotherHalfRegNum = genIsValidDoubleReg(fromReg) ? REG_NEXT(fromReg) : REG_PREV(fromReg);
+
+                freeRegs &= ~genRegMask(anotherHalfRegNum);
+            }
+#endif
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: I suspect that there are other places in resolution that require us to track both halves of the double register. For now, I would suggest adding a wrapper for `genRegMask` that takes, only on ARM, a type, e.g.:
```
getRegisterMask(regNumber reg ARM_ARG( RegisterType type));
```
This would return both bits for a double.

Comment (hqueue) [reply src/jit/lsra.cpp]: > I suspect that there are other places in resolution that require us to track both halves of the double register. 

Yes, as you suspected, I almost found the cause of another remaining bug in resolution conflicts. I will make another PR for that.

> For now, I would suggest adding a wrapper for genRegMask that takes, only on ARM, a type,  on ARM, a type, e.g.:

Thanks for the suggestion. I will apply this.

**Comment by hqueue** [comment]
@CarolEidt I've update the PR. 
I've introduced a helper  `getConflictRegMask` instead of `getRegisterMask` which you suggested, because I found that there is a `genRegMask(regNumber regNum, var_types type)` which confuses me.
What do you think of this ?

**Comment by CarolEidt** [comment]
>  I found that there is a genRegMask(regNumber regNum, var_types type) which confuses me.

Actually, I took a look at that, and I think you can just use it, without the `ARM_ARG` because in the non-ARM case it just throws away the type argument.

**Comment by hqueue** [comment]
>> I found that there is a genRegMask(regNumber regNum, var_types type) which confuses me.

> Actually, I took a look at that, and I think you can just use it, without the ARM_ARG because in the non-ARM case it just throws away the type argument.

@CarolEidt I'm afraid we can't use `genRegMask(regNumber regNum, var_types type)` instead of `getConflictRegMask` , because `genRegMask(regNumber regNum, var_types type)` assumes that `regNum` is even-numbered float register when type is `TYP_DOUBLE`.

If  we are going to use `genRegMask`, we need `#ifdef _TARGET_ARM_` to `lsra.cpp` again.

**Comment by CarolEidt** [comment]
> we can't use genRegMask(regNumber regNum, var_types type) instead of getConflictRegMask , because genRegMask(regNumber regNum, var_types type) assumes that regNum is even-numbered float register when type is TYP_DOUBLE.

I what case would you be calling it with `TYP_DOUBLE` where `regNum` is not a valid double register? If it is copying a double lclVar, it must be a valid double register.

**Comment by hqueue** [comment]
For example, when `f8` is free and `f9` is occupied by a `TYP_FLOAT` interval.
Then we should exclude both `f8` and `f9` from `freeRegs` when we are trying to find a free double register. So `getTempRegForResolution()` have to call `getConflictRegMask(f9, TYP_DOUBLE)` to exclude both registers from freeRegs at https://github.com/dotnet/coreclr/pull/14588/files#diff-93fb9832a03a9783e2a415b581fcb45cR10051

**Comment by CarolEidt** [comment]
OK, now I see what you're doing. Sorry for my confusion. I think there's still a problem, because if the type passed in is `TYP_FLOAT`, you won't be excluding both double regs for lclVars that are `TYP_DOUBLE`.

I think it would be better to collect the *actual* free regs (i.e. excluding regs from `freeRegs` based on the type of the lclVar), e.g.:
```
            freeRegs &= ~genRegMask(fromReg, getIntervalForLocalVar(varIndex).registerType);
```
and then at the end, ensuring that you have two double regs free for the `TYP_DOUBLE` case, e.g.:
```
    if (freeRegs == RBM_NONE)
    {
        return REG_NA;
    }
    if (type == TYP_DOUBLE)
    {
        // Exclude any doubles for which the odd half isn't in freeRegs.
        freeRegs = freeRegs & (freeRegs<< 1) & RBM_ALL_DOUBLE;
    }
    regNumber tempReg = genRegNumFromMask(genFindLowestBit(freeRegs));
    return tempReg;
```
While this means you have to get the type off of each lclVar, you don't have to check for the odd/even double case, and I believe it handles both the case of looking for a `TYP_DOUBLE` and taking into account the registers occupied by `TYP_FLOAT`, as well as the case where you're looking for a `TYP_FLOAT` and need to remove 2 regs from `freeRegs` for the `TYP_DOUBLE` lclVars.

**Comment by hqueue** [comment]
@CarolEidt Thank for the suggetsion :)

> I think there's still a problem, because if the type passed in is TYP_FLOAT, you won't be excluding both double regs for lclVars that are TYP_DOUBLE.

Right! I've not handled this case.

I also had a similar thought, i.e. exploiting `freeRegs << 1`, in different way to improve throughput instead of using helper functions.

I will update PR with suggested approach.

**Comment by hqueue** [comment]
@CarolEidt Update the PR with suggested approach. Thanks.
