### PR TITLE
Change tests to not modify Core_Root

### LINKED ISSUE #23429: Test failure: Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_/_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_sh
Opened on behalf of @AriNuer

The test `Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_/_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_sh` has failed.

Failure Message:
```

Unhandled Exception: System.IO.IOException: Read-only file system
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at TestLibrary.HostPolicyMock.Initialize(String testBasePath, String coreRoot) in /__w/3/s/tests/src/Common/CoreCLRTestLibrary/HostPolicyMock.cs:line 67
   at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.Initialize() in /__w/3/s/tests/src/Loader/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.cs:line 22
   at AssemblyDependencyResolverTests.TestBase.RunTestsForType(Type testType) in /__w/3/s/tests/src/Loader/AssemblyDependencyResolverTests/TestBase.cs:line 51
   at AssemblyDependencyResolverTests.TestBase.RunTests(Type[] testTypes) in /__w/3/s/tests/src/Loader/AssemblyDependencyResolverTests/TestBase.cs:line 30
   at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.Main() in /__w/3/s/tests/src/Loader/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.cs:line 314
/root/helix/work/workitem/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.sh: line 259:    74 Aborted                 (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"
/n/nReturn code:      1/nRaw output file:      /root/helix/work/workitem/Reports/Loader.AssemblyDependencyResolverTests/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.output.txt/nRaw output:/nBEGIN EXECUTION
/root/helix/work/correlation/corerun AssemblyDependencyResolverTests.exe ''
TestMissingHostPolicy Start
TestMissingHostPolicy PASSED.
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
/nTo run the test:/n> set CORE_ROOT=/root/helix/work/correlation/n> /root/helix/work/workitem/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.sh/n
Expected: True
Actual:   False
```

Stack Trace:
```
   at Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_sh() in /__w/3/s/bin/tests/Linux.arm64.Release/TestWrappers/Loader.AssemblyDependencyResolverTests/Loader.AssemblyDependencyResolverTests.XUnitWrapper.cs:line 109
```

Build : 3.0 - 20190324.72 (Core Tests)
Failing configurations:
- (Ubuntu.18.04.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-0a0ebdd-20190312220351-arm64
  - 
  - 
- (Debian.9.Arm64 on Docker)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-0a0ebdd-20190312215438-arm64
  - 
  - 

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190324.72/workItem/Loader.AssemblyDependencyResolverTests/analysis/xunit/Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_~2F_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_sh

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Redesign tests that needed to modify Core_Root to no longer do so.

- Loader.FromNativePaths: Use `CORE_LIBRARIES` instead of `COREROOT`
- Loader.AssemblyDependencyResolver: Split out the invalid hosting test that needs hostpolicy to not be preloaded. Have `CoreRun` and `CoreShim` preload hostpolicy when a path to a hostpolicy is specified in the `MOCK_HOSTPOLICY` environment variable.
- Add a `CLRTest.MockHosting.targets` file that is imported when a test requires hostpolicy. It adds the reference to the mock hostpolicy and ensures that the `MOCK_HOSTPOLICY` environment variable is correctly set in the test scripts.

Old description:

For tests that need to modify Core_Root during execution, copy the Core_Root folder to a subfolder named Local_Core_Root and run from there. This is to avoid trying to write to Core_Root (which is read-only on some Helix agents) and avoid the possibility of non-determinism between tests.

Fixes #23429.

cc: @AaronRobinsonMSFT

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
In general I am not opposed to this, but I did some reworking to avoid modifying Core_Root for COM tests. What is the current reason this is needed?

**Comment by jkoritzinsky** [comment]
The hostpolicy mock needs to be placed next to `System.Private.CoreLib` as I understand it so `System.Private.CoreLib` can P/Invoke into it (since we limit its search paths to its directory and the system search paths). If that's not the case and hostpolicy can live next to the test app, then we can do that instead.

**Comment by AaronRobinsonMSFT** [comment]
>since we limit its search paths to its directory

See https://github.com/dotnet/coreclr/tree/master/tests/src/Interop/COM/Activator for an example of a test using the mocked out `hostpolicy` in the test directory. This could also be due to the work I did in [`CoreShim`](https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/coreshim/CoreShim.cpp#L165-L195), which should be applied to `CoreRun` if that is also needed there.

**Comment by AaronRobinsonMSFT** [comment]
The gist here is we shouldn't be modifying Core_Root in any way because it will break any chance we have for the possibility of running tests in parallel. Making a copy is a reasonable compromise, but that should be an absolute last resort.

**Comment by jkoritzinsky** [comment]
So based on @AaronRobinsonMSFT's feedback, we don't need a local Core_Root for the COM tests.

However, I don't believe we can unconditionally enable CoreRun to load hostpolicy.dll if present for a few reasons:

- I don't know if Unix shared object loading works the same way as Windows, where you can effectively intercept a DLL load by pre-loading a dll with the same name. If they don't have the same behavior, then we have no way to correctly pre-load a hostpoilcy since it needs to live in the right location. Although, we might be able to use `LD_PRELOAD` to forcibly load the correct .so beforehand.

- The AssemblyDependencyResolverTests suite includes a test for the behavior for when hostpolicy isn't found. As a result, we can't preload hostpolicy since it would be found when the test is assuming that it won't be. If we remove this test verifying the missing-hostpolicy behavior, then we could pre-load hostpolicy here if we wanted.

- The FromNativePaths test verifies that a native library can be loaded from a path given by the `"NATIVE_DLL_SEARCH_DIRECTORIES"` configuration parameter passed to the runtime, which CoreRun sets to its current directory and also the directory pointed to by the `CORE_LIBRARIES` environment variable. It does not use hostpolicy, so pre-loading hostpolicy won't help here. We could intercept the `CORE_LIBRARIES` environment variable and modify it in the script before starting the test.

**Comment by jkoritzinsky** [comment]
I've updated the tests to not need to modify Core_Root and load hostpolicy differently to ensure we do everything correct.

File: src/coreclr/hosts/coreshim/CoreShim.cpp [hunk 1]
```diff
@@ -150,6 +150,39 @@ namespace Utility
...
+        // Initialize the hostpolicy mock to a default state
+        using Set_corehost_resolve_component_dependencies_Values_fn = void(__cdecl *)(
+            int returnValue,
+            const WCHAR *assemblyPaths,
+            const WCHAR *nativeSearchPaths,
+            const WCHAR *resourceSearchPaths);
+        auto set_comp_depend_values = (Set_corehost_resolve_component_dependencies_Values_fn)
+            ::GetProcAddress(hMod, "Set_corehost_resolve_component_dependencies_Values");
+
+        if (set_comp_depend_values != nullptr)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/coreshim/CoreShim.cpp]: Please don't check for null, this is a bug and should crash if it isn't null.

File: src/coreclr/hosts/coreshim/CoreShim.cpp [hunk 2]
```diff
@@ -158,39 +191,12 @@ HRESULT coreclr::GetCoreClrInstance(_Outptr_ coreclr **instance, _In_opt_z_ cons
...
-        HRESULT hr;
-        std::wstring coreShimPath;
-        RETURN_IF_FAILED(Utility::GetCoreShimDirectory(coreShimPath));
-
-        std::wstring hostpolicyPath{ coreShimPath };
-        hostpolicyPath.append(hostpolicyName);
-
-        // Check if a hostpolicy exists and if it does, load it.
-        if (INVALID_FILE_ATTRIBUTES != ::GetFileAttributesW(hostpolicyPath.c_str()))
+        if(!TryLoadHostPolicy(GetEnvVar(mockHostPolicyEnvVar).c_str()))
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/coreshim/CoreShim.cpp]: Space between `if` and `(`.

File: src/coreclr/hosts/coreshim/CoreShim.cpp [hunk 3]
```diff
@@ -158,39 +191,12 @@ HRESULT coreclr::GetCoreClrInstance(_Outptr_ coreclr **instance, _In_opt_z_ cons
...
 
-    // Since the CoreShim is being loaded, there is a chance the scenario depends on
-    // other aspects of the offical host platform (e.g. hostpolicy). Verify a hostpolicy
-    // is _not_ already loaded and if not, attempt to load a hostpolicy library adjacent
-    // to the coreshim. If there isn't one, just keep going.
-    const WCHAR *hostpolicyName = W("hostpolicy.dll");
-    HMODULE hMod = ::GetModuleHandleW(hostpolicyName);
-    if (hMod == nullptr)
+    const wchar_t* mockHostPolicyEnvVar = W("MOCK_HOSTPOLICY");
+    if (::GetEnvironmentVariableW(mockHostPolicyEnvVar, nullptr, 0) != 0)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/coreshim/CoreShim.cpp]: Why the double call? This makes no sense. Please just check for an empty string.

File: tests/src/CLRTest.MockHosting.targets [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+***********************************************************************************************
+-->
+<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+  <PropertyGroup>
+    <HostPolicyFileExtension>so</HostPolicyFileExtension>
+    <HostPolicyFileExtension Condition="$(TargetsOSX) =='true'">dylib</HostPolicyFileExtension>
+  </PropertyGroup>
+  <ItemGroup>
+    <ProjectReference Include="$(MSBuildThisFileDirectory)/Common/hostpolicymock/CMakeLists.txt" />
+    <CLRTestBashEnvironmentVariable Include="export MOCK_HOSTPOLICY=$%28pwd)/hostpolicy.$(HostPolicyFileExtension)" />
```
Comment (AaronRobinsonMSFT) [inline tests/src/CLRTest.MockHosting.targets]: Comment on why the `%28` and `%25` are needed.

File: src/coreclr/hosts/coreshim/CoreShim.cpp (hunk 3 above)
Comment (jkoritzinsky) [reply src/coreclr/hosts/coreshim/CoreShim.cpp]: The double call is because the implementation of `GetEnvVar` throws if the length is `0`. I'll make that throw optional and remove the double call.

**Comment by jkoritzinsky** [comment]
Test failures are due to #23558 as far as I can tell.

**Comment by jkoritzinsky** [comment]
@echesakovMSFT test failures in Pri1 Windows x86 look unrelated to this PR and it passed on Linux arm64.

File: src/coreclr/hosts/coreshim/CoreShim.cpp [hunk 5]
```diff
@@ -64,10 +64,10 @@ namespace
         return std::wstring{ buffer.Buf, buffer.Buf + len };
     }
 
-    std::wstring GetEnvVar(_In_z_ const WCHAR *env)
+    std::wstring GetEnvVar(_In_z_ const WCHAR *env, _In_opt_ bool throwOnEmpty = true)
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/coreshim/CoreShim.cpp]: I realize this is a common idiom in the CoreCLR codebase but in my opinion it is a very bad design. Either a function throws or it doesn't. Instead please create another function that uses try semantics returns an `HRESULT`. For example:

```
bool TryGetEnvVar(_In_z_ const WCHAR *, _Inout_ std::wstring &);
```

This could be implemented any number of ways, but doesn't have the default argument nor do arguments dictate function semantics.

File: src/coreclr/hosts/corerun/corerun.cpp [hunk 6]
```diff
@@ -498,6 +515,16 @@ bool TryRun(const int argc, const wchar_t* argv[], Logger &log, const bool verbo
     nativeDllSearchDirs.Append(W(";"));
     nativeDllSearchDirs.Append(hostEnvironment.m_coreCLRDirectoryPath);
 
+    // Preload mock hostpolicy if requested.
+    StackSString hostpolicyPath;
+    if (WszGetEnvironmentVariable(W("MOCK_HOSTPOLICY"), hostpolicyPath) > 0 && hostpolicyPath.GetCount() > 0)
+    {
+        if (!TryLoadHostPolicy(hostpolicyPath))
+        {
+            log << W("Unable to load requested mock hostpolicy.");
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/corerun/corerun.cpp]: Why is this okay? Tests should fail hard if they don't operate as expected.

File: src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp [hunk 7]
```diff
@@ -339,6 +339,17 @@ int ExecuteManagedAssembly(
...
     nativeDllSearchDirs.append(clrFilesAbsolutePath);
 
+    void* hostpolicyLib = nullptr;
+    char* mockHostpolicyPath = getenv("MOCK_HOSTPOLICY");
+    if (mockHostpolicyPath)
+    {
+        hostpolicyLib = dlopen(mockHostpolicyPath, RTLD_LAZY);
+        if (hostpolicyLib == nullptr)
+        {
+            fprintf(stderr, "Failed to load mock hostpolicy at path '%s'. Error: %s", mockHostpolicyPath, dlerror());
```
Comment (AaronRobinsonMSFT) [inline src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp]: Again, if a tests requests the behavior and it can't be satisfied then it needs to fail/crash/format drive... something to indicate the test can't verify the intended scenario.

File: tests/src/CLRTest.Execute.Bash.targets [hunk 8]
```diff
@@ -251,9 +251,8 @@ fi
 ]]>
           </BashLinkerTestCleanupCmds>
       </PropertyGroup>
-      <PropertyGroup>
+      <PropertyGroup>
```
Comment (AaronRobinsonMSFT) [inline tests/src/CLRTest.Execute.Bash.targets]: Remove spaces

File: tests/src/CLRTest.MockHosting.targets [hunk 9]
```diff
@@ -0,0 +1,21 @@
...
+CLRTest.MockHosting.targets
+
+This file contains the logic for correctly hooking up a mock hostpolicy to a test.
+
+***********************************************************************************************
+-->
+<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
+  <PropertyGroup>
+    <HostPolicyFileExtension>so</HostPolicyFileExtension>
+    <HostPolicyFileExtension Condition="$(TargetsOSX) =='true'">dylib</HostPolicyFileExtension>
```
Comment (AaronRobinsonMSFT) [inline tests/src/CLRTest.MockHosting.targets]: This condition is wrong. It should be `'$(TargetsOSX)' =='true'` (i.e. missing single quotes).

Comment (AaronRobinsonMSFT) [reply tests/src/CLRTest.MockHosting.targets]: Also please add the `.` in the extension, otherwise it is just a string.

File: tests/src/Loader/AssemblyDependencyResolver/MissingHostPolicyTests/InvalidHostingTest.cs [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+                
+                object innerException = Assert.Throws<InvalidOperationException>(() =>
+                {
+                    AssemblyDependencyResolver resolver = new AssemblyDependencyResolver(
+                        Path.Combine(testBasePath, componentAssemblyPath));
+                }).InnerException;
+
+                Assert.IsType<DllNotFoundException>(innerException);
+            }
+            catch (System.Exception ex)
```
Comment (AaronRobinsonMSFT) [inline tests/src/Loader/AssemblyDependencyResolver/MissingHostPolicyTests/InvalidHostingTest.cs]: Remove `System.`
