### PR TITLE
Fix various disassembly issues

### LINKED ISSUE #8300: RyuJIT debug dump displays YMM registers on 128 bit AVX instruction instead of XMM registers
Currently by setting COMPlus_JITDump or COMPlus_JITDisasm on debug build, the RyuJIT debug dump displays YMM registers instead of XMM registers on 128 bit AVX instruction. To be consistent with Intel Architecture manual and WinDbg/SOS output, the JIT debug dump should print YMM registers on 256 bit AVX instruction and XMM registers on 128 bit AVX instruction.

For example, following C# code:

    static Guid s_dt;
    private static void test()
    {
        var dt = new Guid();
        Method1(dt);
    }

RyuJIT generated following related code via COMPlus_JITDisasm setting:

       33C9                 xor      rcx, rcx
       488D45E8             lea      rax, bword ptr [rbp-18H]
       C4E17957C0           vxorpd   ymm0, ymm0
       C4E17A7F00           vmovdqu  qword ptr [rax], ymm0
       C4E17A6F45E8         vmovdqu  ymm0, qword ptr [rbp-18H]
       C4E17A7F45D8         vmovdqu  qword ptr [rbp-28H], ymm0
       488D4DD8             lea      rcx, bword ptr [rbp-28H]
       E8B49CFFFF           call     Program:Method1(struct)

The vmovdqu instruction has 128bit encode version VMOVDQU xmm2/m128, xmm1 and 256bit encode
version VMOVDQU ymm1, ymm2/m256. Above instruction  "C4E17A7F00         vmovdqu  qword ptr [rax], ymm0" is using 128bit encode version (emitter attr is not EA_32BYTE), the encoding code C4E17A7F00 is correct, however, the dump should display the register to be xmm0 instead of ymm0 to avoid misleading.

### PR DESCRIPTION
**Pull request by mikedn**
- (null) being displayed instead of ymmword ptr
- lack of a space between some instructions and their first operand
- incorrect display of pmovmskb's first operand (was something like yrax)
- displaying ymm registers in cases where xmm registers were actually used
- displaying mm instead of xmm/ymm (e.g. cmpps mm1, mm2)

Fixes #8300 
Alternative to #8301

### CODE REVIEW

**Comment by mikedn** [comment]
cc @dotnet/jit-contrib @litian2025

**Comment by pgavlin** [comment]
LGTM

@CarolEidt, @BruceForstall: can one of you take a look as well?

**Comment by CarolEidt** [comment]
Awesome! These are issues that have been around for a long time, and it will be great to have them addressed.

**Comment by BruceForstall** [comment]
Excellent! These have bothered me for a while (but apparently not enough for me to do anything about them! :-) )

LGTM

File: src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -6575,9 +6598,9 @@ void emitter::emitDispIns(
         printf(" %-9s", sstr);
     }
 #ifndef FEATURE_PAL
-    if (strnlen_s(sstr, 10) > 8)
+    if (strnlen_s(sstr, 10) >= 8)
 #else  // FEATURE_PAL
-    if (strnlen(sstr, 10) > 8)
+    if (strnlen(sstr, 10) >= 8)
```
Comment (mikedn) [inline src/jit/emitxarch.cpp]: I missed the FEATURE_PAL case in the original commit. I wonder if using `strnlen`/`strnlen_s` is warranted here...

File: src/jit/emitxarch.cpp [hunk 2]
```diff
@@ -5890,10 +5899,24 @@ const char* emitter::emitRegName(regNumber reg, emitAttr attr, bool varName)
...
+            }
+            break;
+
+        case EA_4BYTE:
+            if ((REG_XMM0 <= reg) && (reg <= REG_XMM7))
+            {
+                return emitXMMregName(reg);
+            }
+            break;
+#else // LEGACY_BACKEND
```
Comment (mikedn) [inline src/jit/emitxarch.cpp]: Formatting fixed.
