### PR TITLE
Stack size override

### LINKED ISSUE #21450: Enable overriding default stack size on Windows
When hosting CoreCLR inside IIS using AspNetCoreModule it inherits stack sizes from `w3wp.exe` that are smaller then default (512K in 64 bit version and 256K in 32bit one.). 

Customers started hitting stack overflow exceptions in apps that used to work because of that: https://github.com/aspnet/AspNetCore/issues/4531 https://github.com/aspnet/EntityFrameworkCore/issues/14116

Would be nice if we can give them a way to increase managed stack size similar to https://github.com/dotnet/coreclr/pull/13517

@janvorli @jkotas

### PR DESCRIPTION
**Pull request by sdmaclea**
Add code to override process default stack size for VM from the property bag

Fixes #21450

/cc @jkotalik

### CODE REVIEW

File: src/vm/threads.cpp [hunk 1]
```diff
@@ -2144,6 +2144,30 @@ HANDLE Thread::CreateUtilityThread(Thread::StackSizeBucket stackSizeBucket, LPTH
...
+
+        SIZE_T max4KPages = SIZE_T(1) << (31 - 12);
+
+        if ((errno == ERANGE) || (valueStr == end) || (end == nullptr) || (end[0] != 0) || (value >= max4KPages))
+        {
+            ThrowMessage("OVERRIDE_DEFAULT_STACK_SIZE_4KPAGES value parse error");
+        }
+        else
+        {
+            FastInterlockExchange((int32_t*)&s_overrideDefaultStackSize, (uint32_t) value * 4096);
```
Comment (janvorli) [inline src/vm/threads.cpp]: Why do we need interlocked operation here? Do you expect multiple threads to race for setting the value? It seems that it is called only on the initial thread.

Comment (sdmaclea) [reply src/vm/threads.cpp]: It will only be used at startup.  I was thinking it needed a barrier on ARM systems to make sure the stack size was visible to all threads, but I am certain that thread create will already add a barrier.  I'll remove it.

**Comment by vitek-karas** [comment]
I'm curious about the property name: `OVERRIDE_DEFAULT_STACK_SIZE_4KPAGES` - why 4K pages? I think it would be cleaner to simple take number of bytes and decide on rounding (probably down?). I find it funny that we require the specified value to be 4K "aligned" and then convert it to bytes internally and use it everywhere like that. What happens if we run on OS which has larger pages?

I guess what I'm saying is, why not `OVERRIDE_DEFAULT_STACK_SIZE`.

File: src/vm/threads.cpp [hunk 2]
```diff
@@ -2144,6 +2144,30 @@ HANDLE Thread::CreateUtilityThread(Thread::StackSizeBucket stackSizeBucket, LPTH
...
+    {
+        LPWSTR end;
+        errno = 0;
+        unsigned long value = wcstoul(valueStr, &end, 10);
+
+        SIZE_T max4KPages = SIZE_T(1) << (31 - 12);
+
+        if ((errno == ERANGE) || (valueStr == end) || (end == nullptr) || (end[0] != 0) || (value >= max4KPages))
+        {
+            ThrowMessage("OVERRIDE_DEFAULT_STACK_SIZE_4KPAGES value parse error");
```
Comment (vitek-karas) [inline src/vm/threads.cpp]: I don't know much about exceptions in the runtime... so maybe this is correct, but I find it weird that `ThrowMessage` is not used anywhere else as far as I can tell. And also then there's this comment:
https://github.com/dotnet/coreclr/blob/e0fd735a866861b35679ac503193809a305fac2b/src/vm/exceptmacros.h#L481

Another consideration is the error message, I would think it should be localized (as in coming from resources somewhere?).

**Comment by sdmaclea** [comment]
> why 4K pages? 

It is arbitrary.  I started with bytes, then decided 4K was the absolute minimum stack size we could ever support, and a 4K granularity was the minimum that would ever make sense. I considered bytes, 4K, 64K, 1M.

I could switch it to bytes and set a minimum stack size. I would probably arbitrarily chose 64K.

File: src/vm/threads.cpp (hunk 2 above)
Comment (sdmaclea) [reply src/vm/threads.cpp]:
```
#define ThrowMessage        "Don't use this in the VM directory" 
```
That is a terrible worthless define.  It should be a static assert at least. Silently ignoring the error is just silly.  More technical debt...

I didn't expect this to be a user facing error. I think the message will get lost anyway.  It will likely become one of those E_FAIL startup errors that are so nice to debug....

Looks like this might have to become a `COMPlusThrowHR`...

**Comment by jkotas** [comment]
I think bytes would be better.

**Comment by jkotalik** [comment]
Similar to the UseEntryPoint feature, I think it makes sense to have an option to have an environment variable to set the stack size. It's significantly easier for a user to set it as it doesn't require using runtime properties. Thoughts?

File: src/vm/corhost.cpp [hunk 3]
```diff
@@ -742,6 +742,12 @@ HRESULT CorHost2::_CreateAppDomain(
             pwzAppNiPaths = pPropertyValues[i];
         }
         else
+        if (wcscmp(pPropertyNames[i], W("OVERRIDE_DEFAULT_STACK_SIZE")) == 0)
```
Comment (jkotas) [inline src/vm/corhost.cpp]: Nit: Make it just `DEFAULT_STACK_SIZE` ? `

**Comment by anurse** [comment]
It looks like (from the commit history) we have an environment variable 🎉. So just to confirm, the `COMPLUS_DEFAULT_STACK_SIZE` variable should be usable now to set the stack size?

**Comment by sdmaclea** [comment]
> COMPLUS_DEFAULT_STACK_SIZE variable should be usable now to set the stack size?

Yes.

**Comment by jkotas** [comment]
It should be `COMPlus_DefaultStackSize`, I think.

**Comment by janvorli** [comment]
> It should be `COMPlus_DefaultStackSize`, I think.

Right

**Comment by anurse** [comment]
Thanks!
