### PR TITLE
IsSupported returns false for not-fully-implemented ISA classes

### LINKED ISSUE #14930: IsSupported needs to return false for not-yet-implemented intrinsics
Repro:

```
using System;
using System.Runtime.Intrinsics.X86;

unsafe class My {

static void Main()
{
    Span<float> span1 = stackalloc float[4];
    span1[0] = 9.5f;
    span1[1] = 8.5f;
    span1[2] = 7.5f;
    span1[3] = 6.5f;

    if (Sse.IsSupported)
    {
        fixed (float* span1Ptr = &span1.DangerousGetPinnableReference())
        {
           var vector1 = Sse.Load(span1Ptr);
        }
    }
}

}
```

Actual result: Invalid program exception
Expected result: succeeds

It is very hard for folks to experiment with this otherwise. And we would have to do this before shipping .NET Core 2.1 for non-yet-implemented intrinsics anyway.

### PR DESCRIPTION
**Pull request by fiigii**
Resolve #14930

### CODE REVIEW

**Comment by fiigii** [comment]
@jkotas @CarolEidt @BruceForstall My current solution is to add a new environment variable `COMPlus_EnableIncompleteISAClass` to test partially implemented classes.

File: src/jit/hwintrinsicxarch.cpp [hunk 1]
```diff
@@ -204,8 +231,10 @@ GenTree* Compiler::impX86HWIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HA
     // Will throw PlatformNotSupportedException if
     // - calling hardware intrinsics on unsupported hardware
     // - calling SIMD hardware intrinsics with featureSIMD=false
-    if ((!compSupports(isa) || (!featureSIMD && isa != InstructionSet_BMI1 && isa != InstructionSet_BMI2 &&
-                                isa != InstructionSet_LZCNT && isa != InstructionSet_POPCNT)) &&
+    // - the ISA class is not yet fully implemented and EnableIncompleteISAClass=false
+    if ((!compSupports(isa) || (!JitConfig.EnableIncompleteISAClass() && !isFullyImplmentedISAClass(isa)) ||
```
Comment (CarolEidt) [inline src/jit/hwintrinsicxarch.cpp]: I think it would be cleaner to have this check look something like this:
```
if ((!compSupports(isa) || !compSupportsIntrinsics(isa)) && !isIntrinsicAnIsSupportedPropertyGetter(intrinsic))
```
Then, `compSupportsIntrinsics(isa)` can incorporate both the check for those that are fully supported, as well as, under `DEBUG` only, checking `JitConfig.EnableIncompleteISAClass()`.

File: src/jit/hwintrinsicxarch.cpp [hunk 2]
```diff
@@ -186,6 +186,33 @@ bool Compiler::isIntrinsicAnIsSupportedPropertyGetter(NamedIntrinsic intrinsic)
     }
 }
 
+// TODO - remove the fully implemented ISA
```
Comment (CarolEidt) [inline src/jit/hwintrinsicxarch.cpp]: I think that all these `TODO` comments should be omitted. I expect that it will take some time to complete the current set of ISAs, and there are likely to be more in future.

File: src/jit/hwintrinsicxarch.cpp (hunk 1 above)
Comment (fiigii) [reply src/jit/hwintrinsicxarch.cpp]: That would be more elegant. Will change.

**Comment by fiigii** [comment]
> I think the new config variable is a good approach, but would like to see it enabled only under DEBUG 

@CarolEidt I remember we talked this issue in that email thread. @jkotas mentioned that inconsistent behavior between release and debug build will make some test problem.
If the inconsistency is allowed, I think this new envirnoment variable would be unnecessary.
My original plan was disable incomplete classes in release and debug both, then add some new CI jobs with `COMPlus_EnableIncompleteLSAClass`.

**Comment by fiigii** [comment]
@jkotas @BruceForstall comments?

**Comment by jkotas** [comment]
Without any environment variable, the debug and release need to behave the same.

It is fine for the environment variable to be respected in debug build only. Debug and release can behave differently with environment variable set.

**Comment by fiigii** [comment]
> It is fine for the environment variable to be respected in debug build only. Debug and release can behave differently with environment variable set.

Got it, thank you!

**Comment by fiigii** [comment]
Moved `COMPlus_EnableIncompleteISAClass` under DEBUG and addressed feedback. @jkotas @CarolEidt PTAL.

File: src/jit/compiler.h [hunk 3]
```diff
@@ -3044,6 +3044,7 @@ class Compiler
     GenTree* impLZCNTIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HANDLE method, CORINFO_SIG_INFO* sig);
     GenTree* impPCLMULQDQIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HANDLE method, CORINFO_SIG_INFO* sig);
     GenTree* impPOPCNTIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HANDLE method, CORINFO_SIG_INFO* sig);
+    bool compSupportHWIntrinsic(InstructionSet isa);
```
Comment (CarolEidt) [inline src/jit/compiler.h]: This should be `compSupportsHWIntrinsic`

File: src/jit/hwintrinsicxarch.cpp [hunk 4]
```diff
@@ -324,7 +365,10 @@ GenTree* Compiler::impSSEIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HAND
     switch (intrinsic)
     {
         case NI_SSE_IsSupported:
-            retNode = gtNewIconNode(featureSIMD && compSupports(InstructionSet_SSE));
+            // TODO - remove "JitConfig.EnableIncompleteISAClass()" after fully implement hardware intrinsics of this
+            // class
+            retNode =
+                gtNewIconNode(JitConfig.EnableIncompleteISAClass() && featureSIMD && compSupports(InstructionSet_SSE));
```
Comment (CarolEidt) [inline src/jit/hwintrinsicxarch.cpp]: Isn't this test redundant with the one above? The check for `JitConfig.EnableIncompleteISAClass()` can only be done under `DEBUG`, but I believe that this check is redundant anyway, unless there's something I've missed.
Also, I still think these "TODO" comments are unnecessary, as I believe that we will need that facility for some time as new ISA feature sets are added and implemented over time.

Comment (fiigii) [reply src/jit/hwintrinsicxarch.cpp]: > Isn't this test redundant with the one above?

No, this check lets `IsSupported` return `false` for incomplete classes, but the above one lets intrinsics throw PNSE when the call site is not guarded by `IsSupported`.

> The check for JitConfig.EnableIncompleteISAClass() can only be done under DEBUG,

Oops, my mistake. Will fix.

File: src/jit/hwintrinsicxarch.cpp [hunk 5]
```diff
@@ -203,10 +246,8 @@ GenTree* Compiler::impX86HWIntrinsic(NamedIntrinsic intrinsic, CORINFO_METHOD_HA
     InstructionSet isa = isaOfHWIntrinsic(intrinsic);
     // Will throw PlatformNotSupportedException if
     // - calling hardware intrinsics on unsupported hardware
-    // - calling SIMD hardware intrinsics with featureSIMD=false
-    if ((!compSupports(isa) || (!featureSIMD && isa != InstructionSet_BMI1 && isa != InstructionSet_BMI2 &&
-                                isa != InstructionSet_LZCNT && isa != InstructionSet_POPCNT)) &&
-        !isIntrinsicAnIsSupportedPropertyGetter(intrinsic))
+    // - JIT does not support this hardware intrinsics (compSupportHWIntrinsic return false)
+    if ((!compSupports(isa) || !compSupportHWIntrinsic(isa)) && !isIntrinsicAnIsSupportedPropertyGetter(intrinsic))
```
Comment (CarolEidt) [inline src/jit/hwintrinsicxarch.cpp]: Could you extract the check for the specific ISA intrinsics at the beginning, e.g.
```
bool supported = (featureSIMD && compSupports(isa) && compSupportsHWIntrinsics(isa));
```
Then, the above check can be:
```
if (!supported && !isIntrinsicAnIsSupportedPropertyGetter(intrinsic))
```
and the checks below can be:
```
retNode = gtNewIconNode(supported);
```

Comment (fiigii) [reply src/jit/hwintrinsicxarch.cpp]: Good point, will do.

**Comment by fiigii** [comment]
Streamlined IsSupported code. @CarolEidt @jkotas PTAL

File: src/jit/hwintrinsicxarch.cpp [hunk 6]
```diff
@@ -186,6 +186,49 @@ bool Compiler::isIntrinsicAnIsSupportedPropertyGetter(NamedIntrinsic intrinsic)
     }
 }
 
+bool isFullyImplmentedISAClass(InstructionSet isa)
```
Comment (BruceForstall) [inline src/jit/hwintrinsicxarch.cpp]: This function needs a standard header comment

File: src/jit/hwintrinsicxarch.cpp [hunk 7]
```diff
@@ -186,6 +186,49 @@ bool Compiler::isIntrinsicAnIsSupportedPropertyGetter(NamedIntrinsic intrinsic)
...
+        case InstructionSet_LZCNT:
+        case InstructionSet_POPCNT:
+            return true;
+
+        default:
+            unreached();
+    }
+}
+
+// return true if
```
Comment (BruceForstall) [inline src/jit/hwintrinsicxarch.cpp]: Please use a standard header comment format

File: src/jit/hwintrinsicxarch.cpp (hunk 6 above)
Comment (BruceForstall) [reply src/jit/hwintrinsicxarch.cpp]: Also, please make this a (static) member of the Compiler class.

File: src/jit/hwintrinsicxarch.cpp [hunk 8]
```diff
@@ -186,6 +186,49 @@ bool Compiler::isIntrinsicAnIsSupportedPropertyGetter(NamedIntrinsic intrinsic)
...
+// - isa is a scalar ISA
+// - isa is a SIMD ISA and featureSIMD=true
+// - isa is fully implemented or EnableIncompleteISAClass=true
+bool Compiler::compSupportsHWIntrinsic(InstructionSet isa)
+{
+    return (featureSIMD || isa == InstructionSet_BMI1 || isa == InstructionSet_BMI2 || isa == InstructionSet_LZCNT ||
```
Comment (BruceForstall) [inline src/jit/hwintrinsicxarch.cpp]: Looks like you should add a:
```
bool Compiler::compIsScalarISA(InstructionSet isa)
{
  return (isa == InstructionSet_BMI1) || (isa == InstructionSet_BMI2) || (isa == InstructionSet_LZCNT) || (isa == InstructionSet_POPCNT);
}
```

Comment (fiigii) [reply src/jit/hwintrinsicxarch.cpp]: Thanks, will change.

**Comment by fiigii** [comment]
@BruceForstall addressed feedback. PTAL.

**Comment by danmosemsft** [comment]
FYI @eerhardt

**Comment by fiigii** [comment]
@dotnet-bot test Windows_NT x86 Checked Innerloop Build and Test

**Comment by fiigii** [comment]
@CarolEidt @BruceForstall ping?
