### PR TITLE
Fix VN for byrefx on x86.

### LINKED ISSUE #27279: Test failure : System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan
**Job:**
[coreclr-corefx : 20191017.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=391287)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/1d928d1c-439e-4f3c-90bb-5dc9ebadfa88/workitems/System.Runtime.CompilerServices.Unsafe.Tests/console

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0

**Note:**
This failure **repro** on our windows x86 machine.

**Log:**
```
C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Work\ecca1366-293c-42bd-bd59-6fa4019e510f\Exec>"C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.CompilerServices.Unsafe.Tests.runtimeconfig.json xunit.console.dll System.Runtime.CompilerServices.Unsafe.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.CompilerServices.Unsafe.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.CompilerServices.Unsafe.Tests (found 52 test cases)
  Starting:    System.Runtime.CompilerServices.Unsafe.Tests (parallel test collections = on, max threads = 2)
    System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs(631,0): at System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan()
  Finished:    System.Runtime.CompilerServices.Unsafe.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 108, Errors: 0, Failed: 1, Skipped: 0, Time: 18.384s
----- end Thu 10/17/2019 10:55:51.69 ----- exit code 1 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by sandreenko**
Fixes #27279.

Thanks @jkotas for the small repro, I have added it as [the first commit](https://github.com/dotnet/coreclr/pull/27702/commits/6672efdd97f79882ee352446b01ae377b5c21d6c).

[The second commit](https://github.com/dotnet/coreclr/pull/27702/commits/4c6b7bbfa2c792a7a0585be965a10569d05e736f) fixes the issues.

[The third commit](https://github.com/dotnet/coreclr/pull/27702/commits/2749ca315950baed754937cfc23ea40e1afad1e5) was my try to delete code duplication between `VNFor*Con` methods so we don't have issues like that in the future. However, I do not like that the template function has 3 arguments, so I will probably drop it unless somebody thinks that it is better than the current version or knows how to improve that.

The issue itself means that all byrefs value numbers were incorrect on x86, but it is not a regression (the bug existing in 2015) so I do not think it should be backported.

### CODE REVIEW

File: src/jit/valuenum.cpp [hunk 1]
```diff
@@ -1592,6 +1592,41 @@ ValueNumStore::Chunk* ValueNumStore::GetAllocChunk(var_types              typ,
...
+    {
+        Chunk*   chunk               = GetAllocChunk(varType, CEA_Const);
+        unsigned offsetWithinChunk   = chunk->AllocVN();
+        res                          = chunk->m_baseVN + offsetWithinChunk;
+        T* chunkDefs                 = reinterpret_cast<T*>(chunk->m_defs);
+        chunkDefs[offsetWithinChunk] = cnsVal;
+        numMap->Set(cnsVal, res);
+        return res;
+    }
+}
```
Comment (echesakovMSFT) [inline src/jit/valuenum.cpp]: You can define
```c++
template<typename T>
struct VnForConstHelper;

template<>
struct VnForConstHelper<INT32>
{
    VnForConstHelper(ValueNumStore& store): m_store(store) { }
    typedef NumMap IntToValueNumMap;
    NumMap* GetCnsMap() { return m_store.GetIntCnsMap(); }
    var_types GetVarType() { return TYP_INT; }
private:
  ValueNumStore& m_store;
};

template<>
struct VnForConstHelper<INT64>
{
// impl
};

template<>
struct VnForConstHelper<float>
{
// impl
};
```

and then use it as
```c++
template <typename T>
ValueNum ValueNumStore::VnForConst(T cnsVal)
{
    ValueNumStoreHelper<T> helper(*this);
    ValueNum res;
    if (helper.GetCnsMap()->Lookup(cnsVal, &res))
    {
        return res;
    }
    else
    {
        Chunk*   chunk               = GetAllocChunk(helper.GetVarType(), CEA_Const);
        unsigned offsetWithinChunk   = chunk->AllocVN();
// impl
```

File: src/jit/valuenum.h [hunk 2]
```diff
@@ -264,6 +264,9 @@ class ValueNumStore
     ValueNum VNForDoubleCon(double cnsVal);
     ValueNum VNForByrefCon(size_t byrefVal);
 
+    template <typename T, typename NumMap>
+    inline ValueNum VnForConst(T cnsVal, NumMap* numMap, var_types varType);
```
Comment (echesakovMSFT) [inline src/jit/valuenum.h]: Shall this function be private?

**Review by echesakov — APPROVED** [review]
I like the cleanup.

File: src/jit/valuenum.cpp [hunk 3]
```diff
@@ -1678,7 +1678,7 @@ ValueNum ValueNumStore::VNForByrefCon(size_t cnsVal)
         Chunk*   c                                             = GetAllocChunk(TYP_BYREF, CEA_Const);
         unsigned offsetWithinChunk                             = c->AllocVN();
         res                                                    = c->m_baseVN + offsetWithinChunk;
-        reinterpret_cast<INT64*>(c->m_defs)[offsetWithinChunk] = cnsVal;
+        reinterpret_cast<size_t*>(c->m_defs)[offsetWithinChunk] = cnsVal;
```
Comment (echesakovMSFT) [inline src/jit/valuenum.cpp]: I think this should be `target_size_t`?

Comment (echesakovMSFT) [reply src/jit/valuenum.cpp]: Can the original issue be repro-d on arm?

Comment (sandreenko) [reply src/jit/valuenum.cpp]: > Can the original issue be repro-d on arm?

I see no reason why it can't be repro on arm, I will try it today.

> I think this should be target_size_t?

When we cross-compile for arm32 on arm64 do we use 4byte pointers? If yes then the signature  needs to be changed to `VNForByrefCon(target_size_tcnsVal)`?

File: src/jit/valuenum.h (hunk 2 above)
Comment (sandreenko) [reply src/jit/valuenum.h]: Thanks, missed that.

File: src/jit/valuenum.cpp (hunk 3 above)
Comment (echesakovMSFT) [reply src/jit/valuenum.cpp]: Yes, the signature should also be changed to use target_size_t

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by sandreenko** [comment]
> Can the original issue be repro-d on arm?

I have confirmed that it reproduces on arm.

> Yes, the signature should also be changed to use target_size_t

I will open an issue and fix it in a separate PR (mostly because of testing that needs to be done for such a change).
