### PR TITLE
Use LclFld for full-width cpblk of different types

### LINKED ISSUE #21080: [x86/windows] Test failed:JIT_HardwareIntrinsics._General_Vector64_Vector64_ro_Vector64_ro_._General_Vector64_Vector64_ro_Vector64_ro_cmd
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitstress2/669/

**Failed test:**
JIT_HardwareIntrinsics._General_Vector64_Vector64_ro_Vector64_ro_._General_Vector64_Vector64_ro_Vector64_ro_cmd

**Log:**
```
JIT_HardwareIntrinsics._General_Vector64_Vector64_ro_Vector64_ro_._General_Vector64_Vector64_ro_Vector64_ro_cmd [FAIL]
        
        Assert failure(PID 1156 [0x00000484], Thread: 10024 [0x2728]): Assertion failed '(varDsc->lvIsParam && !varDsc->lvIsRegArg) || isPrespilledArg' in 'JIT.HardwareIntrinsics.General.VectorCreate__CreateDouble:RunBasicScenario():this' (IL size 37)
        
            File: d:\j\workspace\x86_checked_w---13785110\src\jit\compiler.hpp Line: 2122
            Image: D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
        
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\Reports\JIT.HardwareIntrinsics\General\Vector64\Vector64_ro\Vector64_ro.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Vector64_ro.exe 
        Beginning test case Create.Byte at 11/18/2018 8:42:20 AM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Beginning scenario: RunBasicScenario
        Beginning scenario: RunReflectionScenario
        
        Ending test case at 11/18/2018 8:42:23 AM
        Beginning test case Create.Double at 11/18/2018 8:42:23 AM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\General\Vector64\Vector64_ro\Vector64_ro.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---13785110\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(1019,0): at JIT_HardwareIntrinsics._General_Vector64_Vector64_ro_Vector64_ro_._General_Vector64_Vector64_ro_Vector64_ro_cmd()
```

### PR DESCRIPTION
**Pull request by CarolEidt**
This issue arose because the source tree was a struct with a single double field, and the destination was a struct with a single long field. Copy prop replaced the lclVar in the source, which was under a `IND(ADDR)` with a lclVar that was not address taken, although it was marked `GTF_DONT_CSE`. Replacing the src tree with a `GT_LCL_FLD` addresses this issue.

Fix #21080

### CODE REVIEW

**Comment by CarolEidt** [comment]
There are a number of diffs. Most are code size reductions due to eliminating a bunch of adds of zero. There are code size increases for the failing `JIT\HardwareIntrinsics` tests, as well as a small number of CSE changes.

**Comment by tannergooding** [comment]
Thanks @CarolEidt

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -10648,13 +10650,44 @@ GenTree* Compiler::fgMorphCopyBlock(GenTree* tree)
...
+                    curFieldSeq        = GetFieldSeqStore()->CreateSingleton(fieldHnd);
+                    var_types destType = lvaGetDesc(fieldLclNum)->lvType;
 
-                    src = gtNewOperNode(GT_ADD, TYP_BYREF, src,
-                                        new (this, GT_CNS_INT)
-                                            GenTreeIntCon(TYP_I_IMPL, lvaTable[fieldLclNum].lvFldOffset, curFieldSeq));
-
-                    src = gtNewIndir(lvaTable[fieldLclNum].TypeGet(), src);
+                    bool done = false;
+                    if (lvaGetDesc(fieldLclNum)->lvFldOffset == 0)
```
Comment (tannergooding) [inline src/jit/morph.cpp]: Just wondering, do we know why this wasn't showing on x64 (and was only showing on x86, Arm, and Arm64)?

**Comment by tannergooding** [comment]
Based on the tests being re-enabled, this should also resolve: https://github.com/dotnet/coreclr/issues/21064

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -10648,13 +10650,44 @@ GenTree* Compiler::fgMorphCopyBlock(GenTree* tree)
...
+                                srcLclVarTree->gtType                 = destType;
+                                srcLclVarTree->AsLclFld()->gtFieldSeq = curFieldSeq;
+                                src                                   = srcLclVarTree;
+                                done                                  = true;
+                            }
+                        }
+                    }
+                    else // if (lvaGetDesc(fieldLclNum)->lvFldOffset != 0)
+                    {
+                        src = gtNewOperNode(GT_ADD, TYP_BYREF, src,
```
Comment (tannergooding) [inline src/jit/morph.cpp]: Should we be setting `done` here?

Comment (tannergooding) [reply src/jit/morph.cpp]: ah, nevermind, I see where this is in the old code

**Comment by CarolEidt** [comment]
It now seems to be asserting on linux - bummer.

File: src/jit/morph.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/morph.cpp]: ... and now we know. It's still failing on arm64.

Comment (CarolEidt) [reply src/jit/morph.cpp]: The arm64 failure looks like a related but slightly different issue. For some reason in the double case the SIMD16 lclVar that's partially written in `ToVector128` is not marked as address-taken. I'd like to investigate further before deciding whether to incorporate a fix for that issue into this PR.

Comment (mikedn) [reply src/jit/morph.cpp]: > For some reason in the double case the SIMD16 lclVar that's partially written in ToVector128 is not marked as address-taken.

Address taken or not enregistered? I'm on the road now so I can't check easily but I'm pretty sure LocalAddressVisitor won't flag such a variable as address exposed. AFAIR it is expected that morph will convert such a tree to a LCL_FLD rather than keeping it as address taken. But then of course, we're talking about SIMD so it wouldn't be too surprising that a SIMD specific case was missed somewhere.

Comment (CarolEidt) [reply src/jit/morph.cpp]: The fundamental issue is that codegen expects it to *not* be enregistered, which in this context I would expect to have happened by marking it as address-taken. As you say, it seems to be related to the SIMD-ness - i.e. a SIMD store/assignment is not being treated in the same way as a primitive type.

However, it's Thanksgiving so I'll plan to investigate this more on Monday!

Comment (mikedn) [reply src/jit/morph.cpp]: @CarolEidt It looks like this is one of the cases we were discussing in the "remove GT_ASG" issue. Because `LCL_FLD` doesn't carry enough info about structs it cannot be used as the destination of a struct copy so instead we get a `BLK(ADDR(LCL_VAR))` tree. For such a tree, it is normal to not have the lclvar address-exposed, it's even normal for the `LCL_VAR` node to act as a SSA def.

This case also occurs when you're assigning to a part of a large, unpromotable struct, even on x64, and it works fine.

The actual problem might be somewhere in ARM64 lowering, the `LCL_VAR_ADDR` node that appears after rationalization might need to be contained so codegen doesn't actually try to obtain the address of the lclvar. But it's not:
```
N001 (  3,  2) [000017] -c----------        t17 =    LCL_VAR   struct(P) V11 loc1         
                                                  *    long   V11._00 (offs=0x00) -> V13 tmp1          $140
N002 (  1,  1) [000026] U------N----        t26 =    LCL_VAR_ADDR byref  V10 loc0         ud:2->3
                                                 /--*  t26    byref  
                                                 +--*  t17    struct 
N004 (  4,  4) [000018] nA----------              *  STORE_BLK(8) struct (copy) (Unroll)
```

**Comment by CarolEidt** [comment]
@tannergooding - I added a fix for #21064. Could you take another look?
Also, @dotnet/jit-contrib PTAL

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -10309,13 +10309,11 @@ GenTree* Compiler::fgMorphCopyBlock(GenTree* tree)
 
         JITDUMP(requiresCopyBlock ? " this requires a CopyBlock.\n" : " using field by field assignments.\n");
 
-        // Mark the dest/src structs as DoNotEnreg
-        // when they are not reg-sized non-field-addressed structs and we are using a CopyBlock
-        // or the struct is not promoted
+        // Mark the dest/src structs as DoNotEnreg when they are not being fully referenced.
```
Comment (tannergooding) [inline src/jit/morph.cpp]: Should this clarify that this also includes when the src/dest are not the same type (in some of these cases, the destination struct and register are the same size, and I would guess that implies the destination struct is fully referenced).

**Comment by tannergooding** [comment]
Mac failure is https://github.com/dotnet/coreclr/issues/21105

I've sent an e-mail requesting the dumps from the machine so I can try and investigate further.

**Comment by CarolEidt** [comment]
I was hoping for a review from someone on @dotnet/jit-contrib but it seems that this is needed for #21198, so I'm going to merge.
