### PR TITLE
Fix enregistered lclFld bug

### LINKED ISSUE #18408: Bad codegen + Assertion failed 'varDsc->lvIsParam'
Repro:

Compile with `/o+`:

```csharp
using System;
using System.Reflection;
using System.Threading;
using System.Runtime.CompilerServices;

class MetadataReader
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public Method GetMethod(MethodHandle handle)
    {
        throw null;
    }

}

struct Handle
{
    int _value;

    public MethodHandle ToMethodHandle(MetadataReader reader)
    {
        return new MethodHandle(this);
    }
}

static class MetadataReaderExtensions
{
    public static unsafe Handle AsHandle(this int token)
    {
        return *(Handle*)&token;
    }
}

struct MethodHandle
{
    internal int _value;

    [MethodImpl(MethodImplOptions.NoInlining)]
    internal MethodHandle(Handle value)
    {
        throw null;
    }

    public Method GetMethod(MetadataReader reader)
    {
        return reader.GetMethod(this);
    }
}

struct Method
{
    internal MetadataReader _reader;
    internal MethodHandle _handle;
    internal MethodAttributes _flags;

    public MethodAttributes Flags => _flags;
}

struct QMethodDefinition
{
    private QMethodDefinition(MetadataReader reader, int token)
    {
        _reader = reader;
        _handle = token;
    }

    public static QMethodDefinition FromObjectAndInt(MetadataReader reader, int token)
    {
        return new QMethodDefinition(reader, token);
    }

    public MetadataReader Reader { get { return _reader; } }
    public int Token { get { return _handle; } }

    public bool IsValid { get { return _reader == null; } }

    private readonly MetadataReader _reader;
    private readonly int _handle;

    public MetadataReader NativeFormatReader { get { return _reader; } }
    public MethodHandle NativeFormatHandle { get { return _handle.AsHandle().ToMethodHandle(NativeFormatReader); } }
}

class Test
{

    [MethodImpl(MethodImplOptions.NoInlining)]
    static object foo(QMethodDefinition methodHandle)
    {
        Method method = methodHandle.NativeFormatHandle.GetMethod(methodHandle.NativeFormatReader);

        return (method.Flags != (MethodAttributes)0) ? new object() : null;
    }

    static void Main()
    {
        foo(default(QMethodDefinition));
    }
}
```

Result:

On debug/checked Windows x64 build, this fails with:

```

Assert failure(PID 26504 [0x00006788], Thread: 8952 [0x22f8]): Assertion failed 'varDsc->lvIsParam' in 'QMethodDefinition:get_NativeFormatHandle():struct:this' (IL size 26)

    File: c:\coreclr\src\jit\compiler.hpp Line: 2321
```

### PR DESCRIPTION
**Pull request by CarolEidt**
In `impFixupStructReturnType()`, don't transform to `GT_LCL_FLD` if we have a scalar lclVar.
Also, to avoid future bad codegen, add verification and recovery code to Lowering.

Fix #18408

### CODE REVIEW

**Comment by CarolEidt** [comment]
The reason this was not encountered previously is that, prior to #17996, the `IND(ADDR)` wasn't folded away due to a cast.

**Comment by CarolEidt** [comment]
> Is this something we could catch earlier with some kind of IR check?

Possibly; I thought it best to add a check just prior to where it matters - i.e. in `Lowering`. However, apparently this has caused a failure in one of the HW intrinsics tests. Working now on trying to repro.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -1386,6 +1389,105 @@ bool LinearScan::isRegCandidate(LclVarDsc* varDsc)
     {
         return false;
     }
+
+    // Don't enregister if the ref count is zero.
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: This section of code, and the above check for `!enregisterLocalVars` were extracted from `identifyCandidates()` so that `isRegCandidate` can be called from the assert in `Lowering`.

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -8654,7 +8654,12 @@ GenTree* Compiler::impFixupStructReturnType(GenTree* op, CORINFO_CLASS_HANDLE re
     // and no normalizing
     if (op->gtOper == GT_LCL_VAR)
     {
-        op->ChangeOper(GT_LCL_FLD);
+        // It is possible that we now have a lclVar of scalar type.
+        // If so, don't transform it to GT_LCL_FLD.
+        if (varTypeIsStruct(lvaTable[op->AsLclVarCommon()->gtLclNum].lvType))
```
Comment (mikedn) [inline src/jit/importer.cpp]: Could be `AsLclVar` but I guess it doesn't really matter.

File: src/jit/lower.h [hunk 3]
```diff
@@ -355,6 +355,23 @@ class Lowering : public Phase
         return LIR::AsRange(m_block);
     }
 
+    // Any tracked lclVar accessed by a LCL_FLD or STORE_LCL_FLD should be marked doNotEnregister.
+    // This method checks, and asserts in the DEBUG case if it is not so marked,
+    // but in the non-DEBUG case (asserts disabled) set the flag so that we don't generate bad code.
+    // Thie ensures that the local's value is valid on-stack as expected for a *LCL_FLD.
```
Comment (mikedn) [inline src/jit/lower.h]: This

File: src/jit/importer.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: Yes, I think I'm programmed to use `AsLclVarCommon`

File: src/jit/lower.h (hunk 3 above)
Comment (CarolEidt) [reply src/jit/lower.h]: Thanks will fix

File: src/jit/lsra.cpp [hunk 4]
```diff
@@ -1386,6 +1389,105 @@ bool LinearScan::isRegCandidate(LclVarDsc* varDsc)
...
+    {
+        return false;
+    }
+
+    switch (genActualType(varDsc->TypeGet()))
+    {
+#if CPU_HAS_FP_SUPPORT
+        case TYP_FLOAT:
+        case TYP_DOUBLE:
+            if (compiler->opts.compDbgCode)
```
Comment (mikedn) [inline src/jit/lsra.cpp]: I think the whole switch would be more readable if this and other similar cases below are changed to `return !compiler->opts.compDbgCode;`.

File: src/jit/lsra.cpp [hunk 5]
```diff
@@ -1386,6 +1389,105 @@ bool LinearScan::isRegCandidate(LclVarDsc* varDsc)
...
+        // TODO-1stClassStructs: Move TYP_SIMD8 up with the other SIMD types, after handling the param issue
+        // (passing & returning as TYP_LONG).
+        case TYP_SIMD8:
+#endif // FEATURE_SIMD
+
+        case TYP_STRUCT:
+        {
+            return false;
+        }
+        break;
```
Comment (mikedn) [inline src/jit/lsra.cpp]: Braces and break not necessary.
