### PR TITLE
Ensure BuildUse uses the correct reg number

### LINKED ISSUE #18153: Assertion failed 'farthestRefPhysRegRecord != nullptr' /dotnet/coreclr/src/jit/lsra.cpp:3637
I'm using the x86 version of the CoreCLR to run CoreRT and compile tests for ARM.

After the commit:
> b39a5b2cfad4620ae23cda84186a36ffb463cd5a 

compilation fails (for all tests) with message

> cd /overlay.arm.Debug && ./corerun ilc.dll --codegenopt "AltJitNgen=*" @/overlay.arm.Debug/pow3/base.ilc.rsp
/dotnet/coreclr/src/jit/lsra.cpp:3637
Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'Sys:DoubleToString(double,int,int,int):int' (IL size 14)

The folder /overlay.arm.Debug/ contains necessary parts from CoreRT, CoreCLR and CoreFX to 
cross-compile IL binary to native ARM code.  I've followed the following guide: [https://github.com/dotnet/corert/blob/master/Documentation/cross-building.md](url)
The `@/overlay.arm.Debug/pow3/base.ilc.rsp` is dependency file, generated by the `msbuild`. 
The pow3 test is one of the CoreCRL's tests for CoreRT. The tests are downloaded by `/dotnet/corert/tests/runtest.sh`  script and could be run by the following command `./tests/runtest.sh -coreclr all`

I've checked with the following versions of the CoreCRL, CoreRT and CoreFX:

CoreCLR: 6bf04a47badd74646e21e70f4e9267c71b7bfd08
CoreFX: ccdb5a48a49d3e932aa00d02749777464f4c8d5b
CoreRT: a028615abe80057e413d632a7c9257208b7c6865

### PR DESCRIPTION
**Pull request by CarolEidt**
`BuildUse` was setting the regNumber for all of the uses of a multi-reg  node to the main/first regNum. This was missed because this results in a def/use conflict on that reg (the def was set correctly), which is generally resolved in favor of the def. The exception is when there is a kill of the register in between, in which case the use tries to allocate the register its been assigned, causing the `farthestRefPhysRegRecord != nullptr` assert (aka "a register can't be found to spill").
This fixes the specific issue, and adds additional asserts to identify future/additional such issues.
The new asserts depend upon all the regNums being appropriately when/if any are set, which wasn't always the case prior to register allocation.

Fix #18153

### CODE REVIEW

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -1055,13 +1055,17 @@ GenTree* Lowering::NewPutArg(GenTreeCall* call, GenTree* arg, fgArgTabEntry* inf
...
             GenTreePutArgSplit(arg, info->slotNum PUT_STRUCT_ARG_STK_ONLY_ARG(info->numSlots), info->numRegs,
                                call->IsFastTailCall(), call);
-        putArg->gtRegNum = info->regNum;
 
         // If struct argument is morphed to GT_FIELD_LIST node(s),
         // we can know GC info by type of each GT_FIELD_LIST node.
         // So we skip setting GC Pointer info.
         //
         GenTreePutArgSplit* argSplit = putArg->AsPutArgSplit();
+        for (int regIndex = 0; regIndex < (int)info->numRegs; regIndex++)
```
Comment (mikedn) [inline src/jit/lower.cpp]: Why not `unsigned`?

Comment (CarolEidt) [reply src/jit/lower.cpp]: No good reason; changed.

File: src/jit/lsrabuild.cpp [hunk 2]
```diff
@@ -2501,7 +2506,11 @@ RefPosition* LinearScan::BuildUse(GenTree* operand, regMaskTP candidates, int mu
     Interval* interval;
     bool      regOptional = operand->IsRegOptional();
 
-    if (operand->gtRegNum != REG_NA)
+    if (candidates != RBM_NONE)
+    {
+        assert((operand->gtRegNum == REG_NA) || (candidates == genRegMask(operand->GetRegByIndex(multiRegIdx))));
```
Comment (CarolEidt) [inline src/jit/lsrabuild.cpp]: This assert is too strong, because there is no guarantee that the register required for a target is the same as the register required by the consumer. That said, this assert fired because `fgMorphTailCall()` puts `REG_R11` on the node that is created by `Compiler::fgGetStubAddrArg()`, but in `Lowering` the `PUTARG_REG` for this node puts the value in `REG_R8`. I'm not sure if this is what is supposed to be happening. @jashook - can you comment on this? This results in the following in codegen:
```
Generating: N071 (  3, 10) [000028] ------------        t28 =    CNS_INT(h) long   0x7ffa8aa20020 ftn REG r11 $c2
IN0010:        mov      r11, 0x7FFA8AA20020
                                                             /--*  t28    long   
Generating: N073 (???,???) [000063] ------------        t63 = *  PUTARG_REG long   REG r8
IN0011:        mov      r8, r11
```

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
I had originally added an overly-aggressive assert that the "use" candidates were the same as the `gtRegNum` on the node, but that is clearly not right, because the use may have different requirements than the def. But the assert *can* be added on the def side, and should provide additional value, though the assert that would have caught this case is the one that asserts that we don't have two `RefTypeFixedReg` `RefPositions` at the same location.

File: src/jit/gentree.h [hunk 3]
```diff
@@ -6006,6 +6009,45 @@ inline bool GenTree::IsMultiRegNode() const
...
+    {
+        return AsCall()->GetRegNumByIdx(regIndex);
+    }
+
+#if defined(_TARGET_ARM_)
+    if (OperIsMultiRegOp())
+    {
+        return AsMultiRegOp()->GetRegNumByIdx(regIndex);
+    }
+    else if (OperIsPutArgSplit())
```
Comment (jashook) [inline src/jit/gentree.h]: OperIsPutArgSplit  could return true for Arm64 Windows native varargs.

File: src/jit/gentree.h [hunk 4]
```diff
@@ -6030,16 +6030,18 @@ inline regNumber GenTree::GetRegByIndex(int regIndex)
         return AsCall()->GetRegNumByIdx(regIndex);
     }
 
+#if defined(_TARGET_ARMARCH_)
```
Comment (jashook) [inline src/jit/gentree.h]: As ugly as this sounds, I believe this should change to #if defined(_TARGET_ARM_) || (defined(_TARGET_ARM64_) && defined(_TARGET_WINDOWS_)).

Just defining _TARGET_ARMARCH_ I blieve will cause errors on arm64 unix :(, because AsPutArgSplit will most likely be undefined.

Comment (CarolEidt) [reply src/jit/gentree.h]: Right - I think it could be `FEATURE_ARG_SPLIT`.

Comment (jashook) [reply src/jit/gentree.h]: Yes, forgot about that. Thank you, much much nicer.

**Comment by CarolEidt** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
