### PR TITLE
JIT: rework codegen for Arm64 SIMD Extract/Insert intrinsics

### LINKED ISSUE #20260: [Linux/arm64] Assert failures during PMI System.Private.CoreLib
```
PREPALL type# 474 method# 8112 System.Numerics.Vector`1[[System.Numerics.Vector`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::ToString

Assert failure(PID 14239 [0x0000379f], Thread: 14239 [0x379f]): Assertion failed 'type == lvaTable[lnum].lvType || (lvaIsImplicitByRefLocal(lnum) && fgGlobalMorph && (lvaTable[lnum].lvType == TYP_BYREF))' in 'System.Numerics.Vector`1[Vector`1][System.Numerics.Vector`1[System.Single]]:ToString(ref,ref):ref:this' (IL size 146)

    File: /opt/code/src/jit/gentree.cpp Line: 6252
    Image: /home/robox/echesako/git/_/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun
```
The assert above fixed by #20285

```
PREPALL type# 1743 method# 22166 System.Runtime.Intrinsics.Arm.Arm64.Base::LeadingSignCount

Assert failure(PID 14246 [0x000037a6], Thread: 14246 [0x37a6]): Assertion failed '!"Unimplemented SIMD Intrinsic form"' in 'System.Runtime.Intrinsics.Arm.Arm64.Base:LeadingSignCount(int):int' (IL size 7)

    File: /opt/code/src/jit/hwintrinsicArm64.cpp Line: 324
    Image: /home/robox/echesako/git/_/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun
```

```
PREPALL type# 1743 method# 22168 System.Runtime.Intrinsics.Arm.Arm64.Base::LeadingZeroCount

Assert failure(PID 14254 [0x000037ae], Thread: 14254 [0x37ae]): Assertion failed '!"Unimplemented SIMD Intrinsic form"' in 'System.Runtime.Intrinsics.Arm.Arm64.Base:LeadingZeroCount(int):int' (IL size 7)

    File: /opt/code/src/jit/hwintrinsicArm64.cpp Line: 324
    Image: /home/robox/echesako/git/_/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun
```
The two assertions above fixed by #20306
```
PREPALL type# 1746 method# 22324 System.Runtime.Intrinsics.Arm.Arm64.Simd::Extract

Assert failure(PID 14268 [0x000037bc], Thread: 14268 [0x37bc]): Compiler optimization assumption invalid: ERROR: failed to find exception throw blockFAILED: (add != nullptr)
    File: /opt/code/src/jit/codegencommon.cpp Line: 2005
    Image:
```

**Steps to reproduce:**
1. Set these environement variables
```
COMPlus_TieredCompilation=0
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0
```
2. Run PMI DriveAll (needs https://github.com/dotnet/jitutils)
`$CORE_ROOT/corerun pmi.dll DRIVEALL $CORE_ROOT/System.Private.CoreLib.dll`

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Add an up-front bounds check during importation instead of waiting
until codegen. Mirrors what we do for similar cases on xarch.

Closes #20260.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@CarolEidt @tannergooding PTAL
cc @dotnet/jit-contrib 

```asm
; Assembly listing for method System.Runtime.Intrinsics.Arm.Arm64.Simd:Extract(struct,ubyte):long
; Emitting BLENDED_CODE for generic ARM64 CPU - Unix
; optimized code
; fp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  3,  3   )  simd16  ->  d16
;  V01 arg1         [V01,T01] (  3,  3   )   ubyte  ->   x2
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [sp+0x00]   "OutgoingArgSpace"
;  V03 cse0         [V03,T02] (  3,  3   )     int  ->   x0         "ValNumCSE"
;
; Lcl frame size = 0

G_M46294_IG01:
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
        4E081C10          mov     v16.d[0], x0
        4E181C30          mov     v16.d[1], x1

G_M46294_IG02:
        53001C40          uxtb    w0, w2
        52800041          mov     w1, #2
        6B01001F          cmp     w0, w1
        54000142          bhs     G_M46294_IG05
        10000061          adr     x1, [G_M46294_IG03]
        8B000C21          add     x1, x1, x0, LSL #3
        D61F0020          br      x1

G_M46294_IG03:
        4E083E00          umov    x0, v16.d[0]
        14000003          b       G_M46294_IG04
        4E183E00          umov    x0, v16.d[1]
        14000001          b       G_M46294_IG04

G_M46294_IG04:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr

G_M46294_IG05:
        97F03F69          bl      CORINFO_HELP_THROW_ARGUMENTOUTOFRANGEEXCEPTION
        D43E0000          bkpt

; Total bytes of code 76, prolog size 8 for method System.Runtime.Intrinsics.Arm.Arm64.Simd:Extract(struct,ubyte):long
```

**Comment by AndyAyersMS** [comment]
With this, I can now run SPC through PMI on arm64 linux....
```
~/repos/coreclr$ bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun ~/repos/jitutils/bin/pmi.dll prepall-quiet bin/tests/Linux.arm64.Checked/Tests/Core_Root/System.Private.CoreLib.dll

TypeLoadException System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::get_Item
TypeLoadException System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::get_Item
TypeLoadException System.ReadOnlySpan`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::GetPinnableReference
TypeLoadException System.ReadOnlySpan`1+Enumerator[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::get_Current
DllNotFoundException System.Runtime.Loader.AssemblyDependencyResolver::corehost_resolve_component_dependencies (Unable to load shared library 'hostpolicy' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhostpolicy: cannot open shared object file: No such file or directory)
DllNotFoundException System.Runtime.Loader.AssemblyDependencyResolver::corehost_set_error_writer (Unable to load shared library 'hostpolicy' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhostpolicy: cannot open shared object file: No such file or directory)

Completed assembly System.Private.CoreLib - #types: 2159, #methods: 26917, skipped types: 23, skipped methods: 435
```
Not sure yet what's behind those type load exceptions, but they are not jit issues.

File: src/jit/hwintrinsicArm64.cpp [hunk 1]
```diff
@@ -195,6 +187,46 @@ bool HWIntrinsicInfo::isScalarIsa(InstructionSet isa)
...
+// addRangeCheckIfNeeded: add a GT_HW_INTRINSIC_CHK node for non-full-range imm-intrinsic
+//
+// Arguments:
+//    immOp      -- the operand of the intrinsic that points to the imm-arg
+//    max        -- maximum allowable value for the immOp
+//    mustExpand -- true if the compiler is compiling the fallback(GT_CALL) of this intrinsics
+//
+// Return Value:
+//     if necessary, add a GT_HW_INTRINSIC_CHK node which throws an ArgumentOutOfRangeException
+//     when the immOp is not in the valid range
```
Comment (CarolEidt) [inline src/jit/hwintrinsicArm64.cpp]: I would add ", otherwise, returns the provided immOp"

**Comment by AndyAyersMS** [comment]
8 bit extracts are potentially more interesting here...  maybe I should officially extend PMI to try instantiating with short int types.
```
G_M11437_IG02:
        53001C40          uxtb    w0, w2
        52800201          mov     w1, #16
        6B01001F          cmp     w0, w1
        540004C2          bhs     G_M11437_IG05
        10000061          adr     x1, [G_M11437_IG03]
        8B000C21          add     x1, x1, x0, LSL #3
        D61F0020          br      x1

G_M11437_IG03:
        0E013E00          umov    w0, v16.b[0]
        1400001F          b       G_M11437_IG04
        0E033E00          umov    w0, v16.b[1]
        1400001D          b       G_M11437_IG04
        0E053E00          umov    w0, v16.b[2]
        1400001B          b       G_M11437_IG04
        0E073E00          umov    w0, v16.b[3]
        14000019          b       G_M11437_IG04
        ...
```

File: src/jit/compiler.h [hunk 2]
```diff
@@ -3510,7 +3510,7 @@ class Compiler
 #ifdef _TARGET_ARM64_
     InstructionSet lookupHWIntrinsicISA(const char* className);
     NamedIntrinsic lookupHWIntrinsic(const char* className, const char* methodName);
-    bool impCheckImmediate(GenTree* immediateOp, unsigned int max);
+    GenTree* addRangeCheckIfNeeded(GenTree* lastOp, unsigned int max, bool mustExpand);
```
Comment (CarolEidt) [inline src/jit/compiler.h]: Once the Arm64 intrinsics are also table-driven (I *think* there's an issue for that?) it would make sense to just declare and implement this once.

**Comment by AndyAyersMS** [comment]
Windows Arm64 jenkins hangup:
```
16:29:55 FATAL: command execution failed
16:29:55 java.nio.channels.ClosedChannelException
16:29:55 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
```
Am about to push another commit to address feedback so will let that trigger retest.

File: src/jit/compiler.h (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/compiler.h]: It is not quite the same signature as in the x64 version (didn't need to be quite as flexible). They could converge, I think.

File: src/jit/hwintrinsicArm64.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/hwintrinsicArm64.cpp]: Sure.

**Comment by AndyAyersMS** [comment]
Opened #23136 for the pmi issue I saw on arm64.
