### PR TITLE
[RyuJIT/ARM32] Unassign double register properly

### LINKED ISSUE #12615: [RyuJIT/ARM32] Assertion failed 'genIsValidDoubleReg(regRec->regNum)'
Following assertion is observed in 18 tests while compiling with ryujit/arm32.

```
               Assert failure(PID 1038 [0x0000040e], Thread: 1038 [0x040e]): Assertion failed 'genIsValidDoubleReg(regRec->regNum)' in 'HFATest.TestCase:Main():int' (IL size 2894)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 6420
```

Related tests:
```
JIT/jit64/hfa/main/testA/hfa_nd0A_d/hfa_nd0A_d.sh
JIT/jit64/hfa/main/testA/hfa_nd0A_r/hfa_nd0A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd1A_d/hfa_nd1A_d.sh
JIT/jit64/hfa/main/testA/hfa_nd1A_r/hfa_nd1A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd2A_d/hfa_nd2A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd0A_d/hfa_sd0A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd0A_r/hfa_sd0A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd1A_d/hfa_sd1A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd1A_r/hfa_sd1A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd2A_d/hfa_sd2A_d.sh
JIT/jit64/hfa/main/testB/hfa_nd0B_d/hfa_nd0B_d.sh
JIT/jit64/hfa/main/testB/hfa_nd0B_r/hfa_nd0B_r.sh
JIT/jit64/hfa/main/testB/hfa_sd0B_d/hfa_sd0B_d.sh
JIT/jit64/hfa/main/testB/hfa_sd0B_r/hfa_sd0B_r.sh
JIT/jit64/hfa/main/testG/hfa_nd0G_r/hfa_nd0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd1G_r/hfa_nd1G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_r/hfa_sd2G_r.sh
```

### PR DESCRIPTION
**Pull request by hqueue**
Fix #12615 
In LinearScan::tryAllocateFreeReg(), unassign a double register properly
when a found float register is a part of a double register.

After applying this PR, all assertions of RA phase reported at #12615 are resolved and blocked by  another assertions which can be fixed by #12621.

With this PR and PR #12621, 15 tests from issue #12615 is passed.
Remaining 3 tests are blocked by other known issues.

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by hqueue** [comment]
@dotnet-bot please test Windows_NT x64 Debug Build and Test

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -5750,7 +5750,17 @@ regNumber LinearScan::tryAllocateFreeReg(Interval* currentInterval, RefPosition*
     {
         if (intervalToUnassign != nullptr)
         {
+#ifdef _TARGET_ARM_
+            RegRecord* unassignedPhysReg = availablePhysRegInterval;
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: I would suggest that you name this `physRegToUnassign` since at this point it has not yet actually been unassigned. Also, if you move this out of the `#ifdef`, the code at line 5762 can be moved out of the `#ifdef` and the code at line 5776 will not require an `#ifdef` at all.

Comment (hqueue) [inline src/jit/lsra.cpp]: Sure. I've update this PR.
