### PR TITLE
RyuJIT/x86: implement tailcall via helper

### LINKED ISSUE #4185: RyuJIT x86: NYI_X86: "Tail call morphing"
This NYI:

NYI_X86: "Tail call morphing"
File: coreclr\src\jit\morph.cpp Line: 5892

Is hit by these tests:

JIT\Directed\IL\Tailcall\JitTailcall2\JitTailcall2.cmd
JIT\Methodical\VT\callconv\_il_dbgjumps4\_il_dbgjumps4.cmd
JIT\Methodical\tailcall\_il_dbgtest_mutual_rec\_il_dbgtest_mutual_rec.cmd
JIT\Methodical\tailcall\_il_reldeep_virt\_il_reldeep_virt.cmd
JIT\Methodical\tailcall\_il_dbgtest_2b\_il_dbgtest_2b.cmd
JIT\Directed\IL\PInvokeTail\TailWinApi\TailWinApi.cmd
JIT\Methodical\nonvirtualcall\tailcall_d\tailcall_d.cmd
JIT\Methodical\VT\callconv\_il_dbgjumps3\_il_dbgjumps3.cmd
JIT\Methodical\tailcall\_il_relcompat_obj\_il_relcompat_obj.cmd
JIT\Regression\VS-ia64-JIT\V1.2-M02\b17904\b17904\b17904.cmd

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #4185

### CODE REVIEW

**Comment by BruceForstall** [comment]
@sivarv @adiaaida PTAL
cc @dotnet/jit-contrib

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -6747,12 +6797,46 @@ void                Compiler::fgMorphTailCall(GenTreeCall* call)
     arg = gtNewIconHandleNode(ssize_t(pfnCopyArgs), GTF_ICON_FTN_ADDR);
     call->gtCallArgs = gtNewListNode(arg, call->gtCallArgs);
 
+#else // !_TARGET_AMD64_
+
+    // Find the end of the argument list
+    GenTreeArgList** ppArg = &call->gtCallArgs;
+    for (GenTreeArgList* args = call->gtCallArgs; args != nullptr; ppArg = (GenTreeArgList**)&args->gtOp2, args = args->Rest())
```
Comment (mikedn) [inline src/jit/morph.cpp]: Seems like `ppArg = (GenTreeArgList**)&args->gtOp2` could go in the `for` body.

**Comment by sivarv** [comment]
There are few differences between x86 vs amd64 in honoring .tail prefixed calls.  For e.g. if the method requires GS cookie check, then amd64 ignores tail prefix - see fgMorphCall().  You might want to check whether it is the case on x86.  If not we don't have codegenxarch support for emitting GS Cookie check just before the tail call.  Perhaps there could be other differences.  A place to look for those differences is impImportCall() and fgMorphCall().

**Comment by sivarv** [comment]
I would suggest to do a jitstress=2 and tail call stress run for testing these changes.

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -1892,26 +1909,100 @@ GenTree* Lowering::LowerTailCallViaHelper(GenTreeCall* call, GenTree *callTarget
...
     // Now add back tail call flags for identifying this node as tail call dispatched via helper.
-    call->gtFlags |= GTF_CALL_M_TAILCALL | GTF_CALL_M_TAILCALL_VIA_HELPER;
+    call->gtCallMoreFlags |= GTF_CALL_M_TAILCALL | GTF_CALL_M_TAILCALL_VIA_HELPER;
 
     // Insert profiler tail call hook if needed.
     // Since we don't know the insertion point, pass null for second param.
-    if(comp->compIsProfilerHookNeeded())
+    if (comp->compIsProfilerHookNeeded())
     {
         InsertProfTailCallHook(call, nullptr);
```
Comment (sivarv) [inline src/jit/lower.cpp]: I think InsertProfTailCallHook() is amd64 centric and needs to be examined to see whether it will work for x86.  Either we need to add a NYI or run profiler tests on desktop to verify that this functionality works as expected.

**Comment by sivarv** [comment]
Looks good.

File: src/jit/morph.cpp (hunk 1 above)
Comment (BruceForstall) [inline src/jit/morph.cpp]: Yeah, that might make it easier to read. Done.

File: src/jit/lower.cpp [hunk 3]
```diff
@@ -1892,26 +1909,100 @@ GenTree* Lowering::LowerTailCallViaHelper(GenTreeCall* call, GenTree *callTarget
...
+    GenTree* arg2 = argEntry->node->gtOp.gtOp1;
+    assert(arg2->gtOper == GT_CNS_INT);
+
+    arg2->gtIntCon.gtIconVal = nNewStkArgs;
+
+#ifdef DEBUG
+    // arg 3 == numberOfOldStackArgs
+    argEntry = comp->gtArgEntryByArgNum(call, numArgs - 4);
+    assert(argEntry != nullptr);
+    assert(argEntry->node->gtOper == GT_PUTARG_STK);
```
Comment (adiaaida) [inline src/jit/lower.cpp]: It looks like we're hitting his assert in the lab in a bunch of different tests

Comment (BruceForstall) [inline src/jit/lower.cpp]: Yep, there are some asserts I need to work through.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstress1

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib I updated this PR with a few fixes so all the tests pass, plus a little cleanup of non-standard args in fgMorphArgs (I was planning to extend it, but ended up not doing so, hence it's just cleanup). Anyone want to take another look?
