### PR TITLE
Disable marshalling delegates as _Delegate and enable marshalling delegates as IDispatch.

### LINKED ISSUE #23730: PInvoke Delegate AsInterface tests failing on master
Looks like the PInvoke tests for marshalling a delegate as an interface just started failing on master as of build 20190404.73.

See https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190404.73/workItem/Interop.PInvoke/analysis/xunit/Interop_PInvoke._Delegate_MarshalDelegateAsField_AsInterface_AsInterfaceTest_AsInterfaceTest_~2F_Delegate_MarshalDelegateAsField_AsInterface_AsInterfaceTest_AsInterfaceTest_cmd

I'll take a look.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
As part of the transition to .NET Core, we dropped the concept of the mscorlib tlb interfaces. However, in the marshalling space we continued to imply that their usage was safe, particularly with delegates. In .NET Framework, it is possible to marshal a delegate as a COM object implementing the `_Delegate` interface provided by the `mscorlib.tlb` type library. Since we did not make many significant changes to the `System.Delegate` type in .NET Core, this behavior continued to work in .NET Core. However, when the `System.Delegate` type was moved to the shared partition in #23552, the change to the compiled type's surface was large enough to change how the dispid's were assigned, breaking the marshalling to the Framework `_Delegate` interface and resulting in bad runtime errors (crashes, incorrect return values depending on exactly how the interface pointer is generated).

We've decided that since the `_Delegate` COM interface is a .NET Framework type, that we are not going to try to add back support to marshalling to it. Instead, we are changing behavior as follows:

- Using `[MarshalAs(UnmanagedType.Interface)]` on a delegate-typed field, parameter, or return value is illegal.
- Using the default marshallling for delegates on parameters or return values in non-WinRT COM methods is illegal since it implies `[MarshalAs(UnmanagedType.Interface)]`.
- Using `[MarshalAs(UnmanagedType.IDispatch)]` on a delegate-typed field, parameter or return value is now legal and is the suggested change for consumers. Additionally, these consumers will have to change their native code to take an `IDispatch` pointer and operate on the delegate's COM wrapper via the `IDispatch` interface instead of the `_Delegate` interface.

Fixes #23730.

### CODE REVIEW

File: src/vm/fieldmarshaler.cpp [hunk 1]
```diff
@@ -590,11 +590,18 @@ do                                                      \
                 }
                 else
                 {
-                    ItfMarshalInfo itfInfo;
-                    if (FAILED(MarshalInfo::TryGetItfMarshalInfo(thNestedType, FALSE, FALSE, &itfInfo)))
-                        break;
-
-                    INITFIELDMARSHALER(NFT_INTERFACE, FieldMarshaler_Interface, (itfInfo.thClass.GetMethodTable(), itfInfo.thItf.GetMethodTable(), itfInfo.dwFlags));
+                    if (COMDelegate::IsDelegate(thNestedType.GetMethodTable()))
```
Comment (AaronRobinsonMSFT) [inline src/vm/fieldmarshaler.cpp]: Fold this into the `else` branch above?
