### PR TITLE
[arm64] Fix GitHub 20211 Issue

### LINKED ISSUE #20211: [Linux/arm64] System.Numerics.Tests.GenericVectorTests.SquareRootSByte Failure
**JitStress=2**

```
/home/robox/echesako/git/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Numerics.Vectors.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26927.0)
  Discovering: System.Numerics.Vectors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Vectors.Tests (found 1150 test cases)
  Starting:    System.Numerics.Vectors.Tests (parallel test collections = on, max threads = 46)
    System.Numerics.Tests.GenericVectorTests.SquareRootSByte [FAIL]
      AssertEqual failed for operation SquareRoot( -117 ). Expected: 0, Actual: 11.
      Stack Trace:
        /opt/code/_/fx/src/System.Numerics.Vectors/tests/GenericVectorTests.cs(2634,0): at System.Numerics.Tests.GenericVectorTests.AssertEqual[T](T expected, T actual, String operation, Int32 precision)
        /opt/code/_/fx/src/System.Numerics.Vectors/tests/GenericVectorTests.cs(1913,0): at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass533_0`1.<TestSquareRoot>b__0(Int32 index, T val)
        /opt/code/_/fx/src/System.Numerics.Vectors/tests/GenericVectorTests.cs(2696,0): at System.Numerics.Tests.GenericVectorTests.ValidateVector[T](Vector`1 vector, Action`2 indexValidationFunc)
        /opt/code/_/fx/src/System.Numerics.Vectors/tests/GenericVectorTests.cs(1886,0): at System.Numerics.Tests.GenericVectorTests.SquareRootSByte()
  Finished:    System.Numerics.Vectors.Tests
=== TEST EXECUTION SUMMARY ===
   System.Numerics.Vectors.Tests  Total: 1150, Errors: 0, Failed: 1, Skipped: 0, Time: 15.278s
```

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Below is the description of the problem in #20211

**SIMDIntrinsicGetItem** in the tree node
```
               [000011] ------------              *  STMT      void  (IL 0x000...  ???)
               [000010] ------------              \--*  RETURN    int
               [000009] ------------                 \--*  CAST      int <- byte <- double
               [000008] ------------                    \--*  INTRINSIC double sqrt
               [000007] ------------                       \--*  CAST      double <- int
               [000003] ------------                          |  /--*  CNS_INT   int    0
               [000006] ------------                          \--*  SIMD      int    byte get[i]
               [000005] n-----------                             \--*  OBJ(16)   simd16
               [000004] L-----------                                \--*  ADDR      byref
               [000001] ------------                                   \--*  LCL_VAR   simd16 V00 arg0
```
is lowered into `mov     w0, v16.b[0]` as can be seen in the following JIT output
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            mov     w0, v16.b[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            sxtb    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr

```
where instead it should have lowered into signed `smov`.

In #20211, the issue was reproducible only for `sbyte` GetItem, but in my regression test the issue also reproduces for `short` . 

For example, 
```
               [000011] ------------              *  STMT      void  (IL 0x000...  ???)
               [000010] ------------              \--*  RETURN    int
               [000009] ------------                 \--*  CAST      int <- short <- double
               [000008] ------------                    \--*  INTRINSIC double sqrt
               [000007] ------------                       \--*  CAST      double <- int
               [000003] ------------                          |  /--*  CNS_INT   int    0
               [000006] ------------                          \--*  SIMD      int    short get[i]
               [000005] n-----------                             \--*  OBJ(16)   simd16
               [000004] L-----------                                \--*  ADDR      byref
               [000001] ------------                                   \--*  LCL_VAR   simd16 V00 arg0
```
got compiled into
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            mov     w0, v16.h[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            sxth    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
```

Fixes #20211

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet-bot help

**Comment by echesakovMSFT** [comment]
After the change the following is produced 

**sbyte**
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            smov    x0, v16.b[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            sxtb    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
```

**short**
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            smov    x0, v16.h[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            sxth    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
```
**ubyte**
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            umov    w0, v16.b[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            uxtb    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
```
**ushort**
```
G_M60354_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
            mov     v16.d[0], x0
            mov     v16.d[1], x1

G_M60354_IG02:
            umov    w0, v16.h[0]
            scvtf   d16, w0
            fsqrt   d16, d16
            fcvtzs  w0, d16
            uxth    w0, w0

G_M60354_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
```

**Comment by echesakovMSFT** [comment]
test Ubuntu16.04 arm64 Cross Checked Build and Test

**Comment by echesakovMSFT** [comment]
It still not clear for me why JIT explicitly sets 128-bit datasize for INS_smov in **emitter::emitOutputInstr**
https://github.com/dotnet/coreclr/blob/209bca9c6caf59bc60bffd16a8da5c67c6d6138b/src/jit/emitarm64.cpp#L9788-L9802

and why destination general register always assumed to be 64-bit in **emitter::emitDispIns**
https://github.com/dotnet/coreclr/blob/209bca9c6caf59bc60bffd16a8da5c67c6d6138b/src/jit/emitarm64.cpp#L11367-L11380

@dotnet/jit-contrib @dotnet/arm64-contrib ?

**Comment by sdmaclea** [comment]
Take a look at the instruction encoding for smov.  Without looking at the ARM Reference Manual, I would guess it is just the way it is in arm64. When sign extending a vector element and moving from vector to general purpose it makes sense the the GP register is signeextended to 64 bits and the Vector source register is treated as 128 bits and the element can be any element withiun the 128 bit register.  There is really no need to support anything else.

**Comment by briansull** [comment]
I took a look at the docs for `smov` and I aggree with Egor the current special casing for `smov` looks wrong.
The only difference between smov and umov is that umov supports:
`UMOV Xd, Vn.D`

**Comment by echesakovMSFT** [comment]
Seems that both UMOV and SMOV encodings support moving to 64-bit general register as well as to 32-bit general register:

> `UMOV Wd, Vn.<Ts>[index]` Unsigned integer move element to 32-bit general register. Zero-extends an integer vector element from Vn into 32-bit general register Wd. Where <Ts> may be 8B, 16B, 4H, 8H, 2S or 4S. The index is in the range 0 to nelem(\<Ts\>)-1.
> 
> `UMOV Xd, Vn.D[index]`
> Unsigned integer move element to 64-bit general register. Moves an unsigned 64-bit integer vector
> element from Vn into 64-bit general register Wd. The immediate index is in the range 0 to 1.
> 
> `SMOV Wd, Vn.<T>[index]`
> Signed integer move element to 32-bit general register. Sign-extends an integer vector element from Vn
> into 32-bit general register Wd. Where <T> may be B or H. The index is a value is in the range 0 to nelem(\<T\>)-1.
> 
> `SMOV Xd, Vn.<T>[index]`
> Signed integer move element to 64-bit general register. Sign-extends an integer vector element from Vn
> into 64-bit general register Xd. Where <T> may be B, H or S. The index is in the range 0 to nelem(\<T\>)-1.

What confuses me is that emitter makes implicit for INS_umov whether reg1 is either Wd or Xd depending on the elemsize while for INS_smov reg1 is always Xd. 

What is even more confusing, that the behavior in emitter for INS_smov is different from what we assert in CodeGen for SIMDIntrinsicGetItem:
https://github.com/dotnet/coreclr/blob/030e0af89bb897554acef575075c69aaf5176268/src/jit/codegenarm64.cpp#L4551

For INS_smov `targetType` must be always `TYP_LONG` if we always sign-extend to Xd.

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib Please review this

File: src/jit/codegenarm64.cpp [hunk 1]
```diff
@@ -4601,8 +4601,28 @@ void CodeGen::genSIMDIntrinsicGetItem(GenTreeSIMD* simdNode)
                 assert(op1->isUsedFromReg());
                 regNumber srcReg = op1->gtRegNum;
 
-                // mov targetReg, srcReg[#index]
-                getEmitter()->emitIns_R_R_I(INS_mov, baseTypeSize, targetReg, srcReg, index);
+                instruction ins;
+                if (varTypeIsFloating(baseType))
+                {
+                    assert(genIsValidFloatReg(targetReg));
+                    // dup targetReg, srcReg[#index]
```
Comment (sandreenko) [inline src/jit/codegenarm64.cpp]: Why do you change floating logic here? Does your test check this part?

Comment (echesakovMSFT) [reply src/jit/codegenarm64.cpp]: Techically, the logic for floating point targetReg hasn't changed.

`emitIns_R_R_I(INS_mov, baseTypeSize, targetReg, srcReg, index)` where targetReg is float register (or vector register) and srcReg is vector register would emit `IF_DV_2E` which is encoding for INS_dup:
https://github.com/dotnet/coreclr/blob/27c848e37e9998142b60e776cf5b5d08a3543fe1/src/jit/emitarm64.cpp#L4504-L4523

I just made the floating point move more explicit by using INS_dup:
https://github.com/dotnet/coreclr/blob/27c848e37e9998142b60e776cf5b5d08a3543fe1/src/jit/emitarm64.cpp#L4748-L4757

But I can add the test cases for `Vector<float>` and `Vector<double>`

File: tests/src/JIT/Regression/JitBlue/GitHub_20211/GitHub_20211.cs [hunk 2]
```diff
@@ -0,0 +1,247 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System;
+using System.Numerics;
+using System.Runtime.CompilerServices;
+
+namespace GitHub_20211
```
Comment (CarolEidt) [inline tests/src/JIT/Regression/JitBlue/GitHub_20211/GitHub_20211.cs]: For the purpose of validating this fix, it seems fine to test only an index of 0, but it would be useful to add a comment to this test to clarify what the bug was.

Comment (echesakovMSFT) [reply tests/src/JIT/Regression/JitBlue/GitHub_20211/GitHub_20211.cs]: @CarolEidt I have added a bug description to the test. PTAL

Comment (CarolEidt) [reply tests/src/JIT/Regression/JitBlue/GitHub_20211/GitHub_20211.cs]: Thanks - meant to approve before.

**Comment by echesakovMSFT** [comment]
I will merge since the last commit just added a comment.
