### PR TITLE
Fixing encodeXmmRegAsIval to ensure the result meets the 'fits in imm8' check

### LINKED ISSUE #18815: [RyuJIT] Assert failure "unexpected operand size" when folding LCL_FLD into Avx.BlendVariable
The assert failture happens
```
Assert failure(PID 2324 [0x00000914], Thread: 8032 [0x1f60]): Assertion failed '!"unexpected operand size"' in 'Packet256Tracer:GetNaturalColor(struct,struct,struct,struct,ref):struct:this' (IL size 830)

    File: d:\workspace\coreclr\src\jit\emitxarch.cpp Line: 10343
    Image: C:\Program Files\dotnet\dotnet.exe
```
when RyuJIT tries to generate the below `vblendvps`
```
IN00cd:        vinsertf128 ymm8, ymm9, 1
Added IP mapping: 0x0095 STACK_EMPTY (G_M18437_IG06,ins#34,ofs#229)
Generating: N583 (  0,  3) [000182] ------------                 IL_OFFSET void   IL offset: 0x95 REG NA
Generating: N585 (  0,  0) [000178] ------------       t178 =    HWIntrinsic simd32 float SetZeroVector256 REG mm7 $626
IN00ce:        vxorps   ymm7, ymm7, ymm7
                                                             /--*  t178   simd32 
Generating: N587 (  0,  3) [000181] DA----------              *  STORE_LCL_VAR simd32 V17 loc10        d:3 mm7 REG mm7
							V17 in reg mm7 is becoming live  [000181]
							Live regs: 0000F0E8 {rbx rbp rsi rdi r12 r13 r14 r15 xmm8} => 0000F0E8 {rbx rbp rsi rdi r12 r13 r14 r15 xmm7 xmm8}
							Live vars: {V00 V01 V02 V03 V04 V05 V06 V07 V08 V14 V15 V21 V24 V25 V31} => {V00 V01 V02 V03 V04 V05 V06 V07 V08 V14 V15 V17 V21 V24 V25 V31}
Added IP mapping: 0x009C STACK_EMPTY (G_M18437_IG06,ins#35,ofs#234)
Generating: N589 (  8,  9) [000195] ------------                 IL_OFFSET void   IL offset: 0x9c REG NA
Generating: N591 (  1,  1) [000183] ------------       t183 =    LCL_VAR   simd32 V17 loc10        u:3 mm7 REG mm7 $7cb
Generating: N593 (  3,  4) [000184] -c----------       t184 =    LCL_FLD   simd32 V16 loc9         u:3[+0] Fseq[Xs] NA REG NA <l:$764, c:$765>
Generating: N595 (  1,  1) [000187] ------------       t187 =    LCL_VAR   simd32 V15 loc8         u:3 mm8 REG mm8 $6ff
                                                             /--*  t183   simd32 
                                                             +--*  t184   simd32 
                                                             +--*  t187   simd32 
Generating: N597 (  8,  9) [000191] ------------       t191 = *  HWIntrinsic simd32 float BlendVariable REG mm0 $627
IN00cf:        vblendvps ymm0, ymm7, [V16 rsp+1190H], ymm8
```

This bug is detected in the work of https://github.com/dotnet/coreclr/issues/17798, and .NET Core 2.1 works fine, so it seems introduced by the recent containment change.

@tannergooding @CarolEidt

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @CarolEidt, @fiigii, @eerhardt

This resolves #18815

### CODE REVIEW

**Comment by tannergooding** [comment]
This is the same as https://github.com/dotnet/coreclr/pull/18820, but in a new PR as the old one seems to have gotten into some weird state that caused the perf correctness jobs to fail (even with a whitespace only change).

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic please

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic please

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic please

File: src/jit/emitfmtsxarch.h [hunk 1]
```diff
@@ -111,7 +111,7 @@ IF_DEF(RRW_RRW_CNS, IS_R1_RW|IS_R2_RW,          SCNS)     // r/w    reg , r/w  r
 IF_DEF(RWR_RRD_RRD, IS_R1_WR|IS_R2_RD|IS_R3_RD, NONE)     // write  reg , read reg2 , read reg3
 IF_DEF(RWR_RRD_RRD_CNS, IS_R1_WR|IS_R2_RD|IS_R3_RD, SCNS) // write  reg , read reg2 , read reg3, const
 
-IF_DEF(RWR_RRD_RRD_RRD, IS_R1_WR|IS_R2_RD|IS_R3_RD|IS_R4_RD, NONE)     // write  reg , read reg2 , read reg3 , read reg4
+IF_DEF(RWR_RRD_RRD_RRD, IS_R1_WR|IS_R2_RD|IS_R3_RD|IS_R4_RD, CNS)     // write  reg , read reg2 , read reg3 , read reg4
```
Comment (tannergooding) [inline src/jit/emitfmtsxarch.h]: @fiigii, @CarolEidt. This was causing the additional assert, we need to ensure that RWR_RRD_RRD_RRD is marked as carrying a constant (for encoding reg4) so that the debug only id size checks succeed.

This seems to only matter when reg4 is an extended register and generates "large" constant (which is really just a sign-extended byte constant)

File: src/jit/emitxarch.cpp [hunk 2]
```diff
@@ -4512,10 +4512,13 @@ void emitter::emitIns_R_R_S_I(
...
 static int encodeXmmRegAsIval(regNumber opReg)
 {
-    assert(opReg >= XMMBASE);
     // AVX/AVX2 supports 4-reg format for vblendvps/vblendvpd/vpblendvb,
     // which encodes the fourth register into imm8[7:4]
-    return (opReg - XMMBASE) << 4;
+    assert(opReg >= XMMBASE);
+    int ival = (opReg - XMMBASE) << 4;
+
+    assert((ival >= 0) && (ival <= 255));
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: > But I would at least not cast to a signed type (int8_t) when you're using an unsigned range above.

@CarolEidt, we actually can't do that and both are required.

The JIT does signed check (value must be in range of -128 to 127) for "fits in byte". However, the value returned by the computation, (opReg - XMMBASE) << 4, is within the unsigned range (0 to 255).

If we cast to uint8_t, then the value is zero-extended, rather than sign-extended, and we will fail the "fits in byte" check. This was the same problem that was plaguing the HWIntrinsic APIs that directly take an immediate parameter (as they take a byte). -- I think we also discussed, briefly, that this may cause us to emit code that is larger than necessary in some cases (but I don't see an issue tracking that)...

**Comment by tannergooding** [comment]
@CarolEidt, do you know who to tag on the Perf Tests Correctness failures? I can't get them to fail locally and it seems to be persistent no matter what the PR contains (it failed last night, on the previous PR with a whitespace only change).

**Comment by tannergooding** [comment]
For reference, the jenkins logs are indicating that `submission-metadata.json` can't be found in the workspace directory:
>23:03:59 Traceback (most recent call last):
23:03:59   File "tests\scripts\run-xunit-perf.py", line 530, in <module>
23:03:59     sys.exit(main(Args))
23:03:59   File "tests\scripts\run-xunit-perf.py", line 521, in main
23:03:59     upload_to_benchview(python, coreclrRepo, benchviewPath, uploadToBenchview, benchviewGroup, runType, configuration, operatingSystem, etwCollection, optLevel, jitName, pgoOptimized, arch)
23:03:59   File "tests\scripts\run-xunit-perf.py", line 285, in upload_to_benchview
23:03:59     raise Exception('%s does not exist. There is no data to be uploaded.' % jsonFile)
23:03:59 Exception: D:\j\w\perf_perflab_---89ec9f56\submission-metadata.json does not exist. There is no data to be uploaded.

**Comment by CarolEidt** [comment]
So ... perhaps @adiaaida or @noahfalk who have most recently touched the tests\scripts\run-xunit-perf.py script.

**Comment by tannergooding** [comment]
@CarolEidt, @adiaaida, @noahfalk. I found the issue. My PR title contains quotes, which break the `tools\submission-metadata.py` script

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x64 min_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness please
@dotnet-bot test Windows_NT x86 min_opt ryujit CoreCLR Perf Tests Correctness please

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/coreclr/issues/18855 to track the issue and changed my PR title in the meantime.
