### PR TITLE
Fix RyuJIT/x86 P/Invoke inlining

### LINKED ISSUE #4181: RyuJIT x86: NYI_X86: "Implement PInvoke frame init inlining for x86"
This NYI: 

NYI_X86: "Implement PInvoke frame init inlining for x86"
File: coreclr\src\jit\lower.cpp Line: 2521

Is hit by these tests:

JIT\jit64\hfa\main\testC\hfa_nf2C_d\hfa_nf2C_d.cmd
JIT\jit64\hfa\main\testG\hfa_nf2G_d\hfa_nf2G_d.cmd
JIT\jit64\hfa\main\testE\hfa_nd2E_r\hfa_nd2E_r.cmd
JIT\jit64\regress\vsw\286991\test\test.cmd
JIT\jit64\hfa\main\testA\hfa_nf2A_d\hfa_nf2A_d.cmd
JIT\jit64\hfa\main\testA\hfa_nf2A_r\hfa_nf2A_r.cmd
JIT\jit64\hfa\main\testC\hfa_nf2C_r\hfa_nf2C_r.cmd
JIT\Generics\pinvoke\instance01\instance01.cmd
JIT\Generics\pinvoke\instance03\instance03.cmd
JIT\Directed\pinvoke\calli_excep\calli_excep.cmd

### PR DESCRIPTION
**Pull request by BruceForstall**
Enable RyuJIT/x86 PInvoke lowering

Fixes #4181 "NYI_X86: Implement PInvoke frame init inlining for x86"

The main work here is to handle the custom calling convention for the
x86 CORINFO_HELP_INIT_PINVOKE_FRAME helper call: it takes EDI as an argument,
trashes only EAX, and returns the TCB in ESI.

The code changes are as follows:
1. Lowering::InsertPInvokeMethodProlog(): don't pass the "secret stub param" for x86.
Also, don't store the InlinedCallFrame.m_pCallSiteSP in the prolog: for x86 this is done
at the call site, due to the floating stack pointer.
2. LinearScan::getKillSetForNode(): for helper calls, call compHelperCallKillSet() to get the killMask,
to account for non-standard kill sets.
3. Morph.cpp::fgMorphArgs(): set non-standard arguments for CORINFO_HELP_INIT_PINVOKE_FRAME.
4. compHelperCallKillSet(): set the correct kill set for CORINFO_HELP_INIT_PINVOKE_FRAME.
5. codegenxarch.cpp::genCallInstruction(): set the ABI return register for CORINFO_HELP_INIT_PINVOKE_FRAME.
6. lowerxarch.cpp::TreeNodeInfoInit(): set the GT_CALL dstCandidates for CORINFO_HELP_INIT_PINVOKE_FRAME.

5 & 6 are both needed to avoid a copy.

With this change, the `#1` NYI with 18415 hits over the tests is gone.
The total number of NYI is now 29516.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@jashook Looks like the ARM tasks aren't doing anything, and are either failing or succeeding with no interesting output.

**Comment by BruceForstall** [comment]
@briansull @sivarv @adiaaida PTAL
cc @dotnet/jit-contrib

**Comment by jashook** [comment]
@BruceForstall that error is quite strange, that file should be present after a merge with master.

**Comment by jashook** [comment]
@dotnet-bot test Linux ARM emulator Release build

**Comment by jashook** [comment]
@BruceForstall this is a CI issue caused from merging the wrong hash. @mmitche can explain better. The arm legs are not the problem, you can ignore the errors.

**Comment by briansull** [comment]
LGTM

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -3109,6 +3116,8 @@ void Lowering::InsertPInvokeMethodProlog()
     GenTree* lastStmt = stmt;
     DISPTREE(lastStmt);
 
+#ifndef _TARGET_X86_ // For x86, this step is done at the call site.
```
Comment (sivarv) [inline src/jit/lower.cpp]: Please also mention the reason for doing this step at call site (i.e. due to floating stack pointer)

File: src/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -903,6 +903,16 @@ void Lowering::TreeNodeInfoInit(GenTree* stmt)
             }
 
             // Set destination candidates for return value of the call.
+#ifdef _TARGET_X86_
+            if ((tree->gtCall.gtCallType == CT_HELPER) && (tree->gtCall.gtCallMethHnd == compiler->eeFindHelper(CORINFO_HELP_INIT_PINVOKE_FRAME)))
```
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: I see this condition is used more than once (also in codegenxarch.cpp and in morph.cpp).  I would suggest to abstract it in a member routine of call node

e.g.
bool GenTreeCall::IsInitPInvokeFrameHelper() const

File: src/jit/lsra.cpp [hunk 3]
```diff
@@ -2563,12 +2562,25 @@ LinearScan::getKillSetForNode(GenTree* tree)
...
                 needFloatTmpForFPCall = true;
             }
-#endif // _TARGET_X86_
-            killMask = RBM_CALLEE_TRASH;
+        }
+        if (tree->IsHelperCall())
+        {
+            GenTreeCall* call = tree->AsCall();
+            CorInfoHelpFunc helpFunc = compiler->eeGetHelperNum(call->gtCallMethHnd);
+            killMask = compiler->compHelperCallKillSet(helpFunc);
```
Comment (sivarv) [inline src/jit/lsra.cpp]: Here we already know that tree is a GenTreeCall node since its oper is GT_CALL.  Here  too we can use the same condition that was used in codegenxarch.cpp/morph.cpp to know whether a initPInvokeFrame helper call

`if ((call->gtCallType == CT_HELPER) && (call->gtCallMethHnd == compiler->eeFindHelper(CORINFO_HELP_INIT_PINVOKE_FRAME)))`

The it would be 4th such place and assuming that we abstract it in a routine IsInitPInvokeFrameHelper() on GenTreeCall, the above check reduces to

```
if (tree->AsCall()->IsInitPInvokeFrameHelper())
{
     killMask = compiler->compHelperCallKillSet(CORINFO_HELP_INIT_PINVOKE_FRAME);
}
```

File: src/jit/lowerxarch.cpp (hunk 2 above)
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: To make the above member function more generic to useful in more ways we could add

```
// Returns true if the call node is a call to a given helper.
bool GenTree::IsHelperCall(CorInfoHelpFunc  helper)
{
}

// usage
if (tree->IsHelperCall(CORINFO_HELP_INIT_PINVOKE_FRAME))
```

File: src/jit/codegencommon.cpp [hunk 4]
```diff
@@ -686,6 +686,13 @@ regMaskTP Compiler::compHelperCallKillSet(CorInfoHelpFunc helper)
     case CORINFO_HELP_STOP_FOR_GC:
         return RBM_STOP_FOR_GC_TRASH;
 
+#ifdef _TARGET_X86_
+    case CORINFO_HELP_INIT_PINVOKE_FRAME:
+        // On x86, this helper has a custom calling convention that takes EDI as argument
+        // (but doesn't trash it), trashes EAX, and returns ESI.
+        return RBM_PINVOKE_SCRATCH | RBM_PINVOKE_TCB;
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: How about defining a constant in target.h for this?

e.g.
#define RBM_INIT_PINVOKE_FRAME_TRASH  (RBM_PINVOKE_SCRATCH | RBM_PINVOKE_TCB)

For targets other than x86 it will be RBM_CALLEE_TRASH.

This would not only serve as documentation but also while porting JIT, we just have to define appropriately in target.h.  Otherwise one would have to remember to update this routine which is very easy to miss.  In fact for amd64 unix we had such an instance.

File: src/jit/lsra.cpp (hunk 3 above)
Comment (BruceForstall) [inline src/jit/lsra.cpp]: There may be other cases of custom calling conventions, in which case the way it's written now would allow for those.

Comment (sivarv) [inline src/jit/lsra.cpp]: Thanks for clarifying. Makes sense.

**Comment by sivarv** [comment]
Looks good 
Except for two of my comments: one related to defining a constant in target.h and another abstracting Init PInvoke helper call check.  I would leave it up to you whether you want to make that change with this PR or in a subsequent PR.

**Comment by BruceForstall** [comment]
@sivarv : I like the suggestions. I'll try to make it more general, easy to port, and with less `#ifdef`s as per your suggestions. For now, though, I'm going to merge.
