### PR TITLE
Fix some frequently failing PAL tests

### LINKED ISSUE #1561: File Attribute pal tests failing in PRs on linux release.
```
file_io.CopyFileA.test3 (from (empty))

Failing for the past 1 build (Since Failed#1969 )
Took 0 ms.
Stacktrace

MESSAGE:
CopyFileA : The file attributes of the destination file do not match the file attributes of the source file.
+++++++++++++++++++
```
```
file_io.GetFileAttributesA.test1 (from (empty))
```
```
file_io.GetFileAttributesW.test1 (from (empty))
```

### PR DESCRIPTION
**Pull request by kouvel**
Fix some frequently failing PAL tests

Some PAL tests are frequently failing in the CI. The specified output folder is currently used as the working folder for all PAL tests. The CI machine happened to have the output folder on a mount mounted as fuseblk instead of ext4. We don't know why this is happening. For the moment, I'm fixing the test runner to work around this issue.

Changes:
- Use /tmp/PalTestOutput/default as the output folder by default
- If a specific folder is specified for the output, use a unique folder inside /tmp/PalTestOutput for output files, and copy them to the specified folder at the end. A unique folder is used to support parallel runs on the same machine in this mode.
- Run each test in its own folder. Many PAL tests don't clean up after themselves, and create/use the same file/folder names in the current folder.
- Add a few more checks to some tests to hopefully provide more information upon the next failure
- Fix GetFileAttributes tests, which were crashing upon some failures due to mismatched number of placeholders and arguments to vprintf

Fixes #1561

### CODE REVIEW

**Comment by kouvel** [comment]
If after this there are still failures, I'll disable the tests. I'm investigating further meanwhile in any case.

CC @sergiy-k @jkotas

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
Got a machine to see the issue, updated title and description, and pushed latest fixes

**Comment by kouvel** [comment]
Fixed to use mktemp instead

**Comment by sergiy-k** [comment]
LGTM

**Comment by kouvel** [comment]
Sorry added one more fix to create the initial root directory and not delete the directory created by mktemp

**Comment by sergiy-k** [comment]
LGTM

**Comment by sergiy-k** [comment]
cc @mmitche

File: src/pal/tests/palsuite/runpaltests.sh [hunk 1]
```diff
@@ -38,16 +38,35 @@ PAL_TEST_LIST=$PWD/paltestlist.txt
 cd $OLDPWD
 echo The list of PAL tests to run will be read from $PAL_TEST_LIST
 
-# Create path to a folder where PAL tests will store their output
-# First check if the output folder was passed as a parameter to the script.
-# It is supposed be the second parameter so check if we have more than 1 argument.
+# Create the test output root directory
+mkdir -p /tmp/PalTestOutput
```
Comment (mmitche) [inline src/pal/tests/palsuite/runpaltests.sh]: Won't this block cause problems for multiple jobs running on the same machine at the same time?

Comment (kouvel) [inline src/pal/tests/palsuite/runpaltests.sh]: This isn't the directory tests actually use as their working folder. It's just the root directory under which a unique temp directory is created below with mktemp. The PalTestOutput directory needs to exist for mktemp to succeed creating a directory under it. Otherwise, I was just preserving the previous behavior to delete PalTestOutput if it exists but is not a directory, which shouldn't happen more than once, and typically should never happen.

Comment (mmitche) [inline src/pal/tests/palsuite/runpaltests.sh]: Ahh okay that sounds fine then.

**Comment by mmitche** [comment]
LGTM then.
