### PR TITLE
JIT: make suitably optimistic prejit inline assessments

### LINKED ISSUE #3482: Inliner: inconsistencies between prejit analysis and jit analysis
When prejitting a method, the compiler will do some analysis to try and determine if that method is a viable inline candidate. If not, the method attributes in the prejit image are modified to mark the method as noinline.

However, the analysis done at prejit time is inconsistent with the analysis done at jit time. That is, a given method might look like a better inline candidate when jitting than it does during prejitting (this is true even if we ignore information coming from the call site).

Consider the inline hints computed during `fgFindJumpTargets` and stored in the `compInlineeHints` member variable on the compiler instance. All but one of these hints are set only if `compIsForInlining()` is true, which excludes them from prejit analysis (`InlMostlyMethodLdSt` being the perhaps inadvertent exception). So for instance if a method has an an argument that feeds a compare vs constant or a range check, it will make the method a more attractive inline candidate when jitting but not when prejitting.

When we get a bit further along in the program outlined in #3371 we'll need to decide how best to handle this quirk. It would be cleanest for `fgFindJumpTargets` to simply make observations (in place of the current hinting) and have the policy decide when they observations are relevant. This means the `LegacyPolicy` must distinguish between the prejit analysis and the normal inline analysis, so in the prejit case, it can ignore most of the hint observations.

### LINKED ISSUE #14441: JIT: prejit classifier may be overly pessimistic
When prejitting a method we perform an assessment to determine if any caller would ever decide to inline this method. If the answer is no, we mark the method as noinline to save the jit from wasting time examining this method as an inline candidate.

This assessment is not intended to alter the inlining decisions made by the jit. The jit should produce the same codegen with or without these assessments, but should run somewhat faster with them. So the assessment needs to be optimistic and anticipate various profitability boosts from callers.

There's at least one example now where this doesn't happen: see notes in #14420 and below. A relatively simple experiment to unearth these cases is to disable the "propagate never to runtime" logic in the inline policy, eg modify `EnhancedLegacyPolicy::PropagateNeverToRuntime()` to return false and see if that gives different crossgen results than if it is left as is.

Pre 14420 results when prejitting System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this
```
multiplier in methods of promotable struct increased to 3.
Inline candidate callsite is hot.  Multiplier increased to 6.
calleeNativeSizeEstimate=710
callsiteNativeSizeEstimate=115
benefit multiplier=6
threshold=690
Native estimate for function size exceeds threshold for inlining 71 > 69 (multiplier = 6)
INLINER: during 'prejit' result 'failed this callee' reason 'unprofitable inline' for 'n/a' calling 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this'

INLINER: Marking System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this as NOINLINE because of unprofitable inline
```
Post 14420 results when prejitting a caller before we've prejitted the method: System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this
```
Invoking compiler for the inlinee method System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this
...
multiplier in methods of promotable struct increased to 3.
Inline candidate looks like a wrapper method.  Multiplier increased to 4.
Inline candidate has an arg that feeds a constant test.  Multiplier increased to 5.
Inline candidate callsite is boring.  Multiplier increased to 6.3.
calleeNativeSizeEstimate=710
callsiteNativeSizeEstimate=115
benefit multiplier=6.3
threshold=724
Native estimate for function size is within threshold for inlining 71 <= 72.4 (multiplier = 6.3)
...
Successfully inlined System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Int32][System.Int32]:SetResult(int):this (58 IL bytes) (depth 1) [profitable inline]
```
So the wrapper method and presence of a constant arg seems to have been the key differences in the benefit estimation. I wouldn't have expected the wrapper method benefit to vary this way so that is a surprise. We don't see the argument values when doing the assessment, so that part is not a surprise, but we should account for the fact that callers may have them.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
When prejitting, the jit assesses whether each root method is a potential
inline candidate for any possible caller. Methods deemed un-inlinable in any
caller are marked in the runtime as "noinline" to save the jit some work
later on when it sees calls to these methods.

This assessment was too conservative and led to prejit-ordering dependences
for inlines. It also meant that prejitting was missing some inlines that
would have happened had we not done the prejit root assessment.

This change removes some of the prejit observation blockers. These mostly
will enable more prejit methods to become candidates. We also now track when
a method argument reaches a test.

When we are assessing profitability for a prejit root, assume the call site
best possible case.

Also, update the inline XML to capture the prejit assessments.

This increases the number of inlines considered and performed when prejitting
and will also lead to slightly more inlining when jitting. However we do not
expect a large througput impact when jitting -- the main impact of this change
is that inlining when prejitting is now just as aggressive as inlining when
jitting, and the decisions no longer depend on the order in which methods are
prejitted.

Closes #14441.
Closes #3482.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib 

Verified that if I disable the propagation of the noinline bit into the runtime we get the same inlines in corelib as we do when we propagate.

Size impact from jit-diffs. Note size increase is expected as this makes the prejit inliner as aggressive as the jit inliner. 

I plan to follow-up with some commentary on the largest regressions.
```
Total bytes of diff: 179408 (0.79 % of base)
    diff is a regression.

Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes

Top file regressions by size (bytes):
       36286 : Microsoft.CodeAnalysis.CSharp.dasm (1.67 % of base)
       28841 : System.Private.Xml.dasm (0.99 % of base)
       26980 : System.Private.CoreLib.dasm (0.77 % of base)
       21377 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.92 % of base)
        9905 : System.Data.Common.dasm (0.92 % of base)

Top file improvements by size (bytes):
         -11 : System.Net.WebSockets.dasm (-0.03 % of base)

57 total files with size differences (1 improved, 56 regressed), 73 unchanged.

Top method regessions by size (bytes):
        3847 : System.Text.RegularExpressions.dasm - System.Text.RegularExpressions.RegexInterpreter:Go():this (1 methods)
        2093 : System.Private.DataContractSerialization.dasm - CriticalHelper:WriteMembers(ref,ref,ref):int:this (2 methods)
        1384 : System.Private.Xml.dasm - System.Xml.XmlSqlBinaryReader:RescanNextToken():int:this (1 methods)
        1303 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Binder:ReduceFrom(ref,ref,ref):this (1 methods)
        1189 : System.Private.Xml.dasm - <ParseElementMixedContentAsync>d__167:MoveNext():this (1 methods)

Top method improvements by size (bytes):
         -86 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.LambdaRewriter:IntroduceFrame(ref,ref,ref,ref):ref:this (1 methods)
         -58 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol:AddSyntheticMyGroupCollectionProperty(ref,bool,ref,ref,ref,ref,ref,ref,ref):this (1 methods)
         -38 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.LocalRewriter:RewriteObjectInitializerExpression(ref,ref,ref):ref:this (1 methods)
         -37 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.LocalRewriter:VisitSyncLockStatement(ref):ref:this (1 methods)
         -37 : Microsoft.CodeAnalysis.VisualBasic.dasm - Microsoft.CodeAnalysis.VisualBasic.LocalRewriter:RewriteWinRtEvent(ref,ref,bool):ref:this (1 methods)

2379 total methods with size differences (86 improved, 2293 regressed), 140651 unchanged.
```

Some data on the impact to inlining in corelib below. We seen more candidates and so more inline attempts and a successes. Fewer failures from "noinline" and more from "unprofitable". Unprofitable rejects are still somewhat cheap (requires IL scan but no importation).

About 10% more methods in corelib are now considered inline candidates.

| Version | Methods | w/Inlines | Attempts | Successes | Failures | Extras | PrejitCand |
| :------ | ------: | --------: | -------: | --------: | -------: | -----: | ---------: |
| Base    | 27079   | 13151     | 103663   | 46278     | 57385    | 3602   | 15663      |
| Diff    | 27079   | 13222     | 105614   | 47454     | 58160    | 3611   | 18452      |
| Delta   | 0       | 71        | 1951     | 1176      | 775      | 9      | 2789       |

Success Breakdown

| Base Count | Base Percent | Reason | Diff Count | Diff Percent |
| ----: | ----: | :---- | ----: | ----: |
|  31585 | 68.25 % | below ALWAYS_INLINE size     |  31937 | 67.30 % |
|  12009 | 25.95 % | profitable inline            |  12830 | 27.04 % |
|   2684 |  5.80 % | aggressive inline attribute  |   2687 |  5.66 % |

Failure Breakdown

| Base Count | Base Percent | Reason | Diff Count | Diff Percent |
| ----: | ----: | :---- | ----: | ----: |
|  25470 | 44.38 % | noinline per IL/cached result   |  23262 | 40.00 % |
|  10700 | 18.65 % | unprofitable inline             |  13413 | 23.06 % |
|   9091 | 15.84 % | target not direct               |   9132 | 15.70 % |
|   6668 | 11.62 % | does not return                 |   6869 | 11.81 % |
|   1541 |  2.69 % | within catch region             |   1541 |  2.65 % |
|   1309 |  2.28 % | too many il bytes               |   1308 |  2.25 % |
|    977 |  1.70 % | cannot get method info          |    977 |  1.68 % |
|    477 |  0.83 % | has exception handling          |    476 |  0.82 % |
|    402 |  0.70 % | ldfld needs helper              |    402 |  0.69 % |
|    298 |  0.52 % | runtime dictionary lookup       |    299 |  0.51 % |
|    125 |  0.22 % | not inline candidate            |    131 |  0.23 % |
|    105 |  0.18 % | rarely called, has gc struct    |    120 |  0.21 % |
|    104 |  0.18 % | too many basic blocks           |    105 |  0.18 % |
|     31 |  0.05 % | this pointer argument is null   |     31 |  0.05 % |
|     27 |  0.05 % | implicit recursive tail call    |     27 |  0.05 % |
|     23 |  0.04 % | complex handle access           |     23 |  0.04 % |
|     12 |  0.02 % | ldsfld of value class           |     14 |  0.02 % |
|      8 |  0.01 % | inline exceeds budget           |     13 |  0.02 % |
|      5 |  0.01 % | uses stack crawl mark           |      5 |  0.01 % |
|      4 |  0.01 % | has switch                      |      4 |  0.01 % |
|      4 |  0.01 % | unsupported opcode              |      3 |  0.01 % |
|      2 |  0.00 % | recursive                       |      3 |  0.01 % |
|      1 |  0.00 % | too many locals                 |      1 |  0.00 % |
|      1 |  0.00 % | delegate invoke                 |      1 |  0.00 % |

Extra Breakdown

| Base Count | Base Percent | Reason | Diff Count | Diff Percent
| ----: | ----: | :---- | ----: | ----: |
|   2684 |  4.68 % | aggressive inline attribute |   2687 |  4.62 % |
|    483 |  0.84 % | below ALWAYS_INLINE size    |    485 |  0.83 % |
|    435 |  0.76 % | profitable inline           |    439 |  0.75 % |

"Extras" are methods inlined because some inline parent is an aggressive inline, eg we have a call chain A->B->C where B is an aggressive inline. Once the jit inlines B into A it now may be required to do even more inlines. So think of it as the assessment of the knock-on effect from an aggressive non-leaf inline.

File: src/jit/inline.cpp [hunk 1]
```diff
@@ -474,6 +474,12 @@ void InlineContext::DumpXml(FILE* file, unsigned indent)
         m_Sibling->DumpXml(file, indent);
     }
 
+    // Optionally suppress failing inline records
+    if ((JitConfig.JitInlineDumpXml() == 3) && !m_Success)
+    {
```
Comment (briansull) [inline src/jit/inline.cpp]: Should we add an enum for the three values used by JitInlineDumpXml()

Comment (AndyAyersMS) [reply src/jit/inline.cpp]: There are a bunch of enhancements I have in mind for the inline XML, though as far as I know nobody but me has ever used it.... also I have some analysis tooling lying about that I should publish somewhere, maybe over in jitutils.

I should really change this into a flags-style thing.... you should be able to choose:
* get XML for all methods or only those with inlines or inline attempts
* get XML for all inline attempts or only those with successful inlines
* get XML with full details or just summary details
* specify filename to contain the results (currently always goes to stderr)

So maybe this is best done as a follow-up change.

**Comment by AndyAyersMS** [comment]
Looking at the larger regressions, so far they fall into two related patterns:
* Top level method has many call sites to mid-sized methods that now get inlined. For instance `RegexInterpreter:Go` has a large switch to handle the various regex cases, and most switch arms end up calling `Advance`, and this now gets inlined.
* Top level method has a few call sites but the call tree at those sites fans out into sets of mid-sized methods, as in `CriticalHelper:WriteMembers`.

These cases highlight the fact that in the current inline heuristics the profitability model is not dependent on the overall set of inline candidates and/or the history of inlines done so far. Each inline is assessed independently of all others. So if a method presents the inliner with a large number of marginal candidates the inliner can grow size fairly aggressively as each candidate when considered on its own passes the bar. There is a limiter that can kick in if things get too far out of hand (the "inline exceeds budget" rejection case) and we do see an uptick in this in the data but it is mainly there to prevent pathological behavior.

As I have stated elsewhere the current profitability heuristics are not well founded and it is likely they give improper weight to the various facts available to the inliner. The upshot is that many marginal candidates appear more attractive then they ought to be. While some tweaking is possible the biggest missing factor is some kind of call site frequency estimate which is entirely lacking*. For example in the case of `RegexInterpreter:Go` the call sites in the switch arms would likely be assigned fairly low frequencies and so would become much less attractive inline candidates.
```asm
;;; Before
       mov      rcx, rsi
       mov      edx, 2
       call     [System.Text.RegularExpressions.RegexInterpreter:Advance(int):this]

;;; After
       add      dword ptr [rsi+124], 3               // rsi == 'this'; need it in rcx below
       mov      gword ptr [rsp+68H], rsi             // questionable spill
       mov      rcx, gword ptr [rsi+104]
       mov      rcx, gword ptr [rcx+8]
       mov      edx, dword ptr [rsi+124]
       cmp      edx, dword ptr [rcx+8]
       jae      G_M25344_IG182
       movsxd   rdx, edx
       mov      ecx, dword ptr [rcx+4*rdx+16]       // would like to see this go into rdx
       mov      dword ptr [rsp+64H], ecx            // to avoid this spill...
       mov      rcx, gword ptr [rsp+68H]            // rsi still has this value!
       mov      edx, dword ptr [rsp+64H]            // ... and reload
       call     [System.Text.RegularExpressions.RegexInterpreter:SetOperator(int):this]
```

Finally the profitability model must take into account the capabilities of the rest of the optimization pipeline, so what looks like a good inline may in fact produce suboptimal code. The `Go` example provides some evidence of this as the inlines of `Advance` end up being larger than they should be.

At any rate the behavior seen here is "by design" as things are working the way they are supposed to work.

*Such data is available with IBC (profile feedback) but the inliner doesn't handle this very well either.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Perf Build and Test

@jorive This leg is now 3h30m or longer. Can we split it into multiple legs (say one for x64 and one for x86) to try and cut down the latency?

**Comment by benaadams** [comment]
> For instance RegexInterpreter:Go has a large switch to handle the various regex cases, and most switch arms end up calling Advance, and this now gets inlined

Don't think it does this; and would likely be a large undertaking if not. 

However, if the same method is inlined multiple times, and only the parameters are changing could it be inlined once with the setup register values changed prior to `jmp`? 

Downside would be reduced optimization from dead code elimination (as branches may be active on multiple paths, so indeterminate)

**Comment by adiaaida** [comment]
@AndyAyersMS All of the builds/tests run in parallel, as it's a pipeline job. So breaking it into different jobs will not make a difference in terms of time spent. It is running long because we have some serious backlog on the linux jobs, so the machines are slammed. Strangely, it still shows as pending, but the Perf leg has actually completed and failed due to not being able to restore the opt data packages.

**Comment by AndyAyersMS** [comment]
@adiaaida recent history for the leg not looking promising...
image

Thinking I should just ignore this failure and merge. Does that seem reasonble?

**Comment by briansull** [comment]
Could you wait until the build break job is checked in:
https://github.com/dotnet/coreclr/pull/14888

**Comment by AndyAyersMS** [comment]
@benaadams you mean treat repeated inlines like some kind of local procedure call? That idea has floated about at times but I've never seen it pursued seriously.

Doing this presents modelling challenges: simple flow graph representations now contain many "infeasible" flow paths can seriously degrade the quality and running time of analyses.

**Comment by AndyAyersMS** [comment]
@briansull sure, I'm in no hurry to merge, just hate rerunning failing jobs at random thinking that for some reason they might now pass.

**Comment by adiaaida** [comment]
I think you can ignore the failure, but if you're interested in the perf implications of the change, you should rerun.

**Comment by briansull** [comment]
I merged the build break fix, so you are all clear from my point of view

**Comment by benaadams** [comment]
> @benaadams you mean treat repeated inlines like some kind of local procedure call?

Yes

> Doing this presents modelling challenges: simple flow graph representations now contain many "infeasible" flow paths can seriously degrade the quality and running time of analyses.

For running time; for example, it could be crossgen only? 

However; may also reduce CQ by keeping multiple paths alive; rather than branch eliminating them (i.e. constants becoming variables) - so may not be worth it. Just musing...

**Comment by AndyAyersMS** [comment]
I do care about perf; in particular this is going to look like it causes TP regressions.

The last 30 or so runs of "perf build and test" have all failed, so it seems unlikely triggering a rerun will do anything useful.

**Comment by AndyAyersMS** [comment]
@benaadams the quality of the solutions can degrade pretty badly if you just wire everything up like it is normal dataflow. To get good results you typically need techniques like those developed for interprocedural dataflow, and that gets tricky with things like SSA.

Large fan-ins (say at the "entry" to the local procedure) are troublemakers since they commonly represent places where facts must merge and it requires thoughtful engineering to avoid quadratic bad behavior in dataflow models. This fan-in issue also plagues SSA which generally copes very nicely with large methods. So lots of places where things can go off the rails.

A compromise is to "fix" an ABI and decouple some of what is going on in the local procedure from the main method, and give special treatment to things that are live across the boundaries. This is more or less what we do for catches and finallys that are compiled as funclets and (for finallys anyways) invoked as local procedures.

Or you can just let the compiler do its thing and they very late try to pattern match and combine the disparate copies back into common code.

However all of these sorts of things are pretty far down there in priority.

In the case of the Regex interpreter it is pretty common that the call to `Advance` is the last thing done in a switch case (though not all cases call Advance and some do only conditionally). Some kind of conditional tail merge at the end of the switch would also be a way of commoning this path. But this is perhaps something better done at the source level.

**Comment by benaadams** [comment]
@dotnet-bot test Perf Build and Test

**Comment by benaadams** [comment]
> But this is perhaps something better done at the source level.

That is probably true 😁

**Comment by benaadams** [comment]
@AndyAyersMS just had a look at `System.Text.RegularExpressions.RegexInterpreter:Go` and see what you mean; that's a very large function, trying to use a funclet would probably be extraordinarily complex

**Comment by benaadams** [comment]
Added PR for `RegexInterpreter:Go` https://github.com/dotnet/corefx/pull/25096

**Comment by benaadams** [comment]
> It is running long because we have some serious backlog on the linux jobs, so the machines are slammed.

Over  6 hr 40 min for "Perf Build and Test" so far; might need some more machines?

**Comment by AndyAyersMS** [comment]
Perf build and test actually had a few passing runs recently, but some legs are now at 16hrs+ and still running.

Seems like we are having some challenges figuring out adequate provisioning for the some of the tests we'd really like to run here.  Perf runs are a bit more complex to set up since we run on dedicated HW and not VMs. @jorive suggested to me privately that perhaps we move the Linux perf to a "rolling" basis -- triggered only by commits instead of PRs -- which I think is sensible if we can't handle the per-PR traffic load yet.

@RussKeldorph we should really settle on a policy here as having likely to fail long-running CI legs is not helpful to anyone. I would like to see us be more proactive and nimble with legs that start failing with any frequency.

image

**Comment by AndyAyersMS** [comment]
Odds of a successful perf run still not good.

I am going to merge and let the rolling CI perf runs pick this up.

**Comment by benaadams** [comment]
> Perf runs are a bit more complex to set up since we run on dedicated HW and not VMs. 

Bit of an aside; but interestingly .NET Core runs happily on a 272 thread Xeon Phi https://twitter.com/damageboy/status/928208914759462912 might be an interesting testbed and highlight contention issues well
