### PR TITLE
X86: Fix inline assertion

### LINKED ISSUE #6844: x86: JIT inliner assert running CscBench test
Same assert for both RyuJIT and legacy backend.

```
Assert failure(PID 17324 [0x000043ac], Thread: 9244 [0x241c]): Assertion failed 'm_IsPrejitRoot || (obs == InlineObservation::CALLSITE_TOO_MANY_LOCALS)' in 'Microsoft.CodeAnalysis.CommonReferenceManager`2[__Canon,__Canon][System.__Canon,System.__Canon]:ResolveMetadataReferences(ref,ref,byref,byref,byref,byref,byref,ref):struct:this' (IL size 1115)

    File: d:\gh\coreclr3\src\jit\inlinepolicy.cpp Line: 155
    Image: d:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

### PR DESCRIPTION
**Pull request by kyulee1**
Inline assertion occurred since we didn't bail out the inline fail case early.
During the test, I got another assertion about debug flag, which seems
suspicious, so I just deleted it.
This passes the legacy code path but still fails with x86 ryujit where the
test case is timed out.

Fixes #6844

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

**Comment by kyulee1** [comment]
@dotnet-bot test OSX x64 Checked Build and Test

**Comment by kyulee1** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
Did you check that the infinite loop is in the generated code, and not in the JIT?

**Comment by BruceForstall** [comment]
It seems strange to need to remove a long-existing assert now. What would have changed to require that?

**Comment by BruceForstall** [comment]
@kyulee1 ping

**Comment by kyulee1** [comment]
> Did you check that the infinite loop is in the generated code, and not in the JIT?
I don't get it. 

With regard to the existing assert, I hit it after fixing inline assertion issue. I'm not sure what the assertion actually means, and felt it's redundant.

**Comment by pgavlin** [comment]
> This passes the legacy code path but still fails with x86 ryujit where the
test case is timed out.

Just to be clear: the CscBench test times out once this change is applied?

**Comment by kyulee1** [comment]
Before this change, there was an assertion in inliner so we didn't see the bad codegen. 
After this change, we now see the latent issue: the time-out is from a bad codegen with regard to long (64 bit) compare expansion, which caused the infinite loop. Will create an issue today and asssign it to @adiaaida.

**Comment by mikedn** [comment]
> with regard to long (64 bit) compare expansion, which caused the infinite loop

Perhaps this is the same as #7038?

**Comment by kyulee1** [comment]
I didn't notice #7038 before. Yes, it appears the same issue that I'm seeing in cscbench where compare expansion is delayed until conditional jump while reloading register values transhes the register operands of compare.

**Comment by kyulee1** [comment]
I just updated the issue number in this change and the code snippet in the issue.

File: src/jit/codegenlegacy.cpp [hunk 1]
```diff
@@ -11371,8 +11371,6 @@ void CodeGen::genCodeForTreeSmpOpAsg(GenTreePtr tree)
 
             if (VarSetOps::IsMember(compiler, genUpdateLiveSetForward(op2), varDsc->lvVarIndex))
             {
-                noway_assert(compiler->opts.compDbgCode);
```
Comment (kyulee1) [inline src/jit/codegenlegacy.cpp]: Can anyone explain why we needed this assertion here?

Comment (CarolEidt) [inline src/jit/codegenlegacy.cpp]: If this assert fires, it indicates that the variable is live after encountering a def. I believe this assert should still be valid. You shouldn't delete it without understanding why it is firing.

---
In reply to: [78632294](https://github.com/dotnet/coreclr/pull/7012#discussion_r78632294) [](ancestors = 78632294)

Comment (kyulee1) [inline src/jit/codegenlegacy.cpp]: Ok. Then I will create an issue for it and revert the change since I don't think this has something to do with inline fix here.

**Comment by BruceForstall** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
It seems to me the check mentioned just above the assert (over in `fgMakeBasicBlocks`) should have prevented this assert from firing. So perhaps it is worth taking another look to understand what triggered this assert.
