### PR TITLE
ildasm: incorrect signess usage with char

### LINKED ISSUE #4746: Test: ildasm/ilasm failure with 'loopEH' testcase
The loopEH test case of CoreCLR, `tests/src/JIT/jit64/eh/basics/loopEH.cs`, has no issue of exception handling at ARM/Linux IF we directly execute the resulting `loopEH.exe`: it returns 100 as expected.

However, as `loopEH.sh` suggests, if we apply `ildasm` to `loopEH.exe` and try `ilasm` to the resulting assembly, we get the following error:
```
bash-3.2# ./ilasm -out=test.exe loopEH.dasm.il 

Microsoft (R) .NET Framework IL Assembler.  Version 4.5.22220.0
C
Assembling 'loopEH.dasm.il'  to EXE --> 'test.exe'
Source file is ANSI

Assembled method Program::Main
loopEH.dasm.il(152) : error : Unable to find forward reference label 'IL_012a' called from PC=59
loopEH.dasm.il(152) : error : Method 'Test' compilation failed.
Assembled method Program::.ctor

***** FAILURE ***** 
bash-3.2# 
```

This is a legit complaint from `ilasm` because the given disasm does have undefined label `IL_012a`. If I compile `loopEH.cs` in Linux/ARM with Roslyn and the today's `mscorlib.dll` and `coreclr`, it shows equivalent disasm that has the same error from `ilasm`.

This appears to be a BUG in `ildasm`, not CoreCLR's JIT or EH functionality.

```
bash-3.2# cat loopEH.dasm.il 

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.22220.0



// Metadata version: v4.0.30319
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:1:0:0
}
.assembly extern System.Collections
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
.assembly extern System.Console
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
.assembly loopEH
{
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                   63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [System.Runtime]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 02 00 00 00 00 00 ) 

  .publickey = (00 24 00 00 04 80 00 00 94 00 00 00 06 02 00 00   // .$..............
                00 24 00 00 52 53 41 31 00 04 00 00 01 00 01 00   // .$..RSA1........
                07 D1 FA 57 C4 AE D9 F0 A3 2E 84 AA 0F AE FD 0D   // ...W............
                E9 E8 FD 6A EC 8F 87 FB 03 76 6C 83 4C 99 92 1E   // ...j.....vl.L...
                B2 3B E7 9A D9 D5 DC C1 DD 9A D2 36 13 21 02 90   // .;.........6.!..
                0B 72 3C F9 80 95 7F C4 E1 77 10 8F C6 07 77 4F   // .r<......w....wO
                29 E8 32 0E 92 EA 05 EC E4 E8 21 C0 A5 EF E8 F1   // ).2.......!.....
                64 5C 4C 0C 93 C1 AB 99 28 5D 62 2C AA 65 2C 1D   // d\L.....(]b,.e,.
                FA D6 3D 74 5D 6F 2D E5 F1 7E 5E AF 0F C4 96 3D   // ..=t]o-..~^....=
                26 1C 8A 12 43 65 18 20 6D C0 93 34 4D 5A D2 93 ) // &...Ce. m..4MZ..
  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
.module loopEH.exe
// MVID: {f6bff5b9-562d-4aa0-a6c3-624df3302aa7}
.imagebase 0x00400000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000009    //  ILONLY
// Image base: 0xB6FD5000


// =============== CLASS MEMBERS DECLARATION ===================

.class private auto ansi beforefieldinit Program
       extends [System.Runtime]System.Object
{
  .method private hidebysig static int32 
          Main(string[] args) cil managed
  {
    .entrypoint
    // Code size       12 (0xc)
    .maxstack  8
    IL_0000:  ldnull
    IL_0001:  ldnull
    IL_0002:  ldnull
    IL_0003:  ldc.i4.0
    IL_0004:  ldc.i4.1
    IL_0005:  conv.i8
    IL_0006:  call       int32 Program::Test(class [System.Collections]System.Collections.Generic.List`1<string>,
                                             class [System.Collections]System.Collections.Generic.List`1<string>,
                                             string,
                                             int32,
                                             int64)
    IL_000b:  ret
  } // end of method Program::Main

  .method public hidebysig static int32  Test(class [System.Collections]System.Collections.Generic.List`1<string> liste,
                                              class [System.Collections]System.Collections.Generic.List`1<string> unused1,
                                              string unused2,
                                              int32 unused3,
                                              int64 p_lFirstId) cil managed
  {
    // Code size       119 (0x77)
    .maxstack  2
    .locals init (class [System.Runtime]System.Text.StringBuilder V_0,
             int32 V_1,
             valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<string> V_2,
             string V_3)
    IL_0000:  newobj     instance void class [System.Collections]System.Collections.Generic.List`1<string>::.ctor()
    IL_0005:  starg.s    liste
    IL_0007:  newobj     instance void [System.Runtime]System.Text.StringBuilder::.ctor()
    IL_000c:  stloc.0
    IL_000d:  ldc.i4.0
    IL_000e:  stloc.1
    IL_000f:  br.s       IL_004f

    IL_0011:  ldloc.0
    IL_0012:  ldarg.s    p_lFirstId
    IL_0014:  callvirt   instance class [System.Runtime]System.Text.StringBuilder [System.Runtime]System.Text.StringBuilder::Append(int64)
    IL_0019:  pop
    IL_001a:  ldarg.s    p_lFirstId
    IL_001c:  ldc.i4.1
    IL_001d:  conv.i8
    IL_001e:  add
    IL_001f:  starg.s    p_lFirstId
    IL_0021:  ldarg.0
    IL_0022:  callvirt   instance valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<!0> class [System.Collections]System.Collections.Generic.List`1<string>::GetEnumerator()
    IL_0027:  stloc.2
    IL_0028:  br.s       IL_0032

    IL_002a:  ldloca.s   V_2
    IL_002c:  call       instance !0 valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<string>::get_Current()
    IL_0031:  stloc.3
    IL_0032:  ldloca.s   V_2
    IL_0034:  call       instance bool valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<string>::MoveNext()
    IL_0039:  brtrue.s   IL_012a

    IL_003b:  leave.s    IL_004b

    IL_003d:  ldloca.s   V_2
    IL_003f:  constrained. valuetype [System.Collections]System.Collections.Generic.List`1/Enumerator<string>
    IL_0045:  callvirt   instance void [System.Runtime]System.IDisposable::Dispose()
    IL_004a:  endfinally
    IL_004b:  ldloc.1
    IL_004c:  ldc.i4.1
    IL_004d:  add
    IL_004e:  stloc.1
    IL_004f:  ldloc.1
    IL_0050:  ldc.i4.s   10
    IL_0052:  blt.s      IL_0111

    IL_0054:  ldloc.0
    IL_0055:  callvirt   instance string [System.Runtime]System.Object::ToString()
    IL_005a:  call       void [System.Console]System.Console::WriteLine(string)
    IL_005f:  ldloc.0
    IL_0060:  callvirt   instance string [System.Runtime]System.Object::ToString()
    IL_0065:  ldstr      "12345678910"
    IL_006a:  call       bool [System.Runtime]System.String::op_Equality(string,
                                                                         string)
    IL_006f:  brfalse.s  IL_0074

    IL_0071:  ldc.i4.s   100
    IL_0073:  ret

    IL_0074:  ldc.i4.s   101
    IL_0076:  ret
    IL_0077:  
    // Exception count 1
    .try IL_0028 to IL_003d finally handler IL_003d to IL_004b
  } // end of method Program::Test

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [System.Runtime]System.Object::.ctor()
    IL_0006:  ret
  } // end of method Program::.ctor

} // end of class Program


// =============================================================

// *********** DISASSEMBLY COMPLETE ***********************
```

### PR DESCRIPTION
**Pull request by myungjoo**
Treat pCode signed. It is originally BYTE, not unsigned char.

Fix #4746

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>

The incorrect branch reference of CoreCLR Unit Test Case `loopEH.cs` is cured with this:
```
   IL_0039:  brtrue.s   IL_012a
```
is corrected as:
```
   IL_0039:  brtrue.s   IL_002a
```
as supposed.

### CODE REVIEW

File: src/ildasm/dis.cpp [hunk 1]
```diff
@@ -1646,7 +1646,7 @@ BOOL Disassemble(IMDInternalImport *pImport, BYTE *ILHeader, void *GUICookie, md
 
             case ShortInlineBrTarget:
             {
-                char offset = (char) pCode[PC];
+                signed char offset = (signed char) pCode[PC];
```
Comment (manu-silicon) [inline src/ildasm/dis.cpp]: Because offset is just used once here, I think we should just have:
long offset = pCode[PC];

Comment (kyulee1) [inline src/ildasm/dis.cpp]: LGTM as long as it works. BTW, char is already signed and I wonder why we need signed keyword explicitly. I understand pCode is declared as BYTE* which is unsigned one, but casting to (char) should work. I guess this might be a bug (or different semantic) in arm compiler that you're using. I couldn't make a simple c++ cutdown to repro this with x64 clang though.

Comment (myungjoo) [inline src/ildasm/dis.cpp]: `pCode` is `BYTE`, which is `unsigned char` or `uint8`.
`long offset = pCode[PC]` or `long offset = (long) pCode[PC]` will revive the bug.

Comment (kyulee1) [inline src/ildasm/dis.cpp]: I searched some online, and it appears depending on machines, default char could be either signed or unsigned. I guess yours seems to be the latter.
Can you do one more testing by adding `-fsigned-char` under Unix path in CMakeLists.txt at the top of coreclr repo without any source change?
My concern is if singleness of char is inconsistent, we could have a similar issue in other place as well.

And also with regard to `long`, in fact we should use `int` which is 32 bit since MS compiler handles  `long` as `int` with the same size 32 bit while other platforms do not.

Comment (myungjoo) [inline src/ildasm/dis.cpp]: Yes, ARM assumes char unsigned: http://infocenter.arm.com/help/topic/com.arm.doc.faqs/ka11308.html

Because there might be other signedness sensitive char logic, I'll try `-fsigned-char` and replace the current commit with it if it does fine.

Comment (hqueue) [inline src/ildasm/dis.cpp]: I think using `-fisnged-char` may solve the problem.
However I prefer modifying C/C++ source code to `signed char` if we need signed `char`, because C/C++ doesn't define char is sign or unsigned.
And compiler suggests using `signed char` and `unsigned char` when sign of char matters.

Source: https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html
GCC also suggests that
"-funsigned-char
Let the type char be unsigned, like unsigned char.
Each kind of machine has a default for what char should be. It is either like unsigned char by default or like signed char by default.

Ideally, a portable program should always use signed char or unsigned char when it depends on the signedness of an object. But many programs have been written to use plain char and expect it to be signed, or expect it to be unsigned, depending on the machines they were written for. This option, and its inverse, let you make such a program work with the opposite default.

The type char is always a distinct type from each of signed char or unsigned char, even though its behavior is always just like one of those two. "

**Comment by myungjoo** [comment]
@kyulee1 Tested and verified with `-fsigned-char`.

> And also with regard to long, in fact we should use int which is 32 bit since MS compiler handles long as int with the same size 32 bit while other platforms do not.

`long` is `int` in ARM as well (both are signed 32b): http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0348c/Babfcgfc.html

**Comment by kyulee1** [comment]
LGTM. Thanks for testing it! `long` vs `int` is different for other x64, which is a benign issue.

File: src/ildasm/dis.cpp (hunk 1 above)
Comment (kyulee1) [inline src/ildasm/dis.cpp]: > However I prefer modifying C/C++ source code to signed char if we need signed char, because C/C++ doesn't define char is sign or unsigned.

This is ported code like other pieces with the assumption of MS compiler. We cannot simply find all such instances. Our porting strategy is to lay PAL or equivalent operation with MS compiler in case there is difference like this.

Comment (hqueue) [inline src/ildasm/dis.cpp]: I see. Now I understand what PAL does exactly and thank you for sharing the strategy :)
