### PR TITLE
Fix/4859 Unit Test 143837 Fail

### LINKED ISSUE #4859: Unit Test Fail: 143837 ARM/Linux (Cannot Handle NullReference Exception)
The CoreCLR Unittest of `JIT/jit64/gc/regress/vswhidbey/143837` fails at ARM/Linux:

```
bash-3.2# gdb --args ./corerun 143837.exe 
...
(gdb) run
...

Program received signal SIGSEGV, Segmentation fault.
0xb650c974 in JIT_WriteBarrier () at patchedcode.S:413
413	patchedcode.S: No such file or directory.
(gdb) bt
#0  0xb650c974 in JIT_WriteBarrier () at patchedcode.S:413
#1  0xb1cf095c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

I'll update as soon as some useful data comes out.

### PR DESCRIPTION
**Pull request by myungjoo**
1. Handle hardware exception unwinding seperately (suggested/written by janvorli, tested by myungjoo)
2. Fix function range check for ARM-Thumb instructions.

Fix #4859

### CODE REVIEW

**Comment by myungjoo** [comment]
@dotnet-bot Test OSX x64 Checked Build and Test Please

File: src/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -4635,33 +4635,43 @@ VOID DECLSPEC_NORETURN UnwindManagedExceptionPass1(PAL_SEHException& ex, CONTEXT
     EEPOLICY_HANDLE_FATAL_ERROR(COR_E_EXECUTIONENGINE);
 }
 
-VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex)
+VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex, bool isHardwareException)
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: I have figured out a simplification - if we changed the SEHProcessException in src/pal/src/exception/seh.cpp so that we add 'pointers->ContextRecord.ContextFlags |= CONTEXT_EXCEPTION_ACTIVE' to the beginning of the function, then we don't have to add the isHardwareException parameter anywhere. In the code below, we would replace 'if (isHardwareException)' by 'if (ex.ContextRecord.ContextFlags & CONTEXT_EXCEPTION_ACTIVE)' and remove the setting of the flag.
Could you please change it this way?
 Also, the source code alignment is broken below - you seem to have tabs at the beginning of some lines.

Comment (myungjoo) [inline src/vm/exceptionhandling.cpp]: Yeah. That looks better to me as well.

I'll change the alignment as well. (my vim has been configured for Linux kernel. :( I might need to get it dual-configured)

**Comment by myungjoo** [comment]
@janvorli  Lookd like the "cleaned up" version 2 breaks Windows?

File: src/vm/exceptionhandling.cpp [hunk 2]
```diff
@@ -4643,24 +4643,34 @@ VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex)
...
-
-            if (Thread::VirtualUnwindToFirstManagedCallFrame(&frameContext) == 0)
+            if (ex.ContextRecord.ContextFlags & CONTEXT_EXCEPTION_ACTIVE)
             {
-                // There are no managed frames on the stack, so we need to continue unwinding using C++ exception
-                // handling
-                break;
-            }
+                frameContext = ex.ContextRecord;
+                frameContext.ContextFlags |= CONTEXT_EXCEPTION_ACTIVE;
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: This is not needed, we've just checked that the flag is set.

File: src/vm/exceptionhandling.cpp [hunk 3]
```diff
@@ -4677,6 +4687,7 @@ VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex)
         catch (PAL_SEHException& ex2)
         {
             ex = ex2;
+            ex.ContextRecord.ContextFlags &= ~CONTEXT_EXCEPTION_ACTIVE;
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: This is not needed, the exception contains correct flags

File: src/vm/exceptionhandling.cpp [hunk 4]
```diff
@@ -4643,24 +4643,34 @@ VOID DECLSPEC_NORETURN DispatchManagedException(PAL_SEHException& ex)
...
-                // handling
-                break;
-            }
+                frameContext = ex.ContextRecord;
+                frameContext.ContextFlags |= CONTEXT_EXCEPTION_ACTIVE;
+                if (IsIPInMarkedJitHelper(GetIP(&frameContext)))
+                {
+                    PAL_VirtualUnwind(&frameContext, NULL);
+                }
+            } else {
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: A nit - coding style, could you please change it to 
```C++
}
else
{
```

File: src/vm/excep.cpp [hunk 5]
```diff
@@ -7280,8 +7280,17 @@ bool IsIPInMarkedJitHelper(UINT_PTR uControlPc)
 {
     LIMITED_METHOD_CONTRACT;
 
+#ifdef _ARM_
```
Comment (janvorli) [inline src/vm/excep.cpp]: Could you please make it _ARM_ && FEATURE_PAL so that it doesn't interfere with how windows do that?

File: src/vm/excep.cpp [hunk 6]
```diff
@@ -7280,8 +7280,17 @@ bool IsIPInMarkedJitHelper(UINT_PTR uControlPc)
...
+    // The least bit denoting THUMB might confuse the range check because
+    // PC values have the least bit reset. It causes a bug if PC is at
+    // the first byte of the function range.
+#define CHECK_RANGE(name) \
+    if ((GetEEFuncEntryPoint(name)|0x1) <= (uControlPc|0x1) && (uControlPc|0x1) < (GetEEFuncEntryPoint(name##_End)|0x1)) return true;
```
Comment (janvorli) [inline src/vm/excep.cpp]: Isn't the range we get from GetEEFuncEntryPoint "normalized"? In that case, we can just set or clear the bit in the uControlPc.

**Comment by janvorli** [comment]
@myungjoo there is no way for it to break windows, none of this code is even compiled for windows x64.

**Comment by janvorli** [comment]
@myungjoo do you think it would be possible for you to make the few changes that I've just asked for today so that we can merge it in today?

**Comment by myungjoo** [comment]
No, sorry but I will be able to continue next week. (moving)

**Comment by janvorli** [comment]
@myungjoo Ok, no problem I will then probably take the change except of the IsIPInMarkedJitHelper part and merge it in.

File: src/vm/excep.cpp (hunk 6 above)
Comment (myungjoo) [inline src/vm/excep.cpp]: `GetEEFuncEntryPoint` has been showing the address of `name`+1 if the instruction in `name` is Thumb, which made the CHECK_RANGE incorrect if uControlPC is pointing at `name`+0, which often does with JIT_WriteBarrier.

It is right that we only need to set 0x1 of uControlPC; however, can we guarantee that GetEEFuncEntryPoint() is going to be always set 0x1?

File: src/vm/exceptionhandling.cpp (hunk 3 above)
Comment (myungjoo) [inline src/vm/exceptionhandling.cpp]: Uh.. then `isHardwareException = false;` of the previous version was not required?

File: src/vm/excep.cpp (hunk 5 above)
Comment (myungjoo) [inline src/vm/excep.cpp]: sure.

File: src/vm/excep.cpp (hunk 6 above)
Comment (janvorli) [inline src/vm/excep.cpp]: I would guess it is the case. @jkotas, am I right? Does the GetEEFuncEntryPoint on ARM always return address with the bit 0 set?

File: src/vm/exceptionhandling.cpp (hunk 3 above)
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: It was, because we were not using the contents of the context, but tracking it separately using that bool.

File: src/vm/excep.cpp (hunk 6 above)
Comment (jkotas) [inline src/vm/excep.cpp]: `GetEEFuncEntryPoint` returns `PCODE`. `PCODE` is expected to have the thumb bit set (https://github.com/dotnet/coreclr/blob/master/src/inc/daccess.h#L2410).

There is `PCODEToPINSTR` macro that should be used to do the kind of adjustment like what you are doing here, without ifdefs.

However, it may be better to set the thumb bit during unix context -> CONTEXT conversion in PAL instead. `CONTEXT::Pc` has the bit set on Windows ARM, and it is likely that number of random places like this one may took subtle decency on it. Setting the bit in the PAL will save you from chasing all of them down.

Comment (myungjoo) [inline src/vm/excep.cpp]: There are possibilities that we might hit a stack frame with ARM instructions (native stacks). I do not think it is safe to do |0x1 on PC at PAL/ARM/Linux.

I'll do
```
#define CHECK_RANGE(name) \
    if (PCODEToPINSTR(GetEEFuncEntryPoint(name)) <= PCODEToPINSTR(uControlPc) && PCODEToPINSTR(uControlPc) < PCODEToPINSTR(GetEEFuncEntryPoint(name##_End))) return true;
```

**Comment by janvorli** [comment]
It seems that it would be better to follow @jkotas's advice and make the context for hardware exceptions on arm have the bit 0 set instead of this change. Since we don't handle hardware exceptions in other code than the jitted managed code or the helpers, we can be sure that setting the bit is ok - if we hit that exception in some external ARM code, it would not match our tests with out without the bit set anyways.
It looks like a good place to do that would be again the beginning of the SEHProcessException (ifdefed for ARM only).
Or alternatively, if the CPSR "T" bit is set properly in the context passed to the signal handler, we can set the PC bit zero based on that.

**Comment by myungjoo** [comment]
@janvorli, There are other execution paths that covers IsIPInMarkedJitHelper(), is it really safe to set 0x1 of PC at SEHProcessException() only?

```
vm/exceptionhandling.cpp:                if (IsIPInMarkedJitHelper(GetIP(&frameContext)))
vm/exceptionhandling.cpp:        IsIPInMarkedJitHelper(controlPc));
vm/exceptionhandling.cpp:            if (IsIPInMarkedJitHelper(controlPc))
vm/excep.cpp:bool IsIPInMarkedJitHelper(UINT_PTR uControlPc)
vm/excep.cpp:    BOOL fExcluded = IsIPInMarkedJitHelper((UINT_PTR)f_IP);
vm/excep.h:bool IsIPInMarkedJitHelper(UINT_PTR uControlPc);
```

**Comment by janvorli** [comment]
All the other cases except the `vm/excep.cpp:    BOOL fExcluded = IsIPInMarkedJitHelper((UINT_PTR)f_IP);` come from the HandleHardwareException and the one that doesn't is not called on Unix.
However, you've brought up a good point, since it made me realize that we need to add the same IP adjustment to inject_activation_handler right after we extract the winContext.

**Comment by myungjoo** [comment]
Maybe, we need a PC value comparison macro used globally in CoreCLR that ignores address bits below the alignment.
e.g., 
```
#ifdef _ARM_
#define RealAddress(x) (x & ~0x1)
...
```
or
```
#ifdef _ARM_
#define ComparePC_LTE(x, y) ((x<<1) <= (y<<1))
```

Anyway, do you think that it'd be better to correct the least bit at the caller (`SEHProcessException`), not at the callee who does the comparison (`IsIPInMarkedJitHelper`) although for the case of IsIPInMarkedJitHelper with hardware exceptions, it is also correct to do so with `SEHProcessException`. The same question applies to `inject_activation_handler` case as well.

**Comment by janvorli** [comment]
@myungjoo - @jkotas said that all CoreCLR assumes that the PC address in the context on ARM has always the bit set, since that's what Windows do and the ARM related code in the CoreCLR expects. That's why I believe the PAL is the right place to ensure that.

**Comment by myungjoo** [comment]
Ok.. then. I'll try to gatekeep unwind-context <--> wincontext.

**Comment by janvorli** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by janvorli** [comment]
@dotnet-bot test  Ubuntu x64 Checked Build and Test please

File: src/pal/src/exception/seh.cpp [hunk 7]
```diff
@@ -212,6 +212,12 @@ VOID
 SEHProcessException(PEXCEPTION_POINTERS pointers)
 {
     pointers->ContextRecord->ContextFlags |= CONTEXT_EXCEPTION_ACTIVE;
+#if defined(_ARM_) && defined(FEATURE_PAL)
```
Comment (jkotas) [inline src/pal/src/exception/seh.cpp]: This `FEATURE_PAL` condition is not needed here because of this code lives in PAL - `FEATURE_PAL` is always defined for it.

**Comment by jkotas** [comment]
LGTM modulo minor comment.

File: src/pal/src/exception/seh-unwind.cpp [hunk 8]
```diff
@@ -141,7 +141,7 @@ static void UnwindContextToWinContext(unw_cursor_t *cursor, CONTEXT *winContext)
 #elif defined(_ARM_)
     unw_get_reg(cursor, UNW_REG_SP, (unw_word_t *) &winContext->Sp);
     unw_get_reg(cursor, UNW_REG_IP, (unw_word_t *) &winContext->Pc);
-    winContext->Pc &= ~0x1;
+    winContext->Pc |= 0x1;
```
Comment (janvorli) [inline src/pal/src/exception/seh-unwind.cpp]: Ah, I have not realized that we were explicitly clearing the bit. So maybe the value extracted from the cursor has the bit set correctly?

File: src/pal/src/exception/seh.cpp [hunk 9]
```diff
@@ -212,6 +212,12 @@ VOID
...
+    // WinContext assumes that the least bit of Pc is always 1 (denoting thumb)
+    // although the pc value retrived from native context might not have set the least bit.
+    // This becomes especially problematic if the context is on the JIT_WRITEBARRIER.
+    pointers->ContextRecord->Pc |= 0x1;
```
Comment (janvorli) [inline src/pal/src/exception/seh.cpp]: We should to do that in the CONTEXTFromNativeContext instead. That way, it would cover both activation injection and hardware exceptions. Also, no need to check for FEATURE_PAL in PAL.

It should be here:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/thread/context.cpp#L491

File: src/pal/src/exception/seh-unwind.cpp [hunk 10]
```diff
@@ -108,7 +108,7 @@ static void WinContextToUnwindContext(CONTEXT *winContext, unw_context_t *unwCon
     unwContext->regs[12] = 0;
     unwContext->regs[13] = winContext->Sp;
     unwContext->regs[14] = winContext->Lr;
-    unwContext->regs[15] = winContext->Pc;
+    unwContext->regs[15] = winContext->Pc & ~0x1;
```
Comment (janvorli) [inline src/pal/src/exception/seh-unwind.cpp]: I wonder why this is needed - I know it was getting the Pc with bit 0 cleared before this change due to the fact that it was cleared in UnwindContextToWinContext. I just wonder how the libunwind handles code with mixed ARM and THUMB frames in general.

File: src/pal/src/exception/seh-unwind.cpp (hunk 8 above)
Comment (myungjoo) [inline src/pal/src/exception/seh-unwind.cpp]: A few months ago, when Linux/ARM CoreCLR was extremely unstable, ensuring the last bit unset for libunwind-arm helped stabilizing exception handling and GC. However, with much more robust Linux/ARM CoreCLR support, such workaround might be unnecessary. I'll test with some cases.

**Comment by jkotas** [comment]
LGTM
