### PR TITLE
Disable IJW tests on Windows 7.

### LINKED ISSUE #21796: IJW tests continue failing on Windows 7
I see these failures in my private runs in Azure DevOps (Checked build) as well as in buildpipeline (Release build) on Windows 7

**An example of failures:**

**Checked** (e.g. https://mc.dot.net/#/user/4ae9b87d-f80b-4977-8984-b4c67c7cd398/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F2~2Fmerge/test~2Ffunctional~2Fcli~2Fpri0/20190102.71/workItem/Interop.IJW/wilogs)
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'IjwNativeDll, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
         at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
         at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
         at System.Reflection.Assembly.Load(String assemblyString)
         at ManagedCallingNative.ManagedCallingNative.Main(String[] args)

Return code:      1
Raw output file:      C:\dotnetbuild\work\d0bbea5e-181f-468b-ad47-e70059b15b5c\Work\6499e7bf-8622-4ac9-abcc-ac2753c5b9c5\Unzip\Reports\Interop.IJW\ManagedCallingNative\ManagedCallingNative\ManagedCallingNative.output.txt
Raw output:
BEGIN EXECUTION
       "C:\dotnetbuild\work\d0bbea5e-181f-468b-ad47-e70059b15b5c\Payload\corerun.exe" ManagedCallingNative.exe 
      Beginning scenario: Calling from managed to native IJW code
      Beginning test case Load IJW dll via reflection at 1/3/2019 3:35:08 AM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
     

      Expected: 100
      Actual: -532462766
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\d0bbea5e-181f-468b-ad47-e70059b15b5c\Payload
> C:\dotnetbuild\work\d0bbea5e-181f-468b-ad47-e70059b15b5c\Work\6499e7bf-8622-4ac9-abcc-ac2753c5b9c5\Unzip\ManagedCallingNative\ManagedCallingNative\ManagedCallingNative.cmd

      Expected: True
      Actual:   False
      Stack Trace:
       F:\vsagent\78\s\bin\tests\Windows_NT.x64.Checked\TestWrappers\Interop.IJW\Interop.IJW.XUnitWrapper.cs(109,0): at Interop_IJW._ManagedCallingNative_ManagedCallingNative_ManagedCallingNative_._ManagedCallingNative_ManagedCallingNative_ManagedCallingNative_cmd()
```

**Release** (e.g. https://mc.dot.net/#/product/netcore/30/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20190103.03/workItem/Interop.IJW.XUnitWrapper/analysis/xunit/Interop_IJW._ManagedCallingNative_ManagedCallingNative_ManagedCallingNative_~2F_ManagedCallingNative_ManagedCallingNative_ManagedCallingNative_cmd) 
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'IjwNativeDll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.Load(String assemblyString)
   at ManagedCallingNative.ManagedCallingNative.Main(String[] args)


Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\111b4f1d-ef18-4dee-b5f0-1be2df78d6d0\\Work\\c1be48e3-db4f-40c3-bf1f-f264e42c2aaa\\Unzip\\Reports\\Interop.IJW\\ManagedCallingNative\\ManagedCallingNative\\ManagedCallingNative.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\111b4f1d-ef18-4dee-b5f0-1be2df78d6d0\\Payload\\corerun.exe\" ManagedCallingNative.exe 
Beginning scenario: Calling from managed to native IJW code
Beginning test case Load IJW dll via reflection at 1/3/2019 3:07:54 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
```

It seems that the tests fail to load *api-ms-win-core-** DLLs while searching in test directory (i.e. ManagedCallingNative) and %PATH% (but not in the directory containing corerun.exe - is this desired behavior?). 

After I had installed Windows 10 Universal C Runtime for Windows 7 from https://www.microsoft.com/en-us/download/details.aspx?id=48234 the original issue disappeared and now the tests fail with the assertion

```
BEGIN EXECUTION
 "C:\git\Core_Root\corerun.exe" ManagedCallingNative.exe 
Beginning scenario: Calling from managed to native IJW code
Beginning test case Load IJW dll via reflection at 1/3/2019 4:44:04 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Assert failure(PID 2700 [0x00000a8c], Thread: 2688 [0x0a80]): TypeFromToken(tok) == mdtMethodDef || TypeFromToken(tok) == mdtMemberRef

<no module>! <no symbol> + 0x0 (0x00000000`00000000)
    File: d:\git\coreclr2\src\vm\ceeload.cpp Line: 6566
    Image: C:\git\Core_Root\CoreRun.exe

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
```
The same effect could be done by adding Core_Root to the Path.

At this point, I am not sure how to proceed.

@morganbr @AaronRobinsonMSFT Can you please take a look at the failure? I am planning to disable the IJW tests for now to get green CI - please let me know if you object

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Windows 7 loads desktop mscoree.dll when loading System.Private.CoreLib, before we can load our fake mscoree. So, when IJW modules are loaded, they load the real mscoree.dll, which breaks coreclr's IJW loading. Once we have true .NET Core IJW support in the MSVC++ compiler and .NET Core, then we'll be able to reenable these tests on Win7.

Fixes #21796.

cc: @RussKeldorph @echesakovMSFT

### CODE REVIEW

File: tests/src/Interop/IJW/ManagedCallingNative/ManagedCallingNative.cs [hunk 1]
```diff
@@ -14,7 +14,8 @@ class ManagedCallingNative
     {
         static int Main(string[] args)
         {
-            if(Environment.OSVersion.Platform != PlatformID.Win32NT)
+            // Disable running on Windows 7 until IJW activation work is complete. See dotnet/coreclr#21796
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/IJW/ManagedCallingNative/ManagedCallingNative.cs]: I would prefer to avoid putting bug numbers in code. I am hoping the bug in question would point to this location instead.
