### PR TITLE
Fix SIMD Scalar Move Encoding: VEX.L should be 0

### LINKED ISSUE #8328: SIMD Scalar move instruction should encoded VEX.L = 0 instead of VEX.L = 1
Currently in RyuJIT genSIMDScalarMove() when it's on an AVX system and useAVX() is enabled, SIMD scalar move instructions such as such as vmovlpd, vmovlps, vmovhps, vmovhps and vmovss are been encoded as VEX.L to be 1, however, JIT should ensure VEX.L is 0 for those SIMD Scalar move instructions. 

For example, following instruction: 

vmovss xmm4, xmm4, xmm0 

Currently it is encoded as: C4E1**5E**10E0

This instruction is encoded as 3-byte VEX form, VEX.L is bit[2] on Byte 2:

For 5**E** = 01011**1**10 as binary format, VEX.L = 1 {bit[2] = 1}

The correct encoding should be: C4E1**5A**10E0, because

For 5**A** = 01011**0**10 as binary format, VEX.L = 0 {bit[2] = 0}

JIT should ensure VEX.L=0 here because encoding VMOVSS with VEX.L=1 may encounter unpredictable behavior across different processor generations.

### PR DESCRIPTION
**Pull request by litian2025**
For SIMD Scalar Move instructions such as vmovlpd, vmovlps, vmovhps,
vmovhps and vmovss on AVX system, JIT should ensure that those
instructions are encoded with VEX.L=0, because encoding them with
VEX.L=1 may encounter unpredictable behavior across different
processor generations. The reason of VEX.L is encoded with 1 is
because JIT calls compiler->getSIMDVectorType() which returns
EA_32BYTE, and it is been passed into emitter AddVexPrefix() which
ends up encoded VEX.L=1, the fix is to pass EA_16BYTE for those
instructions to ensure that VEX.L=0 at emitter AddVexPrefix()

Fix #8328

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
@sivarv @CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/simdcodegenxarch.cpp [hunk 1]
```diff
@@ -493,7 +493,9 @@ void CodeGen::genSIMDScalarMove(var_types type, regNumber targetReg, regNumber s
                         // In general, when we use a three-operands move instruction, we want to merge the src with
                         // itself. This is an exception in that we actually want the "merge" behavior, so we must
                         // specify it with all 3 operands.
-                        inst_RV_RV_RV(ins, targetReg, targetReg, srcReg, emitTypeSize(targetType));
```
Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: >emitTypeSize(targetType)); [](start = 73, length = 26)

We are supposed to use emitTypeSize(type) and type here.

Same comment applies to lines 502, 524, 542 and 566 as well.

In general since this routine is meant for scalar move, it should be using type/emitTypeSize(type)  instead of targetType/emitTypeSize(targetType) and should hard code specific SIMD type while emitting insertps and shift left.
We can completely do away with targetType.

**Comment by litian2025** [comment]
@sivarv, Could you please review the updated PR when you get a chance? Removed "var_types targetType = compiler->getSIMDVectorType();" and get the targetType via parameter passing, which appears to be a better and cleaner approach.

File: src/jit/simdcodegenxarch.cpp [hunk 2]
```diff
@@ -475,9 +476,9 @@ instruction CodeGen::getOpForSIMDIntrinsic(SIMDIntrinsicID intrinsicId, var_type
 // Notes:
 //    This is currently only supported for floating point types.
 //
-void CodeGen::genSIMDScalarMove(var_types type, regNumber targetReg, regNumber srcReg, SIMDScalarMoveType moveType)
+void CodeGen::genSIMDScalarMove(
+    var_types targetType, var_types type, regNumber targetReg, regNumber srcReg, SIMDScalarMoveType moveType)
```
Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: I find it confusing to have both targetType and type parameters.  It would be better to name params targetType/type as simdType/baseType respectively.

Besides genSIMDScalarMove() is selecting instruction based on 'type' parameter but is passing targetType, which doesn't seem correct to me.

I still think in all the places where instruction selection is based on 'type' should use type/emitTypeSize(type) instead of targetType/emitTypeSize(targetType).

**Comment by litian2025** [comment]
@sivarv could you please review the updated PR and let me know that if there's anything else need to be done? Thanks.

**Comment by danmosemsft** [comment]
@sivarv for new CR.

File: src/jit/simdcodegenxarch.cpp [hunk 3]
```diff
@@ -464,7 +464,8 @@ instruction CodeGen::getOpForSIMDIntrinsic(SIMDIntrinsicID intrinsicId, var_type
 // to target mm reg, zeroing out the upper bits if and only if specified.
 //
 // Arguments:
-//    type             the type of value to be moved
+//    targetType       the targe type
```
Comment (litian2025) [inline src/jit/simdcodegenxarch.cpp]: Nice catch, will change it to target.

File: src/jit/simdcodegenxarch.cpp [hunk 4]
```diff
@@ -475,10 +476,10 @@ instruction CodeGen::getOpForSIMDIntrinsic(SIMDIntrinsicID intrinsicId, var_type
 // Notes:
 //    This is currently only supported for floating point types.
 //
-void CodeGen::genSIMDScalarMove(var_types type, regNumber targetReg, regNumber srcReg, SIMDScalarMoveType moveType)
+void CodeGen::genSIMDScalarMove(
+    var_types targetType, var_types baseType, regNumber targetReg, regNumber srcReg, SIMDScalarMoveType moveType)
```
Comment (litian2025) [inline src/jit/simdcodegenxarch.cpp]: However, I do see the targetType is been used in this method at  "case SMT_ZeroInitUpper:" (when it's SSE, not within FEATURE_AVX_SUPPORT define) when srcReg != targetReg, it is been used in genSIMDZero(targetType, TYP_FLOAT, targetReg);

Comment (litian2025) [inline src/jit/simdcodegenxarch.cpp]: thanks, I will fix the typo, squash the commits into 1, update the PR and ping you to merge it.

Comment (litian2025) [inline src/jit/simdcodegenxarch.cpp]: @sivarv PR has been updated, please merge it at your convenient time. Thanks.
