### PR TITLE
Fix the codegen for by-value struct args on x86.

### LINKED ISSUE #7088: RyuJIT x86: [GCStress=0xC][ZapDisable=1] Consistency check failed: AV in clr at CLRVectoredExceptionHandlerShim
In Windows_NT.ryujit.x86.Checked.gc_stress.0xc.zap_disable.1

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_GCStress=0xc
set COMPlus_ZapDisable=1

/Regressions/common/date/date.cmd

> D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\TestWrappers\Regressions\Regressions.XUnitWrapper.cs(450): error : Regressions._common_date_date_._common_date_date_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---d780febb\tests\runtest.proj]
> Assert failure(PID 3408 [0x00000d50], Thread: 8552 [0x2168]): Consistency check failed: AV in clr at this callstack:
> ------
> CORECLR! CLRVectoredExceptionHandlerShim + 0x194 (0x716d2604)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> NTDLL! KiUserExceptionDispatcher + 0xF (0x77a105bf)
> CORECLR! PreStubWorker + 0x3BE (0x717afd8e)
> CORECLR! ThePreStub + 0x11 (0x716738f2)
> CORECLR! CallDescrWorkerInternal + 0x34 (0x71673501)
> CORECLR! CallDescrWorker + 0xDB (0x718a36a9)
> CORECLR! CallDescrWorkerWithHandler + 0x137 (0x718a3845)
> CORECLR! MethodDescCallSite::CallTargetWorker + 0x894 (0x718a410d)
> CORECLR! MethodDescCallSite::Call_RetArgSlot + 0x8B (0x718644d7)
> CORECLR! ``RunMain'::`21'::__Body::Run'::`5'::__Body::Run + 0x15D (0x7186a2ce)
> CORECLR! `RunMain'::`21'::__Body::Run + 0x64 (0x7186a46e)
> CORECLR! RunMain + 0xD1 (0x7186a5a1)
> CORECLR! Assembly::ExecuteMainMethod + 0x144 (0x718664e0)
> CORECLR! CorHost2::ExecuteAssembly + 0x23C (0x715f2cec)
> CORERUN! TryRun + 0x567 (0x002ed884)
> CORERUN! wmain + 0x98 (0x002ee41c)
> CORERUN! invoke_main + 0x1E (0x0030da5e)
> -----
> .AV on tid=0x2168 (8552), cxr=02A4D364, exr=02A4D314
> FAILED: false
> CORECLR! CHECK::Trigger + 0x30E (0x715ba13c)
> CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x229 (0x716d23c2)
> CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4B (0x716d206e)
> CORECLR! CLRVectoredExceptionHandler + 0x138 (0x716d201b)
> CORECLR! CLRVectoredExceptionHandlerShim + 0xBB (0x716d252b)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> NTDLL! KiUserExceptionDispatcher + 0xF (0x77a105bf)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> File: d:\j\workspace\x86_ryujit_ch---d780febb\src\vm\excep.cpp Line: 8141
> Image: D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\Reports\Regressions\common\date\date.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---d780febb\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" date.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by pgavlin**
Fix the codegen for by-value struct args on x86.
Although the existing code generation for by-value struct args containing
GC references on x86 was correct with respect to the layout of the data
being passed, it was not correct with respect to the invariants necessary
for the GC info encoder.

The existing codegen for by-value struct args--whether represented by
`GT_OBJ` or `GT_FIELD_LIST` nodes--takes what is essentially the
following approach:

    sub esp, argument_size
    mov [esp + offset_0], field_0
    mov [esp + offset_1], field_1
    ...
    mov [esp + offset_n], field_n

Although this puts the correct data in the correct locations, the
emitter is unable to recognize that a GC info update is requires if any
of the `mov` instructions write a GC reference to the stack: instead,
on x86, `push` instructions must be used to write GC references on the
stack. Furthermore, the stack must be kept 4-byte aligned.

This change modifies the code generator to use `push` instructions to
write outgoing GC references to the stack while obeying the alignment
invariant required by the GC encoding. For outgoing by-value struct
args represented by `GT_OBJ`, this results in very straightforward code:

    push [val_addr]
    push [val_addr + 4]
    ...
    push [val_addr + n]

For args represented by `GT_FIELD_LIST`, the picture is a bit more
complicated as the stack must be kept 4-byte aligned. Handling of these
args is split into two cases: if a field list contains no GC references
and is larger than 16 bytes or contains any fields that cannot be
treated as a 4-byte-aligned, int32-sized value, the argument is passed
using the `sub esp, arg_size; mov [esp + offset], field` approach.
Otherwise--if the struct contains any GC references or is smaller than
16 bytes and only contains fields that can be treated as slots--the
argument is passed using the following approach:
- If a field is a GC reference or can be treated as a 4-byte slot, the
  field is stored to the stack using a `push` instruction.
- Otherwise, the stack pointer is first adjusted to the next 4-byte
  aligned address after the offset of the field and the field is
  stored to the appropriate address using a `mov`.

For example, given the following IR:

     t55 =    lclVar    bool   V06 tmp4         u:6 esi REG esi RV $40

    t138 =    dconst    float  0.00000000000000000 REG mm0 $80

           /--*  t138   float
           +--*  t55    bool
    t139 = *  <fldList> void   float at offset 4 REG NA $180

           /--*  t139   void
    t152 = *  putarg_stk [+0x00] void   REG NA

The backend will generate the following code:

    sub      esp, 8
    movss    dword ptr [esp+04H], xmm0
    mov      dword ptr [esp], esi

And given the following IR:

    t13 =    lclVar    ref    V04 tmp1         u:2 esi (last use) REG esi RV $1c0

    t45 =    lclVar    int    V05 tmp2         u:2 eax (last use) REG eax RV $200

          /--*  t45    int
          +--*  t13    ref
    t46 = *  <fldList> void   int at offset 4 REG NA $240

The backend will instead generate the following:

    push     eax
    push     esi

These changes also produce beneficial diffs: for example, the native image
for System.Private.CoreLib.dll has diffs in ~1000 methods for an overall
size improvement of 1%.

Fixes #7088.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @BruceForstall @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test Windows_NT x86 ryujit Checked gcstress0xc
@dotnet-bot test Windows_NT x86 ryujit Checked gcstress0xc_zapdisable

**Comment by CarolEidt** [comment]
Do you know if there is any fundamental reason that the emitter couldn't be modified (presumably in future) to handle the non-push approach? When there are double fields and/or holes, it could be more efficient.

File: src/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -7397,30 +7397,106 @@ void CodeGen::genPutArgStk(GenTreePtr treeNode)
     }
     else if (data->OperGet() == GT_FIELD_LIST)
     {
-        GenTreeFieldList* fieldList = data->AsFieldList();
-        // TODO-X86-CQ: If there are no gaps or padding in the layout, we can use a series of pushes.
-        // For now, always make space for the struct, and store each field at its offset.
+        GenTreePutArgStk* const putArgStk = treeNode->AsPutArgStk();
```
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: It might be reasonable to change the signature of this method to take a GenTreePutArgStk*.

**Comment by pgavlin** [comment]
> Do you know if there is any fundamental reason that the emitter couldn't be modified (presumably in future) to handle the non-push approach? When there are double fields and/or holes, it could be more efficient.

I don't think that there's any fundamental reason with respect to the emitter, but I am less certain about the GC info encoding. @briansull may know more.

File: src/jit/codegenxarch.cpp [hunk 2]
```diff
@@ -7397,30 +7397,106 @@ void CodeGen::genPutArgStk(GenTreePtr treeNode)
...
+        // Set the current field offset to the size of the struct arg (which must be a multiple of the target pointer
+        // size).
+        int currentOffset = argSize;
+
+        // If there are no GC references in this field list and the argument is either larger than 16 bytes or the
+        // argument contains padding, we will pre-adjust the stack pointer and use stores instead of pushes.
+        const bool preAdjustStack =
+            (putArgStk->gtNumberReferenceSlots == 0) &&
+            ((argSize > 16) || (putArgStk->gtPutArgStkKind != GenTreePutArgStk::PutArgStkKindRepInstr));
+        if (preAdjustStack)
```
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: I think it would be cleaner to extract the code from the beginning of `genPutArgStk` that determines whether it is using push (enhancing that logic as needed), and then in this method check `!m_pushStkArg` instead of using a local `preAdjustStack` variable. Then locally use `genStoreRegToStackArg` instead of having to duplicate the stack adjustment logic - then you'll only have the special casing of the "not a slot but treat as a slot" case.

File: src/jit/codegenxarch.cpp [hunk 3]
```diff
@@ -7397,30 +7397,106 @@ void CodeGen::genPutArgStk(GenTreePtr treeNode)
...
+                varTypeIsIntegralOrI(fieldType) && ((fieldOffset % 4) == 0) && ((prevFieldOffset - fieldOffset) >= 4);
+            if (fieldIsSlot)
+            {
+                fieldType = genActualType(fieldType);
+                assert(genTypeSize(fieldType) == 4);
+            }
+
+            // We can use a push instruction for any slot-like field.
+            //
+            // NOTE: if the field is of GC type, we must use a push instruction, since the emmitter is not otherwise
```
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: Typo: emmitter

File: src/jit/codegenxarch.cpp (hunk 2 above)
Comment (pgavlin) [inline src/jit/codegenxarch.cpp]: > Then locally use `genStoreRegToStackArg` instead of having to duplicate the stack adjustment logic - then you'll only have the special casing of the "not a slot but treat as a slot" case.

Which stack adjustment logic are you referring to? The stack adjustment logic that occurs when `preAdjustStack` is `true`, or the logic that adjusts the stack between arguments if necessary? The latter is not the same as the logic in `genStoreRegToStackArg`--it is necessary in order to account for padding between fields.

File: src/jit/gentree.h [hunk 4]
```diff
@@ -4602,14 +4595,11 @@ struct GenTreePutArgStk : public GenTreeUnOp
...
 
-    enum PutArgStkKind : __int8{
-        PutArgStkKindInvalid, PutArgStkKindRepInstr, PutArgStkKindUnroll,
-    };
+    enum PutArgStkKind : __int8{PutArgStkKindInvalid, PutArgStkKindRepInstr, PutArgStkKindUnroll};
 
     PutArgStkKind gtPutArgStkKind;
 
     unsigned gtNumSlots;             // Number of slots for the argument to be passed on stack
-    bool     gtIsStruct;             // This stack arg is a struct.
```
Comment (CarolEidt) [inline src/jit/gentree.h]: Thanks for getting rid of this. I think we might also want to consider eliminating the other fields, as they can be obtained from the `GT_OBJ` in the usual case, though the `GT_FIELD_LIST` case may require summary info (minimally a bool indicating whether it has any GC ptrs).

Comment (CarolEidt) [inline src/jit/gentree.h]: (Just a note for future consideration, not really apropos of this change.)

---
In reply to: [82645419](https://github.com/dotnet/coreclr/pull/7537#discussion_r82645419) [](ancestors = 82645419)

File: src/jit/lowerxarch.cpp [hunk 5]
```diff
@@ -1994,18 +1994,116 @@ void Lowering::TreeNodeInfoInitPutArgStk(GenTree* tree)
...
+                putArgStk->gtNumberReferenceSlots++;
+            }
+
+            prevOffset = fieldOffset;
+        }
+
+        // If all fields of this list are slots, set the copy kind.
+        if (allFieldsAreSlots)
+        {
+            putArgStk->gtPutArgStkKind = GenTreePutArgStk::PutArgStkKindRepInstr;
```
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: I believe that the code in codegenxarch.cpp will handle this correctly, but I don't think you should set this to RepInstr if there are GC slots, since it won't actually be using that kind of copy.

File: src/jit/codegenxarch.cpp (hunk 2 above)
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: Right, that's what I meant by "enhancing the logic as needed". And I think there's actually some value in having just the logic that adjusts the stack between arguments in this method - I think it would even more clearly make that a "special case".

---
In reply to: [82645034](https://github.com/dotnet/coreclr/pull/7537#discussion_r82645034) [](ancestors = 82645034)

File: src/jit/lowerxarch.cpp [hunk 6]
```diff
@@ -2096,34 +2186,37 @@ void Lowering::TreeNodeInfoInitPutArgStk(GenTree* tree)
...
-        }
-
         // If src or dst are on stack, we don't have to generate the address into a register
         // because it's just some constant+SP
         putArgStkTree->gtPutArgStkKind = GenTreePutArgStk::PutArgStkKindUnroll;
     }
+#ifdef _TARGET_X86_
+    else if (putArgStkTree->gtNumberReferenceSlots != 0)
+    {
+        putArgStkTree->gtPutArgStkKind = GenTreePutArgStk::PutArgStkKindRepInstr;
```
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: > I'm confused why you would set the kind this way. We never use rep movs for a struct with GC slots, correct?

That's right. It wasn't entirely clear what the invariants were regarding `gtPutArgStkKind` when I added this case. I will change this.

File: src/jit/lowerxarch.cpp (hunk 5 above)
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Yeah, I'm not proud of this one--it was essentially a hack to avoid adding another field to `GenTreePutArgStk` to indicate that all of the elements in a `GT_FIELD_LIST` may be treated as slots. Any suggestions on alternatives are welcome.

Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: I'd probably just add a new enum value `PutArgStkKindAllSlots` or something like that.

**Comment by mikedn** [comment]
> Do you know if there is any fundamental reason that the emitter couldn't be modified (presumably in future) to handle the non-push approach? When there are double fields and/or holes, it could be more efficient.

Depends. Intels have dedicated stack hardware for push/pop/call/ret so using `push` may actually be more efficient. Also, mixing `push` with instructions like `mov [esp], 42` requires an extra uop to sync the stack hardware with the rest of the CPU. At least that's what the manual says :)

**Comment by CarolEidt** [comment]
> Intels have dedicated stack hardware for push/pop/call/ret so using push may actually be more efficient. Also, mixing push with instructions like mov [esp], 42 requires an extra uop to sync the stack hardware with the rest of the CPU. At least that's what the manual says :)

Right, but since we are using mm regs for floating point (and there's no push for those), we will have to use the subtract-and-mov approach for those anyway, so we might be better off not using the pushes for the integer fields when they are mixed.

File: src/jit/lowerxarch.cpp (hunk 5 above)
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Done.

File: src/jit/lowerxarch.cpp (hunk 6 above)
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Fixed.

File: src/jit/codegenxarch.cpp (hunk 2 above)
Comment (pgavlin) [inline src/jit/codegenxarch.cpp]: Fixed.

**Comment by briansull** [comment]
> I don't think that there's any fundamental reason with respect to the emitter, but I am less certain about the GC info encoding. @briansull may know more.

I think that the x86 GC info encoding would work provided we are not storing GC pointers or byrefs into the stack frame.  

For fully interruptible ESP based methods we have to track the exact stack depth, but there is an encoding that supports subtracting a fixed amount from the ESP.  So adjusting the stack pointer prior to a store is fine.  I think that we already pass doubles this way in Jit32.

If we plan to store GC pointers into the stack frame we have to investigate this further as I think that the current encoder doesn't support this.

File: src/jit/codegenxarch.cpp [hunk 7]
```diff
@@ -7619,16 +7695,74 @@ void CodeGen::genPutStructArgStk(GenTreePutArgStk* putArgStk)
     else
     {
         // No need to disable GC the way COPYOBJ does. Here the refs are copied in atomic operations always.
+        CLANG_FORMAT_COMMENT_ANCHOR;
+
+#ifdef _TARGET_X86_
```
Comment (pgavlin) [inline src/jit/codegenxarch.cpp]: Done.

File: src/jit/lower.h [hunk 8]
```diff
@@ -202,10 +202,10 @@ class Lowering : public Phase
 #endif // FEATURE_SIMD
     void TreeNodeInfoInitCast(GenTree* tree);
 #ifdef _TARGET_ARM64_
-    void TreeNodeInfoInitPutArgStk(GenTree* argNode, fgArgTabEntryPtr info);
+    void TreeNodeInfoInitPutArgStk(GenTreePutArgStk* argNode, fgArgTabEntryPtr info);
```
Comment (CarolEidt) [inline src/jit/lower.h]: Thanks!

File: src/jit/lowerxarch.cpp (hunk 5 above)
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: This is still `RepInstr` - it looks like you meant that this should change to `AllSlots`

---
In reply to: [82675447](https://github.com/dotnet/coreclr/pull/7537#discussion_r82675447) [](ancestors = 82675447)

**Comment by pgavlin** [comment]
@CarolEidt: I think I've addressed all feedback--PTAL.

**Comment by CarolEidt** [comment]
:shipit:

**Comment by CarolEidt** [comment]
LGTM
