### PR TITLE
Stop hoisting statics above cctors

### LINKED ISSUE #10780: NullReferenceException during 'dotnet build' on ubuntu arm32
It appears there is a JIT bug on ubuntu arm machines. While trying to get a .NET Core SDK that runs on my Raspberry Pi, I encountered an error:

```
Microsoft (R) Build Engine version 15.2.93.5465
Copyright (C) Microsoft Corporation. All rights reserved.

/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileLookup..ctor(LockFile lockFile) [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.Build() [/home/ubuntu/HelloWorld/HelloWorld.csproj]
```

Looking into that code, there was no way a NullReferenceException was coming from that method.

Using Console.WriteLines, I traced it down to [this exact line that was failing](https://github.com/dotnet/sdk/blob/09c2a6bd8e2c0ec1524361d3a560a1ef961e4367/src/Tasks/Microsoft.NET.Build.Tasks/LockFileLookup.cs#L26).  Note that `LibraryType` is a struct.

I have 2 repos of this bug, one is the long way and one is the short way.

### Short Repo
- Clone https://github.com/eerhardt/ArmJITBug
- Using the [latest 2.0 SDK](https://github.com/dotnet/cli#installers-and-binaries) (on a non-linux-arm machine or else you will run into this bug 😀)
  - dotnet restore
  - dotnet publish -c Release
- Copy the contents of `bin\Release\netcoreapp2.0\publish` to a Raspberry Pi running a recent [ubuntu (14 or 16) arm32 build](https://github.com/dotnet/core-setup#daily-builds) of dotnet.
- On the Pi:  `dotnet App.dll`.

#### result
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TestIt.LockFileLookup..ctor(LockFile lockFile) in F:\DotNetTest\TestIt\App\Program.cs:line 30
   at TestIt.Program.Main(String[] args) in F:\DotNetTest\TestIt\App\Program.cs:line 14
```

### Long Repo
- Extract an ubuntu arm32 [shared framework](https://github.com/dotnet/core-setup#daily-builds) tarball onto your Raspberry Pi/arm machine.
- Build the dotnet/cli repo using `--configuration Release /p:DISABLE_CROSSGEN=1`.
- Extract the `artifacts/RID/packages/dotnet-sdk-RID.VERSION.tar.gz` archive into the same folder as the shared framework on your arm machine.  This will get you the SDK installed on your machine.

1. `dotnet new console`
1. `dotnet restore`
1. `dotnet run`

#### result
Same error as above with GenerateDepsFile task failing during the build.

## Notes
This only happens when I build the managed assembly for `Release`. The error doesn't repro when I build for `Debug`.

/cc @Petermarcu @jaredpar @VSadov @RussKeldorph

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Extend the logic in optLoopHoist around `CLS_VAR` nodes to ensure we don't
hoist any tree that contains a `CLS_VAR` for a field with the flag
`CORINFO_FLG_FIELD_INITCLASS` set, unless we also (identify and) hoist the
corresponding static init helper call.  The previous logic was
insufficient in that it blocked hoisting of singleton `CLS_VAR` nodes, but
not hoisting of trees that contain `CLS_VAR` nodes as sub-trees.

Add flag `GTF_FLD_INITCLASS`/`GTF_CLS_VAR_INITCLASS` so that optLoopHoist
can recall which fields are paired with static init helper calls, and only
block the hoisting of their trees.

Fixes #10780.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@briansull @hseok-oh PTAL
/cc @RussKeldorph @dotnet/jit-contrib

**Comment by JosephTremoulet** [comment]
I'm kicking off asm diffs now and will report back...

**Comment by JosephTremoulet** [comment]
jit-diff (x86 release --tests --frameworks) shows no diffs
Desktop superpmi shows diffs in just 6 methods, where we're now able to hoist a few more static vars because they are not `CORINFO_FLG_FIELD_INITCLASS` fields.

**Comment by JosephTremoulet** [comment]
@briansull, @dotnet/jit-contrib hopefully someone can take a look today, since this is intended for 2.0

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -6628,9 +6628,10 @@ GenTreePtr Compiler::fgMorphField(GenTreePtr tree, MorphAddrContext* mac)
                 else
 #endif // _TARGET_64BIT_
                 {
-                    // Only volatile could be set, and it maps over
-                    noway_assert((tree->gtFlags & ~(GTF_FLD_VOLATILE | GTF_COMMON_MASK)) == 0);
-                    noway_assert(GTF_FLD_VOLATILE == GTF_IND_VOLATILE);
+                    // Only volatile or classinit could be set, and they map over
+                    noway_assert((tree->gtFlags & ~(GTF_FLD_VOLATILE | GTF_FLD_INITCLASS | GTF_COMMON_MASK)) == 0);
+                    noway_assert(GTF_FLD_VOLATILE == GTF_CLS_VAR_VOLATILE);
+                    noway_assert(GTF_FLD_INITCLASS == GTF_CLS_VAR_INITCLASS);
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: I see that this is repeating an existing pattern, but it seems weird to have a `noway_assert` for a condition that is statically checkable, though I guess a `#if` and `#error` combination would probably be less readable.

Comment (BruceForstall) [inline src/jit/morph.cpp]: Use static_assert or static_assert_no_msg instead.

Comment (JosephTremoulet) [inline src/jit/morph.cpp]: Updated

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -6057,6 +6057,11 @@ GenTreePtr Compiler::impImportStaticFieldAccess(CORINFO_RESOLVED_TOKEN* pResolve
                 // In future, it may be better to just create the right tree here instead of folding it later.
                 op1 = gtNewFieldRef(lclTyp, pResolvedToken->hField);
 
+                if (pFieldInfo->fieldFlags & CORINFO_FLG_FIELD_INITCLASS)
+                {
+                    op1->gtFlags |= GTF_FLD_INITCLASS;
```
Comment (briansull) [inline src/jit/importer.cpp]: While this location may suffice for the case that we have here,
 I think that it may fail to set the flag on other kinds of GT_FIELD nodes. 
(Like instance fields , can they have or do they need it set?)
(Also what should happen for address of static fields?)

File: tests/src/JIT/Regression/JitBlue/GitHub_10780/GitHub_10780.cs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+using System.Runtime.CompilerServices;
+
+namespace N
+{
+    public struct Pair
+    {
+        public int Left;
+        public int Right;
+
+        public static Pair TenFour = new Pair() { Left = 10, Right = 4 };
```
Comment (briansull) [inline tests/src/JIT/Regression/JitBlue/GitHub_10780/GitHub_10780.cs]: I expected that this construction would reference the current value of C.Two

File: src/jit/importer.cpp (hunk 2 above)
Comment (JosephTremoulet) [inline src/jit/importer.cpp]: I searched for other appearances of `gtNewFieldRef` (and the `GenTreeField` constructor) and didn't see any others that should need this.  Instance fields are not triggers for static initialization (the rules are in [ecma 335](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi65JmEjeTTAhUO3WMKHR1yDbYQFggiMAA&url=https%3A%2F%2Fwww.ecma-international.org%2Fpublications%2Fstandards%2FEcma-335.htm&usg=AFQjCNGmzI4xDYNpbHE274KyfnbDUQPD_g) I.8.9.5).  Address of static gets imported as an `IconHandleNode` (just a few lines down), not a FT_FIELD node.

File: tests/src/JIT/Regression/JitBlue/GitHub_10780/GitHub_10780.cs (hunk 3 above)
Comment (JosephTremoulet) [inline tests/src/JIT/Regression/JitBlue/GitHub_10780/GitHub_10780.cs]: Yeah, the role of `C.Two` in this test is a bit confusing -- I just needed something in the loop that would keep us from hoisting the type init call (which, btw, is the call to init the statics of `Pair`, *not* the statics of `C`), and needed it to not keep registers live across the loop (lest our costing decide not to hoist the reference to `Pair.TenFour`), so writing to a static (which stops us from hoisting the call because it may throw) was what I landed on.  The bug is in reordering the call to `Pair..cctor` vs the load of`Pair.TenFour`, not vs the store of `C.Two`.
