### PR TITLE
Issue 7346 ConstructorArguments from CustomAttributes for null array of enum

### LINKED ISSUE #7346: Bug in the ConstructorArguments from CustomAttributes for null array of enum
There is an issue with a **null** array of enum as CustomAttribute in the constructor (notice that it is ok for an empty array new Test[0] as a workaround).

StackTrace

`   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(String name, RuntimeModule scope)
   at System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)
   at System.Reflection.CustomAttributeTypedArgument..ctor(RuntimeModule scope, CustomAttributeEncodedArgument encodedArg)
   at System.Reflection.CustomAttributeData.get_ConstructorArguments()`

Here is a full CoreCLR complaint example

```csharp
using System;
using System.Diagnostics;
using System.Reflection;

class Program
{
    [Test(new[] { Test.Foo }, null)]
    static void Main(string[] args)
    {
        var type = typeof(Program);
        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
        var attrEnum = method.CustomAttributes.GetEnumerator();
        attrEnum.MoveNext();
        int count = 0;
        try
        {
            var attr = attrEnum.Current.ConstructorArguments;
            count = attr.Count;
        }
        catch (Exception exc)
        {
            Debug.WriteLine(exc.Message);
            Debug.WriteLine(exc.StackTrace);
        }
        Console.WriteLine("Does the CoreCLR rock? {0}", count == 2);
        Console.ReadKey();
    }
}

public enum Test
{
    Foo,
    Bar
}

[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class TestAttribute : Attribute
{
    public TestAttribute(Test[] valuesOne, Test[] valuesTwo)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by giuliohome**
Creating a pull request, as discussed, to fix issue #7346

In the structure of the blob where the custom attribute is specified, array values start with an integer indicating the number of elements in the array, then the item values concatentated together. 
A null array is represented using a length of -1.
Unfortunately, what happens if you pass an array of enum as null is that enum name is lost

Fix #7346

### CODE REVIEW

File: src/vm/customattribute.cpp [hunk 1]
```diff
@@ -294,13 +294,11 @@ HRESULT Attribute::ParseCaValue(
         IfFailGo(ca.GetU4(&len));
         pCaArg->arr.length = len;
         pCaArg->arr.pSArray = NULL;
-        if (pCaArg->arr.length == (ULONG)-1)
-            break;
 
         IfNullGo(pCaArg->arr.pSArray = pCaValueArrayFactory->Create());
```
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: "IfNullGo(pCaArg->arr.pSArray = pCaValueArrayFactory->Create()); "

This doesn't look like something that we'd want to execute if the array value is null.

File: src/vm/customattribute.cpp [hunk 2]
```diff
@@ -294,13 +294,11 @@ HRESULT Attribute::ParseCaValue(
         IfFailGo(ca.GetU4(&len));
         pCaArg->arr.length = len;
         pCaArg->arr.pSArray = NULL;
-        if (pCaArg->arr.length == (ULONG)-1)
-            break;
 
         IfNullGo(pCaArg->arr.pSArray = pCaValueArrayFactory->Create()); 
         elementType.Init(pCaArg->type.arrayType, SERIALIZATION_TYPE_UNDEFINED,
```
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: I think it would be better to hoist this line before the original "early out if arr.Length == -1" check and leave that original check in. The code will be more maintainble if we early out - we just have to init the EnumName before we do that.

File: src/vm/customattribute.cpp (hunk 1 above)
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: "IfNullGo(pCaArg->arr.pSArray = pCaValueArrayFactory->Create()); "

This doesn't look like something that we'd want to execute if the array value is null.

File: src/vm/customattribute.cpp (hunk 2 above)
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: "elementType.Init(pCaArg"....

I think it would be better to hoist this line before the original "early out if arr.Length == -1" check and leave that original check in. The code will be more maintainble if we early out - we just have to init the EnumName before we do that.

File: src/vm/customattribute.cpp [hunk 3]
```diff
@@ -165,11 +165,11 @@ CustomAttributeManagedValues Attribute::GetManagedCaValue(CaValue* pCaVal)
         ULONG length = pCaVal->arr.length;
         BOOL bAllBlittableCa = arrayType != SERIALIZATION_TYPE_ENUM;
 
-        if (length == (ULONG)-1)
```
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: As with my comments on the other function, I think it's better to keep the early out and move the NewString(...szEnumName) call above this. This requires replicating the GC_PROTECT. You don't need to replicate the "if (!bAllBlittableCa)" check as you're already checking "arrayType == SERIALIZATION_TYPE_ENUM", and that's the same check.

File: src/vm/customattribute.cpp [hunk 4]
```diff
@@ -165,11 +165,11 @@ CustomAttributeManagedValues Attribute::GetManagedCaValue(CaValue* pCaVal)
...
-        
-        gc.array = (CaValueArrayREF)AllocateValueSzArray(MscorlibBinder::GetClass(CLASS__CUSTOM_ATTRIBUTE_ENCODED_ARGUMENT), length);
-        CustomAttributeValue* pValues = gc.array->GetDirectPointerToNonObjectElements();
+        if (length != (ULONG)-1)
+        {
+            gc.array = (CaValueArrayREF)AllocateValueSzArray(MscorlibBinder::GetClass(CLASS__CUSTOM_ATTRIBUTE_ENCODED_ARGUMENT), length);
+            CustomAttributeValue* pValues = gc.array->GetDirectPointerToNonObjectElements();
+        }
 
         for (COUNT_T i = 0; i < length; i ++)
```
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: This loop shouldn't be executed if the array is null (yes, it conveniently early-out's anyway since the "length" is -1 but this is fragile and unintuitive.) If you follow my suggestion of retaining the early-out structure, then this issue will be moot.

File: tests/src/readytorun/main.cs [hunk 5]
```diff
@@ -49,8 +50,45 @@ public static string OpenClosedDelegateTarget(this string x, string foo)
...
+    public TestAttribute(Test[] valuesOne, Test[] valuesTwo, Test[] valuesThree, Test[] valuesFour)
+    {
+    }
+}
+
 class Program
 {
+    static void TestCtorAttr()
+    {
+        var type = typeof(Program);
```
Comment (AtsushiKan) [inline tests/src/readytorun/main.cs]: We'll probably want to migrate these tests to the corefx repo, so we probably want to follow the corefx repo guidelines. I.e. we only use "var" in these situations:

    var x = new Foo();
    var x = (IFoo)something;
    var x = something as IFoo;

File: src/vm/customattribute.cpp (hunk 3 above)
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: Amending my prior comment about "replicating the GC_PROTECT" - the correct change is to replace the existing GC_PROTECT with one that guards the whole function, starting from the line after "ZeroMemory(&gc, sizeof(gc)). Right now, the GC_PROTECT regions covers <b>just</b> enough to get by but that structure is an accident waiting to happen.

File: src/vm/customattribute.cpp (hunk 1 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: We want to Attribute::ParseCaValue at least... (let me read also your next comments)

File: src/vm/customattribute.cpp (hunk 2 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: Oh, now I understand your point... clear, let me double check, I will add another commit for this...

**Comment by AtsushiKan** [comment]
You’re bypassing ParseCaValue() anyway with the “length != (ULONG)-1” check you added.

**Comment by giuliohome** [comment]
> You’re bypassing ParseCaValue() anyway with the “length != (ULONG)-1” check you added.

Sure, you're absolutely right.  In fact I need to double check your comment about "elementType.Init(pCaArg".... before, forget what I wrote about  ParseCaValue 10 minutes ago, sorry

File: src/vm/customattribute.cpp (hunk 1 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: Received your message, again give me some minutes to double check this and add a new commit plus a reply/comment

File: tests/src/readytorun/main.cs [hunk 6]
```diff
@@ -49,8 +50,45 @@ public static string OpenClosedDelegateTarget(this string x, string foo)
...
+        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
+        var attributeEn = method.CustomAttributes.GetEnumerator();
+        attributeEn.MoveNext();
+        var attribute = attributeEn.Current.ConstructorArguments;
```
Comment (AtsushiKan) [inline tests/src/readytorun/main.cs]: "constructorArgument" (or "argument") would be a more descriptive name than "attribute"

**Comment by AtsushiKan** [comment]
No prob – actually, I’m just on my way out the door for the weekend so we can pick this up Monday.

File: src/vm/customattribute.cpp (hunk 1 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: OK, this is not needed. I'm preparing my final comment

File: src/vm/customattribute.cpp (hunk 2 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: You're right, but I've seen that we can skip this part.

File: src/vm/customattribute.cpp (hunk 3 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: > I think it's better to keep the early out and move the NewString(...szEnumName) call above this.

done in my final commit

> You don't need to replicate the "if (!bAllBlittableCa)"

ok, I didn't replicate it in my last commit

File: tests/src/readytorun/main.cs (hunk 6 above)
Comment (giuliohome) [inline tests/src/readytorun/main.cs]: ok, renamed as "argument"

File: src/vm/customattribute.cpp [hunk 7]
```diff
@@ -166,8 +166,15 @@ CustomAttributeManagedValues Attribute::GetManagedCaValue(CaValue* pCaVal)
         BOOL bAllBlittableCa = arrayType != SERIALIZATION_TYPE_ENUM;
 
         if (length == (ULONG)-1)
+        {
+            GCPROTECT_BEGIN(gc)
+            {   
+                if (arrayType == SERIALIZATION_TYPE_ENUM)
```
Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: Ok, since this "if (arrayType == SERIALIZATION_TYPEENUM)" statement appears twice now, they should be merged and hoisted up before the "if (length == (ULONG)-1)". 

This does also require merging the two GCPROTECTED_BEGIN clauses into a single one (they can't nest.)
While it would be sufficient for your change to make it guard just the stuff in the SERIALIZATION_TYPE_SZARRAY, we might as well take this opportunity to have it guard everything after ZeroMemory(&gc, sizeof(gc)). The way the function is structured right now is pretty chancy.

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: Oh, and I do need you to sign that contribution license agreement (https://cla2.dotnetfoundation.org.). Our lawyers do require that :-)

Comment (giuliohome) [inline src/vm/customattribute.cpp]: Ok, signed :-)

**Comment by AtsushiKan** [comment]
cc @MichalStrehovsky

File: src/vm/customattribute.cpp (hunk 7 above)
Comment (giuliohome) [inline src/vm/customattribute.cpp]: ok, let me see if I can quickly change this via git online... so, you're suggesting to start `GCPROTECT_BEGIN(gc) {` after `CustomAttributeManagedValues gc;` and to close `} GCPROTECT_END();` before `return gc;` corect? Thanks

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: Almost correct... you'll want the GCPROTECT_BEGIN after the ZeroMemory(&gc, sizeof(gc)). Nicer to initialize the memory before asking the GC to monitor it :-)

Comment (giuliohome) [inline src/vm/customattribute.cpp]: Sorry, I'm a bit lost here... there is a first `return gc;` after `if (length == (ULONG)-1)` ... can it be included in the merged `GCPROTECT_BEGIN { ... } GCPROTECT_END();` or should it disappear by changing the if statement etc..? 

and also (sorry for another trivial question) ... 
when "if (arrayType == SERIALIZATION_TYPEENUM)" statement is hoisted up before the "if (length == (ULONG)-1)", do you agree that executing the "for (COUNT_T i = 0; i < length; i ++)
            Attribute::SetBlittableCaValue" *after* it instead of *before* is irrelevant?

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: >Sorry, I'm a bit lost here... there is a first  return gc; 

Ah yes, that "return gc" will screw things up. Yes, we should delete that and use and turn the "if" into an "if {...} else {...}". Good catch.

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: >do you agree that executing the "for (COUNT_T i = 0; i < length; i ++)>Attribute::SetBlittableCaValue" after it instead of before is irrelevant?

Yes, my recommended change is contingent on the ordering of those two operations being interchangable.

There is a strange interaction there in that SetBlittableCaValue() is modifying the bAllBlittableCA boolean which then gates the next "if". I need to take a closer look at that.

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: >do you agree that executing the "for (COUNT_T i = 0; i < length; i ++)>Attribute::SetBlittableCaValue" after it instead of before is irrelevant?

Yes, my recommended change is contingent on the ordering of those two operations being interchangable.

There is a strange interaction there in that SetBlittableCaValue() is modifying the bAllBlittableCA boolean which then gates the next "if". I need to take a closer look at that.

Comment (AtsushiKan) [inline src/vm/customattribute.cpp]: Well... my read on it says it's okay to reorder them. Probably worth stepping through it on a couple of examples and counter-examples to make sure, thought.

Comment (giuliohome) [inline src/vm/customattribute.cpp]: ok, I'll push a commit for the *extended* GCPROTECT after finishing checks, thanks

**Comment by AtsushiKan** [comment]
Ok, looks good. Just a few final things and we're ready to go:

- That last commit altered the indentation of a number of lines you didn't change otherwise - please set those back to indenting 4-spaces.

- Please squash the commits.

- We need one other MSFT person to sign off before I merge - I've pinged a few other folks.

Thanks for your contribution!

cc @jkotas 
cc @MichalStrehovsky

**Comment by giuliohome** [comment]
sorry for the formatting, where are the lines without indenting 4-spaces?

**Comment by giuliohome** [comment]
> That last commit altered the indentation of a number of lines you didn't change otherwise - please set those back to indenting 4-spaces.

just lines 172-190? I'll format them like below..

```
            if (length != (ULONG)-1)
            {
                gc.array = (CaValueArrayREF)AllocateValueSzArray(MscorlibBinder::GetClass(CLASS__CUSTOM_ATTRIBUTE_ENCODED_ARGUMENT), length);
                CustomAttributeValue* pValues = gc.array->GetDirectPointerToNonObjectElements();

                for (COUNT_T i = 0; i < length; i ++)
                    Attribute::SetBlittableCaValue(&pValues[i], &pCaVal->arr[i], &bAllBlittableCa); 

                if (!bAllBlittableCa)
                {
                    for (COUNT_T i = 0; i < length; i ++)
                    {
                        CustomAttributeManagedValues managedCaValue = Attribute::GetManagedCaValue(&pCaVal->arr[i]);
                        Attribute::SetManagedValue(
                            managedCaValue,
                            &gc.array->GetDirectPointerToNonObjectElements()[i]);
                    }
                }
            }
```

File: tests/src/readytorun/main.cs (hunk 5 above)
Comment (jkotas) [inline tests/src/readytorun/main.cs]: Agree. These tests should be added in corefx repo - they do not belong to this file.

File: tests/src/readytorun/main.cs [hunk 8]
```diff
@@ -420,6 +463,7 @@ static void GenericLdtokenFieldsTest()
 
     static void RunAllTests()
     {
+        TestCtorAttr();
```
Comment (MichalStrehovsky) [inline tests/src/readytorun/main.cs]: I don't think that whoever owns the ready to run test would approve of random stuff showing up in here. This is not related to the R2R feature. @weshaggard Do you know if there's any sort of process for checking in regression tests like this? I assume it would have to be something like a disabled corefx test until new System.Private.CoreLib propagates to corefx.

**Comment by AtsushiKan** [comment]
Right, it was lines 172-190.

**Comment by giuliohome** [comment]
> Please squash the commits.

They are 9 now.
I guess I've to do

```
git reset --soft HEAD~9 &&
git commit -m"Issue 7346 Ctor Ars from CustomAttributes for null array of enum"
```

correct?

**Comment by AtsushiKan** [comment]
Yep – that’s how I do it.

**Comment by AtsushiKan** [comment]
Looks like you did a merge commit after the squash, which brought all the intermediate commits back into the history :-)

Here's what you want to do:

  ```
   git checkout issue-7346
   git merge master
   git reset --soft master
   git commit -m "Your commit message"
   git push --force origin issue-7346
```

The GitHub PR page should now show just 1 commit.

**Comment by giuliohome** [comment]
I think I've squashed the commits now, sorry for the late reply but I'm new to git

**Comment by AtsushiKan** [comment]
Please remove main.cs from the commit - we'll add the tests to the corefx repo once the coreclr fix has propagated over. Otherwise, LGTM.

**Comment by giuliohome** [comment]
> Please remove main.cs from the commit - we'll add the tests to the corefx repo once the coreclr fix has propagated over. Otherwise, LGTM.

@AtsushiKan 

Sure, done! Thank you very much for your guidance... and for your patience :-)
