### PR TITLE
Notify dac when prejitted code is going to be used for a method

### LINKED ISSUE #22265: sos bpmd doesn't seem to work on prejitted code
On Arm64 Linux, I can't get `bpmd` to break into the debugger when executing prejitted code. Once the process exits, `bpmd -list` shows the breakpoint twice, once listed with what is likely the method code address.
```
$ lldb-6.0 -- ./corerun ../../JIT/Regression/CLR-x86-JIT/v2.1/DDB/b163200/b163200/b163200.exe
(lldb) target create "./corerun"
Current executable set to './corerun' (aarch64).
(lldb) settings set -- target.run-args  "../../JIT/Regression/CLR-x86-JIT/v2.1/DDB/b163200/b163200/b163200.exe"
(lldb) process launch -s
Process 7611 launched: './corerun' (aarch64)
(lldb) breakpoint set -n LoadLibraryExW
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) plugin load libsosplugin.so
(lldb) continue
Process 7611 resuming
1 location added to breakpoint 1
Process 7611 stopped
* thread #1, name = 'corerun', stop reason = breakpoint 1.1
    frame #0: 0x0000ffffb7750964 libcoreclr.so`::LoadLibraryExW(lpLibFileName=u"/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/libclrjit.so", hFile=0x0000000000000000, dwFlags=0) at module.cpp:214
(lldb) sos bpmd System.Private.CoreLib.dll System.Globalization.TimeSpanFormat+FormatLiterals.InitInvariant
Adding pending breakpoints...
(lldb) continue
Process 7611 resuming
1 location added to breakpoint 1
Process 7611 exited with status = 100 (0x00000064)
(lldb) sos bpmd -list
bpmd pending breakpoint list
 Breakpoint index - Location, ModuleID, Method Token
1 - System.Private.CoreLib.dll!System.Globalization.TimeSpanFormat+FormatLiterals.InitInvariant+0, 0x0000000000000000, 0x00000000
2 - System.Private.CoreLib.dll!System.Globalization.TimeSpanFormat+FormatLiterals.InitInvariant+0, 0x0000FFFF3D566020, 0x06004663
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This allows sos bpmd breakpoints to work on prejitted methods.

Closes #22265.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @noahfalk 

Not sure if this is the right place for notification -- maybe there is some bulk way to handle this when the R2R image is loaded....

**Comment by AndyAyersMS** [comment]
OSX hitting typical pal test failures...

@dotnet-bot retest OSX10.12 x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
arm cross jenkins hangup...

@dotnet-bot retest Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
@noahfalk Ping

File: src/vm/prestub.cpp [hunk 1]
```diff
@@ -369,12 +369,17 @@ PCODE MethodDesc::PrepareILBasedCode(PrepareCodeConfig* pConfig)
...
+
     if (pCode == NULL)
     {
         LOG((LF_CLASSLOADER, LL_INFO1000000,
             "    In PrepareILBasedCode, calling JitCompileCode\n"));
         pCode = JitCompileCode(pConfig);
     }
+    else
+    {
+        DACNotifyCompilationFinished(this, pCode);
```
Comment (noahfalk) [inline src/vm/prestub.cpp]: Hmm, this isn't intended to be necessary although I don't mind putting this in with a comment and leaving the issue #22265 open.

What I would expect to happen if things were working smoothly is that the debugger would bind the breakpoint in response to a module load at roughly this callstack:
    
    IssueDebuggerBPCommand ( CLRDATA_ADDRESS addr )
    Breakpoints::ResolveMethodInstances(IXCLRDataMethodDefinition *pMeth, DWORD ilOffset)
    Breakpoints::ResolvePendingBreakpoint(TADDR addr, PendingBreakpoint *pCur)
    Breakpoints::Update(TADDR mod, BOOL isNewModule)

Triggering an event for each method as it loads also works, but has higher performance overhead vs. doing a single sweep at module load.
