### PR TITLE
Synchronize managed and unmanaged Variant fields

### LINKED ISSUE #24948: Debug Error: stack was corrupted in olevariant.cpp
When executing `tests\runtest.cmd`, I encountered a Debug Error in the ConsumeNETServer test.

What I did to reproduce it:

1. `set CORE_ROOT=C:\code\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root`
2. `C:\code\coreclr\bin\tests\Windows_NT.x64.Debug\Interop\COM\NETClients\ConsumeNETServer\ConsumeNETServer\ConsumeNETServer.cmd`

This displays:

Output:

```
BEGIN EXECUTION
Copying 'C:\code\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreShim.dll'...
        1 file(s) copied.
 "C:\code\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" ConsumeNETServer.exe
Validate_Activation...
Validate_CCW_Wasnt_Unwrapped...
Validate_Client_CCW_RCW...
Expected: 100
Actual: 3
END EXECUTION - FAILED
```

cc: @jkotas

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #24948

### CODE REVIEW

File: src/vm/mscorlib.h [hunk 1]
```diff
@@ -432,6 +432,11 @@ DEFINE_CLASS(VARIANT,               System,                 Variant)
 DEFINE_METHOD(VARIANT,              CONVERT_OBJECT_TO_VARIANT,MarshalHelperConvertObjectToVariant,SM_Obj_RefVariant_RetVoid)
 DEFINE_METHOD(VARIANT,              CAST_VARIANT,           MarshalHelperCastVariant,   SM_Obj_Int_RefVariant_RetVoid)
 DEFINE_METHOD(VARIANT,              CONVERT_VARIANT_TO_OBJECT,MarshalHelperConvertVariantToObject,SM_RefVariant_RetObject)
+
+DEFINE_CLASS_U(System,              Variant,                VariantData)
```
Comment (jkotas) [inline src/vm/mscorlib.h]: This validates that the managed/unmanaged views are in sync.

File: src/vm/olevariant.h [hunk 2]
```diff
@@ -324,9 +326,16 @@ struct VariantData
     }
 
 private:
-    Object*     m_or;
+#ifdef _WIN64
+    Object*     m_objref;
+    INT64       m_data;
+    INT32       m_flags;
+    INT32       m_padding;
```
Comment (jkotas) [inline src/vm/olevariant.h]: This padding field is fixing the actual bug.

File: src/vm/olevariant.h [hunk 3]
```diff
@@ -324,9 +326,16 @@ struct VariantData
...
+#else
     INT64       m_data;
```
Comment (AaronRobinsonMSFT) [inline src/vm/olevariant.h]: The order of these fields in the `#else` is wrong. I would suggest we simply add the `m_padding` field in a `#ifdef _WIN64` or am I missing something else here?

File: src/System.Private.CoreLib/src/System/Variant.cs [hunk 4]
```diff
@@ -112,180 +110,143 @@ internal struct Variant
...
-        {
-            return ((long)m_data2 << 32 | ((long)m_data1 & 0xFFFFFFFFL));
-        }
-
         //
         // Constructors
         //
 
-        internal Variant(int flags, object or, int data1, int data2)
+        internal Variant(int flags, object or, long data = 0)
```
Comment (AaronRobinsonMSFT) [inline src/System.Private.CoreLib/src/System/Variant.cs]: I don't see any usage of `Variant` that needs the default value for `data`. I would prefer if that was explicit.

File: src/vm/olevariant.h (hunk 3 above)
Comment (jkotas) [reply src/vm/olevariant.h]: The order is right. The type loader reorders the fields for non-blittable types and this reordering differs for 32-bit vs. 64-bit.

Comment (AaronRobinsonMSFT) [reply src/vm/olevariant.h]: >The type loader reorders the fields for non-blittable types and this reordering differs for 32-bit vs. 64-bit.

Can we comment that here. Do we have a link somewhere so I can educate myself?

File: src/System.Private.CoreLib/src/System/Variant.cs (hunk 4 above)
Comment (jkotas) [reply src/System.Private.CoreLib/src/System/Variant.cs]: These two lines depend on the default value: https://github.com/dotnet/coreclr/pull/24951/files#diff-6493f97f2c623d9845d14c55ab8a6eafR113. I can change them to pass 0 explicitly ... I do not have a preference.

Comment (AaronRobinsonMSFT) [reply src/System.Private.CoreLib/src/System/Variant.cs]: Sorry, I meant existing lines not in this PR. Since those lines were already being touched I didn't count them. I would prefer them to be explicit in this case.

File: src/vm/olevariant.h (hunk 3 above)
Comment (AaronRobinsonMSFT) [reply src/vm/olevariant.h]: A link to the general area in the code base would be enough too.

Comment (jkotas) [reply src/vm/olevariant.h]: The type loader is trying to maximize the packing and that's why it reorders the fields when it is allowed to do so.

The type loader lives in https://github.com/dotnet/coreclr/blob/master/src/vm/methodtablebuilder.cpp . There are number of different methods involved in the layout - PlaceInstanceFields is probably the more interesting ones.

There are more types used with manually-managed code that have similar difference. E.g.  https://github.com/dotnet/coreclr/blob/master/src/vm/object.h#L1627

Comment (AaronRobinsonMSFT) [reply src/vm/olevariant.h]: >The type loader is trying to maximize the packing and that's why it reorders the fields when it is allowed to do so.

I figured that would be the rational. Wasn't aware reordering was automatically done by the CLR. Is there publicly documented? Thanks for the source links.

Comment (jkotas) [reply src/vm/olevariant.h]: We do document that non-blittable types have different managed and unmanaged layout: https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types

We do not document the specific optimizations that we apply to the layout, but you can find approximate descriptions of them on stackoverflow and similar places.
