### PR TITLE
[RyuJIT/armel] Passing stack double arguments

### LINKED ISSUE #11927: [RyuJIT/armel] CodeGenBringUpTests Assertion failed 'info->numSlots == 1'
A sub-issue for #11822 

Some tests fail with below assert failure.

```
               Assert failure(PID 31095 [0x00007977], Thread: 31095 [0x7977]): Assertion failed 'info->numSlots == 1' in 'BringUpTest:StaticCalls():int' (IL size 688)

                   File: /opt/code/github/hqueue/coreclr/src/jit/lsraarmarch.cpp Line: 681
```

List of the tests fail with above message in `JIT/CodeGenBringUpTests`

```
FAILED   - [  25]JIT/CodeGenBringUpTests/DblArea/DblArea.sh
FAILED   - [  28]JIT/CodeGenBringUpTests/DblAvg6/DblAvg6.sh
FAILED   - [  30]JIT/CodeGenBringUpTests/DblCall2/DblCall2.sh
FAILED   - [  31]JIT/CodeGenBringUpTests/DblDist/DblDist.sh
FAILED   - [  34]JIT/CodeGenBringUpTests/DblFillArray/DblFillArray.sh
FAILED   - [  39]JIT/CodeGenBringUpTests/DblRoots/DblRoots.sh
FAILED   - [  81]JIT/CodeGenBringUpTests/InstanceCalls/InstanceCalls.sh
FAILED   - [ 128]JIT/CodeGenBringUpTests/OpMembersOfStructLocal/OpMembersOfStructLocal.sh
FAILED   - [ 135]JIT/CodeGenBringUpTests/StaticCalls/StaticCalls.sh
```

### PR DESCRIPTION
**Pull request by wateret**
Fix #11927

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib @dotnet/arm32-contrib

File: src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -555,6 +555,16 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
         {
             genConsumeReg(source);
             emit->emitIns_S_R(storeIns, storeAttr, source->gtRegNum, varNumOut, argOffsetOut);
+            if (compiler->opts.compUseSoftFP && targetType == TYP_LONG)
+            {
+                // This case currently only occurs for double types that are passed as TYP_LONG;
+                // actual long types would have been decomposed by now.
+                assert(source->IsCopyOrReload());
+                regNumber otherReg = (regNumber)source->AsCopyOrReload()->gtOtherRegs[0];
+                assert(otherReg != REG_NA);
```
Comment (BruceForstall) [inline src/jit/codegenarmarch.cpp]: Instead, can you use:
```
                regNumber otherReg = source->AsCopyOrReload()->GetRegNumByIdx(1);
```
? Seems better to not touch gtOtherRegs directly.

Comment (wateret) [inline src/jit/codegenarmarch.cpp]: Thank you. I'll fix it.

**Comment by wateret** [comment]
@dotnet-bot Test Windows_NT x64 Debug Build and Test
@dotnet-bot Ubuntu x64 Checked Build and Test
@dotnet-bot OSX10.12 x64 Checked Build and Test
@dotnet-bot FreeBSD x64 Checked Build

**Comment by wateret** [comment]
@dotnet-bot Test this please

File: src/jit/codegenarmarch.cpp [hunk 2]
```diff
@@ -555,6 +555,16 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
         {
             genConsumeReg(source);
             emit->emitIns_S_R(storeIns, storeAttr, source->gtRegNum, varNumOut, argOffsetOut);
+            if (compiler->opts.compUseSoftFP && targetType == TYP_LONG)
```
Comment (CarolEidt) [inline src/jit/codegenarmarch.cpp]: Shouldn't this be under `#ifdef ARM_SOFTFP`?

File: src/jit/lsraarmarch.cpp [hunk 3]
```diff
@@ -738,8 +738,22 @@ void Lowering::TreeNodeInfoInitPutArgStk(GenTreePutArgStk* argNode, fgArgTabEntr
...
+        if ((info->numSlots == 2) && (putArgChild->TypeGet() == TYP_LONG))
+        {
+            argNode->gtLsraInfo.srcCount = 2;
+        }
+        else
+        {
+            assert(info->numSlots == 1);
+        }
+#endif // ARM_SOFTFP
+
```
Comment (CarolEidt) [inline src/jit/lsraarmarch.cpp]: As a rule, when you have both an if and else clause, you should refactor to avoid the double negative (i.e. in this case put the `ARM_SOFTFP` code first). However, the above could be greatly simplified as:
```
#ifdef ARM_SOFTFP
        // The `double` types have been transformed to `long` on armel.
        var_types doubleType = TYP_LONG;
#else
        var_types doubleType = TYP_DOUBLE:
#endif
        assert((info->numSlots == 1) || ((info->numSlots == 2) && (putArgChild->TypeGet() == doubleType)));
```

File: src/jit/codegenarmarch.cpp (hunk 2 above)
Comment (wateret) [inline src/jit/codegenarmarch.cpp]: `compUseSoftFP` was introduced when we first ported armel. The value is TRUE when `ARM_SOFTFP` is defined, FALSE otherwise(for all architectures). Since then I use `compUseSoftFP` if applicable. However some modules like LSRA which do not hold `compiler` object I just use `#ifdef ARM_SOFTFP`.

File: src/jit/lsraarmarch.cpp (hunk 3 above)
Comment (wateret) [inline src/jit/lsraarmarch.cpp]: @CarolEidt I first tried something like your code, but updating srcCount was needed for ARM_SOFTFP. So here's what I've got. Would this look better than the current one? Or would there be a better implementation?

```cpp
#ifdef _TARGET_ARM_

#ifdef ARM_SOFTFP
        // The `double` types have been transformed to `long` on armel.
        var_types doubleType = TYP_LONG;
#else
        var_types doubleType = TYP_DOUBLE:
#endif

        // We must not have a multi-reg struct; double uses 2 slots and isn't a multi-reg struct
        const bool isDouble = (info->numSlots == 2) && (putArgChild->TypeGet() == doubleType);
        assert((info->numSlots == 1) || isDouble);

#ifdef ARM_SOFTFP
        if (isDouble)
        {
            argNode->gtLsraInfo.srcCount = 2;
        }
#endif

#else  // !_TARGET_ARM_
        // We must not have a multi-reg struct
        assert(info->numSlots == 1);
#endif // !_TARGET_ARM_
```

Comment (CarolEidt) [inline src/jit/lsraarmarch.cpp]: > updating srcCount was needed for ARM_SOFTFP

I see; in that case, it's probably better to set `isDouble` conditionally instead, and move the srcCount update into the same `#ifdef`. How about this:
```
#ifdef _TARGET_ARM_

#ifdef ARM_SOFTFP
        // The `double` types have been transformed to `long` on armel.
        const bool isDouble = (info->numSlots == 2) && (putArgChild->TypeGet() == TYP_LONG);
        if (isDouble)
        {
            argNode->gtLsraInfo.srcCount = 2;
        }
#else
        const bool isDouble = (info->numSlots == 2) && (putArgChild->TypeGet() == TYP_DOUBLE);
#endif

        // We must not have a multi-reg struct; double uses 2 slots and isn't a multi-reg struct
        assert((info->numSlots == 1) || isDouble);

#else  // !_TARGET_ARM_
        // We must not have a multi-reg struct
        assert(info->numSlots == 1);
#endif // !_TARGET_ARM_
```

Comment (wateret) [inline src/jit/lsraarmarch.cpp]: @CarolEidt Thanks! That looks much better.

File: src/jit/codegenarmarch.cpp (hunk 2 above)
Comment (CarolEidt) [inline src/jit/codegenarmarch.cpp]: >  However some modules like LSRA which do not hold compiler object I just use #ifdef ARM_SOFTFP.

`LinearScan` has a `compiler` field, for future reference.

**Comment by wateret** [comment]
@dotnet-bot test Tizen armel Cross Release Build please

**Comment by wateret** [comment]
@CarolEidt arm/armel test fails intermittently, and it seems like it is qemu related issue.
Related Issues : #6573 #6298
