### PR TITLE
Fix SystemV AMD64 Explicit structure classification

### LINKED ISSUE #4195: MarshalStructAsLayoutExp test fails non-windows platform

### LINKED ISSUE #4307: Error in passing structure to native method on OSX
On OSX debug build (both native and managed) following occurs:
The number written by native part is not 10 (see attached source code).
But if struct layout changed to Sequential (in .cs file) everything works fine.

[src.zip](https://github.com/dotnet/coreclr/files/216055/src.zip)

### LINKED ISSUE #22016: Structures with fixed buffers sometimes misclassified in SystemV eightbyte classification
The struct below is misclassified by the SystemV classifier:

```csharp
[StructLayout(LayoutKind.Sequential)]
public unsafe struct FixedBufferClassificationTest
{
    public fixed int arr[3];
    public float f;
}
```

The two eightbytes should both be classified as `INTEGER` eightbytes; however, the runtime sees the type above as equivalent to the following:

```csharp
[StructLayout(LayoutKind.Sequential)]
public unsafe struct FixedBufferClassificationTest
{
    [StructLayout(LayoutKind.Sequential, Size=12)]
    private struct FixedBufferType
    {
         private int i;
    }
    [FixedBufferAttribute(typeof(int),3)]
    public FixedBufferType arr;
    public float f;
}
```

Since the classifier has no special knowledge of the concept of fixed buffers, the classifier marks the first four bytes as `INTEGER`, the next 8 as `NO_CLASS`, and the final four as `SSE`. This results in the second eightbyte being classified as `SSE` instead of `INTEGER`.

### LINKED ISSUE #23150: Bug with FieldOffset and marshaling by value
Attached is a repro for where a struct with Explicit layout and FieldOffsets modeling a C union gets marshaled as garbage to C through p/invoke on linux and mac, while it works as expected on windows. I haven't tried to figure out what exactly breaks it, but the sample should be simple enough. It assumes 64-bit linux.

C code is like this:

```c
    struct Repro
    {
        int discriminator;
        union
        {
            int integer;
            void* pointer;
            char* string;
         };
    };
```

    void consume(struct Repro repro); // passing the struct by value

and C# binding is like this:
```c#
        [StructLayout(LayoutKind.Explicit)]
        public struct Repro
        {
            [FieldOffset(0)]
            public int discriminator;
            [FieldOffset(8)]
            public int integer;
            [FieldOffset(8)]
            public IntPtr string_;
            [FieldOffset(8)]
            public IntPtr pointer;
        }

        [DllImport("repro")]
        public static extern void consume(Repro value);
```

It results in garbage passed to C code, see attached. It outputs

```
    discriminator: 497673040
    pointer: 0x7f7cec7f5818
```

instead of expected 8 and 42.

To reproduce unpack the attachment and run ./repro.sh in it.

[repro.zip](https://github.com/dotnet/core/files/2946475/repro.zip)

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Our current implementation of our SystemV classifier just bails out on explicit structures. This PR changes our classifier to assign SystemV eightbytes with an algorithm that accounts for overlapping fields and fields that span multiple eightbytes. It also fixes a variety of bugs in the classifier related to structs (we wouldn't advance onto the next field when classifying a value-type or class-type field).

Fixes #4195
Fixes #4307
Fixes #22016 
Fixes #23150
Fixes #23150

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX10.12 x64 Debug Build and Test

**Comment by jashook** [comment]
@jkoritzinsky this may affect several tests which used to assume explicit layout forces structs to the stack. Off the top of my head this could effect the structABI test and the FastTailCallCandidates tests.

File: src/vm/methodtable.cpp [hunk 1]
```diff
@@ -2915,13 +2957,13 @@ bool MethodTable::ClassifyEightBytesWithNativeLayout(SystemVStructRegisterPassin
             }
         }
 
-        if ((normalizedFieldOffset % fieldNativeSize) != 0)
+        if ((normalizedFieldOffset % pFieldMarshaler->AlignmentRequirement()) != 0)
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: Why was this change needed?

File: src/vm/methodtable.cpp [hunk 2]
```diff
@@ -3001,7 +3048,7 @@ bool MethodTable::ClassifyEightBytesWithNativeLayout(SystemVStructRegisterPassin
 // Assigns the classification types to the array with eightbyte types.
 void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHelperPtr helperPtr, unsigned int nestingLevel) const
 {
-    static const size_t CLR_SYSTEMV_MAX_BYTES_TO_PASS_IN_REGISTERS = CLR_SYSTEMV_MAX_EIGHTBYTES_COUNT_TO_PASS_IN_REGISTERS * SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
+    constexpr size_t CLR_SYSTEMV_MAX_BYTES_TO_PASS_IN_REGISTERS = CLR_SYSTEMV_MAX_EIGHTBYTES_COUNT_TO_PASS_IN_REGISTERS * SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: It is not clear to me why was this change needed. All of the symbols in the expression are plain constants.

**Comment by CarolEidt** [comment]
@jashook - I don't *think* that this will impact the JIT's decision to force explicit layout structs to the stack. That decision is made independent of how the struct is passed. That is, even if the struct is passed in registers, the JIT will already have determine that such structs can't be enregistered, so they would be loaded into the appropriate registers from the stack (or other memory location).

File: src/vm/methodtable.cpp [hunk 3]
```diff
@@ -3061,72 +3115,69 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
...
-                _ASSERTE((fieldClassificationType != SystemVClassificationTypeIntegerReference) && 
-                    (fieldClassificationType != SystemVClassificationTypeIntegerByRef));
+            unsigned int fieldStartEightByte = offset / SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
+            unsigned int fieldEndEightByte = (offset + fieldSize) / SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
 
-                helperPtr->eightByteClassifications[currentEightByte] = SystemVClassificationTypeInteger;
-            }
-            else if ((helperPtr->eightByteClassifications[currentEightByte] == SystemVClassificationTypeIntegerReference) ||
-                (fieldClassificationType == SystemVClassificationTypeIntegerReference))
+            if ((offset + fieldSize) % SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES == 0)
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: You can get rid of this whole `if` if you modify the computation of the `fieldEndEightByte` above as follows:
```C++
unsigned int fieldEndEightByte = (offset + fieldSize - 1) / SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
```
(assuming the fieldSize cannot be zero here)

**Comment by jashook** [comment]
Looked into a few different tests, FastTailCallCandidates is effected as it used to attempt to test FastTailCalls with a caller/callee with stack space passing explicit structs. I believe there should not be an issue as the test still correct and mostly testing the same stuff.

File: src/vm/methodtablebuilder.cpp [hunk 4]
```diff
@@ -3828,6 +3829,20 @@ VOID    MethodTableBuilder::InitializeFieldDescs(FieldDesc *pFieldDescList,
             }
         }
 
+        // Determine if a field is a fixed buffer.
+        {
+            HRESULT hr;
+
+            hr = pInternalImport->GetCustomAttributeByName(bmtMetaData->pFields[i],
```
Comment (tannergooding) [inline src/vm/methodtablebuilder.cpp]: Just as a note. It is somewhat unfortunate that this detection is limited to `FixedBufferAttribute`.

The C# compiler currently only supports a limited set of types for its `fixed-sized buffers` and it currently results in an error (`error CS1716: Do not use 'System.Runtime.CompilerServices.FixedBuffer' attribute. Use the 'fixed' field modifier instead.`) if you try to use it for custom types.

This means that, in some scenarios, it may be impossible to create a struct with the appropriate layout. But, perhaps, this is something that can be fixed on the compiler end of things....

Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: At worst, the user can create a structure with each of the elements of the array as separate fields. The code in here for dealing with `FixedBufferAttribute` is more of a workaround for the fact that Roslyn only emits metadata for one field in the generated structure for a fixed buffer and that the attribute is placed on the field and not the type.

**Comment by jkotas** [comment]
This is Unix x64 ABI change and it would require major R2R format increment.

cc @fadimounir @trylek

**Comment by trylek** [comment]
Hmm, and a port to the CPAOT GC ref map emitter :-).

File: src/vm/methodtablebuilder.cpp [hunk 5]
```diff
@@ -3828,6 +3829,20 @@ VOID    MethodTableBuilder::InitializeFieldDescs(FieldDesc *pFieldDescList,
             }
         }
 
+        // Determine if a field is a fixed buffer.
+        {
```
Comment (jkotas) [inline src/vm/methodtablebuilder.cpp]: What is the performance impact of fetching a custom attribute on every field in the type loader now?

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX10.12 x64 Debug Build and Test

File: src/vm/methodtable.cpp (hunk 1 above)
Comment (jkoritzinsky) [reply src/vm/methodtable.cpp]: Fixed arrays have the alignment requirement of their type instead of the size of the array. For example, an `int[3]` can be aligned on a 4 byte boundary. It doesn't have to be on a 12 byte boundary. The same situation happens with structures and classes.

File: src/vm/methodtablebuilder.cpp (hunk 4 above)
Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: Also as a quick note, for compatibility reasons, the runtime will likely never support correctly marshalling fixed buffers of non-blittable types.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX10.12 x64 Debug Build and Test

File: src/vm/methodtablebuilder.cpp (hunk 5 above)
Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: I'll try to go run some benchmarks.

I also just went and checked with roslyn where fixed buffers can appear and it looks like they can only be in value types. I'll go add in some conditions here to only look for the attribute when absolutely necessary to reduce the impact.

**Comment by jkotas** [comment]
How is what we are doing here compatible with Mono? Is Mono going to be able to match this behavior?

cc @marek-safar

**Comment by jkoritzinsky** [comment]
As far as I can tell from a glance Mono's implementation, they're already fully compatible with the SystemV ABI here. So this change brings us more in line with Mono.


See https://github.com/mono/mono/blob/21d77b319a346f3eca439814f151a29de55b906f/mono/mini/mini-amd64.c#L631 for the Mono implementation.

**Comment by jkotas** [comment]
I do not see any place where Mono looks at the Fixed attribute...

**Comment by jkoritzinsky** [comment]
Good point on the `FixedBufferAttribute`. That part I don't see in mono either.

File: src/vm/methodtablebuilder.cpp (hunk 5 above)
Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: And after a few more runs of those benchmarks again in a different order, I've now seen all of the benchmarks I've run come in at 0% perf hit or 1% perf improvement (which is very likely just noise).

**Comment by marek-safar** [comment]
@jkotas we know that we are already incompatible especially with behaviour around overlapping. I think we will be able to match if it will be well defined or at least specified by test suite

File: src/vm/methodtablebuilder.cpp (hunk 4 above)
Comment (jkotas) [reply src/vm/methodtablebuilder.cpp]: The HFA classifier for ARM/ARM64 deals with this case by assuming that all fields in the struct with explicitly specified size are of the same type, without checking the fixed attribute: https://github.com/dotnet/coreclr/blob/master/src/vm/class.cpp#L1316 . Can we do the same here?

Also, do we need to make matching fixes in the HFA classifier as well to make the explicit layout work better across all platforms (ARM/ARM64)? It has the same block for explicit layout: https://github.com/dotnet/coreclr/blob/master/src/vm/class.cpp#L1246

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs [hunk 6]
```diff
@@ -316,6 +317,13 @@ public static int Main()
...
     static extern bool MarshalStructAsParam_AsSeqByValSequentialAggregateSequentialWrapper(AggregateSequentialWrapper wrapper);
 
+    [DllImport("MarshalStructAsParam")]
+    static extern bool MarshalStructAsParam_AsSeqByValFixedBufferClassificationTest(FixedBufferClassificationTest str, float f);
+    [DllImport("MarshalStructAsParam")]
+    static extern bool MarshalStructAsParam_AsSeqByValFixedBufferClassificationTest(FixedBufferClassificationTestBlittable str, float f);
+    [DllImport("MarshalStructAsParam")]
+    static extern bool MarshalStructAsParam_AsSeqByValFixedBufferClassificationTest(FixedArrayClassificationTest str, float f);
+
     [DllImport("MarshalStructAsParam")]
```
Comment (jkotas) [inline tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs]: We should have more variants of HFAs. E.g. the `ExplicitHFA` like this should have the same ABI as the `HFA` - across all platforms. Do you agree? I do not think it is the case today.

```
[StructLayout(LayoutKind.Explicit, Size = 16)]
struct ExplicitHFA
{
    [Offset(0)]
    float f1;
    [Offset(4)]
    float f2;
    [Offset(8)]
    fixed float f[2];
}
```

File: src/vm/methodtablebuilder.cpp (hunk 4 above)
Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: > The HFA classifier for ARM/ARM64 deals with this case by assuming that all fields in the struct with explicitly specified size are of the same type, without checking the fixed attribute: https://github.com/dotnet/coreclr/blob/master/src/vm/class.cpp#L1316 . Can we do the same here?

We can't do the same logic. HFAs are unique in that they always have fields of the same type, and by the time the code gets to that line, that check has already been completed. We could probably do a check of "Sequential struct has one field of primitive value type, with an explicit size that is a multiple of that value type" to determine if a type is maybe a fixed buffer. That might catch some false-positives, but those false positives would be really weird ways of writing structures anyway.

> Also, do we need to make matching fixes in the HFA classifier as well to make the explicit layout work better across all platforms (ARM/ARM64)? It has the same block for explicit layout: https://github.com/dotnet/coreclr/blob/master/src/vm/class.cpp#L1246

Possibly? I haven't looked at the ARM/ARM64 calling convention docs. A quick fix for most explicit layout HFAs likely would be bailing out of there are any overlapping or unaligned fields. I'll see if I can find more information on how the HFA stuff works.

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs (hunk 6 above)
Comment (jkotas) [reply tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs]: > how the HFA stuff works

It is simpler version of the SystemV calling convention - it just deals with homegenous floating point values. E.g. consider this:

```
[StructLayout(LayoutKind.Explicit, Size = 8)]
struct MyHFA
{
    [Offset(0)]
    float f1;
    [Offset(4)]
    float f2;
}
```

And matching C/C++ structure like this:

```
struct MyHFA
{
    float f1;
    float f2;
}
```

Today, it does not work on either Unix x64 or any ARM platform. Your fix makes it work on Unix x64. I think we should make it work on ARM/ARM64 as well for consistency.

**Comment by jkotas** [comment]
> how the HFA stuff works

It is simpler version of the SystemV calling convention - it just deals with homegenous floating point values. E.g. consider this:

```
[StructLayout(LayoutKind.Explicit, Size = 8)]
struct MyHFA
{
    [Offset(0)]
    float f1;
    [Offset(4)]
    float f2;
}
```

And matching C/C++ structure like this:

```
struct MyHFA
{
    float f1;
    float f2;
}
```

Today, it does not work on either Unix x64 or any ARM platform. Your fix makes it work on Unix x64. I think we should make it work on ARM/ARM64 as well for consistency.

File: src/vm/methodtablebuilder.cpp (hunk 4 above)
Comment (jkotas) [reply src/vm/methodtablebuilder.cpp]: > We could probably do a check of "Sequential struct has one field of primitive value type, with an explicit size that is a multiple of that value type" to determine

Right, this is what I meant. It is roughly what the HFA classifier does on ARM/ARM64.

Comment (jkoritzinsky) [reply src/vm/methodtablebuilder.cpp]: Ok I'll try that out and see if it works.

**Comment by jkoritzinsky** [comment]
@jkotas I've added support for aligned, non overlapping HFAs even if marked as explicit. I'm in the process of adding tests for it. I have a question though: Are structures with overlapping (float/double only and aligned) fields also allowed to be HFAs/not forbidden from being HFAs?

File: src/vm/class.cpp [hunk 7]
```diff
@@ -1282,9 +1281,17 @@ EEClass::CheckForHFA()
             break;
 
         case ELEMENT_TYPE_R4:
+            if (pFD->GetOffset() % alignof(float) != 0) // HFAs don't have unaligned fields.
```
Comment (jkotas) [inline src/vm/class.cpp]: We do not want to depend on the C/C++ idea of alignment. It breaks with cross-compilation among other things. The alignment should be actual number.

**Comment by jkotas** [comment]
> Are structures with overlapping (float/double only and aligned) fields also allowed to be HFAs

I do not know. Try to compile a couple of tests using C++ compiler and look at the disassembly.

File: src/vm/methodtable.cpp [hunk 8]
```diff
@@ -2330,25 +2320,54 @@ bool MethodTable::ClassifyEightBytesWithManagedLayout(SystemVStructRegisterPassi
...
+    // It is possible that we catch a false positive with this check, but that chance is extremely slim
+    // and the user can always change their structure to something more descriptive of what they want
+    // instead of adding additional padding at the end of a one-field structure.
+    // We do this check here to save looking up the FixedBufferAttribute when loading the field
+    // from metadata.
+    bool isFixedBuffer = numIntroducedFields == 1
+                                && ( CorTypeInfo::IsPrimitiveType_NoThrow(firstFieldElementType)
+                                    || firstFieldElementType == ELEMENT_TYPE_VALUETYPE)
+                                && (pFieldStart->GetOffset() == 0)
+                                && IsValueType()
```
Comment (jkotas) [inline src/vm/methodtable.cpp]: Can we ever come here for non ValueType types?

File: src/vm/methodtable.cpp [hunk 9]
```diff
@@ -2330,25 +2320,54 @@ bool MethodTable::ClassifyEightBytesWithManagedLayout(SystemVStructRegisterPassi
...
+    // and who's size is an exact multiple of the size of the field.
+    // It is possible that we catch a false positive with this check, but that chance is extremely slim
+    // and the user can always change their structure to something more descriptive of what they want
+    // instead of adding additional padding at the end of a one-field structure.
+    // We do this check here to save looking up the FixedBufferAttribute when loading the field
+    // from metadata.
+    bool isFixedBuffer = numIntroducedFields == 1
+                                && ( CorTypeInfo::IsPrimitiveType_NoThrow(firstFieldElementType)
+                                    || firstFieldElementType == ELEMENT_TYPE_VALUETYPE)
+                                && (pFieldStart->GetOffset() == 0)
```
Comment (jkotas) [inline src/vm/methodtable.cpp]: The HFA classifier does not check for offset 0. I would expect both of them to use same logic - either both check for offset 0 or none of them.

File: src/vm/methodtable.cpp [hunk 10]
```diff
@@ -2330,25 +2320,54 @@ bool MethodTable::ClassifyEightBytesWithManagedLayout(SystemVStructRegisterPassi
...
+                                && IsValueType()
+                                && HasLayout()
+                                && (GetLayoutInfo()->GetManagedSize() % pFieldStart->GetSize() == 0);
+
+    if (isFixedBuffer)
+    {
+        numIntroducedFields = GetLayoutInfo()->GetManagedSize() / pFieldStart->GetSize();
```
Comment (jkotas) [inline src/vm/methodtable.cpp]: The HFA classifier uses `GetMethodTable()->GetNumInstanceFieldBytes()` and does not require the struct to have Layout to be eligible.

File: src/vm/methodtable.cpp (hunk 8 above)
Comment (jkoritzinsky) [reply src/vm/methodtable.cpp]: I don't think we can get here for non ValueType types for the managed layout. We definitely can for the native layout though.

**Comment by jkoritzinsky** [comment]
The HFA classification rules are simple enough that they don't need any special knowledge about C# fixed buffer structures. They are effectively a "go/no go" on enregistering. Conversely, the SystemV rules include the reclassification and classification resolution that depends on the specific classifications of fields in their specific locations in layout, which is why I added the special logic for fixed buffers to the SystemV classifier.

**Comment by jkoritzinsky** [comment]
As far as I understand the rules for ARM/ARM64, if something is enregistered on ARM/ARM64 as an HFA, it will also be enrigistered on Unix x64. I believe that holds with this change.

File: src/vm/methodtable.cpp [hunk 11]
```diff
@@ -2627,15 +2644,10 @@ bool MethodTable::ClassifyEightBytesWithNativeLayout(SystemVStructRegisterPassin
 #ifdef _DEBUG
     LOG((LF_JIT, LL_EVERYTHING, "%*s**** Classify for native struct %s (%p), startOffset %d, total struct size %d\n",
         nestingLevel * 5, "", this->GetDebugClassName(), this, startOffsetOfStruct, helperPtr->structSize));
-    int fieldNum = -1;
 #endif // _DEBUG
 
-    while (numIntroducedFields--)
+    for (unsigned int fieldNum = 0; fieldNum < numIntroducedFields; fieldNum++)
```
Comment (AaronRobinsonMSFT) [inline src/vm/methodtable.cpp]: Can we change `fieldNum` to `fieldIndex`? When I see 'num' I think of number/count and that isn't what this means in this case. See `numIntroducedFields` as an example.

File: src/vm/methodtable.cpp [hunk 12]
```diff
@@ -2703,17 +2722,33 @@ bool MethodTable::ClassifyEightBytesWithNativeLayout(SystemVStructRegisterPassin
...
 
                 if (!structRet)
                 {
                     // If the nested struct says not to enregister, there's no need to continue analyzing at this level. Just return do not enregister.
                     return false;
                 }
 
+                if (!isFixedBuffer) // We reuse the field marshaler for fixed buffers.
+                {
+                    ((BYTE*&)pFieldMarshaler) += MAXFIELDMARSHALERSIZE;
```
Comment (AaronRobinsonMSFT) [inline src/vm/methodtable.cpp]: This deserves a comment. Whenever pointer arithmetic is being done after a cast to `BYTE*` there needs to be a comment.

File: src/vm/methodtable.cpp [hunk 13]
```diff
@@ -2703,17 +2722,33 @@ bool MethodTable::ClassifyEightBytesWithNativeLayout(SystemVStructRegisterPassin
...
-                helperPtr->inEmbeddedStruct = inEmbeddedStructPrev;
+                unsigned int numElements = ((FieldMarshaler_FixedArray*)pFieldMarshaler)->GetNumElements();
+
+                bool structRet = true;
+
+                for (unsigned int i = 0; i < numElements; i++, normalizedFieldOffset += pFieldMT->GetNativeSize())
+                {
+                    bool inEmbeddedStructPrev = helperPtr->inEmbeddedStruct;
+                    helperPtr->inEmbeddedStruct = true;
+                    structRet = pFieldMT->ClassifyEightBytesWithNativeLayout(
```
Comment (AaronRobinsonMSFT) [inline src/vm/methodtable.cpp]: We only care about the last setter of `structRet`? Seems like at the very least we should assert something consistent about them, or is there something I am missing about this loop? (i.e. we only ever care about the last element?)

File: src/vm/methodtable.cpp (hunk 12 above)
Comment (AaronRobinsonMSFT) [reply src/vm/methodtable.cpp]: This snippet it used multiple times. I am really curious what we are offsetting into.

File: src/vm/methodtable.cpp [hunk 14]
```diff
@@ -3029,23 +3087,31 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
...
 
-        unsigned offset = 0;
-        for (unsigned fieldSize = 0; offset < helperPtr->structSize; offset += fieldSize)
+        unsigned int usedEightBytes = 0;
+        unsigned int accumulatedSizeForEightBytes = 0;
+        bool foundFieldInEightByte = false;
+        for (unsigned int offset = 0; offset < helperPtr->structSize; offset++)
         {
             SystemVClassificationType fieldClassificationType;
+            unsigned fieldSize = 0;
```
Comment (AaronRobinsonMSFT) [inline src/vm/methodtable.cpp]: Please use `unsigned int` or `uint32_t`, not a plain `unsigned`.

File: tests/src/Interop/StructMarshalling/PInvoke/Struct.cs [hunk 15]
```diff
@@ -298,6 +298,25 @@ public struct LongStructPack16Explicit
...
+    public long l;
+
+    [FieldOffset(4)]
+    public float f;
+}
+
+[StructLayout(LayoutKind.Explicit)]
+public struct OverlappingLongFloat2
+{
+
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/StructMarshalling/PInvoke/Struct.cs]: Remove line

File: src/vm/methodtable.cpp (hunk 14 above)
Comment (jkotas) [reply src/vm/methodtable.cpp]: What's wrong with `unsigned` ?

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h [hunk 16]
```diff
@@ -196,11 +196,23 @@ union InnerArrayExplicit // size = 32 bytes
 #endif
 
 #ifndef WINDOWS
-	struct OUTER3 // size = 28 bytes
-	{
-		struct InnerSequential arr[2];
-		LPCSTR f4;
-	};
+    #ifdef __x86_64__
+        union OUTER3 // size = 32 bytes
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h]: Fix the alignment here. Also if you are declaring a size in comments, instead please use the `static_assert()` to compute and make it enforceable.

File: src/vm/methodtable.cpp (hunk 14 above)
Comment (AaronRobinsonMSFT) [reply src/vm/methodtable.cpp]: Technically nothing, but it is generally considered an antiquated way of declaring an `unsigned int` and in this PR is inconsistent since all other cases use `unsigned int`. I also personally prefer the use of `uint32_t` because it tells me the bitness without me thinking about target platform. In this case I don't think we compile on any platform where `int` is 16, but I tend to use it for clarity.

It is definitely a personal preference. If this is still considered a fine practice, then ignore.

Comment (danmosemsft) [reply src/vm/methodtable.cpp]: +1 I think not everyone knows what just unsigned means.

Comment (BruceForstall) [reply src/vm/methodtable.cpp]: Maybe this is going to be a religious argument, but I think any C/C++ programmer should know what plain `unsigned` means. We have almost interest in compiling with a toolset that doesn't think `int` or `unsigned int` isn't 32-bits, on any platform. (I think `wchar_t` is the only case where it differs in size by platform, and it's a huge pain.) Seems unlikely we would change all our code to use the size-specific types (e.g., `uint32_t`) instead of `unsigned` or `unsigned int`, etc.

**Comment by briansull** [comment]
I believe that on Arm64 a struct containing 3 or 4 floats or doubles is an HFA and is enregistered, 
The same struct having four fields will not be enregistered (there are no HFA on x64)

**Comment by jkoritzinsky** [comment]
I just checked on Godbolt. A structure with 3 or 4 doubles will be enregistered on ARM and ARM64, but not on x64.

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h (hunk 16 above)
Comment (jkoritzinsky) [reply tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h]: The alignment here is actually correct. The alignment of the `f4` field needs to be at the 24th byte on all architectures that this test runs on to match the managed definition (which gives the `f4` field an explicit `FieldOffset(24)`).

File: src/vm/methodtable.cpp (hunk 13 above)
Comment (jkoritzinsky) [reply src/vm/methodtable.cpp]: The return value of `ClassifyEightBytesWithNativeLayout` only depends on the `this` pointer. Which makes sense since the return value says "this type can or cannot be enregistered based on its native layout".

The only code-paths where it will return something different based on the passed in parameters are paths where it asserts in debug mode because it breaks an invariant. So the value we assign to `structRet` would be the same every time.

File: src/vm/methodtable.cpp (hunk 12 above)
Comment (jkoritzinsky) [reply src/vm/methodtable.cpp]: The field marshalers are stored sequentially in a single memory block. Each block for a field marshaler is `MAXFIELDMARSHALERSIZE` wide to support any of the derived `FieldMarshaler_*` types in it. This construct here is used basically anywhere field marshalers are used to move along to the next FieldMarshaler in the block.

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h (hunk 16 above)
Comment (AaronRobinsonMSFT) [reply tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h]: Uh... sorry. By alignment I meant source code. Please do the `static_assert` for size.

File: src/vm/methodtable.cpp (hunk 12 above)
Comment (AaronRobinsonMSFT) [reply src/vm/methodtable.cpp]: Sure, but that is not obvious. In fact this seems easy to just make a helper function that says `GetNextMarshaller(...)`.

Comment (AaronRobinsonMSFT) [reply src/vm/methodtable.cpp]: Nevermind. I see what you are saying.

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h [hunk 17]
```diff
@@ -63,8 +63,6 @@ struct INNER2 // size = 12 bytes
     LPCSTR f3;
 };
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h]: If the static assert doesn't hold, then the comment about 'size = 12 bytes' should definitely be removed since it is wrong. If seems like you want the condition to be 12 or 16 no?

Comment (jkoritzinsky) [reply tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsParamDLL.h]: Yeah. I thought I removed that comment. My mistake.

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX10.12 x64 Debug Build and Test

**Comment by jkoritzinsky** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test OSX10.12 x64 Debug Build and Test

**Comment by jkotas** [comment]
If we like this change, we should take it for 3.0 and bump the minimum required R2R version number. (It will cause R2R native images compiled on existing runtimes to be rejected and fallback to JIT.)

I do not think we will want to take this change for 3.x. If we do not take this change for 3.0, the next opportunity to take it would be 4.0.

**Comment by trylek** [comment]
Hmm, what's the quorum to make a call on whether "we like the change and take it for 3.0"? Technically it looks like general goodness; are there additional business considerations we need to keep in mind and / or managers who need to approve such a decision?

**Comment by jkotas** [comment]
I do not think we need to get shiproom approval for this. R2R has not been advertised broadly for apps and roll-forward between major version is not the default, so the impact of resetting R2R band for 3.0 is low.

**Comment by jkoritzinsky** [comment]
I can't seem to repro any of the OSX test failures on my Macbook Pro (running OSX10.13). I've tried each of the tests both on my branch and on the merge commit that CI is using and I can't repro any of the failures locally.

**Comment by janvorli** [comment]
> I can't seem to repro any of the OSX test failures on my Macbook Pro

You can try to rebase your local change to the latest master (or merge, whatever you prefer). The issue with Alpine build in your other issue the other day also did't repro on my box until I've merged the latest master.

**Comment by jkoritzinsky** [comment]
@janvorli I'll try that. It's weird though that I can't get it to repro even with using the exact commit SHA that the CI is using....

**Comment by jkoritzinsky** [comment]
@janvorli after rebasing, looks like the tests are passing on Jenkins but failing on Azure DevOps. I tried to get a repro via mc.dot.net, but even on that I can't repro the failures.

**Comment by jkotas** [comment]
> Also explicitly opt-out of HFAs for System.Numerics.Vector`1

We really want to be passing these perf-sensitive types in registers. Is this going be a perf regression from where we are today?

**Comment by jkoritzinsky** [comment]
The JIT classifies the `System.Numerics.Vector<T>` type somewhere else and actually requires that the SystemV and HFA classifier don't accidentally capture them. The current code on master actually already disqualifies `System.Numerics.Vector<T>` from being an HFA by the fact that the `System.Numerics.Register` type is explicit-layout, so this doesn't actually change anything; it's preserving current behavior.

File: tests/src/JIT/SIMD/SqrtGeneric.cs [hunk 18]
```diff
@@ -34,12 +34,14 @@ static int Main(string[] args)
             d = System.Numerics.Vector.SquareRoot(d);
             if (((int)d[0]) != 10)
             {
+                Console.WriteLine($"Expected 10, got {d[0]}.");
```
Comment (AaronRobinsonMSFT) [inline tests/src/JIT/SIMD/SqrtGeneric.cs]: Remove these?

**Comment by jkoritzinsky** [comment]
CoreFX failures are known and will be fixed by #23697.

CoreCLR Pri 1 failures are known and will be fixed by #23738
