### PR TITLE
JIT: ensure float folding is done using float precision

### LINKED ISSUE #20561: JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48990\b48990a regression
This regression is caused by #17996.

if we have such IL:
```
    [ 0]  17 (0x011) ldloc.0
    [ 1]  18 (0x012) ldc.r4 2.0000000000000000
    [ 2]  23 (0x017) div
    [ 1]  24 (0x018) conv.r4 <- cast from double to float.
    [ 1]  25 (0x019) ldc.r4 0.00000000000000000
    [ 2]  30 (0x01e) ceq
    [ 1]  32 (0x020) stloc.3
```
then before the change we had:
```
               [000017] ------------              *  STMT      void  (IL 0x011...  ???)
               [000013] ------------              |     /--*  CNS_DBL   float  0.00000000000000000
               [000014] ------------              |  /--*  EQ        int
               [000012] ------------              |  |  \--*  CAST      float <- float
               [000010] ------------              |  |     |  /--*  CNS_DBL   float  2.0000000000000000
               [000011] ------------              |  |     \--*  DIV       float
               [000009] ------------              |  |        \--*  LCL_VAR   float  V00 loc0
               [000016] -A----------              \--*  ASG       int
               [000015] D------N----                 \--*  LCL_VAR   int    V03 loc3
```
but now we do not have this cast `[000012]`.

This cast protected us on x86 with x87 floating point stack.
The next tree in this test is:
```
    [ 0]  33 (0x021) ldloc.3
    [ 1]  34 (0x022) brtrue.s

               [000022] ------------              *  STMT      void  (IL 0x021...  ???)
               [000021] ------------              \--*  JTRUE     void
               [000019] ------------                 |  /--*  CNS_INT   int    0
               [000020] ------------                 \--*  NE        int
               [000018] ------------                    \--*  LCL_VAR   int    V03 loc3
```
when we do `Folding fp operator with constant nodes into a fp constant` for `[000011]` in https://github.com/dotnet/coreclr/blob/f69b623c9f41c5d358d52f40e5cdad808b005bed/src/jit/gentree.cpp#L14136-L14145
on x87 c++ compiler generates:
```
0F407222  fld         dword ptr [f1]  
0F407225  fdiv        dword ptr [f2] <- push a result on stack as qword.  
0F407228  fstp        qword ptr [d1] <- read the result as qword(double).
```
that leaves `d1=7.0064923216240854e-46` and then we propogate it as `LCL_VAR   int    V03 loc3` and fold 
` 0 != 7.0064923216240854e-46  ( [000014] ------------              |  /--*  EQ        int)` to `false`.

on x86 with SIMD C++ generates:
```
00007FFA95D2A819  movss       xmm0,dword ptr [f1]  
00007FFA95D2A81F  divss       xmm0,dword ptr [f2]  <- stores the single-precision floating-point result in the destination operand.
00007FFA95D2A828  cvtss2sd    xmm0,xmm0  
00007FFA95D2A82C  movsd       mmword ptr [d1],xmm0 
```
that sets `d0=0` and works fine.

So on x87 the test return 1 (because everything is collapsed into on false branch), on other platforms 100.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Cast float folded values back to float before assigning to the double
the jit uses for storing FP literal constants.

Fixes #20561.

No diffs on Core; exposing the original bug requires building RyuJit with
an older x86 C++ compiler that uses x87 floating point.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@sandreenko PTAL
cc @dotnet/jit-contrib 

Verified this fixes the original test (using x86 protojit on desktop). Still running wider desktop tests; will update the PR when I have more info.

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -14099,7 +14099,7 @@ GenTree* Compiler::gtFoldExprConst(GenTree* tree)
                     {
                         f1 = forceCastToFloat(d1);
                         f2 = forceCastToFloat(d2);
-                        d1 = f1 + f2;
+                        d1 = forceCastToFloat(f1 + f2);
```
Comment (tannergooding) [inline src/jit/gentree.cpp]: is the `non-x86 arch` comment above still valid? Now that x86 uses SSE/SSE2 (rather than the FPU stack), the comment should be applicable for all architectures. Right?

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -14112,7 +14112,7 @@ GenTree* Compiler::gtFoldExprConst(GenTree* tree)
                     {
                         f1 = forceCastToFloat(d1);
                         f2 = forceCastToFloat(d2);
-                        d1 = f1 - f2;
+                        d1 = forceCastToFloat(f1 - f2);
```
Comment (tannergooding) [inline src/jit/gentree.cpp]: Would it be beneficial to just store these as floats as well?

Comment (tannergooding) [reply src/jit/gentree.cpp]: (maybe as a long term goal, not necessarily as part of this PR)

File: src/jit/gentree.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Yes, I will update it. Thanks.

File: src/jit/gentree.cpp (hunk 2 above)
Comment (AndyAyersMS) [reply src/jit/gentree.cpp]: Hard to say ... there are some interesting bits of code here and there which might benefit:

https://github.com/dotnet/coreclr/blob/8939f019c34febbf0bab9dcc0f13b9ddc58735d8/src/jit/optcse.cpp#L2506-L2520

Comment (tannergooding) [reply src/jit/gentree.cpp]: Right, and in apps that largely use `floats`, rather than `doubles` (like ML.NET, games, graphics, etc); there might be some space-savings (and with the `System.MathF` support, you don't have the intermediate `double` either).

Comment (tannergooding) [reply src/jit/gentree.cpp]: > There's no connection between storing float constants as doubles, JIT32 leftovers like the CSE one above and space-savings of any kind.

I meant that `double` takes twice the space of `float` (8-bytes vs 4-bytes), so each `float` constant being stored is taking twice as much memory as is needed. That will have some impact in the tree, everywhere a `DconNode` appears, and in the ValueNum store where the values are actually cached (although this looks to already have separate maps for double vs float).

Comment (mikedn) [reply src/jit/gentree.cpp]: > I meant that double takes twice the space of float (8-bytes vs 4-bytes), so each float constant being stored is taking twice as much memory as is needed. That will have some impact in the tree, everywhere a DconNode appears,

No, it won't.

Comment (tannergooding) [reply src/jit/gentree.cpp]: > No, it won't.

Would you care to elaborate? There is obviously something I'm missing here 😄

Comment (mikedn) [reply src/jit/gentree.cpp]: > Would you care to elaborate? There is obviously something I'm missing here 

Like the fact that tree nodes have a fixed size so removing stuff from them won't make them smaller. And that on 64 bit targets using float instead of double will only buy you 4 bytes of padding at the end of the struct.

Comment (tannergooding) [reply src/jit/gentree.cpp]: Ah, right. I forgot that it uses `TREE_NODE_SZ_SMALL` and `TREE_NODE_SZ_LARGE`, rather than the sizeof the struct.

**Comment by AndyAyersMS** [comment]
* ubuntu arm cross another failed test assembly load by xunit:
```
13:53:53   System.IO.FileLoadException: Could not load file or assembly 'Exceptions.ForeignThread.XUnitWrapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509 (COR_E_INVALIDOPERATION))
```
* ubuntu x64 another xunit dispose-related issue
```
13:44:36   Unhandled Exception: System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
13:44:36      at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
13:44:36      at Xunit.Sdk.DisposalTracker.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
13:44:36      at Xunit.Sdk.ExtensibilityPointFactory.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 54
13:44:36      at Xunit.Sdk.TestFramework.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 49
13:44:36      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
13:44:36   --- End of stack trace from previous location where exception was thrown ---
13:44:36      at System.Threading.ThreadPoolWorkQueue.Dispatch()
13:44:36   Aborted (core dumped)
```
* windows x86 perf failed for no good reason:
```
13:41:33   Building Custom Rule D:/j/w/perf_perflab_---1c2b0529/src/ildasm/rcdll/CMakeLists.txt
13:41:33   CMake does not need to re-run because D:/j/w/perf_perflab_---1c2b0529/bin/obj/Windows_NT.x86.Release/src/ildasm/rcdll/CMakeFiles/generate.stamp is up-to-date.
13:42:39 FATAL: command execution failed
13:42:39 java.nio.channels.ClosedChannelException
13:42:39 	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
```

**Comment by AndyAyersMS** [comment]
* windows NT arm64 cross 

failure is tracked by #20580 

* wiindows NT arm another CI hangup:
```
14:56:52 dotnet_coreclr » master » arm_cross_checked_windows_nt_innerloop_tst_prtest #1877 completed 
14:56:52 FATAL: Remote call on JNLP4-connect connection from 13.64.171.65/13.64.171.65:49176 failed. The channel is closing down or has closed down
14:56:52 java.nio.channels.ClosedChannelException
14:56:52 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
```

**Comment by AndyAyersMS** [comment]
Copying from the linked issue:

Desktop test.devBVT.SelfHost.RyuJIT@x86chk passed with no failures.
Still working on desktop SPMI diffs, having some technical difficulties.

**Comment by AndyAyersMS** [comment]
Finally got the desktop x86 SPMI diffs (thanks @sandreenko). 

The only two diffs reported were in the two b48990 test cases.
