### PR TITLE
Disable VSD Stub Kind Prediction on H/W Exception

### LINKED ISSUE #14031: [ARM/Linux] Segmentation fault inside SIGSEGV signal handler
We often see the following segmentation fault in ARM/Linux:
```
Program received signal SIGSEGV, Segmentation fault.
0xf76e0ee2 in VirtualCallStubManager::predictStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
(gdb) bt
#0  0xf76e0ee2 in VirtualCallStubManager::predictStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#1  0xf76e902e in VirtualCallStubManager::getStubKind(unsigned int) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#2  0xf76e4b7f in VirtualCallStubManager::FindStubManager(unsigned int, VirtualCallStubManager::StubKind*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#3  0xf77a03d0 in IsSafeToHandleHardwareException(_CONTEXT*, _EXCEPTION_RECORD*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#4  0xf7a1be08 in SEHProcessException(PAL_SEHException*) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#5  0xf7a1d4c7 in common_signal_handler(int, siginfo_t*, void*, int, ...) () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#6  0xf7a1d30e in signal_handler_worker () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#7  0xf7a58497 in CallSignalHandlerWrapper12 () from /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Release.Release/libcoreclr.so
#8  0x00000007 in ?? ()
```

I could reproduce this issue with the following code:
 - Program.cs
```cs
using System;
using System.Reflection;
using System.Runtime.Loader;
using System.Runtime.InteropServices;

namespace ReversePInvoke
{
    class Program
    {
        [DllImport("libmiddle.so")]
        static extern int Invoke(int n);

        static void Main(string[] args)
        {
            Invoke(0);
        }
    }
}
```
 - native.c
```c
#include <stdio.h>

typedef void (*cb_t)(int);

int Invoke(int n)
{
    printf("Invoke!\n");
    cb_t fn = (cb_t)0x7;
    fn(4);
    return 0;
}
```

The issue itself comes from native code, but coredump debugging would be much easier if CLR's signal handler does not crash for this case.

### PR DESCRIPTION
**Pull request by parjong**
This commit disables VSD Stub Kind Prediction on H/W Exception (as suggested in #14032) to fix #14031.

### CODE REVIEW

File: src/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -5156,7 +5156,7 @@ static BOOL IsIPinVirtualStub(PCODE f_IP)
     }
 
     VirtualCallStubManager::StubKind sk;
-    VirtualCallStubManager::FindStubManager(f_IP, &sk);
+    VirtualCallStubManager::FindStubManager(f_IP, &sk, false);
```
Comment (janvorli) [inline src/vm/exceptionhandling.cpp]: A nit - could you please add comment with the argument name after the false to indicate what that false means for easier reading of the code? Like this:
```C++
VirtualCallStubManager::FindStubManager(f_IP, &sk, false /* usePredictStubKind */); 

```

File: src/vm/virtualcallstub.cpp [hunk 2]
```diff
@@ -974,7 +974,7 @@ void VirtualCallStubManager::Reclaim()
 
 //----------------------------------------------------------------------------
 /* static */
-VirtualCallStubManager *VirtualCallStubManager::FindStubManager(PCODE stubAddress,  StubKind* wbStubKind)
+VirtualCallStubManager *VirtualCallStubManager::FindStubManager(PCODE stubAddress,  StubKind* wbStubKind, bool usePredictStubKind)
```
Comment (janvorli) [inline src/vm/virtualcallstub.cpp]: A nit - for the sake of consistency, it would be better to use `BOOL` instead of `bool` to match other functions in this class.

File: src/vm/exceptionhandling.cpp [hunk 3]
```diff
@@ -5156,7 +5156,7 @@ static BOOL IsIPinVirtualStub(PCODE f_IP)
     }
 
     VirtualCallStubManager::StubKind sk;
-    VirtualCallStubManager::FindStubManager(f_IP, &sk);
+    VirtualCallStubManager::FindStubManager(f_IP, &sk, false /* usePredictStubKind */);
```
Comment (parjong) [inline src/vm/exceptionhandling.cpp]: @janvorli Should I use ``FALSE`` (instead of ``false``) here?

Comment (janvorli) [reply src/vm/exceptionhandling.cpp]: Yes

File: src/vm/virtualcallstub.h [hunk 4]
```diff
@@ -317,7 +317,7 @@ class VirtualCallStubManager : public StubManager
     /* know thine own stubs.  It is possible that when multiple
     virtualcallstub managers are built that these may need to become
     non-static, and the callers modified accordingly */
-    StubKind getStubKind(PCODE stubStartAddress)
+    StubKind getStubKind(PCODE stubStartAddress, bool usePredictStubKind = true)
```
Comment (janvorli) [inline src/vm/virtualcallstub.h]: The parameter default value should be "TRUE".
