### PR TITLE
Fix struct assignment where types differ

### LINKED ISSUE #27551: impAssignStructPtr incorrectly optimizes assignment when dst and src are different struct types
As from https://github.com/dotnet/coreclr/pull/27481, on ARM32 the `Vector256<T> AsVector256<T>(Vector<T>)` method is not behaving as expected when TieredCompilation is disabled:
* [JitDump_AsVector256_TC=1.txt](https://github.com/dotnet/coreclr/files/3785975/JitDump_AsVector256_TC.1.txt) -- Doesn't repro
* [JitDump_AsVector256_TC=0.txt](https://github.com/dotnet/coreclr/files/3785976/JitDump_AsVector256_TC.0.txt) -- Does repro

Namely, the JIT is detecting a struct initializer to have no side-effects and is therefore removing it:
```
removing stmt with no side effects

Removing statement STMT00005 (IL 0x019...  ???)
N003 (  5,  4) [000015] IA------R----             *  ASG       struct (init)
N002 (  3,  2) [000012] D------N-----             +--*  LCL_VAR   struct V02 loc0         
N001 (  1,  1) [000014] -------------             \--*  CNS_INT   int    0
 in BB03 as useless:
```

This appears to have been root caused to https://github.com/dotnet/coreclr/blob/80867d1b5753ea5625b63aecccab1084c84e62af/src/jit/importer.cpp#L1185-L1195 where it is failing because both `destNode` and `src` are TYP_STRUCT, but their handles differ.

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #27551 
The first commit adds a small repro test case. I verified that it fails on arm/linux without the fix: https://dev.azure.com/dnceng/public/_build/results?buildId=409199&view=logs
The second commit fixes `impAssignStructPtr` by moving the optimization to eliminate the indirection after the various cases have been handed, and adds a check that the handles are the same.

### CODE REVIEW

File: tests/src/JIT/Regression/JitBlue/GitHub_27551/GitHub_27551.cs [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    static byte GetByte()
+    {
+        return 0xaa;
+    }
+
+    [MethodImpl(MethodImplOptions.NoInlining)]
+    static void ValidateResult(Byte[] resultElements, Byte[] valueElements)
+    {
+        bool succeeded = true;
```
Comment (sandreenko) [inline tests/src/JIT/Regression/JitBlue/GitHub_27551/GitHub_27551.cs]: Nit: `succeeded` is unused.

**Comment by CarolEidt** [comment]
There are a small number of diffs, so I'm trying to rework this to avoid them.

**Comment by CarolEidt** [comment]
There were two regressions in crossgen diffs. One is a case where it shouldn't be eliding the block (it's a test with an invalid type `Vector<Vector<>>`. The other was a case where it was eliding the block node for an assignment between two vector types of the same size but different class handle, which we should continue to allow. The 4th commit allows that case. Now there is only that one regression in crossgen diffs, and no regressions in PMI diffs.

**Comment by CarolEidt** [comment]
@sandreenko @dotnet/jit-contrib PTAL

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -1407,6 +1382,28 @@ GenTree* Compiler::impAssignStructPtr(GenTree*             destAddr,
         asgType     = impNormStructType(structHnd);
         src->gtType = asgType;
     }
+    if ((dest == nullptr) && (destAddr->OperGet() == GT_ADDR))
+    {
+        GenTree* destNode = destAddr->gtGetOp1();
+        // If the actual destination is a local, or already a block node, or is a node that
+        // will be morphed, don't insert an OBJ(ADDR) if it already has the right type.
+        if ((destNode->gtOper == GT_INDEX) || destNode->OperIsBlk() || (destNode->OperGet() == GT_LCL_VAR))
```
Comment (briansull) [inline src/jit/importer.cpp]: This can be expressed better as:

`if (destNode->OperIs(GT_LCL_VAR, GT_INDEX) ||  destNode->OperIsBlk())`

Also the comment above should be updated to:

` // If the actual destination is a local, a GT_INDEX or  a block node,  ...`

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your coreclr repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/coreclr <path to the patch created in step 1>`

**Comment by BruceForstall** [comment]
Interesting win-arm64 build failure:
```
Assert failure(PID 2656 [0x00000a60], Thread: 12392 [0x3068]): Assertion failed '(node->TypeGet() == TYP_STRUCT) || use.User()->OperIsInitBlkOp()' in 'System.Numerics.Matrix4x4:CreateBillboard(System.Numerics.Vector3,System.Numerics.Vector3,System.Numerics.Vector3,System.Numerics.Vector3):System.Numerics.Matrix4x4' (IL size 318)

    File: F:\workspace\_work\1\s\src\jit\rationalize.cpp Line: 752
    Image: F:\workspace\_work\1\s\bin\Product\Windows_NT.arm64.Checked\x64\crossgen.exe
```

**Comment by CarolEidt** [comment]
@BruceForstall - yes, I'm tracking down that failure. It's problematic to discern what the invariants are at this point, in order to identify the right conditions for eliding the block node.

**Comment by CarolEidt** [comment]
I ran crossgen altjit diffs, and encountered another diff on arm64 (an improvement this time) - it's a case where we avoid creating a block node where we had previously created one. The final code is essentially the same, but we wind up with slightly better register allocation.
