### PR TITLE
Fix build warnings in Vector3Interop test

### LINKED ISSUE #6236: Native build warnings under tests\src\jit
```
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(250): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(386): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(387): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(403): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(404): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
c:\git\coreclr\tests\src\jit\simd\vector3testnative.cpp(419): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\git\coreclr\bin\tests\obj\Windows_NT.x64.Checked\Native\src\JIT\SIMD\Vector3TestNative.vcxproj]
```

### PR DESCRIPTION
**Pull request by RussKeldorph**
Fixes #6236

### CODE REVIEW

File: tests/src/JIT/SIMD/Vector3TestNative.cpp [hunk 1]
```diff
@@ -21,6 +21,10 @@
 #endif  // !__i386__
 #endif // !defined(_MSC_VER)
 
+#ifndef _countof
```
Comment (RussKeldorph) [inline tests/src/JIT/SIMD/Vector3TestNative.cpp]: All of this stuff belongs in a common header, but we currently don't have that.  The Interop tests have some common stuff that should probably be moved to a common location that all tests can share.

File: tests/src/JIT/SIMD/Vector3TestNative.cpp [hunk 2]
```diff
@@ -247,7 +249,7 @@ EXPORT(void) __stdcall nativeCall_PInvoke_Vector3InComplexStruct(ComplexDT* arg)
     arg->v3.y = arg->v3.y + 1;
     arg->v3.z = arg->v3.z + 1;    
     arg->iv = arg->iv + 1;
-    strncpy(arg->str, ret_str, strnlen("ret_str", 32));
+    snprintf(arg->str, _countof(arg->str), "%s", "ret_string");
```
Comment (RussKeldorph) [inline tests/src/JIT/SIMD/Vector3TestNative.cpp]: This should be strcpy_s, but we don't have that outside of Windows.  Again, there are implementations in other places; they just aren't currently available to this test.

**Comment by RussKeldorph** [comment]
@CarolEidt PTAL
/cc @dotnet/jit-contrib

File: tests/src/JIT/SIMD/Vector3TestNative.cpp (hunk 1 above)
Comment (CarolEidt) [inline tests/src/JIT/SIMD/Vector3TestNative.cpp]: It was previously suggested that this test should be moved to the Interop tests, but we felt that it belongs with the SIMD tests. I agree that it would be a good thing to have this is a common location.

**Comment by CarolEidt** [comment]
LGTM
