### PR TITLE
[RyuJIT/ARM32] Update LinearScan::resolveLocalRef() for ARM32

### LINKED ISSUE #11847: [RyuJIT/arm32] Assertion failed '!assignedInterval->isActive || isSecondHalfReg(physRegRecord, assignedInterval)'
At lsra.cpp Line: 6861

Example:
```
Assert failure(PID 13744 [0x000035b0], Thread: 9416 [0x24c8]): Assertion failed '!assignedInterval->isActive || isSecondHalfReg(physRegRecord, assignedInterval)' in 'JitTest.Test:TestSqrt(double,double)' (IL size 195)

    File: c:\gh\coreclr\src\jit\lsra.cpp Line: 6861
    Image: c:\brucefo\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

Tests with this assert:
```
JIT\Methodical\NaN\intrinsic_cs_do\intrinsic_cs_do.cmd
JIT\Methodical\NaN\intrinsic_cs_ro\intrinsic_cs_ro.cmd
JIT\Methodical\NaN\intrinsic_nonf_il_r\intrinsic_nonf_il_r.cmd
```

### PR DESCRIPTION
**Pull request by hqueue**
Fix #11847 

Update LinearScan::resolveLocalRef()
- Always update two float register consisting a double register
- Use helper function for ARM32 double register
- Use stronger assertion condition

### CODE REVIEW

**Comment by hqueue** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by BruceForstall** [comment]
cc @dotnet/arm32-contrib

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -7952,6 +7952,17 @@ void LinearScan::resolveLocalRef(BasicBlock* block, GenTreePtr treeNode, RefPosi
...
+            // Update overlapping floating point register for TYP_DOUBLE
+            if (interval->registerType == TYP_DOUBLE)
+            {
+                assert(genIsValidDoubleReg(interval->assignedReg->regNum));
+
+                RegRecord* nextPhysRegRecord = findAnotherHalfRegRec(interval->assignedReg);
+
+                nextPhysRegRecord->assignedInterval = nullptr;
+            }
+#endif
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: It might be nice to extract this, perhaps into a method called `ResetAssignedReg(RegRecord, RegisterType)`. With a bit of refactoring it could also be used in `unassignPhysReg()`

Comment (hqueue) [inline src/jit/lsra.cpp]: @CarolEidt You are right and I'm planning to do some refactoring for `lsra.cpp`.

For example, we can reuse part of `checkAndClearInterval` and `checkAndAssignInterval` when updating `assignedInterva`l in `RegRecord`. If you don't mind I will make another PR for refactoring after many bugs in register allocation for ryujit/arm32 are fixed.

**Comment by hqueue** [comment]
@CarolEidt PTAL. I've update the PR with refactoring `resolveLocalRef()` using a new helper function.

I'm going to apply similar refactoring to whole `lsra.cpp` by extending a helper function in the next PR.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -7874,6 +7874,40 @@ void LinearScan::allocateRegisters()
 #endif // DEBUG
 }
 
+#ifdef _TARGET_ARM_
+//-----------------------------------------------------------------------------
+// updateAssignedInterval: Update assigned interval of register for ARM32
+// considering reigster type. When reigster type is TYP_DOUBLE, update
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Typo: "reigster" -> "register" also a couple of places below.

Comment (hqueue) [inline src/jit/lsra.cpp]: Thanks! I found same typo across lsra.cpp.

**Comment by BruceForstall** [comment]
@hqueue Can you fix the formatting?

**Comment by hqueue** [comment]
@dotnet-bot please test Ubuntu x64 Formatting

**Comment by hqueue** [comment]
> @hqueue Can you fix the formatting?

@BruceForstall It's weird, because the formatting error is from master branch. There is no code related to formatting error in this PR. I will rebase this PR to fix the formatting.
