### PR TITLE
JIT: fix bug with int casts of long shifts

### LINKED ISSUE #15077: JIT: codegen bug when propagating cast through long shift
In the following:
```C#
using System;
using System.Runtime.CompilerServices;

class P
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Q()
    {
        return 0x20;
    }
    
    public static UInt32 G()
    {
        int q = Q();
        return (UInt32)(((((UInt64)1) << q) - 1) << (32 - q));
    }
    
    public static int Main()
    {
        UInt32 r = G();
        Console.WriteLine("r is {0:X}", r);
        return r == UInt32.MaxValue ? 100 : 0;
    }
}
```
When jitting `G`, during morph, the jit will propagate the long->int cast down through the left shift incorrectly. Cast propagation of this kind through shifts needs to be careful when the shift amount is 32 bits or more.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit is pushing int casts down through long left shifts in ways that can
change computation. The push is only safe if the shift amount is 31 bits or
less. So split the current optimization for shifts into three cases:
* shift amount unknown: don't push the cast
* shift amount > 31: result of cast/shift is zero
* shift amout <= 31: push the cast

Fixes #15077.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@erozenfeld PTAL
cc @dotnet/jit-contrib 

No diffs in jit-diffs.

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -465,9 +465,50 @@ GenTreePtr Compiler::fgMorphCast(GenTreePtr tree)
...
             // For these operations the lower 32 bits of the result only depends
-            // upon the lower 32 bits of the operands
+            // upon the lower 32 bits of the operands.
             //
-            if (oper->OperIs(GT_ADD, GT_SUB, GT_MUL, GT_AND, GT_OR, GT_XOR, GT_NOT, GT_NEG, GT_LSH))
+            bool canPushCast = oper->OperIs(GT_ADD, GT_SUB, GT_MUL, GT_AND, GT_OR, GT_XOR, GT_NOT, GT_NEG);
+
+            // For long LSH cast to int, there is a discontinuity in behavior
+            // when the shift amount 32 or larger.
+            //
```
Comment (erozenfeld) [inline src/jit/morph.cpp]: amount --> amount is

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -465,9 +465,50 @@ GenTreePtr Compiler::fgMorphCast(GenTreePtr tree)
...
+            // LSH(CAST(INT, 1LL), CAST(INT, 31)) == LSH(1, 31)
+            //
+            // CAST(INT, LSH(1LL, 32)) == 0
+            // LSH(CAST(INT, 1LL), CAST(INT, 32)) == LSH(1, 32) == LSH(1, 0) == 1
+            //
+            // So some extra validation is needed.
+            //
+            if (oper->OperIs(GT_LSH))
+            {
+                GenTree* shiftAmount = oper->gtOp.gtOp2;
```
Comment (erozenfeld) [inline src/jit/morph.cpp]: Should we call gtFoldExprConst on shiftAmount to catch more cases? I see that's called in the GT_AND case above.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: We can call `gtFoldExpr`. We don't yet know if the expression will fold to a constant. Added.

Comment (erozenfeld) [reply src/jit/morph.cpp]: LGTM

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -465,9 +465,55 @@ GenTreePtr Compiler::fgMorphCast(GenTreePtr tree)
...
+
+                // Expose constant value for shift, if possible, to maximize the number
+                // of cases we can handle.
+                shiftAmount = oper->gtOp.gtOp2 = gtFoldExpr(shiftAmount);
```
Comment (briansull) [inline src/jit/morph.cpp]: Only one assignment should occur per stmt.

```
shiftAmount = gtFoldExpr(shiftAmount);
oper->gtOp.gtOp2 = shiftAmount;
```

File: src/jit/morph.cpp [hunk 4]
```diff
@@ -465,9 +465,55 @@ GenTreePtr Compiler::fgMorphCast(GenTreePtr tree)
...
+                {
+                    const ssize_t shiftAmountValue = shiftAmount->AsIntCon()->IconValue();
+                    assert(shiftAmountValue >= 0);
+
+                    if (shiftAmountValue >= 32)
+                    {
+                        // Result of the shift is zero.
+                        DEBUG_DESTROY_NODE(tree);
+                        GenTree* zero = gtNewZeroConNode(TYP_INT);
+                        return fgMorphTree(zero);
```
Comment (briansull) [inline src/jit/morph.cpp]: Does your new test case cover this case?
If so you may want to mention it in a comment in the test case.
Otherwise please add a test case.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: It is covered.

File: src/jit/morph.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Copied this pattern from a few lines above. Will fix.

**Comment by AndyAyersMS** [comment]
CentOS failure is a known issue (#15096) so ignoring.
