### PR TITLE
Bug fix: fgOptimizeBranch loses bbFlags while duplicating the conditional block

### LINKED ISSUE #6886: RyuJIT: fgOptimizeBranch loses bbFlags while duplicating the conditional block
When `fgOptimizeBranch` procedure duplicates the conditional basic block it does not copy flags of the `bDest` block to the `bJump` block. For example, if a flag `BBF_HAS_NEWOBJ` was set in `bDest`, but not in `bJump` when the branch optimization is done the flags of `bJump` will not reflect the fact that we have construction of new object in this block. We need to decide which flags we are going to copy over to the `bJump` block. The current workaround is copying the following flags: `BBF_HAS_NEWOBJ` , `BBF_HAS_NEWARRAY`, `BBF_HAS_NULLCHECK`.

### PR DESCRIPTION
**Pull request by echesakov**
1. When `fgOptimizeBranch` procedure duplicates the conditional basic block it does
not copy flags of the `bDest` block to the `bJump` block. For example, if a flag
`BBF_HAS_NEWOBJ` was set in `bDest`, but not in `bJump` when the branch optimization
is done the `bbFlags` of `bJump` will not reflect the fact that we have new object
construction in this block.

2. In `DEBUG` in `ObjectAllocator` phase always check if `bbFlags` has `BBF_HAS_NEWOBJ` flag set if at least one `GT_ALLOCOBJ` canonical node found. This helps to identify situations when compiler loses `BBF_HAS_NEWOBJ` flag.

Fixes #6886 

SuperPMI asm diffs show code size improvements in 4 methods: a few comparisons were eliminated because EarlyProp was able to propagate more array lengths.

@dotnet-bot 
cc @erozenfeld  @briansull @dotnet/jit-contrib PTAL

### CODE REVIEW

**Comment by erozenfeld** [comment]
LGTM

File: src/jit/objectalloc.cpp [hunk 1]
```diff
@@ -66,10 +66,13 @@ void ObjectAllocator::MorphAllocObjNodes()
 
     foreach_block(comp, block)
     {
-        if ((block->bbFlags & BBF_HAS_NEWOBJ) == 0)
+        bool basicBlockHasNewObj = (block->bbFlags & BBF_HAS_NEWOBJ) == BBF_HAS_NEWOBJ;
```
Comment (pgavlin) [inline src/jit/objectalloc.cpp]: Nit: `const bool`

**Comment by pgavlin** [comment]
LGTM aside from one nit.

**Comment by echesakov** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by echesakov** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build

**Comment by pgavlin** [comment]
@echesakov: don't worry if the ARM Emulator builds are failing; this is a known issue.
