### PR TITLE
Fix #3561: assert on RyuJIT x86 when generating shl by 1

### LINKED ISSUE #3561: RyuJIT x86: Assert when generating shl by 1
The following tests get this assert:
Assert failure(PID 15836 [0x00003ddc], Thread: 14924 [0x3a4c]): Assertion failed 'val != 1'
File: d:\git\coreclr\src\jit\emitxarch.cpp Line: 4187

JIT\Directed\coverage\oldtests\cse1_cs_r\cse1_cs_r.cmd
in 'CSE1:Main(ref):int' (IL size 523)
JIT\Directed\coverage\oldtests\cse1_cs_ro\cse1_cs_ro.cmd
in 'CSE1:Main(ref):int' (IL size 401)
JIT\Performance\CodeQuality\V8\Richards\Richards\Richards.cmd
in 'Richards.IdleTask:run(ref):ref:this' (IL size 125)
JIT\Directed\coverage\oldtests\cse1_cs_do\cse1_cs_do.cmd
in 'CSE1:Main(ref):int' (IL size 401)
JIT\Directed\coverage\oldtests\cse1_cs_d\cse1_cs_d.cmd
in 'CSE1:Main(ref):int' (IL size 523)

It may be that this assert is related to the following code in codegenlegacy.cpp for a left shift:
                /* "add reg, reg" is smaller and faster than "shl reg, 1" */
                inst_RV_RV(INS_add, reg, reg, treeType, size, flags);

### PR DESCRIPTION
**Pull request by BruceForstall**
This assert hit in the encoder when we were trying to generate an
INS_shl_N with a constant of 1, instead of using the special xarch
INS_shl_1 encoding, which saves a byte. It turns out, the assert was
and in fact amd64 does generate the suboptimal encoding currently.

The bad code occurs in the RMW case of genCodeForShift(). It turns out
that function is unnecessarily complex, unique (it doesn't use the
common RMW code paths), and has a number of other latent bugs.

To fix this, I split genCodeForShift() by leaving the non-RMW case
there, and adding a genCodeForShiftRMW() function just for the RMW case.
I rewrote the RMW case to use the existing emitInsRMW functions.

Other related cleanups along the way:
1. I changed emitHandleMemOp to consistently set the idInsFmt field,
and changed all callers to stop pre-setting or post-setting this field.
This makes the API much easier to understand. I added a big header
comment for the function. Now, it takes a "basic" insFmt (using ARD,
AWR, or ARW forms), which might be munged to a MRD/MWR/MRW form
if necessary.
2. I changed some places to always use the most derived GenTree type
for all uses. For instance, if the code has
"GenTreeIndir* mem = node->AsIndir()", then always use "mem" from then
on, and don't use "node". I changed some functions to take more derived
GenTree node types.
3. I rewrote the emitInsRMW() functions to be much simpler, and rewrote
their header comments.
4. I added GenTree predicates OperIsShift(), OperIsRotate(), and
OperIsShiftOrRotate().
5. I added function genMapShiftInsToShiftByConstantIns() to encapsulate
mapping from INS_shl to INS_shl_N or INS_shl_1 based on a constant.
This code was in 3 different places already.
6. The change in assertionprop.cpp is simply to make JitDumps readable.

Fixes #3561.

In addition to fixing the bug for RyuJIT/x86, there are a small number
of x64 diffs where we now generate smaller encodings for shift by 1.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@adiaaida @sivarv PTAL
/cc @dotnet/jit-contrib

File: src/jit/codegencommon.cpp [hunk 1]
```diff
@@ -11419,6 +11419,66 @@ unsigned Compiler::GetHfaSlots(CORINFO_CLASS_HANDLE hClass)
 
 #endif // _TARGET_ARM_
 
+
+#ifdef _TARGET_XARCH_
+
+//------------------------------------------------------------------------
+// genMapShiftInsToShiftByConstantIns: Given a general shift/rotate instruction,
+// map it to the specific x86/x64 shift opcode for a ahift/rotate by a constant.
```
Comment (pgavlin) [inline src/jit/codegencommon.cpp]: s/ahift/shift

File: src/jit/codegenxarch.cpp [hunk 2]
```diff
@@ -4247,241 +4247,133 @@ instruction CodeGen::genGetInsForOper(genTreeOps oper, var_types type)
...
+//    parent:   the actual bitshift node (that specifies the
+//              type of bitshift to perform).
+//
+// Assumptions:
+//    a) All GenTrees are register allocated.
+//    b) Either shiftBy is a contained constant or it's an expression sitting in RCX.
+//
+void CodeGen::genCodeForShift(GenTreePtr operand,
+                              GenTreePtr shiftBy,
                               GenTreePtr parent)
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: Does this routine need 3 params or just 'parent' param?
if parent is shift oper node. Its op1 is operand and op2 is shiftBy.

Since you are editing this, please change this  as well.

Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: I wanted to do that, but hesitated because that means touching all platforms (which share this declaration). But, since you mention it, I'll do it.

File: src/jit/codegenxarch.cpp [hunk 3]
```diff
@@ -4247,241 +4247,133 @@ instruction CodeGen::genGetInsForOper(genTreeOps oper, var_types type)
...
+// genCodeForShiftRMW: Generates the code sequence for a GT_STOREIND GenTree node that
+// represents a RMW bit shift or rotate operation (<<, >>, >>>, rol, ror), for example:
+//      GT_STOREIND( AddressTree, GT_SHL( Ind ( AddressTree ), Operand ) )
+//
+// Arguments:
+//    storeIndNode: the GT_STOREIND node.
+//
+void CodeGen::genCodeForShiftRMW(GenTreePtr storeIndNode)
+{
+    GenTreeStoreInd* storeInd = storeIndNode->AsStoreInd();
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: Since the caller of this routine is has a GenTreeStoreInd*, we can make type of param of this routine to be GenTreeStoreInd* and avoid the need to cast it using AsStoreInd()

File: src/jit/codegenxarch.cpp [hunk 4]
```diff
@@ -4247,241 +4247,133 @@ instruction CodeGen::genGetInsForOper(genTreeOps oper, var_types type)
...
-        else
-        {
-            if (parent->gtRegNum != operandReg)
-            {
-                inst_RV_RV(INS_mov, parent->gtRegNum, operandReg, targetType);
-            }
-            inst_RV_CL(ins, parent->gtRegNum, targetType);
-        }
+        // The shiftBy operand is implicit, so call the unary version of emitInsRMW.
+        getEmitter()->emitInsRMW(ins, attr, storeInd);
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: This looks soo much cleaner.  Thanks for making this change.

File: src/jit/emitxarch.cpp [hunk 5]
```diff
@@ -3063,88 +3081,68 @@ regNumber emitter::emitInsBinary(instruction ins, emitAttr attr, GenTree* dst, G
...
+//          StoreInd( AddressTree, BinOp( Ind ( AddressTree ), Operand ) )
+//    The address to store is already sitting in a register.
+//
+// Notes:
+//    This is a no-produce operation, meaning that no register output will
+//    be produced for future use in the code stream.
+//
+//    The caller is responsible for calling genConsumeReg() on all source registers, and
+//    genProduceReg on the target register, if any.
+//
```
Comment (CarolEidt) [inline src/jit/emitxarch.cpp]: These two notes are somewhat confusing to me. The first makes sense, given that this deals with a memory operand. Then the latter implies that it might actually produce a register. Is it the case that there are some RMW ops that also write to a register or that update the base register or something? (I could look it up, but ...) If so, perhaps this could be made clearer - or just omit the  second half of the second note.

File: src/jit/emitxarch.cpp [hunk 6]
```diff
@@ -3063,88 +3081,68 @@ regNumber emitter::emitInsBinary(instruction ins, emitAttr attr, GenTree* dst, G
...
-    GenTreeIndir* indir = dstAddr->AsIndir();
-    GenTreePtr mem = indir->Addr();
-    assert(mem->gtSkipReloadOrCopy()->OperGet() == GT_LCL_VAR ||
-           mem->gtSkipReloadOrCopy()->OperGet() == GT_LCL_VAR_ADDR ||
-           mem->gtSkipReloadOrCopy()->OperGet() == GT_LEA ||
-           mem->gtSkipReloadOrCopy()->OperGet() == GT_CLS_VAR_ADDR ||
-           mem->gtSkipReloadOrCopy()->OperGet() == GT_CNS_INT);
+    GenTreePtr mem = storeInd->Addr();
+    mem = mem->gtSkipReloadOrCopy();
+    assert(mem->OperGet() == GT_LCL_VAR ||
```
Comment (CarolEidt) [inline src/jit/emitxarch.cpp]: Not a big deal - but "mem" is weird to me because it is somewhat ambiguous whether you are referring to the actual memory contents (which is usually represented by a GT_IND), or the address of the memory. So "addr" seems better to me, but since it was already "mem" it is fine to leave as-is.

File: src/jit/emitxarch.cpp [hunk 7]
```diff
@@ -3155,51 +3153,50 @@ void emitter::emitInsRMW(instruction ins, emitAttr attr, GenTree* dstAddr, GenTr
...
+//    Lowering has taken care of recognizing the StoreInd pattern of:
+//          StoreInd( AddressTree, UnaryOp( Ind ( AddressTree ) ) )
+//    The address to store is already sitting in a register.
+//
+// Notes:
+//    This is a no-produce operation, meaning that no register output will
+//    be produced for future use in the code stream.
+//
+//    The caller is responsible for calling genConsumeReg() on all source registers, and
+//    genProduceReg on the target register, if any.
```
Comment (CarolEidt) [inline src/jit/emitxarch.cpp]: Similar question here - are there cases where this is actually a target register?

File: src/jit/codegenxarch.cpp (hunk 4 above)
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: I am assuming that asm diffs are all good and entirely on expected lines.

**Comment by CarolEidt** [comment]
Very nice! LGTM other than a few minor suggestions/questions.

**Comment by sivarv** [comment]
Looks good.

File: src/jit/codegenxarch.cpp (hunk 4 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: Yes. No actual opcode changes on x64, just a few encoding changes for shift-by-1.

File: src/jit/emitxarch.cpp (hunk 5 above)
Comment (BruceForstall) [inline src/jit/emitxarch.cpp]: Those comments were carried over from before. It doesn't look like any caller calls genProduceReg, so I'm going to delete the last sentence.

File: src/jit/codegenxarch.cpp (hunk 3 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: done.

File: src/jit/emitxarch.cpp (hunk 6 above)
Comment (BruceForstall) [inline src/jit/emitxarch.cpp]: good point. changed to 'addr' to be consistent with many other uses. (also noticed I'd called gtSkipReloadOrCopy() twice in one case).

File: src/jit/codegenxarch.cpp [hunk 8]
```diff
@@ -4247,241 +4247,133 @@ instruction CodeGen::genGetInsForOper(genTreeOps oper, var_types type)
...
+//
+// Arguments:
+//    operand:  the value to be shifted or rotated by shiftBy bits.
+//    shiftBy:  the number of bits to shift or rotate the operand.
+//    parent:   the actual bitshift node (that specifies the
+//              type of bitshift to perform).
+//
+// Assumptions:
+//    a) All GenTrees are register allocated.
+//    b) Either shiftBy is a contained constant or it's an expression sitting in RCX.
```
Comment (briansull) [inline src/jit/codegenxarch.cpp]: This should probably be updated to:
b) Either shiftBy is a contained constant or it's sitting in a registers
    If the register isn't RCX then that register is copied into RCX.

File: src/jit/codegenxarch.cpp [hunk 9]
```diff
@@ -4247,241 +4247,131 @@ instruction CodeGen::genGetInsForOper(genTreeOps oper, var_types type)
...
+// genCodeForShift: Generates the code sequence for a GenTree node that
+// represents a bit shift or rotate operation (<<, >>, >>>, rol, ror).
+//
+// Arguments:
+//    tree - the bit shift node (that specifies the type of bit shift to perform).
+//
+// Assumptions:
+//    a) All GenTrees are register allocated.
+//    b) The shift-by-amount in tree->gtOp.gtOp2 is a contained constant or
+//       it's an expression sitting in RCX.
```
Comment (briansull) [inline src/jit/codegenxarch.cpp]: This should probably be updated to:
 b) Either shift-by-amount is a contained constant or it's sitting in a register
 If the register isn't RCX then that register is copied into RCX.

**Comment by briansull** [comment]
Looks Good

File: src/jit/codegenxarch.cpp (hunk 9 above)
Comment (BruceForstall) [inline src/jit/codegenxarch.cpp]: fixed.

**Comment by BruceForstall** [comment]
@dotnet-bot OSX x64 Checked Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test OSX x64 Checked Build and Test
@dotnet-bot test Ubuntu x64 Checked Build and Test
@dotnet-bot test Windows_NT x64 Debug Build and Test
@dotnet-bot test Windows_NT x64 Release Priority 1 Build and Test

**Comment by RussKeldorph** [comment]
From my superficial POV, this feels like a change that should be separated into refactoring and functional pieces.  I'll defer to the experts who have signed off, however.

**Comment by adiaaida** [comment]
LGTM
