### PR TITLE
[x86/Linux] Fix WIN64EXCEPTIONS build error

### LINKED ISSUE #8631: [x86/Linux] Support exception handling
#8613 allows us to run "Hello, World" example in x86/Linux, but currently x86/Linux port is unable to handle any exceptions.

### PR DESCRIPTION
**Pull request by parjong**
This is the first step to resolve #8631.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark

**Comment by jkotas** [comment]
I think it would be useful to batch all commits for the WIN64EXCEPTIONS into a single PR. It is hard to tell whether the small incremental changes like this one are good.

**Comment by parjong** [comment]
@jkotas I'll use this PR to elaborate all the related commits.

File: src/inc/clrnt.h [hunk 1]
```diff
@@ -837,6 +837,13 @@ RtlVirtualUnwind_Unsafe(
 
 #ifdef _TARGET_X86_
 #ifndef FEATURE_PAL
+//
+// x86 ABI does not define RUNTIME_FUNCTION. Define our own to allow unification between x86 and other platforms.
```
Comment (janvorli) [inline src/inc/clrnt.h]: @parjong I am not sure I understand how could the Windows build get broken. Things that you change for the WIN64EXCEPTIONS should be done in a way that doesn't influence windows x86 stuff.

Comment (parjong) [inline src/inc/clrnt.h]: Sure, I tried not to affect windows x86 stuff via submitting small commits frequently (I have no mean to check Windows build issue).

File: src/inc/regdisp.h [hunk 2]
```diff
@@ -11,7 +11,7 @@ class Thread;
 #endif // DEBUG_REGDISPLAY
 
 
-#if defined(_TARGET_X86_)
+#if defined(_TARGET_X86_) && !defined(WIN64EXCEPTIONS)
```
Comment (janvorli) [inline src/inc/regdisp.h]: Why is the REGDISPLAY commented out for WIN64EXCEPTIONS? It is a structure that is generally needed.

Comment (parjong) [inline src/inc/regdisp.h]: By mistake, I thought that ``GetRegdisplayReturnValue`` is available only for ``WIN64EXCEPTIONS``.

File: src/inc/clrnt.h (hunk 1 above)
Comment (parjong) [inline src/inc/clrnt.h]: It turns out that windows build uses PORTABILITY_ASSERT that raises compile error (instead of runtime error).

File: src/inc/regdisp.h (hunk 2 above)
Comment (parjong) [inline src/inc/regdisp.h]: I agree that code cleanup need to be done separately. I created #8643 as a staring point of this cleanup issue.

File: src/inc/regdisp.h [hunk 3]
```diff
@@ -35,6 +35,24 @@ struct REGDISPLAY {
     PCODE   ControlPC;
     TADDR   PCTAddr;
 
+#ifdef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/inc/regdisp.h]: You can also ifdef out the pContextForUnwind, it is not used with WIN64EXCEPTIONS. So maybe you can move this block next to the pContextForUnwind so that you can have single #ifdef / #else / #endif there.

Comment (parjong) [inline src/inc/regdisp.h]: It sounds good! I revised PR as you suggested.

**Comment by parjong** [comment]
@janvorli @jkotas This PR now allows us to build x86/Linux port (although it has some undefined references). Please take a look.

File: src/inc/regdisp.h [hunk 4]
```diff
@@ -370,7 +389,9 @@ inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pC
 
 #ifdef _TARGET_X86_
     pRD->pContext = pctx;
+#ifndef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/inc/regdisp.h]: This needs to be different. We need to use the common code that's below for _WIN64 for WIN64EXCEPTIONS on Linux x86 too. So please keep this part of the code that is for _TARGET_X86_ untouched, just change the condition from _TARGET_x86_  to #ifndef WIN64EXCEPTIONS and the #elif defined(_WIN64) below to #else. Then in the #ifdef _TARGET_AMD64_ etc add branch for _TARGET_X86_ and put the registers copying in there in a way similar to what we do for the other targets.
There is also an #ifdef for _TARGET_ARM below, which would need to be merged with the _WIN64 part. They are almost the same, so it would be good anyways. Just be careful, the ARM path has two additional tiny details,  explicit copying of Lr and Pc.

File: src/vm/excep.cpp [hunk 5]
```diff
@@ -7556,7 +7556,7 @@ void InitSavedExceptionInfo()
 void FaultingExceptionFrame::Init(CONTEXT *pContext)
 {
     WRAPPER_NO_CONTRACT;
-#if defined(_TARGET_X86_)
+#if defined(_TARGET_X86_) && !defined(WIN64EXCEPTIONS)
```
Comment (janvorli) [inline src/vm/excep.cpp]: It seems that in many places where you use this `#if` condition, it would make sense to use `#ifndef (WIN64EXCEPTIONS)` with `#ifdef _TARGET_X86_ ... #else PORTABILITY_ASSERT #endif` in it.

File: src/vm/i386/excepcpu.h [hunk 6]
```diff
@@ -90,15 +91,24 @@ extern VOID ResetSEHRecord(PEXCEPTION_REGISTRATION_RECORD record);
 
 #endif
 
+
+PEXCEPTION_REGISTRATION_RECORD GetCurrentSEHRecord();
```
Comment (janvorli) [inline src/vm/i386/excepcpu.h]: GetCurrentSEHRecord etc. is a part of the change that was made to compile with the WIN32EXCEPTIONS and that should be reverted now (it was made in https://github.com/dotnet/coreclr/pull/8613)

File: src/vm/i386/unixstubs.cpp [hunk 7]
```diff
@@ -6,7 +6,7 @@
 
 extern "C"
 {
-    void ThrowControlForThread()
+    void ThrowControlForThread(ONWIN64EXCEPTIONS(FaultingExceptionFrame *pfef))
```
Comment (janvorli) [inline src/vm/i386/unixstubs.cpp]: The ONWIN64EXCEPTIONS is not needed here, as we now have the WIN64EXCEPTIONS always on for Linux x86.

File: src/vm/stackwalk.cpp [hunk 8]
```diff
@@ -1035,7 +1033,7 @@ StackWalkAction Thread::StackWalkFrames(PSTACKWALKFRAMESCALLBACK pCallback,
         FillRegDisplay(&rd, &ctx);
     }
 
-#ifdef STACKWALKER_MAY_POP_FRAMES
+#if defined(STACKWALKER_MAY_POP_FRAMES)
```
Comment (janvorli) [inline src/vm/stackwalk.cpp]: A nit, can you remove this cosmetic change, please?

File: src/vm/threads.h [hunk 9]
```diff
@@ -697,13 +697,15 @@ EXTERN_C void __stdcall OnHijackFPTripThread();  // hijacked JIT code is returni
 
 void CommonTripThread();
 
+#ifdef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/vm/threads.h]: Since this is used at one place only, I don't think it is worth introducing the macro.

File: src/vm/stackwalk.cpp [hunk 10]
```diff
@@ -725,7 +723,7 @@ PCODE Thread::VirtualUnwindNonLeafCallFrame(T_CONTEXT* pContext, KNONVOLATILE_CO
 #if defined(_WIN64)
     UINT64              EstablisherFrame;
```
Comment (parjong) [inline src/vm/stackwalk.cpp]: @janvorli Is ``_WIN64`` is for general 64-bit architecture? Then, it would be better to use _BIT64 instead of _WIN64 (and _BIT32 for the below as well).

File: src/vm/i386/excepcpu.h (hunk 6 above)
Comment (parjong) [inline src/vm/i386/excepcpu.h]: ``GetCurrentSEHRecord`` and ``GetFirstCOMPlusSEHRecord``is not a part of #8613 (It was there from the beginning).
#8613 introduces only ``SetSEHRecord`` and ``ResetSEHRecord``.

File: src/vm/i386/unixstubs.cpp (hunk 7 above)
Comment (parjong) [inline src/vm/i386/unixstubs.cpp]: It would be better to revise this once we could run "Hello, World" with WIN64EXCEPTIONS.

**Comment by parjong** [comment]
@dotnet-bot test this please

**Comment by parjong** [comment]
@janvorli I revised PR per feedback, but CI checks are suddenly disappeared..

**Comment by parjong** [comment]
@dotnet-bot help

**Comment by parjong** [comment]
@dotnet-bot test this please

**Comment by parjong** [comment]
@dotnet-bot test ci please

**Comment by parjong** [comment]
@janvorli Windows non-X64 ports checks failed with ``NEED_TO_PORT_THIS_ONE': undeclared identifier`` error which comes from the 409 in ``regdisp.h`` (included from disasmARM.cpp):
```
388 inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pCallerCtx = NULL)
389 {
390     WRAPPER_NO_CONTRACT;
391
392     SUPPORTS_DAC;
393
394 #ifndef WIN64EXCEPTIONS
395 #ifdef _TARGET_X86_
396     pRD->pContext = pctx;
397     pRD->pContextForUnwind = NULL;
398     pRD->pEdi = &(pctx->Edi);
399     pRD->pEsi = &(pctx->Esi);
400     pRD->pEbx = &(pctx->Ebx);
401     pRD->pEbp = &(pctx->Ebp);
402     pRD->pEax = &(pctx->Eax);
403     pRD->pEcx = &(pctx->Ecx);
404     pRD->pEdx = &(pctx->Edx);
405     pRD->Esp  = pctx->Esp;
406     pRD->ControlPC = (PCODE)(pctx->Eip);
407     pRD->PCTAddr = (UINT_PTR)&(pctx->Eip);
408 #else // _TARGET_X86_
409     PORTABILITY_ASSERT("FillRegDisplay");
410 #endif // _TARGET_???_ (ELSE)
411
412 #else // !WIN64EXCEPTIONS
413     pRD->pContext   = pctx;
```
I couldn't understand what happen. 
 - Is Windows arm port uses ``WIN32EXCEPTIONS``?
 - Why Windows arm port touches 409 line?

Could you let me know some details??

**Comment by parjong** [comment]
@janvorli Please take a look.

File: src/inc/regdisp.h [hunk 11]
```diff
@@ -359,6 +343,45 @@ inline LPVOID GetRegdisplayStackMark(REGDISPLAY *display) {
...
+    PORTABILITY_ASSERT("GetRegdisplayReturnValue NYI for this platform (Regdisp.h)");
+    return NULL;
+#endif
+}
+
+inline void SyncRegDisplayToCurrentContext(REGDISPLAY* pRD)
+{
+    LIMITED_METHOD_CONTRACT;
+
+#if defined(_WIN64)
```
Comment (janvorli) [inline src/inc/regdisp.h]: I would recommend changing the name of the stack pointer in the regdisplay for x86 from Esp to SP and then adding `|| defined(_TARGET_X86_)` to the `defined(_ARM_)` below.

It is kind of unfortunate that the REGDISPLAY for x86 and arm use DWORD as a type for the SP and ControlPC while x64 and arm64 use size_t. If that was not that way, the code here could be unified. But I guess that trying to make such change would have a ripple effect, so I would make it as a cleanup later.

File: src/inc/regdisp.h [hunk 12]
```diff
@@ -381,57 +405,35 @@ inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pC
...
     for (int i = 0; i < 8; i++)
     {
         *(&pRD->ctxPtrsOne.R4 + i) = (&pctx->R4 + i);
     }
+#else  // _TARGET_ARM_
+    PORTABILITY_ASSERT("FillRegDisplay");
+#endif // ELSE
 
+#ifdef _TARGET_ARM_
     pRD->ctxPtrsOne.Lr = &pctx->Lr;
```
Comment (janvorli) [inline src/inc/regdisp.h]: It seems this could be next to the loop that copies the registers instead of a separate #ifdef.

File: src/vm/excep.cpp [hunk 13]
```diff
@@ -7556,20 +7551,22 @@ void InitSavedExceptionInfo()
...
     CalleeSavedRegisters *pRegs = GetCalleeSavedRegisters();
     pRegs->ebp = pContext->Ebp;
     pRegs->ebx = pContext->Ebx;
     pRegs->esi = pContext->Esi;
     pRegs->edi = pContext->Edi;
     m_ReturnAddress = ::GetIP(pContext);
     m_Esp = (DWORD)GetSP(pContext);
-#elif defined(WIN64EXCEPTIONS)
+#else // _TARGET_X86_
+    PORTABILITY_ASSERT("FaultingExceptionFrame::InitAndLink");
```
Comment (janvorli) [inline src/vm/excep.cpp]: The assert message is stale, could you please fix it since you are touching this code?

File: src/vm/frames.h [hunk 14]
```diff
@@ -1114,17 +1114,19 @@ class FaultingExceptionFrame : public Frame
 {
     friend class CheckAsmOffsets;
 
-#if defined(_TARGET_X86_)
+#ifndef WIN64EXCEPTIONS
+    #ifdef _TARGET_X86_
```
Comment (janvorli) [inline src/vm/frames.h]: Please keep the #ifdef etc aligned at the first column.

File: src/vm/i386/excepcpu.h (hunk 6 above)
Comment (janvorli) [inline src/vm/i386/excepcpu.h]: Ah, right

File: src/vm/stackwalk.cpp (hunk 10 above)
Comment (janvorli) [inline src/vm/stackwalk.cpp]: Yes, the _WIN64  is equivalent to BIT64. It would be nice to clean that up in the codebase at some point. There are about 600 usages in 180 files of the _WIN64.
But for now, it would not hurt if you could change it to BIT64 in place you are changing (please note it is BIT64, not _BIT64).

**Comment by janvorli** [comment]
I assume the next step is to implement the various REGDISPLAY accessing stuff for x86, right?

File: src/inc/regdisp.h (hunk 11 above)
Comment (parjong) [inline src/inc/regdisp.h]: @janvorli I tried to rename Esp as Sp, but it will introduce non-local changes in this PR. It would be better to make another PR to clean up the code.

**Comment by parjong** [comment]
@janvorli We need to resolve undefined reference issues first. (This PR resolves compile errors, but does not resolve undefined reference issues, yet).

File: clrdefinitions.cmake [hunk 15]
```diff
@@ -15,6 +15,7 @@ if (CLR_CMAKE_TARGET_ARCH_AMD64)
   if (CLR_CMAKE_PLATFORM_UNIX)
     add_definitions(-DDBG_TARGET_AMD64_UNIX)
   endif()
+  add_definitions(-DBIT64=1)
   add_definitions(-D_TARGET_AMD64_=1)
```
Comment (parjong) [inline clrdefinitions.cmake]: Currently, ``BIT32`` and ``BIT64`` are defined only in PAL. I revised ``clrdefinitions.cmake`` to defined ``BIT32`` / ``BIT64`` appropriately, and use the to revise ``stackwalk.cpp``

Comment (janvorli) [inline clrdefinitions.cmake]: The BIT64 was already defined in the root CMakeLists.txt - see:
https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L447

File: src/inc/regdisp.h (hunk 11 above)
Comment (janvorli) [inline src/inc/regdisp.h]: Ok, sounds good.

File: clrdefinitions.cmake (hunk 15 above)
Comment (parjong) [inline clrdefinitions.cmake]: Oh, could I add BIT32 there? I tried the following structure, but it doesn't work:
```
#if defined(BIT32)
  ...
#elif defined(BIT64)
  ...
#else
  ASSERT(...)
#endif
```
I thought that both BIT32 and BIT64 are missing, but only BIT32 is missing as you pointed out.

Comment (janvorli) [inline clrdefinitions.cmake]: Sure, it makes sense to add the BIT32 too. First I was thinking that BIT32 is a negation of BIT64, but who knows, maybe in the future there will be a 128 bit processor.

**Comment by jkotas** [comment]
Do we really need BIT32 ? It is defined in PAL right now, but it is not used anywhere.

File: clrdefinitions.cmake (hunk 15 above)
Comment (jkotas) [inline clrdefinitions.cmake]: 128 bit processors are not going mainstream anytime soon. And in the unlikely case they will ever become mainstream, the 32-bit ones are likely to be obsolete by then.

**Comment by parjong** [comment]
@jkotas ``stackwalk.cpp`` contains has the following code fragment:
```
#ifdef _WIN64
   (Code for 64-bit arch)
#elif defined(_TARGET_ARM_)
   (Code for 32-bit arch)
#endif
```
We need to enable (code for 32-bit arch) for x86/Linux port, and I tried to use BIT32 instead of adding ``|| defined(_TARGET_X86_)``

Anyway, both approach will resolve this issue, but I just prefer ``BIT32``-approach as it is more easy to understand for me.

**Comment by jkotas** [comment]
> We need to enable (code for 32-bit arch) for x86/Linux port

So just make if `#else` ?

**Comment by parjong** [comment]
@jkotas It is also fine. I just thought that it is a bit strange that !BIT64 == BIT32.

**Comment by parjong** [comment]
@jkotas Please let me know which approach would be better. I'll revised PR in that way.

**Comment by parjong** [comment]
@jkotas @janvorli I revised PR per feedback. Please take a look.

File: src/pal/inc/pal.h [hunk 16]
```diff
@@ -6529,8 +6529,8 @@ struct PAL_SEHException
 
 typedef BOOL (PALAPI *PHARDWARE_EXCEPTION_HANDLER)(PAL_SEHException* ex);
 typedef BOOL (PALAPI *PHARDWARE_EXCEPTION_SAFETY_CHECK_FUNCTION)(PCONTEXT contextRecord, PEXCEPTION_RECORD exceptionRecord);
-typedef VOID (PALAPI *PTERMINATION_REQUEST_HANDLER)();
-typedef DWORD (PALAPI *PGET_GCMARKER_EXCEPTION_CODE)(LPVOID ip);
+typedef VOID (*PTERMINATION_REQUEST_HANDLER)();
```
Comment (janvorli) [inline src/pal/inc/pal.h]: For the sake of consistency, could you please keep the PALAPI on these two function pointers and add it to the actual functions instead?

File: src/vm/i386/excepx86.cpp [hunk 17]
```diff
@@ -3769,10 +3783,27 @@ AdjustContextForVirtualStub(
     return TRUE;
 }
 
+#ifndef DACCESS_COMPILE
+#ifndef WIN64EXCEPTIONS
 #ifdef FEATURE_PAL
+EXTERN_C
+_Unwind_Reason_Code
+UnhandledExceptionHandlerUnix(
```
Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: Is there any reason for moving it out of the unixstubs.cpp and putting it here? I assume it will go away once the switch to WIN64EXCEPTIONS is complete, right?

File: src/pal/inc/pal.h (hunk 16 above)
Comment (parjong) [inline src/pal/inc/pal.h]: It seems that ``PALAPI`` is unavailable for Windows build, and adding ``PALAPI`` causes build error on all the Windows ports.

File: src/vm/i386/excepx86.cpp (hunk 17 above)
Comment (parjong) [inline src/vm/i386/excepx86.cpp]: Yes, I thought that here is better place if we will remove all the WIN32EXCEPTIONS-related features from x86/Linux port.

File: src/pal/inc/pal.h (hunk 16 above)
Comment (parjong) [inline src/pal/inc/pal.h]: Please check fcbdf54e9d9d77a492cf6fd9fe96879df64d945c for details.

File: src/vm/i386/excepx86.cpp (hunk 17 above)
Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: I am not sure I understand. The function already has implementation in exceptionhadling.cpp, so this would go away completely.

File: src/pal/inc/pal.h (hunk 16 above)
Comment (janvorli) [inline src/pal/inc/pal.h]: Ah, ok, I have not realized the actual functions are compiled for Windows too. Then keep it as it is.

File: src/vm/i386/excepx86.cpp (hunk 17 above)
Comment (parjong) [inline src/vm/i386/excepx86.cpp]: The implementation of ``UnhandledExceptionHandlerUnix`` in ``exceptionhandling.cpp`` is available only when ``WIN64EXCEPTIONS`` is defined, but ``FuncEvalHijack``in ``debug/ee/i386/dbghelpers.S`` uses ``UnhandledExceptionHandlerUnix`` as a personality routine even when ``WIN64EXCEPTIONS`` is not defined (which causes undefined reference issue in the checked-in stuff).

We could eliminate the above stub once we enable ``WIN64EXCEPTIONS``.

Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: I am sorry for not being clear. That is exactly what I meant - once we enable WIN64EXCEPTIONS for x86 Linux, this stub will be eliminated. So that's why I was wondering what is the reason for moving it from one file to another when it will be removed soon anyways.

Comment (parjong) [inline src/vm/i386/excepx86.cpp]: And, we need to embrace ``UnhandledExceptionHandlerUnix`` with ``WIN64EXCEPTIONS`` in order to remove duplicated definition if we decide to leave it in ``unixstubs.cpp``.

Comment (parjong) [inline src/vm/i386/excepx86.cpp]: Ah, I got it. I just want to locate both ``UnhandledExceptionHandlerUnix`` and ``DispatchManagedException`` in the same place as both functions are implemented in ``exceptionhanding.cpp``, and will be removed once ``WIN64EXCEPTIONS`` is enabled.

Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: Ok, makes sense, thanks for the explanation.

File: src/inc/jithelpers.h [hunk 18]
```diff
@@ -135,7 +135,7 @@
     JITHELPER(CORINFO_HELP_FIELD_ACCESS_EXCEPTION,JIT_ThrowFieldAccessException, CORINFO_HELP_SIG_REG_ONLY)
     JITHELPER(CORINFO_HELP_CLASS_ACCESS_EXCEPTION,JIT_ThrowClassAccessException, CORINFO_HELP_SIG_REG_ONLY)
 
-#ifdef WIN64EXCEPTIONS
+#ifndef _TARGET_X86_
```
Comment (janvorli) [inline src/inc/jithelpers.h]: Why is this change needed?

Comment (parjong) [inline src/inc/jithelpers.h]: @janvorli It is a simple workaround. As JIT is not revised yet, JIT attempts to use JIT_EndCatch even when WIN64EXCEPTIONS is enabled while running simple 'Hello, World' example. This causes assert failure.

Comment (janvorli) [inline src/inc/jithelpers.h]: Ok, thanks for the explanation.

**Comment by parjong** [comment]
@janvorli @jkotas IMHO, it is time to revise JIT to bring up WIN64EXCEPTIONS. It is reasonable to append those changes to this PR?. 

FYI, this PR currently allows me to load simple dummy application (do nothing) and "Hello, World" application even when WIN64EXCEPTIONS are defined.

**Comment by janvorli** [comment]
@parjong that's great! As for the JIT changes, I would prefer making them in a separate PR and merging the current stuff now. Let me look at all of the changes one more time to make sure I have not missed something before we merge.

File: src/inc/clrnt.h [hunk 19]
```diff
@@ -845,6 +852,46 @@ typedef struct _DISPATCHER_CONTEXT {
...
+EXTERN_C ULONG
+RtlpGetFunctionEndAddress (
+    __in PT_RUNTIME_FUNCTION FunctionEntry,
+    __in ULONG ImageBase
+    );
+
+#define RUNTIME_FUNCTION__EndAddress(prf, ImageBase)   RtlpGetFunctionEndAddress(prf, ImageBase)
+
+#define RUNTIME_FUNCTION__GetUnwindInfoAddress(prf)    (prf)->UnwindData
+#define RUNTIME_FUNCTION__SetUnwindInfoAddress(prf, addr) \
```
Comment (janvorli) [inline src/inc/clrnt.h]: A nit - for the sake of consistency, could you please define this macro as one-liner like it is done at other places in this file?

File: src/inc/jithelpers.h (hunk 18 above)
Comment (janvorli) [inline src/inc/jithelpers.h]: Could you please add UNIXTODO here to revert this change once the JIT is revised?

File: src/inc/regdisp.h [hunk 20]
```diff
@@ -359,6 +343,48 @@ inline LPVOID GetRegdisplayStackMark(REGDISPLAY *display) {
...
+{
+    LIMITED_METHOD_CONTRACT;
+
+#if defined(_TARGET_AMD64_)
+    return (LPVOID)display->pCurrentContext->Rax;
+#elif defined(_TARGET_ARM64_)
+    return (LPVOID)display->pCurrentContext->X0;
+#elif defined(_TARGET_ARM_)
+    return (LPVOID)display->pCurrentContext->R0;
+#else
```
Comment (janvorli) [inline src/inc/regdisp.h]: You are missing the _TARGET_X86_ stuff here

File: src/inc/regdisp.h [hunk 21]
```diff
@@ -381,57 +408,38 @@ inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pC
...
+#elif defined(_TARGET_ARM_) // _TARGET_ARM64_
     // Copy over the nonvolatile integer registers (R4-R11)
     for (int i = 0; i < 8; i++)
     {
         *(&pRD->ctxPtrsOne.R4 + i) = (&pctx->R4 + i);
     }
 
-    pRD->ctxPtrsOne.Lr = &pctx->Lr; 
+    pRD->ctxPtrsOne.Lr = &pctx->Lr;
+#elif defined(_TARGET_X86_) // _TARGET_X86_
```
Comment (janvorli) [inline src/inc/regdisp.h]: The comment should be _TARGET_ARM_, if I understand your convention correctly, right?

File: src/vm/codeman.cpp [hunk 22]
```diff
@@ -3020,7 +3020,7 @@ void * EEJitManager::allocCodeFragmentBlock(size_t blockSize, unsigned alignment
     {
         CrstHolder ch(&m_CodeHeapCritSec);
 
-        mem = (TADDR) allocCodeRaw(&requestInfo, sizeof(TADDR), blockSize, alignment, &pCodeHeap);
+        mem = (TADDR) allocCodeRaw(&requestInfo, sizeof(CodeHeader), blockSize, alignment, &pCodeHeap);
```
Comment (janvorli) [inline src/vm/codeman.cpp]: Good catch! @jkotas - It is interesting we have not caught this bug before. It is benign for indirect code headers, but otherwise we underallocate.

File: src/vm/exstatecommon.h [hunk 23]
```diff
@@ -51,10 +51,10 @@ class DebuggerExState
         m_pDebuggerContext = NULL;
         m_pDebuggerInterceptNativeOffset = 0;
 
-        // x86-specific fields
-  #if defined(_TARGET_X86_)      
+  #ifndef WIN64EXCEPTIONS
+        // WIN32EXCEPTIONS-specific fields
```
Comment (janvorli) [inline src/vm/exstatecommon.h]: There is actually nothing like WIN32EXCEPTIONS. The comment should really stay as it was.

File: src/vm/frames.h [hunk 24]
```diff
@@ -1114,17 +1114,19 @@ class FaultingExceptionFrame : public Frame
...
+#ifndef WIN64EXCEPTIONS
+#ifdef _TARGET_X86_
     DWORD                   m_Esp;
     CalleeSavedRegisters    m_regs;
     TADDR                   m_ReturnAddress;
-#endif
-
-#ifdef WIN64EXCEPTIONS
+#else  // _TARGET_X86_
+    #error "WIN32EXCEPTIONS is supported only for X86"
```
Comment (janvorli) [inline src/vm/frames.h]: Again, there is nothing like WIN32EXCEPTIONS. It is only windows x86 exceptions.

File: src/vm/i386/cgenx86.cpp [hunk 25]
```diff
@@ -518,9 +519,12 @@ void FaultingExceptionFrame::UpdateRegDisplay(const PREGDISPLAY pRD)
     pRD->pEsi = (DWORD*) &regs->esi;
     pRD->pEbx = (DWORD*) &regs->ebx;
     pRD->pEbp = (DWORD*) &regs->ebp;
+    pRD->Esp = m_Esp;
     pRD->PCTAddr = GetReturnAddressPtr();
     pRD->ControlPC = *PTR_PCODE(pRD->PCTAddr);
-    pRD->Esp = m_Esp;
+#else
+    PORTABILITY_ASSERT("FaultingExceptionFrame::UpdateRegDisplay");
```
Comment (janvorli) [inline src/vm/i386/cgenx86.cpp]: We should implement it for WIN64EXCEPTIONS before we merge the change.

File: src/vm/i386/excepx86.cpp [hunk 26]
```diff
@@ -38,6 +38,7 @@
 #include "asmconstants.h"
 #include "virtualcallstub.h"
 
+#ifndef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: This whole file should be excluded for WIN64EXCEPTIONS and so you can revert all the changes in it.

File: src/vm/i386/unixstubs.cpp [hunk 27]
```diff
@@ -6,7 +6,11 @@
 
 extern "C"
 {
-    void ThrowControlForThread()
+    void ThrowControlForThread(
+#ifdef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/vm/i386/unixstubs.cpp]: This ifdef can go away with this change that switches to WIN64EXCEPTIONS on x86 Linux.

File: src/vm/jitinterface.h [hunk 28]
```diff
@@ -391,7 +391,9 @@ void ValidateWriteBarrierHelpers();
 
 extern "C"
 {
+#ifdef _TARGET_X86_
```
Comment (janvorli) [inline src/vm/jitinterface.h]: Please add UNIXTODO to revert this change after the jitter is modified

File: src/vm/stackwalk.cpp [hunk 29]
```diff
@@ -722,15 +720,13 @@ PCODE Thread::VirtualUnwindNonLeafCallFrame(T_CONTEXT* pContext, KNONVOLATILE_CO
...
 
     PCODE           uControlPc = GetIP(pContext);
-#if defined(_WIN64)
+#ifdef BIT64
     UINT64              EstablisherFrame;
     PVOID               HandlerData;
-#elif defined(_TARGET_ARM_)
+#else  // BIT64
     DWORD               EstablisherFrame;
     PVOID               HandlerData;
```
Comment (janvorli) [inline src/vm/stackwalk.cpp]: The HandlerData can be moved out of the ifdef.

**Comment by janvorli** [comment]
@jkotas can you please take a look? We are close to merging this change.

File: src/vm/codeman.cpp (hunk 22 above)
Comment (jkotas) [inline src/vm/codeman.cpp]: We only use the last field of CodeHeader on this codepath, so I think the original code was fine. We will allocate extra unused 12 bytes on Windows x86 with this change. It would be worth a comment at least.

File: src/vm/excep.cpp [hunk 30]
```diff
@@ -7314,8 +7318,8 @@ AdjustContextForWriteBarrier(
 {
     WRAPPER_NO_CONTRACT;
 
+#ifndef WIN64EXCEPTIONS
 #ifdef _TARGET_X86_
```
Comment (jkotas) [inline src/vm/excep.cpp]: This ifdef is not really about WIN64EXCEPTIONS. It is about whether OS unwinder is available. Changing it to `#if defined(_TARGET_X86_) && !defined(PLATFORM_UNIX)` maybe more appropriate.

File: src/vm/codeman.cpp (hunk 22 above)
Comment (parjong) [inline src/vm/codeman.cpp]: @jkotas When I enable WIN64EXCEPTIONS, I encountered assert failure during method table generation. While digging that issue, I found that the changes in the last field of CodeHeader overwrites the previous method table.

I'm still wondering why that issue doesn't happen unless WIN64EXCEPTIONS is defined.

File: src/vm/excep.cpp (hunk 30 above)
Comment (parjong) [inline src/vm/excep.cpp]: @jkotas Could you let me know some details? I thought that ``WIN64EXCEPTIONS`` is a exception handling ABI based on C++ try/catch and libunwind, but it seems wrong.

File: src/vm/stackwalk.cpp (hunk 29 above)
Comment (parjong) [inline src/vm/stackwalk.cpp]: Thanks you for comment. I'll revise.

File: src/vm/i386/unixstubs.cpp (hunk 27 above)
Comment (parjong) [inline src/vm/i386/unixstubs.cpp]: Actually, this PR does not include a commit to switch ``WIN64EXCEPTIONS``. (I applied it only internally). 

Is it required to remove #ifdef after adding ``WIN64EXCEPTIONS`` switch commit?

File: src/vm/excep.cpp (hunk 30 above)
Comment (jkotas) [inline src/vm/excep.cpp]: WIN64EXCEPTIONS is based on Windows `RUNTIME_FUNCTION` descriptors and funclets. It does not have any coupling with libunwind; or with how C++ try/catch works on given platform. The way C++ try/catch works on Unix is actually different from how WIN64EXCEPTIONS work - Linux C++ try/catch is based on landing pads, not funclets.

File: src/inc/regdisp.h (hunk 21 above)
Comment (parjong) [inline src/inc/regdisp.h]: Oops. Yes, you are right. I'll fix it.

File: src/vm/i386/excepx86.cpp (hunk 26 above)
Comment (parjong) [inline src/vm/i386/excepx86.cpp]: Is it better to another implementation of ``CLRNoCatchHandler``? 

``EX_END_NOCATCH`` in ``vm/clrex.h`` uses ``CLRNoCatchHandler`` and we need to in order to resolve undefined reference issues.

It would be the best if we could eliminate the use of ``CLRNoCatchHandler``, but I'm not sure whether it is possible.

File: src/vm/excep.cpp (hunk 30 above)
Comment (parjong) [inline src/vm/excep.cpp]: Thanks you for kind answer. It was a big question for me.

File: src/vm/jitinterface.h (hunk 28 above)
Comment (parjong) [inline src/vm/jitinterface.h]: I added a comment.

File: src/vm/i386/excepx86.cpp (hunk 26 above)
Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: Hmm, CLRNoCatchHandler is really needed, I have not realized it is defined here. And maybe I am wrong with excluding the whole file. Let me go through it and see what is actually needed.

Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: There are too many functions just to try to go through them one by one. But looking at the excepamd64.cpp and exceparm.cpp, it looks like only a few functions are needed here. So I would recommend wrapping the whole body of the source file (starting after the includes) in #ifndef WIN64EXCEPTIONS and then moving out if that only functions that you'll find as missing. I guess it should be about 5 functions, CLRNoCatchHandler being one of them.

Comment (janvorli) [inline src/vm/i386/excepx86.cpp]: @parjong I just tried to ifdef-out what I've said and have built it on a x86 Linux. Then used `ldd -r libcoreclr.so` to see the missing symbols. There were just two:
```
AdjustContextForVirtualStub(_EXCEPTION_RECORD*, _CONTEXT*)
CLRNoCatchHandler(_EXCEPTION_POINTERS*, void*)
```

Comment (parjong) [inline src/vm/i386/excepx86.cpp]: @janvorli I'll move them as you suggested (Actually, it was my first attempt, but I thought that it would make it hard to review).

Comment (parjong) [inline src/vm/i386/excepx86.cpp]: @janvorli I submitted revised PR per feedback.

File: src/vm/i386/unixstubs.cpp (hunk 27 above)
Comment (janvorli) [inline src/vm/i386/unixstubs.cpp]: Well, after we switch, there is no reason for leaving in things that are not needed.

File: src/vm/i386/excepcpu.h [hunk 31]
```diff
@@ -90,14 +91,34 @@ extern VOID ResetSEHRecord(PEXCEPTION_REGISTRATION_RECORD record);
...
 // RedirectedHandledJITCaseForXXX_Stub's.
 //
 PTR_CONTEXT GetCONTEXTFromRedirectedStubStackFrame(CONTEXT * pContext);
+#ifdef WIN64EXCEPTIONS
+PTR_CONTEXT GetCONTEXTFromRedirectedStubStackFrame(T_DISPATCHER_CONTEXT * pDispatcherContext);
+#endif // WIN64EXCEPTIONS
 
-PEXCEPTION_REGISTRATION_RECORD GetCurrentSEHRecord();
-PEXCEPTION_REGISTRATION_RECORD GetFirstCOMPlusSEHRecord(Thread*);
+#ifdef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/vm/i386/excepcpu.h]: Can you please merge the two ifdef blocks since they have the same condition?

File: src/vm/i386/unixstubs.cpp (hunk 27 above)
Comment (parjong) [inline src/vm/i386/unixstubs.cpp]: I'm sorry for not being clear. What I intended is "Should I add a patch to enable ``WIN64EXCEPTIONS`` for x86/Linux in this PR?". (That patch is not added, yet.)

Comment (janvorli) [inline src/vm/i386/unixstubs.cpp]: I would like to enable them with this merge unless you can see some benefit from doing it later.

Comment (parjong) [inline src/vm/i386/unixstubs.cpp]: Okay. I added a commit that enables ``WIN64EXCEPTIONS`` and removes unnecessary stubs from ``excepcpu.h`` and ``excepx86.cpp``.

File: src/vm/codeman.cpp (hunk 22 above)
Comment (janvorli) [inline src/vm/codeman.cpp]: @jkotas, I have looked at that and we are not accessing the last field. When WIN64EXCEPTIONS is defined, the CodeInfo  ends with DWORD nUnwindInfos and the code here accesses the phdrMDesc.
```C++
   PTR_BYTE            phdrDebugInfo;
    
    // Note - *(&(pCodeHeader->phdrJitEHInfo) - sizeof(size_t)) 
    // contains the number of EH clauses, See EEJitManager::allocEHInfo
    PTR_EE_ILEXCEPTION  phdrJitEHInfo;
    PTR_BYTE            phdrJitGCInfo;

#if defined(FEATURE_GDBJIT)
    VOID*            pCalledMethods;
#endif

    PTR_MethodDesc      phdrMDesc;

#ifdef WIN64EXCEPTIONS
    DWORD               nUnwindInfos;
    T_RUNTIME_FUNCTION  unwindInfos[0];
#endif // WIN64EXCEPTIONS
```

Comment (jkotas) [inline src/vm/codeman.cpp]: Sounds good. Nice catch!

Comment (jkotas) [inline src/vm/codeman.cpp]: Wait - it is still does not make sense. `nUnwindInfo/unwindInfos` fields require `USE_INDIRECT_CODEHEADER` to be used. and this structure is variable size allocated out of line. The above `sizeof(TADDR)` has nothing to do with it.

Comment (parjong) [inline src/vm/codeman.cpp]: The issue that I mentioned above happens when ``WIN64EXCEPTIONS`` is set, but ``USE_INDIRECT_CODEHEADER`` is not set. Later I decide to set ``USE_INDIRECT_CODEHEADER`` for x86/Linux.

Is there any difference bettwen Windows and Linux? IMHO, this issue should be reproduced for x86/Windows port (which uses ditect code header), but it isn't.

Comment (parjong) [inline src/vm/codeman.cpp]: Ah, I got why it happens. When ``WIN64EXCEPTIONS`` is not set, ``phdrMDesc`` occupies the region added by ``sizeof(TADDR)``, and thus the issue that I mentioned before does not happen.

Comment (janvorli) [inline src/vm/codeman.cpp]: Right. That's what @jkotas was originally saying.  So the WIN64EXCEPTIONS has to always be used with USE_INDIRECT_CODEHEADER only.

Comment (parjong) [inline src/vm/codeman.cpp]: For x86/Windows, there is no update on other fields, such``phdrDebugInfo`` / ``phdrJitEHInfo``? If so, it would be better to introduce ifdef if we should cencern additional memory usage.

Comment (janvorli) [inline src/vm/codeman.cpp]: I would just add #error to the codeman.h around line 125 that would fire if the WIN64EXCEPTIONS was defined without USE_INDIRECT_CODEHEADER

Comment (parjong) [inline src/vm/codeman.cpp]: @janvorli I added related #error directive (6019340).

**Comment by parjong** [comment]
@janvorli I revised PR per feedback. Please take a look.

**Comment by parjong** [comment]
@jkotas @janvorli Please take a look.

File: src/debug/inc/dbgipcevents.h [hunk 32]
```diff
@@ -1355,11 +1355,11 @@ struct MSLAYOUT DebuggerIPCE_JITFuncData
     LSPTR_DJI   nativeCodeJITInfoToken;
     VMPTR_MethodDesc vmNativeCodeMethodDescToken;
 
-#if defined(DBG_TARGET_WIN64) || defined(DBG_TARGET_ARM)
+#ifdef WIN64EXCEPTIONS
```
Comment (janvorli) [inline src/debug/inc/dbgipcevents.h]: Please change also the same condition at src\debug\di\rsthread.cpp:5852

Comment (parjong) [inline src/debug/inc/dbgipcevents.h]: @janvorli Revised.

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by parjong** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please

**Comment by janvorli** [comment]
@mmitche both ARM CI legs are failing with
`19:18:53 + ./tests/scripts/arm32_ci_script.sh --emulatorPath=/opt/linux-arm-emulator --mountPath=/opt/linux-arm-emulator-root --buildConfig=debug --testRootDir=./bin/tests/Windows_NT.x64.Debug --coreFxNativeBinDir=./bin/Linux.arm-softfp.Debug --coreFxBinDir=./bin/Linux.AnyCPU.Debug;./bin/Unix.AnyCPU.Debug;./bin/AnyOS.AnyCPU.Debug --testDirFile=./tests/testsRunningInsideARM.txt
19:18:53 ERROR: Path specified in --coreFxNativeBinDir does not exist`
@parjong has re-run it multiple times and the error persists. Could you please take a look?

**Comment by mmitche** [comment]
@janvorli I'm guessing something changed with some of the upstream jobs.  @jashook Who is repsonsible for these now?

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by janvorli** [comment]
@dotnet-bot test Linux ARM Emulator Cross Release Build please
