### PR TITLE
Fix #16402

### LINKED ISSUE #16402: [Arm64/Ubuntu] Crossgen of Microsoft.CodeAnalysis.CSharp.dll fails
Spending 93% of time in `HashMap::Rehash()`

### PR DESCRIPTION
**Pull request by sdmaclea**
AssemblySpec comparisons were failing when binders were null.
Also add early out to `HashMap::Rehash()`

Fixes #16402

@jkotas Please assign as appropriate

### CODE REVIEW

File: src/vm/hash.cpp [hunk 1]
```diff
@@ -878,9 +878,16 @@ void HashMap::Rehash()
...
 
-    ASSERT(m_iPrimeIndex < 70);
+    if ((m_iPrimeIndex == newPrimeIndex) && (m_cbDeletes == 0))
+    {
+        return;
+    }
+
+    DWORD cbNewSize = g_rgPrimes[m_iPrimeIndex = newPrimeIndex];
+
+    ASSERT(m_iPrimeIndex < g_rgNumPrimes);
```
Comment (jkotas) [inline src/vm/hash.cpp]: Should this assert be before it is used to index into `g_rgPrimes` array?
