### PR TITLE
Fixing 23941

### LINKED ISSUE #23941: CallbackTests.cmd and ResolveEventTests.cmd time out on Windows_NT x86 in PRs
For example,
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F23916~2Fmerge/test~2Ffunctional~2Fr2r~2Fcli~2F/20190412.713/workItem/Interop/wilogs

```
  Discovering: Interop.NativeLibraryResolveCallback.XUnitWrapper

  Discovered:  Interop.NativeLibraryResolveCallback.XUnitWrapper

  Starting:    Interop.NativeLibraryResolveCallback.XUnitWrapper

    Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd [FAIL]

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd Timed Out

      

Return code:      -100
Raw output file:      C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\Reports\Interop.NativeLibraryResolveCallback\CallbackTests\CallbackTests.output.txt
Raw output:
BEGIN EXECUTION

              1 file(s) copied.

      " C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\crossgen.exe"  /Platform_Assemblies_Paths C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\IL;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests /in CallbackTests.org /out CallbackTests.exe

      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0

      Copyright (c) Microsoft Corporation.  All rights reserved.

      

      Native image CallbackTests.exe generated successfully.

       "C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\corerun.exe" CallbackTests.exe 

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd Timed Out

      Test Harness Exitcode is : -100

      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload
> C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd


      Expected: True

      Actual:   False

      Stack Trace:

        F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.NativeLibraryResolveCallback\Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(112,0): at Interop_NativeLibraryResolveCallback._CallbackTests_CallbackTests_._CallbackTests_CallbackTests_cmd()

  Finished:    Interop.NativeLibraryResolveCallback.XUnitWrapper

  Discovering: Interop.NativeLibraryResolveEvent.XUnitWrapper

  Discovered:  Interop.NativeLibraryResolveEvent.XUnitWrapper

  Starting:    Interop.NativeLibraryResolveEvent.XUnitWrapper

    Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd [FAIL]

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd Timed Out

      

Return code:      -100
Raw output file:      C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\Reports\Interop.NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.output.txt
Raw output:
BEGIN EXECUTION

              1 file(s) copied.

      " C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\crossgen.exe"  /Platform_Assemblies_Paths C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\IL;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests /in ResolveEventTests.org /out ResolveEventTests.exe

      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0

      Copyright (c) Microsoft Corporation.  All rights reserved.

      

      Native image ResolveEventTests.exe generated successfully.

       "C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\corerun.exe" ResolveEventTests.exe 

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd Timed Out

      Test Harness Exitcode is : -100

      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload
> C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd


      Expected: True

      Actual:   False

      Stack Trace:

        F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.NativeLibraryResolveEvent\Interop.NativeLibraryResolveEvent.XUnitWrapper.cs(112,0): at Interop_NativeLibraryResolveEvent._ResolveEventTests_ResolveEventTests_._ResolveEventTests_ResolveEventTests_cmd()
```

### PR DESCRIPTION
**Pull request by fadimounir**
The issue here is that in R2R code, unlike jitted IL code, the pinvoke calls are wrapped by a pair of calls to the JIT_PInvokeBegin and JIT_PInvokeEnd helpers, which link and unlink the InlinedCallFrame to the current thread. We do not initialize and link the ICF in the method prolog, and unlink it in the epilog, like jitted code does. We do this in the JIT helpers, right before/after the pinvoke call.
When an exception is thrown, the JIT_PInvokeEnd helper will be skipped since execution will resume at the nearest valid catch block, and the ICF will remain linked to the thread, which poses a problem if the method attempts another pinvoke operation (it will try to link the ICF which is already the top frame, and we'll end up in an infinite loop). Therefore, for the R2R case, we need to pop the ICF from the chain during exception unwinding.

Fixes #23941

### CODE REVIEW

**Comment by fadimounir** [comment]
@janvorli suggested an alternative solution to this, and that is to have the JIT wrap the pinvoke into a try-finally block, so we can have the finally block call the JIT_PInvokeEnd helper, and unlink the ICF. I'm exploring that option too, hence the WIP.

In the mean time, @janvorli @jkotas could you please give me your feedback on these changes which pop the ICF during unwinding?

**Comment by jkotas** [comment]
> have the JIT wrap the pinvoke into a try-finally block,

This would increase the PInvoke overhead and introduce a completely new path across JIT&runtime ...

File: src/vm/exceptionhandling.cpp [hunk 1]
```diff
@@ -1851,9 +1857,20 @@ CLRUnwindStatus ExceptionTracker::ProcessOSExceptionNotification(
...
+
+                    // When unwinding an exception in ReadyToRun, the JIT_PInvokeEnd helper which unlinks the ICF from 
+                    // the thread will be skipped. This is because unlike jitted code, each pinvoke is wrapped by calls
+                    // to the JIT_PInvokeBegin and JIT_PInvokeEnd helpers, which push and pop the ICF on the thread. The
+                    // ICF is not linked at the method prolog and unlined at the epilog when running R2R code. Since the
+                    // JIT_PInvokeEnd helper will be skipped, we need to unlink the ICF here. If the executing method
+                    // has another pinovoke, it will re-link the ICF again when the JIT_PInvokeBegin helper is called
+
+                    MethodDesc* pPInvokeTargetMD = pFrame->GetFunction();
+                    if (pPInvokeTargetMD != NULL && pPInvokeTargetMD->GetModule()->IsReadyToRun())
```
Comment (jkotas) [inline src/vm/exceptionhandling.cpp]: This needs to check whether the *code* being unwound is in R2R image. The code for MethodDesc from R2R image can be JITed for number of reasons.

File: src/vm/dllimport.cpp [hunk 2]
```diff
@@ -7076,6 +7076,15 @@ EXTERN_C LPVOID STDCALL NDirectImportWorker(NDirectMethodDesc* pMD)
             _ASSERTE(pThread->GetFrame()->GetVTablePtr() == InlinedCallFrame::GetMethodFrameVPtr());
 
             CONSISTENCY_CHECK(pMD->IsNDirect());
+
+            if (pMD->GetModule()->IsReadyToRun())
+            {
+                // We need pMD in the case of an exception unwinding, so we can test if the pinvoke method is
+                // in a R2R module, and if so, properly pop the PInvoke frame from the thread. This is because
+                // the JIT_PInvokeEnd helper that pops the frame will not run when there's an exception.
+                ((InlinedCallFrame*)pThread->GetFrame())->m_Datum = pMD;
```
Comment (jkotas) [inline src/vm/dllimport.cpp]: What will happen if the exception is thrown from the method in steady state? Note that we do support exception interop on Windows.

Comment (fadimounir) [reply src/vm/dllimport.cpp]: I'm not sure if I understood this correctly, but if you're referring to exceptions being thrown by the method with pinvoke away from any pinvoke code, then this works (also updated the test with this scenario)

File: src/vm/exceptionhandling.cpp (hunk 1 above)
Comment (fadimounir) [reply src/vm/exceptionhandling.cpp]: Oh ok, makes sense

File: src/vm/dllimport.cpp (hunk 2 above)
Comment (fadimounir) [reply src/vm/dllimport.cpp]: Or did you mean after a tiered re-compilation of the method?

Comment (jkotas) [reply src/vm/dllimport.cpp]: The case I am wondering about is when the `DllImport` method throws exception in C/C++. I do not see a test for that in your changes.

To add coverage for this, you can add `[DllImport]` for `RaiseException` that will get called in a loop.

File: src/vm/readytoruninfo.cpp [hunk 3]
```diff
@@ -334,6 +334,12 @@ PTR_BYTE ReadyToRunInfo::GetDebugInfo(PTR_RUNTIME_FUNCTION pRuntimeFunction)
     return dac_cast<PTR_BYTE>(m_pLayout->GetBase()) + debugInfoOffset;
 }
 
+BOOL ReadyToRunInfo::IsReadyToRunEntryPoint(PCODE pCode)
+{
+    return pCode >= dac_cast<TADDR>(m_pLayout->GetBase()) && 
+           pCode < dac_cast<TADDR>(m_pLayout->GetBase()) + m_pLayout->GetSize();
```
Comment (fadimounir) [inline src/vm/readytoruninfo.cpp]: It would have been more ideal to use `GetBase + m_pRuntimeFunctions[0].BeginAddress` and `GetBase + m_pRuntimeFunctions[m_nRuntimeFunctions - 1].EndAddress`, but `EndAddress` is not available on x86

File: src/vm/i386/excepx86.cpp [hunk 4]
```diff
@@ -1868,6 +1868,24 @@ NOINLINE LPVOID COMPlusEndCatchWorker(Thread * pThread)
...
+        // the thread will be skipped. This is because unlike jitted code, each pinvoke is wrapped by calls
+        // to the JIT_PInvokeBegin and JIT_PInvokeEnd helpers, which push and pop the ICF on the thread. The
+        // ICF is not linked at the method prolog and unlined at the epilog when running R2R code. Since the
+        // JIT_PInvokeEnd helper will be skipped, we need to unlink the ICF here. If the executing method
+        // has another pinovoke, it will re-link the ICF again when the JIT_PInvokeBegin helper is called
+
+        MethodDesc* pPInvokeTargetMD = pThread->m_pFrame->GetFunction();
+        if (pPInvokeTargetMD != NULL && 
+            pPInvokeTargetMD->GetModule()->IsReadyToRun() &&
+            pPInvokeTargetMD->GetModule()->GetReadyToRunInfo()->IsReadyToRunEntryPoint(((InlinedCallFrame*)pThread->m_pFrame)->m_pCallerReturnAddress))
```
Comment (jkotas) [inline src/vm/i386/excepx86.cpp]: This is not compatible with large version bubbles. With larger version bubbles, the MethodDesc may be from a different module than the module containing the code.

It may be better to check whether the code is managed by ReadyToRunJitManager

File: src/vm/dllimport.cpp (hunk 2 above)
Comment (fadimounir) [reply src/vm/dllimport.cpp]: Ok, that one works. I added it to the test

File: src/vm/i386/excepx86.cpp (hunk 4 above)
Comment (fadimounir) [reply src/vm/i386/excepx86.cpp]: Ok, that's exactly what I was looking for. This actually simplifies a whole lot!

File: src/vm/codeman.cpp [hunk 5]
```diff
@@ -4357,6 +4357,31 @@ BOOL ExecutionManager::IsManagedCodeWorker(PCODE currentPC)
     return FALSE;
 }
 
+//**************************************************************************
+// Assumes that it is safe not to take it the ExecutionManager reader/writer lock
```
Comment (fadimounir) [inline src/vm/codeman.cpp]: The IsManagedCode has a version that takes a lock, but the exception handling code doesn't use it, so I just added a IsReadyToRunCode version that assumes it's not safe to take the lock. Not sure if need one with lock taking. I don't know what would use it
