### PR TITLE
[ARM/Linux] Fix incorrect return marshaling in PInvoke stub

### LINKED ISSUE #5009: [ARM/Linux] Unittest failure - JIT.jit64.hfa.main.testE.hfa_nf2E_d.hfa_nf2E_d
Running 'JIT.jit64.hfa.main.testE.hfa_nf2E_d.hfa_nf2E_d' on ARM/Linux shows the following output:
```
**** MessageBox invoked, title 'corerun - Assert Failure (PID 14370, Thread 14370/0x3822)' ****
  Assertion failed 'ret->TypeGet() == TYP_VOID' in 'DomainBoundILStubClass:IL_STUB_PInvoke(struct):struct' (IL size 52)


/home/parjong/projects/toolchains/coreclr/src/jit/morph.cpp, Line: 14585

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/mnt/dotnet-latest/Linux.arm.Debug/corerun

********
```

### PR DESCRIPTION
**Pull request by parjong**
For ARM, the current implementation of 'compMethodReturnsMultiRegRetType'
always returns false.

Unfortunately, this behavior is inconsistent with JIT importer. JIT impoter
attempts to merge various return statements as one statement via inserting
an assignment statement just before each return statement if there are more
than 4 returns.

If the method of interest has a return value, then JIT importer
introduces a local temporary variable, and use it to return value.

Due to the above implementation, JIT importer never generates a return
variable, which results in assertion violation inside JIT morph, which
is discussed in #5009.

This commit attempts to fix #5009 via implementing 'compMethodReturnsMultiRegRetType'
for ARM.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test please

**Comment by parjong** [comment]
@dotnet-bot test FreeBSD x64 Checked Build please

**Comment by parjong** [comment]
@janvorli Please take a look. It seems that the patches are not related with OSX, but OSX testcases fails. 

@wateret When I checked via Linux/ARM emulator, it seems that this PR also fixes #4745. Please check it.

**Comment by parjong** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by janvorli** [comment]
cc: @dotnet/jit-contrib

**Comment by wateret** [comment]
@parjong, I tested #4745 and it works! :+1:

**Comment by janvorli** [comment]
@BruceForstall could you please take a look? I've cc'ed @dotnet/jit-contrib last week, but it seems it was missed.

**Comment by RussKeldorph** [comment]
@CarolEidt @briansull @sivarv PTAL in @BruceForstall's absence.

File: src/jit/compiler.h [hunk 1]
```diff
@@ -7901,6 +7901,9 @@ public :
         // Methods returning a struct in two registers is considered having a return value of TYP_STRUCT.
         // Such method's compRetNativeType is TYP_STRUCT without a hidden RetBufArg
         return varTypeIsStruct(info.compRetNativeType) && (info.compRetBuffArg == BAD_VAR_NUM);
+#elif defined(_TARGET_ARM_)
+        // TODO-ARM HFA Support
+        return varTypeIsStruct(info.compRetNativeType) && (info.compRetBuffArg == BAD_VAR_NUM);
```
Comment (briansull) [inline src/jit/compiler.h]: I will revisit this area shortly as I implement this for ARM64

**Comment by briansull** [comment]
LGTM

File: src/jit/compiler.h (hunk 1 above)
Comment (CarolEidt) [inline src/jit/compiler.h]: Even though this will be revisited shortly, I don't know why we would repeat the same code in a separate #ifdef. Why would this not be combined with the above line?

Comment (sivarv) [inline src/jit/compiler.h]: I agree with Carol, why do we need to duplicate the same code instead of adding 

`"|| defined(_TARGET_ARM_)"`

?

File: src/jit/compiler.h [hunk 2]
```diff
@@ -7901,6 +7901,9 @@ public :
         // Methods returning a struct in two registers is considered having a return value of TYP_STRUCT.
         // Such method's compRetNativeType is TYP_STRUCT without a hidden RetBufArg
         return varTypeIsStruct(info.compRetNativeType) && (info.compRetBuffArg == BAD_VAR_NUM);
+#elif defined(_TARGET_ARM_)
```
Comment (sivarv) [inline src/jit/compiler.h]: Is the comment on line 7895 still relevant or needs to be updated?

Also what is genReturnLocaled referring to?  I am sensing a typo here.
