### PR TITLE
[Unix] runtest.sh crossgen should exit on failure

### LINKED ISSUE #8988: Crossgen failure should terminate the build
This does not happen today as evidenced in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=526522 where build.cmd passes even when crossgen failed:

```
2017-01-18T16:28:40.9144814Z Command execution succeeded.
2017-01-18T16:28:40.9144814Z BUILD: Generating native image of System.Private.CoreLib for Windows_NT.arm64.Checked
2017-01-18T16:28:40.9144814Z "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\x64\crossgen.exe" /Platform_Assemblies_Paths "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked" /out "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\System.Private.CoreLib.ni.dll" "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\System.Private.CoreLib.dll"
2017-01-18T16:28:48.0710293Z BUILD: Error: CrossGen System.Private.CoreLib build failed. Refer to E:\A\_work\22\s\bin\Logs\CrossgenCoreLib_Windows_NT__arm64__Checked.log
2017-01-18T16:28:48.0710293Z     E:\A\_work\22\s\bin\Logs\CrossgenCoreLib_Windows_NT__arm64__Checked.log
2017-01-18T16:28:48.0710293Z ##[section]Finishing: Run build.cmd
```

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #8988 on unix

@wtgodbe  @gkhanna79 @parjong PTAL This code is only exercised when run when running runtest.sh with --crossgen option.

### CODE REVIEW

File: src/utilcode/pedecoder.cpp [hunk 1]
```diff
@@ -1829,7 +1829,7 @@ BOOL PEDecoder::HasNativeHeader() const
 
 #ifdef FEATURE_PREJIT
     // Pretend that ready-to-run images do not have native header
-    RETURN (((GetCorHeader()->Flags & VAL32(COMIMAGE_FLAGS_IL_LIBRARY)) != 0) && !HasReadyToRunHeader());
+    RETURN (GetCorHeader() && ((GetCorHeader()->Flags & VAL32(COMIMAGE_FLAGS_IL_LIBRARY)) != 0) && !HasReadyToRunHeader());
```
Comment (sdmaclea) [inline src/utilcode/pedecoder.cpp]: This was triggering a segfault when running crossgen on files that were not managed assemblies.

File: tests/runtest.sh [hunk 2]
```diff
@@ -382,11 +383,17 @@ function create_core_overlay {
...
+    while read line
+    do
+      skipCrossGenFiles[$line]=1
+    done <  "$(dirname "$0")/skipCrossGenFiles.$ARCH.txt"
 
     if [ $doCrossgen == 1 ]; then
         local overlayDir=$CORE_ROOT
 
-        filesToPrecompile=$(ls -trh $overlayDir/*.dll)
+        filesToPrecompile=$(find -L $overlayDir -iname \*.dll -not -iname \*.ni.dll -not -iname \*-ms-win-\* -type f )
```
Comment (sdmaclea) [inline tests/runtest.sh]: Using find to reduce the number of crossgen calls.  

* Removed *.ni.dll from list.  
* Removed *-ms-win-* from the list as these represent the bulk of the native windows dll which are copied into the unix overlay.  It is possible this should just be a rm *-ms-win* when the overlay is created

File: tests/runtest.sh [hunk 3]
```diff
@@ -397,20 +404,23 @@ function precompile_overlay_assemblies {
                     echo Unable to generate dasm for $filename
                 fi
             else
-                # Precompile any assembly except mscorlib since we already have its NI image available.
-                if [[ "$filename" != *"mscorlib.dll"* ]]; then
-                    if [[ "$filename" != *"mscorlib.ni.dll"* ]]; then
-                        echo Precompiling $filename
-                        $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename 2>/dev/null
-                        local exitCode=$?
-                        if [ $exitCode == -2146230517 ]; then
```
Comment (sdmaclea) [inline tests/runtest.sh]: This code never worked as the exitcode is always 0-255 on Unix bash

File: tests/runtest.sh [hunk 4]
```diff
@@ -397,20 +404,23 @@ function precompile_overlay_assemblies {
                     echo Unable to generate dasm for $filename
                 fi
             else
-                # Precompile any assembly except mscorlib since we already have its NI image available.
-                if [[ "$filename" != *"mscorlib.dll"* ]]; then
-                    if [[ "$filename" != *"mscorlib.ni.dll"* ]]; then
```
Comment (sdmaclea) [inline tests/runtest.sh]: Removed these lines because they are a special case of a skip list.  Added to skip lists instead.

File: tests/runtest.sh [hunk 5]
```diff
@@ -397,20 +404,23 @@ function precompile_overlay_assemblies {
...
+                    if grep -q -e '(COR_E_ASSEMBLYEXPECTED)' $filename.stderr; then
+                        printf "\n\t$filename is not a managed assembly.\n\n"
+                    else
+                        echo Unable to precompile $filename.
+                        cat $filename.stdout
+                        cat $filename.stderr
+                        exit $exitCode
                     fi
+                else
+                    rm $filename.{stdout,stderr}
```
Comment (sdmaclea) [inline tests/runtest.sh]: I quieted the output significantly I only print stdout/stderr if test is failing.

File: tests/runtest.sh [hunk 6]
```diff
@@ -397,20 +404,23 @@ function precompile_overlay_assemblies {
...
-                            echo Successfully precompiled $filename
-                        fi
+                if [[ -v skipCrossGenFiles[$(basename $filename)] ]]; then
+                    continue
+                fi
+                echo Precompiling $filename
+                $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename 1> $filename.stdout 2>$filename.stderr
+                local exitCode=$?
+                if [[ $exitCode != 0 ]]; then
+                    if grep -q -e '(COR_E_ASSEMBLYEXPECTED)' $filename.stderr; then
```
Comment (sdmaclea) [inline tests/runtest.sh]: Since exit code is not reliable using grep of stdout to find the not a managed assembly error.  Choose to search on the human readable error rather than the hex error.

File: tests/skipCrossGenFiles.arm.txt [hunk 7]
```diff
@@ -0,0 +1,2 @@
+mscorlib.dll
+System.Runtime.WindowsRuntime.UI.Xaml.dll
```
Comment (sdmaclea) [inline tests/skipCrossGenFiles.arm.txt]: This test fails because there is a missing *.dll.  It seems logical to believe the managed assembly is for windows only.

File: tests/skipCrossGenFiles.arm.txt [hunk 8]
```diff
@@ -0,0 +1,2 @@
+mscorlib.dll
```
Comment (sdmaclea) [inline tests/skipCrossGenFiles.arm.txt]: This had been explicitly skipped in earlier code.  I do not believe this has to be skipped, but since it is built by build.sh, skipping seems reasonable.

System.Private.CoreLib.dll could be added for similar reasons.

File: tests/skipCrossGenFiles.arm64.txt [hunk 9]
```diff
@@ -0,0 +1,5 @@
+System.Runtime.WindowsRuntime.UI.Xaml.dll
```
Comment (sdmaclea) [inline tests/skipCrossGenFiles.arm64.txt]: See x64.

File: tests/skipCrossGenFiles.arm64.txt [hunk 10]
```diff
@@ -0,0 +1,5 @@
...
+Microsoft.CodeAnalysis.VisualBasic.dll
+System.Net.NameResolution.dll
+System.Net.Sockets.dll
+System.Net.Primitives.dll
```
Comment (sdmaclea) [inline tests/skipCrossGenFiles.arm64.txt]: These are tracked by #9898

File: tests/skipCrossGenFiles.arm.txt (hunk 7 above)
Comment (sdmaclea) [inline tests/skipCrossGenFiles.arm.txt]: @parjong  I was think you might be able to identify someone to populate the arm/x86 lists if needed.

File: tests/runtest.sh [hunk 11]
```diff
@@ -397,20 +404,23 @@ function precompile_overlay_assemblies {
...
-                        $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename 2>/dev/null
-                        local exitCode=$?
-                        if [ $exitCode == -2146230517 ]; then
-                            echo $filename is not a managed assembly.
-                        elif [ $exitCode != 0 ]; then
-                            echo Unable to precompile $filename.
-                        else
-                            echo Successfully precompiled $filename
-                        fi
+                if [[ -v skipCrossGenFiles[$(basename $filename)] ]]; then
```
Comment (sdmaclea) [inline tests/runtest.sh]: The test -v is a bash extension in bash 4.2 or newer.  If we will cross compile from machines with older bash, we can use older style tests which are backward compatible.

**Comment by wtgodbe** [comment]
LGTM

**Comment by sdmaclea** [comment]
@wtgodbe The OSX failure is real

```
08:29:47 ./tests/runtest.sh: line 407: conditional binary operator expected
08:29:47 ./tests/runtest.sh: line 407: syntax error near `$filename)]'
08:29:47 ./tests/runtest.sh: line 407: `                if [[ -v skipCrossGenFiles[$(basename $filename)] ]]; then'
```

Looks like the test -v is not supported on OSX.   I'll need to amend the commit

File: tests/runtest.sh (hunk 2 above)
Comment (gkhanna79) [inline tests/runtest.sh]: @wtgodbe Can you please file an issue against yourself to ensure that APISets are not part of the non-Windows overlay?

Comment (wtgodbe) [inline tests/runtest.sh]: https://github.com/dotnet/coreclr/issues/9918

File: tests/skipCrossGenFiles.arm.txt (hunk 7 above)
Comment (parjong) [inline tests/skipCrossGenFiles.arm.txt]: @sdmaclea Thank you for letting me know. 
@jyoungyun @hqueue @hseok-oh Do we currently have any files that should be included here?

Comment (parjong) [inline tests/skipCrossGenFiles.arm.txt]: @sjsinju This may be interesting to you.

Comment (hseok-oh) [inline tests/skipCrossGenFiles.arm.txt]: In fact, `mscorlib.ni.dll` and `System.Private.CoreLib.ni.dll` cannot be generated in build time for arm32/linux yet. But we should generate these files first to test crossgen in target device, so it seems reasonable.

Comment (hseok-oh) [inline tests/skipCrossGenFiles.arm.txt]: @parjong I have faced no problem when running runtest.sh crossgen to generating *.ni.dll file. We have a little runtime issue to use crossgen, but it's different problem.

**Comment by sdmaclea** [comment]
Can this be merged?

**Comment by sdmaclea** [comment]
@wtgodbe @gkhanna79 There were merge conflicts on tip, so I just resolved.  Checks just restarted.  This PR has a crossgen segfault fix buried in it, so I would like to see it merged.  Should I move the segfault fix to a separate PR if this will take a long time to merge?

**Comment by danmosemsft** [comment]
@dotnet-bot test osx10.12 x64 checked build and test please (https://github.com/dotnet/coreclr/issues/10312)

**Comment by gkhanna79** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test please

**Comment by sdmaclea** [comment]
Is there anything preventing this from being merged?
