### PR TITLE
Force byteable register for CMP if op2 is CNS_INT

### LINKED ISSUE #7478: RyuJIT x86 [JitStress=2][JitStressRegs=1]: Assertion failed 'emitVerifyEncodable(ins, size, reg)' in 'System.Runtime.Serialization.Json.XmlJsonReader:ReadQuotedText(bool):this'
```
07:55:07 D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(307155): error : JIT._Performance_CodeQuality_Serialization_Deserialize_Deserialize_._Performance_CodeQuality_Serialization_Deserialize_Deserialize_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\runtest.proj]
07:55:07         
07:55:07         Assert failure(PID 6272 [0x00001880], Thread: 6008 [0x1778]): Assertion failed 'emitVerifyEncodable(ins, size, reg)' in 'System.Runtime.Serialization.Json.XmlJsonReader:ReadQuotedText(bool):this' (IL size 244)
07:55:07         
07:55:07             File: d:\j\workspace\x86_ryujit_ch---0cf1dcc7\src\jit\emitxarch.cpp Line: 3385
07:55:07             Image: D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
07:55:07         
07:55:07         
07:55:07   
07:55:07   Return code:      1
07:55:07   Raw output file:      D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Performance\CodeQuality\Serialization\Deserialize\Deserialize.output.txt
07:55:07   Raw output:
07:55:07   BEGIN EXECUTION
07:55:07          "D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Deserialize.exe 
07:55:07         Expected: 100
07:55:07         Actual: 123456789
07:55:07         END EXECUTION - FAILED
07:55:07         FAILED
07:55:07         Test Harness Exitcode is : 1
07:55:07         
07:55:07   To run the test:
07:55:07   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
07:55:07   > D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\JIT\Performance\CodeQuality\Serialization\Deserialize\Deserialize.cmd
07:55:07   
07:55:07         Expected: True
07:55:07         Actual:   False
07:55:07           D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(307155,0): at JIT._Performance_CodeQuality_Serialization_Deserialize_Deserialize_._Performance_CodeQuality_Serialization_Deserialize_Deserialize_cmd()
```

I believe that this may be addressed by #7466.

### PR DESCRIPTION
**Pull request by adiaaida**
On x86 we need to force byteable registers for compares not only when both
ops are typ_byte, but also when the first is of typ_byte and the second is
a constant int. The original condition for cmp only considered the first
case. This change adds the second condition.

Fixes #7478.

### CODE REVIEW

**Comment by adiaaida** [comment]
@sivarv PTAL
/cc: @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
LGTM.

Any asm diffs?

File: src/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -925,7 +925,8 @@ void Lowering::TreeNodeInfoInit(GenTree* tree)
     // the below logic leads to conservative register specification.  In future when or if we find
     // one such case, this logic needs to be fine tuned for that case(s).
     if (varTypeIsByte(tree) || ((tree->OperGet() == GT_CAST) && varTypeIsByte(tree->CastToType())) ||
-        (tree->OperIsCompare() && varTypeIsByte(tree->gtGetOp1()) && varTypeIsByte(tree->gtGetOp2())))
+        (tree->OperIsCompare() && varTypeIsByte(tree->gtGetOp1()) &&
+         (varTypeIsByte(tree->gtGetOp2()) || tree->gtGetOp2()->IsCnsIntOrI())))
```
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Do these conditions also need to cover the other small types (`TYP_BOOL`, `TYP_UBYTE`, `TYP_CHAR`, `TYP_SHORT`, `TYP_USHORT`)?

**Comment by adiaaida** [comment]
@BruceForstall there do not appear to be diffs according to jit-diff.

**Comment by adiaaida** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstressregs8

File: src/jit/lowerxarch.cpp (hunk 1 above)
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: varTypeIsByte covers the following types TYP_BOOL, BYTE, UBYTE  whose original size is 1-byte

CHAR, SHORT, USHORT are 16-bit (or 2-byte) types - these don't need to be covered by these conditions.

---
In reply to: [82429683](https://github.com/dotnet/coreclr/pull/7518#discussion_r82429683) [](ancestors = 82429683)

Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: > varTypeIsByte covers the following types TYP_BOOL, BYTE, UBYTE whose original size is 1-byte

Excellent.

> CHAR, SHORT, USHORT are 16-bit (or 2-byte) types - these don't need to be covered by these conditions.

Ah, yeah--I could not recall whether or not all x86 registers were 16-bit-addressable, but I believe they are. LGTM.

Comment (sivarv) [inline src/jit/lowerxarch.cpp]: IMO, Long term it is best that individual GenTree nodes that deal with byte types have logic to specify byteable reg specification in the corresponding TreeNodeInfoInit*() routine.
That way we can tailor the conditions for byteable register specification for each GenTree node and other GenTree nodes that don't deal with byte types don't need to be concerned about this logic.

Since you are modifying the condition for compare, how about taking this opportunity to move compare specific logic to TreeNodeInfoInitCmp()?

If you don't want to club that restructuring with this PR, please file a git issue to track it.

Comment (sivarv) [inline src/jit/lowerxarch.cpp]: What if we have op1 is CNS_INT and op2 is a byte type? the above condition will not handle it?

Comment (sivarv) [inline src/jit/lowerxarch.cpp]: >       (varTypeIsByte(t [](start = 2, length = 23)

Please update the comment block above with an example IR because of which compare condition needs to be changed.

Comment (adiaaida) [inline src/jit/lowerxarch.cpp]: Can we have that situation? Does our IR support having a constant as op1 at this point?

Comment (adiaaida) [inline src/jit/lowerxarch.cpp]: Opened #7527 for the restructure.

Comment (sivarv) [inline src/jit/lowerxarch.cpp]: I have seen one such case in the past.  AFAIK, there is nothing in our implementation that ensures that op1 is never a constant.

Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: > AFAIK, there is nothing in our implementation that ensures that op1 is never a constant.

`gtSetEvalOrder` tries to maintain this invariant, but AFAIK it is not always possible and it is not consistently checked in later phases. See https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L5208-L5219 for details.

Comment (adiaaida) [inline src/jit/lowerxarch.cpp]: Added an additional condition.

File: src/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -921,11 +921,17 @@ void Lowering::TreeNodeInfoInit(GenTree* tree)
...
+    //
     // Though this looks conservative in theory, in practice we could not think of a case where
     // the below logic leads to conservative register specification.  In future when or if we find
     // one such case, this logic needs to be fine tuned for that case(s).
     if (varTypeIsByte(tree) || ((tree->OperGet() == GT_CAST) && varTypeIsByte(tree->CastToType())) ||
-        (tree->OperIsCompare() && varTypeIsByte(tree->gtGetOp1()) && varTypeIsByte(tree->gtGetOp2())))
+        (tree->OperIsCompare() && ((varTypeIsByte(tree->gtGetOp1()) &&
+         (varTypeIsByte(tree->gtGetOp2()) || tree->gtGetOp2()->IsCnsIntOrI())) ||
+         (varTypeIsByte(tree->gtGetOp2()) && tree->gtGetOp1()->IsCnsIntOrI()))))
     {
```
Comment (briansull) [inline src/jit/lowerxarch.cpp]: Normally we use locals for op1 and op2 instead of repeatedly writing tree->gtGetOp1() and gtGetOp2()

**Comment by sivarv** [comment]
Looks good.

**Comment by briansull** [comment]
LGTM

File: src/jit/lowerxarch.cpp (hunk 2 above)
Comment (adiaaida) [inline src/jit/lowerxarch.cpp]: We have #7527 opened to restructure this code, so this won't stay around for very long.

Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: I don't really trust issues that are filed for refactoring or code cleanup. If I can't reasonably easily parse the code and understand what it's doing, it should be at least minimally restructured before checking it in.

Comment (adiaaida) [inline src/jit/lowerxarch.cpp]: @CarolEidt I separated the condition out into a separate function. PTAL.

**Comment by adiaaida** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4

File: src/jit/lowerxarch.cpp (hunk 2 above)
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: Wow - so much easier to read and understand! Thanks! I think it will also make it easier for someone to figure out what code to extract for the different opcodes, if/when we go down that road.

---
In reply to: [82696082](https://github.com/dotnet/coreclr/pull/7518#discussion_r82696082) [](ancestors = 82696082)

**Comment by CarolEidt** [comment]
:shipit:

**Comment by CarolEidt** [comment]
LGTM
