### PR TITLE
ILDAMS: Ignore Metadata flag for CoreCLR

### LINKED ISSUE #2771: ildasm fails to dump metadata from mscorlib.dll
Repro:
```
D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked>ildasm /metadata mscorlib.dll

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.22220.0


// ================================= M E T A I N F O ================================================


Assert failure(PID 10504 [0x00002908], Thread: 13988 [0x36a4]): !"Invalid GUID"

CORECLR! Disp::SetOption + 0x299 (0x00007ffe`14c00889)
ILDASM! MDInfo::MDInfo + 0xCF (0x00007ff7`a3e681e7)
ILDASM! DumpMetaInfo + 0x1F5 (0x00007ff7`a3e4ac89)
ILDASM! DumpFile + 0x669 (0x00007ff7`a3e471a5)
ILDASM! main + 0x1FC (0x00007ff7`a3e7dcdc)
ILDASM! _scrt_common_main_seh + 0x124 (0x00007ff7`a3eaf4b4)
KERNEL32! BaseThreadInitThunk + 0x22 (0x00007ffe`49d22d92)
NTDLL! RtlUserThreadStart + 0x34 (0x00007ffe`4bc29f64)
    File: d:\repos\coreclr\src\md\compiler\disp.cpp Line: 838
    Image: D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked\ildasm.exe
```

### PR DESCRIPTION
**Pull request by kyulee1**
Full metadata emission is disabled under coreclr.
So does ILDASM instead of failing during the run.

Fixes #2771

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
PR title has a typo (ILDAMS)

otherwise, LGTM

File: src/ildasm/windasm.cpp [hunk 1]
```diff
@@ -383,6 +383,9 @@ int ProcessOneArg(__in __nullterminated char* szArg, __out char** ppszObjFileNam
         }
         else if ((_stricmp(szOpt, "met") == 0)&&g_fTDC)
         {
+#ifdef FEATURE_CORECLR
+            printf("Warning: 'METADATA' option is ignored for ildasm on CoreCLR.\n");
```
Comment (pgavlin) [inline src/ildasm/windasm.cpp]: Should this be printed to `stderr`, or do we dump all warnings to `stdout`?

File: src/ildasm/windasm.cpp [hunk 2]
```diff
@@ -383,6 +383,9 @@ int ProcessOneArg(__in __nullterminated char* szArg, __out char** ppszObjFileNam
...
+#else
             if(g_fTDC)
```
Comment (sivarv) [inline src/ildasm/windasm.cpp]: A little orthogonal to what you are fixing but happened to notice.

The if check on line 389 is redundant, since the if check on line 384 means that g_fTDC is non-null already.

File: src/ildasm/windasm.cpp (hunk 1 above)
Comment (kyulee1) [inline src/ildasm/windasm.cpp]: We only use stderr for error case where we stop ilasming/ildasming.  I think  so this warning is okay with stdout as it is.

File: src/ildasm/windasm.cpp (hunk 2 above)
Comment (kyulee1) [inline src/ildasm/windasm.cpp]: Will delete the condition below.

**Comment by pgavlin** [comment]
LGTM

**Comment by sivarv** [comment]
Looks good.
