### PR TITLE
fix lvaStressLclFldCB

### LINKED ISSUE #14567: [arm64] Assertion failed '!BitVecOps::IsMember(&nodesVecTraits, uniqueNodes, gtTreeID)'
From an x64_arm64_altjit JitStress=1 run.

E.g.,
```
Assert failure(PID 17080 [0x000042b8], Thread: 17432 [0x4418]): Assertion failed '!BitVecOps::IsMember(&nodesVecTraits, uniqueNodes, gtTreeID)' in 'DoubLink.DLBigLeakThd:Main(ref):int' (IL size 190)

    File: e:\gh\coreclr2\src\jit\flowgraph.cpp Line: 21782
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```

tests:
```
GC\Scenarios\DoublinkList\dlbigleakthd\dlbigleakthd.cmd
JIT\CheckProjects\CheckProjects\CheckProjects.cmd
JIT\CodeGenBringUpTests\DivConst\DivConst.cmd
JIT\Performance\CodeQuality\BenchmarksGame\k-nucleotide\k-nucleotide-9\k-nucleotide-9.cmd
JIT\Performance\CodeQuality\BenchmarksGame\mandelbrot\mandelbrot-4\mandelbrot-4.cmd
JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd
JIT\Regression\JitBlue\DevDiv_461649\DevDiv_461649\DevDiv_461649.cmd
managed\Compilation\Compilation\Compilation.cmd
```

### PR DESCRIPTION
**Pull request by sandreenko**
Don't create trees with the same ID.

Before the transformation:
```
[000005] L------------ arg2        |  |  \--*  ADDR      byref
[000004] -------------             |  |     \--*  LCL_VAR   long   V04 loc1
```

after the transformation:
 the old version has two trees with [000005] id:
```
[000027] -------------             |  |  /--*  CNS_INT   int    4
[000005] ----G-------- arg2        |  \--*  ADD       byref
[000005] L---G--------             |     \--*  ADDR      byref
[000004] -------------             |        \--*  LCL_VAR   blk   (AX) V04 loc1
```
the new version:
```
[000027] -------------             |  |  /--*  CNS_INT   int    4
[000028] ----G-------- arg2        |  \--*  ADD       byref
[000005] L---G--------             |     \--*  ADDR      byref
[000004] -------------             |        \--*  LCL_VAR   blk   (AX) V04 loc1
```

Fix #14567 .

### CODE REVIEW

File: src/jit/lclvars.cpp [hunk 1]
```diff
@@ -7331,11 +7331,10 @@ Compiler::fgWalkResult Compiler::lvaStressLclFldCB(GenTreePtr* pTree, fgWalkData
...
-            GenTreePtr newAddr = new (pComp, GT_NONE) GenTreeOp(*tree->AsOp());
+            GenTreePtr paddingTree = pComp->gtNewIconNode(padding);
+            GenTreePtr newAddr     = pComp->gtNewOperNode(GT_ADD, tree->gtType, tree, paddingTree);
 
-            tree->ChangeOper(GT_ADD);
-            tree->gtOp.gtOp1 = newAddr;
-            tree->gtOp.gtOp2 = pComp->gtNewIconNode(padding);
+            *pTree = newAddr;
 
             lcl->gtType = TYP_BLK;
```
Comment (sandreenko) [inline src/jit/lclvars.cpp]: It is unrelated with the issue, but why do we change lclType here and do not change in the previous block `if (oper == GT_LCL_VAR)`?

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by sandreenko** [comment]
@dotnet-bot
test Windows_NT x64_arm64_altjit Checked Build and Test
test Windows_NT x86_arm_altjit Checked Build and Test
test Windows_NT x86_arm_altjit Checked jitstress1
test Windows_NT x86_arm_altjit Checked tailcallstress
test Windows_NT x64_arm64_altjit Checked jitstress1
test Windows_NT x64_arm64_altjit Checked tailcallstress

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test
