### PR TITLE
JIT: fixup finally target flag after finally opts run

### LINKED ISSUE #9015: fgRemoveEmptyFinally disabled on ARM32
The EH model on ARM requires requires predecessors to have been computed in order to sucessfully leave the bit unset for cases where there are multiple CALLFINALLY / BBJ_ALWAYS pairs that point to the same finally target.

The following example demonstrates the problem.

<pre>
-------------------------------------------------------------------------------------------------------------------------------------
BBnum descAddr ref try hnd                 weight   [IL range]      [jump]      [EH region]         [flags]
-------------------------------------------------------------------------------------------------------------------------------------
BB01 [06172A40]  1  0                           1   [000..00D)-> BB03 ( cond ) T0      try {       keep i try label
BB02 [06172AF0]  1  0                           1   [00D..00F)-> BB08 (callf ) T0                  i
BB11 [06175168]  0  0                           1   [???..???)-> BB09 (ALWAYS) T0                  i internal KEEP
BB03 [06172BA0]  1  0                           1   [00F..016)-> BB07 ( cond ) T0                  i
BB04 [06172C50]  1  0                           1   [016..022)-> BB07 ( cond ) T0                  i
BB05 [06172D00]  1  0                           1   [022..02F)-> BB07 ( cond ) T0                  i
BB06 [06172DB0]  1  0                           1   [02F..035)                 T0                  i
BB07 [06172E60]  4  0                           1   [035..037)-> BB08 (callf ) T0                  i
BB10 [06173D94]  0  0                           1   [???..???)-> BB09 (ALWAYS) T0      }           i internal KEEP
BB08 [06172F10]  1     0                        1   [037..03E)        (finret)    H0   finally { } keep i label target
BB09 [06172FC0]  2                              1   [03E..03F)        (return)                     i ftarget
-------------------------------------------------------------------------------------------------------------------------------------

***************  Exception Handling table
index  eTry, eHnd
  0  ::            - Try at BB01..BB10 [000..037), Finally at BB08..BB08 [037..03E)

EH#0 has empty finally, removing the region.
fgRemoveBlock BB11

Removing unreachable BB11
fgRemoveBlock BB10

Removing unreachable BB10
EH#0: New last block of try: BB07
</pre>

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The finally target flag can't be incrementally maintaned during finally
opts, so flag if any of these opts run and then run a post-opts fixup pass
to properly determine the flag value.

Only impacts arm targets.

Closes #9015.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib

File: src/jit/flowgraph.cpp [hunk 1]
```diff
@@ -23827,3 +23829,47 @@ void Compiler::fgCleanupContinuation(BasicBlock* continuation)
...
+            BasicBlock* const continuation = leave->bbJumpDest;
+
+            if ((continuation->bbFlags & BBF_FINALLY_TARGET) == 0)
+            {
+                JITDUMP("Found callfinally BB%02u; setting finally target bit on BB%02u\n", block->bbNum,
+                        continuation->bbNum);
+
+                continuation->bbFlags |= BBF_FINALLY_TARGET;
+            }
+        }
```
Comment (BruceForstall) [inline src/jit/flowgraph.cpp]: You could just set it unconditionally, but make the DEBUG-only JITDUMP conditional, if you only want to print once per set bit.

**Comment by BruceForstall** [comment]
LGTM

I looked at whether we could simply not mark finally targets until just prior to codegen -- after adding/removing blocks is no longer allowed -- but it's not clear we can do that, as the finally target bit is used to inhibit various optimizations that might break unwind behavior. The semantics are subtle so it's not obvious if there are other ways to achieve the same goals (easily) without the finally target bit.

**Comment by AndyAyersMS** [comment]
Yeah, I looked into late marking, but it seemed like it would require a prepass (since finally targets BBs might appear before any of the corresponding callfinallys) and also we'd have to sort through anything sensitive in between. So it seemed simpler to just fix things immediately.

**Comment by AndyAyersMS** [comment]
Unexpected failure [(log)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/2221/) that seems to be GC related:
```
11:14:23          "D:\j\workspace\debug_windows---17180f1b\tests\..\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" HandleCopy.exe 
11:14:23         Expected: 100
11:14:23         Actual: -532462766
```

@dotnet-bot retest Windows_NT x64 Debug Build and Test

**Comment by AndyAyersMS** [comment]
@gkhanna79 any way to test this more completely before merging? Trying to avoid similar issues to the ones flagged in #8989, where the builds that broke don't seem to run in CI.

**Comment by jashook** [comment]
@dotnet-bot test Windows_Arm64 debug

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 debug

**Comment by AndyAyersMS** [comment]
@dotnet-bot test Windows_NT Arm64 checked

**Comment by AndyAyersMS** [comment]
Looks like there is no checked arm64 test? Hmm. Not clear if debug will expose issues since in such builds the core library probably doesn't get optimized, and likewise, release won't have the asserts.

**Comment by AndyAyersMS** [comment]
Am going to merge this and keep an eye on things that don't seem well tested in CI.
