### PR TITLE
Fix constrained call corner cases

### LINKED ISSUE #22423: assertion failed: !pMDAfterConstraintResolution->IsInterface() in constrainedcall test
I saw this in both JitStress=1 and JitStress=2, but not without stress.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/25/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_tst_prtest/32/consoleFull

(My PR had no source code changes)

Assert failure(PID 6447 [0x0000192f], Thread: 6447 [0x192f]): !pMDAfterConstraintResolution->IsInterface()
18:01:00             File: /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/vm/jitinterface.cpp Line: 5218

Test:
```
Loader_classloader._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_sh
```

Stack fragment:
```
18:03:32 #8  0x0000ffff9f7fc414 in CEEInfo::getCallInfo (this=0xffffc33a0350, pResolvedToken=0xffffc339dcc0, pConstrainedResolvedToken=0xffffc339dc70, callerHandle=0xffff2746f730, flags=(CORINFO_CALLINFO_ALLOWINSTPARAM | CORINFO_CALLINFO_CALLVIRT | CORINFO_CALLINFO_SECURITYCHECKS), pResult=0xffffc339dda0) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/vm/jitinterface.cpp:5218
18:03:32         directMethod = 0xffff274a37a8
18:03:32         fForceUseRuntimeLookup = 0
18:03:32         pTargetMD = <optimized out>
18:03:32         pMD = <optimized out>
18:03:32         resolvedCallVirt = <optimized out>
18:03:32         directCall = <optimized out>
18:03:32         signatureKind = <optimized out>
18:03:32         pMDAfterConstraintResolution = <optimized out>
18:03:32         fResolvedConstraint = 0
18:03:32         __gcHolder = <optimized out>
18:03:32         __pThread = <optimized out>
18:03:32         CURRENT_THREAD = <optimized out>
18:03:32         CURRENT_THREAD = <optimized out>
18:03:32         __fExceptionCatched = false
18:03:32         __pThread = <optimized out>
18:03:32         __pUnCEntryFrame = <optimized out>
18:03:32         CURRENT_THREAD = <optimized out>
18:03:32 #9  0x0000ffff9cde05d8 in Compiler::eeGetCallInfo (this=<optimized out>, pResolvedToken=<optimized out>, pConstrainedToken=0x6, flags=(CORINFO_CALLINFO_ALLOWINSTPARAM | CORINFO_CALLINFO_CALLVIRT | CORINFO_CALLINFO_KINDONLY | CORINFO_CALLINFO_VERIFICATION | CORINFO_CALLINFO_LDFTN | unknown: 6400), pResult=<optimized out>) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/jit/ee_il_dll.hpp:40
18:03:32 No locals.
18:03:32 #10 Compiler::impImportBlockCode (this=<optimized out>, block=<optimized out>) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/jit/importer.cpp:14078
18:03:32         lclTyp = var_types::TYP_SHORT
18:03:32         clsFlags = 0
18:03:32         resolvedToken = <optimized out>
18:03:32         newObjThisPtr = <optimized out>
18:03:32         isLocal = true
18:03:32         mflags = 0
18:03:32         stelemClsHnd = <optimized out>
18:03:32         op1 = <optimized out>
18:03:32         uns = true
18:03:32         ldelemClsHnd = <optimized out>
18:03:32         op2 = <optimized out>
18:03:32         opcode = <optimized out>
18:03:32         clsHnd = <optimized out>
18:03:32         fieldInfo = <optimized out>
18:03:32         sz = <optimized out>
18:03:32         args = <optimized out>
18:03:32         callInfo = <optimized out>
18:03:32         nxtStmtIndex = <optimized out>
18:03:32         opcodeOffs = <optimized out>
18:03:32         lastSpillOffs = <optimized out>
18:03:32         prevOpcode = CEE_ILLEGAL
18:03:32         numArgs = <optimized out>
18:03:32         codeAddr = <optimized out>
18:03:32         prefixFlags = <optimized out>
18:03:32         codeEndp = <optimized out>
18:03:32         delegateCreateStart = <optimized out>
18:03:32         nxtStmtOffs = <optimized out>
18:03:32         jmpDist = <optimized out>
18:03:32         accessAllowedResult = <optimized out>
18:03:32         tiRetVal = <optimized out>
18:03:32         helper = <optimized out>
18:03:32         arrayNodeFrom = <optimized out>
18:03:32         arrayNodeTo = <optimized out>
18:03:32 #11 0x0000ffff9cdecb0c in Compiler::impImportBlock(BasicBlock*)::$_1::operator()(Compiler::impImportBlock(BasicBlock*)::FilterVerificationExceptionsParam*) const (this=<optimized out>, pParam=<optimized out>) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/jit/importer.cpp:17258
18:03:32 No locals.
18:03:32 #12 Compiler::impImportBlock (this=0xe920fa8, block=0xe9294b8) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/jit/importer.cpp:17268
18:03:32         __param = 0xffffc339e078
18:03:32         disposition = -1
18:03:32         baseTmp = <optimized out>
18:03:32         reimportSpillClique = <optimized out>
18:03:32         tgtBlock = <optimized out>
18:03:32 #13 0x0000ffff9cdef568 in Compiler::impImport (this=<optimized out>, method=<optimized out>) at /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04_prtest/src/jit/importer.cpp:18343
18:03:32         dsc = 0xe9295d8
18:03:32         inlineRoot = <optimized out>
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #22423. I'm still unclear on how JitStress manages to get itself into that situation, but I was able to write a repro that triggers the `!pMDAfterConstraintResolution->IsInterface()` assert using regular IL, so we need to handle that either way. The repro for that is constrained3.il.

While figuring out the repro, I wrote a bunch of other test code and found another bug (constrained2), where we would box in a situations that doesn't require boxing (canonically ambiguous situation where there's a suitable default interface implementation and a valuetype implementation of the constrained method that does not requires boxing once we no longer deal with __Canon).

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @sergiy-k

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test
@dotnet-bot test Ubuntu arm Cross Checked no_tiered_compilation_innerloop Build and Test

File: src/vm/methodtable.cpp [hunk 1]
```diff
@@ -9850,7 +9850,7 @@ MethodTable::TryResolveConstraintMethodApprox(
                 pMD = pCanonMT->GetMethodDescForInterfaceMethod(thPotentialInterfaceType, pGenInterfaceMD, FALSE /* throwOnConflict */);
 
                 // See code:#TryResolveConstraintMethodApprox_DoNotReturnParentMethod
-                if ((pMD != NULL) && !pMD->GetMethodTable()->IsValueType())
+                if ((pMD != NULL) && !pMD->GetMethodTable()->IsValueType() && !pMD->IsInterface())
```
Comment (davidwrighton) [inline src/vm/methodtable.cpp]: What happens if the method that we resolve to hear is a generic, instantiated over canon. Does this still work here?

Comment (MichalStrehovsky) [reply src/vm/methodtable.cpp]: I've added test coverage for the generic methods case, but I'm not sure I understood the concern - we strip the method instantiation before entering this code path, so the particular instantiation of the generic method shouldn't matter.

Comment (davidwrighton) [reply src/vm/methodtable.cpp]: I meant type generic. You know, the notorious case that looks like

```csharp

interface ITest<A>
{
 string M() { return "default implementation"; }
}


interface IDerivedTest<A> : ITest<A>
{
    override ITest<A>.M() { return "derived default implementation"; }
}

struct Test<X, Y> : ITest<X> : IDerivedTest<Y>
{
}

...
string SomeGenericMethod<W, Z> where W : ITest<Z>
{
    return W.M();
}

...
SomeGenericMethod<Test<object,string>, object>() -> should yield "default implementation"
and 
SomeGenericMethod<Test<object,object>, object>() -> should yield "derived default implementation"
```

Now that I think about it though, I think you've discussed already disabling this weird situation in any case, so it shouldn't matter.

Comment (MichalStrehovsky) [reply src/vm/methodtable.cpp]: Yes, this case is going to throw because it requires a "boxing stub". `constrained2.il` has a test for a similar situation (we're in a situation where the dispatch is ambiguous at compile time between an implementation provided by the value type and the default implementation), but at runtime we can call the implementation on the value type (there's also a try/catch for the "boxing stub" case that works both if the runtime does the right thing, or when it throws).

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test CentOS7.1 x64 Checked Innerloop Build and Test
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Checked Innerloop Build and Test
@dotnet-bot test Windows_NT x64 Release CoreFX Tests
