### PR TITLE
[RyuJIT] Fix assertion condition for interval of constant value in LSRA

### LINKED ISSUE #13750: [RyuJIT/arm32][JitStressRegs=1] Assertion failed 'nextAssignedRef != nullptr'
From a Windows RyuJIT/arm32 run with `COMPlus_JitStressRegs=1`:
```
Assert failure(PID 7732 [0x00001e34], Thread: 1800 [0x0708]): Assertion failed 'nextAssignedRef != nullptr' in 'testout1:Func_0():int' (IL size 24124)

    File: e:\gh\coreclr2\src\jit\lsra.cpp Line: 5868
    Image: c:\brucefo\core_root\Windows_NT.arm.Checked.2017-08-23\CoreRun.exe
```

Tests:
```
JIT\Methodical\fp\exgen\1000w1d_cs_do\1000w1d_cs_do.cmd (TEST_IDENTIFIER = Tests.lst=1000w1d_cs_do.cmd_10444)
JIT\Methodical\fp\exgen\1000w1d_cs_ro\1000w1d_cs_ro.cmd (TEST_IDENTIFIER = Tests.lst=1000w1d_cs_ro.cmd_9983)
JIT\Methodical\fp\exgen\200w1d-01_cs_do\200w1d-01_cs_do.cmd (TEST_IDENTIFIER = Tests.lst=200w1d-01_cs_do.cmd_11241)
JIT\Methodical\fp\exgen\200w1d-01_cs_ro\200w1d-01_cs_ro.cmd (TEST_IDENTIFIER = Tests.lst=200w1d-01_cs_ro.cmd_1598)
```

### PR DESCRIPTION
**Pull request by hqueue**
Fix #13750

Update condition for assertion to handle a constant interval,
because we do not free registers assigned to a constant interval as below.

https://github.com/dotnet/coreclr/blob/8342127913aa9c2dd1c17b05ea9c97c76e9be5ac/src/jit/lsra.cpp#L7634-L7650

### CODE REVIEW

**Comment by hqueue** [comment]
@CarolEidt Please take a look. And if necessary, please invoke arm64 CI, because common code for all targets is changed.

/cc: @dotnet/arm32-contrib

**Comment by hqueue** [comment]
@dotnet-bot please test Tizen armel Cross Debug Build

**Comment by CarolEidt** [comment]
It is surprising to me that we are encountering this issue now, but have not before.
- First, a `PhysRegRecord` with a constant interval assigned to it would be considered to be available, so normally it would be allocated during `tryAllocateFreeReg()` rather than being encountered in `allocateBusyReg()`.
- Second, this doesn't seem to be an abnormal situation, so I would like to understand what is special about the situation that is currently being encountered.

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -5900,6 +5900,7 @@ bool LinearScan::checkActiveInterval(Interval* interval, LsraLocation refLocatio
 {
     if (!interval->isActive)
     {
+#ifdef DEBUG
```
[the remark this answers is not in the document]
Comment (hqueue) [reply src/jit/lsra.cpp]: Right and  I just want to ease reading the code for readers :)
I will remove this after verifying the situation as you mentioned above.

**Comment by hqueue** [comment]
> It is surprising to me that we are encountering this issue now, but have not before.

@CarolEidt Yes, I also wonder why this assertion observed only in ARM32 and not in other targets. I will check your concerns.

**Comment by hqueue** [comment]
@CarolEidt  The situation is as follows.
```
---------------------------------------+-------+-------+-------+-------+
Loc   RP#    Name    Type  Action Reg  |f24    |f25    |f26    |f27    |
---------------------------------------+-------+-------+-------+-------+
                            Restr f26  |V30   a|V30   a|V32   i|C1805 i|
 4398.#6038  V32     Def    Alloc f26  |V30   a|V30   a|V32   a|C1805 i|

...(supressed)...

 4414.#6051  I1812   Def    Alloc f28  |V30   a|V30   a|V32   a|C1805 i|I1812 a|I1812 a|C1811 i|
 4415.#6052  I1812   Use *  Keep  f28  |V30   a|V30   a|V32   a|C1805 i|I1812 a|I1812 a|C1811 i|
                            Restr f28  |V30   a|V30   a|V32   a|C1805 i|V33   i|V33   i|C1811 i|
 4416.#6053  V33     Def    Alloc f28  |V30   a|V30   a|V32   a|C1805 i|V33   a|V33   a|C1811 i|
 4420.#6054  I1813   Def    Alloc f30  |V30   a|V30   a|V32   a|C1805 i|V33   a|V33   a|I1813 a|       
 4421.#6055  I1813   Use *  Keep  f30  |V30   a|V30   a|V32   a|C1805 i|V33   a|V33   a|I1813 a|       
 4422.#6056  V34     Def    Alloc f30  |V30   a|V30   a|V32   a|C1805 i|V33   a|V33   a|V34   a|       
 4426.#6057  I1814   Def
```
LSRA is going to allocate register for `Interval 1814` whose type is `TYP_DOUBLE`. (all double registers are candidate)
And `f26` is assigned to `V32`(active) and `f27` is assgined to `C1805`(inactive).


- LSRA first try to allocate register using `tryAllocateFreeReg()`
  - but it fails to because `registerIsAvailable()` return false, because `f26` is allocated to active interval. `f27` is not test, because `d13` is consist of  `f26` and `f27`.
- So LSRA tries to allocate register using `allocateBusyReg()`.
  - It tests all candidates registers by invoking  `checkActiveIntervals()` for `f26` which invoke `checkActiveInterval()` two times for `f26` and `f27`.
  - And assertion raised  when `checkActiveInterval()`  is invoked for `f27`.

Therefore it turns out that this is a ARM32 specific issue.

I will update the PR based on this analysis to reduce the change only to ARM32.

**Comment by hqueue** [comment]
@CarolEidt Please take a look. Thanks.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -5913,9 +5913,25 @@ bool LinearScan::checkActiveInterval(Interval* interval, LsraLocation refLocatio
...
                 RefPosition* nextAssignedRef = recentAssignedRef->nextRefPosition;
+#ifdef _TARGET_ARM_
+                // This function is invoked only from allocateBusyReg() through checkActiveIntervals().
+                //
+                // For ARM32, when we try to allocate a double register which consists of two float registers,
+                // tryAllocateFreeReg() may fail to allocate a double register even if one of two float
+                // reigsters is assigned to a inactive constant interval.
+                // https://github.com/dotnet/coreclr/pull/14080
+                //
+                // Therefore an inactive constant interval can be tested here.
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: This should probably be worded: "Therefore an inactive constant interval may be encountered here."
Otherwise looks good.

Comment (hqueue) [reply src/jit/lsra.cpp]: Thanks !

**Comment by hqueue** [comment]
@CarolEidt I've updated the comment as suggested. Also squashed commits.
It's ready to be merged. Thanks!

**Comment by hqueue** [comment]
@CarolEidt It's ready to be merged. Please take a look.
