### PR TITLE
Fix marshalling UTF8 string struct member from native to managed.

### LINKED ISSUE #22394: Marshal.PtrToStructure Marshals LPUTF8Str Incorrectly
When calling `Marshal.PtrToStructure` on a `struct` with a string field with a `     [MarshalAs(UnmanagedType.LPUTF8Str)]` attribute, the wrong value is read into the field.  It appears that a level of indirection is missing.  The string value marshaled into the struct is the value you get by interpreting the string's pointer value as a string instead of the value pointed to by that pointer.

Changing the marshal attribute to `[MarshalAs(UnmanagedType.LP8Str)]` works as expected (although the UTF8 string are mangled on Windows since they are decoded as ANSI).  Marshaling the structure to a pointer using with `Marshal.StructureToPtr` works as expected.

The following code reproduces the issue by marshaling the struct to pointer and showing that un-marshaling as an `LPStr` works, while `LPUTF8Str` does not, that we can read the UTF8 string manually, and that `Marshal.PtrToStructure` is reading the string pointer as the string.

```
[StructLayout(LayoutKind.Sequential)]
struct Utf8Struct {
    [MarshalAs(UnmanagedType.LPUTF8Str)]
    public string Value;
}

[StructLayout(LayoutKind.Sequential)]
struct StrStruct {
    [MarshalAs(UnmanagedType.LPStr)]
    public string Value;
}

class Program {
    static void Main() {
        var stringValue = "åäö";
        var sizeOfStruct = Marshal.SizeOf<Utf8Struct>();
        var structPtr = Marshal.AllocCoTaskMem(Marshal.SizeOf<Utf8Struct>());
        Marshal.WriteByte(structPtr + sizeOfStruct, 0);
        Marshal.StructureToPtr(new Utf8Struct {Value = stringValue}, structPtr, false);

        var utf8Struct = Marshal.PtrToStructure<Utf8Struct>(structPtr);
        var strStruct = Marshal.PtrToStructure<StrStruct>(structPtr);

        var strPtr = Marshal.ReadIntPtr(structPtr);
        var stringAsAnsi = Marshal.PtrToStringAnsi(strPtr);
        var manualUnmarshal = Marshal.PtrToStringUTF8(strPtr);
        var incorrectMarshalValue = Marshal.PtrToStringUTF8(structPtr);

        // This is True as expected
        Console.WriteLine($"MarshalAs(UnmanagedType.LPTR) was correct: {strStruct.Value == stringAsAnsi}");
         // This is False but should be True
        Console.WriteLine($"MarshalAs(UnmanagedType.LPUTF8STR) was correct: {utf8Struct.Value == stringValue}");
       // This is True as expected
        Console.WriteLine($"Manual PtrToStringUTF8 was correct: {manualUnmarshal == stringValue}");
        // This is True, but should be False
        Console.WriteLine($"MarshalAs(UnmanagedType.LPUTF8STR) read struct pointer: {utf8Struct.Value == incorrectMarshalValue}");

        Marshal.FreeCoTaskMem(structPtr);
    }
}
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #22394

### CODE REVIEW

File: src/vm/fieldmarshaler.cpp [hunk 1]
```diff
@@ -3300,7 +3300,7 @@ VOID FieldMarshaler_StringUtf8::UpdateCLRImpl(const VOID *pNativeValue, OBJECTRE
         MethodDescCallSite convertToManaged(METHOD__CUTF8MARSHALER__CONVERT_TO_MANAGED);
         ARG_SLOT args[] =
         {
-            PtrToArgSlot(pNativeValue),
+            PtrToArgSlot(sz),
```
Comment (AaronRobinsonMSFT) [inline src/vm/fieldmarshaler.cpp]: Oh boy, silly mistake. Can you do me a favor - flip the conditional and remove the `else` since `pString` is initialized to `NULL`? Thanks.

File: tests/src/Interop/StringMarshalling/UTF8/UTF8Test.cs [hunk 2]
```diff
@@ -152,6 +155,13 @@ public static void TestUTF8StructMarshalling(string[] utf8Strings)
         }
         if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
          CompareWithUTF8Encoding();
+
+        SetStringInStruct(ref utf8Struct, "StructTestString");
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/StringMarshalling/UTF8/UTF8Test.cs]: Care to embed a non-ascii character? Just so the test is really doing the right thing? Remember to use the [escaped unicode format](https://blogs.msdn.microsoft.com/csharpfaq/2004/03/12/what-character-escape-sequences-are-available/).
