### PR TITLE
Remove CoreFX runtest dependency

### LINKED ISSUE #15096: Unix Build and Test failing in CI frequently
The error is:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

The problem is that we copy the CoreFX build straight from CoreFX jobs, but the CoreFX job for CentOS is not running anymore and we get stale build (on some CI machines at least).

### PR DESCRIPTION
**Pull request by jashook**
This change will start using build-test.sh generatelayoutonly to build
the coreoverlay directory for use with runtest.sh.

Note that there are many small changes. The following are a short summary:

1. build-test.sh
    - Add a generate layout only step which will only setup the coreroot but not build tests
    - Fixes restore issues on CentOS 7, ubuntu 14.04, OSX 10.12, 10.13
2. netci.groovy
    - Use build-test.sh generate layout to setup the core_root
    - Change runtest to use coreoverlay (it no longer builds the coreoverlay).
3. runtest.sh
    - Copy all .dylib and .so dependencies for the tests **directly** into core_root instead of the tests path

This fixes #15096

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test ci please

**Comment by jashook** [comment]
Adding others who are most likely interested.

@dotnet/jit-contrib 
@janvorli

**Comment by jashook** [comment]
Note this has been tested in coreclr/dev/unix_test_workflow.

**Comment by jashook** [comment]
@dotnet-bot test Tizen armel Cross Checked Innerloop Build and Test

**Comment by jashook** [comment]
Was explained that I missed updating documentation, will update that pr with the documentation for building/testing on unix.

**Comment by jashook** [comment]
In an effort to simplify the pr I will also hoist out the python script for another change.

File: build-test.sh [hunk 1]
```diff
@@ -52,16 +55,21 @@ initTargetDistroRid()
     if [ "$__PortableBuild" == 1 ]; then
         if [ "$__BuildOS" == "Linux" ]; then
             export __DistroRid="linux-$__BuildArch"
+            export __RuntimeId="linux-$__BuildArch"
         elif [ "$__BuildOS" == "OSX" ]; then
             export __DistroRid="osx-$__BuildArch"
+            export __RuntimeId="osx-$__BuildArch"
+        elif [ "$__BuildOS" == "FreeBSD" ]; then
+            export __DistroRid="freebsd-$__BuildArch"
+            export __RuntimeId="freebsd-$__BuildArch"
```
Comment (wtgodbe) [inline build-test.sh]: Do we already have packages being published with this RID? I suspect this could cause some problems in package restore, or once we start using this in official builds.

File: build-test.sh [hunk 2]
```diff
@@ -130,29 +138,101 @@ build_Tests()
...
-    build_Tests_internal "Tests_GenerateRuntimeLayout" "${__ProjectDir}/tests/runtest.proj" "-BinPlaceRef -BinPlaceProduct -CopyCrossgenToProduct" "Restore product binaries (run tests)"
+    build_Tests_internal "Restore_FrameWork_Packages" "${__ProjectDir}/tests/build.proj" " -BatchRestorePackages" "Restore product binaries (build tests)"
 
     if [ -n "$__UpdateInvalidPackagesArg" ]; then
         __up=-updateinvalidpackageversion
     fi
 
+    echo "${__MsgPrefix}Creating test overlay..."
+
+    if [ -z "$XuintTestBinBase" ]; then
```
Comment (wtgodbe) [inline build-test.sh]: nit: ``XuintTestBinBase` should be `XunitTestBinBase`

File: build-test.sh [hunk 3]
```diff
@@ -130,29 +138,101 @@ build_Tests()
...
+
+    export CORE_ROOT=$XuintTestBinBase/Tests/Core_Root
+
+    if [ -d "${CORE_ROOT}" ]; then
+      rm -rf $CORE_ROOT
+    fi
+
+    mkdir -p $CORE_ROOT
+
+    build_Tests_internal "Tests_Overlay_Managed" "${__ProjectDir}/tests/runtest.proj" "-testOverlay" "Creating test overlay"
```
Comment (wtgodbe) [inline build-test.sh]: Are you building Core_Root against packages here, or from a locally built product?

**Comment by wtgodbe** [comment]
LGTM pending questions.

File: build-test.sh [hunk 4]
```diff
@@ -3,38 +3,41 @@
...
     fi
+
     if [ "$__HostOS" == "FreeBSD" ]; then
         __freebsd_version=`sysctl -n kern.osrelease | cut -f1 -d'.'`
         __HostDistroRid="freebsd.$__freebsd_version-$__HostArch"
     fi
 
     if [ "$__HostDistroRid" == "" ]; then
-        echo "WARNING: Cannot determine runtime id for current distro."
+        echo "WARNING: Can not determine runtime id for current distro."
```
Comment (RussKeldorph) [inline build-test.sh]: Revert: Cannot is a word and is generally preferred.

Comment (RussKeldorph) [reply build-test.sh]: I see this was probably copied from below.  Make consistent (use cannot).

File: build-test.sh [hunk 5]
```diff
@@ -588,8 +697,9 @@ export __CMakeBinDir="$__BinDir"
 
 if [ ! -d "$__BinDir" ] || [ ! -d "$__BinDir/bin" ]; then
 
-    echo "Has not been found built CoreCLR instance"
-    echo "Please build it before tests using './build.sh $__BuildArch $__BuildType'"
+    echo "Cannot find build directory for the Coreclr Product."
```
Comment (BruceForstall) [inline build-test.sh]: nit: use consistent capitalization: Coreclr => CoreCLR

File: download_tests.py [hunk 6]
```diff
@@ -0,0 +1,346 @@
+#!/usr/bin/env python
+################################################################################
+################################################################################
+#
+# Module: ci_job_diff.py
```
Comment (BruceForstall) [inline download_tests.py]: This doesn't match the file name

File: download_tests.py [hunk 7]
```diff
@@ -0,0 +1,346 @@
...
+#
+# Script to download and setup the tests on a machine. There are two main uses
+# for this script, either for use in netci or dev use. 
+# 
+# In the lab, the script requires the ability to automatically determine if 
+# there has been a change in the <CoreclrRootDir>/test/ directory.
+#
+# For dev purposes the script is assumed to be invoked only when the tests are
+# needed. Note that the script will overwrite and place the tests in the default
+# location under bin/<OS>.<Arch>.<Configruation> even if that requires deleting
```
Comment (BruceForstall) [inline download_tests.py]: typo: Configruation

File: download_tests.py [hunk 8]
```diff
@@ -0,0 +1,346 @@
...
+# the existing folder to place it there. To avoid destructive behavoir pass
```
Comment (BruceForstall) [inline download_tests.py]: typo: behavoir

File: download_tests.py [hunk 9]
```diff
@@ -0,0 +1,346 @@
...
+
+description = """Script to download and setup the tests on a machine. 
+There are two main uses for this script, either for use in netci or dev use.
+ 
+In the lab, the script requires the ability to automatically determine if 
+there has been a change in the <CoreclrRootDir>/test/ directory.
+
+For dev purposes the script is assumed to be invoked only when the tests are
+needed. Note that the script will overwrite and place the tests in the default
+location under bin/<OS>.<Arch>.<Configruation> even if that requires deleting
```
Comment (BruceForstall) [inline download_tests.py]: same typo

File: download_tests.py [hunk 10]
```diff
@@ -0,0 +1,346 @@
...
+the existing folder to place it there. To avoid destructive behavoir pass
```
Comment (BruceForstall) [inline download_tests.py]: same typo

File: download_tests.py [hunk 11]
```diff
@@ -0,0 +1,346 @@
...
+the -test_location parameter.
+"""
```
Comment (BruceForstall) [inline download_tests.py]: I'd like to see some script usage examples and explanations

File: build-test.sh (hunk 3 above)
Comment (jashook) [reply build-test.sh]: CoreCLR is locally built, needs the framework components.

File: build-test.sh [hunk 12]
```diff
@@ -3,38 +3,61 @@
...
             __HostDistroRid="$ID.$VERSION_ID-$__HostArch"
-        elif [ -e /etc/redhat-release ]; then
-            local redhatRelease=$(</etc/redhat-release)
-            if [[ $redhatRelease == "CentOS release 6."* || $redhatRelease == "Red Hat Enterprise Linux Server release 6."* ]]; then
-               __HostDistroRid="rhel.6-$__HostArch"
-            fi
-        fi
+        fi        
     fi
-    if [ "$__HostOS" == "FreeBSD" ]; then
```
Comment (janvorli) [inline build-test.sh]: The FreeBSD should stay in

File: netci.groovy [hunk 13]
```diff
@@ -2408,6 +2418,9 @@ Constants.allScenarios.each { scenario ->
 
                             // Coreclr build containing the tests and mscorlib
 
+                            def isUnixArm64 = (windowsArmJob != true) && (architecture == 'arm64')
```
Comment (janvorli) [inline netci.groovy]: I don't see this being used anywhere.

File: netci.groovy [hunk 14]
```diff
@@ -2703,7 +2693,10 @@ Constants.allScenarios.each { scenario ->
                         return
                     }
 
-                    if (windowsArmJob == true) {
+                    def isUnixArm64 = ((osGroup == "Linux") && (architecture == "arm64"))
```
Comment (janvorli) [inline netci.groovy]: This one also doesn't seem to be used anywhere.

**Comment by jashook** [comment]
Feedback should be addressed and documentation is changed to to reflect the changes.

File: Documentation/building/unix-test-instructions.md [hunk 15]
```diff
@@ -83,41 +88,54 @@ sudo apt-get install libunwind8:armhf libunwind8-dev:armhf libicu-dev:armhf libl
...
 The following instructions assume that on the Unix machine:
-- The CoreCLR repo is cloned at `~/coreclr`
-- The CoreFX repo is cloned at `~/corefx`
-- The Windows clone of the CoreCLR repo is mounted at `/media/coreclr`
+- The CoreCLR repo is cloned at `/mnt/coreclr`
 
-Tests currently need to be built on Windows and copied over to the Unix machine for testing. Copy the test build over to the Unix machine:
+If DotNet is unsupported
+- The CoreFX repo is cloned at `/mnt/corefx`
+- The other paltform's clone of the CoreCLR repo is mounted at `/media/coreclr`
```
Comment (janvorli) [inline Documentation/building/unix-test-instructions.md]: A nit - spelling: platform -> platform

**Comment by jashook** [comment]
@dotnet-bot test ci please
