### PR TITLE
GCStress: Fix a race-condition

### LINKED ISSUE #4794: GcStress: Race between background-GC and RedirectionFrame setup
Windows NT X64 GCStress 0xC failure.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_gcstress0xc/7/consoleFull

```
set CORE_ROOT=D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
21:15:06   > D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\JIT\IL_Conformance\Old\Conformance_Base\shr_u8\shr_u8.cmd
21:15:06   
21:15:06         Expected: True
21:15:06         Actual:   False
21:15:06           src\TestWrappers_x64_Checked\JIT\JIT.XUnitWrapper.cs(88149,0): at JIT._IL_Conformance_Old_Conformance_Base_shr_u8_shr_u8_._IL_Conformance_Old_Conformance_Base_shr_u8_shr_u8_cmd()
21:16:22 D:\j\workspace\x64_checked_w---cae8e941\tests\src\TestWrappers_x64_Checked\JIT\JIT.XUnitWrapper.cs(259476): error : JIT._Methodical_MDArray_DataTypes_bool_cs_do_bool_cs_do_._Methodical_MDArray_DataTypes_bool_cs_do_bool_cs_do_cmd [FAIL] [D:\j\workspace\x64_checked_w---cae8e941\tests\runtest.proj]
21:16:22         
21:16:22         Assert failure(PID 12112 [0x00002f50], Thread: 7868 [0x1ebc]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
21:16:22         
21:16:22         CORECLR! DoJITFailFast + 0x119 (0x00007ffc`d004d739)
21:16:22         CORECLR! CrawlFrame::SetCurGSCookie + 0x1A (0x00007ffc`cff29eae)
21:16:22         CORECLR! CrawlFrame::GotoNextFrame + 0x11F (0x00007ffc`cff274f3)
21:16:22         CORECLR! StackFrameIterator::NextRaw + 0xD74 (0x00007ffc`cff29350)
21:16:22         CORECLR! StackFrameIterator::Next + 0xC3 (0x00007ffc`cff2851b)
21:16:22         CORECLR! Thread::StackWalkFramesEx + 0x168 (0x00007ffc`cff2a850)
21:16:22         CORECLR! Thread::StackWalkFrames + 0x159 (0x00007ffc`cff2a651)
21:16:22         CORECLR! ScanStackRoots + 0x228 (0x00007ffc`d040c628)
21:16:22         CORECLR! GCToEEInterface::GcScanRoots + 0x1E3 (0x00007ffc`d040b947)
21:16:22         CORECLR! WKS::gc_heap::background_mark_phase + 0x12B2 (0x00007ffc`d04df696)
21:16:22             File: d:\j\workspace\x64_checked_w---cae8e941\src\vm\jithelpers.cpp Line: 5639
21:16:22             Image: D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
21:16:22         
21:16:22         cmdLine:D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\MDArray\DataTypes\bool_cs_do\bool_cs_do.cmd Timed Out
21:16:22         
21:16:22   
21:16:22   Return code:      -100
21:16:22   Raw output file:      D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Reports\JIT\Methodical\MDArray\DataTypes\bool_cs_do\bool_cs_do.output.txt
21:16:22   Raw output:
```

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
This change ensures that calls to `CORINFO_HELP_STOP_FOR_GC()` themselves
are not converted to GC-Stress traps -- thus preventing the race between
the GC thread, and a managed thread under GCStress.

Identification of calls to `CORINFO_HELP_STOP_FOR_GC()`:
Since this is a GCStress only requirement, its not worth special identification in the GcInfo
Since `CORINFO_HELP_STOP_FOR_GC()` calls are realized as indirect calls by the JIT, we cannot identify
them by address at the time of `SprinkleBreakpoints()`.
So, we actually let the `SprinkleBreakpoints()` replace the call to `CORINFO_HELP_STOP_FOR_GC()`
with a trap, and revert it back to the original instruction the first time we hit the trap in
`OnGcCoverageInterrupt()`.

Upside: No change to GCInfo or JIT is necessary
Downside: Need to decode a few bytes on every GCStress interrupt.

Local testing with `COMPlus_GCStress=0xC` and `COMPlus_GCConcurrent=1` did not encounter the race condition in #4794

Fixes #4794

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
@sergiy-k / @jkotas please review.
+CC: @RussKeldorph

File: src/vm/gccover.cpp [hunk 1]
```diff
@@ -1175,33 +1262,30 @@ BOOL OnGcCoverageInterrupt(PCONTEXT regs)
...
-    ****/
+    BYTE * savedInstrPtr = &gcCover->savedCode[offset];
+
+    // If this trap instruction is taken in place of CORINFO_HELP_STOP_FOR_GC()
+    // Do not start a GC, but continue with the original instruction.
+    // See the comments above SprinkleBreakpoints() function.
+    SLOT nextInstr;
+    SLOT target = getTargetOfCall(savedInstrPtr, regs, &nextInstr);
+
+    if (target == (SLOT)JIT_RareDisableHelper) {
```
Comment (jkotas) [inline src/vm/gccover.cpp]: Instead of doing all this call target decoding, would it be better to just check whether we are in preemptive mode?

The call target decoding will need ongoing tweaks, e.g. I hope to add support for interop transitions for ReadyToRun (based on `CORJIT_FLG2_USE_PINVOKE_HELPERS`) - that will use a different helper.

**Comment by jkotas** [comment]
Can we also delete `m_fPreemptiveGCDisabledForGCStress` now? It solving the same problem - it should be unnecessary now with this fix.

File: src/vm/gccover.cpp (hunk 1 above)
Comment (swaroop-sridhar) [inline src/vm/gccover.cpp]: I just spoke with @jkotas.
The check for PremptiveMode will not work, because when returning from a PInvoke epilog, the thread is already in cooperative mode.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot  test Windows_NT x64 Checked gcstress0xc

**Comment by swaroop-sridhar** [comment]
@dotnet-bot  test Windows_NT Checked arm64

**Comment by swaroop-sridhar** [comment]
The latest commit is to fix an X86 build break, by fixing an `extern "C" ` declaration here: https://github.com/dotnet/coreclr/pull/5356/files#diff-4cbc7cebee869048dc921baad12c9240R420

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT x64 Checked gcstress0xc

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT Checked arm64

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT Checked arm

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT Checked x64  gcstress0xc

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT arm64 Checked

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT arm Checked

**Comment by swaroop-sridhar** [comment]
@jkotas: Checking if you had any more corrections.
Most of the testing has passed. The GCStress leg is still running, and hasn't hit the race.

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows_NT gcstress0xc

**Comment by swaroop-sridhar** [comment]
The failures in GCStress are pres-existing / timeouts.

**Comment by jkotas** [comment]
LGTM

**Comment by swaroop-sridhar** [comment]
Looks like this change also fixes https://github.com/dotnet/coreclr/issues/5310 and https://github.com/dotnet/coreclr/issues/2785
