### PR TITLE
Fix localloc with large out arg space

### LINKED ISSUE #23915: localloc + outgoing argument space stack probing hole
This doesn't apply to Windows x86; it only applies to `FEATURE_FIXED_OUT_ARGS` targets (arm32, arm64, x64).

The implementation for localloc codegen in the JIT, in `genLclHeap`, first removes the outgoing argument space from the stack, then probes and allocates the localloc space, then adds back the outgoing argument space at the bottom of the stack. When it re-establishes the outgoing argument space (by subtracting the outgoing argument space size from the stack pointer after doing the localloc), it does not do any stack probes. If the next stack touch is at the bottom of the stack, and if the outgoing argument space is larger than the number of guard pages, we could hit an AV.

This is very difficult to achieve on x64/arm64, since their calling conventions (which determine the outgoing argument space size) mostly pass stucts by reference. Arm32, however, passes structs by value. In addition, the CLR (on Windows) uses the `SetThreadStackGuarantee` API to expand the number of guard pages. For example, I saw 6 in my DEBUG Windows x64 test case.

### PR DESCRIPTION
**Pull request by BruceForstall**
Add stack probing in localloc with fixed outgoing arg frames

The SP adjustment when we re-establish the outgoing argument
space after doing a localloc must be probed. This is true for
all architectures with fixed outgoing argument space, namely,
everything but x86.

Add new tests for this.

Fixes #23915

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked pmi_asm_diffs
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86 Checked pmi_asm_diffs

**Comment by BruceForstall** [comment]
arm32 diffs show a surprising number of cases in S.P.C.dll of small, constant-sized localloc, where previously we could have merged the outgoing arg space re-establishment into the localloc SP adjustment, e.g.:
```
            sub     sp, 64
            sub     sp, sp, 32
```
now we generate a probe with the outgoing args re-establishment:
```
            sub     sp, 64
            ldr     r0, [sp]
            sub     sp, 32
```
there is actually no code size increase because apparently we were previously using a sub-optimal 32-bit encoding and now we use a 16-bit encoding. For the constant case, we could/should optimize/merge the two SP adjustments and probes, but that can be done later.

On the plus side, the skippage6 and skippage7 tests no longer assert.

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked pmi_asm_diffs
@dotnet-bot test Ubuntu16.04 arm64 Cross Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86 Checked pmi_asm_diffs

**Comment by BruceForstall** [comment]
x64 pmi diffs:
```
12:20:27 Total bytes of diff: 201 (0.00 % of base)
12:20:27     diff is a regression.
12:20:27 
12:20:27 Top file regressions by size (bytes):
12:20:27           48 : System.Private.CoreLib.dasm (0.00 % of base)
12:20:27           33 : System.Security.Cryptography.Algorithms.dasm (0.01 % of base)
12:20:27           30 : System.Security.Cryptography.Cng.dasm (0.02 % of base)
12:20:27           18 : System.Security.Cryptography.X509Certificates.dasm (0.01 % of base)
12:20:27           15 : System.Runtime.Numerics.dasm (0.02 % of base)
12:20:27 
12:20:27 12 total files with size differences (0 improved, 12 regressed), 117 unchanged.
12:20:28 
12:20:28 Top method regressions by size (bytes):
12:20:28           12 (0.41 % of base) : System.Security.Cryptography.Algorithms.dasm - System.Security.Cryptography.Pkcs.Pkcs12Kdf:Derive(struct,struct,int,ubyte,struct,struct)
12:20:28           12 (0.41 % of base) : System.Security.Cryptography.Cng.dasm - System.Security.Cryptography.Pkcs.Pkcs12Kdf:Derive(struct,struct,int,ubyte,struct,struct)
12:20:28            9 (0.58 % of base) : System.Private.CoreLib.dasm - System.Diagnostics.Tracing.EventSource:WriteMultiMergeInner(ref,byref,ref,long,long,ref):this
12:20:28            9 (0.36 % of base) : System.Private.CoreLib.dasm - System.Diagnostics.Tracing.EventSource:WriteImpl(ref,byref,ref,long,long,ref):this
12:20:28            9 (0.56 % of base) : System.Runtime.Numerics.dasm - System.Numerics.BigIntegerCalculator:Multiply(long,int,long,int,long,int)
12:20:28 
12:20:28 Top method regressions by size (percentage):
12:20:28            3 (1.53 % of base) : System.Security.Cryptography.Algorithms.dasm - System.Security.Cryptography.CngPkcs8:FillRandomAsciiString(struct)
12:20:28            3 (1.53 % of base) : System.Security.Cryptography.Cng.dasm - System.Security.Cryptography.CngPkcs8:FillRandomAsciiString(struct)
12:20:28            3 (1.01 % of base) : System.Private.CoreLib.dasm - System.StubHelpers.AnsiCharMarshaler:ConvertToNative(ushort,bool,bool):ubyte
12:20:28            3 (0.86 % of base) : System.Diagnostics.DiagnosticSource.dasm - System.Diagnostics.ActivityTraceId:SpanToHexString(struct):ref
12:20:28            3 (0.84 % of base) : System.Security.Cryptography.X509Certificates.dasm - Internal.Cryptography.Pal.Native.Helpers:DecodeObjectNoThrow(ref,int,ref):bool
12:20:28 
12:20:28 49 total methods with size differences (0 improved, 49 regressed), 247829 unchanged.
```

This is all additional probes before re-establishing outgoing arg space after dynamic localloc.

**Comment by BruceForstall** [comment]
arm crossgen diffs:
```
Crossgen Diffs for System.Private.CoreLib.dll for x86 protononjit.dll
Summary:
(Lower is better)
Total bytes of diff: -200 (0.00% of base)
    diff is an improvement.
Top file improvements by size (bytes):
        -200 : System.Private.CoreLib.dasm (0.00% of base)
1 total files with size differences (1 improved, 0 regressed), 0 unchanged.
Top method improvements by size (bytes):
         -12 (-0.65% of base) : System.Private.CoreLib.dasm - System.Environment:get_UserDomainName():ref (2 methods)
          -8 (-0.28% of base) : System.Private.CoreLib.dasm - System.String:SplitInternal(ref,ref,int,int):ref:this (2 methods)
          -8 (-0.09% of base) : System.Private.CoreLib.dasm - System.Buffers.Text.Utf8Parser:TryParse(struct,byref,byref,ushort):bool (32 methods)
          -4 (-0.22% of base) : System.Private.CoreLib.dasm - Kernel32:GetMessage(int,int):ref (2 methods)
          -4 (-0.45% of base) : System.Private.CoreLib.dasm - MemberInfoCache`1[__Canon][System.__Canon]:Populate(ref,int,int):ref:this (2 methods)
Top method improvements by size (percentage):
          -4 (-1.05% of base) : System.Private.CoreLib.dasm - System.Diagnostics.Tracing.EventSource:WriteEvent(int,int,int,int):this (2 methods)
          -4 (-1.05% of base) : System.Private.CoreLib.dasm - System.Diagnostics.Tracing.EventSource:WriteEvent(int,long,long,long):this (2 methods)
          -4 (-1.01% of base) : System.Private.CoreLib.dasm - System.Buffers.ArrayPoolEventSource:BufferRented(int,int,int,int):this (2 methods)
          -4 (-0.91% of base) : System.Private.CoreLib.dasm - System.Buffers.ArrayPoolEventSource:BufferAllocated(int,int,int,int,int):this (2 methods)
          -4 (-0.82% of base) : System.Private.CoreLib.dasm - System.Diagnostics.Tracing.EventSource:WriteEvent(int,ref,int,int):this (2 methods)
46 total methods with size differences (46 improved, 0 regressed), 25849 unchanged.
```

Note that arm32/arm64 PMI diffs are pretty useless because there are so many spurious diffs due to constant encoding changes.

**Comment by BruceForstall** [comment]
The musl failures are all infrastructure.

**Comment by BruceForstall** [comment]
@briansull PTAL
cc @dotnet/jit-contrib

File: src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -22,6 +22,91 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
...
+// Return Value:
+//    None.
+//
+void CodeGen::genStackPointerConstantAdjustment(ssize_t spDelta)
+{
+    assert(spDelta < 0);
+
+    // We assert that the SP change is less than one page. If it's greater, you should have called a
+    // function that does a probe, which will in turn call this function.
+    assert((target_size_t)(-spDelta) <= compiler->eeGetPageSize());
```
Comment (CarolEidt) [inline src/jit/codegenarmarch.cpp]: How does this assert not fire when it is called by `genStackPointerConstantAdjustmentLoopWithProbe`?

File: src/jit/codegenxarch.cpp [hunk 2]
```diff
@@ -2687,18 +2712,19 @@ void CodeGen::genLclHeap(GenTree* tree)
             {
                 inst_IV(INS_push_hide, 0); // push_hide means don't track the stack
             }
+
+            lastTouchDelta = 0;
+
             goto ALLOC_DONE;
         }
 
         bool doNoInitLessThanOnePageAlloc =
```
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: I realize that this is pre-existing, but this negative name makes the negation of it below even more confusing than this already is. Also, could you add a comment to this? Is it intended to be "doNot" rather than "doNo"?

File: src/jit/lsraarm.cpp [hunk 3]
```diff
@@ -41,6 +41,9 @@ int LinearScan::BuildLclHeap(GenTree* tree)
     //   >4 ptr words               Yes             1
     //   Non-const                  Yes             1
     //   Non-const                  No              1
+    //
+    // If the outgoing argument space is too large to encode in an "add/sub sp, icon"
+    // instruction, we also need a temp (which can be shared).
```
Comment (CarolEidt) [inline src/jit/lsraarm.cpp]: I'm not sure what it means to be shared. The internal registers are only live within the code generation for this single node.

File: src/jit/codegen.h [hunk 4]
```diff
@@ -1211,11 +1216,21 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
...
     void genReturn(GenTree* treeNode);
 
+    // clang-format off
+    void genStackPointerConstantAdjustment(ssize_t spDelta
+                                           X86_ARG(bool hideSpChangeFromEmitter)
+                                           X86_ARG(regNumber regTmp));
+    void genStackPointerConstantAdjustmentWithProbe(ssize_t spDelta
+                                                    ARM_ARG(regNumber regTmp)
+                                                    X86_ARG(bool hideSpChangeFromEmitter)
+                                                    X86_ARG(regNumber regTmp));
```
Comment (briansull) [inline src/jit/codegen.h]: Ugg...  optional arguments
At least reorder the optional args so that `hideSpChangeFromEmitter `always comes last. 
Also it seems we could just normal arguments and pass `REG_ZR `on ARM64 and `REG_NA `on X64.
You could eliminate `hideSpChangeFromEmitter`, by making it the default when regTmp is specified.
I''m pretty sure the optimizer would eliminate any extra overhead from these arguments

File: src/jit/codegenarmarch.cpp [hunk 5]
```diff
@@ -22,6 +22,91 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
...
+//    spDelta                 - the value to add to SP. Must be negative or zero. If zero, the probe happens,
+//                              but the stack pointer doesn't move.
+//    regTmp                  - arm32 only: temporary register to use as target for probe load instruction
+//
+// Return Value:
+//    None.
+//
+void CodeGen::genStackPointerConstantAdjustmentWithProbe(ssize_t spDelta ARM_ARG(regNumber regTmp))
+{
+    getEmitter()->emitIns_R_R_I(INS_ldr, EA_4BYTE ARM_ARG(regTmp) ARM64_ARG(REG_ZR), REG_SP, 0);
```
Comment (briansull) [inline src/jit/codegenarmarch.cpp]: typing `ARM_ARG(regTmp) ARM64_ARG(REG_ZR)` here is a very tricky way to pass a single argument...

File: src/jit/codegen.h [hunk 6]
```diff
@@ -317,6 +317,11 @@ class CodeGen : public CodeGenInterface
 
 #if defined(_TARGET_ARM_)
 
+    bool genInstrWithConstant(
+        instruction ins, emitAttr attr, regNumber reg1, regNumber reg2, ssize_t imm, insFlags flags, regNumber tmpReg);
```
[the remark this answers is not in the document]
Comment (BruceForstall) [reply src/jit/codegen.h]: It does the same thing as an arm64 version, but in that case we actually need to know if we're generating unwind codes or not, which doesn't seem like it should be in the emitter. Also, both of them will possibly use an additional register. In some cases for arm32, mostly for loads/stores of locals, the emitter functions automatically use the reserved register, and pre-codegen is required to allocate the reserved register if necessary. That seems pretty tenuous; it seems better to pass in a temp register if it might be needed. It's possible the related emitter functions should take one. But it kind of seems like this is "higher level", and the emitter functions should generate exactly one instruction.

File: src/jit/codegenarm.cpp [hunk 7]
```diff
@@ -271,11 +361,13 @@ void CodeGen::genLclHeap(GenTree* tree)
...
-    emitAttr    easz            = emitTypeSize(type);
-    BasicBlock* endLabel        = nullptr;
-    unsigned    stackAdjustment = 0;
+    regNumber      regCnt          = tree->gtRegNum;
+    var_types      type            = genActualType(size->gtType);
+    emitAttr       easz            = emitTypeSize(type);
+    BasicBlock*    endLabel        = nullptr;
+    unsigned       stackAdjustment = 0;
+    regNumber      regTmp          = REG_NA;
+    target_ssize_t lastTouchDelta  = (target_ssize_t)-1;
```
[the remark this answers is not in the document]
Comment (BruceForstall) [reply src/jit/codegenarm.cpp]: Done.

File: src/jit/codegenarm.cpp [hunk 8]
```diff
@@ -453,19 +555,33 @@ void CodeGen::genLclHeap(GenTree* tree)
...
+
+        // lastTouchDelta is dynamic, and can be up to a page. So if we have outgoing arg space,
+        // we're going to assume the worst and probe.
     }
 
 ALLOC_DONE:
-    // Re-adjust SP to allocate out-going arg area
-    if (stackAdjustment != 0)
+    // Re-adjust SP to allocate outgoing arg area. We must probe this adjustment.
+    if (stackAdjustment > 0)
```
[the remark this answers is not in the document]
Comment (BruceForstall) [reply src/jit/codegenarm.cpp]: I guess I thought it was clearer. I'll change it back.

File: src/jit/codegenarmarch.cpp (hunk 1 above)
Comment (BruceForstall) [reply src/jit/codegenarmarch.cpp]: The "loop with probe" function breaks up the probes into pageSize chunks, so a SP change is never more than one page when this is called.

File: src/jit/codegenxarch.cpp (hunk 2 above)
Comment (BruceForstall) [reply src/jit/codegenxarch.cpp]: It's supposed to be parsed "do" "no-init", as in "we don't need to zero init the allocated memory". I'll reverse the condition and name it "initMemOrLargeAlloc"

File: src/jit/lsraarm.cpp (hunk 3 above)
Comment (BruceForstall) [reply src/jit/lsraarm.cpp]: This single node generates a lot of code, and there are multiple conditions that require a temp register. This is just to say that there we can use the same temp register if there are multiple conditions that require one. I'll clarify the comment.

File: src/jit/codegen.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (CarolEidt) [reply src/jit/codegen.h]: OK, thanks for the explanation

File: src/jit/codegen.h (hunk 4 above)
Comment (BruceForstall) [reply src/jit/codegen.h]: I guess I don't share your distaste for optional arguments, if the alternative is either `#ifdef` or arguments that are not used on a platform (e.g., arm64, x64 here).

> You could eliminate hideSpChangeFromEmitter, by making it the default when regTmp is specified.

I could. The semantic seems a little circuitous: "why would a register imply hiding the SP change?" would be my thinking. Also, it's a hack: we should just fix the emitter to hide the change directly, without requiring a register.

File: src/jit/codegenarmarch.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/codegenarmarch.cpp]: Ah yes, I see that described a bit further down. It's just a bit confusing because the function that's calling this one isn't actually the one that breaks it up.

File: src/jit/codegenxarch.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/codegenxarch.cpp]: I think that would be clearer, thanks.

File: src/jit/lsraarm.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/jit/lsraarm.cpp]: Great, thanks.

File: src/jit/codegen.h (hunk 4 above)
Comment (briansull) [reply src/jit/codegen.h]: There is no real cost for:

" arguments that are not used on a platform (e.g., arm64, x64 here)."

as the optimizer can inline and eliminate them.

Comment (BruceForstall) [reply src/jit/codegen.h]: > as the optimizer can inline and eliminate them.

My concern isn't the runtime overhead of extra arguments, it's the programmer's mental overhead of seeing things that aren't used on a particular platform. If I see an argument, I expect it to be needed and used. If it's not, that's annoying and possibly confusing. I think the existence of unnecessary arguments is worse than platform-specific function signatures.

Comment (briansull) [reply src/jit/codegen.h]: I still think that we can get rid of these (horrible) optional args and just always pass regTmp.

And pass REG_NA or REG_ZR when they are not really needed.  IMO that isn't confusing to the  programmer's mental model.  We already do that all over the pass, rather than overload a method with different number of args.

**Comment by BruceForstall** [comment]
@briansull I updated the code to avoid per-arch function arguments. How does this look to you?
