### PR TITLE
ARM64: Enable Fast Tail Call

### LINKED ISSUE #4420: ARM64: StackOverflowException.
JIT\Directed\tailcall\tailcall
JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271
```
Process is terminated due to StackOverflowException.
```

### PR DESCRIPTION
**Pull request by kyulee1**
Fixes #4420
Like x64, enable fast tail call but tail call opt is still off.
This means explicit tail call is converted to epilog + jmp IP0.
Tail call recursive/tail call via helper is still not enabled yet.

### CODE REVIEW

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

**Comment by kyulee1** [comment]
@dotnet/jit-contrib @dotnet/arm64-contrib PTAL

File: src/jit/compiler.hpp [hunk 1]
```diff
@@ -632,7 +632,7 @@ bool                isRegParamType(var_types type)
 #endif // !_TARGET_X86_
 }
 
-#ifdef _TARGET_AMD64_
+#if defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)
```
Comment (sivarv) [inline src/jit/compiler.hpp]: This method doesn't seem to be handling the case of 16-byte struct passed in two argument registers.  For an example see x64 unix logic in this routine.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -6217,7 +6217,7 @@ bool                Compiler::fgCanFastTailCall(GenTreeCall* callee)
             // Get the size of the struct and see if it is register passable.
             if (argx->OperGet() == GT_OBJ)
             {
-#ifdef _TARGET_AMD64_
+#if defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)
```
Comment (sivarv) [inline src/jit/morph.cpp]: See x64 unix logic that applies to arm64 as well.  The callee method could have a 16-byte struct param that should be counted as two 8-byte slots.

File: src/jit/codegenarm64.cpp [hunk 3]
```diff
@@ -9396,6 +9388,38 @@ void                CodeGen::genArm64EmitterUnitTests()
...
+// getFirstArgWithStackSlot - returns the first argument with stack slot on the caller's frame.
+//
+// Return value:
+//    The number of the first argument with stack slot on the caller's frame.
+
+unsigned
+CodeGen::getFirstArgWithStackSlot()
+{
+    // Iterate over all the local variables in the lclvartable.
+    // They contain all the implicit argumets - thisPtr, retBuf,
```
Comment (sivarv) [inline src/jit/codegenarm64.cpp]: misspelled "argumets"

File: src/jit/codegenarm64.cpp [hunk 4]
```diff
@@ -9396,6 +9388,38 @@ void                CodeGen::genArm64EmitterUnitTests()
...
+    // generic context, PInvoke cookie, var arg cookie,no-standard args, etc.
+    unsigned baseVarNum = 0;
+    LclVarDsc* varDsc = nullptr;
+    for (unsigned i = 0; i < compiler->lvaCount; i++)
```
Comment (sivarv) [inline src/jit/codegenarm64.cpp]: lvaCount would imply that we would iterate over all lcl vars both params and locals.  To just iterate only over arguments/params use compiler->info.compArgsCount

During testing didn't the assert on line 9411 fire?

Comment (sivarv) [inline src/jit/codegenarm64.cpp]: I see the same bug is present in xarch version of getFirstArgWithStackSlot.  It would be great if you can fix it as well.

Comment (sivarv) [inline src/jit/codegenarm64.cpp]: I see the implementation of this routine is same as x64 unix.  How about moving this routine to codegencommon.cpp and enabling x64 unix implementation for Arm64?

File: src/jit/codegencommon.cpp [hunk 5]
```diff
@@ -9530,6 +9542,15 @@ void                CodeGen::genFnEpilog(BasicBlock* block)
                 BAD_IL_OFFSET, REG_NA, REG_NA, 0, 0, /* iloffset, ireg, xreg, xmul, disp */
                 true);                     /* isJump */
         }
+#if FEATURE_FASTTAILCALL
+        else
+        {
+            // Fast tail call.
+            // Call target = REG_IP0.
+            // TODO: Do we need a special encoding for stack walker like rex.w prefix for x64?
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: Please file a Git issue to track this TODO. I think to support fast tail calls VM side support might be needed. It would be good to track that work with an issue.

File: src/jit/codegenarm64.cpp [hunk 6]
```diff
@@ -9396,6 +9388,38 @@ void                CodeGen::genArm64EmitterUnitTests()
...
+    {
+        varDsc = &(compiler->lvaTable[i]);
+
+        // We are iterating over the arguments only.
+        assert(varDsc->lvIsParam);
+
+        if (varDsc->lvArgReg == REG_STK)
```
Comment (sivarv) [inline src/jit/codegenarm64.cpp]: The reason why assert on line 9411 wasn't fired thought we used lvaCount as loop limit is that this routine was called while generating code for GT_PUTARG_STK and that by that time fast tail call logic has established that caller method also has a stack arg (and hence tail call possible).  Since caller method is guaranteed to have at least one arg passed on stack, within 0 to compiler->info.compArgsCount, the above loop will find such an arg.

On the other hand if the above routine was called in any other context could lead to an assert.

**Comment by kyulee1** [comment]
@dotnet-bot test Windows_NT arm64 Checked
@dotnet-bot test Windows_NT arm64 Release

File: src/jit/morph.cpp (hunk 2 above)
Comment (kyulee1) [inline src/jit/morph.cpp]: Yes. I added the logic like unix struct below

File: src/jit/compiler.hpp (hunk 1 above)
Comment (kyulee1) [inline src/jit/compiler.hpp]: My understanding is `argOrReturnTypeForStruct` handles arm64 for multi-reg case.

**Comment by kyulee1** [comment]
Updated the change per feedback and verified the tests. PTAL again.

File: src/jit/codegencommon.cpp [hunk 7]
```diff
@@ -11532,6 +11554,72 @@ instruction CodeGen::genMapShiftInsToShiftByConstantIns(instruction ins, int shi
...
+
+//------------------------------------------------------------------------------------------------ //
+// getFirstArgWithStackSlot - returns the first argument with stack slot on the caller's frame.
+//
+// Return value:
+//    The number of the first argument with stack slot on the caller's frame.
+//
+// Note:
+//    On x64 Windows the caller always creates slots (homing space) in its frame for the
+//    first 4 arguments of a calee (register passed args). So, the the variable number
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: Misspelled "calee"

File: src/jit/morph.cpp [hunk 8]
```diff
@@ -6217,13 +6217,13 @@ bool                Compiler::fgCanFastTailCall(GenTreeCall* callee)
...
 
                 unsigned typeSize = 0;
                 hasMultiByteArgs = !VarTypeIsMultiByteAndCanEnreg(argx->TypeGet(), argx->gtObj.gtClass, &typeSize, false);
 
-#if defined(FEATURE_UNIX_AMD64_STRUCT_PASSING)
-                // On System V the args could be a 2 eightbyte struct that is passed in two registers.
+#if defined(FEATURE_UNIX_AMD64_STRUCT_PASSING) || defined(_TARGET_ARM64_)
+                // On System V/arm64 the args could be a 2 eightbyte struct that is passed in two registers.
                 // Account for the second eightbyte in the nCalleeArgs.
                 // TODO-CQ-Amd64-Unix:  Structs of size between 9 to 16 bytes are conservatively estimated
```
Comment (sivarv) [inline src/jit/morph.cpp]: Please add a separate TODO-CQ-ARM64:

I think there is a GIT issue tracking this issue for x64 Unix.  Please update it to include Arm64 as well.

**Comment by sivarv** [comment]
Looks good.

File: src/jit/codegencommon.cpp [hunk 9]
```diff
@@ -11532,6 +11554,72 @@ instruction CodeGen::genMapShiftInsToShiftByConstantIns(instruction ins, int shi
...
+    baseVarNum = compiler->lvaFirstStackIncomingArgNum;
+
+    if (compiler->lvaFirstStackIncomingArgNum != BAD_VAR_NUM)
+    {
+        baseVarNum = compiler->lvaFirstStackIncomingArgNum;
+    }
+    else
+#endif // FEATURE_UNIX_ARM64_STRUCT_PASSING
+    {
+        // Iterate over all the local variables in the lclvartable.
```
Comment (sivarv) [inline src/jit/codegencommon.cpp]: (Minor typo) Lcl var table instead of "lclvartable"

File: src/jit/morph.cpp (hunk 8 above)
Comment (kyulee1) [inline src/jit/morph.cpp]: I tried to search it, but couldn't find a right one.
@LLITCHEV I think the code is introduced by https://github.com/dotnet/coreclr/pull/1906
Did you ever create an issue for that?
And also I'm not sure why using two registers for the size of 9 to 16 is an issue and what other optimization opportunity remains.

File: src/jit/codegencommon.cpp (hunk 7 above)
Comment (kyulee1) [inline src/jit/codegencommon.cpp]: Will fix on merge.

File: src/jit/codegencommon.cpp (hunk 9 above)
Comment (kyulee1) [inline src/jit/codegencommon.cpp]: Will fix on merge.

File: src/jit/morph.cpp (hunk 8 above)
Comment (sivarv) [inline src/jit/morph.cpp]: I have created the following git issue for it #2666
https://github.com/dotnet/coreclr/issues/2666

Comment (kyulee1) [inline src/jit/morph.cpp]: Thanks for the point. Will update it.
