### PR TITLE
Fix consume-order checking in codegen.

### LINKED ISSUE #7963: Ensure that codegen consumes registers in the proper order
(This was the original description of this issue, when it was opened; see below)
When reversing the GT_FIELD_LIST for pushing the fields onto the stack, we will, as a result, consume them in the wrong order, relative to their execution order. This is generally benign (and doesn't cause an assert, but instead causes "consumed in the wrong order" messages in a jitdump), but could result in problems with GC encoding if we have copy-propagated two GC ref fields to be the same lclVar. I was going to address this with the fix for DevDiv bug 278375, but I would like to create a repro first, and in the meantime I want to get that one fixed. It could potentially be fixed either by reversing the nodes in the execution order (not just in the list) - this should rarely (never?) require new temps because these are fields of promoted structs that shouldn't have side-effects. However, another alternative would be to first consume all the list entries, in original order, and then generate the code.

### PR DESCRIPTION
**Pull request by pgavlin**
The switch to LIR invalidated the correspondence between a node's
sequence number and the order in which it must be consumed with respect
to other nodes. This in turn made the consume-order checks during code
generation incorrect.

This change introduces a new field, `gtUseNum`, that is used during code
generation to check the order in which nodes are consumed. Re-enabling
these checks revealed a bug in code generation for locked instructions
on x86, which were consuming their operands out-of-order; this change
also contains a fix for that bug.

Fixes #7963.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/codegenlinear.cpp [hunk 1]
```diff
@@ -335,6 +328,25 @@ void CodeGen::genCodeForBBlist()
...
+            for (GenTree* node : LIR::AsRange(block).NonPhiNodes())
+            {
+                assert((node->gtDebugFlags & GTF_DEBUG_NODE_CG_CONSUMED) == 0);
+
+                node->gtUseNum = -1;
+                for (GenTree* operand : node->Operands())
+                {
+                    assert(operand->gtUseNum == -1);
+                    operand->gtUseNum = useNum;
+                    useNum++;
```
Comment (pgavlin) [inline src/jit/codegenlinear.cpp]: Although this works, we may want to set these use numbers during LSRA's traversal of a node's operands to help ensure that the correspondence between a node's use number and the relative order in which it is visited by LSRA is correct. Thoughts?

Comment (CarolEidt) [inline src/jit/codegenlinear.cpp]: This seems like a reasonable approach. If one were to get fancy, one could maintain the `LsraLocation` at which it is consumed, along with its operand index - but that would be more info than is needed here (though possibly handy for debugging purposes!)

File: src/jit/codegenlinear.cpp [hunk 2]
```diff
@@ -1031,34 +1046,55 @@ void CodeGen::genConsumeRegAndCopy(GenTree* node, regNumber needReg)
...
+        else if ((lastConsumedNode != nullptr) && (node->gtUseNum < lastConsumedNode->gtUseNum))
+        {
+            printf("Nodes were consumed out-of-order:\n");
+            compiler->gtDispTree(lastConsumedNode, nullptr, nullptr, true);
+            compiler->gtDispTree(node, nullptr, nullptr, true);
         }
-        lastConsumedNode = treeNode;
     }
+
+    assert((node->OperGet() == GT_CATCH_ARG) || ((node->gtDebugFlags & GTF_DEBUG_NODE_CG_CONSUMED) == 0));
```
Comment (CarolEidt) [inline src/jit/codegenlinear.cpp]: I don't know - I'm not very familiar with the code for `GT_CATCH_ARG` but in general we shouldn't be consuming the current node in `genCodeForTreeNode`

Comment (BruceForstall) [inline src/jit/codegenlinear.cpp]: Don't know...

---
In reply to: [92242247](https://github.com/dotnet/coreclr/pull/8601#discussion_r92242247) [](ancestors = 92242247)

**Comment by pgavlin** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build
