### PR TITLE
Fix another overly agressive assert

### LINKED ISSUE #14732: [RyuJIT/x86][JitStressRegs=8] Assertion failed '!nextRefPosition->RequiresRegister()'
This is similar to #14624. It is an overly aggressive assert that needs to be loosened when the register candidates have been constrained for stress testing.
It appeared in the ARM altjit stress testing, but is actually an x86 failure.

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #14732

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -6444,42 +6444,50 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
-            Interval* assignedInterval =
-                (farthestRefPhysRegRecord == nullptr) ? nullptr : farthestRefPhysRegRecord->assignedInterval;
-            Interval* assignedInterval2 =
-                (farthestRefPhysRegRecord2 == nullptr) ? nullptr : farthestRefPhysRegRecord2->assignedInterval;
-            RefPosition* nextRefPosition =
-                (assignedInterval == nullptr) ? nullptr : assignedInterval->getNextRefPosition();
-            RefPosition* nextRefPosition2 =
-                (assignedInterval2 == nullptr) ? nullptr : assignedInterval2->getNextRefPosition();
-            if (nextRefPosition != nullptr)
+            // This must be a RefPosition that is constrained to use a snigle register, either directly,
```
Comment (BruceForstall) [inline src/jit/lsra.cpp]: typo: snigle
