### PR TITLE
[RyuJIT/ARM32] Remove unnecessary genIsValidDoubleReg() assertion

### LINKED ISSUE #13443: [RyuJIT/ARM32] Assertion failed 'genIsValidDoubleReg(reg->regNum)
test commit : 82f487f94871c6fcc90f209d030eb8c0fc17bc00

After merged #13100, following tests met assertion.
```

JIT/Methodical/divrem/rem/r4rem_cs_do/r4rem_cs_do.sh
JIT/Methodical/divrem/rem/r4rem_cs_ro/r4rem_cs_ro.sh
JIT/jit64/hfa/main/testA/hfa_nd0A_d/hfa_nd0A_d.sh
JIT/jit64/hfa/main/testA/hfa_nd0A_r/hfa_nd0A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd1A_d/hfa_nd1A_d.sh
JIT/jit64/hfa/main/testA/hfa_nd1A_r/hfa_nd1A_r.sh
JIT/jit64/hfa/main/testA/hfa_nd2A_d/hfa_nd2A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf0A_d/hfa_nf0A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf0A_r/hfa_nf0A_r.sh
JIT/jit64/hfa/main/testA/hfa_nf1A_d/hfa_nf1A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf1A_r/hfa_nf1A_r.sh
JIT/jit64/hfa/main/testA/hfa_nf2A_d/hfa_nf2A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd0A_d/hfa_sd0A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd0A_r/hfa_sd0A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd1A_d/hfa_sd1A_d.sh
JIT/jit64/hfa/main/testA/hfa_sd1A_r/hfa_sd1A_r.sh
JIT/jit64/hfa/main/testA/hfa_sd2A_d/hfa_sd2A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf0A_d/hfa_sf0A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf0A_r/hfa_sf0A_r.sh
JIT/jit64/hfa/main/testA/hfa_sf1A_d/hfa_sf1A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf1A_r/hfa_sf1A_r.sh
JIT/jit64/hfa/main/testA/hfa_sf2A_d/hfa_sf2A_d.sh
JIT/jit64/hfa/main/testB/hfa_nd0B_d/hfa_nd0B_d.sh
JIT/jit64/hfa/main/testB/hfa_nd0B_r/hfa_nd0B_r.sh
JIT/jit64/hfa/main/testB/hfa_nf0B_d/hfa_nf0B_d.sh
JIT/jit64/hfa/main/testB/hfa_nf0B_r/hfa_nf0B_r.sh
JIT/jit64/hfa/main/testB/hfa_sd0B_d/hfa_sd0B_d.sh
JIT/jit64/hfa/main/testB/hfa_sd0B_r/hfa_sd0B_r.sh
JIT/jit64/hfa/main/testB/hfa_sf0B_d/hfa_sf0B_d.sh
JIT/jit64/hfa/main/testB/hfa_sf0B_r/hfa_sf0B_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
```
```
Assertion failed 'genIsValidDoubleReg(reg->regNum)'
    File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 8428
```

```
JIT/Methodical/fp/exgen/1000w1d_cs_do/1000w1d_cs_do.sh
JIT/Methodical/fp/exgen/1000w1d_cs_ro/1000w1d_cs_ro.sh
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b59782/b59782/b59782.sh
```
```
Assertion failed 'genIsValidDoubleReg(regRec->regNum)'
    File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 6770
```

### PR DESCRIPTION
**Pull request by sjsinju**
To fix #13443, Unnecessary genIsValidDoubleReg() assertions are removed.
In case the assignedInterval has TYP_DOUBLE register, It doesn't matter which register is updated first in update assignedInterval and previousInterval.

### CODE REVIEW

**Comment by sjsinju** [comment]
@dotnet-bot  test OSX10.12 x64 Checked Build and Test

**Comment by sjsinju** [comment]
@dotnet-bot test OSX10.12 x64 Checked Build and Test

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -5679,11 +5679,12 @@ regNumber LinearScan::tryAllocateFreeReg(Interval* currentInterval, RefPosition*
 
     if (availablePhysRegInterval != nullptr)
     {
-        intervalToUnassign = availablePhysRegInterval->assignedInterval;
         if (isAssigned(availablePhysRegInterval ARM_ARG(currentInterval->registerType)))
         {
             unassignPhysReg(availablePhysRegInterval ARM_ARG(currentInterval->registerType));
-            if (bestScore & VALUE_AVAILABLE)
+            intervalToUnassign = availablePhysRegInterval->assignedInterval;
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: You have just unassigned the interval, so this will now be `nullptr`. I think that you need to capture `intervalToUnassign` before calling `unassignPhysReg`

Comment (sjsinju) [inline src/jit/lsra.cpp]: @CarolEidt OK. I have changed the position to before calling unassignPhysReg like what you said. Thank you.!
