### PR TITLE
Fix PAL_GetLogicalProcessorCacheSizeFromOS on mac

### LINKED ISSUE #24658: Gen-0 collections happens more frequently on macOS
We've observed the GC running much more frequently on .NET Core 3.0 preview 5 than .NET Core 2.2.5 on macOS.

The data I provide may be replicated via the following benchmark:
```csharp
[MemoryDiagnoser]
public class ConcurrentQueueBenchmarks
{
    [Benchmark]
    public ConcurrentQueue<int> Queue()
    {
        return new ConcurrentQueue<int>();
    }
}
```

| Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
|  macOS (.NET Core 2.2.5) | 96.63 ns | 0.8469 ns | 0.7922 ns | 0.2441 |     - |     - |     768 B |
|  macOS (.NET Core 3.0-preview5) | 278.4 ns | 1.203 ns | 1.066 ns | 3.5210 |     - |     - |     576 B |
|  Windows (.NET Core 2.2.5) | 104.2 ns | 2.094 ns | 1.958 ns | 0.2440 |     - |     - |     768 B |
|  Windows (.NET Core 3.0-preview5) | 97.15 ns | 0.5990 ns | 0.5002 ns | 0.1836 |     - |     - |     576 B |
| Ubuntu 18.04 (.NET Core 2.2.5) | 113.8 ns | 7.344 ns | 21.42 ns | 0.2440 |     - |     - |     768 B | 
| Ubuntu 18.04 (.NET Core 3.0-preview5) | 93.64 ns | 5.161 ns | 15.22 ns | 0.1836 |     - |     - |     576 B |

This is not only exhibited by `ConcurrentQueue`; for example, `Lazy` experiences a similar ~10x increase in Gen 0 collections per 1000 instances.

I'm unsure of how to debug this further (please let me know how to, if required) - going this deep into the CLR without memory profiling tools on macOS is outside of my area of expertise at the moment.

### PR DESCRIPTION
**Pull request by andy-ms**
In a previous PR
(https://github.com/dotnet/coreclr/commit/ed52a006c01a582d4d34add40c318d6f324b99ba#diff-8447e54277bb962d167a77bb260760d7R1879),
GetCacheSizePerLogicalCpu was changed to no longer rely on cpuid on
amd64 systems; instead it uses GetLogicalProcessorCacheSizeFromOS().
Unfortunately that function consisted of a number of `#if`s, none of
which were active on macs, and we just returned 0. This caused us to
default to a gen0size of only 0.25MB, causing many GCs.

Fixed by adding a new case that uses `sysctlbyname`.

Fix #24658

### CODE REVIEW

**Comment by andy-ms** [comment]
I tested the change using this simple program:
```cs
using System;
using System.Collections.Concurrent;

static class Program
{
    static volatile object s_o;
    static void Main(string[] args)
    {
        for (int i = 0; i < 1_000_000_000; i++)
        {
            s_o = new object();
        }

        for (int gen = 0; gen <= 2; gen++)
        {
            Console.WriteLine($"Gen {gen}: {GC.CollectionCount(gen)}");
        }
    }
}
```

With the 2.2 release, I saw 3805 gen0 gcs and about 6.8 seconds.
With the 3.0 preview 5, I saw 146903 gcs and about 9.0 seconds.
With this PR, I saw 7651 gen0 gcs and about 6.0 seconds.

The remaining increase in gcs compared to the 2.2 release is because in GetCacheSizePerLogicalCpu, we no longer multiply cache size by 3 to get the "trueSize" like we did when using cpuId.

I did experiment with an altered build that multiplies by 3. Then I saw 3825 gcs and about 6.3 seconds. So we are better off in the new code even when we do more gcs.

File: src/pal/src/misc/sysinfo.cpp [hunk 1]
```diff
@@ -525,5 +525,20 @@ PAL_GetLogicalProcessorCacheSizeFromOS()
...
+        const bool success = sysctlbyname("hw.l3cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
+            || sysctlbyname("hw.l2cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
+            || sysctlbyname("hw.l1dcachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0;
+        if (success)
+        {
+            cacheSize = cacheSizeFromSysctl;
+        }
+    }
+#endif
+
```
Comment (stephentoub) [inline src/pal/src/misc/sysinfo.cpp]: Would it make sense to have an assert that cacheSize > 0, and then if it still is 0 return some default > 0?

Or should the default computation fallback based on PAL_GetLogicalCpuCountFromOS above instead be moved here and made unconditional?

Comment (andy-ms) [reply src/pal/src/misc/sysinfo.cpp]: It looks like this function is only used by `GetCacheSizePerLogicalCpu`, which is only used by gc, which manually already provides its own default each time it calls that. It might indeed clean up the code a bit to move all those defaults here.
I assume you're referring to `cacheSize = logicalCPUs*std::min(1536, std::max(256, (int)logicalCPUs*128))*1024;`? I guess it doesn't make sense to have two separate locations for default cache sizes (here vs in gc), though it might not make sense to have the same default on different systems.

Comment (janvorli) [reply src/pal/src/misc/sysinfo.cpp]: The semantics of the GetLogicalProcessorCacheSizeFromOS is to return 0 when it cannot determine the cache size. The PAL_GetLogicalProcessorCacheSizeFromOS is a unix version of that function and thus its implementation followed the same logic.
https://github.com/dotnet/coreclr/blob/580152a50e4092d32c7d05ec876cd6976483ebf1/src/vm/util.cpp#L1461-L1463.
I wonder if GC should be fixed too to handle this case in a more sensible way instead of using so small gen0 size.

File: src/pal/src/misc/sysinfo.cpp [hunk 2]
```diff
@@ -525,5 +525,20 @@ PAL_GetLogicalProcessorCacheSizeFromOS()
     }
 #endif
 
+#ifdef HAVE_SYSCTL
```
Comment (janvorli) [inline src/pal/src/misc/sysinfo.cpp]: This needs to be `#if HAVE_SYSCTL`, cmake always defines a symbol we check for and assigns it a value 0 or 1 based on whether the check succeeded.

File: src/pal/src/misc/sysinfo.cpp [hunk 3]
```diff
@@ -525,5 +525,20 @@ PAL_GetLogicalProcessorCacheSizeFromOS()
...
+    if (cacheSize == 0)
+    {
+        size_t cacheSizeFromSysctl = 0;
```
Comment (janvorli) [inline src/pal/src/misc/sysinfo.cpp]: The type of the value returned by the `hw.l3cachesize` is `int64_t`, not `size_t`. Only the `sz` is of size_t.

**Comment by janvorli** [comment]
@andy-ms the build is failing on Linux non-MUSL platforms, since these have sysctl, but they don't have getsysctlbyname. You can either add a new check for getsysctlbyname to https://github.com/dotnet/coreclr/blob/5af77fa0dcc99abb3c9610f1a062493ddc2e0584/src/pal/src/configure.cmake and https://github.com/dotnet/coreclr/blob/5af77fa0dcc99abb3c9610f1a062493ddc2e0584/src/pal/src/config.h.in or you could just use `#ifdef __APPLE__` since this is OSX specific anyways.

**Comment by sandreenko** [comment]
Hi @andy-ms , with that change y OSX build fails with:
```
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/safecrt/sprintf_s.cpp.o
/Users/ac-pc/git/coreclr/src/pal/src/misc/sysinfo.cpp:542:13: error: use of undeclared identifier 'Use__ASSERTE_instead_of_assert'
            assert(cacheSizeFromSysctl > 0);
            ^
/Users/ac-pc/git/coreclr/src/pal/src/include/pal/palinternal.h:650:17: note: expanded from macro 'assert'
#define assert (Use__ASSERTE_instead_of_assert) assert
                ^
1 error generated.
```

Do you know why it fails? Do you know why it doesn't fail in CI?

I fixed it by commenting this assert in my local repo, but probably a proper fix is needed.

**Comment by janvorli** [comment]
It should use _ASSERTE in the PAL instead of assert, as the error says. I am clueless on why it didn't fail in the CI. I can see that the HAVE_SYSCTLBYNAME was detected during the CI build.

**Comment by andy-ms** [comment]
I'll take a look at this tomorrow.

**Comment by janvorli** [comment]
Interestingly, it doesn't fail building on my local OSX either. Letting cmake generate preprocessed sysinfo.cpp.i and looking at it, it is obvious that the standard definition of assert was used instead of the redefined one, so I wonder how come it behaves differently on different OSX devices.
```c++
size_t
__attribute__((visibility("default")))
PAL_GetLogicalProcessorCacheSizeFromOS()
{
    size_t cacheSize = 0;
# 533 "/Users/janvorli/git/coreclr2/src/pal/src/misc/sysinfo.cpp"
    if (cacheSize == 0)
    {
        int64_t cacheSizeFromSysctl = 0;
        size_t sz = sizeof(cacheSizeFromSysctl);
        const bool success = sysctlbyname("hw.l3cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
            || sysctlbyname("hw.l2cachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0
            || sysctlbyname("hw.l1dcachesize", &cacheSizeFromSysctl, &sz, nullptr, 0) == 0;
        if (success)
        {
            (__builtin_expect(!(cacheSizeFromSysctl > 0), 0) ? __assert_rtn(__func__, "/Users/janvorli/git/coreclr2/src/pal/src/misc/sysinfo.cpp", 542, "cacheSizeFromSysctl > 0") : (void)0);
            cacheSize = (size_t) cacheSizeFromSysctl;
        }
    }


    return cacheSize;
}
```

**Comment by janvorli** [comment]
Ah, I can see it. On my machine, the assert.h is included again transitively via the #include <algorithm> after we redefine the assert macro. So it undefines our definition and puts back the platform one.
It seems that on @sandreenko's machine, the platform include headers are different and don't include the assert.h.

**Comment by sandreenko** [comment]
> the platform include headers are different and don't include the assert.h.

Where can I look at the included headers and their order? Sadly I am not a MacOS expert.

**Comment by janvorli** [comment]
The following will generate the preprocessed file:
```sh
cd bin/obj/OSX.x64.Debug/src/pal/src
make sysinfo.cpp.i
```
I have also edited the `CMakeFiles/coreclrpal.dir/build.make` (relative to the directory above) before running the `make` command above to see the defines in the preprocessed file too. Find line with `src/pal/src/CMakeFiles/coreclrpal.dir/misc/sysinfo.cpp.i: cmake_force` and 3 lines below that, you'll see clang++ invocation. Before the `-E`, add `-dD`.
