### PR TITLE
Do not use FP registers when soft-fp ABI is used

### LINKED ISSUE #7868: [ARM/Linux] Core FX Unittest 'System.Linq.Expressions.Tests' Failure
While testing Core FX, I encountered the following test failure:

```
System.Linq.Expressions.Tests.Compiler_Tests.BinaryOperators(useInterpreter: True) [FAIL]
   Assert.Equal() Failure
   Expected: 16
   Actual:   1.05685337245341E-314
```

I can reproduce this issue with the following example (which is reduced from the above test):

```
using System;
using System.Linq.Expressions;

namespace ConsoleApplication {

  public class Program {

    private static R TestBinary<T, R>(Expression<Func<T, T, R>> f, T v1, T v2, bool useInterpreter) {
      Func<T, T, R> d = f.Compile(useInterpreter);

      R rv = d(v1, v2);
      return rv;
    }

    private static R TestBinary<T, R>(ExpressionType op, T v1, T v2, bool useInterpreter) {
      ParameterExpression p1 = Expression.Parameter(typeof(T), "v1");
      ParameterExpression p2 = Expression.Parameter(typeof(T), "v2");

      Expression<Func<T, T, R>> f = Expression.Lambda<Func<T, T, R>>(Expression.MakeBinary(op, p1, p2), p1, p2);

      return TestBinary(f, v1, v2, useInterpreter);
    }

    public static void RunTest1() {
      var num = TestBinary<double, double>(ExpressionType.Power, 2, 4, true);

      Console.WriteLine("RunTest1: num = " + num);

      if ( 16 == num ) {
        Console.WriteLine("Pass");      
      }
    }


    public static void RunTest2() {
      var num = TestBinary<double?, double?>(ExpressionType.Power, 2, 4, true);

      Console.WriteLine("RunTest2: num = " + num);

      if ( 16 == num ) {
        Console.WriteLine("Pass");
      }
    }

    public static void Main(string[] args) {
      RunTest1();
      RunTest2();
    }
  }
}
```

### PR DESCRIPTION
**Pull request by parjong**
Soft FP ABI enforces a return value to be passed via integer registers
even though it is of float/double type (which means that 'r0 ~ r4' should
be preseved even for functions that return a float/double value).

The current implement of 'HasFloatRegister' and 'GetFPReturnSize' does
not consider this ABI difference, which makes 'CallDescrWorkerInternal'
function to preserve FP registers instead of 'r0 ~ r4' (and spoils
'r0/r1' during preservation), which leads to #7868.

This commit revises these functions in order to fix #7868.

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet test Linux ARM Emulator Cross Debug Build please

**Comment by jkotas** [comment]
cc @janvorli

File: src/vm/callingconvention.h [hunk 1]
```diff
@@ -210,7 +210,11 @@ struct TransitionBlock
             return argLocDescForStructInRegs->m_cFloatReg > 0;
         }
     #endif        
+    #ifdef ARM_SOFTFP
+        return (FALSE);
```
Comment (janvorli) [inline src/vm/callingconvention.h]: This should not be needed. The offset should never be < 0 on ARM_SOFTFP. If you can see the offset being negative with ARM_SOFTFP, then it needs to be fixed at the place where the offset is generated.

File: src/vm/callingconvention.h [hunk 2]
```diff
@@ -326,9 +330,13 @@ class ArgIteratorTemplate : public ARGITERATOR_BASE
     UINT GetFPReturnSize()
     {
         WRAPPER_NO_CONTRACT;
+#ifdef ARM_SOFTFP
+        return 0;
```
Comment (janvorli) [inline src/vm/callingconvention.h]: This should rather be fixed in the `ArgIteratorTemplate<ARGITERATOR_BASE>::ComputeReturnFlags()` by excluding the two cases for ELEMENT_TYPE_R4 and ELEMENT_TYPE_R8 for ARM_SOFTFP.

**Comment by parjong** [comment]
@janvorli I revised PR. Please take a look.

**Comment by janvorli** [comment]
@parjong  Thank you!
