### PR TITLE
JIT: update byref null check logic to handle field chains

### LINKED ISSUE #23791: Null check incorrectly (?) optimized out for nested struct access
Repro:

```
using System;
using System.Runtime.CompilerServices;

unsafe struct F
{
    long X;
    fixed byte A[10];

    [MethodImpl(MethodImplOptions.NoInlining)]
    byte NextElement(int i) => A[1+i];

    static int Main() {
        F* x = null;
        return x->NextElement(100000);
    }
}
```

Expected result: NullReferenceException
Actual result: AccessViolationException, or passed

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit was not properly accumulating offsets when figuring out if a byref
should be null checked.

Use ~~GTF_DONT_CSE~~ a non-null MorphAddressContext as indication that
GT_FIELD and GT_IND nodes are actually part of an ongoing address computation.
During field morphing propagate the current address context to the child node,
instead of starting a new one.

Fixes #23791.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Diffs
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 1199 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
         681 : System.Private.CoreLib.dasm (0.02% of base)
         228 : System.Private.Xml.dasm (0.01% of base)
          79 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
          56 : System.IO.FileSystem.dasm (0.05% of base)
          54 : System.Transactions.Local.dasm (0.05% of base)
13 total files with size differences (0 improved, 13 regressed), 116 unchanged.
Top method regressions by size (bytes):
         262 ( 5.69% of base) : System.Private.CoreLib.dasm - ConcurrentQueue`1:get_Count():int:this (7 methods)
         121 ( 3.39% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:ParseXmlDeclaration(bool):bool:this
          97 ( 5.40% of base) : System.Private.CoreLib.dasm - ConcurrentQueueSegment`1:TryDequeue(byref):bool:this (7 methods)
          91 ( 5.95% of base) : System.Private.CoreLib.dasm - ConcurrentQueueSegment`1:TryPeek(byref,bool):bool:this (7 methods)
          84 ( 5.26% of base) : System.Private.CoreLib.dasm - ConcurrentQueue`1:SnapForObservation(byref,byref,byref,byref):this (7 methods)
Top method improvements by size (bytes):
         -12 (-0.36% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:ParseAttributeValueSlow(int,ushort,ref):this
          -7 (-1.20% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - TraceLoggingEventId:GetEventIDForTraceLoggingEvent(long,long):ushort:this
          -7 (-3.47% of base) : System.Net.Http.dasm - ConcurrentQueueSegment`1:TryEnqueue(double):bool:this
          -7 (-3.47% of base) : System.Private.CoreLib.dasm - ConcurrentQueueSegment`1:TryEnqueue(double):bool:this
          -7 (-1.00% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:HandleEntityReference(bool,int,byref):int:this
Top method regressions by size (percentage):
           6 (40.00% of base) : System.Transactions.Local.dasm - EnlistableStates:CompleteAbortingClone(ref):this
           6 (40.00% of base) : System.Transactions.Local.dasm - EnlistableStates:CreateBlockingClone(ref):this
           6 (40.00% of base) : System.Transactions.Local.dasm - EnlistableStates:CreateAbortingClone(ref):this
           6 (40.00% of base) : System.Transactions.Local.dasm - TransactionStatePromotedNonMSDTCBase:CompleteAbortingClone(ref):this
           6 (40.00% of base) : System.Transactions.Local.dasm - TransactionStatePromotedNonMSDTCBase:CreateBlockingClone(ref):this
Top method improvements by size (percentage):
          -7 (-3.47% of base) : System.Net.Http.dasm - ConcurrentQueueSegment`1:TryEnqueue(double):bool:this
          -7 (-3.47% of base) : System.Private.CoreLib.dasm - ConcurrentQueueSegment`1:TryEnqueue(double):bool:this
          -6 (-3.26% of base) : System.Net.Http.dasm - ConcurrentQueueSegment`1:TryEnqueue(int):bool:this
          -6 (-3.26% of base) : System.Private.CoreLib.dasm - ConcurrentQueueSegment`1:TryEnqueue(int):bool:this
          -5 (-2.73% of base) : System.Net.Http.dasm - ConcurrentQueueSegment`1:TryEnqueue(ubyte):bool:this
101 total methods with size differences (21 improved, 80 regressed), 200043 unchanged.
```

Many of the new null checks appear to be unnecessary, but we lack the context to see how the byref is ultimately used (eg a byref is passed as an arg to an inline and so gets spilled to a temp).

Some extra diffs arise because morph can't reassociate an ADD tree with an embedded COMMA like we get when we add a nullcheck.

**Comment by AndyAyersMS** [comment]
Hmm, CoreFX fails with
```
 Could not find/download: ".NET Core SDK" with version = 2.1.503
```
Looks like has also hit other recent runs.

**Comment by VSadov** [comment]
Curious - why the size of the offset matters? 
It seems that in typesafe code LDFLDA of a struct field should always succeed (field of a class is a different matter), and if unsafe code was used, then refs could be anything - null, negative or not aligned numbers. There is not a lot of value in a null check in either case.

Is this because we may not know whether the struct is a field of a class and whether we did nullcheck on the containing class reference?

**Comment by AndyAyersMS** [comment]
Right, these checks are for cases where we do not know if the base address is null.

For small offsets from such a base, when the jit knows there will be an imminent dereference, the jit will rely on the dereference for the null check (aka an implicit null check). 

The runtime translation from access violation to null reference exception only happens for AVs in managed code with small addresse values (below `NULL_AREA_SIZE`). The jit will explicitly null check once the offset gets to be half that value or more (`MAX_UNCHECKED_OFFSET_FOR_NULL_OBJECT`).

If there's no imminent dereference, or the offset is large or unknown, the jit will do an explicit null check on the byref before adding any offset.

**Comment by AndyAyersMS** [comment]
Looks like the CoreFX issue was a transient failure, and newer legs are getting past the error, so will retry.

@dotnet-bot retest Windows_NT x64 Checked CoreFX Tests

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -6110,6 +6110,7 @@ GenTree* Compiler::fgMorphField(GenTree* tree, MorphAddrContext* mac)
     GenTree*             objRef          = tree->gtField.gtFldObj;
     bool                 fieldMayOverlap = false;
     bool                 objIsLocal      = false;
+    bool                 fieldAddr       = (tree->gtFlags & GTF_DONT_CSE) != 0;
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: Could you name this `isFieldAddr` and add some comments? In particular, that this is intending to capture the case where this `FIELD` is simply being used in an addressing context.

Also, it seems a bit dicey to me to rely on the `GTF_DONT_CSE` flag for this. That flag generally means either "this isn't idempotent" or "this is unlikely to be profitable to CSE", and here you're relying on it to mean "This may be part of an address computation". This may be an OK workaround, but it seems to merit some pretty serious caution comments.

Comment (erozenfeld) [reply src/jit/morph.cpp]: I'm also worried about using `GTF_DONT_CSE` for this. 
Your comment in #23791 is
```
Looks like morph is losing track of context in ADDR/FIELD/ADDR/FIELD chains (as in the "one more ldflda case" and in the initial example). fgMorphField will modify the FIELD into an IND, and this causes morph to reset the address context as it thinks the IND will actually do a deref. But that's not true if the parent of the IND is an ADDR, as morph will later change ADDR(IND(X)) to X.
```
Can't fgMorphField take the context into account and not reset context if the current context is ADDR? I haven't thought this through completely but we can even add a new MorphAddrContextKind if necessary.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: The drawback of using GTF_DONT_CSE here is that we will sometimes explicitly null check when it's not really needed, as we continue using the current context in some cases, rather than starting a new one. So this is not an ideal fix but I don't see it as particularly risky (other than the usual risk of perturbing IR by adding commas, etc). The offset value in the context only steers the checking logic, it won't (say) rematerialize as a constant in the IR.

But maybe I'm overlooking something?

My first impulse was to handle this via the `MorphAddressContext`, but it is not fine-grained enough. In the bug case we're in and IND context when we process the field. The kind field in the context doesn't always reflect the parent node. It may be determined by an ancestor.

We could possibly add logic so that the context could capture information about the parent node too, but we'd need to be setting and resetting this continually, and that seemed like it would be hard to get right.

Comment (briansull) [reply src/jit/morph.cpp]: I also have reservations about using the  `GTF_DONT_CSE` flag.

Comment (erozenfeld) [reply src/jit/morph.cpp]: I don't like this new implicit contract between the code that sets `GTF_DONT_CSE`  and this logic. If one considers changing the code that sets `GTF_DONT_CSE` in the future, it won't be obvious that it will affect null-checking logic. I understand that we already have lots of these non-obvious implicit contracts, but I would prefer not to add another one.

I don't completely understand why we are losing context. Can you describe the context changes in the bug example `ADDR/FIELD/ADDR/FIELD`?

**Comment by VSadov** [comment]
Ah, I see. You are "deferring" the nullcheck of the outer class to the imminent deref of a field reference. 
Only when you suspect that deref has wandered out of null area, you check the base. 
That is pretty clever.

Now, in the situation when we cannot "defer", there are still cases when base does not need to be null-checked. It looks like the code has special case for a recursive situation - when base is another GT_ADDR.

I would argue that loading byref local or a byref parameter (`this` in the repro case) also does _not_ need null check. 

The spec seems to imply that the base must be null checked, but it feels redundant since the only way it could throw is if unsafe code was used.

That feels unfortunate since that is redundant in typesafe code and benefits to unsafe code are questionable.

File: tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+    static int Main() 
+    {
+        int result = -1;
+        GitHub_23791* x = null;
+        bool threw = true;
+
+        try
+        {
+            byte t = x->NextElement(100000);
```
Comment (VSadov) [inline tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs]: May want to try a variant like

```cs
byte t = x[offsetThatMakesitValidAddr]->NextElement();
```

File: src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: It does not seem that all implicit -- `fgMorphSmpOp` explicitly sets `GTF_DONT_CSE` for `GT_ADDR` children "pre order". So it will be set on all the cases we care about... and more.

https://github.com/dotnet/coreclr/blob/29fabe7114d006af73ef768c529b4477b355a284/src/jit/morph.cpp#L11344-L11348

As far as where we were losing context:
* `fgMorphField` did not pass any context when it remorphed the tree (which was now a `GT_IND`). Perhaps if the last arg was not optional that choice would have been more obvious.
* `fgMorphSmpOp` would usually start a new context for children of `GT_IND`, and would always do so when given a null context.

So the changes I made are basically: if we suspect `GT_FIELD` or `GT_IND` nodes are really parts of address computations, just keep the existing context.

**Comment by erozenfeld** [comment]
When we are processing the left `ADDR/FIELD` are we in Addr context? Shouldn't we be passing Addr context to the right `ADDR/FIELD`?

File: src/jit/morph.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/jit/morph.cpp]: When we are processing the left `FIELD` the context argument we are getting is `MACK_Addr`, correct? Then we transform `FIELD` to `IND` and call fgMorphSmpOp on the `IND`. Shouldn't we be passing `MACK_Addr` to fgMorphSmpOp if the fgMorphField argument was `MACK_Addr`?

**Comment by AndyAyersMS** [comment]
Here is the tree from the bug case, with the current jit's logic.
```
[000012] ---XG-------    *  RETURN    int   
[000011] *--XG-------    \--*  IND       ubyte 
[000009] ------------       |  /--*  CAST      long <- int
[000007] ------------       |  |  |  /--*  LCL_VAR   int    V01 arg1         
[000008] ------------       |  |  \--*  ADD       int   
[000006] ------------       |  |     \--*  CNS_INT   int    1
[000010] ---XG-------       \--*  ADD       byref 
[000005] ---XG-------          \--*  ADDR      byref 
[000004] ---XG-------             \--*  FIELD     ubyte  FixedElementField
[000003] ---XG-------                \--*  ADDR      byref 
[000002] ---XG-------                   \--*  FIELD     struct A
[000001] ------------                      \--*  LCL_VAR   byref  V00 this         
```
Contexts are set top-down, so IND 011 sets an MACK_Ind context. This context gets "unknown offset" flagging from the ADD 010 when it sees CAST 009. That context gets passed to ADDR 005 and `fgMorphSmpOp` will not reset it --  basically  MACK_Ind trumps MACK_Addr in context logic -- if we are going to dereference we'd prefer the implicit null check.

So the context at FIELD 004 is an MACK_Ind with unknown offset. In `fgMorphField`, the FIELD 004 gets modified to IND 004 and that tree is remorphed with null context. So we lose the "unknown offset" from the ADD 010 up above. Then IND 004 sets a new MACK_Ind context for its child ADDR, 003 which passes down to the FIELD 002, which likewise becomes and IND 002, and likewise loses that context when remorphing. Finally we bottom out and don't think we need a null check. The various ADDR/IND nodes get cleaned up on the way back up, and we're left with:
```
[000012] ---XG+------      *  RETURN    int   
[000011] *--XG+------      \--*  IND       ubyte 
[000009] -----+------         |  /--*  CAST      long <- int
[000006] -----+------         |  |  |  /--*  CNS_INT   int    1
[000008] -----+------         |  |  \--*  ADD       int   
[000007] -----+------         |  |     \--*  LCL_VAR   int    V01 arg1         
[000010] ----G+------         \--*  ADD       byref 
[000001] -----+------            \--*  LCL_VAR   byref  V00 this         
```

Now, one could argue that if a MACK_Ind context at an ADDR like ADDR 005 shows the chances for an implicit check are already blown, we could change the context kind over to MACK_Addr. We are now going to explicitly null check at any rate (provided we don't lose the context).

Then we could fix things so a MACK_Addr context would propagate at the field remorph, and via current logic, IND would not replace it either. That should also fix this bug, and would not rely on GTF_DONT_CSE in any way, but might not be sufficiently general, as we would not be able to observe that an accumulation of smaller offsets ended up putting us over the implicit offset limit.

**Comment by AndyAyersMS** [comment]
> That feels unfortunate since that is redundant in typesafe code and benefits to unsafe code are questionable.

Explicit null checks from this logic are fairly rare; most cases are handled implicitly. Unknown offsets usually come from array indexing, and there we've usually already implicitly null checked as part of bounds checking. 

And, this bit code is not the final arbiter -- even if it calls for a null check, the optimizer can later show (in some cases) that the check is not needed, or can be CSEd, etc.

It would be easy to turn off this chunk logic and get an upper bound of the number of potentially unneeded checks. I think the numbers would be fairly small.

File: src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: > When we are processing the left FIELD the context argument we are getting is MACK_Addr, correct?  

No, ADDR will not override a MACK_Ind, see here:

https://github.com/dotnet/coreclr/blob/29fabe7114d006af73ef768c529b4477b355a284/src/jit/morph.cpp#L11878-L11894

**Comment by jkotas** [comment]
> The spec seems to imply that the base must be null checked, but it feels redundant since the only way it could throw is if unsafe code was used.

@VSadov It is perfectly valid to have a null byref in type safe verifiable IL. Type safe IL != safe C#.

File: src/jit/morph.cpp (hunk 1 above)
Comment (mikedn) [reply src/jit/morph.cpp]: FWIW, the `GTF_DONT_CSE` is also used for the same purpose in `fgMorphLocalVar`. That's in general a bad idea and it was partially responsible for a bug too: #19599

But in this case it's probably fine as the worst outcome of having it set for reasons other than being address taken is an extra null check. And considering that a proper fix for this is likely far more complex, well...

**Comment by VSadov** [comment]
> I I.14.4.2 Managed pointers
Managed pointers (&) can point to an instance of a value type, a field of an object, a field of a value
type, an element of an array, or the address where an element just past the end of an array would be
stored (for pointer indexes into managed arrays). Managed pointers **cannot be null**, and they shall be
reported to the garbage collector even if they do not point to managed memory.

I read above as "in safe verifiable IL, null byrefs should not be observed". 
(of course they exist, since nothing can be done about uninitialized state).

Practically speaking you must use something unsafe to make one and must be very careful when using it. 
We can have additional checks for that, but I do not think we have to.

**Comment by jkotas** [comment]
> I read above as "in safe verifiable IL, null byrefs should not be observed".

This is bug in ECMA spec. It does not match reality.

> Practically speaking you must use something unsafe to make one

The standard way to make one is to create a local with InitLocals=true frame and read from it. Managed C++ compiler (`/clr:safe`) has done it all the time.

File: src/jit/morph.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/morph.cpp]: > I don't like this new implicit contract between the code that sets GTF_DONT_CSE and this logic. If one considers changing the code that sets GTF_DONT_CSE in the future, it won't be obvious that it will affect null-checking logic.

I agree, but I also agree with @mikedn that this may be the best practical fix for the moment. If we go this route, however, I would like to see us clearly indicate 1) at the declaration of `GTF_DONT_CSE`, 2) The code in morph that sets it, and 3) the places that use it for this purpose, that it must be set on nodes that appear to be indirections but are actually part of an address computation.

Comment (erozenfeld) [reply src/jit/morph.cpp]: @AndyAyersMS Thank you for the explanation.

Isn't it the case that fgMorphField will get a non-null context only if its parent is GT_ADDR? The lines below seem to ensure that. If that's the case we don't need to rely on GTF_DONT_CSE.

https://github.com/dotnet/coreclr/blob/311b5e2fe413c6c74a2a3680ab54d8a978651472/src/jit/morph.cpp#L11939-L11951

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: I don't think so -- we could have for example IND(FIELD) and the FIELD would see a MACK_Ind, just like it would if we had IND(ADDR(FIELD)).

Comment (erozenfeld) [reply src/jit/morph.cpp]: In the case of IND(FIELD) when `tree` is `IND` we will set context to `MACK_Ind` here
https://github.com/dotnet/coreclr/blob/311b5e2fe413c6c74a2a3680ab54d8a978651472/src/jit/morph.cpp#L11904
but then change it to nullptr here
https://github.com/dotnet/coreclr/blob/311b5e2fe413c6c74a2a3680ab54d8a978651472/src/jit/morph.cpp#L11939-L11951
before calling `fgMorphTree` (that calls `fgMorphField`):
https://github.com/dotnet/coreclr/blob/311b5e2fe413c6c74a2a3680ab54d8a978651472/src/jit/morph.cpp#L11953

What am I missing?

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Ah, right... had forgotten about that latter bit. So we could perhaps get rid of the GTF_DONT_CSE check for FIELD and have it always pass whatever mac it gets when remorphing, but we'd still need to keep the part where we consult GTF_DONT_CSE for IND to make sure the mac does not subsequently get reset.

Comment (erozenfeld) [reply src/jit/morph.cpp]: We can extend the latter bit to do the same for indirections, e.g., 

```
if (((op1->gtOper == GT_FIELD) || (op1->gtOper == GT_IND)) && (tree->gtOper != GT_ADDR)) 
 { 
     subMac1 = nullptr; 
  
     // The impact of this field's value to any ongoing 
     // address computation is handled below when looking 
     // at op2. 
 } 
```
(Not sure if in addition to `GT_IND` we need to have `GT_OBJ`, `GT_BLK`, and `GT_DYN_BLK`, in which case we may use `OperIsIndir`).

Then we won't need the other change that consults `GTF_DONT_CSE`.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: I don't think this will work in this case -- when we remorph in `fgMorphField`, we remorph starting at the IND.

Comment (erozenfeld) [reply src/jit/morph.cpp]: I don't see why that's a problem. The parent of `GT_IND` was already through this logic before `fgMorphField` was called. So, if we pass the context unconditionally when re-morphing from `fgMorphField`, it will be nullptr if the parent of `IND` was not `GT_ADDR`. Then it will be set to `MAC_Ind` when morphing `GT_IND`.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Right, the remorphed IND is going to reset the mac, which is wrong, since (if the parent is ADDR) the IND is part of the ongoing address computation, just like the FIELD was.

Comment (erozenfeld) [reply src/jit/morph.cpp]: If ADDR(FIEELD(op))) gets a non-null context, it will be passed to gtMorphField. Then gtMorphField will call fgMorphSmpOp on IND(op) and will pass the non-null context it got. If you remove the `GTF_DONT_CSE` part from your check (but keep the null check), it will become

```
                case GT_OBJ:
                case GT_BLK:	                case GT_BLK:
                case GT_DYN_BLK:	                case GT_DYN_BLK:
                case GT_IND:	                case GT_IND:
                    subMac1 = &subIndMac1;	                    // If not part of an address computation, use the new mac.
                    if (subMac1 == nullptr)
                    {
                        subMac1 = &subIndMac1;
                    }
```
so mac won't be reset.

Comment (erozenfeld) [reply src/jit/morph.cpp]: I updated the last comment with a correct code snippet.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: If we do that we'll potentially introduce more unnecessary checks. Some INDs should start new macs even if when a mac is passed in, eg `IND(ADD(x, IND(y))`.

Let me try it and see; maybe those cases are rare.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Looks like they are indeed rare, no FX diffs beween  the latest fix (which has no dependence on GTF_DONT_CSE) and my original.

**Comment by AndyAyersMS** [comment]
Latest commit (based on some great feedback from @erozenfeld) removes all dependence on GTF_DONT_CSE and has same diffs as the original.

We now presume for FIELD/IND that a non-null mac implies we're in an address context. That is true for FIELD and approximately true for IND, seems to do well in practice.

Assuming this is a more palatable change, I'll update the top comment and reword the commit message before merging.

File: src/jit/morph.cpp (hunk 1 above)
Comment (erozenfeld) [reply src/jit/morph.cpp]: I think you also need to change

```
        if ((op1->gtOper == GT_FIELD) && (tree->gtOper != GT_ADDR))
        {
            subMac1 = nullptr;

            // The impact of this field's value to any ongoing
            // address computation is handled below when looking
            // at op2.
        }
```

to
```
        if (((op1->gtOper == GT_FIELD) || op1->OperIsIndir()) && (tree->gtOper != GT_ADDR))
        {
            subMac1 = nullptr;

            // The impact of this field's value to any ongoing
            // address computation is handled below when looking
            // at op2.
        }

```
and

```
        // If gtOp2 is a GT_FIELD, we must be taking its value,
        // so it should evaluate its address in a new context.
        if (op2->gtOper == GT_FIELD)
        {
            // The impact of this field's value to any ongoing
            // address computation is handled above when looking
            // at op1.
            mac = nullptr;
        }
```
to

```
        // If gtOp2 is a GT_FIELD, we must be taking its value,
        // so it should evaluate its address in a new context.
        if ((op2->gtOper == GT_FIELD) || op2->OperIsIndir())
        {
            // The impact of this field's value to any ongoing
            // address computation is handled above when looking
            // at op1.
            mac = nullptr;
        }
```

That should take care of `IND(ADD(x, IND(y))` case. With these changes I don't see any cases where we may introduce unnecessary checks.

File: tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs (hunk 2 above)
Comment (AndyAyersMS) [reply tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs]: You are suggesting I figure out how to make `x[y]` point at the start of an actual `GitHub_23791` instance? Seems tricky to do, as the address of the struct is unlikely to be a multiple of `sizeof(GitHub_23791)`.

Comment (VSadov) [reply tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs]: I was thinking about something like:

```cs
using System;
using System.Runtime.CompilerServices;

// The jit should null check 'this' in NextElement

unsafe struct GitHub_23791
{
    fixed byte A[16];

    [MethodImpl(MethodImplOptions.NoInlining)]
    byte NextElement(int i) => A[1 + i];

    static int Main()
    {
        int result = -1;
        GitHub_23791* x = null;
        bool threw = true;

        GitHub_23791 dummy;

        try
        {
            dummy.A[0] = 42;

            byte t = x[(long)(&dummy) / sizeof(GitHub_23791)].A[0];
            System.Console.WriteLine(t);

            t = x->A[(long)(&dummy)];
            System.Console.WriteLine(t);

            threw = false;
        }
        catch (NullReferenceException)
        {
            result = 100;
        }

        if (!threw)
        {
            Console.WriteLine($"FAIL: did not throw an exception");
        }

        return result;
    }
}
```

Currently it prints

```cs
42
42
```

As I understand you want the second one (or both?) to fail.

Comment (VSadov) [reply tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs]: Yes, it may be tricky.   
It works when size is something like `16`, but I am not sure if it is guaranteed.

Anyways, if it is supposed to NRE, then guessing the address exactly may not matter.

Comment (AndyAyersMS) [reply tests/src/JIT/Regression/JitBlue/GitHub_23791/GitHub_23791.cs]: With the current fix (for windows x64) this prints 42 and then exits with 100, which is what I'd expect (printing 42 is perhaps a happy accident, we may not get that on other ISAs or OSs).

The first instance should not throw, as the base address `x[...]` is accessible; the second should throw, as the base address x is not accessible.

File: src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Turns out we wouldn't ever null check a pure IND case anyways, as null checking requires a FIELD.

Latest commit has the extensions to the mac reset logic.

**Comment by AndyAyersMS** [comment]
Did one more update based on Eugene's feedback. No codegen diffs vs the prior commits.

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -11932,7 +11933,16 @@ GenTree* Compiler::fgMorphSmpOp(GenTree* tree, MorphAddrContext* mac)
                 case GT_BLK:
                 case GT_DYN_BLK:
                 case GT_IND:
-                    subMac1 = &subIndMac1;
+                    // If this node is part of an address computation, propagate
+                    // the existing mac.
+                    //
+                    // We can't check for this exactly, but a non-null mac is a
+                    // reasonable approximation for "this node is part of an
+                    // address computation".
```
Comment (erozenfeld) [inline src/jit/morph.cpp]: Do you think this is still only an approximation? What are the cases where this check is not checking for "this node is part of an address computation" exactly?

**Comment by AndyAyersMS** [comment]
> Is this something we can teach optFoldNullCheck to clean up?

Seems likely. Here is an example new diff where we should have been able to optimize away the check....
```diff
; System.Transactions.Local   InternalEnlistment:FinishEnlistment():this
        mov      rax, gword ptr [rcx+32]
-       add      rax, 260
+       cmp      dword ptr [rax], eax
+       add      rax, 232
+       add      rax, 28
        inc      dword ptr [rax]
```
The broken constant fold here is caused by the new nullcheck comma. Looks like multiple adds is not something the optimization can handle.

File: src/jit/morph.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: I don't know of any cases, so I'll update the comment.

**Comment by erozenfeld** [comment]
Can you please open a future issue for extending optFoldNullCheck with example diffs? I'll look into that after 3.0.

**Comment by AndyAyersMS** [comment]
Jenkins hangup for Arm64 windows:

@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

Arm32 failure is #23905.

**Comment by AndyAyersMS** [comment]
Retrigger arn32 now that fix is in.

@dotnet test Windows_NT arm Cross Checked Innerloop Build and Test
