### PR TITLE
Disable Interop/WinRT/NETClients/Primitives test on Nano Server.

### LINKED ISSUE #24661: Test failure: Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd
The test `Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd` has failed.

Failure Message:
```
\r
Return code:      1\r
Raw output file:      C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\Reports\\Interop.WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
 \"C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\\corerun.exe\" NETClientPrimitives.exe \r
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstanceHelper(Char* rawUri, Int32 strLen)\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstance(String rawUri)\r
   at Component.Contracts.IUriTesting.GetFromUri(Uri uri)\r
   at NetClient.UriTests.RunTest() in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\UriTests.cs:line 15\r
   at NetClient.Program.Main(String[] args) in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\Program.cs:line 28\r
Expected: 100\r
Actual: 101\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\r
> C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x64.Release\TestWrappers\Interop.WinRT\Interop.WinRT.XUnitWrapper.cs:line 218
```

Build : Master - 20190519.72 (Core Tests)
Failing configurations:
- Windows.10.Nano.Amd64-x64
  - 
  - 

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190519.72/workItem/Interop/analysis/xunit/Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #24661

### CODE REVIEW

File: tests/src/Interop/WinRT/NETClients/Primitives/Program.cs [hunk 1]
```diff
@@ -10,7 +10,7 @@ class Program
     {
         static int Main(string[] args)
         {
-            if (!TestLibrary.Utilities.IsWinRTSupported)
+            if (!TestLibrary.Utilities.IsWinRTSupported || TestLibrary.Utilities.IsWindowsNanoServer)
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/WinRT/NETClients/Primitives/Program.cs]: Couldn't we fold this check into `IsWinRTSupported`?
