### PR TITLE
Fix GCStress C issue with the fix to VS2019 optimization

### LINKED ISSUE #27495: Test failed: Assert failure: this == GetThread()
**Job:**
[coreclr-gcstress0x3-gcstress0xc #20191027.1 Run Test Pri1 Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=403705)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/9a904906-7f3b-49bc-bb84-90cf3cc1f260/workitems/Loader.classloader.TypeGeneratorTests.TypeGeneratorTest1200-1500/console

**OS & Arch:**
windows x64

**Mode:**
COMPlus_TieredCompilation=0
COMPlus_GCStress=0xC

**Note:**
This failure **repros** on our windows x64 machine

**Log:**
```
Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1218\Generated1218\Generated1218.cmd [FAIL]
      
      Assert failure(PID 3204 [0x00000c84], Thread: 836 [0x0344]): this == GetThread()
      
      CORECLR! GCFrame::~GCFrame + 0xFD (0x00007ffb`9da1d37d)
      CORECLR! DoGcStress + 0x504 (0x00007ffb`9dd0a0e8)
      CORECLR! Thread::RedirectedHandledJITCase + 0x1F6 (0x00007ffb`9d8e9526)
      CORECLR! RedirectedHandledJITCaseForGCStress_Stub + 0x26 (0x00007ffb`9dd095a6)
      <no module>! <no symbol> + 0x0 (0x00007ffb`3e4bf2e5)
      <no module>! <no symbol> + 0x0 (0x000001ee`22877110)
          File: F:\workspace\_work\1\s\src\vm\threads.h Line: 2103
          Image: C:\dotnetbuild\work\9a904906-7f3b-49bc-bb84-90cf3cc1f260\Payload\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\9a904906-7f3b-49bc-bb84-90cf3cc1f260\Work\9866f678-c52f-49d9-98b4-b7f9a71192ae\Exec\Loader\classloader\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest1218\Generated1218\Generated1218.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\dotnetbuild\work\9a904906-7f3b-49bc-bb84-90cf3cc1f260\Payload\corerun.exe" Generated1218.dll 
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by janvorli**
There is a place in the runtime that we hit during GCStress C and that
was creating uninitialized GCFrame and initializing it only
conditionally. In the GCFrame destructor, we always try to pop the
GCFrame out of the per-thread linked list and this was breaking it.

The fix is to always initialize the GCFrame. In the problematic place,
it was not being initialized / pushed on the linked list when number of
GC slots it was to protect was 0. But the logic in GCFrame works just
fine even in that case, so I've made the initialization over there
unconditional.

I've also made a couple of methods in the GCFrame private as they are
never supposed to be called from the outside, removed the default
GCFrame constructor so that noone can create uninitialized GCFrame
anymore and also removed placement new from GCFrame that doesn't seem to
have any purpose.

Close #27495

### CODE REVIEW

File: src/vm/frames.h [hunk 1]
```diff
@@ -2466,17 +2466,22 @@ class ComPrestubMethodFrame : public ComMethodFrame
 //------------------------------------------------------------------------
 class GCFrame
 {
+    void Init(Thread *pThread, OBJECTREF *pObjRefs, UINT numObjRefs, BOOL maybeInterior);
```
Comment (jkotas) [inline src/vm/frames.h]: The can be merged into the constructor. The constructor that does not take `pThread` can forward to constructor that does take `pThread`.

File: src/vm/frames.h [hunk 2]
```diff
@@ -2466,17 +2466,22 @@ class ComPrestubMethodFrame : public ComMethodFrame
...
+    void Push(Thread *pThread);
```
Comment (jkotas) [inline src/vm/frames.h]: These do not need to be separate methods either. Folding them in may help a code quality a little bit - I am not sure whether the C/C++ compiler is smart enough to inline these.

Comment (janvorli) [reply src/vm/frames.h]: Done, the compiler was not inlining them even in Release builds

File: src/vm/frames.h (hunk 1 above)
Comment (janvorli) [reply src/vm/frames.h]: Done
