### PR TITLE
LSRA Arm64 consistent reg sets

### LINKED ISSUE #14591: [Arm64] Lsra breaking tip
New change was merge which is causing 33 new test failures

```
JIT/Directed/coverage/oldtests/33objref_cs_do/33objref_cs_do.sh
JIT/Directed/coverage/oldtests/33objref_cs_ro/33objref_cs_ro.sh
JIT/jit64/hfa/main/testC/hfa_sd0C_d/hfa_sd0C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd0C_r/hfa_sd0C_r.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_d/hfa_sd1C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_r/hfa_sd1C_r.sh
JIT/jit64/opt/cse/staticFieldExpr1_ro_loop/staticFieldExpr1_ro_loop.sh
JIT/jit64/opt/cse/volatilefield/volatilefield.sh
JIT/jit64/opt/rngchk/RngchkStress2_o/RngchkStress2_o.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_b/_il_dbghuge_b.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_i4/_il_dbghuge_i4.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_objref/_il_dbghuge_objref.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_r4/_il_dbghuge_r4.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_r8/_il_dbghuge_r8.sh
JIT/Methodical/Arrays/huge/_il_dbghuge_u8/_il_dbghuge_u8.sh
JIT/Methodical/Arrays/huge/_il_relhuge_b/_il_relhuge_b.sh
JIT/Methodical/Arrays/huge/_il_relhuge_i4/_il_relhuge_i4.sh
JIT/Methodical/Arrays/huge/_il_relhuge_objref/_il_relhuge_objref.sh
JIT/Methodical/Arrays/huge/_il_relhuge_r4/_il_relhuge_r4.sh
JIT/Methodical/Arrays/huge/_il_relhuge_r8/_il_relhuge_r8.sh
JIT/Methodical/Arrays/huge/_il_relhuge_struct/_il_relhuge_struct.sh
JIT/Methodical/Arrays/huge/_il_relhuge_u8/_il_relhuge_u8.sh
JIT/Methodical/int64/arrays/_il_dbghugedim/_il_dbghugedim.sh
JIT/Methodical/int64/arrays/_il_relhugedim/_il_relhugedim.sh
JIT/Methodical/Invoke/25params/25param2a_cs_do/25param2a_cs_do.sh
JIT/Methodical/Invoke/25params/25param2a_cs_ro/25param2a_cs_ro.sh
JIT/Methodical/Invoke/25params/25param2b_il_r/25param2b_il_r.sh
JIT/Methodical/Invoke/25params/25param2c_il_r/25param2c_il_r.sh
JIT/Methodical/VT/port/_il_relhuge_gcref/_il_relhuge_gcref.sh
JIT/Regression/CLR-x86-JIT/dev10/b393481/b393481/b393481.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b29456/b29456/b29456.sh
Regressions/common/AboveStackLimit/AboveStackLimit.sh
Regressions/coreclr/0099/AboveStackLimit/AboveStackLimit.sh
```

Looking at a few failures seems an assert is firing in lsra.

```
Assert failure(PID 22851 [0x00005943], Thread: 22851 [0x5943]): Assertion failed 'nextPhysRegPosition->nodeLocation == refLocation && candidateBit != refPosition->registerAssignment' in 'DomainNeutralILStubClass:IL_STUB_Array_Set(int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int):this' (IL size 1396)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 6222
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

@CarolEidt @dotnet/jit-contrib 

git bisect info  
bad  138f0b7
good 29865c3

### PR DESCRIPTION
**Pull request by CarolEidt**
tryAllocateFreeReg() uses the RegOrder array to iterate over the available registers. This needs to be consistent with the available registers of the given type. Otherwise, allocateBusyReg() will assert when it finds a free register that should have been allocated in tryAllocateFreeReg().
Fix #14591

### CODE REVIEW

**Comment by CarolEidt** [comment]
Note that:
1. The regression was caused by a more aggressive assert added as part of the refactoring in PR #14534
2. I have opened #14607 to ensure that we are using the correct set of registers in LSRA.

**Comment by CarolEidt** [comment]
@sdmaclea @briansull PTAL
cc @dotnet/jit-contrib

File: src/jit/target.h [hunk 1]
```diff
@@ -1595,6 +1595,7 @@ typedef unsigned short regPairNoSmall; // arm: need 12 bits
   #define REG_VAR_ORDER            REG_R9,REG_R10,REG_R11,REG_R12,REG_R13,REG_R14,REG_R15,\
                                    REG_R8,REG_R7,REG_R6,REG_R5,REG_R4,REG_R3,REG_R2,REG_R1,REG_R0,\
                                    REG_R19,REG_R20,REG_R21,REG_R22,REG_R23,REG_R24,REG_R25,REG_R26,REG_R27,REG_R28,\
+                                   REG_IP0,REG_IP1,\
```
Comment (sdmaclea) [inline src/jit/target.h]: What is the order used for?  

The list is currently in Caller saved, Args, Callee saved, Linkage.

Having Linkage, `REG_IP0,REG_IP1`, at he end of the list seems suspicious.  These are reserved in the ABI for linkage, but they can be used transiently as temps.

From what I remember, some of the LIR nodes use the IP regs freely during code generation, because the allocator never used to allocate them.

Comment (CarolEidt) [reply src/jit/target.h]: > What is the order used for?

It is the order in which `tryAllocateFreeReg()` looks for a register.

> Having Linkage, REG_IP0,REG_IP1, at he end of the list seems suspicious.

I was unable to find usage of them in codegen. But I was uncertain; that's why I opened #14607.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -1170,7 +1170,11 @@ LinearScan::LinearScan(Compiler* theCompiler)
 #endif // DEBUG
 
     enregisterLocalVars = ((compiler->opts.compFlags & CLFLG_REGVAR) != 0) && compiler->lvaTrackedCount > 0;
-    availableIntRegs    = (RBM_ALLINT & ~compiler->codeGen->regSet.rsMaskResvd);
+#ifdef _TARGET_ARM64_
+    availableIntRegs = (RBM_ALLINT & ~(RBM_PR | RBM_FP | RBM_LR) & ~compiler->codeGen->regSet.rsMaskResvd);
```
[the remark this answers is not in the document]
Comment (CarolEidt) [reply src/jit/lsra.cpp]: REG_PR == REG_R18 (defined in registeram64.h)

File: src/jit/target.h (hunk 1 above)
Comment (sdmaclea) [reply src/jit/target.h]: Since they are in `RBM_INT_CALLEE_TRASH` , it seems Ok to add them to REG_VAR_ORDER

Given the current definition of `RBM_CALLEE_TRASH_NOGC` it seems VAR ORDER should be
CALLEE_TRASH & ~ CALLEE_TRASH_NOGC
CALLEE_TRASH_NOGC
RBM_CALLEE_SAVED

Since that is not the current order, this is OK.

**Comment by BruceForstall** [comment]
@dotnet-bot
test Windows_NT x64_arm64_altjit Checked Build and Test

**Comment by CarolEidt** [comment]
Ignoring CentOS, since those seem to be in an always-failing state.
I will transfer the notes above to #14607 so that the order and inclusivity of these register sets can be corrected and/or verified.
