### PR TITLE
Fix #7093

### LINKED ISSUE #7093: x86: Assertion failed 'genActualType(tree->gtType) == TYP_LONG'
Note that this is in codegenlegacy.cpp, suggesting that the fallback is failing in this particular case.

Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.4

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=4

/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309548/b309548/b309548.cmd

> D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(385056): error : JIT._Regression_VS_ia64_JIT_V2_0_Beta2_b309548_b309548_b309548_._Regression_VS_ia64_JIT_V2_0_Beta2_b309548_b309548_b309548_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\runtest.proj]
> Assert failure(PID 6492 [0x0000195c], Thread: 3368 [0x0d28]): Assertion failed 'genActualType(tree->gtType) == TYP_LONG' in 'AA:Static3(char):ref' (IL size 73)
> File: d:\j\workspace\x86_ryujit_ch---5357ccf8\src\jit\codegenlegacy.cpp Line: 13220
> Image: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b309548\b309548\b309548.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b309548.exe
> Testing AA::Static3
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by BruceForstall**
This is an assert due to how STRESS_64RSLT_MUL is implemented. This
stress mode converts:
```
/--*  lclVar    int    V01 loc0
*  *         int
\--*  lclVar    int    V01 loc0
```
to:
```
*  cast      int <- long
|  /--*  cast      long <- int
|  |  \--*  lclVar    int    V01 loc0
\--*  *         long
   \--*  cast      long <- long
      \--*  nop       long
         \--*  lclVar    int    V01 loc0
```
Thus, the long 'nop' node is above an 'int' operand node. This led to an assert
in genCodeForTreeLng() that the lclVar was type long, which is isn't.

I added yet another cast under the 'nop' to fix this typing problem:
```
*  cast      int <- long
|  /--*  cast      long <- int
|  |  \--*  lclVar    int    V01 loc0
\--*  *         long
   \--*  cast      long <- long
      \--*  nop       long
         \--*  cast      long <- int
            \--*  lclVar    int    V01 loc0
```

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT jitstress1
@dotnet-bot test Windows_NT jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT jitstress2_jitstressregs1
@dotnet-bot test Windows_NT jitstress2_jitstressregs2
@dotnet-bot test Windows_NT jitstress2_jitstressregs3
@dotnet-bot test Windows_NT jitstress2_jitstressregs4
@dotnet-bot test Windows_NT jitstress2_jitstressregs8
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 ryujit Checked jitstress2

**Comment by BruceForstall** [comment]
@adiaaida I tried triggering RyuJIT x86 stress runs, but it looks like they all failed. And the "Details" link is bad on all of them. Is that expected?

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by adiaaida** [comment]
No, it should all work. I'm not sure why it isn't, but it looks like they haven't even been run yet? If you ran them last night, it's possible you tried triggering them when dotnet-ci was having problems.

**Comment by sivarv** [comment]
Looks good.

**Comment by pgavlin** [comment]
LGTM

**Comment by CarolEidt** [comment]
LGTM

File: src/jit/flowgraph.cpp [hunk 1]
```diff
@@ -19810,23 +19810,40 @@ Compiler::fgWalkResult      Compiler::fgStress64RsltMulCB(GenTreePtr* pTree, fgW
...
+
+#ifdef DEBUG
+    if (pComp->verbose)
+    {
+        printf("STRESS_64RSLT_MUL before:\n");              
+        pComp->gtDispTree(tree);
+    }
+#endif // DEBUG
 
     // To ensure optNarrowTree() doesn't fold back to the original tree.
```
Comment (CarolEidt) [inline src/jit/flowgraph.cpp]: I believe that it's the insertion of the `GT_NOP` that ensures that `optNarrowTree()` doesn't fold - so perhaps that comment should remain just above the `GT_NOP`. In fact, it might be good to elaborate on that point.

**Comment by mmitche** [comment]
woah.....how did that happen.  it should have been ignoring dotnet-bot

**Comment by mmitche** [comment]
oh nvm you requested them all

**Comment by adiaaida** [comment]
It looks like the stress jobs are running now, and the details link works.
