### PR TITLE
Unmark unused fields as not lvOnFrame

### LINKED ISSUE #14548: [RyuJIT/arm32][JitStress=1] Assertion failed 'dsc->lvTracked'
From corefx x86_arm_altjit run, e.g. "@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress1".

Happens with `COMPlus_JitStress=1`.

Found in System.Reflection.Metadata.Tests:
```
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>RunTests.cmd E:\gh\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x86\
Using E:\gh\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x86\ as the test runtime folder.
Executing in E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86\
Running tests... Start time: 13:48:26.81

E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_AltJit=*
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_AltJitNgen=*
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_AltJitName=protononjit.dll
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_NoGuiOnAssert=1
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_ContinueOnAssert=0
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_AltJitAssertOnNYI=1
E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_JitStress=1

E:\gh\corefx\bin\tests\System.Reflection.Metadata.Tests\netcoreapp-Windows_NT-Release-x86>call E:\gh\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x86\\dotnet.exe xunit.console.netcore.exe System.Reflection.Metadata.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Reflection.Metadata.Tests
Discovered:  System.Reflection.Metadata.Tests
Starting:    System.Reflection.Metadata.Tests

Assert failure(PID 20072 [0x00004e68], Thread: 16792 [0x4198]): Assertion failed 'dsc->lvTracked' in 'Xunit.Sdk.AssertEqualityComparer`1[SerializationTypeCode][System.Reflection.Metadata.SerializationTypeCode]:Equals(ubyte,ubyte):bool:this' (IL size 358)

    File: e:\gh\coreclr2\src\jit\emit.cpp Line: 4715
    Image: E:\gh\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe
```

Full repro:
```
dotnet/coreclr:
E:\gh\coreclr2> build.cmd x86 checked

dotnet/corefx:
E:\gh\corefx> build.cmd -Release -os:Windows_NT -buildArch:x86 -- /p:CoreCLROverridePath=E:\gh\coreclr2\bin\Product\Windows_NT.x86.Checked
E:\gh\corefx> build-tests.cmd -Release -os:Windows_NT -buildArch:x86 -- /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=e:\bugs\SetStressModes.bat

With e:\bugs\SetStressModes.bat:
set COMPlus_AltJit=*
set COMPlus_AltJitNgen=*
set COMPlus_AltJitName=protononjit.dll
set COMPlus_NoGuiOnAssert=1
set COMPlus_ContinueOnAssert=0
set COMPlus_AltJitAssertOnNYI=1
set COMPlus_JitStress=1
```

### PR DESCRIPTION
**Pull request by CarolEidt**
If a dependently promoted (i.e. non-register candidate) field of a struct is unused, and its parent is not allocated onto the stack, we cannot allocate the dependent fields to the stack either (they were previously being assigned offsets from 0, which may be in the GC ptr area, which causes an assert).

Fix #14548

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked corefx_jitstress1

**Comment by CarolEidt** [comment]
The CentOS and armlb failures seem to be pre-existing.
I'm a big confused about the x86_arm_altjit Checked corefx_jitstress1, as the lsra assert:
```
 Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'System.Numerics.Tests.ComplexTests:Conjugate(double,double)'
```
doesn't seem to occur in #14802 that @BruceForstall ran just a couple of days ago, but I see it in both master as well as my branch. I'll try to see if I can track that down.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -12660,8 +12660,8 @@ GenTree* Compiler::gtFoldTypeCompare(GenTree* tree)
         // If we have class handles, try and resolve the type equality test completely.
         if ((cls1Hnd != nullptr) && (cls2Hnd != nullptr))
         {
-            JITDUMP("Asking runtime to compare %p (%s) and %p (%s) for equality\n", cls1Hnd,
-                    info.compCompHnd->getClassName(cls1Hnd), cls2Hnd, info.compCompHnd->getClassName(cls2Hnd));
+            JITDUMP("Asking runtime to compare %p (%s) and %p (%s) for equality\n", dspPtr(cls1Hnd),
+                    info.compCompHnd->getClassName(cls1Hnd), dspPtr(cls2Hnd), info.compCompHnd->getClassName(cls2Hnd));
```
Comment (CarolEidt) [inline src/jit/gentree.cpp]: This change and the one in importer.cpp are unrelated, except that they make it a lot easier to examine diffs in jitdumps.

**Comment by BruceForstall** [comment]
>  `Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'System.Numerics.Tests.ComplexTests:Conjugate(double,double)'`

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/

It seems that most, but not all, of the daily test runs have that assert. In particular, these three recent ones did not:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/27/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/26/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/25/consoleText

So unless that is a fluke, or flakiness, the bug was reintroduce here:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/28/

Note that we had this bug before in this test suite:
https://github.com/dotnet/coreclr/issues/14542

**Comment by BruceForstall** [comment]
(also note that it is a known issue that even despite the asserts, the corefx altjit runs are known to not be clean: https://github.com/dotnet/coreclr/issues/15304)

**Comment by BruceForstall** [comment]
IMO, if your change fixes one bug, you shouldn't hold it to investigate the other assert. I opened a new issue for the other assert: https://github.com/dotnet/coreclr/issues/15325
