### PR TITLE
For LEGACY_BACKEND ARM32 do not overwrite 1 element HFA type

### LINKED ISSUE #8093: Assert failure(PID 10364 [0x0000287c], Thread: 14536 [0x38c8]): Assertion failed 'isGeneralRegister(id->idReg2())' in 'StructABI:Main():int' (IL size 2040)
1 P1 test fails on this

### PR DESCRIPTION
**Pull request by jashook**
On arm64 we will treat 1 element HFA types as the primitive
type that is contained. On Legacy Backend codegenlegacy will
incorrectly assign these two types. Instead keep the struct
type through the IR correctly to do a blockop.

Fixes #8093

### CODE REVIEW

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm64 Checked

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT Arm Checked

**Comment by jashook** [comment]
@dotnet-bot help

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by pgavlin** [comment]
Please do not include the LST file changes in this PR. They are covered by #12945.

LGTM otherwise.

**Comment by pgavlin** [comment]
(besides the change to `StructABI`, of course :))

File: src/jit/compiler.cpp [hunk 1]
```diff
@@ -5589,7 +5596,7 @@ void Compiler::compCompileFinish()
     {
         if (compJitHaltMethod())
         {
-#if !defined(_TARGET_ARM64_) && !defined(_HOST_UNIX_)
+#if !defined(_TARGET_ARM64_) && !defined(_TARGET_ARM_) && !defined(_HOST_UNIX_)
```
Comment (RussKeldorph) [inline src/jit/compiler.cpp]: This doesn't look related.  I'd prefer it be in its own PR, but if you want to keep it here, please at least note it in the description of the change.

**Comment by pgavlin** [comment]
These changes also fix #12907.

File: src/jit/compiler.cpp (hunk 1 above)
Comment (jashook) [inline src/jit/compiler.cpp]: Thank you for catching that, different issue.

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

**Comment by jashook** [comment]
Diffs done, do not see anything.
