### PR TITLE
Fix various fgMorphInitBlock issues

### LINKED ISSUE #21761: JIT asserts when initializing an 8 byte block
The following program triggers a JIT assert:
```
.assembly extern System.Runtime { }
.assembly test { }
.class sequential sealed Point extends [System.Runtime]System.ValueType
{
    .field public int32 X
    .field public int32 Y
}
.method hidebysig static int32 Main() cil managed
{
    .locals init (valuetype Point a)
    .entrypoint

    ldloca a
    ldc.i4 1
    ldc.i4 8
    initblk

    ldloca a
    ldfld int32 Point::X
    ret
}
```
```
Assert failure(PID 1808 [0x00000710], Thread: 1968 [0x07b0]): Assertion failed '((val & 0xFF00000000LL) == 0) || ((val & 0xFFFFFFFF00000000LL) == 0xFFFFFFFF00000000LL)' in '<Module>:Main():int' (IL size 26)

    File: d:\projects\coreclr\src\jit\emit.cpp Line: 6118
    Image: D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\CoreRun.exe
```
Looks like morph produces some constants that have type int but the value is actually long:
```
fgMorphTree BB01, stmt 1 (before)
               [000006] ------------              /--*  INIT_VAL  int   
               [000003] ------------              |  \--*  CNS_INT   int    1
               [000007] IA----------              *  ASG       struct (init)
               [000005] -------N----              \--*  BLK(8)    struct
               [000002] L-----------                 \--*  ADDR      byref 
               [000001] ------------                    \--*  LCL_VAR   struct(P) V00 loc0         
                                                        \--*    int    V00.X (offs=0x00) -> V02 tmp1         
                                                        \--*    int    V00.Y (offs=0x04) -> V03 tmp2         

fgMorphInitBlock: (destDoFldAsg=true) using field by field initialization.
GenTreeNode creates assertion:
               [000016] -A----------              *  ASG       int   
In BB01 New Local Constant Assertion: V02 == 16843009 index=#01, mask=0000000000000001
GenTreeNode creates assertion:
               [000019] -A----------              *  ASG       int   
In BB01 New Local Constant Assertion: V03 == 16843009 index=#02, mask=0000000000000002
fgMorphInitBlock (after):
               [000018] ------------                 /--*  CNS_INT   int    0x101010101010101
               [000019] -A----------              /--*  ASG       int   
               [000017] D------N----              |  \--*  LCL_VAR   int    V03 tmp2         
               [000020] -A---+------              *  COMMA     void  
               [000015] ------------              |  /--*  CNS_INT   int    0x101010101010101
               [000016] -A----------              \--*  ASG       int   
               [000014] D------N----                 \--*  LCL_VAR   int    V02 tmp1         
```

### PR DESCRIPTION
**Pull request by mikedn**
fgMorphInitBlock fails left and right if you use anything other than 0 for initialization. Not exactly a common scenario I'd guess, but since I started to get my hands dirty with struct related issues I decided to just fix the whole thing, rather than attempt to disable field by field initialization for non 0 init values.

More details in test code comments.

Fixes #21761

No FX diffs.

There are all kinds of further improvements that could be made but I've node idea who would need this. For example, there's no reason to not do field by field initialization with a non-const value - you just add `MUL(initValue, 0x01010101)` and use it to initialize the fields. Nor there's any reason to require that the block size be equal to the struct size, if the block is smaller then initialize only the affected fields. But who needs that? We'll have to wait and see.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -9315,232 +9314,260 @@ GenTree* Compiler::fgMorphInitBlock(GenTree* tree)
...
         }
         else
         {
-            if (dest->OperIsBlk())
-            {
-                destAddr   = dest->AsBlk()->Addr();
-                blockWidth = dest->AsBlk()->gtBlkSize;
-            }
-            else
+            GenTree* destAddr = dest->AsIndir()->Addr();
```
Comment (sandreenko) [inline src/jit/morph.cpp]: looks like `GenTree* destAddr = dest->AsIndir()->Addr();` can be moved lower to `FieldSeqNode* destFldSeq = nullptr;`.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -9315,232 +9314,260 @@ GenTree* Compiler::fgMorphInitBlock(GenTree* tree)
...
-        // or the struct is not promoted
-        //
         if (!destDoFldAsg)
         {
-            dest             = fgMorphBlockOperand(dest, dest->TypeGet(), blockWidth, true);
+            // If we're doing an InitBlock and we've transformed the dest to a non-Blk
+            // we need to change it back.
+            if (!dest->OperIsBlk())
+            {
+                noway_assert(blockSize != 0);
```
Comment (sandreenko) [inline src/jit/morph.cpp]: when does it happen? When we call `fgMorphPromoteLocalInitBlock` it changes `dest` but returns `null`?

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -9315,232 +9314,260 @@ GenTree* Compiler::fgMorphInitBlock(GenTree* tree)
...
-                dest->gtFlags |= (lclVarTree->gtFlags & ~(GTF_NODE_MASK | GTF_VAR_USEASG));
+    if (blockSize == 0)
+    {
+        JITDUMP(" size is not known.\n");
+        return nullptr;
+    }
 
-                srcCopy = gtCloneExpr(initVal);
-                noway_assert(srcCopy != nullptr);
+    if (destLclVar->lvAddrExposed && destLclVar->lvContainsHoles)
```
[the remark this answers is not in the document]
Comment (mikedn) [reply src/jit/morph.cpp]: > Could you please give an example of initializing struct with holes overlapping fields?

Such a struct can't ever be promoted, you'd loose the interference between the overlapped fields (unless you modify the IR in such a way to preserve the interference, that would probably be pretty crazy). `CanPromoteStructType` checks this.

So you get normal block initialization:
```C#
Unsafe.InitBlock(&ms, 42, 8);
```
generates
```asm
48B92A2A2A2A2A2A2A2A mov      rcx, 0x2A2A2A2A2A2A2A2A
48894C2428           mov      qword ptr [rsp+28H], rcx
```

> Is not destLclVar->lvContainsHoles enough to reject this optimization? As we saw from #18988 we can access holes even if struct was not defined as destLclVar->lvAddrExposed (via Unsafe.As<>).

Well, that's just how the existing code works, I just moved it around because it was terribly confusing, with similar conditions being tested in different places for no good reason. 

I'd say that it's the right thing to do:
* Rejecting field by field initialization just because the struct has holes is overly conservative - various mixes of integer field types will naturally cause holes due to alignment requirements.
* Normally nobody cares about what values holes contain. They might care when holes are created on purpose (e.g. with explicit layout) but that case is rejected below.
* It may be considered a security issue if it allows information to leak through holes but with CAS being practically dead that's unlikely.

File: src/jit/morph.cpp [hunk 4]
```diff
@@ -9315,232 +9314,260 @@ GenTree* Compiler::fgMorphInitBlock(GenTree* tree)
...
-            INDEBUG(morphed = true);
+    return tree;
+}
 
-            GenTree* dest;
-            GenTree* srcCopy;
-            unsigned fieldLclNum;
-            unsigned fieldCnt = destLclVar->lvFieldCnt;
+//------------------------------------------------------------------------
+// fgMorphPromoteLocalInitBlock: Attempts to promote a local block init tree
```
[the remark this answers is not in the document]
Comment (mikedn) [reply src/jit/morph.cpp]: I'll add an example. Something like:
```
               [000048] ------------              /--*  INIT_VAL  int   
               [000045] ------------              |  \--*  CNS_INT   int    42
               [000049] IA----------              *  ASG       struct (init)
               [000047] -------N----              \--*  BLK(12)   struct
               [000043] L-----------                 \--*  ADDR      long  
               [000044] ------------                    \--*  LCL_VAR   struct(P) V02 loc0         
                                                        \--*    int    V02.a (offs=0x00) -> V06 tmp3         
                                                        \--*    int    V02.b (offs=0x04) -> V07 tmp4         
                                                        \--*    int    V02.c (offs=0x08) -> V08 tmp5         
```
```
               [000071] ------------                 /--*  CNS_INT   int    0x2A2A2A2A
               [000072] -A----------              /--*  ASG       int   
               [000070] D------N----              |  \--*  LCL_VAR   int    V08 tmp5         
               [000073] -A---+------              *  COMMA     void  
               [000067] ------------              |     /--*  CNS_INT   int    0x2A2A2A2A
               [000068] -A----------              |  /--*  ASG       int   
               [000066] D------N----              |  |  \--*  LCL_VAR   int    V07 tmp4         
               [000069] -A----------              \--*  COMMA     void  
               [000064] ------------                 |  /--*  CNS_INT   int    0x2A2A2A2A
               [000065] -A----------                 \--*  ASG       int   
               [000063] D------N----                    \--*  LCL_VAR   int    V06 tmp3         
```

File: src/jit/morph.cpp (hunk 2 above)
Comment (mikedn) [reply src/jit/morph.cpp]: Nah, `fgMorphPromoteLocalInitBlock` doesn't touch the tree if it returns null. This is due to `fgMorphBlkNode` that's called at the start of `fgMorphInitBlock`. Apparently `fgMorphBlkNode` can sometimes transform the block node to a `GT_IND` that's obviously not suitable as a struct store destination because it doesn't have a size. So if we fail to perform field by field initialization we need to change it back.

Now, don't ask me why `fgMorphBlkNode` produces such a `GT_IND` node... Struct promotion and more generally struct handling in the JIT needs a serious shake up. I'll get to it eventually, need to finish #21705 first.

Comment (mikedn) [reply src/jit/morph.cpp]: > Maybe we can change fgMorphBlkNode not to do this?

I hope so. But this needs to be investigated separately because it's pretty convoluted.

As far as I can tell, `fgMorphBlkNode` can only return `GT_IND` if it can't find a class handle. And it only looks for a class handle if it deals with an array element access and then a class handle should exist on `GT_INDEX`/`GT_INDEX_ADDR`.

Except the odd corner case when the destination happens to be a `GT_COMMA` that's not actually related to array access. If that ever happens then that assert in `fgMorphInitBlock` will fire. It really shouldn't happen because the importer is pretty insistent in wrapping struct trees with `GT_OBJ`/`GT_BLK` nodes and there's a good chance that the `GT_COMMA` (and likely the `GT_INDEX_ADDR`) `fgMorphBlkNode` code is actually dead.

Comment (sandreenko) [reply src/jit/morph.cpp]: Thanks for the explanation!
