### PR TITLE
Properly initialize lvaTrackedVarSet.

### LINKED ISSUE #7090: RyuJIT x86: Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)'
In Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.0x80

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=0x80

/JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_d/bigvtbl_cs_d.cmd

> D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(300669): error : JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---945650c9\tests\runtest.proj]
> Assert failure(PID 3096 [0x00000c18], Thread: 7756 [0x1e4c]): Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)' in 'CTest:Main():int' (IL size 149274)
> File: d:\j\workspace\x86_ryujit_ch---945650c9\src\jit\liveness.cpp Line: 3058
> Image: D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\Reports\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---945650c9\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" bigvtbl_cs_d.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by pgavlin**
The lack of initialization when `lvaCount == 0` was causing failures
under JITStressRegs=0x80. When this initialization is not performed,
it is initialized s.t. every bit is set, including bits that represent
non-existent lclVars. This caused LSRA to AV when attempting to access
the lclVar table using a lclNum derived from an iteration over
`lvaTrackedVarSet`.

Fixes #7090.

### CODE REVIEW

**Comment by pgavlin** [comment]
@sivarv @CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/lclvars.cpp [hunk 1]
```diff
@@ -2689,6 +2689,10 @@ void Compiler::lvaSortByRefCount()
     lvaTrackedCount             = 0;
     lvaTrackedCountInSizeTUnits = 0;
 
+#ifdef DEBUG
+    VarSetOps::AssignNoCopy(this, lvaTrackedVars, VarSetOps::MakeEmpty(this));
```
Comment (sivarv) [inline src/jit/lclvars.cpp]: It would be a good idea to capture why this initialization is needed in debug only build here.

**Comment by CarolEidt** [comment]
Isn't it nice when you can make a one-line fix?
LGTM

**Comment by sivarv** [comment]
Looks good.

File: src/jit/lclvars.cpp (hunk 1 above)
Comment (sivarv) [inline src/jit/lclvars.cpp]: On second thought, would it better to add a null check in lsra before trying to use lvaTrackedVars rather than initializing it to empty set in debug builds?  Because, if some other code path uses lvaTrackedVars like LSRA did, then it will go unnoticed on debug builds.  Since JitStress/LSRA stress run is not done on retail bits, the issue will not be caught unless we have a directed test, which we don't have otherwise that test would have caught it instead of stress mode.

Comment (BruceForstall) [inline src/jit/lclvars.cpp]: It's very suspicious that this is only under DEBUG and not unconditional.

Comment (sivarv) [inline src/jit/lclvars.cpp]: @BruceForstall - pointed out that lvaTrackedVars is defined only in debug.  In my source search I was also looking at jit32 occurrences.

This fix looks good.
