### PR TITLE
[RyuJit][Armel] Do not lose type information

### LINKED ISSUE #14955: [RyuJIT/armel] Assertion failed 'argValue->TypeGet() == TYP_STRUCT'
`JIT/Methodical/tailcall/_il_dbgtest_3b/` fails in `armel` with RyuJIT.

In Checked, following tests failed with an assertion as follows.
```
FAILED   - [   0s]JIT/Methodical/tailcall/_il_dbgtest_3b/_il_dbgtest_3b.sh
               BEGIN EXECUTION
               /opt/usr/coreclr-tc/Windows_NT.x86.Release/Tests/coreoverlay/corerun _il_dbgtest_3b.exe
               
               Assert failure(PID 26011 [0x0000659b], Thread: 26011 [0x659b]): Assertion failed 'argValue->TypeGet() == TYP_STRUCT' in 'JitTest.TestClass:TestFunc1():int' (IL size 28)
               
                   File: /var/jenkins/workspace/netcore/github_master/cross_checked/build/build_coreclr_checked/repo/code/src/jit/morph.cpp Line: 4993
                   Image: /opt/usr/coreclr-tc/Windows_NT.x86.Release/Tests/coreoverlay/corerun
               
               ./_il_dbgtest_3b.sh: line 243: 26011 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

In Release, the test fails with segmentation fault as follows.
```
FAILED   - [   1s]JIT/Methodical/tailcall/_il_dbgtest_3b/_il_dbgtest_3b.sh
               BEGIN EXECUTION
               /opt/usr/coreclr-tc/Windows_NT.x86.Release/Tests/coreoverlay/corerun _il_dbgtest_3b.exe
               ./_il_dbgtest_3b.sh: line 243:  6557 Segmentation fault      $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by sandreenko**
fgMorphMultiregStructArg could lose type information when replaced smth like this:
 GT_OBJ - TYP_STRUCT     <== arg
 +GT_ADDR - TYP_I_IMPL
 ++GT_LCL_VAR - TYP_BLK  <== argValue

Fix #14955.

So after the change we do not replace argValue with anything that has different type.

### CODE REVIEW

**Comment by sandreenko** [comment]
The main discussion was there: #15049.

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -4963,11 +4963,17 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
...
-        if (argObj->gtOp1->OperGet() == GT_ADDR)
+        // If we have a GT_OBJ of a GT_ADDR then we set argValue to the child node of the GT_ADDR.
+        GenTree* op1 = argObj->gtOp1;
+        if (op1->OperGet() == GT_ADDR)
         {
-            argValue = argObj->gtOp1->gtOp.gtOp1;
+            GenTree* underlyingTree = op1->gtOp.gtOp1;
+
+            // Only update to the same type.
+            if (underlyingTree->TypeGet() == argValue->TypeGet())
```
Comment (sandreenko) [inline src/jit/morph.cpp]: We have the assert that checks that before `argValue` was struct: 
```
4922 assert(varTypeIsStruct(arg->TypeGet()));
```
and after we still have struct: 
```
5074 // We should still have a TYP_STRUCT
5975  assert(varTypeIsStruct(argValue->TypeGet()));
```

so do not volatile this in the middle, actually it is the only place where we can change  `argValue` value of its type.

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -4963,11 +4963,17 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
...
+            {
+                argValue = underlyingTree;
+            }
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Should we assert we havethe same class handle too?

**Comment by sandreenko** [comment]
cc @hqueue

File: src/jit/morph.cpp (hunk 2 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: I do not see an easy way how to get 'CORINFO_CLASS_HANDLE' from all possible  'underlyingTree' nodes.

Comment (AndyAyersMS) [reply src/jit/morph.cpp]: `gtGetStructHandleIfPresent` ?

**Comment by sandreenko** [comment]
the assert was added;
the test was temporary moved to the innerloop, because we do not have job to run armel pri1 tests.

**Comment by sandreenko** [comment]
Failed test case:
```
     (  9,  9) [000620] x---G--------             *  OBJ(8)    struct
     (  3,  5) [000619] ----G--------             \--*  ADDR      byref
     (  3,  4) [000609] ----G--N-----                \--*  LCL_FLD   struct V02 arg2         [+0] Fseq[Start]
```
LCL_FLD   does not have struct handle.

**Comment by AndyAyersMS** [comment]
So is this an bug/issue with the IR or a shortcoming in `gtGetStructHandleIfPresent`?

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -4963,11 +4963,18 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
...
+        if (op1->OperGet() == GT_ADDR)
         {
-            argValue = argObj->gtOp1->gtOp.gtOp1;
+            GenTree* underlyingTree = op1->gtOp.gtOp1;
+
+            // Only update to the same type.
+            if (underlyingTree->TypeGet() == argValue->TypeGet())
+            {
+                argValue = underlyingTree;
+                assert(objClass == gtGetStructHandleIfPresent(underlyingTree));
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: I think it would be possible in IL to take the address of a lclVar, and then use ldobj with a different struct type (including size) to pass it to a method. While it's not verifiable IL, I don't think it is illegal. In that case, this assert would fail. Also, the arg setup code, such as in `fgMorphMultiregStructArg()` would use the strong struct layout for passing the struct.
I think you need to turn the above assert into the condition for eliding the OBJ(ADDR())

**Comment by sandreenko** [comment]
> So is this an bug/issue with the IR or a shortcoming in gtGetStructHandleIfPresent?

It is both, `LCL_FLD` should be able to return non-zero class handle, but this case was missed. But when I added it, it return a class handle that was not equal to `objClass` and the assert failed again.

**Comment by CarolEidt** [comment]
>> So is this an bug/issue with the IR or a shortcoming in gtGetStructHandleIfPresent?

> It is both, LCL_FLD should be able to return non-zero class handle, but this case was missed. But when I added it, it returned a class handle that was not equal to objClass and the assert failed again.

This is "sort of" by design. I don't recall all of the details, but there are difficulties associated with ensuring that `LCL_FLD` always has a valid class handle. In general, if you have an `OBJ(ADDR())` the handle on the `OBJ` should be used.

**Comment by sandreenko** [comment]
> > > So is this an bug/issue with the IR or a shortcoming in gtGetStructHandleIfPresent?

> > It is both, LCL_FLD should be able to return non-zero class handle, but this case was missed. But when I added it, it returned a class handle that was not equal to objClass and the assert failed again.

> This is "sort of" by design. I don't recall all of the details, but there are difficulties associated with ensuring that LCL_FLD always has a valid class handle. In general, if you have an OBJ(ADDR()) the handle on the OBJ should be used.

Ok, it is strange, because we transform from `LCL_FLD` to `GT_LCL_VAR` both ways and it changes the result of this function.

So I turned the assert into the condition. Please look again.

**Comment by sandreenko** [comment]
Windows_NT arm64 Cross Checked Innerloop Build and Test  is a stable regression. will investigate...

**Comment by sandreenko** [comment]
The PR was updated:
1) Add the missed check that `baseAddr` is `GT_ADDR`.
2) Add check that we do not have `GT_ADDR->GT_LCL_VAR` where the local is not marked as `lvaVarDoNotEnregister` in the rationalize phase. Checked that superPMI for amd64 passed with this assert.

We set `lvaVarDoNotEnregister` during the morph phase so maybe we could find a better place for this check. We can't set this flag in the importer, because it will be too conservative.

The question why do we have structs with different handlers will be solved separately.

**Comment by CarolEidt** [comment]
@sandreenko - I gather that adding a check after rationalizer generated asserts?

**Comment by sandreenko** [comment]
> @sandreenko - I gather that adding a check after rationalizer generated asserts?

I added in into the rationalizer. It failed on x86 checked Private.CoreLib. I will add this check as a separate PR.

Also, the test, that was the original issue, started to fail with another assert after my last change.
