### PR TITLE
[RyuJIT/armel] Make RefPosition arg regs fixed

### LINKED ISSUE #12994: [RyuJIT/armel] Assert Failure `farthestRefPhysRegRecord != nullptr`
```
Assert failure(PID 26005 [0x00006595], Thread: 26005 [0x6595]): Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'r8NaNrem:Main():int' (IL size 8610)

    File: /opt/code/work/src/jit/lsra.cpp Line: 6010
    Image: /opt/usr/home/owner/dotnet/tto/corerun
```

Failed Tests

- JIT/Methodical/NaN/r8NaNrem_cs_do/r8NaNrem_cs_do.exe
- JIT/Methodical/NaN/r8NaNrem_cs_ro/r8NaNrem_cs_ro.exe
- JIT/Methodical/divrem/div/overlddiv_cs_do/overlddiv_cs_do.exe
- JIT/Methodical/divrem/div/overlddiv_cs_ro/overlddiv_cs_ro.exe
- JIT/Methodical/divrem/rem/i4rem_cs_do/i4rem_cs_do.exe
- JIT/Methodical/divrem/rem/i4rem_cs_ro/i4rem_cs_ro.exe
- JIT/Methodical/divrem/rem/i8rem_cs_do/i8rem_cs_do.exe
- JIT/Methodical/divrem/rem/i8rem_cs_ro/i8rem_cs_ro.exe
- JIT/Methodical/divrem/rem/overldrem_cs_do/overldrem_cs_do.exe
- JIT/Methodical/divrem/rem/overldrem_cs_ro/overldrem_cs_ro.exe
- JIT/Methodical/divrem/rem/r4rem_cs_do/r4rem_cs_do.exe
- JIT/Methodical/divrem/rem/r4rem_cs_ro/r4rem_cs_ro.exe
- JIT/Methodical/divrem/rem/r8rem_cs_do/r8rem_cs_do.exe
- JIT/Methodical/divrem/rem/r8rem_cs_ro/r8rem_cs_ro.exe
- JIT/Methodical/divrem/rem/u4rem_cs_do/u4rem_cs_do.exe
- JIT/Methodical/divrem/rem/u4rem_cs_ro/u4rem_cs_ro.exe
- JIT/Methodical/divrem/rem/u8rem_cs_do/u8rem_cs_do.exe
- JIT/Methodical/divrem/rem/u8rem_cs_ro/u8rem_cs_ro.exe

Backtrace (r8NaNrem_cs_do.exe)

```
#8  0xb1272cec in assertAbort (
    why=0xb152f157 "farthestRefPhysRegRecord != nullptr",
---Type <return> to continue, or q <return> to quit---
    file=0xb152d68f "/opt/code/work/src/jit/lsra.cpp", line=6010)
    at /opt/code/work/src/jit/error.cpp:287
#9  0xb13416bc in LinearScan::allocateBusyReg (this=0x591604,
    current=0x808e4c, refPosition=0x80aa14, allocateIfProfitable=false)
    at /opt/code/work/src/jit/lsra.cpp:6010
#10 0xb1339234 in LinearScan::allocateRegisters (this=0x591604)
    at /opt/code/work/src/jit/lsra.cpp:7781
#11 0xb1336138 in LinearScan::doLinearScan (this=0x591604)
    at /opt/code/work/src/jit/lsra.cpp:1776
#12 0xb1251e1e in Compiler::compCompile (this=0x802a8,
    methodCodePtr=0xbeffd2b4, methodCodeSize=0xbeffd758,
    compileFlags=0xbeffd2c8) at /opt/code/work/src/jit/compiler.cpp:4829
```

### PR DESCRIPTION
**Pull request by wateret**
Passing double arg regs via `r0:r1` or `r2:r3`,
each RefPosition's RegMask should have only one exact register
so the candidate register can be fixed.

e.g.)

```
<RefPosition #4099 @2625 RefTypeUse <Ivl:1237> BB35 regmask=[r0-r1] last>
<RefPosition #4100 @2625 RefTypeUse <Ivl:1238> BB35 regmask=[r0-r1] last>
```

to be:

```
<RefPosition #4099 @2625 RefTypeUse <Ivl:1237> BB35 regmask=[r0] last fixed>
<RefPosition #4100 @2625 RefTypeUse <Ivl:1238> BB35 regmask=[r1] last fixed>
```

Fix #12994

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @dotnet/arm32-contrib

File: src/jit/regset.cpp [hunk 1]
```diff
@@ -1604,7 +1604,7 @@ void RegSet::rsSpillTree(regNumber reg, GenTreePtr tree, unsigned regIdx /* =0 *
 #endif // _TARGET_ARM_
     else
     {
-        assert(!varTypeIsMultiReg(tree));
+        assert(!varTypeIsMultiReg(tree) || (m_rsCompiler->opts.compUseSoftFP && treeType == TYP_LONG));
```
Comment (CarolEidt) [inline src/jit/regset.cpp]: I don't think this is correct. How does it know which have of the double/long is being spilled? I think it needs to be handled similarly to the other multiReg ops.

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -3985,6 +3985,15 @@ void LinearScan::buildRefPositionsForNode(GenTree*                  tree,
...
             regMaskTP candidates = getUseCandidates(useNode);
+#ifdef ARM_SOFTFP
+            // If oper is GT_PUTARG_REG, set bits in useCandidates must be in sequential order.
+            if (useNode->OperGet() == GT_PUTARG_REG || useNode->OperGet() == GT_COPY)
+            {
+                regMaskTP candidate = genFindLowestReg(candidates);
+                useNode->gtLsraInfo.setSrcCandidates(this, candidates & ~candidate);
+                candidates = candidate;
+            }
+#endif // ARM_SOFTFP
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: I think this should more generally handle the case of `useNode->IsMultiRegNode()`. And it might be better to extract this into a separate method. I'm not crazy about modifying the `srcCandidates` on `useNode`, but there is probably not a better way that doesn't suffer from inefficiency.

File: src/jit/regset.cpp (hunk 1 above)
Comment (wateret) [inline src/jit/regset.cpp]: Thank you for your comment. Would that mean `GenTreePutArgReg`(for arm) should have the field `gtSpillFlags` and corresponding setter/getters just like `GenTreeCall` and `GenTreePutArgSplit` do?

**Comment by wateret** [comment]
@CarolEidt I updated the commit so each reg now gets own SpillFlag for GenTreeMultiRegOp(just like MultiRegCall and PutArgSplit). And it makes this test case pass on Release mode. However I get an assert failure on Debug.

```
Assert failure(PID 19407 [0x00004bcf], Thread: 19407 [0x4bcf]): Assertion failed 'temp != nullptr' in 'r8NaNrem:Main():int' (IL size 8610)

    File: /opt/code/work/src/jit/regset.cpp Line: 3313
    Image: /opt/usr/home/owner/dotnet/ttt/corerun

crashed [1471040486] processname=corerun, pid=19407, tid=19407, signal=6
```

It looks like RyuJIT does not allow adding temps while codegen, it pre-allocates temps before codegen which probably means that currently it does not correctly calculates how many temps we need. Could you give me some clue on this?

cc: @hseok-oh

**Comment by wateret** [comment]
FYI the register allocation looks unnatural. The below is pushing arguments for a call to a static method with two double arguments. However on RP#2889, `r0` is spilled by the target address then it is spilled on RP#2895 by the argument again, then it gets proper register `r8` on RP#2898. That is, the first two allocation was unnecessary. Maybe this is related to what I stated above.

```
Allocating Registers

...

 1860.#2881  I979   Def    Alloc r0   |I979 a|      |I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1860.#2882  I980   Def    Alloc r1   |I979 a|I980 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1861.#2883  r0     Fixd   Keep  r0   |I979 a|I980 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1861.#2884  I979   Use *  Keep  r0   |I979 a|I980 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1861.#2885  r1     Fixd   Keep  r1   |I979 a|I980 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1861.#2886  I980   Use *  Keep  r1   |I979 a|I980 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1862.#2887  I981   Def    Alloc r0   |I981 a|      |I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
--------------------------------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------
Loc   RP#    Name   Type  Action Reg  |r0    |r1    |r2    |r3    |r4    |r5    |r6    |r7    |r8    |r9    |r10   |r11   |r12   |sp    |lr
--------------------------------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------
 1862.#2888  I982   Def    Alloc r1   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1864.#2889  C983   Def    Spill r0   |      |I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
                           Steal r0   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2890  r2     Fixd   Keep  r2   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2891  I974   Use *  Keep  r2   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2892  r3     Fixd   Keep  r3   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2893  I975   Use *  Keep  r3   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2894  r0     Fixd   Keep  r0   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2895  I981   Use *  ReLod NA   |C983 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
                           Spill r0   |      |I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
                           Steal r0   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2896  r1     Fixd   Keep  r1   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2897  I982   Use *  Keep  r1   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
 1865.#2898  C983   Use *  ReLod NA   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|V5   a|V6   a|----  |----  |V7   a|----  |V21  a
                           Spill r8   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|      |V6   a|----  |----  |V7   a|----  |V21  a
                           Steal r8   |I981 a|I982 a|I974 a|I975 a|V0   a|V1   a|V3   a|V4   a|C983 a|V6   a|----  |----  |V7   a|----  |V21  a
 1866.#2899  r0     Kill   Keep  r0   |      |      |      |      |V0   a|V1   a|V3   a|V4   a|C983 i|V6   a|----  |----  |V7   a|----  |V21  a
 1866.#2900  r1     Kill   Keep  r1   |      |      |      |      |V0   a|V1   a|V3   a|V4   a|C983 i|V6   a|----  |----  |V7   a|----  |V21  a
 1866.#2901  r2     Kill   Keep  r2   |      |      |      |      |V0   a|V1   a|V3   a|V4   a|C983 i|V6   a|----  |----  |V7   a|----  |V21  a
 1866.#2902  r3     Kill   Keep  r3   |      |      |      |      |V0   a|V1   a|V3   a|V4   a|C983 i|V6   a|----  |----  |V7   a|----  |V21  a
 1866.#2903  r12    Kill   Spill r12  |      |      |      |      |V0   a|V1   a|V3   a|V4   a|C983 i|V6   a|----  |----  |      |----  |V21  a

...
```

**Comment by alpencolt** [comment]
@wateret :
> It looks like RyuJIT does not allow adding temps while codegen, it pre-allocates temps before codegen which probably means that currently it does not correctly calculates how many temps we need. Could you give me some clue on this?

You're right. You have to declare amount of used register in `lsra` and then use them in `codegen` not more than you've requested. Another point you should remember is that destination register can be one from temporary set registers (I mean register allocator can provide for source register `r2`, for temporary `r1` and for destination again `r1`). To avoid it set `isInternalRegDelayFree=true`.

File: src/jit/lsra.cpp [hunk 3]
```diff
@@ -8536,6 +8545,13 @@ void LinearScan::recordMaxSpill()
         maxSpill[TYP_FLOAT] += 1;
     }
 #endif // _TARGET_X86_
+
+    if (compiler->opts.compUseSoftFP)
+    {
+        JITDUMP("Adding a spill temp for moving target address to a register.\n");
+        maxSpill[TYP_INT] += 1;
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: Why is this needed? Where is this spill temp being used, what is it used for, and how is it obtained?

File: src/jit/codegenlinear.cpp [hunk 4]
```diff
@@ -1034,6 +1034,32 @@ void CodeGen::genUnspillRegIfNeeded(GenTree* tree)
...
+                    TempDsc* t = regSet.rsUnspillInPlace(multiReg, dstReg, i);
+                    getEmitter()->emitIns_R_S(ins_Load(dstType), emitActualTypeSize(dstType), dstReg, t->tdTempNum(),
+                                              0);
+                    compiler->tmpRlsTemp(t);
+                    gcInfo.gcMarkRegPtrVal(dstReg, dstType);
+                }
+            }
+
+            unspillTree->gtFlags &= ~GTF_SPILLED;
+        }
```
Comment (wateret) [inline src/jit/codegenlinear.cpp]: @CarolEidt Definitely I agree with that.

File: src/jit/lsra.cpp (hunk 3 above)
Comment (wateret) [inline src/jit/lsra.cpp]: @CarolEidt After I made the second commit(I thought it would be enough), but I got the assertion mentioned from https://github.com/dotnet/coreclr/pull/13023#issuecomment-319254128. So I had to fix it, and the code here is sort of a workaround.

Comment (wateret) [inline src/jit/lsra.cpp]: What I stated here https://github.com/dotnet/coreclr/pull/13023#issuecomment-319255219 was strange part while LSRA, the C# code of this part is roughly like:

```cs
func(a, b);
// static SomeReturnType func(double, double)
```

While setting r0-r3 arguments, they are not fixed until the call. So `r0` is spilled (since no other free registers) for call address. Eventually the call address goes to `r8` though. And this probably requires one more temp variable. 
I think this could be an issue for general arm, not only armel, since x86/x64 usually does not store call address to a register, directly uses a full immediate address.

% The exact TC I was looking at is `JIT/Methodical/NaN/r8NaNmul_cs_do/r8NaNmul_cs_do.exe`.

Comment (CarolEidt) [inline src/jit/lsra.cpp]: > Eventually the call address goes to r8 though. And this probably requires one more temp variable.

There should be a spill temp accounted for with the spill address of the target register. Given the dump segment that you shared, it would seem that:
- The instruction at N1861 defines a value (I981) into r0. It is spilled, so that will result in `maxSpill[TYP_INT]` being set to at least 1 (it would be more if there are other outstanding spills, but that's not 100% clear from the dump fragment).
- The instruction at N1863 defines the call target address (and the definition is located at 1864). It is also spilled, so at this point `maxSpill[TYP_INT]` should be at least 2.
- It appears that the call is at N1865. It reloads I981 into r0, which causes `maxSpill[TYP_INT]` to be decremented.
- It then reloads the target address (C983) into r8, which causes `maxSpill[TYP_INT]` to be decremented again - back to 0 or whatever it was at Location 1861.
- Then, it spills r12 (V7), which requires an additional spill temp, so `maxSpill[TYP_INT]` should now be at least one again.

During codegen, these spills and reloads should be happening in this same order. Can you verify that's the case?

Comment (wateret) [inline src/jit/lsra.cpp]: @CarolEidt Looks like it does.

```
Generating: N1851 ( 47, 33) [000885] ---X---------      t885 = *  IND       double REG f8 <l:$350, c:$6db>
							Byref regs: 0008 {r3} => 0000 {}
IN037d:             vldr    d8, [r3]
                                                              /--*  t885   double 
Generating: N1853 (???,???) [014273] ---X---------    t14273 = *  COPY      long   REG r2,r3
                                                              /--*  t14273 long   
Generating: N1855 (???,???) [014274] ---X---------    t14274 = *  PUTARG_REG long   REG r2,r3
IN037e:             vmov.d2i r2, r3, d8
Generating: N1857 (  1,  1) [000872] -------------      t872 =    CNS_DBL   double 0.0000000000000000 REG f8 $80
IN037f:             movs    r0, 0
IN0380:             movs    r1, 0
IN0381:             vmov.i2d d8, r0, r1
                                                              /--*  t872   double 
Generating: N1859 (???,???) [014275] -------------    t14275 = *  COPY      long   REG r0,r1
                                                              /--*  t14275 long   
Generating: N1861 (???,???) [014276] ------------Z    t14276 = *  PUTARG_REG long   REG r0,r1
IN0382:             vmov.d2i r0, r1, d8
reused temp #2, slot 0, size = 4
							The register r0 spilled with    [014276]
IN0383:             str     r0, [sp+0x10]	// [TEMP_02]
Generating: N1863 (  3,  7) [014277] ------------Z    t14277 =    CNS_INT(h) int    0xB642FE33 ftn REG r0
IN0384:             movw    r0, 0xfe33
IN0385:             movt    r0, 0xb642
reused temp #1, slot 0, size = 4
							The register r0 spilled with    [014277]
IN0386:             str     r0, [sp+0x0c]	// [TEMP_01]
                                                              /--*  t14277 int    
Generating:                [019739] -------------    t19739 = *  RELOAD    int    REG r8
                                                              /--*  t14274 long   arg1 r2,r3
                                                              +--*  t14276 long   arg0 r0,r1
                                                              +--*  t19739 int    control expr
Generating: N1865 ( 64, 46) [000886] --CX---------      t886 = *  CALL help double HELPER.CORINFO_HELP_DBLREM <l:$322, c:$323>
							Tree-Node marked unspilled from  [014276]
IN0387:             ldr     r0, [sp+0x10]	// [TEMP_02]
release temp #2, slot 0, size = 4
							Tree-Node marked unspilled from  [014277]
IN0388:             ldr     r8, [sp+0x0c]	// [TEMP_01]
release temp #1, slot 0, size = 4
```

Comment (wateret) [inline src/jit/lsra.cpp]: Of course, this cannot be a solution since it will allocate one more temps for all methods.

**Comment by wateret** [comment]
@CarolEidt 
I reverted the previous commit(https://github.com/dotnet/coreclr/pull/13023/commits/a4f9b3a19728b0666d67194a8d475680eaee1bf8), and made change to `LinearScan::updateMaxSpill()`.

Previously the temps are:

```
;  TEMP_01                                     int  ->  [r11-0x110]
;  TEMP_02                                    long  ->  [r11-0x118]
```

TEMP_02 is unused and we need one more int temp. When it is spilled, since the type of PUTARG_REG is TYP_LONG, a wrong type of temp was generated. I think we need to treat them as two separated INTs.
And the new commit now generates temps correctly.

```
;  TEMP_02                                     int  ->  [r11-0x110]
;  TEMP_01                                     int  ->  [r11-0x114]
```

File: src/jit/lsra.cpp [hunk 5]
```diff
@@ -8613,6 +8622,15 @@ void LinearScan::updateMaxSpill(RefPosition* refPosition)
                     ReturnTypeDesc* retTypeDesc = treeNode->AsCall()->GetReturnTypeDesc();
                     typ                         = retTypeDesc->GetReturnRegType(refPosition->getMultiRegIdx());
                 }
+#ifdef _TARGET_ARM_
+                else if (treeNode->OperIsPutArgReg())
+                {
+                    // For double arg regs, the type is changed to long since they must be passed via `r0-r3`.
+                    // However when they get spilled, they should be treated as separated int registers.
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: I think that this is just the case for `ARM_SOFTFP`, right? In other cases, an actual `TYP_LONG` would have been decomposed, so it would be better to put this under `#ifdef ARM_SOFTFP`.

Comment (wateret) [inline src/jit/lsra.cpp]: @CarolEidt Right, I'll fix it.

**Comment by wateret** [comment]
@CarolEidt With a fix for your comment and rebasing, it is ready to get merged. Thanks!
