### PR TITLE
Fix ckfinite for doubles for RyuJIT/x86

### LINKED ISSUE #3549: RyuJIT x86: Code generation/encoding issue for ckfinite
These tests generate the following assert:
Assert failure(PID 128 [0x00000080], Thread: 11276 [0x2c0c]): Assertion failed 'size <= EA_PTRSIZE || IsSSEOrAVXInstruction(ins)'
File: d:\git\coreclr\src\jit\emitxarch.cpp Line: 3371

It is generating a mov from fp to int register, but is assuming that it can move a double to a long this way.

JIT\IL_Conformance\Old\Conformance_Base\sub_r8\sub_r8.cmd
in '_sub:checkfinite(double):int' (IL size 127)
JIT\IL_Conformance\Old\Conformance_Base\ckfinite_r8\ckfinite_r8.cmd
in '_ckfinite:r8(double):int' (IL size 62)
JIT\Regression\VS-ia64-JIT\M00\b108366\b108366\b108366.cmd
in '_div:checkfinite(double):int' (IL size 129)
JIT\IL_Conformance\Old\Conformance_Base\add_r8\add_r8.cmd
in '_add:checkfinite(double):int' (IL size 127)
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b323557\b323557-ret\b323557-ret.cmd
in 'FullProof:Test():int' (IL size 77)
JIT\IL_Conformance\Old\Conformance_Base\rem_r8\rem_r8.cmd
in '_rem:checkfinite(double):int' (IL size 122)
JIT\IL_Conformance\Old\Conformance_Base\div_r8\div_r8.cmd
in '_div:checkfinite(double):int' (IL size 129)
JIT\IL_Conformance\Old\Conformance_Base\ldc_ckfinite_r8\ldc_ckfinite_r8.cmd
in '_ckfinite:r8_0(double):int' (IL size 72)
JIT\IL_Conformance\Old\Conformance_Base\neg_r8\neg_r8.cmd
in '_neg:checkfinite(double):int' (IL size 127)
JIT\IL_Conformance\Old\Base\ckfinite\ckfinite.cmd
in '_ckfinite:_ckfinite(double):int' (IL size 29)
JIT\IL_Conformance\Old\Conformance_Base\mul_r8\mul_r8.cmd
in '_mul:checkfinite(double):int' (IL size 127)

### PR DESCRIPTION
**Pull request by BruceForstall**
On x86, we can't simply load a double from an xmm reg into a
64-bit integer register. It turns out we only need the high
32 bits for the instruction. But there is no SSE2 instruction
to copy just those bits to the integer registers. So, first,
to a shuffle to swap the first 32 and 2nd 32 bits in the xmm
register. Then, do the xmm2i mov and ckfinite check. Then,
swap the bits back into the original locations so we can return
the correct value in the target register.

Fixes #3549.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@sivarv @adiaaida PTAL
/cc @dotnet/jit-contrib

File: src/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -7377,14 +7377,48 @@ CodeGen::genCkfinite(GenTreePtr treeNode)
...
+    if (targetType == TYP_DOUBLE)
+    {
+        if (treeNode->gtRegNum != op1->gtRegNum)
+        {
+            inst_RV_RV(ins_Copy(targetType), targetReg, op1->gtRegNum, targetType);
+        }
+        inst_RV_RV_IV(INS_shufps, EA_16BYTE, targetReg, targetReg, 0xb1);
+    }
+    inst_RV_RV(ins_CopyFloatToInt(TYP_FLOAT, TYP_INT), op1->gtRegNum, tmpReg, TYP_FLOAT);
+#endif // !_TARGET_AMD64_
```
Comment (CarolEidt) [inline src/jit/codegenxarch.cpp]: A couple of minor suggestions:
1. It would be nice to have a comment outside the #ifdefs that talks about what needs to be done (if the exponent is all 1's, throw ArithmeticException, otherwise copy the value to targetReg. Then, in the #ifdefs you can talk about how that's done in each case.
2. It would also be nice to extract the common parts (getting the targetReg, calling genConsumeReg and ins_CopyFloatToInt).

**Comment by CarolEidt** [comment]
LGTM with a couple of optional suggestions.

File: src/jit/codegenxarch.cpp [hunk 2]
```diff
@@ -7377,14 +7377,48 @@ CodeGen::genCkfinite(GenTreePtr treeNode)
...
+    //    and tmpReg, <mask>
+    //    cmp tmpReg, <mask>
+    //    je <throw block>
+    //    shufps targetReg, targetReg, 0xB1	// ZWXY => WZYX
+
+    genConsumeReg(op1);
+    regNumber targetReg = treeNode->gtRegNum;
+    if (targetType == TYP_DOUBLE)
+    {
+        if (treeNode->gtRegNum != op1->gtRegNum)
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: treeNode->gtRegNum can be replaced with targetReg here.

File: src/jit/codegenxarch.cpp [hunk 3]
```diff
@@ -7393,11 +7427,25 @@ CodeGen::genCkfinite(GenTreePtr treeNode)
...
+        inst_RV_RV_IV(INS_shufps, EA_16BYTE, targetReg, targetReg, 0xb1);
+    }
+    else
+    {
+        if (treeNode->gtRegNum != op1->gtRegNum)
+        {
+            inst_RV_RV(ins_Copy(targetType), targetReg, op1->gtRegNum, targetType);
+        }
+    }
+#endif // !_TARGET_AMD64_
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: IMO,  #ifdefs at multiple places is reducing the readability of logic and also one has to be careful while making fixes/improvements to this routine in future.  My suggestion is structure this on the below lines

```
// common to x86 and x64
GenTree* op1 = treeNode->GetOp1();
regNumber op1Reg = genConsumeReg(op1);
regNumber targetReg = treeNode->gtRegNum;
var_types targetType = treeNode->TypeGet();
int expMask = (targetType == TYP_FLOAT) ? 0x7F800000 : 0x7FF00000;

// Extract reserved reg 
assert(treeNode->gtRsvdRegs != RBM_NONE);
assert(genCountBits(treeNode->gtRsvdRegs) == 1);
regNumber tmpReg = genRegNumFromMask(treeNode->gtRsvdRegs);

#ifdef _TARGET_64BIT_
 // x64 comple implementation goes here
# else
 // x86 complete implementation goes here
# endif

genProduceReg(treeNode);

```

File: src/jit/codegenxarch.cpp [hunk 4]
```diff
@@ -7393,11 +7427,25 @@ CodeGen::genCkfinite(GenTreePtr treeNode)
...
+#ifdef _TARGET_AMD64_
     // if it is a finite value copy it to targetReg
     if (treeNode->gtRegNum != op1->gtRegNum)
     {
         inst_RV_RV(ins_Copy(targetType), treeNode->gtRegNum, op1->gtRegNum, targetType);
     }
+#else // !_TARGET_AMD64_
+    if (targetType == TYP_DOUBLE)
+    {
+        inst_RV_RV_IV(INS_shufps, EA_16BYTE, targetReg, targetReg, 0xb1);
```
Comment (sivarv) [inline src/jit/codegenxarch.cpp]: We don't always have to generate shufps here.  If targetReg != op1->gtRegNum, we can generate "movaps targetReg, op1->gtRegnum".  Note that movaps is faster and smaller than shufps.

**Comment by kyulee1** [comment]
For my education, do we have a CPU ID check for Jit code generation? If that is the case, we could simply emit `pextrd` to extract a particular portion of xmm to integer register if SSE4> is supported which is actually quite common case in the modern hardware.

**Comment by CarolEidt** [comment]
@kyulee1 I believe it has been the practice to restrict x86 to SSE2, and x64 to SSE4.2(?) or AVX2, in order to align with the minimum required hardware for Windows, and to limit the test matrix for supporting too many configurations. That said, when we add SIMD support to x86 we will have at least one additional configuration to support anyway - so it may be worth doing this.

**Comment by sivarv** [comment]
AFAIK, min bar for x64 Windows is SSE2.  Hence x64 CLR default implementation will stick to SSE2.
When we added SIMD support to x64, we added CPU ID check to see whether AVX2 is supported. But all that logic is confined to x64 target only (see EEJItManager::SetCPUInfo().  In fact we enable SSE4/AVX/AVX2 detection logic in VM to let JIT do more CPU specific changes.  As Carol said, the limiting factor is testing matrix.

**Comment by BruceForstall** [comment]
I refactored this more along the lines of Siva's suggestion. It was hard to factor out too much without adding #ifdefs, so I opted for more duplicated (simple) code rather than more #ifdefs.

**Comment by sivarv** [comment]
Looks good.
