### PR TITLE
Stop unloading the profiler on shutdown to prevent segfaults on background threads

### LINKED ISSUE #26687: pProfInterface is used after being freed by TerminateProfiling
It seems that `pProfInterface` can be accessed by `ProfileEnter`/`ProfileLeave`/`ProfileTailcall` callbacks after `TerminateProfiling()` was called.

I was running our tests Pri1 with a sample profiler (https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI/ELTProfiler) on linux-arm64 against my PR https://github.com/dotnet/coreclr/pull/26460 and I hit segmentation faults in GC/Scenarios/FinalizeTimeout test. 

The issue can also be reproduced on linux-x64. 

**What happens:**
1. `ProfilingAPIUtility::TerminateProfiling()` is called during system shutdown. After that point  `pProfInterface` is freed and set to `nullptr`.
2. `ProfileEnter` or `ProfileLeave` callback is called by https://github.com/dotnet/coreclr/blob/9c8ba7773e506db05016f1c278a7a1ea27816dbf/tests/src/GC/Scenarios/FinalizeTimeout/FinalizeTimeout.cs#L75
from a finalizer thread.
3. Asserts when tries to access  `pProfInterface`  (e.g. https://github.com/dotnet/coreclr/blob/master/src/vm/proftoeeinterfaceimpl.cpp#L10259)

**Steps to repro:**
1) build CorProfiler.so - I suggest to alter the code in a sample profiler by removing the printf-s in EnterStub, LeaveStub and TailcallStub in CorProfiler.cpp to avoid cluttering your output.
2) create file FinalizeTimeoutUnderProfiles.lldb with the following steps:
```
b ProfilingAPIUtility::LoadProfiler
r
watchpoint set expression -- &g_profControlBlock.pProfInterface.m_val
cont
cont
```
3) set the environment 
```
export CORECLR_ENABLE_PROFILING=1
export CORECLR_PROFILER={cf0d821e-299b-5307-a3d8-b283c03916dd}
export CORECLR_PROFILER_PATH=<Path to CorProfiler.so>
export CORE_ROOT=<Path to coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root>
```

4) run the test under LLDB
```
lldb-8 -s FinalizeTimeoutUnderProfiles.lldb -- $CORE_ROOT/corerun $CORE_ROOT/../../GC/Scenarios/FinalizeTimeout/FinalizeTimeout/FinalizeTimeout.dll
```

You will see that the debugger will stop at two watchpoints - the first time is during ProfilingAPIUtility::LoadProfiler, the second time - during ProfilingAPIUtility::TerminateProfiling(). 

Then it will stop during SIGSEGV.

@davmason @noahfalk Is this a supported scenario for profiling?
cc @dotnet/dotnet-diag 

**Related issues:** #22176 #22712

### PR DESCRIPTION
**Pull request by davmason**
Fixes #26687

On Linux we were seeing profilers crash in ELT hooks because the profiler would be shut down before all managed threads had exited. These checks will prevent slow path ELT from crashing, profiler vendors will have to deal with fast path ELT calls that come in after the profiler is shut down.

### CODE REVIEW

File: src/vm/proftoeeinterfaceimpl.cpp [hunk 1]
```diff
@@ -10235,11 +10235,15 @@ HCIMPL2(EXTERN_C void, ProfileEnter, UINT_PTR clientData, void * platformSpecifi
 
 #ifdef PROFILING_SUPPORTED
 
+    // We might have already torn down the profiler, if so we need to abort.
+    if (g_profControlBlock.curProfStatus.Get() != kProfStatusActive
```
Comment (jkotas) [inline src/vm/proftoeeinterfaceimpl.cpp]: What happens if the profiler is torn down right after we do this check, but before we actually call it below?

Comment (davmason) [reply src/vm/proftoeeinterfaceimpl.cpp]: Yeah, there are all sorts of races here. I realize now that even the check can race, depending on the order of events `g_profControlBlock.pProfInterface` could be set to null after `g_profControlBlock.pProfInterface.Load() == NULL` and then `g_profControlBlock.pProfInterface->GetEnterHook()          == NULL` would AV. I need to rework this entirely.

**Comment by davmason** [comment]
Looking at why this happens on Linux and not Windows it's because we don't set `g_fProcessDetach` on Linux. Talking to @janvorli this is on purpose, and we should try to avoid doing any checks about why the runtime is terminating. We already would skip freeing the profiler in many cases on Windows, I think the only safe thing to do here is to stop freeing the profiler on shutdown altogether. It may affect some profilers, but I believe they will be able to either free what they need to in the `Shutdown` callback or when the OS frees the library after we exit.

The only other options are to continue crashing sometimes or to put expensive synchronization on a hot path in `ProfilerEnter`,
