### PR TITLE
Set overflow flag for add/sub hi on x86 TYP_LONG

### LINKED ISSUE #4596: RyuJIT x86: Silent bad codegen on add/subtract with overflow for TYP_LONG
We are failing to handle overflow correctly on GT_ADD and GT_SUB with TYP_LONG on x86 RyuJIT. When we perform an operation that has overflow, the generated code produces the wrong output. This is causing the following tests to fail:

JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_i8\ldc_add_ovf_i8.cmd
JIT\IL_Conformance\Old\Conformance_Base\ldc_sub_ovf_i8\ldc_sub_ovf_i8.cmd
JIT\IL_Conformance\Old\Conformance_Base\add_ovf_i8\add_ovf_i8.cmd
JIT\IL_Conformance\Old\Conformance_Base\sub_ovf_i8\sub_ovf_i8.cmd
JIT\IL_Conformance\Old\Base\sub_ovf\sub_ovf.cmd

### PR DESCRIPTION
**Pull request by adiaaida**
When we create the hi operation for add and sub on TYP_LONG, we don't
carry the overflow flag to the hi operation. This change sets the overflow
flag on hiResult in lower if it was set on loResult, and adds GT_ADD_HI
and GT_SUB_HI to the operations that can have overflow. We also need to
pass the unsigned flag to the high part in the instance that we are
dealing with an add or subtract with overflow. Fixes #4596.

### CODE REVIEW

**Comment by adiaaida** [comment]
@BruceForstall PTAL
/cc: @dotnet/jit-contrib

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -462,6 +462,17 @@ void Lowering::DecomposeNode(GenTreePtr* pTree, Compiler::fgWalkData* data)
...
+            if (oper == GT_ADD || oper == GT_SUB)
+            {
+                if (loResult->gtOverflow())
+                {
+                    hiResult->gtFlags |= GTF_OVERFLOW;
+                    if (loResult->gtFlags & GTF_UNSIGNED)
+                    {
+                        hiResult->gtFlags |= GTF_UNSIGNED;
+                    }
+                }
```
Comment (BruceForstall) [inline src/jit/lower.cpp]: should we unconditionally propagate GTF_UNSIGNED (not just for add/sub, or only for overflow-possible nodes), e.g.
    hiResult->gtFlags |= (loResult->gtFlags & GTF_UNSIGNED);
?

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -462,6 +462,17 @@ void Lowering::DecomposeNode(GenTreePtr* pTree, Compiler::fgWalkData* data)
             hiOp2->gtNext      = hiResult;
             hiResult->gtPrev   = hiOp2;
 
+            if (oper == GT_ADD || oper == GT_SUB)
+            {
+                if (loResult->gtOverflow())
+                {
+                    hiResult->gtFlags |= GTF_OVERFLOW;
```
Comment (BruceForstall) [inline src/jit/lower.cpp]: Don't we also want to clear the bit on the loResult? Presumably any overflow/carry from the low 32 bits will will get consumed in the upper 32 bits computation.

File: src/jit/lower.cpp (hunk 1 above)
Comment (adiaaida) [inline src/jit/lower.cpp]: I tried that, but it caused another test to fail, so I'm not sure.

File: src/jit/lower.cpp (hunk 2 above)
Comment (adiaaida) [inline src/jit/lower.cpp]: It appears we don't have any tests that test this. I've run the suite with clearing the bit and without and both pass the tests.

Comment (BruceForstall) [inline src/jit/lower.cpp]: You should be able to find a preexisting test that has the GTF_OVERFLOW bit set of LONG, and look at the generated code. Maybe shouldn't be hard to generate a test case that does overflow-checking long that also generates overflow from the low 32 bits, e.g., adding 0x80000000 + 0x80000000.

Comment (mikedn) [inline src/jit/lower.cpp]: If you don't clear GTF_OVERFLOW from loResult then codegen will very likely generate an overflow check for the lo part at the end of `genCodeForBinary`. That's not right, the overflow check should be generated only for the hi part, for the lo part the overflow condition is meaningless.

File: src/jit/lower.cpp (hunk 1 above)
Comment (CarolEidt) [inline src/jit/lower.cpp]: It would be good to understand why this would cause another test to fail - it seems that we would want to always propagate it, if present.

**Comment by BruceForstall** [comment]
LGTM
