### PR TITLE
[RyuJIT/arm32] Add support for tailcall via helper

### LINKED ISSUE #11844: [RyuJIT/arm32] Assertion failed 'node->IsLIR()'
At lir.cpp Line: 1469

Example:
```
Assert failure(PID 8164 [0x00001fe4], Thread: 4784 [0x12b0]): Assertion failed 'node->IsLIR()' in 'JitTest.Test:TestMain()' (IL size 36)

    File: c:\gh\coreclr\src\jit\lir.cpp Line: 1469
    Image: c:\brucefo\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

Tests with this assert:
```
JIT\Directed\IL\Tailcall\jitTailcall1\jitTailcall1.cmd
JIT\jit64\mcc\interop\mcc_i36\mcc_i36.cmd
JIT\jit64\mcc\interop\mcc_i56\mcc_i56.cmd
JIT\jit64\mcc\interop\mcc_i66\mcc_i66.cmd
JIT\jit64\mcc\interop\mcc_i76\mcc_i76.cmd
JIT\Methodical\Invoke\fptr\_il_dbgftn_t\_il_dbgftn_t.cmd
JIT\Methodical\Invoke\fptr\_il_relftn_t\_il_relftn_t.cmd
JIT\Methodical\nonvirtualcall\tailcall_d\tailcall_d.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b10894\b10894\b10894.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b26957\b26957\b26957.cmd
JIT\Regression\CLR-x86-JIT\V1-M10\b02043\b02043\b02043.cmd
JIT\Regression\VS-ia64-JIT\V1.2-M02\b102844\b102844\b102844.cmd
JIT\Regression\VS-ia64-JIT\V1.2-M02\b14364\b14364\b14364.cmd
```

### PR DESCRIPTION
**Pull request by BruceForstall**
Essentially, just do what AMD64 was doing in fgMorphTailCall()
and LowerTailCallViaHelper(). All the VM support for tailcall
via helper is already there (and used by legacy backend).

Fixes #11844, #11836

### CODE REVIEW

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -7671,12 +7671,13 @@ void Compiler::fgMorphTailCall(GenTreeCall* call)
...
-    // will generate
-    GenTreePtr arg = new (this, GT_NOP) GenTreeOp(GT_NOP, TYP_I_IMPL);
+    // Now inject a placeholder for the real call target that codegen will generate
 #ifdef LEGACY_BACKEND
+    GenTreePtr arg = new (this, GT_NOP) GenTreeOp(GT_NOP, TYP_I_IMPL);
     codeGen->genMarkTreeInReg(arg, REG_TAILCALL_ADDR);
-#endif
+#else // !LEGACY_BACKEND
+    GenTreePtr arg = gtNewIconNode(0, TYP_I_IMPL);
+#endif // !LEGACY_BACKEND
```
Comment (BruceForstall) [inline src/jit/morph.cpp]: I made these changes, and the ones below, by adding `#ifdef` to avoid changing any `LEGACY_BACKEND` behavior, but to make the code do just what the amd64 code does.

**Comment by BruceForstall** [comment]
@jashook @pgavlin PTAL
cc @dotnet/arm32-contrib @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@DrewScoggins @dpodder For `Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness` (https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_full_opt_ryujit_smoketest_prtest/379/) I see:
```
[Wed 08/30/2017][ 9:25:41] $ py.exe "D:\j\workspace\perf_perflab_---1c2b0529\Microsoft.Benchview.JSONFormat\tools\submission.py" measurement.json  --build "D:\j\workspace\perf_perflab_---1c2b0529\build.json" --machine-data "D:\j\workspace\perf_perflab_---1c2b0529\machinedata.json" --metadata "D:\j\workspace\perf_perflab_---1c2b0529\submission-metadata.json" --group "CoreCLR" --type "private" --config-name "Release" --config Configuration "Release" --config OS "Windows_NT" --config Profile "Off" --config OptLevel "full_opt" --config JitName  "ryujit" --architecture "x86" --machinepool "PerfSnake"
[2017-08-30 09:25][ERROR] <class 'ValueError'>: Specified submission-metadata json file "D:\j\workspace\perf_perflab_---1c2b0529\submission-metadata.json" does not exist.
[2017-08-30 09:25][ERROR] Traceback (most recent call last):
  File "D:\j\workspace\perf_perflab_---1c2b0529\Microsoft.Benchview.JSONFormat\tools\submission.py", line 121, in main
    submission = read_submission_metadata(args['metadata'])
  File "D:\j\workspace\perf_perflab_---1c2b0529\Microsoft.Benchview.JSONFormat\tools\benchview\format\JSONReaders.py", line 70, in read_submission_metadata
    raise ValueError('Specified submission-metadata json file "{0}" does not exist.'.format(filename))
ValueError: Specified submission-metadata json file "D:\j\workspace\perf_perflab_---1c2b0529\submission-metadata.json" does not exist.


dotnet-bot@WIN2012-885350 "D:\j\workspace\perf_perflab_---1c2b0529\bin\sandbox"
[Wed 08/30/2017][ 9:25:41] [ERROR] Creating BenchView submission data failed.
Build step 'Execute Windows batch command' marked build as failure
```
Is this a know problem?

**Comment by dpodder** [comment]
@BruceForstall Known issue, fix is in #13666 just pending merge.

**Comment by dpodder** [comment]
@dotnet-bot
test Windows_NT x64 full_opt ryujit CoreCLR Perf Tests Correctness 
test Windows_NT x86 full_opt legacy_backend CoreCLR Perf Tests Correctness
test Windows_NT x86 full_opt ryujit CoreCLR Perf Tests Correctness

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Build and Test

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -7671,12 +7671,13 @@ void Compiler::fgMorphTailCall(GenTreeCall* call)
         call->gtFlags |= GTF_EXCEPT;
     }
 
-    // Now inject a placeholder for the real call target that codegen
-    // will generate
-    GenTreePtr arg = new (this, GT_NOP) GenTreeOp(GT_NOP, TYP_I_IMPL);
+// Now inject a placeholder for the real call target that codegen will generate
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: Is there a reason that amd64 (and now arm) use a constant zero node rather than a NOP? Or is it just historical? It appears that it is just removed without really looking at it.
Also, you might want to add a comment anchor here, or you could just declare the arg, e.g.:
```
GenTree* arg;
```
and then assign its value in the different arms of the `#ifdef`. IMO that looks a bit better than the ugly anchor

Comment (BruceForstall) [reply src/jit/morph.cpp]: > Is there a reason that amd64 (and now arm) use a constant zero node rather than a NOP? Or is it just historical?

Well, the argument is for a call target address, which would be a TYP_I_IMPL, and not TYP_VOID. One assert I was seeing was a type mismatch as a result of the void.

Comment (CarolEidt) [reply src/jit/morph.cpp]: Makes sense, thanks.

**Comment by BruceForstall** [comment]
@jashook do you know if the arm failure here is due to an infra issue?

**Comment by BruceForstall** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_prtest/456/

@dotnet-bot test Windows_NT arm Cross Checked Build and Test
