### PR TITLE
Only lock unlocked registers in `rsUnspillRegPair`.

### LINKED ISSUE #12910: [ARM32][LEGACY_BACKEND] Assertion failed '(rsMaskLock & regMask) == 0'
e.g.
```
Assert failure(PID 6868 [0x00001ad4], Thread: 8788 [0x2254]): Assertion failed '(rsMaskLock & regMask) == 0' in 'System.Reflection.Metadata.Ecma335.MethodTableReader:GetRva(struct):int:this' (IL size 40)

    File: c:\dev\coreclr\src\jit\regset.cpp Line: 332
    Image: c:\dev\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

This is causing the following tests to fail:
### JitStressRegs=1
- Compilation.cmd_11084
- ConvertToInt32_17.cmd_859
- ConvertToUInt3213.cmd_447
- CscBench.cmd_3424
### JitStress=1, JitStressRegs=1
- b70994.cmd_9671
- Compilation.cmd_11084
- ConvertToInt32_17.cmd_859
- ConvertToUInt3213.cmd_447
- CscBench.cmd_3424

### PR DESCRIPTION
**Pull request by pgavlin**
`rsUnspillRegPair` needs to lock the hi/lo part of the reg pair when
unspilling the lo/hi part in order to ensure that the two parts of the
pair do not end up in the same register. However, the register to be
locked may already be locked if it is a multi-use register. In this case
`rsUnspillRegPair` does not need to re-lock the register.

Fixes #12910.

### CODE REVIEW

**Comment by pgavlin** [comment]
@BruceForstall @CarolEidt @dotnet/jit-contrib PTAL

File: src/jit/codegenlegacy.cpp [hunk 1]
```diff
@@ -3788,7 +3788,7 @@ void CodeGen::genCondJumpLng(GenTreePtr cond, BasicBlock* jumpTrue, BasicBlock*
 #if CPU_LOAD_STORE_ARCH
         /* Generate the second operand into a register pair */
         // Fix 388442 ARM JitStress WP7
```
Comment (CarolEidt) [inline src/jit/codegenlegacy.cpp]: There was apparently some historical bug associated with this code - did you happen to look into that? It's odd that it would be explicitly passing `false` here (since that's the default).

**Comment by BruceForstall** [comment]
I don't understand why this fixes the issue.

Is the assert from the line just below what you changed, namely:
```
regSet.rsLockUsedReg(genRegPairMask(op2->gtRegPair));
```
That would indicate that the previous
```
genComputeRegPair(op2, REG_PAIR_NONE, genRegPairMask(op1->gtRegPair), RegSet::KEEP_REG, false);
```
computed op2 into a reg pair that was already locked, or it locked it, neither of which should be true. So isn't that the underlying problem?

**Comment by pgavlin** [comment]
> I don't understand why this fixes the issue.

It doesn't, in fact. I'm working on a new fix now.

**Comment by pgavlin** [comment]
To elaborate on the problem a little bit more: the assertion is arising because `op1` and `op2` are concurrently live and end up assigned to conflicting register pairs. We either need some way to indicate to `genComputeRegPair` that the operand passed to `avoidMask` is not in fact a recommendation, but a requirement, or we need some way to ensure that `genRecoverRegPair` is not stuck trying to use one of the locked `op2` registers. I'm investigating both options.

**Comment by BruceForstall** [comment]
> or we need some way to ensure that genRecoverRegPair is not stuck trying to use one of the locked op2 registers.

If op2 caused op1's pair to spill, the genRecoverRegPair should be able to unspill it. There should only be two registers locked by op2, and also thus only two registers locked in total, so genRecoverRegPair should be able to find any other pair of registers to spill while it unspills op1. There are certainly plenty more registers available.

**Comment by pgavlin** [comment]
> If op2 caused op1's pair to spill, the genRecoverRegPair should be able to unspill it. There should only be two registers locked by op2, and also thus only two registers locked in total, so genRecoverRegPair should be able to find any other pair of registers to spill while it unspills op1. There are certainly plenty more registers available.

Yeah, I misunderstood the original assert. I've update the PR and the description with a new fix.

File: src/jit/regset.cpp [hunk 2]
```diff
@@ -2666,17 +2666,24 @@ void RegSet::rsUnspillRegPair(GenTreePtr tree, regMaskTP needReg, KeepReg keepRe
 
         if (rsIsTreeInReg(regHi, tree))
         {
-            /* Temporarily lock the high part */
-
-            rsLockUsedReg(genRegMask(regHi));
+            // Temporarily lock the high part if necessary. If this register is a multi-use register that is shared
+            // with another tree, the register may already be locked.
+            const regMaskTP regHiMask = genRegMask(regHi);
```
Comment (BruceForstall) [inline src/jit/regset.cpp]: It seems very strange to me that someone else has the register locked. Who locked it? How can it become multi-used and also locked?

Comment (pgavlin) [inline src/jit/regset.cpp]: [This code](https://github.com/dotnet/coreclr/blob/master/src/jit/codegenlegacy.cpp#L3788-L3794) locks the registers used by a conditional jump's `op2` before unspilling its `op1`. These operands may share a register if that register is multi-use, so that register may be locked when we enter this function.

**Comment by pgavlin** [comment]
@dotnet-bot 
test Tizen armel Cross Debug Build
test Tizen armel Cross Release Build

**Comment by pgavlin** [comment]
@dotnet-bot test Tizen armel Cross Release Build
