### PR TITLE
Fix GCStress for multireg returns. 

### LINKED ISSUE #23199: [x64] Test failed: ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst/111/

**Failed tests:**
ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh

**Log:**
```
ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh [FAIL]
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh: line 252: 28561 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        /n/nReturn code:      1/nRaw output file:      /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/ilasm/System/Reports/ilasm.System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.output.txt/nRaw output:/nBEGIN EXECUTION
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun MethodImplOptionsTests.exe ''
        AggressiveOptimizationTest
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/n> /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/tests/Linux.x64.Checked/TestWrappers/ilasm.System/ilasm.System.XUnitWrapper.cs(109,0): at ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh()
```

### PR DESCRIPTION
**Pull request by sandreenko**
Fixes #23199, thanks @BruceForstall for finding the bug.

0c16be11a2: Add a repro test.

353637b8cd: Fix DoGcStress for multireg return with GC pointers.

Note: we are overprotecting registers here, for example, we always protect 2 registers even if only one is returned. GCStress infrastructure should be able to tolerate extra registers. We have had such examples before (for example when returned a struct without pointers we protected the first reg anyway).

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @BruceForstall @dotnet/jit-contrib

File: src/vm/gccover.cpp [hunk 1]
```diff
@@ -1692,22 +1692,38 @@ void DoGcStress (PCONTEXT regs, MethodDesc *pMD)
 
 #if defined(_TARGET_X86_) || defined(_TARGET_AMD64_) || defined(_TARGET_ARM_) || defined(_TARGET_ARM64_)
     FrameWithCookie<GCFrame> gcFrame;
-    DWORD_PTR retVal = 0;
+
+    OBJECTREF* retPointer = 0;
+    UINT numObjRefs = 1;
+#if defined(UNIX_AMD64_ABI) || defined(_TARGET_ARM64_)
+    // Multireg return.
```
Comment (CarolEidt) [inline src/vm/gccover.cpp]: Just to be clear, I might say "These targets support multireg returns."

Comment (sandreenko) [reply src/vm/gccover.cpp]: Fixed, thank you.

**Comment by sandreenko** [comment]
The failures were unstable timeout and windows infra problems (opened https://github.com/dotnet/coreclr/issues/24372 to track that).

File: tests/src/JIT/Regression/JitBlue/GitHub_23199/GitHub_23199.cs [hunk 2]
```diff
@@ -0,0 +1,50 @@
+using System;
+using System.Diagnostics;
+using System.Runtime.CompilerServices;
+
+// The test returns 2*pointer size struct where the second pointer is a managed object
+// and need a gc reference. On amd64 Unix and arm64 such structs are returned via registers.
+// The was a problem in GCStress infrastracture where it did not mark this pointer alive.
```
Comment (BruceForstall) [inline tests/src/JIT/Regression/JitBlue/GitHub_23199/GitHub_23199.cs]: typo: infrastracture => infrastructure

File: src/vm/gccover.cpp [hunk 3]
```diff
@@ -1692,22 +1692,38 @@ void DoGcStress (PCONTEXT regs, MethodDesc *pMD)
 
 #if defined(_TARGET_X86_) || defined(_TARGET_AMD64_) || defined(_TARGET_ARM_) || defined(_TARGET_ARM64_)
     FrameWithCookie<GCFrame> gcFrame;
-    DWORD_PTR retVal = 0;
+
+    OBJECTREF* retPointer = 0;
+    UINT numObjRefs = 1;
+#if defined(UNIX_AMD64_ABI) || defined(_TARGET_ARM64_)
+    // These targets support multireg returns.
```
[the remark this answers is not in the document]
Comment (sandreenko) [reply src/vm/gccover.cpp]: Thanks, I will add it in a next PR after I fix GCStress on Windows.
