### PR TITLE
Fix VEX.vvvv encoding for AVX.BlendVariable

### LINKED ISSUE #18875: [RyuJIT] Avx.BlendVariable has incorrect VEX.vvvv encoding with containment form
https://github.com/dotnet/coreclr/issues/18815 has been fixed by https://github.com/dotnet/coreclr/pull/18849, but a new bug appears that `vblendvp*` always uses the default VEX.vvvv (XMM0) to encode the first argument.

cc @CarolEidt @tannergooding

### PR DESCRIPTION
**Pull request by fiigii**
Fix #18875

@CarolEidt @tannergooding PTAL

### CODE REVIEW

**Comment by fiigii** [comment]
We have encountered this kind of issue so many times, and https://github.com/dotnet/coreclr/issues/18836 will help a lot to avoid it.

File: src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -13017,13 +13017,16 @@ size_t emitter::emitOutputInstr(insGroup* ig, instrDesc* id, BYTE** dp)
         {
             emitGetInsAmdCns(id, &cnsVal);
             code = insCodeRM(ins);
+            code = AddVexPrefixIfNeeded(ins, code, size);
```
Comment (tannergooding) [inline src/jit/emitxarch.cpp]: I don't believe this is the right fix....

The `Is4ByteSSE4OrAVXInstruction()` code paths tend to have slightly different handling for this (within `emitOutput*`, generally).

I think you need to update `emitOutputAM` to get this working properly... In this case, it looks like its failing because `emitOutputAM` only calls `insEncode3456` for `DstDstSrc` or `DstSrcSrc` AVX instructions for which `INS_blendvps` is not included (https://github.com/fiigii/coreclr/blob/54c2e6f8e14b8ba349880e7e83eec5f97a7c4561/src/jit/emitxarch.cpp#L9379).

Comment (fiigii) [reply src/jit/emitxarch.cpp]: Will change, thanks!

Comment (tannergooding) [reply src/jit/emitxarch.cpp]: It would help if this entire mess was cleaned up to be more consistent, where possible 😄

Comment (tannergooding) [reply src/jit/emitxarch.cpp]: I think we have a bug tracking it already though

Comment (fiigii) [reply src/jit/emitxarch.cpp]: Fixed.

**Comment by fiigii** [comment]
@tannergooding Thanks! Logged at https://github.com/dotnet/coreclr/issues/18877

**Comment by fiigii** [comment]
@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by tannergooding** [comment]
@dotnet-bot test Windows_NT x64 Checked jitincompletehwintrinsic please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Windows_NT x64 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Windows_NT x64 Checked jitnox86hwintrinsic please

@dotnet-bot test Windows_NT x86 Checked jitincompletehwintrinsic please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Windows_NT x86 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Windows_NT x86 Checked jitnox86hwintrinsic please

@dotnet-bot test Ubuntu x64 Checked jitincompletehwintrinsic please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnoavx2 please
@dotnet-bot test Ubuntu x64 Checked jitx86hwintrinsicnosimd please
@dotnet-bot test Ubuntu x64 Checked jitnox86hwintrinsic please
