### PR TITLE
Handle multi-reg PUTARG_STK nodes.

### LINKED ISSUE #6583: ARM64: Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)
C:\Users\DDJOIN\scratch\System.Private.CoreLib.dll Test compiled Assert failure(PID 9744 [0x00002610], Thread: 6016 [0x1780]): 
Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'Microsoft.Cci.PeWriter:WritePeToStream(ref,ref,ref,ref):bool:this' (IL size 908) File: d:\j\workspace\arm64_cross_c---f41ee988\src\jit\lsra.cpp Line: 3311
```
JIT\Performance\CodeQuality\Roslyn\CscBench.CscBench
managed\Compilation\Compilation.Compilation
```

### PR DESCRIPTION
**Pull request by pgavlin**
When FEATURE_MULTIREG_ARGS is true, a GT_PUTARG_STK node may have a
GT_LIST as a child if the child was originally a multi-reg argument.
Handle this case in `GenTreeUseEdgeIterator`.

Fixes #6583.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x64 Debug Build and Test

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm64 checked

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -8446,11 +8446,17 @@ GenTree** GenTreeUseEdgeIterator::GetNextUseEdge() const
...
+        // If FEATURE_MULTIREG_ARGS is enabled, so PUTARG_STK nodes also have special handling.
         case GT_CALL:
         case GT_PHI:
 #ifdef FEATURE_SIMD
         case GT_SIMD:
 #endif
+#if FEATURE_MULTIREG_ARGS
+        case GT_PUTARG_STK:
+#endif
+
```
Comment (briansull) [inline src/jit/gentree.cpp]: All of these break statements lead to  the
unreached() call outside of the switch.
If it is not expected to get to the unreached() then shouldn't we have an assert before the break

Comment (pgavlin) [inline src/jit/gentree.cpp]: We do want to hit the `unreached()` in these cases, as that is exactly what we expect. I could move these closer to the default case or add another `unreached()`, but the latter seems unnecessary.

**Comment by pgavlin** [comment]
@kyulee1 @briansull @jashook: the ARM64 infrastructure appears to be having some trouble.

File: src/jit/gentree.h [hunk 2]
```diff
@@ -1916,6 +1916,9 @@ class GenTreeUseEdgeIterator final
 #ifdef FEATURE_SIMD
     void MoveToNextSIMDUseEdge();
```
Comment (briansull) [inline src/jit/gentree.h]: The following method probably should not have a default parameter:

 `IteratorPair<GenTreeUseEdgeIterator> GenTree::UseEdges(bool expandMultiRegArgs = true);
`

Comment (briansull) [inline src/jit/gentree.h]: UseEdges() is called in  lir.cpp so it needs the default parameter.
No caller ever passes false for this :-( so maybe we can eliminate it.

Comment (pgavlin) [inline src/jit/gentree.h]: I am hopeful that we can eliminate this, but I'm not convinced. These functions are also used by `GenTree::Operands()`, and I can imagine that there are situations in which we want to iterate over the operands to a call but not expand multi-reg args. It might be worth eliminating the parameter until those cases have been found, but that should be addressed in a separate change.

**Comment by pgavlin** [comment]
@dotnet/jit-contrib PTAL as well. I was hoping to have a green ARM64 run before tagging any of y'all, but it looks like the infrastructure is having some trouble.

**Comment by rahku** [comment]
I working on making arm64 CI green again. But you should be getting test results now albeit few tets failures not related to your PR.

**Comment by jashook** [comment]
@dotnet/arm64-contrib looks like the ip addresses of our machines changed. Every arm64 task launch should fail until this is changed. Updating them now.

File: src/jit/gentree.cpp (hunk 1 above)
Comment (briansull) [inline src/jit/gentree.cpp]: Well maybe you can add a comment say that these cases are consider error cases because they should have been handled specially in GenTreeUseEdgeIterator::operator++()

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by jashook** [comment]
@dotnet/arm64-contrib **update**: most arm64 machines still have the same ip; however, the share was disconnected for some reason causing the server to crash. The problem has been mitigated by remounting the share and restarting the server.

**Comment by jashook** [comment]
@pgavlin please tell me if you experience more problems.

**Comment by briansull** [comment]
LGTM

**Comment by pgavlin** [comment]
@jashook: the ARM64 leg is still broken with the same failure.

**Comment by rahku** [comment]
this is not correct. you are getting test results now http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_prtest/345/testReport/

there are 4 failures and below two seem to be due to your PR. Other two are known and I have a PR out to disable them
JIT\Performance\CodeQuality\Roslyn\CscBench.CscBench
managed\Compilation\Compilation.Compilation

**Comment by pgavlin** [comment]
Okay, I see it now. It is confusing that the same error appears in the logs:

```
[arm64PostBuild] Fail to run C:\Users\dotnet-bot\client.exe 131.107.19.147  
```

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm64 checked

**Comment by pgavlin** [comment]
The x64 release failure is due to #6857.
