### PR TITLE
Preserve value numbers when morphing multiplication into shift.

### LINKED ISSUE #2920: JitStress: Assert fault in SP1a2
```
export COMPlus_JitStress=2
export COMPlus_ZapDisable=1

corerun JIT/Directed/StructPromote/SP1a2/SP1a2.exe
Assert failure(PID 7616 [0x00001dc0], Thread: 7616 [0x1dc0]): Assertion failed 'ad2->gtVNPair.GetLiberal() != ValueNumStore::NoVN' in 'SP1a2:Foo(int,struct,int):int' (IL size 30)
    File: /home/swaroops/git/coreclr/src/jit/morph.cpp Line: 4497
    Image: /home/swaroops/git/coreclr/bin/Product/Linux.x64.Debug/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 7616, Thread 7616/0x1dc0)' ****
  Assertion failed 'ad2->gtVNPair.GetLiberal() != ValueNumStore::NoVN' in 'SP1a2:Foo(int,struct,int):int' (IL size 30)

/home/swaroops/git/coreclr/src/jit/morph.cpp, Line: 4497

Abort - Kill program
Retry - Debug
Ignore - Keep running

Image:
/home/swaroops/git/coreclr/bin/Product/Linux.x64.Debug/corerun

********
/home/swaroops/bin/runn: line 3:  7616 Aborted                 (core dumped) ./corerun ~/test/$1.exe
134
```

### PR DESCRIPTION
**Pull request by erozenfeld**
This change fixes a morpher transformation of multiplication to shift
to preserve the value number of the tree since the new shift expression
will compute the same value as the old multiplication expression.
Without that change we were getting  asserts in fgMoveOpsLeft,
which expects to see value numbers on trees it transforms.

Closes #2920.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@briansull PTAL
/cc @dotnet/jit-contrib

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT jitstress1

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT jitstress2

File: src/jit/compiler.hpp [hunk 1]
```diff
@@ -1405,7 +1408,7 @@ inline
 void                GenTree::InitNodeSize(){}
 
 inline
-void                GenTree::SetOper(genTreeOps oper)
+void                GenTree::SetOper(genTreeOps oper, bool clearVN)
 {
     gtOper = oper;
```
Comment (briansull) [inline src/jit/compiler.hpp]: I don't think we have tried building the JIT without SMALL_TREE_NODES defined in quite sometime.
But you should go ahead and add the if (clearVM) logic here as well as it appears to just be missing.
The instance field gtVNPair is available with and without SMALL_TREE_NODES.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -10327,10 +10327,10 @@ GenTreePtr          Compiler::fgMorphSmpOp(GenTreePtr tree, MorphAddrContext* ma
...
                         assert(tree->OperGet() != oper);
 
-                        ValueNumPair vnp;
-                        vnp = tree->gtVNPair;  // Save the existing ValueNumber for 'tree'
-
-                        tree->SetOper(oper);
+                        // Keep the old ValueNumber for 'tree' as the new expr
+                        // will still compute the same value as before
+                        bool clearVN = false;
+                        tree->SetOper(oper, clearVN);
```
Comment (briansull) [inline src/jit/morph.cpp]: An option here to improve readability is to use a user defined enum like this:

enum ValueNumberUpdate = {CLEAR_VN, PRESERVE_VN);

Instead of using a bool and passing true or false.

File: src/jit/compiler.hpp (hunk 1 above)
Comment (erozenfeld) [inline src/jit/compiler.hpp]: Done.

File: src/jit/morph.cpp (hunk 2 above)
Comment (erozenfeld) [inline src/jit/morph.cpp]: Done.

**Comment by erozenfeld** [comment]
@briansull I addressed your feedback, PTAL.

**Comment by erozenfeld** [comment]
@dotnet-bot retest

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT jitstress1

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT jitstress2

**Comment by CarolEidt** [comment]
LGTM

**Comment by briansull** [comment]
LGTM
