### PR TITLE
Handle multiReg COPY

### LINKED ISSUE #19397: Assertion failed 'op1->OperGet() == GT_LONG || op1->OperGet() == GT_MUL_LONG'
x86 Checked Windows CoreFX JitStressRegs=8

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs8/554/consoleText

hundreds of instances of:
```
  Assert failure(PID 2868 [0x00000b34], Thread: 2232 [0x08b8]): Assertion failed 'op1->OperGet() == GT_LONG || op1->OperGet() == GT_MUL_LONG' in 'System.Text.OSEncoding:GetMaxByteCount(int):int:this' (IL size 55)
  
      File: d:\j\workspace\x86_checked_w---fb0ba759\src\jit\codegenxarch.cpp Line: 8653
      Image: D:\j\workspace\x86_checked_w---fb0ba759\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe
```

This has been failing for a while.

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by CarolEidt**
On x86, `MUL_LONG` wasn't considered a multi-reg node, as it should be, so that when it gets spilled or copied, the additional register will be correctly handled.
Also, the ARM and X86 versions of genStoreLongLclVar should be identical and shared (neither version were handling the copy of a `MUL_LONG`).
Finally, fix the LSRA dumping of multi-reg nodes.

Fix #19397

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x86 Checked jitstressregs8

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm Cross Debug Innerloop Build
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Debug Innerloop Build
@dotnet-bot test Windows_NT x64 Release CoreFX Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64 Release CoreFX Tests

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
@jashook @BruceForstall - the arm & arm64 jobs seem to be stuck, or seriously backed up. The arm64 leg that was started has been executing for 16 hours, and other jobs seem to be similarly taking a very long time. Is this a known issue?

File: src/jit/codegenxarch.cpp [hunk 1]
```diff
@@ -4535,24 +4535,21 @@ void CodeGen::genRegCopy(GenTree* treeNode)
     assert(treeNode->OperGet() == GT_COPY);
     GenTree* op1 = treeNode->gtOp.gtOp1;
 
-    if (op1->IsMultiRegCall())
+    if (op1->IsMultiRegNode())
```
Comment (AndyAyersMS) [inline src/jit/codegenxarch.cpp]: Do you want to add a banner comment while you're here?

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -747,18 +747,13 @@ int GenTree::GetRegisterDstCount() const
     {
         return (const_cast<GenTree*>(this))->AsPutArgSplit()->gtNumRegs;
     }
-    // A PUTARG_REG could be a MultiRegOp on ARM since we could move a double register to two int registers,
-    // either for all double parameters w/SoftFP or for varargs).
-    else
+#endif
+#if !defined(_TARGET_64BIT_)
+    else if (OperIsMultiRegOp())
```
Comment (AndyAyersMS) [inline src/jit/gentree.cpp]: Seems like this deserves a comment?

It is confusing that a multi reg op might only have one register destination.

File: src/jit/codegenlinear.cpp [hunk 3]
```diff
@@ -1947,3 +1947,63 @@ void CodeGen::genCodeForCast(GenTreeOp* tree)
...
+    else
+    {
+        assert((op1->gtSkipReloadOrCopy()->gtFlags & GTF_MUL_64RSLT) != 0);
+        // This is either a multi-reg MUL_LONG, or a multi-reg reload or copy.
+        assert(op1->IsMultiRegNode() && (op1->GetMultiRegCount() == 2));
+
+        // Stack store
+        getEmitter()->emitIns_S_R(ins_Store(TYP_INT), emitTypeSize(TYP_INT), op1->GetRegByIndex(0), lclNum, 0);
+        getEmitter()->emitIns_S_R(ins_Store(TYP_INT), emitTypeSize(TYP_INT), op1->GetRegByIndex(1), lclNum,
+                                  genTypeSize(TYP_INT));
```
[the remark this answers is not in the document]
Comment (mikedn) [reply src/jit/codegenlinear.cpp]: Hmm, might be better the other way around - just use `getEmitter()` everywhere. Or just use `m_cgEmitter`. There's just too much ceremony to access a class data member.

File: src/jit/codegenlinear.cpp [hunk 4]
```diff
@@ -1947,3 +1947,63 @@ void CodeGen::genCodeForCast(GenTreeOp* tree)
     }
     // The per-case functions call genProduceReg()
 }
+
+#if !defined(_TARGET_64BIT_)
+//-----------------------------------------------------------------------------
+//
+// Code Generation for Long integers
```
Comment (mikedn) [inline src/jit/codegenlinear.cpp]: Do we really need such a header?

File: src/jit/gentree.h [hunk 5]
```diff
@@ -1211,13 +1211,18 @@ struct GenTree
...
     bool OperIsMultiRegOp() const
     {
+#if !defined(_TARGET_64BIT_)
+        if (OperIs(GT_MUL_LONG))
+        {
+            return true;
+        }
 #if defined(_TARGET_ARM_)
-        if ((gtOper == GT_MUL_LONG) || (gtOper == GT_PUTARG_REG) || (gtOper == GT_BITCAST))
+        if (OperIs(GT_PUTARG_REG) || OperIs(GT_BITCAST))
```
Comment (mikedn) [inline src/jit/gentree.h]: `OperIs(GT_PUTARG_REG, GT_BITCAST)` ?

File: src/jit/codegenlinear.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (CarolEidt) [reply src/jit/codegenlinear.cpp]: Done.

File: src/jit/codegenxarch.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/codegenxarch.cpp]: Yes, good point. This method deserves a description.

File: src/jit/gentree.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/gentree.cpp]: Modified the code a bit and added a comment; on x86 it is always 2 (just MUL_LONG).

File: src/jit/codegenlinear.cpp (hunk 4 above)
Comment (CarolEidt) [reply src/jit/codegenlinear.cpp]: No; that was copied from the ARM version. I'll delete it.

**Comment by BruceForstall** [comment]
> @jashook @BruceForstall - the arm & arm64 jobs seem to be stuck, or seriously backed up. The arm64 leg that was started has been executing for 16 hours, and other jobs seem to be similarly taking a very long time. Is this a known issue?

There have been lots of issues with the Windows arm/arm64 builds: https://github.com/dotnet/core-eng/issues/4121. Still not fixed. And the Ubuntu arm32 machines had other problems, which is now apparently fixed.

**Comment by echesakovMSFT** [comment]
@CarolEidt GitHub_19397 test has failed in one of my PRs on **Windows_NT arm64 Cross Checked Innerloop Build and Test** -
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_tst_prtest/1465/

**Comment by CarolEidt** [comment]
@echesakovMSFT - thanks for letting me know. After several tries, the arm64 jobs were failing (elsewhere), so I went ahead and merged. You can open an issue (or I will) and I'll take a look.
