### PR TITLE
Fix check for initial induction variable value

### LINKED ISSUE #7906: JIT: loop detection: Initial value dominance test insufficient
When `optRecordLoop` tries to identify a fixed initial value for a loop IV, it must ensure that the proposed initial value is the reaching def on entry to the loop.  The [current check](https://github.com/dotnet/coreclr/blob/f42984160f5f9407f70ebc2e86edfcf226fccd81/src/jit/optimizer.cpp#L1219-L1224) simply checks if the `head` block (which ends with initialization [possibly followed by a duplicated loop condition](https://github.com/dotnet/coreclr/blob/f42984160f5f9407f70ebc2e86edfcf226fccd81/src/jit/optimizer.cpp#L1081-L1086)) dominates the `entry` block, but this is insufficient because there could be a path from `head` to `entry` which modifies the induction var.

I believe we can check instead whether all the preds of the `entry` block that are not the `head` block are in the loop (since if the loop had multiple entries it would be irreducible).

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Checking that `head` dominates `entry` is insufficient, becuase there may
be a codepath from `head` through other nodes that modify the induction
variable to `entry`.  Check instead that all preds of `entry` are either
`head` or in the loop.

Resolves #7906.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@dotnet/jit-contrib PTAL.  This is a prerequisite for #7843.

File: src/jit/optimizer.cpp [hunk 1]
```diff
@@ -1217,10 +1217,14 @@ void Compiler::optRecordLoop(BasicBlock*   head,
...
 
         // Make sure the "iterVar" initialization is never skipped,
-        // i.e. HEAD dominates the ENTRY.
-        if (!fgDominate(head, entry))
+        // i.e. every pred of ENTRY other than HEAD is in the loop.
+        for (flowList* predEdge = entry->bbPreds; predEdge; predEdge = predEdge->flNext)
         {
-            goto DONE_LOOP;
+            BasicBlock* predBlock = predEdge->flBlock;
+            if (predBlock != head && !optLoopTable[loopInd].lpContains(predBlock))
```
Comment (erozenfeld) [inline src/jit/optimizer.cpp]: CC: predBlock != head should be parenthesized

Comment (JosephTremoulet) [inline src/jit/optimizer.cpp]: Shouldn't jit-format have complained, then?

**Comment by erozenfeld** [comment]
LGTM

File: src/jit/optimizer.cpp (hunk 1 above)
Comment (briansull) [inline src/jit/optimizer.cpp]: It also might be a good idea to audit other places where we use` fgDominate(head, entry)` in case a similar issue exist with them.

File: tests/src/JIT/Regression/JitBlue/GitHub_7906/GitHub_7906.cs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+            //
+            // The testcase is intentionally structured so that loop unrolling will try
+            // to unroll loop B3..B5 and generate incorrect code due to the incorrect
+            // initial value.
+            for (int i = Vector<int>.Count; i < Vector<int>.Count || i < 20; ++i)
+            {
+                x += i;
+            }
+
+            return x - 84;
```
Comment (briansull) [inline tests/src/JIT/Regression/JitBlue/GitHub_7906/GitHub_7906.cs]: Can you add a  comment saying what the expected return value for Main is here?

**Comment by briansull** [comment]
LGTM
