### PR TITLE
Fix #7092

### LINKED ISSUE #7092: RyuJIT x86: Assertion failed 'emitVerifyEncodable(ins, EA_SIZE(attr), ireg)'
In Windows_NT.ryujit.x86.Checked.jit_stress_regs.1

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=1

/JIT/Regression/JitBlue/DevDiv_199169/DevDiv_199169/DevDiv_199169.cmd

> D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(373533): error : JIT._Regression_JitBlue_DevDiv_199169_DevDiv_199169_DevDiv_199169_._Regression_JitBlue_DevDiv_199169_DevDiv_199169_DevDiv_199169_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---95c7955c\tests\runtest.proj]
> Assert failure(PID 9792 [0x00002640], Thread: 9136 [0x23b0]): Assertion failed 'emitVerifyEncodable(ins, EA_SIZE(attr), ireg)' in '<Module>:main(ref):int' (IL size 58)
> File: d:\j\workspace\x86_ryujit_ch---95c7955c\src\jit\emitxarch.cpp Line: 4364
> Image: D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\JitBlue\DevDiv_199169\DevDiv_199169\DevDiv_199169.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---95c7955c\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" DevDiv_199169.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

### PR DESCRIPTION
**Pull request by BruceForstall**
The problem is genCodeForInitBlkUnroll() is trying to generate:
```
mov byte ptr [edi], si
```
which is not legal: ebp/esi/edi/esp don't have byte register versions on x86.

This change requires the source register to be an x86 byteable register in
this case.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@sivarv @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
LGTM

**Comment by CarolEidt** [comment]
:shipit:

File: src/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -1575,6 +1575,15 @@ void Lowering::TreeNodeInfoInitBlockStore(GenTreeBlk* blkNode)
                     blkNode->gtLsraInfo.setInternalCandidates(l, l->internalFloatRegCandidates());
                 }
                 blkNode->gtBlkOpKind = GenTreeBlk::BlkOpKindUnroll;
+
+#ifdef _TARGET_X86_
+                // On x86, you can't address the lower byte of ESI, EDI, ESP, or EBP when doing
+                // a "mov byte ptr [dest], val". If the fill size is odd, we will try to do this
+                // when unrolling, so only allow byteable registers as the source value. (We could
+                // consider just using BlkOpKindRepInstr instead.)
+                sourceRegMask = RBM_BYTE_REGS;
```
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: We are pessimising register specification/allocation even when struct size is not odd by constraining it to be bytable registers.  Since size is a const, we can check to constrain to bytable regs only when the size is odd.

Comment (BruceForstall) [inline src/jit/lowerxarch.cpp]: Shoot. In my head I'd written it to only do this for odd sizes, but apparently that thinking didn't make it into the file. I'll fix.

**Comment by sivarv** [comment]
Looks good.
