### PR TITLE
Fix #6893.

### LINKED ISSUE #6893: ARM64: assert in lir.cpp
```
Assert failure(PID 5372 [0x000014fc], Thread: 21420 [0x53ac]): Assertion failed 'insertionPoint == m_lastNode' in 'Microsoft.Cci.PeWriter:WritePeToStream(ref,ref,ref,ref):bool:this' (IL size 908) File: d:\j\workspace\arm64_cross_c---f41ee988\src\jit\lir.cpp Line: 880
```

This is showing up on the tests that were previously failing due to #6583.

### PR DESCRIPTION
**Pull request by pgavlin**
Aggregate arguments to calls (i.e. arguments that are made up
of multiple, independent values such as those to be passed in
multiple registers) are represented by GT_LIST nodes that are
not distiguishable from normal GT_LIST nodes without the extra
context of the call. GT_LIST nodes, however, are disallowed in
LIR ranges. The intersection of these two design choices causes
problems for code that operates on LIR but wants to observe
aggregate arguments as a whole (rather than piecewise). In the
case of #6893, this caused lowering to attempt to insert a
PUTARG_STK node after the GT_LIST node that represented the
aggregate argument that was being forced to the stack, which
caused an assertion in the LIR utilities to fail (the GT_LIST
node was passed as the insertion point to `LIR::Range::InsertAfter`,
which requires that the insertion point be a part of the given
range).

Conceptually, the fix is simple: the nodes that represent
aggregate arguments must be allowed to be part of LIR ranges.
The implementation, however, is complicated somewhat by the
need to distinguish the nodes used for aggregate arguments from
normal GT_LIST nodes. These changes implement a short-term
fix that distiguished these nodes by adding a node-specific flag,
`GTF_LIST_AGGREGATE`, to indicate that a GT_LIST node is in fact
an aggregate argument. In the long term, a more palatable
implementation would be the introduction of a new node and operator
type to represent aggregate arguments, but this is likely to
require broader changes to the compiler.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet/jit-contrib @BruceForstall @briansull PTAL

File: src/jit/gentree.cpp [hunk 1]
```diff
@@ -953,6 +953,27 @@ Compiler::fgWalkResult Compiler::fgWalkTreePostRec(GenTreePtr* pTree, fgWalkData
...
+                        return result;
+                    }
+                }
+                break;
+            }
+            else
+            {
+                __fallthrough;
+            }
+        }
```
Comment (BruceForstall) [inline src/jit/gentree.cpp]: The
```
            else
            {
                __fallthrough;
            }
```
construct seems weird. I would simply use:

```
            __fallthrough;
```

with surrounding blank lines.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -4696,6 +4696,8 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
     // We should still have a TYP_STRUCT
     assert(argValue->TypeGet() == TYP_STRUCT);
 
+    // TODO(pdg): below is where we'll need to create aggregate nodes.
+
     GenTreeArgList* newArg = nullptr;
```
Comment (BruceForstall) [inline src/jit/morph.cpp]: This should be a simple TODO or a TODO-Bug, or similar, not (pdg)

**Comment by BruceForstall** [comment]
:shipit:

File: src/jit/gentree.cpp (hunk 1 above)
Comment (briansull) [inline src/jit/gentree.cpp]: I would also add a comment stating that when we do nothave a aggregate we intentionally fall through here.

File: src/jit/compiler.h [hunk 3]
```diff
@@ -1933,9 +1933,10 @@ class Compiler
     GenTreePtr gtNewIndexRef(var_types typ, GenTreePtr arrayOp, GenTreePtr indexOp);
 
     GenTreeArgList* gtNewArgList(GenTreePtr op);
-
     GenTreeArgList* gtNewArgList(GenTreePtr op1, GenTreePtr op2);
 
+    GenTreeArgList* gtNewAggregate(GenTree* element);
```
Comment (CarolEidt) [inline src/jit/compiler.h]: I don't think Aggregate is a good term to use here because it is not used anywhere else in the source base. I think that something like gtNewMultiRegStruct would be better.

File: src/jit/gentree.h [hunk 4]
```diff
@@ -940,6 +940,9 @@ struct GenTree
 
 #define GTF_ARRLEN_ARR_IDX 0x80000000 // GT_ARR_LENGTH -- Length which feeds into an array index expression
 
+#define GTF_LIST_AGGREGATE 0x80000000 // GT_LIST -- Indicates that this list should be treated as an
```
Comment (CarolEidt) [inline src/jit/gentree.h]: Similar to my previous comment, I think this should be something like GTF_LIST_MULTIREG_ARG

File: src/jit/gentree.cpp [hunk 5]
```diff
@@ -6386,6 +6407,13 @@ GenTreeArgList* Compiler::gtNewArgList(GenTreePtr arg1, GenTreePtr arg2)
     return new (this, GT_LIST) GenTreeArgList(arg1, gtNewArgList(arg2));
 }
 
+GenTreeArgList* Compiler::gtNewAggregate(GenTree* firstElement)
```
Comment (briansull) [inline src/jit/gentree.cpp]: Add a comment that says we are creating a special kind of GT_LIST that is used to hold multi-part struct aggregates.
You might also say that in the future we may change this GT_LIST into it's own node such as GT_AGGREGATE

File: src/jit/gentree.cpp [hunk 6]
```diff
@@ -8576,51 +8602,27 @@ void GenTreeUseEdgeIterator::MoveToNextCallUseEdge()
                 break;
 
             case 1:
-            case 3:
+            case 2:
```
Comment (briansull) [inline src/jit/gentree.cpp]: I don't understand all of these state numbers and what they mean.

File: src/jit/lsra.cpp [hunk 7]
```diff
@@ -3198,18 +3198,18 @@ static int ComputeOperandDstCount(GenTree* operand)
...
     {
         // Stores and void-typed operands may be encountered when processing call nodes, which contain
         // pointers to argument setup stores.
         return 0;
     }
     else
     {
-        // If a non-void-types operand is not an unsued value and does not have source registers, that
-        // argument is contained within its parent and produces `sum(operand_dst_count)` registers.
+        // If an aggregate or non-void-types operand is not an unsued value and does not have source registers,
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: While you're here perhaps you could correct this to be non-void-type

File: src/jit/gentree.h (hunk 4 above)
Comment (briansull) [inline src/jit/gentree.h]: These GT_LIST nodes are need by LIR only when we have TTP_STRUCT argument that is passed on the stack.  Thy aren't needed when these are passed in registers, because  for mulri-reg args we need one PUTARG_REG per register that is passed.  For stack args we use one PURARG_STK that has as its single child a GT_LIST with one element per 8-byte sized struct field. And actually we only need use this form when we do struct promotion so that we no longer are using the TYP_STRUCT base LclVar.

File: src/jit/gentree.cpp (hunk 6 above)
Comment (CarolEidt) [inline src/jit/gentree.cpp]: Yes, that could definitely use a comment or two, though unrelated to this change. It's really just an operand index, so m_index might be a better name.

---
In reply to: [76495055](https://github.com/dotnet/coreclr/pull/6932#discussion_r76495055) [](ancestors = 76495055)

File: src/jit/gentree.h (hunk 4 above)
Comment (CarolEidt) [inline src/jit/gentree.h]: Then perhaps GTF_LIST_FIELD would be better. I just don't like the idea of mixing "struct" and "aggregate" as the term we use to describe the same thing.

---
In reply to: [76495984](https://github.com/dotnet/coreclr/pull/6932#discussion_r76495984) [](ancestors = 76495984)

File: src/jit/morph.cpp (hunk 2 above)
Comment (pgavlin) [inline src/jit/morph.cpp]: Better yet, this can be removed, as this has already been done. The TODO is leftover from my initial notes.

File: src/jit/gentree.cpp (hunk 1 above)
Comment (pgavlin) [inline src/jit/gentree.cpp]: Done.

File: src/jit/compiler.h (hunk 3 above)
Comment (pgavlin) [inline src/jit/compiler.h]: What about `StructFieldList` or `StructFieldValues` (or even just `StructFields`)? Also, do you have any similar concept in the first class struct changes?

File: src/jit/gentree.h (hunk 4 above)
Comment (pgavlin) [inline src/jit/gentree.h]: > These GT_LIST nodes are need by LIR only when we have TYP_STRUCT argument that is passed on the stack.

This is a good explanation of the specific need. I do want to point out that for the sake of uniformity, all lists that represent arguments that may be passed in multiple registers are marked as aggregate arguments. This property is used e.g. by the operand iterator.

File: src/jit/lsra.cpp (hunk 7 above)
Comment (pgavlin) [inline src/jit/lsra.cpp]: Done.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT arm64 checked

File: src/jit/compiler.h (hunk 3 above)
Comment (pgavlin) [inline src/jit/compiler.h]: Ping--aside from nomenclature, this change is ready. If we can agree on a name rather quickly I'm happy to block on that, but otherwise I'd like to get this checked in and follow up on the naming later.

**Comment by CarolEidt** [comment]
I'm OK with merging this, though I still think that the naming could lead to confusion - so perhaps we can consider changing it later.
