### PR TITLE
Treat WinMDs as having been loaded in the default ALC for AssemblyLoadContext.GetLoadContext

### LINKED ISSUE #23583: AssemblyLoadContext.GetLoadContext(Assembly) throwing
With the following modification the corefx test is failing on Windows runs (except uapaot which skips the test)
```diff
diff --git a/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs b/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
index 16e4c38..13aae6f 100644
--- a/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
+++ b/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
@@ -96,12 +96,15 @@ namespace System.Runtime.Loader.Tests
             // Create a secondary load context and wireup its resolving event
             SecondaryLoadContext slc = new SecondaryLoadContext();
             slc.Resolving += ResolveAssembly;
 
+            Assert.Contains(slc, AssemblyLoadContext.All);
+
             // Attempt to load the assembly in secondary load context
             var slcLoadedAssembly = slc.LoadFromAssemblyName(assemblyName);
  
             // We should have successfully loaded the assembly in secondary load context.
             Assert.NotNull(slcLoadedAssembly);
+            Assert.Contains(slcLoadedAssembly, slc.Assemblies);
 
             // And make sure the simple name matches
             Assert.Equal(TestAssemblyName, slcLoadedAssembly.GetName().Name);
@@ -118,12 +121,13 @@ namespace System.Runtime.Loader.Tests
             AssemblyLoadContext.Default.Resolving += ResolveNullAssembly;
             AssemblyLoadContext.Default.Resolving += ResolveAssembly;
             AssemblyLoadContext.Default.Resolving += ResolveAssemblyAgain;
 
             // This will invoke the resolution via VM requiring to bind using the TPA binder
             var assemblyExpectedFromLoad = Assembly.Load(assemblyName);
 
             // We should have successfully loaded the assembly in default context.
             Assert.NotNull(assemblyExpectedFromLoad);
+            Assert.Contains(assemblyExpectedFromLoad, AssemblyLoadContext.Default.Assemblies);
 
             // We should have only invoked non-Null returning handler once
             Assert.Equal(1, _numNonNullResolutions);
```
Failure looks like this
```
C:\dotnetbuild\work\879f0c69-d11e-4b0a-a47c-f5358d852978\Work\a31874fc-8e7f-4c85-9315-92955288f871\Exec>"C:\dotnetbuild\work\879f0c69-d11e-4b0a-a47c-f5358d852978\Payload\dotnet.exe" xunit.console.dll System.Runtime.Loader.DefaultContext.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop 

  Discovering: System.Runtime.Loader.DefaultContext.Tests (method display = ClassAndMethod, method display options = None)

  Discovered:  System.Runtime.Loader.DefaultContext.Tests (found 2 test cases)

  Starting:    System.Runtime.Loader.DefaultContext.Tests (parallel test collections = on, max threads = 4)

0xC0000005
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(System.Reflection.Assembly)
   at System.Runtime.Loader.AssemblyLoadContext+<get_Assemblies>d__46.MoveNext()
   at System.Linq.Enumerable.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Xunit.Assert.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Xunit.Assert.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
```

The failure occurs when the following code tries to get the ALC for an Assembly.
```C#
         public IEnumerable<Assembly> Assemblies
         {
             get
             {
                 foreach (Assembly a in GetLoadedAssemblies())
                 {
                     AssemblyLoadContext alc = GetLoadContext(a);
 
                     if (alc == this)
                     {
                         yield return a;
                     }
                 }
             }
         }
```

`AssemblyLoadContext.GetLoadContext(Assembly)` should not throw.
This also looks like it could be an unloadability issue.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #23583 

There is currently no way to load a WinMD into an ALC and all WinMD dependencies are loaded into the default ALC, so from a user perspective, this is effectively correct.

With #23402 this will change slightly (a WinMD will still be loaded by the WinRT binder but its dependencies can be loaded into an isolated ALC), so we might want to do different behavior then.

### CODE REVIEW

File: src/vm/assemblynative.cpp [hunk 1]
```diff
@@ -1331,7 +1331,10 @@ INT_PTR QCALLTYPE AssemblyNative::GetLoadContextForAssembly(QCall::AssemblyHandl
     // We should have a load context binder at this point.
     _ASSERTE(pOpaqueBinder != nullptr);
 
-    if (!AreSameBinderInstance(pTPABinder, pOpaqueBinder))
+    // the TPA binder uses the default ALC
+    // WinRT assemblies (bound using the WinRT binder) don't actually have an ALC,
+    // so treat them the same as if they were loaded into the TPA ALC in this case.
+    if (!AreSameBinderInstance(pTPABinder, pOpaqueBinder) && !AreSameBinderInstance(pCurDomain->GetWinRtBinder(), pOpaqueBinder))
```
Comment (sdmaclea) [inline src/vm/assemblynative.cpp]: Is this the correct behavior? I wonder if `WinRtBinder` shouldn't just return `null` for `GetLoadContextForAssembly`

@jkotas What do you think?

Comment (jkotas) [reply src/vm/assemblynative.cpp]: I think that this fix is fine.

Comment (sdmaclea) [reply src/vm/assemblynative.cpp]: This would imply this assertion would pass
```C#
Assert.AreEqual(AssemblyLoadContext.Default.LoadFromAssembly(WinRtAssembly.GetName()), WinRtAssembly);
```

Comment (jkoritzinsky) [reply src/vm/assemblynative.cpp]: The call `AssemblyLoadContext.Default.LoadFromAssembly(WinRtAssembly.GetName())` itself will fail to load a WinRT assembly.

Comment (jkoritzinsky) [reply src/vm/assemblynative.cpp]: WinMDs have to be loaded very particularly to make sure they're loaded via the WinRT binder.

Comment (sdmaclea) [reply src/vm/assemblynative.cpp]: So in my humble opinion, the function should return null.

Comment (sdmaclea) [reply src/vm/assemblynative.cpp]: Maybe it doesn't matter, because normal assemblies will not depend on them.

Comment (jkotas) [reply src/vm/assemblynative.cpp]: > the function should return null

Which function?

Comment (sdmaclea) [reply src/vm/assemblynative.cpp]: > Which function?

`AssemblyNative::GetLoadContextForAssembly(Assembly)`

Comment (jkotas) [reply src/vm/assemblynative.cpp]: `AssemblyNative::GetLoadContextForAssembly` will return null for WinRT assemblies with this change.

Comment (sdmaclea) [reply src/vm/assemblynative.cpp]: Hmm! I should read code more thoroughly. `AssemblyLoadContext.GetLoadContext(Assembly assembly)` converts `null` as `Default`.  I assumed that conversion was inside the C++ function.

```C#
                IntPtr ptrAssemblyLoadContext = GetLoadContextForAssembly(rtAsm);
                if (ptrAssemblyLoadContext == IntPtr.Zero)
                {
                    // If the load context is returned null, then the assembly was bound using the TPA binder
                    // and we shall return reference to the active "Default" binder - which could be the TPA binder
                    // or an overridden CLRPrivBinderAssemblyLoadContext instance.
                    loadContextForAssembly = AssemblyLoadContext.Default;
                }
```

But I guess the comment notes that precedence has already been established...

I really wanted `AssemblyLoadContext.GetLoadContext(Assembly winRtAssembly) == null`
