### PR TITLE
[Arm64] reserve for jump stubs

### LINKED ISSUE #17173: [Arm64] CoreFX tests trigger OutOfMemoryException(s)
This is the first of reportedly several.  I'll try to keep them all in this issue.

```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Composition.TypedParts.Tests
Discovered:  System.Composition.TypedParts.Tests
Starting:    System.Composition.TypedParts.Tests
   System.Composition.TypedParts.Tests.ReflectionTests.MultiThreadedGetExportsWorkWithImportingConstuctor [FAIL]
      System.AggregateException : One or more errors occurred. (Insufficient memory within specified address space range to continue the execution of the program.)
      ---- System.OutOfMemoryException : Insufficient memory within specified address space range to continue the execution of the program.
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/tests/ReflectionTests.cs(58,0): at System.Composition.TypedParts.Tests.ReflectionTests.MultiThreadedGetExpoOutOfMemoryExceptionrtsWorkWithImportingConstuctor()
         ----- Inner Stack Trace -----
            at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/src/System/Reflection/Emit/DynamicMethod.cs(374,0): at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.cs(185,0): at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs(206,0): at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/src/System/Composition/TypedParts/Discovery/DiscoveredPart.cs(167,0): at System.Composition.TypedParts.Discovery.DiscoveredPart.GetActivator(DependencyAccessor definitionAccessor, IEnumerable`1 dependencies)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/src/System/Composition/TypedParts/Discovery/DiscoveredExport.cs(42,0): at System.Composition.TypedParts.Discovery.DiscoveredExport.<>c__DisplayClass11_0.<GetExportDescriptorPromise>b__1(IEnumerable`1 deps)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/Lazy.cs(324,0): at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/OutOfMemoryExceptionSystem/Lazy.cs(408,0): at System.Lazy`1.CreateValue()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Hosting/src/System/Composition/Hosting/Core/ExportDescriptorPromise.cs(86,0): at System.Composition.Hosting.Core.ExportDescriptorPromise.GetDescriptor()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/src/System/Composition/TypedParts/Discovery/DiscoveredPart.cs(155,0): at System.Composition.TypedParts.Discovery.DiscoveredPart.GetActivator(DependencyAccessor definitionAccessor, IEnumerable`1 dependencies)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/src/System/Composition/TypedParts/Discovery/DiscoveredExport.cs(42,0): at System.Composition.TypedParts.Discovery.DiscoveredExport.<>c__DisplayClass11_0.<GetExportDescriptorPromise>b__1(IEnumerable`1 deps)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/Lazy.cs(324,0): at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         /home/vmjenkins/workspace/Dotnet/build_and_test/src/mscorlib/shared/System/Lazy.cs(408,0): at System.Lazy`1.CreateValue()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Hosting/src/System/Composition/Hosting/Core/ExportDescriptorPromise.cs(86,0): at System.Composition.Hosting.Core.ExportDescriptorPromise.GetDescriptor()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Linq/src/System/Linq/Select.cs(240,0): at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Hosting/src/System/Composition/Hosting/Core/ExportDescriptorRegistryUpdate.cs(50,0): at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract contract)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Hosting/src/System/Composition/Hosting/Core/ExportDescriptorRegistry.cs(32,0): at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract exportKey, ExportDescriptor& defaultForExport)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Hosting/src/System/Composition/Hosting/Core/LifetimeContext.cs(196,0): at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Runtime/src/System/Composition/CompositionContext.cs(150,0): at System.Composition.CompositionContext.GetExport(CompositionContract contract)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.Runtime/src/System/Composition/CompositionContext.cs(50,0): at System.Composition.CompositionContext.GetExport[TExport](String contractName)
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/tests/ReflectionTests.cs(78,0): at System.Composition.TypedParts.Tests.ReflectionTests.GetExport()
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Composition.TypedParts/tests/ReflectionTests.cs(67,0): at System.Composition.TypedParts.Tests.ReflectionTests.Run(ManualResetEventSlim evnt, ConcurrentBag`1 errors)
Finished:    System.Composition.TypedParts.Tests
```

### PR DESCRIPTION
**Pull request by sdmaclea**
@jkotas PTAL
@dotnet/arm64-contrib 

Fixes #17173

### CODE REVIEW

File: src/vm/jitinterface.cpp [hunk 1]
```diff
@@ -11371,7 +11371,7 @@ void CEEJitInfo::recordRelocation(void * location,
                     // When m_fAllowRel32 == TRUE, the JIT will use REL32s for both data addresses and direct code targets.
                     // Since we cannot tell what the relocation is for, we have to defensively retry.
                     //
-                    m_fRel32Overflow = TRUE;
+                    m_fJumpStubOverflow = TRUE;
```
Comment (sdmaclea) [inline src/vm/jitinterface.cpp]: I renamed this member to be more generic so we could share more code.

File: src/vm/jitinterface.cpp [hunk 2]
```diff
@@ -11429,12 +11429,12 @@ void CEEJitInfo::recordRelocation(void * location,
             if (!FitsInRel28(delta))
             {
                 // Use jump stub.
```
Comment (sdmaclea) [inline src/vm/jitinterface.cpp]: Since this case is used only for branches, it seemed like `arm64` didn't need the `fAllowRel32` stuff

File: src/vm/jitinterface.cpp [hunk 3]
```diff
@@ -12674,25 +12688,27 @@ PCODE UnsafeJitFunction(MethodDesc* ftn, COR_ILMETHOD_DECODER* ILHeader, CORJIT_
...
 #endif
 
-    BOOL fAllowRel32 = g_fAllowRel32 | fForceRel32Overflow;
     size_t reserveForJumpStubs = 0;
 
     // For determinism, never try to use the REL32 in compilation process
     if (IsCompilationProcess())
     {
-        fForceRel32Overflow = FALSE;
-        fAllowRel32 = FALSE;
```
Comment (sdmaclea) [inline src/vm/jitinterface.cpp]: Moved above

File: src/vm/jitinterface.cpp [hunk 4]
```diff
@@ -11443,7 +11443,21 @@ void CEEJitInfo::recordRelocation(void * location,
...
                                                                 (PCODE)  target,
                                                                 (BYTE *) loAddr,
-                                                                (BYTE *) hiAddr);
+                                                                (BYTE *) hiAddr,
+                                                                NULL,
+                                                                false);
+
+                // Keep track of conservative estimate of how much memory may be needed by jump stubs. We will use it to reserve extra memory
+                // on retry to increase chances that the retry succeeds.
+                m_reserveForJumpStubs = max(0x400, m_reserveForJumpStubs + 2*BACK_TO_BACK_JUMP_ALLOCATE_SIZE);
```
Comment (sdmaclea) [inline src/vm/jitinterface.cpp]: You said conservative so i used 2x.  I figured ask for twice as much as failed...

Looks like you used `BACK_TO_BACK_JUMP_ALLOCATE_SIZE` + 4 above.  Hard coded as `0x10`.  

I also used your hardcoded `0x400` which I suspect should be something else....

File: src/vm/jitinterface.cpp [hunk 5]
```diff
@@ -12674,25 +12688,27 @@ PCODE UnsafeJitFunction(MethodDesc* ftn, COR_ILMETHOD_DECODER* ILHeader, CORJIT_
...
+#endif
+
+#if defined(_TARGET_AMD64_)
+    BOOL fAllowRel32 = (g_fAllowRel32 | fForceJumpStubOverflow) && !IsCompilationProcess();
 #endif
 
-    BOOL fAllowRel32 = g_fAllowRel32 | fForceRel32Overflow;
     size_t reserveForJumpStubs = 0;
 
     // For determinism, never try to use the REL32 in compilation process
```
Comment (jkotas) [inline src/vm/jitinterface.cpp]: The `IsCompilationProcess` condition and this comment can be deleted here. We will never get here for compilation process (ie crossgen) for CoreCLR.

File: src/vm/jitinterface.h [hunk 6]
```diff
@@ -1495,8 +1499,10 @@ protected :
 
 #ifdef _TARGET_AMD64_
     BOOL                    m_fAllowRel32;      // Use 32-bit PC relative address modes
-    BOOL                    m_fRel32Overflow;   // Overflow while trying to use encode 32-bit PC relative address. 
-                                                // The code will need to be regenerated with m_fRel32Allowed == FALSE.
+#endif
+#if defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_)
+    BOOL                    m_fJumpStubOverflow;   // Overflow while trying to use encode 32-bit PC relative address.
```
Comment (jkotas) [inline src/vm/jitinterface.h]: Nit: `encode 32-bit PC relative address` is not accurate for ARM64

Comment (sdmaclea) [reply src/vm/jitinterface.h]: Done

File: src/vm/jitinterface.cpp (hunk 5 above)
Comment (sdmaclea) [reply src/vm/jitinterface.cpp]: Done

**Comment by sdmaclea** [comment]
I can see the tizen job.  Since this is allinside amd64/arm64 `#ifdefs` I think this can merge,  I'll try yo trigger it again though.

test Tizen armel Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
I think the tizen job was removed from CI.  This can be merged.

**Comment by sdmaclea** [comment]
Looks like this broke forcerelocs.

Many tests are failing in forcerelocs w/
```
src/pal/src/libunwind/src/mi/mempool.c:78: void *_UIaarch64__sos_alloc(size_t): 
Assertion `(pos+size) <= SOS_MEMORY_SIZE' failed.
```

**Comment by sdmaclea** [comment]
Found the issue.  I will test the fix locally, then open a PR
