### PR TITLE
Jit: Fix SetIndirExceptionFlags.

### LINKED ISSUE #27027: Incorrect exception thrown when evaluating addition operands
This program below incorrectly throws `DivideByZeroException` because `Run` method throws  `DivideByZeroException` instead of `NullReferenceException`.

```
using System;
using System.Runtime.CompilerServices;

public struct S
{
    public int i;
    public int j;
}

public class Test
{
    public S s;
    public int i;    
    public static int Main()
    {
        try {
            Run(null, 0);
        }
        catch (System.NullReferenceException)
        {
            return 100;
        }

        return -1;
    }
 
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int Run(Test test, int j)
    {
        int k = test.s.i + 1/j;        
        return k;
    }    
}
```

The test is similar to #22556 (which has been fixed) but here the field is nested (`test.s.i`).

### PR DESCRIPTION
**Pull request by erozenfeld**
SetIndirExceptionFlags should not set `GTF_IND_NONFAULTING` flag if the
address has `GTF_EXCEPT` flag.

The failing scenario was:

We were setting `GTF_IND_NONFAULTING` on this indirection (since `ADDR` Node
can't be null)

```
               [000003] *--XG-------              *  IND       int
               [000002] ---XG-------              \--*  ADDR      byref  Zero Fseq[i]
               [000001] ---XG-------                 \--*  FIELD     struct s
               [000000] ------------                    \--*  LCL_VAR   ref    V00 arg0
```
this was then transformed to

```
               [000003] *---G-------              *  IND       int
               [000013] -----+------              \--*  ADD       byref
               [000000] -----+------                 +--*  LCL_VAR   ref    V00 arg0
               [000012] -----+------                 \--*  CNS_INT   long   8 field offset Fseq[s, i]
```
The `GTF_EXCEPT` flag was cleared on `IND` because it had `GTF_IND_NONFAULTING`set
and the address no longer had  `GTF_EXCEPT` flag.

Fixes #27027.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib PTAL

**Comment by erozenfeld** [comment]
x64 pmi framework diffs:

```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary:
(Lower is better)
Total bytes of diff: 6 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
          12 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
          10 : System.Private.Xml.dasm (0.00% of base)
           2 : System.Transactions.Local.dasm (0.00% of base)
Top file improvements by size (bytes):
         -18 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.00% of base)
4 total files with size differences (1 improved, 3 regressed), 125 unchanged.
Top method regressions by size (bytes):
           8 ( 2.94% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - GCPerHeapHistoryTraceData:get_HeapIndex():int:this
           7 ( 0.30% of base) : System.Private.Xml.dasm - <ReadDataAsync>d__505:MoveNext():this
           4 (11.11% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - TcpTcbStartTimerArgs:get_TimerType():int:this
           4 ( 0.37% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:ReadData():int:this
           2 ( 4.35% of base) : System.Transactions.Local.dasm - Phase1VolatileEnlistment:CheckComplete():this
Top method improvements by size (bytes):
         -12 (-2.70% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:SkipToNextConditionalLine():struct:this
          -6 (-24.00% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:ResetLineBufferOffset():this
          -1 (-0.13% of base) : System.Private.Xml.dasm - XmlSqlBinaryReader:HashCheckForDuplicateAttributes():this
Top method regressions by size (percentage):
           4 (11.11% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - TcpTcbStartTimerArgs:get_TimerType():int:this
           2 ( 4.35% of base) : System.Transactions.Local.dasm - Phase1VolatileEnlistment:CheckComplete():this
           8 ( 2.94% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - GCPerHeapHistoryTraceData:get_HeapIndex():int:this
           4 ( 0.37% of base) : System.Private.Xml.dasm - XmlTextReaderImpl:ReadData():int:this
           7 ( 0.30% of base) : System.Private.Xml.dasm - <ReadDataAsync>d__505:MoveNext():this
Top method improvements by size (percentage):
          -6 (-24.00% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:ResetLineBufferOffset():this
         -12 (-2.70% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:SkipToNextConditionalLine():struct:this
          -1 (-0.13% of base) : System.Private.Xml.dasm - XmlSqlBinaryReader:HashCheckForDuplicateAttributes():this
8 total methods with size differences (3 improved, 5 regressed), 202937 unchanged.
2 files had text diffs but not size diffs.
System.Private.CoreLib.dasm had 196 diffs
System.Private.DataContractSerialization.dasm had 44 diffs
```

**Comment by erozenfeld** [comment]
No diffs in x64 pmi benchmarks.

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -6188,7 +6188,6 @@ GenTree* Compiler::fgMorphField(GenTree* tree, MorphAddrContext* mac)
         tree->SetOper(GT_IND);
         tree->gtOp.gtOp1 = addr;
 
-        tree->gtFlags &= (~GTF_EXCEPT | addr->gtFlags);
```
Comment (sandreenko) [inline src/jit/morph.cpp]: why does this go away?
` tree->gtFlags &= addr->gtFlags;`

Comment (erozenfeld) [reply src/jit/morph.cpp]: `~GTF_EXCEPT | addr->gtFlags` has all bits set except, possibly for `GTF_EXCEPT` bit. `SetIndirExceptionFlags` will set that bit correctly.

**Comment by erozenfeld** [comment]
@sandreenko I pushed a fix for test failures. PTAL.

**Comment by sandreenko** [comment]
Could you please check other places where we call `OperIsIndirOrArrLength`, like:
https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L7945-L7958

Does it need that change as well?

**Comment by erozenfeld** [comment]
The call to `OperIsIndirOrArrLength` was fine. The problem was the call to `gtGetOp1()`. It was failing on DYN_BLK nodes because they are not simple.

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -9271,6 +9271,30 @@ bool GenTree::Precedes(GenTree* other)
     return false;
 }
 
+void GenTree::SetIndirExceptionFlags(Compiler* comp)
```
Comment (sandreenko) [inline src/jit/gentree.cpp]: Could you please add a header?

Comment (erozenfeld) [reply src/jit/gentree.cpp]: Done.

**Comment by erozenfeld** [comment]
@sandreenko I made a couple of changes: I changed the logic in `gtUpdateNodeOperSideffects` and in `fgMorphSmpOp` (after `DONE_MORPHING_CHILDREN`) to call `SetIndirExceptionFlags`. The latter change caught more cases where we were setting `GTF_IND_NONFAULTING` on indirections that later become faulting. There are several more diffs in benchmarks where we now don't remove potentially faulting indirections.

**Comment by erozenfeld** [comment]
Still no diffs in benchmarks.
x64 frameworks pmi diffs:

```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary:
(Lower is better)
Total bytes of diff: 275 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
         253 : System.Data.Common.dasm (0.02% of base)
          26 : System.Private.Xml.dasm (0.00% of base)
          12 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
           2 : System.Transactions.Local.dasm (0.00% of base)
Top file improvements by size (bytes):
         -18 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.00% of base)
5 total files with size differences (1 improved, 4 regressed), 124 unchanged.
Top method regressions by size (bytes):
          84 ( 0.17% of base) : System.Data.Common.dasm - RBTree`1:RBInsert(int,int,int,int,bool):int:this (7 methods)
          65 ( 0.18% of base) : System.Data.Common.dasm - RBTree`1:RBDeleteX(int,int,int):int:this (7 methods)
          52 ( 0.63% of base) : System.Data.Common.dasm - RBTree`1:LeftRotate(int,int,int):int:this (7 methods)
          52 ( 0.63% of base) : System.Data.Common.dasm - RBTree`1:RightRotate(int,int,int):int:this (7 methods)
          16 ( 2.33% of base) : System.Private.Xml.dasm - XsltLoader:LoadMsScript(ref):this
Top method improvements by size (bytes):
         -12 (-2.70% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:SkipToNextConditionalLine():struct:this
          -6 (-24.00% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:ResetLineBufferOffset():this
          -1 (-0.13% of base) : System.Private.Xml.dasm - XmlSqlBinaryReader:HashCheckForDuplicateAttributes():this
Top method regressions by size (percentage):
           4 (11.11% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - TcpTcbStartTimerArgs:get_TimerType():int:this
           2 ( 4.35% of base) : System.Transactions.Local.dasm - Phase1VolatileEnlistment:CheckComplete():this
           8 ( 2.94% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - GCPerHeapHistoryTraceData:get_HeapIndex():int:this
          16 ( 2.33% of base) : System.Private.Xml.dasm - XsltLoader:LoadMsScript(ref):this
          52 ( 0.63% of base) : System.Data.Common.dasm - RBTree`1:LeftRotate(int,int,int):int:this (7 methods)
Top method improvements by size (percentage):
          -6 (-24.00% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:ResetLineBufferOffset():this
         -12 (-2.70% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Scanner:SkipToNextConditionalLine():struct:this
          -1 (-0.13% of base) : System.Private.Xml.dasm - XmlSqlBinaryReader:HashCheckForDuplicateAttributes():this
13 total methods with size differences (3 improved, 10 regressed), 202932 unchanged.
2 files had text diffs but not size diffs.
System.Private.CoreLib.dasm had 194 diffs
System.Private.DataContractSerialization.dasm had 44 diffs
```

File: src/jit/gentree.cpp [hunk 3]
```diff
@@ -9271,6 +9271,38 @@ bool GenTree::Precedes(GenTree* other)
...
+{
+    GenTree* addr = nullptr;
+    if (OperIsIndir())
+    {
+        addr = AsIndir()->Addr();
+    }
+    else
+    {
+        assert(gtOper == GT_ARR_LENGTH);
```
Comment (sandreenko) [inline src/jit/gentree.cpp]: Nit: you don't need to add an assert before `AsCast` because it has one inside.
