### PR TITLE
[Arm64] Fix stack struct arg packing

### LINKED ISSUE #17933: [Arm64/Linux] SDK fails to build hello world
@richlander @dotnet/arm64-contrib @Petermarcu 

As noted in various places the 2.1 arm64-linux SDK is failing during the build of Hello World with either an assertion or a segmentation fault

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #17933 

With this patch was able to successfully build & run hello world on linux-arm64 for linux-arm64

@CarolEidt @briansull @dotnet/arm64-contrib @dotnet/jit-contrib

### CODE REVIEW

File: src/jit/codegenarmarch.cpp [hunk 1]
```diff
@@ -668,9 +668,10 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
 
                 // Emit store instructions to store the registers produced by the GT_FIELD_LIST into the outgoing
                 // argument area
-                emit->emitIns_S_R(ins_Store(type), attr, reg, varNumOut, argOffsetOut);
-                argOffsetOut += EA_SIZE_IN_BYTES(attr);
-                assert(argOffsetOut <= argOffsetMax); // We can't write beyound the outgoing area area
```
Comment (sdmaclea) [inline src/jit/codegenarmarch.cpp]: Original code was packing the struct on the stack which was incorrect.

Comment (briansull) [reply src/jit/codegenarmarch.cpp]: Looks correct now

**Comment by sdmaclea** [comment]
I revised the patch.  It is now passing on linux-arm64.

I put the change armarch change under `#ifdef _TARGET_ARM64_` since I do not have a arm32 target and I do not fully understand the arm32 ABI.

File: src/jit/codegenarmarch.cpp [hunk 2]
```diff
@@ -666,11 +672,21 @@ void CodeGen::genPutArgStk(GenTreePutArgStk* treeNode)
...
 
+#ifdef _TARGET_ARM64_
+                // Emit store instructions to store the registers produced by the GT_FIELD_LIST into the outgoing
+                // argument area
+                emit->emitIns_S_R(ins_Store(type), attr, reg, varNumOut, argOffsetOut + fieldListPtr->gtFieldOffset);
+
+                // We can't write beyound the outgoing area area
+                assert((argOffsetOut + fieldListPtr->gtFieldOffset + EA_SIZE_IN_BYTES(attr)) <= argOffsetMax);
+#else
+                // TODO-ARM-Bug?  The following code will pack copied structs
```
Comment (briansull) [inline src/jit/codegenarmarch.cpp]: @BruceForstall
 We need to test this code path on ARM32

Comment (CarolEidt) [reply src/jit/codegenarmarch.cpp]: @briansull - this is simply the existing code path for ARM32 (it doesn't use the `gtFieldOffset` as set in `fgMorphLclArgToFieldlist()`) so I'm not sure why it needs to be specially tested.
However, we do need to determine if the existing code was actually correct - is that what you meant?

Comment (briansull) [reply src/jit/codegenarmarch.cpp]: Yes,  I meant - determine if the existing code was actually correct.
If this is only enabled when FEATURE_MULTIREG_STRUCT_PROMOTE then it is ifdef-ed out.
As Steve says it appears to be incorrect, as it will perform mis-aligned stores.

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
test Ubuntu arm64 Cross Checked Innerloop Build and Test

**Comment by sdmaclea** [comment]
Can this be merged?  @CarolEidt @briansull
