### PR TITLE
Fix codegen for `(umod (gt_long) (const int))`.

### LINKED ISSUE #8170: RyuJIT/x86: CoreFx System.Runtime.Serialization.Xml.ReflectionOnly.Tests System.OverflowException
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.ReflectionOnly.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.ReflectionOnly.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:53:12.45
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Serialization.Xml.ReflectionOnly.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Discovered:  System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Starting:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Ok, stream released right after WriteValue
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
   DataContractSerializerTests.DCS_TimeSpanAsRoot [FAIL]
      System.OverflowException : Arithmetic operation resulted in an overflow.
      Stack Trace:
            at System.Xml.Schema.XsdDuration..ctor(TimeSpan timeSpan, DurationType durationType)
            at System.Xml.XmlConvert.ToString(TimeSpan value)
            at System.Runtime.Serialization.TimeSpanDataContract.WriteXmlValue(XmlWriterDelegator writer, Object obj, XmlObjectSerializerWriteContext context)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
            at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
            at DataContractSerializerTests.DCS_TimeSpanAsRoot()
Finished:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Serialization.Xml.ReflectionOnly.Tests  Total: 187, Errors: 0, Failed: 1, Skipped: 0, Time: 21.772s
Finished running tests.  End time=17:53:43.89, Exit code = 1
```

### PR DESCRIPTION
**Pull request by pgavlin**
When targeting x86, we opt not to use a helper call to implement the
64-bit unsigned modulus operator if we have a tree of either of the
following forms:
- `(umod ulong (x ulong) (cast ulong (const int const_val)))`
- `(umod ulong (x ulong) (const ulong const_val))`
where `const_val` falls in the range `[2, 0x3fffffff]`.

We eventually decompose this into `(umod uint (gt_long lo hi) (const int const_val))`.
This was then emitted as:

      mov eax, lo
      mov edx, hi
      mov reg, const_val

      div edx:eax reg

Unfortunately, this generated code does not take into account the fact
that the result of the modulus may not fit into 32 bits. This can cause
an overflow exception at runtime despite the fact that the modulus
originally produced a 64-bit result.

This change fixes the code generation to check for overflow before
performing the modulus and perform a 64-bit division if the result would
overflow. This results in generated code like the following:

      mov eax, lo
      mov edx, hi
      mov reg, const_val

      cmp edx, reg
      jb noOverflow
      mov temp, eax
      mov edx, eax
      xor edx, edx
      div edx:eax, const_val
      mov eax, temp

    noOverflow:
      div edx:eax, const_val

Which is identical to the code produced by JIT32 and the legacy backend.

Fixes #8170.

### CODE REVIEW

**Comment by pgavlin** [comment]
@mikedn @adiaaida @dotnet/jit-contrib PTAL.

**Comment by mikedn** [comment]
Looks good. I was concerned that this might increase the complexity of other code paths (e.g. `TreeNodeInfoInitModDiv`) but it turns out that this is not the case.

File: tests/src/JIT/Regression/JitBlue/GitHub_8170/GitHub_8170.cs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+{
+	[MethodImpl(MethodImplOptions.NoInlining)]
+	static uint M(ulong l)
+	{
+		return (uint)(l % 10000000);
+	}
+
+	static int Main()
+	{
+		return (int)M(ulong.MaxValue);
```
Comment (mikedn) [inline tests/src/JIT/Regression/JitBlue/GitHub_8170/GitHub_8170.cs]: The test return is wrong :smile:

Comment (pgavlin) [inline tests/src/JIT/Regression/JitBlue/GitHub_8170/GitHub_8170.cs]: Yeah, that's what I get from copy/pasting my condensed repro without re-reading it :(

**Comment by adiaaida** [comment]
LGTM
