### PR TITLE
Handle SPC in GetLoadContext

### LINKED ISSUE #22402: AssemblyLoadContext.GetLoadContext(SPC) Segfaults
The call `AssemblyLoadContext.GetLoadContext(a);` Causes a segmentation fault when `a` is `System.Private.CoreLib`.

This worked in .NET Core 2.2 is is failing on tip and on .NET Core 3.0 preview 2.

In the following code the segfault occurs at the `GetLoadContext`.  The dotnet host terminates immediately, without reporting an exception or reaching the finally.

```C#
using System;
using System.Reflection;
using System.Runtime.Loader;

namespace ALC
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("try");
                AssemblyLoadContext.GetLoadContext(typeof(int).Assembly);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            finally
            {
                Console.WriteLine("finally");
            }
        }
    }
}
```

/cc @jkotas @vitek-karas

### PR DESCRIPTION
**Pull request by sdmaclea**
GetBindingContext() returns NULL for System.Private.CoreLib.  Add support
for this special case.

Fixes #22402

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]
LGTM

**Comment by jkotas** [comment]
Could you please add a test for this case to https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L117 ?

File: src/vm/assemblynative.cpp [hunk 1]
```diff
@@ -1302,13 +1302,22 @@ INT_PTR QCALLTYPE AssemblyNative::GetLoadContextForAssembly(QCall::AssemblyHandl
...
-    IfFailThrow(pBindingContext->GetBinderID(&assemblyBinderID));
 
-    // If the assembly was bound using the TPA binder,
-    // then we will return the reference to "Default" binder from the managed implementation when this QCall returns.
-    //
-    // See earlier comment about "Default" binder for additional context.
-    pOpaqueBinder = reinterpret_cast<ICLRPrivBinder *>(assemblyBinderID);
+    if (pBindingContext)
+    {
+        IfFailThrow(pBindingContext->GetBinderID(&assemblyBinderID));
```
Comment (jkotas) [inline src/vm/assemblynative.cpp]: I hope we will get to cleaning removing the unnecessary levels of abstraction one day...

**Review by jkotas — APPROVED** [review]

**Comment by sdmaclea** [comment]
@jkotas sure
