### PR TITLE
Fix for ARM secure delegate non-standard register arg

### LINKED ISSUE #17738: [arm32] Compiler optimization assumption invalid: FAILED: pMgr != 0
In the corefx tests, System.Linq.Expressions.Tests:

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/3/consoleText

```
Running tests in /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Linq.Expressions.Tests/netcoreapp-Linux-Release-arm
./RunTests.sh /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm

----- start 04:16:15 =============== To repro directly: =====================================================
pushd .
#!/usr/bin/env bash
chmod +x /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.netcore.exe System.Linq.Expressions.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Linq.Expressions.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Linq.Expressions.Tests/netcoreapp-Linux-Release-arm
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Linq.Expressions.Tests
Discovered:  System.Linq.Expressions.Tests
Starting:    System.Linq.Expressions.Tests

Assert failure(PID 31436 [0x00007acc], Thread: 31465 [0x7ae9]): Compiler optimization assumption invalid: FAILED: pMgr != 0
    File: /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/src/vm/virtualcallstub.cpp Line: 1601
    Image: /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet


Assert failure(PID 31436 [0x00007acc], Thread: 31465 [0x7ae9]): Compiler optimization assumption invalid: FAILED: pMgr != 0
    File: /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/src/vm/virtualcallstub.cpp Line: 1601
    Image: /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet

./RunTests.sh: line 126: 31436 Aborted                 $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Linq.Expressions.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Linq.Expressions.Tests/netcoreapp-Linux-Release-arm
----- end 04:27:34 ----- exit code 134 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by BruceForstall**
For ARM, doing a secure delegate call requires adding
a custom calling convention argument R4 as the address of the
secure delegate invoke indirection cell. This is done using the
fgMorphArgs nonStandardArgs mechanism, and the argument is added
at the end. For calls with 4 or more register arguments, this
didn't work: we would initially set the non-standard arg as a
non-register argument, and the nonStandardArgs check didn't
consider converting an argument from a stack argument back to
a register argument. The fix allows nonStandardArgs to be either
stack or register arguments, no matter what their place in the
argument list would imply.

Fix #17738

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline

**Comment by BruceForstall** [comment]
@janvorli I think this is the fix; I need to verify, though.

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline

**Comment by BruceForstall** [comment]
The test failures are due to https://github.com/dotnet/coreclr/issues/17744

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by briansull** [comment]
Can you give this fix a better name,  Like:
Fix for nonStandard Args ... more ...

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -4150,9 +4150,9 @@ GenTreeCall* Compiler::fgMorphArgs(GenTreeCall* call)
             // They should not affect the placement of any other args or stack space required.
             // Example: on AMD64 R10 and R11 are used for indirect VSD (generic interface) and cookie calls.
             isNonStandard = nonStandardArgs.FindReg(argx, &nonStdRegNum);
-            if (isNonStandard && (nonStdRegNum == REG_STK))
+            if (isNonStandard)
             {
-                isRegArg = false;
+                isRegArg = (nonStdRegNum != REG_STK);
```
Comment (sandreenko) [inline src/jit/morph.cpp]: Is it possible that this condition change `isRegArg ` from `false` to `true` now?

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -4150,9 +4150,9 @@ GenTreeCall* Compiler::fgMorphArgs(GenTreeCall* call)
...
             }
 #if defined(_TARGET_X86_)
             else if (call->IsTailCallViaHelper())
```
Comment (sandreenko) [inline src/jit/morph.cpp]: Looks like this change makes this condition dead. It affects only `nonStandartArguments` and now they are all processed in the previous condition.

File: src/jit/morph.cpp (hunk 1 above)
Comment (BruceForstall) [reply src/jit/morph.cpp]: Yes. That is in fact the fix.

File: src/jit/morph.cpp (hunk 2 above)
Comment (BruceForstall) [reply src/jit/morph.cpp]: Now the `else if (call->IsTailCallViaHelper())` condition is only executed if `!isNonStandard`. Previously, it was executed for `!isNonStandard || (nonStdRegNum != REG_STK))`. I think this is ok, because the `call->IsTailCallViaHelper()` case doesn't put anything in the nonStandardArgs list, so `!isNonStandard` will always be true. You could argue it would be more clear if we just remove the `else` altogether. I guess before, these two clauses could only make isRegArg false, so there was no need to check both conditions to do that. This case is simply another case of "non-standard args" that isn't handled by the "nonStandardArgs" mechanism. It's possible we could use the nonStandardArgs mechanism here, too, by tagging the last 4 arguments of `call->IsTailCallViaHelper()` calls as REG_STK. I'm not sure why we didn't do that; maybe because nonStandardArgs couldn't handle that at the time.

**Comment by BruceForstall** [comment]
`Ubuntu arm Cross Checked corefx_baseline Build and Test`: System.Linq.Expressions.Tests timed out
```
Discovering: System.Linq.Expressions.Tests
Discovered:  System.Linq.Expressions.Tests
Starting:    System.Linq.Expressions.Tests
   System.Linq.Expressions.Tests.LambdaTests.InvokeComputedLambda [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.ArrayInitializedWithCapturedInstance [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.CallOnCapturedInstance [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.NewExpressionwithMemberAssignInit [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.TestAndAlso [SKIP]
      870811
error: One or more tests failed while running tests from ''.  Exit code 124.
```

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build
@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_baseline

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test

**Comment by BruceForstall** [comment]
Hmmmm... infra error?
```
Starting:    System.Dynamic.Runtime.Tests
FATAL: command execution failed
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

try again:

@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test

**Comment by BruceForstall** [comment]
Looks like we'll need to leave System.Linq.Expressions.Tests disabled. When run by hand it took more than 2 hours:
```
System.Linq.Expressions.Tests  Total: 35208, Errors: 0, Failed: 0, Skipped: 5, Time: 7208.381s
```

**Comment by BruceForstall** [comment]
I opened a test issue about it being very slow: https://github.com/dotnet/corefx/issues/29421

It's possible this is partially an ARM JIT throughput issue, or ARM VM slowness issue, more than just a difference in x86/Windows vs. ARM/Ubuntu performance difference.

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT arm Cross Checked normal Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build
@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_baseline

@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test

@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8
@dotnet-bot test Windows_NT x86 Checked minopts

@dotnet-bot test Windows_NT x86 Checked tailcallstress

**Comment by sdmaclea** [comment]
> When run by hand it took more than 2 hours:

This is probably the same issue as #17414

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked corefx_minopts
@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8
@dotnet-bot test Windows_NT x86 Checked minopts
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x86 Checked r2r_jitminopts
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked tailcallstress
@dotnet-bot test Windows_NT x86 Release r2r

@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x64 Checked jitstress1
@dotnet-bot test Windows_NT x64 Checked jitstress2
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu x64 Build and Test
@dotnet-bot test Ubuntu x64 Checked jitstress1
@dotnet-bot test Ubuntu x64 Checked jitstress2
@dotnet-bot test Ubuntu x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress1
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress2

**Comment by BruceForstall** [comment]
@briansull @sandreenko I made a couple tweaks to this change if you want to take another look: (1) handle the remorph case: get the isNonStandardArg value from the current arg entry, and (2) added a bunch of comments about why we're seeing these secure delegate calls in the first place.

**Comment by BruceForstall** [comment]
A zillion Jenkins infra errors. Rerunning (almost) everything.

@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked corefx_minopts
@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8
@dotnet-bot test Windows_NT x86 Checked minopts
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x86 Checked r2r_jitminopts
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked tailcallstress
@dotnet-bot test Windows_NT x86 Release r2r

@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x64 Checked jitstress1
@dotnet-bot test Windows_NT x64 Checked jitstress2
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress1
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test

@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
(1) Jenkins restarted and lost all my links, (2) a corefx regression was introduced and has now been fixed.

Try again to get clean:

@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked corefx_minopts
@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8
@dotnet-bot test Windows_NT x86 Checked minopts
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x86 Checked r2r_jitminopts
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked tailcallstress
@dotnet-bot test Windows_NT x86 Release r2r

@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x64 Checked jitstress1
@dotnet-bot test Windows_NT x64 Checked jitstress2
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress1
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test

@dotnet-bot test Ubuntu arm Cross Checked Innerloop Build and Test

**Comment by BruceForstall** [comment]
More infra issues? need to start and restart the job to try and kick them all off.

**Comment by BruceForstall** [comment]
@dotnet-bot test this please

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked corefx_baseline Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked minopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked normal Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitminopts Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstress2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x10 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs0x80 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs1 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs2 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs3 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs4 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked tailcallstress Build and Test
@dotnet-bot test Ubuntu arm Cross Debug normal Build
@dotnet-bot test Ubuntu arm Cross Release normal Build and Test
@dotnet-bot test Ubuntu arm Cross Release r2r Build and Test

@dotnet-bot test Windows_NT x86 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked corefx_baseline
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstress2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked corefx_minopts
@dotnet-bot test Windows_NT x86 Checked jitstress1
@dotnet-bot test Windows_NT x86 Checked jitstress2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked jitstressregs1
@dotnet-bot test Windows_NT x86 Checked jitstressregs2
@dotnet-bot test Windows_NT x86 Checked jitstressregs3
@dotnet-bot test Windows_NT x86 Checked jitstressregs4
@dotnet-bot test Windows_NT x86 Checked jitstressregs8
@dotnet-bot test Windows_NT x86 Checked minopts
@dotnet-bot test Windows_NT x86 Checked r2r
@dotnet-bot test Windows_NT x86 Checked r2r_jitminopts
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x10
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x1000
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs0x80
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs1
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs2
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs3
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs4
@dotnet-bot test Windows_NT x86 Checked r2r_jitstressregs8
@dotnet-bot test Windows_NT x86 Checked tailcallstress
@dotnet-bot test Windows_NT x86 Release r2r

@dotnet-bot test Windows_NT x64 Build and Test
@dotnet-bot test Windows_NT x64 Checked jitstress1
@dotnet-bot test Windows_NT x64 Checked jitstress2
@dotnet-bot test Windows_NT x64 Checked corefx_baseline
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress1
@dotnet-bot test Windows_NT x64 Checked corefx_jitstress2

@dotnet-bot test Ubuntu x64 Build and Test
@dotnet-bot test Ubuntu x64 Checked jitstress1
@dotnet-bot test Ubuntu x64 Checked jitstress2
@dotnet-bot test Ubuntu x64 Checked corefx_baseline
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress1
@dotnet-bot test Ubuntu x64 Checked corefx_jitstress2

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86 Checked R2R jitstress1 Build & Test

**Comment by BruceForstall** [comment]
Failures:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs2_tst_prtest/6/
```
System.Net.NameResolution.Functional.Tests:
   System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(hostName: \"\") [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
...
```
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs2 Build and Test

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_minopts_tst_prtest/7/consoleText
```
   System.Linq.Parallel.Tests.AggregateTests.Aggregate_AggregateException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.AggregateException)
      Actual:   (No exception was thrown)
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_minopts_prtest/_/fx/src/System.Linq.Parallel/tests/Helpers/AssertThrows.cs(76,0): at System.Linq.Parallel.Tests.AssertThrows.Wrapped[T](Action action)
```
@dotnet-bot test Ubuntu arm Cross Checked corefx_minopts Build and Test

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_jitstressregs0x1000_tst_prtest/3/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_jitstressregs0x1000_tst_prtest/4/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_jitstressregs4_tst_prtest/4/consoleText
```
FAILED   - baseservices/threading/interlocked/compareexchange/CompareExchangeTString/CompareExchangeTString.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs0x1000_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun CompareExchangeTString.exe empty
               Creating threads
               Joining threads
               Test Expected , but found emptyempty
               Test Failed
               Expected: 100
               Actual: 0
               END EXECUTION - FAILED
```
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs0x1000 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked jitstressregs4 Build and Test

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/3/consoleText
```
FAILED   - baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/bin/tests/Linux.arm.Checked/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/bin/tests/Linux.arm.Checked/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType /in FixedAddressValueType.org /out FixedAddressValueType.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image FixedAddressValueType.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun FixedAddressValueType.exe
               in ReleaseLock
               Expected: 100
               Actual: 255
               END EXECUTION - FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress1_prtest/5/#showFailuresLink
"normal" StackFrameTests failures

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress2_prtest/6/consoleText
```
  Starting:    System.Diagnostics.StackTrace.Tests
     System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected [FAIL]
        Assert.NotEqual() Failure
        Expected: Not Void SkipFrames_CallMethod_ReturnsExpected()
        Actual:   Void SkipFrames_CallMethod_ReturnsExpected()
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline_tst_prtest/2/console
```
18:04:22 ERROR: Failed to copy artifacts from dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest with filter: **
```
I don't think this job works.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_flow_prtest/3214/
timeout
@dotnet-bot test Ubuntu x64 Checked Innerloop Build and Test

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_tst_prtest/702/console
machine ARM64-AMD-023 misconfiguration

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress1_prtest/61/
```
  BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---61cc5bbe\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" waitanyex2a.exe 
        Testing Mutex and non-Mutex, and signaling the other element
        Acquire the Mutex
        Holding the Mutex
        Expected: 100
        Actual: -1073740791
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```
"normal" random failure in waitany

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1_prtest/6/
```
Test Result (5 failures / ±0)DataContractSerializerTests.DCS_ResolveDatacontractBaseTypeDataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespaceSystem.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2)
```
Failures exist in baseline: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2_prtest/12/#showFailuresLink
```
Test Result (3 failures / ±0)System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpectedDataContractSerializerTests.DCS_ResolveDatacontractBaseTypeDataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace
```
Failures exist in baseline: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitstress2_jitstressregs3_prtest/26/
```
D:\j\workspace\x86_checked_w---e8e81761\bin\tests\Windows_NT.x86.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs(17607): error : baseservices_threading._mutex_misc_waitone2_waitone2_._mutex_misc_waitone2_waitone2_cmd [FAIL] [D:\j\workspace\x86_checked_w---e8e81761\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---e8e81761\bin\tests\Windows_NT.x86.Checked\Reports\baseservices.threading\mutex\misc\waitone2\waitone2.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---e8e81761\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" waitone2.exe 
        Beginning test case MutexWaitOne2 at 5/2/2018 6:12:42 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        [Positive]
        Beginning scenario: PosTest1: Wait Infinite
        Beginning scenario: PosTest2: Wait some finite time
        Beginning scenario: PosTest3: Wait some finite time will quit for timeout
        ERROR!!!-004: WaitOne returns true when wait time out
        Beginning scenario: PosTest4: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest5: Wait some finite time will quit for timeout when another thread is in nondefault managed context
        Beginning scenario: PosTest6: Wait infinite time when another thread is in nondefault managed context
        Beginning scenario: PosTest7: Wait infinite time when another thread is in nondefault managed context
        [Negative]
        Beginning scenario: NegTest1: AbandonedMutexException should be thrown if a thread exited without releasing a mutex
        Beginning scenario: NegTest2: ObjectDisposedException should be thrown if current instance has already been disposed
        Beginning scenario: NegTest3: Check ArgumentOutOfRangeException will be thrown if millisecondsTimeout is a negative number other than -1
        
        Ending test case at 5/2/2018 6:13:14 PM
        FAIL
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
```
"normal" random failure in waitone2

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_minopts_prtest/10/#showFailuresLink
```
Test Result (8 failures / ±0)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2)System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpectedSystem.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: null, lineNumber: -1)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: \"\", lineNumber: 0)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber(fileName: \"FileName\", lineNumber: 1)System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix
```
Failures exist in baseline: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_minopts/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1_prtest/7/#showFailuresLink
```
Test Result (3 failures / -2)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1)System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2)
```
Failures exist in baseline: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1/

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress2_prtest/8/#showFailuresLink
```
Test Result (14 failures / ±0)System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutAfterStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutAfterStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutNoStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutAfterStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutAfterStart_GetReturnsNewValueSystem.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutAfterStart_GetReturnsNewValueSystem.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected
```
failures exist in baseline: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress2/470/#showFailuresLink

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs0x10_prtest/15/
```
17:23:29 FATAL: command execution failed
17:23:29 java.nio.channels.ClosedChannelException
```
Jenkins issue.
@dotnet-bot test @dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs0x10

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs3_prtest/16/
```
     System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryAsyncErrorTest [FAIL]
        Timed out after 60000ms waiting for remote process 5984
```
This has been seen before, but I don't see any issue.
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs3

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs4_prtest/6/
```
     System.Data.SqlClient.Tests.DiagnosticTest.ExecuteScalarAsyncTest [FAIL]
        Timed out after 60000ms waiting for remote process 5296
        Expected: True
        Actual:   False
```
same as above.
@dotnet-bot test Windows_NT x86 Checked corefx_jitstressregs4

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_r2r_jitstress1_prtest/6/
```
17:54:19 FATAL: command execution failed
17:54:19 java.nio.channels.ClosedChannelException
```
Jenkins issue
@dotnet-bot test Windows_NT x86 Checked r2r_jitstress1

**Comment by BruceForstall** [comment]
Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test

**Comment by BruceForstall** [comment]
@dotnet-bot test Ubuntu arm Cross Checked jitstress2_jitstressregs0x1000 Build and Test

**Comment by BruceForstall** [comment]
Baseline https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_r2r_jitstress2_tst/9/consoleText got:
```
FAILED   - baseservices/threading/interlocked/compareexchange/CompareExchangeTString/CompareExchangeTString.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Linux.arm.Checked/baseservices/threading/interlocked/compareexchange/CompareExchangeTString/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Linux.arm.Checked/baseservices/threading/interlocked/compareexchange/CompareExchangeTString /in CompareExchangeTString.org /out CompareExchangeTString.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image CompareExchangeTString.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun CompareExchangeTString.exe empty
               Creating threads
               Joining threads
               Test Expected , but found empty
               Test Failed
               in ReleaseLock
               Expected: 100
               Actual: 0
               END EXECUTION - FAILED
```

**Comment by BruceForstall** [comment]
I couldn't repro the r2r_jitstress2 failure manually.
