### PR TITLE
Copy address-taken SIMD intrinsic

### LINKED ISSUE #21854: Boxing vectors results in "Common Language Runtime detected an invalid program."
Repros 100% on Win10 x64 3.0.0-preview-27218-01.

Minimal repro code:

```cs
static void Main(string[] args)
{
    var unused = new object[] { Vector<int>.Zero };
}
```

When compiling this under _Debug_ mode, the program exits without error. When compiling this under _Release_ mode, the CLR fails with the below message.

```txt
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ConsoleAppTestVectors.Program.Main(String[] args)
```

Here's the Debug IL:

```txt
.method private hidebysig static 
	void Main (
		string[] args
	) cil managed 
{
	// Method begins at RVA 0x2048
	// Code size 22 (0x16)
	.maxstack 4
	.entrypoint
	.locals init (
		[0] object[]
	)

	IL_0000: nop
	IL_0001: ldc.i4.1
	IL_0002: newarr [System.Runtime]System.Object
	IL_0007: dup
	IL_0008: ldc.i4.0
	IL_0009: call valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<!0> valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<int32>::get_Zero()
	IL_000e: box valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<int32>
	IL_0013: stelem.ref
	IL_0014: stloc.0
	IL_0015: ret
} // end of method Program::Main
```

And here's the Release IL:

```txt
.method private hidebysig static 
	void Main (
		string[] args
	) cil managed 
{
	// Method begins at RVA 0x2048
	// Code size 21 (0x15)
	.maxstack 8
	.entrypoint

	IL_0000: ldc.i4.1
	IL_0001: newarr [System.Runtime]System.Object
	IL_0006: dup
	IL_0007: ldc.i4.0
	IL_0008: call valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<!0> valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<int32>::get_Zero()
	IL_000d: box valuetype [System.Numerics.Vectors]System.Numerics.Vector`1<int32>
	IL_0012: stelem.ref
	IL_0013: pop
	IL_0014: ret
} // end of method Program::Main
```

I've filed this under CoreClr instead of Roslyn because the IL appears correct to me. I don't see what would cause the verifier to believe that this is an invalid assembly.

### PR DESCRIPTION
**Pull request by CarolEidt**
This occurs, for example, when boxing the result of a SIMD intrinsic. This was being handled for the HW intrinsic case, but not the SIMD Vector intrinsics. Also, eliminate `OperIsSimdHWIntrisic` since it redundantly checks for the case of a SIMD result, even though it was always called in a context where the result is known to be a struct type.

Fix #21854

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL
cc @tannergooding @fiigii

**Comment by fiigii** [comment]
> Also, eliminate OperIsSimdHWIntrisic since it redundantly checks for the case of a SIMD result, even though it was always called in a context where the result is known to be a struct type.

That would be great, thanks.

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -1426,7 +1425,7 @@ GenTree* Compiler::impGetStructAddr(GenTree*             structVal,
         return (structVal->gtObj.Addr());
     }
     else if (oper == GT_CALL || oper == GT_RET_EXPR || oper == GT_OBJ || oper == GT_MKREFANY ||
-             structVal->OperIsSimdHWIntrinsic())
+             structVal->OperIsSIMDorHWintrinsic())
```
Comment (tannergooding) [inline src/jit/importer.cpp]: Just wanted to confirm, this is now also checking for SIMD nodes and is what fixes the bug, the other changes are just simplifying the checks (from two calls into one) and calling the renamed method (`OperIsSimdOrHWIntrinsic()`). Correct?

File: src/jit/gentree.h [hunk 2]
```diff
@@ -1518,18 +1518,9 @@ struct GenTree
...
-    inline bool OperIsSimdHWIntrinsic() const;
-#else
-    inline bool OperIsSimdHWIntrinsic() const
-    {
-        return false;
-    }
-#endif
-
-    bool OperIsSIMDorSimdHWintrinsic() const
+    bool OperIsSIMDorHWintrinsic() const
```
Comment (tannergooding) [inline src/jit/gentree.h]: Should this be cased as `OperIsSimdOrHWIntrinsic`?

File: src/jit/importer.cpp [hunk 3]
```diff
@@ -1146,8 +1146,7 @@ GenTree* Compiler::impAssignStructPtr(GenTree*             destAddr,
     assert(src->gtOper == GT_LCL_VAR || src->gtOper == GT_FIELD || src->gtOper == GT_IND || src->gtOper == GT_OBJ ||
```
Comment (sandreenko) [inline src/jit/importer.cpp]: Maybe it would be nice to replace this long list of `gtOper == one || gtOper == two || ,,,` with `src->OperIs(one, two, ...)`.

File: src/jit/importer.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: Yes, that's correct.

File: src/jit/importer.cpp (hunk 3 above)
Comment (CarolEidt) [reply src/jit/importer.cpp]: Good suggestion

File: src/jit/gentree.h (hunk 2 above)
Comment (CarolEidt) [reply src/jit/gentree.h]: Probably. Will change.

Comment (mikedn) [reply src/jit/gentree.h]: The JIT mainly uses "SIMD", not "Simd".

Comment (tannergooding) [reply src/jit/gentree.h]: > The JIT mainly uses "SIMD", not "Simd".

Yes, it looks that way. Grepping the codebase I get:
* 4843 hits for `SIMD`
* 1709 hits for `simd`
* 1701 hits for `Simd`

It would be nice if we could standardize on one. My preference would be for `Simd`, as it matches the casing specified in the general .NET Framework Design Guidelines and it makes it easier to read (although I don't feel particularly strongly on this point, given that it is native code; rather than managed).

Comment (mikedn) [reply src/jit/gentree.h]: >  as it matches the casing specified in the general .NET Framework Design Guidelines

This isn't C# code.

> and it makes it easier to read

Well, if Simdor looks more readable than SIMDor…

> 1709 hits for simd

Those are variable names.

> 1701 hits for Simd

Those exist only because the people who worked on HW intrinsics ignored the already established naming.

Comment (CarolEidt) [reply src/jit/gentree.h]: Personally I would prefer `SIMD`, but the JIT coding conventions say otherwise: https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#84-local-variables (that's for local variables, but my presumption is that applies generally to identifiers).

I believe that we have intentionally avoided undertaking any massive changes, but it makes sense to ensure that new or modified names are in conformance.

Comment (tannergooding) [reply src/jit/gentree.h]: > This isn't C# code.

I know, and I mentioned as such. My preference, however, is just towards a consistent casing scheme across both and to follow the existing well-defined rules that were already fairly extensively discussed/reviewed/etc.

> Well, if Simdor looks more readable than SIMDor…

The `Or` would also be capitilized (following standard pascal casing):
* `SimdOr`
* `SIMDOr`
* `Simdor`
* `SIMDor`

Comment (mikedn) [reply src/jit/gentree.h]: > but the JIT coding conventions say otherwise

Ha ha, those aren't even consistent with .NET Framework Design Guidelines that says that if it has only 2 characters it's all upper case - `EEConfig` and not `EeConfig`.

Comment (tannergooding) [reply src/jit/gentree.h]: > but my presumption is that applies generally to identifiers

@CarolEidt, it looks to be explicitly covered under 8.9 (given this is a function): https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#89-functions-including-member-functions

Comment (CarolEidt) [reply src/jit/gentree.h]: But that section isn't explicit about acronyms, though perhaps that's implied by "Pascal Casing" (I'm certainly not an expert in coding conventions).

Comment (fiigii) [reply src/jit/gentree.h]: > Personally I would prefer SIMD,

Me too. This is not only about coding convention that is more about RyuJIT history... We have `V.N.Vectors` and `S.R.I.VectorXXX`,  and`V.N.Vectors` have used "SIMD" for a long time, so I named HW intrinsic related stuff in "Simd" at the very beginning. I know this is not a good style, but sometimes useful...

Comment (CarolEidt) [reply src/jit/gentree.h]: I consider @BruceForstall to be the expert in the JIT coding conventions. I don't want to open up a discussion about this (I think we can all agree that such discussions quickly devolve), but it would be great if he could agree (or not) that `Simd` is what is specified in the conventions, and therefore wjat we should evolve to.

Comment (BruceForstall) [reply src/jit/gentree.h]: The JIT coding conventions would say to use "Simd" in function and class names, but I view those as guidelines; I'm certainly willing to accept exceptions, if well motivated. (IMO, in this case I prefer @tannergooding 's `OperIsSimdOrHWIntrinsic` suggestion. `OperIsSimdOrHwIntrinsic` -- with a lower-case `w` for `Hw` looks odd.)
