### PR TITLE
Fix field type for ByReference<T> and TypedReference

### LINKED ISSUE #7894: Span<T>.Slice method is hitting asserts in JIT on Unix
`Assertion failed '((regMask & emitThisGCrefRegs) && (ins == INS_add)) || ((regMask & emitThisByrefRegs) && (ins == INS_add || ins == INS_sub))' in 'System.Span`1[Byte][System.Byte]:Slice(int,int):struct:this' (IL size 44)`

### PR DESCRIPTION
**Pull request by kouvel**
Fixes #7894

### CODE REVIEW

**Comment by kouvel** [comment]
@jkotas @sivarv

File: src/vm/methodtablebuilder.cpp [hunk 1]
```diff
@@ -10235,6 +10236,12 @@ void MethodTableBuilder::CheckForSystemTypes()
             pMT->ClearFlag(MethodTable::enum_flag_Category_Mask);
             pMT->SetInternalCorElementType(ELEMENT_TYPE_VALUETYPE);
 #endif
+
+            // Fix the element type of the by-ref field
+            _ASSERTE(pMT->GetNumIntroducedInstanceFields() == 1);
+            PTR_FieldDesc byRefFieldDesc = pMT->GetFieldDescByIndex(0);
+            _ASSERTE(byRefFieldDesc->GetFieldType() == ELEMENT_TYPE_I);
+            byRefFieldDesc->SetFieldType(ELEMENT_TYPE_BYREF);
```
Comment (jkotas) [inline src/vm/methodtablebuilder.cpp]: I think it would be better to compensate for this on the JIT-EE interface just to make the JIT happy. It is very hard to make this self-consistent in the VM, e.g. the parts of the VM that access metadata directly will still see the IntPtr and not byref.

Comment (kouvel) [inline src/vm/methodtablebuilder.cpp]: Done

File: src/vm/jitinterface.cpp [hunk 2]
```diff
@@ -9105,30 +9105,47 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
-    if (!CorTypeInfo::IsPrimitiveType(type))
+    if (type != ELEMENT_TYPE_BYREF)
     {
-        PCCOR_SIGNATURE sig;
-        DWORD sigCount;
-        CorCallingConvention conv;
+        // For verifying code involving generics, use the class instantiation
+        // of the optional owner (to provide exact, not representative,
+        // type information)
+        SigTypeContext typeContext(field, (TypeHandle)owner);
```
Comment (jkotas) [inline src/vm/jitinterface.cpp]: The SigTypeContext constructor does not have any interesting side-effects. You can move it right in front of GetTypeHandleThrowing where it is used.

Comment (kouvel) [inline src/vm/jitinterface.cpp]: Done

File: src/vm/jitinterface.cpp [hunk 3]
```diff
@@ -9105,30 +9105,47 @@ CorInfoType CEEInfo::getFieldTypeInternal (CORINFO_FIELD_HANDLE fieldHnd,
...
+    {
+        PTR_MethodTable enclosingMethodTable = field->GetApproxEnclosingMethodTable();
+        if (enclosingMethodTable->IsByRefLike() &&
+            (
+                enclosingMethodTable == g_TypedReferenceMT && field->GetOffset() == 0 ||
+                enclosingMethodTable->HasSameTypeDefAs(g_pByReferenceClass)
+            ))
+        {
+            _ASSERTE(field->GetOffset() == 0);
+            type = ELEMENT_TYPE_BYREF;
```
Comment (jkotas) [inline src/vm/jitinterface.cpp]: I think it would be better to just do early out here - `if (pTypeHnd != NULL) *pTypeHnd = NULL; return CORINFO_TYPE_BYREF`, so that it is obvious what happens in this case. It is not easy to follow it through `asCorInfoType`.

Comment (kouvel) [inline src/vm/jitinterface.cpp]: At the top of the function it already does `*pTypeHnd = 0`, so I guess it's not null currently. Should it check for null?

Comment (kouvel) [inline src/vm/jitinterface.cpp]: Since `typeHnd.IsNull()` in `CEEInfo::asCorInfoType` would always be true here, changed to shortcut anyway.

**Comment by jkotas** [comment]
Looks good so far ... crossgen S.P.CoreLib is still crashing though.

**Comment by kouvel** [comment]
It doesn't seem to like returning ByRef for `TypedReference`. Don't know why, and I suppose that must be handled already somehow, but this seems to work.

**Comment by jkotas** [comment]
Make sense. I was kind of surprised that you are able to get away with doing it for TypedReference as well.
