### PR TITLE
Arm64: Fix handling of IP0 & IP1

### LINKED ISSUE #14607: [RyuJIT/arm64] Determine treatment of special regs
Issue #14591 was caused by an inconsistency in the register sets used by LSRA. In particular, the "special" registers IP0, IP1, PR, FP, andLR. In PR #14606 I have added IP0 and IP1 to the set of registers in `REG_VAR_ORDER`, and excluded the others in `availableIntRegs`. This needs to be revisited by someone more intimately familiar with the ABI to ensure that this is the correct treatment.

### LINKED ISSUE #16359: [Arm64/Linux] JitStressRegs=0x200 staticFieldExpr1_ro_loop lsra failure
With JitStressRegs=0x200

JIT/jit64/opt/cse/staticFieldExpr1_ro_loop/staticFieldExpr1_ro_loop.sh

```
corerun staticFieldExpr1_ro_loop.exe

Assert failure(PID 4758 [0x00001296], Thread: 4758 [0x1296]): 
Assertion failed 'isRefPositionActive(assignedInterval->recentRefPosition, refPosition->nodeLocation)' 
in 'CseTest.Test_Main:Main():int' (IL size 1267)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 3391
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

### LINKED ISSUE #17861: [Arm64] JitStressRegs=0x200 GitHub_17777 asserts
JIT/Regression/JitBlue/GitHub_17777/GitHub_17777/GitHub_17777.sh
jitStressRegs=0x200

```
corerun GitHub_17777.exe

Assert failure(PID 1462 [0x000005b6], Thread: 1462 [0x05b6]): Assertion failed 
'!"Unexpected inactive assigned interval in isRegInUse"' in 
'Repro.Program:Test(int,int,int,int,int,int,int,int,int,int,int,int,int,int......' 
(IL size 2418)

    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/jit/lsra.cpp Line: 3441
```

@briansull @CarolEidt Assert is in lsra

### PR DESCRIPTION
**Pull request by CarolEidt**
These are sometimes mandated to be allocated to certain nodes, but they were not in the list of allocatable registers (REG_VAR_ORDER). This led to special handling in LSRA, which, it turns out, was incomplete. This resulted in failures for JitStressRegs=0x200.
Based on the discussion in #14607, this adds IP0 to RBM_CALLEE_TRASH_NOGC, and fixes the REG_VAR_ORDER.

Fix #14607, Fix #16359, Fix #17861

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Ubuntu x64 Checked CoreFX Tests
@dotnet-bot test Ubuntu x64 Formatting

**Comment by CarolEidt** [comment]
@jashook @sdmaclea - I believe that this not only fixes the JitStressRegs=0x200 issues (#16359 and #17861) but also addresses #14607.
@dotnet/jit-contrib PTAL

File: src/jit/target.h [hunk 1]
```diff
@@ -1373,7 +1376,7 @@ typedef unsigned char   regNumberSmall;
   #define REG_WRITE_BARRIER_SRC_BYREF    REG_R13
   #define RBM_WRITE_BARRIER_SRC_BYREF    RBM_R13
 
-  #define RBM_CALLEE_TRASH_NOGC          (RBM_R12|RBM_R15|RBM_IP1|RBM_DEFAULT_HELPER_CALL_TARGET)
+  #define RBM_CALLEE_TRASH_NOGC          (RBM_R12|RBM_R15|RBM_IP0|RBM_IP1|RBM_DEFAULT_HELPER_CALL_TARGET)
```
Comment (sdmaclea) [inline src/jit/target.h]: `RBM_DEFAULT_HELPER_CALL_TARGET==RBM_R12` currently ...

**Comment by sdmaclea** [comment]
Carol you should also know that IP0/IP1 are reserved in the ABI for linking stubs.  Any branch with target out of range is free to contaminate these.  

There were places where they were used without being reserved as quick and dirty temporaries.  I don't remember if that has been cleaned up.

**Comment by CarolEidt** [comment]
@sdmaclean filed #19029 for the jitstressregs8 failures (not connected with this change).
The other legs all fail in the readytorun/r2dump/R2RDumpTest, and it doesn't seem to pass for me locally, even without altjit.

**Comment by sdmaclea** [comment]
`R2RDumpTest` also failed for me locally last night.  It expects a dotnet cli in the test path which is not present in my environment.  I chose to not report it.  @BruceForstall reported an issue with it today though.

**Comment by sdmaclea** [comment]
See #19011

**Comment by CarolEidt** [comment]
@sdmaclea - thanks for all your help. I'm going to merge this, and have filed #19034 to track whether IP0 and IP1 are being appropriately reserved for branch stubs.
