### PR TITLE
Abort FuncEval on unaligned SP

### LINKED ISSUE #25753: Func eval of SpanDebugView crashes when stepping over stackalloc
## Repro steps
1. Create the following program
2. Set a breakpoint on the commented line
3. Hit F10 twice (https://github.com/dotnet/coreclr/issues/14926 tracks the need for this). You will now be stopped at the highlighted instruction (see 'Disassembly' below)
4. Evaluate `mib`

### Result
Target process crashes in `coreclr.dll!ClassLoader::LoadTypeHandleForTypeKey_Body` resulting in the following message from VS:

\---------------------------
Microsoft Visual Studio
\---------------------------
The target process exited with code -2146233082 while evaluating the function 'System.SpanDebugView<T>.SpanDebugView'.

If the problem happens regularly, consider disabling the Tools->Options setting "Debugging->General->Enable property evaluation and other implicit function calls" or debugging the cause by evaluating the expression from the Immediate window. See help for information on doing this.
\---------------------------
OK   Help   
\---------------------------

### Call stack
coreclr.dll!ClassLoader::LoadTypeHandleForTypeKey_Body(TypeKey * pTypeKey, TypeHandle typeHnd, ClassLoadLevel targetLevel) Line 3778
	at f:\workspace.1\_work\1\s\src\vm\clsload.cpp(3778)
coreclr.dll!ClassLoader::LoadTypeHandleForTypeKey(TypeKey * pTypeKey, TypeHandle typeHnd, ClassLoadLevel targetLevel, const InstantiationContext * pInstContext) Line 3677
	at f:\workspace.1\_work\1\s\src\vm\clsload.cpp(3677)
coreclr.dll!ClassLoader::LoadTypeDefThrowing(Module * pModule, unsigned int typeDef, ClassLoader::NotFoundAction fNotFoundAction, ClassLoader::PermitUninstantiatedFlag fUninstantiated, unsigned int tokenNotToLoad, ClassLoadLevel level, Instantiation * pTargetInstantiation) Line 2565
	at f:\workspace.1\_work\1\s\src\vm\clsload.cpp(2565)
coreclr.dll!ClassLoader::LoadTypeDefOrRefThrowing(Module * pModule, unsigned int typeDefOrRef, ClassLoader::NotFoundAction fNotFoundAction, ClassLoader::PermitUninstantiatedFlag fUninstantiated, unsigned int tokenNotToLoad, ClassLoadLevel level) Line 2737
	at f:\workspace.1\_work\1\s\src\vm\clsload.cpp(2737)
coreclr.dll!EEDbgInterfaceImpl::LoadClass(Module * pModule, unsigned int classToken) Line 951
	at f:\workspace.1\_work\1\s\src\vm\eedbginterfaceimpl.cpp(951)
coreclr.dll!EEDbgInterfaceImpl::LoadMethodDef(Module * pModule, unsigned int methodDef, unsigned long numGenericArgs, TypeHandle * pGenericArgs, TypeHandle * pOwnerType) Line 803
	at f:\workspace.1\_work\1\s\src\vm\eedbginterfaceimpl.cpp(803)
coreclr.dll!ResolveFuncEvalGenericArgInfo(DebuggerEval * pDE) Line 1550
	at f:\workspace.1\_work\1\s\src\debug\ee\funceval.cpp(1550)
coreclr.dll!DoNormalFuncEval(DebuggerEval * pDE, unsigned char * pCatcherStackAddr, Object * * pObjectRefArray, void * * pMaybeInteriorPtrArray, void * * pByRefMaybeInteriorPtrArray, __int64 * pBufferForArgsArray, ValueClassInfo * * ppProtectedValueClasses) Line 3087
	at f:\workspace.1\_work\1\s\src\debug\ee\funceval.cpp(3087)
coreclr.dll!GCProtectArgsAndDoNormalFuncEval(DebuggerEval * pDE, unsigned char * pCatcherStackAddr) Line 3441
	at f:\workspace.1\_work\1\s\src\debug\ee\funceval.cpp(3441)
coreclr.dll!FuncEvalHijackRealWorker(DebuggerEval * pDE, Thread * pFEFrame, FuncEvalFrame *) Line 3659
	at f:\workspace.1\_work\1\s\src\debug\ee\funceval.cpp(3659)
coreclr.dll!FuncEvalHijackWorker(DebuggerEval * pDE) Line 3782
	at f:\workspace.1\_work\1\s\src\debug\ee\funceval.cpp(3782)
coreclr.dll!FuncEvalHijack() Line 27
	at F:\workspace.1\_work\1\s\src\debug\ee\amd64\dbghelpers.asm(27)

### Notes
* This reproduces on macOS and Windows on 3.0-preview6, I can also see the problem on Windows in .NET Core 2.2.5, so it doesn't seem to be a regression.
* I can reproduce the same problem with `Span<char>`.
* I didn't investigate if possibly VS is doing something wrong in the way we request the func-eval, so if you can't reproduce this in mdbg let me know and I can see if maybe the problem is on our side.
* If I inspect the span using interpretation instead of func-eval everything works.

### Program

```C#
        static void Main(string[] args)
        {
            Span<int> mib = stackalloc int[3]; // breakpoint here
            mib[0] = 42;

            Console.WriteLine("Hello World {0}!", mib[0]);
        }
```

### Disassembly

```
            Span<int> mib = stackalloc int[3];
00007FFEF90D0FD9  lea         rcx,[rbp+28h]  
00007FFEF90D0FDD  mov         edx,0Ch  
00007FFEF90D0FE2  mov         edx,edx  
00007FFEF90D0FE4  test        rdx,rdx  
00007FFEF90D0FE7  je          00007FFEF90D1007  
00007FFEF90D0FE9  add         rdx,0Fh  
00007FFEF90D0FED  shr         rdx,4  
00007FFEF90D0FF1  add         rsp,20h  
00007FFEF90D0FF5  push        0  
*** 00007FFEF90D0FF7  push        0    // crash when evaluate from here
00007FFEF90D0FF9  dec         rdx  
00007FFEF90D0FFC  jne         00007FFEF90D0FF5  
00007FFEF90D0FFE  sub         rsp,20h  
00007FFEF90D1002  lea         rdx,[rsp+20h]  
00007FFEF90D1007  mov         r8d,3  
00007FFEF90D100D  call        00007FFEF90D0730  
00007FFEF90D1012  vmovdqu     xmm0,xmmword ptr [rbp+28h]  
00007FFEF90D1017  vmovdqu     xmmword ptr [rbp+38h],xmm0  
00007FFEF90D101C  vmovdqu     xmm0,xmmword ptr [rbp+38h]  
00007FFEF90D1021  vmovdqu     xmmword ptr [rbp+48h],xmm0  
```

### PR DESCRIPTION
**Pull request by sdmaclea**
When the debugger is stopped at an arbitrary assembly instruction, the SP is not guaranteed to be aligned. We can't run `FuncEval` on an unaligned thread.

Fixes #25753 

/cc @davidfowl @gregg-miskelly

### CODE REVIEW

**Comment by davidfowl** [comment]
Can we get this in 3.0?

**Comment by sdmaclea** [comment]
@davidfowl I think we missed the window for 3.0 RTM, but I can ask. It will definitely need to be back ported for 3.1.

**Comment by davidfowl** [comment]
> @davidfowl I think we missed the window for 3.0 RTM, but I can ask. It will definitely need to be back ported for 3.1.

We're still taking changes for 3.0 if they meet the bar. The severity seems bad enough here that we should at least try.

File: src/debug/ee/debugger.cpp [hunk 1]
```diff
@@ -15354,6 +15354,10 @@ HRESULT Debugger::FuncEvalSetup(DebuggerIPCE_FuncEvalInfo *pEvalInfo,
         _ASSERTE(filterContext != NULL);
 
         ::SetIP(filterContext, (UINT_PTR)GetEEFuncEntryPoint(::FuncEvalHijack));
+        // The SP must be aligned at call boundaries, but not necessarily on every assembly instruction
+        // Since we are hijacking the thread at an arbitrary location, we must align the SP.
+        // Align the stack down to STACK_ALIGN_SIZE
+        ::SetSP(filterContext, ALIGN_DOWN(::GetSP(filterContext), STACK_ALIGN_SIZE));
```
Comment (janvorli) [inline src/debug/ee/debugger.cpp]: I am not familiar with the code, but I wonder - don't we need to fix the SP back to its original value after the funceval somehow? We are getting a context pointer to the Thread::m_debuggerFilterContext and I wonder if that context is not used for other stuff in the debugger too.

Comment (sdmaclea) [reply src/debug/ee/debugger.cpp]: I was wondering the same thing myself all weekend. I think that's why I added you as a reviewer...

I have abandoned this approach.

File: src/debug/ee/debugger.cpp [hunk 2]
```diff
@@ -15306,6 +15306,13 @@ HRESULT Debugger::FuncEvalSetup(DebuggerIPCE_FuncEvalInfo *pEvalInfo,
         return CORDBG_E_ILLEGAL_AT_GC_UNSAFE_POINT;
     }
 
+    if (::GetSP(filterContext) != ALIGN_DOWN(::GetSP(filterContext), STACK_ALIGN_SIZE))
+    {
+        // SP is not aligned, we cannot do a FuncEval here
+        LOG((LF_CORDB, LL_INFO1000, "D::FEA: SP is unaligned"));
+        return CORDBG_E_FUNC_EVAL_BAD_START_POINT;
```
Comment (sdmaclea) [inline src/debug/ee/debugger.cpp]: @gregg-miskelly I chose this error code as it seemed reasonable.  Would you prefer a different error code?

Comment (gregg-miskelly) [reply src/debug/ee/debugger.cpp]: Sounds reasonable to me.

File: src/debug/ee/debugger.cpp [hunk 3]
```diff
@@ -15306,6 +15306,13 @@ HRESULT Debugger::FuncEvalSetup(DebuggerIPCE_FuncEvalInfo *pEvalInfo,
         return CORDBG_E_ILLEGAL_AT_GC_UNSAFE_POINT;
     }
 
+    if (::GetSP(filterContext) != ALIGN_DOWN(::GetSP(filterContext), STACK_ALIGN_SIZE))
+    {
+        // SP is not aligned, we cannot do a FuncEval here
+        LOG((LF_CORDB, LL_INFO1000, "D::FES SP is unaligned"));
```
Comment (gregg-miskelly) [inline src/debug/ee/debugger.cpp]: Do you know if the x86 JIT will always try to keep the stack alignment at 4-bytes? Since the processor isn't very picky, I wasn't sure if the JIT would try very hard for that.

Comment (sdmaclea) [reply src/debug/ee/debugger.cpp]: The x86 JIT should enforce the `STACK_ALIGN_SIZE`, the JIT uses `STACK_ALIGN`.  I looked at PR history, and there are fixes to fix x86 stack alignment specifically for Linux, but the JIT should enforce either Windows or Linux alignment correctly.
