### PR TITLE
[ARM/Linux] Support unaligned struct read/write

### LINKED ISSUE #11200: [ARM/Linux] System.Runtime.CompilerServices.Unsafe.Tests failures (System.DataMisalignedException)
Unaligned access on double and struct seems to throw ``System.DataMisalignedException``:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.CompilerServices.Unsafe.Tests
Discovered:  System.Runtime.CompilerServices.Unsafe.Tests
Starting:    System.Runtime.CompilerServices.Unsafe.Tests
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct()
Finished:    System.Runtime.CompilerServices.Unsafe.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 113, Errors: 0, Failed: 6, Skipped: 0, Time: 306.077s
```

### PR DESCRIPTION
**Pull request by parjong**
#11224 partially addresses unaligned access issues (discussed in #11200), but unaligned struct read/write still raises System.DataMisalignedException.

This commit supports unaligned struct read/write to fix #11200.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@parjong btw, I assume you will remove the "[WIP]" and tag me (for example) when you are ready to have this reviewed.

**Comment by parjong** [comment]
@BruceForstall The code itself is already ready, but it takes time to run regression test. I'll remove [WIP] tag and tag you when test result is ready.

**Comment by BruceForstall** [comment]
@dotnet-bot test Tizen armel Cross Debug Build

**Comment by parjong** [comment]
@BruceForstall No regression is found under internal evaluation. Please take a look.

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -14819,6 +14819,11 @@ void Compiler::impImportBlockCode(BasicBlock* block)
                 }
                 op1->gtFlags |= GTF_EXCEPT;
 
+                if (prefixFlags & PREFIX_UNALIGNED)
+                {
+                    op1->gtFlags |= GTF_IND_UNALIGNED;
+                }
+
```
Comment (BruceForstall) [inline src/jit/importer.cpp]: Technically, I think this isn't valid to push down, since gtNewObjNode returns an OBJ, meaning you need to use GTF_BLK_UNALIGNED. (Unfortunately, we have no dynamic checking, and in fact that is the same value as GTF_IND_UNALIGNED right now, but you still should use the "right" one).

Comment (parjong) [inline src/jit/importer.cpp]: @BruceForstall I found that ``GenTreeObj`` is derived from ``GenTreeIndir``, and thus used ``GTF_IND_UNALIGNED`` instead of ``GTF_BLK_UNALIGNED`` (which seems to be more generally applicable according to class hierarchy) here.

Are ``GTF_BLK_UNALIGNED`` and ``GTF_IND_UNALIGNED`` mutually exclusive? If not, it seems that we should set both flags for gtNewObjNode path (Please correct me if I am wrong).

BTW, could you let me know if there are any documents about GenTree? I read RuyJIT overview, but the details on each GenTree node seems to be missing.

Comment (BruceForstall) [inline src/jit/importer.cpp]: Ah, ok. It turns out `GTF_BLK_UNALIGNED` is exactly the same as `GTF_IND_UNALIGNED`, by design. So the code here is ok.

> BTW, could you let me know if there are any documents about GenTree?

Unfortunately, there is not very much documentation except for gentree.h itself. We could do better. I'd certainly like the comments for each GenTree class to be more verbose.

**Comment by BruceForstall** [comment]
Since this touches common code, I don't want to merge this until the 'master' branch opens for .NET Core 2.1 changes, hopefully soon.

**Comment by parjong** [comment]
@BruceForstall Is master branch still closed for new changes?

**Comment by BruceForstall** [comment]
@parjong We are just starting to merge changes, in a bit of a staged manner. I'll merge this soon.

**Comment by BruceForstall** [comment]
@dotnet-bot test this please
