### PR TITLE
[x86/Linux] Do NOT use Shadow SP

### LINKED ISSUE #8887: [x86/Linux] Support Simple Exception Catch
I attempted to execute the following program with x86/Linux port:
```
using System;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            Console.WriteLine("Hello World!");
            throw new ArgumentException();
        }
        catch (Exception e)
        {
            Console.WriteLine("Caught");
        }
    }
}
```

CoreCLR currently shows the following assert failure for the above example:
```
Assert failure(PID 19154 [0x00004ad2], Thread: 19154 [0x4ad2]): iUnwindInfo < GetNumberOfUnwindInfos()
    File: /home/parjong/projects/dotnet/coreclr/src/vm/codeman.h Line: 342
    Image: /root/dotnet-test/overlay/current/corerun
```

### PR DESCRIPTION
**Pull request by parjong**
JIT with FEATURE_EH_FUNCLETS seems not to generate shadow SP slots, which results in assert failures inside GetHandlerFrameInfo.

This is another step to resolve #8887.

### CODE REVIEW

**Comment by parjong** [comment]
\CC @seanshpark

**Comment by parjong** [comment]
@dotnet-bot test OSX x64 Checked Build and Test please

**Comment by parjong** [comment]
@janvorli Please take a look.

File: src/vm/eetwain.cpp [hunk 1]
```diff
@@ -562,7 +562,8 @@ FrameType   GetHandlerFrameInfo(hdrInfo   * info,
     // The slots grow towards lower address on the stack and is terminted by a NULL entry.  
     // Since each subsequent slot contains the SP of a more nested EH clause, the contents of the slots are
     // expected to be in decreasing order.
-    size_t lvl;
+    size_t lvl = 0;
```
Comment (janvorli) [inline src/vm/eetwain.cpp]: @parjong looking at the code that calls this function, I wonder if it should be called at all for x86 with WIN64EXCEPTIONS. Most of the callers do nothing if the _TARGET_X86_ is not defined and it seems like these ifdefs should be augmented for _TARGET_X86_ && !WIN64EXCEPTIONS.
I am not 100% sure though.
@jkotas do you know if I am right here or will I need to look through the code to get full understanding?

Comment (jkotas) [inline src/vm/eetwain.cpp]: Both ifdefing the implementation or ifdefing all callers sounds plausible to me. I am not able to tell what will turn out better.

Comment (janvorli) [inline src/vm/eetwain.cpp]: @jkotas I guess I was not clear. My question was if this code is really meant just for the Windows x86 style EH.

Comment (jkotas) [inline src/vm/eetwain.cpp]: Yes, the shadow SP slots that this change is ifdefing out should not be needed for WIN64EXCEPTIONS.
