### PR TITLE
Copy all win32 resources

### LINKED ISSUE #24301: Crossgen removes "Win32Manifest" native resource from System.Windows.Forms.dll
Running crossgen on System.Windows.Forms seems to remove the Win32Manifest, causing errors at runtime that look like this: https://github.com/dotnet/winforms/issues/116.

For 3.0 Preview 5, I merged a workaround that disables crossgen on `System.Windows.Forms.dll`: https://github.com/dotnet/core-setup/pull/6128. Benefits of crossgen are noticeable in the WindowsDesktop shared framework so disabling it is not ideal. I haven't ported the fix to `master` hoping for a fix. (If it doesn't seem like one will land for Preview 6, I'll port the workaround to keep it intact.)

DLL before and after crossgen that exhibits the error: [System.Windows.Forms-compare.zip](https://github.com/dotnet/coreclr/files/3128344/System.Windows.Forms-compare.zip)

I have a 80 MB zip "test rig" that has all the dependencies required to crossgen this assembly--let me know offline if you want this and I can send a link.

@ericstj have you looked into the DLLs? I tried an "ordinary" ildasm and compare, but not sure where this shows up and I didn't see anything.

/cc @brianrob @dreddy-work @fadimounir @sergiy-k @davidwrighton

### PR DESCRIPTION
**Pull request by davidwrighton**
Fix #24301, by implementing general neutral resource copying

### CODE REVIEW

File: src/utilcode/pedecoder.cpp [hunk 1]
```diff
@@ -1790,26 +1790,69 @@ void PEDecoder::LayoutILOnly(void *base, BOOL allowFullPE) const
 
 #endif // #ifndef DACCESS_COMPILE
 
-DWORD PEDecoder::ReadResourceDictionary(DWORD rvaOfResourceSection, DWORD rva, LPCWSTR name, BOOL *pIsDictionary) const
+bool ReadResourceDictionaryHeader(const PEDecoder *pDecoder, DWORD rvaOfResourceSection, DWORD rva, IMAGE_RESOURCE_DIRECTORY_ENTRY** ppDirectoryEntries, IMAGE_RESOURCE_DIRECTORY **ppResourceDirectory)
```
Comment (MichalStrehovsky) [inline src/utilcode/pedecoder.cpp]: I had this comment in the previous pull request too - file format refers to this as "directory", not "dictionary". "Dictionary" makes this more confusing than it needs to be.

File: src/zap/zapheaders.cpp [hunk 2]
```diff
@@ -190,54 +193,245 @@ void ZapImage::SaveCodeManagerEntry()
...
+        ZapWin32ResourceDirectory* m_pRootDirectory;
+        ZapWin32ResourceDirectory* m_pCurrentTypesDirectory;
+        ZapWin32ResourceDirectory* m_pCurrentNamesDirectory;
+
+        bool AddResource(LPCWSTR lpszResourceType, LPCWSTR lpszResourceName)
+        {
+            COUNT_T cbResourceData;
+            PVOID pResourceData = m_pModuleDecoder->GetWin32Resource(lpszResourceName, lpszResourceType, &cbResourceData);
+            if (!pResourceData || !cbResourceData)
+                return true; // There wasn't a neutral resource, skip to next.
```
Comment (MichalStrehovsky) [inline src/zap/zapheaders.cpp]: Are we okay with taking the size on disk hit from keeping IBC data?

Comment (briansull) [reply src/zap/zapheaders.cpp]: Better to keep it here, as there a simple ibcmerge command that can be used to remove it.

Comment (davidwrighton) [reply src/zap/zapheaders.cpp]: I think we need to have a discussion about acceptability of keeping IBC data. @sergiy-k @MichalStrehovsky Do you have an idea of how much space keeping IBC will cost? @briansull Removing IBC data from the resource file may not actually reduce the filesize. In fact, the resource algorithms that ibcmerge uses are not guaranteed to function correctly when removing resources, it just so happens that they work if the resource was added by a prior execution of ibcmerge.

Comment (davidwrighton) [reply src/zap/zapheaders.cpp]: I spoke to @MeiChin-Tsai about this and she asked me to keep the IBC data out of the crossgen'd binaries for now.

File: src/utilcode/pedecoder.cpp (hunk 1 above)
Comment (davidwrighton) [reply src/utilcode/pedecoder.cpp]: Ok, will do.

File: src/zap/zapheaders.cpp (hunk 2 above)
Comment (MeiChin-Tsai) [reply src/zap/zapheaders.cpp]: Yes. I suggest so. Because we can give people choice in the future to keep IBC data in R2R images in the future. Keeping IBC or not should be a choice. Not to having it is the default.

File: tests/src/readytorun/tests/fileversionpreservation/fileversionpreservation.csproj [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+    <Compile Include="fileversionpreservation.cs" />
+    <Compile Include="Properties\AssemblyInfo.cs" />
+  </ItemGroup>
+  <ItemGroup>
+    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
+  </ItemGroup>
+  <PropertyGroup>
+    <CLRTestBatchPreCommands><![CDATA[
+$(CLRTestBatchPreCommands)
+%Core_Root%\crossgen /readytorun /platform_assemblies_paths %Core_Root%%3B%25CD% /out fileversionpreservation.ni.exe fileversionpreservation.exe
```
[the remark this answers is not in the document]
Comment (davidwrighton) [reply tests/src/readytorun/tests/fileversionpreservation/fileversionpreservation.csproj]: This test is written similarly to other ready to run specific tests. As we adjust to testing CPAOT, we should adjust all of the tests at once.

File: src/zap/zapheaders.cpp (hunk 2 above)
Comment (davidwrighton) [reply src/zap/zapheaders.cpp]: Done

**Comment by fadimounir** [comment]
@davidwrighton I was just looking at it. LGTM. Just make sure crossgenning an assembly with no resources doesn't fail.

File: tests/src/readytorun/tests/fileversionpreservation/fileversionpreservation.csproj (hunk 3 above)
[the remark this answers is not in the document]
Comment (fadimounir) [reply tests/src/readytorun/tests/fileversionpreservation/fileversionpreservation.csproj]: Nit: when we change these tests, we can remove the /readytorun switch since it's the default behavior now

**Comment by MattGal** [comment]
@davidwrighton since the azp command I issued worked, I'd guess a momentary network problem from the web hook, but just a guess.  @chcosta might know how to check further.
