### PR TITLE
JIT: update lvaGrabTemp for new minopts/debug ref counting approach

### LINKED ISSUE #19346: Assertion failed 'varDsc->lvImplicitlyReferenced'
Looks like a regression due to https://github.com/dotnet/coreclr/pull/19325

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/10114/consoleText

3 failures, e.g.
```
      JIT_Directed._coverage_oldtests_switchdefaultonly1_il_d_switchdefaultonly1_il_d_._coverage_oldtests_switchdefaultonly1_il_d_switchdefaultonly1_il_d_cmd [FAIL]
        
        Assert failure(PID 13300 [0x000033f4], Thread: 14688 [0x3960]): Assertion failed 'varDsc->lvImplicitlyReferenced' in 'switchdefaultonly1:Main(ref):int' (IL size 31)
        
            File: d:\j\workspace\checked_windo---14fb495b\src\jit\lclvars.cpp Line: 4103
            Image: D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
        
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Reports\JIT.Directed\coverage\oldtests\switchdefaultonly1_il_d\switchdefaultonly1_il_d.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\checked_windo---14fb495b\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" switchdefaultonly1_il_d.exe 
        Expected: 100
        Actual: 123456789
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\JIT\Directed\coverage\oldtests\switchdefaultonly1_il_d\switchdefaultonly1_il_d.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\checked_windo---14fb495b\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.Directed\JIT.Directed.XUnitWrapper.cs(14669,0): at JIT_Directed._coverage_oldtests_switchdefaultonly1_il_d_switchdefaultonly1_il_d_._coverage_oldtests_switchdefaultonly1_il_d_switchdefaultonly1_il_d_cmd()
```

@AndyAyersMS 
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If the jit has started normal ref counting and is in minopts or debug,
set all new temps to be implicitly referenced by default.

Closes #19346.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall ptal
cc @dotnet/jit-contrib 

Will be further extended by #19345, but that is not quite ready for prime time.

@dotnet-bot test Windows_NT x64 Checked Build and Test

**Comment by AndyAyersMS** [comment]
Trying to trigger PRI1 again...

@dotnet-bot test Windows_NT x64 Build and Test

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest Ubuntu x64 Checked CoreFX Tests

File: src/jit/compiler.hpp [hunk 1]
```diff
@@ -1682,13 +1682,22 @@ inline unsigned Compiler::lvaGrabTemp(bool shortLifetime DEBUGARG(const char* re
...
     }
 
-    lvaTable[lvaCount].lvType    = TYP_UNDEF; // Initialize lvType, lvIsTemp and lvOnFrame
-    lvaTable[lvaCount].lvIsTemp  = shortLifetime;
-    lvaTable[lvaCount].lvOnFrame = true;
+    const unsigned tempNum = lvaCount;
+    lvaCount++;
 
-    unsigned tempNum = lvaCount;
+    lvaTable[tempNum].lvType    = TYP_UNDEF; // Initialize lvType, lvIsTemp and lvOnFrame
```
Comment (CarolEidt) [inline src/jit/compiler.hpp]: nit: I think a comment that applies to multiple lines should be above the first line (though I realize this was already here).

Comment (AndyAyersMS) [reply src/jit/compiler.hpp]: I'll fix this as part of #19345.

**Comment by AndyAyersMS** [comment]
@dotnet/dnceng CoreCLR ARM CI seems like it may be having troubles...?
cc @jashook

**Comment by BruceForstall** [comment]
> CoreCLR ARM CI seems like it may be having troubles...?

Our Windows arm64 machines all appear "offline" to Jenkins.

cc @RussKeldorph

**Comment by MattGal** [comment]
@BruceForstall I'm not sure which Windows ARM64 machines you're referencing, but we're definitely experiencing DNS issues in the on-premises OSX machines, which are co-located with the ARM64 machines and likely to experience the same problem.  I'll update if I get more info, @JpratherMS FYI.

**Comment by BruceForstall** [comment]
The ARM64-AMD-xxx machines are the ones. @jashook / @RussKeldorph and I manage those.

**Comment by MattGal** [comment]
I haven't actually used these machines before, but I checked out 011 and noticed that while DNS resolution did work the OS on it expired over a month ago.  This could be part of the problem, automatic login may be failing due to a blocking dialog about windows expiring?

**Comment by sdmaclea** [comment]
These were also failing w/o this patch in `jitMinOpts=1`
```
JIT/jit64/regress/vsw/575343/test2/test2.sh
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b44946/b44946/b44946.sh
JIT/Regression/CLR-x86-JIT/V2.0-RTM/b598031/test2/test2.sh
JIT/Regression/CLR-x86-JIT/v2.1/b569942/b569942/b569942.sh
JIT/Regression/CLR-x86-JIT/v2.1/b608198/b608198/b608198.sh
JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b333008/b333008/b333008.sh
```
They have been resolved also.
