### PR TITLE
Remove extraneous eightbytes check for native structures and add tests.

### LINKED ISSUE #21585: Incorrect marshalling for a struct with a nested struct larger than 8 bytes on SystemV AMD64 ABI
Given the structures and signature below:

```csharp
    public struct SeqStruct
    {
        public int a;
        public bool b;
        public string str;

        public SeqStruct(int _a, bool _b, string _str)
        {
            a = _a;
            b = _b;
            str = String.Concat(_str, "");
        }
    }

    public struct NestedStruct
    {
        public SeqStruct value;
    }

    [DllImport("LayoutClassNative")]
    private static extern bool SimpleNestedLayoutClassByValue(NestedStruct p);
```

And the native side:

```cpp
struct SeqClass
{
    int a; 
    bool b;
    char* str;
};
struct NestedLayoutClass
{
    SeqClass str;
};

extern "C" DLL_EXPORT BOOL STDMETHODCALLTYPE SimpleNestedLayoutClassByValue(NestedLayoutClass v);
```

The SystemV ABI expects the `v` parameter to be enregistered. However, the runtime passes the value of `v` on the stack instead of enregistering it. I've traced the problem to be
https://github.com/dotnet/coreclr/blob/12a8870119b3e8023d68868792b29c28991168b3/src/vm/methodtable.cpp#L2651-L2656

This check is too broad eagerly marks the `NestedStruct` type as not enregisterable.

This bug is blocking one of the tests in #20867.

cc: @janvorli @CarolEidt @RussKeldorph

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #21585.

### CODE REVIEW

File: tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs [hunk 1]
```diff
@@ -22,7 +22,11 @@ enum StructID
         S8Id,
         S9Id,
         IncludeOuterIntergerStructSequentialId,
-        S11Id
+        S11Id,
```
Comment (danmosemsft) [inline tests/src/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq.cs]: Typo interger

**Comment by jkoritzinsky** [comment]
@janvorli can you take another look at this? I had to make another change in the classification system. I think it's correct, but I'd like another pair of eyes to look at it if possible.

**Comment by jkoritzinsky** [comment]
@janvorli I think I've addressed all of the feedback. Let me know what you think of my changes.

File: src/vm/methodtable.cpp [hunk 2]
```diff
@@ -3092,8 +3103,14 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
                 currentEightByte++;
                 _ASSERTE(currentEightByte <= CLR_SYSTEMV_MAX_EIGHTBYTES_COUNT_TO_PASS_IN_REGISTERS);
 
-                currentEightByteOffset = offset + fieldSize;
-                accumulatedSizeForEightByte = 0;
+                currentEightByteOffset = offset + Min(fieldSize, (unsigned int)SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES);
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: I cannot get my head around this change - I think we need to make sure that the `currentEightByteOffset` is set to multiple of `SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES` here (since we support only two eightbytes, it should result in it being set to `SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES`). 
It seems it should be:
```c++
currentEightByteOffset += SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
```

File: src/vm/methodtable.cpp [hunk 3]
```diff
@@ -3092,8 +3103,14 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
...
+                accumulatedSizeForEightByte -= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
+
+                // If a field is large enough to span multiple eightbytes, then set the eightbyte classification to the field's classification.
+                if (accumulatedSizeForEightByte > 0)
+                {
+                    helperPtr->eightByteClassifications[currentEightByte] = fieldClassificationType;
+                }
             }
 
             _ASSERTE(accumulatedSizeForEightByte < SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES);
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: It seems this assert should use "<=" instead of "<".  It seems that if the structure filled the two eightbytes completely, the accumulatedSizeForEightByte would be SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES.

File: src/vm/methodtable.cpp [hunk 4]
```diff
@@ -3092,8 +3103,14 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
...
 
-                currentEightByteOffset = offset + fieldSize;
-                accumulatedSizeForEightByte = 0;
+                currentEightByteOffset = offset + Min(fieldSize, (unsigned int)SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES);
+                accumulatedSizeForEightByte -= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
+
+                // If a field is large enough to span multiple eightbytes, then set the eightbyte classification to the field's classification.
+                if (accumulatedSizeForEightByte > 0)
+                {
+                    helperPtr->eightByteClassifications[currentEightByte] = fieldClassificationType;
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: We should set the eightBytesOffsets here too. In case our data structure filled the two eight bytes completely, we would not enter the `if` at line 3120 below and thus the `helperPtr->eightByteOffsets[currentEightByte]` would remain unset.

File: src/vm/methodtable.cpp [hunk 5]
```diff
@@ -3092,8 +3103,25 @@ void  MethodTable::AssignClassifiedEightByteTypes(SystemVStructRegisterPassingHe
...
+                    helperPtr->eightByteSizes[currentEightByte] = accumulatedSizeForEightByte;
+                    helperPtr->eightByteOffsets[currentEightByte] = currentEightByteOffset;
+
+                    _ASSERTE(accumulatedSizeForEightByte <= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES); // This code path only supports fields up to 2 eightbytes (the max number as of writing)
+                    if(accumulatedSizeForEightByte == SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES)
```
Comment (janvorli) [inline src/vm/methodtable.cpp]: Hmm, it got pretty complex after all the updates. I was thinking that we would update the code at line 2127 and below to handle this case (that's why I was suggesting to change the `<` to `<=`). Basically, that code would handle the "overflow" from the main loop. That means three cases:
1. The struct is smaller than one eightbyte and so it ends in the middle of it
2. The struct is larger than one eightbyte but smaller than two eightbytes, so it ends in the middle of the second eightbyte
3. The struct size is exactly two eightbytes and its last field has crossed eightbyte boundary.

So the code would become something like:
```C++
    if (accumulatedSizeForEightByte >= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES)
    {
        // Save data for this eightbyte.
        helperPtr->eightByteSizes[currentEightByte] = SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
        helperPtr->eightByteOffsets[currentEightByte] = currentEightByteOffset;
    
        // Set up for next eightbyte.
        currentEightByte++;
        _ASSERTE(currentEightByte <= CLR_SYSTEMV_MAX_EIGHTBYTES_COUNT_TO_PASS_IN_REGISTERS);
    
        currentEightByteOffset += SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
        accumulatedSizeForEightByte -= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
    
        // If a field is large enough to span multiple eightbytes, then set the eightbyte classification to the field's classification.
        if (accumulatedSizeForEightByte > 0)
        {
            helperPtr->eightByteClassifications[currentEightByte] = fieldClassificationType;
        }
    }
}

_ASSERTE(accumulatedSizeForEightByte < SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES);
if (accumulatedSizeForEightByte > 0 && accumulatedSizeForEightByte <= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES)
{
    helperPtr->eightByteSizes[currentEightByte] = accumulatedSizeForEightByte;
    helperPtr->eightByteOffsets[currentEightByte] = currentEightByteOffset;
    currentEightByte++;
}
```

Alternatively, we can get back to your original solution with the while loop here, updated a bit:
```C++
    while (accumulatedSizeForEightByte >= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES)
    {
        // Save data for this eightbyte.
        helperPtr->eightByteSizes[currentEightByte] = SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
        helperPtr->eightByteOffsets[currentEightByte] = currentEightByteOffset;
        
        // Set up for next eightbyte.
        currentEightByte++;
        _ASSERTE(currentEightByte <= CLR_SYSTEMV_MAX_EIGHTBYTES_COUNT_TO_PASS_IN_REGISTERS);
        
        currentEightByteOffset += SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
        accumulatedSizeForEightByte -= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES;
        
        // If a field is large enough to span multiple eightbytes, then set the eightbyte classification to the field's classification.
        if (accumulatedSizeForEightByte > 0)
        {
            helperPtr->eightByteClassifications[currentEightByte] = fieldClassificationType;
        }
    }
}
```

Comment (jkoritzinsky) [reply src/vm/methodtable.cpp]: I think I'm going to go for the loop. I personally think it looks cleaner.

**Comment by jkoritzinsky** [comment]
@dotnet-bot Ubuntu arm Cross Checked Innerloop Build and Test
