### PR TITLE
Correctly type SIMD stack values

### LINKED ISSUE #22850: HW intrinsic: Assertion failed 'src->gtObj.gtClass == structHnd' on OSX
Test case:
```csharp
        static unsafe bool test128(byte v)
        {
            return Avx2.BroadcastScalarToVector128(&v).Equals(Vector128.Create(v));
        }
```
That triggers the assert
```
Assert failure(PID 36783 [0x00008faf], Thread: 1960296 [0x1de968]): Assertion failed 'src->gtObj.gtClass == structHnd' in 'System.Runtime.Intrinsics.Vector128`1[Byte][System.Byte]:Equals(struct):bool:this' (IL size 281)

    File: /Users/fiigii/workspace/coreclr/src/jit/importer.cpp Line: 1314
    Image: /usr/local/share/dotnet/dotnet
```

We saw this failure in https://github.com/dotnet/coreclr/pull/22705, maybe related to `AsXXX`.

cc @tannergooding @CarolEidt

### PR DESCRIPTION
**Pull request by CarolEidt**
When `impSIMDPopStack` pops a struct value, it needs to retype the `OBJ` if it exists and doesn't match.

Fix #22850

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

File: src/jit/simd.cpp [hunk 1]
```diff
@@ -1058,10 +1058,18 @@ GenTree* Compiler::impSIMDPopStack(var_types type, bool expectAddr, CORINFO_CLAS
     // If we have a ldobj of a SIMD local we need to transform it.
     if (tree->OperGet() == GT_OBJ)
     {
-        GenTree* addr = tree->gtOp.gtOp1;
-        if ((addr->OperGet() == GT_ADDR) && isSIMDTypeLocal(addr->gtOp.gtOp1))
+        if (tree->AsObj()->gtClass != structHandle)
```
Comment (mikedn) [inline src/jit/simd.cpp]: @CarolEidt  Shouldn't this check for `structHandle` being `NO_CLASS_HANDLE`? I think that's what's causing #23159

Comment (CarolEidt) [reply src/jit/simd.cpp]: I'll take a look at that (probably not until tomorrow), but I believe the issue would lie with the caller of `impSIMDPopStack` which should be supplying a valid class handle. If that's the case, I'll fix the caller and add an assert here. If there is indeed a case where the caller doesn't have a valid class handle then perhaps something else is needed.
