### PR TITLE
Fix perf regression in master.

### LINKED ISSUE #20678: Regressions in span indexer performance
We seem to have had a recent regression in the span indexer performance tests. 

Thanks to @jorive for bringing this to my attention.

Impacted tests are: Indexer2, Indexer4, Indexer5, Indexer6, ReadOnlyIndexer2,  SameIndex2, WriteViaIndexer1, and WriteViaIndexer2.

Likely suspect is #20113 (based on Benchview).

Diff of recent master for `TestIndexer2` vs 2.2 shows we're now failing to eliminate a bounds check:

```asm
;; 2.2
G_M37174_IG03:
       4D63C8               movsxd   r9, r8d
       460FB60C08           movzx    r9, byte  ptr [rax+r9]
       4433C9               xor      r9d, ecx
       410FB6C9             movzx    rcx, r9b
       41FFC0               inc      r8d
       443BC2               cmp      r8d, edx
       7CE9                 jl       SHORT G_M37174_IG03

;; master
G_M37174_IG03:
       413BD0               cmp      edx, r8d
       731B                 jae      SHORT G_M37174_IG05
       4C63CA               movsxd   r9, edx
       460FB60C09           movzx    r9, byte  ptr [rcx+r9]
       4433C8               xor      r9d, eax
       410FB6C1             movzx    rax, r9b
       FFC2                 inc      edx
       413BD0               cmp      edx, r8d
       7CE5                 jl       SHORT G_M37174_IG03
```

@sandreenko can you investigate?
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
The PR returns the behavior that we had before #20113:
increase the parent lclVar counter for the promoted vars, so if we have:
```
FIELD _length
\-- ADDR byref
     \-- LCL_VAR struct V01
          |-- byref  V01._pointer (offs=0x00) -> V10 tmp7
          \-- int    V01._length (offs=0x08) -> V11 tmp8
```
we transform it to `V11 tmp8` but need to update counter for the parent `V01`.

There are no diffs between this version after fix and the version before the regression.

Diffs between this version and master are as expected:
no diffs x86, no diffs x64 debug, 
overall improvement for windows x64 checked: 
  -1044 : System.Private.CoreLib.dasm (-0.03% of base),
      -91 : Span\Indexer\Indexer.dasm (-0.86% of base),
      -23 : Span\SpanBench\SpanBench.dasm (-0.15% of base)

Also during this analysis I have found several places where we can improve our promotion desisions and will publish this change later. 

Note 1: the regression  #20678 was caused by a range check that was not  eliminated, but in the future we should think about improving this elimination to support cases where LVL_VARS are not promoted but their values are known (increase analyzing depth in the hot loops when we get branch counters?).

Note 2: `fgMakeOutgoingStructArgCopy` checks counter for the tree that it sees to elide unnecessary copies, maybe it should check parents's counter instead, but the code there is tricky and I wouldn't change it here.

Fixes #20678.

### CODE REVIEW

**Comment by sandreenko** [comment]
@dotnet-bot test Ubuntu x64 Checked pmi_asm_diffs
@dotnet-bot test Ubuntu16.04 x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x64_arm64_altjit Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86 Checked pmi_asm_diffs
@dotnet-bot test Windows_NT x86_arm_altjit Checked pmi_asm_diffs

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -18416,6 +18417,29 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
...
+    //------------------------------------------------------------------------
+    // UpdateImplicitByRefCounter: updates the ref count for implicit byref params.
+    //
+    // Arguments:
+    //    lclNum - the local number to update the count for.
+    //
+    // Notes:
+    //    fgMakeOutgoingStructArgCopy checks the ref counts for implicit byref params when deciding
+    //    if it's legal to elide certain copies of them;
+    //    fgRetypeImplicitByRefArgs checks the ref counts when decides to undo promotions.
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: when "it" decides?

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -18416,6 +18417,29 @@ class LocalAddressVisitor final : public GenTreeVisitor<LocalAddressVisitor>
         m_compiler->fgMorphLocalField(node, user);
         INDEBUG(m_stmtModified |= node->OperIs(GT_LCL_VAR);)
     }
+
+    //------------------------------------------------------------------------
+    // UpdateImplicitByRefCounter: updates the ref count for implicit byref params.
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Maybe spell this out a bit more? `UpdateEarlyRefCountForImplicitByRef` ?

File: src/jit/morph.cpp (hunk 1 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: It happens here https://github.com/dotnet/coreclr/blob/4410262505b5ebe308476116e9e833b210394638/src/jit/morph.cpp#L5018:
```
        if (lvaIsImplicitByRefLocal(varNum))
        {
            LclVarDsc* varDsc = &lvaTable[varNum];
            // JIT_TailCall helper has an implicit assumption that all tail call arguments live
            // on the caller's frame. If an argument lives on the caller caller's frame, it may get
            // overwritten if that frame is reused for the tail call. Therefore, we should always copy
            // struct parameters if they are passed as arguments to a tail call.
            if (!call->IsTailCallViaHelper() && (varDsc->lvRefCnt(RCS_EARLY) == 1) && !fgMightHaveLoop())
            {
                varDsc->setLvRefCnt(0, RCS_EARLY);
                args->gtOp.gtOp1 = lcl;
                argEntry->node   = lcl;

                JITDUMP("did not have to make outgoing copy for V%2d", varNum);
                return;
            }
        }
```
(suddenly GitHub sttoped to show code from permalinks).

it happens during `fgMorphArgs` under such condition:
```
        if (copyBlkClass != NO_CLASS_HANDLE)
        {
            fgMakeOutgoingStructArgCopy(call, args, argIndex, copyBlkClass);
        }
```

File: src/jit/morph.cpp (hunk 2 above)
Comment (sandreenko) [reply src/jit/morph.cpp]: Thanks, fixed.

File: src/jit/morph.cpp (hunk 1 above)
Comment (AndyAyersMS) [reply src/jit/morph.cpp]: Sorry for not being clearer.

I was only suggesting you add the word "it" to the comment ... "when decides" lacks a subject, "when it decides" reads better.
