### PR TITLE
Fix issue with out-of-scope GCFrame in Frame list

### LINKED ISSUE #25481: Update CI and official build to VS2019
More aggressive C/C++ optimizations done by VS2019 are breaking fragile assumptions of the CoreCLR “manually managed code”. This will need to be fixed before we can update.

The problem was found by the test job https://github.com/dotnet/coreclr/pull/25466 . 

 Unwinding of `Frame` chains accesses stack local variables after the stack frame has been unwound, but it depends on their content to be left intact. The new compiler is breaking this assumption by stack-packing a different variable over it.

The problematic pattern is:

```
HELPER_METHOD_FRAME
{
     ...
     GC_PROTECT
     ...
           throw exception
     ...
     GC_PROTECT_END
     ...
}
HELPER_METHOD_FRAME_END // The GC protect frame that is out of scope is accessed by the  unwinder here.
```

### PR DESCRIPTION
**Pull request by janvorli**
More aggressive C/C++ optimizations done by VS2019 are breaking fragile
assumptions of the CoreCLR "manually managed code".

Unwinding of Frame chains accesses stack local variables after the stack
frame has been unwound, but it depends on their content to be left
intact. The new compiler is breaking this assumption by stack-packing a
different variable over it.

This change fixes the problem by adding a destructor to GCFrame that
pops the frame from the per-thread Frame list.

I also had to refactor two functions where the compiler was complaining about 
mixing SEH and C++ EH in single function.

Close #25481

### CODE REVIEW

File: src/vm/assembly.cpp [hunk 1]
```diff
@@ -1462,6 +1462,62 @@ void ValidateMainMethod(MethodDesc * pFD, CorEntryPointType *pType)
     }
 }
 
+struct Param
```
Comment (janvorli) [inline src/vm/assembly.cpp]: This is just extraction of part of the RunMain into a separate function to prevent mixing SEH and C++ EH in the same function.

File: src/vm/syncblk.cpp [hunk 2]
```diff
@@ -2564,6 +2564,42 @@ double ComputeElapsedTimeInNanosecond(LARGE_INTEGER startTicks, LARGE_INTEGER en
     return (elapsedTicks * NsPerSecond) / freq.QuadPart;
 }
 
+DWORD AwareLock::WaitForSemEvent(INT32 timeOut)
```
Comment (janvorli) [inline src/vm/syncblk.cpp]: This is just extraction of part of the AwareLock::EnterEpilogHelper into a separate function to prevent mixing SEH and C++ EH in the same function.

File: src/vm/syncblk.cpp [hunk 3]
```diff
@@ -2564,6 +2564,42 @@ double ComputeElapsedTimeInNanosecond(LARGE_INTEGER startTicks, LARGE_INTEGER en
...
+    struct Param
+    {
+        AwareLock *pThis;
+        INT32 timeOut;
+        DWORD ret;
+    } param;
+    param.pThis = this;
+    param.timeOut = timeOut;
+
+    EE_TRY_FOR_FINALLY(Param *, pParam, &param)
```
Comment (jkotas) [inline src/vm/syncblk.cpp]: It would be better to rewrite it using object with a destructor that does `m_lockState.InterlockedUnregisterWaiter();`

File: src/vm/frames.h [hunk 4]
```diff
@@ -2535,6 +2535,10 @@ class GCFrame : public Frame
 
     // Keep as last entry in class
     DEFINE_VTABLE_GETTER_AND_DTOR(GCFrame)
+
+#ifndef FEATURE_PAL
```
Comment (jkotas) [inline src/vm/frames.h]: Why not use it everywhere?

Comment (janvorli) [reply src/vm/frames.h]: PAL already has a destructor that does the same thing - all frames in PAL do.

Comment (janvorli) [reply src/vm/frames.h]: I meant - with FEATURE_PAL.

File: src/vm/frames.cpp [hunk 5]
```diff
@@ -1001,6 +1001,31 @@ VOID GCFrame::Pop()
...
+{
+    CONTRACTL
+    {
+        NOTHROW;
+        GC_NOTRIGGER;
+        MODE_ANY;
+    }
+    CONTRACTL_END;
+
+    if (m_Next != NULL)
```
Comment (jkotas) [inline src/vm/frames.cpp]: Would it make sense to get rid of the Pops in the GC_PROTECT macro and just depend on doing the Pop here?

**Comment by jkotas** [comment]
Build breaks:
```
cee_crossgen.lib(clsload.obj) : error LNK2019: unresolved external symbol "public: __cdecl GCFrame::~GCFrame(void)" (??1GCFrame@@QEAA@XZ) referenced in function "int `public: __cdecl FrameWithCookie<class GCFrame>::FrameWithCookie<class GCFrame>(class Object * *,unsigned int,int)'::`1'::dtor$0" (?dtor$0@?0???0?$FrameWithCookie@VGCFrame@@@@QEAA@PEAPEAVObject@@IH@Z@4HA) [F:\workspace\_work\1\s\bin\obj\Windows_NT.x64.Debug\src\tools\crossgen\crossgen.vcxproj]
cee_crossgen.lib(typeparse.obj) : error LNK2001: unresolved external symbol "public: __cdecl GCFrame::~GCFrame(void)" (??1GCFrame@@QEAA@XZ) [F:\workspace\_work\1\s\bin\obj\Windows_NT.x64.Debug\src\tools\crossgen\crossgen.vcxproj]
```

File: src/vm/frames.cpp (hunk 5 above)
Comment (janvorli) [reply src/vm/frames.cpp]: That makes sense

**Comment by janvorli** [comment]
@jkotas, I have updated the syncblk.cpp change based on your feedback. Can you take another look please?

File: src/vm/frames.cpp [hunk 6]
```diff
@@ -1001,6 +1001,31 @@ VOID GCFrame::Pop()
...
```
Comment (jkotas) [inline src/vm/frames.cpp]: Is this check for null needed? GCFrame is always pushed in constructor, so we should never come here with m_Next == NULL

File: src/vm/frames.h [hunk 7]
```diff
@@ -2535,6 +2535,10 @@ class GCFrame : public Frame
 
     // Keep as last entry in class
     DEFINE_VTABLE_GETTER_AND_DTOR(GCFrame)
+
+#if !defined(FEATURE_PAL) && !defined(DACCESS_COMPILE) && !defined(CROSSGEN_COMPILE)
```
Comment (jkotas) [inline src/vm/frames.h]: Nit: `FEATURE_PAL` can be removed from this ifdef if the macro above is changed to just `DEFINE_VTABLE_GETTER`.

File: src/vm/frames.cpp (hunk 6 above)
Comment (janvorli) [reply src/vm/frames.cpp]: Yes, it is. When runtime calls WhateverFrame::GetMethodFrameVPtr, it creates a dummy instance of the frame, then gets the vtable and then destroys it. This check ensures that we don't try to pop such frames.

Comment (jkotas) [reply src/vm/frames.cpp]: ok

File: src/vm/frames.h (hunk 7 above)
Comment (janvorli) [reply src/vm/frames.h]: I didn't want to do that, I wanted all frame kinds on Unix to have destructor defined in an uniform manner at the same place and be explicit for the Windows GCFrame.

File: src/vm/frames.cpp [hunk 8]
```diff
@@ -1001,6 +1001,31 @@ VOID GCFrame::Pop()
...
+    {
+        GCX_COOP();
```
Comment (jkotas) [inline src/vm/frames.cpp]: This can be `GCX_COOP_THREAD_EXISTS(m_pThread)` to save thread-local fetch

File: src/vm/frames.h (hunk 7 above)
Comment (jkotas) [reply src/vm/frames.h]: ok

Comment (jkotas) [reply src/vm/frames.h]: Note that `GCFrame::Pop` does more stuff than `Frame::Pop`. May want to keep calling `GCFrame::Pop` from the `GC_PROTECT` macro on Unix so that keep doing that extra stuff on Unix.

Comment (janvorli) [reply src/vm/frames.h]: Hmm, then I guess that I'll actually follow your original advice and rather make the GCFrame destructor be the same for Windows and Linux instead of making the GCPROTECT_END different for Windows and Linux.

**Comment by janvorli** [comment]
Some x86 tests are failing due to the fact that the GCFrame is not at the top of the explicit frame stack when its destructor is called. I'll investigate it after my vacation.
