### PR TITLE
Fix for SIMD Initialize intrinsic expansion.

### LINKED ISSUE #3208: [JitStress2+JitStressRegs4] SIMD_VectorDot_ro failure
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2_jitstressregs4/1/testReport/JIT/_SIMD_VectorDot_ro_VectorDot_ro_/_SIMD_VectorDot_ro_VectorDot_ro_cmd/

### PR DESCRIPTION
**Pull request by erozenfeld**
Initialize expansion was missing register zero initialization
in some cases. This caused silent bad codegen in #3208.

Closes #3208.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@CarolEidt PTAL

**Comment by CarolEidt** [comment]
LGTM

**Comment by sivarv** [comment]
Looks good.

**Comment by sivarv** [comment]
Apologies, by mistake clicked on 'close and comment'

File: src/jit/simdcodegenxarch.cpp [hunk 1]
```diff
@@ -619,8 +619,8 @@ CodeGen::genSIMDIntrinsicInit(GenTreeSIMD* simdNode)
             // data section using movss/sd.  Similarly if op1 is a memory op we
             // would have loaded it using movss/sd.  Movss/sd when loading a xmm reg
             // from memory would zero-out upper bits. In these cases we can
-            // avoid explicitly zero'ing out targetReg.
-            bool zeroInitRequired = !(op1->IsCnsFltOrDbl() || op1->isMemoryOp());
+            // avoid explicitly zero'ing out targetReg if targetReg and op1Reg are the same.
+            bool zeroInitRequired = (targetReg != op1Reg) || !(op1->IsCnsFltOrDbl() || op1->isMemoryOp());
```
Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: On further thinking...

I am not sure that i understand why zero init is required if targetReg != op1Reg?

As per my understanding if op1 is a float constant or a memory-op, we would have loaded using movss/movsd, in which case upper bits of op1Reg would be zero.  Then genSIMDScalarMove() would have moved entire 128/256-bits of op1reg to targetReg using movaps instruction, which would mean even upper bits of targetReg would be zero initialized.

What am i missing?

Comment (kyulee1) [inline src/jit/simdcodegenxarch.cpp]: It appears to use a scalar move (movss) down the road in genSIMDScalarMove. For the reg to reg, it means merging not zeroing out the upper bits. Ideally we might want to use movups even for scalar move as you said. For the double (8 byte), we could optimize using movq instead of movsd to zero-out the upper bit even in between registers.

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: Yes, movss is generated in genSIMDScalarMove. The other caller of genSIMDScalarMove (genSIMDIntrinsicInitN) relies on genSIMDScalarMove to not modify the upper bits. The comment there:

        // We will now construct the vector from the list items in reverse order.
        // This allows us to efficiently stitch together a vector as follows:
        // vectorReg = (vectorReg << offset)
        // VectorReg[0] = listItemReg
        // Use genSIMDScalarMove with zeroInit of false in order to ensure that the upper
        // bits of vectorReg are not modified.

        regNumber operandReg = operandRegs[initCount - i - 1];
        if (offset != 0)
        {                         
            getEmitter()->emitIns_R_I(insLeftShift, EA_16BYTE, vectorReg, baseTypeSize);
        }
        genSIMDScalarMove(baseType, vectorReg, operandReg, false /* do not zeroInit */);

Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: I see one issue in genSIMDScalarMove() that is using ins_Store(type) instead of using ins_Copy(type) for reg-to-reg move when zeroInit is false.  But not sure whether that will explain this bug.  Using ins_Copy(type) will result in using movaps for reg-to-reg moves.

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: I think that's intentional. When zeroInit is false, the caller expects that the upper bits of targetReg won't be modified.

Comment (CarolEidt) [inline src/jit/simdcodegenxarch.cpp]: I believe that Eugene is correct. It may be that this method could be enhanced to account for additional cases (or additional method(s) could be added). But the existing method expects that either 1) the targetReg will be unmodified except for the scalar (low) bits in the non-zero-init case, or 2) the targetReg will be cleared other than the scalar (low) bits in the zero-init case. It may also be the case that better naming and/or commenting is in order here (mea culpa).

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: We can change the signature of genSIMDScalarMove to take another bool srcUpperBitsAreZero. Then if both zeroInit and srcUpperBitsAreZero are true we can use ins_Copy(type) instead of ins_Store(type).

genSIMDIntrinsicInit will pass 
true for zeroInit 
and 
!(op1->IsCnsFltOrDbl() || op1->isMemoryOp()) for srcUpperBitsAreZero

genSIMDIntrinsicInitN will pass false for both.

How does that sound?

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: Of course the logic will be modified to not do zero initialization if zeroInit is true, srcUpperBitsAreZero is true and the registers are the same.

Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: Note that by necessiating zeroInit when targetReg != op1Reg we are unnecessarily pessimizing code.

In this case there is no need to use genSIMDScalarMove() because we know the type of value we are moving from op1reg to targetReg is TYP_FLOAT.  The right fix here is

if (!zeroInitRequired)
   ins = ins_Copy(TYP_FLOAT)
else
   ins = ins_Store(TYP_FLOAT)

inst_RV_RV(ins, targetReg, op1Reg, emitTypeSize(baseType));

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: That will miss the
if (compiler->getSIMDInstructionSet() == InstructionSet_AVX)
logic from genSIMDScalarMove.

Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: I see your point.

I think the last parameter to genSIMDScalarMove() really has to be an enum

enum SIMDScalarMoveType { 
SMT_ZeroInitUpper,   // Zero initialize unused upper bytes of vector
SMT_PreserveUpper,             // Preserve upper bytes of vector while copying new value
SMT_VerbatimCopy               // Verbatim copy all bytes        
} 

genSIMDIntrinsicInit() will pass either SMT_ZeroInitUpper or SMT_VerbatimCopy depending on whether op1 is known to be zero-inited.

genSIMDIntrinsicInitN() will pass SMT_PreserveUpper

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: Yes, I like that better than my two bools suggestion. @CarolEidt if you also like this I'll make that change tomorrow.

Comment (CarolEidt) [inline src/jit/simdcodegenxarch.cpp]: I think the tri-state enum is a good idea. However, to me "VerbatimCopy" implies more than that the source is known to have upper zero bytes. Let's imagine that a new instruction is added that behaves like the memory move (i.e. zeros the upper bytes) - then perhaps we'd want that. Maybe SMT_CopyKnownUpperZeros? Or just SMT_SrcHasUpperZeros?

Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: Conceptually the way i look at it is that it is upto genSIMDScalarMove() to choose the right instruction when asked to zero initialize upper bytes of dst or preserve upper bytes of dst while copying or copy entire src to dst.

Even if we imagine there is a new instruction that zeros upper bytes, i would expect one of two things: caller of genSIMDScalarMove() will pass SMT_ZeroInitUpper if the src is not known to be initialized using such an instruction or will pass SMT_VerbatimCopy if caller can determine that src is initialized using such an instruction.

With SMT_CopyKnownUpperZeros/SMT_SrcHasUpperZeros we would need to pass two params to genSIMDScalarMove(): one to indicate whether to zero initialize or preserve upper bytes of dst and second whether src is known to have zeros in upper bytes already.  On the other hand if we still want a tri-state enum as single parameter, if I understood correctly, what you are suggesting as third enum is SMT_ZeroInitUpperWithSrcHasUpperZero and to me it is like combining two enums into one.

Comment (CarolEidt) [inline src/jit/simdcodegenxarch.cpp]: First, they are not really independent issues - it would not make sense to specify SrcHasUpperZeros if you want to preserve the upper bits of the target. Second, if the caller is explicitly requesting VerbatimCopy it would be more logical to use:
```
inst_RV_RV(ins_Copy(targetType), targetReg, op1Reg, targetType, emitActualTypeSize(targetType));
```
instead of calling genSIMDScalarMove(), since at that point it's not a scalar move. So my preference would be to either keep the signature as-is, and have callers use the explicit copy if they want to copy the whole register, OR to add the 3rd state to the enum.

Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: Ok. I am fine with a 3rd state enum to be SMT_ZeroInitUpper_SrcHasUpperZeros

enum SIMDScalarMoveType {
 SMT_ZeroInitUpper,
 SMT_ZeroInitUpper_SrcHasUpperZeros,
 SMT_PreserveUpper
}

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: @CarolEidt @sivarv I made a change to use a 3-state enum. PTAL.

File: src/jit/simdcodegenxarch.cpp [hunk 2]
```diff
@@ -461,43 +461,64 @@ CodeGen::getOpForSIMDIntrinsic(SIMDIntrinsicID intrinsicId,
...
+        case SMT_ZeroInitUpper_SrcHasUpperZeros:
+            if ((moveType == SMT_ZeroInitUpper) || (srcReg != targetReg))
             {
-                inst_RV_RV(ins, targetReg, srcReg, targetType, emitTypeSize(targetType));
+                // insertps is a 128-bit only instruction, and clears the upper 128 bits, which is what we want.
+                // The insertpsImm selects which fields are copied and zero'd of the lower 128 bits, so we choose
+                // to zero all but the lower bits.
+                unsigned int insertpsImm = (INSERTPS_TARGET_SELECT(0) | INSERTPS_ZERO(1) | INSERTPS_ZERO(2) | INSERTPS_ZERO(3));
+                inst_RV_RV_IV(INS_insertps, EA_16BYTE, targetReg, srcReg, insertpsImm);
+                break;
```
Comment (CarolEidt) [inline src/jit/simdcodegenxarch.cpp]: It may be worth considering whether a full-reg copy would be more efficient (one might think so, but AFAICT from the optimization manual, insertps is just as efficient as a simple copy.

**Comment by CarolEidt** [comment]
LGTM

File: src/jit/simdcodegenxarch.cpp (hunk 2 above)
Comment (sivarv) [inline src/jit/simdcodegenxarch.cpp]: movaps will be smaller instruction size compared to insertps as it doesn't have to encode an immediate operand?

Comment (CarolEidt) [inline src/jit/simdcodegenxarch.cpp]: Good point!

Comment (kyulee1) [inline src/jit/simdcodegenxarch.cpp]: reg-reg copy in the latest HW doesn't even go thru execution unit. It should be better than insertps in every aspect.

Comment (erozenfeld) [inline src/jit/simdcodegenxarch.cpp]: Updated to use reg-reg copy if possible in AVX case. @sivarv @CarolEidt @kyulee1 PTAL

**Comment by CarolEidt** [comment]
LGTM

File: src/jit/simdcodegenxarch.cpp [hunk 3]
```diff
@@ -461,43 +461,77 @@ CodeGen::getOpForSIMDIntrinsic(SIMDIntrinsicID intrinsicId,
...
+            }
+
+        case SMT_ZeroInitUpper_SrcHasUpperZeros:
+            if (srcReg != targetReg)
+            {
+                instruction ins = ins_Copy(type);
+                if (getEmitter()->IsThreeOperandMoveAVXInstruction(ins))
```
Comment (kyulee1) [inline src/jit/simdcodegenxarch.cpp]: I don't think we have 3 operands avx instructions for copy. You might just add an assert in this case.

**Comment by erozenfeld** [comment]
Ok, I removed the conditional and added an assert that the copy instruction is not 3-operands.

**Comment by kyulee1** [comment]
LGTM. Thanks.
