### PR TITLE
Fix resolveVirtualMethodHelper to check for explicit override cases

### LINKED ISSUE #19222: JIT: devirtualization can't rely on CORINFO_FLG_FINAL for methods
The presence of an explicit method override (see ECMA-355 II.10.3.2) allows a derived class to override an inherited final method. 

Consider the example below.

Currently the jit sees the declared type for local 0 in `main` is C, and the method in the A::f slot of C's method table is C::f and is marked final. So the jit devirtualizes the call, thinking that any derived class of C must likewise have C::f in that slot, as a final method can't be overridden by inheritance.

However D has installed D::f in the corresponding slot in its method table via an explicit override, and so the callvirt in main should target D::f, and the devirtualization is incorrect.

This means that `final` attributions on methods in some class's method table don't convey any guarantees as to the contents of derived class method tables. Instead the jit can only devirtualize here if it knows the exact type of the object.

This kind of override doesn't seem to be possible in C#, but can be described in IL (as below) or C++/CLI.

cc @dotnet/jit-contrib 
cc @adityamandaleeka who brought this example to my attention.

The fix for this is simple. Am currently starting to look at the impact on CQ.

```
.assembly extern mscorlib { }

.assembly X { }

.method assembly static int32 modopt([mscorlib]System.Runtime.CompilerServices.CallConvCdecl) 
        main() cil managed
{
  .entrypoint
  .vtentry 1 : 1
  // Code size       226 (0xe2)
  .maxstack  2
  .locals ([0] class C c,
           [1] uint8 V_1,
           [2] uint8 V_2,
           [3] uint8 V_3,
           [4] uint8 V_4,
           [5] uint8 V_5,
           [6] class B b,
           [7] uint8 V_7,
           [8] uint8 V_8,
           [9] uint8 V_9,
           [10] class C foo)
  IL_0000:  newobj     instance void C::.ctor()
  IL_0005:  stloc.0

  IL_0091:  newobj     instance void D::.ctor()
  IL_0096:  stloc.0
  IL_0097:  ldloc.0
  IL_0098:  callvirt   instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) A::f()
  ret
}

.class public auto ansi beforefieldinit A
       extends [mscorlib]System.Object
{
  .method public hidebysig newslot virtual 
          instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) 
          f() cil managed
  {
    // Code size       2 (0x2)
    .maxstack  1
    IL_0000:  ldc.i4.0
    IL_0001:  ret
  } // end of method A::f

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  1
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  ret
  } // end of method A::.ctor

} // end of class A

.class public auto ansi beforefieldinit B
       extends A
{
  .method public hidebysig virtual instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) 
          f() cil managed
  {
    // Code size       2 (0x2)
    .maxstack  1
    IL_0000:  ldc.i4.1
    IL_0001:  ret
  } // end of method B::f

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  1
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  ret
  } // end of method B::.ctor

} // end of class B

.class public auto ansi beforefieldinit C
       extends B
{
  .method public hidebysig newslot virtual final 
          instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) 
          f() cil managed
  {
    .override A::f
    // Code size       2 (0x2)
    .maxstack  1
    IL_0000:  ldc.i4.2
    IL_0001:  ret
  } // end of method C::f

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  1
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  ret
  } // end of method C::.ctor

} // end of class C

.class public auto ansi beforefieldinit D
       extends C
{
  .method public hidebysig newslot virtual final 
          instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) 
          f() cil managed
  {
    .override A::f
    // Code size       2 (0x2)
    .maxstack  1
    IL_0000:  ldc.i4.3
    IL_0001:  ret
  } // end of method D::f

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       7 (0x7)
    .maxstack  1
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  ret
  } // end of method D::.ctor

} // end of class D
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Explicit method overrides in a class can override a virtual final method
with different method. This is only possible if the different method
first is introduced in a new slot. So when devirtualizing, verify that the
slot of the derived method matches the slot of the base method.

If they don't match, just bail on devirtualizing.

Fixes #19222.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib 

Code size (per pmi). Changes are lost devirtualizations.
```
Total bytes of diff: 1462 (0.00% of base)
    diff is a regression.

Top file regressions by size (bytes):
        1158 : Microsoft.CodeAnalysis.CSharp.dasm (0.03% of base)
         280 : System.Private.CoreLib.dasm (0.01% of base)
         172 : System.Linq.Expressions.dasm (0.02% of base)
          70 : System.Security.Cryptography.X509Certificates.dasm (0.06% of base)
          39 : System.Private.DataContractSerialization.dasm (0.01% of base)

Top file improvements by size (bytes):
        -162 : System.IO.FileSystem.AccessControl.dasm (-1.01% of base)
        -148 : Microsoft.CodeAnalysis.dasm (-0.01% of base)
         -39 : System.Security.AccessControl.dasm (-0.05% of base)

13 total files with size differences (3 improved, 10 regressed), 116 unchanged.

Top method regressions by size (bytes):
         181 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceEventSymbol:CheckModifiersAndType(ref):this
         121 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.ParameterHelpers:ReportParameterErrors(ref,ref,ref,int,ref)
         101 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceUserDefinedOperatorSymbolBase:CheckUserDefinedConversionSignature(ref):this
          82 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbol:TypeChecks(ref,ref,ref,ref):this
          79 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbol:GetFieldType(ref):ref:this

Top method improvements by size (bytes):
        -162 : System.IO.FileSystem.AccessControl.dasm - System.Security.AccessControl.DirectoryObjectSecurity:GetRules(bool,bool,bool,ref):ref:this
        -101 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.LocalRewriter:MakeConversion(ref,ref,struct,ref,bool,bool,ref):ref:this
         -88 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Binder:GetNearestOtherSymbol(ref,ref):ref
         -80 : System.Security.AccessControl.dasm - System.Security.AccessControl.CommonObjectSecurity:GetRules(bool,bool,bool,ref):ref:this
         -78 : Microsoft.CodeAnalysis.CSharp.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeParameterMap:GetDebuggerDisplay():ref:this

675 total methods with size differences (251 improved, 424 regressed), 221011 unchanged.
```

Didn't see any diffs in the perf-sensitive parts of devirtualization I know about (eg equality comparer) and in many cases the missing devirts were just wrapping other calls. So hopefully no bad perf impact. But can't rule out that there could be some impact.

Probably behooves us to go look at better type tracking so we can reclaim some of these lost cases.

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -19601,14 +19593,7 @@ void Compiler::impDevirtualizeCall(GenTreeCall*            call,
         // the time of jitting, objClass has no subclasses that
         // override this method), then perhaps we'd be willing to
         // make a bet...?
-        JITDUMP("    Class not final or exact, method not final, no devirtualization\n");
-        return;
```
Comment (briansull) [inline src/jit/importer.cpp]: It might be worth adding a guard check and doing devirtualization for the methods that are marked as final.
For now you can update the comment.   Thought we can't "trust" final, it is in fact a pretty valuable hint.

**Comment by AndyAyersMS** [comment]
Probably will abandon this -- lots of discussion in over in #19222 about how best to handle this.

**Comment by AndyAyersMS** [comment]
Updated with a slot check in the jit interface method instead.... this is no diff on our current framework code.

@davidwrighton I think this is what you were asking for?

cc @dotnet/jit-contrib

File: tests/src/JIT/Regression/JitBlue/GitHub_19222/GitHub_19222.il [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+  .entrypoint
+  .maxstack  2
+  .locals ([0] class C c)
+  newobj     instance void C::.ctor()
+  stloc.0
+  newobj     instance void D::.ctor()
+  stloc.0
+  ldloc.0
+  // Must invoke D::f
+  callvirt   instance int32 modopt([mscorlib]System.Runtime.CompilerServices.IsLong) A::f()
```
Comment (davidwrighton) [inline tests/src/JIT/Regression/JitBlue/GitHub_19222/GitHub_19222.il]: Could you also add a call to C::F that would ensure that the call actually got to C::F and that C::F didn't get overridden to be D::F. This area of the type loader gets very little testing, and this is a decent spot to add one more test.
