### PR TITLE
Fix assertion regarding byteable reg when ngen'ing desktop mscorlib

### LINKED ISSUE #7483: RyuJIT x86: assertion regarding byteable xor reg, reg ngen'ing desktop mscorlib
When using RyuJIT x86 as the default x86 JIT on desktop and ngen'ing mscorlib, I see:
```
Assertion failed 'emitVerifyEncodable(ins, size, reg1, reg2)' in 'System.Security.Cryptography.Utils:FixupKeyParity(ref):ref' (IL size 84)
```
The code is trying generate a byte `xor ecx, esi`.

Stack:
```
clrjit!emitter::emitIns_R_R(instruction ins = INS_xor (0n15), emitAttr attr = EA_1BYTE (0n1), _regNumber_enum reg1 = REG_ECX (0n1), _regNumber_enum reg2 = REG_ESI (0n6))+0x79
clrjit!emitter::emitInsBinary(instruction ins = <Value unavailable error>, emitAttr attr = EA_1BYTE (0n1), struct GenTree * dst = 0x00b10c3c, struct GenTree * src = 0x00b10b28)+0x332
clrjit!CodeGen::genCodeForBinary(struct GenTree * treeNode = 0x00b10c98)+0x358
clrjit!CodeGen::genCodeForTreeNode(struct GenTree * treeNode = 0x00b10c98)+0x2ac
clrjit!CodeGen::genCodeForBBlist(void)+0x6c3
```

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #7483

The issue is that TreeNodeInfoInitCmp() will, under certain circumstances,
perform a tree transformation of a child node into a TYP_UBYTE type. Since
the TreeNodeInfo walk is bottom-up, its children have already been processed,
and they don't get the "byteable" register processing that is as the end of
TreeNodeInfoInit().

I extracted that processing into a TreeNodeInfoInitCheckByteable() function that
can be called after the TreeNodeInfoInitCmp() transformation.

A better solution might be to extract this, and other, tree transformations into
the prior "lowering" pass, such that TreeNodeInfoInit() and friends will only
do register requirement annotation. But that would be considerably more complicated,
so I opted not to do that for now.

I also fixed up a bunch of comments.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@adiaaida @sivarv PTAL
cc @dotnet/jit-contrib

File: src/jit/lowerxarch.cpp [hunk 1]
```diff
@@ -905,7 +905,28 @@ void Lowering::TreeNodeInfoInit(GenTree* tree)
...
 
+    TreeNodeInfoInitCheckByteable(tree);
+
+    // We need to be sure that we've set info->srcCount and info->dstCount appropriately
+    assert((info->dstCount < 2) || (tree->IsMultiRegCall() && info->dstCount == MAX_RET_REG_COUNT));
+}
+
+//------------------------------------------------------------------------
+// TreeNodeInfoInitCheckByteable: Check the tree to see if "byte-able" registers need to be
+// required, and set the tree node info accordingly.
```
Comment (sivarv) [inline src/jit/lowerxarch.cpp]: Minor: this comment could be simplified as follows:

'if "byte-able" registers are required,'

instead of 'need to be required'

**Comment by sivarv** [comment]
:shipit:

**Comment by adiaaida** [comment]
LGTM

File: src/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -3519,6 +3537,8 @@ void Lowering::TreeNodeInfoInitCmp(GenTreePtr tree)
                             castOp1->gtIntCon.gtIconVal = (UINT8)castOp1->gtIntCon.gtIconVal;
                         }
 
+                        // We're within "if (CheckImmedAndMakeContained(tree, op2))", so isn't the following condition
+                        // always true?
```
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: If you're not going to change this, you should at least make this a TODO-Cleanup

**Comment by CarolEidt** [comment]
:shipit:

**Comment by jkotas** [comment]
@dotnet-bot test this please
