### PR TITLE
Fix mismatched type IND(LCL_VAR_ADDR) folding in RewriteSIMDOperand

### LINKED ISSUE #27405: Converting a Vector4 to a Vector3 using `ref` asserts
The following code under x86 Release mode:
```csharp
static void Main(string[] args)
{
    Console.WriteLine($"Is64Bit: {Environment.Is64BitProcess}");
    var result = AsVector3(Vector4.One);
    Console.WriteLine(result);
}

[MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
public static Vector3 AsVector3(Vector4 value)
{
    return Unsafe.As<Vector4, Vector3>(ref value);
}
```

Fires the following assert:
```
Assert failure(PID 66636 [0x0001044c], Thread: 69336 [0x10ed8]): Assertion failed 'varDsc->lvType == TYP_SIMD12' in 'ConsoleApp10.Program:AsVector3(struct):struct' (IL size 13)

    File: C:\Users\tagoo\repos\coreclr_base\src\jit\compiler.h Line: 3385
    Image: C:\Users\tagoo\repos\coreclr_base\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe
```

### PR DESCRIPTION
**Pull request by mikedn**
If the indirection and the variable have different SIMD types then a LCL_FLD node of the appropiate type is needed instead of a LCL_VAR node.

Fixes #27405

### CODE REVIEW

File: src/jit/rationalize.cpp [hunk 1]
```diff
@@ -93,14 +93,33 @@ void Rationalizer::RewriteSIMDOperand(LIR::Use& use, bool keepBlk)
...
-    // and the var is a SIMD type, replace the expression by GT_LCL_VAR.
+    // If we have GT_IND(GT_LCL_VAR_ADDR) and the var is a SIMD type,
+    // replace the expression by GT_LCL_VAR or GT_LCL_FLD.
     GenTree* addr = tree->AsIndir()->Addr();
-    if (addr->OperIsLocalAddr() && comp->isAddrOfSIMDType(addr))
+    if (addr->OperIs(GT_LCL_VAR_ADDR) && comp->lvaGetDesc(addr->AsLclVar())->lvSIMDType)
     {
         BlockRange().Remove(tree);
 
-        addr->SetOper(loadForm(addr->OperGet()));
```
Comment (sandreenko) [inline src/jit/rationalize.cpp]: `genTreeOps loadForm(genTreeOps addrForm)` is unused after that change, could you please delete it?

File: src/jit/rationalize.cpp [hunk 2]
```diff
@@ -93,14 +93,33 @@ void Rationalizer::RewriteSIMDOperand(LIR::Use& use, bool keepBlk)
         return;
     }
 
-    // If we have GT_IND(GT_LCL_VAR_ADDR) and the GT_LCL_VAR_ADDR is TYP_BYREF/TYP_I_IMPL,
-    // and the var is a SIMD type, replace the expression by GT_LCL_VAR.
+    // If we have GT_IND(GT_LCL_VAR_ADDR) and the var is a SIMD type,
+    // replace the expression by GT_LCL_VAR or GT_LCL_FLD.
     GenTree* addr = tree->AsIndir()->Addr();
-    if (addr->OperIsLocalAddr() && comp->isAddrOfSIMDType(addr))
```
Comment (sandreenko) [inline src/jit/rationalize.cpp]: That looks like before it could process both `GT_IND(GT_LCL_FLD_ADDR(GT_LCL_FLD))`  and `GT_IND(GT_LCL_VAR_ADDR(LCL_VAR))`, but now it is limited to the second option.
Was it intentional? Does it produce diffs?

File: src/jit/rationalize.cpp (hunk 1 above)
Comment (mikedn) [reply src/jit/rationalize.cpp]: Cool, didn't notice it's no longer need. Thanks!

File: src/jit/rationalize.cpp (hunk 2 above)
Comment (mikedn) [reply src/jit/rationalize.cpp]: `GT_LCL_FLD_ADDR` was rejected by `isAddrOfSIMDType`. That's also the reason I got rid of the call to `isAddrOfSIMDType`.

File: src/jit/rationalize.cpp [hunk 3]
```diff
@@ -93,14 +93,33 @@ void Rationalizer::RewriteSIMDOperand(LIR::Use& use, bool keepBlk)
...
+        {
+            addr->SetOper(GT_LCL_VAR);
+        }
+        else
+        {
+            addr->SetOper(GT_LCL_FLD);
+            addr->AsLclFld()->gtLclOffs  = 0;
+            addr->AsLclFld()->gtFieldSeq = FieldSeqStore::NotAField();
+
+            if (((addr->gtFlags & GTF_VAR_DEF) != 0) && (genTypeSize(simdType) < genTypeSize(lclType)))
```
Comment (sandreenko) [inline src/jit/rationalize.cpp]: Could we see `genTypeSize(simdType) > genTypeSize(lclType)` here? Probably not because you can't do `Unsafe.As<Vector3, Vector4>(ref c);` , but if yes then you can use `bool GenTree::IsPartialLclFld(Compiler* comp)` here.

Comment (mikedn) [reply src/jit/rationalize.cpp]: I assume it's possible, but the result will be undefined. If it's a local variable you may end up overwriting another local variable but that's not something that liveness would ever care about.

The `USEASG` case is special - if this isn't set correctly, liveness will believe that the entire variable was written to and it will eliminate any previous stores as dead.

BTW, I'm not sure if this particular case is ever hit. It seems technically possible to hit a `VAR_DEF` but I haven't been able to construct a case showing this so I only added this code out of caution. I hope that eventually we will get rid of the entire function, all this logic should be either in morph or in lowering.
