### PR TITLE
Fix to get the correct value for Environment.TickCount in OSX

### LINKED ISSUE #2441: Tests fail with System.BadImageFormatException
The following tests fail with a mesage like this on a debug win64 test job:

```
Unhandled Exception: System.BadImageFormatException: 
Could not load file or assembly '<testname>.exe' or one of its dependencies.
An attempt was made to load a program with an incorrect format.
```

The failing tests are:

```
JIT\Directed\tls\mutualrecurthd-tls\mutualrecurthd-tls.cmd
JIT\Directed\tls\test-tls\test-tls.cmd
JIT\Regression\CLR-x86-EJIT\v1-m10\b07847\b07847\b07847.cmd
JIT\Regression\CLR-x86-JIT\V1.2-M01\b03689\b03689\b03689.cmd
```

### PR DESCRIPTION
**Pull request by Sridhar-MS**
On linux monotonic clock API clock_gettime is available. But on OSX the PAL implementation falls back to gettimeofday. This always retured the time elapsed since Unix Epoch (1970/01/01). I fixed it by using the mach API clock_get_time on OSX to get the time elapsed since system start.

Fixes #2441
https://github.com/dotnet/corefx/issues/2441

CC: @stephentoub

### CODE REVIEW

File: src/pal/src/misc/time.cpp [hunk 1]
```diff
@@ -270,6 +275,21 @@ GetTickCount64()
         }
         retval = (ts.tv_sec * tccSecondsToMillieSeconds)+(ts.tv_nsec / tccMillieSecondsToNanoSeconds);
     }
+#elif HAVE_MACH_CLOCK_MONOTONIC
+    {
+        kern_return_t machRet;
+        clock_serv_t clock;
+        mach_timespec_t mts;
+
+        host_get_clock_service(mach_host_self(), SYSTEM_CLOCK, &clock);
```
Comment (kangaroo) [inline src/pal/src/misc/time.cpp]: This leaks the host port, no?  Also, why are you not checking the return value here?

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: Yes. I missed checking the return value here. But I am deallocating the host port using 'mach_port_deallocate' a bunch of lines below. I need to make it better to deallocate the host port even in case of failing return values. I am working on the fix.

**Comment by Sridhar-MS** [comment]
I did some reference counting experiment on host ports. I discovered that there is one more place in the PAL layer (src/pal/src/misc/sysinfo.cpp) where the host port is leaking. I have fixed it too.

File: src/pal/src/misc/time.cpp [hunk 2]
```diff
@@ -270,6 +275,29 @@ GetTickCount64()
...
         retval = (ts.tv_sec * tccSecondsToMillieSeconds)+(ts.tv_nsec / tccMillieSecondsToNanoSeconds);
     }
+#elif HAVE_MACH_CLOCK_MONOTONIC
+    {
+        kern_return_t machRet;
+        clock_serv_t clock;
+        mach_timespec_t mts;
+        host_t host = mach_host_self();
+
+        if((machRet = host_get_clock_service(host, SYSTEM_CLOCK, &clock)) != KERN_SUCCESS)
```
Comment (jkotas) [inline src/pal/src/misc/time.cpp]: GetTickCount is expected to be very fast API. Acquiring/releasing the clock service for each call looks pretty expensive. Could you please do some quick performance measuments, and maybe consider caching the clock service?

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: @jkotas I did some crude performance measurements around Environment.TickCount.
With my changes (no caching) - Average time 3.0 microseconds
Without my changes (using gettimeofday) - Average time 0.13 microseconds.
I am not sure if perf cost is within acceptable level of tolerance. Meanwhile I am also trying to get perf measurements with caching the clock service.

It did my testing on release builds and got the average from 10 million iterations.
```c#
[Fact]
        public static void TickCountPerf()
        {            
            int iterations = 10000000;
            long totalTime = 0;
            for (int i = 0; i < iterations; i++)
            {
                long startTime = GetTimeofDay();
                int tick = Environment.TickCount;
                totalTime += GetTimeofDay() - startTime;
            }

            float average = (float)totalTime / iterations;
            Console.WriteLine("totalTime - {0} usecs", totalTime);
            Console.WriteLine("Average - {0} usecs", average);
        }

        public static long GetTimeofDay()
        {
            timeval tv = new timeval();           
            int result = gettimeofday(ref tv, IntPtr.Zero);            
            return (tv.tv_sec * tccSecondsToMicroSeconds) + tv.tv_usec;
        }

        [DllImport("libc")]
        // provides microsecond level resolution
        private static extern int gettimeofday(ref timeval tv, IntPtr tz);
```

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: @jkotas I also got the results with caching the clock service.
With my changes (no caching) - Average time 3.0 microseconds.
With my changes (with caching) - Average time 0.9 microseconds.
Without my changes (using gettimeofday) - Average time 0.13 microseconds.

There is still an increase in perf cost even with caching enabled.

Comment (jkotas) [inline src/pal/src/misc/time.cpp]: The microbenchmark is not right. GetTimeofDay() method should not be called for every iteration because of it is about as expensive as Environment.TickCount that you are trying to measure. It should be called only once before and after the loop:

```
        public static void TickCountPerf()
        {            
            int iterations = 10000000;
            long startTime = GetTimeofDay();
            for (int i = 0; i < iterations; i++)
            {
                int tick = Environment.TickCount;
            }
            long totalTime = GetTimeofDay() - startTime;
            ...
    }
```

Once you fix the microbenchmark, I expect that you will get numbers ~0.03 microseconds without your change, and ~3 microseconds with your change. Making Environment.TickCount 100x slower is certainly not within acceptable level of tolerance.

For reference, Environment.TickCount takes less than 0.01 microseconds on Windows.

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: Thanks for the feedback @jkotas! I updated the benchmark and got the results which are close to the numbers you predicted.

With my changes (no caching) - Average time 2.8 microseconds.
With my changes (with caching) - Average time 0.82 microseconds.
Without my changes (using gettimeofday) - Average time 0.05 microseconds.

So with caching enabled it is around it is around 16.4x slower.

Here is the updated microbench mark

```c#
        const long tccSecondsToMicroSeconds = 1000000;

        [Fact]
        public static void TickCountPerf()
        {            
            int iterations = 10000000;            
            long startTime = GetTimeofDay();

            for (int i = 0; i < iterations; i++)
            {               
                int tick = Environment.TickCount;
                
            }

            long totalTime = GetTimeofDay() - startTime;

            float average = (float)totalTime / iterations;
            Console.WriteLine("totalTime -- {0} usecs", totalTime);
            Console.WriteLine("Average -- {0} usecs", average);
        }

        public static long GetTimeofDay()
        {
            timeval tv = new timeval();           
            int result = gettimeofday(ref tv, IntPtr.Zero);            
            //Console.WriteLine("return value - " + (tv.tv_sec * tccSecondsToMicroSeconds) + tv.tv_usec);
            return (tv.tv_sec * tccSecondsToMicroSeconds) + tv.tv_usec;
        }

        [DllImport("libc")]
        //private static extern int gettimeofday(ref timeval tv, ref timezone tz);
        private static extern int gettimeofday(ref timeval tv, IntPtr tz);
    }

    struct timeval
    {
        public long tv_sec; /* seconds since Jan. 1, 1970 */
        public long tv_usec; /* and microseconds */
    }
```

Comment (jkotas) [inline src/pal/src/misc/time.cpp]: >>> caching enabled it is around it is around 16.4x slower
It is better than before, but still ~100x slower compared to Windows...

I have looked around for what is available ... have you considered using mach_absolute_time()? It seems to be the fastest way to get what you want.

Also, I am wondering whether we need to make similar change in other places like https://github.com/dotnet/coreclr/blob/master/src/pal/src/synchmgr/synchmanager.cpp#L4881 to be robust around clock time adjustment (e.g. day light switch). This can be tracked as separate issue.

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: I am also looking into mach_absolute_time(). I did some initial perf test and I got the time Average time down to 0.04 vs 0.05 without my changes. I will keep you updated on that.

**Comment by Sridhar-MS** [comment]
@jkotas Here are the final perf numbers
Using 'clock_get_time' (without caching host ports) - Average time 2.86 microseconds.
Using 'clock_get_time' (with caching host ports) - Average time 0.82 microseconds.
Using 'gettimeofday' (original implementation) - Average time 0.05 microseconds.
Using 'mach_absolute_time' - Average time 0.04 microseconds.

I was initially was not sure if 'mach_absolute_time' was monotonic, so I went ahead with 'clock_get_time'. Now I verified that both 'clock_get_time' and 'mach_absolute_time' return the exact same time elapsed. With that said I replaced the implementation with 'mach_absolute_time' because of the better performance numbers.

File: src/pal/src/misc/time.cpp [hunk 3]
```diff
@@ -298,4 +320,4 @@ GetTickCount64()
 #endif // HAVE_CLOCK_MONOTONIC 
 EXIT:    
     return retval;
-}
+}
```
Comment (jkotas) [inline src/pal/src/misc/time.cpp]: Could you please add new line at the end of the file?

File: src/pal/src/misc/time.cpp [hunk 4]
```diff
@@ -270,6 +278,20 @@ GetTickCount64()
         }
         retval = (ts.tv_sec * tccSecondsToMillieSeconds)+(ts.tv_nsec / tccMillieSecondsToNanoSeconds);
     }
+#elif HAVE_MACH_ABSOLUTE_TIME
+    {
+        // use denom == 0 to indicate that s_TimebaseInfo is uninitialised.
+        if (s_TimebaseInfo.denom == 0)
```
Comment (jkotas) [inline src/pal/src/misc/time.cpp]: I think there is a potential race if multiple threads are executing this code in parallel. One of the threads can return bogus result.

Comment (jkotas) [inline src/pal/src/misc/time.cpp]: It may be best to just initialize s_TimebaseInfo as part of the PAL initialization.

Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: I have moved the s_TimebaseInfo initializationto PAL initialization. Also fixed QueryPerformanceCounter to return nanosecond resolution in OSX. Now StopWatch class provides higher resolution on OSX.

File: src/pal/src/misc/time.cpp (hunk 2 above)
Comment (kangaroo) [inline src/pal/src/misc/time.cpp]: mach_absolute_time uses rdtsc

File: src/pal/src/misc/time.cpp [hunk 5]
```diff
@@ -28,8 +28,52 @@ Module Name:
...
 #include <string.h>
 
+#if HAVE_MACH_ABSOLUTE_TIME
+#include <mach/mach_time.h>
+static mach_timebase_info_data_t s_TimebaseInfo;
+#endif
+
 SET_DEFAULT_DEBUG_CHANNEL(MISC);
 
+static BOOL s_TimeInitialized = FALSE;
```
Comment (jkotas) [inline src/pal/src/misc/time.cpp]: This variable should not be needed.

File: src/pal/src/misc/time.cpp [hunk 6]
```diff
@@ -179,6 +223,17 @@ QueryPerformanceCounter(
...
+#elif HAVE_MACH_ABSOLUTE_TIME
+    {
+        // use denom == 0 to indicate that s_TimebaseInfo is uninitialised.
+        if (s_TimebaseInfo.denom == 0)
+        {
+            ASSERT("s_TimebaseInfo is uninitialized.\n");
+            goto EXIT;
+        }
+        lpPerformanceCount->QuadPart = 
+            (LONGLONG)mach_absolute_time() * (LONGLONG)s_TimebaseInfo.numer / (LONGLONG)s_TimebaseInfo.denom;
```
Comment (jkotas) [inline src/pal/src/misc/time.cpp]: You should return mach_absolute_time() directly here, and instead use s_TimebaseInfo to compute return value of QueryPerformanceFrequency.

**Comment by jkotas** [comment]
LGTM modulo comments

**Comment by kangaroo** [comment]
I mentioned this in a now outdated comment, but mach_absolute_time uses rdtsc.  My understanding is TickCount is supposed to be monotonic?

**Comment by Sridhar-MS** [comment]
@kangaroo I had the same concern initially. But in the code we are rounding off nanosecond measurement into milliseconds. This makes the TickCount value to be non-decreasing ie. any jump back and forth by mach_absolute_time is offset by this rounding off. 

As an experiment, I ran both mach_absolute_time and monotonic function clock_get_time in a loop for 10 million times and *rounding off both values to milliseconds*. The value returned by mach_absolute_time was always non-decreasing and same as the value returned by clock_get_time.

File: src/pal/src/misc/time.cpp (hunk 5 above)
Comment (Sridhar-MS) [inline src/pal/src/misc/time.cpp]: I am new to the PAL source code, so I was trying to follow existing conventions. Example - https://github.com/dotnet/coreclr/blob/master/src/pal/src/exception/machexception.cpp#L74.

So I believe that if you are not freeing any resources in cleanup you dont need an 'init' variable.

**Comment by kangaroo** [comment]
@Sridhar-MS Did you force core migrations, cpu frequency scaling, and S3 power switching?

**Comment by Sridhar-MS** [comment]
@jkotas Made fixes based on your feedback.
@kangaroo Thanks for the feedback. I have filed an issue #1300 to track it.
