### PR TITLE
Fix GetFunctionEnter3Info on linux

### LINKED ISSUE #19622: GetFunctionEnter3Info does not return correct argument address on Unix
This is an issue I found while investigating an issue reported in this thread: https://github.com/dotnet/coreclr/issues/18977

See also: https://github.com/dotnet/docs/issues/6728

On Linux, GetFunctionEnter3Info does not return the correct argument addresses (It returns correct numRanges and totalArgumentSize). I've successfully verified this issue on x64 (Ubuntu), but I have yet tried to repro this on other architectures (arm). 

The sample profilee is a very simple program with one function call. 
```
    class Program
    { 
        static int foo(int a, int b, int c, string d)
        {
            return a + b + c + d.Length;
        }

        static void Main(string[] args)
        {
            Console.Write("foo: {0:d}\n", foo(0xaa, 0xbb, 0xcc, "bar"));
        }
    }
}
```

I put a breakpoint on ProfilingGetFunctionEnter3Info in the runtime right before it returns. On Windows, WinDbg shows the following when I inspect the memory address pointed by ```pArgumentInfo->ranges[0].startAddress```:

```
00000055`585be2b0 aa 00 00 00 00 00 00 00 bb  .........
00000055`585be2b9 00 00 00 00 00 00 00 cc 00  .........
00000055`585be2c2 00 00 00 00 00 00 80 0e 13  .........
00000055`585be2cb a7 6d 01 00 00 00 00 00 00
```
As shown, the memory indeed contains the arguments that was passed to the function foo. 

In Linux, lldb shows me the following:
```
(lldb) frame variable
(FunctionID) functionId = 140735268410280
(COR_PRF_ELT_INFO) eltInfo = 140737488337952
(COR_PRF_FRAME_INFO *) pFrameInfo = 0x00007fffffffb8f0
(ULONG *) pcbArgumentInfo = 0x00007fffffffb8ec
(COR_PRF_FUNCTION_ARGUMENT_INFO *) pArgumentInfo = 0x00000000013a9120
(COR_PRF_ELT_INFO_INTERNAL *) pELTInfo = 0x00007fffffffbc20
(MethodDesc *) pMethodDesc = 0x00007fff7bae53a8

(lldb) x/20x 0x00000000013a9120
0x013a9120: 0x00000004 0x00000014 0xffffbf50 0x00007fff
0x013a9130: 0x00000004 0xcccccccc 0xffffbf58 0x00007fff
0x013a9140: 0x00000004 0xcccccccc 0xffffbf60 0x00007fff
0x013a9150: 0x00000004 0xcccccccc 0xffffbf68 0x00007fff
0x013a9160: 0x00000008 0xcccccccc 0xcccccccc 0xcccccccc

(lldb) x/20x 0x00007fffffffbf50
0x7fffffffbf50: 0x85af6e00 0xffc21e02 0x00000000 0x00000000
0x7fffffffbf60: 0xf58eedb3 0x00007fff 0x54021b68 0x00007fff
0x7fffffffbf70: 0xffffe480 0x00000001 0x54021b50 0x00007fff
0x7fffffffbf80: 0x85af6e00 0xffc21e02 0xffffe060 0x00007fff
0x7fffffffbf90: 0xffffbfb0 0x00007fff 0xf5bbfc83 0x00007fff
```

As shown above, the argument address (0x00007fffffffbf50) is does not contain the function arguments (0xaa, 0xbb, 0xcc, "bar")

### PR DESCRIPTION
**Pull request by davmason**
Fixes #19622

When slow path ELT is enabled on linux, this will allocate 128 bytes of stack buffer for each function that the profiler can use to copy any enregistered structs to. I chose 128 because that is the size of the available general purpose registers + the available floating point registers for argument passing (since we store the xmm values in the profiler code as 64 bit). Previously we were allocatng 216 bytes of stack space to store the registers, so while this grows the stack usage by ~50% I believe this is an acceptable tradeoff for slow path ELT.

`ProfileArgIterator::CopyStructFromRegisters` is `ArgLocDesc::CopyStructToRegisters` but modified to work with `PROFILE_PLATFORM_SPECIFIC_DATA` instead of `TransitionBlock`, and also to copy out of registers instead of in to registers. `PROFILE_PLATFORM_SPECIFIC_DATA` has a different layout, and uses `UINT64` for all float registers, including the 128 bit registers.

I tested with this program, everything in the foo* functions behaved as I expected. If there are cases I missed please let me know.

```
using System;

namespace linux_elt
{
    struct SampleStruct
    {
        public int a;
        public double b;
        public int c;
        public float d;
    }

    class Program
    { 
        static int foo(int a, int b, int c, string d)
        {
            return a + b + c + d.Length;
        }

        static void foo2(int a, int b, int c, int d, int e, int f, int g, int h,
                        int i, int j, int k, int l, int m, int n, int o, int p,
                        int q, int r, int s, int t, int u, int v, int w, int x,
                        int y, int z)
        {
            int sum = a + b + c + d + e + f + g + h + i + j + k + l + m + n;
            Console.WriteLine($"Sum={sum}");
        }

        static void foo3(SampleStruct ss, float f)
        {
            Console.WriteLine($"foo3={(int)(ss.a + ss.b + ss.c + ss.d + f)}");
        }

        static void foo4(int d, ref int a, out int b, int c)
        {
            b = 10;
            Console.WriteLine($"foo4={a + b + c + d}");
        }

        static void Main(string[] args)
        {
            Console.WriteLine("*****Calling foo!*****");
            Console.WriteLine("foo: {0:d}", foo(0xaa, 0xbb, 0xcc, "bar"));
            foo2(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                 19, 20, 21, 22, 23, 24, 25, 26);

            SampleStruct ss = new SampleStruct();
            ss.a = 1;
            ss.b = 2.0;
            ss.c = 3;
            ss.d = 4.0f;
            foo3(ss, 3.72f);

            int a = 5;
            int b;
            foo4(7, ref a, out b, 13);
        }
    }
}
```

### CODE REVIEW

File: src/vm/amd64/profiler.cpp [hunk 1]
```diff
@@ -204,6 +215,85 @@ ProfileArgIterator::~ProfileArgIterator()
...
+
+        dest = (BYTE*)dest + eightByteSize;
+        INDEBUG(remainingBytes -= eightByteSize;)
+    }
+
+    _ASSERTE(remainingBytes == 0);
+
+    LPVOID destOrig = (LPVOID)&pData->buffer[pData->bufferPos];
+    //Increase bufferPos by ceiling(fieldBytes/8)
+    pData->bufferPos += (fieldBytes + 7) / 8;
```
Comment (davmason) [inline src/vm/amd64/profiler.cpp]: I need to add an asset that checks that the buffer never overflows

File: src/vm/amd64/profiler.cpp [hunk 2]
```diff
@@ -204,6 +215,85 @@ ProfileArgIterator::~ProfileArgIterator()
...
+
+    TypeHandle th;
+    m_argIterator.GetArgType(&th);
+    int fieldBytes = th.AsMethodTable()->GetNumInstanceFieldBytes();
+    INDEBUG(int remainingBytes = fieldBytes;)
+
+    EEClass* eeClass = argLocDesc->m_eeClass;
+    _ASSERTE(eeClass != NULL);
+
+    // We start at the first eightByte that the destOffset didn't skip completely.
```
Comment (janvorli) [inline src/vm/amd64/profiler.cpp]: There is no destOffset in this copy of the code, please remove this comment.

File: src/vm/proftoeeinterfaceimpl.h [hunk 3]
```diff
@@ -71,6 +71,10 @@ class ProfileArgIterator
         LIMITED_METHOD_CONTRACT;
         return m_argIterator.NumFixedArgs();
     }
+    
+#ifdef UNIX_AMD64_ABI
+    LPVOID ProfileArgIterator::CopyStructFromRegisters();
```
Comment (janvorli) [inline src/vm/proftoeeinterfaceimpl.h]: Please remove the class name here.

**Comment by mjsabby** [comment]
@davmason there is a sample clr profiler that tried to do ELT and failed in the clr-samples repo if you'd like to validate that.

File: src/vm/amd64/asmhelpers.S [hunk 4]
```diff
@@ -39,8 +39,10 @@
 //
 .equ SIZEOF_PROFILE_PLATFORM_SPECIFIC_DATA, 0x8*22 + 0x8  // includes fudge to make FP_SPILL right
```
[the remark this answers is not in the document]
Comment (davmason) [reply src/vm/amd64/asmhelpers.S]: Yeah, that conceptually makes more sense

File: src/vm/amd64/asmhelpers.S [hunk 5]
```diff
@@ -39,8 +39,10 @@
...
 .equ SIZEOF_FP_ARG_SPILL, 0x10*2
+// Buffer to copy structs sequentially
+.equ SIZEOF_PROFILE_STRUCT_BUFFER, 0x8*16
 
-.equ SIZEOF_STACK_FRAME, SIZEOF_PROFILE_PLATFORM_SPECIFIC_DATA + SIZEOF_FP_ARG_SPILL
+.equ SIZEOF_STACK_FRAME, SIZEOF_PROFILE_PLATFORM_SPECIFIC_DATA + SIZEOF_FP_ARG_SPILL + SIZEOF_PROFILE_STRUCT_BUFFER
```
[the remark this answers is not in the document]
Comment (davmason) [reply src/vm/amd64/asmhelpers.S]: Doh! I was thinking about as if it were a member on ProfileArgIterator. I changed it to actually be a member, I think it fits better there since it is just an implementation detail on creating the PROFILE_PLATFORM_SPECIFIC_DATA

**Comment by davmason** [comment]
Thanks @noahfalk and @janvorli! I addressed your feedback, and am going to re-run the tests I have plus the profiler Mukul pointed out, then merge once everything is green.

**Comment by davmason** [comment]
@mjsabby what failures were you seeing in the sample profiler? Was it crashing or giving wrong output? I Just ran both from https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI and they both execute without crashing and seem to give coherent output.

**Comment by davmason** [comment]
> 
> 
> @mjsabby what failures were you seeing in the sample profiler? Was it crashing or giving wrong output? I Just ran both from https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI and they both execute without crashing and seem to give coherent output.

Nevermind, I see in https://github.com/microsoft/clr-samples/issues/12 that segfaults were the issue. I was seeing segfaults before my change that are solved now, so I believe this change fixes that issue

**Comment by mjsabby** [comment]
Thanks for confirming @davmason. Now that you have fixed this for Linux it's not as urgent (i.e. in 3.0 timeframe) for me to have an issue where I'd like to propose that we innovate in this area and provide argument and return value inspection for fast path ELT.
