### PR TITLE
Handle multireg copies correctly

### LINKED ISSUE #19029: JitStressRegs=0x8 regressions
The 512 tests started failing recently in JitStress=0x8 mode

Typical failure looks like
```
corerun DecimalMaxValue.exe
Beginning test case for Field:System.Decimal.MaxValue at 7/19/2018 1:46:59 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]

Assert failure(PID 17348 [0x000043c4], Thread: 17348 [0x43c4]): 
Assertion failed 'emitTypeActSz[TypeGet(type)] > 0' in 'DecimalMaxValue:PosTest1():bool:this' (IL size 153)

    File: src/jit/emit.h Line: 2231
```

List of fails follows

```
baseservices/exceptions/regressions/V1/SEH/VJ/NestedEx1/NestedEx1.sh
baseservices/exceptions/regressions/V1/SEH/VJ/NestedEx2/NestedEx2.sh
baseservices/threading/paramthreadstart/ThreadStartDecimal_1/ThreadStartDecimal_1.sh
baseservices/threading/paramthreadstart/ThreadStartDecimal_2/ThreadStartDecimal_2.sh
baseservices/threading/paramthreadstart/ThreadStartDecimal/ThreadStartDecimal.sh
CoreMangLib/cti/system/array/ArrayGetLength/ArrayGetLength.sh
CoreMangLib/cti/system/array/ArrayGetValue2/ArrayGetValue2.sh
CoreMangLib/cti/system/array/ArrayIndexOf1b/ArrayIndexOf1b.sh
CoreMangLib/cti/system/array/ArrayLastIndexOf1b/ArrayLastIndexOf1b.sh
CoreMangLib/cti/system/array/ArraySetValue2/ArraySetValue2.sh
CoreMangLib/cti/system/collections/generic/dictionaryenumerator/DictEnumIDictEnumget_Entry/DictEnumIDictEnumget_Entry.sh
CoreMangLib/cti/system/collections/generic/dictionaryenumerator/DictEnumIDictEnumget_Key/DictEnumIDictEnumget_Key.sh
CoreMangLib/cti/system/collections/generic/dictionaryenumerator/DictEnumIDictEnumget_Value/DictEnumIDictEnumget_Value.sh
CoreMangLib/cti/system/convert/ConvertFromBase64String/ConvertFromBase64String.sh
CoreMangLib/cti/system/convert/ConvertToByte4/ConvertToByte4.sh
CoreMangLib/cti/system/convert/ConvertToDecimal14/ConvertToDecimal14.sh
CoreMangLib/cti/system/convert/ConvertToDecimal15/ConvertToDecimal15.sh
CoreMangLib/cti/system/convert/ConvertToDecimal/ConvertToDecimal.sh
CoreMangLib/cti/system/convert/ConvertToInt16_4/ConvertToInt16_4.sh
CoreMangLib/cti/system/convert/ConvertToInt64_4/ConvertToInt64_4.sh
CoreMangLib/cti/system/convert/ConvertToSByte4/ConvertToSByte4.sh
CoreMangLib/cti/system/convert/ConvertToUInt164/ConvertToUInt164.sh
CoreMangLib/cti/system/convert/ConvertToUInt324/ConvertToUInt324.sh
CoreMangLib/cti/system/convert/ConvertToUInt647/ConvertToUInt647.sh
CoreMangLib/cti/system/decimal/DecimaFloor/DecimaFloor.sh
CoreMangLib/cti/system/decimal/DecimalMaxValue/DecimalMaxValue.sh
CoreMangLib/cti/system/decimal/DecimalMinValue/DecimalMinValue.sh
CoreMangLib/cti/system/decimal/DecimalToByte/DecimalToByte.sh
CoreMangLib/cti/system/decimal/DecimalToInt16/DecimalToInt16.sh
CoreMangLib/cti/system/decimal/DecimalToInt64/DecimalToInt64.sh
CoreMangLib/cti/system/decimal/DecimalToSByte/DecimalToSByte.sh
CoreMangLib/cti/system/decimal/DecimalToUInt16/DecimalToUInt16.sh
CoreMangLib/cti/system/decimal/DecimalToUInt32/DecimalToUInt32.sh
CoreMangLib/cti/system/decimal/DecimalToUInt64/DecimalToUInt64.sh
CoreMangLib/cti/system/double/DoubleIConvertibleToDecimal/DoubleIConvertibleToDecimal.sh
CoreMangLib/cti/system/gc/GCCollect/GCCollect.sh
CoreMangLib/cti/system/gc/GCGetTotalMemory/GCGetTotalMemory.sh
CoreMangLib/cti/system/gc/GCKeepAlive/GCKeepAlive.sh
CoreMangLib/cti/system/gc/GCReRegisterForFinalize/GCReRegisterForFinalize.sh
CoreMangLib/cti/system/gc/GCSuppressFinalize/GCSuppressFinalize.sh
CoreMangLib/cti/system/gc/GCWaitForPendingFinalizers/GCWaitForPendingFinalizers.sh
CoreMangLib/cti/system/guid/GuidNewGuid/GuidNewGuid.sh
CoreMangLib/cti/system/int16/Int16IConvertibleToDecimal/Int16IConvertibleToDecimal.sh
CoreMangLib/cti/system/int64/Int64IConvertibleToDecimal/Int64IConvertibleToDecimal.sh
CoreMangLib/cti/system/int/Int32IConvertibleToDecimal/Int32IConvertibleToDecimal.sh
CoreMangLib/cti/system/mathf/MathFAcos/MathFAcos.sh
CoreMangLib/cti/system/mathf/MathFAtan2/MathFAtan2.sh
CoreMangLib/cti/system/mathf/MathFAtan/MathFAtan.sh
CoreMangLib/cti/system/mathf/MathFCosh/MathFCosh.sh
CoreMangLib/cti/system/mathf/MathFLog/MathFLog.sh
CoreMangLib/cti/system/mathf/MathFSinh/MathFSinh.sh
CoreMangLib/cti/system/mathf/MathFTanh/MathFTanh.sh
CoreMangLib/cti/system/mathf/MathFTan/MathFTan.sh
CoreMangLib/cti/system/math/MathAcos/MathAcos.sh
CoreMangLib/cti/system/math/MathAtan2/MathAtan2.sh
CoreMangLib/cti/system/math/MathAtan/MathAtan.sh
CoreMangLib/cti/system/math/MathCosh/MathCosh.sh
CoreMangLib/cti/system/math/MathLog/MathLog.sh
CoreMangLib/cti/system/math/mathRound1/mathRound1.sh
CoreMangLib/cti/system/math/MathRound2/MathRound2.sh
CoreMangLib/cti/system/math/MathSinh/MathSinh.sh
CoreMangLib/cti/system/math/MathTanh/MathTanh.sh
CoreMangLib/cti/system/math/MathTan/MathTan.sh
CoreMangLib/cti/system/object/ObjectFinalize/ObjectFinalize.sh
CoreMangLib/cti/system/sbyte/SByteIConvertibleToDecimal/SByteIConvertibleToDecimal.sh
CoreMangLib/cti/system/string/StringEquals6/StringEquals6.sh
CoreMangLib/cti/system/uint16/UInt16IConvertibleToDecimal/UInt16IConvertibleToDecimal.sh
CoreMangLib/cti/system/uint32/UInt32IConvertibleToDecimal/UInt32IConvertibleToDecimal.sh
CoreMangLib/cti/system/uint64/UInt64IConvertibleToDecimal/UInt64IConvertibleToDecimal.sh
CoreMangLib/cti/system/weakreference/WeakReferenceCtor2_PSC/WeakReferenceCtor2_PSC.sh
CoreMangLib/cti/system/weakreference/WeakReferenceIsAliveb_PSC/WeakReferenceIsAliveb_PSC.sh
CoreMangLib/cti/system/weakreference/WeakReferenceIsAlive_PSC/WeakReferenceIsAlive_PSC.sh
CoreMangLib/cti/system/weakreference/WeakReferenceTargetb_PSC/WeakReferenceTargetb_PSC.sh
CoreMangLib/system/delegate/miscellaneous/ClosedStatic/ClosedStatic.sh
CoreMangLib/system/guid/Guid_Parsing/Guid_Parsing.sh
CoreMangLib/system/span/RefStructWithSpan/RefStructWithSpan.sh
GC/API/GC/Collect_Forced_1/Collect_Forced_1.sh
GC/API/GC/Collect_Forced_2/Collect_Forced_2.sh
GC/API/GC/Collect_Forced_3/Collect_Forced_3.sh
GC/Features/HeapExpansion/bestfit_1/bestfit_1.sh
GC/Features/HeapExpansion/bestfit/bestfit.sh
GC/Features/HeapExpansion/bestfit-threaded/bestfit-threaded.sh
GC/Features/Pinning/PinningOther/PinnedCollect/PinnedCollect.sh
GC/Regressions/v2.0-beta2/471729/471729/471729.sh
GC/Scenarios/FinalizeTimeout/FinalizeTimeout/FinalizeTimeout.sh
Interop/SimpleStruct/SimpleStruct/SimpleStruct.sh
JIT/CheckProjects/CheckProjects/CheckProjects.sh
JIT/CodeGenBringUpTests/StructReturn/StructReturn.sh
JIT/Directed/coverage/oldtests/lclfldadd_cs_d/lclfldadd_cs_d.sh
JIT/Directed/coverage/oldtests/lclfldadd_cs_do/lclfldadd_cs_do.sh
JIT/Directed/coverage/oldtests/lclfldadd_cs_r/lclfldadd_cs_r.sh
JIT/Directed/coverage/oldtests/lclfldadd_cs_ro/lclfldadd_cs_ro.sh
JIT/Directed/coverage/oldtests/lclflddiv_cs_d/lclflddiv_cs_d.sh
JIT/Directed/coverage/oldtests/lclflddiv_cs_do/lclflddiv_cs_do.sh
JIT/Directed/coverage/oldtests/lclflddiv_cs_r/lclflddiv_cs_r.sh
JIT/Directed/coverage/oldtests/lclflddiv_cs_ro/lclflddiv_cs_ro.sh
JIT/Directed/coverage/oldtests/lclfldmul_cs_d/lclfldmul_cs_d.sh
JIT/Directed/coverage/oldtests/lclfldmul_cs_do/lclfldmul_cs_do.sh
JIT/Directed/coverage/oldtests/lclfldmul_cs_r/lclfldmul_cs_r.sh
JIT/Directed/coverage/oldtests/lclfldmul_cs_ro/lclfldmul_cs_ro.sh
JIT/Directed/coverage/oldtests/lclfldrem_cs_d/lclfldrem_cs_d.sh
JIT/Directed/coverage/oldtests/lclfldrem_cs_do/lclfldrem_cs_do.sh
JIT/Directed/coverage/oldtests/lclfldrem_cs_r/lclfldrem_cs_r.sh
JIT/Directed/coverage/oldtests/lclfldrem_cs_ro/lclfldrem_cs_ro.sh
JIT/Directed/coverage/oldtests/lclfldsub_cs_d/lclfldsub_cs_d.sh
JIT/Directed/coverage/oldtests/lclfldsub_cs_do/lclfldsub_cs_do.sh
JIT/Directed/coverage/oldtests/lclfldsub_cs_r/lclfldsub_cs_r.sh
JIT/Directed/coverage/oldtests/lclfldsub_cs_ro/lclfldsub_cs_ro.sh
JIT/Directed/coverage/oldtests/stfldstatic1_il_d/stfldstatic1_il_d.sh
JIT/Directed/coverage/oldtests/stfldstatic2_il_d/stfldstatic2_il_d.sh
JIT/Directed/nullabletypes/boxunboxinterface_d/boxunboxinterface_d.sh
JIT/Directed/nullabletypes/boxunboxinterface_r/boxunboxinterface_r.sh
JIT/Directed/nullabletypes/castclassinterface_d/castclassinterface_d.sh
JIT/Directed/nullabletypes/castclassinterface_r/castclassinterface_r.sh
JIT/Directed/nullabletypes/castclassvaluetype_d/castclassvaluetype_d.sh
JIT/Directed/nullabletypes/castclassvaluetype_r/castclassvaluetype_r.sh
JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_r/boxunboxvaluetype_r.sh
JIT/Directed/perffix/primitivevt/mixed1_cs_d/mixed1_cs_d.sh
JIT/Directed/perffix/primitivevt/mixed1_cs_do/mixed1_cs_do.sh
JIT/Directed/perffix/primitivevt/mixed1_cs_r/mixed1_cs_r.sh
JIT/Directed/perffix/primitivevt/mixed1_cs_ro/mixed1_cs_ro.sh
JIT/Directed/perffix/primitivevt/mixed2_cs_d/mixed2_cs_d.sh
JIT/Directed/perffix/primitivevt/mixed2_cs_do/mixed2_cs_do.sh
JIT/Directed/perffix/primitivevt/mixed2_cs_r/mixed2_cs_r.sh
JIT/Directed/perffix/primitivevt/mixed2_cs_ro/mixed2_cs_ro.sh
JIT/Generics/Fields/static_assignment_class01/static_assignment_class01.sh
JIT/Generics/Fields/static_assignment_struct01/static_assignment_struct01.sh
JIT/Generics/Fields/static_passing_class01/static_passing_class01.sh
JIT/Generics/Fields/static_passing_struct01/static_passing_struct01.sh
JIT/HardwareIntrinsics/Arm64/Crypto/Crypto.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_r/Avx2_r.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_ro/Avx2_ro.sh
JIT/HardwareIntrinsics/X86/Avx2/ConvertToVector256_r/ConvertToVector256_r.sh
JIT/HardwareIntrinsics/X86/Avx2/ShiftLeftLogicalVariable_r/ShiftLeftLogicalVariable_r.sh
JIT/HardwareIntrinsics/X86/Avx2/ShiftRightLogicalVariable_r/ShiftRightLogicalVariable_r.sh
JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_r/Avx2_r.sh
JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/Avx2_ro.sh
JIT/HardwareIntrinsics/X86/Avx/Avx_r/Avx_r.sh
JIT/HardwareIntrinsics/X86/Avx/Avx_ro/Avx_ro.sh
JIT/HardwareIntrinsics/X86/Avx/BroadcastScalarToVector128_r/BroadcastScalarToVector128_r.sh
JIT/HardwareIntrinsics/X86/Avx/Compare_r/Compare_r.sh
JIT/HardwareIntrinsics/X86/Avx/CompareScalar_r/CompareScalar_r.sh
JIT/HardwareIntrinsics/X86/Avx/CompareScalar_ro/CompareScalar_ro.sh
JIT/HardwareIntrinsics/X86/Avx/ConvertToVector_r/ConvertToVector_r.sh
JIT/HardwareIntrinsics/X86/Avx/ConvertToVector_ro/ConvertToVector_ro.sh
JIT/HardwareIntrinsics/X86/Avx/InsertExtractVector128_r/InsertExtractVector128_r.sh
JIT/HardwareIntrinsics/X86/Avx/InsertExtractVector128_ro/InsertExtractVector128_ro.sh
JIT/HardwareIntrinsics/X86/Avx/MaskLoad_r/MaskLoad_r.sh
JIT/HardwareIntrinsics/X86/Bmi1/Bmi1_ro/Bmi1_ro.sh
JIT/HardwareIntrinsics/X86/Bmi2/Bmi2_ro/Bmi2_ro.sh
JIT/HardwareIntrinsics/X86/Fma_Vector128/Fma_r/Fma_r.sh
JIT/HardwareIntrinsics/X86/Fma_Vector128/Fma_ro/Fma_ro.sh
JIT/HardwareIntrinsics/X86/General/VectorArgs_r/VectorArgs_r.sh
JIT/HardwareIntrinsics/X86/General/VectorRet_r/VectorRet_r.sh
JIT/HardwareIntrinsics/X86/General/VectorUnused_r/VectorUnused_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareEqualScalar_r/CompareEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareGreaterThanOrEqualScalar_r/CompareGreaterThanOrEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareGreaterThanOrEqualScalar_ro/CompareGreaterThanOrEqualScalar_ro.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareGreaterThanScalar_r/CompareGreaterThanScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareLessThanOrEqualScalar_r/CompareLessThanOrEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareLessThanScalar_r/CompareLessThanScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareNotEqualScalar_r/CompareNotEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareNotGreaterThanOrEqualScalar_r/CompareNotGreaterThanOrEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareNotGreaterThanScalar_r/CompareNotGreaterThanScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareNotLessThanOrEqualScalar_r/CompareNotLessThanOrEqualScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareNotLessThanScalar_r/CompareNotLessThanScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareOrderedScalar_r/CompareOrderedScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/CompareUnorderedScalar_r/CompareUnorderedScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128Double_r/ConvertScalarToVector128Double_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128Int32_r/ConvertScalarToVector128Int32_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128Int64_r/ConvertScalarToVector128Int64_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128Single_r/ConvertScalarToVector128Single_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128UInt32_r/ConvertScalarToVector128UInt32_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128UInt64_r/ConvertScalarToVector128UInt64_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertToInt32_r/ConvertToInt32_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertToVector128Double_r/ConvertToVector128Double_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertToVector128Int32_r/ConvertToVector128Int32_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertToVector128Int32WithTruncation_r/ConvertToVector128Int32WithTruncation_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ConvertToVector128Single_r/ConvertToVector128Single_r.sh
JIT/HardwareIntrinsics/X86/Sse2/LoadAlignedVector128_r/LoadAlignedVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/LoadHigh_r/LoadHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse2/LoadLow_r/LoadLow_r.sh
JIT/HardwareIntrinsics/X86/Sse2/LoadScalarVector128_r/LoadScalarVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/LoadVector128_r/LoadVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/MultiplyHigh_r/MultiplyHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse2/MultiplyHorizontalAdd_r/MultiplyHorizontalAdd_r.sh
JIT/HardwareIntrinsics/X86/Sse2/MultiplyLow_r/MultiplyLow_r.sh
JIT/HardwareIntrinsics/X86/Sse2/Multiply_r/Multiply_r.sh
JIT/HardwareIntrinsics/X86/Sse2/PackSignedSaturate_r/PackSignedSaturate_r.sh
JIT/HardwareIntrinsics/X86/Sse2/PackUnsignedSaturate_r/PackUnsignedSaturate_r.sh
JIT/HardwareIntrinsics/X86/Sse2/SetScalarVector128_r/SetScalarVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/SetVector128_ro/SetVector128_ro.sh
JIT/HardwareIntrinsics/X86/Sse2/SetVector128_r/SetVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/SetZeroVector128_r/SetZeroVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ShuffleHigh_r/ShuffleHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse2/ShuffleLow_r/ShuffleLow_r.sh
JIT/HardwareIntrinsics/X86/Sse2/Shuffle_r/Shuffle_r.sh
JIT/HardwareIntrinsics/X86/Sse2/Sqrt_r/Sqrt_r.sh
JIT/HardwareIntrinsics/X86/Sse2/SqrtScalar_r/SqrtScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/Sse2_ro/Sse2_ro.sh
JIT/HardwareIntrinsics/X86/Sse2/Sse2_r/Sse2_r.sh
JIT/HardwareIntrinsics/X86/Sse2/StoreAlignedNonTemporal_r/StoreAlignedNonTemporal_r.sh
JIT/HardwareIntrinsics/X86/Sse2/StoreAligned_r/StoreAligned_r.sh
JIT/HardwareIntrinsics/X86/Sse2/StoreHigh_r/StoreHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse2/StoreLow_r/StoreLow_r.sh
JIT/HardwareIntrinsics/X86/Sse2/Store_r/Store_r.sh
JIT/HardwareIntrinsics/X86/Sse2/StoreScalar_r/StoreScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse2/SumAbsoluteDifferences_r/SumAbsoluteDifferences_r.sh
JIT/HardwareIntrinsics/X86/Sse2/UnpackHigh_r/UnpackHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse2/UnpackLow_r/UnpackLow_r.sh
JIT/HardwareIntrinsics/X86/Sse3/LoadAndDuplicateToVector128_r/LoadAndDuplicateToVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse3/LoadDquVector128_r/LoadDquVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse3/MoveAndDuplicate_r/MoveAndDuplicate_r.sh
JIT/HardwareIntrinsics/X86/Sse3/MoveHighAndDuplicate_r/MoveHighAndDuplicate_r.sh
JIT/HardwareIntrinsics/X86/Sse3/MoveLowAndDuplicate_r/MoveLowAndDuplicate_r.sh
JIT/HardwareIntrinsics/X86/Sse3/Sse3_ro/Sse3_ro.sh
JIT/HardwareIntrinsics/X86/Sse3/Sse3_r/Sse3_r.sh
JIT/HardwareIntrinsics/X86/Sse41/Blend_r/Blend_r.sh
JIT/HardwareIntrinsics/X86/Sse41/ConvertToVector128_r/ConvertToVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse41/ConvertToVector128_ro/ConvertToVector128_ro.sh
JIT/HardwareIntrinsics/X86/Sse41/DotProduct_r/DotProduct_r.sh
JIT/HardwareIntrinsics/X86/Sse41/LoadAlignedVector128NonTemporal_r/LoadAlignedVector128NonTemporal_r.sh
JIT/HardwareIntrinsics/X86/Sse41/MinHorizontal_r/MinHorizontal_r.sh
JIT/HardwareIntrinsics/X86/Sse41/MinHorizontal_ro/MinHorizontal_ro.sh
JIT/HardwareIntrinsics/X86/Sse41/MultipleSumAbsoluteDifferences_r/MultipleSumAbsoluteDifferences_r.sh
JIT/HardwareIntrinsics/X86/Sse41/MultipleSumAbsoluteDifferences_ro/MultipleSumAbsoluteDifferences_ro.sh
JIT/HardwareIntrinsics/X86/Sse41/Multiply_r/Multiply_r.sh
JIT/HardwareIntrinsics/X86/Sse41/Sse41_ro/Sse41_ro.sh
JIT/HardwareIntrinsics/X86/Sse41/Sse41_r/Sse41_r.sh
JIT/HardwareIntrinsics/X86/Sse42/Sse42_ro/Sse42_ro.sh
JIT/HardwareIntrinsics/X86/Sse42/Sse42_r/Sse42_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertScalarToVector128Single_r/ConvertScalarToVector128Single_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertToInt32_r/ConvertToInt32_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertToInt32WithTruncation_r/ConvertToInt32WithTruncation_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertToInt64_r/ConvertToInt64_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertToInt64WithTruncation_r/ConvertToInt64WithTruncation_r.sh
JIT/HardwareIntrinsics/X86/Sse/ConvertToSingle_r/ConvertToSingle_r.sh
JIT/HardwareIntrinsics/X86/Sse/LoadAlignedVector128_r/LoadAlignedVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/LoadHigh_r/LoadHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse/LoadLow_r/LoadLow_r.sh
JIT/HardwareIntrinsics/X86/Sse/LoadScalarVector128_r/LoadScalarVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/LoadVector128_r/LoadVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/MoveHighToLow_r/MoveHighToLow_r.sh
JIT/HardwareIntrinsics/X86/Sse/MoveLowToHigh_r/MoveLowToHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse/MoveMask_r/MoveMask_r.sh
JIT/HardwareIntrinsics/X86/Sse/MoveScalar_r/MoveScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse/Reciprocal_r/Reciprocal_r.sh
JIT/HardwareIntrinsics/X86/Sse/ReciprocalScalar_r/ReciprocalScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse/ReciprocalSqrt_r/ReciprocalSqrt_r.sh
JIT/HardwareIntrinsics/X86/Sse/ReciprocalSqrtScalar_r/ReciprocalSqrtScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse/SetAllVector128_r/SetAllVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/SetScalarVector128_r/SetScalarVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/SetVector128_r/SetVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/SetZeroVector128_r/SetZeroVector128_r.sh
JIT/HardwareIntrinsics/X86/Sse/Shuffle_r/Shuffle_r.sh
JIT/HardwareIntrinsics/X86/Sse/Sqrt_r/Sqrt_r.sh
JIT/HardwareIntrinsics/X86/Sse/SqrtScalar_r/SqrtScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse/Sse_ro/Sse_ro.sh
JIT/HardwareIntrinsics/X86/Sse/Sse_r/Sse_r.sh
JIT/HardwareIntrinsics/X86/Sse/StaticCast_ro/StaticCast_ro.sh
JIT/HardwareIntrinsics/X86/Sse/StaticCast_r/StaticCast_r.sh
JIT/HardwareIntrinsics/X86/Sse/StoreAlignedNonTemporal_r/StoreAlignedNonTemporal_r.sh
JIT/HardwareIntrinsics/X86/Sse/StoreAligned_r/StoreAligned_r.sh
JIT/HardwareIntrinsics/X86/Sse/StoreHigh_r/StoreHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse/StoreLow_r/StoreLow_r.sh
JIT/HardwareIntrinsics/X86/Sse/Store_r/Store_r.sh
JIT/HardwareIntrinsics/X86/Sse/StoreScalar_r/StoreScalar_r.sh
JIT/HardwareIntrinsics/X86/Sse/UnpackHigh_r/UnpackHigh_r.sh
JIT/HardwareIntrinsics/X86/Sse/UnpackLow_r/UnpackLow_r.sh
JIT/HardwareIntrinsics/X86/Ssse3/AlignRight_r/AlignRight_r.sh
JIT/HardwareIntrinsics/X86/Ssse3/Ssse3_ro/Ssse3_ro.sh
JIT/HardwareIntrinsics/X86/Ssse3/Ssse3_r/Ssse3_r.sh
JIT/jit64/gc/misc/struct7_1/struct7_1.sh
JIT/jit64/gc/misc/test3/test3.sh
JIT/jit64/hfa/main/testE/hfa_nd0E_d/hfa_nd0E_d.sh
JIT/jit64/hfa/main/testE/hfa_nd1E_d/hfa_nd1E_d.sh
JIT/jit64/hfa/main/testE/hfa_nd2E_d/hfa_nd2E_d.sh
JIT/jit64/hfa/main/testE/hfa_nd2E_r/hfa_nd2E_r.sh
JIT/jit64/hfa/main/testE/hfa_nf0E_d/hfa_nf0E_d.sh
JIT/jit64/hfa/main/testE/hfa_nf1E_d/hfa_nf1E_d.sh
JIT/jit64/hfa/main/testE/hfa_nf2E_d/hfa_nf2E_d.sh
JIT/jit64/hfa/main/testE/hfa_nf2E_r/hfa_nf2E_r.sh
JIT/jit64/hfa/main/testE/hfa_sd0E_d/hfa_sd0E_d.sh
JIT/jit64/hfa/main/testE/hfa_sd1E_d/hfa_sd1E_d.sh
JIT/jit64/hfa/main/testE/hfa_sd2E_d/hfa_sd2E_d.sh
JIT/jit64/hfa/main/testE/hfa_sd2E_r/hfa_sd2E_r.sh
JIT/jit64/hfa/main/testE/hfa_sf0E_d/hfa_sf0E_d.sh
JIT/jit64/hfa/main/testE/hfa_sf1E_d/hfa_sf1E_d.sh
JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.sh
JIT/jit64/hfa/main/testE/hfa_sf2E_r/hfa_sf2E_r.sh
JIT/jit64/regress/vsw/471729/test/test.sh
JIT/jit64/regress/vsw/539509/test1/test1.sh
JIT/Methodical/divrem/div/decimaldiv_cs_d/decimaldiv_cs_d.sh
JIT/Methodical/divrem/div/decimaldiv_cs_do/decimaldiv_cs_do.sh
JIT/Methodical/divrem/div/decimaldiv_cs_r/decimaldiv_cs_r.sh
JIT/Methodical/divrem/div/decimaldiv_cs_ro/decimaldiv_cs_ro.sh
JIT/Methodical/divrem/div/i4div_cs_d/i4div_cs_d.sh
JIT/Methodical/divrem/div/i4div_cs_do/i4div_cs_do.sh
JIT/Methodical/divrem/div/i4div_cs_r/i4div_cs_r.sh
JIT/Methodical/divrem/div/i4div_cs_ro/i4div_cs_ro.sh
JIT/Methodical/divrem/div/i8div_cs_d/i8div_cs_d.sh
JIT/Methodical/divrem/div/i8div_cs_do/i8div_cs_do.sh
JIT/Methodical/divrem/div/i8div_cs_r/i8div_cs_r.sh
JIT/Methodical/divrem/div/i8div_cs_ro/i8div_cs_ro.sh
JIT/Methodical/divrem/div/overlddiv_cs_d/overlddiv_cs_d.sh
JIT/Methodical/divrem/div/overlddiv_cs_r/overlddiv_cs_r.sh
JIT/Methodical/divrem/div/r4div_cs_d/r4div_cs_d.sh
JIT/Methodical/divrem/div/r4div_cs_r/r4div_cs_r.sh
JIT/Methodical/divrem/div/r8div_cs_d/r8div_cs_d.sh
JIT/Methodical/divrem/div/r8div_cs_r/r8div_cs_r.sh
JIT/Methodical/divrem/div/u4div_cs_do/u4div_cs_do.sh
JIT/Methodical/divrem/div/u4div_cs_d/u4div_cs_d.sh
JIT/Methodical/divrem/div/u4div_cs_ro/u4div_cs_ro.sh
JIT/Methodical/divrem/div/u4div_cs_r/u4div_cs_r.sh
JIT/Methodical/divrem/div/u8div_cs_do/u8div_cs_do.sh
JIT/Methodical/divrem/div/u8div_cs_d/u8div_cs_d.sh
JIT/Methodical/divrem/div/u8div_cs_ro/u8div_cs_ro.sh
JIT/Methodical/divrem/div/u8div_cs_r/u8div_cs_r.sh
JIT/Methodical/divrem/rem/decimalrem_cs_d/decimalrem_cs_d.sh
JIT/Methodical/divrem/rem/decimalrem_cs_do/decimalrem_cs_do.sh
JIT/Methodical/divrem/rem/decimalrem_cs_r/decimalrem_cs_r.sh
JIT/Methodical/divrem/rem/decimalrem_cs_ro/decimalrem_cs_ro.sh
JIT/Methodical/divrem/rem/i4rem_cs_d/i4rem_cs_d.sh
JIT/Methodical/divrem/rem/i4rem_cs_do/i4rem_cs_do.sh
JIT/Methodical/divrem/rem/i4rem_cs_r/i4rem_cs_r.sh
JIT/Methodical/divrem/rem/i4rem_cs_ro/i4rem_cs_ro.sh
JIT/Methodical/divrem/rem/i8rem_cs_d/i8rem_cs_d.sh
JIT/Methodical/divrem/rem/i8rem_cs_do/i8rem_cs_do.sh
JIT/Methodical/divrem/rem/i8rem_cs_r/i8rem_cs_r.sh
JIT/Methodical/divrem/rem/i8rem_cs_ro/i8rem_cs_ro.sh
JIT/Methodical/divrem/rem/overldrem_cs_d/overldrem_cs_d.sh
JIT/Methodical/divrem/rem/overldrem_cs_r/overldrem_cs_r.sh
JIT/Methodical/divrem/rem/r4rem_cs_d/r4rem_cs_d.sh
JIT/Methodical/divrem/rem/r4rem_cs_r/r4rem_cs_r.sh
JIT/Methodical/divrem/rem/r8rem_cs_d/r8rem_cs_d.sh
JIT/Methodical/divrem/rem/r8rem_cs_r/r8rem_cs_r.sh
JIT/Methodical/divrem/rem/u4rem_cs_do/u4rem_cs_do.sh
JIT/Methodical/divrem/rem/u4rem_cs_d/u4rem_cs_d.sh
JIT/Methodical/divrem/rem/u4rem_cs_ro/u4rem_cs_ro.sh
JIT/Methodical/divrem/rem/u4rem_cs_r/u4rem_cs_r.sh
JIT/Methodical/divrem/rem/u8rem_cs_do/u8rem_cs_do.sh
JIT/Methodical/divrem/rem/u8rem_cs_d/u8rem_cs_d.sh
JIT/Methodical/divrem/rem/u8rem_cs_ro/u8rem_cs_ro.sh
JIT/Methodical/divrem/rem/u8rem_cs_r/u8rem_cs_r.sh
JIT/Methodical/fp/exgen/1000w1d_cs_d/1000w1d_cs_d.sh
JIT/Methodical/fp/exgen/1000w1d_cs_do/1000w1d_cs_do.sh
JIT/Methodical/fp/exgen/1000w1d_cs_r/1000w1d_cs_r.sh
JIT/Methodical/fp/exgen/1000w1d_cs_ro/1000w1d_cs_ro.sh
JIT/Methodical/fp/exgen/10w250d_cs_d/10w250d_cs_d.sh
JIT/Methodical/fp/exgen/10w250d_cs_do/10w250d_cs_do.sh
JIT/Methodical/fp/exgen/10w250d_cs_r/10w250d_cs_r.sh
JIT/Methodical/fp/exgen/10w250d_cs_ro/10w250d_cs_ro.sh
JIT/Methodical/fp/exgen/10w5d_cs_d/10w5d_cs_d.sh
JIT/Methodical/fp/exgen/10w5d_cs_do/10w5d_cs_do.sh
JIT/Methodical/fp/exgen/10w5d_cs_r/10w5d_cs_r.sh
JIT/Methodical/fp/exgen/10w5d_cs_ro/10w5d_cs_ro.sh
JIT/Methodical/fp/exgen/200w1d-02_cs_d/200w1d-02_cs_d.sh
JIT/Methodical/fp/exgen/200w1d-02_cs_do/200w1d-02_cs_do.sh
JIT/Methodical/fp/exgen/200w1d-02_cs_r/200w1d-02_cs_r.sh
JIT/Methodical/fp/exgen/200w1d-02_cs_ro/200w1d-02_cs_ro.sh
JIT/Methodical/fp/exgen/5w1d-03_cs_d/5w1d-03_cs_d.sh
JIT/Methodical/fp/exgen/5w1d-03_cs_do/5w1d-03_cs_do.sh
JIT/Methodical/fp/exgen/5w1d-03_cs_r/5w1d-03_cs_r.sh
JIT/Methodical/fp/exgen/5w1d-03_cs_ro/5w1d-03_cs_ro.sh
JIT/Methodical/inlining/bug505642/test/test.sh
JIT/Methodical/int64/superlong/_dbgsuperlong/_dbgsuperlong.sh
JIT/Methodical/int64/superlong/_il_dbgsuperlong/_il_dbgsuperlong.sh
JIT/Methodical/int64/superlong/_il_relsuperlong/_il_relsuperlong.sh
JIT/Methodical/int64/superlong/_relsuperlong/_relsuperlong.sh
JIT/Methodical/int64/superlong/_speed_dbgsuperlong/_speed_dbgsuperlong.sh
JIT/Methodical/int64/superlong/_speed_relsuperlong/_speed_relsuperlong.sh
JIT/Methodical/MDArray/DataTypes/byte_cs_d/byte_cs_d.sh
JIT/Methodical/MDArray/DataTypes/byte_cs_r/byte_cs_r.sh
JIT/Methodical/MDArray/DataTypes/decimal_cs_d/decimal_cs_d.sh
JIT/Methodical/MDArray/DataTypes/decimal_cs_do/decimal_cs_do.sh
JIT/Methodical/MDArray/DataTypes/decimal_cs_r/decimal_cs_r.sh
JIT/Methodical/MDArray/DataTypes/decimal_cs_ro/decimal_cs_ro.sh
JIT/Methodical/MDArray/DataTypes/double_cs_d/double_cs_d.sh
JIT/Methodical/MDArray/DataTypes/double_cs_r/double_cs_r.sh
JIT/Methodical/MDArray/DataTypes/float_cs_d/float_cs_d.sh
JIT/Methodical/MDArray/DataTypes/float_cs_r/float_cs_r.sh
JIT/Methodical/MDArray/DataTypes/int_cs_d/int_cs_d.sh
JIT/Methodical/MDArray/DataTypes/int_cs_r/int_cs_r.sh
JIT/Methodical/MDArray/DataTypes/long_cs_d/long_cs_d.sh
JIT/Methodical/MDArray/DataTypes/long_cs_r/long_cs_r.sh
JIT/Methodical/MDArray/DataTypes/sbyte_cs_d/sbyte_cs_d.sh
JIT/Methodical/MDArray/DataTypes/sbyte_cs_r/sbyte_cs_r.sh
JIT/Methodical/MDArray/DataTypes/short_cs_d/short_cs_d.sh
JIT/Methodical/MDArray/DataTypes/short_cs_r/short_cs_r.sh
JIT/Methodical/MDArray/DataTypes/uint_cs_d/uint_cs_d.sh
JIT/Methodical/MDArray/DataTypes/uint_cs_r/uint_cs_r.sh
JIT/Methodical/MDArray/DataTypes/ulong_cs_d/ulong_cs_d.sh
JIT/Methodical/MDArray/DataTypes/ulong_cs_r/ulong_cs_r.sh
JIT/Methodical/MDArray/DataTypes/ushort_cs_d/ushort_cs_d.sh
JIT/Methodical/MDArray/DataTypes/ushort_cs_r/ushort_cs_r.sh
JIT/Methodical/structs/ExplicitLayout/ExplicitLayout.sh
JIT/Methodical/structs/systemvbringup/structinregs/structinregs.sh
JIT/Methodical/tailcall/_il_dbggcval_nested/_il_dbggcval_nested.sh
JIT/Methodical/tailcall/_il_dbgtest_implicit/_il_dbgtest_implicit.sh
JIT/Methodical/tailcall/_il_relgcval_nested/_il_relgcval_nested.sh
JIT/Methodical/tailcall/_il_reltest_implicit/_il_reltest_implicit.sh
JIT/Methodical/tailcall_v4/smallFrame/smallFrame.sh
JIT/Methodical/VT/callconv/_dbgcall/_dbgcall.sh
JIT/Methodical/VT/callconv/_dbgjumper/_dbgjumper.sh
JIT/Methodical/VT/callconv/_dbgvtret/_dbgvtret.sh
JIT/Methodical/VT/callconv/_il_dbgaa/_il_dbgaa.sh
JIT/Methodical/VT/callconv/_il_dbgcalli/_il_dbgcalli.sh
JIT/Methodical/VT/callconv/_il_dbgdd/_il_dbgdd.sh
JIT/Methodical/VT/callconv/_il_dbgee/_il_dbgee.sh
JIT/Methodical/VT/callconv/_il_dbgjumper1/_il_dbgjumper1.sh
JIT/Methodical/VT/callconv/_il_dbgjumper2/_il_dbgjumper2.sh
JIT/Methodical/VT/callconv/_il_dbgjumper3/_il_dbgjumper3.sh
JIT/Methodical/VT/callconv/_il_dbgjumper4/_il_dbgjumper4.sh
JIT/Methodical/VT/callconv/_il_dbgjumper5/_il_dbgjumper5.sh
JIT/Methodical/VT/callconv/_il_dbgvtret2/_il_dbgvtret2.sh
JIT/Methodical/VT/callconv/_il_dbgvtret/_il_dbgvtret.sh
JIT/Methodical/VT/callconv/_il_relaa/_il_relaa.sh
JIT/Methodical/VT/callconv/_il_relcalli/_il_relcalli.sh
JIT/Methodical/VT/callconv/_il_reldd/_il_reldd.sh
JIT/Methodical/VT/callconv/_il_relee/_il_relee.sh
JIT/Methodical/VT/callconv/_il_reljumper2/_il_reljumper2.sh
JIT/Methodical/VT/callconv/_il_reljumper3/_il_reljumper3.sh
JIT/Methodical/VT/callconv/_il_reljumper4/_il_reljumper4.sh
JIT/Methodical/VT/callconv/_il_reljumper5/_il_reljumper5.sh
JIT/Methodical/VT/callconv/_il_relvtret2/_il_relvtret2.sh
JIT/Methodical/VT/callconv/_il_relvtret/_il_relvtret.sh
JIT/Methodical/VT/callconv/_relcall/_relcall.sh
JIT/Methodical/VT/callconv/_reljumper/_reljumper.sh
JIT/Methodical/VT/callconv/_relvtret/_relvtret.sh
JIT/Methodical/VT/callconv/_speed_dbgcall/_speed_dbgcall.sh
JIT/Methodical/VT/callconv/_speed_relcall/_speed_relcall.sh
JIT/Methodical/VT/port/_dbglcs_gcref/_dbglcs_gcref.sh
JIT/Methodical/VT/port/_rellcs_gcref/_rellcs_gcref.sh
JIT/Methodical/VT/port/_speed_dbglcs_gcref/_speed_dbglcs_gcref.sh
JIT/Methodical/VT/port/_speed_rellcs_gcref/_speed_rellcs_gcref.sh
JIT/opt/Inline/tests/struct_opcodes/struct_opcodes.sh
JIT/opt/virtualstubdispatch/hashcode/ctest1_cs_d/ctest1_cs_d.sh
JIT/opt/virtualstubdispatch/hashcode/ctest1_cs_r/ctest1_cs_r.sh
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_d/ctest_cs_d.sh
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_do/ctest_cs_do.sh
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_r/ctest_cs_r.sh
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_ro/ctest_cs_ro.sh
JIT/Performance/CodeQuality/BenchmarksGame/pidigits/pidigits-3/pidigits-3.sh
JIT/Performance/CodeQuality/Burgers/Burgers/Burgers.sh
JIT/Performance/CodeQuality/Linq/Linq/Linq.sh
JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh
JIT/Performance/CodeQuality/Span/Indexer/Indexer.sh
JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
JIT/Regression/CLR-x86-JIT/V1.1-M1-Beta1/b140902/b140902/b140902.sh
JIT/Regression/CLR-x86-JIT/V1.2-M01/b02345/b02345/b02345.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b14716/b14716/b14716.sh
JIT/Regression/CLR-x86-JIT/V1-M10/b02352/b02352/b02352.sh
JIT/Regression/Dev11/DevDiv2_10623/DevDiv2_10623/DevDiv2_10623.sh
JIT/Regression/Dev11/External/Dev11_90434/UseUnalignedDouble/UseUnalignedDouble.sh
JIT/Regression/JitBlue/DevDiv_546018/DevDiv_546018/DevDiv_546018.sh
JIT/Regression/JitBlue/GitHub_10481/GitHub_10481/GitHub_10481.sh
JIT/Regression/JitBlue/GitHub_1133/GitHub_1133/GitHub_1133.sh
JIT/Regression/JitBlue/GitHub_11814/GitHub_11814/GitHub_11814.sh
JIT/Regression/JitBlue/GitHub_11816/GitHub_11816/GitHub_11816.sh
JIT/Regression/JitBlue/GitHub_13057/GitHub_13057/GitHub_13057.sh
JIT/Regression/JitBlue/GitHub_16254/GitHub_16254/GitHub_16254.sh
JIT/Regression/JitBlue/GitHub_18497/GitHub_18497/GitHub_18497.sh
JIT/Regression/JitBlue/GitHub_4115/GitHub_4115/GitHub_4115.sh
JIT/Regression/JitBlue/GitHub_5164/GitHub_5164/GitHub_5164.sh
JIT/Regression/JitBlue/GitHub_7508/Vector3Test/Vector3Test.sh
JIT/Regression/JitBlue/GitHub_8220/GitHub_8220/GitHub_8220.sh
JIT/Regression/VS-ia64-JIT/V1.2-M02/b26496/b26496/b26496.sh
JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309539/b309539/b309539.sh
JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
JIT/SIMD/AbsSqrt_r/AbsSqrt_r.sh
JIT/SIMD/AddingSequence_r/AddingSequence_r.sh
JIT/SIMD/CircleInConvex_r/CircleInConvex_r.sh
JIT/SIMD/CircleInConvex_ro/CircleInConvex_ro.sh
JIT/SIMD/CreateGeneric_r/CreateGeneric_r.sh
JIT/SIMD/CreateGeneric_ro/CreateGeneric_ro.sh
JIT/SIMD/DivSignedUnsignedTest_r/DivSignedUnsignedTest_r.sh
JIT/SIMD/DivSignedUnsignedTest_ro/DivSignedUnsignedTest_ro.sh
JIT/SIMD/LdfldGeneric_r/LdfldGeneric_r.sh
JIT/SIMD/Ldfld_r/Ldfld_r.sh
JIT/SIMD/Matrix4x4_r/Matrix4x4_r.sh
JIT/SIMD/Plane_r/Plane_r.sh
JIT/SIMD/SqrtGeneric_ro/SqrtGeneric_ro.sh
JIT/SIMD/SqrtGeneric_r/SqrtGeneric_r.sh
JIT/SIMD/Sums_r/Sums_r.sh
JIT/SIMD/Vector3Interop_ro/Vector3Interop_ro.sh
JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
JIT/SIMD/Vector3_r/Vector3_r.sh
JIT/SIMD/Vector4_r/Vector4_r.sh
JIT/SIMD/VectorArgs_ro/VectorArgs_ro.sh
JIT/SIMD/VectorArgs_r/VectorArgs_r.sh
JIT/SIMD/VectorCast_ro/VectorCast_ro.sh
JIT/SIMD/VectorCast_r/VectorCast_r.sh
JIT/SIMD/VectorConvert_ro/VectorConvert_ro.sh
JIT/SIMD/VectorConvert_r/VectorConvert_r.sh
JIT/SIMD/VectorDiv_ro/VectorDiv_ro.sh
JIT/SIMD/VectorDiv_r/VectorDiv_r.sh
JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
JIT/SIMD/VectorExp_r/VectorExp_r.sh
JIT/SIMD/VectorMul_ro/VectorMul_ro.sh
JIT/SIMD/VectorMul_r/VectorMul_r.sh
JIT/SIMD/VectorReturn_ro/VectorReturn_ro.sh
JIT/SIMD/VectorReturn_r/VectorReturn_r.sh
JIT/SIMD/VectorUnused_r/VectorUnused_r.sh
Loader/classloader/regressions/208900/bug/bug.sh
Loader/classloader/v1/Beta1/Layout/Matrix/cs/L-2-5-3/L-2-5-3.sh
readytorun/r2rdump/R2RDumpTest/R2RDumpTest.sh
tracing/eventactivityidcontrol/eventactivityidcontrol/eventactivityidcontrol.sh
tracing/eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh
tracing/tracevalidation/inducedgc/inducedgc/inducedgc.sh
tracing/tracevalidation/jittingstarted/JittingStarted/JittingStarted.sh
tracing/tracevalidation/rundown/rundown/rundown.sh
```

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #19029

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked r2r_jitstressregs8 Build and Test

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT arm64 Cross Checked jitstressregs8 Build and Test
@dotnet-bot test Ubuntu arm Cross Checked corefx_jitstressregs8 Build and Test

**Comment by CarolEidt** [comment]
@dotnet/dnceng - Something is wrong with the CI; it is only kicking off 7 tests instead of the usual 30-ish
cc @dotnet/jit-contrib

**Comment by mmitche** [comment]
Take a look now.

**Comment by MattGal** [comment]
+1, by the time I got here it added up to 31...

File: src/jit/gentree.h [hunk 1]
```diff
@@ -6022,6 +6048,40 @@ inline bool GenTree::IsMultiRegNode() const
...
+// Return Value:
+//     Returns the number of registers defined by this node.
+inline unsigned GenTree::GetMultiRegCount()
+{
+    if (IsMultiRegCall())
+    {
+        return AsCall()->GetReturnTypeDesc()->GetReturnRegCount();
+    }
+
+#if FEATURE_ARG_SPLIT
```
Comment (jashook) [inline src/jit/gentree.h]: I believe that this can safely be #if __TARGET_ARM__ instead of FEATURE_SPLIT_ARG. As arm64 will never have split return types even under windows.

Comment (sandreenko) [reply src/jit/gentree.h]: arm64 won't, but x86 can.

Comment (CarolEidt) [reply src/jit/gentree.h]: But this isn't about return types, this is about arguments.

Comment (jashook) [reply src/jit/gentree.h]: Ah I misread this you can safely ignore my comment :)

**Comment by CarolEidt** [comment]
Well, this didn't magically fix the arm jitStressRegs=8 failures, but at least I got a clean run of "Windows_NT arm64 Cross Checked jitstressregs8".
