### PR TITLE
Fix ordering of operands on GT_RSZ

### LINKED ISSUE #8171: RyuJIT/x86: CoreFx System.Runtime.Numerics.Tests bad output
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Numerics.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
<details>
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Numerics.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:56:21.12
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Numerics.Tests
Discovered:  System.Runtime.Numerics.Tests
Starting:    System.Runtime.Numerics.Tests
   System.Numerics.Tests.powTest.RunPowPositive [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 25)
      Expected: ┬╖┬╖┬╖7683008515512768521713650302149162161179979006561675774412070┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖7683008515512768521739095889163876024558036744685930462639169┬╖┬╖┬╖
                                       Γåæ (pos 25)
      Stack Trace:
            at System.Numerics.Tests.powTest.VerifyPowString(String opstring)
            at System.Numerics.Tests.powTest.RunPowPositive()
   System.Numerics.Tests.ComplexTests.Sin_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.ComplexTests.Cos_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.modpowTest.ModPowAxiom [FAIL]
      Assert.Equal() Failure
                Γåô (pos 0)
      Expected: 35756117882162760394883167857088395196910┬╖┬╖┬╖
      Actual:   -33
                Γåæ (pos 0)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyIdentityString(String opstring1, String opstring2)
            at System.Numerics.Tests.modpowTest.ModPowAxiom()
   System.Numerics.Tests.ComplexTests.Exp [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.ComplexTests.Cosh_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.op_multiplyTest.RunMultiplyPositive [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271800991226528542┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.op_multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.op_multiplyTest.RunMultiplyPositive()
   System.Numerics.Tests.op_multiplyTest.RunMultiplyTests [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 26)
      Expected: ┬╖┬╖┬╖2278240356085911958312282048585909376613748417042912784564252┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖2278240356085911958309821985470873874364021968865128885235425┬╖┬╖┬╖
                                       Γåæ (pos 26)
      Stack Trace:
            at System.Numerics.Tests.op_multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.op_multiplyTest.RunMultiplyTests()
   System.Numerics.Tests.ComplexTests.Sinh_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers_Threshold [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271801170033442122┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.multiplyTest.<>c.<RunMultiply_TwoLargeBigIntegers_Threshold>b__3_0()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers_Threshold()
   System.Numerics.Tests.ComplexTests.Reciprocal [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt_Threshold [FAIL]
      Assert.Equal() Failure
                 Γåô (pos 1)
      Expected: -38776096123501334825274240210298033125015┬╖┬╖┬╖
      Actual:   -18889465607631406169342467084338106397442┬╖┬╖┬╖
                 Γåæ (pos 1)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyModPowString(String opstring)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt_Threshold()
   System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271800991226528542┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers()
   System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 30)
      Expected: ┬╖┬╖┬╖114494808774362973053522177428284780306484519494117131965505
      Actual:   ┬╖┬╖┬╖114494808774362973054202742162285113558476690872315175392321
                                       Γåæ (pos 30)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyModPowString(String opstring)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt()
Finished:    System.Runtime.Numerics.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 1213, Errors: 0, Failed: 8, Skipped: 6, Time: 154.399s
Finished running tests.  End time=17:59:15.76, Exit code = 1
```
</details>

### PR DESCRIPTION
**Pull request by adiaaida**
By removing hiOp1 and loOp1 from LIR and then putting them back in, we
inadvertantly reversed the order of operations for high and lo. This is an
issue when op1 is a long add or sub where the order of operations is
important.

Fixes #8171.

### CODE REVIEW

**Comment by adiaaida** [comment]
@pgavlin PTAL
/cc: @dotnet/jit-contrib

**Comment by adiaaida** [comment]
@pgavlin ping

File: src/jit/decomposelongs.cpp [hunk 1]
```diff
@@ -1134,12 +1132,13 @@ GenTree* DecomposeLongs::DecomposeShift(LIR::Use& use)
...
 
-                    Range().InsertBefore(tree, loOp1, hiCopy, loOp);
+                    Range().InsertBefore(tree, hiCopy, loOp);
                     Range().InsertBefore(tree, shiftByLo, loResult);
-                    Range().InsertBefore(tree, hiOp1, shiftByHi, hiResult);
+                    Range().InsertBefore(tree, shiftByHi, hiResult);
                 }
                 else
                 {
+                    Range().Remove(loOp1);
```
Comment (pgavlin) [inline src/jit/decomposelongs.cpp]: Just to be clear, this codepath completely discards `loOp`, correct?

Comment (adiaaida) [inline src/jit/decomposelongs.cpp]: Yes.
