### PR TITLE
Avoid a large local in a recursive visitor.

### LINKED ISSUE #12691: New tree walker consumes more stack space, leads to stackoverflow
Forked from https://github.com/dotnet/coreclr/pull/12669#issuecomment-313788909

Repro: crossgen bigvtbl_cs_do.exe on Windows x64 Release (or trigger `Windows_NT Release r2r` in CI)

It crashes with stack overflow exception:

```
 # Child-SP          RetAddr           Call Site
clrjit!GenTreeVisitor<GenericTreeWalker<0,1,0,0,1> >::WalkTree+0x1c1 [d:\coreclr\src\jit\compiler.h @ 9862]
clrjit!GenTreeVisitor<GenericTreeWalker<0,1,0,0,1> >::WalkTree+0x1df [d:\coreclr\src\jit\compiler.h @ 9872]
clrjit!GenTreeVisitor<GenericTreeWalker<0,1,0,0,1> >::WalkTree+0x1df [d:\coreclr\src\jit\compiler.h @ 9872]
...
...
```

Introduced by https://github.com/dotnet/coreclr/pull/12487. The failure goes away if I revert this commit. The new tree walker consumes more stack space.

### PR DESCRIPTION
**Pull request by pgavlin**
This local of type `CORINFO_CALL_INFO` bloats the frame size of its
caller when the function is inlined and ends up aggravating stack size
issues in deep recursion. This change refactors the offending method a
bit in order to avoid the local entirely.

Hopefully this fixes #12691.

### CODE REVIEW

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT Release r2r

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -18583,14 +18583,24 @@ bool Compiler::IsMathIntrinsic(GenTreePtr tree)
     return (tree->OperGet() == GT_INTRINSIC) && IsMathIntrinsic(tree->gtIntrinsic.gtIntrinsicId);
 }
 
+void Compiler::impDevirtualizeCall(GenTreeCall*            call,
```
Comment (mikedn) [inline src/jit/importer.cpp]: Do we really need this? Looks like it has only one call site.

File: src/jit/importer.cpp [hunk 2]
```diff
@@ -18612,9 +18622,16 @@ bool Compiler::IsMathIntrinsic(GenTreePtr tree)
 //
 void Compiler::impDevirtualizeCall(GenTreeCall*            call,
                                    GenTreePtr              thisObj,
-                                   CORINFO_CALL_INFO*      callInfo,
+                                   CORINFO_METHOD_HANDLE*  method,
+                                   unsigned*               methodAttribs,
```
Comment (mikedn) [inline src/jit/importer.cpp]: Why not `methodFlags` like it was in the struct?

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT Release r2r

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT Release r2r

**Comment by pgavlin** [comment]
> Since this is evidently a regression it would be good to understand that aspect better.

I agree. I think we can leave #12691 open for now to track.
