### PR TITLE
Fix check for memory containment safety.

### LINKED ISSUE #22556: Incorrect exception thrown when evaluating addition operands
This method
```
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int foo(Test t, int i)
    {
        int x = t.f + 1 / i;
        return x;
    }
```
should throw `NullReferenceException` when passed null, 0 (operands have to be evaluated left to right).

Instead it's currently throwing `DivideByZeroException`.

The generated code:

```
; Assembly listing for method Test:foo(ref,int):int
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; Tier-0 compilation
; compiler->opts.MinOpts() is true
; rbp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00    ] (  1,  1   )     ref  ->  [rbp+0x10]   class-hnd
;  V01 arg1         [V01    ] (  1,  1   )     int  ->  [rbp+0x18]
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M14944_IG01:
       55                   push     rbp
       488BEC               mov      rbp, rsp
       48894D10             mov      gword ptr [rbp+10H], rcx
       895518               mov      dword ptr [rbp+18H], edx

G_M14944_IG02:
       488B4D10             mov      rcx, gword ptr [rbp+10H]
       B801000000           mov      eax, 1
       99                   cdq
       F77D18               idiv     edx:eax, dword ptr [rbp+18H]
       034108               add      eax, dword ptr [rcx+8]

G_M14944_IG03:
       5D                   pop      rbp
       C3                   ret

; Total bytes of code 29, prolog size 4 for method Test:foo(ref,int):int
; ============================================================
```

### PR DESCRIPTION
**Pull request by erozenfeld**
This change ensures that if an operand can produce an exception
and any instructions executed after the operand evaluation but before
the operand's parent can also produce an exception, the operand
shouldn't be contained. The reason is that in this case operand
containment may reorder exceptions.

With `strict` set to true the containment is blocked here:
https://github.com/dotnet/coreclr/blob/d27fff3f65193dd71c6197e9876101f496bbd28b/src/jit/sideeffects.cpp#L485-L488

Fixes #22556.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@CarolEidt @dotnet/jit-contrib PTAL

**Comment by erozenfeld** [comment]
This causes a significant regression on framework assemblies (x64 pmi:
`Total bytes of diff: 170639 (0.46% of base)`
I'll try to find a way to mitigate.

**Comment by CarolEidt** [comment]
@erozenfeld - this seems pretty straightforward, i.e. we need to be setting `strict` to `true` here because we can't change the order of exceptions. Have you identified regressions that indicate that this is restricting containment where it should be safe?

**Comment by erozenfeld** [comment]
The reason for the regression is that this check now blocks containment unnecessarily.
https://github.com/dotnet/coreclr/blob/d27fff3f65193dd71c6197e9876101f496bbd28b/src/jit/sideeffects.cpp#L478-L482

For example, containment of `IND` is blocked for this tree because `IND` has GTF_ORDER_SIDEFF` set:

```
N006 (  3,  2) [000019] ------?-----              /--*  LCL_VAR   long   V03 tmp1         u:1 $141
N008 ( 17, 20) [000023] J----O?N----              *  EQ        int    $18a
N002 (  6,  4) [000022] n----O?-----              \--*  IND       long   $2c0
N001 (  3,  2) [000016] ------?-----                 \--*  LCL_VAR   ref    V04 tmp2         u:1 $80
```

**Comment by erozenfeld** [comment]
As far as I can tell all existing calls to InterferesWith pass false for `strict` argument. So perhaps we can simply remove the `GTF_ORDER_SIDEEFF` check above? I'll need to think about whether there are cases where `GTF_ORDER_SIDEEFF` should legitimately block containment.

**Comment by erozenfeld** [comment]
The diffs with `GTF_ORDER_SIDEEFF` check removed becomes much smaller:
`Total bytes of diff: 180 (0.00% of base)`

**Comment by mikedn** [comment]
How come `GTF_ORDER_SIDEEFF` has such a large impact? Usually it's associated with volatile and that shouldn't be a common occurrence.

**Comment by CarolEidt** [comment]
In this line:
```
if (((m_sideEffectFlags | otherSideEffectFlags) & GTF_ORDER_SIDEEFF) != 0)
```
Why is this an 'or'? It would seem that the ordering would only be an issue if *both* sides had order side effects. Am I missing something?

**Comment by erozenfeld** [comment]
@CarolEidt I believe the intended semantics of GTF_ORDER_SIDEEFF is that the instruction with that flag can't be moved at all. It doesn't depend on the presence of GTF_ORDER_SIDEEFF on other instructions.

@mikedn In addition to volatiles we set `GTF_ORDER_SIDEFF` in a few other places:
1. with catch args (this seems ok);
2. on nops that need to be kept around since they are referenced by the call (misuse of the flag but seems benign);
3. in early prop after determining `GT_NULLCHECK` nodes are unnecessary to prevent reordering with dominating derefs (these `GT_NULLCHECK` nodes are removed eventually, so this doesn't cause problems)
4. In assertion prop after discovering that GT_IND is non-faulting (this is what's causing the regressions).

The last place is what's causing the problem here: https://github.com/dotnet/coreclr/blob/4bda36ad1da00ea80578b0de2b18e26a9f56a573/src/jit/assertionprop.cpp#L3551
The fact that the instruction is non-faulting depends on another dominating `GT_IND` (that may fault). So we set `GTF_ORDER_SIDEFF` to ensure that the `GT_IND` instructions don't get reordered. The flag is still there in lower.

**Comment by erozenfeld** [comment]
Note that `GT_IND` instructions that we are protecting in assertionprop can be safely moved forward in the execution order (which containment does).  We are trying to protect them from backward movement (so that that they don't end up before instructions that created the non-null assertion) but are using the big hammer `GTF_ORDER_SIDEFF`.

**Comment by CarolEidt** [comment]
> the intended semantics of `GTF_ORDER_SIDEEFF` is that the instruction with that flag can't be moved at all. It doesn't depend on the presence of `GTF_ORDER_SIDEEFF` on other instructions.

This doesn't make sense to me. Ordering side effects should only matter relative to other things with ordering side effects. Otherwise, the reordering won't be visible.

**Comment by erozenfeld** [comment]
The main use of `GTF_ORDER_SIDEEFF` is supposed to be to ensure acquire semantics for volatile reads and release semantics for volatile writes. From ECMA-335:

```
A volatile read has “acquire semantics” meaning that the read is guaranteed to occur prior to any
references to memory that occur after the read instruction in the CIL instruction sequence. A
volatile write has “release semantics” meaning that the write is guaranteed to happen after any
memory references prior to the write instruction in the CIL instruction sequence.
A conforming implementation of the CLI shall guarantee this semantics of volatile operations. 
```
So for reads the ordering is with respect to all following instructions, for write the ordering is with respect to all preceding instrructions.

**Comment by erozenfeld** [comment]
To be more precise, the ordering is with respect to all following memory references (not necessarily volatile), for write the ordering is with respect to all preceding memory references (not necessarily volatile).

**Comment by CarolEidt** [comment]
> So for reads the ordering is with respect to all following instructions, for write the ordering is with respect to all preceding instrructions.

I think that's overly conservative. It should only be with respect to all (following/preceding) instructions with global side-effects.

**Comment by erozenfeld** [comment]
Yes, that sounds reasonable. I'll try to change the check in InterferesWith to only block movement of instructions with `GTF_ORDER_SIDEFEFF` over instructions with `GTF_GLOB_REF`.

**Comment by erozenfeld** [comment]
@CarolEidt I pushed an update. It removed the bulk of the regression. New jit-diff numbers:

```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit
Summary:
(Lower is better)
Total bytes of diff: 928 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
         168 : System.Data.Common.dasm (0.01% of base)
         127 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
          86 : System.Private.CoreLib.dasm (0.00% of base)
          72 : System.Text.Encoding.CodePages.dasm (0.10% of base)
          59 : System.Private.Xml.dasm (0.00% of base)
49 total files with size differences (0 improved, 49 regressed), 80 unchanged.
Top method regressions by size (bytes):
          81 ( 2.89% of base) : System.Data.Common.dasm - XMLDiffLoader:ReadOldRowData(ref,byref,byref,ref):int:this
          36 ( 2.84% of base) : System.Text.RegularExpressions.dasm - RegexInterpreter:FindFirstChar():bool:this (2 methods)
          32 (11.27% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - CallTreeNodeBase:CombineByIdSamples(ref,bool,double,bool):this
          24 ( 1.26% of base) : System.Text.Encoding.CodePages.dasm - ISO2022Encoding:GetBytesCP5022xJP(long,int,long,int,ref):int:this
          21 ( 2.40% of base) : System.Threading.Tasks.Dataflow.dasm - ObserversState:ProcessItemAsync(ref):ref:this
Top method regressions by size (percentage):
           3 (23.08% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - TraceModuleFile:get_ImageEnd():long:this
           2 (14.29% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - CallStackInfo:GetHashCode():int:this
           2 (14.29% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - PseudoStack:GetHashCode():int:this
           2 (13.33% of base) : Microsoft.DotNet.InternalAbstractions.dasm - HashCodeCombiner:get_CombinedHash():int:this
           2 (13.33% of base) : System.Private.CoreLib.dasm - Int64:GetHashCode():int:this
187 total methods with size differences (0 improved, 187 regressed), 193195 unchanged.
```

**Comment by erozenfeld** [comment]
@CarolEidt PTAL

File: src/jit/sideeffects.cpp [hunk 1]
```diff
@@ -450,7 +450,7 @@ void SideEffectSet::AddNode(Compiler* compiler, GenTree* node)
 //    Two side effect sets interfere under any of the following
 //    conditions:
 //    - If the analysis is strict, and:
-//        - Either set contains a compiler barrier, or
+//        - One set contains a compiler barrier and the other set contains a global reference, or
```
Comment (briansull) [inline src/jit/sideeffects.cpp]: I believe that when both sides are marked with GTF_ORDER_SIDEEFF you also cannot reorder.

So you should add a check for that as well.

Comment (briansull) [reply src/jit/sideeffects.cpp]: It is quite possible that all indirections that set GTF_ORDER_SIDEEFF also will set GTF_GLOB_REF

**Comment by erozenfeld** [comment]
When we use `GTF_ORDER_SIDEEFF` for volatiles we set `GTF_GLOB_REF` as well.
This place
https://github.com/dotnet/coreclr/blob/4bda36ad1da00ea80578b0de2b18e26a9f56a573/src/jit/assertionprop.cpp#L3551
is really problematic.

There are at least two issues there:
1. Setting of `GTF_ORDER_SIDEEFF` there is supposed to prevent reordering this node with the one that created the non-null assertion. But the node that created the non-null assertion may not have `GTF_GLOB_REF` (e.g., it may have `GTF_IND_INVARIANT` set or it may be-non-heap-pointing) nor `GTF_ORDER_SIDEEFF`.
2. The main reason these non-null assertions are used for indirections is to be able to delete dead indirections. Currently dead code removal checks `GTF_SIDE_EFFECT` so `GTF_ORDER_SIDEEFF` doesn't block dead code removal. And that's a problem because we are not supposed to remove volatile reads (see #18748).

I did run diffs with a check for both sides marked with `GTF_ORDER_SIDEEFF` and there was one additional diff. But it was for two unrelated indirections with `GTF_ORDER_SIDEEFF` added in assertion prop. That additional check won't solve the problems described above. It would be good to invent a different mechanism for dealing with dead indirections and use `GTF_ORDER_SIDEFF` just for volatiles.
