### PR TITLE
Fix HW intrinsic containment bugs

### LINKED ISSUE #23530: JIT HWIntrinsics: Bad codegen with contained loads
Using current master (including https://github.com/dotnet/coreclr/pull/23511) with the following test code:

```C#
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

class Program
{
    struct vec
    {
        public float f1;
        public float f2;
        public float f3;
        public float f4;
    }

    static unsafe float fmaTest()
    {
        vec a;
        var b = Vector128.Create(1f);
        var c = Vector128.Create(2f);
        var d = Vector128.Create(3f);

        c = Fma.MultiplyAdd(Sse.LoadVector128((float*)&a), b, c);

        return Sse.Add(c, d).ToScalar();
    }

    static void Main(string[] args)
    {
        Console.WriteLine(fmaTest());
    }
}
```

fmaTest compiles as

```asm
; Assembly listing for method Program:fmaTest():float
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 loc0         [V00    ] (  1,  1   )  struct (16) [rsp+0x08]   do-not-enreg[XS] must-init addr-exposed ld-addr-op
;  V01 loc1         [V01,T01] (  2,  2   )  simd16  ->  mm0
;  V02 loc2         [V02,T00] (  4,  4   )  simd16  ->  mm1
;* V03 loc3         [V03    ] (  0,  0   )  simd16  ->  zero-ref
;# V04 OutArgs      [V04    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;  V05 tmp1         [V05,T02] (  2,  2   )  simd16  ->  mm0         "Inline return value spill temp"
;  V06 tmp2         [V06,T03] (  2,  2   )  simd16  ->  mm0         "Inline stloc first use temp"
;  V07 tmp3         [V07,T04] (  2,  2   )  simd16  ->  mm1         "Inline return value spill temp"
;  V08 tmp4         [V08,T05] (  2,  2   )  simd16  ->  mm1         "Inline stloc first use temp"
;  V09 tmp5         [V09,T06] (  2,  2   )  simd16  ->  mm2         "Inline return value spill temp"
;  V10 tmp6         [V10,T07] (  2,  2   )  simd16  ->  mm2         "Inline stloc first use temp"
;
; Lcl frame size = 24

G_M51181_IG01:
       sub      rsp, 24
       vzeroupper
       xor      rax, rax
       mov      qword ptr [rsp+08H], rax
       mov      qword ptr [rsp+10H], rax

G_M51181_IG02:
       vmovss   xmm0, dword ptr [reloc @RWD00]
       vbroadcastss xmm0, xmm0
       vmovss   xmm1, dword ptr [reloc @RWD04]
       vbroadcastss xmm1, xmm1
       vmovss   xmm2, dword ptr [reloc @RWD08]
       vbroadcastss xmm2, xmm2
       vfmadd231ps xmm1, xmm0, xmmword ptr [0000H]
       vaddps   xmm0, xmm1, xmm2

G_M51181_IG03:
       add      rsp, 24
       ret

RWD00  dd       3F800000h
RWD04  dd       40000000h
RWD08  dd       40400000h

; Total bytes of code 77, prolog size 19 for method Program:fmaTest():float
; ============================================================
```

The contained address of `vec a` is coming out null.

Also of interest is that the broadcasts are still not using containment.

cc @CarolEidt

### LINKED ISSUE #23534: new failures in  JIT.HardwareIntrinsics
We have gotten a new set of failures after recent changes:
for example JIT_HardwareIntrinsics._X86_Bmi2_Bmi2_r_Bmi2_r_/_X86_Bmi2_Bmi2_r_Bmi2_r_sh fails with:
```
Ending test case at 03/28/2019 15:52:25
Beginning test case MultiplyNoFlags.UInt32.BinRes at 03/28/2019 15:52:25
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Expected: 100
Actual: 139
END EXECUTION - FAILED
```
[Other examples](https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F22963~2Fmerge/test~2Ffunctional~2Fcli~2F/20190328.736/workItem/JIT.HardwareIntrinsics)

cc @CarolEidt @tannergooding @dotnet/jit-contrib 

I am going to disable these tests to get a clean run in PRs.

### PR DESCRIPTION
**Pull request by CarolEidt**
For the Fma case (#23430), fix the handling of contained 3-operand HW intrinsic nodes.
For the Bmi case (#23534), fix a bad assert placement, and re-enable the Bmi tests.

Fix #23530
Fix #23534

### CODE REVIEW

**Comment by tannergooding** [comment]
Just as an FYI, @jkotas logged another bug for `MultiplyNoFlags` and resolved it as a dupe of 23534: https://github.com/dotnet/coreclr/issues/23546

File: src/jit/hwintrinsiccodegenxarch.cpp [hunk 1]
```diff
@@ -1044,39 +1044,47 @@ void CodeGen::genHWIntrinsic_R_R_R_RM(
 
             regSet.tmpRlsTemp(tmpDsc);
         }
-        else if (op3->OperIsHWIntrinsic())
+        else if (op3->isIndir() || op3->OperIsHWIntrinsic())
```
Comment (tannergooding) [inline src/jit/hwintrinsiccodegenxarch.cpp]: Are similar fixes needed for all the other `genHWIntrinsic_` code? Such as: https://github.com/dotnet/coreclr/blob/4ff4ef182e148b8924853aca3d49b80aa9cf926a/src/jit/hwintrinsiccodegenxarch.cpp#L435

Comment (CarolEidt) [reply src/jit/hwintrinsiccodegenxarch.cpp]: I suspect so. However, I will file a separate issue that includes extending the testing to include more containment cases.

File: tests/src/JIT/Regression/JitBlue/GitHub_23530/GitHub_23530.cs [hunk 2]
```diff
@@ -36,10 +36,13 @@ static unsafe float fmaTest()
 
         static int Main(string[] args)
         {
-            float result = fmaTest();
-            if (Math.Abs(result - 5.0F) > System.Single.Epsilon)
+            if (Fma.IsSupported)
             {
-                return -1;
+                float result = fmaTest();
+                if (Math.Abs(result - 5.0F) > System.Single.Epsilon)
```
Comment (tannergooding) [inline tests/src/JIT/Regression/JitBlue/GitHub_23530/GitHub_23530.cs]: I would say we can compare this against `Math.FusedMultiplyAdd` now; but that will get accelerated if `Fma.IsSupported` returns true

Comment (CarolEidt) [reply tests/src/JIT/Regression/JitBlue/GitHub_23530/GitHub_23530.cs]: I'd just as soon be explicit here

**Comment by CarolEidt** [comment]
@tannergooding @dotnet/jit-contrib PTAL

File: src/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (tannergooding) [reply src/jit/hwintrinsiccodegenxarch.cpp]: If it is just this same thing on all of them, I can address that and you can feel free to assign the issue to me.

File: tests/src/JIT/Regression/JitBlue/GitHub_23530/GitHub_23530.cs (hunk 2 above)
Comment (tannergooding) [reply tests/src/JIT/Regression/JitBlue/GitHub_23530/GitHub_23530.cs]: If you are wanting to be explicit, then this result should be deterministic and you shouldn't need anything more than `result != 5.0f`.

If this isn't deterministic, then we have other problems 😄

File: src/jit/hwintrinsiccodegenxarch.cpp (hunk 1 above)
Comment (CarolEidt) [reply src/jit/hwintrinsiccodegenxarch.cpp]: Right - it would be just the same, but I don't want to introduce the code without a test to verify it (plus I thought it would be prudent to do it separately, to keep this focused on fixing the existing failures).

**Comment by CarolEidt** [comment]
@dotnet-bot test Windows_NT x64 min_opt ryujit CoreCLR Perf Tests Correctness

File: tests/issues.targets [hunk 3]
```diff
@@ -74,18 +74,6 @@
...
-        <ExcludeList Include="$(XunitTestBinBase)/JIT/HardwareIntrinsics/X86/Bmi2/**">
-            <Issue>23534</Issue>
-        </ExcludeList>
-        <ExcludeList Include="$(XunitTestBinBase)/JIT/HardwareIntrinsics/X86/Bmi2.X64/**">
-            <Issue>23534</Issue>
-        </ExcludeList>
-        <ExcludeList Include="$(XunitTestBinBase)/JIT/HardwareIntrinsics/X86/Regression/GitHub_21899/**">
-            <Issue>23534</Issue>
-        </ExcludeList>
-        <ExcludeList Include="$(XunitTestBinBase)/JIT/Methodical/flowgraph/dev10_bug679955/volatileLocal1/*">
```
Comment (sandreenko) [inline tests/issues.targets]: You deleted the exclusion for the test that you have not fixed. #23545 is still open.

Comment (CarolEidt) [reply tests/issues.targets]: Yes, bad/mindless merge. I've pushed a PR to re-exclude it.
