### PR TITLE
[RyuJIT/ARM][LSRA] Update register mask for GC helper

### LINKED ISSUE #11784: [RyuJIT/arm32] Assertion failed 'genIsValidDoubleReg(regRec->regNum)'
```
$ COMPlus_AltJit=C:Test \
gdb --args clr-debug/corerun \
tests-release/JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376/DevDiv_278376.exe
...
#9  0xb0c6c1cc in assertAbort (why=0xb0f19a8e "genIsValidDoubleReg(regRec->regNum)", file=0xb0f17ed3 "/home/mskvortsov/git/coreclr/src/jit/lsra.cpp", line=6334) at /home/mskvortsov/git/coreclr/src/jit/error.cpp:287
#10 0xb0d37abc in LinearScan::unassignPhysReg (this=0x9cec0, regRec=0x9d270, spillRefPosition=0xa025c) at /home/mskvortsov/git/coreclr/src/jit/lsra.cpp:6334
#11 0xb0d3046e in LinearScan::allocateRegisters (this=0x9cec0) at /home/mskvortsov/git/coreclr/src/jit/lsra.cpp:7413
#12 0xb0d2d990 in LinearScan::doLinearScan (this=0x9cec0) at /home/mskvortsov/git/coreclr/src/jit/lsra.cpp:1773
```
```
JIT/jit64/hfa/main/testA/hfa_nd2A_d
JIT/jit64/hfa/main/testA/hfa_nd2A_r
JIT/jit64/hfa/main/testA/hfa_sd2A_d
JIT/jit64/hfa/main/testA/hfa_sd2A_r
JIT/jit64/hfa/main/testB/hfa_nd2B_d
JIT/jit64/hfa/main/testB/hfa_nd2B_r
JIT/jit64/hfa/main/testB/hfa_sd2B_d
JIT/jit64/hfa/main/testB/hfa_sd2B_r
JIT/jit64/hfa/main/testC/hfa_nd2C_d
JIT/jit64/hfa/main/testC/hfa_nd2C_r
JIT/jit64/hfa/main/testC/hfa_sd2C_d
JIT/jit64/hfa/main/testC/hfa_sd2C_r
JIT/jit64/hfa/main/testG/hfa_nd2G_d
JIT/jit64/hfa/main/testG/hfa_nd2G_r
JIT/jit64/hfa/main/testG/hfa_sd2G_d
JIT/jit64/hfa/main/testG/hfa_sd2G_r
JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376
JIT/Regression/VS-ia64-JIT/V1.2-M02/b108129/b108129
```

cc @dotnet/arm32-contrib

### PR DESCRIPTION
**Pull request by hqueue**
CORINFO_HELP_STOP_FOR_GC helper preserves integer and double return register.

Fix #11784 

This removes `Assertion failed 'genIsValidDoubleReg(regRec->regNum)'` from following tests.
```
JIT/jit64/hfa/main/testA/hfa_nd2A_d
JIT/jit64/hfa/main/testA/hfa_nd2A_r
JIT/jit64/hfa/main/testA/hfa_sd2A_d
JIT/jit64/hfa/main/testA/hfa_sd2A_r
JIT/jit64/hfa/main/testB/hfa_nd2B_d
JIT/jit64/hfa/main/testB/hfa_nd2B_r
JIT/jit64/hfa/main/testB/hfa_sd2B_d
JIT/jit64/hfa/main/testB/hfa_sd2B_r
JIT/jit64/hfa/main/testC/hfa_nd2C_d
JIT/jit64/hfa/main/testC/hfa_nd2C_r
JIT/jit64/hfa/main/testC/hfa_sd2C_d
JIT/jit64/hfa/main/testC/hfa_sd2C_r
JIT/jit64/hfa/main/testG/hfa_nd2G_d
JIT/jit64/hfa/main/testG/hfa_nd2G_r
JIT/jit64/hfa/main/testG/hfa_sd2G_d
JIT/jit64/hfa/main/testG/hfa_sd2G_r
JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376
JIT/Regression/VS-ia64-JIT/V1.2-M02/b108129/b108129
```

## Example

With `COMPlus_AltJit=C:Test` option, `JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376`

### Before
```
FAILED   - [   0][   2s]JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376/DevDiv_278376.sh
               BEGIN EXECUTION
               /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170523.checked/corerun DevDiv_278376.exe
               
               Assert failure(PID 25738 [0x0000648a], Thread: 25738 [0x648a]): Assertion failed 'genIsValidDoubleReg(regRec->regNum)' in 'C:Test(bool):int' (IL size 17)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 6334
                   Image: /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170523.checked/corerun
               
               ./DevDiv_278376.sh: line 240: 25738 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

### After
```
PASSED   - [   0][   2s]JIT/Regression/JitBlue/DevDiv_278376/DevDiv_278376/DevDiv_278376.sh
               BEGIN EXECUTION
               /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170523.checked.working/corerun DevDiv_278376.exe
               Expected: 100
               Actual: 100
               END EXECUTION - PASSED
```

### CODE REVIEW

**Comment by hqueue** [comment]
@dotnet-bot test Ubuntu x64 Checked Build and Test

File: src/jit/target.h [hunk 1]
```diff
@@ -1440,7 +1440,7 @@ typedef unsigned short regPairNoSmall; // arm: need 12 bits
 
   // The registers trashed by the CORINFO_HELP_STOP_FOR_GC helper
   // See vm\arm\amshelpers.asm for more details.
-  #define RBM_STOP_FOR_GC_TRASH     (RBM_CALLEE_TRASH & ~(RBM_FLOATRET | RBM_INTRET))
+  #define RBM_STOP_FOR_GC_TRASH     (RBM_CALLEE_TRASH & ~(RBM_DOUBLERET | RBM_INTRET))
```
Comment (CarolEidt) [inline src/jit/target.h]: Looking at vm\arm\amshelpers.asm, it appears that `JIT_RareDisableHelper` preserves d0-d3. I'm not sure whether that translates to our f0-f3, or whether that is actually f0-f7, but in any case this doesn't seem consistent with that.
Also, even though the above comment is the same as for the other architectures, it would have eased my search if it said:
```
// The registers trashed by the CORINFO_HELP_STOP_FOR_GC helper (JIT_RareDisableHelper).
// See vm\arm\amshelpers.asm for more details.
```
since otherwise one has to search for the mapping from the `CORINFO` define to the actual helper name.

Comment (hqueue) [inline src/jit/target.h]: > Looking at vm\arm\amshelpers.asm, it appears that JIT_RareDisableHelper preserves d0-d3. I'm not sure whether that translates to our f0-f3, or whether that is actually f0-f7, but in any case this doesn't seem consistent with that.

Yes, and `JIT_RareDisableHelper` defined in asmhelpers.S also preserves d0-d3 as below.
https://github.com/dotnet/coreclr/blob/master/src/vm/arm/asmhelpers.S#L1013-L1031

> I'm not sure whether that translates to our f0-f3, or whether that is actually f0-f7, but in any case this doesn't seem consistent with that.

Are you suggesting that we had better exclude all d0-d3 from `RBM_STOP_FOR_GC_TRASH` ?

> Also, even though the above comment is the same as for the other architectures, it would have eased my search if it said:

Sure, I will update the comment :)
Frankly speaking, I also had searched for the function.

Comment (CarolEidt) [inline src/jit/target.h]: > Are you suggesting that we had better exclude all d0-d3 from RBM_STOP_FOR_GC_TRASH ?

I'm not sure whether it's best to do that, or to avoid having to push and pop them all in `JIT_RareDisableHelper`. But it seems that they should be consistent.

Comment (hqueue) [inline src/jit/target.h]: > I'm not sure whether it's best to do that, or to avoid having to push and pop them all in JIT_RareDisableHelper. But it seems that they should be consistent.

Right, we should keep consistency.
I will take a look again.

BTW I think this decision may affect overall code quality, i.e. size of code (caller vs. callee),  performance (caller-saves vs. callee-saves) and etc.

Comment (hqueue) [inline src/jit/target.h]: I found that there is a comment about preserving registers at https://github.com/dotnet/coreclr/blob/master/src/vm/jithelpers.cpp#L5915-L5916.

```C++
#if defined(_TARGET_ARM_) || defined(_TARGET_AMD64_)
// The JIT expects this helper to preserve the return value on AMD64 and ARM. We should eventually
// switch other platforms to the same convention since it produces smaller code.
extern "C" FCDECL0(VOID, JIT_RareDisableHelper);
extern "C" FCDECL0(VOID, JIT_RareDisableHelperWorker);

HCIMPL0(void, JIT_RareDisableHelperWorker)
#else
HCIMPL0(void, JIT_RareDisableHelper)
#endif
```
Therefore I decide to keep `JIT_RareDisableHelper` as is and update RMB_STOP_FOR_GC_TRASH to exclude all registers preserved by helper function.

Comment (CarolEidt) [inline src/jit/target.h]: Thanks for taking the time to look into this!
