### PR TITLE
Fix step with stackalloc

### LINKED ISSUE #14926: Debugging a stackalloc line takes multiple F10s
I’ve been debugging some code that looks like:

```C#
float *ptr = stackalloc float[10];

Span<float> span1 = stackalloc float[20];
span1[0] = 9.5f;
span1[1] = 8.5f;
span1[2] = 7.5f;
span1[3] = 6.5f;

Span<float> span2 = stackalloc float[4];
span2[0] = .5f;
span2[1] = 10.5f;
span2[2] = 10.5f;
span2[3] = 10.5f;
```

When debugging, it is taking multiple “F10”s in the debugger to get over the stackalloc lines.  I’ve noticed that it grows as the more memory is alloc’d.  But even in the small case (alloc’ing 1 element), it still takes roughly 5 times of hitting “F10” to get past the line.

I’m using:
- .Net Core 2.1.0-preview1-25907-02
- Microsoft Visual Studio Enterprise 2017 Int Preview (2)
  - Version 15.5.0 Preview 4.0 [27106.0.d15rel]
  - VisualStudio.15.IntPreview/15.5.0-pre.4.0+27106.0.d15rel

/cc @AndyAyersMS @mikem8361 @VSadov @stephentoub

### PR DESCRIPTION
**Pull request by sdmaclea**
Generalize handling of stackalloc. Funclets were just a special case of an in function stack allocation.

Currently includes 5 commits
1. Non functional change to make mReturnFrame private. This prepares for further commits.
2. Add ability to get the return frame for the root managed method.  This is not a functional change (yet)
3. Revise IsRangeAppropriate to use the return frames SP to determine if we are in the same frame.
4. Typos
5. Fix a bug in the argument handling in the GetFunctionFromToken() API.  This fixes a hang which blocked testing.

Fixes #14926
This is a safer alternative to #26688

/cc @dotnet/dotnet-diag

### CODE REVIEW

File: src/debug/ee/controller.cpp [hunk 1]
```diff
@@ -5121,40 +5115,23 @@ bool DebuggerStepper::IsRangeAppropriate(ControllerStackInfo *info)
...
     // 2)  We initiate a step in a funclet but end up stepping out to the parent method or a funclet closer to the root.
     //      a) end up in the parent method
     //      b) end up in a funclet
+    // 3)  We initiate a step and then change stack allocation within the method or funclet
     // In both cases the range of the stepper should still be appropriate.
 
     bool fValidParentMethodFP = (m_fpParentMethod != LEAF_MOST_FRAME);
 
-    if (fActiveFrameIsFunclet)
+    // All scenaris have the same condition
```
Comment (cshung) [inline src/debug/ee/controller.cpp]: NIT: Typo (scenaris  -> scenarios)

**Comment by sdmaclea** [comment]
> In regards to 3.1, my guess is that shiproom won't take this unless you have evidence that this issue will be dramatically more prevalent+painful than it appears

FYI /cc @davidfowl
