### PR TITLE
Fix lowering's containment analysis.

### LINKED ISSUE #7380: RyuJIT: incorrect code motion when making operands contained.
This is a silent bad code generation issue that arose during internal testing. The original repro is a test failure under `COMPlus_JitStress=2`. Due to explicit null check insertion, we (eventually) end up with the following LIR:

```
N001 (  3,  2) [006096] -------N----     t6096 =    lclVar    ref    V86 cse10         <l:$4ad, c:$1b5>

                                                 /--*  t6096  ref    
N003 (  3,  3) [002716] DA--G-------             *  st.lclVar ref    V41 tmp29        d:26

N004 (  1,  1) [002733] ------------     t2733 =    lclVar    ref    V41 tmp29        u:26 <l:$4ad, c:$1b5>

                                                 /--*  t2733  ref    
N005 (  2,  2) [002732] ---X---N----             *  nullcheck byte   <l:$4b8, c:$58a>

N007 (  1,  1) [002736] ------------     t2736 =    lclVar    ref    V41 tmp29        u:26 (last use) <l:$4ad, c:$1b5>

N008 (  1,  1) [002737] ------------     t2737 =    const     long   20 field offset Fseq[y] $107

                                                 /--*  t2736  ref    
                                                 +--*  t2737  long   
N009 (  2,  2) [002735] -------N----     t2735 = *  +         byref  <l:$2ad, c:$2ac>

N012 (  3,  2) [006081] -------N----     t6081 =    lclVar    ref    V83 cse7          <l:$4bd, c:$1b7>

                                                 /--*  t6081  ref    
N014 (  3,  3) [002741] DA--G-------             *  st.lclVar ref    V41 tmp29        d:27

N015 (  1,  1) [002762] ------------     t2762 =    lclVar    ref    V41 tmp29        u:27 <l:$4bd, c:$1b7>

                                                 /--*  t2762  ref    
N016 (  2,  2) [002761] ---X---N----             *  nullcheck byte   <l:$583, c:$58f>

N018 (  1,  1) [002765] ------------     t2765 =    lclVar    ref    V41 tmp29        u:27 (last use) <l:$4bd, c:$1b7>

N019 (  1,  1) [002766] ------------     t2766 =    const     long   20 field offset Fseq[y] $107

                                                 /--*  t2765  ref    
                                                 +--*  t2766  long   
N020 (  2,  2) [002764] -------N----     t2764 = *  +         byref  <l:$2af, c:$2ae>

                                                 /--*  t2764  byref  
N021 (  4,  4) [002763] -A--GO------     t2763 = *  indir     int    <l:$54e, c:$1ed>

N023 (  3,  2) [002767] ----G-------     t2767 =    lclVar    int   (AX) V07 loc4          $1ee

                                                 /--*  t2763  int    
                                                 +--*  t2767  int    
N024 ( 13, 12) [002738] -A-XGO------     t2738 = *  +         int    <l:$554, c:$553>

                                                 /--*  t2735  byref  
                                                 +--*  t2738  int    
               [006238] -A-XGO------             *  storeIndir int   
```

During lowering, we attempt to form an RMW add rooted at the final `storeIndir`. The pattern matching that attempts to form RMW operations, however, does not consider whether or not it is safe to perform the code motion involved in making the destination and source addresses for the operator contained. In this case, lowering moves the evaluation of the address (i.e. the dataflow tree rooted at the add that produces `t2735`) into the `storeIndir`. This moves a use of `tmp29` across a def of the same and causes the program to store a value to an incorrect address.

There are many variations on this pattern. For example, given the following C#:

```
static int T(C[] a, C c)
{
    return a.Length != c.M() ? 100 : 0;
}
```

The evaluation of `a.Length` (including the necessary null check) should occur before the call to `c.M()`. The lack of correct checks for safe code motion that caused the original repro, however, cause the JIT to generate bad code in this case as well: the null check for `a` is folded into the load of `a.Length`, which is then made contained by the compare. This results in the call to `c.M()` executing before the null check. This causes the program to behave incorrectly in the case that `a` is null.

### PR DESCRIPTION
**Pull request by pgavlin**
This fixes a silent bad code generation issue that arose during internal testing. The original repro is a test failure under COMPlus_JitStress=2. Due to explicit null check insertion, we (eventually) end up with the following LIR:

```
N001 (  3,  2) [006096] -------N----     t6096 =    lclVar    ref    V86 cse10         <l:$4ad, c:$1b5>

                                                 /--*  t6096  ref    
N003 (  3,  3) [002716] DA--G-------             *  st.lclVar ref    V41 tmp29        d:26

N004 (  1,  1) [002733] ------------     t2733 =    lclVar    ref    V41 tmp29        u:26 <l:$4ad, c:$1b5>

                                                 /--*  t2733  ref    
N005 (  2,  2) [002732] ---X---N----             *  nullcheck byte   <l:$4b8, c:$58a>

N007 (  1,  1) [002736] ------------     t2736 =    lclVar    ref    V41 tmp29        u:26 (last use) <l:$4ad, c:$1b5>

N008 (  1,  1) [002737] ------------     t2737 =    const     long   20 field offset Fseq[y] $107

                                                 /--*  t2736  ref    
                                                 +--*  t2737  long   
N009 (  2,  2) [002735] -------N----     t2735 = *  +         byref  <l:$2ad, c:$2ac>

N012 (  3,  2) [006081] -------N----     t6081 =    lclVar    ref    V83 cse7          <l:$4bd, c:$1b7>

                                                 /--*  t6081  ref    
N014 (  3,  3) [002741] DA--G-------             *  st.lclVar ref    V41 tmp29        d:27

N015 (  1,  1) [002762] ------------     t2762 =    lclVar    ref    V41 tmp29        u:27 <l:$4bd, c:$1b7>

                                                 /--*  t2762  ref    
N016 (  2,  2) [002761] ---X---N----             *  nullcheck byte   <l:$583, c:$58f>

N018 (  1,  1) [002765] ------------     t2765 =    lclVar    ref    V41 tmp29        u:27 (last use) <l:$4bd, c:$1b7>

N019 (  1,  1) [002766] ------------     t2766 =    const     long   20 field offset Fseq[y] $107

                                                 /--*  t2765  ref    
                                                 +--*  t2766  long   
N020 (  2,  2) [002764] -------N----     t2764 = *  +         byref  <l:$2af, c:$2ae>

                                                 /--*  t2764  byref  
N021 (  4,  4) [002763] -A--GO------     t2763 = *  indir     int    <l:$54e, c:$1ed>

N023 (  3,  2) [002767] ----G-------     t2767 =    lclVar    int   (AX) V07 loc4          $1ee

                                                 /--*  t2763  int    
                                                 +--*  t2767  int    
N024 ( 13, 12) [002738] -A-XGO------     t2738 = *  +         int    <l:$554, c:$553>

                                                 /--*  t2735  byref  
                                                 +--*  t2738  int    
               [006238] -A-XGO------             *  storeIndir int 
```
  
During lowering, we attempt to form an RMW add rooted at the final storeIndir. The pattern matching that attempts to form RMW operations, however, does not consider whether or not it is safe to perform the code motion involved in making the destination and source addresses for the operator contained. In this case, lowering moves the evaluation of the address (i.e. the dataflow tree rooted at the add that produces t2735) into the storeIndir. This moves a use of tmp29 across a def of the same and causes the program to store a value to an incorrect address.

There are many variations on this pattern. For example, given the following C#:

```
static int T(C[] a, C c)
{
    return a.Length != c.M() ? 100 : 0;
}
```

The evaluation of a.Length (including the necessary null check) should occur before the call to c.M(). The lack of correct checks for safe code motion that caused the original repro, however, cause the JIT to generate bad code in this case as well: the null check for a is folded into the load of a.Length, which is then made contained by the compare. This results in the call to c.M() executing before the null check. This causes the program to behave incorrectly in the case that a is null.

In order to fix the code motion analysis, this change introduces a new type, `SideEffectSet`, that can be used to summarize the side effects of a set of nodes and check whether or not they interfere with another set of side effects. This change then uses the new type to ensure that it is safe to perform the code motion necessary to make an operand contained before doing so.

Fixes #7380.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @BruceForstall @dotnet/jit-contrib PTAL

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT corefx_baseline
@dotnet-bot test Ubuntu jitstressregs1
@dotnet-bot test Ubuntu jitstressregs2
@dotnet-bot test Ubuntu jitstressregs3
@dotnet-bot test Ubuntu jitstressregs4
@dotnet-bot test Ubuntu jitstressregs8
@dotnet-bot test Ubuntu jitstressregs0x10
@dotnet-bot test Ubuntu jitstressregs0x80
@dotnet-bot test Ubuntu jitstress2
@dotnet-bot test Ubuntu corefx_baseline

**Comment by pgavlin** [comment]
@dotnet-bot test this please

File: src/jit/emitxarch.cpp [hunk 1]
```diff
@@ -9929,7 +9929,7 @@ BYTE* emitter::emitOutputRI(BYTE* dst, instrDesc* id)
                 break;
 
             case IF_RRW_CNS:
-                assert(id->idGCref() == GCT_BYREF);
+                assert((id->idGCref() == GCT_BYREF) || (id->idGCref() == GCT_GCREF));
```
Comment (briansull) [inline src/jit/emitxarch.cpp]: What is the reason (or test case) for allow a GCREF here?

This is an instruction that is doing a Read/Write/Modify operation using a constant right?
Such an operation wouldn't typically produce a GCREF.

File: src/jit/gentree.cpp [hunk 2]
```diff
@@ -1791,6 +1791,11 @@ regMaskTP GenTreeCall::GetOtherRegMask() const
     return resultMask;
 }
 
+bool GenTreeCall::IsPure(Compiler* compiler) const
+{
```
Comment (briansull) [inline src/jit/gentree.cpp]: Should this be called IsPureHelper instead?
Someday we could determine if a Jitted method being called is Pure

Comment (pgavlin) [inline src/jit/gentree.cpp]: > Someday we could determine if a Jitted method being called is Pure

That's why I named the method `IsPure`: if we ever gain the ability to decide whether or not an arbitrary method is pure, we can add that logic to this method.

Comment (briansull) [inline src/jit/gentree.cpp]: Needs a method header as well

File: src/jit/lower.h [hunk 3]
```diff
@@ -269,9 +270,10 @@ class Lowering : public Phase
         return LIR::AsRange(m_block);
     }
 
-    LinearScan* m_lsra;
-    unsigned    vtableCallTemp; // local variable we use as a temp for vtable calls
-    BasicBlock* m_block;
+    LinearScan*   m_lsra;
+    unsigned      vtableCallTemp; // local variable we use as a temp for vtable calls
+    SideEffectSet scratchSideEffects; // SideEffectSet used for IsSafeToContainMem and isRMWIndirCandidate
```
Comment (briansull) [inline src/jit/lower.h]: The new variables should be prefixed with `m_` to make it clear that they are instance members.

File: src/jit/lower.cpp [hunk 4]
```diff
@@ -86,26 +87,13 @@ bool Lowering::CheckImmedAndMakeContained(GenTree* parentNode, GenTree* childNod
 //
 bool Lowering::IsSafeToContainMem(GenTree* parentNode, GenTree* childNode)
 {
-    assert(parentNode->OperIsBinary());
-    assert(childNode->isMemoryOp());
```
Comment (briansull) [inline src/jit/lower.cpp]: Are these two asserts no longer important or valid?

File: src/jit/lower.h (hunk 3 above)
Comment (pgavlin) [inline src/jit/lower.h]: Good catch.

File: src/jit/lower.cpp (hunk 4 above)
Comment (pgavlin) [inline src/jit/lower.cpp]: Correct; they are neither.

File: src/jit/lower.cpp [hunk 5]
```diff
@@ -3262,11 +3250,39 @@ void Lowering::AddrModeCleanupHelper(GenTreeAddrMode* addrMode, GenTree* node)
...
+        {
+            indexSideEffects.AddNode(comp, index);
+        }
+        else
+        {
+            index = nullptr;
+        }
+    }
+
+    for (GenTree* cursor = addr; ; cursor = cursor->gtPrev)
```
Comment (briansull) [inline src/jit/lower.cpp]: A block comment describing the algorithm and the use and range of cursor. is needed here.

File: src/jit/hashbv.cpp [hunk 6]
```diff
@@ -1234,6 +1247,47 @@ class CompareAction
...
+    static inline void BothPresent(hashBv* lhs, hashBvNode**& l, hashBvNode*& r, bool& result, bool& terminate)
+    {
+        if ((*l)->Intersects(r))
+        {
+            terminate = true;
+            result    = true;
+        }
+    }
+    static inline void LeftEmpty(hashBv* lhs, hashBvNode**& l, hashBvNode*& r, bool& result, bool& terminate)
+    {
```
Comment (briansull) [inline src/jit/hashbv.cpp]: Where are these new method being use?

LeftGap, RightGap, BothPresent and LeftEmpty?

Comment (pgavlin) [inline src/jit/hashbv.cpp]: https://github.com/dotnet/coreclr/pull/7368/files/388f064ccbef11a52de3294c4fcbefd9005db547#diff-c6fe48698493e222ef59fdb87cfb9b3eR1564

File: src/jit/gentree.cpp (hunk 2 above)
Comment (CarolEidt) [inline src/jit/gentree.cpp]: The to-be-written method header should describe what we mean here by Pure (and possibly mention that it is the definition shared by the HelperCallProperties).

---
In reply to: [80796498](https://github.com/dotnet/coreclr/pull/7368#discussion_r80796498) [](ancestors = 80796498)

File: src/jit/lower.cpp [hunk 7]
```diff
@@ -23,6 +23,7 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 
 #ifndef LEGACY_BACKEND // This file is ONLY used for the RyuJIT backend that uses the linear scan register allocator
 
+#include "sideeffects.h"
 #include "lower.h"
```
Comment (BruceForstall) [inline src/jit/lower.cpp]: IMO, you should have this `#include` in lower.h, instead of spreading it around to all the cpp files that happen to include lower.h

File: src/jit/codegenarm.cpp [hunk 8]
```diff
@@ -19,6 +19,7 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 
 #ifdef _TARGET_ARM_
 #include "codegen.h"
+#include "sideeffects.h"
```
Comment (CarolEidt) [inline src/jit/codegenarm.cpp]: Why is this included here? If it is a dependency of one of the other include files, shouldn't it be included there?

File: src/jit/hashbv.cpp [hunk 9]
```diff
@@ -289,6 +289,19 @@ elemType hashBvNode::SubtractWithChange(hashBvNode* other)
     return result;
 }
 
+bool hashBvNode::Intersects(hashBvNode* other)
+{
+    for (int i = 0; i < this->numElements(); i++)
+    {
+        if (this->elements[i] & other->elements[i])
```
Comment (CarolEidt) [inline src/jit/hashbv.cpp]: The result of an `&` should be compared against 0.

File: src/jit/sideeffects.h [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+    void Add(Compiler* compiler, unsigned lclNum);
+    bool Intersects(const LclVarSet& other) const;
+    void Clear();
+};
+
+//------------------------------------------------------------------------
+// AliasSet:
+//    Represents a set of reads and writes for the purposes of alias
+//    analysis. This type partitions storage into a two categories:
+//    lclVars and addressable locations. The definition of the former is
```
Comment (BruceForstall) [inline src/jit/sideeffects.h]: nit: grammar: remove "a": "into a two"

File: src/jit/sideeffects.h [hunk 11]
```diff
@@ -0,0 +1,89 @@
...
+
+//------------------------------------------------------------------------
+// SideEffectSet:
+//    Represents a set of side effects for the purposes of analyzing code
+//    motion.
+//
+class SideEffectSet final
+{
+    unsigned m_sideEffectFlags;
+    AliasSet m_aliasSet;
```
Comment (BruceForstall) [inline src/jit/sideeffects.h]: It would be useful to comment all the members, but in particular: comment what set of values can be in m_sideEffectFlags

File: src/jit/lower.cpp [hunk 12]
```diff
@@ -86,26 +87,13 @@ bool Lowering::CheckImmedAndMakeContained(GenTree* parentNode, GenTree* childNod
...
-    assert(childNode->isMemoryOp());
+    scratchSideEffects.Clear();
+    scratchSideEffects.AddNode(comp, childNode);
 
-    unsigned int childFlags = (childNode->gtFlags & GTF_ALL_EFFECT);
-
-    GenTree* node;
-    for (node = childNode; node != parentNode; node = node->gtNext)
+    for (GenTree* node = childNode->gtNext; node != parentNode; node = node->gtNext)
     {
```
Comment (BruceForstall) [inline src/jit/lower.cpp]: Is this a hot loop? If so, we'll be constructing/destructing lots of SideEffectSet.

File: src/jit/lowerxarch.cpp [hunk 13]
```diff
@@ -3674,6 +3756,28 @@ bool Lowering::IsRMWMemOpRootedAtStoreInd(GenTreePtr tree, GenTreePtr* outIndirC
         return false;
     }
 
+    // At the point we can match one of two patterns:
```
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: "At this point"?

**Comment by BruceForstall** [comment]
What kind of diffs do you see?

File: src/jit/lowerxarch.cpp [hunk 14]
```diff
@@ -3521,6 +3522,87 @@ void Lowering::LowerCast(GenTree* tree)
 }
 
 //----------------------------------------------------------------------------------------------
+// Lowering::IsRMWIndirCandidate:
+//    Returns true if the given operand is a candidate indirection for a read-memory-write
```
Comment (BruceForstall) [inline src/jit/lowerxarch.cpp]: >read-memory-write [](start = 73, length = 17)

"read-memory-write" => read-modify-write, to be consistent with other uses?

Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Whoops--yeah.

**Comment by pgavlin** [comment]
Here is one example:

```udiff
--- fx\base\01dd21d1e01ab70b51c15aea46624e887ddf0e5d    Tue Sep 27 13:39:10 2016
+++ fx\diff\01dd21d1e01ab70b51c15aea46624e887ddf0e5d    Tue Sep 27 13:39:20 2016
@@ -230,8 +230,9 @@
        test     rcx, rcx
        je       SHORT G_M63061_IG22
-       mov      rsi, gword ptr [rbp-58H]
+       mov      rcx, gword ptr [rbp-58H]
+       mov      esi, dword ptr [rcx+8]
        mov      rcx, gword ptr [rbp-50H]
        call     hackishModuleName:hackishMethodName()
-       cmp      dword ptr [rsi+8], eax
+       cmp      esi, eax
        jge      SHORT G_M63061_IG22
```

In this case, the JIT used to incorrectly move an indirection across a call by making it contained in the compare. With these changes, the indirection instead happens before the call.

Here is an example of a seperate kind of diff:
```udiff
--- fx\base\08a799cebfa2c9377d88112f14ee0e1c8d6b5b0e    Tue Sep 27 13:39:09 2016
+++ fx\diff\08a799cebfa2c9377d88112f14ee0e1c8d6b5b0e    Tue Sep 27 13:39:20 2016
@@ -42,6 +42,6 @@
        mov      rdx, gword ptr [rsi+16]
        mov      eax, dword ptr [rsi+292]
-       add      eax, dword ptr [rsi+296]
-       inc      eax
+       mov      r8d, dword ptr [rsi+296]
+       lea      eax, [rax+r8+1]
        cmp      eax, dword ptr [rdx+8]
        jae      G_M65468_IG07
```

In this case, the JIT used to miss an opportunity for an address mode because its analysis of whether or not two nodes interfere was incorrect (it always considered one node a read and one a write, even if both were simply reads). There are a number of diffs of this sort; here's another example:
```udiff
--- fx\base\348cab4778d6c7ff0ad7a8e8c6b500aca1f116b7    Tue Sep 27 13:39:10 2016
+++ fx\diff\348cab4778d6c7ff0ad7a8e8c6b500aca1f116b7    Tue Sep 27 13:39:20 2016
@@ -34,8 +34,7 @@
 G_M62804_IG02:
        mov      rcx, gword ptr [rsi+8]
+       mov      edx, dword ptr [rsi+16]
        mov      ebp, dword ptr [rdi+8]
-       mov      edx, ebp
-       add      edx, dword ptr [rsi+16]
-       dec      edx
+       lea      edx, [rdx+rbp-1]
        mov      eax, dword ptr [rcx]
        call     hackishModuleName:hackishMethodName()
```

Note that these are all taken from an internal SPMI run. I'm still working on gathering diffs using the OSS utils.

**Comment by pgavlin** [comment]
The CoreFX tests are known to fail. I'll fix the formatting once I have some more feedback in hand.

File: src/jit/codegenarm.cpp (hunk 8 above)
Comment (pgavlin) [inline src/jit/codegenarm.cpp]: Personally, I feel that headers should not include their dependencies, as it makes discovering which headers are actually necessary for a particular source file more difficult. However, I think I've been outvoted on this one :)

File: src/jit/gentree.cpp (hunk 2 above)
Comment (pgavlin) [inline src/jit/gentree.cpp]: Done.

File: src/jit/hashbv.cpp (hunk 9 above)
Comment (pgavlin) [inline src/jit/hashbv.cpp]: Done.

File: src/jit/lower.cpp (hunk 12 above)
Comment (pgavlin) [inline src/jit/lower.cpp]: Lifted the definition out of the loop.

File: src/jit/lower.cpp (hunk 5 above)
Comment (pgavlin) [inline src/jit/lower.cpp]: These elements are described in the method's header comment.

File: src/jit/lowerxarch.cpp (hunk 13 above)
Comment (pgavlin) [inline src/jit/lowerxarch.cpp]: Done.

File: src/jit/sideeffects.h [hunk 15]
```diff
@@ -0,0 +1,89 @@
...
+{
+    bool m_hasAnyLcl;
+    bool m_hasBitVector;
+
+    union
+    {
+        hashBv*  m_bitVector;
+        unsigned m_lclNum;
+    };
+
```
Comment (pgavlin) [inline src/jit/sideeffects.h]: Done.

File: src/jit/sideeffects.h (hunk 10 above)
Comment (pgavlin) [inline src/jit/sideeffects.h]: Done.

File: src/jit/sideeffects.h (hunk 11 above)
Comment (pgavlin) [inline src/jit/sideeffects.h]: Done.

File: src/jit/emitxarch.cpp (hunk 1 above)
Comment (pgavlin) [inline src/jit/emitxarch.cpp]: I was hitting this with an earlier set of changes; the current changes no longer trigger the assert. I've restored it to its original version.

File: src/jit/gentree.cpp (hunk 2 above)
Comment (pgavlin) [inline src/jit/gentree.cpp]: Done.

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT jitstressregs1
@dotnet-bot test Windows_NT jitstressregs2
@dotnet-bot test Windows_NT jitstressregs3
@dotnet-bot test Windows_NT jitstressregs4
@dotnet-bot test Windows_NT jitstressregs8
@dotnet-bot test Windows_NT jitstressregs0x10
@dotnet-bot test Windows_NT jitstressregs0x80
@dotnet-bot test Windows_NT jitstress2
@dotnet-bot test Windows_NT gcstress0x3
@dotnet-bot test Windows_NT gcstress0xc
@dotnet-bot test Windows_NT gcstress0xc_jitstress2
@dotnet-bot test Ubuntu jitstressregs1
@dotnet-bot test Ubuntu jitstressregs2
@dotnet-bot test Ubuntu jitstressregs3
@dotnet-bot test Ubuntu jitstressregs4
@dotnet-bot test Ubuntu jitstressregs8
@dotnet-bot test Ubuntu jitstressregs0x10
@dotnet-bot test Ubuntu jitstressregs0x80
@dotnet-bot test Ubuntu jitstress2
@dotnet-bot test Ubuntu gcstress0x3
@dotnet-bot test Ubuntu gcstress0xc
@dotnet-bot test Ubuntu gcstress0xc_jitstress2

**Comment by pgavlin** [comment]
@dotnet/jit-contrib I've addressed all feedback and formatted the code. PTAL.

File: src/jit/emitxarch.cpp (hunk 1 above)
Comment (briansull) [inline src/jit/emitxarch.cpp]: Thanks

File: src/jit/gentree.cpp (hunk 2 above)
Comment (briansull) [inline src/jit/gentree.cpp]: OK

File: src/jit/gentree.cpp [hunk 16]
```diff
@@ -1791,6 +1791,26 @@ regMaskTP GenTreeCall::GetOtherRegMask() const
...
+//    definition of "pure" that is that used by HelperCallProperties: a
+//    pure call does not read or write any aliased (e.g. heap) memory or
+//    have other global side effects (e.g. class constructors, finalizers),
+//    but is allowed to throw an exception.
+//
+// Arguments:
+//    Copiler - the compiler context.
+//
+// Returns:
+//    True if the call is pure; false otherwise.
```
Comment (briansull) [inline src/jit/gentree.cpp]: You could add this here:
This currently only handles a the set of  JIT helper calls that are "known" to be pure.

File: src/jit/hashbv.cpp (hunk 6 above)
Comment (briansull) [inline src/jit/hashbv.cpp]: I followed that link but didn't see any code that uses these new methods.

File: src/jit/lower.cpp (hunk 4 above)
Comment (briansull) [inline src/jit/lower.cpp]: This method comment header still reads as follows:

 ```
 // Arguments:		 // Arguments:
 //    parentNode  - a non-leaf binary node		 //    parentNode  - a non-leaf binary node
 //    childNode   - a memory op that is a child op of 'parentNode'
```

File: src/jit/hashbv.cpp (hunk 6 above)
Comment (pgavlin) [inline src/jit/hashbv.cpp]: They are used by `hashBv::Intersects`, which is also a new method.

File: src/jit/gentree.cpp (hunk 16 above)
Comment (pgavlin) [inline src/jit/gentree.cpp]: Okay.

**Comment by CarolEidt** [comment]
:shipit:

**Comment by CarolEidt** [comment]
LGTM

**Comment by briansull** [comment]
LGTM
