### PR TITLE
Fix misplaced volatile

### LINKED ISSUE #13015: optimizing the memory set loop with size requirements the right way
When you have this code:

` for (size_t i = 0; i < nPtrs; i++)
        *memPtr++ = 0;`

even though you need memPtr to be cleared as pointers, the compiler can replace this with a memset which will set by bytes. So when you read this memory you can read a partially cleared pointer value which obviously will cause problems. We had to declare memPtr [to be volatile](https://github.com/dotnet/coreclr/issues/12207) in ZeroMemoryInGCHeap to get around this. This issue is for looking into bringing perf back. Since you could be clearing large amounts of memory with Array.Clear (which uses ZeroMemoryInGCHeap) [the perf degrade can be significant](https://github.com/dotnet/coreclr/issues/12207#issuecomment-317236008).

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #13015

### CODE REVIEW

File: src/vm/object.cpp [hunk 1]
```diff
@@ -1658,9 +1658,9 @@ void __fastcall ZeroMemoryInGCHeap(void* mem, size_t size)
         *memBytes++ = 0;
```
Comment (jkotas) [inline src/vm/object.cpp]: This method is only used to clear structs in a few places in reflection now. Writing assembly code to do that is not worth it.

**Comment by jkotas** [comment]
@dotnet-bot test OSX10.12 x64 Checked Innerloop Build and Test please
