### PR TITLE
Refactoring of struct promotion code for the future fix.

### LINKED ISSUE #18986: Assertion failed 'rhs->OperGet() == GT_LONG'
This is a recent regression.

Every Ubuntu arm32 JitStress=2 with JitStressRegs failed with:
```
FAILED   - JIT/Methodical/fp/exgen/10w250d_cs_ro/10w250d_cs_ro.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun 10w250d_cs_ro.exe
               
               Assert failure(PID 23405 [0x00005b6d], Thread: 23405 [0x5b6d]): Assertion failed 'rhs->OperGet() == GT_LONG' in 'testout1:Func_0_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1():double' (IL size 788)
               
                   File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/jit/decomposelongs.cpp Line: 433
                   Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
               
               ./10w250d_cs_ro.sh: line 244: 23405 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
...
FAILED   - JIT/Methodical/fp/exgen/10w5d_cs_ro/10w5d_cs_ro.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun 10w5d_cs_ro.exe
               Func_0_6_5_6_3: != true
               Func_0_6_5_4_6: <= true
               Func_0_6_5_4_5: > true
               Func_0_6_5_4_3: == false
               Func_0_6_4_6_2: != true
               Func_0_6_4_5_4: < true
               Func_0_6_4_5_1: < true
               Func_0_6_4_4: <= true
               Func_0_6_3_6_5: == false
               Func_0_6_3_4_4: <= true
               Func_0_6_3_4_3: < true
               Func_0_6_3_3: < true
               Func_0_6_3_2_3: >= true
               Func_0_6_3_1_5: < true
               Func_0_6_3_1: <= false
               Func_0_6_3: != true
               Func_0_6_2_5: != true
               Func_0_6_2_1: > false
               Func_0_6_1_6_4: < false
               Func_0_6_1_6_3: > false
               Func_0_6_1_5_4: > true
               
               Assert failure(PID 23525 [0x00005be5], Thread: 23525 [0x5be5]): Assertion failed 'rhs->OperGet() == GT_LONG' in 'testout1:Func_0_6_1_3_3():double' (IL size 157)
               
                   File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/jit/decomposelongs.cpp Line: 433
                   Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
               
               ./10w5d_cs_ro.sh: line 244: 23525 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_jitstressregs1_tst/15/consoleText.

There is currently no recent run without JitStressRegs to see if it fails with just JitStress=2 (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_flow/)

@dotnet/arm32-contrib @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
This PR continues work started in #20141 for #18986.
No asm diffs (x86/x64).
There is a small drop in instructions retired (~0.06%).

The last commit contains code to fix #18986 but it is commented out to keep this PR diff free.
Without the additional analysis  that this PR adds the straightforward fix rejects all cases where we lie about struct types (when use `SIMD` or retype internal structs' fields as scalar types).

In addition to a cleaner code it also gives a better debug experience (for example because now we always initialize all fields in `structInfo`).

Note: now we can move this helper as well as `lvaStructFieldInfo` and `lvaStructPromotionInfo` out of `compiler.h`, but I have not found a better place for them yet.

**Please review per commit.**

b549918379: Create StructPromotionHelper.

It will replace lvaStructPromotionInfo and methods that use it.

c90f266cac: Move struct promotion logic from `fgPromoteStructs` to `TryPromoteStructVar`.

789e8ef859: Create a local variable for `compHandle` in `lvaCanPromoteStructType`.

6adadedebd: Return result from `lvaCanPromoteStructType` as bool return value.

176b013c10: Return result from `lvaCanPromoteStructVar` as bool return value.

5770867651: Replace `lvaCanPromoteStructVar` with `structPromotionHelper.CanPromoteStructVar`.

Note: this change makes `lvaStructPromotionInfo` type specific before it was used both for variables and types.

4765204ad6: Move requiresScratchVar from individual lvaStructPromotionInfo to global StructPromotionHelper.

It allows to make lvaStructPromotionInfo smaller and extract the check from the loop.

ba43c194b6: Replace `lvaCanPromoteStructType` with `structPromotionHelper.CanPromoteStructType`.

403a6380dc: Get rid of `bool shouldPromote;` in `fgPromoteStructs`.

12388d8374: Rename `tooManyLocals` to `tooManyLocalsReported`.

64ad4c7ff1: Replace `lvaShouldPromoteStructVar` with `StructPromotionHelper::ShouldPromoteStructVar`.

2af955c5f0: Replace `lvaPromoteStructVar` with `StructPromotionHelper::PromoteStructVar`.

cdc59b22e2: Refactor one `noway_assert` in `CanPromoteStructType`.

27557081d0: Delete unused local vars in `StructPromotionHelper::CanPromoteStructType`.

0d5fae40f4: Optimize setting of `structPromotionInfo->containsHoles`.

Use the fact that we have already rejected structs with overlapping fields and can just check sum of fields sizes match structSize.

b6f4a7d77b: Extract `StructPromotionHelper::SortFields`.

We need fields to be sorted only when we actually promote struct, so do not waste time when we reject it because `ShouldPromoteStructVar` says `No` or when we ask for inlining.

c78e29b74a: Change `lvaGetFieldLocal` argument to be const.

4213c4db6c: Add the link to the recursive promotion issue.

1cf30ef528: Extract `GetFieldInfo` and `TryPromoteStructField`.

e7ad751dff: Add the check for promoted fields with changed type.

`CanPromoteStructType` can fake a field type if the field type is "structs of a single field of scalar types aligned at their natural boundary.". Add a check in debug that when we morph struct field access we have an expected type in the field handle.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

File: src/jit/lclvars.cpp [hunk 1]
```diff
@@ -1839,34 +1838,38 @@ bool Compiler::lvaCanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd, lvaStructPr
...
+// Return value:
+//   true if the struct var can be promoted.
+//
+bool Compiler::StructPromotionHelper::CanPromoteStructVar(unsigned lclNum)
 {
-    noway_assert(lclNum < lvaCount);
+    assert(lclNum < compiler->lvaCount);
 
-    LclVarDsc* varDsc = &lvaTable[lclNum];
+    LclVarDsc* varDsc = &compiler->lvaTable[lclNum];
```
Comment (mikedn) [inline src/jit/lclvars.cpp]: While you're at it change it to use `lvaGetDesc` and drop the assert.

File: src/jit/compiler.h [hunk 2]
```diff
@@ -2979,13 +2979,14 @@ class Compiler
         unsigned char        fieldCnt;
         lvaStructFieldInfo   fields[MAX_NumOfFieldsInPromotableStruct];
 
-        lvaStructPromotionInfo() : typeHnd(nullptr), canPromote(false), containsHoles(false), customLayout(false)
+        lvaStructPromotionInfo(CORINFO_CLASS_HANDLE typeHnd = nullptr)
+            : typeHnd(typeHnd), canPromote(false), containsHoles(false), customLayout(false), fieldCnt(0)
         {
+            memset(fields, 0, sizeof(fields));
```
Comment (mikedn) [inline src/jit/compiler.h]: I think I'd rather add a constructor to field info

File: src/jit/lclvars.cpp [hunk 3]
```diff
@@ -1615,8 +1605,8 @@ bool Compiler::lvaCanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd, lvaStructPr
             return false; // struct must have between 1 and MAX_NumOfFieldsInPromotableStruct fields
         }
 
-        structPromotionInfo->fieldCnt = (BYTE)fieldCnt;
-        DWORD typeFlags               = compHandle->getClassAttribs(typeHnd);
+        structPromotionInfo.fieldCnt = (BYTE)fieldCnt;
```
Comment (mikedn) [inline src/jit/lclvars.cpp]: Might want to change BYTE to unsigned char to match the fieldCnt definition

File: src/jit/lclvars.cpp [hunk 4]
```diff
@@ -1783,7 +1774,7 @@ bool Compiler::lvaCanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd, lvaStructPr
             //
             if (pFieldInfo->fldSize < TARGET_POINTER_SIZE)
             {
-                structPromotionHelper->SetRequiresScratchVar();
+                SetRequiresScratchVar();
```
Comment (mikedn) [inline src/jit/lclvars.cpp]: Since now it's the helper that sets it I'd drop the function and set the data member directly

File: src/jit/lclvars.cpp [hunk 5]
```diff
@@ -1710,8 +1710,9 @@ bool Compiler::StructPromotionHelper::CanPromoteStructType(CORINFO_CLASS_HANDLE
                     return false;
                 }
 
-                // Retype the field as the type of the single field of the struct
-                pFieldInfo->fldType = fieldVarType;
+                // Retype the field as the type of the single field of the struct.
+                // This is a hack that allows us to promote such fields before we support recursive struct promotion
+                // (tracked by #10019).                pFieldInfo->fldType = fieldVarType;
```
Comment (mikedn) [inline src/jit/lclvars.cpp]: Hmm, did you intend to comment out the existing assignment?

File: src/jit/lclvars.cpp [hunk 6]
```diff
@@ -2039,19 +2042,20 @@ void Compiler::lvaPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo* stru
...
         {
             noway_assert(pFieldInfo->fldOffset > (pFieldInfo - 1)->fldOffset);
         }
 #endif
 
-        unsigned varNum = lvaGrabTemp(false DEBUGARG(bufp)); // Lifetime of field locals might span multiple BBs,
-                                                             // so they must be long lifetime temps.
-        varDsc = &lvaTable[lclNum];                          // lvaGrabTemp can reallocate the lvaTable
+        unsigned varNum =
+            compiler->lvaGrabTemp(false DEBUGARG(bufp)); // Lifetime of field locals might span multiple BBs,
```
Comment (mikedn) [inline src/jit/lclvars.cpp]: Should move the comment before the line so it doesn't get wrapped. Anyway this kind of comment placement is kind of weird.

File: src/jit/compiler.h [hunk 7]
```diff
@@ -3005,6 +3005,10 @@ class Compiler
         bool CanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd);
         bool TryPromoteStructVar(unsigned lclNum);
 
+#ifdef DEBUG
+        void CheckFakedType(CORINFO_FIELD_HANDLE fieldHnd, var_types requestedType);
```
Comment (mikedn) [inline src/jit/compiler.h]: Would be nice to find an alternative to "faked". Can't say I have a better idea though. Maybe "scalar struct type" - a struct containing a single scalar type field?

File: src/jit/lclvars.cpp [hunk 8]
```diff
@@ -1917,48 +1887,204 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
     return shouldPromote;
 }
 
-/*****************************************************************************
- * Promote a struct type local */
+//--------------------------------------------------------------------------------------------
+// SortStructFields - sort the fields according to the increasing order of the field offset.
+//
+// Notes:
+//   This is needed because the fields need to be pushed on stack (when referenced as a struct) in the order.
```
Comment (CarolEidt) [inline src/jit/lclvars.cpp]: Nit: I would say "in offset order" or something ("in the order" seems unnecessarily vague)

File: src/jit/lclvars.cpp [hunk 9]
```diff
@@ -1917,48 +1887,204 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+
+    return fieldInfo;
+}
+
+//--------------------------------------------------------------------------------------------
+// TryPromoteStructField - checks that this struct's field is a struct that can be promoted as scalar type
+//   aligned at its natural boundary. Promote the field as the scalar if succeed.
+//
+// Arguments:
+//   outerFieldInfo - information about the field in the outer struct.
```
Comment (CarolEidt) [inline src/jit/lclvars.cpp]: The term "outer" is counter-intuitive to me. It's seems obvious that if we're trying to promote a field, then we care about its promotability in the containing struct. I would just make this `fieldInfo` and use "inner" to describe any nested field.

File: src/jit/lclvars.cpp [hunk 10]
```diff
@@ -1917,48 +1887,204 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+    // TODO-PERF: Structs containing a single floating-point field on Amd64
+    // needs to be passed in integer registers. Right now LSRA doesn't support
+    // passing of floating-point LCL_VARS in integer registers.  Enabling promotion
+    // of such structs results in an assert in lsra right now.
+    //
+    // TODO-PERF: Right now promotion is confined to struct containing a ptr sized
+    // field (int/uint/ref/byref on 32-bits and long/ulong/ref/byref on 64-bits).
+    // Though this would serve the purpose of promoting Span<T> containing ByReference<T>,
+    // this can be extended to other primitive types as long as they are aligned at their
+    // natural boundary.
```
Comment (CarolEidt) [inline src/jit/lclvars.cpp]: It would be good to add another TODO here (I think these should actually be `TODO-CQ`). We currently only promote an actual SIMD typed field, which would cause a nested SIMD type, e.g. a field of `Color` that's defined to be a `Vector3`, to fail promotion. It would be useful if we could treat SIMD types "as if" they are primitive types, and just handle them here. Then when/if we handle recursive struct promotion (#10019)  that would just fall out.

File: src/jit/lclvars.cpp [hunk 11]
```diff
@@ -1479,15 +1481,93 @@ int __cdecl Compiler::lvaFieldOffsetCmp(const void* field1, const void* field2)
...
+bool Compiler::StructPromotionHelper::TryPromoteStructVar(unsigned lclNum)
+{
+    if (CanPromoteStructVar(lclNum))
+    {
+#if 0
+            // Often-useful debugging code: if you've narrowed down a struct-promotion problem to a single
+            // method, this allows you to select a subset of the vars to promote (by 1-based ordinal number).
+            static int structPromoVarNum = 0;
+            structPromoVarNum++;
+            if (atoi(getenv("structpromovarnumlo")) <= structPromoVarNum && structPromoVarNum <= atoi(getenv("structpromovarnumhi")))
```
[the remark this answers is not in the document]
Comment (sandreenko) [reply src/jit/lclvars.cpp]: Unfortunately it is the formatter issue.

File: src/jit/compiler.h [hunk 12]
```diff
@@ -2969,33 +2969,80 @@ class Compiler
...
+    class StructPromotionHelper
+    {
+    public:
+        StructPromotionHelper(Compiler* compiler);
+
+        bool CanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd);
+        bool TryPromoteStructVar(unsigned lclNum);
+
+#ifdef DEBUG
+        void CheckFakedType(CORINFO_FIELD_HANDLE fieldHnd, var_types requestedType);
```
[the remark this answers is not in the document]
Comment (sandreenko) [reply src/jit/compiler.h]: I have added a standart header to cpp file.

File: src/jit/lclvars.cpp (hunk 10 above)
Comment (sandreenko) [reply src/jit/lclvars.cpp]: Fixed

File: src/jit/compiler.h [hunk 13]
```diff
@@ -2969,33 +2969,80 @@ class Compiler
...
+#endif // DEBUG
+
+#ifdef _TARGET_ARM_
+        bool GetRequiresScratchVar();
```
[the remark this answers is not in the document]
Comment (sandreenko) [reply src/jit/compiler.h]: Added a standart header.

**Comment by sandreenko** [comment]
> For future reference, reviewing 20 separate commits is quite tedious. In future, please try to combine them into a smaller number; it's not clear that this needs 20.

Thank you, I am still trying to find the right balance between one huge commit with walls of green and red that nobody wants to review and `one change - one commit` and dozens commits where you can't response a review. WIll try to do better in the future.

File: src/jit/compiler.h (hunk 7 above)
Comment (sandreenko) [reply src/jit/compiler.h]: What about `Retyped(As)ScalarFieldsMap`?

Comment (mikedn) [reply src/jit/compiler.h]: Yep, sounds fine

**Comment by mikedn** [comment]
> Thank you, I am still trying to find the right balance between one huge commit with walls of green and red that nobody wants to review and one change - one commit and dozens commits where you can't response a review. WIll try to do better in the future.

It should be fine to combine multiple simple and independent changes into one commit. For example, "Return result from lvaCanPromoteStructType as bool return value.", "Return result from lvaCanPromoteStructVar as bool return value.", "Rename tooManyLocals to tooManyLocalsReported." etc.

**Comment by CarolEidt** [comment]
> Thank you, I am still trying to find the right balance between one huge commit with walls of green and red that nobody wants to review and one change - one commit and dozens commits where you can't response a review.

I appreciate the effort - I know that I have not done well at splitting huge commits - I find it quite difficult. Perhaps there's a happy medium somewhere.

In case it wasn't clear, I wasn't suggesting merging the commits from this particular PR. Although I wound up just reviewing the net changes, as I found it easier, your comments about the individual changes were very helpful - breaking the changes down incrementally.

File: src/jit/compiler.h [hunk 14]
```diff
@@ -2967,35 +2967,85 @@ class Compiler
...
     };
 
     static int __cdecl lvaFieldOffsetCmp(const void* field1, const void* field2);
-    void lvaCanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd, lvaStructPromotionInfo* structPromotionInfo);
-    void lvaCanPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo* structPromotionInfo);
 
-    bool lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo* structPromotionInfo);
-    void lvaPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo* structPromotionInfo);
+    // This class is responsible for checking validity and profitability of struct promotion.
+    // If it is both legal and profitable, then TryPromoteStructVar promotes the struct and initializesinitializes
```
Comment (AndyAyersMS) [inline src/jit/compiler.h]: typo: `initializesinitializes ?

File: src/jit/lclvars.cpp [hunk 15]
```diff
@@ -1479,15 +1481,106 @@ int __cdecl Compiler::lvaFieldOffsetCmp(const void* field1, const void* field2)
...
+//
+//   The check initializes only nessasary fields in lvaStructPromotionInfo,
+//   so if the promotion is rejected early than the most fields will be uninitialized.
+//
+bool Compiler::StructPromotionHelper::CanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd)
+{
+    assert(compiler->eeIsValueClass(typeHnd));
+    if (structPromotionInfo.typeHnd != typeHnd)
     {
+        // Analyze this type from scratch.
```
Comment (AndyAyersMS) [inline src/jit/lclvars.cpp]: Why not invert this test and return immediately if the cached value is valid. Then you can de-indent the remainder of the method.

**Comment by AndyAyersMS** [comment]
Part of what makes refactoring challenging is that a lot of what makes code "better" is subjective.

I'd recommend first opening an issue pointing out reasons why you think some bit if code needs to be refactored -- either as a worthy standalone project or as a prerequisite for some future changes.

If you can get some agreement on the problems created by the existing code, then it is easier to for reviewers consider the different options available for fixing those problems.

You can also then or subsequently sketch out how you plan to do the work. From this reviewers can (hopefully) see why the path you propose is a good one. And having this roadmap allows reviewers to see that on review, that the changes made are in keeping with the original goals.

In this case you have some of the rationale spelled out in your PR header, which is helpful, but it's not always easy to follow from there to the actual work you did.

File: src/jit/lclvars.cpp [hunk 16]
```diff
@@ -1479,15 +1481,106 @@ int __cdecl Compiler::lvaFieldOffsetCmp(const void* field1, const void* field2)
...
+    return false;
+}
 
-void Compiler::lvaCanPromoteStructType(CORINFO_CLASS_HANDLE typeHnd, lvaStructPromotionInfo* structPromotionInfo)
+#ifdef DEBUG
+//--------------------------------------------------------------------------------------------
+// CheckFakedType - check that the fldType for this fieldHnd was retyped as requested type.
+//
+// Arguments:
+//   fieldHnd      - the field handler;
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: Typo: handler --> handle

File: src/jit/lclvars.cpp [hunk 17]
```diff
@@ -1479,15 +1481,106 @@ int __cdecl Compiler::lvaFieldOffsetCmp(const void* field1, const void* field2)
...
+// Return value:
+//   true if the struct type can be promoted.
+//
+// Notes:
+//   The last analyzed type is memorized to skip the check if we ask about the same time again next.
+//   However, it was not found profitable to memorize all analyzed types in a map.
+//
+//   The check initializes only nessasary fields in lvaStructPromotionInfo,
+//   so if the promotion is rejected early than the most fields will be uninitialized.
+//
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: the most fields --> most fields

File: src/jit/lclvars.cpp [hunk 18]
```diff
@@ -1917,48 +1898,207 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+    {
+        TryPromoteStructField(fieldInfo);
+    }
+
+    return fieldInfo;
+}
+
+//--------------------------------------------------------------------------------------------
+// TryPromoteStructField - checks that this struct's field is a struct that can be promoted as scalar type
+//   aligned at its natural boundary. Promotes the field as a scalar if succeed.
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: if succeed --> if the check succeeded

File: src/jit/lclvars.cpp [hunk 19]
```diff
@@ -1917,48 +1898,207 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+//
+// Arguments:
+//   fieldInfo - information about the field in the outer struct.
+//
+// Return value:
+//   true if the intrenal struct can be promoted.
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: intrenal --> internal
can be promoted --> was promoted

File: src/jit/lclvars.cpp [hunk 20]
```diff
@@ -1917,48 +1898,207 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+    // fields of TYP_BLK, TYP_FUNC or TYP_VOID.
+    if (fieldInfo.fldType != TYP_STRUCT)
+    {
+        return false;
+    }
+
+    COMP_HANDLE compHandle = compiler->info.compCompHnd;
+
+    // Do Not promote if the struct field in turn has more than one field.
+    if (compHandle->getClassNumInstanceFields(fieldInfo.fldTypeHnd) != 1)
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: Not --> not

File: src/jit/lclvars.cpp [hunk 21]
```diff
@@ -1917,48 +1898,207 @@ bool Compiler::lvaShouldPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo
...
+    CorInfoType fieldCorType = compHandle->getFieldType(innerFieldHndl);
+    var_types   fieldVarType = JITtype2varType(fieldCorType);
+    unsigned    fieldSize    = genTypeSize(fieldVarType);
 
-void Compiler::lvaPromoteStructVar(unsigned lclNum, lvaStructPromotionInfo* structPromotionInfo)
+    // Do not promote if either not a primitive type or size equal to ptr size on
+    // target or a struct containing a single floating-point field.
+    //
+    // TODO-PERF: Structs containing a single floating-point field on Amd64
+    // needs to be passed in integer registers. Right now LSRA doesn't support
```
Comment (erozenfeld) [inline src/jit/lclvars.cpp]: needs --> need

File: src/jit/lclvars.cpp (hunk 15 above)
Comment (sandreenko) [reply src/jit/lclvars.cpp]: Done, thanks, it looks better now.

**Comment by sandreenko** [comment]
Thanks everyone for the commens and the feedback.
