### PR TITLE
Separate TryDsc and ExnFlowDsc

### LINKED ISSUE #4044: RyuJIT bug related to side-effects in exception filter
https://github.com/dotnet/roslyn/issues/7030

Reproes only on /o+ on 64bit.

The following code loops infinitely printing “3”

```
using System;

class C
{
    static void Main()
    {
        int i = 3;
        do
        {
            try
            {
                throw new Exception();
            }
            // we should be decrementing i here, it does not happen
            catch (Exception) when (--i < 0)   
            {
                Console.Write("e");
                break;
            }
            catch (Exception)
            {
                // just printing constant 3 here
                //000000b5  mov         ecx,3 
                //000000ba  call        000000005B3CBAF0
                Console.Write(i);
            }
        } while (true);
    }
}

```

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Supplement the helpers for finding a block's `TryDsc` (the `EHblkDsc` of
the innermost `try` region containing it) and a block's `HndDsc` (the
`EHblkDsc` of the innermost handler it is part of) with helpers for
finding a block's `ExnFlowDsc` (the `EHblkDsc` of the innermost handler to
which control may be transferred if an exception occurs in the given
block).

The `ExnFlowDsc` is the same as the `TryDsc` in most cases, but differs
for blocks in filter expressions -- when an exception escapes a filter,
that new exception is discarded and the search for a handler for the prior
exception is resumed at the next-outer handler, which corresponds to the
next-outer try enclosing the try that the filter protects.  This is not
the try enclosing the filter itself for "mutual-protect" clauses such as
are generated for
  try {
    ...
  } catch when (E) { // <-- E is not in the 'try' but an exception
    ...              //     in it causes flow to go to the 'finally'
  } finally {
    ...
  }

This change adds helpers around the `ExnFlowDsc` and updates code that
was using the `TryDsc`/`TryIndex` where appropriate.

This fixes #4044.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@BruceForstall PTAL
/cc @dotnet/jit-contrib

File: tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+            }
+            catch (Exception)
+            {
+                // just printing constant 3 here
+                //000000b5  mov         ecx,3
+                //000000ba  call        000000005B3CBAF0
+                Print1(i);
+            }
+        } while (true);
+
```
Comment (BruceForstall) [inline tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs]: Does this test infinite loop without your fix? Maybe Print1() should throw if (limit <= 0)?

File: tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs [hunk 2]
```diff
@@ -0,0 +1,250 @@
...
+        // the importer doesn't realize that an exception
+        // from Throw(x) can be caught in this method, it
+        // won't separate Throw(x) out from the Ignore(..)
+        // tree, but will still separate out ++y, creating
+        // the bad reordering
+        catch when (Ignore(Throw(x), ++y)) { }
+        catch { Print3(y); }
+
+        return y - 50; // Caller should passs '50'
+    }
```
Comment (BruceForstall) [inline tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs]: typo

File: src/jit/jiteh.cpp [hunk 3]
```diff
@@ -432,6 +432,29 @@ bool                Compiler::bbInTryRegions(unsigned regionIndex, BasicBlock *
...
+  // we are looking for or an outer/later one
+  while (tryIndex < regionIndex)
+  {
+    tryIndex = ehGetEnclosingTryIndex(tryIndex);
+  }
+
+  // Now we have the index of 2 try bodies, either they match or not!
+  return (tryIndex == regionIndex);
+}
+
```
Comment (BruceForstall) [inline src/jit/jiteh.cpp]: coding conventions: 4-space indents, not 2.

File: src/jit/jiteh.cpp [hunk 4]
```diff
@@ -637,6 +660,59 @@ bool            Compiler::ehIsBlockEHLast(BasicBlock* block)
            (ehIsBlockHndLast(block) != nullptr);
 }
 
+/******************************************************************************************
+* Return the EH descriptor for the most nested region that may handle exceptions raised in this BasicBlock
+* (or nullptr if this block's exceptions propagate to caller).
+*/
+EHblkDsc*       Compiler::ehGetBlockExnFlowDsc(BasicBlock* block)
```
Comment (BruceForstall) [inline src/jit/jiteh.cpp]: coding conventions: 4-space indents. Please use the new style function header comment (see doc on GH, or conventions.txt in JIT directory)

File: src/jit/jiteh.cpp [hunk 5]
```diff
@@ -637,6 +660,59 @@ bool            Compiler::ehIsBlockEHLast(BasicBlock* block)
...
+{
+  EHblkDsc* hndDesc = ehGetBlockHndDsc(block);
+
+  if ((hndDesc != nullptr) && hndDesc->InFilterRegionBBRange(block))
+  {
+    // If an exception escapes a filter, or if 'false' is returned at
+    // the end of a filter, the (original) exception is propagated to
+    // the next outer handler.  The "next outer handler" is the handler
```
Comment (BruceForstall) [inline src/jit/jiteh.cpp]: minor wording, but I would say, "if an exception is thrown in a filter, or if exception_continue_search (0) is returned at the end of the filter". "escapes" has the wrong connotations, IMO. any exception will "escape" since you can't have protected regions in a filter.

File: src/jit/jiteh.cpp (hunk 3 above)
Comment (BruceForstall) [inline src/jit/jiteh.cpp]: btw, this seems to be true throughout your new code.

---
In reply to: [61190340](https://github.com/dotnet/coreclr/pull/4591#discussion_r61190340) [](ancestors = 61190340)

**Comment by BruceForstall** [comment]
This all looks great! (modulo my comments). Any diffs? I'd make sure to run a full internal test pass on these changes.

**Comment by BruceForstall** [comment]
Love the new tests!

**Comment by BruceForstall** [comment]
Assuming the full test pass is clean, LGTM

File: tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs (hunk 1 above)
Comment (JosephTremoulet) [inline tests/src/JIT/Regression/JitBlue/GitHub_4044/GitHub_4044.cs]: Great idea, thanks.

File: src/jit/jiteh.cpp (hunk 5 above)
Comment (JosephTremoulet) [inline src/jit/jiteh.cpp]: How about "If an exception is thrown in a filter (or escapes a callee in a filter), or if exception_continue_search (0/false) is returned"?  Because
 1. While you can't have protected regions in a filter, you can have callees which can catch internal exceptions (or not).
 2. CLR filters can only use two of the return values, so IMO it's natural to think of the return as a bool (and in fact the C# construct expresses it as a bool)

**Comment by JosephTremoulet** [comment]
Updated per feedback.  I ran `jitSuperPmi` and `DDR_and_JitSelfHost_Diffs`, there were no diffs.  I also ran Roslyn's `cibuild /test64` to check its `catch when` tests.

**Comment by BruceForstall** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
@mmitche / @AndyAyersMS  / @CarolEidt - these look like the same 17 OS X failures and 20 Ubuntu failures that are hitting other unrelated jobs, yes?

**Comment by mmitche** [comment]
@JosephTremoulet Yes
