### PR TITLE
Call `gtEffectiveVal` in `gtWalkOp`.

### LINKED ISSUE #6920: RyuJIT x86: assertion failed: '(op2 == idx) || (op2->gtEffectiveVal() == idx)' in 'Platform.Graphics.Typography.TrueType.SfntReader:LoadNamedRecords():this' (IL size 446) at gentree.cpp:429
This is from TrueTypeBench in the internal benchmarks.

### PR DESCRIPTION
**Pull request by pgavlin**
This function was using an ad-hoc, open-coded version of
`gtEffectiveVal` that was missing the effective value of `GT_NOP` nodes.
This change replaces these implementations with calls to
`gtEffectiveVal` and makes `gtEffectiveVal` non-recursive.

Fixes #6920.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CarolEidt @BruceForstall @adiaaida @dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
LGTM

**Comment by adiaaida** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test Windows_NT x86 ryujit Checked Build and Test

File: src/jit/gentree.h [hunk 1]
```diff
@@ -5099,23 +5099,22 @@ inline GenTreePtr GenTree::gtGetOp2()
...
-            {
-                return gtOp.gtOp1->gtEffectiveVal();
-            }
-            break;
-
-        default:
-            break;
+        if (effectiveVal->gtOper == GT_COMMA)
+        {
+            effectiveVal = effectiveVal->gtOp.gtOp2;
```
Comment (sivarv) [inline src/jit/gentree.h]: Say we have the following tree node
treeNode = GT_COMMA1(op1A, op2=GT_COMMA2(Op1B, op2=GT_COMMA3(op1, op2)))

That is three GT_COMMA nodes nested.

Earlier treeNode->gtEffectiveVal() would return op2

Now with this change treeNode->gtEffectiveVal() would return GT_COMMA2 and caller would have to iterate to reach op2.  

But I see this method is called from many places within Jit codebase with the assumption that they will get op2 instead of GT_COMMA2.  Won't this change break those callers?

Comment (sivarv) [inline src/jit/gentree.h]: Pls ignore this comment.  I see this routine iterates instead of using recursion.

**Comment by sivarv** [comment]
Looks good.
