### PR TITLE
[x86/Linux] Fix incorrect FP values

### LINKED ISSUE #9848: [x86/Linux] JIT.Methodical.eh.generics.throwincatch failure
The following tests failed with similar error message:
 - JIT.Methodical.eh.generics.throwincatch_d.throwincatch_d
 - JIT.Methodical.eh.generics.throwincatch_do.throwincatch_do
 - JIT.Methodical.eh.generics.throwincatch_r.throwincatch_r
 - JIT.Methodical.eh.generics.throwincatch_ro.throwincatch_ro

Here is an ouput of ``JIT.Methodical.eh.generics.throwincatch_d.throwincatch_d``
```
FAILED   - [ 3264 :    8 sec ] JIT/Methodical/eh/generics/throwincatch_d/throwincatch_d.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170217_164016_x86_x86-emu/coreclr-unittest-170217-074046/overlay/corerun throwincatch_d.exe
               in try
                 in try
                 in catch: Exception of type 'GenException`1[System.Int32]' was thrown.
               in catch: Exception of type 'GenException`1[System.Int32]' was thrown.
               True
               in try
                 in try
                 in catch: Exception of type 'GenException`1[System.Double]' was thrown.
               in catch: Exception of type 'GenException`1[System.Double]' was thrown.
               True
               in try
                 in try
                 in catch: Exception of type 'GenException`1[System.String]' was thrown.
               ./throwincatch_d.sh: line 131: 23532 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" throwincatch_d.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

### PR DESCRIPTION
**Pull request by wateret**
Restoring FP by CallerSP could be incorrect for nested EH.
Now that we have #9820, we can use current context for 1st pass of EH.

Fix #9848

### CODE REVIEW

**Comment by wateret** [comment]
cc: @parjong @janvorli @jkotas

**Comment by wateret** [comment]
Not sure about using `pRD->pCurrentContext` instead of `pctx` in `FillRegDisplay()`.

File: src/inc/regdisp.h [hunk 1]
```diff
@@ -396,7 +396,7 @@ inline void FillRegDisplay(const PREGDISPLAY pRD, PT_CONTEXT pctx, PT_CONTEXT pC
 #elif defined(_TARGET_X86_) // _TARGET_ARM_
     for (int i = 0; i < 7; i++)
     {
-        *(&pRD->ctxPtrsOne.Esi + i) = (&pctx->Esi + i);
+        *(&pRD->ctxPtrsOne.Esi + i) = (&pRD->pCurrentContext->Esi + i);
```
Comment (janvorli) [inline src/inc/regdisp.h]: This doesn't look right. And you've mentioned that you are not sure about this. What was the reason for making this change?

Comment (parjong) [inline src/inc/regdisp.h]: #9820 revises ``InitializeCurrentContextForCrawlFrame`` to update ``pRD->pCurrentContext`` using ``CurrentNonVolatileContextRecord`` saved in the dispatcher context, but ``pRD->pCurrentContextPointers`` points to ``pctx`` here, and thus it does not update ``*(pRD->pCurrentContextPointers->Ebp)``. This change is required to update ``*(pRD->pCurrentContextPointers->Ebp)``.

Internal evaluation shows that this does not introduce any regression, but we are currently not sure about the correctness of this change. 

Could you let us know why there are two distinct ``pContext`` and ``pCurrentContext``? As I understand, we may take another approach that revises ``InitializeCurrentContextForCrawlFrame`` to update ``pContext`` in order to fix this issue, but we are not sure about which approach is better.

Comment (janvorli) [inline src/inc/regdisp.h]: @parjong the semantics of the FillRegDisplay is to fill the REGDISPLAY from the passed in pctx and using the registers stored in the pctx as the initial locations where the context pointers point. Your change would change that semantics so that the context pointers would point into the context pointed to by the pCurrentContext instead. I would prefer keeping the semantics the same as for other target architectures. 
The *pCurrentContext is initialized with the *pctx values at line 352, so the values that the context pointers point to are the same with or without your change. The only difference is their location.
If I understand what you are saying correctly, the InitializeCurrentContextForCrawlFrame is called after the FillRegDisplay and patches only the pCurrentContext, which causes a trouble later when the GetRegdisplayFP is called, since it gets the value using the context pointers.
I think the fix should rather be in the InitializeCurrentContextForCrawlFrame to let it update the pCurrentContextPointers to point to the registers in the pDispatcherContext->CurrentNonVolatileContextRecord.

Comment (parjong) [inline src/inc/regdisp.h]: @janvorli Sorry for not being clear. Yes, you are right. ``InitializeCurrentContextForCrawlFrame`` is called after ``FillRegDisplay``, which cause this mismatch. 

It seems that your approach would be better than the alternative approach that I mentioned above.

Comment (janvorli) [inline src/inc/regdisp.h]: As for why there is the pContext in the REGDISPLAY, from what I can see from the code, it is used for debugger purposes. It keeps pointer to the context from which the REGDISPLAY was initilized and it does that only until we unwind from that context in one of the XXX::UpdateRegDisplayHelper functions and then it is nulled.

**Comment by wateret** [comment]
@janvorli Updated as your comment. Thank you.

**Comment by wateret** [comment]
Following tests are fixed with this patch.

* JIT/Methodical/Arrays/lcs/_speed_dbglcsmixed/_speed_dbglcsmixed.sh
* JIT/Methodical/Arrays/lcs/_speed_rellcsmixed/_speed_rellcsmixed.sh
* JIT/Methodical/eh/generics/throwincatch_d/throwincatch_d.sh
* JIT/Methodical/eh/generics/throwincatch_do/throwincatch_do.sh
* JIT/Methodical/eh/generics/throwincatch_r/throwincatch_r.sh
* JIT/Methodical/eh/generics/throwincatch_ro/throwincatch_ro.sh
