### PR TITLE
Fix JIT/Directed/pinvoke/tail

### LINKED ISSUE #13048: Test failure: JIT_Directed._pinvoke_tail_tail_/_pinvoke_tail_tail_cmd
Opened on behalf of @Jiayili1

The test `JIT_Directed._pinvoke_tail_tail_/_pinvoke_tail_tail_cmd` has failed.

    
    Return code:      1
    Raw output file:      C:\dotnetbuild\work\3149f6cd-d217-4f59-b062-5ab5811edeb5\Work\c99d960e-07ec-4250-9c74-e95bb720aaef\Unzip\Reports\JIT.Directed\pinvoke\tail\tail.output.txt
    Raw output:
    BEGIN EXECUTION\r
     "C:\dotnetbuild\work\3149f6cd-d217-4f59-b062-5ab5811edeb5\Payload\corerun.exe" tail.exe \r
    CreatePopupMenu failed\r
    Expected: 100\r
    Actual: 101\r
    END EXECUTION - FAILED\r
    FAILED\r
    Test Harness Exitcode is : 1\r
    
    To run the test:
    > set CORE_ROOT=C:\dotnetbuild\work\3149f6cd-d217-4f59-b062-5ab5811edeb5\Payload
    > C:\dotnetbuild\work\3149f6cd-d217-4f59-b062-5ab5811edeb5\Work\c99d960e-07ec-4250-9c74-e95bb720aaef\Unzip\pinvoke\tail\tail.cmd
    \r
    Expected: True\r
    Actual:   False

        Stack Trace:

        
Build : Master - 20170725.03 (Core Tests)
Failing configurations:
- Windows.10.Nano.Amd64
  - x64

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170725.03/workItem/JIT.Directed.XUnitWrapper/analysis/xunit/JIT_Directed._pinvoke_tail_tail_~2F_pinvoke_tail_tail_cmd

category:correctness
theme:testing
skill-level:intermediate
cost:small

### PR DESCRIPTION
**Pull request by RussKeldorph**
Remove dependency on Windows user32 library and enable test for all platforms.

Fixes #13048

### CODE REVIEW

File: tests/src/JIT/Directed/pinvoke/user32menu.cpp [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+AppendMenuA(
+    HMENU hMenu,
+    unsigned __int32 uFlags,
+    unsigned __int32 uID,
+    const char * item
+    )
+{
+    if (uFlags != 0)
+    {
+        throw "AppendMenu: only MF_STRING (0) supported for uFlags";
```
Comment (AaronRobinsonMSFT) [inline tests/src/JIT/Directed/pinvoke/user32menu.cpp]: Throwing like this will result in a very bad failure on non-Windows. I doubt the string will be observed in the logs. That may be okay in this case, but just FYI.

File: tests/src/JIT/Directed/pinvoke/user32menu.def [hunk 2]
```diff
@@ -0,0 +1,5 @@
+EXPORTS
```
Comment (AaronRobinsonMSFT) [inline tests/src/JIT/Directed/pinvoke/user32menu.def]: This file isn't needed since `EXPORT_API  is defined in source.

Comment (RussKeldorph) [reply tests/src/JIT/Directed/pinvoke/user32menu.def]: Fair enough.  I'm used to `.def` files being preferred, and I just followed the example of a nearby project, but I see that there are only a handful of `.def` files in the test tree, so best not to add more.

File: tests/src/JIT/Directed/pinvoke/user32menu.cpp (hunk 1 above)
Comment (RussKeldorph) [reply tests/src/JIT/Directed/pinvoke/user32menu.cpp]: Can you clarify "very bad failure?"  I agree this is low effort error handling, but I really just need to indicate catastrophic failure.  The only "very bad" failure modes IMO would be if the throws are ignored or cause the process to hang.  Can you point out a better example I should follow?  I'm happy to do something else--just not sure what is preferred.

Comment (AaronRobinsonMSFT) [reply tests/src/JIT/Directed/pinvoke/user32menu.cpp]: >Can you clarify "very bad failure?"

The process will simply explode with no indicate this is the cause since as soon as the transition back to the CLR occurs the process stops with an ugly segv or something else that isn't obvious. I think I should have clarified my point a bit better. If you want this message to be in the log so it is obvious why it failed, I would instead write out the message using `printf` and then throw, that was my main point - this message will never be observed in the log.

Comment (RussKeldorph) [reply tests/src/JIT/Directed/pinvoke/user32menu.cpp]: Yeah, I don't care whether the message is in the log.  It's really just taking the place of a comment in the code so I type less characters.

**Comment by echesakovMSFT** [comment]
@RussKeldorph The easiest way to find out if the test was running is to go 
https://dev.azure.com/dnceng/public/_build/results?buildId=113546&view=ms.vss-test-web.build-test-results-tab Click on X to remove Outcome filters and select JIT.Directed under Test file. You can also type "pivoke" in *Filter by test or run name* field
