### PR TITLE
Fix RyuJIT/arm32 asserts

### LINKED ISSUE #14198: [RyuJIT/arm32][JitStress=1] Assertion failed 'this->gtOper == GT_MUL_LONG'
Seen in an x86_arm_altjit run

Tests:
```
JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd
JIT\Performance\CodeQuality\BenchF\Simpsn\Simpsn\Simpsn.cmd
JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd
JIT\Directed\perffix\primitivevt\mixed1_cs_do\mixed1_cs_do.cmd
```

Example:
```
BEGIN EXECUTION
 "E:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" 10w5d_cs_ro.exe

Assert failure(PID 8056 [0x00001f78], Thread: 7664 [0x1df0]): Assertion failed 'this->gtOper == GT_MUL_LONG' in 'testout1:Func_0_6_6():double' (IL size 252)

    File: e:\gh\coreclr2\src\jit\gtstructs.h Line: 113
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

### LINKED ISSUE #14199: [RyuJIT/arm32][JitStress=1] Assertion failed '!"Missing flags on tree"'
Tests:

```
JIT\Methodical\fp\exgen\10w5d_cs_d\10w5d_cs_d.cmd
JIT\Methodical\fp\exgen\10w5d_cs_r\10w5d_cs_r.cmd
```

Example:

```
BEGIN EXECUTION
 "E:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" 10w5d_cs_d.exe
Func_0_6_5_6_3: != true
Func_0_6_5_4_6: <= true
Func_0_6_5_4_5: > true
Func_0_6_5_4_3: == false
Func_0_6_4_6_2: != true
Func_0_6_4_5_4: < true
Func_0_6_4_5_1: < true
Func_0_6_4_4: <= true
Func_0_6_3_6_5: == false
Func_0_6_3_4_4: <= true
Func_0_6_3_4_3: < true
Func_0_6_3_3: < true
Func_0_6_3_2_3: >= true
Func_0_6_3_1_5: < true
Func_0_6_3_1: <= false
Func_0_6_3: != true
Func_0_6_2_5: != true
Func_0_6_2_1: > false
Func_0_6_1_6_4: < false
Func_0_6_1_6_3: > false
Func_0_6_1_5_4: > true
Func_0_6_1_3: == false
Func_0_5_6_6_6: <= true
Func_0_5_6_6_1: > true
Func_0_5_6_4_6: <= false
Func_0_5_6_4_2: >= false
Func_0_5_6_3_6: < false
Func_0_5_6_3_1: == false
Func_0_5_6_3: <= true
Func_0_5_6_2_1: >= false
Func_0_5_6_1_3: > true
Func_0_5_6_1: <= false
Func_0_5_5_6: != true
Func_0_5_5_5_6: != true
Func_0_5_5_5_4: == false
Func_0_5_5_5_2: == false
Func_0_5_5_4_5: < true
Func_0_5_5_4: > true
Func_0_5_5_3_4: != true
Func_0_5_5_3_2: <= true
Func_0_5_5_3_1: > true
Func_0_5_5_1: < false
Func_0_5_4_5: >= false
Func_0_5_4_1_3: <= false
Func_0_5_4_1_2: == false
Func_0_5_4: != true
Missing flags on tree [000637]: --X---------
               [000645] -c-XG--------             /--*  FIELD_LIST void   int at offset 12
               [000644] ---XG--------             |  \--*  IND       int
               [000642] -------------             |     |  /--*  CNS_INT   int    12
               [000643] ----G--------             |     \--*  ADD       byref
     (  1,  1) [000641] -------------             |        |  /--*  CNS_INT   int    4 field offset Fseq[a2_0_5_3_6_3]
     (  5,  5) [000638] ----G--------             |        \--*  ADD       byref
     (  3,  3) [000639] L---G--------             |           \--*  ADDR      byref
     (  3,  2) [000640] ----G--N-----             |              \--*  LCL_VAR   struct(AX) V00 loc0
               [000637] -c--G--------             *  FIELD_LIST void   int at offset 8
               [000636] R---G--------             \--*  IND       int
               [000634] -------------                |  /--*  CNS_INT   int    8
               [000635] ----G--------                \--*  ADD       byref
     (  1,  1) [000633] -------------                   |  /--*  CNS_INT   int    4 field offset Fseq[a2_0_5_3_6_3]
     (  5,  5) [000630] ----G--------                   \--*  ADD       byref
     (  3,  3) [000631] L---G--------                      \--*  ADDR      byref
     (  3,  2) [000632] ----G--N-----                         \--*  LCL_VAR   struct(AX) V00 loc0

Assert failure(PID 18280 [0x00004768], Thread: 8680 [0x21e8]): Assertion failed '!"Missing flags on tree"' in 'testout1:Func_0_5_3_6_3():double' (IL size 466)

    File: e:\gh\coreclr2\src\jit\flowgraph.cpp Line: 21433
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

### PR DESCRIPTION
**Pull request by BruceForstall**
Fix #14199: propagate `GTF_EXCEPT` bits from the end of `GT_FIELD_LIST`
lists to the beginning, to avoid "Missing flags on tree" asserts.

Fix #14198: for RyuJIT/arm32, `GT_BITCAST` needs to be a MultiRegOp.
This is required when a varargs function, which includes the tailcall
helper, needs to pass a double in integer registers. We can end up
with `GT_PUTARG_REG/long(GT_BITCAST/long(double tree))`.

Fixed various GenTree node flags dumping issues.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked forcerelocs
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitsse2only
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked tailcallstress
@dotnet-bot test Windows_NT x86_arm_altjit Checked
@dotnet-bot test Windows_NT x86_arm_altjit Debug
@dotnet-bot test Windows_NT x86_arm_altjit Release

**Comment by BruceForstall** [comment]
@wateret This touches some code you've been recently changing. In particular, it is necessary to make `GT_PUTARG_REG` and `GT_BITCAST` available as MultiRegOp nodes for all RyuJIT/arm32 compilers, not just `ARM_SOFTFP`, so fix some asserts related to varargs functions (in the test case I see, because calling the tailcall helper uses varargs, and passes double via integer registers). PTAL

**Comment by BruceForstall** [comment]
@dotnet-bot test Windows_NT x86_arm_altjit Checked forcerelocs
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitsse2only
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2_jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstress2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x1000
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x10
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs0x80
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs1
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs2
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs3
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs4
@dotnet-bot test Windows_NT x86_arm_altjit Checked jitstressregs8
@dotnet-bot test Windows_NT x86_arm_altjit Checked minopts
@dotnet-bot test Windows_NT x86_arm_altjit Checked tailcallstress
@dotnet-bot test Windows_NT x86_arm_altjit Checked
@dotnet-bot test Windows_NT x86_arm_altjit Debug
@dotnet-bot test Windows_NT x86_arm_altjit Release

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -5311,7 +5311,33 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
...
+        stack.Push(tree);
+    }
 
+    unsigned propFlags = (tree->gtOp.gtOp1->gtFlags & GTF_ALL_EFFECT);
+    tree->gtFlags |= propFlags;
+
+    while (stack.Height() > 0)
+    {
+        tree = stack.Pop();
+        propFlags |= (tree->gtOp.gtOp1->gtFlags & GTF_ALL_EFFECT);
```
Comment (rartemev) [inline src/jit/morph.cpp]: Why it is not `tree->gtGetOp1()->gtFlags` ?

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -5311,7 +5311,33 @@ GenTreePtr Compiler::fgMorphMultiregStructArg(GenTreePtr arg, fgArgTabEntryPtr f
...
+    // This is verified in fgDebugCheckFlags().
+
+    ArrayStack<GenTree*> stack(this);
+    GenTree*             tree;
+    for (tree = newArg; (tree->gtGetOp2() != nullptr) && tree->gtGetOp2()->OperIsFieldList(); tree = tree->gtGetOp2())
+    {
+        stack.Push(tree);
+    }
 
+    unsigned propFlags = (tree->gtOp.gtOp1->gtFlags & GTF_ALL_EFFECT);
```
Comment (rartemev) [inline src/jit/morph.cpp]: Why it is not tree->gtGetOp1()->gtFlags ?

File: src/jit/morph.cpp (hunk 1 above)
Comment (BruceForstall) [reply src/jit/morph.cpp]: They're equivalent. IMO, gtGetOp1() isn't terribly useful, except to provide symmetry to gtGetOp2(), which is useful.

Comment (rartemev) [reply src/jit/morph.cpp]: Symmetry is exactly what I mean

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
@dotnet/arm32-contrib

File: src/jit/gentree.cpp [hunk 3]
```diff
@@ -7125,8 +7125,8 @@ GenTreePtr Compiler::gtNewBitCastNode(var_types type, GenTreePtr arg)
 
     GenTreePtr node = nullptr;
 #if !defined(LEGACY_BACKEND) && defined(_TARGET_ARM_)
-    // A BITCAST could be a MultiRegOp on armel since we could move a double register to two int registers.
-    node = new (this, GT_PUTARG_REG) GenTreeMultiRegOp(GT_BITCAST, type, arg, nullptr);
+    // A BITCAST could be a MultiRegOp on arm since we could move a double register to two int registers.
+    node = new (this, GT_BITCAST) GenTreeMultiRegOp(GT_BITCAST, type, arg, nullptr);
```
Comment (briansull) [inline src/jit/gentree.cpp]: Did this work at all before your change, as previously this created a GT_PUTARG_REG node?

Comment (BruceForstall) [reply src/jit/gentree.cpp]: It always created GT_BITCAST; the `new (this, GT_BITCAST)` only is used for tracking node type statistics, I think.

Comment (briansull) [reply src/jit/gentree.cpp]: Oh, that was confusing.
