### PR TITLE
Set flag in comp info to signal that a caller has >8 byte struct args

### LINKED ISSUE #22330: Bug: incorrect parameters passed only in release build linux-x64
## On a specific project the release build is passing incorrect parameters under linux-x64. 

Platform: Linux x64. I tested on Debian GNU/Linux 9 (stretch) and Red Hat Enterprise Linux Server release 
7.5 (Maipo).

## Steps to replicate:

0. Install .Net Core 2.2 on linux
1. Use this project: https://github.com/abelykh0/NetCoreIssue
2. Open the solution LinuxNetCoreBug.sln in Visual Studio 2017
3. Right click on Publish project, Publish, then choose "Release linux-x64". Change the folder if needed (it is currently set to C:\Projects\Issue). Click Publish
4. Run dotnet exec LinuxNetCoreBug.dll on linux

Here is the implementation of the abstract method (the implementation is in the `LoadedLibrary` assembly, which is loaded dynamically with `Assembly.LoadFrom` by the main program):

```
protected override IList<Guid> DbFileSystemQuery(
    int pageNumber,
    int pageSize,
    ICollection<Guid> queryTargetId,
    FileSystemQueryOptions queryOptions,
    IList<Tuple<FileSystemQueryField, SortDirection>> orderBy,
    ICollection<FileSystemQueryFilterRule> filter)
{
    Console.WriteLine(orderBy.GetType().ToString());
    Console.WriteLine(filter.GetType().ToString());
    Console.WriteLine(orderBy == filter);
    return null;
}
```

This output shows that the `orderBy` and `filter` parameters are the same object. However, this should be impossible because the types don’t even work out.

### PR DESCRIPTION
**Pull request by jashook**
This will be used by fgCanFastTailCall to correctly determine whether an arm64
or x64 linux caller/callee can fastTailCall.

It is also a workaround to #12468 to catch early any slot shuffling that would happen in LowerFastTailCall. Which currently assumes all parameters are one slot size.

Fixes #22330.

### CODE REVIEW

File: src/jit/compiler.h [hunk 1]
```diff
@@ -8588,8 +8588,9 @@ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         unsigned  compArgsCount;     // Number of arguments (incl. implicit and     hidden)
 
 #if FEATURE_FASTTAILCALL
-        size_t compArgStackSize; // Incoming argument stack size in bytes
-#endif                           // FEATURE_FASTTAILCALL
+        size_t compArgStackSize;   // Incoming argument stack size in bytes
+        bool compHasMultiSlotArgs; // Caller has >8 byte sized struct parameter
```
Comment (CarolEidt) [inline src/jit/compiler.h]: I much prefer this "MultiSlot" nomenclature to "Multireg" as in `hasMultiregStructArgs` in `fgMorphArgs`. I think we should change that one to `hasMultiSlotStructArgs` (since it must be set for multi-slot structs even if they're not enregistered), but as I recall there were objections to changing that in one of my earlier refactors, probably because there were already so many changes.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -7243,7 +7244,7 @@ bool Compiler::fgCanFastTailCall(GenTreeCall* callee)
     }
 
     // Callee has a >8 and <=16 byte struct and arguments that has to go on the stack. Do not fastTailCall.
-    if (calleeStackSize > 0 && hasTwoSlotSizedStruct)
+    if (hasStackArgs > 0 && hasTwoSlotSizedStruct)
```
Comment (CarolEidt) [inline src/jit/morph.cpp]: I think this should just be `if (hasStackArgs && hasTwoSlotSizedStruct)`

Comment (jashook) [reply src/jit/morph.cpp]: Oops thanks :)

**Comment by jashook** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test

File: src/jit/morph.cpp [hunk 3]
```diff
@@ -7243,7 +7244,7 @@ bool Compiler::fgCanFastTailCall(GenTreeCall* callee)
     }
 
     // Callee has a >8 and <=16 byte struct and arguments that has to go on the stack. Do not fastTailCall.
-    if (calleeStackSize > 0 && hasTwoSlotSizedStruct)
+    if (hasStackArgs && hasTwoSlotSizedStruct)
```
Comment (AndyAyersMS) [inline src/jit/morph.cpp]: Should this comment say "caller or callee"? In the bug, it's the caller that has a multi-slot stack arg.

You might add a reason why, some thing like

When either caller or callee has multi-slot stack args, we can't safely reason about stack interference between the two with arg numbers, we need to look at stack slot usage. And we don't do this yet.

Comment (jashook) [reply src/jit/morph.cpp]: Yes this comment is now outdated. Thank you will change.

File: src/jit/morph.cpp [hunk 4]
```diff
@@ -7168,6 +7168,7 @@ bool Compiler::fgCanFastTailCall(GenTreeCall* callee)
     }
 
     const unsigned maxRegArgs = MAX_REG_ARG;
+    hasTwoSlotSizedStruct     = hasTwoSlotSizedStruct || info.compHasMultiSlotArgs;
```
Comment (briansull) [inline src/jit/morph.cpp]: This should be written as:

`hasTwoSlotSizedStruct     |= info.compHasMultiSlotArgs;`

Comment (CarolEidt) [reply src/jit/morph.cpp]: I'm not sure it needs to be rewritten, but if it does, it should be:
```
hasTwoSlotSizedStruct ||= info.compHasMultiSlotArgs;
```
since `hasTwoSlotSizedStruct` is a `bool`.

Comment (jashook) [reply src/jit/morph.cpp]: Personally I prefer it as it is, but i'm good either way.

Comment (briansull) [reply src/jit/morph.cpp]: There is no such operator as ||=
These two || && are short-circuiting forms of the standard operators | and &
I only use thme when there is some value is having a short-circuit evaluation.
With two bool values there is no reason not to simply use |=

I don't feel that this has to be changed, so if you want to check this in with a short-circuit form,
 I guess that is OK.

**Comment by jashook** [comment]
I believe this change is good to be merged

**Comment by daniel-white** [comment]
did this not ship with .net core 2.1.12?

**Comment by AndyAyersMS** [comment]
This fix should be in 2.1.12 (and in 2.2.6), but doesn't seem to be called out in the release notes for either.

@vivmishra can you check if #24858 (2.1) and #24954 (2.2) was included in the releases but overlooked in the notes?

**Comment by vivmishra** [comment]
Those two PRs did not have correct label or milestone set. I have fixed that now and added CoreCLR to rel notes. 

Cc: @leecow ; @RussKeldorph
