### PR TITLE
[Ryujit/ARM32] Update allocateBusyReg() in LSRA for ARM32

### LINKED ISSUE #13118: [RyuJIT/ARM32] Assertion failed 'nextPhysRegPosition->nodeLocation == refLocation && candidateBit != candidates'
With `COMPlus_AltJit=*` option, following assertion is observed in Checked build of recent coreclr (e1eb1d56e40)

```
               Assert failure(PID 24654 [0x0000604e], Thread: 24654 [0x604e]): Assertion failed 'nextPhysRegPosition->nodeLocation == refLocation && candidateBit != candidates' in 'DomainBoundILStubClass:IL_STUB_PInvoke(float,double,float,double,float,double,float,double,float,double,float,double,float,struct):float' (IL size 169)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 5856
                   Image: /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170731.Checked/corerun
```

Failed tests:
```
JIT/jit64/hfa/main/testA/hfa_sf2A_d/hfa_sf2A_d.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_d/hfa_sd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_d/hfa_sf2G_d.sh
```

### PR DESCRIPTION
**Pull request by hqueue**
Fix #13118 

- Add two helper functions. `canSpillThisReg()` and `checkReferenceAt()`
- Update allocateBusyReg() to spill and allocate a double register properly

### CODE REVIEW

**Comment by hqueue** [comment]
@CarolEidt PTAL

This PR address the problem of finding a candidate and spilling a double register for TYP_DOUBLE interval in `allocateBusyReg()`.  There is an issue #12873 (PR #13100) which address a similar problem in `tryAllocateFreeReg()`.
I think it would be better to update `unassignPhysReg()` after this PR and #13100 are merged.
What do you think of it ?

File: src/jit/lsra.cpp [hunk 1]
```diff
@@ -6024,7 +6309,55 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
+                unassignPhysReg(farthestRefPhysRegRecord2,
+                                farthestRefPhysRegRecord2->assignedInterval->recentRefPosition);
+            }
+        }
+        else
+        {
+            unassignPhysReg(farthestRefPhysRegRecord, farthestRefPhysRegRecord->assignedInterval->recentRefPosition);
+        }
+#else
         unassignPhysReg(farthestRefPhysRegRecord, farthestRefPhysRegRecord->assignedInterval->recentRefPosition);
```
Comment (CarolEidt) [inline src/jit/lsra.cpp]: You could keep the above call to `unassignPhysReg` in common, and avoid repeating the non-double case. Also, I think it's worth extracting the double case into a method `unassignDoublePhysReg(RegRecord* doubleRegRecord)` that always spills the active `assignedInterval`(s) at their `recentRefPosition`.

**Comment by CarolEidt** [comment]
> I think it would be better to update unassignPhysReg() after this PR and #13100 are merged as you suggested at #13100 (comment).

I'd prefer to reduce the complexity before merging the code.

**Comment by hqueue** [comment]
@CarolEidt Thank you for the feedback. It is very helpful and some of them clearly addressed my concerns which I couldn't figure out better implementation.  I will update this PR based on your feedback. Thanks again :)

File: src/jit/lsra.cpp [hunk 2]
```diff
@@ -5786,12 +5949,24 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
         RegRecord* physRegRecord = getRegisterRecord(regNum);
+#ifdef _TARGET_ARM_
+        RegRecord* physRegRecord2 = nullptr;
+        // For ARM32, let's consider two float registers consisting a double reg together,
+        // when allocaing a double register.
+        if (current->registerType == TYP_DOUBLE && genIsValidDoubleReg(regNum))
+        {
+            physRegRecord2 = findAnotherHalfRegRec(physRegRecord);
+        }
+#endif
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Updated ( https://github.com/dotnet/coreclr/pull/13145/commits/578f6d338b5c3be20ee016b9e47ec55498ff9b84)

File: src/jit/lsra.cpp [hunk 3]
```diff
@@ -5858,14 +6038,57 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
             continue;
         }
 
-        RefPosition* recentAssignedRef = assignedInterval->recentRefPosition;
+#ifdef _TARGET_ARM_
+        RefPosition* recentAssignedRef = (assignedInterval == nullptr) ? nullptr : assignedInterval->recentRefPosition;
+        RefPosition* recentAssignedRef2 =
+            (assignedInterval2 == nullptr) ? nullptr : assignedInterval2->recentRefPosition;
+        // There are four cases for ARM32 when we are trying to allocation a double register for TYP_DOUBLE
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Fixed typo ( https://github.com/dotnet/coreclr/pull/13145/commits/578f6d338b5c3be20ee016b9e47ec55498ff9b84)

File: src/jit/lsra.cpp [hunk 4]
```diff
@@ -5883,11 +6106,18 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
             }
             continue;
         }
-
+#endif
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Update as suggested. (https://github.com/dotnet/coreclr/pull/13145/commits/f091497b322b4bc1b25a4c6ad2a06ea62daae757)

File: src/jit/lsra.cpp [hunk 5]
```diff
@@ -5883,11 +6106,18 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
         // If we have a recentAssignedRef, check that it is going to be OK to spill it
         //
         // TODO-Review: Under what conditions recentAssginedRef would be null?
         unsigned recentAssignedRefWeight = BB_ZERO_WEIGHT;
+#ifdef _TARGET_ARM_
+        if (!canSpillThisReg(physRegRecord, recentAssignedRef, physRegRecord2, recentAssignedRef2, refLocation,
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Updated as suggested :)
(https://github.com/dotnet/coreclr/pull/13145/commits/70e070d44b3b6fb328d5e2b18ec85211bc19cdb3)

File: src/jit/lsra.cpp (hunk 1 above)
Comment (hqueue) [inline src/jit/lsra.cpp]: Updated (https://github.com/dotnet/coreclr/pull/13145/commits/7b8dc3fd1ba66de23f25b173a35959b28648fc56)

File: src/jit/lsra.cpp [hunk 6]
```diff
@@ -5914,19 +6144,40 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
+        if (assignedInterval2 != nullptr)
+        {
+            RefPosition* nextRefPosition2 = assignedInterval2->getNextRefPosition();
+            LsraLocation nextLocation2    = assignedInterval2->getNextRefLocation();
+            if ((nextLocation2 == refLocation) && !refPosition->isFixedRegRef && nextRefPosition2->RequiresRegister())
+            {
+                continue;
+            }
+            nextLocation = (nextLocation > nextLocation2) ? nextLocation : nextLocation2;
+        }
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Updated (https://github.com/dotnet/coreclr/pull/13145/commits/c737c00dc7902466f7e7cf946ec1ec5d2d6104ae)

File: src/jit/lsra.cpp [hunk 7]
```diff
@@ -5706,6 +5706,166 @@ regNumber LinearScan::tryAllocateFreeReg(Interval* currentInterval, RefPosition*
...
+//
+// Return Value:
+//    N/A
+//
+// Note: This helper is designed to be used only from allocateBusyReg()
+//
+void LinearScan::checkReferenceAt(RefPosition* recentAssignedRef, LsraLocation refLocation)
+{
+    // The assigned interval has a reference at this location - otherwise, we would have found
+    // this in tryAllocateFreeReg().
```
Comment (hqueue) [inline src/jit/lsra.cpp]: Because I couldn't make a clear statement, I just removed this line from a newly introduced helper `bool LinearScan::checkActiveInterval(Interval* interval, LsraLocation refLocation)`.
https://github.com/dotnet/coreclr/pull/13145/files#diff-93fb9832a03a9783e2a415b581fcb45cR5806

Can you suggested a comment if necessary ?

**Comment by hqueue** [comment]
@CarolEidt  I've update the PR with your suggestions, but not sure whether I've understood your feedback correctly.  PTAL  Thanks!

**Comment by CarolEidt** [comment]
Excellent - this is much cleaner!
@pgavlin or @BruceForstall could one of you also take a look? This is a big change, and I think another pair of eyes would be useful.

File: src/jit/lsra.cpp [hunk 8]
```diff
@@ -6010,21 +6266,51 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
+#ifdef _TARGET_ARM_
+            Interval* assignedInterval =
+                (farthestRefPhysRegRecord == nullptr) ? nullptr : farthestRefPhysRegRecord->assignedInterval;
+            Interval* assignedInterval2 =
+                (farthestRefPhysRegRecord2 == nullptr) ? nullptr : farthestRefPhysRegRecord2->assignedInterval;
+            RefPosition* nextRefPosition =
+                (assignedInterval == nullptr) ? nullptr : assignedInterval->getNextRefPosition();
+            RefPosition* nextRefPosition2 =
+                (assignedInterval2 == nullptr) ? nullptr : assignedInterval2->getNextRefPosition();
+            if (nextRefPosition != nullptr)
```
Comment (pgavlin) [inline src/jit/lsra.cpp]: Please use braces for these `if` statements.

File: src/jit/lsra.cpp [hunk 9]
```diff
@@ -6010,21 +6266,51 @@ regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPositio
...
+
+#ifdef _TARGET_ARM_
+        if (current->registerType == TYP_DOUBLE)
+        {
+            assert(genIsValidDoubleReg(foundReg));
+            unassignDoublePhysReg(farthestRefPhysRegRecord);
+        }
+        else
+#endif
+            unassignPhysReg(farthestRefPhysRegRecord, farthestRefPhysRegRecord->assignedInterval->recentRefPosition);
```
Comment (pgavlin) [inline src/jit/lsra.cpp]: Please use braces around this statement as well, i.e.

```
{
    unassignPhysReg(farthestRefPhysRegRecord, farthestRefPhysRegRecord->assignedInterval->recentRefPosition);
}
```

File: src/jit/lsra.cpp [hunk 10]
```diff
@@ -5705,6 +5705,245 @@ regNumber LinearScan::tryAllocateFreeReg(Interval* currentInterval, RefPosition*
...
+//
+// Return Value:
+//    True - iff the interval is active
+//    False - otherwise
+//
+// Note: This helper is designed to be used only from checkActiveIntervals()
+//
+bool LinearScan::checkActiveInterval(Interval* interval, LsraLocation refLocation)
+{
+    RefPosition* recentAssignedRef = interval->recentRefPosition;
```
Comment (pgavlin) [inline src/jit/lsra.cpp]: Nit: you can sink this load into the `if` statement, as we only need the `recentAssignedRef` if the interval is not active.

File: src/jit/lsra.cpp (hunk 8 above)
Comment (pgavlin) [inline src/jit/lsra.cpp]: Note that this also applies to the various other locations in the new helpers that are missing braces.

@jashook we may want to consider adding a format leg for ARM/RyuJIT.

File: src/jit/lsra.cpp (hunk 10 above)
Comment (hqueue) [inline src/jit/lsra.cpp]: Right, thanks!

File: src/jit/lsra.cpp (hunk 8 above)
Comment (hqueue) [inline src/jit/lsra.cpp]: I almost forgot that we need braces when there is a `else`  even when there is a single line statement. (
https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#121-braces-for-if)

Thanks :)

**Comment by hqueue** [comment]
@pgavlin I've update the PR. PTAL Thanks.
