### PR TITLE
JIT: fix issue with assertion prop on isinst helpers

### LINKED ISSUE #23039: Assertion failed 'assertion->op2.u1.iconFlags != 0'
See IL repro at the bottom. Please let me know if you need more info, or a repro of a different form.

- Save the IL below as test.il
- `ilasm test.il /dll`
- run amd64 CHK crossgen on the output:
-- `crossgen.exe /in test.dll /out test.dll.ni /nologo /verbose /platform_assemblies_paths "paths_to_il"`

Expected: successful compilation
Actual:

IL repro:
```
Opening input file
Preloading input file D:\scratch\crossgenrepros\test.dll
Compiling input file D:\scratch\crossgenrepros\test.dll
Compiling method TestClass`1[__Canon][System.__Canon]..ctor

Assert failure(PID 11620 [0x00002d64], Thread: 19148 [0x4acc]): Assertion failed 'assertion->op2.u1.iconFlags != 0' in 'TestClass`1[__Canon][System.__Canon]:.ctor(int,ref):this' (IL size 52)

    File: c:\users\markmil\source\repos\coreclr\src\jit\assertionprop.cpp Line: 1661
    Image: C:\Users\markmil\Source\Repos\PMIExperiment\CrossGenner\bin\Debug\coreclr\crossgen.exe
```

```
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Core
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly Test
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.
  .hash algorithm 0x00008004
  .ver 1:0:0:0
}
.module Test.dll
.imagebase 0x00400000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00020003    //  ILONLY 32BITPREFERRED

.class public auto ansi beforefieldinit TestClass`1<T>
	extends [mscorlib]System.Object
{
	// Nested Types
	.class nested private auto ansi sealed beforefieldinit NestedClass`1<T>
		extends [mscorlib]System.Object
	{
		// Fields
		.field public class [mscorlib]System.Collections.Generic.IEqualityComparer`1<!T> a

		// Methods
		.method public hidebysig specialname rtspecialname 
			instance void .ctor () cil managed 
		{
			// Method begins at RVA 0x6e3ac
			// Code size 7 (0x7)
			.maxstack 8

			IL_0000: ldarg.0
			IL_0001: call instance void [mscorlib]System.Object::.ctor()
			IL_0006: ret
		}

		.method public hidebysig 
			instance bool Equals (
				!T a,
				!T b
			) cil managed 
		{
			// Method begins at RVA 0x6e3b4
			// Code size 14 (0xe)
			.maxstack 8

			IL_0000: ldarg.0
			IL_0001: ldfld class [mscorlib]System.Collections.Generic.IEqualityComparer`1<!0> class TestClass`1/NestedClass`1<!T>::a
			IL_0006: ldarg.1
			IL_0007: ldarg.2
			IL_0008: callvirt instance bool class [mscorlib]System.Collections.Generic.IEqualityComparer`1<!T>::Equals(!0, !0)
			IL_000d: ret
		}
	}

	.method public hidebysig specialname rtspecialname 
		instance void .ctor (
			int32 maxSize,
			class [mscorlib]System.Collections.Generic.IEqualityComparer`1<!T> comparer
		) cil managed 
	{
		// Method begins at RVA 0x6e0d4
		// Code size 60 (0x3c)
		.maxstack 4
		.locals init (
			[0] object,
			[1] object
		)

		IL_0008: ldloc.1
		IL_0009: castclass class TestClass`1/NestedClass`1<!T>
		IL_000e: ldarg.2
		IL_000f: stfld class [mscorlib]System.Collections.Generic.IEqualityComparer`1<!0> class TestClass`1/NestedClass`1<!T>::a
		IL_0014: ldarg.0
		IL_0015: ldarg.1
		IL_0016: ldloc.0
		IL_0017: isinst class [mscorlib]System.Func`3<!T, !T, bool>
		IL_001c: brtrue.s IL_0030

		IL_001e: ldloc.1
		IL_001f: castclass class TestClass`1/NestedClass`1<!T>
		IL_0024: ldftn instance bool class TestClass`1/NestedClass`1<!T>::Equals(!0, !0)
		IL_002a: newobj instance void class [mscorlib]System.Func`3<!T, !T, bool>::.ctor(object, native int)
		IL_002f: stloc.0

		IL_0030: ldloc.0
		IL_0031: isinst class [mscorlib]System.Func`3<!T, !T, bool>
		IL_0036: call instance void class TestClass`1<!T>::.ctor(int32, class [mscorlib]System.Func`3<!0, !0, bool>)
		IL_003b: ret
	}
	
		.method public hidebysig specialname rtspecialname 
		instance void .ctor (
			int32 maxSize,
			class [mscorlib]System.Func`3<!T, !T, bool> fnEquals
		) cil managed 
	{
		.maxstack 8

		IL_0000: ldarg.0
		IL_0001: call instance void [mscorlib]System.Object::.ctor()
		IL_002a: ret
	}
	
} // end of class TestClass

```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
For calls to isinst helpers, morph may rearrange the order of args on the late
arg list, so examine the operands to ensure the right ones are passed into the
assertion creation code.

Added simplified test case.

Closes #23039.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@briansull PTAL
cc @dotnet/jit-contrib 

No diffs on x64 fx.

File: src/jit/assertionprop.cpp [hunk 1]
```diff
@@ -1989,11 +1989,23 @@ AssertionInfo Compiler::optAssertionGenJtrue(GenTree* tree)
     op2 = op1->gtCall.gtCallLateArgs->gtOp.gtOp2;
     op1 = op1->gtCall.gtCallLateArgs;
 
+    // For the assertion, ensure op1 is the object being tested.
+    // Morph may have swizzled the operand order.
+    GenTree* op1op = op1->gtOp.gtOp1;
```
Comment (mikedn) [inline src/jit/assertionprop.cpp]: Wouldn't be simpler/safer to get the calls args from `fgArgInfo`?

**Comment by mikedn** [comment]
As far as I can tell the problem is caused by assertions about null values. Should such assertions be generated? They seem pointless, though they're probably rare enough not to matter.

File: src/jit/assertionprop.cpp (hunk 1 above)
Comment (mikedn) [reply src/jit/assertionprop.cpp]: Ahm, looks like it doesn't work because `optCreateAssertion` is trying to guess that you want a subtype assertion from the fact that it receives a GT_LIST. Oh well...

Comment (AndyAyersMS) [reply src/jit/assertionprop.cpp]: The way assertions are created for helper calls is kind of clunky; the code wants to see the operands wrapped in list nodes.

**Comment by AndyAyersMS** [comment]
> Should such assertions be generated?

I'll probably leave it as is, unless there's some strong objection. Maybe we should teach VN that `isinst` on `null` is `null` and these cases would be optimized away instead.

**Comment by mikedn** [comment]
Definitely no objection. I tried this already, it does seem to work but I think it's a bit more difficult to be sure that it covers all possible cases.
