### PR TITLE
JIT: fix bug returning small structs on linux x64

### LINKED ISSUE #18522: Deterministic program outputs indeterministic results on Linux in release
On Ubuntu 14.04 using current HEAD (71f4199), the following program outputs 0 in debug but seemingly random values in release. On Windows, both debug and release output 0.
```csharp
struct S0
{
    public ushort F0;
}

struct S1
{
    public S0 F0;
    public ushort F1;
}

public class Program
{
    static S1 s_36;
    public static void Main()
    {
        s_36.F0 = M113();
        System.Console.WriteLine(s_36.F1);
    }

    static S0 M113()
    {
        return new S0();
    }
}
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit was retyping all calls with small struct returns as 32 bit ints
when generating code for linux x64. When the results of those calls were
assigned to fields the jit would use 32 bit stores which could corrupt
neighboring fields.

The fix is to keep the small int types for 8 and 16 ~~byte~~ bit structs so that
the corresponding stores are the right size.

Fixes #18522.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@CarolEidt PTAL
cc @dotnet/jit-contrib 

No diffs for windows. For linux this causes diff in both crossgen and pmi:
```
Crossgen Diffs for System.Private.CoreLib.dll, framework assemblies for x64 linuxnonjit.dll
Summary: (Lower is better)
Total bytes of diff: 2434 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
        1098 : System.Data.Common.dasm (0.04% of base)
         240 : Microsoft.DotNet.ProjectModel.dasm (0.05% of base)
         218 : Newtonsoft.Json.dasm (0.02% of base)
         198 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
         198 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.00% of base)
Top file improvements by size (bytes):
        -112 : System.Private.CoreLib.dasm (0.00% of base)
          -4 : System.Linq.Parallel.dasm (0.00% of base)
          -4 : System.Net.HttpListener.dasm (0.00% of base)
28 total files with size differences (3 improved, 25 regressed), 102 unchanged.
Top method regessions by size (bytes):
          84 : System.Data.Common.dasm - SqlByte:op_Explicit(struct):struct (18 methods)
          80 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Equals(ref):bool:this (2 methods)
          78 : System.Data.Common.dasm - SqlBoolean:op_Explicit(struct):struct (18 methods)
          64 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Combine(ref):ref (2 methods)
          42 : Microsoft.DotNet.ProjectModel.dasm - DependencyContextBuilder:GetCompilationOptions(ref):ref (2 methods)
Top method improvements by size (bytes):
         -68 : System.Private.CoreLib.dasm - DomainNeutralILStubClass:IL_STUB_CLRtoWinRT():struct:this (18 methods)
         -12 : System.Private.CoreLib.dasm - CLRIPropertyValueImpl:GetPoint():struct:this (2 methods)
         -12 : System.Private.CoreLib.dasm - CLRIPropertyValueImpl:GetSize():struct:this (2 methods)
         -10 : System.Private.CoreLib.dasm - ValueTuple:Create():struct (2 methods)
         -10 : System.Private.CoreLib.dasm - Task:Yield():struct (2 methods)
271 total methods with size differences (11 improved, 260 regressed), 141547 unchanged.
Completed analysis in 233.40s

PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 linuxnonjit.dll
Summary: (Lower is better)
Total bytes of diff: 839 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
         554 : System.Data.Common.dasm (0.04% of base)
         120 : Microsoft.DotNet.ProjectModel.dasm (0.06% of base)
         105 : Newtonsoft.Json.dasm (0.02% of base)
          51 : xunit.runner.utility.dotnet.dasm (0.05% of base)
          48 : xunit.execution.dotnet.dasm (0.02% of base)
Top file improvements by size (bytes):
        -339 : System.Reflection.Metadata.dasm (-0.09% of base)
         -38 : System.Net.HttpListener.dasm (-0.02% of base)
27 total files with size differences (2 improved, 25 regressed), 103 unchanged.
Top method regessions by size (bytes):
          42 : System.Data.Common.dasm - SqlByte:op_Explicit(struct):struct (9 methods)
          40 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Equals(ref):bool:this
          39 : System.Data.Common.dasm - SqlBoolean:op_Explicit(struct):struct (9 methods)
          32 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Combine(ref):ref
          21 : Microsoft.DotNet.ProjectModel.dasm - DependencyContextBuilder:GetCompilationOptions(ref):ref
Top method improvements by size (bytes):
         -94 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeMethodSignature(byref):struct:this (4 methods)
         -76 : System.Reflection.Metadata.dasm - CustomAttributeDecoder`1:DecodeValue(struct,struct):struct:this (4 methods)
         -49 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeMethodSpecificationSignature(byref):struct:this (4 methods)
         -49 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeLocalSignature(byref):struct:this (4 methods)
         -38 : System.Net.HttpListener.dasm - <CloseNetworkConnectionAsync>d__50:MoveNext():this
297 total methods with size differences (16 improved, 281 regressed), 169407 unchanged.
Completed analysis in 133.55s
```
PMI diffs on the new test case:
```diff
 ; Assembly listing for method GitHub_18522:Main():int
 ; Emitting BLENDED_CODE for X64 CPU with AVX
 ; optimized code
 ; rsp based frame
 ; partially interruptible
 ; Final local variable assignments
 ;
 ;# V00 OutArgs      [V00    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]  
 ;  V01 tmp1         [V01,T00] (  3,  6   )   byref  ->  rax        
-;  V02 tmp2         [V02    ] (  3,  3   )  struct ( 8) [rsp+0x10]   do-not-enreg[SF] ld-addr-op
-;  V03 tmp3         [V03    ] (  3,  3   )  ushort  ->  [rsp+0x10]   do-not-enreg[] V02.F0(offs=0x00) P-DEP
-;  V04 cse0         [V04,T01] (  4,  4   )    long  ->  [rsp+0x08]  
+;* V02 tmp2         [V02    ] (  0,  0   )  struct ( 8) zero-ref    ld-addr-op
+;* V03 tmp3         [V03    ] (  0,  0   )  ushort  ->  zero-ref    V02.F0(offs=0x00) P-INDEP
+;  V04 cse0         [V04,T01] (  4,  4   )    long  ->  [rsp+0x00]  
 ;
-; Lcl frame size = 24
+; Lcl frame size = 8
 G_M49330_IG01:
-       sub      rsp, 24
+       push     rax
 G_M49330_IG02:
        mov      rdi, 0xD1FFAB1E
        mov      esi, 3
        call     CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
        mov      rax, 0xD1FFAB1E
        mov      rax, gword ptr [rax]
        mov      word  ptr [rax+10], 170
        mov      rax, 0xD1FFAB1E
        mov      rax, gword ptr [rax]
        add      rax, 8
-       mov      word  ptr [rsp+10H], 0
-       mov      word  ptr [rsp+10H], 0
-       mov      edi, dword ptr [rsp+10H]
-       mov      dword ptr [rax], edi         // bug: wide store
+       mov      word  ptr [rax], 0           // fix: narrow store (+ const)
        mov      rax, 0xD1FFAB1E
        mov      rax, gword ptr [rax]
        cmp      word  ptr [rax+10], 170
        je       SHORT G_M49330_IG04
        xor      eax, eax
 G_M49330_IG03:
-       add      rsp, 24
+       add      rsp, 8
        ret      
 G_M49330_IG04:
        mov      eax, 100
 G_M49330_IG05:
-       add      rsp, 24
+       add      rsp, 8
        ret      
-; Total bytes of code 118, prolog size 4 for method GitHub_18522:Main():int
+; Total bytes of code 100, prolog size 1 for method GitHub_18522:Main():int

 ; Assembly listing for method GitHub_18522:M113():struct
 ; Emitting BLENDED_CODE for X64 CPU with AVX
 ; optimized code
 ; partially interruptible
 ; Final local variable assignments
 ;
-;  V00 loc0         [V00    ] (  2,  2   )  struct ( 8) [rsp+0x00]   do-not-enreg[SF] must-init ld-addr-op
+;* V00 loc0         [V00    ] (  0,  0   )  struct ( 8) zero-ref    ld-addr-op
 ;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]  
-;  V02 tmp1         [V02    ] (  2,  2   )  ushort  ->  [rsp+0x00]   do-not-enreg[] V00.F0(offs=0x00) P-DEP
+;* V02 tmp1         [V02    ] (  0,  0   )  ushort  ->  zero-ref    V00.F0(offs=0x00) P-INDEP
 ;
-; Lcl frame size = 8
+; Lcl frame size = 0
 G_M32228_IG01:
-       push     rax
-       xor      rax, rax
-       mov      qword ptr [rsp], rax
 G_M32228_IG02:
-       mov      word  ptr [rsp], 0
-       mov      eax, dword ptr [rsp]
+       xor      eax, eax
 G_M32228_IG03:
-       add      rsp, 8
        ret      
-; Total bytes of code 21, prolog size 7 for method GitHub_18522:M113():struct
+; Total bytes of code 3, prolog size 0 for method GitHub_18522:M113():struct
```

**Comment by AndyAyersMS** [comment]
I have not yet figured out if this is a regression. I believe the bug requires that the small struct be assigned directly to a field which is perhaps not as common as one might imagine.

**Comment by jakobbotsch** [comment]
This fixes most examples (https://github.com/jakobbotsch/Fuzzlyn/commit/a603f0ecacc846390dfd9acc73620ea1647e2751), but some still remain unfixed:

* [11923495345812789064](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/11923495345812789064.cs)
* [11049252875418439527](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/11049252875418439527.cs)
* [19651690852725464](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/19651690852725464.cs)
* [12352736376880721883](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/12352736376880721883.cs)
* [14212375628084965692](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/14212375628084965692.cs)
* [2772307662329830091](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/2772307662329830091.cs)
* [9665896507812706987](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/9665896507812706987.cs)
* [9570928422850257620](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/9570928422850257620.cs)
* [7491069974763601721](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/7491069974763601721.cs)
* [5049987370376495039](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/5049987370376495039.cs)

I can recheck when you make updates. 😄

**Comment by AndyAyersMS** [comment]
@jakobbotsch thanks much! I'll look at the new examples. It's really nice to have Fuzzlyn double-checking things. Keep up the good work.

[Arm](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_flow_prtest/1199/) and [Arm64](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_flow_prtest/1200/) failures look like the masked load tests. I though these were disabled?

**Comment by CarolEidt** [comment]
> Arm and Arm64 failures look like the masked load tests. I though these were disabled?

@jashook indicates that they still need to be removed from the .lst files, and he'll do so shortly.

**Comment by jashook** [comment]
#18569 addresses arm(64) failures

**Comment by AndyAyersMS** [comment]
First new example [11923495345812789064](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/11923495345812789064.cs) still showing wide stores... 
```asm
;;; windows
       48B96829AC14F8010000 mov      rcx, 0x1F814AC2968
       488B09               mov      rcx, gword ptr [rcx]
       4883C108             add      rcx, 8
       C60100               mov      byte  ptr [rcx], 0

;;; linux
       48BF6829982951010000 mov      rdi, 0x15129982968
       488B3F               mov      rdi, gword ptr [rdi]
       4883C708             add      rdi, 8
       C644241000           mov      byte  ptr [rsp+10H], 0
       C644241000           mov      byte  ptr [rsp+10H], 0
       8B442410             mov      eax, dword ptr [rsp+10H]
       8907                 mov      dword ptr [rdi], eax   // bug
```

**Comment by jakobbotsch** [comment]
> (edited: oops, was using old jits -- with the fix above things look to be correct...)

Ooops. It appears the bug is still there before reduction, but the reduced example I have posted does not have the bug (i.e. the reducer needs to be rerun again to display the new variant required).
I have verified that at least `11049252875418439527` and `19651690852725464` have the issue.

**Comment by AndyAyersMS** [comment]
In [11049252875418439527](https://github.com/jakobbotsch/Fuzzlyn/blob/a603f0ecacc846390dfd9acc73620ea1647e2751/examples/reduced/11049252875418439527.cs) there is a 6 byte struct `S0` returned an assigned. Windows assigns to it in two steps 4 bytes then 2. Linux does it in one step of 8 bytes.
```asm
;;; windows
       8B10                 mov      edx, dword ptr [rax]
       8911                 mov      dword ptr [rcx], edx
       668B5004             mov      dx, word  ptr [rax+4]
       66895104             mov      word  ptr [rcx+4], dx

;;; linux
       488B4016             mov      rax, qword ptr [rax+22]
       4889470E             mov      qword ptr [rdi+14], rax   // writes an extra 2 bytes
```
Implication is that if we are indeed going to return non-power of two sized structs in registers then we need a different strategy to unpack these on the caller side -- we can't just map them to the normal power of two int type sizes (unless it's "safe" to expand the destination size too, which it sometimes is). So my fix above likely only works if the struct being copied is 1, 2, or 4 bytes. We also need to properly handle sizes 3, 5, 6, and 7.

**Comment by jakobbotsch** [comment]
Here are the rereduced examples:
* [11923495345812789064](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/11923495345812789064.cs)
* [11049252875418439527](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/11049252875418439527.cs)
* [19651690852725464](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/19651690852725464.cs)
* [12352736376880721883](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/12352736376880721883.cs)
* [14212375628084965692](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/14212375628084965692.cs)
* [2772307662329830091](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/2772307662329830091.cs)
* [9665896507812706987](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/9665896507812706987.cs)
* [9570928422850257620](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/9570928422850257620.cs)
* [7491069974763601721](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/7491069974763601721.cs)
* [5049987370376495039](https://github.com/jakobbotsch/Fuzzlyn/blob/299fdaab69a909af5a29196bf222b68f96ecedb3/examples/reduced/5049987370376495039.cs)
It may also be informative to look at the commit diff:
https://github.com/jakobbotsch/Fuzzlyn/commit/299fdaab69a909af5a29196bf222b68f96ecedb3

Sorry about the confusion earlier.

**Comment by AndyAyersMS** [comment]
No problem. I haven't checked them all, but I suspect all these new cases have `S0` sizes that are not powers of two.

One thought as to how to fix the size 3, 5, 6, 7 cases is to flag when the "primitive type" produced by `getPrimitiveTypeForStruct` is larger than the actual type returned, and force the call to return the result to a temp which can be safely widened to a power of two size. Then reinterpret the temp as a struct and assign from the temp to the destination.

Not sure if this is viable though.

Also may be clunky if/when we inline as we may see what look like type mismatches that could block inlines, or reinterpret/copy chains (struct -> int -> int  -> struct) that don't nicely optimize away.

**Comment by AndyAyersMS** [comment]
And just for the record: 
* On windows x86/x64 we won't return non-power-of-2 sized structs in registers.
* Windows arm32 and arm64 should have similar bugs with the 3, 5, 6, 7 size cases unless there is some compensating magic I have overlooked.

**Comment by CarolEidt** [comment]
I am probably thinking about this too simplistically, but I think the right thing to do is to *not* change the type in the non-power-of-2 case, and simply allow struct assignments to be created as needed. Then morph should decide (hopefully correctly) when a copy is required.
The wrinkle is that it may be the case that there are assumptions that we don't assign a non-scalar from a call. But I don't know why it shouldn't work, as long as the LHS of the assignment is a node that returns a valid struct handle from `gtGetStructHandleIfPresent()`

**Comment by AndyAyersMS** [comment]
Yeah, I had that idea too -- basically just use the windows rules.

By doing this we would (I believe) diverge from the SysV ABI for some kinds of small structs. Not sure if that has a ripple effect anywhere.

**Comment by CarolEidt** [comment]
> By doing this we would (I believe) diverge from the SysV ABI

I was actually assuming that the RHS of the struct assignment could simply be the call (i.e. the register result), and we would handle any necessary temp creation in `fgMorphCopyBlock`, but it is probably the case that it would require more complexity than I'm imagining.

**Comment by AndyAyersMS** [comment]
Ah, I see. I might need to disentangle things a bit to make sure we still think of it as something returned by value ... but it might work.

**Comment by AndyAyersMS** [comment]
What I'm leaning towards is roughly:
* add a new struct passing kind, something like `SPK_EnclosingPrimitiveType` -- to indicate that the value is returned in a single register that is larger than the actual return type. In those cases, `getReturnTypeForStruct` would return `TYP_STRUCT`.
* `ReturnTypeDesc::InitializeStructReturnType` would handle this case like it does `SPK_PrimitiveType` but with different asserts, keeping the return type as `TYP_STRUCT`.
* Because of this we'd no longer retype those odd-sized struct returning calls, and morph would handle them as struct assigns.
* We would still retype if the struct was 1, 2, 4, or 8 bytes and would get somewhat better codegen for those cases.

**Comment by AndyAyersMS** [comment]
Still wondering about the returned via two register cases, though maybe the really odd ones require ARM64?

@jakobbotsch if you get a chance to tweak Fuzzlyn, you might try playing around with cases where the assigned structs are 9-15 bytes in size.

**Comment by CarolEidt** [comment]
@AndyAyersMS - that sounds like the right direction.

> We would still retype if the struct was 1, 2, 4, or 8 bytes and would get somewhat better codegen for those cases.

It would be good to (eventually) consider whether we could get the same codegen without retyping there. IIRC `fgMorphCopyBlock` should take care of those cases via `fgMorphOneAsgBlockOp`, as long as we can defer any temp creation until that time.

**Comment by AndyAyersMS** [comment]
Updated to try and handle 3, 5, 6, and 7 byte struct cases. May be a bit ragged, but is holding up on the handful of tests I have locally.

Will post diff stats later and look at more examples.

**Comment by AndyAyersMS** [comment]
No new PMI or Crossgen FX diffs for Linux. Will run PMI diffs on tests overnight.

**Comment by AndyAyersMS** [comment]
No new test diffs other than on the newly added test case. Diffs there:
```diff
-       mov      rdi, qword ptr [rdi+22]
-       mov      qword ptr [rax+14], rdi    // store 8 bytes at rax + 14 -- bad
+       lea      rdi, bword ptr [rdi+22]
+       add      rax, 14
+       mov      esi, dword ptr [rdi]
+       mov      dword ptr [rax], esi       // store 4 bytes at rax + 14 -- ok
+       mov      si, word  ptr [rdi+4]
+       mov      word  ptr [rax+4], si      // store 2 bytes at rax + 18 -- ok
...
-; Total bytes of code 124, prolog size 10 for method GitHub_18522_1:Main():int
+; Total bytes of code 136, prolog size 10 for method GitHub_18522_1:Main():int
```

**Comment by jakobbotsch** [comment]
I can confirm that fixes all the previous examples, and also a few others I thought were unrelated.
https://github.com/jakobbotsch/Fuzzlyn/commit/d8c9dbd43817233c4abe0d85d8030bc556554357
(ignore 11949841452559086614, something very strange seems to be going on here, I'm trying to get to the bottom of that one...)

**Comment by jakobbotsch** [comment]
> @jakobbotsch if you get a chance to tweak Fuzzlyn, you might try playing around with cases where the assigned structs are 9-15 bytes in size.

Fuzzlyn already (probabilistically) generates structs of this size. It does not appear to have found anything in this area.

**Comment by AndyAyersMS** [comment]
Did a bit of testing over on OSX with older dotnet SDKs, and as far as I can tell this bug goes back to at least Core 1.1.

File: src/jit/importer.cpp [hunk 1]
```diff
@@ -8465,7 +8465,14 @@ GenTree* Compiler::impFixupCallStructReturn(GenTreeCall* call, CORINFO_CLASS_HAN
         if (retRegCount == 1)
         {
             // struct returned in a single register
-            call->gtReturnType = retTypeDesc->GetReturnRegType(0);
+            // retype iff struct size exactly matches integer type size.
+            if (retTypeDesc->IsEnclosingType())
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/jit/importer.cpp]: I had some JITDUMP stuff there at one point. Will update.

File: src/jit/lclvars.cpp [hunk 2]
```diff
@@ -141,7 +141,8 @@ void Compiler::lvaInitTypeRef()
         Compiler::structPassingKind howToReturnStruct;
         var_types                   returnType = getReturnTypeForStruct(retClsHnd, &howToReturnStruct);
 
-        if (howToReturnStruct == SPK_PrimitiveType)
+        // We can safely widen the return type for enclosed structs.
+        if ((howToReturnStruct == SPK_PrimitiveType) || (howToReturnStruct == SPK_EnclosingType))
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/jit/lclvars.cpp]: Hmm, not sure. I should look at this part more closely.

There is some code in morph that can be simplified now as SPK_Primitive type implies power of two sizes.

**Comment by AndyAyersMS** [comment]
If I modify the _1 test case so M16 is noinline I hit an assert:
```
Assertion failed 'child->isContained()' in 'Program:Main()' (IL size 43)
    File: d:\repos\coreclr\src\jit\lsraxarch.cpp Line: 489
    Image: D:\repos\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```
so need to look into that too.

**Comment by CarolEidt** [comment]
@AndyAyersMS - let me know if you'd like me to help with looking into the assert. I'm guessing that there's an `ADDR` in a position where `Lowering` isn't expecting it, so the expression isn't getting lowered correctly.

**Comment by CarolEidt** [comment]
Ah, I think it's a bit worse than the retying issue. I had thought (misremembered) that morph would copy the src to memory in this case, but apparently not. Ideally, `Lowering` would handle an assignment like this as-is, producing `STORE_BLK(6)(dstAddr, CALL)` and codegen would correctly store the right bits into the right offsets from the register produced by the call. But for the time being I think that somewhere the result has to be copied to a local that gets forced to the stack.

**Comment by AndyAyersMS** [comment]
Or perhaps (since morph really wants to retype) we need to always rewrite such trees to return these enclosed structs via temps which we can subsequently reinterpret as structs.

**Comment by CarolEidt** [comment]
Makes sense. Sorry if I led you down the wrong path.

**Comment by AndyAyersMS** [comment]
No worries. I don't mind having to try a few different approaches. It helps highlight the tricky parts and leads to a better set of test cases.

**Comment by AndyAyersMS** [comment]
Want to make sure we cover the bases here, so at least 3 cases to consider when returning a struct that is smaller than the native return type:
* call is never an inline candidate
* call is an inline candidate that doesn't get inlined
* call is an inline candidate and gets inlined

**Comment by AndyAyersMS** [comment]
Am really tempted to look at what deferring all this retyping would look like. Probably just a different but comparable set of issues...

**Comment by AndyAyersMS** [comment]
Working through issues fixing things up when the struct returning call is an inline candidate. Getting close, I think. But there are more cases to handle:
* call is an inline candidate that gets inlined and inlinee body is also a call
  * and was never an inline candate
  * also got inlined
  * was a failed inline

Luckily I don't think this cascades any further.

The upshot is that calls get retyped at various points depending on whether they are inline candidates or not. So post-inline retyping must be conditional as the necessary transformations may have already happened.

There may be similar issues around tail calls too (another case where we might defer retyping during importation). But perhaps less pressing since there is no "destination" for the call's return value.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib two big changes since you all last reviewed:

* for the "enclosing type" small structs, copy return value to temp during import if we know the call will remain a call
* if we defer doing copy to temp in the importer because the call is an inline candidate, do it later once we've resolved the fate of the inline.

Test cases to hopefully cover the spectrum of possibilities fairly well.

Still thinking of ditching the "enclosing type" concept since everwhere we check it we have the class handle and so can refetch the size and compare it to the primitive size.

Now see a few more diffs in normal PMI runs over FX. 
```
PMI Diffs for System.Private.CoreLib.dll, framework assemblies for x64 linuxnonjit.dll
Summary:
(Lower is better)
Total bytes of diff: 839 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
         554 : System.Data.Common.dasm (0.04% of base)
         120 : Microsoft.DotNet.ProjectModel.dasm (0.06% of base)
         105 : Newtonsoft.Json.dasm (0.02% of base)
          51 : xunit.runner.utility.dotnet.dasm (0.05% of base)
          48 : xunit.execution.dotnet.dasm (0.02% of base)
Top file improvements by size (bytes):
        -339 : System.Reflection.Metadata.dasm (-0.09% of base)
         -38 : System.Net.HttpListener.dasm (-0.02% of base)
27 total files with size differences (2 improved, 25 regressed), 103 unchanged.
Top method regessions by size (bytes):
          42 : System.Data.Common.dasm - SqlByte:op_Explicit(struct):struct (9 methods)
          40 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Equals(ref):bool:this
          39 : System.Data.Common.dasm - SqlBoolean:op_Explicit(struct):struct (9 methods)
          32 : Microsoft.DotNet.ProjectModel.dasm - CommonCompilerOptions:Combine(ref):ref
          21 : Microsoft.DotNet.ProjectModel.dasm - DependencyContextBuilder:GetCompilationOptions(ref):ref
Top method improvements by size (bytes):
         -94 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeMethodSignature(byref):struct:this (4 methods)
         -76 : System.Reflection.Metadata.dasm - CustomAttributeDecoder`1:DecodeValue(struct,struct):struct:this (4 methods)
         -49 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeMethodSpecificationSignature(byref):struct:this (4 methods)
         -49 : System.Reflection.Metadata.dasm - SignatureDecoder`2:DecodeLocalSignature(byref):struct:this (4 methods)
         -38 : System.Net.HttpListener.dasm - <CloseNetworkConnectionAsync>d__50:MoveNext():this
297 total methods with size differences (16 improved, 281 regressed), 169409 unchanged.
```

The overall diff impact is still small and the regressions are mostly necessary diffs. Some of the new diffs happen in methods that return a byte-sized struct:
```diff
 ; ============================================================
 ; Assembly listing for method System.Reflection.Metadata.MethodSignature`1[__Canon][System.__Canon]:get_ReturnType():ref:this
 ; Emitting BLENDED_CODE for X64 CPU with AVX

 G_M15744_IG01:
 
 G_M15744_IG02:
-       8B4710               mov      eax, dword ptr [rdi+16]
+       480FBE4710           movsx    rax, byte  ptr [rdi+16]
 
 G_M15744_IG03:
        C3                   ret      
 
-; Total bytes of code 4, prolog size 0 for method System.Reflection.Metadata.MethodSignature`1[Int32][System.Int32]:get_Header():struct:this
+; Total bytes of code 6, prolog size 0 for method System.Reflection.Metadata.MethodSignature`1[Int32][System.Int32]:get_Header():struct:this
```
Previously bytes 1-3 might contain unrelated stuff.

**Comment by AndyAyersMS** [comment]
Hmm, looks like a rebase is going to be needed. When I do that I'll also reorganize so all the code commits are first (and squashed) and the test commits second (likewise squashed). Let me see how this holds up in testing before doing any of that.

**Comment by AndyAyersMS** [comment]
The new CoreFX legs ([checked](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/5/), [release](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_corefx_innerloop_prtest/6/)) seem to be generally broken.

No diffs on windows over FX with both crossgen and PMI.

**Comment by AndyAyersMS** [comment]
The new _7 test failed for arm32/arm64. Investigating.

**Comment by AndyAyersMS** [comment]
Looks like ARM64 / Windows needs similar "return via temp" logic for the 3, 5, 6, 7 size cases... so more cases to handle.

File: src/jit/compiler.cpp [hunk 3]
```diff
@@ -1004,37 +1004,54 @@ var_types Compiler::getReturnTypeForStruct(CORINFO_CLASS_HANDLE clsHnd,
...
-        assert(structDesc.passedInRegisters == true);
+        if (structDesc.eightByteClassifications[0] == SystemVClassificationTypeSSE)
+        {
+            // If this is returned as a floating type, use that.
+            // Otherwise, we'll use the general case - we don't want to use the "EightByteType"
+            // directly, because it returns `TYP_INT` for any integral type <= 4 bytes, and
+            // we need to preserve small types.
+            useType           = GetEightByteType(structDesc, 0);
+            howToReturnStruct = SPK_PrimitiveType;
+        }
```
Comment (briansull) [inline src/jit/compiler.cpp]: This looks correct,  you might want to add that for the other cases `useType` will remain TYP_UNKNOWN instead of changing to TYP_INT.

File: src/jit/compiler.cpp [hunk 4]
```diff
@@ -1004,37 +1004,54 @@ var_types Compiler::getReturnTypeForStruct(CORINFO_CLASS_HANDLE clsHnd,
...
+        {
+            if (structSize == genTypeSize(useType))
+            {
+                // Currently: 1, 2, 4, or 8 byte structs
+                howToReturnStruct = SPK_PrimitiveType;
+            }
+            else
+            {
+                // Currently: 3, 5, 6, or 7 byte structs
+                assert(structSize <= genTypeSize(useType));
```
Comment (briansull) [inline src/jit/compiler.cpp]: This assert should be less than:

` assert(structSize < genTypeSize(useType));`

File: src/jit/compiler.cpp [hunk 5]
```diff
@@ -1004,37 +1004,54 @@ var_types Compiler::getReturnTypeForStruct(CORINFO_CLASS_HANDLE clsHnd,
...
     SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR structDesc;
     eeGetSystemVAmd64PassStructInRegisterDescriptor(clsHnd, &structDesc);
 
-    // If we have one eightByteCount then we can set 'useType' based on that
     if (structDesc.eightByteCount == 1)
     {
-        // Set 'useType' to the type of the first eightbyte item
-        useType = GetEightByteType(structDesc, 0);
-        assert(structDesc.passedInRegisters == true);
+        if (structDesc.eightByteClassifications[0] == SystemVClassificationTypeSSE)
```
Comment (briansull) [inline src/jit/compiler.cpp]: You could also add:

`assert(structSize <= sizeof(double)));`

As the code at 1031 which finalized the value of useType depends on thsi property.

File: src/jit/compiler.h [hunk 6]
```diff
@@ -4223,6 +4227,8 @@ class Compiler
     {
         SPK_Unknown,       // Invalid value, never returned
         SPK_PrimitiveType, // The struct is passed/returned using a primitive type.
+        SPK_EnclosingType, // Like SPK_Primitive type, but used for return types that
+                           //  are not a power of two byte size.
```
Comment (briansull) [inline src/jit/compiler.h]: Comment should be more like:
```
// Like SPK_Primitive type,  but used for return types that 
// require a primative type temp that is larger that the struct size.
// Currently used for structs of sizes: 3,5,6 or 7 bytes
```

File: src/jit/compiler.cpp (hunk 3 above)
Comment (AndyAyersMS) [reply src/jit/compiler.cpp]: Added comment.

File: src/jit/compiler.cpp (hunk 4 above)
Comment (AndyAyersMS) [reply src/jit/compiler.cpp]: Fixed

File: src/jit/compiler.cpp (hunk 5 above)
Comment (AndyAyersMS) [reply src/jit/compiler.cpp]: Done.

File: src/jit/compiler.h (hunk 6 above)
Comment (AndyAyersMS) [reply src/jit/compiler.h]: I am still not sure if I'm keeping this -- let me work through arm32 / arm64 and see how I feel once that's fixed.

**Comment by AndyAyersMS** [comment]
Rebased to get past test list conflicts...

**Comment by AndyAyersMS** [comment]
BTW, I still expect arm32/arm64 to fail on some of the new tests -- in fact I need to understand why the 6 byte struct cases **are not** failing. Perhaps there is magic somewhere that I could extend to the 3 byte case.

**Comment by AndyAyersMS** [comment]
Result is as expected: Arm64 fails all the new tests; Arm32 only fails the _7 test since that tests a 3 byte struct, not a 6 byte struct. No magic.

**Comment by AndyAyersMS** [comment]
Ok, hopefully this is functionally complete. `SPK_EnclosingType` is still there and I've updated the comment per Brian's suggestion.

**Comment by AndyAyersMS** [comment]
[FMA test](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_flow_prtest/4770/) failed on Ubuntu -- no PMI diffs in this test, so am going to wager this was our old friend `Random` (see #10585).

@dotnet-jit retest Ubuntu x64 Checked Innerloop Build and Test

**Comment by AndyAyersMS** [comment]
Re FMA failing: also #18467

File: tests/arm/Tests.lst [hunk 7]
```diff
@@ -94724,3 +94724,67 @@ MaxAllowedDurationSeconds=600
...
+
+[GitHub_18522_5.cmd_11905]
+RelativePath=JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_5\GitHub_18522_5.cmd
+WorkingDir=JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_5
+Expected=0
+MaxAllowedDurationSeconds=600
+Categories=EXPECTED_PASS
+HostStyle=0
+
+[GitHub_18522_6.cmd_11903]
```
Comment (jakobbotsch) [inline tests/arm/Tests.lst]: `_11906`? Same below.

Comment (jakobbotsch) [reply tests/arm/Tests.lst]: Is this actually important?

Comment (AndyAyersMS) [reply tests/arm/Tests.lst]: Not sure -- but now I remember there is a tool to regenerate these, so I suuppose we should just use that.

tests\scripts\lst_creator.py

It would be nice if the tool output included the command line used to create that output.

Comment (jashook) [reply tests/arm/Tests.lst]: The tool is a little funky because it does a recursive discovery of the tests. Hopefully with the work @sbomer is doing this legacy stuff just goes away. I think the easier approach here is to just keep it as it is, the numbering is not extremely important, it is just output by the tool to make sure the tags are unique. GitHub_18522_6.cmd_11903 should be unique enough.

Comment (jashook) [reply tests/arm/Tests.lst]: Note that the tool will strip the number anyways, so this is not going to break its input either.

**Comment by AndyAyersMS** [comment]
Rebased and reordered so all the code commits (unsquashed, will squash on merge) come first and all the test commits (now squashed) come second.

**Comment by AndyAyersMS** [comment]
@briansull @CarolEidt would appreciate one more round of review (mainly those last two non-test commits) as this is a new part of the change that extends the handling to windows ABIs for arm.

File: src/jit/lclvars.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (briansull) [reply src/jit/lclvars.cpp]: You could update this GitHub comment now that you are done.

[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/jit/lclvars.cpp]: That code was for arg passing, not for return values. So nothing to do there.

File: src/jit/flowgraph.cpp [hunk 8]
```diff
@@ -22324,30 +22324,105 @@ Compiler::fgWalkResult Compiler::fgUpdateInlineReturnExpressionPlaceHolder(GenTr
         }
     }
 
-#if FEATURE_MULTIREG_RET
-
-    // Did we record a struct return class handle above?
+#if FEATURE_MULTIREG_RET || defined(UNIX_AMD64_ABI)
```
[the remark this answers is not in the document]
Comment (AndyAyersMS) [reply src/jit/flowgraph.cpp]: Latest version just has FEATURE_MULTIREG_RET.
