### PR TITLE
New fix for #26417 - Don't allow the hoisting of GT_CLS_VARs that were assigned a constant value.

### LINKED ISSUE #26417: JIT compiler bug: Incorrect caching of loop variable
**Environment:**

•Visual Studio 2019 version 16.2.3
•.Net 4.8
•Console application
•x64 build
•Release build

**Code to reproduce:**

```
using System;

namespace Demo
    {
        class Program
        {
            static int _a;

            static void Main()
            {
                _a = 1;

                while (_a == 1)
                {
                    Console.WriteLine(_a);
                    _a = 0;
                }
            }
        }
    }

```

**Expected Behavior**:
"1" is printed once and the program terminates.

**Actual Behavior**:
"0" is repeatedly printed; the program does not terminate.

**Notes**
If you declare _a as volatile, it works OK.
If you initialise _a as static int _a = 0; it works.

This was reported on StackOverflow here: https://stackoverflow.com/questions/57693386/vs-2019-optimize-code-in-release-mode-broken

category:correctness
theme:optimization
skill-level:expert
cost:large

### PR DESCRIPTION
**Pull request by briansull**
Fixes #26417 - JIT compiler bug: Incorrect caching of loop variable
Contributes to issue  #7147 - JIT: Loop hoisting re-ordering exceptions
Added the Test case for Issue 26417

### CODE REVIEW

**Comment by briansull** [comment]
@mikedn PTAL
@erozenfeld

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

File: src/jit/optimizer.cpp [hunk 1]
```diff
@@ -7003,22 +7015,32 @@ void Compiler::optHoistLoopBlocks(unsigned loopNum, ArrayStack<BasicBlock*>* blo
...
                 if (!treeIsInvariant)
                 {
+                    // Here we have a tree that is not loop invariant and we thus cannot hoist
                     treeIsHoistable = false;
+
+                    // Check if we should also clear m_beforeSideEffect.
+                    if (m_beforeSideEffect)
+                    {
+                        // If 'tree' can throw an exception then we need to set m_beforeSideEffect to false.
+                        if (tree->OperMayThrow(m_compiler))
```
Comment (erozenfeld) [inline src/jit/optimizer.cpp]: This call only checks is the operation itself may throw; it doesn't check whether the children may throw. I think the right check is `if ((tree->gtFlags & GTF_EXCEPT) != 0)`.

Also, I think this check belongs to the block below starting with https://github.com/dotnet/coreclr/pull/26952/files#diff-15cd21de3f1ffaa677e7da145576d60cL7013-L7016
(where we also checks for calls and assignments) so that it's done regardless of `treeIsInvariant` value.

Comment (briansull) [reply src/jit/optimizer.cpp]: I used to have that check, but I refined it to this one.  

When we get here we currently have `m_beforeSideEffect `set to true, and have a tree whose current node is no longer invariant, but it's children were invariant and so are ready to be hoisted out of the loop.

With the old check we would observe any`GTF_EXCEPT ` flag bubbling up from the child nodes, and thus would clear `m_beforeSideEffect`, thus prevent us from doing any further hoisting, even though we haven't moved an expression across another node with an exception side effect.

Comment (briansull) [reply src/jit/optimizer.cpp]: Related test mentioned in #26865

Comment (briansull) [reply src/jit/optimizer.cpp]: Looks like my current change also regresses  JI\Regression\CLR-x86-JIT\V1-M12-Beta2\b79250\b79250\b79250.cmd (x86 checked)

**Comment by BruceForstall** [comment]
I think it's advisable to trigger outerloop and outerloop stress jobs on this change, when you consider it ready.

**Comment by briansull** [comment]
This change isn't particularly dangerous; as it is a chnage that pessimizes a somewhat uncommon optimization, (the hoisting invariant expressions out of loops).  So there isn't a worry about introducing incorrectness.

**Comment by briansull** [comment]
@erozenfeld PTAL

File: src/jit/optimizer.cpp [hunk 2]
```diff
@@ -7003,22 +7015,36 @@ void Compiler::optHoistLoopBlocks(unsigned loopNum, ArrayStack<BasicBlock*>* blo
...
+                        m_beforeSideEffect = false;
+                    }
+                }
                 // For this purpose, we only care about memory side effects.  We assume that expressions will
                 // be hoisted so that they are evaluated in the same order as they would have been in the loop,
-                // and therefore throw exceptions in the same order.  (So we don't use GTF_GLOBALLY_VISIBLE_SIDE_EFFECTS
-                // here, since that includes exceptions.)
+                // and therefore throw exceptions in the same order.
+                // (So we don't use GTF_GLOBALLY_VISIBLE_SIDE_EFFECTS here, since that includes exceptions.)
+                //
```
Comment (erozenfeld) [inline src/jit/optimizer.cpp]: This comment is no longer accurate.

File: src/jit/optimizer.cpp [hunk 3]
```diff
@@ -7003,22 +7015,36 @@ void Compiler::optHoistLoopBlocks(unsigned loopNum, ArrayStack<BasicBlock*>* blo
...
-            //  or if we see an assignment to global we set it to false.
+            // Next check if we need to set 'm_beforeSideEffect' to false.
             //
-            // If we are already set to false then we can skip these checks
+            // If we have already set it to false then we can skip these checks
             //
             if (m_beforeSideEffect)
             {
+                // Is the value of the whole tree loop invariant?
+                if (!treeIsInvariant)
```
Comment (erozenfeld) [inline src/jit/optimizer.cpp]: I think the right check here is `if (!treeIsHoistable)`. If the tree is invariant and can throw but we don't hoist it, we need to set `m_beforeSideEffect` to `false`.

Comment (briansull) [reply src/jit/optimizer.cpp]: Unfortunately we have trees that switch back and forth from having treeIsHoistable as true to false and back to true.
Only the switch to treeIsInvariant is permanent.

One such tree that is important to be able to hoist is an invariant array read inside a loop:

Because ARR_BOUNDS_CHECK is a void, (it doesn't produce a value) it isn't a CSE candidate,
and anything that isn't a CSE candidate has treeIsHoistable  set to false.
It's parent node is a GT_COMMA which produces a ushort value and will be hoistable.


```
               [000054] ---XG+------                 +--*  COMMA     ushort
               [000047] ---X-+------                 |  +--*  ARR_BOUNDS_CHECK_Rng void  
               [000009] -----+------                 |  |  +--*  LCL_VAR   int    V02 loc0         
               [000046] ---X-+------                 |  |  \--*  ARR_LENGTH int   
               [000008] -----+------                 |  |     \--*  LCL_VAR   ref    V01 arg1         
               [000010] a--XG+------                 |  \--*  IND       ushort
               [000053] -----+------                 |     \--*  ADD       byref 
               [000044] -----+------                 |        +--*  LCL_VAR   ref    V01 arg1         
               [000052] -----+------                 |        \--*  ADD       long  
               [000050] -----+------                 |           +--*  LSH       long  
               [000048] -----+------                 |           |  +--*  CAST      long <- int
               [000045] i----+------                 |           |  |  \--*  LCL_VAR   int    V02 loc0         
               [000049] -----+-N----                 |           |  \--*  CNS_INT   long   1
               [000051] -----+------                 |           \--*  CNS_INT   long   12 Fseq[#FirstElem]
```

File: src/jit/optimizer.cpp (hunk 2 above)
Comment (briansull) [reply src/jit/optimizer.cpp]: I can remove the second part of this comment, but the code before this is unchanged, so the comment is still explaining what it does.

Remove:
`(So we don't use GTF_GLOBALLY_VISIBLE_SIDE_EFFECTS here, since that includes exceptions.)`

File: src/jit/optimizer.cpp (hunk 3 above)
Comment (erozenfeld) [reply src/jit/optimizer.cpp]: We may still have a hole here if we encounter a tree that's invariant and can throw an exception but we never hoist it (directly or as part of a parent). I tried to construct an example but ran into another bug where we do an incorrect exception reordering even without a loop: https://github.com/dotnet/coreclr/issues/27027.
I'm ok with this fix as it makes us "more correct" than before but we'll need to revisit this code.
