### PR TITLE
Remove tailcall limitations on unix64 and arm64

### LINKED ISSUE #11717: [amd64 Unix|arm64] fastTailCall stack fixup NYI if TYP_STRUCT
The Issue:

Lowering::LowerFastTailCall will fix up the stack before the jump. In the case that the caller's stack frame has a TYP_STRUCT which needs to be overwritten we would create a temp struct and pass it currently according to the windows ABI. Currently we will not execute this code path because we make several choices before lowering the tail call that keep this from being true. First, we will force create a temp object for structs passed on the stack, so we will simply use the def of the temp we made during morph instead of creating a temp later. Second, we will decide not to fast tail call on amd64 unix and arm64 much more liberally than on amd64 Windows see #2666 for more information.

The closest I could come to a repro is:

<pre>
using System;

public struct A
{
    public int a;
    public int b;
}

class TailCallStructPassing
{
    public static int bar(int count, A temp)
    {
        if (count < 100)
        {
            return count;
        }

        else
        {
            count -= 100;
            return bar(count, temp);
        }
    }

    /// Args
    ///
    /// (0) - A one
    /// (1) - A two
    /// (2) - A three
    /// (3) - A four
    /// (4) - A five
    /// (5) - A six
    /// (6) - int b
    /// (7) - int c
    /// (8) - int d
    /// (9) - int e
    /// (10) - int f
    /// (11) - int g
    /// (12) - int h
    /// (13) - int i
    /// (14) - int j
    /// (15) - A temp
    /// (16) - int k
    /// (17) - int l
    /// (18) - int m
    /// (19) - int n
    /// (20) - int o
    /// (21) - int p
    /// (22) - int q
    /// (23) - int r
    /// (24) - int s
    /// (25) - int t
    /// (26) - int u
    /// (27) - int decision
    /// (28) - int count
    /// (29) - A temp2
    /// (30) - A first
    /// (31) - int
    public static int foo(A one, A two, A three, A four, A five, A six, int b, int c, int d, int e, int f, int g, int h, int i, int j, A temp, int k, int l, int m, int n, int o, int p, int q, int r, int s, int t, int u, int decision, int count, A temp2, A first, int copy)
    {
        if (decision < 100)
        {
            return foo(six, five, four, three, two, one, b, c, u, t, s, r, q, p, o, temp, n, m, l, k, j, i, h, g, f, e, d, 500, 15, temp2, first, copy);
        }

        else
        {
            return bar(count, temp);
        }
    }

    ///
    /// Args
    /// (0) - int decision
    /// (1) - int count
    /// (2) - A one
    /// (3) - A two
    /// (4) - A three
    /// (5) - A four
    /// (6) - A five
    /// (7) - A six
    /// (8) - int a
    /// (9) - int b
    /// (10) - int c 
    /// (11) - int d
    /// (12) - int e
    /// (13) - int f
    /// (14) - int g
    /// (15) - A temp2
    /// (16) - int h
    /// (17) - int i
    /// (18) - int j 
    /// (19) - int k
    /// (20) - int l
    /// (21) - int m
    /// (22) - int n
    /// (23) - int o
    /// (24) - int p
    /// (25) - int q
    /// (26) - int r
    /// (27) - int s
    /// (28) - int t
    /// (29) - A temp
    /// (30) - A first
    /// (31) - A second
    /// (32) - int u
    /// (33) - int v
    /// (34) - int w
    /// (35) - int x
    /// (36) - int y
    /// (37) - int z
    /// (38) - int aa=10
    /// (39) - int ab=11
    /// (40) - int ac=12
    /// (41) - int ad=13
    /// (42) - int ae=14
    /// (43) - int af=15
    /// (44) - int ag=16
    /// (45) - int ah=17
    /// (46) - int ai=18
    /// (47) - int aj=19
    /// (48) - int ak=20
    /// (49) - int al=21
    /// (50) - int am=22
    /// (51) - int an=23
    /// (52) - int ao=24
    /// (53) - int ap=25
    /// (54) - int aq=26
    /// (55) - int ar=27
    /// (56) - int at=29
    /// (57) - int au=30
    public static int foo(int decision, int count, A one, A two, A three, A four, A five, A six, int a, int b, int c, int d, int e, int f, int g, A temp2, int h, int i, int j, int k, int l, int m, int n, int o, int p, int q, int r, int s, int t, A temp, A first, A second, int u, int v, int w, int x, int y, int z, int aa=10, int ab=11, int ac=12, int ad=13, int ae=14, int af=15, int ag=16, int ah=17, int ai=18, int aj=19, int ak=20, int al=21, int am=22, int an=23, int ao=24, int ap=25, int aq=26, int ar=27, int at=29, int au=30)
    {
        if (decision < 100)
        {
            return foo(six, five, four, three, two, first, b, c, u, t, s, r, q, p, o, temp, n, m, l, k, j, i, h, g, f, e, d, 500, 15, temp2, second, decision);
        }

        else
        {
            return bar(count, temp);
        }
    }

    public static void Main()
    {
        A temp = new A();
        temp.a = 50;
        temp.b = 75;
        //temp.c = 100;

        A temp2 = new A();
        temp2.a = 90;
        temp2.b = 75;
        //temp2.c = 10;

        A one = new A();
        A two = new A();
        A three = new A();
        A four = new A();
        A five = new A();
        A six = new A();
        A first = new A();
        A second = new A();

        one.a = 10;
        two.a = 11;
        three.a = 12;
        four.a = 13;
        five.a = 14;
        six.a = 15;

        one.b = 75;
        two.b = 75;
        three.b = 75;
        four.b = 75;
        five.b = 75;
        six.b = 75;

        int ret = foo(50, 19000, one, two, three, four, five, six, 0, 1, 2, 3, 4, 5, 6, temp2, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, temp, first, second, 24, 25, 26, 27, 28, 29);
    } 
}
</pre>

However, the above example will not create the temp due to the stack forced structs having been already copied in morph.
category:correctness
theme:tail-call
skill-level:intermediate
cost:medium

### LINKED ISSUE #12468: [*nix|arm64] [FastTailCall] noway_assert(callerArgNum < comp->info.compArgsCount); in LowerFastTailCall
https://github.com/dotnet/coreclr/blob/master/src/jit/lower.cpp#L1723 assumed the caller has the same number of arguments as the callee to be fastTailCalled. There are many different permutations of caller and callee that will break this assumption while still being decided as a fastTailCall case.

An example on  unix amd64 would be:

```
// 9 arguments
// 8 in registers
// 1 on stack (16 bytes)
caller(float, float, float, float, float, float, float, float, { structOfSize 16 })

// 10 arguments
// 8 in registers
// 2 on stack (16 bytes)
callee(float, float, float, float, float, float, float, float, { structOfSize 8 }, { structOfSize 8} )
```

category:correctness
theme:tail-call
skill-level:intermediate
cost:small

### LINKED ISSUE #12644: [*nix|arm64] canFastTailCall will always report false for non-enregisterable structs
This only applies to the callee which makes this decision flawed. Note that because this bails and reports false it is not a correctness bug. It is just an incorrect fastTailCall decision. Note this decision makes #12468, #11717 and #12479 more difficult to hit.

This happens [here](https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L7021).

category:cq
theme:tail-call
skill-level:intermediate
cost:high

### LINKED ISSUE #20726: [x64 Unix|arm64] Incorrect fastTailCall decision leads to bad codegen
Current decision process requires nCalleeArgs >= nCallerArgs. This can be met, with a caller having a struct that needs to be copied onto the callee's virtual stack frame when the arg is > 8 bytes. If this is the case, only one slot is copied. See example below:

```
// 6 int registers on x64 unix and 16 byte stack
bool callee(long one, long two, long three, long four, long five, long six, long seven, long eight)
{
    // Callee will have incorrect incoming args.
    return ((one == 1) && (two == 2) && (three == 3) && (four == 4) && (five == 5) && (six == 6) && (seven == 7) && (eight == 8));
}

// 6 int registers on x64 unix and 24 byte stack
bool caller(StructSize16 one, long two, long three, long four, long five, long six, long seven, long eight)
{
    // hasStackArgs && nCalleeArgs > nCallerArgs Therefore will fastTailCall
    return callee(1, two, three, four, five, six, seven, eight); 
}
```

category:cq
theme:tail-call
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fast tailcalls have their arguments passed in the incoming argument area
of the caller. This can cause problems when a previous argument might
end up overwriting the stack slot for an incoming argument that is later
used. To resolve this problem, we have logic that detects and introduces
temps in this situation. This logic was originally written for Windows
x64 where it is simple to know what argument is being overwritten, since
every argument always takes up a single slot on the stack. I.e. we know
that outgoing argument 7 can only overwrite incoming argument 7.

On unix x64 and arm64 this assumption does not hold. We previously tried
to workaround this by limiting our fast tailcalls to simple situations
where this assumption held, but this caused many missed fast tailcall
opportunities (for example, when arguments requires two slots or more).

This change removes those limitations. Instead of finding the argument
overwritten using the argument index, it keeps track of which stack
slots are used by each incoming and outgoing argument, allowing us to
more robustly check if an outgoing argument will overwrite an incoming
argument that will be used later.

To do this, we need to set the stack offset during init of args so that
we can use this info to determine whether it is necessary to introduce
temps for fast tailcalls. For arm64 we now define
FEATURE_PUT_STRUCT_ARG_STK to have access to the number of slots in
PUTARG_STK needed for this transformation.

There are also some corner cases we must consider. Since arguments now
consume multiple stack slots we can no longer move them with a single
atomic move instruction. Thus it is possible for us to get into cases
where we need to move an argument that is larger than 8 bytes and where
the move overlaps. This is a problem because codegen cannot handle
partially overlapping struct copies. We see this on unix64 in the
following case (assuming all args are on the stack):
void callee(S16 a, S32 b) { ... }
void caller(S32 a) { callee(default, a); }

Here 'caller' will need to move 'a' 16 bytes ahead in the arg list, and
we thus need a temp because we cannot do this atomically. Fix this by
detecting the partially overlapping case and looking for uses of the arg
from the current PUTARG_STK node's operand (instead of only starting
after).

Fixes #12468 
Fixes #20726
Fixes #12644
Fixes #11717

### CODE REVIEW

**Comment by jakobbotsch** [comment]
@dotnet/jit-contrib

File: src/jit/lower.cpp [hunk 1]
```diff
@@ -2100,6 +2057,80 @@ void Lowering::LowerFastTailCall(GenTreeCall* call)
...
+                callerArgDsc = comp->lvaGetDesc(callerArgLclNum);
+
+                // For promoted locals we have more work to do as its fields could also have been invalidated.
+                if (!callerArgDsc->lvPromoted)
+                    continue;
+
+                unsigned int fieldsFirst = callerArgDsc->lvFieldLclStart;
+                unsigned int fieldsEnd   = fieldsFirst + callerArgDsc->lvFieldCnt;
+                for (unsigned int j = fieldsFirst; j < fieldsEnd; j++)
+                    RehomeArgForFastTailCall(j, insertionPoint, lookForUsesFrom, call);
```
Comment (jakobbotsch) [inline src/jit/lower.cpp]: I am not 100% sure whether this is necessary -- before my change we were introducing temps for the first promoted field so I have left this behavior (in a slightly more robust fashion). I don't know if this should only be done in the dependent promotion case -- is this the only case where the field can live in the same slot as the parent struct?

File: src/jit/lower.cpp [hunk 2]
```diff
@@ -1962,127 +2030,16 @@ void Lowering::LowerFastTailCall(GenTreeCall* call)
...
-
-    // Insert GT_START_NONGC node before the first GT_PUTARG_STK node.
-    // Note that if there are no args to be setup on stack, no need to
-    // insert GT_START_NONGC node.
     GenTree* startNonGCNode = nullptr;
-    if (firstPutArgStk != nullptr)
+    if (!putargs.Empty())
     {
+        bool     unused;
+        GenTree* insertionPoint = BlockRange().GetTreeRange(putargs.Bottom(), &unused).FirstNode();
```
Comment (jakobbotsch) [inline src/jit/lower.cpp]: @BruceForstall Does this look OK?

File: src/jit/lower.cpp [hunk 3]
```diff
@@ -1167,6 +1167,11 @@ GenTree* Lowering::NewPutArg(GenTreeCall* call, GenTree* arg, fgArgTabEntry* inf
                 }
             }
 
+#ifdef DEBUG
+            if (comp->verbose)
+                printf("Creating putarg at slot %d, num slots %d\n", info->slotNum, info->numSlots);
+#endif
+
```
Comment (jakobbotsch) [inline src/jit/lower.cpp]: I will get rid of this.

**Comment by jakobbotsch** [comment]
Copying a comment from #25932:

The only diffs I see on Windows x64/x86 are situations where we now insert the temps a bit earlier:
```diff
 N021 ( 22, 17) [000034] DA-XG-----L-              *  STORE_LCL_VAR ref    V06 tmp1         d:1                                                                    +               [000053] ------------                 START_NONGC void
+N001 (  3,  2) [000054] ------------        t54 =    LCL_VAR   int    V04 arg4
+                                                  /--*  t54    int
+N002 (  4,  3) [000056] DA----------              *  STORE_LCL_VAR int    V07 rat0
 N024 (  1,  1) [000014] ------------        t14 =    CNS_INT   int    0 $40
-N001 (  3,  2) [000053] ------------        t53 =    LCL_VAR   int    V04 arg4
-                                                  /--*  t53    int
-N002 (  4,  3) [000055] DA----------              *  STORE_LCL_VAR int    V07 rat0
-               [000056] ------------                 START_NONGC void
                                                   /--*  t14    int
                [000047] ------------              *  PUTARG_STK [+0x20] void
 N029 (  1,  1) [000035] ------------        t35 =    LCL_VAR   ref    V06 tmp1         u:1 (last use) $143
                                                   /--*  t35    ref
                [000048] ------------        t48 = *  PUTARG_REG ref    REG rdx
 N030 (  1,  1) [000000] ------------         t0 =    LCL_VAR   ref    V00 this         u:1 (last use) $80
                                                   /--*  t0     ref
                [000049] ------------        t49 = *  PUTARG_REG ref    REG rcx
 N031 (  1,  1) [000012] ------------        t12 =    LCL_VAR   ref    V03 arg3         u:1 (last use) $82
                                                   /--*  t12    ref
                [000050] ------------        t50 = *  PUTARG_REG ref    REG r8
 N032 (  3,  2) [000013] ------------        t13 =    LCL_VAR   int    V07 rat0          $100
                                                   /--*  t13    int
                [000051] ------------        t51 = *  PUTARG_REG int    REG r9
 N001 (  3, 10) [000052] ------------        t52 =    CNS_INT(h) long   0x7ffbdcbc07a0 ftn
 N001 (  3, 10) [000052] ------------        t52 =    CNS_INT(h) long   0x7ffbdcbb07a0 ftn
                                                   /--*  t48    ref    arg1 in rdx
                                                   +--*  t49    ref    this in rcx
                                                   +--*  t50    ref    arg2 in r8
                                                   +--*  t51    int    arg3 in r9
                                                   +--*  t52    long   control expr
 N037 ( 49, 33) [000015] --CXG-------              *  CALL      void   System.IO.StreamWriter..ctor $VN.Void
```
This leads to swapped order in some cases:
```diff
        mov      rdx, rax
-       xor      ecx, ecx
-       mov      r9d, ebx

 G_M5466_IG03:
+       mov      r9d, ebx
+       xor      ecx, ecx
        mov      dword ptr [rsp+60H], ecx
        mov      rcx, rdi
        mov      r8, rsi

 G_M5466_IG04:
        add      rsp, 32
        pop      rbx
        pop      rsi
        pop      rdi
        jmp      System.IO.StreamWriter:.ctor(ref,ref,int,bool):this
```
However the temps are just being created before the operand of the first `PUTARG_STK` now, so this should be ok.

File: src/jit/lower.cpp (hunk 3 above)
Comment (jashook) [reply src/jit/lower.cpp]: I think this is useful to keep as jitdump output.

File: src/jit/lower.cpp [hunk 4]
```diff
@@ -1892,6 +1897,71 @@ void Lowering::InsertProfTailCallHook(GenTreeCall* call, GenTree* insertionPoint
     BlockRange().InsertBefore(insertionPoint, profHookNode);
 }
 
+// For fast tail calls it is necessary to set up stack args in the incoming arg space
+// on the stack. When args passed also come from this area we may run into problems
+// because we may end up overwriting the stack slot before using it. For example,
+// for foo(a, b) { return bar(b, a); }, if a and b are on incoming arg space in foo
+// they need to be swapped in this area for the call to bar. This function introduces
+// a new temp for the specified local (assumed to be in the arg space) and updates uses.
+// Note: This function may introduce new temps.
```
Comment (jashook) [inline src/jit/lower.cpp]: Can you document the cases when a temp will be introduced?

File: src/jit/lower.cpp [hunk 5]
```diff
@@ -1892,6 +1897,71 @@ void Lowering::InsertProfTailCallHook(GenTreeCall* call, GenTree* insertionPoint
...
+void Lowering::RehomeArgForFastTailCall(unsigned int lclNum,
```
Comment (jashook) [inline src/jit/lower.cpp]: Nit can you follow the standard header. Example below:

```
//------------------------------------------------------------------------
// NewPutArg: rewrites the tree to put an arg in a register or on the stack.
//
// Arguments:
//    call - the call whose arg is being rewritten.
//    arg  - the arg being rewritten.
//    info - the fgArgTabEntry information for the argument.
//    type - the type of the argument.
//
// Return Value:
//    The new tree that was created to put the arg in the right place
//    or the incoming arg if the arg tree was not rewritten.
//
// Assumptions:
//    call, arg, and info must be non-null.
//
// Notes:
//    For System V systems with native struct passing (i.e. UNIX_AMD64_ABI defined)
//    this method allocates a single GT_PUTARG_REG for 1 eightbyte structs and a GT_FIELD_LIST of two GT_PUTARG_REGs
//    for two eightbyte structs.
//
//    For STK passed structs the method generates GT_PUTARG_STK tree. For System V systems with native struct passing
//    (i.e. UNIX_AMD64_ABI defined) this method also sets the GC pointers count and the pointers
//    layout object, so the codegen of the GT_PUTARG_STK could use this for optimizing copying to the stack by value.
//    (using block copy primitives for non GC pointers and a single TARGET_POINTER_SIZE copy with recording GC info.)
//
GenTree* Lowering::NewPutArg(GenTreeCall* call, GenTree* arg, fgArgTabEntry* info, var_types type)
```

File: src/jit/lower.cpp (hunk 3 above)
Comment (jakobbotsch) [reply src/jit/lower.cpp]: It is basically already there by looking at the trees output -- it prints this information too.

File: src/jit/lower.cpp (hunk 4 above)
Comment (jakobbotsch) [reply src/jit/lower.cpp]: The text above alludes to the reason why, this sentence is mostly there to point out that this function can invalidate `LclVarDesc*`. I will flesh it out a bit more/make it more explicit (and follow the standard header format).

File: src/jit/lower.cpp (hunk 2 above)
Comment (mikedn) [reply src/jit/lower.cpp]: There's `jitstd::vector<T>` but that always allocates memory while `ArrayStack<T>` has an inline array that's sufficient for most purposes, especially in this code. What we really need is `Array<T>` to avoid the `Top`/`Bottom` confusion.

**Comment by jakobbotsch** [comment]
@jashook helped me collect some perf data for Windows. On average it looks like it is within noise, but in the worst case (last number) it seems like this is a significant regression:
```diff
-     Lowering nodeinfo                1.00    30291.02   14373.603       2.65%     447.200
+     Lowering nodeinfo                1.00    33966.28   16095.635       2.46%     558.785
```

I imagine this case has fast tailcalls with extremely many args, though I do not know how to check which function hits the max (anyone?).
This is still a fraction of the worst-case times of other phases so I don't know if I should try optimizing it for this case or leave the code simple. An alternative solution could also be to bail on fast tailcalls for functions with, say, > 15 args. Thoughts?

**Comment by mikedn** [comment]
This perf data is the time reported in the time log file, right? On what scenario?

**Comment by jakobbotsch** [comment]
Yes, this is from `COMPlus_JitTimeLogFile` with SuperPMI over tests I believe.

**Comment by jakobbotsch** [comment]
I ran another run with `COMPlus_JitTimeLogCsv` and `COMPlus_JitTimeLogFile` enabled and this time the max for lowering was 455 ms, so basically the same as before this change. I also looked at the CSV file and the functions taking a long time for lowering do not do any tailcalls, so the max does not seem to be affected significantly by this change. In other words, it seems this change is within noise for Windows.

**Comment by mikedn** [comment]
PIN with "crossgen corelib" shows a 0.02% regression: https://1drv.ms/x/s!Av4baJYSo5pjgs48hU9S2fHrICK-PQ?e=Nc8Jm7
That's borderline noise.
Of course, corelib may not be representative for tailcalls. But JIT tests aren't likely to be either.

**Comment by jakobbotsch** [comment]
Awesome, thank you for collecting that!

File: src/jit/codegenlinear.cpp [hunk 6]
```diff
@@ -1647,8 +1647,10 @@ void CodeGen::genPutArgStkFieldList(GenTreePutArgStk* putArgStk, unsigned outArg
         unsigned thisFieldOffset = argOffset + fieldListPtr->gtFieldOffset;
         getEmitter()->emitIns_S_R(ins_Store(type), attr, reg, outArgVarNum, thisFieldOffset);
 
-        // We can't write beyond the arg area
-        assert((thisFieldOffset + EA_SIZE_IN_BYTES(attr)) <= compiler->lvaLclSize(outArgVarNum));
+        // We can't write beyond the arg area unless this is a tail call, in which case we use
+        // the first stack arg as the base of the incoming arg area.
+        assert(putArgStk->gtCall->IsFastTailCall() ||
+               (thisFieldOffset + EA_SIZE_IN_BYTES(attr)) <= compiler->lvaLclSize(outArgVarNum));
```
Comment (briansull) [inline src/jit/codegenlinear.cpp]: We should  add a check here to insure that we aren't writing beyond our limit when we have a fast tail call.

File: src/jit/morph.cpp [hunk 7]
```diff
@@ -7079,54 +7081,19 @@ bool Compiler::fgCanFastTailCall(GenTreeCall* callee)
...
-
-#if !defined(FEATURE_ARG_SPLIT)
-        if (argStackSize > 0)
-        {
-            assert(argFloatRegCount == 0 && argIntRegCount == 0);
-        }
-#endif // !defined(FEATURE_ARG_SPLIT)
-
-        unsigned countRegistersUsedForArg = argIntRegCount + argFloatRegCount;
+        unsigned argStackSize = arg->stackSize();
```
Comment (briansull) [inline src/jit/morph.cpp]: Seem unnecessary to have a single def/use local `argStackSize` here.

**Comment by jakobbotsch** [comment]
@jashook I have fixed conflicts, would you mind taking another look?
