### PR TITLE
Skip commas when trying to remove some narrowing casts

### LINKED ISSUE #15731: [JIT] Unnecessary movzx instruction when writing a value to a Span of byte
When writing to a `Span<byte>`, the JIT will emit an unnecessary `movzx` instruction if it has also emitted a bounds check for the memory access. Writing code which causes the JIT to elide the bounds check will also remove the extra `movzx` instruction.

The samples below show amd64 codegen.

**Sample code with JIT-included automatic bounds check:**

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Foo(uint value, Span<byte> buffer)
{
    int index = 0;
    value -= 10;
    buffer[index] = (byte)value;
}
```
```asm
00007FF9BCAA2A10  sub         rsp,28h  
00007FF9BCAA2A14  add         ecx,0FFFFFFF6h  
00007FF9BCAA2A17  cmp         dword ptr [rdx+8],0  
00007FF9BCAA2A1B  jbe         00007FF9BCAA2A2A  
00007FF9BCAA2A1D  mov         rax,qword ptr [rdx]  
00007FF9BCAA2A20  movzx       edx,cl  
00007FF9BCAA2A23  mov         byte ptr [rax],dl  
00007FF9BCAA2A25  add         rsp,28h  
00007FF9BCAA2A29  ret  
00007FF9BCAA2A2A  call        00007FFA1C731C50  
00007FF9BCAA2A2F  int         3  
```

Note in particular that instead of writing the contents of the _cl_ register directly, the value is bounced through the _edx / dl_ register before being written.

**Sample code with manual branch which elides JIT's auto bounds check:**

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Bar(uint value, Span<byte> buffer)
{
    int index = 0;
    value -= 10;
    if ((uint)index >= (uint)buffer.Length) { goto OutOfRange; }
    buffer[index] = (byte)value;
    return;

    OutOfRange:
    ref byte unused = ref buffer[index]; // will trigger exception
}
```
```asm
00007FF9BCA92A50  sub         rsp,28h  
00007FF9BCA92A54  mov         rax,qword ptr [rdx]  
00007FF9BCA92A57  mov         edx,dword ptr [rdx+8]  
00007FF9BCA92A5A  add         ecx,0FFFFFFF6h  
00007FF9BCA92A5D  test        edx,edx  
00007FF9BCA92A5F  jbe         00007FF9BCA92A68  
00007FF9BCA92A61  mov         byte ptr [rax],cl  
00007FF9BCA92A63  add         rsp,28h  
00007FF9BCA92A67  ret  
00007FF9BCA92A68  cmp         edx,0  
00007FF9BCA92A6B  jbe         00007FF9BCA92A72  
00007FF9BCA92A6D  add         rsp,28h  
00007FF9BCA92A71  ret  
00007FF9BCA92A72  call        00007FFA1C731C50  
00007FF9BCA92A77  int         3
```

Note the direct write from the _cl_ register to the address in _rax_. (The reason I wrote the _OutOfRange_ label like I did is that it causes the JIT to emit `call 00007FFA1C731C50` in the failure case. Otherwise I'd have to manually throw and it causes the codegen to look wonky.)

### PR DESCRIPTION
**Pull request by mikedn**
In certain cases (assignment to a byte array/span element) the lhs of the assignment happens to be a comma node that wraps the indir.

Fixes #15731

### CODE REVIEW

**Comment by mikedn** [comment]
jit-diff summary:
```
Total bytes of diff: -2642 (-0.01% of base)
    diff is an improvement.
Total byte diff includes 0 bytes from reconciling methods
        Base had    0 unique methods,        0 unique bytes
        Diff had    0 unique methods,        0 unique bytes
Top file improvements by size (bytes):
        -376 : System.Private.CoreLib.dasm (-0.01% of base)
        -356 : Microsoft.CodeAnalysis.dasm (-0.05% of base)
        -311 : System.Private.DataContractSerialization.dasm (-0.04% of base)
        -293 : System.Memory.dasm (-0.33% of base)
        -144 : System.Net.Primitives.dasm (-0.25% of base)
34 total files with size differences (34 improved, 0 regressed), 96 unchanged.
Top method improvements by size (bytes):
         -64 : System.Private.CoreLib.dasm - Decimal:GetBytes(struct,ref)
         -48 : System.Data.Common.dasm - SqlDecimal:get_BinData():ref:this
         -47 : System.Security.Cryptography.Algorithms.dasm - CryptoConfig:EncodeSingleOidNum(int,ref,byref)
         -43 : System.Private.DataContractSerialization.dasm - XmlBinaryNodeWriter:WriteTextNodeWithLength(int,int):this
         -40 : System.Private.DataContractSerialization.dasm - XmlBinaryNodeWriter:WriteTextNodeWithInt64(int,long):this
305 total methods with size differences (305 improved, 0 regressed), 129813 unchanged.
```

**Comment by mikedn** [comment]
Alpine.3.6 x64 Debug build timed out. https://ci3.dot.net/job/dotnet_coreclr/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/653/

@dotnet-bot test Alpine.3.6 x64 Debug Build

File: src/jit/morph.cpp [hunk 1]
```diff
@@ -12501,14 +12502,16 @@ GenTreePtr Compiler::fgMorphSmpOp(GenTreePtr tree, MorphAddrContext* mac)
                 lclVarTree->gtFlags |= GTF_VAR_DEF;
             }
 
-            if (op1->gtEffectiveVal()->OperIsConst())
+            effectiveOp1 = op1->gtEffectiveVal();
+
+            if (effectiveOp1->OperIsConst())
```
Comment (mikedn) [inline src/jit/morph.cpp]: In theory `effectiveOp1` should be updated inside this `if`. In practice what this `if` does is beyond weird. It's either some legacy thing or it's completely bogus. Either way, I've chosen not to update `effectiveOp1` so that the cast doesn't get removed in some weird scenario that can't be reproduced and tested.

File: src/jit/morph.cpp [hunk 2]
```diff
@@ -12518,12 +12521,12 @@ GenTreePtr Compiler::fgMorphSmpOp(GenTreePtr tree, MorphAddrContext* mac)
...
                     // then we can discard the cast.
 
-                    if (varTypeIsSmall(castType) && (genTypeSize(castType) >= genTypeSize(op1->TypeGet())))
+                    if (varTypeIsSmall(castType) && (genTypeSize(castType) >= genTypeSize(effectiveOp1->TypeGet())))
                     {
                         tree->gtOp.gtOp2 = op2 = op2->gtCast.CastOp();
                     }
                 }
-                else if (op2->OperIsCompare() && varTypeIsByte(op1->TypeGet()))
+                else if (op2->OperIsCompare() && varTypeIsByte(effectiveOp1->TypeGet()))
```
Comment (mikedn) [inline src/jit/morph.cpp]: This is another weird transform that's specific to x86/x64 and should be done in lowering. At least this case can be reproduced and verified that it works correctly.

**Comment by CarolEidt** [comment]
@mikedn @GrabYourPitchforks - it's unfortunate that this PR has been languishing. On the surface it seems quite reasonable, but I would propose deferring to 2.2.

**Comment by GrabYourPitchforks** [comment]
@CarolEidt I think the problem is that we don't have a reviewer, and I'm not sure who would really be on point for it. Or was your comment that "it seems quite reasonable" tacit approval? :)

**Comment by CarolEidt** [comment]
> was your comment that "it seems quite reasonable" tacit approval? :)

No, sorry - I plan to review this and/or ask other JIT devs to review it. I hope to get to that soon.
