### PR TITLE
Fix for bug 12398: Lowering is inconsistent in checking safety of RegOptional

### LINKED ISSUE #12398: [RyuJIT] Lowering is inconsistent in checking safety of RegOptional
In a number of places, `Lowering` checks `IsSafeToContainMem()` before setting an operand as contained, then if it fails to make it contained it marks it as `regOptional`. However, if it is unsafe for the node to be contained, it is presumably also unsafe to mark it `regOptional`, as it will be loaded at the point of use in the event that it doesn't get a register.

category:correctness
theme:lower
skill-level:expert
cost:small

### PR DESCRIPTION
**Pull request by erozenfeld**
This fixes an inconsistency in lowering where it fails to make an
operand contained because IsSafeToContainMem() returns false yet
it marks it regOptional, which may cause a problem if the operand
will be loaded at the point of use.

There are 6 places that are affected, I added repro cases for 3 of them.
I wasn't able to construct repros for the 3 places that deal with
floating point operands but decided to fix those places anyway.

Fixes #12398.

### CODE REVIEW

**Comment by erozenfeld** [comment]
x64
jit-diff diff --pmi --frameworks --tests

```
Total bytes of diff: 45 (0.00% of base)
    diff is a regression.
Top file regressions by size (bytes):
          10 : JIT\Performance\CodeQuality\Bytemark\Bytemark\Bytemark.dasm (0.01% of base)
           5 : System.Runtime.Numerics.dasm (0.01% of base)
           5 : JIT\Directed\perffix\primitivevt\mixed1_cs_do\mixed1_cs_do.dasm (0.01% of base)
           5 : JIT\Directed\perffix\primitivevt\mixed1_cs_ro\mixed1_cs_ro.dasm (0.01% of base)
           5 : JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.dasm (0.00% of base)
8 total files with size differences (0 improved, 8 regressed), 8695 unchanged.
Top method regressions by size (bytes):
          10 : JIT\Performance\CodeQuality\Bytemark\Bytemark\Bytemark.dasm - Fourier:thefunction(double,double,int):double
           5 : System.Runtime.Numerics.dasm - Complex:Pow(struct,struct):struct
           5 : JIT\Directed\perffix\primitivevt\mixed1_cs_do\mixed1_cs_do.dasm - testout1:Func_0_1_3():int
           5 : JIT\Directed\perffix\primitivevt\mixed1_cs_ro\mixed1_cs_ro.dasm - testout1:Func_0_1_3():int
           5 : JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.dasm - testout1:Func_0_5_2_3_6():float
8 total methods with size differences (0 improved, 8 regressed), 495319 unchanged.
1 files had text diffs but not size diffs.
JIT\Performance\CodeQuality\Benchstones\BenchF\Whetsto\Whetsto\Whetsto.dasm had 20 diffs
```

**Comment by erozenfeld** [comment]
Here is an example regression from FFT:Bench:

Before
```
       call     Math:Exp(double):double
       vmovsd   qword ptr [rsp+28H], xmm0
       vmovaps  xmm0, xmm6
       call     Math:Sin(double):double
       vmulsd   xmm0, qword ptr [rsp+28H]
```

After:

```
       call     Math:Exp(double):double
       vmovsd   qword ptr [rsp+28H], xmm0
       vmovaps  xmm0, xmm6
       call     Math:Sin(double):double
       vmovsd   xmm1, qword ptr [rsp+28H]
       vmulsd   xmm0, xmm1
```

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib @CarolEidt PTAL

**Comment by erozenfeld** [comment]
@dotnet-bot help

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

File: src/jit/lower.h [hunk 1]
```diff
@@ -246,15 +246,17 @@ class Lowering : public Phase
     // operands.
     //
     // Arguments:
-    //     tree  -  Gentree of a binary operation.
+    //     tree  -             Gentree of a binary operation.
+    //     isSafeToMarkOp1     True if it's safe to mark op1 as register optional
```
Comment (CarolEidt) [inline src/jit/lower.h]: Here (or in a Notes section below) you should mention that it is expected that the caller has already determined this by calling `IsSafeToContainMem`

File: src/jit/lowerxarch.cpp [hunk 2]
```diff
@@ -2113,10 +2145,44 @@ void Lowering::ContainCheckBinary(GenTreeOp* node)
...
+// Arguments:
+//    parentNode        - Parent node of the operand
+//    childNode         - Child node to check for safe containment
+//    isSafeToContainOp - Out-parameter that is set to false if we determined that the operand
+//                        is not safe to contain, true otherwise.
+//
+// Return Value:
+//    Returns true if the operand can be safely contained.
+//
+bool Lowering::IsSafelyContainableMemoryOp(GenTree* parentNode, GenTree* childNode, bool* isSafeToContainOp)
```
Comment (CarolEidt) [inline src/jit/lowerxarch.cpp]: I think this method is confusing. First, the name is too similar to `IsSafeToContainMem`. Second, the difference between the out parameter and the result is only for the case where `childNode` is not a memory op - I think that's inappropriate for a method specifically focused on memory. I think it is better, and articulates the cases more clearly, for the caller to do that checking, and then to call `IsSafeToContainMem` directly, even if it means there are more conditions for the caller to check.

Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: I did it the way you are requesting originally and didn't like the code in the callers. I'll re-do and push that version to show what I got.

Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: @CarolEidt I pushed the changes. Do you like this version better?

File: src/jit/lower.h (hunk 1 above)
Comment (erozenfeld) [reply src/jit/lower.h]: Done

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

File: src/jit/lowerxarch.cpp (hunk 2 above)
Comment (CarolEidt) [reply src/jit/lowerxarch.cpp]: Yes - I think it's much easier to understand this way. Thanks!

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by jakobbotsch** [comment]
I have a couple of examples that look related and still repro with this fix, please let me know if I should open issues for them:
```csharp
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    static int s_32;
    static int s_46 = 1;
    public static void Main()
    {
        s_32 = 0;
        M5();
        System.Console.WriteLine(s_46);
    }

    static void M5()
    {
        s_46 *= (System.Threading.Interlocked.Exchange(ref s_46, 0) | s_32--);
    }
}
```

```csharp
// Debug: Outputs 0
// Release: Outputs 1
public class Program
{
    static int s_3;
    static int s_11;
    public static void Main()
    {
        M9(s_3, System.Threading.Interlocked.Exchange(ref s_3, 1), s_11++);
    }

    static void M9(int arg2, int arg3, int arg4)
    {
        System.Console.WriteLine(arg2);
    }
}
```

File: src/jit/lowerxarch.cpp [hunk 3]
```diff
@@ -1639,21 +1665,42 @@ void Lowering::ContainCheckMul(GenTreeOp* node)
...
     {
-        if ((memOp->TypeGet() != node->TypeGet()) || !IsSafeToContainMem(node, memOp))
+        if ((memOp->TypeGet() != node->TypeGet()))
         {
             memOp = nullptr;
         }
+        else if (!IsSafeToContainMem(node, memOp))
+        {
+            memOp = nullptr;
+            if (memOp == op1)
```
Comment (jakobbotsch) [inline src/jit/lowerxarch.cpp]: This check seems strange considering the line above it.

File: src/jit/lowerxarch.cpp [hunk 4]
```diff
@@ -1669,18 +1716,29 @@ void Lowering::ContainCheckMul(GenTreeOp* node)
             // Has a contained immediate operand.
             // Only 'other' operand can be marked as reg optional.
             assert(other != nullptr);
-            other->SetRegOptional();
+
+            bool isSafeToContainOther = (other == op1) ? isSafeToContainOp1 : isSafeToContainOp2;
+
+            if (isSafeToContainOther && IsSafeToContainMem(node, other))
+            {
+                other->SetRegOptional();
```
Comment (jakobbotsch) [inline src/jit/lowerxarch.cpp]: This code is a little strange. See the following example which still wrongly marks the first operand as reg-optional, even though there is a type size mismatch:
```csharp
// Debug: Outputs 0
// Release: Outputs 6528000
struct S0
{
    public sbyte F1;
    public sbyte F2;
}

public class Program
{
    public static void Main()
    {
        S0 vr2 = new S0();
        vr2.F2--;
        int vr3 = System.Threading.Volatile.Read(ref vr2.F1) * 100;
        System.Console.WriteLine(vr3);
    }
}
```

the generated code is:
```asm
G_M5093_IG01:
       4883EC28             sub      rsp, 40
       33C0                 xor      rax, rax
       4889442420           mov      qword ptr [rsp+20H], rax

G_M5093_IG02:
       C644242000           mov      byte  ptr [rsp+20H], 0
       C644242100           mov      byte  ptr [rsp+21H], 0
       488D4C2421           lea      rcx, bword ptr [rsp+21H]
       FE09                 dec      byte  ptr [rcx]
      ; memory operand on this imul is marked reg-optional, even though the node is a byte node
       6B4C242064           imul     ecx, dword ptr [rsp+20H], 100
       E822FCFFFF           call     System.Console:WriteLine(int)
```
A few lines above there is a check for whether the type of the operand matches the node, and `memOp` is set to null because it doesn't. But then we get here and since there is a contained immediate, we redo the containment check without the type check and set it to reg-optional.

I realize this is probably not exactly #12398, but since you are making changes here anyway it might be nice to fix it too.

File: src/jit/lowerxarch.cpp (hunk 3 above)
Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: Good catch, thanks. I pushed a fix for this.

**Comment by erozenfeld** [comment]
@jakobbotsch Thanks for the new examples. I'll investigate them when I'm back in the office on Wednesday.

File: src/jit/lowerxarch.cpp (hunk 4 above)
Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: @jakobbotsch I pushed a change that fixes this case. @CarolEidt PTAL

**Comment by erozenfeld** [comment]
@jakobbotsch The other two examples are instances of another bug. The importer needs to spill stack side effects when importing interlocked binary operation. In the first example, the first multiplication argument needed to be spilled; in the second example, the first argument to M9 needed to be spilled. I will open a separate issue for this bug.

**Comment by erozenfeld** [comment]
Yes, it's the same as #19583 although the fix proposed there won't be sufficient to fix this. I'll comment in that issue.

File: src/jit/lowerxarch.cpp [hunk 5]
```diff
@@ -1553,25 +1553,51 @@ void Lowering::ContainCheckMul(GenTreeOp* node)
...
+                }
+            }
         }
-        else
+
+        if (!op1->isContained() && !op2->isContained())
         {
             // If there are no containable operands, we can make an operand reg optional.
-            SetRegOptionalForBinOp(node);
+            isSafeToContainOp1 = isSafeToContainOp1 && IsSafeToContainMem(node, op1);
```
[the remark this answers is not in the document]
Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: No, there are no cases where `IsSafeToContainMem` is called multiple times. Whenever `IsSafeToContainMem` returns true we make an operand contained; this line only executes if neither operand is contained.

**Comment by erozenfeld** [comment]
@dotnet-bot test this please

File: src/jit/lowerxarch.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (CarolEidt) [reply src/jit/lowerxarch.cpp]: I see, thanks. Could you add a comment to that effect?

[the remark this answers is not in the document]
Comment (erozenfeld) [reply src/jit/lowerxarch.cpp]: I added a comment to each method with this pattern.

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT x64 Checked Build and Test
@dotnet-bot test Windows_NT x86 Checked Build and Test

**Comment by erozenfeld** [comment]
@dotnet-bot test Windows_NT arm Cross Checked Innerloop Build and Test
@dotnet-bot test Windows_NT arm64 Cross Checked Innerloop Build and Test

**Comment by erozenfeld** [comment]
Windows_NT arm Cross Checked Innerloop Build and Test and Windows_NT arm64 Cross Checked Innerloop Build and Test are known failures (#19853)
