### PR TITLE
Fix stack walking and reporting of default interface methods

### LINKED ISSUE #16376: GCStress failure: Loader\classloader\DefaultInterfaceMethods\sharedgenerics\sharedgenerics_r
x86 checked `GCStress=4` failure in Loader\classloader\DefaultInterfaceMethods\sharedgenerics\sharedgenerics_r:

```
e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Loader\classloader\DefaultInterfaceMethods\sharedgenerics\sharedgenerics_r>sharedgenerics_r.cmd -coreroot e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
BEGIN EXECUTION
 "e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" sharedgenerics_r.exe
Calling IFoo<string>.Foo on FooBar<string, object> - expecting default method IFoo<string>.Foo

Assert failure(PID 28984 [0x00007138], Thread: 27232 [0x6a60]): Precondition failure: FAILED: !IsNull()

CORECLR! CHECK::Trigger + 0x310 (0x0f8a944b)
CORECLR! RelativePointer<Module *>::GetValue + 0x90 (0x0f912589)
CORECLR! GcStackCrawlCallBack + 0x3AD (0x0fd62dbd)
CORECLR! Thread::MakeStackwalkerCallback + 0x45 (0x0f9f70f0)
CORECLR! Thread::StackWalkFramesEx + 0x16E (0x0f9f8789)
CORECLR! Thread::StackWalkFrames + 0x16A (0x0f9f8598)
CORECLR! ScanStackRoots + 0x18D (0x0fe692bb)
CORECLR! GCToEEInterface::GcScanRoots + 0x118 (0x0fe68856)
CORECLR! WKS::gc_heap::mark_phase + 0x1C7 (0x0fe32fd1)
CORECLR! WKS::gc_heap::gc1 + 0x1A9 (0x0fe2dab8)
    File: e:\gh\coreclr3\src\inc\fixuppointer.h Line: 67
    Image: e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/67/testReport/junit/Loader_classloader/_DefaultInterfaceMethods_sharedgenerics_sharedgenerics_r_sharedgenerics_r_/_DefaultInterfaceMethods_sharedgenerics_sharedgenerics_r_sharedgenerics_r_cmd/

### LINKED ISSUE #16898: [Arm64/Ubuntu] genericcontext failing gcStress!=0
Test added in #16690 is failing in all gcStress modes

@A-And FYI

### LINKED ISSUE #21044: Regressions\coreclr\16355\boring fails with GCStress=0x8
Repro steps:
build CoreCLR x64 checked
set complus_gcstress=0x8
set core_root=F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Regressions\coreclr\16355\boring\boring.cmd 

output:
```
F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Regressions\coreclr\16355\boring>boring.cmd
BEGIN EXECUTION
 "F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" boring.exe

Assert failure(PID 16228 [0x00003f64], Thread: 37540 [0x92a4]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! GcStackCrawlCallBack + 0x5C2 (0x00007ffd`f387b3d2)
CORECLR! Thread::MakeStackwalkerCallback + 0x52 (0x00007ffd`f333ca32)
CORECLR! Thread::StackWalkFramesEx + 0x180 (0x00007ffd`f333e5bc)
CORECLR! Thread::StackWalkFrames + 0x184 (0x00007ffd`f333e39c)
CORECLR! ScanStackRoots + 0x28D (0x00007ffd`f3a0490d)
CORECLR! GCToEEInterface::GcScanRoots + 0x1DA (0x00007ffd`f3a035f6)
CORECLR! WKS::gc_heap::mark_phase + 0x228 (0x00007ffd`f39b4608)
CORECLR! WKS::gc_heap::gc1 + 0x1EC (0x00007ffd`f39ad144)
CORECLR! WKS::gc_heap::garbage_collect + 0x6DD (0x00007ffd`f39acf05)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x2C0 (0x00007ffd`f39998f4)
CORECLR! WKS::GCHeap::GarbageCollect + 0x106 (0x00007ffd`f39995e6)
CORECLR! WKS::GCHeap::StressHeap + 0x615 (0x00007ffd`f399c265)
CORECLR! VSD_ResolveWorker + 0x7DB (0x00007ffd`f351103b)
CORECLR! ResolveWorkerAsmStub + 0x6D (0x00007ffd`f382938d)
<no module>! <no symbol> + 0x0 (0x00007ffd`93f91fc3)
<no module>! <no symbol> + 0x0 (0x000002c0`b0d9ef80)
<no module>! <no symbol> + 0x0 (0x000002c0`aed6cb50)
<no module>! <no symbol> + 0x0 (0x00000000`0000018d)
<no module>! <no symbol> + 0x0 (0x00000000`000001cd)
-----
.AV on tid=0x92a4 (37540), cxr=000000DED9D7B1C0, exr=000000DED9D7B6B0
FAILED: false

CORECLR! CHECK::Trigger + 0x2C4 (0x00007ffd`f313d174)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x379 (0x00007ffd`f32091fd)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x72 (0x00007ffd`f3208c56)
CORECLR! CLRVectoredExceptionHandler + 0x1D9 (0x00007ffd`f3208bc9)
CORECLR! CLRVectoredExceptionHandlerShim + 0x18A (0x00007ffd`f320944a)
NTDLL! RtlInitializeCriticalSectionAndSpinCount + 0x1C6 (0x00007ffe`46a96896)
NTDLL! RtlWalkFrameChain + 0x1119 (0x00007ffe`46a34709)
NTDLL! KiUserExceptionDispatcher + 0x2E (0x00007ffe`46ad231e)
CORECLR! GcStackCrawlCallBack + 0x5C2 (0x00007ffd`f387b3d2)
CORECLR! Thread::MakeStackwalkerCallback + 0x52 (0x00007ffd`f333ca32)
    File: f:\git\coreclr\src\vm\excep.cpp Line: 7830
    Image: F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Default interface methods in their unresolved state don't have a generic context. The generic context is only added once the method is resolved to its implementation.

Fixes #16376. Fixes #16898. Fixes #21044.

### CODE REVIEW

**Comment by janvorli** [comment]
> src/vm/frames.h:2208:5: error: 'VPtrSize' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]

This happens when you try to use override in a class where it was not used before. Basically, once you use override for a single virtual method, you need to use it for all. So here, it would be better to stick with just marking the method as virtual and not using the override.

File: src/vm/frames.cpp [hunk 1]
```diff
@@ -1238,7 +1238,16 @@ void TransitionFrame::PromoteCallerStack(promote_func* fn, ScanContext* sc)
     //If not "vararg" calling convention, assume "default" calling convention
     if (!MetaSig::IsVarArg(pFunction->GetModule(), callSignature))
     {
-        MetaSig msig(pFunction);
+        SigTypeContext typeContext(pFunction);
+        PCCOR_SIGNATURE pSig;
+        DWORD cbSigSize;
+        pFunction->GetSig(&pSig, &cbSigSize);
+
+        MetaSig msig(pSig, cbSigSize, pFunction->GetModule(), &typeContext);
```
Comment (jkotas) [inline src/vm/frames.cpp]: Do we know a matching fix for `PromoteCallerStackUsingGCRefMap` - adjust the GCRef map that gets saved into R2R image at crossgen time?

You should be able to verify it by compiling the affected tests using crossgen before running them.

File: src/vm/frames.h [hunk 2]
```diff
@@ -2267,6 +2276,23 @@ class StubDispatchFrame : public FramedMethodFrame
...
+        // Shared default interface methods (i.e. virtual interface methods with an implementation) require
+        // an instantiation argument. But if we're in the stub dispatch frame, we haven't actually resolved
+        // the method yet (we could end up in class's override of this method, for example).
+        //
+        // So we need to pretent that unresolved default interface methods are like any other interface
+        // methods and don't have an instantiation argument.
+        //
+        // See code:CEEInfo::getMethodSigInternal
+        //
+        return pMD->GetMethodTable()->IsInterface();
```
Comment (jkotas) [inline src/vm/frames.h]: Are there any cases where we actually get into `StubDispatchFrame` with hidden generic arg? 

Maybe this can just return `TRUE` unconditionally.

Comment (MichalStrehovsky) [reply src/vm/frames.h]: Normal virtual method calls on generic types maybe? Or they don't go through here?

File: src/vm/frames.cpp (hunk 1 above)
Comment (MichalStrehovsky) [reply src/vm/frames.cpp]: Yeah, it didn't work. Thanks for spotting! I pushed out a fix.

File: src/vm/frames.h (hunk 2 above)
Comment (jkotas) [reply src/vm/frames.h]: Normal virtual method calls do not have hidden generic arg. The context is in `this` pointer.

Generic virtual method calls do not go through here.

Comment (jkotas) [reply src/vm/frames.h]: I will leave it up to you whether to do this simplification.

**Comment by jkotas** [comment]
`src\vm\frames.h(2281): warning C4189: 'pMD': local variable is initialized but not referenced`

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test Windows_NT x64 Checked CoreFX Tests
@dotnet-bot test Windows_NT x64 Formatting
