### PR TITLE
Initialize variant return value.

### LINKED ISSUE #26139: Test failed: Interop\PInvoke\Delegate\DelegateTest\DelegateTest.cmd
**Job:**
https://helix.dot.net/api/2019-06-17/jobs/e15a2731-c82b-422d-88b0-cddf09a861cd/workitems/Interop/console

**Failed tests:**
Interop\PInvoke\Delegate\DelegateTest\DelegateTest.cmd

**Log:**
```
Interop\PInvoke\Delegate\DelegateTest\DelegateTest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Work\16efc325-4829-438b-85c0-fe7192d1c2a1\Exec\Interop\PInvoke\Reports\Interop.PInvoke\Delegate\DelegateTest\DelegateTest.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Payload\corerun.exe" DelegateTest.exe 
      Expected: 100
      Actual: -1073740940
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Payload
      > C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Work\16efc325-4829-438b-85c0-fe7192d1c2a1\Exec\Interop\PInvoke\Delegate\DelegateTest\DelegateTest.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace.5\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.PInvoke\Interop.PInvoke.XUnitWrapper.cs(6154,0): at Interop_PInvoke._Delegate_DelegateTest_DelegateTest_._Delegate_DelegateTest_DelegateTest_cmd()
      Output:
        
        Return code:      1
        Raw output file:      C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Work\16efc325-4829-438b-85c0-fe7192d1c2a1\Exec\Interop\PInvoke\Reports\Interop.PInvoke\Delegate\DelegateTest\DelegateTest.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\dotnetbuild\work\e15a2731-c82b-422d-88b0-cddf09a861cd\Payload\corerun.exe" DelegateTest.exe 
        Expected: 100
        Actual: -1073740940
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #26139

### CODE REVIEW

File: tests/src/Interop/PInvoke/Delegate/DelegateAsInterfaceTestNative.cpp [hunk 1]
```diff
@@ -8,6 +8,7 @@ namespace
 {
     HRESULT InvokeDelegate(IDispatch* dele, VARIANT* pResult)
     {
+        VariantInit(pResult);
```
Comment (AaronRobinsonMSFT) [inline tests/src/Interop/PInvoke/Delegate/DelegateAsInterfaceTestNative.cpp]: Can you move this closer to the `dele->Invoke()` call? It is weird to initialize an out prior to anything in a function utilizing COM semantics.
